const {chapter}=require('./author.cjs');
module.exports=chapter('',String.raw`
CF|CF_t=Cashflow zum Zeitpunkt t, in der Währung des Rechenmodells. Zuflüsse sind positiv, Abflüsse negativ; zusätzliche Indizes bezeichnen ausdrücklich das Szenario oder den Zahlungstermin.
PV|PV,\ PV_t=Barwert, also Wert einer Zahlung am Bewertungsstichtag. PV_t kann den heutigen Barwert der Zahlung zum Termin t bezeichnen; ein Zusatz due bedeutet vorschüssige, infinity eine unendliche Zahlungsreihe.
FV|FV_n=Endwert beziehungsweise zukünftiger Wert am genannten Termin, in derselben Währung wie der Anfangsbetrag.
DF|DF_t,\ DF(0,t)=Abzinsungsfaktor für eine Zahlung am Termin t. Er ist dimensionslos; Cashflow mal Abzinsungsfaktor ergibt den Barwert. Zwei Zeitargumente kennzeichnen Bewertungs- und Zahlungstermin.
NPV=Net Present Value, Kapitalwert: Summe aller auf den Bewertungsstichtag abgezinsten Zahlungen einschließlich der Anfangsinvestition, in Geldeinheiten.
IRR=Internal Rate of Return, interner Zinsfuß: Diskontsatz, bei dem der Kapitalwert null ist; pro Zahlungsperiode als Dezimalzahl.
EV=Enterprise Value, Wert des operativen Unternehmens für seine Kapitalgeber, in Geldeinheiten.
ND=Nettoverschuldung: Finanzschulden abzüglich der in der Definition berücksichtigten Zahlungsmittel.
FCFF=Free Cashflow to the Firm: verfügbarer Zahlungsüberschuss für alle Kapitalgeber nach operativen Kosten, Steuern und notwendigen Investitionen.
FCFE=Free Cashflow to Equity: verfügbarer Zahlungsüberschuss für Eigenkapitalgeber nach Fremdfinanzierungszahlungen und unter Berücksichtigung neuer Nettoschulden.
WACC=Gewichtete durchschnittliche Kapitalkosten pro Periode, als Dezimalzahl; passen zu Cashflows für alle Kapitalgeber.
CFO=Cashflow aus der laufenden Geschäftstätigkeit in der betrachteten Periode.
CFI=Cashflow aus Investitionstätigkeit; etwa Auszahlung für Anlagen als negativer Betrag.
CFF=Cashflow aus Finanzierungstätigkeit; etwa Kreditaufnahme als positiver Betrag oder Ausschüttung als negativer Betrag.
NI=Net Income, Periodengewinn nach den in der jeweiligen Rechnung berücksichtigten Aufwendungen und Steuern.
DA=Depreciation and Amortization, planmäßige Abschreibungen der Periode. Als Aufwand meist positiv angegeben und in der indirekten Cashflow-Rechnung wieder hinzuaddiert.
NC=Weitere nicht zahlungswirksame Aufwendungen abzüglich entsprechender Erträge, mit dem für die Cashflow-Überleitung passenden Vorzeichen.
AR=Accounts Receivable, Forderungen aus Lieferungen und Leistungen; eine Zunahme bindet bei sonst gleichen Größen Liquidität.
AP=Accounts Payable, Verbindlichkeiten aus Lieferungen und Leistungen; eine Zunahme stellt bei sonst gleichen Größen Liquidität bereit.
INV=Vorratsbestand; ein Balken bezeichnet den durchschnittlichen Bestand der Periode.
DIV=Dividenden beziehungsweise Ausschüttungen der Periode in Geldeinheiten.
CAPEX=Investitionsauszahlungen für längerfristige operative Vermögenswerte, in der Rechnung gewöhnlich als positiver Auszahlungsbetrag angegeben und dann abgezogen.
NWC=Nettoumlaufvermögen; der Zusatz op begrenzt es auf die operativen Bestandteile. Delta NWC ist die periodische Veränderung, eine Erhöhung bindet Liquidität.
REV=Umsatz der Periode. Ein Länder- oder Währungsindex kennzeichnet, in welcher Währung der Umsatz gemessen wird.
EXP=Aufwendungen der Periode, mit positivem Betrag in der Gewinnermittlung abgezogen.
EBIT=Ergebnis vor Zinsen und Steuern, in Geldeinheiten pro Periode.
EBT=Ergebnis vor Steuern, aber nach Zinsaufwand.
EBITDA=Ergebnis vor Zinsen, Steuern und planmäßigen Abschreibungen; trotz des Namens kein vollständiger Cashflow.
NOPAT=Operatives Ergebnis nach Steuern, vor Finanzierungseffekten; passend zum investierten operativen Kapital.
ROIC=Rendite auf das investierte operative Kapital: NOPAT geteilt durch IC, pro Periode als Dezimalzahl.
IC=Investiertes operatives Kapital, dessen Abgrenzung zum verwendeten operativen Gewinn passen muss.
ROE=Eigenkapitalrendite: Periodengewinn geteilt durch das geeignete, meist durchschnittliche Eigenkapital.
EPS=Earnings per Share, Gewinn je Aktie: den Stammaktionären zurechenbarer Gewinn geteilt durch die passende Aktienzahl.
PPE=Property, Plant and Equipment: Buchwert der Sachanlagen. Die Indizes 0 und 1 bezeichnen Anfangs- und Endbestand.
COGS=Cost of Goods Sold, Aufwand für die in der Periode verkauften Waren beziehungsweise Produkte.
DSO=Days Sales Outstanding, durchschnittliche Forderungslaufzeit in Tagen; beim Jahresumsatzmodell wird mit 365 Tagen gerechnet.
DIO=Days Inventory Outstanding, durchschnittliche Lagerdauer in Tagen.
DPO=Days Payables Outstanding, durchschnittliches Zahlungsziel gegenüber Lieferanten in Tagen.
CCC=Cash Conversion Cycle in Tagen: Forderungslaufzeit plus Lagerdauer minus Lieferantenziel.
PD=Probability of Default, Ausfallwahrscheinlichkeit für den ausdrücklich betrachteten Zeithorizont, zwischen null und eins.
LGD=Loss Given Default, Verlustquote bei Ausfall als Anteil der Ausfallforderung; 1 − Recovery-Quote unter übereinstimmender Abgrenzung.
EAD=Exposure at Default, ausstehender gefährdeter Forderungsbetrag zum Ausfallzeitpunkt, in Geldeinheiten.
EL=Expected Loss, erwarteter Verlustbetrag für den betrachteten Horizont, in Geldeinheiten.
RR=Recovery Rate, im Ausfall zurückgewonnener Anteil der Forderung, zwischen null und eins.
NAV=Net Asset Value, Nettoinventarwert beziehungsweise verbleibender Wert des Fondsanteils zum Bewertungsstichtag.
PIC=Paid-in Capital, kumuliert tatsächlich eingezahltes Kapital; nicht die bloße Kapitalzusage.
DPI=Distributions to Paid-in Capital: bereits erfolgte Ausschüttungen geteilt durch eingezahltes Kapital, als Kapitalmultiplikator.
RVPI=Residual Value to Paid-in Capital: verbleibender Nettoinventarwert geteilt durch eingezahltes Kapital, als Kapitalmultiplikator.
TVPI=Total Value to Paid-in Capital: Summe aus Ausschüttungen und Restwert geteilt durch eingezahltes Kapital; gleich DPI + RVPI.
MOIC=Multiple on Invested Capital, Wert beziehungsweise Erlös im Verhältnis zum eingesetzten Kapital; ein Multiplikator ohne eigene Zeitinformation.
bp|\mathrm{bp}=Basispunkt: 0,01 Prozentpunkte beziehungsweise 0,0001 als Dezimalzahl. Eine Änderung um 100 Basispunkte entspricht einem Prozentpunkt.
Delta|\Delta=Endlicher Unterschied zwischen zwei Werten, gewöhnlich neuer Wert minus Ausgangswert. Delta P/P ist eine relative Preisänderung; Delta y eine absolute Zinsänderung als Dezimalzahl.
t=Zeitindex beziehungsweise Zeitpunkt der Zahlung oder Beobachtung; die Periodenlänge muss zum verwendeten Zinssatz passen.
T=Letzter betrachteter Zeitpunkt beziehungsweise Horizont. Bei Zinsen pro Jahr wird T in Jahren gemessen; bei Periodenzinsen in Perioden.
n=Anzahl der in der Formel gezählten Beobachtungen, Zahlungen oder Perioden; eine dimensionslose Zählgröße. Der jeweilige Summenbereich bestimmt, was gezählt wird.
i j k=Index einer einzelnen Beobachtung, Anlage, Zahlung oder eines Szenarios im angegebenen Summenbereich; keine zusätzliche Ergebnisgröße.
e|\mathrm e=Eulersche Zahl, ungefähr 2,71828. e hoch x ist die Exponentialfunktion; bei stetiger Verzinsung wird damit ein Wachstums- oder Abzinsungsfaktor gebildet.
` ).entries;
