const T=String.raw;
const S=(text,tex=null)=>({text,tex});
const X=(type,prompt,hint,steps,focus)=>({type,level:'Vertiefung',prompt,hint,steps,focus});
module.exports=[
X('Zahlungsfrequenz','Eine Anleihe hat Macaulay Duration 6,12 Jahre und nominale Jahresrendite 8 % bei halbjährlichen Kupons. Berechne Modified Duration. Welche falsche Zahl entsteht, wenn die Jahresrendite ungeteilt im Nenner verwendet wird?','Macaulay Duration ist bereits in Jahren angegeben. Bestimme zuerst den Zinssatz pro Halbjahr.',[
S('Halbjährliche Zahlungen bedeuten zwei Perioden im Jahr. Die nominale Jahresrendite wird zur Bewertung jeder Halbjahreszahlung durch zwei geteilt.',T`m=2,\qquad \frac{y}{m}=\frac{0.08}{2}=0.04`),
S('Die Kettenregel der Preisableitung liefert den Umrechnungsfaktor. Es ist keine weitere Division der bereits in Jahren gemessenen Macaulay Duration durch zwei nötig.',T`D_{mod}=\frac{D_{Mac}}{1+y/m}=\frac{6.12}{1.04}\approx5.8846`),
S('Der ungeteilte Jahreszins ergäbe eine zu kleine Sensitivität. Er würde die vereinbarte halbjährliche Renditekonvention mit jährlicher Verzinsung verwechseln.',T`D_{\mathrm{falsch}}=\frac{6.12}{1.08}\approx5.6667`)
],'derivation-3'),
X('Laufzeitvergleich','Vergleiche zwei Nullkuponanleihen mit 100 € Nennwert, Laufzeiten zwei und zehn Jahre sowie effektiv 5 % Jahresrendite. Berechne Preise und beide Durationarten. Schätze den prozentualen Verlust bei einem Anstieg um 50 Basispunkte.','Jede Nullkuponanleihe besitzt nur eine Zahlung. Ihr barwertgewichteter Zahlungsschwerpunkt ist deshalb besonders einfach.',[
S('Ohne Zwischenzahlungen liegt das gesamte Preisgewicht am Rückzahlungstermin. Die längere Zahlung wird stärker abgezinst und hat einen kleineren heutigen Preis.',T`P_2=\frac{100}{1.05^2}\approx90.7029,\qquad P_{10}=\frac{100}{1.05^{10}}\approx61.3913`),
S('Macaulay Duration entspricht der Laufzeit. Modified Duration teilt durch den jährlichen Wachstumsfaktor.',T`D_{Mac,2}=2,\quad D_{Mac,10}=10,\qquad D_{mod,2}=\frac{2}{1.05}\approx1.9048,\quad D_{mod,10}=\frac{10}{1.05}\approx9.5238`),
S('50 Basispunkte sind 0,005 als Dezimaländerung. Die zehnjährige Anlage reagiert relativ zum eigenen Preis fünfmal so stark in der linearen Näherung. Das ist kein Vergleich gleicher Euro-DV01 bei beliebigen Positionsgrößen.',T`\frac{\Delta P_2}{P_2}\approx-1.9048(0.005)\approx-0.9524\%,\qquad\frac{\Delta P_{10}}{P_{10}}\approx-9.5238(0.005)\approx-4.7619\%`)
],'derivation-8'),
X('Kupon und Schwerpunkt','Eine zweijährige Anleihe zahlt bei Nennwert 100 € jährlich 5 € Kupon, die Jahresrendite beträgt 5 %. Berechne die Barwertgewichte und Macaulay Duration. Vergleiche mit einem zweijährigen Nullkuponbond bei derselben Rendite.','Die letzte Zahlung enthält Kupon und Tilgung. Die Gewichte müssen zusammen eins ergeben.',[
S('Zuerst werden beide Zahlungen diskontiert. Bei Übereinstimmung von Kuponrate und Rendite liegt der Kuponbond auf pari.',T`PV_1=\frac5{1.05}=4.7619,\quad PV_2=\frac{105}{1.05^2}=95.2381,\quad P=100`),
S('Die erste Zahlung erhält ein kleines, aber positives Preisgewicht. Dadurch liegt der Schwerpunkt vor dem letzten Termin.',T`w_1=0.047619,\quad w_2=0.952381,\quad D_{Mac}=1w_1+2w_2\approx1.952381\ \mathrm{Jahre}`),
S('Beim Nullkuponbond fehlt dieses frühe Gewicht. Seine Macaulay Duration ist deshalb höher; dieselbe Endfälligkeit impliziert nicht dieselbe Zinssensitivität.',T`D_{Mac,zero}=2,\qquad D_{mod,coupon}=\frac{1.952381}{1.05}\approx1.859410,\quad D_{mod,zero}=\frac2{1.05}\approx1.904762`)
],'derivation-1'),
X('DV01 und Positionsgröße','Portfolio A hat Marktwert 2 Mio. € und Modified Duration 4. Portfolio B hat Marktwert 1 Mio. € und Modified Duration 7. Welches hat die größere relative und welches die größere Geldsensitivität? Berechne DV01 und den linearen Verlust bei +20 Basispunkten.','Trenne die Veränderung je Euro Anlagewert vom Gesamtbetrag einer Position.',[
S('B hat mit Duration 7 die höhere relative Sensitivität. A ist aber doppelt so groß; für den Geldbetrag muss die Duration mit dem Marktwert multipliziert werden.',T`MD_A=2{,}000{,}000\cdot4=8{,}000{,}000,\quad MD_B=1{,}000{,}000\cdot7=7{,}000{,}000`),
S('DV01 wird hier als positiver Betrag des lokalen Wertverlusts bei einem Basispunkt Anstieg berichtet. A trägt deshalb mehr Euro-Risiko pro Basispunkt.',T`DV01_A=800\ \mathrm{EUR/bp},\qquad DV01_B=700\ \mathrm{EUR/bp}`),
S('Der Zinsanstieg erzeugt in beiden Fällen ein negatives Vorzeichen. Der Vergleich zeigt, warum eine kleinere Duration nicht automatisch den kleineren absoluten Verlust bedeutet.',T`\Delta P_A\approx-800\cdot20=-16{,}000\ \mathrm{EUR},\qquad\Delta P_B\approx-700\cdot20=-14{,}000\ \mathrm{EUR}`)
],'derivation-4'),
X('Konvexität und Asymmetrie','Ein Portfolio hat Preis 100, Modified Duration 6 und Konvexität 50. Berechne die quadratische Preisnäherung bei Zinsänderungen von +1 und −1 Prozentpunkt. Warum sind Gewinn und Verlust nicht betragsgleich?','Das Quadrat des Zinsschocks ist für beide Richtungen positiv.',[
S('Die lineare Komponente wechselt mit der Schockrichtung ihr Vorzeichen. Der Konvexitätsterm ist bei positiver Konvexität in beiden Richtungen positiv.',T`\delta=0.01,\qquad\frac12C\delta^2=\frac12\cdot50\cdot0.01^2=0.0025`),
S('Beim Anstieg mindert die Konvexität den linearen Verlust; beim Rückgang erhöht sie den linearen Gewinn. Die Preise sind Näherungen, da höhere Ableitungen fehlen.',T`P_+\approx100(1-6\cdot0.01+0.0025)=94.25,\qquad P_-\approx100(1+6\cdot0.01+0.0025)=106.25`),
S('Die Asymmetrie stammt aus der Krümmung der Preisfunktion. Sie begründet keinen sicheren Handelsertrag, denn der künftige Zinspfad, Finanzierung und mögliche Kosten bleiben offen.',T`\Delta P_+=-5.75,\quad\Delta P_-=+6.25,\qquad\frac{P_++P_-}{2}-P_0=0.25`)
],'derivation-5'),
X('Effektive Risikomaße','Ein Bewertungsmodell liefert Preis 100, bei einem Kurvenrückgang um 50 Basispunkte Preis 103 und bei einem Anstieg um 50 Basispunkte Preis 96. Berechne effektive Duration und Konvexität. Interpretiere das Konvexitätsvorzeichen.','Achte darauf, welcher Preis zum Zinsanstieg gehört. Verwende in beiden Nennern denselben symmetrischen Dezimalschock.',[
S('Für die zentrale Differenz werden beide Seiten unter dem jeweils verschobenen Kurvenszenario neu bewertet. Bei Optionen dürfen die resultierenden Cashflows reagieren.',T`P_0=100,\quad P_-=103,\quad P_+=96,\quad\delta=0.005`),
S('Die symmetrische erste Differenz liefert eine positive lokale Zinssensitivität. Die zweite Differenz ist negativ, weil der Preisanstieg bei sinkenden Zinsen kleiner ausfällt als der Verlust auf der anderen Seite.',T`D_{eff}=\frac{P_--P_+}{2P_0\delta}=\frac7{1}=7,\qquad C_{eff}=\frac{P_-+P_+-2P_0}{P_0\delta^2}=\frac{-1}{0.0025}=-400`),
S('Die negative Konvexität ist mit einer optionalen Struktur vereinbar. Sie wäre bei einem normalen Bond mit ausschließlich festen positiven Cashflows im üblichen Yieldmodell nicht die typische Form. Die Schockgröße und das Bewertungsmodell begrenzen die Aussage.')
],'derivation-6'),
X('Key-Rate-Szenario','Portfolio A hat Key-Rate-Durationen 2, 0 und 4; Portfolio B 0, 6 und 0 für kurze, mittlere und lange Kurvenpunkte. Vergleiche einen parallelen Anstieg um 10 Basispunkte mit einer Drehung: kurz −10, Mitte 0 und lang +10 Basispunkte.','Summiere für jeden Kurvenpunkt das Produkt aus Key-Rate-Duration und zugehörigem Dezimalschock, mit negativem Vorzeichen.',[
S('Beide Vektoren summieren sich auf sechs. Unter konsistent definierten kleinen Parallelverschiebungen ist die aggregierte Näherung daher gleich.',T`\frac{\Delta P_A}{P_A}\approx-(2+0+4)0.001=-0.006,\qquad\frac{\Delta P_B}{P_B}\approx-6\cdot0.001=-0.006`),
S('Bei der Drehung liegen Risiken auf verschiedenen Kurvenabschnitten. Der mittlere Punkt bewegt sich im vorgegebenen Szenario nicht.',T`\frac{\Delta P_A}{P_A}\approx-[2(-0.001)+0(0)+4(0.001)]=-0.002,\qquad\frac{\Delta P_B}{P_B}\approx0`),
S('A verliert näherungsweise 0,2 %, B zeigt in dieser linearen Darstellung keine Änderung. Konvexität, Kreuzwirkungen und die konkrete Kurveninterpolation können bei größeren Bewegungen zusätzliche Effekte erzeugen.')
],'derivation-7'),
X('Anlagehorizont und Immunisierung','Ein festverzinslicher Zahlungsplan hat Macaulay Duration 5 Jahre. Vergleiche den lokalen Effekt einer sofortigen kleinen dauerhaften parallelen Zinsänderung auf das Vermögen an Horizonten von 2, 5 und 8 Jahren. Unterstelle dieselbe Jahresrendite für Verkauf und Wiederanlage.','Schreibe das Horizontvermögen als heutigen Preis mal Aufzinsungsfaktor bis zum Horizont und leite seinen Logarithmus nach dem Zins ab.',[
S('Unter den angegebenen idealisierten Annahmen können erhaltene Cashflows bis zum Horizont wiederangelegt und spätere Cashflows am Horizont bewertet werden. Das ergibt denselben gemeinsamen Horizontwert.',T`W_H(y)=P(y)(1+y)^H`),
S('Die Preisableitung wirkt negativ, die Wiederanlage beziehungsweise Aufzinsung positiv. Bei jährlicher Verzinsung verbindet Macaulay Duration beide Terme.',T`\frac{1}{W_H}\frac{\partial W_H}{\partial y}=-D_{mod}+\frac{H}{1+y}=\frac{H-D_{Mac}}{1+y}`),
S('Bei zwei Jahren überwiegt lokal Preisrisiko, bei fünf verschwindet der Effekt erster Ordnung und bei acht überwiegt der Wiederanlageeffekt. Diese Aussage gilt nicht pauschal für beliebige zukünftige Zinskurvenpfade, Ausfälle oder veränderte Cashflows.',T`H=2:\ \frac{-3}{1+y}<0;\qquad H=5:\ 0;\qquad H=8:\ \frac3{1+y}>0`)
],'derivation-9')
];
