const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Erwartungen aus Bausteinen statt aus einem historischen Mittelwert',`Für Aktien können Ausschüttungsrendite, reales Wachstum, Inflation und Bewertungsänderung als Prognosebausteine dienen. Für Anleihen sind Anfangsrendite, Roll-down, Kurven- und Spreadänderungen sowie Kreditverluste relevant. Die Bausteine müssen so definiert werden, dass Ausschüttungen oder Wachstum nicht doppelt gezählt werden.

Historische Durchschnittsrenditen enthalten die damaligen Startbewertungen und einmalige Regimeänderungen. Sie sind deshalb nicht automatisch unverzerrte Prognosen vom heutigen Preisniveau. Langfristige Gleichgewichtsannahmen und kurzfristige zyklische Abweichungen sollten getrennt entwickelt werden.`,T`E[R_E]\approx DY+g_{EPS}+g_{P/E}`),S('Unsicherheit und konsistente Szenarien',`Punktschätzungen verdecken, wie wenig genau erwartete Renditen oft bekannt sind. Ein Bayes- oder Shrinkage-Ansatz verbindet unsichere eigene Schätzung mit einer strukturierten Ausgangsannahme. Das Gewicht der neuen Schätzung sollte von ihrer Evidenz und nicht von bloßer Überzeugungsstärke abhängen.

Szenarien müssen über Anlageklassen zusammenpassen. Hohe Inflation kann nominale Gewinne, Realzinsen und Margen unterschiedlich beeinflussen. Gleichzeitig optimistische Aktiengewinne, besonders niedrige Diskontsätze und problemlose Kreditmärkte benötigen eine gemeinsame wirtschaftliche Begründung.`,T`\mu_{post}=w\mu_{sample}+(1-w)\mu_{prior}`)],C('Gleiche neue Prognose, unterschiedliches Vertrauen','Ausgangsannahme 5 %, neue Schätzung 9 %.',['Gewicht der neuen Schätzung','Kombinierte Erwartung'],[['25 %','6 %'],['50 %','7 %'],['100 %','9 %']],'Die Kombination macht den Einfluss der Evidenz transparent. Sie ist nur eine schematische Shrinkage-Darstellung; ein vollständiges statistisches Modell leitet Gewichte aus Varianzen und Abhängigkeiten ab. Eine präzise Ausgabe allein macht die Erwartung nicht präzise.'),[['quant-07','Schätzunsicherheit quantifizieren.'],['economics-04','Langfristiges Wachstum auf Produktivität und Kapital zurückführen.']]),
D([S('Nebenbedingungen verändern die ökonomische Lösung',`Eine theoretische Allokation kann Shortpositionen, Kreditaufnahme oder sofortige Verkäufe voraussetzen. Reale Mandate besitzen Grenzen für Konzentration, Liquidität, Steuern und zulässige Instrumente. Diese Restriktionen gehören in das Optimierungsproblem und können die optimale Lösung grundlegend verändern.

Bindende Nebenbedingungen haben einen Schattenpreis: Er beschreibt lokal, wie stark sich der optimale Zielfunktionswert bei einer kleinen Lockerung ändern würde. Dieser mathematische Wert ist kein automatischer Grund, eine rechtliche oder kundenseitige Grenze zu lockern; er macht deren Opportunitätskosten sichtbar.`,T`\max_{\mathbf w}\left[\boldsymbol\mu^T\mathbf w-\frac A2\mathbf w^T\Sigma\mathbf w-C(\Delta\mathbf w)\right]\quad\text{s.t.}\quad G\mathbf w\le\mathbf h`),S('Robustheit gegenüber Inputfehlern',`Erwartete Renditen sind oft viel ungenauer geschätzt als eine Optimierung suggeriert. Kleine Differenzen können große Gewichtsverschiebungen erzeugen. Robuste Ansätze prüfen mehrere plausible Parameterkombinationen, bestrafen Instabilität oder begrenzen extreme Exponierungen.

Restriktionen können Fehlerrisiko reduzieren, aber auch echte Chancen ausschließen. Ihre Wirkung sollte daher anhand von Zielerreichung, Stressverlusten und Umsetzbarkeit geprüft werden. Die Anzahl von Dezimalstellen eines optimalen Gewichts ist kein Qualitätsmerkmal.`)],C('Gleiche unbeschränkte Präferenz, andere zulässige Quote','Modelloptimum für eine riskante Anlage 80 %, übriger Anteil sicher.',['Mandatsgrenze','Zulässige optimale Quote bei konkavem Einanlagenproblem'],[['Maximal 100 %','80 %'],['Maximal 60 %','60 %'],['Maximal 30 %','30 %']],'Die Randlösung folgt daraus, dass der Nutzen bis zum unbeschränkten Optimum steigt. Sie ist nicht durch erneutes Erfinden einer Renditeannahme zu umgehen. Bei mehreren Anlagen müssen die Wechselwirkungen im vollständigen Problem neu berechnet werden.'),[['quant-13','Optimierungsbedingungen und Restriktionen.'],['portfolio-06','Mandatsziele vor Produktwahl festlegen.']]),
D([S('Überschussvermögen statt isoliertem Anlagevermögen',`Beim Asset-Liability-Management ist die Differenz zwischen Aktiva und Verpflichtungen zentral. Eine Anlage kann für sich schwanken und dennoch die Unterdeckung stabilisieren, wenn Verpflichtungen ähnlich reagieren. Umgekehrt kann ein nominal stabiler Cashbestand den Barwert langfristiger realer Verpflichtungen schlecht absichern.

Die Surplusvarianz enthält Varianz beider Seiten und ihren Kovarianzterm. Diese Gleichung zeigt, warum ein hoher Gleichlauf von Aktiva und Verpflichtungen nützlich sein kann. Die Definition der Verpflichtung – nominal, real, marktwertbezogen oder gesetzlich – bestimmt die passende Risikobetrachtung.`,T`S=A-L,\quad Var(S)=Var(A)+Var(L)-2Cov(A,L)`),S('Funding Ratio und Zinssensitivität',`Die Funding Ratio setzt Vermögenswert ins Verhältnis zum Verpflichtungsbarwert. Für kleine Zinsänderungen hängt ihre relative Bewegung näherungsweise von der Differenz der prozentualen Durationsmaße ab. Für Stabilisierung des absoluten Überschusses werden dagegen Dollar-Durationsbeträge verglichen.

Bei Unter- oder Überdeckung sind gleiche prozentuale Durationswerte deshalb nicht automatisch dasselbe wie gleiche absolute Zinsrisiken. Kuponwiederanlage, Kurvenform, Konvexität und neue Verpflichtungen erfordern laufende Anpassung.`,T`FR=\frac AL,\quad \Delta S\approx(-AD_A+LD_L)\Delta y,\quad \frac{\Delta FR}{FR}\approx(D_L-D_A)\Delta y`)],C('Gleicher Vermögenswert, andere Anlageduration','A = L = 100, Verpflichtungsduration 10; Zins steigt 1 %, lineare Näherung.',['Anlageduration','Aktiva danach','Verpflichtung danach','Überschuss danach'],[['0','100','90','10'],['5','95','90','5'],['10','90','90','0']],'Ein zinsbedingter Verlust der Anlagen kann zusammen mit gleich stark fallenden Verpflichtungen den Überschuss stabil halten. Der Erfolg einer ALM-Strategie lässt sich deshalb nicht allein an der Anlagenrendite beurteilen.'),[['bonds-08','Duration als Preisableitung.'],['path-portfolio-03','Immunisierung unter Kurven- und Konvexitätsrisiko.']]),
D([S('Institutionelle und private Ziele aus Zahlungsstrukturen ableiten',`Pensionsfonds haben zugesagte oder erwartete Leistungen, Versicherer vertragliche Risiken, Stiftungen laufende Ausschüttungsziele und private Haushalte Lebenszykluszahlungen. Diese Unterschiede wirken auf Zeithorizont, Liquidität, Steuerstatus und Risikotragfähigkeit. Eine identische Vermögenshöhe impliziert deshalb keine identische Allokation.

Auch die Governance unterscheidet sich. Ein institutionelles Gremium kann spezialisierte Ressourcen besitzen, aber langsame Entscheidungswege. Ein privater Anleger kann flexibler sein, jedoch durch Familienkonflikte oder begrenzte Fachkenntnis eingeschränkt werden. Umsetzbarkeit umfasst daher auch organisatorische Fähigkeiten.`),S('Ausschüttung, Inflation und Vermögenserhalt',`Eine Stiftung, die dauerhaft realen Vermögenswert erhalten und zugleich ausschütten möchte, benötigt eine konsistente Rendite- und Ausgabenrechnung. Eine einfache additive Näherung aus Ausschüttung, Inflation und Kosten hilft der Orientierung; exakte Mehrperiodenrechnung hängt von Zahlungszeitpunkten ab.

Eine geglättete Ausschüttungsregel kann operative Planung stabilisieren, reagiert aber langsamer auf Marktverluste. Dadurch steigt nach einem Einbruch möglicherweise die aktuelle Ausschüttung relativ zum Vermögen. Reserven und Anpassungsregeln müssen diesen Zielkonflikt berücksichtigen.`,T`W_{t+1}=(W_t-D_t)(1+R_{t+1})\quad\text{bei Entnahme am Periodenanfang}`)],C('Gleiche Ausgabe, anderer Vermögensstand','Jährliche geplante Ausschüttung 5.',['Vermögen','Aktuelle Ausschüttungsquote'],[['100','5 %'],['80','6,25 %'],['60','8,33 %']],'Nach Verlusten verbraucht dieselbe absolute Ausgabe einen größeren Vermögensanteil. Eine stabile nominale Ausschüttung und langfristiger realer Vermögenserhalt können daher in Konflikt geraten. Die Reaktion hängt von der Flexibilität der begünstigten Ausgaben ab.'),[['path-wealth-03','Entnahmepfade und Reihenfolgerisiko.'],['path-portfolio-04','Institutionelle Verpflichtungen konkretisieren.']]),
D([S('Anlageklassen auf gemeinsame Risikotreiber abbilden',`Aktien, Unternehmensanleihen und Private Equity können alle stark auf Wachstum und Finanzierung reagieren. Immobilien und Infrastruktur besitzen zugleich Zins-, Inflations- und operative Exponierungen. Eine Allokation nach Produktkategorien kann daher wirtschaftlich konzentrierter sein als sie aussieht.

Eine Faktormatrix B bildet Positionen auf gemeinsame Treiber ab. Mit Faktor-Kovarianzmatrix Ω und residualer Risikomatrix Ψ lässt sich die Gesamtkovarianz strukturiert darstellen. Das Modell erleichtert die Erkennung überlappender Wetten, bleibt aber von Faktorwahl und Datenqualität abhängig.`,T`\Sigma=B\Omega B^T+\Psi,\qquad\mathbf b_P=B^T\mathbf w`),S('Liquidität und Bewertung in die Integration aufnehmen',`Private NAVs reagieren häufig verzögert, während öffentliche Preise sofort schwanken. Nach einem Börsenverlust kann deshalb die gemessene Privatmarktquote steigen, auch wenn der wirtschaftliche Privatwert ebenfalls gefallen ist. Zusageplanung und Rebalancing dürfen diesen Nenner- und Bewertungseffekt nicht ignorieren.

Eine integrierte Steuerung betrachtet daher Marktwertschätzungen, Kapitalabrufe, Sicherheitenbedarf und Verkaufsmöglichkeiten zusammen. Die optimale langfristige Mischung kann eine Reserve benötigen, deren niedrige erwartete Rendite der Preis für Handlungsfähigkeit in Krisen ist.`)],C('Drei Kategorien, ein gemeinsamer Faktor','Je ein Drittel Aktien, High-Yield-Anleihen und Private Equity; illustrative Wachstumsbetas 1, 0,6 und 1,4.',['Position','Kapitalgewicht','Beitrag zum Wachstumsbeta'],[['Aktien','1/3','0,333'],['High Yield','1/3','0,200'],['Private Equity','1/3','0,467'],['Gesamt','1','1,000']],'Drei Kategorien liefern hier keine Neutralität gegenüber Wachstum. Fast die Hälfte des gemeinsamen Faktorbeitrags stammt aus Private Equity. Die Betas sind illustrative Annahmen; tatsächliche Werte müssen mit passender Methode geschätzt werden.'),[['portfolio-05','Faktormodelle und Exponierung.'],['alternatives-03','Bewertungsglättung berücksichtigen.']]),
D([S('Währungsrendite mit lokaler Rendite verbinden',`Bei einer Auslandsanlage multipliziert der lokale Wachstumsfaktor den Wechselkursfaktor. Eine Absicherung verkauft typischerweise einen erwarteten Fremdwährungsbetrag auf Termin. Der gesicherte Betrag und der spätere tatsächliche Vermögenswert können wegen Marktbewegungen voneinander abweichen.

Forwardpunkte entstehen aus Zinsrelationen und weiteren Marktbedingungen. Sie sind keine beliebige Versicherungsgebühr, müssen aber in die Gesamtrendite der Absicherung eingehen. Ein häufiger Fehler ist, Spotänderung vollständig zu entfernen und zugleich den Zinsunterschied zu ignorieren.`,T`1+R_H=(1+R_L)(1+R_{FX})`),S('Optimale Hedge Quote hängt vom Gesamtportfolio ab',`In einer linearen Näherung kann die nicht abgesicherte Rendite als lokale Rendite plus verbleibende Währungsexponierung geschrieben werden. Ableiten ihrer Varianz nach Hedge Quote h zeigt, dass Kovarianz zwischen lokaler Anlage und Währung die Minimum-Varianz-Lösung beeinflusst.

Die Formel setzt eine einfache perfekte Währungsabsicherung ohne zusätzliche Basis- und Kostenrisiken voraus. Die tatsächliche Quote kann außerdem durch erwartete Währungsprämien, Liquidität, Mandat und Schätzunsicherheit bestimmt werden. Vollständige Absicherung ist daher eine mögliche Politik, kein universelles mathematisches Optimum.`,T`R_H\approx R_L+(1-h)R_{FX},\quad h^*=1+\frac{Cov(R_L,R_{FX})}{Var(R_{FX})}`)],C('Gleiche Währungsvolatilität, andere Gegenbewegung','Varianz der Währungsrendite 0,01.',['Kovarianz lokal / Währung','Unbeschränkte Minimum-Varianz-Hedgequote'],[['−0,005','50 %'],['0','100 %'],['+0,005','150 %']],'Bei negativer Kovarianz stabilisiert ein Teil der Währungsexponierung die lokale Anlage. Die 150-%-Lösung entspricht im einfachen Modell einer Überabsicherung und kann außerhalb des Mandats liegen. In der Praxis werden Beschränkungen und unsichere Schätzungen ausdrücklich berücksichtigt.'),[['economics-11','Forwardpunkte aus Zinsparität.'],['derivatives-12','Hedgequoten nach Risikofaktoren bestimmen.']]),
D([S('Overlay trennt Kapitalanlage und Risikosteuerung',`Ein Overlay verändert über Derivate bestimmte Exponierungen, ohne alle zugrunde liegenden Anlagen zu kaufen oder zu verkaufen. Beispiele sind Cash-Equitization, Durationanpassung oder Währungsabsicherung. Die physische Kapitalallokation und die wirtschaftliche Risikoallokation können dadurch voneinander abweichen.

Mehrere Sensitivitäten lassen sich als lineares Gleichungssystem darstellen: Jeder Kontrakt liefert Beiträge zu Beta, DV01 oder anderen Faktoren; die Kontraktzahlen sollen die gewünschte Änderung erzeugen. Ist das System nicht exakt lösbar, wird eine begründete Näherung unter Kosten und Nebenbedingungen gewählt.`,T`A\mathbf n=\Delta\mathbf b`),S('Governance und Sicherheiten gehören zur Strategie',`Ein Overlaymanager kann dieselbe Exponierung absichern, die ein anderer Manager bewusst aufbaut. Ohne gemeinsame Risikosicht entstehen gegenläufige Trades und unnötige Kosten. Zuständigkeit, Referenzdaten und Gesamtgrenzen müssen deshalb klar sein.

Derivate benötigen Sicherheiten und operative Betreuung. Ein niedriger Anfangsmarktwert ist kein niedriger möglicher Cashbedarf. Zudem kann ein linearer Hedge nicht jede Nichtlinearität abdecken. Delta-, Gamma- und Volatilitätsexponierungen sind gegebenenfalls gemeinsam zu überwachen.`)],C('Gleiche Zieländerung, unterschiedliche Kontraktwirkung','Ziel: Portfolio-DV01 um 1.000 reduzieren.',['Kontrakt-DV01 je gegenläufigem Kontrakt','Benötigte Anzahl'],[['25','40'],['50','20'],['100','10']],'Die Stückzahl folgt aus Zieländerung geteilt durch Kontraktwirkung. Nominalbeträge allein reichen nicht. Bei mehreren Laufzeitfaktoren kann ein einziger Kontrakt zwar die Gesamtduration treffen, aber Key-Rate-Risiken offenlassen.'),[['bonds-08','DV01 und Key-Rate-Vektoren.'],['derivatives-09','Nichtlineare Exponierungen separat behandeln.']]),
D([S('Liquidität als zeitabhängige Zahlungsfähigkeit',`Ein Portfolio kann einen positiven Nettovermögenswert besitzen und dennoch eine fällige Zahlung nicht leisten können. Verfügbare Liquidität hängt von Verkaufbarkeit, Abwicklungsfristen, Sicherheitenbindung und Kreditlinien ab. Die Summe aller bilanziellen Vermögenswerte ist dafür kein geeigneter Ersatz.

Eine einfache interne Deckungsquote kann liquide verfügbare Mittel mit gestressten Nettoabflüssen vergleichen. Sie ist hier eine Planungskennzahl und keine Behauptung über eine regulatorische Basel-LCR. Zeitfenster und Haircuts müssen ausdrücklich definiert werden.`,T`\ell_H=\frac{A_{liq,H}}{O_{net,H}}`),S('Konzentration, Sprünge und Rückkopplungen',`Konzentration kann in Namen, Sektoren, Gegenparteien, Finanzierung oder Liquiditätsquellen entstehen. Ein Herfindahl-Index auf Gewichten misst eine einfache Form, erfasst aber keine wirtschaftlichen Korrelationen. Zwei formal verschiedene Positionen können gemeinsam ausfallen.

Extremrisiken verbinden häufig mehrere Kanäle: Marktverlust, höherer Haircut, Rückgaben und geringere Verkaufserlöse. Ein Liquiditätsstress sollte deshalb die Reihenfolge von Zahlungen und Maßnahmen modellieren. Eine Kreditlinie, die im selben Stress unsicher wird, ist nicht vollständig mit sofort verfügbarem Cash gleichzusetzen.`,T`HHI=\sum_iw_i^2`)],C('Gleicher NAV, unterschiedlicher Stressbedarf','NAV 100, sofort verfügbare Mittel 15.',['Nettoabfluss im Stress','Interne Deckungsquote','Fehlbetrag'],[['10','1,5','0'],['20','0,75','5'],['30','0,5','15']],'Der NAV bleibt in der isolierten Rechnung gleich. Trotzdem entsteht bei höherem Zahlungsbedarf ein konkreter Fehlbetrag. Ein Risikobericht muss daher nicht nur mögliche Endverluste, sondern auch zwischenzeitliche Finanzierung zeigen.'),[['bonds-12','Haircutänderungen lösen Cashbedarf aus.'],['alternatives-01','Kapitalzusagen sind zusätzliche Verpflichtungen.']]),
D([S('Attribution erklärt aktive Rendite, Appraisal beurteilt sie',`Attribution zerlegt den Unterschied zur Benchmark in nachvollziehbare Beiträge. Im Brinson-Fachler-Ansatz werden Allokation, Selektion und Interaktion getrennt. Die Gewichte und Segmentrenditen müssen dieselbe Periode, Währung und Kostenbasis verwenden.

Allokation misst, ob Segmente mit überdurchschnittlicher Benchmarkrendite übergewichtet waren. Selektion misst innerhalb eines Segments den Renditeunterschied mit Benchmarkgewicht. Interaktion erfasst die gleichzeitige Abweichung von Gewicht und Segmentrendite. Andere Konventionen verteilen diesen Interaktionsterm anders; die Methodik muss genannt werden.`,T`A_i=(w_{Pi}-w_{Bi})(R_{Bi}-R_B),\quad S_i=w_{Bi}(R_{Pi}-R_{Bi}),\quad I_i=(w_{Pi}-w_{Bi})(R_{Pi}-R_{Bi}),\quad R_P-R_B=\sum_i(A_i+S_i+I_i)`),S('Mehrperiodigkeit und Faktorbeiträge',`Einperiodige arithmetische Beiträge summieren sich zur aktiven Rendite dieser Periode. Über mehrere Perioden werden Renditen jedoch verkettet. Die bloße Summe jährlicher Beiträge stimmt deshalb nicht automatisch mit dem mehrperiodigen relativen Vermögenseffekt überein; es braucht eine festgelegte Linking-Methode.

Faktorattribution erklärt Renditen über Exponierungen und realisierte Faktorbewegungen. Sie ergänzt die Segmentansicht, kann aber modellabhängige Residuen hinterlassen. Ein positiv benannter Beitrag beweist außerdem noch keine Fähigkeit; dafür werden Wiederholbarkeit, Risiko und Kosten beurteilt.`)],C('Allokation und Selektion in einem vollständigen Vergleich','Benchmark 50/50 in A/B mit Renditen 10 %/0 %; Portfolio 60/40 mit Segmentrenditen 12 %/0 %.',['Beitrag','A','B','Summe'],[['Allokation','0,5 %','0,5 %','1,0 %'],['Selektion','1,0 %','0 %','1,0 %'],['Interaktion','0,2 %','0 %','0,2 %'],['Gesamte aktive Rendite','1,7 %','0,5 %','2,2 %']],'Benchmarkrendite ist 5 %, Portfoliorendite 7,2 %. Die Beiträge summieren sich exakt auf 2,2 Prozentpunkte. Der Vergleich zeigt, dass höhere Gewichtung und bessere Auswahl gemeinsam einen zusätzlichen Interaktionseffekt erzeugen.'),[['portfolio-08','Strategische und taktische Gewichte unterscheiden.'],['advanced-10','Erklärte Beiträge anschließend bewerten.']]),
D([S('Track Records enthalten Schätzfehler',`Eine historische Überrendite ist eine Stichprobenschätzung. Ihre Aussage hängt von Streuung, Beobachtungszahl, Abhängigkeit und der Auswahl des Managers ab. Bei unabhängigen Beobachtungen sinkt der Standardfehler mit der Quadratwurzel der Anzahl; bei Autokorrelation oder geglätteten Daten gilt diese einfache Rechnung nicht unverändert.

Ein t-Wert setzt Schätzung ins Verhältnis zu ihrem Standardfehler. Statistische Signifikanz bedeutet weder wirtschaftliche Größe noch Zukunftsgarantie. Ein nach vielen Tests ausgewählter Gewinner benötigt eine strengere Beurteilung als eine vorab festgelegte einzelne Hypothese.`,T`SE(\bar a)=\frac{s_a}{\sqrt n},\qquad t=\frac{\bar a}{SE(\bar a)}`),S('Fähigkeit, Faktorlast und Umsetzbarkeit',`Ein Manager kann eine Prämie verdienen, die durch günstige systematische Exponierung erklärt wird. Die Frage ist dann, ob diese Exponierung günstiger und transparenter anderweitig erhältlich wäre. Ein Residualalpha muss zusätzlich nach Gebühren, Handel und Kapazitätsgrenzen betrachtet werden.

Persistenzprüfung untersucht, ob Prozess und wirtschaftlicher Mechanismus außerhalb der ursprünglichen Daten bestehen. Teamwechsel, wachsende Assets oder ein verändertes Marktregime können einen früheren Vorteil schwächen. Ein gutes Leistungsurteil verbindet quantitative Evidenz mit plausibler Ursache.`)],C('Gleiche Überrendite und Streuung, andere Beobachtungszahl','Jährliche aktive Rendite im Mittel 2 %, Standardabweichung 8 %, unabhängige Jahre als Modellannahme.',['Jahre','Standardfehler','t-Wert'],[['4','4 %','0,5'],['16','2 %','1'],['64','1 %','2']],'Die gleiche durchschnittliche Überrendite wird mit mehr unabhängigen Daten genauer geschätzt. 64 Jahre desselben unveränderten Prozesses sind in der Praxis selten verfügbar; eine lange Reihe kann zugleich Strukturbrüche enthalten. Mehr Daten sind deshalb nicht automatisch gleich viele vergleichbare Beobachtungen.'),[['quant-08','Tests und Fehlerwahrscheinlichkeiten.'],['portfolio-04','Alpha ist relativ zu einem Modell definiert.']]),
D([S('Managerauswahl als mehrstufige Evidenzprüfung',`Die Auswahl beginnt mit der benötigten Rolle im Portfolio. Danach werden Philosophie, Prozess, Personen, Portfolio und Ergebnisse geprüft. Ein Manager mit guter absoluter Rendite kann ungeeignet sein, wenn er vorhandene Risiken dupliziert oder die Liquiditätsbedingungen nicht erfüllt.

Quantitative Analyse identifiziert Exponierungen, Kosten und auffällige Muster. Qualitative Due Diligence untersucht, ob die Organisation den behaupteten Vorteil erzeugen und kontrollieren kann. Bewertung, Handel, Compliance, Verwahrung und Geschäftskontinuität sind dabei eigenständige Aspekte.`),S('Monitoring und Wechselentscheidung',`Schwache Performance kann aus einer erwartbaren Faktorphase stammen oder aus einem gebrochenen Prozess. Die Reaktion hängt von der Ursache ab. Vorab definierte Beobachtungskriterien helfen, panische Kündigungen nach Verlusten und blindes Festhalten an einer alten Geschichte zu vermeiden.

Ein Wechsel erzeugt Transaktionskosten, mögliche Steuerzahlungen, Marktphasenrisiko und organisatorischen Aufwand. Erwarteter Mehrwert eines Nachfolgers muss diese Kosten und die Unsicherheit der Einschätzung übersteigen. Vergangenheit und bereits gezahlte Gebühren sind keine rückholbaren Gründe, ein ungeeignetes Mandat fortzuführen.`,T`NPV_{switch}=\sum_t\frac{E[\Delta CF_t]}{(1+r)^t}-C_0`)],C('Gleiche erwartete Verbesserung, unterschiedliche Wechselkosten','Erwarteter zusätzlicher Nettoertrag 1 pro Jahr über drei Jahre, Diskontsatz 5 %. Barwert 2,72.',['Einmalige Wechselkosten','NPV des Wechsels'],[['1','1,72'],['3','−0,28'],['5','−2,28']],'Die gleiche Prognose rechtfertigt nicht jeden Wechselpreis. Zusätzlich ist zu prüfen, wie belastbar die erwartete Verbesserung ist. Eine kleine positive Modellzahl bei großer Prognoseunsicherheit liefert nur schwache Entscheidungsevidenz.'),[['alternatives-03','Operational Due Diligence und Datenverzerrungen.'],['ethics-09','Unternehmensweite Kontrollen beurteilen.']]),
D([S('Compositeberechnung beginnt bei der passenden Grundgesamtheit',`Ein Composite fasst Portfolios mit einer definierten Strategie nach den einschlägigen GIPS-Anforderungen zusammen. Die Definition muss nachvollziehbar und konsistent angewandt werden. Eine nachträgliche Auswahl erfolgreicher Konten verzerrt das Ergebnis auch dann, wenn jede Einzelrendite mathematisch korrekt ist.

Vermögensgewichtung verbindet Portfoliorenditen zu einer periodischen Composite-Rendite. Die tatsächliche Behandlung von Zahlungsströmen und Gewichten folgt der verwendeten zulässigen Methodik. Mehrperiodige Ergebnisse werden aus den Periodenrenditen verkettet, nicht einfach addiert.`,T`R_{C,t}=\sum_iw_{i,t}R_{i,t},\quad\sum_iw_{i,t}=1,\quad R_{C,0:T}=\prod_t(1+R_{C,t})-1`),S('Präsentation, Streuung und Prüfungsumfang',`Eine einzelne Composite-Rendite verdeckt mögliche Unterschiede zwischen Konten. Streuung, Vermögensgrößen, Gebührenbasis, Benchmark und relevante Offenlegungen helfen, den Track Record zu verstehen. Eine vergleichbare Präsentation verlangt dieselben Zeiträume und klar definierte Brutto- beziehungsweise Nettoangaben.

Firmweite Einhaltung, unabhängige Verifizierung und eine gegebenenfalls gesonderte Performanceprüfung sind unterschiedliche Aussagen. Für eine tatsächliche GIPS-Präsentation sind die aktuellen Standards und anwendbaren Anforderungen maßgeblich. Eine mathematisch korrekte Übungsrechnung allein begründet keine Einhaltungserklärung.`)],C('Gleiche Kontorenditen, andere Vermögensgewichte','Keine externen Cashflows in der Periode. A erzielt 10 %, B −10 %.',['Anfangsvermögen A / B','Composite-Rendite'],[['50 / 50','0 %'],['90 / 10','8 %'],['10 / 90','−8 %']],'Die Gewichtung erklärt den gesamten Unterschied. Eine einfache Mittelung wäre nur in der ersten Zeile dieselbe Aussage. Für Zeitreihen müssen Gewichte und Zahlungsflüsse nach der festgelegten Methode periodengerecht aktualisiert werden.'),[['ethics-10','Faire Auswahl und Darstellung der Performance.'],['quant-04','Renditeverkettung bei Zahlungsflüssen.']])
];
