const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Zusage, investiertes Kapital und Nettoinventarwert',`Bei einem geschlossenen Fonds verpflichtet sich ein Anleger zunächst zu einer Kapitalzusage. Der Fonds ruft Mittel später ab, investiert sie und schüttet bei Veräußerungen aus. Zusage, eingezahltes Kapital und aktueller NAV sind daher unterschiedliche Größen. Nicht abgerufenes Kapital bleibt eine mögliche künftige Liquiditätsverpflichtung.

Ein offener Fonds bietet Rückgaberechte nach seinen Bedingungen, kann aber ebenfalls Fristen, Gates oder andere Beschränkungen besitzen. Liquidität des Fondsanteils und Liquidität der gehaltenen Vermögenswerte müssen zueinander passen. Ein jederzeit sichtbarer NAV bedeutet nicht jederzeitige Auszahlung zu diesem Wert.`,T`U_t=C_{commit}-C_{called,t}\quad\text{im einfachen Modell ohne Recycling}`),S('Illiquidität und Portfolioeffekt',`Langfristige Bindung kann dem Manager erlauben, operative Maßnahmen ohne kurzfristigen Verkaufsdruck umzusetzen. Sie belastet den Anleger jedoch mit geringerer Anpassungsfähigkeit. Eine mögliche Illiquiditätsprämie ist eine erwartete Kompensation und kein garantierter Mehrertrag jedes privaten Investments.

Kapitalabrufe können mit Marktkrisen zusammenfallen, während Ausschüttungen ausbleiben. Die Planung muss deshalb Zusagen, liquide Reserve und bestehende Exponierungen gemeinsam berücksichtigen. Der NAV privater Anlagen kann sich zudem langsamer an Marktveränderungen anpassen und dadurch Portfolioquoten optisch stabilisieren.`)],C('Gleicher NAV, verschiedene offene Verpflichtungen','Beide Anleger halten Fondsanteile mit NAV 50.',['Anleger','Noch abrufbare Zusage','Möglicher zusätzlicher Cashbedarf'],[['A','0','0 aus dieser Zusage'],['B','50','Bis 50 nach Vertragsbedingungen']],'Eine reine NAV-Allokation würde beide gleich behandeln. Ihre Liquiditätsrisiken unterscheiden sich erheblich. Der zweite Anleger muss mögliche Abrufe zusätzlich zu seinen anderen Zahlungen finanzieren können.'),[['path-private-04','Kapitalabrufe und Ausschüttungen planen.'],['advanced-08','Liquiditätsstress über alle Verpflichtungen erfassen.']]),
D([S('Gebührenwasserfall mit klarer Berechnungsbasis',`Management Fee, Hurdle, Carry und Catch-up definieren unterschiedliche Ansprüche. Die Reihenfolge entscheidet, ob Gebühren auf zugesagtes oder investiertes Kapital, NAV oder andere Basen berechnet werden und ab wann der Manager am Gewinn beteiligt ist. Ein bloßer Satz wie „2 und 20“ beschreibt den Vertrag nicht vollständig.

Whole-fund- und dealbezogene Wasserfälle können Carry zu verschiedenen Zeitpunkten ausschütten. Clawback-Regeln sollen unter bestimmten Bedingungen zu viel früh ausgeschütteten Carry zurückholen. Ihre Wirksamkeit hängt auch von Sicherung, Steuern und tatsächlicher Einbringlichkeit ab.`),S('IRR, Multiples und öffentlicher Vergleich',`DPI setzt erhaltene Ausschüttungen ins Verhältnis zu eingezahltem Kapital, RVPI den verbleibenden NAV, TVPI ihre Summe. IRR berücksichtigt zusätzlich Zeitpunkte. Ein früher kleiner Rückfluss kann IRR stark verändern, ohne einen großen absoluten Vermögenszuwachs zu erzeugen.

Ein Public Market Equivalent vergleicht private Cashflows mit einem definierten öffentlichen Anlageweg. Die konkrete PME-Methode und Benchmark bestimmen das Ergebnis. Unterschiede in Risiko, Leverage und Liquidität bleiben gesondert zu beurteilen.`,T`DPI=\frac{D}{PIC},\quad RVPI=\frac{NAV}{PIC},\quad TVPI=DPI+RVPI`)],C('Gleicher Bruttogewinn, andere Carry-Schwelle','Einjährig 100 investiert, Endwert 130, keine Management Fee oder Catch-up; Carry 20 % nur auf Gewinn oberhalb der genannten Hurdle.',['Hurdle','Carry-Basis','Carry','Nettoendwert Anleger'],[['0 %','30','6','124'],['8 %','22','4,4','125,6']],'Die Differenz entsteht ausschließlich durch die ausdrücklich definierte Schwelle. Ein Vertrag mit Catch-up kann zu einer anderen Gewinnverteilung führen. Deshalb muss vor jeder Rechnung der tatsächliche Wasserfall in Schritte zerlegt werden.'),[['path-private-06','Wertbeiträge und Vergütung gemeinsam beurteilen.'],['quant-04','Cashflowzeitpunkte beeinflussen IRR.']]),
D([S('Bewertungsglättung verändert gemessene Risiken',`Private Vermögenswerte werden oft seltener und teilweise modellbasiert bewertet. Ein geglätteter gemeldeter Ertrag kann einen Teil früherer Wertänderungen erst später zeigen. Dadurch wirken Volatilität und zeitgleiche Korrelation mit öffentlichen Märkten zu niedrig, obwohl das wirtschaftliche Risiko nicht verschwunden ist.

Ein einfaches Glättungsmodell mischt aktuellen latenten Ertrag mit zuvor gemeldeter Rendite. Es erzeugt serielle Abhängigkeit. Eine Entglättung benötigt Annahmen über diesen Prozess und kann Messfehler verstärken; sie ist keine sichere Rekonstruktion eines unbekannten Marktpreises.`,T`r_t^{obs}=\theta r_t^*+(1-\theta)r_{t-1}^{obs},\quad0<\theta\le1`),S('Auswahlverzerrungen und Due Diligence',`Survivorship Bias entsteht, wenn gescheiterte Fonds fehlen. Backfill Bias entsteht, wenn Anbieter zunächst erfolgreiche Historien nachmelden. Freiwillige Berichterstattung kann weitere Auswahl erzeugen. Ein Datenbankdurchschnitt muss deshalb nicht die Rendite aller tatsächlich verfügbaren Fonds darstellen.

Due Diligence prüft neben Performance auch Team, Strategie, Bewertung, Kontrollen, Rechtsstruktur und Interessenkonflikte. Bei einer modellbasierten Bewertung sind Unabhängigkeit, Inputherkunft und Abweichungen zu späteren Verkaufspreisen wichtige Kontrollinformationen.`)],C('Gleicher wirtschaftlicher Schock, anderer Ausweis','Latenter Verlust −20 %, vorher gemeldete Rendite 0 %.',['Glättungsgewicht θ','Gemeldete aktuelle Rendite'],[['1','−20 %'],['0,5','−10 %'],['0,25','−5 %']],'Der kleinere gemeldete Verlust bedeutet im Modell keine geringere wirtschaftliche Wertänderung. Der Rest wird zeitlich verschoben. Eine Portfoliokorrelation auf gemeldeten Quartalswerten kann diesen Effekt mit echter Diversifikation verwechseln.'),[['quant-11','Serielle Abhängigkeit und Stationarität prüfen.'],['advanced-11','Managerprozess statt nur Renditehistorie untersuchen.']]),
D([S('Buyout-Rendite in operative Leistung und Finanzierung zerlegen',`Ein Buyout erwirbt ein Unternehmen häufig mit erheblichem Fremdkapital. Eigenkapitalwert beim Exit ergibt sich aus Unternehmenswert minus verbleibender Nettoschuld. Höheres EBITDA, veränderter Bewertungsmultiplikator und Schuldentilgung wirken daher über verschiedene Kanäle auf den Eigentümerertrag.

Leverage verstärkt die Rendite auf das kleinere anfängliche Eigenkapital, erhöht aber auch Ausfall- und Refinanzierungsrisiko. Die Tilgung muss aus tatsächlich verfügbarem Cashflow finanziert werden. Eine isolierte Annahme sinkender Schuld ohne entsprechende Cashflowrechnung ist inkonsistent.`,T`EV_{exit}=EBITDA_{exit}M_{exit},\quad E_{exit}=EV_{exit}-D_{exit},\quad MOIC=\frac{E_{exit}}{E_0}`),S('Venture Capital: Verwässerung und asymmetrische Verteilung',`Junge Unternehmen besitzen oft geringe aktuelle Gewinne und hohe Unsicherheit über Produkt, Markt und Finanzierung. Mehrere Finanzierungsrunden verändern Eigentumsanteile. Ein steigender Unternehmenswert kann daher mit einem weniger stark steigenden Wert der ursprünglichen Beteiligung einhergehen.

Vorzugsrechte und Liquidationspräferenzen verteilen Exitwerte nicht immer proportional nach vollständig verwässerten Anteilen. Die Bewertung muss den Wasserfall je Exit-Szenario abbilden. Portfolioerträge können stark von wenigen Erfolgen abhängen; Medianunternehmen und durchschnittlicher Fondsbeitrag erzählen dann unterschiedliche Geschichten.`)],C('Gleicher Exit-Unternehmenswert, andere Schuldentilgung','Kauf EV 100, Schulden 60, Eigenkapital 40. Exit EV bleibt 100.',['Restschuld beim Exit','Eigenkapital beim Exit','MOIC'],[['60','40','1,0'],['40','60','1,5'],['20','80','2,0']],'Der Wertzuwachs des Eigentümers entsteht hier vollständig durch Schuldentilgung. Er ist nur möglich, wenn zwischenzeitlicher Cashflow oder weitere Mittel die Tilgung finanzieren. Er darf nicht zugleich noch einmal als separate Ausschüttung gezählt werden.'),[['path-private-02','Transaktionsmodell vollständig aufbauen.'],['corporate-07','Leverage verstärkt auch Verluste.']]),
D([S('Private Credit: Vertragsrendite und Kreditverlust',`Private Kredite können individuelle Covenants, Sicherheiten und flexible Strukturen bieten. Die höhere versprochene Verzinsung kompensiert möglicherweise Illiquidität, Komplexität und Kreditrisiko. Sie ist nicht gleich der erwarteten Nettorendite nach Ausfällen, Kosten und Wiedergewinnung.

PIK-Zinsen werden dem Kapital zugeschlagen statt bar gezahlt. Dadurch wächst der vertragliche Anspruch, aber zugleich die spätere Belastung des Schuldners. Ein hoher ausgewiesener Ertrag kann daher ohne laufenden Cashzufluss entstehen und von der endgültigen Einbringlichkeit abhängen.`,T`D_t=D_0(1+r_{PIK})^t`),S('Distressed Debt und Restrukturierungswert',`Bei notleidenden Ansprüchen ist die zentrale Frage, welcher Wert nach Restrukturierung verfügbar ist und wie er auf Ränge verteilt wird. Rechtliche Position, Sicherheiten, Verfahrenskosten, Zeit und Verhandlungsmacht beeinflussen Recovery. Ein niedriger Kurs allein beweist keine günstige Anlage.

Der Investor kann an einer Umwandlung von Schuld in Eigenkapital teilnehmen. Dann verändert sich das Risikoprofil vom vertraglichen Anspruch zum Restanspruch. Szenarien müssen diese möglichen Pfade und die erforderliche zusätzliche Finanzierung erfassen.`)],C('Gleicher Kaufpreis, andere Recovery','Notleidender Nominalanspruch 100 wird für 40 gekauft. Rückfluss nach einem Jahr, keine Kosten oder Zwischenzahlungen.',['Recoverybetrag','Anleger-Haltedauerrendite'],[['20','−50 %'],['40','0 %'],['60','50 %']],'Recovery wird oft auf Nominal bezogen, die Anlegerrendite hier aber auf den Kaufpreis 40. Eine Recovery von 60 % kann daher eine Rendite von 50 % erzeugen. Zeitverzögerung und Verfahrenskosten würden den Ertrag reduzieren.'),[['bonds-10','Recoverybasis und Verlustquote definieren.'],['path-private-05','Strategierisiken nach Zahlungsrang vergleichen.']]),
D([S('Immobilienwert aus nachhaltigem Betriebsertrag',`NOI umfasst den operativen Immobilienertrag vor Finanzierung und typischerweise vor bestimmten Kapitalausgaben und Steuern. Die genaue Abgrenzung muss offengelegt werden. Ein Cap Rate kapitalisiert einen passenden stabilisierten NOI, ist aber keine vollständige mehrperiodige IRR.

Im vereinfachten stabilen Wachstumsmodell entspricht die Cap Rate dem Abstand zwischen geforderter Rendite und nachhaltigem Wachstum. Ein niedriger Satz kann daher geringeres Risiko oder höheres Wachstum ausdrücken. Veränderte Instandhaltung, Leerstand und Mietanpassungen erfordern häufig einen expliziten DCF.`,T`V=\frac{NOI_1}{c},\qquad c\approx k-g`),S('Leverage, Mietverträge und Ersatzinvestitionen',`Lange Mietverträge können Cashflow stabilisieren, aber auch unter Markt liegende Mieten festschreiben oder Mieterausfall konzentrieren. Indexierung überträgt Inflation nur nach Vertragsbedingungen. Leerstand und Neuvermietungskosten erzeugen nichtlineare Belastungen.

Fremdkapital verstärkt die Eigenkapitalwirkung von Wertänderungen. Gleichzeitig kann Refinanzierung zu einem ungünstigen Zeitpunkt erforderlich werden. REIT-Aktien besitzen zusätzlich Börsenliquidität und Unternehmensmerkmale; der Kurs muss deshalb nicht jederzeit exakt dem geschätzten Nettoimmobilienwert entsprechen.`)],C('Gleicher NOI, andere Kapitalisierungsrate','Nachhaltiger nächstjähriger NOI 100.000; Schulden konstant 1 Mio.',['Cap Rate','Immobilienwert','Eigenkapitalwert'],[['4 %','2,5 Mio.','1,5 Mio.'],['5 %','2,0 Mio.','1,0 Mio.'],['6 %','1,667 Mio.','0,667 Mio.']],'Der Anstieg von 5 % auf 6 % senkt den Immobilienwert um rund 16,7 %, den Eigenkapitalwert aber um rund 33,3 %. Gleicher laufender NOI schützt deshalb nicht vor Bewertungs- und Finanzierungsrisiko.'),[['equity-08','Wachstumsnenner und Bewertungsnichtlinearität.'],['bonds-08','Langfristige Cashflows reagieren auf Diskontsätze.']]),
D([S('Langfristige Anlagen sind nicht automatisch sichere Anlagen',`Infrastruktur kann vertraglich regulierte oder nutzungsabhängige Einnahmen besitzen. Bau-, Betriebs-, Nachfrage- und Regulierungsrisiko fallen zu unterschiedlichen Phasen an. Eine fertig betriebene Anlage mit gesicherten Zahlungen ist anders als ein Projekt mit ungewissem Fertigstellungstermin.

Land- und Forstwirtschaft verbinden biologische Produktion, Wetter, Rohstoffpreise und Bodenwert. Ernte- oder Einschlagsentscheidungen können Flexibilität erzeugen, sind aber durch Wachstum, Verderblichkeit und Regulierung begrenzt. Ein langes Anlageleben allein sagt wenig über jährliche Cashflowstabilität.`),S('Projektfinanzierung und Schuldendienstdeckung',`Projektfinanzierung stützt sich auf Cashflows eines abgegrenzten Projekts. Die Debt Service Coverage Ratio vergleicht für den Schuldendienst verfügbaren Cashflow mit Zins und Tilgung. Ein hoher Durchschnitt kann einzelne Unterdeckungsjahre verbergen.

Reservekonten, Covenants und Zahlungswasserfälle schützen Gläubiger, binden aber Liquidität für Eigentümer. Bei indexierten Einnahmen sind zeitliche Verzögerung und nicht gleich laufende Kosten wichtig. Eine nominale Inflationskopplung garantiert daher keine vollständige reale Absicherung.`,T`DSCR_t=\frac{CFADS_t}{I_t+Principal_t}`)],C('Gleicher Durchschnittscashflow, andere Jahresverteilung','Jährlicher Schuldendienst 80, zwei Jahre.',['Projekt','CFADS Jahr 1 / 2','DSCR Jahr 1 / 2'],[['A','100 / 100','1,25 / 1,25'],['B','60 / 140','0,75 / 1,75']],'Beide erzeugen insgesamt 200. B kann die erste Zahlung dennoch nicht aus dem laufenden Cashflow decken. Der Vergleich zeigt, warum Fälligkeiten und Reservekonten wichtiger sind als nur ein Durchschnittsertrag.'),[['advanced-03','Zeitliche Deckung von Verpflichtungen.'],['corporate-05','Bau- und Betriebsoptionen modellieren.']]),
D([S('Terminkurve aus Lager- und Verfügbarkeitsökonomie',`Rohstoffbesitz verursacht Finanzierung und Lagerkosten, kann aber einen Nutzen unmittelbarer Verfügbarkeit liefern. Dieser Convenience Yield kann besonders bei knappen Beständen steigen. Contango beschreibt höhere spätere Futurespreise, Backwardation niedrigere; daraus folgt allein noch keine sichere künftige Spotbewegung.

Eine Futuresanlage hält keine unverändert ewige Position. Vor Fälligkeit wird sie häufig in einen späteren Kontrakt gerollt. Ihre Rendite hängt von Preisänderung des gehaltenen Kontrakts, Rollvorgang und Verzinsung beziehungsweise Finanzierung der Sicherheiten ab. Die genaue Renditezerlegung ist methodenabhängig.`,T`F_0=S_0e^{(r+u-y)T}`),S('Rollrendite ohne mechanischen Sofortverlust verstehen',`Der Wechsel vom auslaufenden in einen teureren späteren Future ist nicht einfach der Kauf derselben Stückzahl eines physischen Gegenstands gegen sofortigen vollen Preis. Futures haben eigene Nominale und Marginbedingungen. Die ökonomische Belastung eines Contango zeigt sich in der Preisentwicklung der gehaltenen Kontrakte unter einem angenommenen unveränderten Kurvenverlauf.

Ein rollender Index kann negative Rollbeiträge haben, während der Spotpreis steigt. Umgekehrt garantiert Backwardation keinen positiven Gesamtertrag. Indexmethodik, Kontraktwahl und Besicherung entscheiden, welche Rohstoffexponierung tatsächlich entsteht.`)],C('Gleicher späterer Spotpreis, anderer anfänglicher Future','Ein Future konvergiert bis Fälligkeit auf Spot 100. Collateral-Ertrag und Kosten werden ausgeblendet.',['Anfänglicher Futurespreis','Preisänderung bis Fälligkeit','Änderung relativ zum Anfangsfuturespreis'],[['105','−5','−4,76 %'],['100','0','0 %'],['95','+5','5,26 %']],'Die Tabelle isoliert Konvergenz bei konstantem Endspot. Sie beschreibt keine garantierte Zukunft: Der tatsächliche Endspot kann abweichen. Die Prozentgröße ist eine Preisänderungsrelation und nicht automatisch die Rendite auf hinterlegte Margin.'),[['derivatives-02','Cost of Carry durch Replikation erklären.'],['derivatives-04','Futuresabrechnung und Margin verstehen.']]),
D([S('Strategien über Risikofaktoren statt Etiketten vergleichen',`Long-short Equity kann Aktienbeta, Branchenwetten und Titelauswahl kombinieren. Global Macro setzt auf makroökonomische Preise; Relative Value auf Preisrelationen; Event Driven auf konkrete Ereignisse. Der Name allein verrät weder Leverage noch Liquidität oder Tail-Risiko.

Ein scheinbar marktneutrales Portfolio kann in einer Krise gemeinsame Finanzierungs- oder Short-Volatilitätsrisiken tragen. Historische Regressionen auf gewöhnliche Aktien- und Anleihefaktoren erfassen solche nichtlinearen Exponierungen nur begrenzt. Szenario- und Positionsanalyse ergänzen die Renditehistorie.`,T`Net=\frac{L-S}{NAV},\quad Gross=\frac{L+S}{NAV}`),S('Leverage, Crowding und Rückgaben',`Hohe Bruttoexponierung kann bei geringer Nettoexponierung verbleiben. Dann wirken kleine relative Preisfehler auf große Positionen. Wenn viele Manager ähnliche Trades halten, können gemeinsame Rückgaben und Finanzierungsrestriktionen einen ungeordneten Abbau erzwingen.

Lock-ups und Gates geben dem Manager Zeit, verschieben aber Liquiditätsrisiko auf Anleger. Gebühren, High-Water Marks und Bewertungsverfahren beeinflussen Anreize. Eine gründliche Auswahl betrachtet deshalb Performance, Positionsmechanik und betriebliche Kontrollen gemeinsam.`)],C('Gleiches Nettoexposure, unterschiedlicher Bruttohebel','NAV 100. Long- und Shortbestände nach Marktwert.',['Portfolio','Long','Short','Netto','Brutto'],[['A','100','100','0 %','200 %'],['B','300','300','0 %','600 %']],'Beide sind nominal netto null. Bei einem relativen Verlust von 1 % auf beiden Seiten kann B dreimal so viel verlieren wie A. Nettoneutralität ist daher keine hinreichende Risikobeschreibung.'),[['portfolio-05','Lineare Faktoren und Restexponierung prüfen.'],['bonds-12','Finanzierungsstress bei gehebelten Positionen.']]),
D([S('Token, Anspruch und technische Übertragung',`Ein Token kann einen Zahlungsanspruch, Nutzungsrecht, Governance-Recht oder keinen einklagbaren Cashflowanspruch darstellen. Die technische Übertragbarkeit sagt noch nicht, welche rechtlichen und wirtschaftlichen Rechte erworben werden. Tokenisierung eines Vermögenswerts verändert dessen Risikoeigenschaften nicht automatisch.

Verwahrung, Schlüsselkontrolle, Smart-Contract-Logik und Abwicklungsmechanismus erzeugen eigene operative Risiken. Ein dezentral wirkendes Frontend kann von zentralen Preisfeeds, Administratorrechten oder Dienstleistern abhängen. Die Analyse verfolgt deshalb, wer in welchem Fehlerfall tatsächlich Kontrolle und Haftung besitzt.`),S('Bewertung und Renditequellen offenlegen',`Bei einem echten Cashflowanspruch können bekannte Bewertungsmethoden nach Prüfung der Durchsetzbarkeit verwendet werden. Bei nicht ausschüttenden digitalen Gütern hängt der Wert stärker von Nutzung, Knappheit, erwarteter Nachfrage und Marktstruktur ab. Eine Kennzahl wie Marktkapitalisierung ist eine Mengen-Preis-Relation, kein Nachweis realisierbarer Liquidität.

Staking-, Lending- oder andere Renditeangaben können Tokeninflation, Kreditrisiko und Kursrisiko enthalten. Eine hohe nominale Tokenrendite ist nicht dasselbe wie reale Kaufkraftsteigerung. Regulierung und Produktbedingungen ändern sich; konkrete Anlagen müssen anhand aktueller Primärinformationen beurteilt werden.`)],C('Gleiche Tokenvergütung, anderer Preisverlauf','100 Token zu je 1 gekauft; nach einem Jahr 110 Token, keine Gebühren.',['Endpreis je Token','Endwert','Rendite in Geld'],[['1,00','110','10 %'],['0,80','88','−12 %'],['1,20','132','32 %']],'Die Tokenzahl steigt immer um 10 %. Die Anlegerrendite hängt zusätzlich vom Preisfaktor ab. Ein beworbener Tokenzins allein beschreibt deshalb nicht das wirtschaftliche Ergebnis.'),[['economics-10','Mehrere Renditefaktoren multiplikativ verbinden.'],['ethics-06','Rechte, Daten und Annahmen transparent kommunizieren.']]),
D([S('Diversifikation muss auf wirtschaftlichen Renditen beruhen',`Alternative Anlagen können andere Cashflowquellen und Risikotreiber ergänzen. Der Nutzen hängt jedoch von tatsächlicher Kovarianz, Kosten, Liquidität und bereits vorhandenen Exponierungen ab. Private Equity kann trotz privater Rechtsform viel Aktien- und Leverage-Risiko besitzen.

Bewertungsglättung kann Korrelation künstlich senken. Eine belastbare Analyse verwendet soweit möglich wirtschaftliche Exponierungen, zeitliche Anpassungen und Stressszenarien. Der historische niedrigste Korrelationswert ist keine verlässliche Allokationsregel.`,T`\sigma_P^2=w^2\sigma_A^2+(1-w)^2\sigma_B^2+2w(1-w)\rho\sigma_A\sigma_B`),S('Nachhaltigkeit, Illiquidität und Verpflichtungen',`Reale Anlagen können physischen Klima-, Übergangs- und Regulierungsrisiken ausgesetzt sein. Lange Bindung erschwert die Anpassung, kann aber zugleich langfristige operative Verbesserungen ermöglichen. Standort, Versicherung, Verträge und Kapitalbedarf bestimmen den konkreten Effekt.

Portfolioentscheidungen verbinden diese Risiken mit Verpflichtungen und Liquiditätsreserven. Ein attraktiver langfristiger Erwartungswert kann ungeeignet sein, wenn Abrufe oder Schäden kurzfristige Zahlungen erfordern. Die Bewertung muss daher sowohl Gesamtvermögen als auch den Zeitpunkt seiner Verfügbarkeit betrachten.`)],C('Gleiche Volatilität, unterschiedlicher tatsächlicher Gleichlauf','80 % traditionelle Anlage und 20 % Alternative, beide 20 % Volatilität.',['Korrelation','Portfoliovolatilität'],[['0','16,49 %'],['0,5','18,33 %'],['1','20 %']],'Bei hoher tatsächlicher Korrelation verschwindet der Diversifikationsvorteil, obwohl das Produkt weiterhin „alternativ“ heißt. Die Rechnung zeigt, warum eine wirtschaftliche Faktorprüfung wichtiger ist als die Zuordnung zu einer separaten Kategorie.'),[['alternatives-03','Geglättete Daten nicht mit geringem Risiko verwechseln.'],['advanced-05','Anlageklassen über gemeinsame Faktoren integrieren.']])
];
