const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Vertraglicher Cashflow und tatsächlich erwartete Zahlung',`Eine Anleihe definiert Nominalbetrag, Kupon, Termine, Rang und weitere Rechte. Ein fest vereinbarter Kupon ist nicht automatisch eine sichere tatsächliche Zahlung. Ausfall, Stundung, Währungsumrechnung und Kündigungsrechte können die realisierten Cashflows verändern. Bewertung beginnt daher mit dem Vertragsprofil und ergänzt danach Kredit- und Optionsrisiken.

Für eine reguläre Festzinsanleihe wird der jährliche Kuponsatz c auf m Zahlungen verteilt. Am Endtermin kommt der Nominalbetrag F hinzu. Unregelmäßige erste oder letzte Perioden, Tilgungspläne und Day-Count-Konventionen erfordern eine genauere Terminspezifikation.`,T`CF_k=\frac{cF}{m}+F\,\mathbf1_{\{k=n\}}`),S('Covenants verändern Handlungsmöglichkeiten',`Positive Covenants verlangen bestimmte Handlungen oder Informationen; negative begrenzen beispielsweise zusätzliche Verschuldung, Sicherheitenbestellung oder Ausschüttung. Sie können Gläubiger vor einer nachträglichen Risikoerhöhung schützen. Ihr Wert hängt von Definitionen, Schwellen, Ausnahmen und Durchsetzbarkeit ab.

Rang und Besicherung bestimmen die Verteilung im Stress, garantieren aber keine feste Recovery. Sicherheiten können gleichzeitig mit der Bonität an Wert verlieren. Zwei Anleihen desselben Emittenten können deshalb unterschiedliche erwartete Verluste und Liquidität besitzen.`)],C('Gleicher Emittent, andere Rangfolge','Im vereinfachten Liquidationsfall stehen 70 Vermögenswert einer Seniorforderung 60 und Juniorforderung 40 gegenüber; keine Kosten.',['Anspruch','Versprochen','Erhalten','Recovery'],[['Senior','60','60','100 %'],['Junior','40','10','25 %']],'Der Gesamtverlust beträgt 30, fällt aber vollständig beim Junioranspruch an. Ein identisches Emittentenrating allein erklärt daher nicht jeden Anleihepreis. Vertraglicher Rang und tatsächliche Sicherheiten müssen mitgelesen werden.'),[['bonds-10','Verlustquote aus Recovery ableiten.'],['corporate-01','Anspruchsstruktur und Anreize verstehen.']]),
D([S('Zinsnotierungen besitzen unterschiedliche Nenner',`Geldmarktinstrumente können als Diskontsatz auf Nominalwert oder als Rendite auf Kaufpreis notiert werden. Beide beziehen denselben Ertrag auf unterschiedliche Basen. Zusätzlich unterscheiden sich Jahreslängen und Aufzinsung. Ein numerischer Vergleich der veröffentlichten Sätze ohne Umrechnung kann deshalb falsch sein.

Beim einfachen Diskontinstrument wird der Abschlag auf den Nominalbetrag angewandt. Die tatsächliche Haltedauerrendite setzt dagegen Auszahlung minus Kaufpreis ins Verhältnis zum Kaufpreis. Eine jährliche Anlagerendite benötigt anschließend eine ausdrücklich gewählte Jahreskonvention.`,T`P=F\left(1-d\frac{D}{360}\right),\quad HPR=\frac{F-P}{P},\quad y_{365}=HPR\frac{365}{D}`),S('Emittententyp und Risikofreiheit',`Staats-, Kommunal-, Unternehmens- und supranationale Emittenten besitzen unterschiedliche Einnahmequellen, Rechtsstrukturen und Ausfallmechanismen. Eine Anleihe in eigener Währung kann andere Zahlungsrisiken haben als eine Fremdwährungsverbindlichkeit. „Staatlich“ bedeutet weder automatisch inflationssicher noch für jeden Anleger währungsrisikofrei.

Ein Benchmarkinstrument wird für eine bestimmte Währung, Laufzeit und Anwendung gewählt. Kreditrisiko, Sicherheitenfähigkeit, Marktliquidität und regulatorische Nachfrage können seine Rendite beeinflussen. Die Rolle als Referenzzins ist daher eine Modellkonvention mit wirtschaftlichem Hintergrund.`)],C('Gleicher Abschlag, unterschiedliche Renditebasis','Nominal 100, Laufzeit 180 Tage, Diskontsatz 4 % auf 360-Tage-Basis.',['Größe','Wert','Nenner'],[['Preis','98','100 × (1 − 0,04 × 0,5)'],['Haltedauerrendite','2,0408 %','Kaufpreis 98'],['Einfache Jahresrendite, 365 Tage','4,1383 %','HPR × 365 / 180']],'Die tatsächliche Rendite liegt über dem Diskontsatz, weil der Investor nur 98 einsetzt. Die weitere Abweichung entsteht aus der Jahreslänge. Beide Effekte müssen getrennt von ökonomischen Renditeunterschieden betrachtet werden.'),[['start-04','Basispunkte und Bezugsgrößen korrekt verwenden.'],['quant-01','Verzinsungskonventionen umrechnen.']]),
D([S('Clean Price und wirtschaftlicher Zahlungsbetrag',`Zwischen Kuponterminen hat der Verkäufer einen Teil der laufenden Kuponperiode gehalten. Stückzinsen ordnen diesen Anteil der nächsten Kuponzahlung wirtschaftlich zu. Der tatsächlich abgerechnete Full oder Dirty Price setzt sich aus Clean Price und Stückzinsen zusammen, sofern die konkrete Markt- und Ex-Kupon-Konvention so gilt.

Der Clean Price erleichtert Vergleiche über die Kuponperiode, weil der mechanische Stückzinsaufbau entfernt wird. Für Barwertrechnung, investiertes Vermögen und Zinsrisiko wird der volle Preis benötigt. Ein Kuponabschlag am Zahlungstag ist deshalb nicht automatisch ein ökonomischer Verlust.`,T`P_{dirty}=P_{clean}+AI,\qquad AI=\frac{cF}{m}\frac{d_{accrued}}{d_{period}}`),S('Zwischenperiodige Diskontierung und Tilgung',`Bei regelmäßigen Kupons und einem Restperiodenanteil w bis zum nächsten Termin werden die Exponenten entsprechend verschoben. Dabei ist die tatsächliche Day-Count-Regel zu verwenden. Eine schematische Halbjahresannahme reicht nicht für jedes Wertpapier oder jeden Abrechnungstag.

Bei amortisierenden Anleihen wird Nominal schon vor Endfälligkeit zurückgezahlt. Kupons beziehen sich dann häufig auf die verbleibende Restschuld. Endfälligkeit, durchschnittliche Tilgungszeit und Macaulay Duration sind deshalb verschiedene Größen. Der vollständige Zahlungsplan ist die gemeinsame Ausgangsbasis.`,T`P_{dirty}=\sum_{k=1}^{n}\frac{CF_k}{(1+y/m)^{k-1+w}}`)],C('Gleicher Clean Price, anderer Abrechnungstag','Nominal 100, jährlicher Kupon 6, vereinfachte lineare Stückzinskonvention; Clean Price konstant 100.',['Anteil seit letztem Kupon','Stückzinsen','Zahlungsbetrag'],[['0','0','100'],['1/2','3','103'],['3/4','4,5','104,5']],'Der höhere Rechnungsbetrag bedeutet im isolierten Vergleich keine gestiegene reine Kursnotierung. Er enthält den angesammelten Anteil am nächsten Kupon. Eine Renditeberechnung, die nur 100 als Einsatz verwendet und den vollen Kupon vereinnahmt, würde den Ertrag überschätzen.'),[['bonds-05','Full Price als Barwertbasis.'],['bonds-08','Duration mit vollständigen Cashflows berechnen.']]),
D([S('Emission, Preisfindung und Sekundärhandel',`Im Primärmarkt werden neue Ansprüche verteilt und Finanzierungskonditionen festgelegt. Im Sekundärmarkt wechseln bestehende Ansprüche den Eigentümer. Emissionsprämie, Auktionsergebnis und spätere Handelsrendite können sich unterscheiden, weil Nachfrage, Liquidität und Information variieren.

Viele Anleihemärkte sind durch Händlerintermediation geprägt. Ein veröffentlichter Preis kann indikativ, veraltet oder nur für eine kleine Menge handelbar sein. Für eine konkrete Transaktion zählen ausführbare Preise, Stückgröße, Abwicklung und der Zeitpunkt der Beobachtung.`),S('Liquiditätskosten von Kreditrisiko trennen',`Ein höherer Spread kann sowohl erwartete Kreditverluste als auch Liquiditäts- und Risikoprämien enthalten. Zwei ansonsten ähnliche Papiere können unterschiedliche Renditen haben, wenn eines leichter finanziert, als Sicherheit genutzt oder in großen Mengen verkauft werden kann.

Liquidität ist zustandsabhängig. Gerade bei gemeinsamen Verkaufswünschen können Markttiefe und Händlerkapazität sinken. Historische durchschnittliche Spreads unterschätzen dann mögliche Stresskosten. Für Portfolios sind deshalb geplante Verkäufe und mögliche Sicherheitenanforderungen gemeinsam zu betrachten.`,T`C_{round}\approx\frac{Ask-Bid}{Mid}`)],C('Gleicher Mittelpreis, andere Handelskosten','Beide Anleihen haben Mid 100; sofortiger Kauf zum Ask und Verkauf zum Bid, ohne sonstige Bewegung.',['Anleihe','Bid / Ask','Verlust pro 100 ungefähr'],[['Liquider','99,95 / 100,05','0,10'],['Illiquider','99,50 / 100,50','1,00']],'Der zehnmal größere Spread erzeugt höhere Kosten, obwohl der Mittelpreis identisch ist. Die relative Kostenformel verwendet Mid als Vergleichsbasis; eine exakte Rendite auf den Kaufbetrag hätte Ask im Nenner.'),[['portfolio-10','Rebalancing mit tatsächlichen Kosten beurteilen.'],['advanced-08','Liquidität unter Stress planen.']]),
D([S('Preis aus Diskontfaktoren, YTM als zusammenfassende Nullstelle',`Ein Zahlungsstrom wird grundsätzlich mit zu den Terminen und Risiken passenden Diskontfaktoren bewertet. Die Yield to Maturity ist dagegen der einheitliche Zinssatz, der genau denselben Preis für den gesamten vertraglichen Cashflowstrom reproduziert. Bei einer nicht flachen Zinskurve sind diese Begriffe nicht identisch.

Für positive feste Cashflows fällt der Preis mit der YTM. Das ermöglicht eine eindeutige Renditelösung im zulässigen Zinsbereich. Bei komplexen oder vorzeichenwechselnden Zahlungen sind die Bedingungen gesondert zu prüfen. Kupon und aktuelle Rendite sind ebenfalls andere Größen: Sie beschreiben weder sämtliche Zeitpunkte noch einen eventuellen Kursgewinn bis Rückzahlung.`,T`P=\sum_k CF_kDF(t_k)=\sum_{k=1}^{n}\frac{CF_k}{(1+y/m)^k},\qquad CY=\frac{cF}{P}`),S('Premium, Discount und Pull to Par',`Liegt der Kuponsatz über der zur gleichen Konvention passenden YTM, ist eine reguläre optionfreie Anleihe bei Bewertung am Kupontermin über pari. Unter sonst gleichen Bedingungen nähert sich ihr Preis mit kürzerer Restlaufzeit dem Rückzahlungsbetrag an. Dieser Pull to Par ist eine Zeitwirkung, kein zusätzlicher sicherer Ertrag unabhängig vom gezahlten Premium.

YTM entspricht nur unter passenden Bedingungen der tatsächlich realisierten zusammengesetzten Haltedauerrendite. Dazu gehören vertragsgemäße Zahlungen, Halten bis Fälligkeit und eine zur Rendite passende Wiederanlage der Zwischenzahlungen. Ein Zero Coupon benötigt keine Kuponwiederanlage; sein Kredit- und gegebenenfalls Währungsrisiko bleiben bestehen.`),S('Konventionen und Sensitivität',`Ein nominaler Jahreszins mit m Zahlungen ist durch m zu teilen und über m mal Laufzeit Perioden anzuwenden. Die effektive Jahresrendite ergibt sich durch Aufzinsung, nicht durch bloße Umbenennung. Ein Preisvergleich muss dieselbe Abrechnung und Cashflowkonvention verwenden.

Die Preisableitung nach YTM führt direkt zur Modified Duration. Damit ist die Renditeberechnung nicht isoliert: dieselbe Barwertfunktion liefert Preis, erste Ableitung als Zinsrisiko und zweite Ableitung als Konvexität.`,T`y_{eff}=(1+y/m)^m-1,\qquad D_{mod}=-\frac1P\frac{\partial P}{\partial y}`)],C('Gleicher Kupon und Nominalwert, unterschiedliche Marktrendite','Zweijährige Anleihe, Nominal 100, jährlicher Kupon 5, Bewertung am Kupontermin.',['YTM','Preis','Kupon / Preis'],[['3 %','103,83','4,82 %'],['5 %','100','5 %'],['7 %','96,38','5,19 %']],'Bei 7 % besteht der erwartete vertragliche Ertrag nicht nur aus dem Kupon, sondern auch aus dem Weg des unter pari liegenden Preises zur Rückzahlung. Die Current Yield von 5,19 % erfasst diesen Teil nicht. Die Werte ergeben sich aus 5/(1+y) plus 105/(1+y)².'),[['bonds-06','Diskontkurven statt einheitlicher Rendite.'],['bonds-08','Ableitungen derselben Preisfunktion verstehen.']]),
D([S('Diskontfaktoren sind die gemeinsame Sprache der Zinskurve',`Ein Diskontfaktor DF(t) ist der heutige Wert einer Einheit zum Zeitpunkt t unter der gewählten Kurve. Spotzinsen sind eine alternative Darstellung dieser Faktoren. Bei jährlicher Verzinsung entsteht der Faktor durch Potenzieren; bei stetiger durch eine Exponentialfunktion. Verschiedene Zinskonventionen können somit dieselbe Kurve beschreiben.

Ein Par-Kupon ist der Kupon, der einen Zahlungsstrom bei gegebenen Diskontfaktoren genau auf den Nominalwert bringt. Er ist ein gewichteter Zusammenhang mehrerer Laufzeiten, kein Spotzins allein am Endtermin.`,T`DF(t)=(1+s_t)^{-t}=e^{-r_tt},\quad c_{par}=\frac{1-DF(T)}{\sum_{k=1}^{n}\alpha_kDF(t_k)}`),S('Bootstrapping Schritt für Schritt',`Wenn frühere Diskontfaktoren bekannt sind, kann aus dem Preis eines Kuponinstruments der letzte unbekannte Faktor isoliert werden. Man zieht zunächst den Barwert früherer Zahlungen ab und teilt den verbleibenden Preis durch die letzte Zahlung. Danach wird der Spotzins aus dem Faktor zurückgerechnet.

Zwischen beobachteten Terminen benötigt man Interpolation. Die Wahl zwischen Zinsen, Faktoren oder Forwardraten beeinflusst glatte Ableitungen und Key-Rate-Risiken. In modernen besicherten Derivatemärkten können Diskontierung und Prognose variabler Zahlungen unterschiedliche Kurven verwenden; ein einzelner Schulbuchbaum ist dann eine vereinfachte Darstellung.`,T`DF(t_n)=\frac{P-\sum_{k=1}^{n-1}CF_kDF(t_k)}{CF_n}`),S('Forwardraten durch Replikation verbinden',`Eine Anlage bis T und eine Anlage bis t mit anschließend gesichertem Anschlusszins müssen ohne Friktionen denselben Endwert ergeben. Daraus folgt die Forwardbeziehung als Quotient von Diskontfaktoren. Die Forwardrate ist eine heute festgelegte Tauschkondition, nicht automatisch die unverzerrte Erwartung des späteren Spotzinses.

Auf- und absteigende Kurven können erwartete Zinspfade und Prämien kombinieren. Erst die Trennung von mathematischer Arbitragebeziehung und ökonomischer Erwartung verhindert, dass eine Kurvenrechnung als sichere Prognose missverstanden wird.`,T`(1+f_{t,T})^{T-t}=\frac{DF(t)}{DF(T)}=\frac{(1+s_T)^T}{(1+s_t)^t}`)],C('Spot-, Par- und Forwardzins an derselben Kurve','Einjähriger Spotzins 4 %, zweijähriger 5 %, jährliche Verzinsung.',['Größe','Berechnung','Wert'],[['DF(1)','1 / 1,04','0,961538'],['DF(2)','1 / 1,05²','0,907029'],['Einjahresforward ab Jahr 1','1,05² / 1,04 − 1','6,0096 %'],['Zweijähriger Par-Kupon','(1 − DF(2)) / (DF(1) + DF(2))','4,9755 %']],'Der Par-Kupon liegt nahe, aber nicht genau bei 5 %, weil der erste Kupon mit dem einjährigen Faktor bewertet wird. Die Forwardrate liegt höher, damit die Kombination aus 4 % im ersten und rund 6,01 % im zweiten Jahr denselben Zweijahresfaktor erzeugt.'),[['economics-11','Devisenforwards ebenfalls durch Anlagewege herleiten.'],['derivatives-05','Swap-Festsatz aus Diskontfaktoren bestimmen.']]),
D([S('Zinsstrukturtheorien erklären verschiedene Komponenten',`Die reine Erwartungshypothese verbindet längere Zinsen mit erwarteten kurzfristigen Sätzen. Liquiditäts- beziehungsweise Laufzeitprämien ergänzen eine Entschädigung für Risiken längerer Bindung. Preferred Habitat und Marktsegmentierung betonen unterschiedliche Laufzeitnachfrage und beschränkte Substitution.

Diese Erklärungen schließen sich empirisch nicht vollständig aus. Eine beobachtete steile Kurve kann sowohl höhere erwartete Kurzfristzinsen als auch größere Laufzeitprämien enthalten. Die Kurvenform allein identifiziert die Anteile nicht. Für Anlageentscheidungen ist wichtig, welcher Anteil sich im eigenen Szenario verändern soll.`),S('Zinsmodelle und ihre Zustandsvariablen',`Ein Kurzfristzinsmodell beschreibt die Dynamik des momentanen Zinses. Im Vasicek-Modell zieht Mean Reversion den Zins zum langfristigen Niveau, während ein normalverteilter Schock negative Zinsen zulässt. Das CIR-Modell skaliert die Schockstärke mit der Quadratwurzel des Zinses und besitzt unter geeigneten Bedingungen andere Randbedingungen.

Kalibrierung passt Modellpreise an beobachtete Instrumente an. Sie beweist nicht, dass die geschätzten Parameter den tatsächlichen künftigen Prozess darstellen. Historische Dynamik und risikoneutrale Bewertungsdynamik können sich durch Risikoprämien unterscheiden. Das ist besonders bei Optionsbewertung entscheidend.`,T`dr_t=a(b-r_t)dt+\sigma dW_t,\qquad dr_t=a(b-r_t)dt+\sigma\sqrt{r_t}\,dW_t`)],C('Gleicher langer Zins, andere Zusammensetzung','Eine vereinfachte langfristige Rendite beträgt in beiden Fällen 5 %.',['Szenario','Durchschnitt erwarteter Kurzfristzinsen','Laufzeitprämie'],[['A','4 %','1 %'],['B','3 %','2 %']],'Die identische Rendite kann unterschiedliche politische Erwartungen enthalten. Wer aus 5 % unmittelbar einen künftigen Leitzins ableitet, übersieht diese Identifikationsfrage. Die additive Darstellung ist eine ökonomische Näherung, keine exakte Zerlegung jeder beobachteten Kuponrendite.'),[['economics-07','Geldpolitik und Erwartungskanal.'],['bonds-15','Zinsmodelle für eingebettete Optionen nutzen.']]),
require('./duration.cjs'),
D([S('Haltedauerrendite aus Vermögen am Horizont',`Für einen Verkauf vor Fälligkeit zählen Verkaufspreis, erhaltene Kupons und deren Wiederanlage. Der Preis am Horizont hängt von Restlaufzeit und dann geltender Kurve ab. Die anfängliche YTM allein bestimmt diese Größen nicht.

Ein höherer Zins senkt zunächst den Marktpreis, erhöht aber die Wiederanlageerträge späterer Kupons. Welche Wirkung überwiegt, hängt vom Anlagehorizont ab. Diese Gegenläufigkeit führt zur Duration-Immunisierung, deren Annahmen im Duration-Kapitel hergeleitet werden.`,T`W_H=P_H+\sum_{t_k\le H}CF_k(1+r_{re})^{H-t_k},\quad R_H=\frac{W_H}{P_0}-1`),S('Carry, Roll-down und Kurvenänderung',`Carry bezeichnet den Ertrag aus Halten unter einer gewählten Konvention, etwa Kupon und Finanzierungskosten. Roll-down beschreibt die Preiswirkung, wenn ein Papier entlang einer unveränderten Kurve eine kürzere Laufzeit erreicht. Eine separate Kurvenänderung verändert den Preis zusätzlich.

Diese Zerlegung ist von Definition und Szenario abhängig. Eine heute steile Kurve garantiert keinen Roll-down-Gewinn, wenn sie sich anschließend ungünstig verschiebt. Kreditspread, Ausfall, Finanzierung und Transaktionskosten können das Gesamtergebnis weiter verändern. Einzelne Renditekomponenten dürfen nicht doppelt gezählt werden.`)],C('Gleiche Anfangsanleihe, andere Rendite beim Verkauf','Zweijähriger 5-%-Bond zu 100 gekauft. Verkauf direkt nach dem ersten Kupon; verbleibende Zahlung 105 in einem Jahr.',['YTM beim Verkauf','Verkaufspreis','Kupon','Einjahresrendite'],[['3 %','101,94','5','6,94 %'],['5 %','100','5','5 %'],['7 %','98,13','5','3,13 %']],'Der Kupon bleibt immer 5. Die unterschiedliche Gesamtrendite entsteht aus dem Verkaufspreis 105/(1+y). Wer nur auf den Kupon schaut, übersieht hier den gesamten Szenariounterschied.'),[['bonds-08','Horizontrisiko und Duration verbinden.'],['path-portfolio-02','Carry, Kurve und Spread aktiv steuern.']]),
D([S('Erwarteten Verlust aus bedingten Größen',`PD ist die Wahrscheinlichkeit eines Ausfalls über einen definierten Horizont. LGD ist der Verlustanteil unter der Bedingung des Ausfalls, EAD die Exponierung im Ausfallzeitpunkt. Bei festen oder passend bedingten Größen entsteht die bekannte Produktform. Sind EAD und Verlustquote stochastisch abhängig, muss der bedingte Produkterwartungswert verwendet werden.

Recovery und LGD ergänzen sich nur bei identischer Bezugsbasis und Kostenabgrenzung zu eins. Marktpreis-Recovery, Nominal-Recovery und Barwertverlust können unterschiedliche Zahlen liefern. Ein pauschaler Vergleich ohne Definition ist deshalb problematisch.`,T`EL=P(D)E[EAD\cdot LGD\mid D],\quad EL=PD\cdot EAD\cdot LGD,\quad LGD=1-RR`),S('Hazardrate und kumulierte Ausfallwahrscheinlichkeit',`Eine konstante kontinuierliche Hazardrate λ beschreibt die bedingte Ausfallintensität bei bisherigem Überleben. Die Überlebenswahrscheinlichkeit fällt exponentiell; kumulierte PD ist eins minus Überleben. Jährliche PD und Hazardrate sind daher nicht exakt gleich, auch wenn sie für kleine Werte nahe beieinanderliegen.

Historische Ausfallwahrscheinlichkeiten sind reale Häufigkeitsannahmen. Aus Marktpreisen abgeleitete risikoneutrale Größen enthalten eine Risikobewertung und sind nicht unmittelbar dieselbe Prognose. Für Preisbildung und Kreditbudget müssen diese Rollen getrennt werden.`,T`Q(T)=e^{-\lambda T},\qquad PD(0,T)=1-e^{-\lambda T},\qquad \lambda=-\frac{\ln(1-PD)}{T}`)],C('Gleicher erwarteter Verlust, andere Verlustverteilung','EAD 100, zwei vereinfachte einjährige Kredite.',['Kredit','PD','LGD','Erwarteter Verlust','Verlust bei Ausfall'],[['A','2 %','50 %','1','50'],['B','10 %','10 %','1','10']],'Der Durchschnittsverlust ist gleich, aber A hat seltenere und schwerere Verluste. Kapitalbedarf, Konzentrationsrisiko und Tail-Risiko können deshalb verschieden sein. EL allein beschreibt nicht die gesamte Verlustverteilung.'),[['portfolio-12','Erwartungswert und Extremverlust unterscheiden.'],['derivatives-11','Ausfallintensität in CDS-Bewertung verwenden.']]),
D([S('Bonität aus Zahlungsfähigkeit und Finanzierungsstruktur',`Kreditanalyse untersucht, ob operative Mittel, verfügbare Liquidität und Refinanzierung die fälligen Verpflichtungen decken. Verschuldungsquoten, Zinsdeckung und Fälligkeitsprofil ergänzen sich. Ein Unternehmen kann bilanziell solvent sein und dennoch durch kurzfristige Zahlungsunfähigkeit in Schwierigkeiten geraten.

Ratings verdichten Informationen nach einer Methodik und können verzögert reagieren. Migration in schlechtere Kategorien kann bereits vor einem Ausfall den Marktwert senken oder Mandatsgrenzen auslösen. Kreditrisiko besteht daher nicht nur aus dem Endereignis Ausfall.`),S('Spread ist mehr als erwarteter Verlust',`Im vereinfachten kontinuierlichen Modell wird ein Kreditspread häufig durch Hazardrate mal Verlustquote angenähert. Tatsächliche Spreads enthalten zusätzlich Prämien für Risiko, Liquidität, Unsicherheit und andere Markteffekte. Der relevante Referenzzins und eingebettete Optionen müssen ebenfalls berücksichtigt werden.

Spread Duration misst die Preisempfindlichkeit gegenüber einer Spreadänderung bei festgehaltener Basiskurve. Zinsduration und Spread Duration können ähnlich sein, beziehen sich aber auf unterschiedliche Risikotreiber. In Stressphasen können steigende Spreads und fallende Staatszinsen teilweise gegeneinander wirken.`,T`s\approx\lambda LGD,\qquad \frac{\Delta P}{P}\approx-D_s\Delta s`)],C('Gleicher Spread, andere implizite Intensität','Spread 1,2 %, vereinfachtes Modell s ≈ λ × LGD; weitere Prämien werden ausgeblendet.',['LGD','Implizite Hazardrate ungefähr'],[['60 %','2 %'],['40 %','3 %'],['20 %','6 %']],'Eine höhere angenommene Recovery erfordert für denselben Spread eine höhere implizite Ausfallintensität. Marktpreise identifizieren PD und LGD also nicht ohne zusätzliche Annahmen getrennt. Die errechneten Größen sind unter diesen Annahmen Preisparameter, keine direkt beobachteten realen Ausfallhäufigkeiten.'),[['bonds-10','PD, Hazardrate und LGD unterscheiden.'],['bonds-15','Optionskomponenten aus Spreads herauslösen.']]),
D([S('Repo als besicherte Finanzierung',`Ein Repo verbindet den Verkauf eines Wertpapiers mit einem vereinbarten Rückkauf. Wirtschaftlich dient es häufig als besicherte Geldaufnahme. Repozins, Laufzeit, Sicherheitenbewertung und Haircut bestimmen die Finanzierung. Eigentums- und Rechtsdetails sind vertragsspezifisch und können für Insolvenzfolgen relevant sein.

Der Haircut lässt den verliehenen Cashbetrag unter dem Sicherheitenwert liegen. Er schützt gegen Preisänderungen und Verwertungskosten, beseitigt aber weder Gegenparteirisiko noch Liquiditätsbedarf bei Nachschussforderungen. Fällt der Sicherheitenwert oder steigt der Haircut, muss der Kreditnehmer zusätzliche Mittel oder Sicherheiten bereitstellen.`,T`L=(1-h)V_C,\qquad P_{rep}=L\left(1+r_{repo}\frac{D}{B}\right)`),S('Finanzierungshebel und Liquiditätsspirale',`Wer einen Vermögenswert mit Repo finanziert, setzt zunächst ungefähr den Haircut als Eigenmittel ein. Kleine Preisverluste können dann relativ zu diesem Eigenmitteleinsatz groß sein. Der tatsächliche Leverage hängt zusätzlich von weiteren Sicherheiten und Vertragsbedingungen ab.

In Stressphasen können Preise fallen, Haircuts steigen und Finanzierung gleichzeitig knapper werden. Erzwungene Verkäufe können weitere Preisrückgänge auslösen. Eine vermeintlich marktneutrale Relative-Value-Position kann dadurch an Finanzierung scheitern, bevor eine erwartete Konvergenz eintritt.`,T`\frac{V_C}{E}\approx\frac1h`)],C('Gleiche Sicherheit, steigender Haircut','Sicherheitenwert bleibt 100; Haircut steigt ohne Preisänderung.',['Haircut','Maximale Cashfinanzierung','Erforderliche Eigenmittel'],[['2 %','98','2'],['5 %','95','5'],['10 %','90','10']],'Der Wechsel von 2 % auf 10 % erfordert 8 zusätzliche Mittel pro 100 Sicherheit, selbst bei unverändertem Marktpreis. Ein reiner Marktpreis-Stresstest würde diesen Finanzierungsbedarf übersehen.'),[['advanced-08','Nachschussbedarf in Liquiditätsplanung aufnehmen.'],['derivatives-01','Sicherheiten und Gegenparteirisiko verbinden.']]),
D([S('Pooling verteilt Cashflows, beseitigt kein Gesamtrisiko',`Bei einer Verbriefung werden Forderungen gebündelt und Zahlungsansprüche auf den Pool strukturiert. Diversifikation kann idiosynkratische Ausfälle glätten; gemeinsame wirtschaftliche Risiken bleiben. Die rechtliche Abgrenzung und tatsächliche Übertragung der Forderungen beeinflussen, welche Ansprüche Anleger besitzen.

Tranchen erhalten unterschiedliche Prioritäten im Zahlungswasserfall. Juniorpositionen absorbieren Verluste zuerst und schützen dadurch Seniorpositionen bis zu einem Schwellenwert. Die Gesamtverluste des Pools verschwinden dabei nicht, sondern werden anders verteilt.`,T`L_{[a,d]}=\frac{\min(\max(L-a,0),d-a)}{d-a}`),S('Attachment, Detachment und Korrelation',`In der Formel sind a und d die Verlustschwellen der Tranche als Anteile des ursprünglichen Pools, L der Poolverlust. Durch Division durch die Tranchengröße entsteht deren relative Verlustquote. Unterschiedliche Nenner erklären, warum ein kleiner Poolverlust eine Juniortranche vollständig auslöschen kann.

Höhere Ausfallkorrelation erhöht die Wahrscheinlichkeit gemeinsamer schwerer Poolverluste und verändert Tranchenwerte unterschiedlich. Ein unveränderter erwarteter Poolverlust garantiert deshalb keine unveränderte Seniorrisikoverteilung. Vorzeitige Tilgungen, Servicingkosten und Trigger beeinflussen zusätzlich den zeitlichen Zahlungswasserfall.`)],C('Gleicher Pool, unterschiedliche Verlustschichten','Pool 100, Equitytranche 0–10, Mezzanine 10–20, Senior 20–100; nur Kapitalverluste.',['Poolverlust','Equityverlustquote','Mezzanineverlustquote','Seniorverlustquote'],[['5','50 %','0 %','0 %'],['15','100 %','50 %','0 %'],['30','100 %','100 %','12,5 %']],'Bei Poolverlust 30 entfallen 10 auf Senior. Bezogen auf deren ursprüngliche Größe 80 sind das 12,5 %. Die Tabelle zeigt, warum Poolverlust und Trancheverlust nicht dieselbe Prozentzahl sind.'),[['bonds-10','Einzelkreditverluste als Ausgangspunkt.'],['portfolio-01','Abhängigkeit bestimmt Diversifikationswirkung.']]),
D([S('Vorzeitige Tilgung verändert den Cashflow selbst',`Bei vielen Hypotheken können Schuldner früher zurückzahlen. Fallende Zinsen machen Refinanzierung attraktiver, sodass Anleger gerade dann Kapital zurückerhalten, wenn neue Anlagen weniger verzinsen. Steigende Zinsen können Tilgungen verlangsamen und Kapital länger binden. Kontraktion und Extension sind daher zwei Seiten desselben Schuldnerrechts.

CPR ist eine annualisierte bedingte Tilgungsrate; SMM die entsprechende monatliche Rate. Die Umrechnung erfolgt über Überlebensfaktoren. Vorzeitige Tilgung wird typischerweise auf den nach planmäßiger Tilgung verbleibenden relevanten Bestand angewendet, nicht beliebig auf den ursprünglichen Nominalwert.`,T`SMM=1-(1-CPR)^{1/12},\qquad CPR=1-(1-SMM)^{12}`),S('Negative Konvexität und effektive Risikomaße',`Bei einer gewöhnlichen optionfreien Anleihe steigen Preise bei fallenden Renditen konvex. Eine kündbare Struktur begrenzt diesen Anstieg, weil der Schuldner die günstige Finanzierung ersetzt. Dadurch kann die lokale Preiskrümmung negativ werden. Die Duration ist dann selbst stark zustandsabhängig.

Effektive Duration bewertet den gesamten Cashflowmechanismus bei höherer und niedrigerer Kurve neu. Eine Ableitung mit unveränderten vertraglichen Cashflows würde das Tilgungsrecht übersehen. Modelle benötigen Annahmen über Zinsen, Refinanzierungsanreize, Saisonalität und Schuldnerverhalten; historische Tilgung ist keine vollständige Prognose.`,T`D_{eff}=\frac{P_- -P_+}{2P_0\Delta r},\qquad C_{eff}=\frac{P_-+P_+-2P_0}{P_0(\Delta r)^2}`)],C('Gleiche Ausgangsposition, asymmetrische Preisreaktion','Illustrative neu bewertete Preise einer optionalen Struktur: P0 = 100, parallele Schocks von ±1 %.',['Szenario','Preis','Preisänderung'],[['Zins −1 %','103','+3 %'],['Unverändert','100','0'],['Zins +1 %','95','−5 %']],'Die symmetrische Duration beträgt (103 − 95)/(2 × 100 × 0,01) = 4. Die Konvexität ist (103 + 95 − 200)/(100 × 0,01²) = −200. Der begrenzte Aufwärtsgewinn und größere Abwärtsverlust erzeugen die negative Krümmung; die Preise sind illustrative Modelleingaben, keine universellen MBS-Werte.'),[['bonds-08','Yield- und effektive Duration sorgfältig unterscheiden.'],['bonds-15','Schuldneroption getrennt bewerten.']]),
D([S('Optionfreie Anleihe und eingebettetes Recht zerlegen',`Eine kündbare Anleihe entspricht aus Anlegersicht einer optionfreien Anleihe abzüglich einer dem Emittenten eingeräumten Call-Option. Eine kündbare Struktur ist daher unter sonst gleichen Bedingungen weniger wert. Eine Put-Option des Anlegers erhöht dagegen dessen Wert.

Diese Zerlegung erklärt die Wirkung von Volatilität: Ein wertvolleres Emittentenkündigungsrecht belastet den Anlegerpreis. Bei einem Zinsbaum wird an jedem möglichen Kündigungstermin der Fortführungswert mit dem zulässigen Kündigungspreis verglichen. Die Entscheidung verändert frühere Werte durch Rückwärtsrechnung.`,T`P_{callable}=P_{straight}-C_{issuer},\quad P_{putable}=P_{straight}+P_{investor}`),S('Z-Spread und OAS beantworten verschiedene Fragen',`Ein Z-Spread ist ein konstanter Aufschlag auf eine gewählte Spotkurve, der bei fest angenommenen Cashflows den Marktpreis reproduziert. Ein OAS wird innerhalb eines Modells bestimmt, das zinsabhängige Optionsausübung und veränderliche Cashflows berücksichtigt. Er soll die modellierte Optionskomponente aus der Spreadinterpretation herauslösen.

Die Differenz wird häufig als modellabhängige Optionskosten interpretiert. Ein OAS ist jedoch kein beobachtbarer reiner Kreditverlustaufschlag: Referenzkurve, Volatilität, Tilgungsmodell, Liquidität und weitere Annahmen beeinflussen ihn. Eine andere Modellkalibrierung kann bei gleichem Marktpreis einen anderen OAS ergeben.`,T`P_{mkt}=E^{Q}\!\left[\sum_t CF_t(\omega)\exp\!\left(-\int_0^t[r_u(\omega)+s]du\right)\right]`)],C('Gleiche optionfreie Basis, andere Optionskosten','Optionfreie Anleihe 105; die Emittentenoption wird unter zwei Volatilitätsannahmen bewertet.',['Optionswert','Wert kündbarer Anleihe'],[['2','103'],['6','99']],'Der Unterschied entsteht vollständig aus dem abgegebenen Recht. Bei gleichem Marktpreis müsste ein Bewertungsmodell seine übrige Spreadkomponente entsprechend anpassen. Deshalb sind OAS-Vergleiche nur mit bekannten Modellannahmen sinnvoll.'),[['derivatives-07','Rückwärtsbewertung und Ausübungsentscheidung.'],['bonds-14','Vorzeitige Tilgung erzeugt negative Konvexität.']])
];
