const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Ansprüche, Kontrolle und Haftung',`Eine Unternehmensform verteilt Zahlungsansprüche, Entscheidungsrechte und Haftung. Eigenkapital erhält grundsätzlich den verbleibenden Wert nach vorrangigen Ansprüchen; Gläubiger besitzen vertragliche Ansprüche und gegebenenfalls Sicherheiten oder Covenants. Stimmrechte und wirtschaftliche Beteiligung müssen nicht proportional sein, etwa bei mehreren Aktienklassen.

In einem vereinfachten Endzeitpunktmodell mit begrenzter Haftung erhält Eigenkapital den positiven Rest nach Rückzahlung einer einzigen Schuld. Diese Auszahlungsform ähnelt einer Kaufoption auf das Unternehmensvermögen. Sie erklärt den Anreiz zu riskanteren Projekten bei hoher Verschuldung, ist aber keine allgemeine Formel für den heutigen Buchwert des Eigenkapitals.`,T`E_T=\max(A_T-D,0),\qquad B_T=\min(A_T,D),\qquad A_T=E_T+B_T`),S('Stakeholderbeziehungen beeinflussen den Gesamtwert',`Arbeitnehmer, Lieferanten, Kunden und Staat besitzen weitere wirtschaftliche oder rechtliche Beziehungen zum Unternehmen. Langfristige Wertschaffung hängt auch davon ab, ob diese Beziehungen tragfähig bleiben. Kurzfristige Einsparungen können spätere Qualitäts-, Personal- oder Finanzierungsprobleme auslösen.

Ein Interessenkonflikt zwischen Eigen- und Fremdkapital wird besonders sichtbar, wenn Eigentümer zusätzliche Chancen erhalten, einen Teil der Verluste aber Gläubiger tragen. Covenants, Sicherheiten und Beteiligungsrechte versuchen diese Anreize zu begrenzen. Ihr Nutzen ist gegen Kosten eingeschränkter unternehmerischer Flexibilität abzuwägen.`)],C('Gleicher Erwartungswert, andere Risikoverteilung','Schuldversprechen 80. Projekt A zahlt sicher 100; B zahlt mit je 50 % 50 oder 150.',['Projekt','Erwarteter Gesamtwert','Erwartete Gläubigerzahlung','Erwartete Eigenkapitalzahlung'],[['A','100','80','20'],['B','100','65','35']],'Das riskantere Projekt erhöht den erwarteten Eigentümerrest um 15 und senkt den Gläubigerwert um 15. Es schafft in dieser undiskontierten Darstellung keinen zusätzlichen Gesamtwert. Die Rechnung illustriert Risikoabwälzung; eine vollständige heutige Bewertung benötigt zustandsabhängige Preise.'),[['bonds-10','Gläubigerverluste im schlechten Zustand.'],['derivatives-06','Asymmetrische Auszahlungen verstehen.']]),
D([S('Principal-Agent-Probleme besitzen unterschiedliche Richtungen',`Beim Konflikt zwischen Eigentümern und Management kann das Management private Vorteile, Größe oder Arbeitsplatzsicherheit höher gewichten als den Unternehmenswert. Zwischen kontrollierenden und kleinen Aktionären drohen andere Mechanismen, etwa Transaktionen mit nahestehenden Parteien. Ein unabhängiger Aufsichtsprozess muss deshalb zum konkreten Konflikt passen.

Vergütung soll Handlungen an den Unternehmenszielen ausrichten. Eine Kennzahl allein kann jedoch Ausweichverhalten erzeugen: Umsatzboni belohnen möglicherweise unprofitables Wachstum; EPS-Ziele können Rückkäufe fördern, obwohl Investitionen wertvoller wären. Messgröße, Zeithorizont, Risikokorrektur und Rückforderungsregeln bestimmen gemeinsam den Anreiz.`),S('Kontrolle und Entscheidungsfähigkeit ausbalancieren',`Governance verteilt Vorschlags-, Entscheidungs-, Überwachungs- und Informationsrechte. Unabhängigkeit von Kontrollgremien ist hilfreich, ersetzt aber weder Fachkenntnis noch ausreichende Informationen. Eine formell unabhängige Person kann eine komplexe Transaktion ohne geeignete Daten kaum beurteilen.

Für Anleger ist entscheidend, wie Governance über Kapitalallokation, Finanzierungskosten und Minderheitenschutz auf den Wert wirkt. Eine gute Struktur garantiert keine erfolgreiche Strategie, kann aber opportunistische Entscheidungen erschweren und Fehler früher sichtbar machen. Die Analyse verbindet Regeln mit tatsächlichen Entscheidungen und deren dokumentierten Begründungen.`)],C('Gleicher Zusatzumsatz, andere Vergütungsbasis','Ein Auftrag erhöht Umsatz um 100, benötigt aber 110 zusätzliche wirtschaftliche Kosten.',['Bonuskriterium','Gemessener Erfolg','Anreiz'],[['Umsatzwachstum','+100','Auftrag attraktiv trotz Wertverlust'],['Ökonomischer Ergebnisbeitrag','−10','Auftrag nur mit anderer strategischer Begründung']],'Die Differenz entsteht durch die Zielgröße. Ein umsatzbasierter Bonus ist nicht in jedem Kontext falsch, muss aber mit Kosten, Risiko und langfristiger Qualität abgestimmt werden. Sonst belohnt die Organisation systematisch die falsche Entscheidung.'),[['corporate-04','Wertschaffung mit NPV beurteilen.'],['ethics-07','Vergütungsanreize und Interessenkonflikte behandeln.']]),
D([S('Geschäftsmodell in Ertrags- und Kapitaltreiber zerlegen',`Ein Geschäftsmodell erklärt, wer für welchen Nutzen bezahlt, welche Ressourcen dafür nötig sind und warum der Ertrag gegen Wettbewerb bestehen kann. Umsatz wird durch Menge und Preis zerlegt, operative Marge durch Kostenstruktur, Kapitalbedarf durch Anlagen und Working Capital. Erst diese Verbindung zeigt, ob Wachstum freien Cashflow erzeugt.

ROIC setzt operativen Nachsteuergewinn in Beziehung zum eingesetzten operativen Kapital. Ein Geschäft schafft durch zusätzliches Kapital nur dann Wert, wenn dessen inkrementelle Rendite die relevanten Kapitalkosten übersteigt. Hohe historische Durchschnittsrendite garantiert nicht dieselbe Rendite für das nächste Projekt.`,T`ROIC=\frac{NOPAT}{IC},\qquad EP=NOPAT-WACC\cdot IC`),S('Risikotreiber und strategische Optionen',`Operative Risiken betreffen Absatz, Preise, Kosten, Kapazität und Ausführung. Finanzielle Risiken entstehen zusätzlich aus Verschuldung, Fälligkeiten und Währungen. Ein Unternehmen kann ein stabiles Produkt verkaufen und dennoch durch eine kurzfristige Refinanzierungskonzentration fragil werden.

Strategische Flexibilität kann diese Risiken verändern: variable statt fixe Kosten, mehrere Lieferanten oder gestufte Investitionen reduzieren bestimmte Verluste, kosten aber möglicherweise Marge. Die Analyse fragt deshalb nach dem Preis der Resilienz und den Zuständen, in denen sie sich auszahlt. Ein einzelnes Basisszenario zeigt diese Abwägung nicht.`)],C('Gleicher operativer Gewinn, anderer Kapitaleinsatz','NOPAT = 20 und WACC = 10 %.',['Operatives Kapital','ROIC','Ökonomischer Gewinn'],[['100','20 %','10'],['200','10 %','0'],['300','6,67 %','−10']],'Der ausgewiesene operative Gewinn bleibt positiv. Mit höherem Kapitalbedarf reicht er dennoch nicht mehr zur geforderten Vergütung des Kapitals. Gewinnwachstum und Wertschaffung sind deshalb nur bei Berücksichtigung des zusätzlich eingesetzten Kapitals vergleichbar.'),[['equity-05','Wachstum aus Reinvestition und Rendite ableiten.'],['corporate-05','Flexibilität als reale Option modellieren.']]),
D([S('Kapitalwert aus dem Vermögensvergleich herleiten',`Der Kapitalwert vergleicht die heutige Investition mit dem Barwert ihrer zusätzlichen künftigen Cashflows. Ein positiver NPV bedeutet, dass das Projekt nach Vergütung des passend gemessenen Risikos mehr Wert liefert als es kostet. Relevant sind inkrementelle Zahlungen einschließlich Opportunitätskosten und Folgewirkungen; bereits unwiederbringlich angefallene Kosten ändern die heutige Wahl nicht.

Steuern, Working Capital und Veräußerungswerte gehören auf den Zeitstrahl. Abschreibung wirkt über Steuern, nicht als erneute Auszahlung. Nominale Cashflows werden nominal, reale real diskontiert. Finanzierungscashflows werden nicht zusätzlich in FCFF abgezogen, wenn ihre Wirkung bereits über einen konsistenten WACC erfasst wird.`,T`NPV(r)=\sum_{t=0}^{T}\frac{CF_t}{(1+r)^t},\qquad CF_0<0`),S('IRR ist eine Nullstelle, keine Wertgröße',`Der interne Zins ist der Diskontsatz, bei dem NPV null wird. Bei einem normalen Zahlungsstrom mit einer anfänglichen Auszahlung und nur folgenden Einzahlungen fällt der NPV mit dem Zins; dann ist die positive Nullstelle gegebenenfalls eindeutig. Mehrfache Vorzeichenwechsel können mehrere oder keine ökonomisch brauchbare IRR erzeugen.

Bei sich ausschließenden Projekten können Rangfolgen wegen Größe und Zahlungszeitpunkten abweichen. NPV misst absoluten Wertbeitrag bei den relevanten Opportunitätskosten; IRR eine interne Prozentrelation. Die Differenz der Projektcashflows liefert den Crossover-Zins, an dem beide NPV gleich sind. Eine höhere IRR allein entscheidet daher keine Kapitalallokation.`,T`NPV(IRR)=0,\quad \frac{dNPV}{dr}=-\sum_{t=1}^{T}\frac{t\,CF_t}{(1+r)^{t+1}},\quad NPV_A(r_c)-NPV_B(r_c)=0`),S('Kapitalrationierung und Sensitivität',`Bei begrenztem Investitionsbudget ist die Auswahl ein Optimierungsproblem. Ein Profitability Index kann bei teilbaren unabhängigen Projekten hilfreich sein; bei unteilbaren oder miteinander verknüpften Projekten kann eine einfache Rangliste suboptimal sein. Die Nebenbedingungen müssen ausdrücklich modelliert werden.

Sensitivitätsanalysen ändern jeweils einen Treiber; Szenarien kombinieren zusammenpassende Änderungen. Ein Break-even-Umsatz ist der Wert, bei dem NPV null wird, nicht zwingend der buchhalterische Gewinnschwellenumsatz. Diese Unterscheidung verhindert, dass ein Projekt mit positivem Jahresgewinn trotz unzureichender Kapitalverzinsung als vorteilhaft gilt.`)],C('Skala erzeugt unterschiedliche Rangfolgen','Zwei einjährige, sich ausschließende Projekte; Diskontsatz 10 %.',['Projekt','Auszahlung','Endzahlung','IRR','NPV'],[['A','100','130','30 %','18,18'],['B','1.000','1.200','20 %','90,91']],'A hat die höhere Prozentverzinsung, B den größeren absoluten Wertbeitrag. Ohne bindende Kapitalrestriktion und bei vergleichbarem Risiko ist B nach NPV vorzuziehen. Die Zusatzinvestition von 900 erzeugt 1.070 zusätzliche Endzahlung; ihre IRR beträgt 18,89 % und liegt über 10 %.'),[['quant-01','Diskontierung und Opportunitätskosten.'],['corporate-06','Den zum Projektrisiko passenden Satz bestimmen.']]),
D([S('Flexibilität verändert die Entscheidungsregel',`Ein statischer NPV unterstellt häufig eine heute festgelegte Handlungskette. Eine reale Option erlaubt spätere Anpassung an neue Information: warten, erweitern, verkleinern, wechseln oder abbrechen. Weil eine Option nicht ausgeübt werden muss, schneidet sie schlechte Handlungsalternativen ab; ihr Wert hängt aber von Kosten, Wettbewerb und tatsächlicher Kontrollmöglichkeit ab.

Der Maximaloperator muss innerhalb der Zustandsrechnung stehen, wenn die Entscheidung nach Beobachtung des Zustands erfolgt. Erst Durchschnitt bilden und dann entscheiden ist eine andere Informationsstruktur. Diese Reihenfolge erklärt mathematisch den Wert von Information und Flexibilität.`,T`V_{\mathrm{flex}}=E[\max(V_s-I,0)],\qquad E[\max(X,0)]\ge\max(E[X],0)`),S('Entscheidungsbaum und Optionsbewertung',`Ein Entscheidungsbaum trennt zufällige Ereignisse von kontrollierbaren Entscheidungen. Rückwärtsrechnung wählt an jedem Entscheidungsknoten die beste zulässige Handlung. Wahrscheinlichkeiten und Diskontsätze müssen das Risiko konsistent berücksichtigen; ein risikoneutraler Baum und reale Wahrscheinlichkeiten mit pauschalem risikofreiem Satz dürfen nicht vermischt werden.

Finanzoptionsmodelle bieten nützliche Analogien, aber reale Projekte sind oft nicht handelbar und unvollständig absicherbar. Technologische Unsicherheit, Konkurrenz und die Möglichkeit, dass Warten Marktvorteile kostet, begrenzen direkte Black-Scholes-Anwendungen. Der Optionswert ist daher nur so belastbar wie die modellierten Handlungsrechte.`)],C('Gleiche Projekte, unterschiedlicher Entscheidungszeitpunkt','In einem Jahr kostet die Investition 100 und ist dann 140 oder 60 wert, jeweils mit 50 %. Zur Isolation wird nicht diskontiert.',['Regel','Guter Zustand','Schlechter Zustand','Erwarteter Nettowert'],[['Heute verbindlich investieren','40','−40','0'],['Nach Beobachtung optional investieren','40','0','20']],'Die flexible Variante verzichtet im schlechten Zustand. Ihre Verbesserung beträgt 20 vor Kosten des Wartens oder des Optionsrechts. Das Ergebnis setzt voraus, dass die Investitionsmöglichkeit bis zur Entscheidung tatsächlich erhalten bleibt.'),[['derivatives-07','Rückwärtsbewertung im Baum verstehen.'],['economics-12','Unsicherheit und Anpassungsfähigkeit verbinden.']]),
D([S('WACC aus den Ansprüchen der Kapitalgeber',`FCFF steht Eigen- und Fremdkapital gemeinsam zur Verfügung. Sein Diskontsatz muss deshalb die geforderten Renditen beider Kapitalgeber entsprechend ihren Marktwertanteilen abbilden. Bei steuerlich nutzbarem Zinsabzug wird der Fremdkapitalanteil nach Unternehmenssteuern angesetzt. Historische Kupons sind nicht automatisch die heutigen marginalen Fremdkapitalkosten.

Marktwerte erfassen die aktuellen Opportunitätskosten. Buchgewichte können davon stark abweichen. Der Satz gilt für Cashflows mit passendem operativem Risiko und einer mit der Methode vereinbaren Finanzierungspolitik. Ein Konzern-WACC ist nicht automatisch für ein neues, deutlich riskanteres Projekt geeignet.`,T`WACC=\frac{E}{D+E}k_e+\frac{D}{D+E}k_d(1-\tau)`),S('Beta enthebeln und wieder hebeln',`Ein beobachtetes Aktienbeta enthält Geschäfts- und Finanzierungsrisiko. Unter vereinfachten Annahmen mit risikoloser Schuld und entsprechendem Steuerschildzusammenhang kann das Eigenkapitalbeta auf ein unverschuldetes Beta zurückgeführt werden. Für eine Zielkapitalstruktur wird anschließend wieder gehebelt. Risikobehaftete Schuld oder andere Steuerannahmen erfordern eine erweiterte Beziehung.

Dieser Prozess erlaubt einen Vergleich von Unternehmen mit ähnlichem Geschäft, aber verschiedener Finanzierung. Er beseitigt jedoch keine Unterschiede in Produktmix, operativem Leverage oder Schätzfehlern. Deshalb sind mehrere passende Vergleichsunternehmen und Sensitivitäten sinnvoll.`,T`\beta_U=\frac{\beta_L}{1+(1-\tau)D/E},\qquad \beta_{L,\mathrm{target}}=\beta_U[1+(1-\tau)(D/E)_{\mathrm{target}}]`),S('APV und veränderliche Verschuldung',`Bei stark wechselndem Leverage kann ein Adjusted-Present-Value-Ansatz übersichtlicher sein. Zunächst wird das operative Projekt unverschuldet bewertet; anschließend werden Finanzierungseffekte wie Steuerschilde und Finanzierungskosten separat addiert oder abgezogen. Jeder Bestandteil benötigt einen zu seinem Risiko passenden Diskontsatz.

WACC und APV können bei konsistenten Annahmen denselben Wert liefern. Unterschiede entstehen häufig durch implizit andere Schuldpolitiken: eine konstante Marktwertquote ist nicht dasselbe wie ein fest geplanter nominaler Schuldenpfad. Der gewählte Ansatz muss zur geplanten Finanzierung passen.`,T`V_L=V_U+PV(TS)-PV(FC)`)],C('Nur die Finanzierung ändern, Geschäftsrisiko konstant','βU = 0,8, Steuersatz 25 %, risikolose Schuld im vereinfachten Beta-Modell. Risikofreier Satz 3 %, Marktprämie 5 %.',['D/E','Eigenkapitalbeta','Eigenkapitalkosten'],[['0','0,8','7 %'],['0,5','1,1','8,5 %'],['1','1,4','10 %']],'Mehr Schuld macht Eigenkapital zum riskanteren Restanspruch. Die Eigenkapitalkosten dürfen daher nicht bei 7 % festgehalten werden, während man immer mehr günstige Schuld beimischt. Genau dieser Fehler würde einen künstlich beliebig sinkenden WACC erzeugen.'),[['portfolio-04','CAPM und Beta herleiten.'],['equity-09','FCFF und FCFE mit passenden Sätzen bewerten.']]),
D([S('Operativer Hebel aus der Gewinnfunktion',`Mit Preis p, variablen Stückkosten v, Menge Q und fixen operativen Kosten F ist EBIT der Deckungsbeitrag abzüglich F. Die Elastizität des EBIT gegenüber der Menge ergibt sich durch Ableiten und Normieren. Nahe der Gewinnschwelle ist der Nenner klein; kleine Mengenänderungen bewirken dann große relative Ergebnisänderungen.

Die Kennzahl ist lokal. Bei Kapazitätssprüngen, Mengenrabatten oder wechselnden Preisen bleibt die lineare Kostenfunktion nicht gültig. Unterhalb der Gewinnschwelle können Vorzeichen und relative Prozentinterpretationen außerdem irreführend werden.`,T`EBIT=(p-v)Q-F,\quad DOL=\frac{\partial EBIT}{\partial Q}\frac{Q}{EBIT}=\frac{(p-v)Q}{(p-v)Q-F}`),S('Finanzieller Hebel und gesamter Ergebnishebel',`Fester Zinsaufwand I wird nach dem operativen Ergebnis abgezogen. Bei konstanter Steuerquote und Aktienzahl folgt die lokale Elastizität des Eigentümergewinns gegenüber EBIT. Multipliziert man operativen und finanziellen Hebel, erhält man die Elastizität gegenüber Absatzänderungen.

Die Kapitalstrukturtheorie erklärt zusätzlich, warum billiger erscheinende Schuld nicht unbegrenzt Wert schafft. Ohne Friktionen steigt die geforderte Eigenkapitalrendite mit Leverage. In der Realität kommen Steuervorteile, erwartete Krisenkosten, Agency-Konflikte und Informationsprobleme hinzu. Ein höherer ROE ist deshalb nicht automatisch eine bessere risikobereinigte Finanzierung.`,T`DFL=\frac{EBIT}{EBIT-I},\qquad DTL=DOL\cdot DFL`)],C('Gleicher operativer Gewinn, andere Fixkostenstruktur','Umsatz 100. A hat variable Kosten 60 und Fixkosten 20; B variable Kosten 20 und Fixkosten 60. Preise und Kostenquoten bleiben im Szenario konstant.',['Firma','EBIT vorher','DOL','EBIT bei Umsatz +10 %'],[['A','20','2','24'],['B','20','4','28']],'Beide starten mit EBIT 20. B gewinnt bei Wachstum stärker, verliert bei einem Rückgang aber ebenso stärker: Bei −10 % Umsatz fällt EBIT auf 12 statt 16. Der höhere Hebel erzeugt beide Richtungen und ist keine isolierte Verbesserung.'),[['corporate-01','Restansprüche verteilen Risiko asymmetrisch.'],['statements-12','ROE in operative Leistung und Hebel zerlegen.']]),
D([S('Cash Conversion Cycle aus den Zahlungsterminen',`Zwischen Lieferantenzahlung und Kundenzahlung muss das Unternehmen den Produktions- und Verkaufszyklus finanzieren. Lagerdauer und Forderungslaufzeit verlängern die Bindung; Lieferantenkredit verkürzt sie. Deshalb werden DIO und DSO addiert und DPO abgezogen.

Die Kennzahlen verwenden unterschiedliche passende Ströme: Forderungen beziehen sich typischerweise auf Umsatz, Lager auf Wareneinsatz und Verbindlichkeiten möglichst auf Einkäufe. Eine pauschale Verwendung von Umsatz für alle Nenner verändert die Interpretation. Saisonalität und Durchschnittsbestände sind ebenfalls zu berücksichtigen.`,T`CCC=DIO+DSO-DPO,\quad DSO=\frac{\overline{AR}}{S}\,365`),S('Liquiditätsvorteil und wirtschaftliche Kosten',`Kürzere Zahlungsziele senken Forderungsbindung, können aber Kunden kosten. Mehr Lieferantenkredit spart Finanzierung, kann Skonto verlieren oder Lieferbeziehungen belasten. Working-Capital-Optimierung ist daher keine Maximierung jeder Zahlungsfrist, sondern eine Abwägung von Kosten, Absatz und Resilienz.

Ein negativer Cash Conversion Cycle ist möglich, wenn Kunden früher zahlen als Lieferanten bezahlt werden. Wachstum kann dann Liquidität freisetzen; ein Umsatzrückgang kann diesen Effekt umkehren. Das scheinbar günstige Finanzierungsmodell muss daher auch im Abschwung geprüft werden.`)],C('Gleicher Umsatz, nur Forderungslaufzeit verändern','Jahresumsatz 365.000, gleichmäßige Verkäufe, keine Umsatzsteuer oder Ausfälle.',['DSO','Durchschnittliche Forderung','Gebundenes Cash relativ zu 30 Tagen'],[['15 Tage','15.000','−15.000'],['30 Tage','30.000','0'],['60 Tage','60.000','+30.000']],'Ein Tag Umsatz entspricht 1.000. Die Verlängerung von 30 auf 60 Tage bindet zusätzliche 30.000, obwohl Umsatz und Marge unverändert sind. Die Rechnung macht sichtbar, warum Zahlungsbedingungen ein Finanzierungstreiber sind.'),[['statements-02','Forderungsänderung im CFO überleiten.'],['statements-15','Liquiditätsbedarf im integrierten Modell abbilden.']]),
D([S('Ausschüttung verteilt vorhandenen Wert',`Eine Dividende reduziert unter idealisierten Bedingungen den Unternehmenscashbestand und damit den Wert der Aktie um den ausgeschütteten Betrag. Der Aktionär besitzt anschließend weniger Aktienwert plus Cash. Ein fair bewerteter Rückkauf reduziert dagegen Cash und Aktienzahl; der proportionale Anspruch der verbleibenden Eigentümer verändert sich.

Steuern, Transaktionskosten, Informationssignale und Bewertungsabweichungen können die wirtschaftliche Wahl beeinflussen. Ein Rückkauf unter innerem Wert kann verbleibende Eigentümer begünstigen, ein überteuerter Rückkauf benachteiligen. Der Begriff „Kapitalrückgabe“ allein beantwortet daher nicht die Wertfrage.`,T`P_{ex}\approx P_{cum}-DPS,\qquad N_1=N_0-\frac{B}{P_{rep}}`),S('EPS-Anstieg ist kein automatischer Wertgewinn',`Wenn Aktienzahl sinkt, kann EPS steigen. Gleichzeitig verliert die Firma Zinsertrag auf Cash oder trägt zusätzliche Finanzierungskosten. Ein mechanischer EPS-Vergleich muss diese Ergebniswirkung berücksichtigen. Selbst ein EPS-Anstieg beweist noch keinen positiven NPV des Rückkaufs.

Nachhaltige Ausschüttungen hängen von freien Cashflows, Investitionsmöglichkeiten und finanzieller Flexibilität ab. Eine starre Ausschüttungsquote kann bei zyklischen Gewinnen problematisch sein. Für die Bewertung zählen die gesamten Eigentümerzahlungen über die Zeit, nicht allein eine hohe aktuelle Dividendenrendite.`)],C('Gleicher Gesamtwert, andere Ausschüttungsform','Unternehmenswert 1.000 einschließlich 100 überschüssigem Cash, 100 Aktien; keine Friktionen.',['Maßnahme','Restwert','Aktienzahl','Wert je verbleibender Aktie'],[['Dividende 1 je Aktie','900','100','9 plus 1 Cash je alter Aktie'],['Rückkauf 10 Aktien zu 10','900','90','10']],'Der Rückkauf erhöht hier nicht den fairen Kurs, obwohl weniger Aktien existieren. Die Dividende senkt den Kurs, vernichtet aber keinen Gesamtwert für den Empfänger. Steuern und nicht faire Rückkaufpreise würden den Vergleich verändern.'),[['equity-08','Ausschüttungen als Bewertungsgrundlage.'],['equity-11','Clean-Surplus-Verbindung zwischen Buchwert und Ausschüttung.']]),
D([S('Synergie und gezahlte Prämie auseinanderhalten',`Der kombinierte Wert kann durch höhere Umsätze, geringere Kosten, bessere Kapitalnutzung oder Finanzierungseffekte steigen. Davon sind Integrationskosten, Verzögerungen und mögliche Nachteile abzuziehen. Die Akquisitionsprämie ist der Teil, den der Käufer über den eigenständigen Zielwert hinaus an Verkäufer abgibt.

Der Käufer schafft nur dann Wert für seine bisherigen Eigentümer, wenn sein Anteil an realisierbaren Nettosynergien die Prämie und weitere Transaktionskosten übersteigt. Ein positives kombiniertes Synergiepotenzial genügt nicht, wenn es vollständig oder mehr als vollständig im Kaufpreis bezahlt wird.`,T`V_{AB}=V_A+V_B+S,\qquad NPV_A=S-Prem-C`),S('Zahlungsmittel und Verteilung des Risikos',`Barzahlung legt die Gegenleistung weitgehend fest und belastet Cash oder Verschuldung des Käufers. Eine Aktienzahlung macht Verkäufer zu Beteiligten am kombinierten Unternehmen. Ihr tatsächlicher Wert hängt von Aktienkurs und Umtauschverhältnis ab. Die Wahl verteilt Bewertungs- und Integrationsrisiko unterschiedlich.

EPS-Akkretion kann allein aus unterschiedlichen Bewertungsmultiplikatoren oder Finanzierung entstehen. Sie ist kein Ersatz für eine DCF-Prüfung der Transaktion. Außerdem können Kaufpreisallokation, neue Abschreibungen und nicht beherrschende Anteile die spätere Ergebnisdarstellung verändern, ohne den ursprünglichen wirtschaftlichen Kaufpreis rückgängig zu machen.`)],C('Gleiche Synergie, anderer Kaufpreis','Eigenständiger Zielwert 100, Nettosynergie vor separaten Transaktionskosten 30, Kosten 5.',['Kaufpreis','Prämie','NPV für Käufer'],[['110','10','15'],['125','25','0'],['140','40','−15']],'Der maximal wertneutrale Kaufpreis beträgt hier 125. Die Synergie bleibt in allen Fällen 30; der Unterschied entsteht durch ihre Verteilung zwischen Käufer und Verkäufer. Eine erfolgreiche operative Integration kann daher mit einer schlechten Investition zusammenfallen, wenn zu viel bezahlt wurde.'),[['statements-10','Kaufpreisallokation und Konsolidierung verstehen.'],['path-private-02','Transaktionsstruktur und Eigentümerrendite verbinden.']])
];
