const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Marktwert, Nominalwert und Exponierung',`Der Nominalwert dient der Berechnung vertraglicher Zahlungen. Er ist nicht automatisch der aktuelle Marktwert oder der mögliche Verlust. Ein neu abgeschlossener fairer Swap kann Marktwert null und trotzdem erhebliche künftige Zins- und Gegenparteiexponierung besitzen.

Bei einem positiven Wiederbeschaffungswert droht dem Inhaber ein Verlust, wenn die Gegenpartei ausfällt und die Position nicht vollständig besichert ist. Künftige Exponierung ist selbst zufällig. Netting kann gegenläufige Ansprüche innerhalb rechtlich durchsetzbarer Vereinbarungen reduzieren; es darf nicht über unabhängige Gegenparteien hinweg beliebig angesetzt werden.`,T`EE_t=E[\max(V_t-C_t,0)],\quad CVA\approx\sum_t DF_t\,LGD_t\,EE_t\,\Delta PD_t`),S('Clearing und Margin verändern die Risikoverteilung',`Variation Margin gleicht laufende Marktwertänderungen aus. Initial Margin soll potenzielle Änderungen während einer Schließungsperiode abdecken. Clearing reduziert bestimmte bilaterale Risiken durch Standardisierung und Sicherheiten, konzentriert aber Aufgaben bei der zentralen Gegenpartei und benötigt robuste Ausfallverfahren.

Eine ökonomisch passende Absicherung kann zwischenzeitlich hohe Marginzahlungen erfordern. Die abgesicherte Anlage gewinnt möglicherweise erst später oder ist nicht sofort liquide. Marktwertschutz und Zahlungsfähigkeit müssen deshalb getrennt geplant werden. Wrong-Way-Risk entsteht, wenn hohe Exponierung mit schwacher Gegenparteibonität zusammenfällt.`)],C('Gleicher Vertragswert, unterschiedliche Besicherung','Positiver Marktwert 10, Verlustquote im Ausfall 60 %, nur heutige Exponierung betrachtet.',['Anrechenbare Sicherheit','Ungesicherte Exponierung','Verlust bei sofortigem Ausfall'],[['0','10','6'],['8','2','1,2'],['10','0','0 im vereinfachten Modell']],'Die Sicherheit reduziert hier den unbesicherten Betrag. Bewertungsänderungen, Streitigkeiten, Haircuts und Abwicklungsverzögerungen können jedoch weitere Risiken erzeugen. Eine heutige Exponierung von null garantiert keine künftige Exponierung von null.'),[['bonds-12','Besicherte Finanzierung und Haircuts.'],['advanced-08','Marginbedarf als Liquiditätsrisiko.']]),
D([S('Replikation erzwingt gleiche Preise gleicher Zahlungen',`Wenn zwei heute handelbare Strategien in jedem relevanten Zustand denselben künftigen Cashflow erzeugen, müssen ihre Preise unter idealisierten friktionsfreien Bedingungen übereinstimmen. Andernfalls kauft man die billigere und verkauft die teurere. Eine Übereinstimmung nur im Erwartungswert reicht nicht für diese Arbitrageargumentation.

Für einen Basiswert ohne laufende Erträge wird ein Forward durch kreditfinanzierten Kauf repliziert. Laufende Erträge reduzieren die Nettokosten des Haltens; Lagerkosten erhöhen sie. Bei physischer Ware kann ein Nutzen aus Verfügbarkeit als Convenience Yield auftreten, dessen Arbitrageinterpretation durch Lager- und Leerverkaufsbeschränkungen begrenzt ist.`,T`F_0=S_0e^{(r+u-q-y)T}`),S('Welche Größe ist sicher und handelbar?',`In der Formel stehen r für Finanzierung, u für proportionale Lagerkosten, q für laufende Ertragsrendite und y für Convenience Yield, jeweils in derselben stetigen Konvention. Sichere absolute Zahlungen können alternativ mit ihren Barwerten vor Aufzinsung abgezogen oder addiert werden.

Transaktionskosten erzeugen in der Praxis Arbitragebänder. Unterschiedliche Kredit- und Anlagezinsen, Sicherheitenbedingungen und eingeschränkte Leerverkäufe verhindern eine kostenlose Umsetzung jedes theoretischen Trades. Eine beobachtete Abweichung ist deshalb zunächst gegen tatsächlich ausführbare Replikationskosten zu prüfen.`)],C('Gleicher Spotpreis, andere Haltekosten und Erträge','S0 = 100, ein Jahr, stetiger Finanzierungszins 5 %.',['Zusatzannahme','Netto-Carry','Forward'],[['Keine Erträge oder Lagerkosten','5 %','105,13'],['Ertragsrendite 3 %','2 %','102,02'],['Lagerkosten 2 %, kein Ertrag','7 %','107,25']],'Die Unterschiede entstehen durch den wirtschaftlichen Nutzen und die Kosten des Besitzes vor Fälligkeit. Ein Forwardkäufer erhält diesen Besitznutzen während der Laufzeit nicht unmittelbar; der Preis gleicht die Replikationswege aus.'),[['economics-11','Währungen als verzinsliche Basiswerte.'],['alternatives-08','Convenience Yield und Rohstoffkurven.']]),
D([S('Forwardpreis und Wert eines bestehenden Forwards',`Der Forwardpreis F(t,T) ist der heute faire Lieferpreis für einen neuen Vertrag mit Fälligkeit T. Ein bestehender Vertrag hat dagegen einen früher vereinbarten Lieferpreis K. Sein Wert kann positiv oder negativ sein, obwohl ein neuer fairer Vertrag typischerweise ohne anfänglichen Wert abgeschlossen wird.

Für einen Long-Forward auf einen Basiswert ohne Erträge besteht die Replikation aus einer Aktie und einer Finanzierung des Lieferpreises. Daraus entsteht sein laufender Wert. Die Darstellung über den Unterschied zwischen neuem Forwardpreis und altem K macht den erforderlichen Abzinsungsschritt sichtbar.`,T`V_t=S_t-Ke^{-r(T-t)}=e^{-r(T-t)}[F(t,T)-K]`),S('Zeit, Carry und unterschiedliche Basiswerte',`Bei Dividenden oder anderen Erträgen wird der Wert des vor Fälligkeit zufließenden Besitznutzens berücksichtigt. Für Währungen ist der ausländische Zins die Ertragskomponente. Für Anleihen müssen vor Lieferung gezahlte Kupons und Preisnotierung konsistent abgegrenzt werden.

Die Auszahlung am Ende ist linear im Basiswertpreis, die Rendite auf eine eventuell kleine Sicherheitenzahlung jedoch nicht mit einer gewöhnlichen ungehebelten Anlagerendite gleichzusetzen. Ein Forward kann ohne große Anfangsauszahlung erhebliche spätere Verpflichtungen erzeugen.`)],C('Gleicher Spotkurs, andere alte Vertragskondition','Aktueller fairer Einjahresforward 105, Diskontfaktor 0,95.',['Alter Lieferpreis K','Heutiger Long-Wert'],[['100','4,75'],['105','0'],['110','−4,75']],'Der Unterschied von fünf am Liefertermin ist heute nur 4,75 wert. Spotpreis oder neuer Forwardpreis allein sagen daher nicht, ob ein bestehender Vertrag im Gewinn liegt; sein vereinbarter Lieferpreis wird benötigt.'),[['derivatives-02','Replikation des fairen Lieferpreises.'],['advanced-06','Währungsforwards im Portfolio verwenden.']]),
D([S('Tägliche Abrechnung verändert Zahlungszeitpunkte',`Futures werden laufend über Margin abgerechnet. Ein gleicher Endpreis wie bei einem Forward garantiert deshalb nicht identische Zwischenzahlungen. Bei deterministischen Zinsen können die Preise unter passenden Bedingungen übereinstimmen; bei stochastischen Zinsen hängt der Unterschied unter anderem von der Kovarianz zwischen Preisbewegungen und Wiederanlagezinsen ab.

Standardisierung erleichtert Handel und Clearing, erzeugt aber mögliche Unterschiede zum tatsächlich abzusichernden Risiko: Basiswert, Qualität, Lieferort, Laufzeit und Kontraktgröße können abweichen. Diese Differenzen sind Quellen von Basisrisiko.`),S('Minimum-Varianz-Hedge herleiten',`Die Änderung einer abgesicherten Position ist Spotänderung minus h mal Futuresänderung. Ihre Varianz enthält Spotvarianz, Futuresvarianz und den Kovarianzterm. Ableiten nach h und Gleichsetzen mit null liefert die optimale lineare Hedge Ratio für das verwendete Datenmodell.

Die optimale statistische Quote ist nicht automatisch eins. Geschätzte Korrelation und Volatilitäten können sich ändern; ein historisch optimaler Hedge muss deshalb überwacht werden. Für die Kontraktzahl werden Exposure und Kontraktgröße zusätzlich in konsistente Einheiten übersetzt.`,T`\sigma_H^2=\sigma_S^2+h^2\sigma_F^2-2h\rho\sigma_S\sigma_F,\quad h^*=\rho\frac{\sigma_S}{\sigma_F},\quad \sigma_{H,*}^2=\sigma_S^2(1-\rho^2)`)],C('Gleiche Volatilitäten, andere Korrelation','σS = 20 %, σF = 25 %, Renditebasis konsistent.',['Korrelation','Optimale Hedge Ratio','Verbleibende Volatilität'],[['1','0,8','0 % im Modell'],['0,8','0,64','12 %'],['0','0','20 %']],'Bei niedrigerer Korrelation wird eine kleinere Quote optimal und mehr Risiko bleibt übrig. Der Futureskontrakt ist dann ein schlechterer Ersatz für das Exposure. Mehr Kontrakte lösen mangelnde wirtschaftliche Passung nicht automatisch.'),[['quant-09','Regressionssteigung entspricht der Hedge Ratio.'],['portfolio-01','Kovarianz bestimmt Diversifikationswirkung.']]),
D([S('Swap als Bündel von Zahlungsansprüchen',`Ein Zinsswap tauscht fixe gegen variable Zinszahlungen auf einen Nominalbetrag. In einem vereinfachten Single-Curve-Modell hat die variable Seite bei Reset und passenden Bedingungen den Wert einer variablen Anleihe abzüglich der Nominalrückzahlung. Daraus folgt der Par-Swapsatz als Verhältnis von Diskontfaktordifferenz zur Annuity.

Die Zeitanteile α berücksichtigen Day Count und Zahlungstermine. Im heutigen Multi-Curve-Rahmen werden variable Forwardzahlungen aus einer Prognosekurve und Barwerte aus der passenden Diskontkurve gewonnen. Die einfache Teleskopform gilt dann nicht ohne Anpassung.`,T`A=\sum_i\alpha_iDF(t_i),\quad K_{par}=\frac{DF(t_0)-DF(T)}{A},\quad PV_{float}=N\sum_i\alpha_iF_iDF(t_i)`),S('Laufender Wert und wirtschaftliche Absicherung',`Für einen Receiver-Fixed-Swap ist ein alter hoher Festsatz wertvoll, wenn aktuelle faire Festsätze gesunken sind. Bei identischen verbleibenden Terminen lässt sich der Wert durch die Annuity mal Differenz zwischen Vertrags- und aktuellem Par-Satz ausdrücken. Für Payer Fixed kehrt sich das Vorzeichen um.

Währungs- und Equity Swaps tauschen andere Ertragskomponenten und gegebenenfalls Nominalbeträge. Absicherung ist nur so genau wie die Übereinstimmung von Referenzzins, Reset, Laufzeit, Währung und Exposure. Ein variabler Kredit mit anderem Referenzsatz kann trotz Swap Basisrisiko behalten.`,T`V_{rec}=NA(K-K_{par}),\qquad V_{pay}=-V_{rec}`)],C('Gleicher alter Swap, anderer aktueller Marktsatz','Nominal 1 Mio., verbleibende Annuity 4, alter Festsatz 5 %. Sicht: fest empfangen.',['Aktueller Par-Satz','Swapwert'],[['4 %','+40.000'],['5 %','0'],['6 %','−40.000']],'Ein Prozentpunkt auf 1 Mio. ergibt 10.000 jährliche Satzdifferenz; die Annuity 4 verwandelt sie in einen Barwert von 40.000. Die Tabelle hält die Annuity zur isolierten Sensitivität konstant; bei echten Kurvenänderungen wird auch sie neu berechnet.'),[['bonds-06','Diskontfaktoren und Par-Kupon verbinden.'],['bonds-08','Swap-DV01 in Zinsabsicherungen verwenden.']]),
D([S('Auszahlung und Gewinn sind nicht identisch',`Ein Long Call zahlt am Ende den positiven Unterschied zwischen Basiswert und Strike, ein Long Put den umgekehrten positiven Unterschied. Der Käufer bezahlt dafür eine Prämie. Gewinn berücksichtigt diese Prämie und gegebenenfalls ihre Finanzierung; die reine Auszahlung nicht.

Der Stillhalter erhält die entgegengesetzte Auszahlung und die Prämie. Ein begrenzter Verlust des Käufers bedeutet nicht, dass die Strategie wenig Verlustrisiko hat: Die gesamte Prämie kann verfallen. Umgekehrt kann ein ungedeckter Call-Verkauf sehr große Verluste erzeugen.`,T`C_T=(S_T-K)^+,\quad P_T=(K-S_T)^+,\quad \Pi_C=C_T-C_0e^{rT}`),S('Put-Call-Parität über gleiche Endzahlungen',`Eine Aktie plus Put liefert am Ende mindestens K und behält darüber den Aktienwert. Ein Call plus sicherer Betrag K liefert exakt dieselbe Endzahlung. Für europäische Optionen mit identischen Konditionen erzwingt dies die Preisparität. Bei stetiger Dividendenrendite wird der Wert des vor Fälligkeit zufließenden Aktienbesitznutzens berücksichtigt.

Die Beziehung erlaubt synthetische Positionen und Konsistenzprüfungen. Amerikanische Ausübungsrechte, unterschiedliche Dividendenannahmen und Transaktionskosten verändern die unmittelbar anwendbare Gleichung. Gleicher Strike ohne gleiche Laufzeit reicht nicht.`,T`C_0-P_0=S_0e^{-qT}-Ke^{-rT}`)],C('Gleicher Call, unterschiedliche Endkurse','Europäischer Call K = 100, Prämie 8; Zinsen zur Isolation null.',['Endkurs','Auszahlung','Gewinn'],[['80','0','−8'],['100','0','−8'],['108','8','0'],['130','30','22']],'Der Strike markiert den Beginn positiver Auszahlung, der Break-even liegt dagegen bei 108. Die Unterscheidung erklärt, warum eine Option im Geld sein kann und ihr Käufer trotzdem insgesamt Verlust macht.'),[['derivatives-10','Optionskombinationen aus Auszahlungen aufbauen.'],['corporate-05','Reale Optionen besitzen ähnliche Asymmetrie.']]),
D([S('Replizierendes Portfolio im Einperiodenbaum',`Im Binomialmodell kann der Basiswert auf Su steigen oder auf Sd fallen. Eine Kombination aus Δ Aktien und einer sicheren Finanzierung B wird so gewählt, dass sie beide Optionsauszahlungen reproduziert. Subtraktion der beiden Zustandsgleichungen liefert Δ; Einsetzen liefert B. Der heutige Optionspreis ist anschließend der Preis dieser Replikation.

Diese Konstruktion verwendet keine subjektive Eintrittswahrscheinlichkeit. Sie benötigt stattdessen handelbare Replikationsinstrumente und einen arbitragefreien Baum. Liegt der sichere Wachstumsfaktor nicht zwischen d und u, wäre das einfache Modell selbst inkonsistent.`,T`\Delta=\frac{C_u-C_d}{S_0(u-d)},\quad B=\frac{uC_d-dC_u}{(u-d)(1+r)},\quad C_0=\Delta S_0+B`),S('Risikoneutrale Wahrscheinlichkeit als Bewertungsgewicht',`Die Replikationsformel lässt sich als diskontierter gewichteter Erwartungswert schreiben. Das Gewicht q ist so gewählt, dass der Basiswert im Modell im Erwartungswert mit dem sicheren Satz wächst. q ist daher ein Preisgewicht und nicht zwingend die reale Prognosewahrscheinlichkeit.

Bei mehreren Perioden wird rückwärts gerechnet. Für amerikanische Optionen wird an jedem Knoten Fortführungswert gegen sofortigen Ausübungswert geprüft. Eine amerikanische Option kann daher unter gleichen Bedingungen nicht weniger wert sein als die entsprechende europäische.`,T`q=\frac{1+r-d}{u-d},\quad C_0=\frac{qC_u+(1-q)C_d}{1+r},\quad V_{Am}=\max(V_{cont},V_{exercise})`)],C('Gleiche Auszahlungen, verschiedene reale Meinungen','S0 = 100, u = 1,2, d = 0,8, sicherer Satz 5 %, Call K = 100.',['Größe','Wert','Ableitung'],[['Auszahlungen oben / unten','20 / 0','max(S − 100, 0)'],['Δ','0,5','20 / (120 − 80)'],['Sichere Finanzierung B','−38,0952','−40 / 1,05'],['Optionswert','11,9048','50 − 38,0952'],['Risikoneutrales q','0,625','(1,05 − 0,8) / 0,4']],'Auch wenn zwei Anleger die reale Aufwärtswahrscheinlichkeit mit 40 % beziehungsweise 70 % einschätzen, bleibt im vollständigen Replikationsmodell derselbe Optionspreis. Ihre Prognosen können ihre Anlageentscheidung ändern, nicht die Kosten identischer replizierter Zahlungen.'),[['derivatives-02','Gleiche Zustandszahlungen erzwingen gleiche Preise.'],['quant-06','Reale Wahrscheinlichkeiten von Preisgewichten unterscheiden.']]),
D([S('Vom dynamischen Hedge zur Black-Scholes-Gleichung',`Im Black-Scholes-Merton-Modell folgt der Basiswert einer geometrischen Brownschen Bewegung mit konstanter Volatilität. Itôs Lemma zerlegt die Optionswertänderung in Zeit-, Drift-, Zufalls- und Krümmungseffekte. Eine Delta-Hedge-Position entfernt den lokalen Zufallsterm; ihr verbleibender Ertrag muss unter den Modellannahmen mit der sicheren Finanzierung konsistent sein.

Daraus entsteht eine partielle Differentialgleichung mit der Optionsauszahlung als Endbedingung. Die reale erwartete Aktienrendite verschwindet aus dieser Replikationsgleichung. Sie wird deshalb nicht als zusätzlicher Parameter in die Standardformel eingesetzt.`,T`\frac{\partial V}{\partial t}+\frac12\sigma^2S^2\frac{\partial^2V}{\partial S^2}+(r-q)S\frac{\partial V}{\partial S}-rV=0`),S('Geschlossene Lösung und Bedeutung der Terme',`Der europäische Call wird als gewichteter Wert des Basiswertanspruchs minus gewichteter Barwert des Strikes geschrieben. d1 und d2 standardisieren Log-Moneyness, Carry und Laufzeit relativ zur Unsicherheit. N bezeichnet die kumulative Standardnormalverteilung.

N(d2) besitzt im Modell eine risikoneutrale Endereignisinterpretation. N(d1) ist nicht einfach dieselbe reale Ausübungswahrscheinlichkeit; bei Dividendenrendite ist das Call-Delta zusätzlich mit dem Dividendenfaktor skaliert. Laufzeit muss in derselben Jahreseinheit wie Zins und annualisierte Volatilität eingehen.`,T`C=Se^{-qT}N(d_1)-Ke^{-rT}N(d_2),\quad d_1=\frac{\ln(S/K)+(r-q+\sigma^2/2)T}{\sigma\sqrt T},\quad d_2=d_1-\sigma\sqrt T`),S('Modellgrenzen erklären die Volatilitätsoberfläche',`Konstante Volatilität, kontinuierliches reibungsloses Hedging, keine Sprünge und passende Finanzierungsbedingungen sind starke Annahmen. Reale Optionspreise weisen häufig unterschiedliche implizite Volatilitäten nach Strike und Laufzeit auf. Der Smile ist dann ein Hinweis, dass ein einziger konstanter Parameter nicht alle Preise zugleich erklärt.

Die Formel bleibt als Quotierungs- und Sensitivitätssprache nützlich. Für Absicherung müssen jedoch Diskretisierung, Sprünge, Kosten und Veränderungen der Volatilitätsstruktur berücksichtigt werden. Ein kalibrierter Preis ist keine Garantie für einen perfekten künftigen Hedge.`)],C('Gleiche Moneyness, nur Unsicherheit ändern','S = K = 100, r = q = 0, T = 1 Jahr. Dann C = 100 × [2N(σ/2) − 1].',['Volatilität','Callwert ungefähr'],[['10 %','3,99'],['20 %','7,97'],['40 %','15,85']],'Mehr Unsicherheit erhöht den Wert der konvexen Käuferauszahlung: Verluste bleiben auf die Prämie begrenzt, hohe Endkurse können zusätzliche Auszahlung erzeugen. Die höheren Prämien sind der Preis dieses Vorteils und kein kostenloser erwarteter Gewinn.'),[['derivatives-07','Diskrete Replikation als Vorbereitung.'],['derivatives-09','Ableitungen der Optionswertfunktion verstehen.']]),
D([S('Greeks als lokale Ableitungen einer mehrdimensionalen Funktion',`Der Optionswert hängt von Kurs, Zeit, Volatilität, Zins und weiteren Faktoren ab. Delta ist die erste Kursableitung, Gamma die zweite. Vega misst die Volatilitätsableitung, Rho die Zinsableitung. Theta wird hier als Ableitung nach fortschreitender Kalenderzeit definiert; bei Ableitung nach Restlaufzeit kehrt sich das Vorzeichen um.

Eine Taylor-Näherung kombiniert lineare Effekte und die quadratische Kurskrümmung. Sie ist lokal und lässt zunächst Kreuzableitungen und höhere Ordnungen aus. Bei großen Sprüngen oder gleichzeitiger Veränderung mehrerer Parameter kann ihr Fehler wesentlich werden.`,T`\Delta=V_S,\quad\Gamma=V_{SS},\quad\nu=V_\sigma,\quad\rho=V_r,\quad\Theta=V_t,\quad dV\approx\Delta\,dS+\tfrac12\Gamma(dS)^2+\nu\,d\sigma+\rho\,dr+\Theta\,dt`),S('Einheiten und Hedge-Dynamik',`Vega aus einer analytischen Ableitung bezieht sich auf eine Volatilitätsänderung von 1,00, also 100 Prozentpunkten. Für einen Volatilitätspunkt wird durch 100 geteilt. Entsprechend sind Rho pro Dezimalzins und DV01 pro Basispunkt verschiedene Skalierungen. Kontraktmultiplikatoren kommen zusätzlich hinzu.

Delta-Neutralität beseitigt nur den lokalen linearen Kurseffekt. Bei positivem Gamma ändert sich Delta mit dem Kurs; der Hedge muss angepasst werden. Positive Gamma- und Vega-Exponierung wird bei gewöhnlichen gekauften Optionen häufig mit Zeitwertverlust bezahlt. Smile-Änderungen können außerdem unterschiedliche Strikes verschieden beeinflussen.`,T`\Delta_C=e^{-qT}N(d_1),\quad\Gamma=\frac{e^{-qT}\phi(d_1)}{S\sigma\sqrt T},\quad\nu=Se^{-qT}\phi(d_1)\sqrt T`)],C('Gleiches Delta, anderes Gamma','Zwei Positionen haben Delta 0,5. Kursänderung ±10; andere Faktoren konstant. Gamma A = 0, Gamma B = 0,02.',['Position','Näherung bei +10','Näherung bei −10'],[['A','+5','−5'],['B','+6','−4']],'Der Gamma-Beitrag beträgt in beiden Richtungen 0,5 × 0,02 × 10² = 1. Positive Krümmung verbessert die lokale symmetrische Preisreaktion, verursacht aber typischerweise einen entsprechenden Optionspreis beziehungsweise andere laufende Exponierungen.'),[['bonds-08','Duration und Konvexität sind analoge Preisableitungen.'],['advanced-07','Mehrere Risikosensitivitäten mit Overlays steuern.']]),
D([S('Strategien durch Addition von Auszahlungen verstehen',`Eine Optionsstrategie ist eine Kombination einzelner linearer oder geknickter Auszahlungen. Statt Namen auswendig zu lernen, werden Endbereiche durch Strikes getrennt und die Positionen in jedem Bereich addiert. Erst danach werden Nettoprämie und Finanzierung berücksichtigt.

Ein Protective Put kombiniert Aktie und Put und begrenzt den Endwert nach unten. Ein Covered Call gibt gegen Prämie einen Teil der Aufwärtschance ab; er beseitigt den großen Aktienverlust nicht. Ein Collar finanziert einen Teil des Puts durch einen verkauften Call und begrenzt beide Seiten.`,T`W_T^{PP}=S_T+(K-S_T)^+=\max(S_T,K)`),S('Spreads, Volatilität und Pfadabhängigkeit',`Ein Bull Call Spread kauft einen Call mit niedrigerem und verkauft einen mit höherem Strike. Die Auszahlung ist unterhalb des ersten Strikes null, steigt dazwischen linear und ist darüber begrenzt. Die niedrigere Prämie gegenüber einem einzelnen Call wird durch den Verzicht auf weitere Gewinne bezahlt.

Straddles und Strangles reagieren auf Bewegungsgröße und Volatilität, nicht nur auf Richtung. Ein positiver Optionsgewinn setzt trotzdem voraus, dass realisierte Endbewegung und Preisänderungen die bezahlte Prämie rechtfertigen. Endauszahlungsdiagramme zeigen nicht alle zwischenzeitlichen Margin- und Liquiditätsrisiken.`,T`X_T=(S_T-K_1)^+-(S_T-K_2)^+,\quad 0\le X_T\le K_2-K_1`)],C('Gleicher Aktienbestand, verschiedene Schutzrechte','Aktie heute 100. Put K = 90 kostet 4; Call K = 110 bringt 4. Zinsen null.',['Endkurs','Aktie allein: Gewinn','Protective Put: Gewinn','Collar: Gewinn'],[['60','−40','−14','−10'],['100','0','−4','0'],['140','40','36','10']],'Beim Put beträgt der Gesamteinsatz 104 und der Mindestendwert 90. Beim Collar kompensieren sich die angenommenen Prämien, dafür wird der Endwert auf 110 begrenzt. Gleiche Schutzwirkung nach unten kann somit durch Prämienzahlung oder Verzicht auf Aufwärtsgewinn finanziert werden.'),[['derivatives-06','Auszahlung und Gewinn getrennt berechnen.'],['path-wealth-05','Konzentrierte Aktienpositionen absichern.']]),
D([S('CDS tauscht Prämien gegen Ausfallschutz',`Der Käufer von Kreditschutz zahlt laufende Prämien und erhält bei einem definierten Kreditereignis eine vertraglich bestimmte Ausgleichszahlung. Im vereinfachten Modell entspricht diese Nominal mal Verlustquote. Tatsächliche Ereignisdefinition, Referenzverbindlichkeit und Abwicklung sind wesentlich.

Der faire Spread setzt Barwert der Prämienseite und Schutzseite gleich. Prämien werden nur unter den vertraglichen Bedingungen bis Ausfall oder Fälligkeit gezahlt; aufgelaufene Prämien im Ausfall und konkrete Termine müssen in einer vollständigen Bewertung ergänzt werden.`,T`s\sum_i\alpha_iDF_iQ_i\approx LGD\sum_iDF_i(Q_{i-1}-Q_i)`),S('Hazard-Näherung und Basisrisiko',`Bei konstanten Größen und vereinfachter kontinuierlicher Zahlung ergibt sich die Näherung Spread gleich Hazardrate mal Verlustquote. Sie ist nützlich zur Intuition, ersetzt aber keine vollständige Kurvenkalibrierung. Risikoneutrale Hazardraten werden aus Preisen abgeleitet und enthalten Risikoprämien.

Eine Anleihe plus CDS ist nicht in jeder Hinsicht risikofrei. Finanzierung, Liquidität, Lieferbarkeit, Gegenpartei und Vertragsdefinition können Restexponierungen erzeugen. Die CDS-Bond-Basis misst einen Preisunterschied verwandter Kreditexposures, dessen Handel eigene Risiken besitzt.`,T`s\approx\lambda(1-RR)`)],C('Gleiche Ausfallintensität, andere Recovery','Konstante Hazardrate 2 %, vereinfachte Spreadnäherung.',['Recovery','LGD','Fairer Spread ungefähr'],[['20 %','80 %','160 Basispunkte'],['40 %','60 %','120 Basispunkte'],['60 %','40 %','80 Basispunkte']],'Je größer der bedingte Verlust, desto mehr Schutzleistung wird erwartet und desto höher die faire Prämie. Ein beobachteter Spread kann deshalb nicht ohne Recoveryannahme direkt als Ausfallwahrscheinlichkeit gelesen werden.'),[['bonds-10','Hazardrate und kumulierte PD unterscheiden.'],['bonds-11','Kreditspreads in ihre wirtschaftlichen Komponenten zerlegen.']]),
D([S('Hedge nach Risikofaktor statt nur Nominalbetrag',`Eine Absicherung wird aus dem zu reduzierenden wirtschaftlichen Risiko abgeleitet. Für Aktien kann Betaexponierung relevant sein, für Zinsen DV01 oder Key-Rate-Vektoren, für Währungen der tatsächlich offene Betrag. Gleiche Nominalbeträge können sehr unterschiedliche Sensitivitäten besitzen.

Bei einem linearen Einfaktorhedge wird die Sensitivität der Ausgangsposition durch die Sensitivität eines Kontrakts geteilt. Das Vorzeichen bestimmt die Gegenposition. Kontraktmultiplikatoren, Währungsumrechnung und Preisnotierung müssen vollständig enthalten sein.`,T`N^*=-\frac{\partial V_P/\partial x}{\partial V_F/\partial x}`),S('Restfehler, Rebalancing und ökonomisches Ziel',`Ein Hedge kann lokale Preisvolatilität senken und trotzdem Basis-, Konvexitäts-, Ausfall- oder Liquiditätsrisiko behalten. Sensitivitäten ändern sich mit Marktbewegung und Zeit. Deshalb benötigt eine Absicherungsstrategie Überwachung und Regeln für Anpassung.

Das Ziel kann ein fester Zahlungsbetrag, eine Benchmarkexponierung oder ein Risikobudget sein. Vollständige Absicherung jedes sichtbaren Einzelrisikos muss nicht optimal sein, wenn Risiken im Gesamtportfolio bereits gegenläufig wirken. Kosten und Sicherheitenbedarf gehören zur Nutzenrechnung.`)],C('Gleicher Marktwert, andere Zinssensitivität','Zwei Anleiheportfolios zu je 1 Mio.; Hedgekontrakt-DV01 50 pro Kontrakt.',['Modified Duration','Portfolio-DV01','Benötigte gegenläufige Kontrakte'],[['2','200','4'],['8','800','16']],'Die DV01 entsteht aus Marktwert × Duration × 0,0001. Das zweite Portfolio benötigt viermal so viele Kontrakte, obwohl der Marktwert gleich ist. Die Rechnung gleicht nur den betrachteten parallelen Zinsfaktor aus; Kurven- und Konvexitätsrisiken bleiben gesondert zu prüfen.'),[['bonds-08','DV01 und Key-Rate-Risiko herleiten.'],['advanced-07','Overlays auf Gesamtportfolioebene koordinieren.']])
];
