const {S,C,D,T}=require('./schema.cjs');
function bond(n,c,y,m=1){
 const cash=Array.from({length:n*m},(_,i)=>({t:(i+1)/m,cf:100*c/m+(i===n*m-1?100:0)}));
 const price=cash.reduce((s,x)=>s+x.cf/(1+y/m)**(m*x.t),0);
 const mac=cash.reduce((s,x)=>s+x.t*x.cf/(1+y/m)**(m*x.t),0)/price;
 const conv=cash.reduce((s,x)=>s+x.cf*x.t*(x.t+1/m)/(1+y/m)**(m*x.t+2),0)/price;
 return {price,mac,mod:mac/(1+y/m),conv,dv01:price*mac/(1+y/m)*.0001,cash};
}
const f=(n,d=4)=>n.toLocaleString('de-DE',{minimumFractionDigits:d,maximumFractionDigits:d});
const rows=cases=>cases.map(([label,n,c,y,m=1])=>{const b=bond(n,c,y,m),shock=bond(n,c,y+.01,m);return [label,f(b.price,2),f(b.mac),f(b.mod),f(b.dv01),f((shock.price/b.price-1)*100,3)+' %'];});
const b=bond(3,.05,.05),h=.001,pminus=bond(3,.05,.05-h).price,pplus=bond(3,.05,.05+h).price;
module.exports=D([
S('1. Ausgangspunkt: Welche Größe wird verändert, welche bleibt fest?',`Zinsänderungsrisiko beginnt bei einer Bewertungsfunktion. Eine festverzinsliche Anleihe verspricht zu bestimmten Zeitpunkten feste Cashflows. Der Preis ergibt sich aus deren Barwerten. Ändert sich nur der Diskontsatz, ändern sich diese Barwerte, obwohl keine vertragliche Zahlung geändert wird. Die Duration beschreibt eine lokale Eigenschaft dieser Preisfunktion. Sie ist weder die zugesagte Endfälligkeit noch eine Prognose des künftigen Zinssatzes.

Wir betrachten zunächst eine Bewertung direkt nach einem Kupontermin, positive feste Cashflows, keine eingebettete Option und keine Änderung der Bonität. F ist der Nennwert, c der jährliche Kuponsatz, m die Zahl der Kuponzahlungen pro Jahr, T die Restlaufzeit in Jahren und n=mT die Periodenzahl. y ist eine nominale Jahresrendite mit m-facher Verzinsung; pro Periode wird daher mit y/m diskontiert. P bezeichnet den vollen Preis. Bei Bewertung zwischen Kuponterminen sind die tatsächlichen verbleibenden Zeitabstände und der Dirty Price zu verwenden.`,T`P(y)=\sum_{k=1}^{n}\frac{CF_k}{(1+y/m)^k},\quad CF_k=\frac{Fc}{m}+F\mathbf1_{\{k=n\}},\quad t_k=\frac{k}{m}`),
S('2. Macaulay Duration: der Schwerpunkt der abgezinsten Zahlungen',`Jede Zahlung erhält ein Gewicht gleich ihrem Barwert geteilt durch den gesamten Anleihepreis. Die Gewichte summieren sich zu eins. Die Macaulay Duration ist der gewichtete Durchschnitt der Zahlungszeitpunkte in Jahren. Es werden Barwerte gewichtet, nicht die Nominalbeträge der Kupons. Eine hohe späte Rückzahlung kann deshalb weniger Gewicht besitzen, als ihr Nominalanteil vermuten lässt.

Bei einem Zero-Coupon-Bond gibt es nur eine Zahlung. Ihr Gewicht beträgt eins; die Macaulay Duration ist exakt T. Bei einer gewöhnlichen Kuponanleihe mit positiven Zwischenzahlungen liegt sie vor der Endfälligkeit. Dieser Schwerpunkt darf nicht als Amortisationszeit missverstanden werden: Er gibt nicht den Zeitpunkt an, bis zu dem kumulierte Kupons den Kaufpreis zurückgezahlt haben. Er ist eine Gewichtungsgröße mit einer wichtigen Verbindung zur Zinsableitung.`,T`w_k=\frac{CF_k(1+y/m)^{-k}}{P},\quad\sum_kw_k=1,\quad D_{\mathrm{Mac}}=\sum_kt_kw_k=\frac{\sum_k(k/m)CF_k(1+y/m)^{-k}}{P}`),
S('3. Herleitung der Modified Duration aus der Preisableitung',`Um die Preiswirkung einer sehr kleinen Renditeänderung zu bestimmen, leiten wir jeden diskontierten Cashflow nach der Jahresrendite y ab. Die Potenzregel liefert −k, die innere Ableitung von 1+y/m zusätzlich 1/m. Diese zweite Komponente ist der Grund, warum eine Halbjahresrendite nicht ohne Umrechnung mit einer Jahresduration kombiniert werden darf.

Nach Ausklammern von 1/(1+y/m) bleibt genau die Zahlungszeitsumme der Macaulay Duration übrig. Die Modified Duration normiert die negative Preisableitung durch den aktuellen Preis. Damit wird aus einer absoluten Preisänderung eine relative Empfindlichkeit. Sie ist bei positiven festen Cashflows positiv; das Minuszeichen gehört in die Preisänderungsformel. Eine Modified Duration von 7 bedeutet näherungsweise −7 % Preisänderung bei +1 Prozentpunkt Jahresrendite, nicht −7 % bei einem relativen Zinsanstieg um 1 %.`,T`\frac{\partial P}{\partial y}=-\sum_k\frac{k}{m}CF_k(1+y/m)^{-k-1}=-\frac{P D_{\mathrm{Mac}}}{1+y/m}\quad\Longrightarrow\quad D_{\mathrm{mod}}=-\frac1P\frac{\partial P}{\partial y}=\frac{D_{\mathrm{Mac}}}{1+y/m}`),
S('4. Periodenabgleich und stetige Verzinsung',`Bei halbjährlicher Kuponzahlung wird eine zunächst in Halbjahresperioden errechnete Macaulay Duration durch zwei geteilt, bevor sie als Jahre interpretiert wird. Für die Umrechnung zur jährlichen Modified Duration ist anschließend 1+y/2 der Divisor. Die Abkürzung „Macaulay durch eins plus Rendite“ ist deshalb nur bei jährlicher Zahlung vollständig.

Bei stetiger Verzinsung r lautet der Diskontfaktor exp(−rt). Seine Ableitung ist −t exp(−rt), ohne den zusätzlichen diskreten Verzinsungsfaktor. Die relative Empfindlichkeit gegenüber r entspricht dann der barwertgewichteten Zahlungszeit. Die gleiche Preisfunktion wird nach unterschiedlich definierten Zinsvariablen abgeleitet. Um Jahresrendite y und stetigen Satz r zu vergleichen, verwendet man r=m ln(1+y/m); die Kettenregel liefert wieder denselben Umrechnungsfaktor.`,T`D_{\mathrm{Mac,J}}=\frac{D_{\mathrm{Mac,Per}}}{m},\quad r=m\ln(1+y/m),\quad P(r)=\sum_kCF_ke^{-rt_k},\quad-\frac1P\frac{\partial P}{\partial r}=\sum_kt_kw_k`),
S('5. Money Duration, DV01 und PVBP: von Prozenten zu Geld',`Zwei Positionen können dieselbe Modified Duration besitzen und trotzdem sehr unterschiedliche Geldverluste verursachen. Money Duration multipliziert die relative Empfindlichkeit mit dem Marktwert V der Position. Multipliziert man zusätzlich mit 0,0001, erhält man die angenäherte Wertänderung für einen Basispunkt. DV01 und PVBP werden häufig als positive Risikobeträge berichtet; das Vorzeichen des Ergebnisses folgt aus Positionsrichtung und Renditebewegung.

Ein Anleihepreis von 100 ist eine Notierung je 100 Nennwert und noch kein Portfoliowert. Bei 2 Mio. Nennwert und Preis 98 beträgt der Marktwert 1,96 Mio. Die Money Duration muss mit diesem Marktwert berechnet werden. Werden Sensitivitäten über Positionen addiert, müssen Währung, Renditevariable und Vorzeichen übereinstimmen. Ein Netto-DV01 nahe null kann erhebliche gegenläufige Risiken an verschiedenen Laufzeiten verbergen.`,T`D_{\mathrm{money}}=VD_{\mathrm{mod}},\quad\mathrm{DV01}\approx10^{-4}VD_{\mathrm{mod}},\quad\Delta V\approx-VD_{\mathrm{mod}}\Delta y=-\mathrm{DV01}\cdot\Delta y_{\mathrm{bp}}`),
S('6. Warum die lineare Näherung ungenau wird: Konvexität',`Die erste Ableitung ist die Tangentensteigung an der aktuellen Stelle. Die exakte Preisfunktion einer optionsfreien Anleihe ist gekrümmt, weil Zinsen in den Nennern aller diskontierten Zahlungen stehen. Eine zweite Ableitung erfasst, wie sich die Steigung selbst verändert. Nach Normierung durch P heißt diese Größe hier Konvexität C_y; ihre Definition muss zur gleichen Jahresrendite y und Zahlungsfrequenz m passen.

Die Taylorentwicklung erklärt sowohl das Minuszeichen der Duration als auch den Faktor ein Halb vor der Konvexität. Bei positiven festen Cashflows ist die zweite Ableitung positiv. Ein gleich großer Zinsrückgang erzeugt daher einen größeren Preisgewinn als der Preisverlust beim entsprechenden Zinsanstieg. Die Korrektur ist auf beiden Seiten positiv. Bei großen Schocks werden weitere Ableitungen relevant; die vollständige Neubewertung ist dann der bessere Vergleichsmaßstab.`,T`C_y=\frac1P\frac{\partial^2P}{\partial y^2}=\frac1P\sum_k\frac{t_k(t_k+1/m)CF_k}{(1+y/m)^{k+2}},\quad\frac{\Delta P}{P}\approx-D_{\mathrm{mod}}\Delta y+\frac12C_y(\Delta y)^2`),
S('7. Numerische Duration: dieselbe Ableitung mit zwei Neubewertungen',`Nicht jede Bewertungsfunktion liegt als leicht ableitbare Formel vor. Dann wird der Preis bei einer kleinen Absenkung und Erhöhung der Rendite erneut berechnet. Die symmetrische Differenz approximiert die erste Ableitung; die zweite Differenz approximiert die Krümmung. Der Schock h muss in Dezimaleinheiten eingesetzt werden. Zehn Basispunkte sind 0,001.

Bleiben die Cashflows fest und wird nur die eigene Yield to Maturity verändert, approximiert diese Rechnung die Modified Duration. Wird dagegen eine Benchmarkkurve verschoben und werden zinsabhängige Cashflows im Modell neu bestimmt, spricht man von Effective Duration. Die äußere Formel sieht ähnlich aus, aber die Neubewertungen beantworten andere Fragen. Für Optionen kann derselbe Zinsschock eine Kündigung auslösen oder verhindern; dort reicht das Diskontieren unveränderter Cashflows nicht aus.`,T`D_{\mathrm{approx}}=\frac{P(y-h)-P(y+h)}{2hP(y)},\quad C_{\mathrm{approx}}=\frac{P(y-h)+P(y+h)-2P(y)}{h^2P(y)},\quad D_{\mathrm{eff}}=\frac{P_{-}-P_{+}}{2hP_0}`),
S('8. Key Rate, Fisher-Weil, Spread und empirische Duration',`Eine Zinskurve kann sich versteilen oder verdrehen. Key Rate Duration verschiebt einen definierten Kurvenknoten, während die übrigen Knoten unverändert bleiben und Zwischenbereiche nach einer festgelegten Interpolation angepasst werden. Der Vektor der Key-Rate-Durations zeigt, wo das Risiko liegt. Wenn sich die einzelnen Kurvenschocks zu einer Parallelverschiebung addieren und alle Konventionen konsistent sind, addieren sich die lokalen Beiträge näherungsweise zur entsprechenden Parallel-Duration.

Fisher-Weil Duration verwendet für jede Zahlung ihren eigenen Spotdiskontfaktor. Bei stetigen Spot Rates und einem additiven parallelen Schock der Spotkurve entspricht die Sensitivität wieder dem barwertgewichteten Zahlungszeitpunkt. Sie ist nicht allgemein dieselbe Zahl wie eine Yield-basierte Duration. Spread Duration verändert den Kreditspread z bei festgehaltener Referenzkurve. Empirische Duration schätzt historische Preisreaktionen statistisch; sie enthält die damaligen gemeinsamen Bewegungen von Zinsen, Spreads und weiteren Faktoren und ist keine reine Vertragsableitung.`,T`\mathrm{KRD}_j=-\frac1P\frac{\partial P}{\partial s_j},\quad\frac{\Delta P}{P}\approx-\sum_j\mathrm{KRD}_j\Delta s_j-D_s\Delta z,\quad D_{\mathrm{FW}}=\frac{\sum_kt_kCF_ke^{-s(t_k)t_k}}{P},\quad D_s=-\frac1P\frac{\partial P}{\partial z}`),
S('9. Laufzeit, Kupon und Rendite getrennt untersuchen',`Die folgenden Vergleiche ändern jeweils nur einen Einflussfaktor. Bei gleicher positiver Rendite und gleichem Kuponsatz führt eine längere übliche Laufzeit dazu, dass mehr Barwert in ferneren Zeitpunkten liegt. Die Modified Duration wächst und derselbe Zinsschock verursacht einen größeren relativen Verlust. Der Kupon verändert dagegen die Verteilung innerhalb derselben Laufzeit: Hohe Kupons holen Gewicht nach vorne; ein Zero-Coupon-Bond konzentriert alles auf die Endfälligkeit.

Bei höherem Diskontsatz verlieren ferne Zahlungen relativ zu frühen Zahlungen stärker an Gewicht. Für feste positive Cashflows nimmt die Macaulay Duration deshalb mit y ab; ihre Ableitung hängt von der Streuung der Zahlungszeitpunkte ab. Bei einem Zero ist diese Streuung null und Macaulay bleibt exakt T, während Modified wegen des Divisors dennoch sinkt. „Längere Laufzeit bedeutet immer höhere Duration“ ist keine universelle Regel: Stark unter pari notierende Anleihen mit sehr langen Laufzeiten können ein nichtmonotones Verhältnis zeigen. Negative Cashflows, Optionen und veränderte Vertragsbedingungen verlangen eine eigene Analyse.`,T`\frac{\partial D_{\mathrm{Mac}}}{\partial y}=-\frac{\sum_kw_k(t_k-D_{\mathrm{Mac}})^2}{1+y/m}\leq0,\quad D_{\mathrm{Mac,Zero}}=T,\quad D_{\mathrm{mod,Zero}}=\frac{T}{1+y/m}`),
S('10. Preisrisiko, Wiederanlagerisiko und Anlagehorizont',`Ein Anleger, der vor Fälligkeit verkauft, trägt Kursrisiko. Wer Kupons erhält, trägt zusätzlich Wiederanlagerisiko. Steigende Zinsen senken zunächst den Marktpreis, ermöglichen aber höhere Erträge auf wiederangelegte Kupons. Unter den klassischen Annahmen einer kleinen sofortigen parallelen und danach konstanten Renditeänderung kompensieren sich diese Effekte lokal, wenn der Anlagehorizont der Macaulay Duration entspricht.

Werden alle Zahlungen zum Horizont H zu demselben Satz auf- beziehungsweise abgezinst, ist das Horizontvermögen P(y)(1+y/m)^{mH}. Seine logarithmische Ableitung ist proportional zu H−D_Mac. Ein Horizont unterhalb der Duration wird vom Preiseffekt dominiert; oberhalb gewinnt der Wiederanlageeffekt relativ an Bedeutung. Das ist keine Verlustgarantie: Kurvenbewegungen, Ausfälle, Kuponoptionen, Handelskosten und spätere Schocks können den Abgleich durchbrechen. Für Pensionspläne zählt außerdem das Risiko relativ zu den Verpflichtungen.`,T`W_H(y)=P(y)(1+y/m)^{mH},\quad\frac1{W_H}\frac{\partial W_H}{\partial y}=\frac{H-D_{\mathrm{Mac}}}{1+y/m}`)
],[
C('A. Eine Duration vollständig aus den Cashflows berechnen','Drei Jahre, Nennwert 100, jährlicher Kupon 5 %, Rendite 5 %. Die Zahlen folgen direkt aus dem Zahlungsplan.',['Jahr t','CF','Barwert bei 5 %','Gewicht','t × Gewicht'],b.cash.map(x=>{const pv=x.cf/1.05**x.t,w=pv/b.price;return [String(x.t),f(x.cf,2),f(pv),f(w*100,3)+' %',f(x.t*w)];}),`Der Preis ist die Summe der Barwerte und beträgt 100. Die letzte Spalte summiert sich zur Macaulay Duration von ${f(b.mac)} Jahren. Erst die Division durch 1,05 liefert Modified Duration ${f(b.mod)}. Bei einer Million Euro Marktwert beträgt DV01 rund ${f(1e6*b.mod*.0001,2)} €. Ein Renditeanstieg um zehn Basispunkte bedeutet linear einen Verlust von rund ${f(1e6*b.mod*.001,2)} €.

Mit h=0,001 liefert die Neubewertung P₋=${f(pminus)} und P₊=${f(pplus)}. Die symmetrische Formel ergibt ${f((pminus-pplus)/(2*h*b.price))}, nahezu denselben Wert wie die analytische Modified Duration. Zahlungsgewichtung, Ableitung und Preisszenarien sind drei Zugänge zum selben lokalen Zusammenhang.`),
C('B. Nur die Laufzeit verändern','Alle Anleihen: Nennwert 100, jährlicher Kupon 5 %, Anfangsrendite 5 %. Zinsschock jeweils +100 Basispunkte.',['Restlaufzeit','Preis','D Mac (Jahre)','D mod','DV01 je 100','Exakter Preiseffekt'],rows([['2 Jahre',2,.05,.05],['10 Jahre',10,.05,.05],['30 Jahre',30,.05,.05]]),`Alle Ausgangspreise sind 100, weil Kupon und Rendite übereinstimmen. Die verschiedenen Verluste entstehen aus der zeitlichen Verteilung der Zahlungen, nicht aus einem anderen Einstiegspreis. Die Tabelle quantifiziert den Zusammenhang zwischen längerer Kapitalbindung und höherem Zinsänderungsrisiko.

Duration wächst nicht proportional zur Endfälligkeit: Der 30-jährige Bond zahlt viele Kupons deutlich vor Jahr 30. Wer allein die Endfälligkeiten durcheinander teilt, überschätzt den relativen Risikounterschied dieser Kuponanleihen.`),
C('C. Gleiche Laufzeit, anderer Kupon','Zehn Jahre Restlaufzeit, Rendite 5 %, jährliche Zahlung. Nur der Kupon wird verändert.',['Kupon','Preis','D Mac (Jahre)','D mod','DV01 je 100','Exakter Effekt +1 pp'],rows([['0 %',10,0,.05],['5 %',10,.05,.05],['10 %',10,.10,.05]]),`Beim Zero liegt das gesamte Gewicht in Jahr 10. Höhere Kupons verschieben Gewicht nach vorne und verringern die relative Preisempfindlichkeit. Gleichzeitig steigt der Preis pro 100 Nennwert. Relative Duration und absolute DV01 pro 100 Nennwert sind deshalb nicht gleichbedeutend: Der höhere Preis kann die Wirkung einer geringeren Duration ausgleichen.

Für ein gleiches Anlagebudget von einer Million Euro gilt in jeder Zeile DV01=100×D_mod Euro. Ein Vergleich mit gleichem Nennwert beantwortet dagegen die Frage nach einer gleichen Zahl vertraglicher Rückzahlungsansprüche. Vor dem Vergleich absoluter Risiken muss diese Bezugsbasis festgelegt werden.`),
C('D. Gleicher Vertrag, anderer Ausgangszins','Zehn Jahre, Kupon 5 %, Nennwert 100. Jede Zeile beginnt auf einem anderen Renditeniveau und erhält dann denselben Schock von +1 Prozentpunkt.',['Anfangsrendite','Preis','D Mac (Jahre)','D mod','DV01 je 100','Exakter Preiseffekt'],rows([['2 %',10,.05,.02],['5 %',10,.05,.05],['10 %',10,.05,.10]]),`Die Vertragszahlungen bleiben gleich. Niedrige Renditen geben späten Zahlungen relativ mehr Gewicht und erzeugen höhere Modified Duration. Die Sensitivität lässt sich daher nicht unverändert aus einer Hochzinsphase in eine Niedrigzinsphase übertragen.

Ein Anstieg von 2 % auf 3 % und von 10 % auf 11 % beträgt jeweils einen Prozentpunkt. Die relativen Änderungen des Zinssatzes von 50 % beziehungsweise 10 % sind nicht die in die Durationformel einzusetzende Schockgröße.`),
C('E. Tangente, Krümmung und exakte Neubewertung','Zehn Jahre, Kupon und Anfangsrendite jeweils 5 %. Für beide Schockrichtungen werden dieselben Cashflows bewertet.',['Schock Δy','Nur Duration','Duration + Konvexität','Exakte Änderung'],[-.02,-.01,.01,.02].map(d=>{const q=bond(10,.05,.05);return [f(d*100,1)+' pp',f(-q.mod*d*100,3)+' %',f((-q.mod*d+.5*q.conv*d*d)*100,3)+' %',f((bond(10,.05,.05+d).price/q.price-1)*100,3)+' %'];}),`Die lineare Schätzung liefert für gleich große Schocks betragsgleiche Gewinne und Verluste. Die exakte Rechnung zeigt positive Konvexität. Die zweite Ordnung verkleinert den Näherungsfehler deutlich, bleibt bei großen Schocks aber ebenfalls eine Näherung.

Die Vorzeichen lassen sich ökonomisch kontrollieren: Steigende Renditen senken bei unverändert positiven Cashflows den Preis. Bei einem Zinsrückgang macht positive Krümmung den Gewinn größer als die reine Tangente; bei einem Anstieg macht sie den Verlust kleiner. Ein falsches Vorzeichen der Konvexitätskorrektur würde diesen Zusammenhang zerstören.`)
],[['bonds-05','Die Preisfunktion und ihre Cashflows sind die Grundlage jeder Duration.'],['bonds-06','Spotkurven erklären, warum ein einziger YTM nicht jedes Kurvenrisiko beschreibt.'],['bonds-14','Vorzahlungen verändern Cashflows und verlangen effektive Maße.'],['derivatives-09','Delta und Gamma sind die analogen ersten und zweiten Sensitivitäten bei Optionen.'],['path-portfolio-03','Immunisierung gleicht Vermögen und Verpflichtungen auf derselben Sensitivitätsbasis ab.']],
[['P,V','Voller Anleihepreis beziehungsweise Marktwert der Position','Währung'],['CF_k,F','Zahlung in Periode k beziehungsweise Nennwert','Währung'],['c,y','Jährlicher Kuponsatz und nominale Jahresrendite','Dezimalrate'],['m,n,T,t_k','Zahlungen pro Jahr, Perioden, Restlaufzeit, Zahlungszeitpunkt','Anzahl / Jahre'],['D_Mac,D_mod','Gewichteter Zahlungszeitpunkt und relative Renditesensitivität','Jahre bei konsistenter Jahresrendite'],['C_y,h','Konvexität bezüglich y und symmetrischer Renditeschock','Jahre² / Dezimalrate'],['s_j,z','Referenzzins am Knoten j und Kreditspread','Dezimalrate']]);
Object.defineProperty(module.exports,'calculateBond',{value:bond,enumerable:false});
