const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Vom Gleichgewicht zur komparativen Statik',`Bei linearer Nachfrage mit Achsenabschnitt a und positiver Steigungskonstante b sowie Angebot mit Achsenabschnitt c und positiver Steigung d wird die gehandelte Menge durch Gleichsetzen bestimmt. Eine Bewegung entlang der Nachfragekurve entsteht durch einen anderen Preis. Ein höheres Einkommen oder eine geänderte Präferenz verschiebt dagegen die ganze Kurve. Ohne diese Trennung kann eine beobachtete Preis-Mengen-Korrelation nicht kausal interpretiert werden.

Differenziert man den Gleichgewichtspreis nach a, erkennt man, dass eine stärkere Angebotsreaktion den Preisanstieg dämpft. Der zusätzliche Nachfrageimpuls wird dann stärker durch Mengenanpassung aufgenommen. Kurzfristig starre Kapazitäten und langfristig elastischeres Angebot können deshalb sehr unterschiedliche Preisreaktionen auf denselben Schock erzeugen.`,T`Q_D=a-bP,\quad Q_S=c+dP,\quad P^*=\frac{a-c}{b+d},\quad \frac{\partial P^*}{\partial a}=\frac1{b+d}`),S('Elastizität, Umsatz und Steuerlast verbinden',`Die Punktelastizität normiert eine Ableitung durch Preis und Menge. Dieselbe lineare Nachfragesteigung hat entlang der Kurve unterschiedliche Elastizität. Bei diskreten Änderungen vermeidet die Mittelpunktmethode, dass das Ergebnis von der gewählten Ausgangsrichtung abhängt.

Umsatz ist Preis mal Menge. Seine Ableitung enthält den direkten Preiseffekt und den indirekten Mengeneffekt. Bei betragsmäßig elastischer Nachfrage überwiegt der Mengenrückgang; eine Preiserhöhung senkt den Umsatz. Bei einer kleinen Stücksteuer verteilt sich die Last im Wettbewerbsmodell nach den relativen Elastizitäten. Die gesetzliche Abführung der Steuer legt nicht allein fest, wer sie wirtschaftlich trägt.`,T`\varepsilon_D=\frac{dQ}{dP}\frac{P}{Q},\quad \frac{d(PQ)}{dP}=Q(1+\varepsilon_D),\quad \frac{dP_c}{d\tau}=\frac{\varepsilon_S}{\varepsilon_S-\varepsilon_D}`)],C('Gleiche Nachfrageverschiebung, andere Angebotsflexibilität','Nachfrage Q = 100 − P, Angebot zunächst Q = dP. Danach steigt der Nachfrageabschnitt von 100 auf 110.',['d','Preis vorher','Preis nachher','Preisanstieg'],[['1','50','55','5'],['4','20','22','2']],'Bei elastischerem Angebot steigt die Menge stärker und der Preis schwächer. Die Rechnung setzt lineare Kurven und Wettbewerb voraus. Sie zeigt einen Mechanismus, keine allgemeine empirische Vorhersage für jeden Markt.'),[['equity-05','Preissetzung verändert Umsatz und Marge.'],['economics-03','Marktmacht verändert die Preissetzungsbedingung.']]),
D([S('Marginale Entscheidung und Gesamtrentabilität',`Gewinn ergibt sich aus Umsatz abzüglich variabler und fixer Kosten. Im Preisnehmermodell ist der zusätzliche Umsatz einer Einheit der Marktpreis. Für ein inneres Maximum muss der Preis den Grenzkosten entsprechen; zusätzlich muss die lokale Krümmung ein Maximum ergeben. Fixkosten beeinflussen den Gesamtgewinn, aber nicht unmittelbar diese kurzfristige Ableitung.

Kurzfristig kann eine Firma trotz Verlust weiterproduzieren, wenn der Preis vermeidbare variable Durchschnittskosten deckt. Dann trägt die Produktion zu ohnehin anfallenden Fixkosten bei. Langfristig müssen sämtliche vermeidbaren Kosten einschließlich der Opportunitätskosten des Kapitals gedeckt werden. Rechnungslegungsgewinn und ökonomischer Gewinn unterscheiden sich daher.`,T`\pi(Q)=PQ-VC(Q)-FC,\quad \pi'(Q)=P-MC(Q),\quad P=MC(Q),\quad P\ge AVC(Q)`),S('Produktivität übersetzt Inputpreise in Grenzkosten',`Wenn kurzfristig nur Arbeit variabel ist, kostet eine zusätzliche Arbeitseinheit den Lohn w und erzeugt MPL zusätzliche Produkte. Kosten je zusätzlichem Produkt sind daher w geteilt durch MPL. Sinkende Grenzproduktivität erhöht bei konstantem Lohn die Grenzkosten. Eine technische Verbesserung kann diese Beziehung verschieben.

Skalenerträge betreffen dagegen die proportionale Veränderung aller Inputs. Sie sind nicht dasselbe wie kurzfristig abnehmende Grenzerträge eines einzelnen Inputs. Für Unternehmensanalysen ist diese Unterscheidung wichtig: freie Kapazität kann zunächst hohe inkrementelle Margen ermöglichen, während eine neue Fabrik später einen sprunghaften Kapitalbedarf auslöst.`,T`MPL=\frac{\partial Q}{\partial L},\qquad MC=\frac{w}{MPL}`)],C('Gleicher Betrieb, nur Fixkosten ändern','P = 20, variable Kosten Q², daher MC = 2Q und optimale Menge 10.',['Fixkosten','Umsatz','Variable Kosten','Gewinn'],[['50','200','100','50'],['150','200','100','−50']],'Die optimale kurzfristige Menge bleibt 10, weil unvermeidbare Fixkosten die marginale Bedingung nicht verändern. Im zweiten Fall deckt der Beitrag von 100 einen Teil der Fixkosten. Ob weiterproduziert werden sollte, hängt davon ab, welche Kosten durch Stilllegung tatsächlich vermeidbar wären.'),[['corporate-07','Fixkosten erzeugen operative Hebel.'],['economics-04','Produktivität treibt langfristige Produktionsmöglichkeiten.']]),
D([S('Warum ein Monopolist nicht einfach jeden Preis setzen kann',`Auch ein Monopolist ist an die Nachfrage gebunden. Bei einheitlichem Preis muss er für zusätzliche Menge häufig den Preis aller verkauften Einheiten senken. Der Grenzerlös liegt dann unter dem Preis. Für lineare inverse Nachfrage hat die Grenzerlöskurve denselben Achsenabschnitt und die doppelte negative Steigung.

Die Bedingung Grenzerlös gleich Grenzkosten bestimmt die Menge; der zugehörige Preis wird anschließend von der Nachfrage abgelesen. Aus der allgemeinen Grenzerlösform lässt sich der Lerner-Index ableiten. Die Beziehung gilt für die statische Einproduktentscheidung mit differenzierbarer Nachfrage und ist keine universelle Regel für regulierte oder mehrseitige Plattformmärkte.`,T`P=a-bQ,\quad MR=a-2bQ,\quad MR=MC,\quad \frac{P-MC}{P}=-\frac1{\varepsilon_D}`),S('Oligopol: die Reaktion anderer gehört zum Modell',`In einem Oligopol hängt die beste eigene Entscheidung von den erwarteten Entscheidungen der Wettbewerber ab. Cournot modelliert Mengen, Bertrand Preise. Homogene Güter, Kapazitätsgrenzen, Differenzierung und wiederholte Interaktion können die Ergebnisse stark verändern. Eine Marktanteilszahl allein bestimmt deshalb keine nachhaltige Marge.

Ein Wettbewerbsvorteil muss erklären, warum neue Anbieter oder Ersatzprodukte hohe Erträge nicht rasch abbauen. Skaleneffekte, Wechselkosten und Netzeffekte wirken über unterschiedliche Mechanismen. Hohe historische Profitabilität ist erst der Ausgangspunkt der Untersuchung, nicht der Beweis einer dauerhaften Eintrittsbarriere.`)],C('Gleiche Nachfrage und Kosten, andere Marktstruktur','P = 100 − Q und konstante Grenzkosten 20; Fixkosten werden ignoriert.',['Struktur','Menge','Preis','Gewinn'],[['Wettbewerbsbenchmark','80','20','0'],['Monopol','40','60','1.600']],'Im Monopol folgt Q = 40 aus 100 − 2Q = 20. Preis 60 wird erst danach eingesetzt. Gegenüber Wettbewerb werden profitable Transaktionen zwischen den Mengen 40 und 80 nicht durchgeführt; der Wohlfahrtsverlust beträgt als Dreiecksfläche 800. Der Monopolgewinn und dieser Verlust sind verschiedene Größen.'),[['equity-04','Eintrittsbarrieren auf Werttreiber übersetzen.'],['economics-01','Nachfrageelastizität begrenzt den Aufschlag.']]),
D([S('Bestandsidentitäten und Wachstumsursachen unterscheiden',`Die Verwendungsrechnung zerlegt inländische Produktion in Konsum, Investitionen, Staatsnachfrage und Nettoexporte. Importe werden abgezogen, weil sie bereits in Ausgaben enthalten sein können, ohne inländische Produktion zu sein. Transfers sind keine direkte staatliche Nachfrage nach neu produzierten Gütern. Nominales Wachstum vermischt Preis- und Mengenänderungen.

Eine Produktionsfunktion erklärt dagegen mögliche Ursachen realer Produktion. In der Cobb-Douglas-Darstellung werden Kapital und Arbeit mit ihren Elastizitäten gewichtet. Logarithmisches Differenzieren liefert die Wachstumszerlegung. Das verbleibende Produktivitätswachstum ist ein Residuum und kann auch Messfehler, Auslastungsänderungen oder ausgelassene Faktoren enthalten.`,T`Y=C+I+G+X-M,\quad Y=AK^\alpha L^{1-\alpha},\quad g_Y\approx g_A+\alpha g_K+(1-\alpha)g_L`),S('Kapitalvertiefung und langfristiges Pro-Kopf-Wachstum',`Mehr Kapital je Beschäftigtem steigert bei abnehmenden Grenzerträgen zunächst die Produktion je Beschäftigtem, aber immer weniger stark. Im einfachen Solow-Modell muss Investition Abschreibung, Bevölkerungswachstum und technischen Fortschritt ausgleichen, um Kapital je effektiver Arbeitseinheit konstant zu halten.

Eine höhere Sparquote kann das langfristige Produktionsniveau erhöhen, ohne dauerhaft die Wachstumsrate je effektiver Arbeitseinheit zu steigern. Dauerhaftes Pro-Kopf-Wachstum benötigt im Basismodell technischen Fortschritt. Für Kapitalmarktprognosen folgt daraus: Eine Phase hoher Investitionen darf nicht ohne Prüfung als unbegrenzt fortsetzbare Wachstumsrate in einen Terminal Value übernommen werden.`,T`\dot k=sf(k)-(\delta+n+g)k`)],C('Gleicher Kapitalzuwachs, anderer Produktivitätspfad','Kapital wächst 4 %, Arbeit 1 %, Kapitalelastizität α = 0,3.',['TFP-Wachstum','Kapitalbeitrag','Arbeitsbeitrag','Outputwachstum ungefähr'],[['0 %','1,2 %','0,7 %','1,9 %'],['2 %','1,2 %','0,7 %','3,9 %']],'Der Unterschied von zwei Prozentpunkten kommt vollständig aus Produktivität, nicht aus mehr Inputs. Die Beiträge sind gewichtete Wachstumsraten. Eine beobachtete Wachstumszahl allein zeigt deshalb noch nicht, ob ein Land durch Faktoreinsatz oder durch höhere Effizienz wächst.'),[['equity-05','Dauerwachstum an realistische Werttreiber binden.'],['advanced-01','Makroannahmen in Kapitalmarkterwartungen übersetzen.']]),
D([S('Niveau, Wachstumsrate und Überraschung',`Ein Index kann weiter wachsen und trotzdem eine Abschwächung anzeigen, wenn seine Wachstumsrate sinkt. Für Märkte kommt eine weitere Ebene hinzu: Eine schwache Veröffentlichung kann positiv überraschen, wenn noch schlechtere Werte eingepreist waren. Konjunkturanalyse muss deshalb Niveau, Veränderung und Erwartungsabweichung getrennt berichten.

Die Outputlücke vergleicht tatsächliche mit geschätzter potenzieller Produktion. Das Potenzial ist unbeobachtet und wird revidiert. Eine rückblickend klare Rezession kann mit Echtzeitdaten erheblich unsicherer gewesen sein. Backtests mit endgültig revidierten Daten überschätzen dann die damals mögliche Prognosequalität.`,T`x_t=\frac{Y_t-Y_t^*}{Y_t^*},\qquad u_t=z_t-E_{t-1}[z_t]`),S('Lager, Kredit und Investitionen erzeugen Verstärkung',`Unternehmen passen Produktion nicht nur an den laufenden Absatz, sondern auch an gewünschte Lagerbestände an. Eine kleine Nachfrageänderung kann daher einen größeren Produktionsimpuls auslösen. Bei Investitionen verstärken lange Planungsfristen und Fixkosten die Reaktion. Kreditbedingungen wirken zusätzlich auf Nachfrage und Finanzierungsmöglichkeiten.

Frühindikatoren sind nützlich, wenn sie einen plausiblen Vorlaufmechanismus besitzen; sie bleiben fehleranfällig. Eine invertierte Zinskurve kann Erwartungen künftiger Zinssenkungen enthalten, aber auch Laufzeitprämien verändern ihre Form. Mehrere voneinander unabhängige Informationsquellen sind aussagekräftiger als mehrere fast identische Indikatoren.`)],C('Gleiche Veröffentlichung, andere Erwartung','Das reale Wachstum wird mit 1 % veröffentlicht.',['Vorherige Erwartung','Überraschung','Interpretation'],[['0 %','+1 Prozentpunkt','Besser als erwartet'],['2 %','−1 Prozentpunkt','Schlechter als erwartet']],'Die reale Wirtschaftslage ist in beiden Fällen gleich. Die mögliche Marktreaktion unterscheidet sich, weil Preise Erwartungen verarbeiten. Eine Prognose des BIP ist daher noch keine vollständige Prognose von Aktien- oder Anleiherenditen.'),[['quant-11','Prognosen und Strukturbrüche behandeln.'],['economics-07','Erwartungen beeinflussen geldpolitische Transmission.']]),
D([S('Fisher-Beziehung exakt und näherungsweise',`Eine nominale Anlage vermehrt Geldbeträge, Inflation verändert deren Kaufkraft. Reale Bruttorendite entsteht durch Division des nominalen Wachstumsfaktors durch den Preiswachstumsfaktor. Auflösen liefert die exakte Fisher-Beziehung mit Kreuzprodukt. Die häufige Differenz nominaler Zins minus Inflation ist eine Näherung für kleine Raten.

Ex ante verwendet man erwartete Inflation; ex post die tatsächlich eingetretene. Der Unterschied ist Inflationsrisiko. Ein nominal sicherer Endbetrag ist deshalb nicht real sicher. Bei inflationsgebundenen Anleihen können unter anderem Indexverzögerung, steuerliche Behandlung und Liquiditätsunterschiede die Beobachtung beeinflussen.`,T`1+r_{\mathrm{real}}=\frac{1+i}{1+\pi},\quad i=r_{\mathrm{real}}+\pi+r_{\mathrm{real}}\pi`),S('Inflationsdynamik und Arbeitsmarkt',`Nachfrageüberhänge, Angebotsengpässe und veränderte Erwartungen können Inflation über verschiedene Kanäle erhöhen. Ein negativer Angebotsschock kann gleichzeitig Produktion senken und Preise erhöhen. Eine rein nachfrageorientierte Erklärung würde diese Kombination verfehlen.

Eine erwartungserweiterte Phillips-Beziehung verknüpft Inflation mit Erwartungen, Auslastung und Angebotsschocks. Sie ist keine dauerhaft stabile Tauschmöglichkeit zwischen beliebig niedriger Arbeitslosigkeit und hoher Inflation. Wenn Erwartungen reagieren, verändert sich die kurzfristige Beziehung. Für Anleihen sind zusätzlich Realzinsen und Inflationsrisikoprämien relevant.`,T`\pi_t=E_{t-1}[\pi_t]+\kappa x_t+v_t`)],C('Gleicher Nominalzins, andere Kaufkraft','Eine Anlage zahlt nach einem Jahr 105 auf einen Einsatz von 100.',['Inflation','Realer Endwert in heutigen Preisen','Reale Rendite'],[['2 %','102,94','2,94 %'],['5 %','100,00','0 %'],['8 %','97,22','−2,78 %']],'Die Nominalzahlung bleibt unverändert. Jeder reale Endwert entsteht durch Division von 105 durch den jeweiligen Preisfaktor. Die Differenznäherung liefert 3 %, 0 % und −3 %; bei größeren Raten wird ihr Fehler sichtbar.'),[['bonds-07','Nominalzinskurven enthalten mehrere Prämien.'],['path-wealth-03','Ruhestandsziele in Kaufkraft planen.']]),
D([S('Vom Leitzins zu längeren Marktzinsen',`Ein Zentralbanksatz beeinflusst kurzfristige Finanzierung und Erwartungen künftiger Sätze. Ein langfristiger Zins lässt sich näherungsweise in den Durchschnitt erwarteter kurzfristiger Zinsen und eine Laufzeitprämie zerlegen. Eine heutige Zinserhöhung muss daher nicht jeden langfristigen Zins gleich stark anheben: Sie kann zugleich spätere Inflationserwartungen senken.

Weitere Kanäle laufen über Bankkredite, Sicherheitenwerte, Wechselkurse und Vermögenspreise. Ihre Stärke hängt von Finanzierungssystem, Verschuldung, Zinsbindung und Vertrauen ab. Die gleiche Leitzinsänderung trifft einen variabel verschuldeten Haushalt schneller als einen mit langjährig festem Kreditzins.`,T`y_{n,t}\approx\frac1n\sum_{j=0}^{n-1}E_t[i_{t+j}]+TP_{n,t}`),S('Reaktionsregel und kausale Wirkung nicht verwechseln',`Eine Taylor-artige Regel beschreibt eine systematische Reaktion auf Inflations- und Outputabweichungen. Sie ist eine analytische Orientierung und keine universell geltende Vorschrift jeder Zentralbank. Der neutrale Realzins und die Produktionslücke sind zudem geschätzt.

Wenn Zinsen und Inflation gleichzeitig steigen, beweist das nicht, dass höhere Zinsen Inflation verursachen. Die Zentralbank kann gerade auf den Inflationsschock reagieren. Für Wirkungsanalysen muss der unerwartete geldpolitische Impuls von dieser Reaktion getrennt werden. Verzögerungen und Erwartungen erschweren die Identifikation zusätzlich.`,T`i_t=r^*+\pi_t+a(\pi_t-\pi^*)+bx_t`)],C('Gleicher Leitzinsschritt, andere Erwartungsänderung','Eine zweijährige Näherung ohne Laufzeitprämie mittelt heutigen und erwarteten nächstjährigen Jahreszins. Heute steigt der Satz von 3 % auf 4 %.',['Erwartung nächstes Jahr','Zweijahreszins danach','Mechanismus'],[['4 %','4 %','Anhaltend straffe Politik erwartet'],['2 %','3 %','Spätere Lockerung erwartet']],'Der heutige Satz allein bestimmt den längeren Zins nicht. Die Tabelle ist eine arithmetische Erwartungsnäherung; exakte Spot- und Forward-Beziehungen verwenden Wachstumsfaktoren und enthalten gegebenenfalls Risikoprämien.'),[['bonds-06','Zinskurven mit Diskontfaktoren exakt verbinden.'],['economics-05','Überraschungen von angekündigten Schritten unterscheiden.']]),
D([S('Schuldenquote aus der Budgetrestriktion herleiten',`Der Schuldenbestand wächst um Zinszahlungen und das Primärdefizit. Für die Schuldenquote wird der neue Bestand durch das gewachsene nominale BIP geteilt. Dadurch hängt die Quote nicht allein vom Haushaltssaldo ab: Nominales Wachstum kann sie bei unverändertem Schuldenbestand senken.

Bezeichnet s einen Primärüberschuss relativ zum aktuellen BIP, ergibt sich die exakte diskrete Quotengleichung. Bei Zins über Wachstum ist zur Stabilisierung einer positiven Quote grundsätzlich ein entsprechender Überschuss erforderlich. Bewertungseffekte, Wechselkurse, Rekapitalisierungen und andere Bestandsanpassungen müssen für eine tatsächliche Staatsschuldenanalyse zusätzlich berücksichtigt werden.`,T`B_t=(1+i)B_{t-1}-S_t,\quad b_t=\frac{1+i}{1+g}b_{t-1}-s_t,\quad \Delta b_t=\frac{i-g}{1+g}b_{t-1}-s_t`),S('Multiplikator ist modellabhängig',`Im einfachen geschlossenen Nachfragemodell erhöht eine zusätzliche autonome Ausgabe das Einkommen und löst weitere Konsumrunden aus. Mit marginaler Konsumquote c entsteht eine geometrische Reihe. Steuern und Importe verringern die Rückkopplung; Kapazitätsgrenzen, geldpolitische Reaktion und erwartete künftige Steuern verändern den Effekt weiter.

Automatische Stabilisatoren reagieren ohne neuen Beschluss, etwa durch sinkende Steuerzahlungen im Abschwung. Diskretionäre Maßnahmen benötigen Entscheidungen und können verzögert wirken. Der Finanzierungskanal ist für Anleger ebenfalls wichtig: Mehr Emissionen und veränderte Inflationserwartungen können die Zinskurve beeinflussen.`,T`\Delta Y=\frac1{1-c}\Delta G`)],C('Gleiche Ausgangsschuld, anderes Wachstum','Ausgangsquote 100 %, Nominalzins 4 %, Primärsaldo null, keine weiteren Anpassungen.',['Nominalwachstum','Neue Schuldenquote','Änderung'],[['2 %','101,96 %','+1,96 Prozentpunkte'],['4 %','100 %','0'],['6 %','98,11 %','−1,89 Prozentpunkte']],'Die Rechnung lautet jeweils 1,04 geteilt durch den Wachstumsfaktor. Eine sinkende Quote bedeutet im dritten Fall nicht, dass nominale Schulden getilgt wurden; der Nenner wächst schneller als der verzinste Bestand.'),[['bonds-11','Staatliche Kreditfähigkeit beurteilen.'],['economics-04','Nominales und reales Wachstum auseinanderhalten.']]),
D([S('Komparativer Vorteil ist eine Opportunitätskostenrelation',`Ein Land kann bei allen Gütern produktiver sein und trotzdem von Spezialisierung profitieren. Entscheidend ist, auf wie viel eines anderen Gutes es für eine zusätzliche Einheit verzichten muss. Der absolute Arbeitsaufwand und die relativen Opportunitätskosten beantworten verschiedene Fragen.

Handelsgewinne im Grundmodell sind aggregierte Möglichkeiten. Anpassungskosten und Verteilungswirkungen können einzelne Gruppen belasten. Transportkosten, nicht handelbare Leistungen, Faktorbeweglichkeit und strategische Abhängigkeiten begrenzen eine direkte Übertragung des einfachen Zwei-Güter-Modells.`),S('Leistungsbilanz und Finanzierung gemeinsam lesen',`Aus der volkswirtschaftlichen Einkommensidentität folgt, dass die Leistungsbilanz im vereinfachten Rahmen der Differenz zwischen nationalem Sparen und Investieren entspricht. Ein Defizit kann daher mit hoher produktiver Investition oder mit niedrigem Sparen zusammenhängen. Dieselbe Saldenzahl enthält noch kein vollständiges Qualitätsurteil.

In der Zahlungsbilanz steht jeder Transaktion eine Gegenbuchung gegenüber. Die Vorzeichen der Finanzbilanz hängen von der verwendeten Konvention ab; in einer Darstellung als Nettoerwerb von Aktiva minus Nettoaufnahme von Verbindlichkeiten entspricht sie unter Vernachlässigung von Kapitalbilanz und Fehlern der Leistungsbilanz. Reserveänderungen sind Teil dieser Finanzierungssicht.`,T`CA=S-I,\qquad CA+KA=FA\quad(\text{ohne statistische Differenzen})`)],C('Produktivität und relativen Vorteil auseinanderhalten','Benötigte Arbeitsstunden je Einheit: Land A produziert Wein in 1 Stunde und Tuch in 2, Land B Wein in 6 und Tuch in 3.',['Land','Kosten eines Weins in Tuch','Kosten eines Tuchs in Wein','Relativer Vorteil'],[['A','0,5','2','Wein'],['B','2','0,5','Tuch']],'A ist bei beiden Gütern absolut schneller. B hat dennoch geringere Opportunitätskosten bei Tuch. Ein Tauschverhältnis von einem Wein gegen ein Tuch liegt zwischen den jeweiligen Opportunitätskosten und kann beiden nutzen, solange die Modellannahmen gelten.'),[['economics-10','Kapitalströme und Wechselkurse verbinden.'],['economics-12','Handelsgewinne von Verteilungs- und Sicherheitsfragen trennen.']]),
D([S('Notierung zuerst, Interpretation danach',`Definiere S als Einheiten der Heimatwährung je Einheit Fremdwährung. Ein steigendes S bedeutet dann eine Aufwertung der Fremdwährung. Der Kehrwert beschreibt dieselbe wirtschaftliche Relation mit umgekehrter Richtung. Die prozentualen Änderungen sind nicht einfach betragsgleich, weil sie unterschiedliche Ausgangsbasen haben.

Eine ausländische Anlage besitzt zwei Wachstumsfaktoren: lokale Wertentwicklung und Wechselkursentwicklung. Durch Multiplikation entsteht die Heimatrendite einschließlich Kreuzprodukt. Nur bei kleinen Bewegungen ist die Addition eine gute Näherung. Für Absicherung muss zusätzlich feststehen, welcher Betrag zu welchem Zeitpunkt tatsächlich konvertiert wird.`,T`S=\frac{H}{F},\quad S^{-1}=\frac{F}{H},\quad 1+R_H=(1+R_F)\frac{S_1}{S_0}`),S('Realer Wechselkurs und Wechselkurssystem',`Der reale Wechselkurs korrigiert den nominalen Kurs um relative Preisniveaus. Bei der gewählten Notierung kann ein Anstieg anzeigen, dass ausländische Güter relativ teurer werden. Preisindizes, Warenkörbe und Basisjahre müssen vergleichbar interpretiert werden; der Index ist kein direkt handelbarer Kurs.

Ein fester Wechselkurs verschiebt Anpassungsdruck auf Reserven, Geldpolitik, Preise oder Kapitalverkehr. Freier Kapitalverkehr, feste Wechselkurse und autonome Geldpolitik lassen sich im klassischen Trilemma nicht gleichzeitig vollständig sichern. Eine formale Bindung beseitigt deshalb weder Abwertungsrisiko noch die Kosten ihrer Verteidigung.`,T`q=S\frac{P_F}{P_H}`)],C('Gleiche Auslandsanlage, andere Währungsbewegung','Lokale Aktienrendite +10 %, keine Kosten und keine Absicherung.',['Fremdwährung gegenüber Heimat','Heimatrendite','Rechnung'],[['+10 %','21 %','1,10 × 1,10 − 1'],['0 %','10 %','1,10 × 1 − 1'],['−10 %','−1 %','1,10 × 0,90 − 1']],'Ein Währungsverlust von 10 % hebt den lokalen Gewinn von 10 % mehr als auf. Der Kreuzterm beträgt im dritten Fall −1 Prozentpunkt. Wechselkursrisiko ist deshalb Teil der Portfoliorendite und keine bloße Übersetzungsnotiz.'),[['advanced-06','Absicherungsquote im Gesamtportfolio wählen.'],['economics-11','Forwardkurse konsistent aus Zinsen ableiten.']]),
D([S('Gedeckte Zinsparität durch zwei sichere Wege',`Bei S als Heimatwährung je Fremdwährung kann eine Einheit Heimatgeld entweder im Inland verzinst oder sofort in Fremdwährung getauscht, dort angelegt und zum vereinbarten Forwardkurs zurückgetauscht werden. Ohne Kredit-, Liquiditäts- und Transaktionsfriktionen müssen beide sicheren Heimatergebnisse übereinstimmen.

Auflösen nach F liefert die gedeckte Zinsparität. Ein höherer Heimatgeldzins erzeugt bei dieser Notierung einen höheren Forwardkurs. Das ist zunächst eine Arbitragebeziehung, keine Vorhersage, dass der spätere Spotkurs tatsächlich so ausfällt. Bei verschiedenen Laufzeiten müssen Zinskonventionen und Diskontfaktoren exakt übereinstimmen.`,T`1+i_H=\frac1S(1+i_F)F,\quad \frac FS=\frac{1+i_H}{1+i_F}=\frac{DF_F}{DF_H}`),S('Ungedeckte Parität und Kaufkraftparität',`Die ungedeckte Zinsparität ersetzt den gesicherten Forwardkurs durch einen erwarteten künftigen Spotkurs. Sie benötigt eine Aussage über Risiko und erwartete Erträge; deshalb ist sie keine risikolose Arbitrageidentität. Abweichungen können eine Währungsrisikoprämie und Prognosefehler enthalten.

Relative Kaufkraftparität verbindet langfristige nominale Kursänderung mit relativer Inflation. Kurzfristig wirken Kapitalströme, Zinsen, Risiko und nicht handelbare Güter. Unterschiedliche Warenkörbe und Handelskosten begrenzen auch die absolute Kaufkraftparität. Die drei Paritäten sollten deshalb weder als identisch noch als gleich starke Prognosegesetze behandelt werden.`,T`\frac{E[S_1]}{S_0}\approx\frac{1+i_H}{1+i_F},\qquad \frac{S_1}{S_0}\approx\frac{1+\pi_H}{1+\pi_F}`)],C('Nur die Heimatverzinsung ändern','Spot 1,10 Heimatwährung je Fremdwährung; Fremdzins 2 %, Laufzeit ein Jahr.',['Heimatzins','Arbitragefreier Forward','Abweichung vom Spot'],[['2 %','1,1000','0 %'],['5 %','1,13235','+2,94 %'],['0 %','1,07843','−1,96 %']],'Bei 5 % ergibt sich 1,10 × 1,05 / 1,02. Der teurere spätere Fremdwährungskauf gleicht den höheren Heimatgeldzins aus. Würde man den Kehrwert notieren, kehrte sich die Richtung des Auf- beziehungsweise Abschlags um.'),[['derivatives-03','Forwardpreis und Vertragswert unterscheiden.'],['economics-10','Die Notierung legt die Interpretationsrichtung fest.']]),
D([S('Politische Ereignisse in Werttreiber übersetzen',`Ein geopolitisches Ereignis ist noch kein Bewertungsmodell. Der nächste Schritt fragt nach Absatz, Inputkosten, Investitionsbedarf, Steuern, Kapitalzugang und Zahlungsdurchsetzbarkeit. Ein Exportverbot kann Mengen senken; Sanktionen können einen Anspruch rechtlich oder praktisch blockieren; eine Subvention kann Investitionen verlagern. Die Kanäle wirken auf unterschiedliche Zeilen einer Prognose.

Ein pauschaler höherer Diskontsatz kann unpassend sein, wenn das Risiko bereits als geringerer erwarteter Cashflow modelliert wurde. Besonders bei binären Ereignissen ist eine explizite Szenariorechnung oft verständlicher. Abhängigkeiten zwischen Ländern und Lieferanten bestimmen, ob mehrere vermeintlich getrennte Positionen gleichzeitig betroffen sind.`,T`V_0=\sum_s p_s\sum_t\frac{CF_{t,s}}{(1+r_s)^t},\qquad \sum_s p_s=1`),S('Unsicherheit, Resilienz und Modellgrenzen',`Historische Ereignishäufigkeiten liefern bei einmaligen politischen Entscheidungen nur begrenzte Wahrscheinlichkeitsinformation. Szenarien sollten deshalb neben Eintrittsannahmen auch Frühindikatoren, Anpassungsfähigkeit und Konsequenzen enthalten. Ein Unternehmen mit austauschbaren Lieferanten besitzt andere Handlungsoptionen als eines mit einer einzigen kritischen Quelle.

Diversifikation nach Börsenland reicht nicht, wenn Umsätze, Produktionsorte und Finanzierung wirtschaftlich konzentriert sind. Für ein Portfolio werden direkte Exponierung, indirekte Lieferketten und gemeinsame Finanzierungsbedingungen zusammengeführt. Stresstests zeigen mögliche Folgen, ohne dadurch deren Wahrscheinlichkeit exakt zu kennen.`)],C('Gleicher Normalfall, andere Ausweichmöglichkeit','Ein Projekt ist im Normalfall 100 wert. Ein Stressereignis wird illustrativ mit 20 % gewichtet.',['Struktur','Wert im Stress','Erwarteter Szenariowert'],[['Keine Alternative','20','84'],['Diversifizierte Lieferkette','70','94']],'Die Werte entstehen als 0,8 × 100 plus 0,2 × Stresswert. Eine Ausweichstruktur verbessert den erwarteten Wert hier um 10, bevor ihre Kosten abgezogen werden. Die 20 % sind eine transparente Modellannahme, keine aus dem Beispiel bewiesene Ereigniswahrscheinlichkeit.'),[['corporate-05','Flexibilität als reale Option bewerten.'],['portfolio-13','Szenarien mit gemeinsamen Risikotreibern aufbauen.']])
];
