const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Ökonomischer Anspruch und Stimmrecht',`Eine Aktie ist ein Beteiligungsanspruch mit bestimmten Zahlungs-, Kontroll- und Übertragungsrechten. Stamm- und Vorzugsrechte können Dividendenpriorität, Stimmrechte und Liquidationsrang unterschiedlich verteilen. Gleicher Unternehmensbezug bedeutet deshalb nicht automatisch denselben Wert je Anteil.

Die Marktkapitalisierung ist Preis mal ausstehende Aktienzahl. Eigene Aktien, Verwässerungspotenzial und mehrere Aktienklassen erfordern eine saubere Bestandsdefinition. Ein niedriger Einzelkurs sagt ohne Aktienzahl nichts darüber aus, ob ein Unternehmen günstig bewertet ist.`,T`E=\sum_k P_kN_k`),S('Primär- und Sekundärmarkt',`Bei einer Neuemission fließt Kapital an das Unternehmen oder bei einem Verkauf bestehender Anteile an deren Eigentümer. Im Sekundärhandel tauschen Anleger Ansprüche untereinander. Liquidität und Preisfindung des Sekundärmarkts können dennoch die Finanzierungskosten künftiger Emissionen beeinflussen.

Ein Aktiensplit verändert im idealisierten Fall nur die Stückelung. Eine Kapitalerhöhung verändert dagegen Mittelbestand und Anzahl der Ansprüche. Ob bestehende Eigentümer wirtschaftlich verwässert werden, hängt vom Emissionspreis, Bezugsrechten und der Verwendung des neuen Kapitals ab.`)],C('Gleicher Unternehmenswert, andere Stückelung','Eigenkapitalwert 1.000 vor und nach einem Split; keine weiteren Vorgänge.',['Aktienzahl','Kurs','Wert von 10 % Beteiligung'],[['100','10','100'],['1.000','1','100']],'Der zehnmal niedrigere Kurs macht die Firma nicht zehnmal günstiger. Ein Anteil von 10 % besteht anschließend aus zehnmal so vielen Aktien. Bewertungsvergleiche müssen Preis und Anspruchsmenge gemeinsam berücksichtigen.'),[['corporate-09','Ausschüttungen und Rückkäufe verändern Ansprüche.'],['equity-10','Preise durch passende Bezugsgrößen vergleichbar machen.']]),
D([S('Ordertypen verteilen Ausführungs- und Preisrisiko',`Eine Market Order priorisiert die sofortige Ausführung zu verfügbaren Preisen. Eine Limit Order begrenzt den Preis, kann aber unerfüllt bleiben oder gerade dann ausgeführt werden, wenn neue Information den fairen Wert verschlechtert. Ein Stop ist ein Auslöser nach definierten Bedingungen und keine allgemeine Garantie für einen bestimmten Ausführungskurs.

Das Orderbuch zeigt gestaffelte Liquidität. Eine große Kauforder kann mehrere Verkaufsstufen verbrauchen und einen höheren Durchschnittspreis als den besten sichtbaren Ask erzielen. Der Spread ist daher nur ein Teil der tatsächlichen Handelskosten.`,T`Spread=Ask-Bid,\quad Mid=\frac{Ask+Bid}{2},\quad P_{VWAP}=\frac{\sum_i P_iQ_i}{\sum_i Q_i}`),S('Liquiditätsbereitstellung und adverse Selektion',`Ein Liquiditätsanbieter verdient unter anderem den Spread, trägt aber Bestandsrisiko und das Risiko, gegen besser informierte Händler zu handeln. Bei hoher Unsicherheit können Spreads steigen und verfügbare Mengen sinken. Beobachtetes Volumen allein beschreibt deshalb nicht jede Dimension von Liquidität.

Orderwahl hängt von Dringlichkeit, Informationsrisiko, Größe und Marktstruktur ab. Langsames Handeln kann Marktwirkung reduzieren, aber die Position länger einem unerwünschten Preisrisiko aussetzen. Diese Abwägung wird im Implementation Shortfall messbar gemacht.`)],C('Gleiche Kaufmenge, andere Orderstrategie','100 Aktien: 50 werden zu 10,00 angeboten, die nächsten 50 zu 10,20.',['Order','Sofort ausgeführt','Durchschnittspreis','Rest'],[['Market über 100','100','10,10','0'],['Limit 10,00 über 100','50','10,00','50 ungefüllt']],'Das Limit verbessert hier den Preis der ausgeführten Stücke, lässt aber die Hälfte offen. Ein Vergleich nur der Durchschnittspreise würde den unerfüllten Auftrag ignorieren. Die spätere Preisentwicklung entscheidet, welche Opportunitätskosten entstehen.'),[['path-portfolio-05','Ausführungs- und Opportunitätskosten zusammen messen.'],['ethics-04','Faire Orderzuteilung organisieren.']]),
D([S('Indexgewichte bestimmen die wirtschaftliche Wette',`Ein preisgewichteter Index gibt Aktien mit höherem Einzelkurs mehr Einfluss und benötigt bei Splits einen angepassten Divisor. Ein kapitalisierungsgewichteter Index gewichtet nach Marktwert, gegebenenfalls nur dem frei handelbaren Anteil. Gleichgewichtung setzt pro Titel gleiche Gewichte und muss nach Kursbewegungen wieder hergestellt werden.

Die Indexrendite entsteht aus den Anfangsgewichten und den Gesamtrenditen der Bestandteile, sofern keine zwischenzeitlichen Strukturänderungen zusätzliche Behandlung erfordern. Ein Preisindex ignoriert Ausschüttungen, ein Total-Return-Index berücksichtigt sie nach seiner Methodik. Diese Definition kann einen Performancevergleich wesentlich verändern.`,T`R_I=\sum_i w_{i,0}R_i,\quad w_i^{cap}=\frac{P_iN_i}{\sum_jP_jN_j}`),S('Effizienz ist eine Aussage relativ zu Information und Kosten',`Schwache, halbstrenge und starke Formen unterscheiden, welche Informationsmenge in Preisen verarbeitet sein soll. Effizienz bedeutet nicht, dass Preise rückblickend immer richtig sind oder Renditen konstant bleiben. Überraschungen und neue Risikoeinschätzungen können Preise stark verändern.

Ein empirischer Alpha-Test prüft gleichzeitig das verwendete Risikomodell und die Effizienzbehauptung. Ein auffälliger Ertrag kann auf Fehlbewertung, ausgelassene Risikofaktoren, Datenfehler oder Auswahlverzerrung zurückgehen. Nach Kosten handelbare Gewinne sind eine stärkere Aussage als ein statistischer In-sample-Effekt.`)],C('Gleiche Aktienrenditen, andere Gewichtung','A hat Marktwert 900 und Rendite +10 %, B Marktwert 100 und Rendite −10 %.',['Index','Gewicht A / B','Rendite'],[['Kapitalisierungsgewichtet','90 % / 10 %','8 %'],['Gleichgewichtet','50 % / 50 %','0 %']],'Die Renditedifferenz ist vollständig durch Gewichte erklärt. Sie beweist keine bessere Titelauswahl. Gleichgewichtung bringt andere Größen- und Rebalancing-Exponierungen mit sich, die bei einem Strategievergleich berücksichtigt werden müssen.'),[['portfolio-05','Faktormodelle erklären systematische Exponierungen.'],['path-portfolio-01','Indexumsetzung und Tracking Error analysieren.']]),
D([S('Wettbewerbsvorteil in Rendite und Haltbarkeit übersetzen',`Eine Branchenanalyse untersucht, warum ein Unternehmen Preise über ökonomischen Kosten erzielen oder Kapital effizienter einsetzen kann. Eintrittsbarrieren, Ersatzprodukte, Lieferanten- und Kundenmacht beeinflussen unterschiedliche Werttreiber. Eine bekannte Marke ist erst dann bewertungsrelevant, wenn sie beispielsweise Preissetzung, Kundenbindung oder geringere Akquisitionskosten erklärt.

Der Wert eines Vorteils hängt nicht nur von der heutigen Höhe der Überschussrendite, sondern von ihrer Dauer und dem zusätzlich investierbaren Kapital ab. Ein kleines hochrentables Nischengeschäft kann weniger absolute Wachstumschancen besitzen als ein größerer Markt mit niedrigeren Renditen.`,T`EP_t=(ROIC_t-WACC_t)IC_{t-1}`),S('Zyklus, Struktur und Unternehmensposition',`Branchenzyklus und Unternehmensqualität sind getrennt zu analysieren. Hohe Rohstoffpreise können auch schwache Produzenten zeitweise sehr profitabel machen. Eine normalisierte Prognose untersucht Kostenkurve, Kapazitätsreaktion und Ersatzinvestitionen, statt die Spitzenmarge dauerhaft fortzuschreiben.

Wettbewerbsvorteile können erodieren, wenn Technologien wechseln oder Kunden Alternativen erhalten. Szenarien sollten deshalb Margenrückgang, Kapitalumschlag und Anpassungsinvestitionen gemeinsam verändern. Eine pauschal lange Wachstumsphase ohne Erklärung des Schutzmechanismus ist keine belastbare Branchenanalyse.`)],C('Gleiche Renditehöhe, andere Dauer','Operatives Kapital 100, ROIC 20 %, WACC 10 %. Jährlicher ökonomischer Gewinn 10; Diskontierung mit 10 %, keine weiteren Änderungen.',['Dauer des Vorteils','Barwert der Überschussgewinne'],[['1 Jahr','9,09'],['5 Jahre','37,91'],['Unbegrenzt','100']],'Die heutige Renditezahl ist identisch. Der zusätzliche Wert unterscheidet sich durch die Haltbarkeit des Vorteils. Die ewige Variante setzt besonders starke Annahmen voraus; sie darf nicht allein aus einem guten Geschäftsjahr abgeleitet werden.'),[['corporate-03','Geschäftsmodell und Kapitalbedarf verknüpfen.'],['equity-11','Residualgewinne als Bewertungsansatz.']]),
D([S('Wachstum ist das Ergebnis von Reinvestition und Rendite',`Wenn zusätzlich eingesetztes Kapital dieselbe inkrementelle Rendite erzielt und die Kapitalbasis konsistent gemessen wird, verbindet die Reinvestitionsquote b Wachstum und ROIC. Die Beziehung zeigt, dass Wachstum Cash benötigt: Ein Teil des operativen Nachsteuergewinns wird im Unternehmen gebunden.

Im stabilen FCFF-Modell kann die Reinvestitionsquote durch Wachstum geteilt durch ROIC ersetzt werden. Dadurch werden Wachstum und freier Cashflow ausdrücklich verknüpft. Eine höhere Wachstumsrate erhöht nicht nur spätere Gewinne, sondern senkt zunächst die Ausschüttungsfähigkeit.`,T`g=b\,ROIC,\quad b=\frac g{ROIC},\quad FCFF=NOPAT\left(1-\frac g{ROIC}\right)`),S('Wertwirkung des Wachstums hängt vom Renditeüberschuss ab',`Mit dauerhaft konstanten Größen und WACC größer als g entsteht eine geschlossene Bewertungsform. Hält man den nächsten NOPAT konstant, zeigt ihre Ableitung nach Wachstum, dass dessen Wertwirkung vom Abstand zwischen ROIC und WACC abhängt. Wachstum mit Rendite unter den Kapitalkosten vernichtet im Modell Wert.

Für reale Prognosen müssen Anfangs- und Endbestände, Übergangsjahre und inkrementelle Renditen sauber abgestimmt werden. Eine historische ROIC-Schätzung kann für neue Projekte zu hoch sein. Auch eine mathematisch zulässige Wachstumsrate kann langfristig ökonomisch unplausibel sein.`,T`V=\frac{NOPAT_1(1-g/ROIC)}{WACC-g},\quad \frac{\partial V}{\partial g}=\frac{NOPAT_1(1-WACC/ROIC)}{(WACC-g)^2}`)],C('Gleiches Wachstum, andere Kapitalproduktivität','NOPAT nächstes Jahr 10, Wachstum 4 %, WACC 10 %. Stabiles Modell.',['ROIC','Reinvestitionsquote','FCFF nächstes Jahr','Wert'],[['20 %','20 %','8','133,33'],['10 %','40 %','6','100'],['5 %','80 %','2','33,33']],'Alle Firmen wachsen gleich schnell. Die schwach rentierende Firma muss jedoch fast den gesamten operativen Gewinn reinvestieren. Die Rechnung zeigt, warum eine Wachstumsprognose ohne Kapitalbedarfsannahme unvollständig ist.'),[['corporate-04','Investitionen nach Wertbeitrag auswählen.'],['equity-09','Free Cashflow aus operativen Treibern ableiten.']]),
D([S('Geforderte Rendite ist eine Opportunitätskostenannahme',`Eigenkapitalkosten sind die erwartete Rendite, die Anleger für das relevante Risiko verlangen. Im CAPM wird systematisches Risiko über Beta erfasst, nicht über die gesamte Einzelaktienvolatilität. Der risikofreie Satz muss zu Währung und Zeithorizont passen; die Marktprämie ist eine unsichere Erwartungsgröße.

Historische Regressionsbetas hängen von Datenfrequenz, Beobachtungsfenster, Marktproxy und Kapitalstruktur ab. Für ein Unternehmen mit veränderter Geschäftstätigkeit kann eine sektorbasierte Bottom-up-Schätzung sinnvoller sein. Sie benötigt trotzdem eine begründete Auswahl und Anpassung der Vergleichsunternehmen.`,T`k_e=r_f+\beta_e(E[R_M]-r_f)`),S('Risikoprämien nicht beliebig addieren',`Mehrfaktormodelle vergüten Exponierungen gegenüber mehreren systematischen Faktoren. Eine zusätzliche Länder-, Größen- oder Liquiditätskomponente muss wirtschaftlich und empirisch begründet sein. Dieselbe Gefahr zugleich in niedrigeren Cashflows, höherem Beta und einem pauschalen Zuschlag zu erfassen kann zu Doppelzählung führen.

Eigenkapitalkosten sind nicht mit beobachteter Jahresrendite gleichzusetzen. Eine Aktie kann trotz hoher geforderter Rendite in einem Jahr verlieren. Für Bewertungsbandbreiten werden Unsicherheiten des Diskontsatzes getrennt von operativen Szenarien untersucht und anschließend auf konsistente Kombinationen geprüft.`,T`k_e=r_f+\sum_j\beta_j\lambda_j`)],C('Gleiche Cashflows, anderes systematisches Risiko','Ewige Zahlung 5, risikofreier Satz 3 %, Marktprämie 5 %, kein Wachstum.',['Beta','Eigenkapitalkosten','Modellwert'],[['0,6','6 %','83,33'],['1,0','8 %','62,50'],['1,4','10 %','50']],'Die geringeren Werte folgen aus höherer geforderter Vergütung des Risikos, nicht aus niedrigeren erwarteten Zahlungen. Die Tabelle isoliert Beta; eine reale Risikoveränderung kann auch Cashflows beeinflussen.'),[['portfolio-04','Beta aus Kovarianz und Marktvarianz ableiten.'],['corporate-06','Geschäfts- und Finanzierungsrisiko trennen.']]),
D([S('These, Preis und Gegenposition',`Eine Investmentthese erklärt, welche relevante Erwartung vom Marktpreis abweicht, wodurch sie begründet ist und wie sich ihr Wertbeitrag berechnen lässt. Eine gute Firma ist nicht automatisch eine gute Anlage, wenn der Preis bereits außergewöhnliche Erfolge voraussetzt. Reverse DCF kann zeigen, welche Wachstums- oder Margenannahmen im Preis stecken.

Katalysatoren sind Ereignisse, die neue Information oder Kapitalverteilung auslösen können. Ihr Ausbleiben beweist nicht automatisch eine falsche Bewertung, kann aber den Realisierungshorizont verlängern. Eine These sollte deshalb zwischen langfristigem Wert und zeitnaher Preisreaktion unterscheiden.`),S('Falsifizierbare Bedingungen und Entscheidung',`Vor dem Kauf werden Beobachtungen festgelegt, die die These schwächen oder widerlegen würden. Dazu gehören operative Kennzahlen, Kapitalallokation und Finanzierung, nicht nur der Kurs. Ein fallender Kurs kann eine bessere Chance oder neue schlechte Information anzeigen; die Ursache entscheidet.

Der Bericht verbindet Basisszenario, Alternativen, Bewertung, Risiken und Portfolioeignung. Ein erwarteter Ertrag allein bestimmt keine Positionsgröße. Unsicherheit, Korrelation mit vorhandenen Anlagen und Liquiditätsbedarf gehören in die Umsetzung. Fakten, Schätzungen und Werturteile bleiben sichtbar getrennt.`)],C('Gleiches Kursziel, andere Ausgangsbewertung','Zwei Analysten erwarten in einem Jahr Wert 120 und Dividende 5; sie betrachten unterschiedliche Kaufkurse.',['Kaufkurs','Erwartete einfache Gesamtrendite'],[['100','25 %'],['120','4,17 %'],['140','−10,71 %']],'Jede Rendite folgt aus (120 + 5 − Kaufkurs) geteilt durch Kaufkurs. Dieselbe operative Prognose führt je nach Preis zu einer anderen Anlageentscheidung. Zusätzlich muss die erwartete Rendite mit Risiko, Alternativen und Prognoseunsicherheit verglichen werden.'),[['equity-12','Bewertungsbandbreiten statt Scheingenauigkeit.'],['portfolio-06','These in den Mandatskontext stellen.']]),
D([S('Dividendenmodell aus der Einperiodenbewertung',`Der heutige Aktienwert ist der Barwert der nächsten Dividende und des erwarteten späteren Preises. Wiederholtes Einsetzen der gleichen Beziehung ersetzt den späteren Preis durch weitere Dividenden. Eine passende Transversalitätsbedingung verhindert, dass ein unendlich ferner unbegründeter Restpreis den Wert trägt.

Bei dauerhaftem Dividendenwachstum g wird die Reihe geometrisch. Sie konvergiert nur, wenn die geforderte Eigenkapitalrendite über g liegt. Im Zähler steht die nächste Dividende, nicht ungeprüft die zuletzt gezahlte.`,T`P_0=\frac{D_1+P_1}{1+k_e}=\sum_{t=1}^{\infty}\frac{D_t}{(1+k_e)^t},\qquad P_0=\frac{D_1}{k_e-g}\quad(k_e>g)`),S('Mehrstufige Modelle und Übergang zum Terminal Value',`In einer expliziten Wachstumsphase werden Dividenden einzeln prognostiziert. Der Terminal Value am Ende dieser Phase verwendet die erste Dividende der stabilen Folgephase. Anschließend wird auch dieser Endwert auf heute diskontiert. Eine häufige Doppelzählung entsteht, wenn dieselbe Übergangsdividende sowohl in der Detailphase als auch im Terminal Value falsch angesetzt wird.

Das Gordon-Modell ist besonders empfindlich, wenn der Abstand zwischen Diskontsatz und Wachstum klein ist. Die Ableitungen zeigen diese Nichtlinearität. Hält man statt D1 die aktuelle Dividende D0 konstant, enthält die Wachstumsableitung zusätzlich deren Aufzinsung; die Konvention muss deshalb genannt werden.`,T`P_0=\sum_{t=1}^{N}\frac{D_t}{(1+k_e)^t}+\frac{D_{N+1}}{(k_e-g)(1+k_e)^N},\quad \frac{\partial P_0}{\partial k_e}=-\frac{D_1}{(k_e-g)^2},\quad \frac{\partial P_0}{\partial g}=\frac{D_1}{(k_e-g)^2}`),S('Dividende, Rückkauf und Ausschüttungsfähigkeit',`Ein Unternehmen kann Eigentümer über Rückkäufe statt Dividenden vergüten. Ein reines Dividendenmodell benötigt dann eine Prognose, wie die gesamte wirtschaftliche Ausschüttungsfähigkeit später in Zahlungen je Aktie übergeht. FCFE oder Total-Payout-Ansätze können bei stark veränderlicher Ausschüttung verständlicher sein.

Wachstum muss mit einbehaltenen Mitteln und deren Rendite vereinbar sein. Eine hohe Ausschüttungsquote und dauerhaft hohes Wachstum passen nur zusammen, wenn die Kapitalrendite oder externe Finanzierung dies ermöglicht. Das Modell ist deshalb eine Verdichtung eines Geschäftsmodells und kein frei bestückbarer Bruch.`)],C('Gleiche nächste Dividende, zunehmende Nennerempfindlichkeit','D1 = 4, Eigenkapitalkosten 8 %.',['Dauerwachstum','Abstand k − g','Wert','Wertanstieg zur Vorzeile'],[['2 %','6 %','66,67','—'],['3 %','5 %','80','13,33'],['4 %','4 %','100','20'],['5 %','3 %','133,33','33,33']],'Jeder zusätzliche Wachstumspunkt erhöht den Wert stärker, weil der Nenner immer kleiner wird. Diese Krümmung erklärt, warum kleine Änderungen einer ohnehin aggressiven Terminalannahme extreme Bewertungsunterschiede erzeugen.'),[['equity-05','Wachstum erfordert Reinvestition.'],['quant-02','Geometrische Reihe und ewige Rente herleiten.']]),
D([S('FCFF aus dem operativen Ergebnis',`FCFF misst Zahlungen für sämtliche Kapitalgeber vor Nettofinanzierung. Man beginnt mit operativem Nachsteuergewinn, addiert nicht zahlungswirksame Abschreibungen und zieht Investitionen sowie zusätzlich gebundenes operatives Working Capital ab. Die Steuerquote und EBIT-Abgrenzung müssen eine zur Finanzierung unabhängige operative Größe erzeugen.

Ein positiver EBITDA ist deshalb noch kein positiver FCFF. Abschreibungen approximieren nicht automatisch den notwendigen Ersatz-CAPEX, und Wachstum kann erhebliche zusätzliche Umlaufmittel benötigen. Cashsteuern, Leasing, Pensionsbeiträge und andere operative Verpflichtungen benötigen eine konsistente Behandlung.`,T`FCFF=EBIT(1-\tau)+DA-CAPEX-\Delta NWC`),S('FCFE durch Übergang zu Eigentümerzahlungen',`Vom Cashflow aller Kapitalgeber werden nachsteuerliche Zinszahlungen abgezogen und Nettoneuverschuldung addiert. Alternativ kann direkt beim Nettogewinn begonnen werden, der den Zinsaufwand bereits enthält. Beide Wege müssen bei gleichen Definitionen denselben FCFE liefern.

Tilgung ist Teil negativer Nettoneuverschuldung. Eine Firma kann deshalb guten operativen Cashflow haben und trotzdem wenig ausschüttungsfähigen Eigentümercashflow, wenn sie Schulden abbaut. Umgekehrt ist hoher FCFE durch neue Kredite nicht unbegrenzt nachhaltig.`,T`FCFE=FCFF-I(1-\tau)+\Delta D=NI+DA-CAPEX-\Delta NWC+\Delta D`),S('Wertbrücke und Konsistenz der Diskontierung',`FCFF wird mit WACC zum operativen Unternehmenswert diskontiert. Nicht operative Vermögenswerte werden anschließend ergänzt und relevante vorrangige Ansprüche abgezogen. FCFE wird mit Eigenkapitalkosten direkt zum Eigentümerwert diskontiert. Bei konsistenten Finanzierungsannahmen sollten beide Ansätze zusammenpassen.

Zu den Anpassungen können neben Finanzschulden auch nicht beherrschende Anteile und weitere anspruchsähnliche Positionen gehören. Überschüssiges Cash wird nur ergänzt, soweit es nicht schon durch operative Cashflows oder andere Vermögenswerte erfasst ist. Der Name „Enterprise Value“ allein garantiert keine einheitliche Abgrenzung.`,T`V_{op}=\sum_t\frac{FCFF_t}{(1+WACC)^t},\quad E=V_{op}+A_{nonop}-D-NCI-OC,\quad E=\sum_t\frac{FCFE_t}{(1+k_e)^t}`)],C('Gleicher Betrieb, unterschiedlicher Schuldenpfad','EBIT 100, Steuersatz 25 %, DA 20, CAPEX 30, ΔNWC 10, Zinsen 8. Damit FCFF 55 und NI 69.',['Nettoneuverschuldung','FCFE aus FCFF','FCFE aus NI'],[['−20','55 − 6 − 20 = 29','69 + 20 − 30 − 10 − 20 = 29'],['0','49','49'],['+20','69','69']],'Die operative Wertschöpfung bleibt gleich. Nur die Verteilung zwischen Kreditgebern und Eigentümern verändert den aktuellen FCFE. Ein steigender FCFE durch Neuverschuldung darf deshalb nicht als verbessertes operatives Geschäft interpretiert werden.'),[['corporate-06','WACC und Eigenkapitalkosten abstimmen.'],['statements-15','Cashflows aus integrierten Abschlüssen ableiten.']]),
D([S('Multiplikatoren sind verkürzte Bewertungsmodelle',`Ein Multiplikator verbindet einen Wert mit einer Ertrags-, Umsatz- oder Bestandsgröße. Eigentümerwerte gehören zu Eigentümergrößen wie Nettogewinn; Enterprise Value zu vor Finanzierung abgegrenzten Größen. Ein EV/Net-Income-Verhältnis mischt ohne besondere Begründung unterschiedliche Ansprüche.

Im stabilen Dividendenmodell lässt sich ein gerechtfertigtes Forward-P/E aus Ausschüttungsquote, Eigenkapitalkosten und Wachstum ableiten. Ähnliche Multiplikatoren sind deshalb nur bei ähnlichen Werttreibern plausibel. Ein niedrigeres P/E kann geringeres Wachstum oder höheres Risiko ausdrücken und muss keine Unterbewertung sein.`,T`\frac{P_0}{E_1}=\frac{1-b}{k_e-g},\quad \frac{P_0}{E_0}=\frac{(1-b)(1+g)}{k_e-g}`),S('Vergleichsgruppe, Normalisierung und Ausreißer',`Peer-Auswahl benötigt ähnliche Geschäftsmodelle, Wachstum, Kapitalintensität, Risiko und Bilanzierungsbasis. Ein Branchenetikett allein reicht nicht. Zyklische Spitzengewinne können ein optisch niedriges P/E erzeugen, obwohl normalisierte Gewinne deutlich geringer sind.

Median, Mittelwert und gewichtete Aggregate beantworten verschiedene Fragen. Negative oder sehr kleine Nenner können einzelne Verhältnisse unbrauchbar machen. Eine angemessene Analyse zeigt daher Verteilung, Ausschlüsse und die Wirkung wesentlicher Normalisierungen, statt nur einen einzigen Zielmultiplikator zu präsentieren.`)],C('Gleiche Ausschüttungsquote, anderes Wachstum','Ausschüttungsquote 50 %, Eigenkapitalkosten 10 %; Forward-P/E im stabilen Modell.',['Wachstum','Gerechtfertigtes P/E'],[['0 %','5'],['4 %','8,33'],['6 %','12,5']],'Der höhere Multiplikator ist im Modell die Folge längerer und wachsender Eigentümerzahlungen. Die Wachstumsraten müssen allerdings mit Einbehaltung und Kapitalrendite vereinbar sein. Vergleichbarkeit verlangt deshalb mehr als dieselbe aktuelle Gewinnhöhe.'),[['equity-08','Gordon-Modell als Grundlage des Multiplikators.'],['statements-12','Bilanzierungs- und Leverageunterschiede normalisieren.']]),
D([S('Residualgewinn aus Clean Surplus ableiten',`Clean Surplus verbindet Buchwert, Gewinn und Ausschüttung: Der Endbuchwert entspricht Anfangsbuchwert plus Gewinn minus Eigentümerzahlungen, soweit andere direkte Eigenkapitalbewegungen entsprechend angepasst werden. Setzt man diese Identität in das Dividendenmodell ein, kann der Wert als heutiger Buchwert plus Barwert künftiger Residualgewinne geschrieben werden.

Residualgewinn zieht vom Nettogewinn eine Eigenkapitalbelastung auf den Anfangsbuchwert ab. Ein positiver Buchgewinn reicht daher nicht; die Buchrendite muss die geforderte Eigenkapitalrendite übersteigen. Der Ansatz kann nützlich sein, wenn Dividenden oder freie Cashflows vorübergehend wenig aussagekräftig sind.`,T`B_t=B_{t-1}+NI_t-D_t,\quad RI_t=NI_t-k_eB_{t-1},\quad P_0=B_0+\sum_{t=1}^{\infty}\frac{RI_t}{(1+k_e)^t}`),S('Buchwertqualität und Substanzbewertung',`Die Aussage hängt von der Qualität des Buchwerts und der Behandlung direkter Eigenkapitalbewegungen ab. Nicht bilanzierte immaterielle Werte oder aggressive Aktivierung verändern Buchrenditen. Ein hoher ROE auf sehr kleinem Buchwert kann daher weniger über ökonomische Rendite aussagen als erwartet.

Eine substanzorientierte Bewertung setzt Vermögenswerte und Verpflichtungen zu passenden Werten an. Liquidationswert, Wiederbeschaffungswert und Fortführungswert sind unterschiedliche Konzepte. Doppelzählung droht, wenn Ertragswert und die zu seiner Erzeugung benötigten Vermögenswerte ohne konsistente Abgrenzung addiert werden.`)],C('Gleicher Buchwert, unterschiedliche Überschussrendite','B0 = 100, Eigenkapitalkosten 10 %, im isolierten Beispiel entsteht nur im nächsten Jahr Residualgewinn, danach keiner.',['NI nächstes Jahr','RI nächstes Jahr','Wert heute'],[['8','−2','98,18'],['10','0','100'],['15','5','104,55']],'Der Wertunterschied entsteht aus dem Barwert des Gewinns oberhalb beziehungsweise unterhalb der Kapitalbelastung von 10. Positiver Gewinn von 8 führt hier trotzdem zu einem Wert unter Buchwert.'),[['statements-12','ROE und seine Treiber analysieren.'],['equity-09','Alternative Bewertungswege auf Konsistenz prüfen.']]),
D([S('Fehlender Marktpreis und besondere Ansprüche',`Private Unternehmen besitzen oft weniger standardisierte Daten und keinen laufenden Börsenpreis. Eigentümervergütung, verbundene Geschäfte und einmalige Aufwendungen können normalisiert werden müssen. Ziel ist eine nachhaltig übertragbare Ertragsbasis, nicht eine beliebige Gewinnsteigerung durch das Entfernen unbequemer Kosten.

Kontrollrechte, Übertragungsbeschränkungen und Liquidität beeinflussen den konkreten Beteiligungswert. Ein Minderheitsanteil mit begrenztem Informationszugang ist nicht automatisch proportional so viel wert wie eine kontrollierende Beteiligung. Pauschale Abschläge ohne Bezugsbasis, Rechteanalyse und Marktbezug können jedoch ebenso irreführen.`),S('Unsicherheit in Bandbreiten und Entscheidungen übersetzen',`Eine Bewertungsbandbreite sollte aus konkreten Treibern entstehen: normalisierte Marge, Reinvestition, Wachstum, Diskontsatz und Transaktionsrechte. Die Spannweite allein sagt nichts über Eintrittswahrscheinlichkeiten. Ein Erwartungswert verlangt explizite Szenariogewichte; ein Worst Case ist eine andere Aussage.

Bei jungen Unternehmen können Finanzierungslücken und Überlebenswahrscheinlichkeit besonders wichtig sein. Eine Erfolgsbewertung, die nur über einen extrem hohen Diskontsatz korrigiert wird, kann die zeitliche und zustandsabhängige Finanzierung unzureichend darstellen. Szenariobäume und Verwässerungspfade können transparenter sein.`,T`E[V]=\sum_s p_sV_s,\qquad V_{stake}=f(V,C,L)`)],C('Gleicher Erfolgswert, andere Ausfallwahrscheinlichkeit','Im Erfolg beträgt der Eigenkapitalwert 200, im Ausfall 0. Diskontierung wird zur Isolation ausgeblendet.',['Erfolgswahrscheinlichkeit','Erwarteter Wert'],[['30 %','60'],['60 %','120'],['90 %','180']],'Die 200 allein sind keine vollständige Bewertung. Der Vergleich isoliert die Erfolgswahrscheinlichkeit. Bei einer konkreten Investition müssen zusätzlich Zeitpunkt, Finanzierungsrunden und vorrangige Ansprüche auf die möglichen Auszahlungen angewendet werden.'),[['path-private-02','Finanzierungsrunden und Ansprüche modellieren.'],['quant-06','Bedingte Wahrscheinlichkeiten aktualisieren.']])
];
