const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Pflicht, Folgen und Verfahren getrennt beurteilen',`Ein ethisches Urteil hat mehrere Ebenen. Eine Handlung kann nützliche Folgen haben und trotzdem eine Pflicht verletzen, etwa wenn vertrauliche Daten ohne Befugnis genutzt werden. Umgekehrt garantiert ein korrekter Prozess keinen Anlagegewinn. Deshalb prüft man zuerst zulässige Handlungen und danach, welche davon den begründeten Interessen der Betroffenen am besten dient.

Die Analyse beginnt mit einer Chronologie: Wer wusste zu welchem Zeitpunkt was, in welcher Rolle, mit welchem Handlungsspielraum? Damit verhindert man Rückschaufehler. Anschließend werden Kunden, Begünstigte, Arbeitgeber und Marktteilnehmer sowie deren Ansprüche identifiziert. Persönliche Sympathie für eine beteiligte Person ersetzt diese Rollenanalyse nicht.`),S('Vom Urteil zur wirksamen Maßnahme',`Ein Ergebnis wie „Interessenkonflikt“ ist nur eine Diagnose. Die Maßnahme muss den Mechanismus unterbrechen: einen Vorteil ablehnen, einen Auftrag unabhängig prüfen lassen, eine Transaktion aussetzen oder einen Fehler offen korrigieren. Die Wahl hängt davon ab, ob Vermeidung möglich ist und ob die verbleibende Tätigkeit sachgerecht ausgeführt werden kann.

Dokumentation hält Tatsachen, Informationslücken, verworfene Alternativen und Gründe fest. Bei neuer Evidenz wird die Entscheidung überprüft. Das ist besonders wichtig bei Prognosen: Eine sorgfältige Schätzung kann falsch sein; die bewusste Verschleierung ihrer Unsicherheit ist ein eigenständiges Problem. Ethik ist daher Teil des laufenden Investmentprozesses und keine abschließende Textprüfung.`)],C('Gleicher Gewinn, unterschiedliche Qualität der Entscheidung','Zwei Berater erzielen zufällig 12 % für einen Kunden. Der Ergebniswert wird konstant gehalten.',['Fall','Entscheidungsgrundlage','Beurteilung'],[['A','Geeignete Anlage, geprüfte Daten, offener Konflikt','Prozess nachvollziehbar; Gewinn allein beweist keine Exzellenz'],['B','Ungeprüftes Gerücht, verschwiegene Provision','Gewinn beseitigt den Prozessmangel nicht']],'Der kontrollierte Vergleich trennt ex ante vertretbare Entscheidungen von ex post Glück. Bei einer Fallfrage werden deshalb die damaligen Fakten verwendet. Ein späterer Verlust kann eine Überprüfung auslösen, ist aber kein Ersatz für den Nachweis, welche konkrete Pflicht wie verletzt wurde.'),[['ethics-11','Grenzfälle anhand veränderter Tatsachen lösen.'],['advanced-10','Auch Performancebeurteilung muss Glück und Können trennen.']]),
D([S('Unabhängigkeit ist eine Eigenschaft der Anreizstruktur',`Die Frage lautet nicht nur, ob ein Analyst sich subjektiv beeinflusst fühlt. Zuwendungen, Karriereabhängigkeit und die Drohung, Managementzugang zu verlieren, verändern den Preis einer unliebsamen Meinung. Eine wirksame Kontrolle setzt daher vor der fertigen Empfehlung an: Wer finanziert die Analyse, wer entscheidet über Vergütung und wer kann die Veröffentlichung blockieren?

Ein sachlich notwendiger Zugang kann organisiert werden, ohne private Vorteile zu gewähren. Eigenständige Datenprüfung und eine nachvollziehbare Bewertungsmethode verringern Abhängigkeit, beseitigen aber nicht jeden Konflikt. Die Herkunft der Information, die Qualität der Analyse und die Unabhängigkeit des Urteils bleiben drei getrennte Prüfungen.`),S('Kompetenz, Fehler und irreführende Präzision',`Professionelle Kompetenz verlangt, die Aufgaben mit ausreichenden Fähigkeiten zu bearbeiten und Grenzen rechtzeitig zu erkennen. Ein bekanntes Modell falsch anzuwenden wird nicht dadurch unproblematisch, dass die Software das Ergebnis automatisch erzeugt. Bei neuer Assetklasse, neuer Regulierung oder neuem Modell sind Weiterbildung, qualifizierte Unterstützung oder ein engerer Auftrag mögliche Konsequenzen.

Eine Aussage kann irreführen, ohne wörtlich falsch zu sein. Beispielsweise ist ein Modellkurs ohne Szenarioannahmen scheinbar präzise, obwohl sein Wert stark von Wachstum und Diskontsatz abhängt. Eigene Beiträge, fremde Analysen und Schätzungen müssen erkennbar bleiben. Die konkrete Einordnung erfolgt anhand der aktuellen Standards; eine interne Freigabe ersetzt deren Anforderungen nicht.`)],C('Nur die Finanzierung des Vorteils ändern','Ein notwendiger Unternehmensbesuch umfasst dieselbe Werksführung.',['Variante','Zusätzliche Leistung','Konsequenz'],[['A','Normale fachlich notwendige Organisation','Sachlich prüfen und angemessen organisieren'],['B','Privater Luxusurlaub für die Analystin','Persönlichen Vorteil ablehnen; fachlichen Besuch getrennt planen']],'Nicht jeder Kontakt mit einem Emittenten ist problematisch. Entscheidend ist, ob der persönliche Nutzen das unabhängige Urteil beeinträchtigen kann. Eine selbst gewählte pauschale Eurogrenze würde den Kontext ausblenden; Art, Anlass und Abhängigkeit sind mitzubeurteilen.'),[['equity-07','Research muss unabhängig begründet werden.'],['ethics-07','Vergütung und andere Nebeninteressen systematisch erfassen.']]),
D([S('Informationsmosaik und Insiderinformation unterscheiden',`Wesentlichkeit betrifft die Bedeutung für eine vernünftige Anlageentscheidung; Öffentlichkeit betrifft die Verfügbarkeit für den Markt. Beide Achsen müssen getrennt untersucht werden. Eine öffentliche Umsatzmeldung darf analysiert werden. Eine vertrauliche, konkrete Übernahmeentscheidung kann auch dann wesentlich bleiben, wenn der Analyst bereits öffentliche Übernahmegerüchte gesammelt hat.

Die Mosaic Theory beschreibt die Bildung einer Analyse aus zulässigen Bausteinen. Die Schlussfolgerung kann erheblich sein, obwohl einzelne nicht öffentliche Bausteine unwesentlich sind. Dagegen wird ein wesentlicher vertraulicher Baustein nicht durch viele öffentliche Daten neutralisiert. Der Übergang hängt vom Informationsgehalt ab, nicht von der Zahl der Quellen.`),S('Manipulation: Preisbewegung ist nicht der alleinige Maßstab',`Große legitime Orders können Preise bewegen. Manipulation betrifft dagegen das Erzeugen irreführender Signale, etwa durch fingierte Nachfrage oder bewusst falsche Informationen. Bei der Analyse werden wirtschaftlicher Zweck, tatsächliches Risiko, Kommunikation und Handelsmuster zusammen betrachtet. Eine profitable Transaktion ist für sich genommen weder Beweis noch Entlastung.

Bei möglicher wesentlicher nicht öffentlicher Information ist eigenmächtiges Weitergeben keine Lösung. Handel und Empfehlungen dürfen die Information nicht ausnutzen; geeignete interne Stellen klären Behandlung und Beschränkungen. Ebenso wenig macht ein verspäteter persönlicher Handel die vorherige Weitergabe an andere unproblematisch.`)],C('Eine Tatsache kippt die Beurteilung','Ein Analyst prognostiziert eine Gewinnwarnung.',['Information','Öffentlichkeit / Bedeutung','Nutzung'],[['Veröffentlichte Absatzdaten und unwesentliche Lieferantenbeobachtung','Zulässige Analysebausteine unter den getroffenen Annahmen','Eigene Schlussfolgerung möglich'],['Vertrauliche konkrete Warnung des Finanzvorstands','Wesentlich und nicht öffentlich','Nicht für Handel oder Empfehlung nutzen']],'Beide Analysen könnten dieselbe Prognose ergeben. Maßgeblich ist der Weg zur Information. Die zweite Variante darf nicht als bloß besonders gutes Research dargestellt werden. In Prüfungsfällen ist deshalb jede Quelle einzeln zu klassifizieren.'),[['equity-03','Markteffizienz erklärt die Bedeutung von Informationsverarbeitung.'],['ethics-06','Quellen und Schlussfolgerungen dokumentieren.']]),
D([S('Eignung entsteht aus Ziel und Gesamtposition',`Ein Produkt wird nicht allein durch seine erwartete Rendite geeignet. Die Prüfung verbindet erforderliche Zahlungen, Verlusttragfähigkeit, Anlagehorizont, vorhandene Positionen und Vertragsrestriktionen. Ein Unternehmer kann über seine Firma und sein Arbeitseinkommen schon stark demselben Risiko ausgesetzt sein, das ein neuer Fonds zusätzlich einbringt.

Bei diskretionären Mandaten ist der vereinbarte Gesamtauftrag maßgeblich; bei einer einzelnen Empfehlung muss deren Eignung im relevanten Kontext beurteilt werden. Unaufgeforderte Kundenwünsche werden nicht automatisch durch eine Warnung passend. Eine wesentliche Abweichung erfordert Klärung, gegebenenfalls eine Anpassung des Mandats oder Verzicht auf eine ungeeignete Umsetzung.`),S('Fairness, Loyalität und Vertraulichkeit zusammenführen',`Faire Behandlung bedeutet ein sachgerechtes Verfahren, nicht identische Portfolios oder sekundengleiche persönliche Gespräche. Zuteilungsregeln müssen vor Kenntnis günstiger Ergebnisse feststehen, damit attraktive Ausführungen nicht nachträglich bevorzugten Konten zufallen. Unterschiedliche Dienstleistungen können legitim sein, wenn sie transparent sind und andere Kunden nicht unfair benachteiligen.

Der Kunde im beruflichen Sinn muss richtig identifiziert werden. Bei einem Pensionsfonds sind Begünstigteninteressen von persönlichen Interessen des anweisenden Managers zu trennen. Vertrauliche Informationen werden geschützt; Ausnahmen sind anhand tatsächlicher Befugnis und einschlägiger Anforderungen zu prüfen. Bequeme interne Weitergabe ist kein eigener Rechtfertigungsgrund.`)],C('Gleiches Produkt, unterschiedliche Eignung','Ein zehn Jahre gebundener Fonds mit identischer Strategie und Kosten wird zwei Anlegern angeboten.',['Kunde','Liquiditätsbedarf','Schlussfolgerung'],[['A','Gesicherte Reserve; Geld langfristig frei','Weitere Risiko- und Eignungsprüfung sinnvoll'],['B','Gesamter Betrag in zwölf Monaten für feste Zahlung nötig','Bindung widerspricht dem bekannten Bedarf']],'Die erwartete Fondsrendite kann in beiden Fällen gleich sein. Der entscheidende Unterschied ist die Verfügbarkeit des Geldes. Eine hohe Risikobereitschaft von B hebt die Zahlungsfrist nicht auf; diese Unterscheidung verbindet Ethik direkt mit Asset-Liability-Management.'),[['portfolio-06','Mandatsziele und Restriktionen festhalten.'],['advanced-03','Verpflichtungen in Vermögensentscheidungen übersetzen.']]),
D([S('Aufsichtspflicht als Regelkreis',`Wirksame Aufsicht verbindet Prävention, Erkennung und Reaktion. Prävention legt Zuständigkeiten, zulässige Tätigkeiten und Schulung fest. Erkennung prüft Daten und Ausnahmen. Reaktion untersucht Hinweise, begrenzt laufende Gefahren und beseitigt die Ursache. Nur einen dieser Schritte zu erfüllen lässt systematische Lücken offen.

Delegation kann fachlich erforderlich sein, hebt aber die Verantwortung für angemessene Überwachung nicht auf. Kontrolltiefe muss Risiko, Teamgröße und Tätigkeit berücksichtigen. Wer eine Aufsichtsfunktion ohne ausreichende Befugnisse oder Verfahren übernehmen soll, muss diese Lücke vor der Übernahme adressieren; eine bloße Unterschrift schafft keine funktionierende Kontrolle.`),S('Loyalität ist keine Verpflichtung zu Fehlverhalten',`Die Interessen des Arbeitgebers umfassen vertrauliche Daten, Arbeitsleistung und berechtigte Geschäftschancen. Eigene Erfahrung und Fähigkeiten sind davon zu unterscheiden. Bei einem Wechsel kommt es darauf an, welche Unterlagen wem gehören und welche Informationen geschützt sind; Erinnerungswissen ist keine pauschale Erlaubnis, vertrauliche Kundeninformationen zu verwenden.

Zusätzliche Vergütung kann Zeit, Loyalität und Kundenauswahl beeinflussen. Eine organisatorische Prüfung muss die relevante Zustimmung und Transparenz vor der Tätigkeit herstellen. Bei Fehlverhalten des Arbeitgebers sind Unterstützen, Schweigen, interne Eskalation und Distanzierung unterschiedlich zu beurteilen. Welche externen Schritte erforderlich sind, hängt zusätzlich von den anwendbaren Regeln ab.`)],C('Gleicher Warnhinweis, andere Reaktion','Eine Leitung erfährt von verdächtigen Eigengeschäften vor Kundenorders.',['Reaktion','Unmittelbare Wirkung','Verbleibendes Problem'],[['Nur jährliche Schulung wiederholen','Keine Klärung des konkreten Vorgangs','Mögliche fortdauernde Verstöße'],['Untersuchen, geeignete Beschränkung, Kontrolle der Abhilfe','Konkreten Mechanismus adressieren','Wirksamkeit weiter überwachen']],'Schulung ist eine präventive Maßnahme. Nach einem konkreten Hinweis reicht sie allein regelmäßig nicht aus, weil sie weder Tatsachen feststellt noch weitere Vorgänge zuverlässig begrenzt. Das Beispiel zeigt, warum die Maßnahmen zum Stadium des Problems passen müssen.'),[['ethics-07','Transaktionsvorrang überwachen.'],['practice-01','Kontrollen nachvollziehbar dokumentieren.']]),
D([S('Von Rohdaten zu einer vertretbaren Empfehlung',`Eine Analyse besteht aus Daten, Transformation, Modell und Urteil. Jeder Übergang kann Fehler erzeugen: Der Datensatz kann Überlebende bevorzugen, eine Formel falsche Einheiten verwenden, das Modell einen Strukturbruch ignorieren oder die Kommunikation Unsicherheit verschweigen. Eine tragfähige Grundlage verlangt Prüfungen an allen vier Stellen.

Bei fremdem Research und KI-Ausgaben bleibt die Eignung der Grundlage zu beurteilen. Ein seriöser Anbieter reduziert bestimmte Risiken, macht eine Untersuchung aber nicht automatisch für jedes Mandat passend. Relevante Kontrollen betreffen Datenherkunft, Modellannahmen, aktuelle Änderungen und den Umfang der eigenen Nachprüfung.`),S('Nachvollziehbarkeit trotz unsicherer Zukunft',`Fakten sind beobachtete Angaben, Schätzungen bedingte Zahlen und Meinungen bewertende Schlussfolgerungen. Die Trennung erlaubt einem Leser, anderer Meinung zu sein, ohne die Rechnung neu rekonstruieren zu müssen. Ein Kursziel sollte daher seine Treiber und Empfindlichkeit offenlegen. Auch wesentliche Änderungen des Analyseprozesses können für Kunden entscheidend sein.

Dokumentation ist kein möglichst großer Dateibestand. Sie muss die damalige Empfehlung reproduzierbar machen: verwendete Datenversion, Annahmen, methodische Auswahl und Freigaben. Nachträgliches Überschreiben der ursprünglichen Prognose erschwert diese Prüfung. Archivierungsanforderungen richten sich nach den einschlägigen Regeln und nicht nach einer universell erfundenen Aufbewahrungsfrist.`)],C('Gleiche Modellrechnung, andere Kommunikation','Ein Bewertungsmodell liefert 80; in einem plausiblen schwächeren Szenario 60.',['Bericht','Was der Kunde erfährt','Bewertung'],[['„Der sichere Wert beträgt 80.“','Keine Bedingtheit','Gewissheit wird übertrieben'],['„Basisszenario 80; schwächeres Wachstum 60; zentrale Annahmen …“','Werttreiber und Unsicherheit','Bedingte Aussage nachvollziehbar']],'Die zweite Darstellung ist nicht durch ihre Länge besser, sondern weil sie den Zusammenhang zwischen Annahme und Ergebnis offenlegt. Sensitivitäten ersetzen ihrerseits keine plausible Begründung der Bandbreite.'),[['equity-08','Wachstumsannahmen verändern Bewertungsnenner.'],['quant-12','Modelle und Backtests unabhängig überprüfen.']]),
D([S('Konflikte als konkurrierende Handlungsanreize erkennen',`Ein Konflikt besteht bereits, wenn ein eigenes Interesse das berufliche Urteil beeinflussen könnte. Ein tatsächlicher Schaden ist keine Voraussetzung. Neben Eigengeschäften gehören Vermittlungsvergütung, Beteiligungen, familiäre Beziehungen und andere Mandate in die Analyse. Die Frage ist, wessen Vorteil durch welche Entscheidung steigen würde.

Vermeidung beseitigt die konkurrierende Position; organisatorische Kontrolle begrenzt ihren Einfluss; Offenlegung versetzt andere in die Lage, den verbleibenden Konflikt zu beurteilen. Diese Maßnahmen sind nicht austauschbar. Eine unfaire Transaktion wird durch Bekanntgabe nicht fair, und eine unvermeidbare Beziehung muss so verständlich erläutert werden, dass ihre Bedeutung erkennbar ist.`),S('Transaktionsvorrang und Reihenfolge',`Bei konkurrierenden Kunden- und Eigentransaktionen darf die eigene wirtschaftliche Position nicht bevorzugt werden. Relevant sind tatsächliche Begünstigung und Kontrolle, nicht nur der Kontoname. Ein Familienkonto mit eigener wirtschaftlicher Beteiligung kann deshalb anders zu behandeln sein als ein unabhängiges Kundenkonto eines Familienmitglieds.

Eine faire Reihenfolge braucht vorab definierte Regeln, zeitnahe Aufzeichnungen und Überwachung. Werden Orders erst nach günstigen oder ungünstigen Ausführungen Konten zugeteilt, entsteht ein Anreiz zur Ergebnisverschiebung. Auch Empfehlungsvergütungen müssen dem Empfänger so offengelegt werden, dass er die wirtschaftliche Beziehung beurteilen kann.`)],C('Offenlegung und Abhilfe getrennt testen','Ein Berater erwartet, dass eine große Kundenorder den Kurs anhebt.',['Vorgehen','Konflikt offengelegt?','Kundenpriorität gewahrt?'],[['Vorher privat kaufen, anschließend informieren','Ja, nachträglich','Nein'],['Eigengeschäft nach sachgerechter Kundenabwicklung und geltenden Kontrollen','Angemessen vor Entscheidung behandeln','Kann gewahrt sein']],'Der erste Fall zeigt den Unterschied zwischen Transparenz und zulässigem Verhalten. Die Reihenfolge verändert, wer von der erwarteten Marktbewegung profitiert. Eine Offenlegung ist daher kein Freibrief für den zugrunde liegenden Vorteil.'),[['equity-02','Marktwirkung großer Orders verstehen.'],['ethics-05','Eigengeschäftsregeln wirksam beaufsichtigen.']]),
D([S('Statusangaben und Leistungsversprechen trennen',`Eine Qualifikation beschreibt einen nachgewiesenen Status. Sie garantiert weder bestimmte Renditen noch eine überlegene Prognosefähigkeit. Eine korrekte Berufsbezeichnung kann deshalb in einer insgesamt irreführenden Werbeaussage verwendet werden. Geprüft wird der Gesamteindruck, nicht nur die Schreibweise einzelner Buchstaben.

Kandidatenstatus, bestandene Prüfungsstufe und Berechtigung zur Verwendung der Bezeichnung sind unterschiedliche Sachverhalte. Die Darstellung muss den tatsächlichen aktuellen Status wiedergeben. Ein früherer Status darf nicht als gegenwärtige Teilnahme ausgegeben werden; ebenso ist ein einzelnes bestandenes Level keine Teilqualifikation, die einen Charter ersetzt.`),S('Prüfungsintegrität schützt Vergleichbarkeit',`Eine Prüfung soll Fähigkeiten unter gleichen Bedingungen messen. Vertrauliche Aufgaben, unerlaubte Hilfsmittel oder detaillierte Weitergabe geschützter Prüfungsinhalte verschieben diesen Vergleich. Dass eine Prüfung bereits beendet ist, beendet nicht automatisch die Vertraulichkeit ihrer Inhalte.

Allgemeine Aussagen über Vorbereitung oder persönliche Schwierigkeit sind von der Offenlegung konkreter Aufgaben zu trennen. Bei Fallfragen helfen zwei Prüfungen: Ist die Information öffentlich freigegeben, und wird durch ihre Weitergabe die Integrität des Programms beeinträchtigt? Die jeweils aktuellen Programmregeln sind die maßgebliche Grundlage.`)],C('Nur den Aussageinhalt verändern','Zwei Absolventen beschreiben dieselbe Berufserfahrung.',['Aussage','Implikation','Problem'],[['„Die Qualifikation ergänzt meine Ausbildung.“','Beschreibung des Hintergrunds','Keine Renditegarantie enthalten'],['„Durch die Qualifikation sind höhere Renditen garantiert.“','Zukunftserfolg zugesichert','Unzulässige Schlussfolgerung aus dem Status']],'Die Qualifikation kann fachlich relevant sein, liefert aber keinen mathematischen Beweis für künftige Überrenditen. Dieser Denkfehler ähnelt der Verwechslung eines historischen Track Records mit sicherer zukünftiger Fähigkeit.'),[['advanced-10','Unsicherheit von Leistungsnachweisen.'],['practice-07','Aussagen präzise und begründet formulieren.']]),
D([S('Von individueller Integrität zur Organisation',`Ein Verhaltenskodex für Asset Manager übersetzt Grundsätze in unternehmensweite Prozesse. Kundeninteressen, Investmentprozess, Handel, Risikomanagement, Performance und Offenlegung müssen zusammenpassen. Ein sorgfältiger Analyst hilft wenig, wenn die Organisation anschließend Orders unfair verteilt oder Risiken verschweigt.

Entscheidend ist die Verantwortungsarchitektur: Wer darf ein Modell einsetzen, wer prüft Interessenkonflikte, wer bewertet illiquide Positionen und wer korrigiert Kundenberichte? Unabhängige Kontrollen reduzieren das Risiko, dass dieselbe Stelle einen wirtschaftlichen Anreiz besitzt und zugleich die eigene Leistung beurteilt.`),S('Kontrollgestaltung an einem vollständigen Ablauf prüfen',`Ein Prozess lässt sich an einem fiktiven Geschäft vom Auftrag bis zum Kundenbericht testen. Dabei werden Freigabe, Ausführung, Verbuchung, Bewertung, Gebühren und Kommunikation verfolgt. Schnittstellen sind besonders anfällig: Eine korrekte Order kann im falschen Konto landen oder ein richtiger Marktpreis kann mit falschem Bestand multipliziert werden.

Notfallplanung und laufende Überwachung sichern die Fortsetzung wesentlicher Leistungen. Outsourcing verändert die Durchführung, beseitigt aber nicht die Notwendigkeit einer angemessenen Auswahl und Kontrolle des Dienstleisters. Eine erklärte Einhaltung des Kodex muss auf tatsächlicher Umsetzung beruhen; eine allgemeine Werbeaussage ist kein Prüfbericht.`)],C('Gleiche Richtlinie, unterschiedliche Umsetzung','Zwei Firmen untersagen nachträgliche bevorzugte Orderzuteilung.',['Firma','Prozess','Wirkung'],[['A','Zuteilung vor Ausführung erfasst und unabhängig geprüft','Verstoß wird verhindert oder erkennbar'],['B','Zuteilung nach Tagesende frei änderbar','Richtlinie ohne wirksame Kontrolle']],'Beide Richtlinientexte sind identisch. Erst die Daten, Berechtigungen und Kontrollen bestimmen, ob das Kundeninteresse geschützt wird. Dieses Vorgehen eignet sich auch für die Due Diligence bei der Managerauswahl.'),[['advanced-11','Organisation und Prozess eines Managers untersuchen.'],['ethics-10','Performanceberichterstattung ist Teil der Kontrollkette.']]),
D([S('Renditeberechnung und Auswahl der dargestellten Konten',`Faire Performance braucht sowohl korrekte Mathematik als auch eine sachgerechte Grundgesamtheit. Eine richtig berechnete Rendite eines nachträglich ausgewählten Gewinnerkontos kann ein irreführendes Bild der Strategie erzeugen. Composites fassen Portfolios nach nachvollziehbaren Strategiedefinitionen zusammen; ihre Zusammensetzung darf nicht opportunistisch nach Ergebnissen verändert werden.

Zeitgewichtete Renditen entfernen den Einfluss externer Zahlungsgrößen durch Teilperiodenbildung. Geldgewichtete Renditen berücksichtigen dagegen die tatsächlich investierten Beträge und Zeitpunkte. Welches Maß nach GIPS für einen konkreten Fall anzuwenden ist, hängt von den einschlägigen Anforderungen ab. Die mathematische Unterscheidung bleibt unabhängig davon wichtig.`,T`R_{\mathrm{TWR}}=\prod_{j=1}^{n}(1+r_j)-1,\qquad R_{C,t}=\sum_i w_{i,t}r_{i,t}`),S('Brutto, netto, Composite und Firma',`Gebühren und Kosten verändern die Aussage einer Rendite. „Brutto“ bedeutet nicht automatisch vor sämtlichen Kosten; Begriffe müssen entsprechend dem verwendeten Standard definiert werden. Ebenso sind Portfoliorendite, Compositeergebnis und die Erklärung der firmweiten Einhaltung verschiedene Ebenen.

Eine unabhängige Verifizierung untersucht die einschlägigen firmweiten Prozesse und Anforderungen. Sie garantiert weder zukünftige Leistung noch macht sie jede einzelne Zahl zu einer separat geprüften Zusicherung. Der Umfang einer Verifizierung und einer gegebenenfalls zusätzlichen Performanceprüfung muss korrekt beschrieben werden. Für eine konkrete Präsentation sind das aktuelle GIPS-Handbuch und die anwendbaren Bestimmungen heranzuziehen.`)],C('Gleiche Konten, andere Auswahl','Zwei gleich große Konten derselben Strategie erzielen +20 % und −10 %, ohne externe Cashflows.',['Darstellung','Ausgewiesene Einperiodenrendite','Information'],[['Nur Gewinnerkonto','20 %','Verlustkonto ausgeblendet'],['Beide gleich gewichteten Konten','5 %','Ergebnisse der gesamten dargestellten Gruppe']],'Die 5 % entstehen als halbe Summe der beiden Kontorenditen. Die Abweichung zu 20 % ist kein Rechenfehler im Gewinnerkonto, sondern ein Auswahlproblem. Bei ungleichen Vermögen wären passende Vermögensgewichte erforderlich; die einfache Mittelung wäre dann nicht dieselbe Aussage.'),[['advanced-12','Compositeberechnung und Verkettung vertiefen.'],['quant-04','Zeit- und geldgewichtete Rendite herleiten.']]),
D([S('Grenzfälle mit einer Tatsachenvariation lösen',`Schwierige Ethikfälle enthalten oft eine plausible Handlung mit einem entscheidenden zusätzlichen Detail. Statt intuitiv die sympathischste Antwort zu wählen, wird dieses Detail isoliert: War die Information öffentlich? Lag eine erforderliche Zustimmung rechtzeitig vor? Wurde ein Konflikt verständlich offengelegt? Passte die Empfehlung zum Mandat?

Eine gute Begründung nennt die einschlägige Pflicht, ordnet die konkrete Tatsache ein und leitet eine Handlung ab. Allgemeine Sätze wie „transparent sein“ sind zu unbestimmt, wenn gerade eine Transaktion ausgesetzt oder eine Zustimmung eingeholt werden muss. Fehlende Fakten werden nicht stillschweigend zugunsten einer Antwort erfunden.`),S('Mehrere Standards können gleichzeitig betroffen sein',`Ein verschwiegenes Eigeninteresse kann zugleich die Unabhängigkeit der Analyse, die faire Kundenbehandlung und die Kommunikation beeinträchtigen. Die Analyse endet daher nicht beim ersten gefundenen Etikett. Umgekehrt muss jede behauptete Verletzung durch Tatsachen gestützt sein; nicht jeder Konflikt beweist automatisch Insiderhandel oder Manipulation.

Prävention und Reaktion sind ebenfalls zu trennen. Eine Richtlinie kann das künftige Risiko senken, während ein bereits versandter falscher Bericht noch korrigiert werden muss. Bei der Auswahl der besten Maßnahme ist deshalb zu prüfen, ob sie die konkrete Pflichtverletzung beendet, Betroffene angemessen informiert und Wiederholung begrenzt.`)],C('Vorherige Zustimmung statt nachträglicher Entschuldigung','Eine zusätzliche Vergütung kann mit der beruflichen Tätigkeit konkurrieren; die notwendigen Parteien und Anforderungen seien bekannt.',['Variante','Zeitpunkt','Entscheidender Unterschied'],[['A','Erforderliche informierte Zustimmung vor Vereinbarung und Tätigkeit','Konflikt kann rechtzeitig beurteilt werden'],['B','Mitteilung erst nach Erhalt der Vergütung','Vorherige Beurteilung wurde umgangen']],'Die wirtschaftliche Höhe ist identisch. Der Zeitunterschied verändert dennoch die Möglichkeit, den Konflikt zu verhindern oder Bedingungen festzulegen. Fallentscheidungen verlangen deshalb eine zeitliche Rekonstruktion und nicht nur eine Liste beteiligter Personen.'),[['ethics-01','Urteilsprozess systematisch anwenden.'],['practice-06','Vignetten über entscheidende Fakten lösen.']])
];
