const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Vom Deal-Zugang zur investierbaren Hypothese',`Deal Sourcing schafft Zugang, ersetzt aber keine Prüfung des Preises und der Qualität. Ein Screening untersucht zunächst Strategiepassung, Größenordnung, Finanzierung, Kontrollrechte und offensichtliche Ausschlussgründe. Erst danach rechtfertigt die verbleibende Unsicherheit den Aufwand einer vertieften Due Diligence.

Die Investmentthese benennt, welche operativen oder strukturellen Verbesserungen realistisch sind und warum der Verkäufer sie nicht bereits vollständig im Preis vereinnahmt. Ein exklusiver Zugang kann Verhandlungsspielraum schaffen, ist aber kein Beweis günstiger Bewertung.`),S('Due Diligence als Hypothesentest',`Kommerzielle Prüfung untersucht Markt und Kunden, finanzielle Prüfung nachhaltige Gewinne und Cashflows, rechtliche Prüfung Ansprüche und Verpflichtungen, operative Prüfung die tatsächliche Umsetzbarkeit. Jede Prüfung sollte eine entscheidungsrelevante Annahme bestätigen, verändern oder widerlegen.

Quality of Earnings normalisiert unter anderem Einmaleffekte, Abgrenzungen und verbundene Geschäfte. Ein bereinigter Gewinn ist nur dann aussagekräftig, wenn die Anpassungen nachvollziehbar und künftig tatsächlich entbehrlich sind. Wiederkehrende „Einmalkosten“ sind ein typischer Anlass zur Vertiefung.`)],C('Gleicher ausgewiesener Gewinn, andere Nachhaltigkeit','Beide Zielunternehmen berichten EBITDA 20.',['Ziel','Einmaliger Veräußerungsbeitrag im EBITDA','Normalisiertes EBITDA'],[['A','0','20'],['B','8','12']],'Bei einem beispielhaften Multiplikator von 8 ergäben sich 160 gegenüber 96, wenn alle übrigen Faktoren gleich wären. Die Differenz kommt aus der Ertragsbasis, nicht aus einem anderen Multiplikator. Die Klassifikation des Einmaleffekts muss durch Belege getragen sein.'),[['statements-13','Ergebnisqualität und Abgrenzungen prüfen.'],['equity-07','Eine falsifizierbare Investmentthese formulieren.']]),
D([S('Sources and Uses schließen die Finanzierung',`Ein Transaktionsmodell listet auf der Verwendungsseite Kaufpreis, Schuldentilgung, Gebühren und gegebenenfalls benötigtes operatives Cash. Auf der Finanzierungsseite stehen neues Eigenkapital, neue Schulden und zulässige weitere Quellen. Beide Seiten müssen gleich sein; ein Restbetrag ist ein offener Finanzierungsbedarf.

Die Bewertung bestimmt den ökonomisch vertretbaren Preis. Die Finanzierungsstruktur bestimmt anschließend, wie dieser Preis finanziert wird und welche Eigentümerrisiken entstehen. Eine hohe modellierte Eigenkapital-IRR kann aus Leverage stammen, ohne dass das Unternehmen günstig gekauft wurde.`,T`U=S,\qquad E_0=U-D_{new}-O`),S('Exit-Brücke und Verwässerung',`Der Exitwert wird aus operativem Ergebnis und Bewertungsannahme oder einem anderen passenden Verfahren abgeleitet. Verbleibende Schulden und vorrangige Ansprüche werden abgezogen. Bei mehreren Aktienklassen wird der Rest nach Vertragsrechten verteilt, nicht automatisch proportional.

In Venture-Finanzierungen unterscheidet Pre-Money den Wert vor neuem Kapital und Post-Money nach dessen Zufluss. Bei einer einfachen Runde ohne Sonderrechte ist der Anteil des neuen Investors Einzahlung geteilt durch Post-Money. Optionspools, wandelbare Instrumente und Präferenzen verändern die tatsächliche Verwässerung.`,T`V_{post}=V_{pre}+I,\qquad p_{new}=\frac{I}{V_{post}}`)],C('Gleicher Unternehmenswert, andere Finanzierungsrunde','Pre-Money 80, einfache neue Eigenkapitalrunde ohne Sonderrechte.',['Neue Einzahlung','Post-Money','Anteil neuer Investor','Verbleibender Altanteil'],[['20','100','20 %','80 %'],['40','120','33,33 %','66,67 %']],'Mehr neues Kapital erhöht den Gesamtwert um den Zufluss, reduziert aber den prozentualen Altanteil stärker. Der alte Anspruch hat unmittelbar rechnerisch weiterhin Wert 80. Ob die Finanzierung anschließend Wert schafft, hängt von ihrer Verwendung ab.'),[['corporate-06','Finanzierung und Kapitalkosten abstimmen.'],['alternatives-04','Leverage und Exitbeiträge zerlegen.']]),
D([S('Wertsteigerungsplan an messbare Ursachen binden',`Ein Wertsteigerungsplan verbindet Maßnahmen mit Umsatz, Marge, Kapitalumschlag und Risiko. Preiserhöhungen benötigen eine Nachfrageannahme; Kostensenkungen können Investition oder Qualität beeinflussen; Expansion bindet Working Capital. Die Maßnahmen dürfen nicht als voneinander unabhängige positive Zuschläge addiert werden.

Für jede Maßnahme werden Verantwortlichkeit, Kosten, Zeitplan und Frühindikatoren festgelegt. So lässt sich unterscheiden, ob eine Abweichung aus schlechter Umsetzung oder aus einer falschen ursprünglichen Annahme entsteht. Ein steigender Markt-Multiplikator ist kein operativer Erfolg des Managements.`),S('Exitentscheidung und Beitragserklärung',`Trade Sale, Börsengang, Secondary Buyout und Rekapitalisierung besitzen unterschiedliche Kosten, Käuferkreise und Zeitrisiken. Ein späterer Exit kann höheren Wert ermöglichen, verschiebt aber den Rückfluss und belastet IRR. Ein früher Exit verbessert möglicherweise IRR, ohne den höchsten absoluten Gewinn zu erzielen.

Eine logarithmische Multiplikatorzerlegung kann operative Ergebnisänderung und Multipleänderung exakt für positive Werte trennen. Für Eigenkapital kommen Schuldentilgung und Ausschüttungen hinzu. Die Darstellung sollte keine Finanzierungseffekte als operative Wertsteigerung etikettieren.`,T`\frac{EV_1}{EV_0}=\frac{EBITDA_1}{EBITDA_0}\frac{M_1}{M_0},\quad\ln\frac{EV_1}{EV_0}=\ln\frac{EBITDA_1}{EBITDA_0}+\ln\frac{M_1}{M_0}`)],C('Gleicher Exitwert, andere Ursache','Einstieg EBITDA 10 und Multiple 10, also EV 100.',['Pfad','Exit-EBITDA','Exit-Multiple','Exit-EV'],[['Operative Verbesserung','15','10','150'],['Marktbewertung steigt','10','15','150']],'Beide erzeugen denselben Unternehmenswert. Im ersten Fall stammt er aus höherem Ergebnis, im zweiten aus höherer Bewertung pro Ergebniseinheit. Wiederholbarkeit und Managerbeitrag sind deshalb unterschiedlich zu beurteilen.'),[['advanced-09','Renditen nach ihren Ursachen attribuieren.'],['equity-05','Operative Wachstumstreiber modellieren.']]),
D([S('Fondsverträge legen Kapitalrechte fest',`Ein Limited-Partnership-Vertrag regelt Zusagen, Abrufe, Investitionsperiode, Laufzeit, Gebühren, Ausschüttung und Kontrollrechte. Recycling kann Rückflüsse erneut investierbar machen. Key-Person-, Abberufungs- und Verlängerungsklauseln bestimmen, wie Anleger auf veränderte Umstände reagieren können.

Nicht jede Zusage wird sofort investiert und nicht jede Ausschüttung beendet alle Verpflichtungen. Die Liquiditätsplanung muss daher die konkret vertraglich noch möglichen Abrufe und Rückrufrechte berücksichtigen. Eine historische Durchschnittsabrufkurve ist nur eine Planungsannahme.`),S('Cashflowmodell für den Anleger',`Der Anleger verfolgt Anfangsliquidität, eigene Zuflüsse, Abrufe und Ausschüttungen über die Zeit. Marktstress kann Abrufe beschleunigen und Verkäufe beziehungsweise Ausschüttungen verzögern. Ein scheinbar diversifiziertes Vintage-Portfolio kann dann gemeinsam Liquidität benötigen.

Overcommitment versucht ungenutzte Zusagen zu reduzieren, erhöht aber das Risiko gleichzeitiger Abrufe. Die passende Höhe hängt von sicheren Zuflüssen, Reserven und Verkaufsmöglichkeiten ab. Eine erwartete Ausschüttung sollte im Stress nicht wie garantierter Cash behandelt werden.`,T`Cash_t=Cash_{t-1}+In_t+Dist_t-Calls_t-Out_t`)],C('Gleiche Zusage, andere zeitliche Verteilung','Anfangsliquidität 30, zwei Jahre, keine weiteren Zuflüsse.',['Szenario','Abrufe Jahr 1 / 2','Ausschüttungen Jahr 1 / 2','Liquidität nach Jahr 1 / 2'],[['Basis','10 / 20','0 / 15','20 / 15'],['Stress','25 / 20','0 / 0','5 / −15']],'Die negative Zahl im Stress markiert einen Finanzierungsbedarf, kein zulässiges tatsächliches Bankguthaben ohne Kredit. Der Gesamt-NAV des Fonds kann gleichzeitig positiv sein. Zahlungsplanung und Wertentwicklung müssen deshalb getrennt geprüft werden.'),[['alternatives-01','Zusage und NAV auseinanderhalten.'],['advanced-08','Liquiditätslücken unter Stress identifizieren.']]),
D([S('Strategien nach Wertquelle und Verlustmechanismus',`Buyouts nutzen operative Verbesserung und Finanzierung etablierter Unternehmen. Venture Capital finanziert unsichere Skalierung mit stark asymmetrischen Ergebnissen. Private Debt besitzt begrenztere Aufwärtschance und hängt stärker von Vertragsrang, Zins und Recovery ab. Real Assets verbinden operative Nutzung mit Standort- und Sachwertrisiken.

Die passende Analysemethode folgt dem Zahlungsprofil. Eine Venturebewertung braucht Finanzierungs- und Verwässerungsszenarien, ein Kreditmodell Schuldendienst und Verlustschichten, ein Infrastrukturmodell Bau- und Betriebsphasen. Ein einheitlicher IRR-Schwellenwert erklärt diese Unterschiede nicht.`),S('Risikobudget und gemeinsame Faktoren',`Mehrere Privatmarktstrategien können dieselben Wachstums- oder Refinanzierungsrisiken teilen. Eine Kombination verschiedener Fondsnamen ist daher nicht automatisch wirtschaftlich diversifiziert. Manager, Vintage, Region, Branche und Finanzierung ergänzen die strategische Einteilung.

Eine höhere vertragliche Verzinsung bei Private Debt bietet keine unbegrenzte Kompensation für Ausfall: Die Aufwärtsschance bleibt begrenzt, während der Verlust groß sein kann. Bei Equity ist die Verteilung anders. Die erwartete Rendite muss deshalb zusammen mit der gesamten Auszahlungsstruktur bewertet werden.`)],C('Gleicher Projektendwert, unterschiedliche Ansprüche','Investiert werden insgesamt 100, davon Kredit 60 mit Endanspruch 66 und Eigenkapital 40. Keine Kosten.',['Projektendwert','Kredit erhält','Eigenkapital erhält'],[['40','40','0'],['100','66','34'],['160','66','94']],'Der Kredit partizipiert oberhalb von 66 nicht weiter, Eigenkapital erhält den zusätzlichen Rest. Im schlechten Zustand verlieren beide, aber in unterschiedlichem Ausmaß relativ zu ihrem Einsatz. Genau diese Form der Auszahlung bestimmt die geeigneten Risikomaße.'),[['corporate-01','Anspruchsstruktur als Optionsprofil.'],['alternatives-05','Private Credit und Distressed Debt vertiefen.']]),
D([S('Erfolg nach Cash, Restwert und Zeit beurteilen',`Ein hoher TVPI kann überwiegend aus noch nicht realisiertem NAV bestehen. DPI zeigt dagegen bereits zurückgeflossenes Kapital. IRR gewichtet Zeitpunkte, während ein Multiple die absolute Vervielfachung erfasst. Die Kennzahlen werden gemeinsam benötigt, um Realisierung und Modellbewertung zu unterscheiden.

Eine Subscription Line kann Abrufe beim Anleger verzögern und dadurch seine gemessene IRR erhöhen. Finanzierungskosten und Risiko bleiben bestehen. Ein Vergleich mit und ohne solche Linien oder mit geeigneten Zusatzangaben macht den Effekt sichtbar.`),S('Wertbeiträge und Interessenausrichtung',`Managerbeitrag wird nach operativer Verbesserung, Leverage, Multipleänderung, Timing und Marktumfeld untersucht. Gebühren und Carry reduzieren den Anlegerertrag und können Verhalten beeinflussen. Ein symmetrischer Vergleich betrachtet deshalb Nettoergebnisse und tatsächlich übernommene Risiken.

Co-Investment und GP Commitment können Interessen verbinden, beseitigen aber nicht alle Konflikte. Dealzuteilung, Bewertungsentscheidungen und Exitzeitpunkt bleiben kontrollbedürftig. Ein überzeugender Track Record ist eine Kombination aus Ergebnissen, plausibler Wertquelle und belastbarer Organisation.`)],C('Gleicher Gesamtmultiple, andere Realisierung','Eingezahltes Kapital 100.',['Fonds','Ausschüttungen','Rest-NAV','DPI','RVPI','TVPI'],[['A','150','0','1,5','0','1,5'],['B','30','120','0,3','1,2','1,5']],'Beide berichten TVPI 1,5. A hat den Wert bereits ausgezahlt, B hängt noch wesentlich von künftiger Realisierung des NAV ab. Der Vergleich sagt ohne Zeitpunkte nichts über IRR, zeigt aber den Unterschied zwischen Cash und verbleibender Bewertung.'),[['alternatives-02','Gebühren und Renditemaße definieren.'],['advanced-10','Fähigkeit von Markt- und Timingeffekten trennen.']])
];
