const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Beratungsleistung und Produktvertrieb unterscheiden',`Wealth Management verbindet Vermögensanlage mit Liquidität, Familienzielen, Steuern, Nachfolge und gegebenenfalls Unternehmensvermögen. Die konkrete Dienstleistung muss klar abgegrenzt werden: Wer erstellt den Plan, wer entscheidet, wer setzt um und wer überwacht? Ein Produktangebot allein ist noch kein integrierter Vermögensplan.

Vergütungsmodelle setzen unterschiedliche Anreize. Transaktionsvergütung kann Handel begünstigen, vermögensabhängige Vergütung Vermögen im Mandat halten, Festhonorar den Leistungsumfang begrenzen. Kein Modell ist automatisch konfliktfrei. Entscheidend sind Transparenz, Eignung und die Behandlung konkurrierender Interessen.`),S('Beratung als laufender Entscheidungsprozess',`Zunächst werden Ziele, Ressourcen und Verpflichtungen aufgenommen. Danach werden Handlungsalternativen mit Kosten und Unsicherheit verglichen. Umsetzung und Monitoring prüfen, ob sich Annahmen, Lebenssituation oder Restriktionen geändert haben. Ein einmal unterschriebener Plan ersetzt diese Aktualisierung nicht.

Erfolg sollte an den vereinbarten Zielen gemessen werden. Eine höhere Portfoliorendite kann mit ungeeigneter Liquiditätsbindung erkauft sein. Umgekehrt kann ein bewusst gehaltener Sicherheitsbestand den Erwartungsertrag senken und trotzdem die entscheidende Familienzahlung zuverlässig sichern.`)],C('Gleiche Anlage, unterschiedliche Gesamtkosten','Vermögen 1 Mio., Produktkosten 0,3 %, zusätzliche Beratung entweder 0,5 % oder 1 %. Weitere Kosten ausgeblendet.',['Beratungsmodell','Gesamtquote','Jährlicher Betrag'],[['A','0,8 %','8.000'],['B','1,3 %','13.000']],'Die Differenz von 5.000 ist nur sinnvoll zu beurteilen, wenn Leistungsumfang und Qualität verglichen werden. Ein günstigeres Angebot kann unvollständig sein; ein teureres muss seinen zusätzlichen Nutzen begründen. Die Kostenbasis muss alle vergleichbaren Bestandteile enthalten.'),[['ethics-07','Vergütung und Interessenkonflikte offenlegen.'],['portfolio-06','Ziele vor Produktauswahl festlegen.']]),
D([S('Die wirtschaftliche Familie ist mehr als ein Depot',`Ein vollständiges Kundenprofil umfasst liquide Anlagen, Immobilien, Unternehmen, Humankapital, Schulden und künftige Ansprüche. Auch Abhängigkeiten zwischen Arbeitseinkommen und Vermögenswerten zählen. Ein Unternehmer kann im Depot konservativ erscheinen und im Gesamtvermögen trotzdem stark konzentriert sein.

Familienmitglieder können unterschiedliche Ziele, Zeithorizonte und Entscheidungsmacht besitzen. Rechtliches Eigentum, wirtschaftlicher Nutzen und tatsächliche Kontrolle sind getrennt zu erfassen. Ein gemeinsamer Familienplan benötigt deshalb klare Zuständigkeiten und eine verständliche Konfliktlösung.`),S('Family Governance und Entscheidungsregeln',`Family Governance legt fest, wie Informationen geteilt, Entscheidungen getroffen und Übergänge vorbereitet werden. Familienrat, Anlageausschuss oder schriftliche Grundsätze können helfen, ersetzen aber keine rechtlich wirksamen Regelungen, wo diese benötigt werden.

Die Anlagepolitik sollte festhalten, welche Ziele gemeinsam und welche individuell verfolgt werden. Unterschiedliche Risikopräferenzen lassen sich nicht immer durch einen einfachen Durchschnitt lösen. Eine feste Verpflichtung eines Familienmitglieds kann eine eigene Reserve benötigen, auch wenn andere langfristig investieren möchten.`)],C('Gleicher Depotwert, unterschiedliche Gesamtposition','Depot jeweils 1 Mio.; davon 60 % Aktien.',['Familie','Weiteres Unternehmervermögen','Wirtschaftliche Konzentration'],[['A','0','Aktienquote beschreibt einen großen Teil des Finanzrisikos'],['B','4 Mio. in eigener Firma','Depotquote unterschätzt Unternehmens- und Einkommensrisiko']],'Bei B beträgt das Unternehmervermögen allein 80 % der betrachteten Vermögenswerte. Der Aktienanteil im Depot ist deshalb kein ausreichendes Gesamtmaß. Eine Beratung muss die gemeinsame Abhängigkeit von Firma, Einkommen und Kapitalanlage berücksichtigen.'),[['path-wealth-05','Konzentrierte Positionen behandeln.'],['portfolio-07','Risikobereitschaft und Verlusttragfähigkeit trennen.']]),
D([S('Lebenszyklus als Zahlungsstrommodell',`In der Ansparphase erhöhen Sparbeiträge das Vermögen; im Ruhestand reduzieren Entnahmen die verbleibende Anlagebasis. Zeitpunkt und Inflation jeder Zahlung sind entscheidend. Humankapital kann als unsicherer Barwert künftiger Arbeitseinkommen betrachtet werden, ist aber meist nicht frei handelbar und kann mit Kapitalmarktrisiken korrelieren.

Eine Rechnung mit konstanter Rendite zeigt eine bedingte Basisplanung. Unsichere Renditen erfordern zusätzliche Szenarien. Langlebigkeit ist ebenfalls eine Zufallsgröße: Planung nur bis zum durchschnittlichen Lebensalter lässt die längere Lebensdauer unzureichend gedeckt.`,T`W_{t+1}=(W_t+C_t-D_t)(1+R_{t+1})`),S('Reihenfolgerisiko mathematisch sichtbar machen',`Ohne Zwischenzahlungen hängt das Endvermögen nur vom Produkt der Wachstumsfaktoren ab; deren Reihenfolge ist gleichgültig. Mit Entnahmen werden jedoch vor jeder folgenden Rendite unterschiedliche Beträge investiert. Frühe Verluste können deshalb den Kapitalstock besonders stark verringern und spätere Erholung auf einer kleineren Basis stattfinden lassen.

Entnahmeflexibilität, Reservevermögen, garantierte Zahlungsansprüche und spätere Arbeitsbeiträge können dieses Risiko unterschiedlich beeinflussen. Keine feste Entnahmequote ist ohne Annahmen über Horizont, Bewertung, Inflation und Anpassungsregeln universell sicher.`,T`W_2=[(W_0-D)(1+r_1)-D](1+r_2)`),S('Nominale und reale Ziele konsistent planen',`Ein heute benötigter Lebensstandard muss über Inflation auf künftige nominale Ausgaben hochgerechnet oder vollständig in realen Größen geplant werden. Steuern und Gebühren reduzieren verfügbare Rendite zusätzlich. Ein nominaler Kontostand kann steigen, während seine Kaufkraft fällt.

Für feste unverzichtbare Ausgaben kann eine andere Risikopolitik passen als für flexible Konsumwünsche oder Erbziele. Zielbasierte Planung macht diese Prioritäten sichtbar, sollte aber gemeinsame Risiken und Kosten der Teilportfolios weiterhin auf Gesamtvermögensebene kontrollieren.`)],C('Gleiche Renditen, nur Reihenfolge ändern','Startvermögen 100, Entnahme 10 jeweils am Jahresanfang. Zwei Jahre mit +20 % und −20 %.',['Reihenfolge','Ende Jahr 1','Ende Jahr 2'],[['+20 %, dann −20 %','108','78,4'],['−20 %, dann +20 %','72','74,4'],['Ohne Entnahmen, beide Reihenfolgen','—','96']],'Erster Pfad: 90 × 1,2 = 108, dann 98 × 0,8 = 78,4. Zweiter Pfad: 90 × 0,8 = 72, dann 62 × 1,2 = 74,4. Die vier Einheiten Unterschied entstehen nur durch die Kombination aus Reihenfolge und Entnahmen.'),[['quant-03','Geometrische Rendite und Wachstumsfaktoren.'],['advanced-03','Verpflichtungen in den Mittelpunkt stellen.']]),
D([S('Steuern verändern Betrag und Zeitpunkt des Zinseszinseffekts',`Eine jährlich besteuerte Rendite lässt nur den Nachsteuerertrag weiterwachsen. Bei aufgeschobener Besteuerung kann zunächst der volle Ertrag reinvestiert werden; die Steuer fällt später auf den nach der angenommenen Regel steuerpflichtigen Gewinn an. Der Unterschied entsteht aus dem Zeitwert der Steuerzahlung.

Die passende Rechnung hängt von Steuerart, Bemessungsgrundlage, Verlustverrechnung und Kontoform ab. Deshalb werden im Lehrmodell Annahmen ausdrücklich gesetzt. Eine allgemeine Formel ersetzt keine aktuelle länder- und personenbezogene steuerliche Prüfung.`,T`W_n^{annual}=W_0[1+r(1-\tau)]^n,\quad W_n^{deferred}=W_0\{1+[(1+r)^n-1](1-\tau)\}`),S('Asset Location und grenzüberschreitende Konsistenz',`Asset Allocation bestimmt die wirtschaftlichen Anlagen, Asset Location ihre Zuordnung zu Konten oder rechtlichen Strukturen. Unterschiedliche laufende Erträge, Umschlagshäufigkeit und Verlustnutzbarkeit können die Nachsteuerrendite beeinflussen. Eine günstige Kontozuordnung darf aber Liquiditäts- oder Rechtsbeschränkungen nicht ignorieren.

Grenzüberschreitende Vermögen können mehrere Steuerzugriffe, Währungen und Nachfolgeregeln verbinden. Ansässigkeit, Quellensteuer und Abkommen müssen anhand des konkreten Falls geprüft werden. Der allgemeine Lernpunkt ist, Bruttoerträge nicht ohne diese Zahlungs- und Rechtsstruktur als frei verfügbaren Wohlstand zu behandeln.`)],C('Gleiche Bruttorendite, anderer Steuerzeitpunkt','Start 100, Bruttorendite 8 %, Steuersatz 25 %, zehn Jahre; keine weiteren Steuern oder Kosten.',['Besteuerung','Endvermögen ungefähr'],[['Jährlich auf Ertrag','179,08'],['Am Ende nur auf gesamten Gewinn','186,92'],['Ohne Steuer als Vergleich','215,89']],'Jährliche Besteuerung lässt nur 6 % wachsen. Bei Aufschub wachsen zunächst 8 %; am Ende bleiben 75 % des Gewinns plus ursprüngliches Kapital. Die Differenz von rund 7,84 ist der Wert des angenommenen Aufschubs, nicht eine Änderung der Bruttoanlage.'),[['quant-01','Zeitwert und Zinseszins.'],['portfolio-10','Steuern in Rebalancingentscheidungen aufnehmen.']]),
D([S('Konzentration über Vermögen und Einkommen messen',`Eine große Position kann finanzielle Rendite, Arbeitseinkommen und persönliche Kontrolle miteinander verbinden. Ihr Risiko wird durch eine isolierte historische Volatilität oft unvollständig beschrieben. Verkaufbarkeit, Veräußerungssteuern, Sperrfristen und emotionale Bedeutung beeinflussen die Handlungsmöglichkeiten.

Die Entscheidung beginnt mit dem maximal tragbaren Verlust relativ zu den übrigen Zielen. Erst danach werden gestufter Verkauf, Diversifikation, Absicherung oder Finanzierung geprüft. Ein erwarteter hoher Firmenwert ersetzt keine Liquiditätsreserve für feste Zahlungen.`),S('Hedges verändern das Auszahlungsprofil',`Ein Put begrenzt Verluste gegen Prämie, ein Collar tauscht einen Teil der Aufwärtschance gegen Finanzierung des Schutzes. Monetarisierungs- oder Kreditstrukturen können Liquidität schaffen, lassen aber je nach Ausgestaltung Markt-, Gegenpartei- und Nachschussrisiko bestehen.

Steuerliche und rechtliche Folgen können die scheinbar einfache ökonomische Absicherung wesentlich verändern. Im Lernmodell wird daher zunächst der Zahlungsmechanismus erklärt und anschließend die Notwendigkeit einer konkreten Prüfung der anwendbaren Regeln festgehalten. Eine Renditekurve allein ist kein vollständiger Umsetzungsplan.`,T`W_T^{collar}=S_T+(K_P-S_T)^+-(S_T-K_C)^+`)],C('Gleiche Konzentration, verschiedene Schutzmaßnahmen','Position heute 100. Put-Strike 80, Call-Strike 120; Collar-Nettoprämie hier illustrativ null.',['Endwert der Aktie','Ungehedgter Wert','Collar-Endwert'],[['50','50','80'],['100','100','100'],['150','150','120']],'Der Collar begrenzt den Endwert auf das Intervall 80 bis 120. Der Preis für Schutz ist hier die abgegebene Aufwärtschance. Zwischenzeitliche Sicherheiten und tatsächliche Prämien müssen für einen realen Vertrag zusätzlich geprüft werden.'),[['derivatives-10','Optionskombinationen nach Zahlungsbereichen erklären.'],['portfolio-07','Tragfähigkeit aus den übrigen Verpflichtungen ableiten.']]),
D([S('Nachfolge verbindet Kontrolle, Versorgung und Übertragung',`Ein Vermögenstransfer kann die Versorgung des Übertragenden, die Verteilung zwischen Begünstigten und den Fortbestand eines Unternehmens betreffen. Diese Ziele können kollidieren: Eine frühe Übertragung reduziert möglicherweise Kontrolle oder Liquidität, ein später Transfer erhöht andere Unsicherheiten.

Rechtliches Eigentum, wirtschaftliche Nutzungsrechte und Entscheidungsbefugnis müssen getrennt geplant werden. Zuständigkeiten, Vertretung bei Handlungsunfähigkeit und verfügbare Liquidität sind ebenso wichtig wie der geschätzte Vermögenswert. Die konkrete Ausgestaltung ist rechtsordnungsabhängig.`),S('Philanthropie und nachhaltiges Ausschüttungsvermögen',`Philanthropische Ziele können sofortige Wirkung, dauerhafte Förderung oder bestimmte Zweckbindungen priorisieren. Eine Stiftung mit langfristiger Ausschüttung benötigt eine konsistente Ausgaben-, Kosten- und Anlagepolitik. Ein hoher Anfangswert allein garantiert keinen dauerhaft gleichen realen Förderbetrag.

Für Transfers werden Steuern und Kosten im jeweiligen Szenario transparent berücksichtigt. Allgemeine Lernrechnungen verwenden ausdrücklich fiktive Sätze und sind keine Aussage über aktuell geltende Freibeträge. Änderungen von Familie, Recht und Vermögensstruktur lösen eine erneute Prüfung aus.`,T`W_N=W_G-\mathcal T-C`)],C('Gleicher Vermögenswert, andere verfügbare Liquidität','Nachlasswert 1 Mio., illustrative sofortige Zahlungen insgesamt 200.000.',['Struktur','Liquide Mittel','Zusätzlicher Finanzierungs- oder Verkaufsbedarf'],[['A','300.000','0'],['B','50.000','150.000']],'Beide Vermögen sind gleich hoch, können die Zahlungen aber unterschiedlich leicht leisten. Ein erzwungener Unternehmens- oder Immobilienverkauf kann zusätzliche Kosten verursachen. Nachfolgeplanung braucht deshalb neben Verteilungsregeln einen Zahlungsplan.'),[['advanced-08','Wert und Zahlungsfähigkeit unterscheiden.'],['portfolio-06','Begünstigtenziele in einer Anlagepolitik festhalten.']])
];
