const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Portfoliovarianz aus der Renditesumme herleiten',`Die Portfoliorendite ist bei festen Anfangsgewichten die gewichtete Summe der Einzelrenditen. Erwartungswerte lassen sich linear addieren. Für die Varianz wird dagegen die quadrierte Abweichung dieser Summe betrachtet. Beim Ausmultiplizieren entstehen neben den Einzelvarianzen auch Kreuzprodukte; ihre Erwartungswerte sind Kovarianzen.

Korrelation normiert Kovarianz durch beide Standardabweichungen. Sie beschreibt lineare gemeinsame Bewegung, nicht jede Form von Abhängigkeit. Eine Korrelation von null bedeutet außerhalb besonderer Verteilungsannahmen nicht Unabhängigkeit. Genau deshalb kann ein Portfolio mit niedriger Durchschnittskorrelation weiterhin gemeinsame Extremverluste besitzen.`,T`R_P=\sum_iw_iR_i,\quad E[R_P]=\mathbf w^T\boldsymbol\mu,\quad \sigma_P^2=\sum_i\sum_jw_iw_j\sigma_{ij}=\mathbf w^T\Sigma\mathbf w`),S('Zwei Anlagen und die Rolle der Kreuzterme',`Bei zwei Anlagen mit Gewichten w und 1−w besteht die Varianz aus drei Komponenten. Der Kovarianzterm kann die Summe der gewichteten Einzelrisiken erhöhen oder senken. Bei perfekter positiver Korrelation gibt es für positive Gewichte keine Volatilitätsreduktion gegenüber dem gewichteten Durchschnitt der Volatilitäten. Bei perfekter negativer Korrelation ist unter passenden Gewichten eine lokale risikolose Kombination möglich.

Die Mindestvarianzquote folgt durch Differenzieren der quadratischen Funktion nach w. Sie kann außerhalb null bis eins liegen; ein Long-only-Mandat muss dann die Randlösung verwenden. Geschätzte Kovarianzen und strukturelle Veränderungen begrenzen die praktische Stabilität.`,T`\sigma_P^2=w^2\sigma_1^2+(1-w)^2\sigma_2^2+2w(1-w)\rho\sigma_1\sigma_2,\quad w_{MV}=\frac{\sigma_2^2-\sigma_{12}}{\sigma_1^2+\sigma_2^2-2\sigma_{12}}`),S('Risikobeiträge sind keine Kapitalgewichte',`Die marginale Veränderung der Portfoliovolatilität ergibt sich aus der Kovarianz eines Titels mit dem Portfolio. Multipliziert mit dem Gewicht entsteht sein Komponentenrisikobeitrag. Diese Beiträge summieren sich unter der homogenen Volatilitätsfunktion zur Gesamtvolatilität.

Ein kleiner hochvolatiler oder stark korrelierter Bestandteil kann einen großen Risikobeitrag besitzen. Eine negativ korrelierte Position kann sogar einen negativen marginalen Beitrag liefern. Kapitaldiversifikation und Risikodiversifikation sind deshalb unterschiedliche Aussagen.`,T`MRC_i=\frac{(\Sigma\mathbf w)_i}{\sigma_P},\quad RC_i=w_iMRC_i,\quad\sum_iRC_i=\sigma_P`)],C('Gleiche Anlagen und Gewichte, nur Korrelation verändern','Zwei Anlagen mit je 20 % Volatilität und gleichen Gewichten.',['Korrelation','Portfoliovolatilität'],[['1','20 %'],['0,5','17,32 %'],['0','14,14 %'],['−0,5','10 %'],['−1','0 % im idealisierten Modell']],'Die Erwartungsrendite verändert sich bei konstanten Einzelannahmen nicht. Die gesamte Risikodifferenz stammt aus dem Kreuzterm. Die Nullrisikovariante benötigt perfekte negative gemeinsame Bewegung und stabile Parameter; sie ist kein allgemein verfügbarer Diversifikationstrick.'),[['quant-05','Varianz und Standardabweichung unterscheiden.'],['portfolio-13','Gemeinsame Stressbewegungen zusätzlich prüfen.']]),
D([S('Nutzen verbindet Ertrag und Risikobudget',`Die Mean-Variance-Nutzenfunktion zieht von erwarteter Rendite eine mit Risikoaversion A gewichtete Varianzbelastung ab. Sie ist exakt für bestimmte Präferenz-Verteilungs-Kombinationen oder eine lokale Näherung. Bei stark schiefen Auszahlungen und Insolvenzgrenzen kann sie wichtige Aspekte übersehen.

Mischt man einen riskanten Fonds mit einer sicheren Anlage, verändert der Anteil y die erwartete Überschussrendite linear und die Varianz quadratisch. Ableiten liefert die optimale Quote. Höhere Risikoaversion senkt die Quote; höhere erwartete Prämie erhöht sie; mehr Varianz senkt sie.`,T`U=E[R]-\frac A2\sigma^2,\quad U(y)=r_f+y(\mu-r_f)-\frac A2y^2\sigma^2,\quad y^*=\frac{\mu-r_f}{A\sigma^2}`),S('Präferenz, Fähigkeit und Restriktion',`Die mathematische Lösung kann über 100 % oder unter null liegen. Das bedeutet Kreditaufnahme oder Shortposition im unbeschränkten Modell. Ein reales Mandat kann beides ausschließen. Dann wird innerhalb des zulässigen Bereichs optimiert, statt die unzulässige Lösung als Empfehlung auszugeben.

Risikobereitschaft beschreibt Präferenz, Risikotragfähigkeit die finanziellen Folgen möglicher Verluste. Wer in Kürze eine feste Zahlung leisten muss, kann trotz hoher subjektiver Risikofreude wenig Verlust tragen. Nutzenfunktionen sind Hilfsmittel zur Konsistenz, keine alleinige Vermessung persönlicher Ziele.`)],C('Gleiche Prämie, unterschiedliche Risikoaversion','Prämie 6 %, Volatilität 20 %, sichere Anlage verfügbar.',['A','Unbeschränkte riskante Quote'],[['2','75 %'],['4','37,5 %'],['8','18,75 %']],'Der Nenner enthält die Varianz 0,04 und nicht die Volatilität 0,20. Verdoppelte Risikoaversion halbiert hier die optimale Quote. Die Zahlen sind bedingte Modellergebnisse und hängen empfindlich von der geschätzten Prämie ab.'),[['quant-13','Optimierung unter Nebenbedingungen.'],['kelly','Logarithmischen Vermögensnutzen und Einsatzquoten vergleichen.']]),
D([S('Effiziente Grenze als Optimierungsproblem',`Für eine vorgegebene erwartete Rendite wird die kleinste erreichbare Varianz gesucht. Die Nebenbedingungen sichern vollständige Gewichtssumme und Zielrendite. Die Gesamtheit der Lösungen bildet die Minimum-Varianz-Grenze; nur der obere Teil oberhalb des globalen Minimums ist im Mean-Variance-Sinn effizient.

Die Kovarianzmatrix muss eine gültige Risikostruktur darstellen. Nahe Singularität kann extreme Gewichte erzeugen. Realistische Grenzen, Schätzfehlerbehandlung und Stabilitätsprüfung sind deshalb Teil der Umsetzung, nicht bloß technische Nacharbeit.`,T`\min_{\mathbf w}\mathbf w^T\Sigma\mathbf w\quad\text{s.t.}\quad\mathbf1^T\mathbf w=1,\quad\boldsymbol\mu^T\mathbf w=\mu^*`),S('Tangentialportfolio und Kapitalmarktlinie',`Mit einer sicheren Anlage bildet jede Kombination mit einem riskanten Portfolio eine Gerade im Rendite-Volatilitäts-Diagramm. Die höchste Steigung erreicht das Portfolio mit maximaler Sharpe Ratio. Im unbeschränkten Modell hängen dessen relativen Gewichte von inverser Kovarianzmatrix und erwarteten Überschussrenditen ab.

Die Kapitalmarktlinie beschreibt effiziente Mischungen aus sicherer Anlage und Tangentialportfolio. Sie gilt nicht als Preisgleichung für jede einzelne Aktie; dafür verwendet das CAPM die Wertpapiermarktlinie mit Beta. Unterschiedliche Kredit- und Anlagezinsen oder Restriktionen verändern die einfache Gerade.`,T`\mathbf w_T\propto\Sigma^{-1}(\boldsymbol\mu-r_f\mathbf1),\qquad E[R_C]=r_f+\frac{E[R_T]-r_f}{\sigma_T}\sigma_C`)],C('Gleiches Tangentialportfolio, andere sichere Beimischung','Riskantes Portfolio: Erwartung 8 %, Volatilität 15 %; sicherer Satz 2 %.',['Riskante Quote','Erwartete Gesamtrendite','Volatilität'],[['0 %','2 %','0 %'],['50 %','5 %','7,5 %'],['100 %','8 %','15 %'],['150 %','11 %','22,5 %']],'Die letzte Zeile unterstellt Kreditaufnahme zum selben sicheren Satz. In der Realität können Finanzierungskosten höher sein oder Leverage verboten. Alle Punkte besitzen im idealisierten Modell dieselbe Überschussrendite je Einheit Volatilität.'),[['portfolio-02','Die individuell passende Mischung wählen.'],['portfolio-04','CML und SML nicht verwechseln.']]),
D([S('Beta aus dem Beitrag zum Marktrisiko',`Im CAPM wird ein zusätzlicher Titel danach beurteilt, wie er das Risiko eines bereits diversifizierten Marktportfolios verändert. Dafür ist seine Kovarianz mit dem Markt entscheidend. Normierung durch die Marktvarianz ergibt Beta. Ein Titel kann hohe eigene Volatilität und trotzdem niedriges Beta besitzen, wenn ein großer Teil seiner Schwankung marktfremd ist.

Die Regressionsdarstellung zerlegt Überschussrendite in Alpha, Marktbeitrag und Residuum. Unter der üblichen orthogonalen Regression zerfällt die Varianz in systematischen und residualen Anteil. Das CAPM behauptet unter seinen Gleichgewichtsannahmen eine Vergütung des systematischen Anteils, nicht jeder beliebigen Einzelunsicherheit.`,T`\beta_i=\frac{Cov(R_i,R_M)}{Var(R_M)}=\rho_{iM}\frac{\sigma_i}{\sigma_M},\quad R_i-r_f=\alpha_i+\beta_i(R_M-r_f)+\varepsilon_i,\quad\sigma_i^2=\beta_i^2\sigma_M^2+\sigma_\varepsilon^2`),S('Wertpapiermarktlinie und erwartete Rendite',`Die Security Market Line verbindet erwartete Rendite mit Beta. Ihr Achsenabschnitt ist der sichere Satz, ihre Steigung die erwartete Marktprämie. Sie gilt im Modell für korrekt bepreiste Anlagen und Portfolios. Die Kapitalmarktlinie verwendet dagegen Gesamtvolatilität und beschreibt nur effiziente Kombinationen.

Die CAPM-Annahmen umfassen unter anderem eine gemeinsame Anlageperiode, Mean-Variance-Entscheidungen und eine geeignete Marktportfoliosicht. Das tatsächlich verwendete Aktienindex-Proxy bildet nicht jedes investierbare Vermögen ab. Empirische Abweichungen können deshalb sowohl Modellgrenzen als auch Fehlbewertung widerspiegeln.`,T`E[R_i]=r_f+\beta_i(E[R_M]-r_f)`),S('Alpha als Rest nach einer ausdrücklich gewählten Erklärung',`Ein realisiertes Einperiodenalpha zieht vom beobachteten Ertrag den modellierten Beitrag aus sicherem Satz und Marktrendite ab. Ein Regressionsalpha wird dagegen über mehrere Beobachtungen als Achsenabschnitt geschätzt. Beide sind vom Modell, der Benchmark, den Kosten und dem Zeitraum abhängig.

Ein positives Alpha kann Fähigkeit, Glück, ausgelassene Faktoren oder Datenfehler enthalten. Zur Beurteilung werden Standardfehler, Stabilität, Auswahlprozess und ökonomische Umsetzbarkeit benötigt. Die Bezeichnung „Überrendite“ ohne Angabe gegenüber welcher Erklärung bleibt unvollständig.`,T`\alpha_i=R_i-[r_f+\beta_i(R_M-r_f)],\qquad t_\alpha=\frac{\widehat\alpha}{SE(\widehat\alpha)}`)],C('Gleiche Gesamtrendite, unterschiedliche Marktexponierung','Beobachtete Portfoliorendite 11 %, sicherer Satz 2 %, Marktrendite 8 %.',['Beta','CAPM-Beitrag','Einperiodenalpha'],[['0,5','5 %','6 %'],['1','8 %','3 %'],['1,5','11 %','0 %']],'Bei Beta 1,5 erklärt das Modell den gesamten Ertrag durch die höhere Marktexponierung. Die gleiche Rendite von 11 % ist bei Beta 0,5 eine viel größere Abweichung. Ob diese Abweichung Können belegt, lässt sich aus einer einzigen Periode nicht entscheiden.'),[['quant-09','Regression und Schätzunsicherheit verstehen.'],['advanced-10','Alpha statistisch und wirtschaftlich beurteilen.']]),
D([S('Faktormodell als Renditezerlegung',`Ein Mehrfaktormodell beschreibt Renditen durch Exponierungen gegenüber mehreren gemeinsamen Treibern und einen idiosynkratischen Rest. Faktoren können makroökonomische Überraschungen, handelbare Stilportfolios oder statistisch geschätzte Komponenten sein. Ihre Skalierung bestimmt die Einheit der Betas.

Ein Renditemodell erklärt beobachtete Schwankungen; ein Preismodell verknüpft Exponierung mit erwarteter Vergütung. Diese Aussagen sind nicht identisch. Ein Faktor kann viel Varianz erklären, ohne eine positive erwartete Prämie zu besitzen.`,T`R_i-r_f=\alpha_i+\sum_{k=1}^{K}\beta_{ik}F_k+\varepsilon_i,\quad E[R_i]-r_f=\sum_k\beta_{ik}\lambda_k`),S('APT und Diversifikation des Restes',`Die Arbitrage Pricing Theory nutzt unter ihren Annahmen die Möglichkeit, idiosynkratisches Risiko in ausreichend großen Portfolios zu diversifizieren. Eine verbleibende systematische Preisabweichung könnte dann durch Faktorabgleich isoliert werden. In endlichen realen Portfolios bleiben Schätzfehler, Kosten und Restexponierung bestehen.

Faktorprämien werden häufig aus vielen getesteten Kandidaten ausgewählt. Daten-Snooping, überlappende Definitionen und instabile Exponierungen können scheinbar starke Ergebnisse erzeugen. Ein neues Modell sollte daher außerhalb der Entwicklungsstichprobe und nach Implementierungskosten geprüft werden.`,T`Var(\varepsilon_P)=\sum_iw_i^2\sigma_{\varepsilon_i}^2\quad\text{bei unkorrelierten Residuen}`)],C('Gleiche Marktexponierung, anderer Stilbeitrag','Sicherer Satz 2 %, Marktprämie 6 %, Valuefaktor realisiert 4 %, beide Portfolios Beta Markt 1 und Rendite 10 %.',['Value-Beta','Erklärte Rendite','Restalpha'],[['0','8 %','2 %'],['0,5','10 %','0 %']],'Was im Einfaktormodell als Alpha erscheint, wird im zweiten Modell durch Valueexponierung erklärt. Das beweist nicht automatisch, dass das zweite Modell wahr ist; es zeigt die Modellabhängigkeit des Leistungsurteils.'),[['portfolio-04','Ein-Faktor-Beta als Ausgangspunkt.'],['advanced-09','Performance nach Faktoren attribuieren.']]),
D([S('Ziele in messbare Kriterien übersetzen',`Ein Investment Policy Statement verbindet den wirtschaftlichen Zweck des Vermögens mit Renditeanforderung, Risikogrenzen und praktischen Restriktionen. Ein Ziel wie „Kapital erhalten“ muss konkretisiert werden: nominal oder real, zu welchem Datum, vor oder nach Ausgaben und Steuern, mit welcher zulässigen Unterdeckungswahrscheinlichkeit?

Die erforderliche Rendite kann aus Anfangsvermögen und künftiger Zielzahlung abgeleitet werden. Bei mehreren Ein- und Auszahlungen ist eine vollständige Cashflowrechnung erforderlich. Eine rechnerisch hohe Zielrendite macht sie nicht am Markt verfügbar. Wenn Ziele und Tragfähigkeit unvereinbar sind, müssen Sparen, Ausgaben, Horizont oder Zielniveau angepasst werden.`,T`r_{req}=\left(\frac{L_T}{A_0}\right)^{1/T}-1`),S('Governance und Änderungsregeln',`Das IPS legt Zuständigkeiten, zulässige Anlagen, Benchmark und Überprüfungsanlässe fest. Es schützt vor spontanen Strategieänderungen nach Marktbewegungen, muss aber auf neue wirtschaftliche Umstände reagieren können. Eine geänderte Familien- oder Verpflichtungssituation ist etwas anderes als eine kurzfristige Marktmeinung.

Liquidität, Steuern, Rechtsrahmen, Zeithorizont und besondere Einschränkungen können sich gegenseitig begrenzen. Ihre Priorität sollte sichtbar sein. Die Portfoliokonstruktion folgt danach innerhalb des zulässigen Raums; ein bevorzugtes Produkt sollte nicht nachträglich die Zieldefinition bestimmen.`)],C('Gleiches Ziel, unterschiedlicher Zeithorizont','Anfangsvermögen 100, Ziel 150, keine Zwischenzahlungen.',['Horizont','Erforderliche Jahresrendite'],[['5 Jahre','8,45 %'],['10 Jahre','4,14 %'],['20 Jahre','2,05 %']],'Jede Rate löst 100 × (1+r)^T = 150. Ein längerer Horizont reduziert die nötige Wachstumsrate, beseitigt aber weder Inflation noch Unsicherheit. Nominalziel und reales Ziel würden unterschiedliche Rechnungen verlangen.'),[['path-wealth-03','Ziele mit Lebenszyklus und Entnahmen verbinden.'],['advanced-03','Verpflichtungen explizit bewerten.']]),
D([S('Risikotragfähigkeit ist an Zahlungen gebunden',`Eine feste kurzfristige Verpflichtung begrenzt den Betrag, der Verluste tragen kann. Illiquides Vermögen oder unsicheres Arbeitseinkommen können diesen Puffer nicht immer rechtzeitig ersetzen. Die Analyse betrachtet deshalb verfügbares Vermögen, Mindestzahlungen und zusätzliche Handlungsmöglichkeiten gemeinsam.

Ein langer Horizont kann Anpassung durch Sparen oder flexible Entnahmen erlauben. Er macht Aktienverluste aber nicht unmöglich. Unterschiedliche Risikomaße reagieren über die Zeit verschieden: Die Streuung durchschnittlicher Jahresrenditen kann sinken, während die absolute Streuung des Endvermögens steigt.`,T`\sigma(\bar R_T)=\frac{\sigma}{\sqrt T}\quad\text{für unabhängige additive Jahresrenditen}`),S('Liquiditäts- und Konzentrationsrestriktionen',`Eine Anlage kann einen hohen erwarteten Ertrag besitzen und trotzdem ungeeignet sein, wenn sie vor einem Zahlungstermin nicht veräußert werden kann. Konzentration entsteht nicht nur durch einzelne Wertpapiere, sondern auch durch gemeinsame Branche, Arbeitgeber, Immobilienstandort oder Währung.

Restriktionen werden möglichst in wirtschaftlichen Größen ausgedrückt: benötigte liquide Mittel, maximal tragbarer Stressverlust oder Exponierung gegenüber einem gemeinsamen Faktor. Reine Produktquoten können hilfreich sein, erfassen die zugrunde liegenden Risiken aber nicht immer vollständig.`)],C('Gleiches Vermögen, andere feste Verpflichtung','Liquides Vermögen 100; konservativ wird die fällige Zahlung vollständig reserviert.',['Feste Zahlung bald','Verbleibender Risikopuffer'],[['20','80'],['60','40'],['90','10']],'Die subjektive Risikobereitschaft kann gleich sein. Trotzdem sinkt der frei verfügbare Puffer mit der Verpflichtung. Eine Portfolioberatung muss beide Dimensionen getrennt erfassen und anschließend zusammenführen.'),[['portfolio-06','Restriktionen im IPS dokumentieren.'],['advanced-08','Liquidität in Stresszuständen prüfen.']]),
D([S('Strategische Allokation als langfristige Entscheidung',`Die strategische Asset Allocation setzt die langfristigen Gewichte im Rahmen der Ziele und Kapitalmarkterwartungen. Sie bestimmt wesentliche Exponierungen gegenüber Wachstum, Inflation, Zinsen und Liquidität. Die wirtschaftlichen Risikotreiber sind dabei oft aussagekräftiger als Produktnamen.

Taktische Allokation weicht vorübergehend von diesen Gewichten ab, weil relative Ertragserwartungen verändert sind. Jede Abweichung verbraucht aktives Risikobudget und erzeugt Handelskosten. Eine taktische Meinung muss deshalb mit Zeithorizont, Rückkehrregel und Verlustgrenze verbunden sein.`,T`\mathbf w_P=\mathbf w_S+\mathbf w_A,\qquad\mathbf1^T\mathbf w_A=0`),S('Schätzunsicherheit und robuste Umsetzung',`Optimale Gewichte reagieren häufig sehr stark auf kleine Unterschiede erwarteter Renditen. Restriktionen, Shrinkage und Szenarioansätze können die Empfindlichkeit reduzieren. Das ist eine wirtschaftliche Reaktion auf unsichere Inputs, nicht bloß ein Wunsch nach schöneren Gewichten.

Eine Allokation muss außerdem umsetzbar sein: illiquide Anlagen werden nicht täglich auf Zielgewicht gebracht, Steuern und Mindestgrößen erzeugen Reibung. Die praktische Strategie kann daher Bandbreiten und schrittweise Anpassung statt eines einzigen exakt einzuhaltenden Punktes vorsehen.`)],C('Gleicher Marktverlauf, andere taktische Abweichung','Aktienrendite +10 %, Anleiherendite 0 %. Strategische Quote 60/40.',['Portfolio','Aktien / Anleihen','Rendite','Aktiver Beitrag'],[['Strategisch','60 / 40','6 %','0'],['Aktien übergewichtet','70 / 30','7 %','+1 %'],['Aktien untergewichtet','50 / 50','5 %','−1 %']],'Der aktive Beitrag ist aktive Aktiengewichtung mal Renditedifferenz der Anlageklassen. Bei umgekehrtem relativen Marktverlauf kehrt sich sein Vorzeichen um. Eine erfolgreiche Einzelperiode belegt deshalb noch keine wiederholbare Timingfähigkeit.'),[['advanced-01','Erwartungen mit Unsicherheitsbandbreiten formulieren.'],['advanced-09','Allokationsbeiträge getrennt messen.']]),
D([S('Vehikelkosten und wirtschaftliche Exponierung',`Fonds und ETFs bündeln Anlagen, können aber sehr unterschiedliche Strategien, Replikationsmethoden und Liquiditätsstrukturen besitzen. Die laufende Kostenquote ist nur ein Teil der Anlegerkosten. Handelskosten, Steuern, Spread, Wertpapierleihe und Trackingeffekte beeinflussen das Ergebnis zusätzlich.

Ein ETF kann im Sekundärmarkt gehandelt werden, während Creation und Redemption autorisierten Teilnehmern den Austausch mit dem Fonds ermöglichen. Dieser Mechanismus unterstützt Preisnähe zum Nettoinventarwert, garantiert aber nicht unter allen Stressbedingungen jederzeit perfekte Übereinstimmung.`,T`TD=R_F-R_B,\qquad TE=\sigma(R_F-R_B)`),S('Aktiv versus passiv als Entscheidung nach Kosten',`Aktives Management versucht durch Auswahl, Gewichtung oder Timing nach Kosten einen Mehrwert gegenüber einem passenden Vergleich zu schaffen. Passive Umsetzung versucht eine definierte Exponierung effizient abzubilden. Auch die Wahl eines Index ist eine wirtschaftliche Entscheidung über Gewichtung und Risiken.

Tracking Difference misst die durchschnittliche beziehungsweise konkrete Renditeabweichung, Tracking Error deren Schwankung. Ein Fonds kann jedes Jahr stabil um Kosten hinter dem Index liegen und einen niedrigen Tracking Error besitzen. Ein niedriger TE bedeutet deshalb nicht automatisch geringe Gesamtkosten oder hohe Rendite.`)],C('Gleiche durchschnittliche Abweichung, andere Stabilität','Vier Jahresabweichungen vom Index, arithmetische Betrachtung.',['Fonds','Abweichungen in Prozentpunkten','Durchschnitt','Schwankung'],[['A','−0,2 / −0,2 / −0,2 / −0,2','−0,2','0'],['B','−1,2 / 0,8 / −1,2 / 0,8','−0,2','Positiv']],'Beide haben dieselbe mittlere jährliche Abweichung. B trägt zusätzlich variierende Abbildungsrisiken. Mehrperiodige Vermögensdifferenzen müssen mit den tatsächlichen Renditen verkettet werden; der einfache Durchschnitt ist dafür nur eine Zusammenfassung.'),[['path-portfolio-01','Indexreplikation und Sampling vergleichen.'],['advanced-10','Aktive Leistung nach Risiko und Kosten beurteilen.']]),
D([S('Gewichtsdrift entsteht durch unterschiedliche Wachstumsfaktoren',`Nach einer Periode ist der neue Wert eines Bestandteils sein Anfangsgewicht mal Portfoliowert mal eigener Wachstumsfaktor. Division durch den neuen Gesamtwert liefert das neue Gewicht. Selbst ohne Handel ändern sich daher Gewichte, wenn Renditen unterschiedlich ausfallen.

Rebalancing verkauft relativ gewachsene Positionen und kauft relativ zurückgebliebene, um das gewünschte Risikoprofil wiederherzustellen. Es ist keine Garantie für Mehrertrag: Bei anhaltenden Trends kann es Gewinner früh reduzieren. Sein primärer Zweck ist die Kontrolle der Exponierung.`,T`w_{i,1}=\frac{w_{i,0}(1+r_i)}{\sum_jw_{j,0}(1+r_j)}`),S('Kalender, Schwellen und Kosten',`Kalenderregeln prüfen in festen Abständen; Bandregeln reagieren auf definierte Abweichungen. Engere Bänder begrenzen Drift stärker, erzeugen aber mehr Handel. Die passende Regel hängt von Volatilität, Korrelation, Kosten, Steuern und dem Risiko unzulässiger Exponierung ab.

Ein- und Auszahlungen können für Anpassungen genutzt werden, um Verkäufe zu reduzieren. Illiquide Anlagen benötigen möglicherweise Zusageplanung statt kurzfristigen Handel. Entscheidend ist die wirtschaftliche Gesamtwirkung nach Kosten und nicht die exakte Rückkehr zu jeder Nachkommastelle eines Zielgewichts.`)],C('Gleiche Startgewichte, anschließende Drift','Anfang 50 Aktien und 50 Anleihen. Aktien steigen 20 %, Anleihen bleiben unverändert.',['Größe','Vorher','Nach Marktbewegung','Nach Rebalancing'],[['Aktienwert','50','60','55'],['Anleihewert','50','50','55'],['Aktiengewicht','50 %','54,55 %','50 %']],'Das neue Gesamtvermögen beträgt 110, daher ist das Ziel je Anlageklasse 55. Verkauft werden 5 Aktienwert, nicht 10. Der Unterschied zeigt, warum auf den neuen Gesamtwert und nicht den alten Ausgangsbetrag rebalanciert wird.'),[['portfolio-01','Gewichte in Risikobeiträge übersetzen.'],['path-portfolio-05','Handelskosten systematisch messen.']]),
D([S('Referenzpunkte verändern die Wahrnehmung',`In der Prospect Theory werden Ergebnisse relativ zu einem Referenzpunkt bewertet. Eine typische Wertfunktion ist für Gewinne konkav, für Verluste konvex und auf der Verlustseite steiler. Dadurch können gleich große Eurogewinne und Euroverluste unterschiedlich stark empfunden werden.

Die Parameter α und β bestimmen die Krümmung, λ die zusätzliche Gewichtung von Verlusten. Diese Funktion ist ein beschreibendes Modell bestimmter Entscheidungen, keine universelle Nutzenform jedes Menschen. Wahrscheinlichkeitsgewichtung ist ein weiterer eigener Bestandteil und wird nicht allein durch Verlustaversion erklärt.`,T`v(x)=\begin{cases}x^\alpha,&x\ge0,\\-\lambda(-x)^\beta,&x<0,\end{cases}\quad 0<\alpha,\beta\le1,\ \lambda>1`),S('Verzerrungen in überprüfbare Gegenmaßnahmen übersetzen',`Dispositionseffekt bezeichnet die Tendenz, Gewinne eher zu realisieren und Verluste festzuhalten. Mental Accounting trennt wirtschaftlich zusammengehörige Vermögensteile gedanklich. Overconfidence kann zu zu engen Prognoseintervallen oder zu hohem Handel führen. Diese Mechanismen benötigen unterschiedliche Gegenmaßnahmen.

Vorab definierte Entscheidungsregeln, schriftliche Gegenargumente und Basisraten können helfen. Ein Prozess sollte aber nicht jede abweichende Präferenz als Fehler behandeln: Ein bewusst gewähltes Sicherheitsziel kann rational zum Mandat passen. Die Analyse unterscheidet inkonsistente Wahrnehmung von legitimen Zielen.`)],C('Gleicher absoluter Betrag, andere subjektive Gewichtung','Vereinfachte Wertfunktion α = β = 1 und λ = 2.',['Ergebnis relativ zum Referenzpunkt','Subjektiver Wert'],[['+100','+100'],['−100','−200'],['50/50-Chance auf beide','Erwarteter subjektiver Wert −50']],'Der monetäre Erwartungswert der symmetrischen Chance ist null. Im illustrativen Modell ist ihr subjektiver Erwartungswert negativ. Das erklärt eine mögliche Ablehnung, beweist aber nicht, dass λ für jede Person genau 2 beträgt.'),[['portfolio-02','Normative Nutzenmodelle mit Verhalten vergleichen.'],['ethics-01','Rückschaufehler bei Urteilen vermeiden.']]),
D([S('VaR ist ein Quantil der Verlustverteilung',`Definiere L als positiven Verlust. Der VaR zum Niveau α ist das kleinste Verlustniveau, das mit Wahrscheinlichkeit mindestens α nicht überschritten wird. Er ist weder maximal möglicher Verlust noch der durchschnittliche Verlust jenseits der Schwelle. Konfidenzniveau, Horizont und Positionsannahmen gehören immer zur Zahl.

Expected Shortfall mittelt die oberen Verlustquantile. Für stetige Verteilungen entspricht er dem bedingten Durchschnitt der Verluste oberhalb des VaR. Die Quantilintegraldefinition bleibt auch bei diskreten Verteilungen sinnvoll, bei denen eine einfache bedingte Erwartung an einer Masse nicht dieselbe Grenze trifft.`,T`VaR_\alpha=\inf\{l:P(L\le l)\ge\alpha\},\qquad ES_\alpha=\frac1{1-\alpha}\int_\alpha^1VaR_u\,du`),S('Normalmodell und seine Annahmen',`Bei normalverteilten Portfoliorenditen ist der Verlust ebenfalls normalverteilt. VaR ergibt sich aus Mittelwert und Standardabweichung mal Normalquantil. Expected Shortfall verwendet zusätzlich die Dichte am Quantil. Eine reine Wurzel-Zeit-Skalierung der Volatilität setzt unter anderem passende unabhängige und stationäre Änderungen voraus.

Historische Simulation verwendet beobachtete Szenarien, parametrische Ansätze eine angenommene Verteilung und Monte Carlo ein simuliertes Modell. Jede Methode besitzt eigene Schwächen. Historie kann relevante Krisen fehlen lassen; Normalmodelle können Tails unterschätzen; Simulation kann ein falsches Modell nur sehr präzise auswerten.`,T`VaR_\alpha=V(-\mu+z_\alpha\sigma),\qquad ES_\alpha=V\left[-\mu+\sigma\frac{\phi(z_\alpha)}{1-\alpha}\right]`),S('Backtesting, Aggregation und Liquidität',`VaR-Ausnahmen werden hinsichtlich Häufigkeit und zeitlicher Häufung untersucht. Eine korrekte durchschnittliche Trefferquote kann trotzdem mit problematischen Clustern zusammenfallen. Expected Shortfall liefert mehr Tail-Information, benötigt aber ebenfalls sorgfältige Validierung und genügend relevante Daten.

VaR ist im Allgemeinen nicht subadditiv; Diversifikation kann unter manchen diskreten Verteilungen den gemessenen VaR erhöhen. ES besitzt unter den üblichen Definitionen kohärente Aggregationseigenschaften. Beide Maße müssen durch Stress- und Liquiditätsanalyse ergänzt werden, wenn Positionen nicht zum Modellpreis geschlossen werden können.`)],C('Gleicher 95-%-VaR, unterschiedliche Katastrophenverluste','100 gleich wahrscheinliche Szenarien: 95-mal Verlust 0, fünfmal der unten genannte Verlust. Quantildefinition wie oben.',['Portfolio','Verlust in den schlechtesten 5 Fällen','95-%-VaR','95-%-ES'],[['A','10','0','10'],['B','100','0','100']],'Beide VaR-Werte sind null, weil bereits 95 % der Masse bei null liegen. ES unterscheidet die Schwere der schlechtesten fünf Prozent. Das bewusst diskrete Beispiel zeigt besonders deutlich, welche Information ein einzelnes Quantil auslässt.'),[['quant-07','Verteilungen und Stichprobenunsicherheit verstehen.'],['portfolio-13','Nicht beobachtete Krisen als Szenario ergänzen.']]),
D([S('Stressszenario braucht einen wirtschaftlichen Mechanismus',`Ein Szenario kombiniert zusammengehörige Veränderungen: etwa schwächeres Wachstum, fallende Aktien, höhere Kreditspreads und veränderte Liquidität. Willkürlich die schlechteste Einzelbewegung jeder Variable zu addieren kann ein inkonsistentes Szenario erzeugen. Historische Szenarien sind konkret, können aber heutige Positionen und Marktstrukturen verfehlen.

Hypothetische Szenarien lassen sich an heutigen Verwundbarkeiten ausrichten. Für nichtlineare Instrumente werden Preise vollständig neu berechnet; eine lineare Sensitivität kann bei großen Schocks wesentliche Optionswirkungen übersehen. Ergebnis und Modellunsicherheit werden getrennt berichtet.`,T`\Delta V_s=V(\mathbf x_s)-V(\mathbf x_0)`),S('Reverse Stress und Maßnahmen',`Reverse Stress beginnt bei einem nicht tragbaren Ergebnis und fragt, welche Kombination von Ereignissen dazu führen könnte. Dadurch werden Konzentrationen und Schwellen sichtbar, die eine normale Szenarioliste übersehen kann. Das Verfahren liefert keine automatische Eintrittswahrscheinlichkeit.

Ein Stresstest ist erst entscheidungsrelevant, wenn er mit Maßnahmen verbunden wird: Liquiditätsreserve, Positionsgrenze, Hedge, alternative Finanzierung oder Eskalation. Manche Maßnahmen sind nur vor dem Stress günstig verfügbar. Deshalb müssen Kosten und Vorlaufzeiten ebenfalls bedacht werden.`)],C('Gleiches Aktienrisiko, unterschiedliche Anleihekorrelation im Stress','Portfolio 60 % Aktien, 40 % Anleihen; Aktien verlieren 30 %.',['Anleiheszenario','Anleiherendite','Portfoliorendite'],[['Deflationärer Stress','+10 %','−14 %'],['Inflationsstress','−10 %','−22 %']],'Der Aktienbeitrag beträgt in beiden Fällen −18 Prozentpunkte. Der Anleihebeitrag ist einmal +4, einmal −4. Die übliche Aussage „Anleihen stabilisieren“ hängt somit vom wirtschaftlichen Stressmechanismus ab.'),[['portfolio-01','Durchschnittskorrelation von Stressabhängigkeit unterscheiden.'],['advanced-08','Marktverluste mit Liquiditätsbedarf verbinden.']]),
D([S('Kennzahl nach dem relevanten Risikonenner wählen',`Sharpe setzt Überschussrendite ins Verhältnis zur Gesamtvolatilität. Treynor verwendet Beta und setzt eine passende diversifizierte Betrachtung voraus. Information Ratio setzt aktive Rendite ins Verhältnis zum Tracking Error. Die Nenner messen verschiedene Risiken; ihre Rangfolgen müssen daher nicht übereinstimmen.

Jensen-Alpha misst eine Abweichung vom gewählten Faktormodell, keine dimensionslose Effizienzquote. Sortino konzentriert sich auf Abweichungen unter einem Ziel, dessen Definition und Schätzverfahren offengelegt werden müssen. Keine einzelne Kennzahl beschreibt alle Ziele eines Mandats.`,T`SR=\frac{R_P-r_f}{\sigma_P},\quad TR=\frac{R_P-r_f}{\beta_P},\quad IR=\frac{R_P-R_B}{TE}`),S('Benchmark und Mehrzielbeurteilung',`Eine Benchmark muss zum Auftrag passen, investierbar beziehungsweise nachvollziehbar sein und vor der Ergebnisbeurteilung feststehen. Ein risikoreicher Fonds gegen Cash kann optisch erfolgreich erscheinen, obwohl seine tatsächliche Exponierung eine andere Vergleichsgröße verlangt. Änderungen der Benchmark nach Kenntnis der Ergebnisse verzerren den Vergleich.

Nachhaltigkeits- oder andere nicht rein finanzielle Ziele benötigen eigene messbare Kriterien und Datenqualität. Finanzielle Rendite, Risikoeinhaltung und Zielerreichung werden zusammen beurteilt, ohne sie durch eine willkürliche Einheitskennzahl zu verdecken. Kosten und Steuern müssen auf derselben Basis wie die Benchmark behandelt werden.`)],C('Gleiche aktive Rendite, anderes aktives Risiko','Beide Manager übertreffen ihre passende Benchmark durchschnittlich um 2 % pro Jahr.',['Tracking Error','Information Ratio'],[['2 %','1,0'],['4 %','0,5'],['8 %','0,25']],'Die gleiche Überrendite wird mit unterschiedlicher Schwankung relativ zur Benchmark erreicht. Die höhere IR ist im Modell effizienter, aber ihre Schätzung kann unsicher sein. Ein kurzer Track Record mit hoher IR ist noch kein verlässlicher Nachweis dauerhafter Fähigkeit.'),[['advanced-10','Kennzahlen auf Schätzunsicherheit prüfen.'],['advanced-09','Ertrag zunächst in Ursachen zerlegen.']])
];
