const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Ein Finanzmodell ist ein Netz wirtschaftlicher Beziehungen',`Ein gutes Modell trennt Eingaben, Berechnungen und Ergebnisse. Eingaben besitzen Quelle, Datum, Einheit und Begründung; Berechnungen verbinden sie mit nachvollziehbaren Formeln. Harte Zahlen mitten in einer Formel erschweren spätere Prüfung, wenn ihre wirtschaftliche Bedeutung nicht sichtbar ist.

Zeitachsen, Vorzeichen und Währungen müssen durchgängig gleich definiert sein. Eine Cashflowzeile kann aus Sicht des Unternehmens positiv und aus Sicht des Investors negativ sein. Die Sichtweise wird vor Beginn festgelegt, damit nicht innerhalb der Rechnung gewechselt wird.`),S('Kontrollen prüfen Identitäten und Verhalten',`Bilanzgleichheit, Cashflowüberleitung und Quellen-Verwendungs-Gleichheit sind sinnvolle Kontrollen, weil sie unabhängige wirtschaftliche Beziehungen testen. Zusätzlich werden Grenzfälle geprüft: null Wachstum, null Zins, keine Schuld oder ein isolierter Preiswechsel. Ein Modell kann formal rechnen und wirtschaftlich falsch reagieren.

Sensitivitäten sind besonders aussagekräftig, wenn erwartete Wirkungsrichtung und Größenordnung vorab bekannt sind. Bei einer optionfreien Festzinsanleihe muss ein höherer Diskontsatz bei positiven Cashflows den Preis senken. Ein Verstoß deutet auf einen Fehler in Formel, Einheit oder Eingabezuordnung hin.`,T`Check_{BS}=A-L-E,\quad Check_{Cash}=Cash_t-Cash_{t-1}-\Delta Cash_t`)],C('Gleicher Modelloutput, unterschiedliche Kontrollfähigkeit','Zwei Tabellen zeigen Eigenkapitalwert 120.',['Modell','Kontrollen','Aussage'],[['A','Keine Überleitungen, manuell gesetztes Cash','Ergebnis schwer nachprüfbar'],['B','Bilanz und Cashflow schließen; Zinssensitivität plausibel','Mehr unabhängige Evidenz für Konsistenz']],'Die identische Zahl ist kein Qualitätsvergleich. Gute Kontrollen machen Ursachen eines Fehlers sichtbar. Sie beweisen nicht jede Prognoseannahme, trennen aber Rechenlogik von wirtschaftlicher Unsicherheit.'),[['statements-15','Integrierte Abschlüsse aufbauen.'],['corporate-04','Cashflows und Diskontsätze konsistent halten.']]),
D([S('Datenbereinigung muss die ökonomische Bedeutung erhalten',`Finanzdaten enthalten Preise, Ausschüttungen, Splits, Währungen und Zeitstempel. Eine Rendite aus unbereinigten Preisen kann einen Split als Verlust interpretieren. Eine bereits um Dividenden bereinigte Reihe zusätzlich um dieselbe Dividende zu ergänzen zählt Ertrag doppelt.

Fehlende Werte sind nicht automatisch null. Unterschiedliche Feiertage und Zeitzonen können Reihen versetzen. Eine veraltete private Bewertung darf nicht wie ein gleichzeitig beobachteter Börsenpreis behandelt werden. Die Bereinigung dokumentiert deshalb jede Transformation und ihren Zweck.`,T`R_t=\frac{P_t+D_t}{P_{t-1}}-1\quad\text{bei konsistenten unbereinigten Preisen ohne Kapitalmaßnahmen}`),S('Reproduzierbarkeit und zeitgerechte Information',`Ein reproduzierbarer Workflow speichert Datenversion, Transformation, Parameter und Zufallsstartwerte. Ergebnisse werden auf kleine bekannte Fälle und unabhängige Identitäten geprüft. Ein Diagramm allein zeigt nicht, ob die zugrunde liegende Tabelle korrekt ist.

Backtests dürfen nur Informationen verwenden, die zum jeweiligen Entscheidungszeitpunkt verfügbar waren. Revidierte Makrodaten, spätere Indexmitglieder oder zukünftige Bilanzwerte erzeugen Look-ahead Bias. Zeitliche Train-Test-Trennung muss auch die Datenvorbereitung und Parameterauswahl umfassen.`)],C('Gleiche wirtschaftliche Aktie, Split ohne Verlust','Eine Aktie zu 100 wird im Verhältnis 2:1 geteilt. Danach besitzt der Anleger zwei Aktien zu 50, keine Dividende.',['Berechnung','Ergebnis'],[['Naiv: 50 / 100 − 1','−50 % scheinbarer Verlust'],['Vermögensvergleich: 2 × 50 / 100 − 1','0 %'],['Konsistent splitbereinigte Preisreihe','0 %']],'Der wirtschaftliche Wert bleibt gleich. Der Fehler entsteht aus nicht vergleichbaren Stückeinheiten. Kapitalmaßnahmen müssen deshalb vor Rendite- und Volatilitätsberechnung korrekt berücksichtigt werden.'),[['quant-14','Datenleckage und Modellvalidierung.'],['equity-01','Aktienzahl und Unternehmenswert unterscheiden.']]),
D([S('Research als Kette überprüfbarer Hypothesen',`Eine Researchfrage beginnt mit einer behaupteten Beziehung: etwa, dass eine höhere Preissetzungsmacht Margen stabilisiert oder ein geldpolitischer Impuls die Finanzierung verteuert. Danach werden passende Daten, alternative Erklärungen und ein Bewertungsmechanismus gewählt. Nur bestätigende Informationen zu sammeln erhöht Confirmation Bias.

Unternehmens-, Makro- und Due-Diligence-Analysen unterscheiden sich in ihren Daten, teilen aber diese Struktur. Beobachtung, Kausalhypothese und Anlageentscheidung sind getrennte Ebenen. Eine korrekte Prognose kann bereits vollständig im Preis enthalten sein.`),S('Triangulation und Widerlegung',`Mehrere unabhängige Quellen können eine Annahme stützen. Drei Berichte, die dieselbe ursprüngliche Quelle abschreiben, sind jedoch keine drei unabhängigen Belege. Besonders bei alternativen Daten werden Abdeckung, Auswahl und mögliche Veränderungen der Datenerzeugung geprüft.

Eine belastbare These benennt außerdem, was sie widerlegen würde. Das erleichtert spätere Aktualisierung und verhindert, dass jedes neue Ergebnis nachträglich passend erklärt wird. Der Bericht sollte den Einfluss einer geänderten Annahme auf Wert und Entscheidung quantifizieren, soweit dies sinnvoll möglich ist.`)],C('Gleiche Umsatzprognose, andere eingepreiste Erwartung','Eigene Prognose: Umsatz wächst 10 %.',['Markterwartung','Informationsabweichung','Mögliche Interpretation'],[['5 %','+5 Prozentpunkte','Positive Überraschung, falls eigene Prognose eintritt'],['10 %','0','Keine erkennbare Prognosedifferenz'],['15 %','−5 Prozentpunkte','Wachstum trotz negativer Überraschung']],'Eine optimistische absolute Zahl genügt nicht für eine Kaufthese. Der Anleger benötigt eine begründete Abweichung von dem, was der Preis bereits voraussetzt, sowie eine Übersetzung in Cashflow und Bewertung.'),[['equity-07','Preis und Investmentthese verbinden.'],['ethics-06','Fakten, Schätzungen und Meinungen kennzeichnen.']]),
D([S('Grafiken müssen dieselbe Aussage wie die Daten zeigen',`Achsen, Einheiten, Zeiträume und Bezugsbasen bestimmen die Interpretation. Ein Linienchart eignet sich für zeitliche Entwicklung, ein Balkendiagramm für diskrete Vergleiche, eine Sensitivitätskurve für den Zusammenhang zwischen Eingabe und Ergebnis. Ein abgeschnittener Maßstab kann kleine Unterschiede groß erscheinen lassen.

Bei Renditen muss zwischen Prozent und Prozentpunkten unterschieden werden. Bei Vermögen können nominale und reale Werte verschiedene Geschichten erzählen. Die Grafik sollte die wirtschaftlich relevante Basis nennen und keine Unsicherheit durch unnötige Dezimalstellen verdecken.`),S('Entscheidungsorientierte Kommunikation',`Eine verständliche Darstellung nennt zunächst die Entscheidung, dann den ausschlaggebenden Mechanismus und die wichtigsten Zahlen. Tabellen eignen sich besonders für kontrollierte Szenarien, weil konstante und veränderte Größen nebeneinander sichtbar werden. Annahmen und Grenzen gehören in unmittelbare Nähe.

Unsicherheitsintervalle, Szenariobänder und Quellenangaben verbessern die Prüfbarkeit. Sie sollten jedoch klar als unterschiedliche Konzepte bezeichnet werden: Ein statistisches Konfidenzintervall ist keine willkürlich gewählte Best-Worst-Spanne und kein Garantieband für den nächsten realisierten Wert.`)],C('Gleiche Rendite, unterschiedliche Darstellungsbasis','Eine Anlage steigt von 100 auf 110, das Preisniveau steigt 5 %.',['Darstellung','Wertänderung'],[['Nominal','+10 %'],['Real','1,10 / 1,05 − 1 = +4,76 %']],'Beide Angaben sind korrekt, beantworten aber verschiedene Fragen. Ein Chart für Kaufkrafterhalt sollte die reale Sicht verwenden oder den Unterschied ausdrücklich zeigen. Nur „Wachstum 10 %“ wäre für dieses Ziel unvollständig.'),[['economics-06','Nominal und real exakt umrechnen.'],['portfolio-14','Kennzahlen an Zielen ausrichten.']]),
D([S('Formeln über Dimensionen und Grenzfälle kontrollieren',`Eine Formel ist eine Beziehung zwischen definierten Größen. Vor dem Einsetzen werden Bedeutung, Einheit, Zeitpunkt und Vorzeichen jedes Symbols festgelegt. Zinssätze werden beispielsweise als Dezimalzahlen eingegeben; 100 Basispunkte entsprechen 0,01 und nicht 1.

Dimensionsanalyse prüft, ob beide Seiten dieselbe Einheit besitzen. Eine Duration in Jahren mal Jahreszinsänderung ergibt eine dimensionslose relative Preisänderung. Multipliziert mit Marktwert entsteht ein Geldbetrag. Diese Kette erklärt die Verbindung zwischen Modified Duration, Dollar Duration und DV01.`,T`\frac{\Delta P}{P}\approx-D_{mod}\Delta y,\quad DD=P D_{mod},\quad DV01=DD\cdot10^{-4}`),S('Vom Symbol zur Zahl ohne versteckte Zwischenschritte',`Der Rechenweg sollte zuerst die allgemeine Formel zeigen, dann Werte mit ihrer Einheit einsetzen und erst am Ende runden. So wird erkennbar, welche Annahme das Ergebnis verändert. Bei mehreren Verzinsungsperioden müssen Rate und Anzahl der Perioden gemeinsam umgestellt werden.

Grenzfälle bieten schnelle Plausibilitätsprüfungen. Bei Zins null entspricht Barwert der Summe sicherer ungewichteter Zahlungen; bei einem Zero Coupon entspricht Macaulay Duration der Restlaufzeit. Eine Näherung sollte zusätzlich mit einem exakten Ergebnis verglichen werden, wenn große Änderungen vorliegen.`)],C('Gleicher Bond, drei Einheiten derselben Sensitivität','Marktwert 200.000, Modified Duration 6.',['Größe','Berechnung','Wert'],[['Dollar Duration','200.000 × 6','1.200.000'],['DV01','1.200.000 × 0,0001','120 je Basispunkt'],['Preisänderung bei +25 bp','−120 × 25','−3.000 linear']],'Die Dollar Duration bezieht sich auf eine Zinsänderung von 1,00, die DV01 auf 0,0001. Die Umrechnung verhindert einen Faktor-10.000-Fehler. Bei größeren Schocks wird Konvexität ergänzt oder der Preis vollständig neu berechnet.'),[['bonds-08','Sämtliche Durationvarianten herleiten.'],['quant-01','Verzinsungseinheiten konsistent umrechnen.']]),
D([S('Vignetten durch wirtschaftliche Zuständigkeit strukturieren',`Eine Fallvignette enthält häufig mehr Information als für eine einzelne Teilfrage nötig. Zuerst wird geklärt, welche Größe gefragt ist und aus wessen Sicht. Danach werden relevante Daten, Zeitpunkte und Annahmen ausgewählt. Ein vertraut wirkendes Stichwort rechtfertigt nicht automatisch die zuerst erinnerte Formel.

Bei verknüpften Fragen können dieselben Ausgangsdaten für Bilanzanalyse, Bewertung und Portfolioentscheidung genutzt werden. Fehler entstehen, wenn eine Zwischengröße ohne Beachtung ihrer Definition weitergereicht wird, etwa Enterprise Value als Eigenkapitalwert oder nominale Rendite als reale.`),S('Antwortoptionen als Diagnose, nicht als Rechenersatz',`Falsche Optionen spiegeln oft typische Fehler: falscher Nenner, fehlende Diskontierung, Prozentpunktverwechslung oder falsches Vorzeichen. Eine unabhängige Herleitung vor der Auswahl verringert die Gefahr, die Rechnung an eine vertraute Antwort anzupassen.

Wenn mehrere Antworten plausibel wirken, werden ihre Annahmen verglichen. Eine Frage nach „am wahrscheinlichsten“ verlangt eine relative Beurteilung unter den gegebenen Informationen, keine absolute Gewissheit. Fehlende Daten werden nicht erfunden, sondern im Rahmen der Aufgabenstellung behandelt.`)],C('Gleiche Zahlen, unterschiedliche gesuchte Größe','Kaufpreis 100, Endpreis 105, Dividende 3, ein Jahr.',['Gefragte Größe','Rechnung','Ergebnis'],[['Kursrendite','(105 − 100) / 100','5 %'],['Dividendenrendite','3 / 100','3 %'],['Gesamtrendite','(105 + 3 − 100) / 100','8 %']],'Alle Zahlen können als Antwortoption erscheinen. Die richtige Auswahl hängt von der ausdrücklich gefragten Größe ab. Ein Rechenfehler ist hier nicht nötig, um falsch zu antworten; eine Definitionsverwechslung reicht.'),[['start-06','Begriffe und Anspruchsebenen sauber definieren.'],['practice-05','Einheiten vor dem Rechnen kontrollieren.']]),
D([S('Begründen heißt Ursache und Folge verbinden',`Eine schriftliche Antwort soll eine konkrete Schlussfolgerung mit einer Tatsache aus dem Fall und einem fachlichen Mechanismus verbinden. „Risiko ist zu hoch“ bleibt unbestimmt. „Die Zahlung in zwölf Monaten kann aus dem gebundenen Fonds nicht rechtzeitig finanziert werden“ benennt dagegen das relevante Risiko und seine Ursache.

Vergleichen verlangt mindestens eine gemeinsame Dimension. Empfehlen verlangt eine Wahl im Kontext der Ziele. Berechnen verlangt nachvollziehbare Größen und Einheit. Die Form der Antwort folgt dem Arbeitsauftrag; zusätzliche unverbundene Fachbegriffe ersetzen keine Begründung.`),S('Präzision und Grenzen der Aussage',`Eine kurze Antwort kann fachlich tief sein, wenn jeder Satz eine notwendige Funktion erfüllt. Erst werden maßgebliche Daten genannt, dann der Zusammenhang, dann die Konsequenz. Bei bedingten Modellergebnissen werden die entscheidenden Annahmen ausdrücklich gemacht.

Widersprüchliche Zusatzbehauptungen können eine richtige Kernaussage entwerten. Deshalb werden Schlussfolgerungen auf das begrenzt, was die vorliegenden Informationen tragen. Eine lange Liste aller denkbaren Risiken ist weniger hilfreich als die beiden tatsächlich entscheidungsrelevanten.`)],C('Gleiche Empfehlung, unterschiedliche Begründung','Empfehlung: Duration der Anlagen erhöhen, weil Verpflichtungsduration höher ist; Marktwerte sind passend abgestimmt.',['Antwort','Prüfbare Logik'],[['„Mehr Anleihen kaufen, das ist sicherer.“','Kein konkreter Risikofaktor oder Umfang'],['„Die geringere Anlageduration lässt die Verpflichtungen bei fallenden Zinsen stärker steigen; zusätzliche DV01 reduziert diese Lücke.“','Fakt, Mechanismus und Ziel verbunden']],'Die zweite Antwort erklärt, warum die Maßnahme zum Verpflichtungsrisiko passt. Sie behauptet nicht, dass jede zusätzliche Anleihe allgemein sicherer ist. Für eine vollständige Umsetzung wären passende Laufzeiten und Kontrakt- beziehungsweise Positionsgrößen zu ergänzen.'),[['advanced-03','ALM-Mechanismus quantitativ verstehen.'],['path-portfolio-06','Fallentscheidung bis zur Umsetzung führen.']]),
D([S('Gemischte Fälle testen Verbindungen zwischen Kapiteln',`Eine vollständige Fallstudie kann mit operativen Daten beginnen, über Bilanz und Cashflow zur Bewertung führen und anschließend eine Portfolioentscheidung verlangen. Jede Stufe verwendet Ergebnisse der vorherigen, verändert aber die Fragestellung. Profitabilität, Unternehmenswert und Eignung für einen bestimmten Anleger sind verschiedene Urteile.

Ein sinnvoller Lernablauf arbeitet zuerst ohne Lösung, dokumentiert Annahmen und kontrolliert anschließend nicht nur das Endergebnis, sondern jeden Übergang. So wird sichtbar, ob ein Fehler aus Fachverständnis, Algebra, Einheiten oder unvollständiger Fragenerfassung stammt.`),S('Fehleranalyse nach Ursache und Wiederholung planen',`Ein Fehlerprotokoll erfasst die falsche Entscheidung, ihre Ursache, die korrigierte Regel und einen neuen Transferfall. Nur dieselbe Aufgabe erneut auswendig zu lösen prüft kaum, ob der Zusammenhang verstanden ist. Ein guter Folgefall verändert eine entscheidende Annahme oder Einheit.

Selbstvertrauen und Trefferquote werden gemeinsam betrachtet. Eine zufällig richtige Antwort mit unsicherer Begründung bleibt ein Lernpunkt; eine selbstsicher falsche Antwort weist auf eine robuste Fehlvorstellung hin. Wiederholung richtet sich deshalb nach Fehlermechanismus und nicht nur nach Kapitelzahl.`,T`\hat p=\frac{k}{n}`)],C('Gleiche Trefferquote, unterschiedlicher Lernbedarf','Beide Lernenden beantworten 8 von 10 Fragen richtig.',['Lernender','Fehlermuster','Sinnvolle nächste Übung'],[['A','Zweimal Basispunkte als Prozent eingegeben','Einheitenumrechnung mit neuen Zahlen und Größen'],['B','Zweimal FCFF und FCFE verwechselt','Anspruchsbrücke aus EBIT und Finanzierung herleiten']],'Die gleiche Quote verdeckt unterschiedliche Ursachen. A benötigt eine stabile Einheitenkontrolle, B ein besseres Verständnis der Zahlungsansprüche. Ein gezielter Transferfall prüft, ob die Korrektur auch außerhalb der ursprünglichen Aufgabe funktioniert.'),[['equity-09','FCFF und FCFE vollständig verbinden.'],['practice-05','Dimensionen und Grenzfälle als Kontrolle nutzen.']])
];
