const {D,S,C,T}=require('./schema.cjs');
module.exports=[
D([
S('Vom Periodenfaktor zur allgemeinen Zinsfunktion',`Die erste Verzinsung erhöht P auf P(1+r). In der zweiten Periode wird auch der erste Zins verzinst; deshalb entsteht P(1+r)². Wiederholung liefert die Potenzformel. Der Exponent zählt Zinsperioden, nicht beliebige Kalenderjahre. Ist r ein Monatszins, muss n Monate zählen. Der Barwert entsteht durch Division durch denselben Wachstumsfaktor.

Ein nominaler Jahreszins j mit m Zinsgutschriften wird in j/m pro Periode übersetzt. Ein effektiver Jahreszins zählt dagegen bereits den vollständigen Jahreszuwachs. Die äquivalente stetige Rate δ ist der Logarithmus des Jahresfaktors. Gleiche wirtschaftliche Verzinsung kann deshalb unterschiedliche Zahlenwerte besitzen, wenn die Konvention wechselt.`,T`FV=P(1+r)^n,\quad r_{eff}=\left(1+\frac jm\right)^m-1,\quad\delta=\ln(1+r_{eff}),\quad FV=Pe^{\delta T}`),
S('Sensitivität gegenüber Zins und Zeit',`Die Ableitung des Barwerts nach dem Zinssatz ist negativ für eine positive zukünftige Zahlung. Ferne Zahlungen reagieren stärker, weil der Zinsfaktor öfter wirkt. Das ist der mathematische Ursprung der Duration eines Zero-Coupon-Bonds. Die Sensitivität hängt nicht nur von T ab, sondern auch vom Ausgangszins und vom heutigen Barwert.

Die Ableitung nach der Laufzeit zeigt ebenfalls: Bei positivem Zins sinkt der Barwert mit längerer Wartezeit; bei negativem Zins kann er steigen. Ein negativer Satz ist mathematisch zulässig, solange der relevante diskrete Wachstumsfaktor positiv bleibt. Das Modell behandelt Zahlungen als sicher beziehungsweise bereits risikogerecht diskontierbar. Unsicherheit darf nicht stillschweigend mit einer beliebigen Zinserhöhung vermischt werden.`,T`PV=F(1+r)^{-T},\quad\frac{\partial PV}{\partial r}=-\frac{T}{1+r}PV,\quad\frac{\partial PV}{\partial T}=-\ln(1+r)PV`)
],C('Zins und Laufzeit getrennt verändern','Jeweils 100 werden später gezahlt. Nur Zeit oder Diskontsatz variieren.',['T','r','PV'],[['1','5 %','95,24'],['10','5 %','61,39'],['1','10 %','90,91'],['10','10 %','38,55']],'Beim Wechsel von 5 % auf 10 % sinkt der einjährige Barwert um rund 4,55 %, der zehnjährige um rund 37,20 %. Der gleiche Zinsunterschied wirkt bei langer Kapitalbindung viel stärker. Die Zahlen werden mit 100/(1+r)^T berechnet; die relative Änderung bezieht sich jeweils auf den ursprünglichen Barwert bei 5 %.'),[['bonds-08','Die relative Ableitung ergibt beim Zero unmittelbar Modified Duration T/(1+r).'],['equity-08','Langfristige Terminalwerte reagieren aus demselben Grund stark auf Diskontsätze.']]),
D([
S('Die Rentenformel aus einer geometrischen Reihe herleiten',`Eine nachschüssige Rente zahlt A erstmals am Ende der ersten Periode. Ihr Barwert ist eine Summe einzelner abgezinster Zahlungen. Setzt man q=1/(1+r), erhält man A(q+q²+…+qⁿ). Multiplikation der Summe mit q und anschließende Subtraktion kürzen die inneren Terme. Übrig bleibt die geschlossene Rentenformel. Sie ist somit eine Abkürzung derselben Cashflowbewertung, kein eigenständiges Bewertungsprinzip.

Bei einer vorschüssigen Rente liegt jede Zahlung eine Periode früher. Daher wird der nachschüssige Barwert mit 1+r multipliziert. Die ewige Rente folgt als Grenzwert n gegen unendlich für r>0. Bei r=0 ist die endliche Rente einfach nA; die formal entstehende Division null durch null muss als Grenzwert behandelt werden.`,T`PV=A\sum_{t=1}^nq^t=A\frac{q(1-q^n)}{1-q}=A\frac{1-(1+r)^{-n}}r,\quad PV_{due}=(1+r)PV,\quad\lim_{n\to\infty}PV=\frac Ar`),
S('Wachsende Renten und Tilgungspläne',`Wächst die Zahlung jährlich mit g, wird jeder nächste Cashflow zusätzlich mit 1+g multipliziert. Die geometrische Reihe hat nun den Quotienten (1+g)/(1+r). Bei einer endlichen Reihe kann r=g als Grenzfall behandelt werden; eine unendliche wachsende Rente benötigt r>g. Je kleiner die Differenz, desto größer die Abhängigkeit des Werts von fernen Zahlungen.

Bei einem Annuitätendarlehen wird die Formel nach A aufgelöst. Jede Rate enthält Zins auf die jeweilige Restschuld und Tilgung als Differenz zwischen Rate und Zins. Weil die Restschuld sinkt, sinkt der Zinsanteil und steigt der Tilgungsanteil. Konstante Rate bedeutet daher nicht konstante Tilgung.`,T`PV=\frac{A_1}{r-g}\left[1-\left(\frac{1+g}{1+r}\right)^n\right],\quad A=P\frac r{1-(1+r)^{-n}},\quad B_t=B_{t-1}(1+r)-A`)
],C('Gleiche drei Zahlungen, andere Lage auf der Zeitachse','Je drei Zahlungen von 100; Zins 5 %.',['Variante','Zeitpunkte','Barwert'],[['Nachschüssig','1, 2, 3','272,32'],['Vorschüssig','0, 1, 2','285,94'],['Alles erst am Ende','3: Zahlung 300','259,15']],'Die nominale Summe ist immer 300. Früheres Geld besitzt bei positivem Zins mehr Wert. Die vorschüssige Variante ist genau um den Faktor 1,05 mehr wert als die nachschüssige. Die endfällige Variante hat keinen frühen Rückfluss und deshalb den niedrigsten Barwert.'),[['equity-08','Das Gordon-Modell ist eine wachsende ewige Rente.'],['statements-07','Leasingverbindlichkeiten verwenden dieselbe Zahlungsreihenbewertung.']]),
D([
S('Arithmetischer Durchschnitt und geometrisches Wachstum',`Der arithmetische Mittelwert beschreibt den Durchschnitt einzelner Periodenrenditen. Die geometrische Rendite ist die konstante Rate, die denselben Endwert wie die tatsächlich verketteten Faktoren erzeugt. Sie wird durch Gleichsetzen des Endvermögens und anschließendes Ziehen der n-ten Wurzel hergeleitet. Unterschiedliche Fragen liefern deshalb unterschiedliche richtige Kennzahlen.

Durch Logarithmieren wird aus dem Produkt der Faktoren eine Summe. Mittlere Logrendite und geometrische Rendite sind exakt über exp verbunden. Die bekannte Näherung geometrisch≈arithmetisch−halbe Varianz stammt aus einer Taylorentwicklung des Logarithmus und ist bei großen Schwankungen oder stark schiefen Verteilungen unzuverlässig. Sie darf nicht als universelle exakte Gleichung verwendet werden.`,T`(1+\bar r_g)^n=\prod_t(1+r_t),\quad\ln(1+\bar r_g)=\frac1n\sum_t\ln(1+r_t),\quad\bar r_g\approx\bar r_a-\frac12s^2`),
S('Warum Volatilität langfristiges Wachstum beeinflusst',`Für einen gegebenen arithmetischen Durchschnitt reduziert Streuung typischerweise den geometrischen Durchschnitt. Der Mechanismus liegt in den wechselnden Vermögensbasen: Nach Verlusten muss auf einer kleineren Basis aufgeholt werden. Das ist kein separates Gebührenkonto, sondern eine Eigenschaft der Multiplikation. Bei einem Totalverlust ist der Wachstumsfaktor null; die Logrendite geht gegen minus unendlich.

Die erwartete Logrendite ist die Zielfunktion des Kelly-Kriteriums. Maximales erwartetes Endvermögen ist dagegen eine andere Zielfunktion und kann viel stärkere Konzentration erzeugen. Ein Anleger sollte daher wissen, ob er durchschnittliches Einperiodenergebnis, erwarteten Endbetrag oder langfristige Wachstumsrate optimiert.`)
],C('Gleicher arithmetischer Durchschnitt, anderer Endwert','Start 100, zwei Perioden, keine Zahlungen.',['Reihe','Arithmetisch','Endvermögen','Geometrisch pro Periode'],[['10 %, 10 %','10 %','121','10 %'],['30 %, −10 %','10 %','117','8,17 %'],['50 %, −30 %','10 %','105','2,47 %']],'Alle Reihen mitteln sich arithmetisch auf 10 %. Der zunehmende Wechsel zwischen hohen Gewinnen und Verlusten senkt aber den verketteten Endwert. Die geometrischen Raten sind jeweils Quadratwurzel aus Endwert/100 minus eins. Dadurch wird der Unterschied der Kennzahlen unmittelbar sichtbar.'),[['portfolio-02','Nutzenfunktionen bestimmen, welche Ergebnisgröße optimiert wird.'],['kelly','Kelly optimiert erwartetes logarithmisches Wachstum.']]),
D([
S('Zeitgewichtung isoliert die Anlageleistung zwischen externen Zahlungen',`TWR trennt die Historie an Ein- und Auszahlungen. Für jede Teilperiode wird die Rendite aus dem Wert nach der letzten externen Zahlung und vor der nächsten externen Zahlung berechnet. Die Teilfaktoren werden verkettet. So verändert ein vom Kunden ausgelöster Zufluss nicht künstlich die gemessene Strategieperformance.

Bei unterperiodigen Zahlungen werden verlässliche Zwischenbewertungen benötigt. Ohne sie sind zeitgewichtete Approximationen wie Modified Dietz möglich, aber deren Genauigkeit hängt von Zahlungsgröße und Marktverlauf ab. Interne Umschichtungen sind keine externen Cashflows; auch ein im Portfolio verbleibender Kupon gehört zum Anlageergebnis.`,T`r_j=\frac{V_j^-}{V_{j-1}^+}-1,\qquad R_{TWR}=\prod_j(1+r_j)-1`),
S('Geldgewichtung als Rendite der tatsächlich investierten Beträge',`Die MWR löst die Barwertgleichung sämtlicher Anlegerzahlungen einschließlich Schlusswert. Große investierte Beträge erhalten damit wirtschaftlich mehr Gewicht. Der IRR ist eine Rate pro definierter Zeitperiode; bei unregelmäßigen Daten werden Zeitabstände als Jahresbruchteile eingesetzt. Annualisierte MWR darf nicht direkt mit einer kumulierten zweijährigen TWR verglichen werden.

Wenn ein Manager die Kapitalabrufe selbst bestimmt, ist deren Timing Teil seiner Leistung. Dann kann eine geldgewichtete Kennzahl besonders relevant sein. Bei mehrfachen Vorzeichenwechseln kann IRR mehrere oder keine wirtschaftlich sinnvollen Lösungen besitzen. Zusätzlich sollte deshalb der absolute Wertzuwachs und bei privaten Anlagen ein Kapitalmultiplikator betrachtet werden.`,T`0=\sum_j\frac{CF_j}{(1+r)^{t_j}},\qquad R_{TWR,ann}=(1+R_{TWR})^{1/T}-1`)
],C('Gleiche Strategie, anderer Einsatzzeitpunkt','Die Strategie erzielt im ersten Jahr +10 %, im zweiten −10 %.',['Anleger','Zusätzlicher Einsatz nach Jahr 1','Endwert','TWR kumuliert','MWR jährlich'],[['A: anfangs 100','0','99','−1 %','−0,50 %'],['B: anfangs 100','100','189','−1 %','−3,71 %']],'Die Strategiehistorie ist identisch. B investiert vor dem Verlustjahr mehr Geld und erlebt deshalb eine schlechtere persönliche Rendite. Für einen fairen Vergleich ist die TWR ebenfalls zu annualisieren: √0,99−1≈−0,50 %. Der Unterschied zur MWR von B erklärt sich aus Zahlungszeitpunkten, nicht aus einer anderen Marktrendite.'),[['ethics-10','Faire Performancedarstellung verlangt passende Renditemethoden.'],['path-private-06','Private Fonds brauchen Zeit- und Kapitalmaße.']]),
D([
S('Varianz als mittlere quadrierte Abweichung',`Der Mittelwert beschreibt das Zentrum, aber nicht die Streuung. Ein einfaches Addieren positiver und negativer Abweichungen ergibt immer null. Quadrieren verhindert diese Aufhebung und gewichtet große Abweichungen stärker. Die Varianz hat quadrierte Einheiten; erst die Standardabweichung kehrt in die Einheit der Rendite zurück.

Bei einer vollständigen diskreten Wahrscheinlichkeitsverteilung wird mit den Wahrscheinlichkeiten gewichtet. Bei einer Stichprobe wird der unbekannte Mittelwert aus denselben Daten geschätzt. Dadurch geht ein Freiheitsgrad verloren; die Division durch n−1 korrigiert unter den üblichen Annahmen die Verzerrung der Varianzschätzung. Das macht die Standardabweichung selbst nicht automatisch exakt unverzerrt.`,T`\sigma^2=\sum_ip_i(x_i-\mu)^2=E[X^2]-\mu^2,\qquad s^2=\frac{\sum_i(x_i-\bar x)^2}{n-1}`),
S('Gleiche Streuung kann unterschiedliche Verlustprofile verdecken',`Varianz behandelt positive und negative Abweichungen symmetrisch. Zwei Anlagen können gleiche Volatilität und unterschiedliche Schiefe besitzen. Ausreißer, seltene Verluste und nichtlineare Optionsprofile verlangen deshalb weitere Kennzahlen. Quantile, Downside-Maße und Szenarien ergänzen die zweite Momentenbeschreibung.

Wird jede Rendite mit einer Konstante a multipliziert, multipliziert sich die Standardabweichung mit |a| und die Varianz mit a². Eine konstante sichere Rendite verschiebt den Mittelwert, ändert aber nicht die Varianz. Diese Regeln sind die Grundlage von Portfoliorisikorechnungen und erklären, warum Prozent- und Dezimalskalen nicht vermischt werden dürfen.`,T`\operatorname{Var}(aX+b)=a^2\operatorname{Var}(X),\qquad\sigma_{aX+b}=|a|\sigma_X`)
],C('Stichprobe und bekannte Verteilung auseinanderhalten','Die Werte −10 %, 0 %, +10 % werden einmal als vollständige gleich wahrscheinliche Verteilung und einmal als Stichprobe interpretiert.',['Interpretation','Divisor','Varianz','Standardabweichung'],[['Bekannte Verteilung','3','0,006667','8,165 %'],['Stichprobenschätzung','2','0,010000','10 %']],'Die Abweichungsquadrate summieren sich in beiden Fällen zu 0,02 in Dezimalskala. Der Unterschied entsteht allein aus der statistischen Fragestellung. Ohne Angabe von Stichprobe oder Grundgesamtheit ist die Frage nach der einen richtigen Standardabweichung unvollständig.'),[['portfolio-01','Portfoliovarianz ergänzt gemeinsame Abweichungen durch Kovarianz.'],['portfolio-12','VaR und ES betrachten die Verlustseite gezielter.']]),
D([
S('Bedingte Wahrscheinlichkeit als Neugewichtung einer Teilmenge',`P(A|B) fragt nach dem Anteil von A unter den Fällen, in denen B bereits eingetreten ist. Der Nenner ist deshalb P(B), nicht die gesamte ursprüngliche Grundgesamtheit. Die Identität P(A∩B)=P(A|B)P(B)=P(B|A)P(A) führt direkt zum Satz von Bayes.

Die Wahrscheinlichkeit von B entsteht aus allen Wegen zu B. Bei einem Warnsignal sind das wahre Signale bei Ausfällen und falsche Signale bei Nichtausfällen. Selbst ein empfindliches System kann bei seltenen Ausfällen überwiegend falsche Warnungen liefern. Das ist ein Basisrateneffekt und kein Widerspruch zu seiner hohen Trefferquote unter den tatsächlichen Ausfällen.`,T`P(A|B)=\frac{P(B|A)P(A)}{P(B|A)P(A)+P(B|A^c)P(A^c)}`),
S('Erwartungswert und Abhängigkeit',`Erwartungswerte werden linear addiert, auch wenn Zufallsgrößen abhängig sind. Für Produkte gilt dagegen E[XY]=E[X]E[Y] nur bei geeigneten Unabhängigkeits- beziehungsweise Unkorreliertheitsbedingungen. Im Kreditrisiko können Ausfall und Verlustquote gemeinsam steigen; die Multiplikation unbedingter Durchschnittswerte kann dann zu niedrige Verluste liefern.

Ein Entscheidungsproblem benötigt neben Wahrscheinlichkeiten die Folgen der Zustände. Eine seltene Warnung kann trotz geringer positiver Vorhersagewahrscheinlichkeit eine Prüfung rechtfertigen, wenn der Schaden eines übersehenen Ausfalls groß und die Prüfung günstig ist. Statistische Klassifikation und wirtschaftliche Entscheidung sind daher zwei Schritte.`,T`E[X+Y]=E[X]+E[Y],\qquad E[XY]=E[X]E[Y]+\operatorname{Cov}(X,Y)`)
],C('Nur die Basisrate verändern','Sensitivität stets 80 %, Falsch-positiv-Rate stets 10 %, jeweils 1.000 Unternehmen.',['Ausfallrate','Wahre Warnungen','Falsche Warnungen','Ausfall unter Gewarnten'],[['2 %','16','98','14,04 %'],['20 %','160','80','66,67 %']],'Das technische Testverhalten bleibt gleich. In der riskanteren Grundgesamtheit steigt die Aussagekraft einer Warnung stark. Die posterioren Werte folgen aus wahr/(wahr+falsch). Ein Modell kann deshalb beim Transfer in eine andere Kundengruppe neue Kalibrierung benötigen, obwohl seine Sensitivität unverändert ist.'),[['bonds-10','Erwartete Kreditverluste verknüpfen Wahrscheinlichkeit und Schadenshöhe.'],['quant-14','Klassifikation muss an wirtschaftlichen Kosten beurteilt werden.']]),
D([
S('Die Wurzelregel aus der Varianz des Mittelwerts',`Der Stichprobenmittelwert ist die Summe aller Beobachtungen geteilt durch n. Bei unabhängigen gleich verteilten Beobachtungen addieren sich deren Varianzen. Wegen des Faktors 1/n vor der Summe wird durch n² geteilt, sodass insgesamt σ²/n verbleibt. Die Quadratwurzel liefert den Standardfehler σ/√n.

Diese Herleitung zeigt die Bedingung der Unabhängigkeit. Bei positiver zeitlicher Korrelation kommen positive Kovarianzterme hinzu; mehr beobachtete Monate sind dann nicht gleichbedeutend mit ebenso vielen unabhängigen Informationen. Eine ungeprüfte Wurzelregel kann die Unsicherheit stark unterschätzen.`,T`\operatorname{Var}(\bar X)=\frac1{n^2}\left[\sum_i\operatorname{Var}(X_i)+2\sum_{i<j}\operatorname{Cov}(X_i,X_j)\right]\xrightarrow{\mathrm{iid}}\frac{\sigma^2}{n}`),
S('Zentraler Grenzwertsatz und seine praktische Reichweite',`Unter geeigneten Bedingungen nähert sich die Verteilung standardisierter Mittelwerte einer Normalverteilung. Die ursprünglichen Einzelbeobachtungen müssen dafür nicht normalverteilt sein. Der Grenzwertsatz betrifft eine Statistik über viele Beobachtungen, nicht die Form eines einzelnen Tagesverlusts.

Sehr schwere Verteilungsschwänze, Strukturbrüche oder starke Abhängigkeit können die Näherung verlangsamen oder Voraussetzungen verletzen. Eine große Stichprobe reduziert außerdem keine systematische Auswahlverzerrung. Tausende falsch ausgewählte Beobachtungen können eine sehr präzise Schätzung der falschen Zielgröße liefern.`,T`\frac{\bar X-\mu}{\sigma/\sqrt n}\overset{d}{\longrightarrow}N(0,1)`)
],C('Mehr Daten senken Schätzfehler, nicht Anlagerisiko','Standardabweichung einer einzelnen Jahresrendite 20 %. Unabhängige Beobachtungen werden für das Beispiel angenommen.',['n','SE des Mittelwerts','Streuung eines Einzelwerts'],[['25','4 %','20 %'],['100','2 %','20 %'],['400','1 %','20 %']],'Viermal mehr Beobachtungen halbieren den Standardfehler. Die Anlage selbst schwankt weiterhin mit 20 %. Diese Unterscheidung ist wesentlich: Schätzpräzision und wirtschaftliches Risiko sind verschiedene Größen. Für tatsächlich abhängige Zeitreihen ist die effektive Information geringer als n vermuten lässt.'),[['quant-08','Konfidenzintervalle skalieren den Standardfehler mit einem kritischen Wert.'],['quant-12','Monte-Carlo-Fehler folgt derselben Wurzelregel.']]),
D([
S('Teststatistik und Konfidenzintervall aus derselben Standardisierung',`Ein Test vergleicht die beobachtete Differenz zum Nullhypothesenwert mit ihrer Schätzunsicherheit. Unter normalverteilten unabhängigen Daten und unbekannter Varianz folgt die standardisierte Mittelwertdifferenz einer t-Verteilung mit n−1 Freiheitsgraden. Der kritische Wert bestimmt, welche Abweichung unter der Nullhypothese als ungewöhnlich gilt.

Ein Konfidenzintervall enthält genau die Nullwerte, die beim entsprechenden zweiseitigen Test nicht verworfen würden. Diese Dualität entsteht durch Umstellen derselben Ungleichung. Frequentistisch bezieht sich das Konfidenzniveau auf die langfristige Abdeckungsrate des Verfahrens; es ist nicht automatisch eine posterior berechnete Wahrscheinlichkeit für den fixen Parameter im bereits beobachteten Intervall.`,T`\left|\frac{\bar x-\mu_0}{s/\sqrt n}\right|\leq t_{1-\alpha/2,n-1}\quad\Longleftrightarrow\quad\mu_0\in\left[\bar x-t^*\frac s{\sqrt n},\bar x+t^*\frac s{\sqrt n}\right]`),
S('Signifikanz, Teststärke und wirtschaftliche Relevanz',`Ein p-Wert beschreibt unter der Nullhypothese die Wahrscheinlichkeit eines mindestens so extremen Teststatistikwerts. Er ist weder die Wahrscheinlichkeit, dass die Nullhypothese wahr ist, noch die Wahrscheinlichkeit eines Verlusts im Portfolio. Ein kleiner p-Wert kann bei sehr großen Stichproben auch für einen ökonomisch unbedeutenden Effekt entstehen.

Teststärke ist die Wahrscheinlichkeit, einen tatsächlich vorhandenen definierten Effekt zu erkennen. Sie steigt typischerweise mit Stichprobengröße und Effektgröße und sinkt bei größerer Streuung. Viele gleichzeitig getestete Hypothesen erhöhen die Gefahr zufälliger Treffer. Eine im Nachhinein ausgewählte erfolgreiche Strategie benötigt daher Korrekturen und unabhängige Validierung.`,T`\alpha=P(\mathrm{reject}\ H_0\mid H_0),\qquad1-\beta=P(\mathrm{reject}\ H_0\mid H_1)`)
],C('Gleicher Effekt, unterschiedliche Präzision','Geschätzter Mehrertrag 2 Prozentpunkte, Standardabweichung 10 Prozentpunkte. Für den Vergleich wird 1,96 als grobe Normalnäherung benutzt.',['n','SE','t gegen null','Ungefähres 95-%-Intervall'],[['25','2','1','[−1,92; 5,92]'],['400','0,5','4','[1,02; 2,98]']],'Die beobachtete Effektgröße ändert sich nicht. Nur ihre Präzision steigt. Die zweite Stichprobe liefert stärkere statistische Evidenz, aber keinen größeren wirtschaftlichen Ertrag. Transaktionskosten von beispielsweise 3 Prozentpunkten würden beide Varianten wirtschaftlich unattraktiv machen, selbst wenn die zweite statistisch signifikant ist.'),[['portfolio-05','Alpha muss zusammen mit seinem Standardfehler interpretiert werden.'],['advanced-10','Managerprüfung berücksichtigt Auswahl und Mehrfachtests.']]),
D([
S('OLS aus der Minimierung der Fehlerquadrate herleiten',`Die einfache Regression sucht Achsenabschnitt a und Steigung b, sodass die Summe quadrierter Residuen minimal wird. Ableiten nach a setzt die Summe der Residuen auf null. Daraus folgt a=ȳ−b x̄. Einsetzen in die Ableitung nach b liefert die Kreuzproduktsumme geteilt durch die Quadratsumme der x-Abweichungen.

Die Steigung misst die Änderung des bedingten linearen Prognosewerts je Einheit x. Sie ist keine automatische kausale Wirkung. Eine gemeinsame Ursache kann x und y zugleich bewegen. Außerdem kann der Interzept bei x=0 außerhalb des beobachteten Datenbereichs liegen und damit wenig direkte wirtschaftliche Bedeutung besitzen.`,T`\min_{a,b}\sum_i(y_i-a-bx_i)^2,\quad\hat a=\bar y-\hat b\bar x,\quad\hat b=\frac{\sum_i(x_i-\bar x)(y_i-\bar y)}{\sum_i(x_i-\bar x)^2}`),
S('Mehrere Regressoren und der Unterschied zwischen Gesamt- und Teileffekt',`In einer multiplen Regression beschreibt ein Koeffizient den linearen Zusammenhang bei konstant gehaltenen anderen aufgenommenen Regressoren. Das kann sich stark von einer einfachen Regression unterscheiden, wenn die Erklärungsgrößen korreliert sind. Ausgelassene Variablen verzerren Koeffizienten, wenn sie das Ergebnis beeinflussen und mit vorhandenen Regressoren zusammenhängen.

Die Matrixlösung entsteht aus den Normalgleichungen. Die Inverse existiert nur bei vollem Spaltenrang. Starke, aber nicht perfekte Kollinearität macht Schätzungen instabil, ohne die Anpassung zwingend schlecht aussehen zu lassen. Für Prognosen ist zusätzlich die Unsicherheit eines neuen Einzelwerts größer als die Unsicherheit des geschätzten bedingten Mittelwerts.`,T`X^{\mathsf T}X\hat\beta=X^{\mathsf T}y,\qquad\hat\beta=(X^{\mathsf T}X)^{-1}X^{\mathsf T}y`)
],C('Skalierung verändert Koeffizienten, nicht Prognosen','Ein Modell lautet y=2+3x. Nun wird x statt in Einheiten in Hundertsteln gemessen: z=100x.',['Darstellung','Koeffizient','Prognose für x=4'],[['x in ursprünglichen Einheiten','3','2+3×4=14'],['z=100x','0,03','2+0,03×400=14']],'Ein kleinerer Koeffizient bedeutet hier keinen schwächeren Zusammenhang. Nur die Einheit hat sich verändert. Die Prognose bleibt identisch. Deshalb sind unstandardisierte Regressionskoeffizienten verschiedener Variablen nicht ohne Einheitenvergleich als Rangliste ihrer Bedeutung geeignet.'),[['quant-10','Diagnostik prüft die Voraussetzungen der Inferenz.'],['portfolio-04','Beta ist eine Regressionssensitivität, keine garantierte Einzelbewegung.']]),
D([
S('Welche Annahme betrifft welche Aussage?',`Linearität und geeignete Exogenität bestimmen, ob der Regressionskoeffizient die beabsichtigte Beziehung misst. Homoskedastizität und fehlende Fehlerautokorrelation bestimmen dagegen die klassische Kovarianzformel. Werden nur diese Varianzannahmen verletzt, kann OLS unter Exogenität weiterhin konsistent sein, während klassische Standardfehler falsch werden. Eine robuste Standardfehlerkorrektur behebt keine ausgelassene Ursache oder umgekehrte Kausalität.

Die allgemeine Sandwichformel zeigt, wo die Fehlerkovarianz Ω eingeht. Unter Ω=σ²I kürzt sie sich zur bekannten klassischen Formel. Heteroskedastizitätsrobuste und HAC-Verfahren schätzen verschiedene Strukturen dieser Matrix. Die Wahl folgt dem Datenprozess, nicht dem Wunsch nach einem kleineren p-Wert.`,T`\operatorname{Var}(\hat\beta|X)=(X^{\mathsf T}X)^{-1}X^{\mathsf T}\Omega X(X^{\mathsf T}X)^{-1}\xrightarrow{\Omega=\sigma^2I}\sigma^2(X^{\mathsf T}X)^{-1}`),
S('Residuen als Diagnose und Grenzen guter Anpassung',`Residuenplots können Trichterformen, Krümmung, Ausreißer oder zeitliche Muster zeigen. Ein hohes R² bedeutet lediglich, dass ein großer Teil der Stichprobenvariation durch die angepasste Gleichung erklärt wird. Es beweist weder richtige Kausalität noch gute Prognosen außerhalb der Stichprobe. Zusätzliche Regressoren senken die Trainingsfehlerquadratsumme mechanisch; Modellvergleich braucht deshalb Komplexitäts- und Validierungsaspekte.

Einflussreiche Beobachtungen können Steigungen stark verschieben. Sie dürfen nicht allein wegen eines unerwünschten Ergebnisses entfernt werden. Zunächst ist zu prüfen, ob Messfehler, eine andere Population oder ein wirtschaftlich relevanter Extremzustand vorliegt. Sensitivitätsrechnungen mit und ohne die Beobachtung machen den Einfluss transparent.`)
],C('Gleicher Koeffizient, andere Standardfehler','Geschätzte Steigung 0,8. Die Daten zeigen positive zeitliche Fehlerabhängigkeit.',['Verfahren','SE','t gegen null'],[['Naiv unabhängig','0,2','4,0'],['Angemessen robuste Schätzung','0,5','1,6']],'Die geschätzte wirtschaftliche Empfindlichkeit bleibt 0,8. Geändert hat sich die Unsicherheit der Aussage. Der klassische starke Signifikanzbefund kann verschwinden, wenn die Information weniger unabhängig ist als angenommen. Ein robuster t-Wert macht die Steigung aber nicht automatisch kausal interpretierbar.'),[['quant-07','Abhängigkeit reduziert effektive Stichprobeninformation.'],['advanced-10','Track Records brauchen geeignete Standardfehler.']]),
D([
S('Stationarität und bedingte Prognose auseinanderhalten',`Im AR(1)-Modell hängt der aktuelle Wert von seinem Vorgänger und einer neuen Innovation ab. Ein konstanter langfristiger Mittelwert μ muss dieselbe Erwartungsgleichung erfüllen: μ=c+φμ. Umstellen liefert c/(1−φ). Ein stationärer Prozess erfordert zusätzlich |φ|<1 sowie geeignete Innovationsannahmen. Nur eine algebraisch endliche Zahl bei φ>1 macht den Prozess nicht stationär.

Die h-Schritt-Prognose nähert sich bei |φ|<1 dem langfristigen Mittel. Wie schnell dies geschieht, bestimmt φ. Bei positivem φ bleiben Abweichungen zunächst in derselben Richtung; bei negativem φ wechseln sie das Vorzeichen. Ein φ nahe eins bedeutet lange Persistenz und macht kurze Stichproben schwer von einer Einheitswurzel unterscheidbar.`,T`\mu=\frac c{1-\phi},\quad E_t[x_{t+h}]=\mu+\phi^h(x_t-\mu),\quad\operatorname{Var}(x_t)=\frac{\sigma_\varepsilon^2}{1-\phi^2}`),
S('Schocks, Prognoseunsicherheit und Scheinkorrelation',`Ein einmaliger Schock wirkt nach h Perioden noch mit φ^h. Gleichzeitig sammeln sich neue unvorhersehbare Innovationen an, sodass die Prognosefehlervarianz mit dem Horizont wächst. Mean Reversion bedeutet daher nicht, dass ein einzelner Pfad sicher zum Mittelwert zurückkehrt; sie beschreibt den bedingten Erwartungswert.

Nichtstationäre Reihen können hohe Korrelation und scheinbar signifikante Regressionen erzeugen, obwohl kein stabiler Zusammenhang besteht. Differenzieren kann Trends entfernen, aber auch langfristige Information verlieren. Kointegration betrifft den besonderen Fall, in dem eine Kombination nichtstationärer Reihen stationär ist. Die Modellwahl folgt diesen Eigenschaften und dem wirtschaftlichen Mechanismus.`,T`\operatorname{Var}_t(x_{t+h})=\sigma_\varepsilon^2\sum_{j=0}^{h-1}\phi^{2j}`)
],C('Gleicher Schock, andere Persistenz','Ein Anfangsschock beträgt 10 Einheiten. Betrachtet wird nur sein erwarteter fortwirkender Beitrag.',['φ','Nach 1 Periode','Nach 5 Perioden'],[['0,2','2','0,0032'],['0,8','8','3,2768'],['1','10','10']],'Bei φ=0,2 verschwindet der Effekt schnell aus der bedingten Erwartung; bei 0,8 bleibt er länger sichtbar. φ=1 liegt außerhalb des stationären AR(1)-Falls: Ein Schock verschwindet nicht. Zusätzliche Zufallsschocks würden in allen Fällen die realisierten Pfade vom dargestellten Erwartungsbeitrag abweichen lassen.'),[['quant-10','Zeitabhängigkeit verändert Regressionsinferenz.'],['economics-05','Konjunkturprognosen brauchen Annahmen über Persistenz und Trend.']]),
D([
S('Simulation trennt ein Modell von der numerischen Auswertung',`Monte Carlo erzeugt Zustände oder Pfade aus ausdrücklich festgelegten Wahrscheinlichkeitsannahmen. Eine Auszahlung wird für jeden Pfad berechnet und anschließend zusammengefasst. Die Methode kann komplexe, nichtlineare oder pfadabhängige Funktionen auswerten, deren Erwartung analytisch schwer zugänglich ist. Sie liefert jedoch genau die Konsequenzen des gewählten Modells, keine automatische realistische Weltbeschreibung.

Für einen unabhängigen Pfadmittelwert gilt die Standardfehlerregel s/√M. Viermal mehr Pfade halbieren den numerischen Standardfehler. Das Anlegerergebnis wird dadurch nicht weniger riskant: Die Streuung einzelner Pfade und ein möglicher Modellfehler bleiben bestehen. Konfidenzintervalle für Quantile oder seltene Verlustwahrscheinlichkeiten verlangen andere beziehungsweise speziell angepasste Schätzungen.`,T`\hat V_M=\frac1M\sum_{j=1}^Mg(X_j),\quad\operatorname{SE}(\hat V_M)\approx\frac{s_g}{\sqrt M}`),
S('Bootstrap und Backtest beantworten weitere Fragen',`Bootstrap ersetzt eine unbekannte Stichprobenverteilung durch wiederholtes Ziehen aus beobachteten Daten. Bei unabhängigen Daten werden einzelne Beobachtungen gezogen; bei Zeitabhängigkeit können Blöcke nötig sein. Ein Bootstrap kann keine bislang unbeobachtete Risikostruktur zuverlässig erfinden. Besonders seltene Katastrophen bleiben bei einer ruhigen Ausgangsstichprobe unterrepräsentiert.

Ein Backtest spielt Entscheidungen mit damals verfügbaren Informationen durch. Datenlecks entstehen etwa durch später korrigierte Fundamentaldaten, heutige Indexmitglieder oder auf der Testperiode optimierte Parameter. Ein fester Zufallsseed macht Simulationen reproduzierbar, aber nicht wahr. Robustheit erfordert mehrere Daten- und Modellannahmen sowie explizite Stressfälle.`)
],C('Numerische Genauigkeit und Modellunsicherheit trennen','Simulierte Endwerte haben Standardabweichung 30. Die angenommene durchschnittliche Rendite selbst ist unsicher.',['Pfade M','SE des Endwertmittels','Streuung einzelner Endwerte'],[['900','1,00','30'],['3.600','0,50','30'],['14.400','0,25','30']],'Die kleinere Standardfehlerzahl zeigt präzisere numerische Auswertung desselben Modells. Ist dessen erwartete Rendite systematisch zu hoch, werden mit mehr Pfaden nur die falschen Erwartungen genauer ausgewertet. Deshalb sollten Parameteränderungen wie niedrigere Rendite oder höhere Krisenkorrelation separat durchgespielt werden.'),[['quant-07','Die Wurzelregel erklärt Konvergenz.'],['portfolio-13','Stressszenarien ergänzen nicht beobachtete Zustände.']]),
D([
S('Optimierung aus Zielfunktion und Nebenbedingungen herleiten',`Im Mean-Variance-Modell wird erwartete Rendite um A/2 mal Varianz vermindert. Ohne zusätzliche Beschränkungen ergibt die Ableitung μ−AΣw. Eine Budgetbedingung wird mit einem Lagrange-Multiplikator berücksichtigt. Das Optimum hängt deshalb von Renditeerwartungen, der gesamten Kovarianzmatrix und dem zulässigen Bereich gemeinsam ab.

Bei einem einzigen riskanten Portfolio und einer sicheren Anlage wird das Problem eindimensional. Erwartete Überschussrendite wächst linear mit dem Anteil y, Varianz quadratisch. Die erste Ableitung setzt Grenznutzen und Grenzrisikokosten gleich. Ein Leverageverbot oder eine Positionsgrenze kann das Optimum an den Rand verschieben, wo die unbeschränkte Ableitung nicht null sein muss.`,T`U(y)=r_f+y(\mu-r_f)-\frac A2y^2\sigma^2,\quad U'(y)=\mu-r_f-Ay\sigma^2,\quad y^*=\frac{\mu-r_f}{A\sigma^2}`),
S('Warum Schätzfehler extreme Gewichte erzeugen können',`Ein Optimierer behandelt geschätzte Eingaben zunächst wie exakte Werte. Kleine scheinbare Renditevorteile können bei hoch korrelierten Anlagen große gegenläufige Positionen auslösen, weil das Modell eine fast risikolose Differenz zu erkennen glaubt. Das Problem verschärft sich bei schlecht konditionierter Kovarianzmatrix.

Gewichtsgrenzen, Shrinkage, Kosten und robuste Erwartungsbandbreiten können die Entscheidung stabilisieren. Sie sind keine willkürlichen Störungen einer idealen Lösung, sondern bilden reale Unsicherheit und Umsetzbarkeit ab. Nachträgliches Abschneiden negativer Gewichte und Normieren ist im Allgemeinen nicht dasselbe wie die korrekte gemeinsame Optimierung mit Leerverkaufsverbot.`)
],C('Gleiche Risikoprämie, anderes Risiko','Risikoprämie 5 %, Risikoaversion A=4; unbeschränktes Einanlagenmodell.',['Volatilität','Varianz','Optimaler Anteil y'],[['10 %','0,01','125 %'],['20 %','0,04','31,25 %'],['30 %','0,09','13,89 %']],'Doppelte Volatilität vervierfacht die Varianz und viertelt den optimalen Anteil. 125 % würde Fremdfinanzierung voraussetzen; bei einem Verbot wäre die Lösung höchstens 100 %. Diese Gegenüberstellung zeigt, warum Varianz und Standardabweichung nicht austauschbar in die Formel eingesetzt werden dürfen.'),[['portfolio-03','Die effiziente Grenze beschreibt zulässige optimale Kombinationen.'],['advanced-02','Reale Restriktionen verändern die Lösung.']]),
D([
S('Die Verlustfunktion bestimmt, was ein Modell lernt',`Ein Lernverfahren minimiert eine definierte Verlustfunktion. Quadratischer Fehler bestraft große Prognoseabweichungen überproportional; absoluter Fehler reagiert robuster auf Ausreißer. Bei Klassifikation hängen optimale Schwellen zusätzlich von den Kosten falscher positiver und falscher negativer Entscheidungen ab. Ein statistisch guter Klassifikator ist nicht automatisch wirtschaftlich optimal.

Training passt Parameter an, Validierung wählt Modell und Komplexität, ein unangetasteter Test schätzt die spätere Leistung. Wird der Test immer wieder zur Auswahl benutzt, wird er faktisch Teil des Trainingsprozesses. Bei Finanzdaten muss die zeitliche Reihenfolge erhalten bleiben; zufälliges Mischen kann Zukunftsinformation in die Vergangenheit tragen.`,T`\hat f=\arg\min_{f\in\mathcal F}\frac1n\sum_iL(y_i,f(x_i))+\lambda\Omega(f)`),
S('Überanpassung, Regularisierung und wirtschaftliche Umsetzung',`Ein sehr flexibles Modell kann Zufallsmuster der Trainingsdaten nachbilden. Dann sinkt der Trainingsfehler, während unbekannte Daten schlechter prognostiziert werden. Regularisierung begrenzt Komplexität, etwa über die Größe der Koeffizienten. Der Parameter λ muss innerhalb des erlaubten Auswahlprozesses bestimmt werden.

Für eine Handelsstrategie kommen Signalverfügbarkeit, Verzögerung, Turnover, Marktimpact und Kapazität hinzu. Ein kleiner Prognosefehler kann wirtschaftlich wertlos sein, wenn die richtigen Signale nur minimale Preisbewegungen betreffen. Umgekehrt kann ein Modell mit geringer Trefferquote nützlich sein, wenn Gewinne systematisch größer als Verluste sind. Interpretierbarkeit und Datenherkunft helfen, instabile Zusammenhänge zu erkennen.`)
],C('Trefferquote und erwarteter Nutzen vergleichen','Je 100 unabhängige Signale, gleiche Einsatzbasis, keine Kosten in der ersten Rechnung.',['Modell','Trefferquote','Gewinn je Treffer','Verlust je Fehler','Erwarteter Ertrag je Signal'],[['A','70 %','1','3','−0,20'],['B','40 %','3','1','+0,60']],'A erzielt 0,7×1−0,3×3=−0,20, B dagegen 0,4×3−0,6×1=0,60. Die höhere Trefferquote reicht nicht aus. Handelskosten von 0,70 je Signal würden auch B unattraktiv machen. Wirtschaftlicher Erfolg hängt von der gesamten Ergebnisverteilung und Umsetzung ab.'),[['quant-06','Bedingte Wahrscheinlichkeiten und Entscheidungskosten gehören zusammen.'],['practice-02','Datenbereinigung und zeitliche Verfügbarkeit verhindern Lecks.']])
];
