const {D,S,C,T}=require('./schema.cjs');
module.exports=[
D([
S('Finanzierung als Zusammenhang von Sektorbilanz und Einzelvertrag',`Ein Finanzierungsüberschuss entsteht, wenn ein Sektor mehr spart, als er real investiert. Er schlägt sich im Erwerb finanzieller Forderungen oder im Abbau von Schulden nieder. Über alle Sektoren einschließlich Ausland saldieren sich die Finanzierungssalden unter konsistenter Abgrenzung zu null. Die Forderung eines Anlegers ist die Verpflichtung einer anderen Partei; zusätzliche Finanzansprüche sind daher nicht automatisch zusätzliches gesamtwirtschaftliches Nettovermögen.

Reale Investition und Finanzanlage müssen getrennt werden. Der Bau einer Maschine schafft einen produktiven Vermögenswert. Der Kauf einer vorhandenen Aktie überträgt einen Anspruch auf ein Unternehmen. Er kann Finanzierungskosten beeinflussen, ist aber nicht selbst der Bau zusätzlicher Produktionskapazität. Hohe Börsenumsätze und hohe reale Investitionen sind deshalb unterschiedliche Größen.`,T`B_s=S_s-I_s=\Delta FA_s-\Delta FL_s,\qquad\sum_sB_s=0`),
S('Warum Intermediäre existieren und welche Risiken sie übernehmen',`Ein einzelner Sparer kann einen Kreditnehmer oft nur teuer prüfen und möchte sein Geld früher zurück als ein Unternehmen die Maschine refinanzieren kann. Eine Bank bündelt Einlagen, prüft Schuldner und hält Liquidität vor. Diversifikation reduziert einzelne Kreditausfälle, beseitigt aber keinen gemeinsamen Konjunkturschock oder gleichzeitigen Einlagenabzug. Fristen- und Risikotransformation sind produktive Leistungen mit eigener Krisenanfälligkeit.

Vor Vertragsabschluss droht adverse Selektion, wenn besonders riskante Schuldner hohe Zinsen leichter akzeptieren. Danach kann Moral Hazard entstehen, wenn ein Schuldner das geliehene Geld riskanter einsetzt. Sicherheiten, Covenants, Eigenkapitalbeteiligung und Überwachung reagieren auf unterschiedliche Teile dieses Problems. Ein hoher Zinssatz allein löst es nicht; er kann die Zusammensetzung der Antragsteller verschlechtern.`)
],C('Gleiche Maschine, andere Finanzierung','Eine Maschine kostet 100 und erzeugt im Erfolgsfall einen Endwert von 120, im schlechten Zustand 70. Finanzierung vollständig mit Eigenkapital oder mit 60 Schulden und 40 Eigenkapital; Schuldversprechen 63.',['Struktur','Eigenkapital heute','Eigenkapital guter Zustand','Eigenkapital schlechter Zustand'],[['Ohne Schulden','100','120','70'],['Mit Schulden','40','57','7']],'Ohne Schulden schwankt die Eigentümerrendite zwischen +20 % und −30 %. Mit dem festen Gläubigeranspruch beträgt sie +42,5 % beziehungsweise −82,5 %. Das operative Projekt ist identisch; nur die Verteilung der Ansprüche verändert sich. Finanzierung erzeugt kein zusätzliches sicheres Projektergebnis, sondern verändert die Risikoaufteilung.\n\nFür den Kreditgeber sind 63 in beiden dargestellten Zuständen noch gedeckt. Erst bei Projektwerten unter 63 entstehen ihm Verluste. Weitere Zustände und ihre Wahrscheinlichkeiten müssen für eine vollständige Erwartungswertrechnung ergänzt werden.'),[['corporate-07','Kapitalstruktur verstärkt Eigenkapitalrenditen.'],['bonds-10','Kreditverluste beginnen unterhalb des Gläubigeranspruchs.']]),
D([
S('Anlageklasse, Vehikel und Strategie bilden drei Ebenen',`Eine Anlageklasse beschreibt wirtschaftliche Ansprüche und Risikotreiber. Ein Vehikel bestimmt Zugang, Kosten, Liquiditätsregeln und Kontrollrechte. Eine Strategie legt fest, welche Positionen wie gewichtet werden. Die Begriffe lassen sich kombinieren: Ein ETF kann Aktien, Anleihen oder eine komplexe Strategie abbilden. Handelbarkeit des Vehikels und Liquidität seiner Anlagen sind ebenfalls getrennte Fragen.

Der Investmentprozess ist eine Kette überprüfbarer Entscheidungen. Verpflichtungen bestimmen zulässige Risiken; Kapitalmarkterwartungen liefern unsichere Ertragsannahmen; Allokation verteilt das Budget; Umsetzung entscheidet über Kosten; Monitoring prüft Abweichungen. Wird ein Produkt zuerst gewählt und das Ziel anschließend passend formuliert, wird diese Logik umgekehrt.`),
S('Nettoergebnis und Zielerreichung sind verschiedene Prüfungen',`Bruttorendite und persönliche Nettorendite unterscheiden sich durch laufende Gebühren, Handelskosten, Steuern, Zahlungszeitpunkte und Wechselkurse. In einer Einperiodenrechnung werden am Ende anfallende Kosten vom Endvermögen abgezogen. Mehrperiodig verändert eine früher gezahlte Gebühr zusätzlich die Wiederanlagebasis.

Die Zielgröße kann ein Mindestbetrag zu einem Termin, realer Vermögenserhalt oder ein Benchmarkziel sein. Eine Strategie mit höherem Durchschnittsertrag kann für einen festen Zahlungstermin schlechter geeignet sein, wenn die Wahrscheinlichkeit einer Unterdeckung zunimmt. Der Mittelwert allein sagt nicht, ob das Geld im benötigten Zustand verfügbar ist.`,T`R_{\mathrm{net}}=\frac{V_1+D_1-C_1-T_1-V_0}{V_0},\qquad p_{\mathrm{short}}=P(V_H<L_H)`)
],C('Gleicher Erwartungswert, andere Zuverlässigkeit','In einem Jahr werden 100 benötigt. Beide fiktiven Anlagen kosten heute denselben Betrag. A zahlt sicher 100; B zahlt mit jeweils 50 % Wahrscheinlichkeit 80 oder 120.',['Anlage','Erwarteter Endwert','Wahrscheinlichkeit unter 100','Fehlbetrag schlechter Zustand'],[['A','100','0 %','0'],['B','100','50 %','20']],'Beide Anlagen haben denselben Erwartungswert. Für die feste Verpflichtung ist ihr Nutzen trotzdem verschieden. Ein Erwartungswert ist der Durchschnitt möglicher Zustände und keine überall verfügbare Zahlung. Zusätzliche Reserven oder flexible Ausgaben können die Eignung von B verändern; die Durchschnittszahl allein kann diese Entscheidung nicht treffen.'),[['portfolio-06','Das IPS legt Zielgrößen fest.'],['portfolio-12','Verlustmaße betrachten unterschiedliche Teile der Ergebnisverteilung.']]),
D([
S('Drei Abschlüsse, drei Perspektiven derselben Transaktion',`Die Bilanz beschreibt Bestände, die Gewinnrechnung periodengerechten Erfolg und die Cashflowrechnung Zahlungen. Ein Kreditverkauf erhöht Forderungen und Umsatz ohne sofortiges Cash. Eine Maschinenzahlung senkt Cash und erhöht Sachanlagen, ohne den gesamten Kaufpreis sofort als Aufwand zu erfassen. Erst die gemeinsame Sicht zeigt Finanzierung und Rentabilität.

Die Bilanzgleichung ist eine Bestandsidentität. Eigenkapital ändert sich durch Gewinn, Ausschüttungen, Einlagen und gegebenenfalls erfolgsneutrale Komponenten. Ein Anstieg ist daher nicht automatisch durch Gewinn entstanden. Für Renditen müssen Einlagen von echter Wertsteigerung getrennt werden.`,T`A_t=L_t+E_t,\qquad E_t=E_{t-1}+NI_t-DIV_t+CI_t+OCI_t`),
S('Indirekter Cashflow: Ergebnis in Zahlungen zurückübersetzen',`Die indirekte Cashflowrechnung beginnt beim Ergebnis. Nicht zahlungswirksamer Aufwand wie Abschreibung wird addiert; entsprechender Ertrag wird abgezogen. Danach werden operative Forderungen, Lager und Verbindlichkeiten berücksichtigt. Steigende Forderungen bedeuten, dass mehr Umsatz im Ergebnis enthalten ist als Geld eingegangen ist; der Anstieg wird deshalb abgezogen.

Die Formel verlangt saubere Abgrenzung. Wechselkurse und Akquisitionen können Bilanzposten ändern, ohne dass derselbe Betrag als operativer Cashflow entsteht. Die bloße Differenz veröffentlichter Bilanzwerte ersetzt daher nicht jede Überleitung. Klassifikationen von Zinsen und Dividenden hängen zusätzlich vom Rechnungslegungsrahmen ab.`,T`CFO=NI+DA+NC-\Delta AR-\Delta INV+\Delta AP`)
],C('Bargeschäft und Kreditverkauf','Zwei Firmen verkaufen dieselbe Leistung für 100 bei sofort bezahlten Kosten von 60. A erhält sofort Geld, B erst nächstes Jahr. Keine weiteren Vorgänge.',['Firma','Gewinn heute','CFO heute','Neue Forderung'],[['A','40','40','0'],['B','40','−60','100']],'B ist ebenso profitabel, muss aber zunächst 60 finanzieren. Die Cashflowdifferenz von 100 entspricht der Forderungsbindung. Im Folgejahr führt die Zahlung bei B zu Cashzufluss ohne erneuten Umsatz. Ein erneuter Gewinnausweis würde dieselbe Leistung doppelt zählen.'),[['statements-02','Die Kapitalflussrechnung verbindet Ergebnis und Zahlungen.'],['corporate-08','Working Capital erklärt operativen Finanzierungsbedarf.']]),
D([
S('Absolute Änderung, relative Änderung und Verkettung',`Steigt ein Zinssatz von 2 % auf 3 %, beträgt die Änderung einen Prozentpunkt, relativ zum alten Satz aber 50 %. Ein Basispunkt ist 0,01 Prozentpunkte. In Sensitivitätsformeln wird die Änderung als Dezimalzahl eingesetzt: 100 Basispunkte entsprechen 0,01. Die relative Veränderung des Zinssatzes ist eine andere Größe.

Renditen verschiedener Perioden wirken auf unterschiedliche Vermögensbasen. Sie werden über Wachstumsfaktoren verkettet. Ein Rückgang von 50 % erfordert danach 100 % Gewinn zur Erholung. Diese Asymmetrie erklärt, warum arithmetischer Durchschnitt und Vermögenszuwachs auseinanderfallen.`,T`R_{0,T}=\prod_{t=1}^T(1+r_t)-1,\qquad r_{\mathrm{recovery}}=\frac{L}{1-L}`),
S('Renditebeiträge statt isolierter Prozentzahlen',`Ein Titel mit 20 % Rendite und 5 % Anfangsgewicht trägt einen Prozentpunkt zur einfachen Einperioden-Portfoliorendite bei. Titelrendite und Beitrag zum gesamten Vermögen sind verschieden. Die Zerlegung multipliziert jedes Anfangsgewicht mit der zugehörigen Rendite.

Mehrperiodige Beiträge brauchen eine konsistente Verkettung. Zwischenzeitliche Gewichtsänderungen oder Mittelzuflüsse erlauben keine starre Anfangsgewichtung über den ganzen Zeitraum. Gerundete Gewichte können zudem eine Summe ungleich 100 % erzeugen. Gerechnet wird deshalb intern mit ungerundeten Zahlen.`,T`R_p=\sum_iw_{i,0}R_i,\qquad C_i=w_{i,0}R_i`)
],C('Verluste und benötigte Erholung','Anfangsvermögen jeweils 100. Nur der vorherige Verlust ändert sich.',['Verlust','Restwert','Erforderlicher Gewinn bis 100'],[['10 %','90','11,11 %'],['25 %','75','33,33 %'],['50 %','50','100 %'],['80 %','20','400 %']],'Die zunehmende Erholungsrate folgt aus dem kleiner werdenden Nenner. Sie ist eine Identität und keine Prognose. Der Zusammenhang erklärt die Bedeutung großer Verlustvermeidung für langfristiges Wachstum, auch wenn zwei Strategien ähnliche durchschnittliche Einperiodenrenditen besitzen.'),[['quant-03','Geometrische Rendite misst die tatsächliche Verkettung.'],['portfolio-10','Gewichte verändern sich auch ohne Handel.']]),
D([
S('Diskontieren kehrt die Aufzinsung um',`Eine Geldeinheit heute wächst nach T Perioden auf (1+r)^T. Der Barwertfaktor ist dessen Kehrwert. Addiert werden dürfen nur Zahlungen am selben Bewertungszeitpunkt. Eine undiskontierte Summe heute und später verfügbarer Beträge vermischt unterschiedliche wirtschaftliche Güter.

Bei Monatszahlungen und effektivem Jahreszins ist der äquivalente Monatszins die zwölfte Wurzel des Jahresfaktors minus eins. Den Jahreszins durch zwölf zu teilen ist nur für einen entsprechend definierten nominalen Satz exakt. Vor der Rechnung werden daher Zeitachse, Zahlungsrichtung und Verzinsungskonvention festgelegt.`,T`DF_T=(1+r)^{-T},\qquad PV_T=CF_TDF_T,\qquad r_m=(1+r_a)^{1/12}-1`),
S('Kapitalwert als Wertmaß, IRR als Schwellenrendite',`Der Kapitalwert zieht den heutigen Einsatz vom Barwert der Rückflüsse ab. Ein positiver Wert bedeutet unter den Annahmen mehr als die geforderte Verzinsung. Der IRR ist dagegen der Zinssatz, bei dem dieser Überschuss null wird. Beide entstehen aus derselben Zahlungsreihe, beantworten aber unterschiedliche Fragen.

Bei konventionellen Reihen mit anfänglicher Auszahlung und später positiven Rückflüssen fällt der NPV mit dem Diskontsatz. Mehrfache Vorzeichenwechsel können mehrere IRRs erzeugen. Selbst eindeutige IRRs können bei unterschiedlichen Projektgrößen anders rangieren als NPV. Für gegenseitig ausschließende Wertentscheidungen ist der Kapitalwert unter passendem Diskontsatz ausschlaggebend.`,T`NPV(k)=\sum_{t=0}^T\frac{CF_t}{(1+k)^t},\quad NPV(IRR)=0,\quad\frac{\partial NPV}{\partial k}=-\sum_{t=1}^T\frac{tCF_t}{(1+k)^{t+1}}`)
],C('Gleiche Rückzahlung, anderer Termin','Heute jeweils −100, später +121. Geforderte Rendite 10 %.',['Rückzahlung','Barwert','NPV','IRR jährlich'],[['Nach 1 Jahr','110','10','21 %'],['Nach 2 Jahren','100','0','10 %']],'Der nominale Gewinn von 21 ist gleich, seine Verfügbarkeit verschieden. Die frühere Rückzahlung kann ein weiteres Jahr angelegt werden. Die Zeitachse erklärt den Wertunterschied und verhindert, dass nur absolute Gewinne verglichen werden.'),[['quant-01','Zeitwert vertieft Zinskonventionen.'],['corporate-04','Kapitalbudgetierung vergleicht Projektgrößen und Laufzeiten.']]),
D([
S('Anspruchsgruppen bestimmen Cashflow und Diskontsatz',`FCFF ist vor Zinszahlungen verfügbar und gehört wirtschaftlich Eigen- und Fremdkapitalgebern. FCFE verbleibt nach Fremdfinanzierung beim Eigenkapital. FCFF wird deshalb mit WACC, FCFE mit Eigenkapitalkosten diskontiert. Das gleiche Wort Cashflow ohne Abgrenzung kann eine systematische Fehlbewertung verdecken.

Multiplikatoren verlangen dieselbe Konsistenz. Enterprise Value passt zu operativen Ertragsgrößen vor Finanzierung; Aktienpreis oder Equity Value zu Gewinnen nach Zinsen. EBITDA ist zudem kein frei verfügbarer Cashflow, weil Investitionen, Working Capital und Steuern noch fehlen.`,T`E=EV-D+C_{\mathrm{ex}},\qquad P=\frac EN,\qquad EV=\sum_t\frac{FCFF_t}{(1+WACC)^t}`),
S('Symbole und Einheiten sind lokale Definitionen',`P kann Preis oder Wahrscheinlichkeit, D Dividende, Schuld oder Duration bezeichnen. Alpha ist je nach Zusammenhang ein Regressionsinterzept oder ein Signifikanzniveau. Jede Formel wird deshalb mit ihrer Symboldefinition und Einheit gelesen. Indizes können Zeitpunkte, Anlagen oder Währungen kennzeichnen und sind nicht automatisch Potenzen.

Dimensionsprüfung entdeckt viele Fehler sofort. Preis je Aktie geteilt durch Gewinn je Aktie ergibt einen dimensionslosen Multiplikator. Unternehmenswert geteilt durch EPS enthält dagegen zusätzlich einen Aktienzahlfaktor. Tausend und Millionen sowie Monats- und Jahresraten verlangen entsprechende Umrechnung. Mehr Nachkommastellen lösen keinen Definitionsfehler.`)
],C('Gleiche operative Firma, andere Schulden','EV=150, überschüssiges Cash=10, Aktienzahl=20. Nur Finanzschulden unterscheiden sich.',['Schulden','Equity Value','Wert je Aktie'],[['30','130','6,50'],['60','100','5,00']],'Der operative Wert bleibt gleich; die Aufteilung auf Gläubiger und Aktionäre ändert sich. EV durch Aktienzahl zu teilen würde in beiden Fällen 7,50 ergeben und die verschiedenen Gläubigeransprüche ignorieren. Begriffspräzision verändert hier unmittelbar den berechneten Preis.'),[['equity-09','FCFF und FCFE müssen bei konsistenten Annahmen denselben Eigentümerwert liefern.'],['equity-10','Multiplikatoren verlangen passende Anspruchsgruppen.']])
];
