const {S,C,D,T}=require('./schema.cjs');
module.exports=[
D([S('Bestände durch Bewegungsrechnungen verbinden',`Jeder Bilanzposten besitzt eine Überleitung vom Anfangs- zum Endbestand. Für Sachanlagen werden Investitionen addiert, Abschreibungen und abgegangene Buchwerte abgezogen; zusätzliche Bewertungseffekte kommen separat hinzu. Für Eigenkapital verbinden Ergebnis, sonstiges Gesamtergebnis, Einlagen und Ausschüttungen die Bestände. Diese Bewegungssicht verhindert, dass jede Bilanzänderung als Zahlung interpretiert wird.

Die Gewinnrechnung ordnet Erträge und Aufwendungen einer Periode zu. Die Kapitalflussrechnung erklärt dagegen, warum sich Zahlungsmittel verändern. Eine Kreditaufnahme erhöht Cash und Schulden, ohne Umsatz zu erzeugen. Eine Abschreibung senkt Gewinn und Anlagenbuchwert, ohne im Abschreibungszeitpunkt eine erneute Auszahlung zu verursachen.`,T`PPE_t=PPE_{t-1}+CAPEX_t-DA_t-BV_{\mathrm{disposals},t}+ADJ_t`),S('Abgrenzung des Unternehmens und der Periode',`Ein Abschluss gilt für eine definierte Berichtseinheit und einen Zeitraum. Konzern- und Einzelabschluss können denselben wirtschaftlichen Betrieb unterschiedlich abbilden, weil interne Beziehungen im Konzern eliminiert werden. Ebenso ist ein Quartalsergebnis eine Stromgröße, eine Quartalsendbilanz aber ein Stichtagsbestand.

Für Kennzahlen werden Ströme häufig auf durchschnittliche Bestände bezogen, weil diese das eingesetzte Kapital über die Periode besser approximieren. Bei starken Akquisitionen, saisonalen Spitzen oder Kapitalerhöhungen kann selbst der Mittelwert aus Anfang und Ende unzureichend sein. Aussagekräftige Analyse beginnt deshalb mit Abgrenzung und Zeitbezug.`)],C('Gleicher Cashzufluss, andere wirtschaftliche Bedeutung','Cash steigt jeweils um 100. Sonstige Vorgänge werden isoliert.',['Vorgang','Gegenposten','Gewinnwirkung sofort'],[['Kreditaufnahme','Schulden +100','0'],['Kundenvorauszahlung vor Leistung','Vertragliche Verpflichtung +100','0'],['Erbrachte Leistung ohne weitere Kosten','Ertrag +100','100 vor Steuern']],'Der gleiche Kontoeingang kann Finanzierung, Verpflichtung oder realisierten Erfolg bedeuten. Die Gegenbuchung erklärt den Unterschied. Allein aus dem Bankkonto lässt sich deshalb kein verlässlicher Periodengewinn ableiten.'),[['start-03','Die gemeinsame Sprache der drei Abschlüsse.'],['statements-02','Cashflowüberleitung detailliert aufbauen.']]),
D([S('Indirekten operativen Cashflow systematisch ableiten',`Der indirekte operative Cashflow korrigiert den Periodengewinn um nicht zahlungswirksame Posten und zeitliche Verschiebungen operativer Zahlungen. DA bezeichnet Abschreibungen, NC weitere nicht zahlungswirksame Nettoaufwendungen und NWC das operative Nettoumlaufvermögen. Ein höherer Forderungsbestand bindet Cash; höhere Lieferantenverbindlichkeiten stellen vorübergehend Finanzierung bereit.

Die Rechnung verlangt Konsistenz: Wird Zinscashflow außerhalb des operativen Bereichs klassifiziert, muss die Überleitung entsprechend angepasst werden. Gewinne aus Anlagenverkäufen werden aus dem operativen Ergebnisbezug entfernt, während der gesamte Verkaufserlös separat im Investitionscashflow erscheint. Sonst würde derselbe Verkauf teilweise doppelt zugeordnet.`,T`CFO=NI+DA+NC-\Delta NWC_{op},\quad NWC_{op}=AR+INV-AP`),S('Bilanzdifferenzen sind nicht immer Cashflowänderungen',`Akquisitionen bringen Forderungen und Vorräte in die Bilanz, ohne dass ihre Veränderung aus dem laufenden Geschäft stammt. Wechselkurse können fremdwährungsbezogene Bestände umrechnen. Umgliederungen und nicht zahlungswirksame Transaktionen erzeugen weitere Differenzen. Deshalb werden für eine saubere Überleitung die Bewegungsangaben im Anhang verwendet.

Die drei Cashflowbereiche müssen zusammen mit Wechselkurseffekten und der konkret verwendeten Zahlungsmittelabgrenzung den Anfangs- zum Endbestand erklären. Eine Bilanz, die rechnerisch aufgeht, beweist noch nicht, dass die Cashflowklassifikation richtig ist. Beide Prüfungen ergänzen sich.`,T`\Delta Cash=CFO+CFI+CFF+FX_{Cash}`)],C('Gleicher Gewinn, andere Zahlungsbindung','NI = 50, DA = 10, Vorräte und Verbindlichkeiten unverändert.',['Forderungsänderung','CFO','Interpretation'],[['0','60','Gewinn plus nicht zahlungswirksame Abschreibung'],['+30','30','Umsatz ist teilweise noch nicht bezahlt'],['−20','80','Zusätzlich alte Forderungen eingezogen']],'Jeder Wert folgt aus 50 + 10 minus Forderungsänderung. Ein besonders hoher CFO im dritten Fall kann aus dem Abbau früher gebundener Beträge stammen und ist nicht automatisch dauerhaft wiederholbar.'),[['corporate-08','Umsatzwachstum kann Finanzierung erfordern.'],['statements-13','Cashflowqualität über mehrere Perioden prüfen.']]),
D([S('Vergleichbarkeit durch wirtschaftliche Normalisierung',`IFRS und US GAAP sind Regelwerke mit vielen Gemeinsamkeiten und einzelnen entscheidenden Unterschieden. Für Analysezwecke fragt man zuerst nach derselben wirtschaftlichen Transaktion und anschließend nach Ansatz, Bewertung, Erfolgsort und Cashflowklassifikation. Ein pauschaler Multiplikator zur Umrechnung eines gesamten Abschlusses ist nicht sachgerecht.

Beispielsweise erlaubt US GAAP unter Voraussetzungen LIFO für Vorräte, IFRS nicht. Bei Entwicklungskosten bestehen unterschiedliche Aktivierungsregeln; nicht jede Forschungsausgabe darf als Vermögenswert behandelt werden. Die konkrete aktuelle Standardfassung, Branchenbesonderheiten und Angaben des Unternehmens bestimmen die erforderliche Anpassung.`),S('Eine Bilanzierungswahl wirkt über mehrere Kennzahlen',`Aktivierung verschiebt Aufwand in spätere Perioden und erhöht zunächst das ausgewiesene Vermögen. Dadurch können Gewinnmarge, Vermögensumschlag, Verschuldungsquote und spätere Abschreibungen gleichzeitig verändert werden. Wer nur den heutigen Gewinn korrigiert, lässt die zugehörigen Bestände und Folgeperioden inkonsistent.

Für Vergleichsrechnungen werden deshalb Ergebnis und Bilanz gemeinsam angepasst. Steuerwirkungen und unterschiedliche Nutzungsdauern kommen hinzu. Solche analytischen Anpassungen stellen Vergleichbarkeit für einen bestimmten Zweck her; sie sind kein Ersatz für einen nach dem jeweils geltenden Standard erstellten Abschluss.`)],C('Gleiche Zahlung, anderer Aufwandszeitpunkt','Eine Ausgabe von 100 sei alternativ sofort Aufwand oder, bei erfüllten Voraussetzungen, über fünf Jahre linear abgeschrieben. Keine Steuern; volles erstes Nutzungsjahr.',['Behandlung','Aufwand Jahr 1','Buchwert Ende Jahr 1','Gesamtaufwand nach 5 Jahren'],[['Sofortiger Aufwand','100','0','100'],['Aktivierung','20','80','100']],'Der wirtschaftliche Cashabfluss bleibt 100. Der erste Gewinnunterschied von 80 ist eine zeitliche Abgrenzung, kein zusätzlich verdienter Cashflow. Für einen Vergleich müssen die späteren Abschreibungen und der verbleibende Vermögenswert mitbetrachtet werden.'),[['statements-06','Nutzungsdauer und Wertminderung unterscheiden.'],['statements-12','Kennzahlen konsistent normalisieren.']]),
D([S('Umsatz folgt Leistung und Anspruch, nicht bloß Rechnung',`Bei Umsatzrealisierung sind Vertrag, Leistungsverpflichtungen, Transaktionspreis, Zuordnung und Erfüllungszeitpunkt zu untersuchen. Eine Rechnung kann vor der Leistung gestellt oder nach der Leistung bezahlt werden. Variable Vergütung, Rückgaberechte und Finanzierungskomponenten können dazu führen, dass der nominelle Rechnungsbetrag nicht dem sofort erfassten Umsatz entspricht.

Bei mehreren Leistungen wird der Gesamtpreis nach sachgerechten Einzelverkaufspreisen verteilt. Eine Vorauszahlung erzeugt zunächst eine Verpflichtung; erst ihre Erfüllung führt zum zugeordneten Ertrag. Die wirtschaftliche Frage lautet, welche zugesagte Leistung bereits übertragen wurde und welcher Anspruch dadurch entstanden ist.`,T`TP_i=TP\frac{SSP_i}{\sum_j SSP_j}`),S('Brutto versus netto und Ergebnisabgrenzung',`Ein Unternehmen kann als Prinzipal eine Leistung selbst kontrollieren oder als Agent deren Vermittlung übernehmen. Im ersten Fall kann der Bruttobetrag relevant sein, im zweiten die Vermittlungsvergütung. Gleicher wirtschaftlicher Nettobeitrag kann dadurch mit sehr unterschiedlichen Umsatz- und Margenzahlen erscheinen.

Aufwendungen sind ebenfalls zeitlich zuzuordnen. Rückstellungen erfassen Verpflichtungen unter den einschlägigen Voraussetzungen, nicht beliebige Reserven zur Glättung späterer Ergebnisse. Für die Analyse sind deshalb Vertragstexte, Forderungsentwicklung und Veränderungen der Abgrenzungsposten wichtige Ergänzungen zur Umsatzwachstumsrate.`)],C('Gleicher Beitrag, andere Umsatzbasis','Ein Geschäft bringt wirtschaftlich 10 ein. Variante A weist als Prinzipal 100 Umsatz und 90 bezogene Leistung aus; Variante B als Agent 10 Vergütung ohne entsprechende Durchlaufkosten.',['Variante','Umsatz','Ergebnisbeitrag','Beitragsmarge'],[['A','100','10','10 %'],['B','10','10','100 %']],'Die Marge unterscheidet sich um 90 Prozentpunkte, der absolute Beitrag nicht. Ein unbereinigter Branchenvergleich könnte deshalb eine wesentlich höhere Profitabilität vermuten, obwohl hauptsächlich die Darstellung verschieden ist.'),[['equity-05','Umsatz und Marge gemeinsam modellieren.'],['statements-13','Abgrenzungen auf Qualitätsrisiken prüfen.']]),
D([S('Kostenfluss von physischem Güterfluss trennen',`FIFO und gewichteter Durchschnitt ordnen historische Anschaffungskosten verkauften und verbleibenden Einheiten zu. Die Bewertungsmethode muss nicht dem tatsächlichen Weg einer einzelnen Ware entsprechen. Bei steigenden Preisen enthält FIFO im Endlager tendenziell neuere höhere Kosten und im Aufwand ältere niedrigere Kosten.

LIFO ordnet unter US GAAP mögliche jüngere Kosten eher dem Verkauf zu. Eine LIFO-Reserve kann einen Vergleich zu FIFO unterstützen: Sie erhöht den analytisch angepassten Lagerbestand; ihre Veränderung korrigiert den Wareneinsatz. Die Steuerwirkung muss separat berücksichtigt werden. Bestandsabbau kann alte günstige LIFO-Schichten freisetzen und den Gewinn vorübergehend erhöhen.`,T`INV_{FIFO}=INV_{LIFO}+LR,\quad COGS_{FIFO}=COGS_{LIFO}-\Delta LR`),S('Wertminderung und Kennzahlen',`Beschädigte oder wirtschaftlich entwertete Bestände können einen niedrigeren erzielbaren Wert haben als ihre historischen Kosten. Ein höherer Lagerbuchwert ist deshalb nicht automatisch ein höherwertiger Vermögensbestand. Wertberichtigungen, spätere zulässige Wertaufholungen und ihre Grenzen hängen vom Regelwerk ab.

Lagerumschlag kombiniert Wareneinsatz als Strom mit durchschnittlichem Lagerbestand als Bestand. Bewertungsmethoden beeinflussen beide Seiten. Bei Vergleichen müssen auch Geschäftsmodell, Saisonalität und Lieferkettenstrategie berücksichtigt werden: Mehr Vorrat kann Ineffizienz oder bewusst bezahlte Versorgungssicherheit darstellen.`,T`IT=\frac{COGS}{\overline{INV}},\qquad DIO=\frac{365}{IT}`)],C('Gleiche Waren, unterschiedliche Kostenverteilung','Kauf einer Einheit für 10 und einer für 14; Verkauf einer Einheit für 20. Keine Steuern oder sonstigen Kosten.',['Methode','Wareneinsatz','Endlager','Bruttogewinn'],[['FIFO','10','14','10'],['Durchschnitt','12','12','8'],['LIFO, falls zulässig','14','10','6']],'Die Summe aus Aufwand und Endlager bleibt jeweils 24. Die Methode verändert die Periodenzuordnung, nicht die Anschaffungsauszahlungen. Wenn beide Einheiten verkauft sind, verschwindet dieser isolierte Gesamtgewinnunterschied.'),[['statements-03','Rechnungslegungsrahmen beim Vergleich beachten.'],['corporate-08','Bestandsbindung und Liquidität verbinden.']]),
D([S('Abschreibung verteilt einen Betrag, sie bewertet keinen Marktpreis',`Bei linearer Abschreibung wird der abschreibbare Betrag aus Anschaffungskosten minus Restwert auf die erwartete Nutzungsdauer verteilt. Änderungen dieser Schätzungen verändern künftige Aufwände. Komponenten mit verschiedenen Nutzungsdauern können getrennt betrachtet werden. Ein niedriger Buchwert sagt daher nicht automatisch, dass eine Anlage wirtschaftlich fast wertlos ist.

Eine beschleunigte Methode verlagert Aufwand nach vorne. Bei gleicher Gesamtnutzung und gleichem Restwert bleibt der gesamte Abschreibungsbetrag gleich. Der Cashflow kann sich über tatsächliche steuerliche Folgen unterscheiden, aber die bloße buchhalterische Abschreibung ist selbst keine Auszahlung.`,T`DA=\frac{C-S}{n},\qquad BV_t=C-t\,DA`),S('Wertminderung ist eine zusätzliche Werthaltigkeitsprüfung',`Wertminderung reagiert auf eine verschlechterte wirtschaftliche Deckung des Buchwerts. Unter IAS 36 wird der erzielbare Betrag grundsätzlich aus dem höheren Wert von Nutzungswert und beizulegendem Zeitwert abzüglich Veräußerungskosten bestimmt. Bei Cash-generating Units wird die relevante Einheit abgegrenzt; nicht jeder Vermögenswert erzeugt isolierbare Cashflows.

US-GAAP-Verfahren und mögliche Wertaufholungen unterscheiden sich je nach Vermögensart. Goodwill besitzt besondere Regeln. In der Bewertung sollte eine Wertminderung nicht nochmals mechanisch als zusätzlicher künftiger Cashabfluss abgezogen werden, wenn die gesunkenen operativen Cashflows bereits modelliert sind.`,T`RA=\max(VIU,FVLCD),\qquad IL=\max(BV-RA,0)`)],C('Gleiche Maschine, nur Nutzungsdauer ändern','Anschaffung 100, Restwert 10, lineare Abschreibung; keine Wertminderung.',['Nutzungsdauer','Jahresabschreibung','Buchwert nach 3 Jahren'],[['5 Jahre','18','46'],['10 Jahre','9','73']],'Die längere Schätzung erhöht den Jahresgewinn vor Steuern hier um 9 und den Buchwert nach drei Jahren um 27. Daraus folgt keine bessere operative Maschine. Der Analyst muss beurteilen, ob die längere Nutzungsannahme sachlich begründet ist.'),[['corporate-04','Investitionscashflows von Abschreibungen unterscheiden.'],['equity-09','Abschreibung und Reinvestition im Free Cashflow verbinden.']]),
D([S('Leasingverbindlichkeit als Barwert einer Zahlungsreihe',`Bei einem bilanzierten Leasingverhältnis wird die Verpflichtung grundsätzlich aus relevanten Leasingzahlungen und einem geeigneten Diskontsatz abgeleitet. Der Nutzungsrechtsvermögenswert kann durch Vorauszahlungen, Anreize und weitere zulässige Komponenten vom anfänglichen Verbindlichkeitsbetrag abweichen.

Die Verbindlichkeit entwickelt sich wie eine amortisierende Schuld: Anfangsbestand plus Zinsaufwand minus Zahlung. Deshalb ist nicht jede Mietzahlung vollständig Tilgung. Die Darstellung des Aufwands unterscheidet sich zwischen IFRS und den US-GAAP-Leasingkategorien; Ausnahmen und variable Zahlungen erfordern zusätzliche Prüfung.`,T`L_0=\sum_{t=1}^n\frac{PMT_t}{(1+r)^t},\quad L_t=L_{t-1}(1+r)-PMT_t`),S('Analytische Vergleichbarkeit von Miet- und Eigentumsmodellen',`Ein Unternehmen mit gemieteten Flächen und eines mit kreditfinanziertem Eigentum können ähnliche operative Leistungen anbieten, aber unterschiedliche Kennzahlen ausweisen. Für einen Vergleich werden Verpflichtungen, Zinsbestandteile und Abschreibungen konsistent behandelt. Besonders EV/EBITDA kann verzerrt werden, wenn Leasingverbindlichkeiten im Enterprise Value enthalten sind, die Ergebnisgröße aber anders abgegrenzt ist.

Garantien, Kaufverpflichtungen und andere vertragliche Bindungen können zusätzliche Risiken erzeugen, auch wenn sie nicht alle wie gewöhnliche Finanzschulden bilanziert werden. Eine Analyse betrachtet Eintrittsbedingungen, Fälligkeiten und mögliche gemeinsame Belastung in Stressphasen.`)],C('Gleiche Jahreszahlung, anderer Zinsanteil im Zeitablauf','Drei Zahlungen von 100 am Jahresende, Diskontsatz 5 %. Anfängliche Verpflichtung 272,32.',['Jahr','Zins ungefähr','Tilgung ungefähr','Restschuld ungefähr'],[['1','13,62','86,38','185,94'],['2','9,30','90,70','95,24'],['3','4,76','95,24','0']],'Der Zins sinkt, weil die Restschuld sinkt. Da die Zahlung konstant bleibt, steigt die Tilgung. Rundungsdifferenzen werden im letzten Schritt ausgeglichen; gerechnet wird intern mit ungerundeten Barwerten.'),[['quant-02','Annuitäten und Tilgungspläne herleiten.'],['corporate-06','Finanzierungsdefinition und Kapitalkosten abstimmen.']]),
D([S('Temporäre und permanente Unterschiede',`Ein permanenter Unterschied verändert die steuerliche Belastung, ohne sich später als gegenteilige Buch-Steuer-Differenz umzukehren. Ein temporärer Unterschied betrifft dagegen abweichende Buch- und Steuerwerte von Vermögenswerten oder Verpflichtungen. Latente Steuern ordnen die daraus erwarteten künftigen Steuerfolgen zu.

Für einen Vermögenswert mit höherem Buchwert als Steuerbasis entsteht im einfachen Fall eine steuerpflichtige temporäre Differenz: Bei Realisierung ist weniger steuerliche Kostenbasis verfügbar. Für eine Verpflichtung wirkt die Richtung anders; ein heute bilanziell erfasster, erst später steuerlich abzugsfähiger Aufwand kann eine latente Steuerforderung erzeugen. Ansatzvoraussetzungen und Ausnahmen müssen zusätzlich geprüft werden.`,T`DTL_A=\tau(BV_A-TB_A),\quad DTA_L=\tau(BV_L-TB_L)`),S('Steueraufwand, laufende Steuer und Cashzahlung',`Der gesamte Steueraufwand enthält laufende und erfolgswirksame latente Komponenten. Steuerzahlungen können durch Vorauszahlungen, Nachzahlungen und Erstattungen nochmals davon abweichen. Nicht jede latente Steuerbewegung läuft durch die Gewinnrechnung; etwa direkt im sonstigen Gesamtergebnis erfasste Vorgänge erfordern eine entsprechende Zuordnung.

Eine latente Steuerforderung ist nur so werthaltig wie die Möglichkeit, ihre Vorteile unter den maßgeblichen Regeln zu nutzen. Erwartete Gewinne, Verlustvortragsgrenzen und Fristen sind deshalb wirtschaftlich relevant. Bei geänderten Steuersätzen kann sich der Buchwert latenter Steuern ändern, ohne dass in derselben Periode entsprechend Cash fließt.`,T`TE=CTE+\Delta DTL_{P\&L}-\Delta DTA_{P\&L}`)],C('Gleiche Maschine, andere Abschreibungszeitpunkte','Buchwert nach Jahr 1 ist 80. Die Steuerbasis beträgt alternativ 80 oder 60; Steuersatz 25 %.',['Steuerbasis','Temporäre Differenz des Aktivums','Latente Steuerschuld'],[['80','0','0'],['60','20','5']],'Schnellere steuerliche Abschreibung senkt zunächst die laufende Steuer, verbraucht aber mehr künftige steuerliche Kostenbasis. Die 5 sind deshalb kein neuer operativer Verlust, sondern die Steuerwirkung einer zeitlichen Verschiebung. Ein späterer Umkehreffekt hängt vom weiteren Nutzungs- und Steuerverlauf ab.'),[['statements-06','Buch- und Steuerabschreibung unterscheiden.'],['equity-09','Cashsteuern und normalisierte Steuerquote verwenden.']]),
D([S('Pensionsversprechen und Planvermögen getrennt bewerten',`Eine leistungsorientierte Zusage hängt von künftigen Zahlungen, Gehaltsentwicklung, Dienstzeiten und biometrischen Annahmen ab. Der Verpflichtungsbarwert reagiert auf den Diskontsatz ähnlich wie eine langfristige Anleihe. Das Planvermögen besitzt eigene Markt- und Liquiditätsrisiken; es ist nicht automatisch eine perfekte Absicherung der Verpflichtung.

Der Finanzierungsstatus ist die Differenz zwischen Planvermögen und Verpflichtung. Eine Arbeitgeberzahlung erhöht das Planvermögen, während Dienstzeit- und Zinseffekte die Verpflichtung verändern. Die Rechnungslegung verteilt diese Bewegungen je nach Regelwerk auf Ergebnis und andere Komponenten. Eine einzelne Pensionsaufwandszahl ersetzt deshalb keine Bestandsüberleitung.`,T`FS=PA-DBO,\qquad DBO=\sum_t\frac{E[B_t]}{(1+r_t)^t}`),S('Aktienvergütung kostet wirtschaftlichen Wert',`Eine Vergütung in Aktien oder Optionen kann ohne sofortigen operativen Cashabfluss erfolgen und trotzdem bestehende Eigentümer verwässern. Bei der Analyse werden erfasster Aufwand, mögliche künftige Aktienzahl und Rückkäufe gemeinsam betrachtet. Ein Rückkauf, der nur Mitarbeiteremissionen ausgleicht, ist wirtschaftlich anders als ein gleicher Rückkauf ohne neue Aktien.

Optionen haben aufgrund ihrer asymmetrischen Auszahlung einen Zeitwert. Ihr Aufwand entspricht nicht einfach dem inneren Wert am Zuteilungstag. Bewertungsannahmen, Erdienungsbedingungen und Abwicklungsart beeinflussen die Bilanzierung. Im DCF dürfen Verwässerung und ein korrespondierender Cashkostenersatz nicht unreflektiert doppelt belastet werden.`)],C('Gleiche Verpflichtung, nur Diskontsatz ändern','Eine vereinfachte sichere Zahlung von 100 in 20 Jahren; Planvermögen heute 40.',['Diskontsatz','Verpflichtungsbarwert','Finanzierungsstatus'],[['3 %','55,37','−15,37'],['5 %','37,69','+2,31']],'Die zugesagte spätere Zahlung bleibt 100. Der niedrigere Satz erhöht ihren heutigen Barwert erheblich. Ein verbesserter Status durch höhere Diskontsätze ist daher nicht dasselbe wie eine zusätzliche Arbeitgebereinzahlung.'),[['bonds-08','Langfristige Verpflichtungen besitzen Duration.'],['advanced-03','Aktiva und Verpflichtungen gemeinsam steuern.']]),
D([S('Kontrolle, Einfluss und Finanzanlage unterscheiden',`Die wirtschaftliche Beziehung zur Beteiligung bestimmt, ob voll konsolidiert, nach der Equity-Methode oder als Finanzinstrument bilanziert wird. Prozentanteile können Hinweise liefern, ersetzen aber nicht die Prüfung tatsächlicher Kontrolle oder maßgeblichen Einflusses. Bei Vollkonsolidierung erscheinen grundsätzlich die relevanten Vermögenswerte und Schulden vollständig; fremde Eigentümeranteile werden separat berücksichtigt.

Bei der Equity-Methode erhöht der anteilige Ergebnisbeitrag den Beteiligungsbuchwert, während Ausschüttungen ihn verringern. Eine Dividende ist dann nicht noch einmal derselbe Ertrag. Interne Gewinne und weitere Anpassungen können den einfachen Zusammenhang ergänzen.`,T`I_t=I_{t-1}+p\,NI_t-DIV_t+ADJ_t`),S('Kaufpreisallokation und Goodwill',`Bei einem Unternehmenszusammenschluss werden identifizierbare Nettovermögenswerte nach den einschlägigen Regeln erfasst und bewertet. Goodwill ist im Grundschema der verbleibende Unterschied zwischen Gegenleistung einschließlich relevanter weiterer Komponenten und identifizierbarem Nettovermögen. Er ist keine unabhängig garantierte Reserve künftiger Gewinne.

Erhöhte Zeitwerte können spätere Abschreibungen und damit Gewinne verändern. Nicht beherrschende Anteile müssen in Enterprise-Value- und Ergebnisvergleichen konsistent behandelt werden. Wer einen vollständig konsolidierten operativen Gewinn verwendet, aber nur den Wert des beherrschenden Eigenkapitals berücksichtigt, mischt Anspruchsebenen.`,T`GW=C+NCI+FV_{\mathrm{old}}-FV_{NA}`)],C('Gleicher wirtschaftlicher Anteil, andere Darstellung','Eine 30-%-Beteiligung verdient 100 und schüttet 40 aus; Equity-Methode, keine weiteren Anpassungen.',['Komponente','Betrag für Investor','Buchwertwirkung'],[['Anteil am Ergebnis','30','+30'],['Erhaltene Ausschüttung','12','−12'],['Nettoänderung','18','+18']],'Die 12 Cashzufluss sind Teil des bereits anteilig erfassten Ergebnisses. Würden zusätzlich 12 Dividendenertrag angesetzt, wäre der Gewinn doppelt erfasst. Ergebnis, Cash und Beteiligungsbestand müssen deshalb gemeinsam verfolgt werden.'),[['corporate-10','Akquisitionspreis und Synergien trennen.'],['equity-09','Ansprüche im Enterprise-Value-Übergang abstimmen.']]),
D([S('Transaktion und Abschlussumrechnung sind verschiedene Vorgänge',`Eine Fremdwährungsforderung erzeugt ein wirtschaftliches Wechselkursrisiko zwischen Erfassung und Zahlung. Die Umrechnung eines ausländischen Tochterabschlusses betrifft dagegen die Darstellung vieler Bestände und Ströme in einer Berichtswährung. Funktionale Währung, Berichtswährung und Vertragswährung können verschieden sein.

Monetäre Posten beziehen sich auf feste oder bestimmbare Währungsbeträge; nicht monetäre historische Kostenposten folgen anderen Umrechnungsregeln. Je nach Methode und Situation werden Effekte in der Gewinnrechnung oder im sonstigen Gesamtergebnis erfasst. Eine pauschale Multiplikation aller Zeilen mit demselben Jahresendkurs ist häufig nicht sachgerecht.`),S('Währungsbereinigtes Wachstum rekonstruieren',`Berichtetes Wachstum kombiniert lokale Geschäftsentwicklung, Wechselkurse und Veränderungen des Konsolidierungskreises. Eine konstante-Währung-Rechnung hält die Umrechnungskurse für den Vergleich fest. Sie hilft, den operativen Treiber zu isolieren, ist aber eine analytische Zusatzgröße mit offenzulegender Methodik.

Ein Umrechnungsverlust ist nicht immer ein sofortiger Cashabfluss. Umgekehrt können ungünstige Kurse später reale Wettbewerbs- oder Finanzierungsfolgen haben. Absicherung einer einzelnen Forderung, einer Nettoinvestition und künftiger Umsätze sind daher unterschiedliche Entscheidungen.`,T`1+g_{\mathrm{reported}}=(1+g_{\mathrm{local}})(1+g_{FX})`)],C('Gleicher lokaler Umsatz, andere Berichtswährung','Umsatz steigt lokal von 100 auf 110. Der Umrechnungskurs sinkt von 1 auf 0,9 Berichtswährung je lokale Einheit.',['Sicht','Vorjahr','Aktuell','Wachstum'],[['Lokal','100','110','10 %'],['Berichtet','100','99','−1 %'],['Konstanter alter Kurs','100','110','10 %']],'Der berichtete Rückgang beweist keine schrumpfende lokale Nachfrage. Die Faktoren 1,10 und 0,90 ergeben gemeinsam 0,99. Für die Bewertung bleiben jedoch sowohl operative Entwicklung als auch die in Anlegerwährung zufließenden Beträge relevant.'),[['economics-10','Renditen und Wechselkurse multiplikativ verbinden.'],['advanced-06','Währungsrisiken auf Portfolioebene beurteilen.']]),
D([S('DuPont durch Kürzen statt Auswendiglernen',`Eigenkapitalrendite ist Gewinn geteilt durch durchschnittliches Eigenkapital. Multipliziert man mit Umsatz und durchschnittlichem Vermögen jeweils im Zähler und Nenner, bleibt der Wert unverändert, wird aber in Marge, Vermögensumschlag und Eigenkapitalmultiplikator zerlegt. Das zeigt, ob eine hohe ROE aus operativer Leistung oder stärkerem Leverage entsteht.

Die fünfteilige Erweiterung trennt zusätzlich Steuer- und Zinsbelastung von der operativen Marge. Alle Komponenten müssen dieselbe Perioden- und Bestandsdefinition verwenden. Negative Gewinne, sehr kleines oder negatives Eigenkapital und Akquisitionen können die Interpretation stark erschweren.`,T`ROE=\frac{NI}{S}\frac{S}{\bar A}\frac{\bar A}{\bar E}=\frac{NI}{EBT}\frac{EBT}{EBIT}\frac{EBIT}{S}\frac{S}{\bar A}\frac{\bar A}{\bar E}`),S('Kennzahlen als verknüpftes System lesen',`Eine höhere Marge kann mit niedrigerem Umschlag einhergehen, etwa bei einem kapitalintensiven Premiumgeschäft. Ein Rückkauf kann ROE erhöhen, indem Eigenkapital sinkt, auch ohne besseren operativen Gewinn. Isolierte Zielwerte laden deshalb zu Fehlinterpretationen ein.

Vergleichbarkeit verlangt ähnliche Bilanzierung, Geschäftsmodelle und Risikostrukturen. Für Kreditgeber sind Liquidität und Schuldendienst wichtig; Eigentümer interessieren sich zusätzlich für Wertschaffung über die Kapitalkosten hinaus. Eine Kennzahl beschreibt eine Relation, nicht automatisch eine Qualität. Die Frage nach ihrer Ursache führt zurück zu den einzelnen Abschlüssen.`)],C('Gleiche operative Leistung, anderer Leverage','Nettomarge 5 % und Vermögensumschlag 2 werden konstant gehalten; vereinfachend ist die Marge bereits nach Zins.',['Eigenkapitalmultiplikator','ROE','Rechenweg'],[['1','10 %','0,05 × 2 × 1'],['2','20 %','0,05 × 2 × 2'],['3','30 %','0,05 × 2 × 3']],'Die Zerlegung zeigt mechanisch den Multiplikatoreffekt. Wirtschaftlich kann zusätzlicher Fremdkapitaleinsatz zugleich Zinsaufwand und Risiko erhöhen; dann bleibt die Nettomarge nicht konstant. Die Tabelle isoliert bewusst nur einen Faktor und ist keine kostenlose Renditesteigerungsstrategie.'),[['corporate-07','Leverage und Eigenkapitalrisiko herleiten.'],['equity-11','Buchrendite mit geforderter Eigenkapitalrendite vergleichen.']]),
D([S('Accruals als Brücke, nicht als Betrugsbeweis',`Der Unterschied zwischen Gewinn und operativem Cashflow umfasst periodische Abgrenzungen. Ein wachsendes gesundes Unternehmen kann Forderungen und Lager aufbauen und deshalb weniger CFO als Gewinn ausweisen. Dauerhaft große Abweichungen benötigen jedoch eine Erklärung durch Umsatzbedingungen, Zahlungsdisziplin und Investitionen in Umlaufvermögen.

Eine normalisierte Accruals-Kennzahl skaliert den Unterschied häufig mit durchschnittlichen Aktiva. Sie macht Größenordnungen vergleichbarer, löst aber Bilanzierungs- und Branchenunterschiede nicht auf. Ein Warnsignal ist ein Anlass zur Untersuchung, kein automatischer Nachweis einer Manipulation.`,T`ACC=NI-CFO,\qquad ACC_R=\frac{NI-CFO}{\bar A}`),S('Wiederholbarkeit und ökonomische Substanz prüfen',`Ergebnisqualität betrifft unter anderem Nachhaltigkeit, angemessene Abgrenzung und die Aussagekraft für künftige Cashflows. Ein Veräußerungsgewinn kann korrekt bilanziert, aber nicht wiederholbar sein. Factoring, Lieferantenfinanzierung und verschobene Zahlungen können kurzfristig Cashflowkennzahlen verbessern, ohne das operative Geschäftsmodell zu stärken.

Eine gründliche Prüfung verbindet mehrere Perioden, Anhangangaben und operative Daten. Forderungsalterung, Rückgaben, Lagerreichweite und Veränderungen der Schätzungen erklären, wie ein ausgewiesener Gewinn zustande kommt. Besonders aussagekräftig sind Abweichungen zwischen der erzählten Geschäftsentwicklung und den dazugehörigen Bilanzbewegungen.`)],C('Gleicher Gewinn, verschiedene Cashflowquellen','Beide Firmen weisen NI = 100 und CFO = 120 aus.',['Firma','Quelle des zusätzlichen Cashflows','Nachhaltigkeitsfrage'],[['A','20 planmäßige nicht zahlungswirksame Abschreibung','Welcher Ersatzinvestitionsbedarf folgt?'],['B','20 einmalige Verlängerung von Zahlungszielen','Kann die spätere Zahlung geleistet werden?']],'Die identische CFO-Zahl verbirgt verschiedene zukünftige Verpflichtungen. Auch ein CFO über Gewinn ist daher nicht automatisch hochwertige freie Liquidität. Die Überleitung erklärt, ob der Vorteil wiederholbar ist oder spätere Zahlungen vorzieht.'),[['statements-02','Cashflowquellen einzeln überleiten.'],['equity-09','Nachhaltigen freien Cashflow statt bloßen CFO bewerten.']]),
D([S('Bei Banken ist Finanzierung Teil des Produkts',`Für Industrieunternehmen wird Zinsaufwand oft unterhalb des operativen Ergebnisses betrachtet. Bei Banken sind Kreditvergabe und Einlagenfinanzierung zentrale Geschäftsaktivitäten. Deshalb müssen Zinsmarge, Kreditqualität, Liquidität und regulatorisches Kapital gemeinsam analysiert werden. Ein gewöhnlicher EV/EBITDA-Vergleich kann die ökonomische Struktur verfehlen.

Die Nettozinsmarge setzt Zinsergebnis ins Verhältnis zu durchschnittlichen zinstragenden Aktiva. Eine höhere Marge kann aus besserem Geschäft, aber auch aus höherem Kredit- oder Fristentransformationsrisiko stammen. Risikogewichtete Kapitalquoten reagieren außerdem auf Risikomessung und Zusammensetzung der Aktiva, nicht nur auf deren Nominalvolumen.`,T`NIM=\frac{II-IE}{\overline{EA}},\qquad CET1R=\frac{CET1}{RWA}`),S('Versicherung: Underwriting und Kapitalanlage',`Bei Schadenversicherern zerlegt die Combined Ratio Schaden- und Kostenquote relativ zu den verwendeten Prämienbasen. Eine Quote unter 100 % signalisiert im vereinfachten Rahmen einen positiven versicherungstechnischen Beitrag vor Kapitalanlageergebnis. Reservierung und Rückversicherung beeinflussen die Aussage; die genauen Nenner sind offenzulegen.

Lebensversicherer besitzen andere Verpflichtungsprofile, Garantien und Laufzeiten. Ein positiver Kapitalanlageertrag allein beweist keine ausreichende Deckung langfristiger Zusagen. Zinsrisiko, Stornoverhalten und Solvenzanforderungen verbinden die Versicherungsanalyse mit Asset-Liability-Management.`,T`CR=LR+ER`)],C('Gleiche Zinsmarge, andere Kreditausfälle','Zinstragende Aktiva 1.000, Nettozinsergebnis 30, sonstige Kosten 10.',['Kreditverlustaufwand','NIM','Ergebnis vor weiteren Posten'],[['5','3 %','15'],['25','3 %','−5']],'Beide Banken zeigen dieselbe NIM. Nach Risikokosten unterscheiden sich ihre Ergebnisse um 20. Die Marge muss daher mit Kreditqualität und Kapitalverbrauch beurteilt werden; allein reicht sie nicht zur Rangfolge der Geschäftsqualität.'),[['bonds-10','Erwartete Kreditverluste in Komponenten zerlegen.'],['advanced-03','Verpflichtungen und Anlagen abstimmen.']]),
D([S('Ein integriertes Modell braucht kausale Reihenfolge',`Eine Prognose beginnt mit operativen Treibern: Mengen, Preisen, Margen und Kapazität. Daraus folgen Working Capital, Investitionen und Abschreibungen. Finanzierung deckt anschließend den resultierenden Mittelbedarf; Zinsaufwand und Steuern wirken wieder auf Ergebnis und Cashflow. Wird jede Abschlusszeile unabhängig fortgeschrieben, entstehen leicht wirtschaftlich unmögliche Kombinationen.

Roll-forward-Gleichungen verbinden Bestände mit Bewegungen. Eine abschließende Bilanzdifferenz ist ein Kontrollsignal, kein frei zu verteilender Ausgleichsbetrag. Ein expliziter Finanzierungsmechanismus kann einen revolvierenden Kredit ziehen oder überschüssiges Cash ansammeln; seine Grenzen und Zinsen gehören ins Modell.`,T`Cash_t=Cash_{t-1}+CFO_t-CAPEX_t+\Delta D_t-DIV_t`),S('Sensitivitäten müssen Folgewirkungen mitnehmen',`Höheres Umsatzwachstum erhöht nicht nur Gewinn, sondern kann mehr Forderungen, Lager und Kapazität erfordern. Ein Modell, das ausschließlich Umsatz erhöht, überschätzt dann freien Cashflow. Ebenso kann eine höhere Verschuldung weitere Zinsen auslösen und Covenants verändern.

Zirkularität entsteht etwa, wenn Zinsen vom durchschnittlichen Schuldenstand abhängen und dieser wiederum vom Cashflow nach Zinsen. Sie lässt sich durch begründete zeitliche Konventionen oder kontrollierte Lösungsmethoden behandeln. Iteration ohne Konvergenzprüfung liefert keine verlässliche Prognose.`)],C('Gleiche zusätzliche Marge, anderer Working-Capital-Bedarf','Umsatz steigt um 100, operative Cashmarge vor zusätzlichem Working Capital beträgt 20 %. Keine weiteren Änderungen.',['Zusätzliche NWC-Quote','Zusätzlicher operativer Beitrag','NWC-Bindung','Cashbeitrag'],[['10 %','20','10','10'],['30 %','20','30','−10']],'Die zweite Firma wächst profitabel und benötigt trotzdem zusätzliche Finanzierung. Der Zusammenhang entsteht, weil der Gewinnstrom kleiner ist als der neu gebundene Bestand. Wachstumsannahmen und Finanzierung können daher nicht getrennt prognostiziert werden.'),[['corporate-08','Cash Conversion Cycle als Modelltreiber.'],['equity-05','Wachstum, Margen und Reinvestition verknüpfen.']]),
D([S('Nachhaltigkeit über wirtschaftliche Übertragungswege analysieren',`Ein Nachhaltigkeitsthema wird finanziell relevant, wenn es Cashflows, Vermögenswerte, Verpflichtungen oder Kapitalkosten beeinflusst. Emissionen können etwa über Abgaben, Investitionsbedarf oder Nachfrage wirken; Arbeitsbedingungen über Produktivität, Fluktuation und Haftung. Eine allgemeine Bewertungskategorie ersetzt diese Übertragung nicht.

Exposition und Anpassungsfähigkeit sind getrennt zu untersuchen. Zwei Unternehmen derselben emissionsintensiven Branche können unterschiedliche Energiequellen, Preisweitergabemöglichkeiten und Transformationsinvestitionen besitzen. Eine einzige Branchenkennzahl kann diese Unterschiede verdecken.`,T`\Delta EBIT\approx-\Delta c_{CO2}\,E(1-\theta)-\Delta OPEX+\Delta S`),S('Datenqualität, Doppelzählung und Zeitbezug',`Die beispielhafte Gleichung verwendet Emissionen E, zusätzlichen Preis je Emissionseinheit und Weitergabeanteil θ. Sie ist eine vereinfachte Sensitivität, keine Bilanzierungsregel. Investitionen werden separat über Cashflow und Abschreibung modelliert; erwartete Nachfrageeffekte benötigen eigene Annahmen.

Berichtete und geschätzte Daten, absolute Emissionen und Intensitäten sowie unterschiedliche Berichtsgrenzen dürfen nicht unbemerkt vermischt werden. Sinkende Intensität bei stark wachsendem Umsatz kann mit steigenden Gesamtemissionen einhergehen. Werden Risiken bereits in Cashflows berücksichtigt, ist ein zusätzlicher pauschaler Bewertungsabschlag auf mögliche Doppelzählung zu prüfen.`)],C('Gleiche Emissionen, andere Weitergabefähigkeit','10.000 Emissionseinheiten, zusätzliche Kosten 20 je Einheit. Mengen bleiben im isolierten Beispiel konstant.',['Weitergabeanteil','Zusätzliche Bruttokosten','Verbleibende EBIT-Belastung'],[['0 %','200.000','200.000'],['50 %','200.000','100.000'],['100 %','200.000','0']],'Vollständige Weitergabe neutralisiert hier die direkte Margenbelastung, könnte aber real die Nachfrage senken. Die konstante Menge ist deshalb eine offen gelegte Annahme. Für eine vollständige Analyse wird anschließend die Preiselastizität ergänzt.'),[['economics-01','Weitergabe und Nachfrageelastizität verbinden.'],['equity-05','Szenarien konsistent in Umsatz und Kosten übersetzen.']])
];
