const {F,T,X,S,G}=require('../author.cjs');
module.exports={id:'business-models',intro:[
 'Ein Geschäftsmodell erklärt, für wen ein Unternehmen welchen Nutzen bereitstellt, wie es diese Leistung erzeugt und zugänglich macht und auf welchem Weg daraus eigene Erträge entstehen. Eine attraktive technische Idee genügt nicht: Kunden müssen einen Grund zur Nutzung haben, jemand muss bezahlen und die erforderlichen Ressourcen müssen finanzierbar sein.',
 'Für CFA Level I 2027 stehen Merkmale und Arten von Geschäftsmodellen im Mittelpunkt. Dieses Kapitel verbindet die begriffliche Einordnung mit eigenen Zahlenfällen und Gegenbeispielen. Die vertiefenden Kennzahlen zu Kundenbindung, Kundenwert und Plattformökonomie machen die Mechanik verständlich; sie sind keine Behauptung zusätzlicher offizieller Rechenlernziele. Alle Zahlen sind hypothetisch.'
],sections:[
 S('map','1. Das Geschäftsmodell als überprüfbare Wirkungskette','a',[
  'Geschäftsmodell, Strategie und Finanzprognose beantworten verwandte Fragen auf verschiedenen Ebenen. Das Geschäftsmodell beschreibt die wirtschaftliche Funktionsweise. Die Strategie legt fest, wie sich das Unternehmen im Wettbewerb positioniert und welche Entscheidungen es trifft. Die Finanzprognose übersetzt diese Annahmen in zeitlich bestimmte Umsätze, Kosten, Investitionen und Zahlungen. Keine Ebene ersetzt die andere.',
  T(['Leitfrage','Was geklärt werden muss','Eigener Fall: Wartungsdienst für kleine Betriebe'],[['Für wen?','Nutzer, Käufer, Zahler und relevante Kundensegmente.','Der Betriebsleiter nutzt die Planung; das Unternehmen bezahlt.'],['Welche Leistung und warum?','Welches Problem wird besser gelöst als durch Alternativen?','Weniger ungeplante Maschinenausfälle statt lediglich einer zusätzlichen App.'],['Über welchen Zugang?','Vertrieb, Auslieferung, laufende Betreuung und Kundenbeziehung.','Direktvertrieb, Installation durch Partner und telefonischer Service.'],['Welche Bezahlung?','Preis, Abrechnungseinheit, Zeitpunkt und Bedingungen.','Monatliche Grundgebühr plus nutzungsabhängige Einsätze.'],['Mit welchen Ressourcen?','Aktivitäten, Personal, Anlagen, Daten, Lieferanten und Partner.','Techniker, Ersatzteillager, Software und verlässliche Servicelogistik.'],['Mit welcher Wirtschaftlichkeit?','Deckungsbeitrag, Fixkosten, Kapitalbedarf und Risiken.','Wiederkehrende Erlöse müssen auch Bereitschaft, Teile und Kundenakquisition finanzieren.']],'Die ersten vier Fragen ordnen das Kundenangebot; die letzten beiden prüfen seine tatsächliche Erfüllbarkeit und finanzielle Tragfähigkeit.'),
  'Ein Preismodell wie monatliche Zahlung ist nur ein Baustein. Zwei Abonnementanbieter können völlig andere Anlagen, Kosten, Kündigungsrechte und Kundengewohnheiten besitzen. Ebenso sagt das Wort digital noch nicht, wer bezahlt oder warum dauerhafte Erträge entstehen sollten.',
  'Die Analystin rekonstruiert die Wirkungskette aus Berichten, Vertragsmerkmalen, Segmenten, Kundenverhalten und Wettbewerb. Eine überzeugende Managementbeschreibung wird dabei als zu prüfende Hypothese behandelt. Ein Geschäftsmodell kann wirtschaftlich sinnvoll klingen und trotzdem an Ausführung, Eintrittspreis oder Finanzierung scheitern.'
 ]),
 S('value','2. Kundennutzen schaffen und einen Anteil daran verdienen','a',[
  'Die Value Proposition ist der konkrete Grund, aus dem ein Kunde das Angebot gegenüber seinen Alternativen bevorzugt. Das kann ein niedrigerer Gesamtpreis, höhere Zuverlässigkeit, Zeitersparnis, bessere Qualität, bequemere Nutzung oder geringeres Risiko sein. Eine Produkteigenschaft wird erst dann zum relevanten Nutzen, wenn sie für einen bestimmten Kunden wichtig ist.',
  F('S_C=W-P,\\qquad S_F=P-C,\\qquad S_C+S_F=W-C','Im einfachen Einproduktfall wird der geschaffene Überschuss zwischen Kunde und Anbieter verteilt. Der Preis verschiebt diese Verteilung, ohne bei unveränderter Leistung und Kosten automatisch neuen Gesamtüberschuss zu schaffen.',[['S_C','Kundenüberschuss pro Einheit.'],['W','Zahlungsbereitschaft des Kunden für die betrachtete Einheit.'],['P','Preis je Einheit.'],['S_F','Überschuss des Anbieters pro Einheit vor sonstigen hier nicht erfassten Fixkosten.'],['C','Im Modell relevante Ressourcen- beziehungsweise Opportunitätskosten je Einheit.']]),
  X('Ein besserer Preis ist nicht immer mehr Wertschöpfung','Ein Kunde bewertet eine Leistung mit 120 Euro. Die zugeordneten Ressourcen kosten im vereinfachten Fall 50. Zunächst beträgt der Preis 80; eine Preiserhöhung auf 90 verändert hier weder Menge noch Qualität oder Kosten.',[
   T(['Größe','Preis 80','Preis 90'],[['Kundenüberschuss','40','30'],['Anbieterüberschuss vor weiteren Fixkosten','30','40'],['Summe','70','70']],'Der Anbieter gewinnt zehn Euro auf Kosten des verbleibenden Kundenüberschusses. Der gesamte geschaffene Überschuss bleibt unverändert.'),
   'Sinken dagegen bei gleicher Qualität die relevanten Kosten von 50 auf 40, steigt der insgesamt mögliche Überschuss auf achtzig. Wer diesen zusätzlichen Betrag erhält, hängt von Preis, Wettbewerb und Verhandlungsmacht ab. Reale Preiserhöhungen können auch Mengen, Kündigungen oder Wettbewerbsreaktionen verändern.'
  ],'Value Creation und Value Capture müssen getrennt untersucht werden. Viele begeisterte Nutzer beweisen noch keine ausreichende Ertragsmöglichkeit für den Anbieter.'),
  'Ein hoher Nutzen kann an Beschäftigte, Lieferanten, Vertriebspartner oder Kunden weitergegeben werden, statt beim betrachteten Unternehmen zu verbleiben. Für eine Aktienbewertung interessiert deshalb nicht nur der Nutzen des gesamten Systems, sondern der nachhaltig vom Emittenten beanspruchbare Anteil nach erforderlichen Reinvestitionen.'
 ]),
 S('customers','3. Nutzer, Käufer und Zahler auseinanderhalten','a b',[
  T(['Beziehung','Mechanik','Typischer Analysefehler'],[['B2C','Ein Unternehmen verkauft an private Endkunden.','Viele Nutzer mit hoher Zahlungsbereitschaft gleichsetzen.'],['B2B','Ein Unternehmen liefert an andere Unternehmen.','Den Nutzer einer Software mit dem Einkaufsentscheider verwechseln.'],['B2B2C','Ein Unternehmen erreicht Endkunden über einen Geschäftspartner.','Den Partnerzugang als dauerhaft eigenen Kundenzugang behandeln.'],['Werbefinanziertes Angebot','Eine Gruppe nutzt Inhalte, eine andere bezahlt für Werbemöglichkeiten.','Die kostenlosen Nutzer als zahlende Kunden im selben Erlösmodell zählen.'],['Mehrseitiger Marktplatz','Verschiedene Gruppen nutzen eine Vermittlungsleistung.','Nur eine Seite betrachten, obwohl Angebot und Nachfrage zusammenpassen müssen.']],'Die Kategorien können sich im selben Unternehmen überlagern. Entscheidend ist die konkrete Beziehung, nicht allein das Etikett.'),
  'Bei einer Lernsoftware können Schüler die Nutzer, Lehrkräfte die Entscheider und Schulen die Zahler sein. Gute Nutzerbewertungen reichen nicht, wenn der Beschaffungsprozess oder das Budget die Einführung verhindert. Bei Industriegütern zählen außerdem Freigaben, Integration, Service und mögliche Ausfallkosten.',
  'Kundensegmente benötigen unterschiedliche Angebote, Preise und Betreuung. Ein einheitlicher Durchschnittserlös kann verdecken, dass ein kleines profitables Segment ein großes verlustreiches Segment trägt. Hohe Kundenkonzentration erhöht die Abhängigkeit von einzelnen Verträgen; eine große Kundenzahl allein beseitigt hingegen nicht die Abhängigkeit von einem einzigen Vermittler oder Werbekanal.',
  'Kundenbeziehung und Zugriff auf Daten sind ebenfalls wirtschaftliche Ressourcen. Ein Direktanbieter kann Wiederkäufe selbst ansprechen, während ein Zulieferer unter Umständen keinen direkten Zugang zum Endkunden besitzt. Daraus folgt aber nicht automatisch ein Vorteil: Direktansprache, Datenschutzprozesse und Betreuung verursachen eigene Kosten.'
 ]),
 S('value-chain','4. Wertschöpfungskette: Wer erledigt was und trägt welches Risiko?','a',[
  'Die Value Chain verbindet Beschaffung, Entwicklung, Herstellung, Vertrieb, Lieferung und Betreuung mit unterstützenden Tätigkeiten. Nicht jedes Unternehmen erledigt sämtliche Schritte selbst. Vertikale Integration verlagert mehrere Stufen in dieselbe Organisation; Outsourcing bezieht definierte Leistungen von externen Partnern.',
  T(['Gestaltung','Möglicher Vorteil','Mögliche Gegenwirkung'],[['Eigene Fertigung','Kontrolle über Qualität, Termin und spezifisches Wissen.','Anlagenbindung, Fixkosten und Auslastungsrisiko.'],['Auftragsfertigung','Zugang zu spezialisierter Kapazität und weniger eigene Anlagen.','Abhängigkeit, Qualitätskontrolle, Lieferausfälle und Verhandlungsmacht des Partners.'],['Eigener Vertrieb','Direkter Kundenkontakt und einbehaltener Handelsbeitrag.','Akquisitionskosten, Service, Retouren und eigene Vertriebsorganisation.'],['Externe Distribution','Bestehender Marktzugang und lokale Betreuung.','Abgegebene Marge, eingeschränkte Daten und mögliche Kanalabhängigkeit.']],'Die Vorteile sind Möglichkeiten unter Bedingungen, keine allgemeine Rangliste.'),
  'Asset-light bedeutet weniger eigene bestimmte Vermögenswerte, nicht kostenfrei oder risikolos. Ein Markenanbieter ohne Fabrik benötigt weiterhin Entwicklung, Marketing, Verträge und möglicherweise Lagerbestände. Mindestabnahmemengen können Auslastungsrisiko trotz ausgelagerter Produktion beim Auftraggeber belassen.',
  'Die Analyse verfolgt deshalb physische Güter, Zahlungsansprüche und Entscheidungsrechte getrennt. Wer besitzt einen Bestand? Wer bezahlt bei Ausfall? Wer kann Preise ändern? Wer hält die Beziehung zum Endkunden? Die Antwort zeigt häufig mehr über das Geschäftsmodell als die Rechtsform einer einzelnen Tochtergesellschaft.'
 ]),
 S('channels','5. Direktvertrieb und Zwischenhandel kontrolliert vergleichen','a b',[
  X('Mehr Marge pro Stück, aber mehr eigene Fixkosten','Ein Hersteller kann bei gleicher vorgegebener Absatzmenge entweder direkt verkaufen oder an einen Händler liefern. Direktpreis 100 Euro, Herstellung 40 und zusätzliche variable Direktabwicklung 10 je Stück; jährliche Fixkosten 240.000. Über den Händler erhält der Hersteller 70 je Stück, trägt Herstellungskosten von 40 und Fixkosten von 60.000. Keine weiteren Kosten, Steuern oder Kapitaländerungen im Modell.',[
   F('\\Pi_D=50Q-240000,\\qquad \\Pi_H=30Q-60000','Der Direktkanal behält zwanzig Euro mehr Stückbeitrag, benötigt aber 180.000 Euro mehr jährliche Fixkosten.',[['\\Pi_D,\\Pi_H','Jährliches operatives Ergebnis im Direkt- beziehungsweise Händlerkanal in Euro.'],['Q','Jährlich verkaufte identische Stückzahl; die Gleichheit ist eine kontrollierte Vergleichsannahme.']]),
   F('50Q-240000=30Q-60000\\quad\\Longrightarrow\\quad Q^*=9000','Der höhere Fixkostenblock wird durch zwanzig Euro zusätzlichen Beitrag je Stück aufgeholt.',[['Q','Jährlicher Absatz in Stück.'],['Q^*','Absatzmenge, bei der beide Wege dasselbe operative Ergebnis liefern.']]),
   T(['Absatz in Stück','Direktergebnis in Euro','Händlerkanalergebnis in Euro'],[['6.000','60.000','120.000'],['9.000','210.000','210.000'],['12.000','360.000','300.000']],'Die Handelsmarge vollständig selbst zu behalten ist nur dann vorteilhaft, wenn die zusätzlich übernommenen Aufgaben und Kosten ausreichend gedeckt werden.'),
   'Die eigene Gewinnschwelle des Direktkanals liegt schon bei 4.800 Stück; die des Händlerkanals bei 2.000. Die Vergleichsschwelle 9.000 beantwortet eine andere Frage: welcher positive oder negative Ergebnisbetrag größer ist. In der Realität können sich auch erreichbare Menge, Preis, Retouren und Betriebskapital unterscheiden.'
  ],'Ein höherer Bruttobeitrag pro Stück beweist keinen höheren Gesamtgewinn oder Kapitalwert.'),
  G({id:'channel-profit',title:'Die Vertriebskosten verändern, welcher Kanal vorteilhaft ist',caption:'Eigener Jahresvergleich bei gleicher Menge: Direktkanal 50 Euro Stückbeitrag und 240.000 Euro Fixkosten; Händlerkanal 30 Euro und 60.000 Euro. Keine weiteren Effekte.',reading:'Unter neuntausend Stück liefert der Händlerkanal das höhere Ergebnis. Darüber überwiegt der zusätzliche Stückbeitrag des Direktkanals. Die Schnittmenge ist keine Behauptung, dass beide Kanäle dieselbe Nachfrage erreichen würden.',plot:{x:[0,16000],y:[-250,600],xTicks:[0,4000,8000,12000,16000],yTicks:[-200,0,200,400,600],xLabel:'Absatz pro Jahr in Stück',yLabel:'Operatives Ergebnis in Tausend Euro',series:[{name:'Direktvertrieb',points:[[0,-240],[16000,560]]},{name:'Über Händler',points:[[0,-60],[16000,420]]}],marks:[{x:9000,y:210,label:'9.000 Stück: gleicher Gewinn',dx:-150,dy:-55}]}})
 ]),
 S('pricing','6. Das Preismodell übersetzt Nutzen in eine Zahlung','a b',[
  F('R=\\sum_{j=1}^{J}P_jQ_j','Umsatz aus mehreren Angeboten ergibt sich aus den jeweiligen Preisen und tatsächlich abrechenbaren Mengen. Ein veränderter Mix kann den Durchschnittspreis auch ohne einzelne Preiserhöhung bewegen.',[['R','Periodenumsatz der betrachteten Angebote.'],['P_j','Realisierter Preis je Einheit des Angebots j nach den hier relevanten Preisnachlässen.'],['Q_j','Abgerechnete Einheiten dieses Angebots.'],['J','Anzahl der Angebote.'],['j','Index des jeweiligen Angebots.']]),
  T(['Preismechanik','Woran die Zahlung anknüpft','Prüffrage'],[['Einzelverkauf','Ein Produkt oder eine definierte Leistung.','Wie häufig muss der Anbieter neue Nachfrage gewinnen?'],['Nutzungsabhängig','Einheiten wie Kilometer, Transaktionen oder Rechenzeit.','Wie reagieren Zahlung und Bereitstellungskosten auf Nutzung?'],['Abonnement oder Mitgliedschaft','Zugang über einen Zeitraum; Leistungsumfang vertraglich bestimmt.','Was ist enthalten, wie kann gekündigt werden und wie stabil ist die Nutzung?'],['Provision','Ein Anteil oder Festbetrag je vermitteltem Vorgang.','Auf welche Größe wird der Prozentsatz angewandt und wer trägt Ausfälle?'],['Grundpreis plus Zusatzleistung','Basiszugang und zusätzliche optional gekaufte Merkmale.','Wie hoch sind tatsächlicher Gesamtpreis und Zusatzkosten für typische Nutzer?'],['Dynamischer oder ausgehandelter Preis','Zahlungsbereitschaft, Auslastung oder Verhandlung.','Welche Mengen-, Kunden- und Vertrauenseffekte entstehen?']],'Das Abrechnungsmodell ist von der Preisfindung zu unterscheiden: Ein Festpreis kann etwa kostenorientiert, wettbewerbsorientiert oder am Kundennutzen ausgerichtet sein.'),
  'Cost-plus Pricing setzt einen Aufschlag auf eine definierte Kostenbasis. Das vereinfacht eine Kalkulation, beweist aber nicht, dass Kunden den Preis akzeptieren oder alle relevanten Fix- und Kapitalkosten enthalten sind. Value-based Pricing orientiert sich stärker am Nutzen und an Alternativen der Kunden, benötigt dafür aber belastbare Informationen zur Zahlungsbereitschaft.',
  'Ein höherer Preis kann pro Einheit mehr Beitrag liefern und zugleich Menge, Bindung oder den Produktmix verschlechtern. Eine Gebühr pro Mitarbeiter, pro Transaktion oder pro Ergebnis erzeugt außerdem andere Anreize zur Nutzung. Das Preismodell sollte deshalb zusammen mit dem tatsächlichen Nutzen und den Kosten der Leistung gelesen werden.'
 ]),
 S('unit-economics','7. Stückbeitrag, Gewinnschwelle und Preisnachlass verbinden','a',[
  F('m=P-v,\\qquad \\Pi=mQ-F,\\qquad Q_{BE}=\\frac{F}{m}','Ein positiver Stückdeckungsbeitrag finanziert zunächst die gemeinsamen Fixkosten. Die einfache Gewinnschwelle gilt für konstanten positiven Stückbeitrag innerhalb des betrachteten Kapazitätsbereichs.',[['m','Deckungsbeitrag je verkaufter Einheit.'],['P','Nettoerlös je Einheit.'],['v','Variable Kosten je Einheit.'],['\\Pi','Operatives Periodenergebnis im Modell.'],['Q','Verkaufte Stückzahl der Periode.'],['F','Fixkosten derselben Periode.'],['Q_{BE}','Absatz an der operativen Gewinnschwelle.']]),
  X('Zehn Prozent Preisnachlass verlangen mehr als zehn Prozent Zusatzmenge','Ein Anbieter verkauft jährlich 10.000 Einheiten zu 100 Euro, hat variable Stückkosten von 50 und Fixkosten von 300.000. Der Preis soll auf 90 sinken; Stückkosten und Fixkosten bleiben im geprüften Kapazitätsbereich unverändert.',[
   F('\\Pi_0=(100-50)10000-300000=200000','Der Ausgangsgewinn beträgt 200.000 Euro.',[['\\Pi_0','Operatives Jahresergebnis vor Preisänderung in Euro.']]),
   F('Q_1=\\frac{300000+200000}{90-50}=12500','Für denselben Gewinn muss der kleinere Stückbeitrag insgesamt erneut 500.000 Euro decken.',[['Q_1','Erforderlicher neuer Jahresabsatz in Stück.']]),
   'Das sind 25 % zusätzliche Menge. Bloß denselben Umsatz zu erhalten, würde rund 11.111 Stück verlangen; das reicht wegen der zusätzlichen variablen Kosten nicht für denselben Gewinn. Die neue reine Gewinnschwelle liegt bei 7.500 Stück und ist wieder eine andere Bezugsgröße.'
  ],'Eine Rabattentscheidung braucht eine Mengenreaktion und Kapazitätsprüfung. Umsatzstabilität ist nicht Gewinnstabilität.'),
  'Unit Economics untersucht Beiträge je passender Einheit, etwa Auftrag, Kunde oder vermitteltem Geschäft. Man muss offenlegen, welche Kosten bereits enthalten sind. Positiver Beitrag nach Lieferung, aber vor teurer Akquisition oder zentraler Entwicklung ist noch kein vollständiger Unternehmensgewinn. Skaleneffekte können helfen; dauerhaft negativer zusätzlicher Beitrag kann durch mehr identische Transaktionen auch größer werden.'
 ]),
 S('conventional','8. Konventionelle Geschäftsmodelle anhand ihrer Aufgaben vergleichen','b',[
  T(['Typ','Ertragsmechanik','Wichtige Ressourcen und Risiken'],[['Hersteller','Verkauf selbst entwickelter oder produzierter Güter.','Anlagen, Technologie, Rohstoffe, Ausschuss, Auslastung und Vorräte.'],['Großhändler / Distributor','Einkauf, Bündelung, Verfügbarkeit und Weiterverkauf an Geschäftskunden.','Beschaffung, Logistik, Kredit an Kunden und Lagerumschlag.'],['Einzelhändler','Sortiment und Zugang für Endkunden; Erlös aus dem Weiterverkauf.','Standort oder digitaler Zugang, Warenbestand, Retouren und Schwund.'],['Dienstleister','Vergütung für Arbeitszeit, Projekt, Ergebnis oder laufenden Service.','Fachkräfte, Auslastung, Qualität, Reputation und Nacharbeit.'],['Vermittler','Gebühr für das Zusammenbringen oder Abwickeln einer Transaktion.','Vertrauen, Reichweite, passende Gegenparteien und Vertragsabgrenzung.']],'Diese Typen sind lange etabliert. Digitale Werkzeuge können ihre Ausführung verändern, ohne die zugrunde liegende Erlöslogik vollständig zu ersetzen.'),
  'Ein Großhändler kann durch zuverlässige Verfügbarkeit und kleine Liefermengen Nutzen erzeugen, auch wenn er die Ware nicht selbst herstellt. Sein niedriger prozentualer Gewinn muss nicht schwache Kapitalrendite bedeuten: schneller Umschlag und begrenzte Kapitalbindung können den Vergleich verändern. Umgekehrt kann ein Hersteller mit hoher Marge viel Ersatzkapital benötigen.',
  'Dienstleistungen sind nicht automatisch beliebig skalierbar. Eine Beratung, die für jeden zusätzlichen Auftrag weitere Spezialisten einstellen muss, hat eine andere Kostenlogik als standardisierte Software. Auch Software benötigt allerdings Entwicklung, Sicherheit, Betrieb und Kundenbetreuung. Der wirtschaftliche Engpass muss konkret benannt werden.',
  'Ein Unternehmen kann Hersteller, Händler und Dienstleister gleichzeitig sein. Dann werden die Teile nach ihren jeweiligen Treibern analysiert. Eine pauschale Gesamtmarge kann Verschiebungen zwischen diesen Geschäftsarten verdecken.'
 ]),
 S('recurring','9. Abonnements, Mitgliedschaften und laufende Nutzung','a b',[
  'Ein Subscription Model berechnet wiederkehrende Zahlungen für einen vereinbarten Zugang oder wiederkehrende Leistungen. Mitgliedschaften können ähnliche Zahlungsformen haben, aber andere Nutzenpakete enthalten. Wiederkehrende Abrechnung erhöht unter Umständen Planbarkeit, garantiert jedoch keine dauerhafte Bindung oder positive Marge.',
  'Eine nutzungsunabhängige Pauschale verschiebt das Risiko intensiver Nutzung zum Anbieter, soweit seine Kosten mit der Nutzung steigen. Eine nutzungsabhängige Abrechnung lässt Erlöse stärker schwanken, kann aber Kosten besser folgen. Grundgebühr plus variable Nutzung kombiniert beide Elemente. Rabatte für Vorauszahlung tauschen Preis gegen Liquidität und mögliche längere Bindung.',
  F('MRR=\\sum_{i=1}^{N}M_i,\\qquad ARR=12\\cdot MRR','Die hier verwendete Kennzahl summiert die auf einen Monat normierten wiederkehrenden Vertragsbeträge. ARR annualisiert diese Momentaufnahme, ohne zukünftige Änderungen vorauszusagen.',[['MRR','Monthly Recurring Revenue: hier monatlich normierter wiederkehrender Umsatzbestand zu einem Stichtag.'],['M_i','Für Kunde i auf einen Monat normierter wiederkehrender Vertragsbetrag nach relevanten Rabatten.'],['N','Anzahl einbezogener Kunden.'],['i','Kundenindex.'],['ARR','Annual Recurring Revenue: hier zwölfmal MRR, kein tatsächlich bereits erzielter Jahresumsatz.']]),
  'Ein heute abgeschlossener Jahresvertrag über 1.200 Euro kann bei gleichmäßiger monatlicher Leistung hier MRR 100 beitragen. Vorauszahlung von 1.200 bedeutet trotzdem weder MRR 1.200 noch automatisch vollständig heutigen bilanziellen Umsatz. Vertragsbestand, abrechenbarer Betrag, Zahlungseingang und erfüllte Leistung bleiben verschiedene Größen.',
  'Definitionen von MRR und ARR sind nicht durchgehend standardisiert. Einmalige Einrichtung, variable Nutzung, Testphasen, Währungen und pausierte Kunden können unterschiedlich behandelt werden. Vor Firmenvergleichen ist die jeweilige Abgrenzung zu lesen.'
 ]),
 S('retention','10. Kundenbindung, Bruttoumsatzbindung und Nettoumsatzbindung','a b',[
  F('CR=\\frac{L_N}{N_0},\\qquad GRR=\\frac{R_0-L_R-D_R}{R_0},\\qquad NRR=\\frac{R_0-L_R-D_R+X_R}{R_0}','Kundenverlust zählt Kunden; Umsatzbindung gewichtet nach ihrem Umsatz. Nettoumsatzbindung berücksichtigt zusätzlich Expansion derselben Anfangskohorte.',[['CR','Customer Churn Rate der Periode: verlorene Anfangskunden relativ zum Anfangsbestand.'],['L_N','Anzahl während der Periode verlorener Kunden aus dem Anfangsbestand.'],['N_0','Anzahl Kunden am Periodenanfang.'],['GRR','Gross Revenue Retention: Umsatzbindung der Anfangskohorte ohne Expansion.'],['NRR','Net Revenue Retention: Umsatzbindung derselben Kohorte einschließlich Expansion.'],['R_0','Wiederkehrender Umsatzbestand der Anfangskohorte zu Beginn.'],['L_R','Durch vollständige Abgänge verlorener Umsatz dieser Kohorte.'],['D_R','Durch Verkleinerung bestehender Verträge verlorener Umsatz.'],['X_R','Zusätzlicher wiederkehrender Umsatz durch größere Verträge oder Preise innerhalb derselben Kohorte.']]),
  X('Gesamtwachstum kann verdecken, wie viel Bestand verloren geht','Zu Monatsbeginn: 1.000 Kunden mit insgesamt MRR 50.000 Euro. Achtzig dieser Kunden kündigen und nehmen MRR 4.000 mit. Verkleinerungen anderer Bestandsverträge kosten 2.000. Expansion verbleibender Anfangskunden bringt 6.000. Zusätzlich kommen zweihundert neue Kunden mit insgesamt MRR 10.000 hinzu. Keine Reaktivierungen oder Währungseffekte.',[
   T(['Schritt','Kundenbestand beziehungsweise MRR'],[['Kundenbindung der Anfangskohorte','920 / 1.000 = 92 %'],['GRR','44.000 / 50.000 = 88 %'],['NRR','50.000 / 50.000 = 100 %'],['MRR des gesamten Endbestands','60.000 Euro'],['Kunden im gesamten Endbestand','1.120'],['Annualisierter Endbestand ARR','720.000 Euro']],'Neukunden erhöhen Gesamtbestand und Gesamtumsatz, gehören jedoch nicht in die hier definierte Retention der Anfangskohorte.'),
   'Gesamt-MRR wächst um zwanzig Prozent, die ursprüngliche Kohorte wächst netto gar nicht. Innerhalb dieser Kohorte werden zwölf Prozent Umsatzverlust durch Expansion ausgeglichen. NRR von hundert Prozent bedeutet deshalb nicht, dass kein Kunde gekündigt hat oder sämtliche Verträge stabil geblieben sind.',
   'Wären nur fünf besonders große Kunden statt achtzig kleiner Kunden gegangen, könnte die Kundenbindung sehr gut aussehen und die Umsatzbindung trotzdem schwach sein. Deshalb werden Kundenzahl, Umsatz und passende Segmente nebeneinander gelesen.'
  ],'Kohorten halten den betrachteten Ausgangsbestand konstant. Neue Akquisition darf eine Bindungsschwäche nicht im selben Nenner verstecken.'),
  F('R_{12}=r^{12}=0{,}95^{12}\\approx54{,}04\\%','Die gleichbleibende monatliche Bindung wird über zwölf aufeinanderfolgende Übergänge multipliziert, nicht einfach als Jahresrate übernommen.',[['R_{12}','Erwarteter verbleibender Anteil der Anfangskohorte nach zwölf Übergängen ohne Reaktivierung.'],['r','Monatliche bedingte Kundenbindungswahrscheinlichkeit, hier 95 Prozent.']]),
  'Im einfachen Modell ohne Wiederkehr ist die Kundenbindungsrate eins minus Kunden-Churn. Bei wechselnden Raten multipliziert man die einzelnen Übergänge; eine pauschale Jahreshochrechnung aus einem außergewöhnlichen Monat ist entsprechend unsicher.'
 ]),
 S('lifetime','11. Vertiefung: Kundenwert aus Beitrag, Bindung und Zeitwert herleiten','a b',[
  'Customer Acquisition Cost, kurz CAC, bezeichnet passend abgegrenzte Akquisitionsausgaben je tatsächlich gewonnenem Kunden. Die Kosten und die gewonnenen Kunden müssen zum selben wirtschaftlichen Akquisitionsprozess gehören. Marketingausgaben einer Periode und Verkäufe aus älteren Kampagnen können sonst einen irreführenden Durchschnitt bilden.',
  F('CAC=\\frac{A}{N_{new}},\\qquad PV_C=\\sum_{t=1}^{\\infty}\\frac{m r^{t-1}}{(1+d)^t}=\\frac{m}{1+d-r},\\qquad CLV=PV_C-CAC','Im eigenen konstanten Modell ist die erste Monatsleistung sicher vereinbart; danach bleibt ein Kunde je Übergang mit Wahrscheinlichkeit r. Beiträge fallen am Monatsende an. Die geometrische Reihe ergibt den Kundenbeitragsbarwert.',[['CAC','Akquisitionskosten pro gewonnenem Kunden heute.'],['A','Der betrachteten Akquisition zugeordnete Ausgaben.'],['N_{new}','Anzahl dadurch gewonnener Kunden.'],['PV_C','Barwert erwarteter zukünftiger Kundenbeiträge vor Akquisitionskosten.'],['m','Monatlicher Beitrag nach den zugeordneten laufenden Kosten, solange der Kunde aktiv ist.'],['r','Konstante monatliche Bindungswahrscheinlichkeit nach dem ersten sicher vereinbarten Leistungsmonat; keine Reaktivierung.'],['d','Passender effektiver monatlicher Diskontsatz; die Reihe verlangt r kleiner als 1 plus d.'],['t','Monatsindex ab dem ersten späteren Monatsende.'],['CLV','Customer Lifetime Value: hier Kundenbeitragsbarwert nach einmaligen heutigen Akquisitionskosten.']]),
  'Der erste Term ist der Monatsbeitrag geteilt durch eins plus Diskontsatz. Jeder nächste Term wird mit Bindungsrate geteilt durch eins plus Diskontsatz multipliziert. Die Formel folgt daraus, dass die unendliche Summe gleich erster Term geteilt durch eins minus dieses Verhältnis ist. Beginnt die Rechnung stattdessen mit einer Bindungsentscheidung schon vor dem ersten Zahlungstermin, steht zusätzlich die Bindungsrate im Zähler. Unterschiedliche Zeitkonventionen dürfen nicht ungeprüft gemischt werden.',
  X('Gleicher Preis und gleiche Akquisition, andere Bindung','Monatlicher Kundenbeitrag 20 Euro, heutige CAC 250, monatlicher Diskontsatz 1 %. Erste Monatsleistung sicher, anschließend konstante Übergangsbindung. Keine Expansion, Reaktivierung oder zusätzlichen nicht modellierten Kundenkosten. Zentrale Fixkosten sind noch nicht abgezogen.',[
   T(['Monatlicher Churn','Monatliche Bindung','Beitragsbarwert vor CAC','Kundenwert nach CAC'],[['2 %','98 %','666,67','416,67'],['5 %','95 %','333,33','83,33'],['10 %','90 %','181,82','−68,18']],'Beträge in Euro je heute gewonnenem Kunden. Gleiche Neukundenzahl und gleicher Monatsumsatz können sehr verschiedene Kundenwerte erzeugen.'),
   F('CLV=\\frac{20}{1{,}01-0{,}95}-250\\approx83{,}33','Im mittleren Fall reicht der erwartete Beitragsbarwert über die Akquisitionsausgabe hinaus. Der Überschuss muss noch zentrale Kosten und weitere nicht enthaltene Anforderungen tragen.',[['CLV','Kundenbeitragswert nach Akquisition in Euro unter den angegebenen Annahmen.']]),
   'Eine undiskontierte Näherung Beitrag geteilt durch Churn ergäbe vierhundert vor CAC. Sie ignoriert den Zeitwert. Ein auf Umsatz statt Beitrag beruhender Wert ließe zusätzlich die Leistungskosten aus. Beide Vereinfachungen können einen tatsächlich schwachen Kundenstamm zu attraktiv erscheinen lassen.'
  ],'Die Formel ist eine Transparenzhilfe für eine ausdrücklich einfache Kundenwelt, keine garantierte Lebensdauer oder alleinige Unternehmensbewertung.'),
  'Bindung kann vom Kundenalter, Kanal und Preis abhängen. Profitablere ältere Kunden, Rabatte, fehlgeschlagene Zahlungen und hohe Betreuungskosten erfordern einzelne Kohorten oder Zahlungsreihen. Die Summe bestehender Kundenwerte ist außerdem nicht automatisch der gesamte Unternehmenswert: zukünftige Akquisition, gemeinsame Kosten, Steuern, Investitionen und übrige Vermögenswerte fehlen je nach Abgrenzung.'
 ]),
 S('payback','12. Rückflussdauer und Liquiditätsbedarf trotz positivem Kundenwert','a b',[
  F('PV_C(n)=\\frac{m}{1+d-r}\\left[1-\\left(\\frac{r}{1+d}\\right)^n\\right]','Die endliche geometrische Reihe bewertet nur die Beiträge bis zum Ende von Monat n. So lässt sich prüfen, wann die anfängliche Akquisition im Erwartungswert aufgeholt ist.',[['PV_C(n)','Heutiger Wert der erwarteten Beiträge bis einschließlich Monat n.'],['m','Monatlicher Beitrag je aktivem Kunden.'],['r','Monatliche Bindungsrate nach dem ersten sicher vereinbarten Monat.'],['d','Passender monatlicher Diskontsatz.'],['n','Anzahl berücksichtigter Monatsendzahlungen.']]),
  X('Eine scheinbar kurze Amortisation wird durch Abgänge länger','Der mittlere Kundenfall wird fortgesetzt: 20 Euro monatlicher Beitrag, 95 % Bindung, 1 % monatlicher Diskontsatz und 250 Euro Akquisition heute.',[
   'CAC geteilt durch einen unveränderten Monatsbeitrag ergibt 12,5 Monate. Das wäre eine einfache ungekündigte und undiskontierte Rückflussrechnung. Sie ist nicht die erwartete Rückflussdauer einer Kohorte mit Abgängen.',
   F('PV_C(12)=\\frac{20}{0{,}06}\\left[1-\\left(\\frac{0{,}95}{1{,}01}\\right)^{12}\\right]\\approx173{,}49','Nach zwölf Monaten sind im Erwartungswert erst rund 173,49 Euro Beitragsbarwert zurückgeflossen.',[['PV_C(12)','Beitragsbarwert aus den ersten zwölf Monaten in Euro.']]),
   'Die undiskontierte erwartete Beitragssumme überschreitet 250 erstmals mit der zwanzigsten Monatszahlung. Mit Diskontierung geschieht dies erst mit der dreiundzwanzigsten. Das sind Erwartungsrechnungen über viele vergleichbare Kunden; ein einzelner Kunde kann vorher gehen oder länger bleiben.',
   'Hundert gleichzeitig gewonnene Kunden benötigen heute 25.000 Euro Akquisition. Ihr modellierter Netto-Kundenwert beträgt rund 8.333 Euro, aber der Barwert der ersten zwölf Monate liefert nur rund 17.349. Schnelles Wachstum kann deshalb trotz positiver Einzelkundenwerte einen erheblichen Zwischenfinanzierungsbedarf erzeugen.'
  ],'Langfristiger erwarteter Wert und rechtzeitig verfügbare Liquidität sind verschiedene Anforderungen.'),
  G({id:'customer-payback',title:'Kündigungen verschieben den erwarteten Rückfluss',caption:'Kumulierte diskontierte Kundenbeiträge minus 250 Euro Akquisition heute. Monatlicher Beitrag 20, Diskontsatz 1 %, erste Monatsleistung sicher. Danach konstante Bindung von 98 %, 95 % oder 90 %.',reading:'Bei fünf Prozent monatlichem Churn wird die Nulllinie erst mit der dreiundzwanzigsten Monatszahlung überschritten. Bei zehn Prozent Churn reicht unter diesen Annahmen selbst die unendliche Beitragsfolge nicht zur Deckung der Akquisition.',plot:{x:[0,36],y:[-260,250],xTicks:[0,6,12,18,24,30,36],yTicks:[-250,-125,0,125,250],xLabel:'Berücksichtigte Monatsendzahlungen',yLabel:'Netto-Beitragsbarwert je Kunde in Euro',series:[.98,.95,.90].map(r=>({name:(Math.round((1-r)*100))+' % monatlicher Churn',points:Array.from({length:37},(_,n)=>[n,20/(1.01-r)*(1-(r/1.01)**n)-250])})),marks:[{x:23,y:20/.06*(1-(.95/1.01)**23)-250,label:'5 % Churn: erstmals positiv',dx:25,dy:-45}]}}),
  'Ein positiver Kundenwert rechtfertigt keine unbegrenzte Akquisition zum bisherigen Durchschnittspreis. Zusätzliche Kanäle können teurer sein und schlechter gebundene Kunden liefern. Entscheidend sind die inkrementellen Kunden und Kosten der nächsten Wachstumsstufe sowie der finanzierbare Zeitraum bis zum Rückfluss.'
 ]),
 S('freemium','13. Freemium und Werbung: kostenlos für wen?','a b',[
  'Freemium verbindet einen dauerhaft verfügbaren kostenlosen Grundumfang mit bezahlten Zusatzleistungen. Eine zeitlich begrenzte kostenlose Testphase ist etwas anderes: Nach ihrem Ende muss der Nutzer für weiteren vergleichbaren Zugang zahlen oder aufhören. Im Freemium-Modell können kostenlose Nutzer Akquisition, Daten oder Netzwerkqualität unterstützen, verursachen aber häufig auch Betrieb und Betreuung.',
  X('Mehr kostenlose Nutzer sind nicht automatisch mehr Gewinn','Ein Dienst besitzt in einer Periode insgesamt 10.000 aktive Nutzer. Zahlende Nutzer zahlen 20 Euro und verursachen je 4 Euro variable Kosten. Kostenlose Nutzer kosten je 0,20 Euro. Fixkosten der Periode einschließlich der hier vorgegebenen gemeinsamen Entwicklung und Akquisition betragen 8.000 Euro. Nutzerzahl und Kostenstruktur bleiben beim Vergleich unverändert.',[
   F('\\Pi=N\\left[f(P-v_P)-(1-f)v_F\\right]-F','Der Beitrag zahlender Nutzer muss kostenlose Nutzung und gemeinsame Kosten mittragen.',[['\\Pi','Operatives Periodenergebnis im Modell.'],['N','Gesamtzahl aktiver Nutzer, kostenlos und zahlend zusammen.'],['f','Anteil zahlender Nutzer an dieser Gesamtheit.'],['P','Erlös pro zahlendem Nutzer und Periode.'],['v_P','Variable Kosten pro zahlendem Nutzer und Periode.'],['v_F','Variable Kosten pro kostenlosem Nutzer und Periode.'],['F','Fixkosten derselben Periode.']]),
   F('\\Pi=162000f-10000,\\qquad f_{BE}=\\frac{10000}{162000}\\approx6{,}1728\\%','Ein Nutzer, der in diesem kontrollierten Vergleich zahlend wird, erzeugt sechzehn Euro Beitrag und beseitigt zugleich zwanzig Cent kostenlose Betreuungskosten.',[['\\Pi','Periodenergebnis in Euro.'],['f','Zahlender Anteil als Dezimalzahl.'],['f_{BE}','Erforderlicher zahlender Anteil an der Gewinnschwelle.']]),
   T(['Zahlender Anteil','Zahlende Nutzer','Erlös','Kostenlose Nutzungskosten','Operatives Ergebnis'],[['5 %','500','10.000','1.900','−1.900'],['8 %','800','16.000','1.840','2.960'],['10 %','1.000','20.000','1.800','6.200']],'Beträge je Periode in Euro; variable Kosten zahlender Nutzer und 8.000 Fixkosten sind im Ergebnis ebenfalls abgezogen.')
  ],'Die Zahl aktiver Nutzer benötigt eine monetarisierbare Beziehung zu Erlösen und Kosten. Ein hoher Konversionsanteil allein ersetzt auch keine Bindungsprüfung.'),
  G({id:'freemium-conversion',title:'Die zahlenden Nutzer tragen beide Nutzergruppen',caption:'Eigener Freemium-Fall mit 10.000 aktiven Nutzern. Ergebnis gleich 162.000 mal zahlendem Anteil als Dezimalzahl minus 10.000 Euro; Kosten und Gesamtzahl unverändert.',reading:'Bei fünf Prozent zahlenden Nutzern verliert der Dienst 1.900 Euro. Bei acht Prozent verdient er 2.960 Euro. Die Gewinnschwelle liegt bei etwa 6,17 Prozent; sie verändert sich mit Betreuungskosten, Preis und gemeinsamen Kosten.',plot:{x:[0,12],y:[-11000,11000],xTicks:[0,3,6,9,12],yTicks:[-10000,-5000,0,5000,10000],xLabel:'Zahlender Nutzeranteil in %',yLabel:'Operatives Periodenergebnis in Euro',series:[{name:'Operatives Ergebnis',points:[[0,-10000],[12,9440]]},{name:'Gewinnschwelle',dash:'5 4',points:[[0,0],[12,0]]}],marks:[{x:10000/162000*100,y:0,label:'6,17 %',dx:-58,dy:-24}]}}),
  F('R_{ad}=\\frac{I a}{1000}CPM=\\frac{10000000\\cdot0{,}80}{1000}\\cdot4=32000','Beim werbefinanzierten Modell bezahlt eine andere Kundengruppe. Nur tatsächlich vermarktete Kontakte werden in dieser Rechnung zum angegebenen Tausenderpreis vergütet.',[['R_{ad}','Werbeerlös der Periode in Euro.'],['I','Verfügbare Anzahl Werbekontakte der Periode.'],['a','Anteil dieser Kontakte, der tatsächlich zum angesetzten Preis vermarktet wird.'],['CPM','Cost per Mille: Preis in Euro pro tausend vermarktete Werbekontakte, hier aus Sicht des Anbieters Erlös.']]),
  'Nutzerwachstum kann durch sinkende Vermarktung, niedrigere Werbepreise oder höhere Inhaltskosten überkompensiert werden. Reichweite, Erlös und Gewinn sind deshalb getrennt zu prüfen.'
 ]),
 S('complements','14. Basisprodukt, Verbrauchsgut, Zusatzleistung und Bündel','a b',[
  'Razor-and-Blades Pricing kombiniert ein günstig angebotenes Basisgerät mit profitablen späteren Verbrauchsgütern oder Ergänzungen. Der Zusammenhang funktioniert nur, wenn das Gerät tatsächlich genutzt wird, Ergänzungen wiederholt benötigt werden und der Anbieter genügend dieser Käufe erhält. Kompatible Fremdprodukte, längere Nutzungszyklen oder frühe Aufgabe können die Rechnung verändern.',
  X('Ein anfänglicher Verlust braucht ausreichende spätere Beiträge','Ein Gerät wird heute für 90 Euro verkauft und kostet 120. Jeder spätere Nachfüllkauf liefert fünf Euro zusätzlichen Beitrag nach allen zugeordneten variablen Kosten. Für den einfachen Vergleich finden alle Nachfüllkäufe am Ende von Jahr eins statt; passende Jahresrenditeforderung zehn Prozent.',[
   F('NPV=-30+\\frac{5q}{1{,}10}','Die anfängliche Subvention wird gegen den heutigen Wert der späteren Beiträge gerechnet.',[['NPV','Kapitalwert je neu verkauftem Gerät vor zusätzlichen hier nicht angesetzten gemeinsamen Kosten.'],['q','Anzahl dem Anbieter zurechenbarer Nachfüllkäufe am Ende des Jahres.']]),
   'Sechs Käufe decken nominal die dreißig Euro, ergeben aber Kapitalwert minus 2,73. Sieben Käufe liefern rund plus 1,82; acht rund plus 6,36. Der Zeitwert macht den erforderlichen Rückfluss größer als den heutigen Verlust. Käufe bei einem Fremdanbieter zählen nicht als eigener Beitrag.'
  ],'Die installierte Gerätebasis ist nur dann wertvoll, wenn sie zukünftige profitable eigene Zahlungen trägt.'),
  'Add-on Pricing verkauft optionale Leistungen zusätzlich zu einer Basisleistung. Die Zusatzleistung muss kein regelmäßig verbrauchtes komplementäres Gut sein; beispielsweise kann ein Kunde einmalig zusätzliche Betreuung buchen. Bundling bietet mehrere Bestandteile gemeinsam an. Das kann Suchkosten reduzieren und unterschiedliche Zahlungsbereitschaften nutzen, aber Rabatte können auch bisher einzeln bezahlte Erlöse verdrängen.',
  'Bei einem Paket für 90 statt einzeln jeweils 60 für zwei Produkte muss man fragen, welche Kunden vorher tatsächlich beide gekauft hätten. Wer nur ein Produkt für sechzig gekauft hätte und jetzt neunzig bezahlt, erhöht den Erlös. Wer vorher beide für insgesamt 120 gekauft hätte, zahlt weniger. Eine pauschale Paketmarge ohne Segment- und Kostenbetrachtung erklärt diese Wirkungen nicht.'
 ]),
 S('assets','15. Verkauf, Vermietung und ergebnisabhängige Leistung','a b',[
  T(['Modell','Wofür bezahlt wird','Typische wirtschaftliche Risikoverteilung'],[['Verkauf','Übertragung des vereinbarten Produkts.','Käufer trägt häufig nachgelagerte Nutzung und Restwert, abhängig von Garantien und Vertrag.'],['Vermietung / Leasing','Vertraglich bestimmter Zugriff auf ein Gut für einen Zeitraum.','Anbieter kann Kapital- und Restwertrisiko behalten; Nutzung, Wartung und Rückgabe richten sich nach dem Vertrag.'],['Ergebnisabhängiger Dienst','Eine bestimmte Leistung, etwa gelieferte Betriebsstunden oder Verfügbarkeit.','Anbieter kann stärker für Zuverlässigkeit und Effizienz einstehen; Messbarkeit und Verhalten des Kunden werden wichtig.'],['Gemeinsam genutzte Kapazität','Zeit- oder nutzungsbezogener Zugriff auf eine geteilte Ressource.','Auslastung, Überlastung, Wartung und lokale Nachfrage bestimmen die Wirtschaftlichkeit.']],'Wirtschaftliches Geschäftsmodell und konkrete bilanzielle Leasingklassifikation sind getrennte Analysen.'),
  X('Wiederkehrende Mieterlöse müssen das bereitgestellte Gut finanzieren','Ein Anbieter kauft heute eine Anlage für 1.000. Sie erzeugt vier Jahre lang am Jahresende je 300 Nettozahlungsüberschuss nach laufenden Kosten. Am Ende des vierten Jahres kommt ein Nettoverkaufserlös von 100 hinzu. Die angegebenen Zahlungen berücksichtigen alle hier relevanten Steuer- und Kostenwirkungen; Diskontsatz zehn Prozent.',[
   F('NPV=-1000+\\sum_{t=1}^{4}\\frac{300}{1{,}10^t}+\\frac{100}{1{,}10^4}\\approx19{,}26','Die Anlage bindet Kapital vor dem ersten wiederkehrenden Zufluss. Der Restwert wird zusätzlich erst am tatsächlichen Endtermin berücksichtigt.',[['NPV','Kapitalwert des bereitgestellten Mietobjekts.'],['t','Jahresindex der jeweiligen Zahlung.']]),
   'Entfallen nur die zusätzlichen hundert am Ende, sinkt der NPV um rund 68,30 auf minus 49,04. Wiederkehrender Umsatz allein macht das Modell daher nicht automatisch attraktiv. Geringere Auslastung, höhere Wartung oder längere Leerstände können einen ähnlich großen Einfluss besitzen.'
  ],'Ein Verkauf kann Geld früher freisetzen; ein Zugangsmodell kann Beziehungen verlängern, bindet aber unter Umständen mehr eigenes Kapital.'),
  'Beim ergebnisabhängigen Vertrag lohnt sich für den Anbieter effiziente Wartung, wenn er die Kosten trägt und der Kunde für verlässliche Leistung zahlt. Der Anreiz kann kippen, wenn der Kunde die Anlage übermäßig belastet oder Erfolg nicht sauber messbar ist. Solche Grenzen gehören zum Geschäftsmodell, nicht erst in eine spätere Vertragsnotiz.'
 ]),
 S('rights','16. Lizenzierung und Franchising: Rechte statt jedes Geschäft selbst betreiben','b',[
  'Licensing erlaubt die definierte Nutzung geistiger oder anderer geschützter Rechte gegen eine Vergütung. Diese kann ein Festbetrag, eine laufende Gebühr oder eine umsatz- beziehungsweise nutzungsabhängige Royalty sein. Ein Lizenzgeber kann wachsen, ohne jede Anwendung selbst zu produzieren, benötigt aber wertvolle Rechte, Durchsetzung, Qualitätssicherung und laufende Erneuerung.',
  'Franchising verbindet typischerweise Marke und Geschäftssystem mit Vorgaben und Unterstützung für rechtlich eigenständige Betreiber. Der Franchisegeber erzielt vereinbarte Gebühren; der Franchisenehmer betreibt das lokale Geschäft und trägt die ihm zugewiesenen Investitionen und Kosten. Die genaue rechtliche Einordnung und Pflichten hängen vom Vertrag und Rechtsraum ab; hier wird die wirtschaftliche Mechanik untersucht.',
  X('Systemumsatz ist nicht der Umsatz des Franchisegebers','Ein eigenständiger Standort verkauft jährlich für eine Million Euro. Er trägt variable Kosten von 650.000 und weitere operative Kosten von 250.000. Der Franchisegeber erhält als einzige Vergütung eine laufende Gebühr von sechs Prozent des Standortumsatzes und trägt dafür eigene Betreuungskosten von 20.000. Keine weiteren Transaktionen im Modell.',[
   F('R_F=0{,}06\\cdot1000000=60000,\\qquad \\Pi_F=60000-20000=40000','Der Franchisegeber besitzt hier sechzigtausend Euro Gebührenumsatz und vierzigtausend Beitrag nach den angegebenen Betreuungskosten.',[['R_F','Jährlicher Umsatz des Franchisegebers aus diesem Vertrag.'],['\\Pi_F','Jährlicher Beitrag dieses Vertrags beim Franchisegeber vor weiteren gemeinsamen Kosten.']]),
   F('\\Pi_N=1000000-650000-250000-60000=40000','Die gleiche Gebühr ist beim Standort eine Ausgabe. Dessen übrige Kosten bleiben trotz Nutzung der Marke bestehen.',[['\\Pi_N','Operatives Jahresergebnis des Franchisenehmers im angegebenen Fall.']]),
   'Die gleiche Ergebniszahl von vierzigtausend hat zwei verschiedene Umsatz- und Kapitalbasen. Eine Million Systemumsatz als eigener Franchisegeberumsatz würde die Größenordnung verfälschen. Anfangsgebühren, Werbung, Warenlieferungen und eigene Standorte würden zusätzliche getrennte Zahlungs- und Leistungsströme erzeugen.'
  ],'Ein Netzwerk vieler unabhängiger Betreiber ist kein kostenloses Filialnetz. Qualität, Anreize, Unterstützung und Abhängigkeiten bestimmen seine Tragfähigkeit.'),
  'Ein lokaler Betreiber kann kurzzeitig Kosten sparen und damit das gemeinsame Markenversprechen beschädigen. Der Franchisegeber kann Gebühren erhöhen und damit die Investitionsfähigkeit der Betreiber schwächen. Dieses Zusammenspiel verbindet Geschäftsmodell und Principal-Agent-Analyse.'
 ]),
 S('platforms','17. Plattformökonomie: Handelsvolumen, Umsatz und Ergebnis trennen','a b',[
  'Eine Plattform ermöglicht Interaktion zwischen mehreren Teilnehmergruppen und setzt dafür Regeln, Zugang oder Infrastruktur bereit. Sie muss die gehandelten Güter nicht selbst besitzen. Ein gewöhnlicher Händler kauft dagegen häufig selbst ein und verkauft auf eigene Rechnung. Mischformen sind möglich; die Bezeichnung Plattform entscheidet nicht allein über Risiko oder Umsatzdarstellung.',
  F('R=GMV\\cdot t,\\qquad \\Pi=GMV(t-c)-F','Im einfachen reinen Provisionsmodell wird nur ein Anteil des vermittelten Werts zum eigenen Erlös. Variable Kosten können ebenfalls vom vermittelten Wert abhängen.',[['R','Eigener Provisionserlös der Periode.'],['GMV','Gross Merchandise Value: hier vermittelter Transaktionswert nach der ausdrücklich verwendeten Abgrenzung.'],['t','Take Rate: hier Provision als Anteil am GMV.'],['c','Variable Kosten als Anteil am gleichen GMV, etwa Zahlungsabwicklung und erwartete Verluste.'],['F','Gemeinsame Fixkosten der Periode.'],['\\Pi','Operatives Periodenergebnis des abgegrenzten Plattformmodells.']]),
  X('Mehr Handelsvolumen und sogar mehr Erlös, aber weniger Gewinn','GMV zunächst zehn Millionen Euro, Take Rate 8 %, variable Kosten 2,5 % desselben Volumens und Fixkosten 400.000. Ein niedrigerer Gebührensatz von 6 % soll das GMV auf vierzehn Millionen erhöhen. Die variable Kostenquote und Fixkosten bleiben im Vergleich unverändert.',[
   T(['Größe','Ausgangsfall','Niedrigere Gebühr'],[['GMV','10.000.000','14.000.000'],['Provisionserlös','800.000','840.000'],['Variable Kosten','250.000','350.000'],['Fixkosten','400.000','400.000'],['Operatives Ergebnis','150.000','90.000']],'Alle Beträge je Periode in Euro. GMV wächst um vierzig Prozent, Erlös um fünf Prozent, Ergebnis fällt um vierzig Prozent.'),
   F('GMV^*=\\frac{400000+150000}{0{,}06-0{,}025}\\approx15714285{,}71','Für den alten Ergebnisbetrag wären beim niedrigeren Gebührensatz rund 15,714 Millionen GMV nötig, also gut 57 Prozent mehr als zuvor.',[['GMV^*','Erforderliches Transaktionsvolumen zur Erhaltung des bisherigen Ergebnisses.']]),
   'Die neue Gebühr kann langfristige Vorteile für Teilnahme und Bindung besitzen, aber die gegebene kurzfristige Mengensteigerung reicht für gleichen Gewinn nicht. Diese späteren Vorteile müssten eigenständig begründet werden; höheres Volumen allein beweist sie nicht.'
  ],'Die Bezugsgröße eines Prozentsatzes entscheidet über seine Bedeutung. Eine hohe ausgewiesene Marge auf Nettogebühren ist nicht direkt mit einer Händlermarge auf Bruttowarenumsatz vergleichbar.'),
  'GMV ist keine einheitlich normierte Rechnungslegungsgröße. Retouren, Steuern, Versand und abgebrochene Bestellungen können unterschiedlich erfasst werden. Auch Take Rate kann weitere Dienste enthalten. Für Umsatz nach IFRS 15 zählt insbesondere, ob die Firma die zugesagte bestimmte Leistung vor Übertragung kontrolliert und als Principal liefert oder als Agent deren Bereitstellung arrangiert. Allein Geld einzusammeln oder Plattform genannt zu werden entscheidet die Frage nicht.'
 ]),
 S('networks','18. Netzwerkeffekte sind keine bloßen Skaleneffekte','a b',[
  'Ein Netzwerkeffekt liegt vor, wenn sich der Nutzen für Teilnehmer durch Anzahl, Qualität oder Aktivität anderer relevanter Teilnehmer verändert. Bei einem direkten Netzwerkeffekt können zusätzliche Nutzer derselben Seite den Dienst wertvoller machen, etwa wenn mehr relevante Kontakte erreichbar sind. Bei einem indirekten Netzwerkeffekt erhöhen zusätzliche Teilnehmer einer anderen Seite den Nutzen, etwa mehr passende Anbieter für Käufer.',
  T(['Mechanismus','Was sich verändert','Was damit nicht bewiesen ist'],[['Skaleneffekt','Kosten je Einheit sinken durch größere Produktion oder Verteilung gemeinsamer Kosten.','Kunden müssen das Angebot deshalb nicht stärker bevorzugen.'],['Direkter Netzwerkeffekt','Relevante zusätzliche Teilnehmer derselben Gruppe erhöhen den Nutzen.','Jeder beliebige neue registrierte Nutzer schafft denselben Wert.'],['Indirekter Netzwerkeffekt','Eine Gruppe profitiert von passender Größe oder Qualität einer anderen Gruppe.','Beide Seiten gewinnen automatisch gleich viel.'],['Überlastung oder Qualitätsverlust','Mehr Aktivität kann Wartezeit, Suchkosten, Betrug oder Konkurrenz erhöhen.','Netzwerkeffekte sind nicht immer positiv und unbegrenzt.']],'Wachstum kann mehrere dieser Effekte zugleich auslösen. Die jeweilige Ursache sollte einzeln überprüfbar sein.'),
  'Eine Buchungsplattform braucht sowohl Anbieter als auch Nachfrager. Ein Rabatt für die eine Seite kann die andere Seite anziehen; er verursacht zunächst aber einen echten Aufwand oder entgangenen Erlös. Mehr Anbieter helfen Käufern möglicherweise bei Auswahl und Verfügbarkeit, verstärken zugleich die Konkurrenz unter den Anbietern. Deshalb ist das Vorzeichen für jede Seite einzeln zu bestimmen.',
  'Multi-Homing bedeutet, dass Nutzer mehrere vergleichbare Plattformen gleichzeitig verwenden. Das kann die Bindung und die Möglichkeit dauerhafter Gebührenaufschläge begrenzen. Ein lokaler Vermittlungsmarkt benötigt außerdem relevante Dichte vor Ort: Eine Million Anbieter in einer anderen Region lösen nicht zwingend das aktuelle Problem des Kunden.',
  'Daten können Qualität und Personalisierung verbessern. Ein pauschaler Satz mehr Daten erzeugen immer einen uneinholbaren Vorteil ist dennoch zu stark. Datenrelevanz, abnehmender Zusatznutzen, technische Umsetzbarkeit, erlaubte Nutzung und alternative Datenzugänge beeinflussen den tatsächlichen Vorteil. Hohe Nutzerzahl allein beweist weder einen Netzwerkeffekt noch einen dauerhaften Burggraben.'
 ]),
 S('hybrids','19. Digitale und hybride Modelle anhand ihrer Bausteine analysieren','b',[
  'Unkonventionelle Geschäftsmodelle kombinieren bekannte Tätigkeiten und Zahlungsformen auf neue Weise oder nutzen besondere technologische Möglichkeiten. Digitalisierung kann ein neues Produkt schaffen, Vertriebskosten ändern, Informationen schneller verfügbar machen oder Transaktionen ermöglichen. Nicht jede digitale Oberfläche ist deshalb eine neue Ertragslogik.',
  T(['Hybrider Fall','Getrennt zu untersuchende Bausteine','Mögliche Wechselwirkung'],[['Händler mit Marktplatz und Werbung','Eigener Warenverkauf, Vermittlungsgebühr, Werbeerlös.','Eigene Produkte können mit externen Händlern konkurrieren; Werbung kann Suche finanzieren oder verschlechtern.'],['Geräteanbieter mit Serviceabonnement','Gerätebeitrag, Finanzierung des Geräts, laufender Service, Ersatzteile.','Günstiges Gerät kann späteren Service fördern, aber dessen Kosten und Kündigungen bleiben relevant.'],['Medienangebot mit kostenlosem und bezahltem Zugang','Werbung, zahlende Abonnenten und unterschiedliche Inhaltskosten.','Kostenlose Reichweite kann Kunden gewinnen oder einen bezahlten Zugang ersetzen.'],['Franchisenetz mit eigenen Standorten','Lizenzgebühren, eigene Standortumsätze, zentrale Leistungen.','Eigene Standorte liefern Erfahrung, binden aber Kapital und besitzen andere Margen.']],'Ein Geschäftsbereich kann mehrere Rollen gleichzeitig erfüllen. Sie werden nicht allein nach dem Namen des Konzerns zusammengefasst.'),
  'Cross-Selling kann den Beitrag vorhandener Kunden erhöhen und Akquisitionskosten auf mehrere Produkte verteilen. Es kann aber auch Rabatte, zusätzliche Betreuung oder unerwünschte Komplexität erzeugen. Die behauptete Synergie wird deshalb mit den zusätzlichen Zahlungen gegenüber realistischen getrennten Alternativen begründet.',
  'Ein Wechsel von Verkauf zu Abonnement verändert nicht nur die Erlösetiketten. Zahlungen können später eintreffen, laufende Leistungspflichten zunehmen und kurzfristiger ausgewiesener Umsatz sinken, obwohl der Vertragsbestand wächst. Ob der Wechsel Wert schafft, hängt von Bindung, Gesamtpreis, Kosten, Kapitalbindung und Alternativen ab.'
 ]),
 S('financial-profile','20. Vom Geschäftsmodell zu Abschluss und Finanzierung','a b',[
  T(['Modellmerkmal','Mögliche finanzielle Spur','Zusätzliche Prüfung'],[['Vorproduzierte Waren und später Kundenzahlung','Lager- und Forderungsbindung vor dem Geldzufluss.','Absatzqualität, Vorratsrisiko und Finanzierung des Wachstums.'],['Vorausbezahlte künftige Leistung','Früher Geldzufluss bei verbleibender Leistungspflicht.','Mittelbedarf für spätere Erfüllung und mögliche Rückerstattung.'],['Wiederkehrender Service mit hohen Anfangsausgaben','Akquisition und Einrichtung vor vielen späteren Beiträgen.','Kohortenbindung, Rückflussdauer und Engpässe bei schneller Expansion.'],['Vermietete eigene Anlagen','Hoher anfänglicher Investitionsbedarf und spätere Zuflüsse.','Erhaltung, Restwert, Auslastung und Finanzierungslaufzeit.'],['Rechte- oder Provisionsmodell','Möglicherweise geringe eigene Waren- oder Anlagenbindung.','Entwicklung, Marke, Partnerabhängigkeit und beim Unternehmen verbleibende Risiken.']],'Die Spuren sind Hypothesen zur Prüfung. Ein Modellname ersetzt weder den Abschluss noch seine Anhangangaben.'),
  'Ein hoher Bruttomargenanteil kann aus Nettoumsatzausweis, nicht aus überlegenem absoluten Gewinn stammen. Ein niedrigerer Umsatz bei Wechsel der Rolle vom Eigenhändler zum Vermittler kann teilweise eine andere Darstellung derselben Kundenaktivität widerspiegeln. Deshalb werden wirtschaftliche Transaktionen, Rolle und Ausweis gemeinsam untersucht.',
  'Rückkehrende Kunden reduzieren möglicherweise Nachfragerisiko, garantieren aber keine für hohe Schulden ausreichende Zahlungsstabilität. Variable Nutzung, kündbare Verträge, konzentrierte Kunden oder vorfinanzierte Akquisition können die Stabilität begrenzen. Das verbindet Geschäftsmodellanalyse mit Working Capital, Kapitalallokation und Kapitalstruktur.',
  'Kennzahlen müssen die Kapitalbasis berücksichtigen. Ein Modell mit zwanzig Prozent operativer Marge und sehr hoher Anlagenbindung kann weniger Kapitalrendite erzielen als eines mit fünf Prozent Marge und schnellem Kapitalumschlag. Margen, Umschlag, Reinvestitionen und Risiko gehören deshalb in denselben Vergleich.'
 ]),
 S('evidence','21. Eine Managementgeschichte durch Gegenhypothesen prüfen','a b',[
  X('Das Etikett Plattform erklärt den Emittenten noch nicht','Ein fiktiver Emittent nennt sich eine skalierbare Technologieplattform. Er kauft jedoch die angebotenen Geräte vorab selbst, finanziert Kundenzahlungsziele, garantiert Wartung für fünf Jahre und erzielt den größten Teil seines Erlöses aus Geräteverkauf. Daneben vermittelt er Ersatzteilbestellungen externer Anbieter gegen Gebühr.',[
   'Zuerst werden die Transaktionen getrennt: eigener Gerätehandel, selbst versprochene Wartung und Vermittlung externer Ersatzteile. Die digitale Bestelloberfläche verbindet sie, macht ihre Risiken aber nicht identisch.',
   'Für den eigenen Geräteverkauf sind Beschaffung, Lager, Forderungen, Garantie und Rücknahme wichtig. Für Wartung zählen Kosten je installierter Einheit und tatsächliche Ausfälle. Für Vermittlung zählen Transaktionswert, Gebühr, Teilnehmerbindung und vereinbarte Verantwortung.',
   'Danach werden Daten gesucht, die die Skalierungsbehauptung prüfen: wiederkehrende Bruttobeiträge, Wartungskosten alter Kohorten, Lageralter, Zahlungseingänge, Anteil eigener Waren und externe Wiederkäufe. Ein steigender Gesamtumsatz kann dabei weiterhin hohen zusätzlichen Finanzierungsbedarf erzeugen.'
  ],'Eine belastbare Beschreibung benennt die tatsächlichen Tätigkeiten und Ansprüche. Sie übernimmt weder das attraktivste Etikett noch automatisch das skeptischste Gegenetikett.'),
  'Wichtige Informationen können in Segmentangaben, Erlösaufgliederung, Verpflichtungen, Konzentrationsrisiken, Kundenkennzahlen und Zahlungsrechnung liegen. Begriffsdefinitionen und Veränderungen der Kennzahlenbasis gehören dazu. Ein plötzlich steigender Bindungswert nach einer Methodenänderung muss vor einem wirtschaftlichen Urteil auf vergleichbare Basis gebracht werden.',
  'Gegenhypothesen müssen ebenfalls prüfbar sein. Hohe Kundenakquisition kann auf attraktives Wachstum oder auf schwache Bindung hinweisen. Höhere Vorräte können geplante Verfügbarkeit oder Absatzprobleme bedeuten. Die Antwort folgt aus Kohorten, Bestellungen, Preisen, Alterung und tatsächlichen Zahlungen, nicht aus einem einzelnen Verhältnis.'
 ]),
 S('decision','22. Eine knappe, aber vollständige Geschäftsmodellbeschreibung formulieren','a b',[
  T(['Baustein','Frage für die abschließende Analyse'],[['Kundennutzen','Für wen wird welches Problem gegenüber welcher Alternative gelöst?'],['Tätigkeiten und Zugang','Welche Ressourcen, Partner und Vertriebskanäle liefern die Leistung?'],['Monetarisierung','Wer zahlt wofür, in welcher Einheit, zu welchem Zeitpunkt und unter welchen Bedingungen?'],['Wirtschaftlichkeit','Welche Beiträge bleiben nach Akquisition, laufender Erfüllung und gemeinsamen Kosten?'],['Kapital und Risiko','Was muss vorfinanziert werden, was bleibt gebunden und wer trägt die entscheidenden Unsicherheiten?'],['Beleg und Grenze','Welche beobachtbaren Daten stützen die Erklärung, und welche Entwicklung würde sie widerlegen?']],'Eine gute Zusammenfassung ist kurz, weil ihre wirtschaftlichen Beziehungen zuvor geklärt wurden, nicht weil Kosten und Einschränkungen fehlen.'),
  'Für CFA-Level-I-Fragen erkennt man zuerst die Tätigkeit und den Zahlungsmechanismus. Abonnement ist keine Garantie für Bindung, Freemium keine Garantie für profitable Konversion, Franchising kein eigener vollständiger Filialumsatz und Plattformvolumen kein automatisch gleich hoher eigener Erlös. Kombinationen werden nach ihren einzelnen Merkmalen beschrieben.',
  'Die Modelle dieses Kapitels sind Analysewerkzeuge. Ihre Zahlenfälle halten bestimmte Größen bewusst konstant, damit eine Ursache sichtbar wird. In einer echten Prognose werden plausible gemeinsame Szenarien verwendet: Preis beeinflusst möglicherweise Bindung und Menge, Wachstum beeinflusst Kosten und Kapitalbedarf, und Finanzierung beeinflusst den möglichen Entwicklungspfad.'
 ])
],related:[
 {unit:'industry',section:'five-forces',label:'Geschäftsmodell innerhalb von Konkurrenz und Marktgrenzen prüfen'},
 {unit:'market-structures',section:'scale',label:'Skaleneffekte und Kapazität von Netzwerkeffekten unterscheiden'},
 {unit:'forecasting',section:'sales-drivers',label:'Umsatz über Preis, Menge und Mix prognostizieren'},
 {unit:'forecasting',section:'cost-drivers',label:'Kosten und ihre wirtschaftlichen Treiber modellieren'},
 {unit:'income-statement',section:'revenue-estimates',label:'Umsatz nach Leistung, Kontrolle und wirtschaftlicher Rolle'},
 {unit:'working-capital',section:'cash-amount',label:'Wachstum und tatsächlich benötigtes Betriebskapital'},
 {unit:'capital-allocation',section:'incremental',label:'Zusätzliche Zahlungen und Kannibalisierung richtig vergleichen'},
 {unit:'capital-structure',section:'drivers',label:'Geschäftsrisiko und tragfähige Finanzierung verbinden'},
 {unit:'governance',section:'agency-costs',label:'Anreize und Kontrolle in arbeitsteiligen Geschäftsmodellen'}
],sources:[
 {title:'CFA Institute: 2027 Level I Topic Outlines, Business Models',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=10'},
 {title:'CFA Institute: Business Models, öffentliche Einführung 2026; Lernziele mit Outline 2027 abgeglichen',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/business-models'},
 {title:'OpenStax: Entrepreneurship, 11.2 Designing the Business Model',url:'https://openstax.org/books/entrepreneurship/pages/11-2-designing-the-business-model'},
 {title:'Harvard Business School Online: Geschäftsmodelltypen und Nutzen',url:'https://online.hbs.edu/blog/post/types-of-business-models'},
 {title:'Harvard Business School Online: direkte und indirekte Netzwerkeffekte',url:'https://online.hbs.edu/blog/post/what-are-network-effects'},
 {title:'Gupta, Lehmann und Stuart: Valuing Customers, Originalarbeit; eigene Fälle mit ausdrücklich anderer Zahlungskonvention',url:'https://business.columbia.edu/sites/default/files-efs/pubfiles/534/Valuing_Customers--JMR_2003.pdf'},
 {title:'Stripe: Net Revenue Retention und Gross Revenue Retention; Kennzahlendefinitionen',url:'https://stripe.com/resources/more/net-revenue-retention-vs-gross-revenue-retention'},
 {title:'IFRS Foundation: Principal versus Agent, IFRIC Update April 2022',url:'https://www.ifrs.org/news-and-events/updates/ifric/2022/ifric-update-april-2022/'}
],review:{status:'draft',date:'2026-09-28',note:'Eigene vergleichende Geschäftsmodell-, Beitrags-, Bindungs- und Kapitalfälle. Zusätzliche Kennzahlenherleitungen sind Vertiefungen der beschreibenden Lernziele; Gesamtaudit und fachliche Freigabe bleiben offen.'}};
