const {F,T,X,S,G}=require('../author.cjs');
const retention=(r,b)=>100*r*(1-b)/(.1-b*r);
const gordon=(k,g)=>2*(1+g)/(k-g);
module.exports={id:'dcf-equity',intro:[
 'Eine Aktie ist ein Anspruch auf wirtschaftliche Vorteile in der Zukunft. Wie viel dafür heute angemessen ist, hängt davon ab, welche Zahlungen zum Anspruch gehören, wann sie entstehen, wie unsicher sie sind und welches Kapital zur Erzeugung dieser Zahlungen gebunden werden muss. Wachstum verbindet deshalb Gewinn, Investition, Ausschüttung und Risiko; es ist kein kostenloser Zuschlag im Nenner.',
 'Dieses Kapitel behandelt alle vier Lernziele des DCF- und Wachstumsmoduls für CFA Level I 2027. Es entwickelt Dividenden-, FCFE-, FCFF- und Residualgewinnmodelle, leitet konstantes Wachstum her, baut mehrstufige Fälle auf und bewertet Vorzugsaktien mit passenden Vertragsannahmen. Die zusätzlichen algebraischen Herleitungen dienen dem Verständnis; öffentlich zugängliche Level-II-Quellen sind als ergänzende Vertiefungen gekennzeichnet.'
],sections:[
 S('scope','1. Zuerst Anspruch, Zeit und Einheit festlegen','a',[
  'Im direkten Aktienmodell werden Zahlungen an die betrachteten Eigenkapitalgeber mit deren erforderlicher Rendite verbunden. Im operativen Unternehmensmodell werden Zahlungen vor ihrer Verteilung an Fremd- und Eigenkapitalgeber bewertet. Erst danach führt eine Anspruchsbrücke zum Stammkapital. Eine niedrige Renditeforderung ist kein frei wählbarer Weg, den Aktienwert zu vergrößern.',
  'Wir schreiben im Folgenden Werte, Gewinne und Cashflows als Gesamtbeträge, sofern ein Beispiel nicht ausdrücklich Beträge je Aktie verwendet. Die Division durch die passende ausstehende Aktienzahl erfolgt erst nach Abgrenzung des Anspruchs. Eine zeitgewichtete EPS-Aktienzahl ist dafür nicht automatisch richtig. Vorzugskapital, nicht beherrschende Anteile, separate Kasse und Verwässerungsrechte müssen im jeweiligen Modell klar behandelt werden.',
  T(['Modell','Bewerteter Input','Passender Diskontsatz','Ergebnis'],[['DDM','Erwartete Dividenden an betrachtete Stammaktionäre.','Eigenkapitalkosten.','Direkter Stammaktionärswert.'],['FCFE','Nach Investition und Fremdfinanzierung verbleibende Mittel für das betrachtete Eigenkapital.','Eigenkapitalkosten.','Direkter Eigenkapitalwert.'],['FCFF','Operativer freier Cashflow vor Finanzierungsverteilung.','Passender WACC.','Operativer Wert sämtlicher dazugehöriger Kapitalgeberansprüche.'],['Residual Income','Gewinn nach kalkulatorischer Belastung des Anfangsbuchwerts mit Eigenkapitalkosten.','Eigenkapitalkosten.','Buchwert plus Barwert künftiger Residualgewinne.']],'Keine Zeile erlaubt, unterschiedliche Anspruchsebenen beliebig zu mischen.')
 ]),
 S('one-period','2. Der Einperiodenwert und die wirtschaftliche Rekursion','a b',[
  F('V_0=\\frac{D_1+V_1}{1+k_e},\\qquad V_t=\\frac{D_{t+1}+V_{t+1}}{1+k_e}','Der heutige Anspruch erhält die nächste Dividende und besitzt danach einen verbleibenden Wert. Beide Beträge werden auf denselben vorherigen Zeitpunkt abgezinst.',[['V_t','Geschätzter Eigenkapitalwert nach der Zahlung zum Zeitpunkt t.'],['D_{t+1}','Erwartete Ausschüttung am Ende der folgenden Jahresperiode.'],['k_e','Für diesen Eigenkapitalanspruch geeignete jährliche Renditeforderung.'],['t','Jahresindex; null bezeichnet den heutigen Bewertungsstichtag.']]),
  X('Eine Auszahlung und ein verbleibender Anspruch','Eine Aktie soll in einem Jahr vier ausschütten und unmittelbar danach einen Wert von 106 besitzen. Die Eigenkapitalkosten betragen zehn Prozent.',[
   F('V_0=\\frac{4+106}{1{,}10}=100','Die gesamte wirtschaftliche Leistung am Ende des Jahres wird auf heute bezogen.',[['V_0','Heutiger Wert je Aktie im vorgegebenen Modell.']]),
   'Vier allein hätten einen Barwert von etwa 3,64. Der übrige Wert steckt im danach verbleibenden Anspruch. Dessen 106 darf aber nicht ohne Begründung als heutiger Preis eingesetzt werden: Er muss zu den späteren Erträgen und derselben Bewertungsbasis passen.'
  ],'Eine geringe aktuelle Dividende sagt allein wenig über den gesamten Aktienwert.'),
  'Die Rekursion kann wiederholt werden. Jede Einsetzung ersetzt einen zukünftigen Aktienwert durch eine weitere Dividende und einen noch späteren Restanspruch. Ein tatsächlicher erwarteter Verkaufspreis kann in einer Anlageprognose vorkommen; für die fundamentale Herleitung wird der verbleibende Wert selbst aus späteren Vorteilen begründet.'
 ]),
 S('horizon','3. Endliche Prognose und unendlicher Zahlungsstrom','a b c',[
  F('V_0=\\sum_{t=1}^{T}\\frac{D_t}{(1+k_e)^t}+\\frac{V_T}{(1+k_e)^T}','Eine Detailphase erfasst alle Dividenden bis einschließlich T. Der nach der letzten erfassten Dividende verbleibende Anspruch wird separat auf heute abgezinst.',[['V_0','Heutiger Eigenkapitalwert.'],['D_t','Dividende am Ende von Jahr t.'],['T','Letztes Jahr der expliziten Prognose.'],['V_T','Wert am Ende von T nach der Zahlung D_T; enthält nur Vorteile danach.'],['k_e','Hier über alle Jahre konstante jährliche Eigenkapitalkosten.']]),
  F('\\lim_{T\\to\\infty}\\frac{V_T}{(1+k_e)^T}=0\\quad\\Longrightarrow\\quad V_0=\\sum_{t=1}^{\\infty}\\frac{D_t}{(1+k_e)^t}','Die Transversalitätsbedingung verhindert einen unbegründeten zusätzlichen Restwert in unendlich ferner Zukunft. Erst mit dieser Grenzbedingung lässt sich die Bewertung allein durch den unendlichen Dividendenstrom ausdrücken.',[['V_T','Verbleibender Wert zum immer weiter entfernten Termin T.'],['D_t','Erwartete künftige Dividende.'],['k_e','Konstanter Diskontsatz unter den Modellannahmen.'],['T,t','Horizont beziehungsweise Zahlungsindex.'],['V_0','Heutiger Modellwert.']]),
  'Eine Aktie kann über Jahre keine Dividende zahlen und trotzdem einen positiven Wert besitzen, wenn später Ausschüttungen, Rückkäufe, eine Übernahme oder eine Liquidation wirtschaftliche Vorteile zuführen. Werden hingegen alle Eigentümerleistungen für immer ausgeschlossen, darf ein immer weiter wachsender Wiederverkaufspreis nicht ohne weitere Grundlage beliebig Wert schaffen. Rückkäufe erfordern bei einem Modell je verbleibender Aktie eine konsistente Fortschreibung von Bestand und Ausschüttungsbasis.'
 ]),
 S('ddm','4. Wann tatsächliche Dividenden ein guter Ausgangspunkt sind','a c',[
  'Das Dividend Discount Model beginnt bei erwarteten Zahlungen an Aktionäre. Es passt besonders gut, wenn eine nachvollziehbare Ausschüttungspolitik die wirtschaftliche Leistungsfähigkeit abbildet und der betrachtete Minderheitsanleger diese Politik nicht selbst ändern kann. Gewinn, verfügbare Liquidität und Dividende sind trotzdem verschiedene Größen.',
  'Eine geglättete Dividende kann zeitweise höher oder niedriger als der freie Eigenkapitalcashflow liegen. Das ist nicht automatisch ein Fehler: vorhandene Kasse, Finanzierung und bewusste Ausschüttungspolitik beeinflussen die Zahlung. Ein langfristiges Modell muss aber erklären, wie diese Politik finanziert wird. Dauerhafte Ausschüttungen über den verfügbaren Ressourcen lassen sich nicht allein durch eine unveränderte historische Dividende rechtfertigen.',
  X('Gleiche verfügbare Mittel, verschiedene Zahlungstermine','Zehn Einheiten könnten am Ende von Jahr eins ausgeschüttet werden. Alternativ bleiben sie für genau ein weiteres Jahr im Unternehmen und werden danach vollständig ausgezahlt. Für diese isolierten Beträge gelten zehn Prozent jährliche Renditeforderung.',[
   F('PV_A=10/1{,}1=9{,}0909,\\qquad PV_B=11/1{,}1^2=9{,}0909,\\qquad PV_C=10/1{,}1^2=8{,}2645','Wenn der zurückbehaltene Betrag im zweiten Jahr zehn Prozent verdient, bleibt sein heutiger Wert gleich. Ohne Ertrag verringert die Verzögerung den Barwert.',[['PV_A','Barwert sofortiger Zahlung am Ende von Jahr eins.'],['PV_B','Barwert der späteren Zahlung einschließlich angemessenen Ertrags.'],['PV_C','Barwert der verzögerten unverzinsten Zahlung.']]),
   'Die Modellalternative verändert nur Verwendung und Zeitpunkt dieser zehn. Sie lässt die übrige Geschäftsentwicklung gleich. Ein FCFE-Modell, das frei verfügbare Mittel zu angemessener Verwendung bewertet, ist für den Minderheitsanleger nicht automatisch identisch mit tatsächlich durchsetzbaren Ausschüttungen einer ineffizienten Unternehmensleitung.'
  ],'Die Verwendung zurückbehaltener Mittel verbindet Zahlungsfähigkeit und tatsächlichen Eigentümernutzen.')
 ]),
 S('fcff','5. Vom operativen Gewinn zum FCFF','a',[
  F('FCFF_t=EBIT_t(1-\\tau)+NCC_t-Capex_t-\\Delta WC_t','Der operative Nachsteuergewinn wird um nicht zahlungswirksame Aufwendungen bereinigt. Danach werden Anlagen- und zusätzliche operative Betriebskapitalinvestitionen abgezogen.',[['FCFF_t','Freier Cashflow vor Finanzierungsverteilung in Periode t.'],['EBIT_t','Bereinigter operativer Gewinn vor Zinsen und Steuern.'],['\\tau','Hier nutzbarer proportionaler Unternehmenssteuersatz.'],['NCC_t','Hier nicht zahlungswirksame Aufwendungen; im einfachen Fall Abschreibung.'],['Capex_t','Auszahlungen für operative langfristige Investitionen.'],['\\Delta WC_t','Zunahme des nicht zahlungsmittelbezogenen operativen Working Capital; positiv bindet Liquidität.'],['t','Periodenindex.']]),
  'Die einfache Formel setzt voraus, dass EBIT und Steuern sachgerecht abgegrenzt sind. Einmalige Veräußerungen, andere nicht zahlungswirksame Erträge, nicht verfügbare Steuervorteile oder zusätzliche Finanzierungsansprüche benötigen eigene Anpassungen. Abschreibung ist kein Geldzufluss: Sie wird zurückgerechnet, weil sie den Gewinn ohne entsprechende aktuelle Auszahlung vermindert hat.',
  X('Ein Gewinn muss erst in verfügbare Mittel überführt werden','EBIT 120, Zinsaufwand 20, Steuersatz 25 Prozent, Abschreibung zehn, Anlagenzahlungen vierzig und Betriebskapitalzunahme fünfzehn. Alle Beträge gehören zur gleichen Periode; außer den genannten Posten gibt es keine Anpassungen.',[
   F('NI=(120-20)(1-0{,}25)=75,\\qquad FCFF=120(1-0{,}25)+10-40-15=45','Operativer Nachsteuergewinn neunzig ist nicht derselbe Betrag wie der nach Zinsen verbleibende Gewinn fünfundsiebzig.',[['NI','Den betrachteten Stammaktionären zurechenbarer Gewinn.'],['FCFF','Operativer freier Cashflow der Periode.']]),
   F('FCFF=NI+NCC+Int(1-\\tau)-Capex-\\Delta WC=75+10+15-40-15=45','Aus dem Gewinn nach Zinsen wird der nachsteuerliche Zinsaufwand zurückgerechnet, damit der Cashflow wieder vor Finanzierungsverteilung liegt.',[['NI','Gewinn nach Zinsen und Steuern.'],['NCC','Nicht zahlungswirksame Aufwendungen.'],['Int','Zinsaufwand zwanzig.'],['\\tau','Nutzbarer Steuersatz 25 Prozent.'],['Capex,\\Delta WC','Anlagenzahlung und Betriebskapitalinvestition.'],['FCFF','Cashflow für die Kapitalgeber vor Verteilung.']])
  ],'Alternative Herleitungen ergeben bei identischen Abgrenzungen denselben FCFF.')
 ]),
 S('fcfe','6. Finanzierung führt vom FCFF zum FCFE','a',[
  F('FCFE_t=FCFF_t-Int_t(1-\\tau)+NB_t=NI_t+NCC_t-Capex_t-\\Delta WC_t+NB_t','Der Eigenkapitalcashflow berücksichtigt die Zinswirkung sowie Aufnahme und Rückzahlung von Schulden. Neue Kredite sind Finanzierung, kein operativer Ertrag.',[['FCFE_t','Für das betrachtete Eigenkapital verbleibender Cashflow.'],['FCFF_t','Operativer freier Cashflow vor Finanzierungsverteilung.'],['Int_t','Periodischer Zinsaufwand im einfachen Steuermodell.'],['\\tau','Tatsächlich nutzbarer Steuersatz.'],['NB_t','Net borrowing: neue Schuldenaufnahme minus Tilgung.'],['NI_t,NCC_t','Gewinn nach Zinsen und nicht zahlungswirksame Aufwendungen.'],['Capex_t,\\Delta WC_t','Anlagenzahlungen und zusätzliche operative Kapitalbindung.'],['t','Periodenindex.']]),
  X('Fortsetzung der Gewinn-Cashflow-Brücke','Im vorigen Fall beträgt FCFF 45. Die Gesellschaft nimmt zwölf neue Schulden auf und tilgt sieben; Zinsen zwanzig und Steuersatz 25 Prozent bleiben unverändert.',[
   F('NB=12-7=5,\\qquad FCFE=45-20(1-0{,}25)+5=35','Nach dem nachsteuerlichen Zinsabzug stehen dreißig zur Verfügung; die zusätzliche Nettokreditaufnahme erhöht den Betrag auf fünfunddreißig.',[['NB','Nettokreditaufnahme.'],['FCFE','Freier Eigenkapitalcashflow.']]),
   'Ein höheres FCFE durch eine einmalige Kreditaufnahme beweist keine dauerhaft höhere operative Ertragskraft. Umgekehrt kann eine freiwillige größere Tilgung FCFE vorübergehend negativ machen, obwohl das Geschäft positive freie Mittel erwirtschaftet.'
  ],'FCFE darf nicht anschließend noch einmal um denselben Zins oder dieselbe Tilgung vermindert werden.'),
  'Die direkte FCFE-Bewertung enthält bereits die modellierten Finanzierungswirkungen. Wird zunächst FCFF bewertet, werden passende nicht operative Vermögenswerte hinzugefügt und Schulden sowie weitere fremde Ansprüche abgegrenzt. Die ausführliche Wertbrücke steht im Kapitel Preis und fundamentaler Wert.'
 ]),
 S('consistent-debt','7. Warum direkte und indirekte Bewertung übereinstimmen können','a b',[
  F('V_{op}=\\sum_{t=1}^{\\infty}\\frac{FCFF_t}{(1+WACC)^t},\\qquad E=\\sum_{t=1}^{\\infty}\\frac{FCFE_t}{(1+k_e)^t}','Die beiden Reihen betrachten unterschiedliche Anspruchsebenen. Bei vollständig konsistenten Zahlungs-, Finanzierungs- und Risikoannahmen beschreiben sie dieselbe wirtschaftliche Verteilung.',[['V_{op}','Wert des in FCFF enthaltenen operativen Geschäfts.'],['E','Direkter Wert des betrachteten Eigenkapitals.'],['FCFF_t,FCFE_t','Passend abgegrenzte erwartete periodische Cashflows.'],['WACC','Passende gewichtete Kapitalkosten im hier konstanten Modell.'],['k_e','Konstante Eigenkapitalkosten.'],['t','Jahresindex.']]),
  X('Ein abgestimmter ewiger Fall ohne Steuern','FCFF beträgt dauerhaft zehn jährlich. Es gibt nur Schulden und Stammkapital, keine zusätzliche Kasse oder sonstigen Ansprüche. Schulden zahlen dauerhaft zwei Zinsen jährlich, haben Marktwert vierzig und kosten fünf Prozent. Operativer Wert hundert und WACC zehn Prozent sind konsistente Ausgangsannahmen.',[
   F('V_{op}=10/0{,}10=100,\\quad D=2/0{,}05=40,\\quad E=100-40=60','Die Schuld wird mit ihrem eigenen Cashflow und Satz bewertet. Ihr Marktwert wird vom gesamten operativen Anspruch abgegrenzt.',[['V_{op},D,E','Operativer, Fremd- und Eigenkapitalwert.']]),
   F('FCFE=10-2=8,\\quad k_e=8/60=13{,}3333\\%,\\quad E=8/k_e=60','Die Eigenkapitalzahlung ist riskanter als der Schuldanspruch und wird im abgestimmten Modell mit ihrer eigenen Renditeforderung bewertet.',[['FCFE','Ewige Eigenkapitalzahlung ohne zusätzliche Kreditaufnahme.'],['k_e','Mit Zahlung und Wert konsistente Eigenkapitalkosten.'],['E','Direkter Eigenkapitalwert.']]),
   F('WACC=\\frac{60}{100}\\frac{8}{60}+\\frac{40}{100}\\frac{2}{40}=10\\%','Die Marktwertgewichte bringen die Kosten der Teilansprüche zum Gesamtsatz zusammen.',[['WACC','Gewichtete Kosten im ausdrücklich steuerfreien Zwei-Anspruchs-Modell.']]),
   'Würde der Analyst FCFE acht mit zehn Prozent kapitalisieren, erhielte er achtzig. Er verwendete dabei den WACC für einen anderen Anspruch. Würde er von den korrekt direkt berechneten sechzig nochmals vierzig Schulden abziehen, zählte er die Finanzierung doppelt.'
  ],'Gleichheit folgt aus abgestimmten Annahmen; sie ist kein Grund, Diskontsätze beliebig auszutauschen.'),
  'Bei veränderter Verschuldung können sich Eigenkapitalrisiko, Zinsen, Steuervorteile und WACC über die Jahre ändern. Ein konstanter Satz bei zugleich unpassender Finanzierungsplanung erzwingt keine richtige Gleichheit. Die erweiterte Bewertung bestimmter Steuervorteile gehört zu weiterführenden Kapitalstrukturmodellen.'
 ]),
 S('geometric','8. Das Gordon-Modell aus der Zahlungsreihe herleiten','b c',[
  F('CF_t=CF_1(1+g)^{t-1},\\quad q=\\frac{1+g}{1+k},\\quad V_0=\\frac{CF_1}{1+k}\\sum_{j=0}^{\\infty}q^j=\\frac{CF_1}{k-g}','Bei dauerhaft konstantem Wachstum bilden die diskontierten Zahlungen eine geometrische Reihe. Ihre Summe ist nur bei einem absoluten Reihenquotienten kleiner als eins endlich.',[['CF_t','Erwartete Zahlung am Ende von Jahr t; Anspruch unverändert.'],['CF_1','Erste Zahlung nach dem Bewertungsstichtag.'],['g','Konstante jährliche Zahlungswachstumsrate.'],['k','Passender konstanter jährlicher Diskontsatz.'],['q','Verhältnis aufeinanderfolgender abgezinster Zahlungen.'],['j','Summationsindex, beginnend bei null.'],['t','Zahlungsindex ab eins.'],['V_0','Heutiger Barwert.']]),
  F('g>-1,\\quad k>-1,\\quad k>g\\quad\\Longrightarrow\\quad 0<q<1','Für die hier betrachteten nicht vorzeichenwechselnden Wachstumszahlungen gilt als ökonomisch übliche Konvergenzbedingung: Der Diskontsatz liegt über dem Wachstum.',[['g,k','Dezimal angegebene Wachstumsrate und Diskontsatz.'],['q','Quotient der geometrischen Barwertreihe.']]),
  'Wenn Wachstum mindestens so groß wie der Diskontsatz ist, werden die abgezinsten Zahlungen dieser unendlichen Reihe nicht ausreichend kleiner. Ein negativer rechnerischer Nenner liefert dann keinen sinnvollen negativen Wert einer positiven ewigen Dividendenreihe. Man muss das Zahlungsmodell ändern. Eine begrenzte Hochwachstumsphase darf dagegen ein Wachstum oberhalb des Diskontsatzes besitzen, weil nur endlich viele Zahlungen einzeln bewertet werden.',
  'Für Dividenden oder FCFE ist k der Eigenkapitalsatz; für einen passenden FCFF ist k der WACC. Die algebraische Form ist gleich, die wirtschaftliche Bedeutung der Zahlung und des resultierenden Werts bleibt verschieden.'
 ]),
 S('dividend-timing','9. Die nächste Dividende steht im Zähler','b',[
  X('Zwei ähnlich aussehende Dividenden sind nicht austauschbar','Die zuletzt gezahlte Jahresdividende war zwei je Aktie. Ab der nächsten Zahlung wachsen die Dividenden konstant um vier Prozent; Eigenkapitalkosten zehn Prozent.',[
   F('D_1=D_0(1+g)=2(1{,}04)=2{,}08,\\quad V_0=\\frac{2{,}08}{0{,}10-0{,}04}=34{,}6667','Die Zahlung zwei gehört zur Vergangenheit; bewertet wird die nächste erwartete Zahlung 2,08.',[['D_0,D_1','Zuletzt gezahlte und nächste erwartete Dividende je Aktie.'],['g','Jährliches Wachstum vier Prozent.'],['V_0','Heutiger Wert je Aktie.']]),
   'Zwei durch sechs Prozent ergibt 33,33 und lässt die erste Wachstumsstufe weg. Wenn die Aufgabenstellung hingegen bereits die nächste Dividende 2,08 nennt, darf sie nicht erneut mit 1,04 multipliziert werden.'
  ],'Zuerst den Zeitpunkt der angegebenen Dividende markieren, dann die Formel einsetzen.'),
  'Bei einer erwarteten negativen Wachstumsrate bleibt das Modell unter passenden Annahmen möglich. Eine nächste Dividende zwei, Wachstum minus zwei Prozent und Renditeforderung acht Prozent ergeben einen Wert zwanzig. Die Zahlungen sinken, sind aber weiterhin positiv. Das ist etwas anderes als negative Cashflows, die eine Finanzierung erfordern.'
 ]),
 S('implied','10. Renditeforderung und Wachstum aus dem Preis ableiten','b c',[
  F('k_e=\\frac{D_1}{P_0}+g,\\qquad g=k_e-\\frac{D_1}{P_0}','Wenn heutiger Preis und Modellwert gleichgesetzt werden, lässt sich das konstante Modell umstellen. Die Dividendengröße ist hier die bereits festgelegte nächste Zahlung.',[['k_e','Unter dem Modell mit dem Preis konsistente Eigenkapitalrenditeforderung.'],['D_1','Nächste erwartete Dividende je Aktie.'],['P_0','Beobachteter heutiger Preis je Aktie.'],['g','Im Modell impliziertes konstantes Wachstum.']]),
  F('g=\\frac{k_eP_0-D_0}{P_0+D_0}','Wenn die zuletzt gezahlte Dividende statt der nächsten bekannt ist, hängt die nächste Zahlung selbst vom gesuchten Wachstum ab. Diese Umstellung berücksichtigt das.',[['g','Impliziertes dauerhaftes Dividendenwachstum.'],['k_e','Vorgegebene Eigenkapitalkosten.'],['P_0','Aktueller Preis.'],['D_0','Zuletzt gezahlte Dividende auf derselben Aktienbasis.']]),
  X('Eine Markterwartung aus zwei unterschiedlichen Eingaben rekonstruieren','Preis fünfzig, Eigenkapitalkosten zehn Prozent. Zunächst wird eine nächste Dividende zwei angenommen; alternativ wird zwei als zuletzt gezahlte Dividende genannt.',[
   F('g_A=0{,}10-2/50=6\\%,\\qquad g_B=\\frac{0{,}10\\cdot50-2}{50+2}=5{,}7692\\%','Die geringfügig verschiedenen Resultate stammen aus unterschiedlichen Zeitangaben, nicht aus einer Rundungsabweichung.',[['g_A','Impliziertes Wachstum bei festgelegtem D_1 gleich zwei.'],['g_B','Impliziertes Wachstum bei D_0 gleich zwei.']]),
   'Ein impliziertes Wachstum ist eine Interpretation unter dem gewählten Modell. Es misst nicht unmittelbar eine unabhängig beobachtete Marktprognose. Ist die Renditeforderung falsch oder das konstante Modell ungeeignet, verliert auch die Rückrechnung an Aussagekraft.'
  ],'Rückwärtsbewertung macht eine Preisannahme sichtbar, beweist sie aber nicht.')
 ]),
 S('retention','11. Gewinneinbehaltung finanziert Wachstum','b c',[
  'Die Einbehaltungsquote heißt auf Englisch Retention Ratio. Ihr Gegenstück ist der ausgeschüttete Gewinnanteil; der englische Begriff für diese Ausschüttungsquote ist Payout Ratio. Beide Größen werden auf denselben Gewinn und dieselbe Periode bezogen.',
  'Zur Herleitung verwenden wir eine saubere vereinfachte Eigenkapitalfortschreibung: keine neuen Aktien, keine Rückkäufe, keine erfolgsneutralen Buchwertänderungen; Gewinne und Dividenden gehören zum selben Stammkapital. Die Rendite auf das Anfangsbuchkapital bleibt konstant. Die gesamten einbehaltenen Gewinne erhöhen das im Folgejahr gleichermaßen produktive Kapital.',
  F('NI_t=\\rho B_{t-1},\\quad D_t=(1-b)NI_t,\\quad B_t=B_{t-1}+bNI_t=B_{t-1}(1+b\\rho),\\quad g=b\\rho','Einbehaltung b legt fest, welcher Gewinnanteil zusätzlich im Unternehmen verbleibt. Bei konstanter Kapitalrendite wachsen Buchkapital, Gewinn und Dividende danach mit derselben Rate.',[['NI_t','Gewinn der Periode t.'],['\\rho','Konstantes ROE auf den Buchwert am Periodenanfang.'],['B_{t-1},B_t','Stammaktionärsbuchwert vor und nach der Periode.'],['D_t','Periodendividende.'],['b','Retention Ratio: einbehaltener Anteil des Gewinns; Ausschüttungsquote eins minus b.'],['g','Unter diesen Voraussetzungen nachhaltige jährliche Wachstumsrate.'],['t','Jahresindex.']]),
  X('Sechs Prozent Wachstum entstehen aus zwei anderen Größen','Anfangsbuchwert hundert, ROE fünfzehn Prozent und Einbehaltung vierzig Prozent; alle Annahmen bleiben zunächst gleich.',[
   T(['Jahr','Anfangsbuchwert','Gewinn','Dividende','Einbehaltung','Endbuchwert'],[['1','100,00','15,00','9,00','6,00','106,00'],['2','106,00','15,90','9,54','6,36','112,36']],'Beträge sind Gesamtbeträge in derselben Geldeinheit; keine Veränderung der Aktienzahl.'),
   F('g=0{,}40\\cdot0{,}15=6\\%,\\quad 15{,}90/15-1=6\\%,\\quad9{,}54/9-1=6\\%','Mehr Kapital produziert bei unverändertem ROE proportional mehr Gewinn; die feste Ausschüttungsquote überträgt das Wachstum auf Dividenden.',[['g','Nachhaltiges Wachstum im ausdrücklich konstanten Modell.']])
  ],'Einbehaltung vierzig Prozent ist nicht Wachstum vierzig Prozent.'),
  'Historisches ROE ist keine Garantie gleicher Erträge auf neue Investitionen. Änderungen von Margen, Hebel, Aktienzahl oder Rechnungslegung können die einfache Beziehung verändern. Bei vorgegebenem Wachstum und langfristigem ROE folgt die benötigte Einbehaltung durch Division; eine resultierende Quote über hundert Prozent zeigt zusätzlichen Finanzierungsbedarf oder unvereinbare Annahmen.'
 ]),
 S('growth-value','12. Wann mehr Wachstum den Wert verändert','b c',[
  'Present Value of Growth Opportunities, kurz PVGO, bezeichnet hier den zusätzlichen Wert künftiger Investitionsgelegenheiten gegenüber dem ausdrücklich definierten Vergleich ohne weitere Investitionen. Die Zerlegung hilft, vorhandene Erträge und den Nutzen weiterer Kapitalbindung auseinanderzuhalten.',
  F('V_0=\\frac{\\rho B_0(1-b)}{k_e-b\\rho},\\qquad \\frac{\\partial V_0}{\\partial b}=\\frac{B_0\\rho(\\rho-k_e)}{(k_e-b\\rho)^2}','Mehr Einbehaltung reduziert die nächste Ausschüttung und erhöht das spätere Wachstum. Im konstanten Modell hängt die Richtung des Nettoeffekts davon ab, ob die Kapitalrendite die Eigenkapitalkosten übersteigt.',[['V_0','Eigenkapitalwert im Modell mit konstantem ROE und Einbehaltung.'],['B_0','Anfangsbuchwert.'],['\\rho','ROE auf Anfangsbuchkapital.'],['b','Einbehaltener Gewinnanteil.'],['k_e','Eigenkapitalkosten, hier größer als b mal ROE.'],['\\partial V_0/\\partial b','Wertänderung bei einer kleinen Änderung der Einbehaltungsquote, andere Größen unverändert.']]),
  X('Dieselbe Einbehaltung wirkt bei verschiedenen Kapitalrenditen anders','Anfangsbuchwert hundert und Eigenkapitalkosten zehn Prozent. Für jedes ROE werden keine Einbehaltung und vierzig Prozent Einbehaltung bei sonst identischen konstanten Annahmen verglichen.',[
   T(['Konstantes ROE','Wert bei b = 0','Wachstum bei b = 40 %','Nächste Dividende bei b = 40 %','Wert bei b = 40 %'],[['6 %','60,00','2,4 %','3,60','47,3684'],['10 %','100,00','4,0 %','6,00','100,00'],['15 %','150,00','6,0 %','9,00','225,00']],'Die Werte vergleichen jeweils dasselbe Ausgangskapital und dieselbe Renditeforderung.'),
   F('V_{6\\%}=3{,}6/(0{,}10-0{,}024)=47{,}3684,\\quad V_{10\\%}=6/(0{,}10-0{,}04)=100,\\quad V_{15\\%}=9/(0{,}10-0{,}06)=225','In allen drei Fällen steigt der spätere Gewinn. Nur im letzten Fall verdient zusätzlich gebundenes Kapital mehr als die geforderte Rendite.',[['V_{6\\%},V_{10\\%},V_{15\\%}','Werte bei den drei angenommenen Kapitalrenditen und vierzig Prozent Einbehaltung.']])
  ],'Gewinnwachstum und Wertschaffung sind unterschiedliche Aussagen.'),
  G({id:'retention-value',title:'Wachstum schafft nur bei ausreichender Kapitalrendite zusätzlichen Wert',caption:'Eigener konstanter Fall mit Anfangsbuchwert 100 und Eigenkapitalkosten 10 %. Nur die Einbehaltung wird variiert; jedes ROE gilt dauerhaft auch für neues Kapital.',reading:'Bei ROE 15 % erhöht Einbehaltung den Wert, bei 6 % vermindert sie ihn. Bei 10 % bleibt der Wert hundert. Die starke Krümmung des 15%-Falls folgt dem kleiner werdenden Abstand zwischen Diskontsatz und Wachstum; eine ewige Wettbewerbsvorteilannahme ist dabei ausdrücklich vorausgesetzt.',plot:{x:[0,50],y:[0,320],xTicks:[0,10,20,30,40,50],yTicks:[0,50,100,150,225,300],xLabel:'Einbehaltener Gewinnanteil in %',yLabel:'Heutiger Eigenkapitalwert',series:[{name:'ROE 15 %',points:Array.from({length:51},(_,i)=>[i,retention(.15,i/100)])},{name:'ROE 10 %',dash:true,points:Array.from({length:51},(_,i)=>[i,retention(.1,i/100)])},{name:'ROE 6 %',points:Array.from({length:51},(_,i)=>[i,retention(.06,i/100)])}],marks:[{x:40,y:225,label:'40 %: Wert 225',dx:-100,dy:-15}]}}),
  F('PVGO=V_0-\\frac{NI_1}{k_e}','Als kontrollierte Zerlegung lässt sich der zusätzliche Wert der Wachstumsgelegenheiten gegenüber vollständiger Ausschüttung des unveränderten ersten Gewinns zeigen. Ein negativer Betrag kann auf wertmindernde Reinvestition hinweisen.',[['PVGO','Present Value of Growth Opportunities unter dem angegebenen Vergleich.'],['V_0','Wert mit den betrachteten Investitionsgelegenheiten.'],['NI_1','Nächster Gewinn aus dem Ausgangskapital, hier ohne weitere Investition dauerhaft konstant im Vergleichsfall.'],['k_e','Passende Eigenkapitalkosten.']]),
  'Im 15%-Fall beträgt dieser Vergleichswert fünfundsiebzig; im 10%-Fall null. Im 6%-Fall ist er rund minus 12,63. Diese Rechnung unterstellt kein tatsächliches sofort verfügbares Liquidationsangebot und keine sichere Kenntnis eines realen ROE.'
 ]),
 S('reinvestment','13. Operatives Wachstum verlangt Investitionen','a b c',[
  F('g=\\eta\\,ROIC,\\quad \\eta=\\frac{g}{ROIC},\\quad FCFF_1=NOPAT_1(1-\\eta)','Im stabilen operativen Modell bestimmt die Rendite auf benötigtes neues Kapital, wie viel operativer Nachsteuergewinn für Wachstum reinvestiert werden muss.',[['g','Nachhaltiges operatives Wachstum bei konstanter Kapitalrendite.'],['\\eta','Operative Reinvestitionsquote: Nettoanlagen- plus Betriebskapitalinvestition relativ zu NOPAT.'],['ROIC','Rendite auf das im vereinfachten Modell gleichermaßen produktive Anfangs- und zusätzliche operative Kapital.'],['NOPAT_1','Operativer Nachsteuergewinn der nächsten Periode vor Finanzierungsverteilung.'],['FCFF_1','Nach den zu Wachstum passenden Nettoinvestitionen verbleibender operativer Cashflow.']]),
  X('Drei Prozent Wachstum werden mit realer Kapitalbindung bezahlt','Operatives Anfangskapital sechshundert, konstantes ROIC zwölf Prozent und langfristiges Wachstum drei Prozent. WACC zehn Prozent, keine separaten Vermögenswerte oder weiteren Ansprüche in dieser operativen Rechnung.',[
   F('NOPAT_1=600\\cdot0{,}12=72,\\quad\\eta=0{,}03/0{,}12=25\\%,\\quad I_1=72\\cdot0{,}25=18,\\quad FCFF_1=72-18=54','Achtzehn zusätzliches Kapital ermöglichen bei zwölf Prozent Kapitalrendite einen Gewinnzuwachs von 2,16 im Folgejahr, genau drei Prozent von zweiundsiebzig.',[['NOPAT_1','Nächster operativer Nachsteuergewinn.'],['\\eta','Erforderliche Reinvestitionsquote.'],['I_1','Nettoinvestition einschließlich operativer Betriebskapitalbindung.'],['FCFF_1','Nächster verfügbarer operativer Cashflow.']]),
   F('V_{op}=54/(0{,}10-0{,}03)=771{,}4286','Die Bewertung kapitalisiert verfügbare Mittel nach der erforderlichen Reinvestition.',[['V_{op}','Operativer Gesamtwert unter den stabilen Annahmen.']]),
   'Wer zweiundsiebzig mit demselben positiven Wachstum kapitalisiert, erhält etwa 1.028,57. Er hat den Wachstumsnutzen berücksichtigt, aber die zur Erzeugung notwendigen achtzehn pro Jahr in der wachsenden Reihe ausgelassen. Der Überhang beträgt rund 257,14.'
  ],'Ein Terminalwert mit positivem Wachstum und ohne benötigte Reinvestition muss wirtschaftlich begründet werden.'),
  'Marginale Rendite auf neues Kapital und historische Durchschnittsrendite können auseinanderfallen. Effizienzsteigerungen auf vorhandenem Kapital können vorübergehend Wachstum ohne zusätzliche Bindung erzeugen. Auch negative Reinvestition durch Abbau von Beständen ist möglich. Solche Übergangseffekte rechtfertigen aber keine automatische ewige Fortschreibung desselben Verhältnisses.'
 ]),
 S('two-stage','14. Eine Hochwachstumsphase endet an einem bestimmten Termin','b c',[
  F('D_t=D_0(1+g_H)^t\\ (1\\leq t\\leq T),\\quad D_{T+1}=D_T(1+g_L),\\quad V_T=\\frac{D_{T+1}}{k_e-g_L}','Die erste Phase wird einzeln prognostiziert. Der Fortführungswert nach ihrer letzten Zahlung beginnt mit der ersten Zahlung der stabilen Phase.',[['D_0','Zuletzt gezahlte Dividende.'],['D_t,D_T,D_{T+1}','Dividende in der ersten Phase, deren letzte sowie die erste nachfolgende Zahlung.'],['g_H,g_L','Wachstum in der endlichen hohen und in der stabilen langfristigen Phase.'],['T','Ende der Detailphase nach D_T.'],['V_T','Fortführungswert am Ende von T.'],['k_e','Hier konstanter Eigenkapitalsatz mit k_e größer als g_L.']]),
  X('Zwei Jahre hohe Zuwächse, danach vier Prozent','Zuletzt Dividende zwei; nächste zwei Jahre Wachstum zwanzig Prozent; danach dauerhaft vier Prozent. Eigenkapitalkosten zehn Prozent.',[
   T(['Zeitpunkt','Eigene Zahlung','Nach dieser Zahlung verbleibender Anspruch'],[['Heute','D₀ = 2 bereits gezahlt','Gesucht ist V₀.'],['Jahr 1','D₁ = 2,40','Noch Detailjahr zwei und stabile Endphase.'],['Jahr 2','D₂ = 2,88','V₂ = 49,92.'],['Jahr 3','D₃ = 2,9952','Diese Zahlung ist bereits die erste im V₂ enthaltene.']],'Die Zahlung im dritten Jahr wird nicht zusätzlich zum Fortführungswert erfasst.'),
   F('D_3=2{,}88\\cdot1{,}04=2{,}9952,\\quad V_2=2{,}9952/0{,}06=49{,}92,\\quad V_0=2{,}40/1{,}1+(2{,}88+49{,}92)/1{,}1^2=45{,}8182','Die zweite Dividende und der danach verbleibende Anspruch liegen beide in Jahr zwei. Der Fortführungswert ist noch kein heutiger Betrag.',[['D_3','Erste stabile Dividende.'],['V_2','Wert nach der zweiten Dividende.'],['V_0','Heutiger Wert je Aktie.']]),
   'Der abgezinste Fortführungswert erklärt rund neunzig Prozent des Resultats. Zwei detailliert berechnete Jahre machen den langfristigen Teil daher nicht nebensächlich. D₂ statt D₃ im Endwert würde eine Wachstumsstufe auslassen; fehlende Diskontierung von V₂ würde spätere Mittel zu hoch gewichten.'
  ],'Der Übergangstermin entscheidet sowohl den Zähler des Endwerts als auch seine Diskontierungsdauer.')
 ]),
 S('transition','15. Ein gleitender Übergang statt eines abrupten Sprungs','b c',[
  'Ein Zwei-Phasen-Modell wechselt die Wachstumsrate an einer Grenze. Wirtschaftlich können Wettbewerb, Reife, Margen und Investitionsbedarf allmählich wirken. Eine zusätzliche Übergangsphase lässt solche Entwicklungen ausdrücklich zu. Mehr Phasen verbessern eine Prognose nur, wenn ihre Annahmen begründet sind; zusätzliche Dezimalstellen reduzieren keine strukturelle Unsicherheit.',
  X('Vier einzelne Wachstumsjahre vor der stabilen Phase','Zuletzt Dividende zwei; Wachstumsraten der vier nächsten Jahre zwanzig, fünfzehn, zehn und fünf Prozent, danach drei Prozent. Eigenkapitalkosten zehn Prozent. Diese Folge ist eine eigene modellierte Zahlungsprognose, keine empirisch geschätzte Branchenentwicklung.',[
   T(['Jahr','Wachstum gegenüber Vorjahr','Dividende','Wert am Ende von Jahr vier'],[['1','20 %','2,4000',''],['2','15 %','2,7600',''],['3','10 %','3,0360',''],['4','5 %','3,1878','46,9062'],['5','3 %','3,283434','Erste Zahlung des Endwerts.']],'Die jährlichen Zuwächse wirken auf den jeweiligen Vorjahresbetrag.'),
   F('V_4=\\frac{3{,}1878\\cdot1{,}03}{0{,}10-0{,}03}=46{,}9062,\\quad V_0=\\frac{2{,}4}{1{,}1}+\\frac{2{,}76}{1{,}1^2}+\\frac{3{,}036}{1{,}1^3}+\\frac{3{,}1878+46{,}9062}{1{,}1^4}=40{,}9587','Jede Zahlung erhält ihren eigenen Jahresfaktor. Die letzte Detailzahlung und der Endwert liegen am selben Termin.',[['V_4','Nach der vierten Dividende verbleibender stabiler Anspruch.'],['V_0','Heutiger Wert der gesamten Zahlungsfolge.']])
  ],'Ein arithmetischer Durchschnitt der Wachstumsraten ersetzt diesen Zeitstrahl nicht.'),
  G({id:'growth-transition',title:'Die Wachstumsannahme verändert die gesamte spätere Zahlungsbasis',caption:'Eigene Dividendenpfade ab derselben zuletzt gezahlten Dividende zwei. Abrupt: zweimal 20 %, danach 4 %. Übergang: 20 %, 15 %, 10 %, 5 %, danach 3 %. Sofort stabil: von Anfang an 4 %.',reading:'Schon ein niedrigerer Zuwachs im zweiten Jahr wirkt auf alle späteren Zahlungsbeträge. Die Grafik zeigt nominale Dividenden, keine heutigen Barwerte. Risiko und wirtschaftlicher Investitionsbedarf müssten in einem vollständigen Prognosemodell zusätzlich abgestimmt werden.',plot:{x:[0,8],y:[1.8,4],xTicks:[0,1,2,4,6,8],yTicks:[2,2.5,3,3.5,4],xLabel:'Jahr nach dem Bewertungsstichtag',yLabel:'Dividende je Aktie, nominal',series:[{name:'Abrupter Übergang',points:Array.from({length:9},(_,t)=>[t,t<=2?2*1.2**t:2*1.2**2*1.04**(t-2)])},{name:'Gleitender Übergang',points:[2,2.4,2.76,3.036,3.1878,...Array.from({length:4},(_,i)=>3.1878*1.03**(i+1))].map((d,t)=>[t,d])},{name:'Sofort stabil',dash:true,points:Array.from({length:9},(_,t)=>[t,2*1.04**t])}]}}),
  'Die Grafik verwendet null nur zur Orientierung mit der zuletzt gezahlten Dividende. Diese vergangene Zahlung wird in keiner heutigen Bewertung noch einmal hinzugefügt.'
 ]),
 S('terminal-normalization','16. Die erste stabile Zahlung wirklich neu aufbauen','a b c',[
  'Eine Endphase benötigt mehr als eine neue Wachstumszahl. Marge, Steuern, Kapitalumschlag, Rendite auf neue Investitionen, Verschuldung und Ausschüttung müssen zum reifen Zustand passen. Die letzte Detailzahlung kann durch außergewöhnlich hohe Investitionen, eine Bestandsfreisetzung oder eine Übergangsmarge verzerrt sein. Dann wird die erste stabile Zahlung aus normalisierten wirtschaftlichen Größen neu berechnet.',
  X('Die letzte Detaildividende darf nicht mechanisch fortgeschrieben werden','Nach dem zweiten Jahr beträgt der Buchwert 112,36. Bisher galten ROE fünfzehn Prozent und Einbehaltung vierzig Prozent; Dividende im zweiten Jahr 9,54. Ab Jahr drei gelten ROE zehn Prozent und Einbehaltung dreißig Prozent. Eigenkapitalkosten zehn Prozent bleiben unverändert.',[
   F('NI_3=112{,}36\\cdot0{,}10=11{,}236,\\quad D_3=11{,}236\\cdot0{,}70=7{,}8652,\\quad g_L=0{,}30\\cdot0{,}10=3\\%','Das stabile ROE und die neue Ausschüttungsquote bestimmen die erste stabile Dividende. Der sinkende ROE verändert die Zahlungsbasis.',[['NI_3,D_3','Gewinn und Dividende des dritten Jahres.'],['g_L','Danach nachhaltiges Wachstum.']]),
   F('V_2=7{,}8652/(0{,}10-0{,}03)=112{,}36','Wenn die Kapitalrendite ab jetzt den Eigenkapitalkosten entspricht, ist der verbleibende Wert in diesem Modell gleich dem Buchkapital.',[['V_2','Eigenkapitalwert nach der zweiten Dividende.']]),
   '9,54 einfach mit 1,03 zu multiplizieren ergäbe 9,8262. Diese Rechnung würde den alten höheren ROE in die neue niedrigere Renditephase hinübertragen und damit den Endwert auf rund 140,37 erhöhen. Sie ist mit den ausdrücklich geänderten Kapitalrenditen nicht vereinbar.'
  ],'Ein Wechsel von ROE oder Ausschüttung verändert zuerst die Zahlungsbasis und danach die Bewertung.')
 ]),
 S('negative','17. Negative frühe Cashflows und wechselnde Diskontsätze','a b c',[
  'Bei jungen oder investierenden Unternehmen können frühere FCFE oder FCFF negativ sein. In der betreffenden Bewertung sind das benötigte zusätzliche Mittel, keine positiven Dividenden. Ein negativer früher Betrag kann mit einem positiven Gesamtwert vereinbar sein, wenn spätere Vorteile die Finanzierungsbelastung unter konsistenten Annahmen überwiegen. Bei einem Betrag je Aktie muss eine externe Finanzierung und ihre mögliche Verwässerung gesondert geplant werden.',
  X('Zusätzlicher Kapitaleinsatz vor positiven Zahlungen','Eine direkt betrachtete Eigenkapitalbeteiligung erfordert am Ende von Jahr eins fünf zusätzliche Einheiten. Im zweiten Jahr entstehen vier, danach wachsen verfügbare Eigentümermittel dauerhaft um drei Prozent. Jährliche Eigenkapitalkosten zwölf Prozent; der Beitrag wird vom selben Eigentümer geleistet, ohne zusätzliche Verwässerung oder weitere Ansprüche.',[
   F('E_2=\\frac{4\\cdot1{,}03}{0{,}12-0{,}03}=45{,}7778,\\quad E_0=\\frac{-5}{1{,}12}+\\frac{4+45{,}7778}{1{,}12^2}=35{,}2183','Der frühe Finanzierungseinsatz vermindert den Wert. Der positive Endwert enthält nur Zahlungen nach dem zweiten Jahr.',[['E_2','Verbleibender Wert am Ende von Jahr zwei.'],['E_0','Heutiger Wert nach Berücksichtigung des späteren zusätzlichen Eigentümereinsatzes.']]),
   'Ein Weglassen des negativen Betrags erhöht das Ergebnis fälschlich um rund 4,46. Ein aus den ersten beiden Werten berechnetes gewöhnliches prozentuales Wachstum wäre wegen des Vorzeichenwechsels kein sinnvoller Ersatz für die konkrete Prognose.'
  ],'Negative Zahlungen benötigen eine wirtschaftliche Finanzierungserklärung.'),
  X('Mehrstufiger FCFF führt zunächst zum operativen Wert','FCFF der nächsten zwei Jahre vierzig und fünfzig. Ab Jahr drei liefert die normalisierte Rechnung im vorigen Reinvestitionsfall FCFF 54, anschließend Wachstum drei Prozent. WACC zehn Prozent; überschüssige separate Kasse zwanzig, Schuldmarktwert 150, Vorzugskapital dreißig und nicht beherrschende Anteile zwanzig. Zehn identische Stammaktien stehen aus; alle Beträge sind in Millionen.',[
   F('V_{op,2}=54/(0{,}10-0{,}03)=771{,}4286,\\quad V_{op,0}=40/1{,}1+(50+771{,}4286)/1{,}1^2=715{,}2302','Der erste stabile FCFF liegt in Jahr drei, der zugehörige Endwert in Jahr zwei nach der zweiten Detailzahlung.',[['V_{op,2}','Fortführungswert des operativen Geschäfts am Ende von Jahr zwei.'],['V_{op,0}','Heutiger operativer Gesamtwert in Millionen.']]),
   F('E_0=V_{op,0}+20-150-30-20=535{,}2302,\\quad v_0=E_0/10=53{,}5230','Nur die separate überschüssige Kasse wird ergänzt; vorrangige und fremde Eigenkapitalansprüche werden genau einmal abgegrenzt.',[['E_0','Heutiger Stammaktionärswert der Mutter in Millionen.'],['V_{op,0}','Berechneter operativer Wert.'],['v_0','Wert je betrachteter Stammaktie.']])
  ],'Der korrekt berechnete operative Endwert ist noch nicht der gesuchte heutige Aktienwert.'),
  F('V_0=\\sum_{t=1}^{T}\\frac{CF_t}{\\prod_{j=1}^{t}(1+k_j)}+\\frac{V_T}{\\prod_{j=1}^{T}(1+k_j)}','Bei ausdrücklich veränderter periodischer Renditeforderung wird jeder Jahresfaktor bis zum betreffenden Termin multipliziert. Der Endwert verwendet zusätzlich den passenden Satz für die danach geltende Phase.',[['V_0,V_T','Heutiger Wert und Restwert nach der letzten Detailzahlung.'],['CF_t','Passender erwarteter Cashflow im Jahr t.'],['k_j','Für Jahr j festgelegter Diskontsatz des gleichen Anspruchs.'],['j,t,T','Faktorindex, Zahlungsjahr und Detailhorizont.']]),
  'Ein Mittelwert der Sätze ist im Allgemeinen keine exakte Ersetzung dieser Produkte. Eine nominale Fremdwährungszahlung wird außerdem mit einem dazu passenden nominalen Währungssatz bewertet; reale Zahlungen und nominale Sätze dürfen nicht vermischt werden.'
 ]),
 S('residual-charge','18. Ein positiver Gewinn kann wirtschaftlich zu klein sein','a b',[
  F('RI_t=NI_t-k_eB_{t-1}=(ROE_t-k_e)B_{t-1}','Residual Income zieht die kalkulatorische Eigenkapitalbelastung vom für Stammaktionäre verfügbaren Gewinn ab. Die Gewinnrechnung enthält gewöhnlich Fremdkapitalzinsen, aber keine entsprechende Eigenkapitalkostenzeile.',[['RI_t','Residualgewinn in der Periode t; kein zusätzlicher Cashflow.'],['NI_t','Passend bereinigter Stammaktionärsgewinn.'],['k_e','Eigenkapitalrenditeforderung.'],['B_{t-1}','Für die Periode eingesetzter Stammkapitalbuchwert am Anfang.'],['ROE_t','Hier NI_t geteilt durch denselben Anfangsbuchwert.'],['t','Periodenindex.']]),
  X('Rentabilität relativ zur geforderten Verzinsung','Anfangsbuchwert zweihundert und Eigenkapitalkosten acht Prozent. Drei eigene Fälle liefern Gewinne zwölf, sechzehn oder zwanzig.',[
   T(['Gewinn','ROE auf Anfangsbuchwert','Eigenkapitalbelastung','Residualgewinn'],[['12','6 %','16','−4'],['16','8 %','16','0'],['20','10 %','16','4']],'Alle Gewinne sind positiv; nur der letzte liegt über der kalkulatorischen Belastung.'),
   F('RI_A=12-0{,}08\\cdot200=-4,\\quad RI_B=0,\\quad RI_C=4','Ein zu kleiner positiver Gewinn deckt die geforderte Eigenkapitalverzinsung nicht.',[['RI_A,RI_B,RI_C','Residualgewinne der drei Vergleichsfälle.']])
  ],'Gewinn, Cashflow und wirtschaftlicher Überschuss sind getrennte Größen.'),
  'Ein einzelner negativer Residualgewinn begründet keinen abschließenden Wert eines mehrjährigen Geschäfts. Künftige Gewinne, Kapitalbindung und der aktuelle Buchwert gehören ebenfalls in die Bewertung. Gleiches gilt für ein besonders hohes einzelnes Jahr.'
 ]),
 S('clean-surplus','19. Die Buchwertfortschreibung ist die Brücke zum DDM','a b',[
  F('B_t=B_{t-1}+NI_t-D_t,\\quad D_t=NI_t+B_{t-1}-B_t=RI_t+(1+k_e)B_{t-1}-B_t','Unter der einfachen Clean-Surplus-Beziehung ohne zusätzliche Eigentümertransaktionen oder erfolgsneutrale Änderungen lässt sich die Dividende in Residualgewinn und Buchwertbewegung zerlegen.',[['B_{t-1},B_t','Buchwert desselben Stammkapitalanspruchs vor und nach der Periode.'],['NI_t,D_t','Passend bereinigter Periodengewinn und Dividende.'],['RI_t','Gewinn abzüglich k_e mal Anfangsbuchwert.'],['k_e','Eigenkapitalrenditeforderung.'],['t','Periodenindex.']]),
  F('\\sum_{t=1}^{T}\\frac{D_t}{(1+k_e)^t}=B_0+\\sum_{t=1}^{T}\\frac{RI_t}{(1+k_e)^t}-\\frac{B_T}{(1+k_e)^T}','Nach Einsetzen kürzen sich die abgezinsten Zwischenbuchwerte paarweise. Übrig bleiben Anfangsbuchwert, Residualgewinnreihe und letzter abgezinster Buchwert.',[['D_t,RI_t','Dividende und Residualgewinn in Jahr t.'],['B_0,B_T','Buchwert heute und am Ende der Detailphase.'],['k_e','Konstanter Eigenkapitaldiskontsatz.'],['t,T','Summationsindex und Detailhorizont.']]),
  F('V_0=B_0+\\sum_{t=1}^{T}\\frac{RI_t}{(1+k_e)^t}+\\frac{V_T-B_T}{(1+k_e)^T}','Zusammen mit dem nach T verbleibenden Aktienwert ergibt sich die endliche Residualgewinnbewertung. Ihr Restterm ist der Wert über Buchwert, nicht noch einmal der gesamte Endwert.',[['V_0,V_T','Eigenkapitalwert heute und nach der letzten Detaildividende.'],['B_0,B_T','Anfangs- und Endbuchwert.'],['RI_t','Periodischer Residualgewinn.'],['k_e','Eigenkapitalkosten.'],['t,T','Zahlungsindex und Detailhorizont.']]),
  'Wenn der diskontierte Restunterschied gegen null geht, wird daraus Anfangsbuchwert plus Barwert der unendlichen Residualgewinnreihe. Der Buchwert ist hier ein algebraischer Ausgangspunkt, keine Annahme, dass alle Vermögenswerte unabhängig ihren Bilanzbetrag wert wären.',
  X('Erfolgsneutrale Verluste sichtbar machen','Anfangsbuchwert hundert, ausgewiesener Gewinn zehn, Dividende zehn und zusätzliche erfolgsneutrale Buchwertminderung fünf. Der tatsächliche Endbuchwert beträgt 95; Eigenkapitalkosten zehn Prozent. Zur isolierten Kontrolle sei der gesamte übrige Anspruch danach genau 95 wert.',[
   F('NI^{*}=B_1-B_0+D_1=95-100+10=5,\\quad RI^{*}=5-0{,}10\\cdot100=-5','Für diese ausdrücklich vereinfachte Fortschreibung muss das wirtschaftlich erfasste Ergebnis die direkt gebuchte Verlustwirkung enthalten.',[['NI^{*},RI^{*}','Für die gegebene Buchwertfortschreibung bereinigter Gewinn und Residualgewinn.'],['B_0,B_1','Anfangs- und tatsächlicher Endbuchwert.'],['D_1','Dividende.']]),
   F('V_0=(10+95)/1{,}1=95{,}4545=100-5/1{,}1','Die direkte Zahlungsrechnung und die bereinigte Residualgewinnrechnung stimmen überein. Mit unverändertem ausgewiesenem Gewinn und RI null würde man die Verlustwirkung übersehen.',[['V_0','Heutiger Wert im isolierten Kontrollfall.']])
  ],'Direkte Eigenkapitalbuchungen, neue Aktien und Rückkäufe dürfen nicht unbemerkt eine einfache Clean-Surplus-Annahme verletzen.'),
  'In realen Abschlüssen werden weitere Eigentümertransaktionen und erfolgsneutrale Änderungen ausdrücklich abgegrenzt. Ein bereinigtes Modell muss wirtschaftliche Veränderungen vollständig und einmal erfassen. Die hier gezeigte Verlustrechnung ist keine allgemeine Behauptung, jeder OCI-Betrag sei in jeder Bewertung gleichartig zu behandeln.'
 ]),
 S('equivalence-case','20. Ein Unternehmen, zwei gleichwertige Herleitungen','a b c',[
  'Wir verbinden die vorigen Fälle: Buchwert heute hundert, ROE fünfzehn Prozent und Einbehaltung vierzig Prozent für zwei Jahre. Danach ROE und Eigenkapitalkosten jeweils zehn Prozent, Einbehaltung dreißig Prozent. Keine neuen Aktien, keine Schulden, keine übrigen Ansprüche und keine erfolgsneutralen Änderungen. Die Kapitalrendite der stabilen Phase deckt genau die Renditeforderung.',
  T(['Jahr','Anfangsbuchwert','ROE','Gewinn','Dividende','Endbuchwert','Residualgewinn'],[['1','100','15 %','15','9','106','5'],['2','106','15 %','15,9','9,54','112,36','5,3'],['3','112,36','10 %','11,236','7,8652','115,7308','0'],['Danach','Wächst mit 3 %.','10 %','Wächst mit 3 %.','Wächst mit 3 %.','Wächst mit 3 %.','0']],'Die dritte Dividende ist wegen des geänderten ROE niedriger als die zweite, obwohl die spätere stabile Reihe wächst.'),
  X('Die DDM-Rechnung nimmt sämtliche künftigen Ausschüttungen auf','Die Detaildividenden sind neun und 9,54. Der verbleibende Wert nach Jahr zwei beträgt 112,36 aus der ersten stabilen Dividende 7,8652.',[
   F('V_0^{DDM}=\\frac{9}{1{,}1}+\\frac{9{,}54+112{,}36}{1{,}1^2}=108{,}9256','Der Endwert enthält die gesamte stabile Dividendenreihe nach der zweiten Zahlung.',[['V_0^{DDM}','Heutiger Eigenkapitalwert über die Dividendenmethode.']])
  ],'Auch die Phase ohne zusätzlichen wirtschaftlichen Überschuss besitzt einen erheblichen Wert.'),
  X('Die RI-Rechnung bewertet nur Überschüsse zusätzlich zum Buchkapital','Die ersten zwei Residualgewinne sind fünf und 5,3. Danach verdienen Investitionen genau die erforderliche Rendite, sodass alle weiteren Residualgewinne null sind.',[
   F('V_0^{RI}=100+\\frac{5}{1{,}1}+\\frac{5{,}3}{1{,}1^2}=108{,}9256','Der Buchwert erfasst das Kapital, das anschließend angemessen verzinst wird. Die frühen Überschüsse schaffen den Aufschlag von rund 8,93.',[['V_0^{RI}','Heutiger Eigenkapitalwert über die Residualgewinnmethode.']]),
   'In der endlichen Formel ist der Restterm nach Jahr zwei null, weil Wert und Buchwert jeweils 112,36 betragen. Den ganzen Endwert noch auf Buchwert plus Residualgewinne zu addieren würde denselben Kapitalwert doppelt zählen.'
  ],'Die Methoden ordnen den Wert verschiedenen Rechengrößen zu, liefern bei diesen gleichen Annahmen aber denselben Betrag.'),
  'Wenn DDM, FCFE und RI in einem abgestimmten eigenen Modell nicht übereinstimmen, sind zuerst Zahlungsrechte, Kapitalverwendung, neue Finanzierung, Buchwertfortschreibung und Endphase zu prüfen. Eine bloße Mittelung der unterschiedlichen Resultate erklärt den Widerspruch nicht.'
 ]),
 S('continuing-ri','21. Fortgesetzter Residualgewinn und Rentabilitätsgrenzen','a b c',[
  F('V_0=B_0+\\frac{RI_1}{k_e-h}','Wenn der Residualgewinn selbst ab Jahr eins dauerhaft mit h wächst und die notwendige Grenzbedingung gilt, kann seine geometrische Reihe zusätzlich zum Anfangsbuchwert kapitalisiert werden.',[['V_0','Eigenkapitalwert.'],['B_0','Anfangsbuchwert.'],['RI_1','Erster erwarteter Residualgewinn.'],['h','Konstante Wachstumsrate des Residualgewinns, nicht automatisch Dividendenwachstum.'],['k_e','Eigenkapitalkosten, größer als h.']]),
  X('Ein Zuschlag, eine neutrale Phase und ein Abschlag','Buchwert hundert, Eigenkapitalkosten zehn Prozent. Die nächste Residualgewinnreihe beträgt alternativ fünf, null oder minus zwei und bleibt jeweils ohne Wachstum.',[
   F('V_A=100+5/0{,}10=150,\\quad V_B=100,\\quad V_C=100-2/0{,}10=80','Anhaltende Überschüsse erhöhen, ausreichend verzinste Buchkapitalerträge verändern und anhaltende Fehlbeträge vermindern den Wert relativ zum Buchwert.',[['V_A,V_B,V_C','Eigenkapitalwerte unter den drei ausdrücklich verschiedenen ewigen Rentabilitätsannahmen.']])
  ],'Eine niedrige Bewertung relativ zum Buchwert kann eine wirtschaftlich konsistente Rentabilitätserwartung widerspiegeln.'),
  'Ein langfristig konstanter oder wachsender Residualgewinn setzt anhaltende Renditevorteile voraus. Wettbewerb kann sie abschwächen. Außerdem beeinflussen Bilanzierungsentscheidungen Gewinn und Buchwert; unvollständige Bereinigung erzeugt einen scheinbaren Überschuss. Residualgewinn ist kein direkt an Aktionäre ausgezahltes Geld und darf nicht zusätzlich zu derselben Dividendenreihe als weitere Zahlung gezählt werden.'
 ]),
 S('sensitivity','22. Warum der kleine Abstand im Nenner wichtig ist','b c',[
  'Der unten verknüpfte interaktive Rechner hält die nächste Dividende als eigene Eingabe fest. Um den Tabellenfall mit zuletzt gezahlter Dividende zwei und Wachstum vier Prozent nachzustellen, wird daher 2,08 als nächste Zahlung eingegeben. Wird danach allein das Wachstum verändert, bleibt diese eingegebene nächste Zahlung konstant; ein Vergleich bei festem vergangenen Dividendenbetrag benötigt auch einen neu berechneten Zähler.',
  X('Dieselbe historische Dividende unter neun Annahmenkombinationen','Zuletzt gezahlte Dividende zwei. Konstante Wachstumssätze zwei, vier oder sechs Prozent werden mit Eigenkapitalkosten acht, zehn oder zwölf Prozent kombiniert.',[
   T(['Eigenkapitalkosten','g = 2 %','g = 4 %','g = 6 %'],[['8 %','34,0000','52,0000','106,0000'],['10 %','25,5000','34,6667','53,0000'],['12 %','20,4000','26,0000','35,3333']],'Alle Zähler enthalten die jeweils nächste Dividende; die Tabelle verändert bewusst Annahmen, keine Eintrittswahrscheinlichkeiten.'),
   F('V_0(10\\%,4\\%)=2\\cdot1{,}04/(0{,}10-0{,}04)=34{,}6667,\\quad V_0(8\\%,6\\%)=2\\cdot1{,}06/(0{,}08-0{,}06)=106','Nur eine geringe Änderung des nächsten Zahlungsbetrags trifft auf einen wesentlich kleineren Diskont-Wachstums-Abstand.',[['V_0(k_e,g)','Wert bei den jeweils genannten Eigenkapitalkosten und Wachstumsraten.']])
  ],'Ein scheinbar genauer Wert kann stark von unsicherer langfristiger Modellwahl abhängen.'),
  F('\\left.\\frac{\\partial V_0}{\\partial k_e}\\right|_{D_1,g}=-\\frac{D_1}{(k_e-g)^2},\\qquad \\left.\\frac{\\partial V_0}{\\partial g}\\right|_{D_0,k_e}=\\frac{D_0(1+k_e)}{(k_e-g)^2}','Die Ableitungen zeigen die lokale Richtung und die wachsende Empfindlichkeit bei kleinem Abstand. Bei der Wachstumsableitung verändert sich zusätzlich die nächste Dividende aus dem festgehaltenen D_0.',[['V_0','Gordon-Wert.'],['D_0,D_1','Vergangene beziehungsweise nächste Dividende.'],['k_e,g','Eigenkapitalkosten und Wachstum.'],['\\partial','Lokale partielle Änderung; die Zeichen nach dem senkrechten Strich benennen konstant gehaltene Größen.']]),
  G({id:'gordon-sensitivity',title:'Kleine Wachstumsunterschiede werden bei engem Nenner stark verstärkt',caption:'Eigene Gordon-Reihe mit letzter Dividende zwei und Eigenkapitalkosten zehn Prozent. Wachstum variiert von null bis acht Prozent und bleibt im ganzen dargestellten Bereich unter der Renditeforderung.',reading:'Bei vier Prozent Wachstum beträgt der Wert etwa 34,67, bei sechs Prozent 53 und bei acht Prozent 108. Die Kurve ist keine Aussage, dass das höhere Wachstum wirtschaftlich finanzierbar oder dauerhaft erreichbar sei. Dafür sind Reinvestition, Kapitalrendite und Wettbewerb gesondert zu prüfen.',plot:{x:[0,8],y:[0,115],xTicks:[0,2,4,6,8],yTicks:[0,20,40,60,80,100],xLabel:'Dauerhaftes jährliches Dividendenwachstum in %',yLabel:'Heutiger Wert je Aktie',series:[{name:'Konstantes Wachstumsmodell',points:Array.from({length:81},(_,i)=>[i/10,gordon(.1,i/1000)])}],marks:[{x:4,y:gordon(.1,.04),label:'4 %: 34,67',dx:12,dy:17},{x:8,y:108,label:'8 %: 108',dx:-90,dy:-10}]}}),
  'Wenn Wachstum mit höherem Risiko einhergeht, kann gleichzeitig die Renditeforderung steigen. Eine Sensitivitätskurve mit festem Satz isoliert nur einen Zusammenhang. Eine konsistente Szenarioanalyse verändert zusammengehörige Größen gemeinsam und erklärt ihre wirtschaftlichen Gründe.'
 ]),
 S('limitations','23. Was konstante und mehrstufige Modelle nicht leisten','c',[
  T(['Annahme oder Vereinfachung','Möglicher Fehler','Sinnvolle Gegenprüfung'],[['Dauerhaft feste Wachstumsrate.','Eine Firma wächst langfristig über ihren verfügbaren Markt hinaus.','Absolute Umsatzgröße, Marktanteil und reifen Zustand prüfen.'],['Konstante hohe Kapitalrendite.','Historische Vorteile werden auf alle neuen Investitionen übertragen.','Marginale Rendite und Wettbewerb untersuchen.'],['Mechanischer Phasenwechsel.','Gewinnbasis und Investitionsbedarf passen nicht zur neuen Wachstumszahl.','Erste stabile Zahlung aus normalisierten Größen neu aufbauen.'],['Konstante Finanzierungskosten.','Verschuldung oder Risiko verändern sich, der Satz bleibt unpassend.','Finanzierungsplan und passende periodische Risikokosten abstimmen.'],['Ausschüttung gleich verfügbare Mittel.','Zurückbehaltene Mittel werden ineffizient verwendet oder Rechte ignoriert.','Politik, Durchsetzbarkeit und tatsächliche Eigentümerleistungen prüfen.'],['Detailmodell mit großem Endwert.','Mehr Detailjahre verdecken eine weiterhin dominante Endphasenannahme.','Anteil, Treiber und alternative Endphasen transparent zeigen.']],'Modellwahl ist eine wirtschaftliche Entscheidung vor der Zahlenrechnung.'),
  'Ein positives stabiles Wachstum benötigt eine glaubwürdige langfristige Basis. Eine nominale Wachstumshypothese wird mit nominalen Kapitalkosten in derselben Währung verbunden. Wachstum knapp unter dem Satz erfüllt die mathematische Ungleichung, kann aber trotzdem wirtschaftlich unplausibel sein.',
  'Ein länger gewählter Detailhorizont beseitigt den Endwert nicht automatisch. Er sollte lang genug sein, um einen begründeten stabilen Zustand zu erreichen. Gleichzeitig steigern zusätzliche Jahre die Prognoseunsicherheit. Mehrstufige Modelle lösen diesen Zielkonflikt nicht von selbst.',
  'Discounted Cashflow ist keine unabhängige Bestätigung jeder Eingabe. Modellwert, Marktpreis und eine erwartete tatsächliche Anlagerendite bleiben getrennt. Das Training verlangt deshalb sowohl Rechnung als auch Fehlerdiagnose und Beurteilung der Annahmen.'
 ]),
 S('preferred','24. Ewige feste Vorzugsdividende','b d',[
  'Eine nicht kündbare und nicht wandelbare Vorzugsaktie mit fester ewiger Dividende wird im einfachen Modell wie eine konstante Zahlungsreihe bewertet. Nicht kündbar und nicht wandelbar bedeutet allein noch nicht, dass jede reale Vorzugsaktie ewig läuft: Eine vertragliche feste Endfälligkeit benötigt eine endliche Bewertung. Ausschüttungsrisiko und Vorrang gegenüber Stammaktien sind ebenfalls von einer staatlich garantierten Zinszahlung zu unterscheiden.',
  F('V_{PS}=\\sum_{t=1}^{\\infty}\\frac{D_{PS}}{(1+k_{PS})^t}=\\frac{D_{PS}}{k_{PS}},\\qquad D_{PS}=cF_{PS}','Eine konstante jährliche Dividende wird mit der für den Vorzugsanspruch passenden Renditeforderung kapitalisiert. Der Dividendenprozentsatz bezieht sich auf seinen vertraglichen Bezugsbetrag, nicht auf den aktuellen Marktwert.',[['V_{PS}','Heutiger Wert einer Vorzugsaktie.'],['D_{PS}','Feste erwartete jährliche Dividende, erste Zahlung in einem Jahr.'],['k_{PS}','Geeignete jährliche Renditeforderung für diesen Vorzugsanspruch.'],['F_{PS}','Vertraglicher Nominal- oder Bezugsbetrag.'],['c','Fester jährlicher Dividendensatz auf F_PS.'],['t','Jahresindex.']]),
  X('Vertragsprozentsatz ist nicht die aktuelle Rendite','Bezugsbetrag hundert, feste jährliche Vorzugsdividende fünf Prozent dieses Betrags. Die Aktie ist ewig, nicht kündbar, nicht wandelbar; alle Zahlungen werden erwartet. Geforderte Rendite zunächst acht Prozent, alternativ fünf oder zehn Prozent.',[
   F('D_{PS}=0{,}05\\cdot100=5,\\quad V_{8\\%}=5/0{,}08=62{,}50,\\quad V_{5\\%}=100,\\quad V_{10\\%}=50','Die Vertragszahlung fünf bleibt gleich. Eine höhere erforderliche Rendite senkt den heutigen Wert derselben Reihe.',[['D_{PS}','Jährliche Dividende.'],['V_{8\\%},V_{5\\%},V_{10\\%}','Werte bei den drei genannten Renditeforderungen.']]),
   'Bei Preis 62,50 beträgt die laufende Dividendenrendite acht Prozent. Der feste Satz fünf Prozent ist weiterhin korrekt auf den vertraglichen Bezugsbetrag bezogen. Hundert ist hier kein automatisch später zurückgezahlter Betrag.'
  ],'Zahlung, Bezugsbetrag, Marktwert und Renditeforderung müssen getrennt werden.'),
  G({id:'preferred-rate',title:'Die feste Zahlung bleibt gleich, ihr heutiger Wert verändert sich',caption:'Eigene ewige Vorzugsaktie mit Jahresdividende fünf, ohne Kündigung, Wandlung oder Ausfalländerung. Nur die konstante erforderliche Rendite variiert.',reading:'Bei fünf Prozent Renditeforderung ist der Wert hundert, bei acht Prozent 62,50 und bei zehn Prozent fünfzig. Die fallende Kurve zeigt Kapitalisierung desselben Cashflows und kein verändertes Dividendenversprechen.',plot:{x:[4,12],y:[30,135],xTicks:[4,5,8,10,12],yTicks:[40,60,80,100,120],xLabel:'Jährliche Vorzugsrenditeforderung in %',yLabel:'Heutiger Wert je Vorzugsaktie',series:[{name:'Barwert der ewigen Dividende',points:Array.from({length:81},(_,i)=>{const k=4+i/10;return[k,5/(k/100)];})}],marks:[{x:8,y:62.5,label:'8 %: 62,50',dx:14,dy:20}]}})
 ]),
 S('preferred-timing','25. Zahlungsfrequenz und feste Endfälligkeit','b d',[
  F('k_p=(1+k_{eff})^{1/m}-1,\\qquad V_{PS}=\\frac{D_{ann}/m}{k_p}','Bei gleichmäßigen ewigen Teilzahlungen wird die Jahresdividende aufgeteilt und mit der passenden Periodenrendite kapitalisiert. Eine effektive Jahresrendite wird nicht einfach durch m geteilt.',[['k_p','Effektive Rendite je Zahlungsperiode.'],['k_{eff}','Effektive jährliche Renditeforderung.'],['m','Anzahl gleicher Zahlungsperioden pro Jahr.'],['D_{ann}','Gesamte feste Dividende eines Jahres.'],['V_{PS}','Heutiger Wert bei erster Zahlung genau eine Periode nach dem Stichtag.']]),
  X('Vierteljährliche Zahlungen bei acht Prozent effektiver Jahresrendite','Ewige Vorzugsaktie zahlt 1,50 am Ende jedes Quartals, insgesamt sechs pro Jahr. Geforderte effektive Jahresrendite acht Prozent, nächste Zahlung in genau einem Quartal.',[
   F('k_q=1{,}08^{1/4}-1=1{,}9426547\\%,\\qquad V_{PS}=1{,}50/k_q=77{,}2139','Die Teilzahlungen werden früher vereinnahmt als eine gesamte Jahreszahlung am Jahresende. Der korrekte periodische Faktor bildet das ab.',[['k_q','Effektive Vierteljahresrendite.'],['V_{PS}','Heutiger Wert je Vorzugsaktie.']]),
   'Sechs geteilt durch acht Prozent wäre fünfundsiebzig und bewertete eine andere zeitliche Zahlung, nämlich sechs jeweils erst am Jahresende. Bei einer ausdrücklich nominalen Jahresquote mit vierteljährlicher Verzinsung gilt dagegen die zugehörige Division durch vier für den Periodensatz.'
  ],'Die Quote muss zur genannten Zinskonvention und zum Zahlungszeitpunkt passen.'),
  F('V_{PS}=D_{PS}\\frac{1-(1+k_{PS})^{-T}}{k_{PS}}+\\frac{F_T}{(1+k_{PS})^T}','Eine vertraglich endfällige, nicht kündbare und nicht wandelbare Vorzugsaktie enthält eine endliche Dividendenannuität und einen separat versprochenen Rückzahlungsbetrag.',[['D_{PS}','Konstante jährliche Dividende bis einschließlich T.'],['k_{PS}','Passender jährlicher Satz.'],['T','Vertraglich feste Zahl der verbleibenden Jahresperioden.'],['F_T','Rückzahlung am Ende von Jahr T zusätzlich zur letzten Dividende.'],['V_{PS}','Heutiger Wert dieses endlichen Anspruchs.']]),
  X('Eine feste Rückzahlung ist eine zusätzliche Vertragsleistung','Noch fünf jährliche Dividenden zu fünf und danach Rückzahlung hundert; jährliche Renditeforderung acht Prozent.',[
   F('V_{PS}=5\\frac{1-1{,}08^{-5}}{0{,}08}+100/1{,}08^5=88{,}0219','Die fünf Zahlungen besitzen Barwert rund 19,96, die Rückzahlung rund 68,06. Ihr Gesamtwert unterscheidet sich von der ewigen Dividende ohne Rückzahlung.',[['V_{PS}','Heutiger Wert des vertraglich endlichen Vorzugsanspruchs.']])
  ],'Nicht wandelbar und nicht kündbar ersetzt keine Prüfung der Fälligkeit.')
 ]),
 S('contingencies','26. Bedingte Rechte verändern den Zahlungsanspruch','d',[
  T(['Merkmal','Wirtschaftliche Richtung bei sonst gleicher Basis','Was zusätzlich geprüft wird'],[['Emittent darf kündigen.','Die Möglichkeit nimmt dem Anleger den Teil des Vorteils günstiger Anschlussbedingungen.','Zeitpunkt, Kündigungspreis, Schutzfrist und tatsächliche Ausübungsanreize.'],['Anleger darf wandeln.','Ein freiwilliges zusätzliches Wahlrecht kann den Wert gegenüber identischem Vorzug ohne Recht erhöhen.','Umtauschquote, Stammaktienwert, spätere Ausübung, verlorene Vorzugsrechte und Verwässerung.'],['Anleger darf Rückgabe verlangen.','Ein zusätzliches durchsetzbares Rückgaberecht kann schützen.','Preis, Frist, Bedingungen und Erfüllungsfähigkeit.'],['Variable oder zurückgesetzte Dividende.','Eine feste ewige Dividendenformel passt nicht direkt.','Referenzsatz, Zuschlag, Resettermin, Grenzen und Risiko.'],['Kumulative ausgelassene Dividende.','Nachholansprüche verändern mögliche spätere Zahlungen.','Nachholreihenfolge, Zeitpunkt, Solvenz und weitere Vertragsbedingungen.'],['Zusätzliche Teilnahme.','Definierte Gewinn- oder Exitbeteiligung kann zusätzliche Zahlungen liefern.','Schwelle, Quote, Rang und Deckelung.']],'Die Richtungen vergleichen identische Ansprüche mit zusätzlich eingeräumten Rechten; unterschiedliche sonstige Vertragsmerkmale können den Vergleich verändern.'),
  X('Ein Kündigungsrecht beschränkt den Zinsvorteil','Eine sonst identische ewige Vorzugsaktie zahlt fünf jährlich. Bei fünf Prozent Rendite wäre der Wert ohne Kündigung hundert. Der Emittent darf aber unmittelbar nach der ersten Dividende für achtzig kündigen; in diesem vereinfachten sicheren Szenario erfolgt die Kündigung.',[
   F('V_{call}=\\frac{5+80}{1{,}05}=80{,}9524','Der Anleger erhält die erste Dividende und danach den vereinbarten Kündigungsbetrag statt der fortgesetzten ewigen Reihe.',[['V_{call}','Heutiger Wert der hier ausdrücklich sicheren Kündigungsfolge.']]),
   'Die Achtzig ist der Preis am Kündigungstermin, keine strikte heutige Kursobergrenze. Allgemein hängt die Optionswirkung von künftigen Sätzen, Ausübung und Schutzfristen ab; das Beispiel setzt diese Entwicklung ausdrücklich fest.'
  ],'Ein kündbarer Vertrag ist nicht durch bloße Anwendung derselben ewigen Formel vollständig bewertet.'),
  X('Sofortiger Wandlungswert ist nicht der gesamte Optionswert','Eine Vorzugsaktie kann freiwillig in zwei Stammaktien zu jeweils vierzig gewandelt werden. Ohne Wandlung beträgt der aktuelle Wert des weiter gehaltenen Vorzugs siebzig; bei sofortiger Ausübung erlöschen diese Rechte.',[
   F('CV=nP_C=2\\cdot40=80,\\qquad V_{choice}\\geq\\max(70,80)=80','Wenn beide Handlungen ohne Kosten jetzt verfügbar und die Rechte durchsetzbar sind, muss ein rational bewerteter Wahlanspruch mindestens die günstigere sofortige Alternative enthalten.',[['CV','Sofortiger Wandlungswert.'],['n','Zahl erhaltener Stammaktien.'],['P_C','Aktueller Wert je erhaltener Stammaktie.'],['V_{choice}','Wert des freiwilligen Wahlanspruchs; kann wegen zukünftiger Flexibilität höher sein.']]),
   'Siebzig plus achtzig wäre falsch, weil bei Wandlung der bisherige Vorzug aufgegeben wird. Auch Maximum achtzig ist ohne vollständiges Optionsmodell nicht zwingend der genaue Gesamtwert; weiteres Warten kann wertvoll sein.'
  ],'Wahlrechte werden als Alternativen und Bedingungen verstanden, nicht als doppelte volle Zahlungen.'),
  'Bei Pflichtwandlung, vorgeschriebenen Umtauschformeln oder Ausfall sind die freiwilligen Wahlrechtsargumente entsprechend anzupassen. Ein fester hoher Dividendensatz schützt nicht automatisch vor Verlust oder Zahlungsaufschub.'
 ]),
 S('workflow','27. Einen Bewertungsfall nachvollziehbar lösen','a b c d',[
  T(['Schritt','Konkrete Entscheidung'],[['Anspruch bestimmen.','Stammaktie, gesamtes Eigenkapital, operatives Unternehmen oder vertraglicher Vorzug?'],['Zeitstrahl aufbauen.','Welche Beträge sind vergangen, nächstes Jahr, letztes Detailjahr und erste stabile Zahlung?'],['Inputs ableiten.','Gewinn, Abschreibung, Investition, Betriebskapital, Finanzierung und Ausschüttung abstimmen.'],['Risiko zuordnen.','Eigenkapitalkosten, WACC oder Vorzugssatz mit passender Währung und Zinskonvention verwenden.'],['Detailphase rechnen.','Jede Zahlung genau einmal und mit eigenem Termin diskontieren.'],['Endphase begründen.','Rendite, Wachstum, Reinvestition und erste stabile Zahlung konsistent normalisieren.'],['Ansprüche überleiten.','Nur Werte hinzugeben oder abziehen, die im Ausgangsmodell noch fehlen.'],['Aussage prüfen.','Gegenrechnung, Sensitivität, wirtschaftliche Grenzen und Vergleich zum passenden Marktpreis erklären.']],'Die Reihenfolge verhindert richtige Algebra auf einer falschen Anspruchs- oder Zeitbasis.'),
  'Der Finanzrechner hilft bei den Diskontierungen, entscheidet aber nicht über die richtige Zahlungsreihe. Für gleichbleibende endliche Zahlungen werden N, I/Y, PMT und FV mit passenden Perioden verwendet; bei ungleichen Detailcashflows eignet sich das Cashflow-Worksheet. Der Terminalwert wird als zusätzliche letzte Zahlung am richtigen Termin erfasst. Eine Dividende darf dadurch nicht ersetzt oder doppelt gezählt werden. Die grundlegenden BA-II-Plus-Einstellungen und Vorzeichen erklärt das Kapitel Zahlungsströme bewerten.',
  'Beim eigenständigen Üben zuerst Modell, Zeitstrahl und benötigte Größen bestimmen. Erst danach Zahlen einsetzen und das Ergebnis in Worten auf die Frage beziehen. Die Frage nach dem Eigenkapitalwert verlangt nach einer FCFF-Rechnung noch die passende Anspruchsbrücke; die Frage nach einer Vorzugsaktie verlangt ihre eigenen Vertragszahlungen.'
 ]),
 S('review','28. Zusammenhangsfragen statt bloßer Formelwiederholung','a b c d',[
  T(['Prüffrage','Wirtschaftlicher Kern'],[['Warum darf man FCFE nicht mit WACC kapitalisieren?','Finanzierungswirkungen und Risiko gehören zu verschiedenen Anspruchsebenen.'],['Warum steht die nächste Zahlung im Zähler?','Die Reihe beginnt nach dem heutigen Bewertungsstichtag.'],['Warum benötigt stabiles Wachstum Reinvestition?','Zusätzlicher Gewinn muss durch Kapital oder begründete Effizienzsteigerung erzeugt werden.'],['Wann ist mehr Einbehaltung wertsteigernd?','Zusätzlich gebundenes Kapital muss mehr als seine passenden Kosten verdienen.'],['Warum kann D₃ trotz positiver langfristiger Wachstumsrate kleiner als D₂ sein?','Der Wechsel von Rentabilität und Ausschüttung verändert zuerst die Zahlungsbasis.'],['Warum enthält RI den Buchwert zusätzlich?','Die Clean-Surplus-Zerlegung trennt vorhandenes Kapital und Überschüsse.'],['Was steckt im RI-Endterm?','Der zukünftige Wert über dem damaligen Buchwert, nicht der ganze Aktienwert.'],['Warum ist der Vorzugsbezugsbetrag kein heutiger Preis?','Er definiert Vertragszahlungen; Diskontierung bestimmt ihren heutigen Wert.']],'Die eigenen Trainingsfälle enthalten Rechnungen, Modellvergleich und Fehlersuche.'),
  'Die Lösungen der Trainingsfragen bleiben vor der eigenen Antwort verborgen. Zu jeder Antwortalternative gibt es eine Begründung und einen Rückweg zur genauen Erklärung. Die reservierten Klausurfragen verbinden andere eigene Situationen und werden nicht im Kapiteltraining verwendet.'
 ])
],explorations:[{section:'sensitivity',lesson:'equity-08',focus:'lab',label:'Dividende, Wachstum und Renditeforderung im Gordon-Rechner verändern'}],related:[
 {unit:'multiples',section:'growth-pe',label:'Wachstum und Kapitalrendite in gerechtfertigten Multiplikatoren'},
 {unit:'valuation-overview',section:'bridge',label:'Operativen Wert auf Stammaktionärsansprüche überleiten'},
 {unit:'cashflow-analysis',section:'free-cashflow',label:'FCFF aus verschiedenen Abschlussgrößen rekonstruieren'},
 {unit:'cashflow-analysis',section:'fcfe',label:'Nettokreditaufnahme und freier Eigenkapitalcashflow'},
 {unit:'tvm',section:'terminal-value',label:'Endwert und Diskontierung am Zeitstrahl'},
 {unit:'tvm',section:'calculator',label:'BA II Plus: Perioden, Zahlungszeitpunkt und Vorzeichen'},
 {unit:'capital-structure',section:'wacc',label:'Marktwertgewichte und passende Kapitalgeberkosten'},
 {unit:'forecasting',section:'continuing',label:'Reinvestition und langfristiger Prognosezustand'},
 {unit:'equity-features',section:'conversion',label:'Vorzugsrechte und Wandlungsbedingungen'},
 {unit:'equity-returns',section:'reinvestment',label:'Ausschüttungen, Bargeld und Aktionärsvermögen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Discounted Cash Flow and Growth Models, Seite 16',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=16'},
 {title:'CFA Institute: Discounted Dividend Valuation; öffentliche Level-II-Vertiefung zu Zahlungsreihen und Wachstumsmodellen',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/discounted-dividend-valuation'},
 {title:'CFA Institute: Free Cash Flow Valuation; ergänzende Level-II-Vertiefung zu FCFF, FCFE und Bewertungsumfang',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/free-cash-flow-valuation'},
 {title:'CFA Institute: Residual Income Valuation; ergänzende Level-II-Vertiefung zur Eigenkapitalbelastung und Buchwertzerlegung',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/residual-income-valuation'},
 {title:'Aswath Damodaran, NYU Stern: The Fundamental Determinants of Growth; Reinvestition, Kapitalrendite und Grenzen',url:'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/valquestions/growth.htm'}
],review:{status:'draft',date:'2026-10-03',note:'Eigene Cashflowbrücken, algebraische Herleitungen und kontrollierte Wachstum-, Residualgewinn- und Vorzugsfälle. Noch keine vollständige fachliche Gesamtabnahme.'}};
