const {F,T,X,S,G}=require('../author.cjs');
module.exports={id:'equity-returns',intro:[
 'Eine höhere Aktienzahl, eine Dividende auf dem Konto oder ein höherer Gewinn je Aktie ist noch keine vollständige Renditerechnung. Entscheidend ist, welche Ansprüche ein Anleger vorher und nachher besitzt, welche Zahlungen ihm zustehen und welchen Betrag er tatsächlich investiert hat. Dieses Kapitel führt deshalb für jede Kapitalmaßnahme ein kleines Vermögenskonto.',
 'CFA Level I 2027 verlangt die Merkmale und Einsatzmöglichkeiten von Ausschüttungen, Rückkäufen und Splits, die Dividendenchronologie sowie Kurs- und Gesamtrenditen. Die Rechnungen zu Rückkaufpreisen, Ergebniswirkung und Wiederanlage vertiefen diese Grundlagen. Sie sind eigene Modellfälle mit offengelegten Annahmen; Marktpreise, Steuerregeln und Abwicklungstermine sind in der Praxis zusätzlich zu prüfen.'
],sections:[
 S('forms','1. Welche Größe verändert die Maßnahme?','a',[
  'Eine Bardividende überträgt Zahlungsmittel an die berechtigten Eigentümer. Beim Aktienrückkauf bezahlt die Gesellschaft dagegen diejenigen, deren Aktien sie erwirbt. Eine proportionale Stock Dividend eigener Aktien und ein Aktiensplit verändern zunächst die Stückelung der Beteiligung. Diese drei Vorgänge dürfen nicht als derselbe zusätzliche Ertrag behandelt werden.',
  T(['Maßnahme','Zahlungsmittel an Anleger','Ausstehende Aktien im reinen Modell'],[['Reguläre Bardividende','An alle für diese Zahlung berechtigten Aktien nach ihren Rechten.','Unverändert.'],['Sonderdividende','Einmalige beziehungsweise zusätzlich erklärte Zahlung.','Unverändert.'],['Aktienrückkauf','An die tatsächlich verkaufenden Aktionäre.','Sinken, wenn die gekauften Aktien nicht mehr ausstehend sind.'],['Proportionale Stock Dividend eigener Aktien','Keine Bardividende allein durch die Zuteilung.','Steigen proportional.'],['Split / Reverse Split','Kein Geldfluss allein aus der Umstückelung.','Steigen / sinken im festgelegten Verhältnis.']],'Gebühren, Bruchteilsabfindungen und andere gleichzeitig stattfindende Maßnahmen werden gesondert erfasst.'),
  'Eine reguläre Dividende schafft eine Erwartung wiederkehrender Zahlungen, aber keine automatische Garantie aller künftigen Dividenden. Eine Sonderdividende kann außergewöhnlich verfügbares Kapital verteilen, ohne denselben dauerhaften Rhythmus zu versprechen. Eine Liquidationsausschüttung gibt Vermögen im Zuge einer Abwicklung zurück: Eine hohe Zahlung beweist dabei gerade nicht hohe fortdauernde Ertragskraft.',
  'Eine Ausschüttung von Aktien einer Tochtergesellschaft ist von einer bloßen proportionalen Ausgabe weiterer eigener Aktien zu unterscheiden. Nach einer Abspaltung sind mehrere Wertpapierpositionen zu bewerten. Die folgende reine Stock-Dividend-Rechnung gilt ausdrücklich für zusätzliche identische Aktien derselben Gesellschaft.'
 ]),
 S('wealth','2. Das Vermögenskonto verhindert Doppelzählung','a c',[
  F('W_t=n_tP_t+C_t+A_t','Der Depotwert allein ist nicht immer das gesamte Vermögen der Strategie. Eine bereits abgetrennte, noch nicht gezahlte Dividende gehört als eigener Anspruch hinzu, soweit sie dem Anleger zusteht.',[['W_t','Gesamtwert der hier abgegrenzten Strategie zum Zeitpunkt t.'],['n_t','Gehaltene Aktienzahl zu diesem Zeitpunkt.'],['P_t','Kurs je Aktie ohne separat erfasste Ansprüche.'],['C_t','Zur Strategie gehörendes Bargeld.'],['A_t','Wert noch nicht im Kurs oder Bargeld enthaltener Zahlungsansprüche.'],['t','Betrachteter Bewertungszeitpunkt.']]),
  X('Vom Anspruch zum Bargeld','Hundert Aktien notieren unmittelbar vor der Abtrennung einer angekündigten Dividende bei 50. Die Dividende beträgt zwei je Aktie. Keine neuen Informationen, Steuern oder Gebühren; der kurze Zahlungsaufschub wird nicht abgezinst.',[
   T(['Zeitpunkt','Aktienwert','Separater Anspruch','Bargeld','Gesamtwert'],[['Vor Ex-Tag','5.000','0','0','5.000'],['Nach Abtrennung, vor Auszahlung','4.800','200','0','5.000'],['Nach Auszahlung, unveränderter Kurs','4.800','0','200','5.000']],'In der ersten Zeile steckt das Dividendenrecht noch im Aktienpreis. Es wird nicht zusätzlich gezählt.'),
   'Am Auszahlungstag wird im Modell ein Anspruch in Bargeld verwandelt. Es entsteht nicht ein zweiter Anspruch über 200. Wer nur den Aktienkurs betrachtet, sieht am Ex-Tag einen Rückgang; wer die Dividende zusätzlich schon vor dem Ex-Tag zählt, überschätzt dagegen das Anfangsvermögen.'
  ],'Die Form eines Vermögenswerts kann wechseln, ohne dass dadurch allein neues Vermögen entsteht.'),
  'Bei längeren Zahlungsabständen oder relevantem Ausfallrisiko ist der Anspruch zu bewerten, nicht ungeprüft zum Nennbetrag anzusetzen. Ebenso muss klar sein, ob ein Datenanbieter Dividenden bereits in einem bereinigten Kurs berücksichtigt hat.'
 ]),
 S('dates','3. Vier Termine mit verschiedenen Aufgaben','b',[
  'Declaration Date ist der Bekanntgabe- beziehungsweise Beschlusstag der konkreten Ausschüttung. Dividend Record Date bezeichnet den für die Registerzuordnung festgelegten Stichtag. Ex-Dividenden-Tag ist der erste Handelstag ohne das betreffende Dividendenrecht. Payment Date ist der Auszahlungstag. Diese Funktionen bleiben getrennt, auch wenn einzelne Termine zusammenfallen.',
  T(['Termin','Frage','Typischer Denkfehler'],[['Declaration Date','Was wurde mit welchen Bedingungen angekündigt beziehungsweise beschlossen?','Ankündigung mit sofortiger Zahlung gleichsetzen.'],['Ex-Dividenden-Tag','Wird die Aktie heute mit oder ohne diesen Anspruch gehandelt?','Am Ex-Tag kaufen und trotzdem die abgetrennte Dividende erwarten.'],['Dividend Record Date','Welche Registerbestände dienen als Grundlage der Zuteilung?','Registerstichtag ohne Handels- und Abwicklungsregeln lesen.'],['Payment Date','Wann erfolgt die vorgesehene Zahlung?','Erst die Zahlung als Zeitpunkt der Abtrennung ansehen.']],'Die tatsächliche Reihenfolge folgt der konkreten Maßnahme und den Regeln des Marktes; Sonderfälle stehen im nächsten Abschnitt.'),
  'Die registermäßige Zahlung kann zunächst an eine Verwahrstelle gehen, die sie den wirtschaftlich Berechtigten zuordnet. Bei besonderen Abwicklungsfällen können Weiterleitungsansprüche entstehen. Ein Registereintrag allein beantwortet daher nicht jede Frage nach dem endgültigen wirtschaftlichen Empfänger.',
  'Bei Prüfungsaufgaben haben ausdrücklich angegebene Termine Vorrang vor einer erinnerten Standardfolge. Die Aufgabe ist zunächst anhand dieser Daten zu lösen; eine lokale aktuelle Marktregel darf nicht stillschweigend auf jedes Land oder jedes historische Beispiel übertragen werden.'
 ]),
 S('settlement','4. T+1: Kaufdatum und Abwicklung auseinanderhalten','b',[
  'Settlement ist die Abwicklung eines bereits abgeschlossenen Geschäfts durch Lieferung und Zahlung. Nach dem derzeitigen US-Standard werden die hier betrachteten regulären Aktiengeschäfte am nächsten Geschäftstag abgewickelt: T+1. Bei einer gewöhnlichen Bardividende liegt der Ex-Tag dort in der Regel auf dem Record Date, sofern dieser ein Geschäftstag ist. Dies ist eine ausdrücklich datierte US-Konvention, keine weltweite Naturregel.',
  X('Eine gewöhnliche Zahlung in einer Woche ohne Feiertage','Für ein hypothetisches US-Unternehmen ist Freitag der angekündigte Record Date und zugleich der Ex-Tag. Die Dividende wird in der Folgewoche gezahlt. Alle Geschäfte wickeln vertragsgemäß nach T+1 ab; Montag bis Freitag sind Geschäftstage.',[
   T(['Kaufabschluss','Reguläres Settlement','Anspruch auf diese Dividende'],[['Mittwoch','Donnerstag','Ja: Kauf vor dem Ex-Tag.'],['Donnerstag','Freitag','Ja: letzter hier betrachteter Kauf mit Recht.'],['Freitag','Montag der Folgewoche','Nein: Kauf am Ex-Tag.']],'Entscheidend ist das vereinbarte Geschäft mit oder ohne Recht, nicht der Tag, an dem der Käufer erstmals einen Depotbildschirm betrachtet.'),
   'Wer schon vorher berechtigt hält und am Freitag ex Dividende verkauft, behält im normalen Fall den abgetrennten Dividendenanspruch. Der Käufer bezahlt eine Aktie ohne diesen Anspruch. Dafür benötigt der Verkäufer keinen fortgesetzten Aktienbesitz bis zum Auszahlungstag.'
  ],'Den letzten Kauf mit Anspruch erhält man aus Ex-Tag und Abwicklungsrahmen, nicht pauschal durch Abziehen zweier Kalendertage.'),
  'Wo Wochenenden, Feiertage oder ein anderer Abwicklungszyklus gelten, muss der Geschäftskalender mitgeführt werden. Für den US-Fall eines nicht geschäftstäglichen Record Date nennt Investor.gov grundsätzlich den vorhergehenden Geschäftstag als gewöhnlichen Ex-Tag. Die konkrete Bekanntmachung bleibt maßgeblich; ein alter T+2-Merksatz ist für diesen T+1-Fall ungeeignet.'
 ]),
 S('exceptions','5. Sonderfälle: Wenn der Ex-Tag nach der Zahlung liegt','a b',[
  'Bei bestimmten großen US-Barausschüttungen ab 25 Prozent des Aktienwerts wird der Ex-Tag nach der von Investor.gov beschriebenen Regel auf den Geschäftstag nach der Zahlung verschoben. Aktienausschüttungen können ebenfalls abweichende Verfahren besitzen. Dann darf die Standardfolge einer gewöhnlichen Bardividende nicht übernommen werden.',
  'Ein Due Bill ist hier eine Verpflichtung zur Weiterleitung eines Ausschüttungsanspruchs. Verkauft ein bisheriger Registerinhaber während eines Handelszeitraums, in dem das Recht noch mit der Aktie übergeht, kann er eine erhaltene Zahlung oder Aktienzuteilung an den Käufer weiterreichen müssen. Ein Kontoeingang beweist deshalb noch nicht, dass der Betrag endgültig behalten werden darf.',
  X('Ausgezahlt, aber noch mit dem Recht verkauft','Die Bekanntmachung einer besonderen Ausschüttung nennt Dienstag als Payment Date und Mittwoch als Ex-Tag. Ein Anleger, der die Zahlung zunächst erhält, verkauft am Dienstag. Die angegebenen Regeln sehen für diesen Verkauf die Weitergabe des Ausschüttungsrechts vor.',[
   'Der Dienstag liegt vor dem Ex-Tag. Der Verkäufer liefert somit den wirtschaftlichen Anspruch nach den angegebenen Regeln mit; er darf Verkaufserlös und erhaltene Ausschüttung nicht als zwei endgültig unabhängige Vorteile behandeln.',
   'Bei einem Verkauf erst am Mittwoch ex Recht wäre die Zuordnung anders. Der Unterschied kommt vom Handelsstatus der Aktie, nicht von der bloßen Reihenfolge sichtbarer Kontobuchungen.'
  ],'Zuerst die angekündigte Ex-Regel lesen, dann Register, Zahlung und eventuelle Weiterleitung abstimmen.'),
  'Die Prozentgrenze dieses US-Beispiels ist keine Definition jeder Sonderdividende und keine allgemeine globale Regel. Auch eine kleinere unregelmäßige Zahlung kann als Sonderdividende bezeichnet werden, ohne denselben Ex-Mechanismus auszulösen.'
 ]),
 S('exprice','6. Warum der theoretische Kursabschlag kein Verlustbeweis ist','a b c',[
  F('P_{ex}\\approx P_{cum}-D','Unter sonst gleichen Bedingungen geht mit der Abtrennung ein Dividendenanspruch aus dem gehandelten Aktienpaket heraus. Die vereinfachte Rechnung ignoriert Steuern, Diskontierung, Kosten und neue Informationen.',[['P_{ex}','Theoretischer Aktienkurs ohne den abgetrennten Anspruch.'],['P_{cum}','Vergleichskurs einschließlich dieses Anspruchs unmittelbar davor.'],['D','Dividende je Aktie, deren Zahlung im Modell sicher und kurzfristig ist.']]),
  'Die Auszahlung verlässt die Gesellschaft erst am Payment Date; die handelbare Aktie kann den Zahlungsanspruch jedoch schon am Ex-Tag verlieren. Genau deshalb sind Ex-Tag und Zahlungstag nicht austauschbar. Tatsächliche Kurse ändern sich außerdem durch Marktbewegungen und neue Informationen. Ein Abschlag muss daher weder exakt der Bruttodividende entsprechen noch am beobachteten Kurs überhaupt isoliert erkennbar sein.',
  X('Zwei verschiedene Nachrichten am gleichen Tag','Der Cum-Kurs beträgt 50, die abgetrennte Dividende zwei. Ohne weitere Änderung ergäbe das Modell 48. Gleichzeitig erhöht eine neue Geschäftsinformation den Wert des verbleibenden Aktienanspruchs um drei; der Ex-Kurs beträgt deshalb 51.',[
   F('R_P=\\frac{51-50}{50}=2\\%,\\qquad R_T=\\frac{51+2-50}{50}=6\\%','Die positive Kursbewegung widerlegt den Dividendenabschlag nicht: Im Modell überlagert ihn eine größere positive Wertänderung.',[['R_P','Kursrendite über das betrachtete Ereignis.'],['R_T','Gesamtrendite einschließlich des nun separaten Dividendenanspruchs.']]),
   'Ohne die neue Information wäre die Kursrendite minus vier Prozent und die Gesamtrendite null. Mit der Information beträgt der gesamte Wertzuwachs drei auf die anfänglichen fünfzig, also sechs Prozent.'
  ],'Die Dividende selbst und eine gleichzeitige neue Unternehmensinformation werden getrennt erklärt.'),
  G({id:'dividend-wealth',title:'Mehr Ausschüttung verschiebt den Wert aus der Aktie ins Bargeld',caption:'Eigener reiner Vergleich: 100 Aktien zu zunächst 50, sofortige sichere Auszahlung zwischen 0 und 10 je Aktie; keine Steuern, Kosten oder sonstigen Wertänderungen.',reading:'Der Aktienwert sinkt um genau den Betrag, der als Bargeld hinzukommt. Die Gesamtlinie bleibt bei 5.000. Dies ist eine Modellidentität, keine Prognose tatsächlicher Ex-Kurse.',plot:{x:[0,10],y:[0,5500],xTicks:[0,2,5,10],yTicks:[0,1000,3000,5000],xLabel:'Dividende je Aktie',yLabel:'Wert der Position in Geldeinheiten',series:[{name:'Aktienwert',points:[[0,5000],[10,4000]]},{name:'Bargeld',points:[[0,0],[10,1000]]},{name:'Gesamtwert',dash:true,points:[[0,5000],[10,5000]]}]}})
 ]),
 S('yield','7. Dividendenrendite, Ausschüttungsquote und Tragfähigkeit','a c',[
  F('y_D=\\frac{D_{ann}}{P},\\qquad p=\\frac{D_{ann}}{EPS},\\qquad D_{ann}=p\\,EPS','Die Dividendenrendite setzt die Jahresdividende ins Verhältnis zum Aktienpreis; die Ausschüttungsquote setzt sie ins Verhältnis zum Ergebnis je Aktie. Gleicher Zähler bedeutet nicht gleiche Aussage.',[['y_D','Jährliche Dividendenrendite auf der angegebenen Preisbasis.'],['D_{ann}','Jahresdividende je Aktie, ausdrücklich historisch oder prognostiziert.'],['P','Dazu angegebener Aktienpreis.'],['p','Ausschüttungsquote bei positivem EPS.'],['EPS','Ergebnis je Aktie für die zur Quote passende Periode und Aktienbasis.']]),
  X('Eine höhere Rendite kann aus einem schlechteren Ausblick entstehen','Eine Aktie kostet 80; die zuletzt gezahlte Jahresdividende ist vier und das historische EPS acht. Nach schwachen Nachrichten fällt der Kurs auf 40. Die nächsten Dividenden sind noch nicht beschlossen.',[
   T(['Kennzahl','Vor Kursrückgang','Nach Kursrückgang'],[['Historische Dividende je Aktie','4','4'],['Historische Dividendenrendite','5 %','10 %'],['Historische Ausschüttungsquote','50 %','50 %']],'Der Kursrückgang verändert den Nenner der Rendite, nicht rückwirkend den historischen Gewinn oder die historische Zahlung.'),
   'Erwartet der Analyst künftig nur zwei Dividende, beträgt die prognostizierte Dividendenrendite beim Kurs 40 fünf Prozent. Zehn Prozent aus der alten Dividende sind kein garantierter zukünftiger Ertrag.',
   'Selbst ein Gewinn von acht beweist nicht, dass acht Bargeld verfügbar sind. Forderungsaufbau, Investitionen, Tilgungen, Liquiditätsbedarf und Ausschüttungsbeschränkungen können die verfügbaren Mittel begrenzen.'
  ],'Eine hohe historische Dividendenrendite ist zunächst eine Rechengröße, keine Sicherheitsbewertung.'),
  'Bei negativem oder sehr kleinem EPS ist die übliche positive Ausschüttungsquote oft nicht sinnvoll interpretierbar. Sonderausschüttungen aus bestehender Kasse können zeitweise größer als der Jahresgewinn sein. Dauerhafte Tragfähigkeit beurteilt man mit erwarteten Mitteln und Verpflichtungen, nicht mit einem isolierten Quotienten.'
 ]),
 S('repurchases','8. Ein Rückkauf hat Verkäufer und verbleibende Eigentümer','a',[
  'Ein Aktienrückkauf bezahlt verkaufende Aktionäre. Erhaltene eigene Aktien werden als Treasury Shares gehalten oder eingezogen; im beschriebenen Fall sind sie anschließend nicht mehr ausstehend. Ein nicht verkaufender Anleger bekommt dadurch kein Bargeld, besitzt aber einen größeren prozentualen Anteil am kleineren verbleibenden Eigenkapital.',
  F('n_B=\\frac{B}{P_B},\\qquad N_1=N_0-\\frac{B}{P_B},\\qquad q_1=\\frac{h}{N_1}','Das feste Budget bestimmt zusammen mit dem tatsächlich bezahlten Stückpreis die zurückgekaufte Menge. Die Rechnung setzt vollständige Ausführung, keine Kosten und keine gleichzeitig neu ausgegebenen Aktien voraus.',[['n_B','Anzahl zurückgekaufter, nicht mehr ausstehender Aktien.'],['B','Tatsächlich verwendetes Rückkaufbudget.'],['P_B','Durchschnittlich gezahlter Preis je zurückgekaufter Aktie.'],['N_0,N_1','Ausstehende Aktien vor und nach dem Rückkauf.'],['h','Unveränderte Stückzahl eines nicht verkaufenden Anlegers.'],['q_1','Sein Anteil nach dem Rückkauf.']]),
  X('Größere Quote an einem kleineren Ganzen','Zehn Millionen Aktien haben zusammen einen fairen Eigenkapitalwert von einer Milliarde, einschließlich 200 Millionen überschüssiger Kasse. Die Firma kauft für 200 Millionen zu 100 je Aktie zurück. Ein Anleger behält alle seine 100.000 Aktien.',[
   'Es werden zwei Millionen Aktien zurückgekauft. Acht Millionen bleiben ausstehend. Der Eigenkapitalwert nach Abfluss der Kasse beträgt im reinen Modell 800 Millionen; je verbleibender Aktie sind dies weiter 100.',
   F('q_0=\\frac{0{,}1}{10}=1\\%,\\qquad q_1=\\frac{0{,}1}{8}=1{,}25\\%,\\qquad W_1=0{,}0125\\cdot800=10','Millionen Aktien werden durch Millionen Aktien geteilt; der verbleibende Unternehmenswert wird in Millionen Geldeinheiten angegeben.',[['q_0,q_1','Anlegerquote vor und nach dem Rückkauf.'],['W_1','Wert seiner verbleibenden Beteiligung in Millionen Geldeinheiten.']]),
   'Vorher waren ein Prozent von 1.000 ebenfalls zehn Millionen. Eine höhere Quote allein ist deshalb kein Vermögensgewinn.'
  ],'Ein proportionaler Anstieg der Quote und ein proportionaler Rückgang des Unternehmenswerts können sich genau ausgleichen.'),
  'Rückkäufe können über den Markt, ein Angebot an Aktionäre oder ausgehandelte Transaktionen erfolgen. Eine Genehmigung oder Ankündigung ist noch keine ausgeführte Transaktion. Werden parallel Mitarbeiteraktien ausgegeben, kann die ausstehende Nettoaktienzahl trotz Käufen kaum sinken. Für das Ergebnis zählt die tatsächliche Aktienbewegung.'
 ]),
 S('buyback-value','9. Derselbe Rückkaufbetrag zu verschiedenen Preisen','a',[
  F('v_1=\\frac{V_0-B}{N_0-B/P_B},\\qquad v_0=\\frac{V_0}{N_0}','Bei unverändertem Wert des operativen Geschäfts sinkt der gesamte Eigenkapitalwert um die verwendete Kasse. Welche Stückzahl dieser Wert anschließend trägt, hängt vom Rückkaufpreis ab.',[['v_0,v_1','Fairer Wert je Aktie vor und nach dem reinen Rückkaufmodell.'],['V_0','Fairer Eigenkapitalwert einschließlich der verwendbaren Kasse vor Rückkauf.'],['N_0','Vorher ausstehende Aktienzahl.'],['B','Ausgegebenes Budget, hier kleiner als der Eigenkapitalwert.'],['P_B','Gezahlter Rückkaufpreis; die gekaufte Menge bleibt kleiner als N₀.']]),
  X('Zu teuer, fair oder günstig: Wer gewinnt?','Es gelten weiterhin ein fairer Ausgangswert von 1.000 Millionen, zehn Millionen Aktien und ein festes Budget von 200 Millionen. Nur der Ausführungspreis variiert. Operativer Wert, Steuern und Kosten bleiben gleich; die Firma kann die jeweils berechnete Menge zu diesem Preis kaufen.',[
   T(['Preis je Rückkaufaktie','Zurückgekauft in Mio.','Verbleibend in Mio.','Fairer Wert je verbleibender Aktie'],[['80','2,500000','7,500000','106,6667'],['100','2,000000','8,000000','100,0000'],['125','1,600000','8,400000','95,2381']],'Der verbleibende Gesamtwert beträgt in allen drei Zeilen 800 Millionen. Es ist die Aufteilung, die sich ändert.'),
   'Beim Rückkauf unter dem angenommenen fairen Wert werden mehr Ansprüche günstig eingezogen. Das nützt den verbleibenden Eigentümern relativ zu den Verkäufern. Beim überhöhten Preis wird weniger Beteiligung für dasselbe Geld eingezogen; die verbleibenden Eigentümer tragen den Werttransfer.',
   'Die Ausgangsbewertung ist eine Modellannahme, kein direkt beobachtbarer sicherer Wert. In Wirklichkeit können Informationssignale, Preiseffekt der Orders und geänderte Finanzierung den Wert des Geschäfts verändern. Aus „Management kauft zurück“ folgt daher nicht automatisch „Aktie ist unterbewertet“.'
  ],'Rückkaufmenge und Preis gehören zusammen; das ausgegebene Budget allein erklärt die Wertwirkung nicht.'),
  G({id:'buyback-price',title:'Ein teurerer Rückkauf lässt weniger Wert je verbleibender Aktie',caption:'Eigene Modellrechnung: fairer Eigenkapitalwert 1.000 Mio., zehn Mio. Aktien, Rückkaufbudget 200 Mio.; nur der bezahlte Preis variiert.',reading:'Bei Preis 100 bleibt der faire Wert je Aktie 100. Unterhalb davon profitiert im Modell der verbleibende Anleger; oberhalb davon sinkt sein Wert. Die Kurve ist keine Behauptung, dass der faire Ausgangswert sicher bekannt wäre.',plot:{x:[80,125],y:[94,108],xTicks:[80,100,125],yTicks:[95,100,105],xLabel:'Bezahlter Rückkaufpreis je Aktie',yLabel:'Fairer Wert je verbleibender Aktie',series:[{name:'Verbleibender Wert',points:Array.from({length:46},(_,i)=>{const p=80+i;return[p,800/(10-200/p)];})},{name:'Ausgangswert je Aktie',dash:true,points:[[80,100],[125,100]]}],marks:[{x:100,y:100,label:'Fairer Rückkauf',dx:12,dy:20}]}})
 ]),
 S('eps','10. Warum EPS steigen kann, ohne dass Wert entsteht','a',[
  'Ein kleinerer Nenner erhöht EPS nur bei entsprechender Entwicklung des Zählers. Zur Finanzierung genutzte Kasse kann Zinserträge verlieren; Fremdfinanzierung kann zusätzlichen Zinsaufwand verursachen. Die folgende Vertiefung untersucht eine vollständige Folgeperiode nach dem Rückkauf. Für den veröffentlichten Abschluss einer laufenden Periode ist dagegen die zeitgewichtete durchschnittliche Aktienzahl relevant.',
  F('EPS_1=\\frac{NI_0-Bk}{N_0-B/P_B},\\qquad EPS_1>EPS_0\\iff k<\\frac{EPS_0}{P_B}','Bei positiver verbleibender Aktienzahl steigt das Folgeperioden-EPS genau dann, wenn die hier modellierten Nachsteuerkosten je Budgeteinheit kleiner sind als die ursprüngliche Ergebnisrendite zum Rückkaufpreis.',[['EPS_0,EPS_1','Ergebnis je Aktie ohne und mit dem Rückkauf in der vergleichbaren vollständigen Folgeperiode.'],['NI_0','Ergebnis derselben Periode ohne Rückkauf.'],['B','Rückkaufbudget.'],['k','Verlorener Nachsteuerertrag der Kasse oder zusätzliche Nachsteuerfinanzierungskosten pro Jahr.'],['N_0','Ohne Rückkauf ausstehende Aktien.'],['P_B','Rückkaufpreis je Aktie.']]),
  F('\\frac{NI_0-Bk}{N_0-B/P_B}>\\frac{NI_0}{N_0}\\iff N_0NI_0-N_0Bk>N_0NI_0-\\frac{NI_0B}{P_B}\\iff k<\\frac{NI_0}{N_0P_B}','Beide Nenner sind positiv. Nach Ausmultiplizieren fällt der identische Ausgangsterm weg; anschließend wird durch das positive Budget und die positive Aktienzahl dividiert.',[['NI_0','Ergebnis ohne Rückkauf in der vergleichbaren Folgeperiode.'],['B','Positives Rückkaufbudget.'],['k','Jährliche Nachsteuerkosten je Budgeteinheit.'],['N_0','Positive ursprüngliche Aktienzahl.'],['P_B','Positiver Rückkaufpreis; N₀ minus B geteilt durch P_B bleibt positiv.']]),
  'Der Vorteil aus weniger Aktien muss den Ergebnisverlust durch Finanzierung übersteigen. Die Bedingung sagt etwas über EPS, aber noch nichts über Kapitalkosten, Risiko und fairen Eigenkapitalwert aus.',
  X('Identisches Geschäft, unterschiedliche Finanzierungskosten','Vor dem Rückkauf: Ergebnis 80 Millionen, zehn Millionen Aktien, EPS acht. Rückkaufbudget 200 Millionen zu Preis 100; danach acht Millionen Aktien. Die angegebenen jährlichen Kosten sind bereits nach Steuern.',[
   T(['Kostenquote','Ergebnis nach Kosten in Mio.','EPS nach Rückkauf'],[['0 %','80','10,00'],['3 %','74','9,25'],['8 %','64','8,00'],['10 %','60','7,50']],'Die Schwelle ist acht geteilt durch hundert, also acht Prozent. Ein kleinerer Nenner garantiert keinen EPS-Anstieg.'),
   'Selbst die erste Zeile beweist keinen Wertzuwachs: Im fairen Rückkaufmodell des vorigen Abschnitts blieb der Wert je Aktie trotz EPS-Anstieg unverändert. Das Verhältnis von Kurs zu EPS würde entsprechend sinken, wenn beide Größen tatsächlich vergleichbar wären.'
  ],'Eine Kennzahlenverbesserung und eine Verbesserung des wirtschaftlichen Werts sind getrennte Behauptungen.'),
  'Dies ist ein vereinfachtes Finanzierungsmodell, keine vollständige Gewinnprognose. Zinsabzugsgrenzen, schwankende Zinsen, neue Aktien, veränderte Geschäftsaussichten und eine andere Risikoprämie können das Ergebnis ändern.'
 ]),
 S('policy','11. Ausschüttungspolitik als Kapitalverwendungsentscheidung','a',[
  'Vor einer Ausschüttung steht die Frage, welches Kapital für Betrieb, sinnvolle Investitionen und finanziellen Spielraum gebraucht wird. Ein gutes Projekt kann trotz niedriger Dividende Wert schaffen; eine hohe Ausschüttung kann die Aufgabe wertvoller Investitionen erzwingen. Umgekehrt können überschüssige Mittel im Unternehmen schlecht eingesetzt werden. Der Zusammenhang führt direkt zur Kapitalwertrechnung und zu Agency-Konflikten.',
  T(['Frage','Warum sie für die Wahl relevant ist'],[['Dauerhafter oder einmaliger Überschuss?','Eine regelmäßige Zahlung schafft andere Erwartungen als eine einmalige Ausschüttung.'],['Verkaufen einige Eigentümer freiwillig?','Beim Rückkauf konzentriert sich der direkte Geldzufluss auf Verkäufer.'],['Steuern und Kosten?','Die Nettoergebnisse können zwischen Anlegern und Rechtsordnungen abweichen.'],['Preis und Ausführbarkeit des Rückkaufs?','Ein günstiger oder überhöhter Preis verteilt Wert unterschiedlich.'],['Beschränkungen und Verpflichtungen?','Kreditverträge, Kapitalbedarf und rechtliche Grenzen können verfügbare Kasse binden.']],'Keine einzelne Ausschüttungsform ist in jeder Situation für alle Beteiligten überlegen.'),
  X('Selbst erzeugter Geldzufluss im idealisierten Vergleich','Ein Anleger hält hundert Aktien zu 50. Er möchte 200 Bargeld. Ohne Steuern, Kosten, Bruchteilprobleme oder Wertänderungen stehen zwei gedachte Alternativen zur Verfügung.',[
   'Bei Dividende zwei je Aktie besitzt er danach hundert Aktien zu 48 sowie 200 Bargeld: zusammen 5.000.',
   'Ohne Dividende verkauft er vier Aktien zu 50. Er besitzt danach 96 Aktien zu 50 sowie 200 Bargeld: ebenfalls 5.000. Die Stückzahl ist verschieden, der unmittelbar verglichene Gesamtwert gleich.',
   'Das ist eine mechanische Gleichwertigkeit unter engen Voraussetzungen. In der Realität können Verkaufsgebühren, Besteuerung, Restriktionen und eine veränderte Investitionspolitik den Vergleich verändern.'
  ],'Der Wunsch nach laufendem Bargeld und die Frage nach neu geschaffenem Wert werden getrennt beantwortet.'),
  'Ausschüttungsankündigungen können Erwartungen verändern, beispielsweise über künftige Mittel oder Investitionsmöglichkeiten. Solche Signale sind interpretationsbedürftig: Eine Kürzung kann finanzielle Not anzeigen oder Mittel für ein attraktives Projekt erhalten. Eine reine Vorzeichenregel ersetzt keine Analyse der konkreten Ursache.'
 ]),
 S('stock-dividend','12. Stock Dividend: Mehr identische Aktien','a c',[
  'Eine proportionale Stock Dividend eigener identischer Aktien teilt zusätzliche Stücke zu, ohne allein dadurch den gesamten Eigenkapitalwert zu erhöhen. Die prozentuale Beteiligung jedes vollständig proportional berücksichtigten Eigentümers bleibt gleich. Das gilt nicht automatisch für Ausschüttungen fremder Wertpapiere, Wahlrechte oder eine abweichende Behandlung einzelner Anleger.',
  F('n_1=n_0(1+s),\\qquad P_1=\\frac{P_0}{1+s},\\qquad n_1P_1=n_0P_0','Wird nur die Zahl identischer Anteile vergrößert, verteilt sich derselbe Gesamtwert auf mehr Stücke. Die theoretische Preisanpassung ist durch Division herzuleiten.',[['n_0,n_1','Aktienzahl eines proportional beteiligten Anlegers vorher und nachher.'],['s','Zusätzlich zugeteilte Aktien als Anteil der alten Aktien, etwa 0,10 für zehn Prozent.'],['P_0,P_1','Theoretischer Stückpreis vor und nach der reinen Umstückelung.']]),
  X('Zehn Prozent mehr Aktien bedeuten nicht zehn Prozent Rendite','Ein Anleger besitzt zweihundert Aktien zu 55. Jede zehnte alte Aktie berechtigt zu einer zusätzlichen identischen Aktie; keine Bruchteile, Kosten oder weiteren Wertänderungen.',[
   F('n_1=200\\cdot1{,}10=220,\\qquad P_1=\\frac{55}{1{,}10}=50,\\qquad W_1=220\\cdot50=11000','Der Divisor 1,10 hält den Gesamtwert konstant. Ein Preisabschlag von einfach zehn Prozent wäre mathematisch falsch.',[['n_1','Neue Aktienzahl.'],['P_1','Theoretischer neuer Stückpreis.'],['W_1','Aktienwert nach Zuteilung.']]),
   '55 minus zehn Prozent wäre 49,50. Zweihundertzwanzig Aktien zu diesem Preis wären nur 10.890 wert, obwohl der Vorgang im Modell keine 110 vernichtet. Die falsche Rechnung verwechselt zusätzliche Stücke relativ zur alten Zahl mit dem Preisrückgang relativ zum alten Preis.'
  ],'Gegenläufige prozentuale Änderungen benötigen unterschiedliche Bezugsgrößen.'),
  'Bilanzielle Umbuchungen innerhalb des Eigenkapitals hängen von der Maßnahme und den Rechnungslegungsvorschriften ab. Sie schaffen im reinen Modell kein zusätzliches Gesamtvermögen. Der Anleger sollte daher neue Stückzahl, Rechte und Wert statt allein die Bezeichnung der Kapitalmaßnahme vergleichen.'
 ]),
 S('splits','13. Aktiensplit: Verhältnis statt Rendite','a c',[
  F('k=\\frac{a}{b},\\qquad n_1=kn_0,\\qquad P_1=\\frac{P_0}{k}','Ein a-für-b-Split gibt für b alte Aktien a neue. Die Aktienzahl wird mit demselben Faktor multipliziert, durch den der theoretische Preis dividiert wird.',[['a,b','Anzahl neuer beziehungsweise alter Aktien im angekündigten Verhältnis.'],['k','Neue Stücke je altem Stück.'],['n_0,n_1','Bestand vor und nach Umstückelung.'],['P_0,P_1','Theoretischer Preis je alter und neuer Aktie ohne sonstige Wertänderung.']]),
  X('Ein Verhältnis, drei gleichzeitig anzupassende Größen','Eine Gesellschaft mit sechs Millionen Aktien zu 90 führt einen Drei-für-zwei-Split durch. Ein Anleger hält vierzig Aktien. Das Gesamtjahresergebnis bleibt 36 Millionen.',[
   T(['Größe','Vorher','Nach reiner Umstückelung'],[['Ausstehende Aktien','6 Mio.','9 Mio.'],['Aktien des Anlegers','40','60'],['Preis je Aktie','90','60'],['Marktkapitalisierung','540 Mio.','540 Mio.'],['Wert des Anlegerbestands','3.600','3.600'],['Vergleichbares EPS bei voller Anpassung','6','4']],'Der Split verändert weder den Gesamtgewinn noch den Eigentumsanteil. Per-Share-Zahlen müssen auf dieselbe Aktienbasis gebracht werden.'),
   'Ein späterer Kursanstieg von 60 auf 66 ergibt zehn Prozent Kursrendite nach dem Split. Gegenüber dem alten Kurs 90 darf man nicht minus 26,67 Prozent rechnen: Der Anleger besitzt inzwischen anderthalbmal so viele Stücke.'
  ],'Vorher-nachher-Vergleiche sind nur mit konsistenter Stückelung sinnvoll.'),
  'Ein Split kann den nominalen Preis für Handel und Wahrnehmung verändern. Ob er Zugang oder Liquidität verbessert, hängt unter anderem von Stückelungsregeln, Bruchteilhandel, Tick Size und Anlegerstruktur ab. Aus einem kleineren Stückpreis folgt keine billigere Bewertung des Unternehmens.'
 ]),
 S('reverse','14. Reverse Split und Bruchteile','a c',[
  'Ein Reverse Split legt mehrere alte Aktien zu weniger neuen zusammen. Er kann etwa einen nominal niedrigen Kurs anheben. Er behebt dadurch allein weder operative Verluste noch Überschuldung. Notierungsanforderungen und Zustimmungsvoraussetzungen sind markt- und gesellschaftsspezifisch.',
  X('Fünf alte Stücke werden ein neues','Tausend Aktien zu zwei werden in einem Eins-für-fünf-Reverse-Split umgestellt. Sonst ändert sich nichts.',[
   F('n_1=1000\\cdot\\frac15=200,\\qquad P_1=2\\cdot5=10,\\qquad W_1=200\\cdot10=2000','Fünfmal höherer Stückpreis trifft auf ein Fünftel der Stückzahl.',[['n_1','Neue Aktienzahl des Anlegers.'],['P_1','Theoretischer neuer Stückpreis.'],['W_1','Unveränderter Gesamtwert.']]),
   'Der Preisanstieg von zwei auf zehn ist keine Rendite von vierhundert Prozent. Erst ein Preis oberhalb des angepassten Vergleichswerts zehn würde bei sonst gleichen Bedingungen einen Wertzuwachs zeigen.'
  ],'Eine geänderte Maßeinheit darf nicht als Anlageerfolg erscheinen.'),
  X('Wenn der Bestand nicht glatt aufgeht','Ein Anleger hält 103 alte Aktien zu zwei. Nach einem Eins-für-fünf-Reverse-Split entspricht dies 20,6 neuen Aktien. Laut ausdrücklich angenommener Regel erhält er zwanzig ganze Aktien und sechs Bargeld für den Bruchteil; neuer theoretischer Kurs zehn, keine Kosten.',[
   F('W_1=20\\cdot10+6=206=103\\cdot2','Der Bruchteil von 0,6 neuen Aktien wird hier mit zehn je neuer Aktie abgefunden.',[['W_1','Gesamtwert aus ganzen Aktien und Bruchteilsabfindung.']]),
   'Ohne die sechs Bargeld würde die Renditerechnung fälschlich einen Verlust zeigen. In einer echten Maßnahme muss der tatsächliche Abfindungspreis aus den Bedingungen beziehungsweise der Abrechnung stammen; es gibt keinen universell garantierten theoretischen Preis.'
  ],'Auch kleine Ausgleichszahlungen gehören in das Vermögenskonto.')
 ]),
 S('normalization','15. Historische Kurse und Dividenden auf dieselbe Basis bringen','a c',[
  'Ein roher Kursvergleich über einen Split hinweg vergleicht unterschiedliche Beteiligungsmengen. Entweder führt man die tatsächliche Aktienzahl und die erhaltenen Zahlungen fort, oder man passt alle historischen Per-Share-Daten konsistent an. Beide Wege müssen zum selben Ergebnis führen.',
  X('Splitbereinigung ist etwas anderes als Dividendenwiederanlage','Zu Beginn kosten hundert Aktien je 90. Danach erfolgt ein Drei-für-zwei-Split; es werden 150 Aktien gehalten. Eine Dividende von zwei je neuer Aktie wird gezahlt und als unverzinstes Bargeld behalten. Der Endkurs je neuer Aktie ist 64.',[
   F('R_P=\\frac{150\\cdot64-100\\cdot90}{100\\cdot90}=6{,}6667\\%,\\qquad R_T=\\frac{150\\cdot64+150\\cdot2-100\\cdot90}{100\\cdot90}=10\\%','Die tatsächlichen Stückzahlen machen die veränderte Einheit ausdrücklich sichtbar.',[['R_P','Kursrendite des Bestands nach korrekter Splitberücksichtigung.'],['R_T','Gesamtrendite einschließlich der gehaltenen Bardividende.']]),
   'Auf neue Stücke umgerechnet beträgt der alte Einstand 60. Daher ergeben 64 gegenüber 60 dieselbe Kursrendite und 64 plus zwei gegenüber 60 dieselbe Gesamtrendite. Auf alte Stücke umgerechnet entsprechen Endkurs und Dividende dagegen 96 und drei.',
   'Wer 64 mit 90 vergleicht, erzeugt einen künstlichen Verlust. Wer zwei Dividende je neuer Aktie nur mit den hundert alten Aktien multipliziert, lässt ein Drittel der tatsächlichen Zahlung weg.'
  ],'Anpassungsfaktor, Dividendenbasis und tatsächlicher Bestand müssen übereinstimmen.'),
  'Adjusted Close kann je nach Datenanbieter nur Splits oder zusätzlich Ausschüttungen mit einer bestimmten Wiederanlagemethodik berücksichtigen. Vor Verwendung ist die Dokumentation zu lesen. Wenn eine Reihe Ausschüttungen bereits in ihrer Rendite erfasst, darf dieselbe Dividende nicht nochmals im Zähler addiert werden. Ein Etikett ersetzt die Prüfung der Berechnung nicht.'
 ]),
 S('returns','16. Kursrendite und Gesamtrendite herleiten','c',[
  F('R_P=\\frac{P_1-P_0}{P_0},\\qquad R_T=\\frac{P_1-P_0+D}{P_0}=R_P+\\frac{D}{P_0}','Auf konsistenter Aktienbasis wird der gesamte Wertzuwachs durch den Anfangswert geteilt. D ist hier die im Zeitraum zustehende Ausschüttung, die als Bargeld ohne Zwischenverzinsung gehalten beziehungsweise zum Periodenende gezahlt wird.',[['R_P','Kursrendite über genau die betrachtete Haltedauer.'],['R_T','Gesamtrendite über dieselbe Haltedauer ohne Steuern und Gebühren.'],['P_0,P_1','Anfangs- und Endpreis auf gleicher, gegebenenfalls splitbereinigter Basis.'],['D','Summe der zur gehaltenen Aktie gehörenden Ausschüttungen auf dieser Basis.']]),
  X('Gleiche Dividende, unterschiedliche Ergebnisse','Eine Aktie kostet zu Beginn 80 und schüttet vier aus. Die Zahlung erfolgt am Periodenende. Nur der Endkurs variiert; kein Split oder zusätzlicher Geldfluss.',[
   T(['Endkurs','Kursrendite','Dividendenbeitrag','Gesamtrendite'],[['72','−10 %','5 %','−5 %'],['80','0 %','5 %','5 %'],['88','10 %','5 %','15 %']],'Die identische Dividende begrenzt den Kursverlust nicht automatisch. Ein positiver Ausschüttungsbeitrag kann neben einer negativen Gesamtrendite stehen.'),
   'Im ersten Fall sind nach dem Jahr 72 Aktienwert plus vier Bargeld vorhanden. Gegenüber achtzig fehlen vier, also fünf Prozent. Die Aussage „fünf Prozent Dividendenrendite verdient“ ist als Beschreibung eines Renditebausteins richtig, als Beschreibung des gesamten Ergebnisses falsch.'
  ],'Bei jeder Rendite angeben: welcher Zeitraum, welche Preisbasis, welche Ausschüttungen und welche Wiederanlage.'),
  'Ein Rückkauf ist keine zusätzliche Bardividende an einen Anleger, der gar nicht verkauft. Seine Wirkung steckt in dessen Bestand, Anteilsquote und Kurs. Die gesamten Unternehmensrückkäufe nochmals als persönlichen Cashflow zu seiner Kursrendite zu addieren wäre falsch.'
 ]),
 S('reinvestment','17. Wiederanlage: Jede Dividende kauft neue Ansprüche','a c',[
  'Ein Dividend Reinvestment Plan verwendet die erhaltene Dividende zum Kauf weiterer Aktien nach seinen Bedingungen. Für das Modell werden Zahlung und Wiederanlage am jeweiligen Periodenende zum angegebenen Ex-Preis zusammengelegt. In der Praxis können Zahlungstag, Ausführungspreis, Gebühren, Rabatte und Bruchteilregeln abweichen.',
  F('n_t=n_{t-1}\\left(1+\\frac{D_t}{P_t}\\right),\\qquad 1+R_{cum}=\\prod_{t=1}^{T}\\frac{P_t+D_t}{P_{t-1}}','Die Ausschüttung aus allen vorher gehaltenen Aktien kauft zusätzliche Stücke. Wird jede Zahlung sofort vollständig wiederangelegt, multiplizieren sich die periodischen Gesamtrenditefaktoren.',[['n_t,n_{t-1}','Bestand nach beziehungsweise vor der Wiederanlage am Ende von Periode t.'],['D_t','Ausschüttung je bis dahin gehaltener Aktie am Ende dieser Periode.'],['P_t,P_{t-1}','Preis am aktuellen beziehungsweise vorigen Periodenende auf konsistenter Aktienbasis.'],['R_{cum}','Kumulierte Gesamtrendite mit der beschriebenen Wiederanlage.'],['t,T','Laufender Periodenindex und Anzahl der Perioden; das Produkt umfasst alle Perioden von eins bis T.']]),
  X('Die zweite Dividende wird auf mehr Aktien gezahlt','Anfangs hundert Aktien zu 100. Ende Jahr eins: Kurs 100, Dividende zehn. Ende Jahr zwei: Kurs 120, Dividende sechs. Bruchteile sind zulässig; keine Steuern oder Kosten.',[
   T(['Schritt','Rechnung','Ergebnis'],[['Erste Dividende','100 × 10','1.000 Bargeld'],['Erster Wiederanlagekauf','1.000 / 100','10 zusätzliche Aktien'],['Zweite Dividende','110 × 6','660 Bargeld'],['Zweiter Wiederanlagekauf','660 / 120','5,5 zusätzliche Aktien'],['Endbestand','115,5 × 120','13.860 Aktienwert']],'Nach der letzten Wiederanlage wird die bereits investierte Dividende nicht zusätzlich als Bargeld mitgerechnet.'),
   F('R_1=10\\%,\\quad R_2=\\frac{120+6-100}{100}=26\\%,\\quad R_{cum}=1{,}10\\cdot1{,}26-1=38{,}6\\%','Die Verkettung liefert denselben Endwert wie das Aktienkonto: 10.000 mal 1,386.',[['R_1,R_2','Gesamtrenditen der ersten und zweiten Jahresperiode.'],['R_{cum}','Zweijahresrendite mit vollständiger Wiederanlage.']]),
   'Die einfache Summe zehn plus sechsundzwanzig ergibt 36 Prozent und ignoriert hier den Ertrag auf die im ersten Jahr erworbenen zusätzlichen Ansprüche. Zinseszinseffekt ist eine Multiplikation von Vermögensfaktoren.'
  ],'Wiederanlage verändert den künftigen Bestand und damit den späteren Dividendenbetrag.')
 ]),
 S('cash-comparison','18. Wiederanlage ist eine zusätzliche Risikoentscheidung','a c',[
  'Bleiben Dividenden als unverzinstes Bargeld liegen, bleibt die Aktienzahl im selben Beispiel hundert. Der Anleger besitzt am Ende 12.000 Aktienwert und 1.600 Bargeld, zusammen 13.600. Die Zweijahresrendite beträgt 36 Prozent. Das ist eine andere Strategie als die durchgängige Wiederanlage, kein Rechenfehler.',
  X('Ein fallender Kurs kehrt den Vorteil um','Die erste Jahresperiode bleibt unverändert: Kurs 100 und Dividende zehn. In der zweiten Periode fällt der Endkurs jedoch auf 80; die Dividende bleibt sechs. Steuer- und Kostenannahmen bleiben gleich.',[
   F('W_R=110(80+6)=9460,\\qquad W_C=100\\cdot80+100(10+6)=9600','Mit Wiederanlage wirken die zusätzlichen zehn Aktien auf Kursbewegung und zweite Dividende. Ohne Wiederanlage bleiben die ersten tausend als unverzinstes Bargeld erhalten.',[['W_R','Endvermögen der Wiederanlagestrategie; letzte Zahlung darf als Bargeld oder sofort wiederangelegt bewertet werden.'],['W_C','Endvermögen der Strategie mit sämtlichen Dividenden in unverzinstem Bargeld.']]),
   'Die Renditen sind minus 5,4 und minus vier Prozent. Die zusätzlichen Aktien erhalten zwar ebenfalls eine Dividende, ihr Wertverlust ist aber größer. Ein Dividend Reinvestment Plan ist deshalb keine Versicherung gegen fallende Kurse.'
  ],'Mehr langfristige Aktienexponierung kann helfen oder schaden; die Kursfolge entscheidet.'),
  G({id:'reinvestment-path',title:'Welche Strategie vorne liegt, hängt vom zweiten Endkurs ab',caption:'Eigener Zweijahresfall: Anfang hundert Aktien zu 100; Jahr eins Preis 100 und Dividende zehn, Jahr zwei Dividende sechs. Nur der zweite Endkurs variiert. Bargeld wird nicht verzinst.',reading:'Beide Strategien treffen sich beim Endkurs 94, weil eine in Jahr eins wiederangelegte Einheit dann einschließlich der zweiten Dividende genau ihren Einsatz zurückliefert. Oberhalb hilft die Wiederanlage, darunter schadet sie im Vergleich zum unverzinsten Bargeld.',plot:{x:[60,140],y:[-30,65],xTicks:[60,80,94,120,140],yTicks:[-20,0,20,40,60],xLabel:'Aktienkurs am Ende des zweiten Jahres',yLabel:'Gesamtrendite über zwei Jahre in Prozent',series:[{name:'Jede Dividende wiederangelegt',points:[[60,1.1*66-100],[140,1.1*146-100]]},{name:'Dividenden als unverzinstes Bargeld',points:[[60,-24],[140,56]]}],marks:[{x:94,y:10,label:'Gleicher Endwert',dx:10,dy:20}]}}),
  'Entnimmt der Anleger die Dividenden aus der abgegrenzten Strategie, statt sie dort als Bargeld zu halten, braucht die Performancerechnung eine passende Behandlung externer Geldflüsse. Der Abschnitt über zeit- und geldgewichtete Renditen erklärt diesen Unterschied. Hier ist Bargeld ausdrücklich Teil des verglichenen Endvermögens.'
 ]),
 S('costs','19. Brutto, netto und tatsächlicher Kapitaleinsatz','c',[
  F('R_{net}=\\frac{nP_1-F_S+nD(1-\\tau_D)-(nP_0+F_B)}{nP_0+F_B}','Bei unveränderter Aktienzahl werden Endverkaufserlös nach Gebühr und Nettodividende mit dem tatsächlichen Anfangseinsatz einschließlich Kaufgebühr verglichen. Eine Steuer auf Kursgewinne ist in dieser ausdrücklich vereinfachten Aufgabe nicht vorgesehen.',[['R_{net}','Nettorendite unter den angegebenen Kosten- und Steuerannahmen.'],['n','Durchgehend gehaltene Aktienzahl.'],['P_0,P_1','Kauf- und Verkaufspreis je Aktie.'],['F_B,F_S','Gesamte Kauf- beziehungsweise Verkaufsgebühr.'],['D','Bruttodividende je Aktie während der Haltedauer, hier ohne Wiederanlage.'],['\\tau_D','Angenommener effektiver Steuersatz allein auf diese Dividende.']]),
  X('Zehn Prozent brutto sind nicht zehn Prozent nach Kosten','Hundert Aktien werden zu 50 gekauft und zu 53 verkauft. Dividende zwei je Aktie; 25 Prozent Steuer ausschließlich auf die Dividende. Kauf- und Verkaufsgebühr jeweils zehn; keine weiteren Steuern, Zinsen oder Zahlungen.',[
   'Der Anfangseinsatz beträgt 5.010. Der Nettoverkaufserlös ist 5.290; von zweihundert Bruttodividende bleiben 150. Das Endvermögen beträgt 5.440, der Überschuss über den Einsatz 430.',
   F('R_{net}=\\frac{5440-5010}{5010}=8{,}5828\\%,\\qquad R_{gross}=\\frac{53+2-50}{50}=10\\%','Fünfzig Dividendensteuer und zwanzig Gebühren mindern den Gewinn gegenüber dem Bruttovergleich. Zusätzlich ist der tatsächliche Anfangseinsatz um zehn höher.',[['R_{net}','Nettorendite auf den vollständigen Kapitaleinsatz.'],['R_{gross}','Kosten- und steuerfreie Rendite auf den reinen Aktienkaufpreis.']]),
   '430 durch 5.000 wäre keine Rendite auf den vollständigen tatsächlichen Einsatz. Ebenso wäre ein pauschaler Abzug von 25 Prozent der gesamten Bruttorendite falsch: Im Fall wird nur die Dividende besteuert.'
  ],'Jede Steuer und Gebühr muss auf die in der Aufgabe bezeichnete Basis angewandt werden.'),
  'Reale Steuerregime können Kursgewinne, Quellensteueranrechnung, Verlustverrechnung und Zeitpunkte anders behandeln. Das Beispiel ist eine offengelegte Rechenkonvention, keine allgemeine Aussage über einen bestimmten Anlegerstaat.'
 ]),
 S('horizon','20. Vergleichbare Zeiträume und Währungen','c',[
  F('R_{ann}=(1+R_H)^{1/H}-1','Eine mehrjährige Gesamtrendite wird über einen äquivalenten konstanten jährlichen Wachstumsfaktor annualisiert, nicht durch bloße Division des Prozentwerts.',[['R_{ann}','Geometrisch annualisierte Rendite.'],['R_H','Kumulierte Rendite über den gesamten betrachteten Zeitraum.'],['H','Länge dieses Zeitraums in Jahren; hier positiv und mit positivem Endvermögensfaktor.']]),
  X('Der Zweijahresfall als Jahresvergleich','Die Wiederanlagestrategie endet nach zwei Jahren bei 13.860 aus einem Anfangseinsatz von 10.000. Keine weiteren Ein- oder Auszahlungen.',[
   F('R_{ann}=\\sqrt{1{,}386}-1\\approx17{,}7285\\%','Dieser jährliche Faktor führt bei zweimaliger Multiplikation wieder zum tatsächlichen Endvermögensfaktor.',[['R_{ann}','Äquivalente jährliche Rendite für genau diesen Zweijahrespfad.']]),
   '38,6 geteilt durch zwei wäre 19,3 Prozent. Würde man tatsächlich zweimal 19,3 Prozent erzielen, läge der Endwert über 13.860. Die Division ignoriert die jährliche Wiederverzinsung.'
  ],'Haltedauerrendite und annualisierte Rendite beantworten unterschiedliche Fragen.'),
  'Bei Fremdwährungsaktien kommen die Wechselkursbewegungen hinzu. Werden sämtliche in Fremdwährung verbleibenden Werte erst am Ende umgerechnet, multiplizieren sich Aktien- und Währungsfaktor. Werden Dividenden schon früher in die Heimatwährung konvertiert, muss jede Zahlung mit ihrem damaligen Wechselkurs erfasst werden. Ein einziger Schlusskurs für die gesamte Periode wäre dann eine andere Strategie.'
 ]),
 S('case','21. Ein vollständiger Fall mit Split, Dividende und Teilverkauf','a b c',[
  X('Das Depotkonto als gemeinsame Kontrollrechnung','Anfangs zweihundert Aktien zu 60. Danach erfolgt ein Zwei-für-eins-Split. Für alle vierhundert neuen Aktien entsteht vor einem späteren Teilverkauf ein Dividendenanspruch von 1,50 je neuer Aktie. Er wird ohne Wiederanlage gezahlt. Anschließend werden hundert neue Aktien zu 32 verkauft; die übrigen dreihundert stehen am Periodenende bei 35. Keine Steuern, Gebühren oder Bargeldzinsen; alle Verkaufserlöse bleiben in der Strategie.',[
   T(['Vorgang','Aktienbestand danach','Bargeld / Anspruch danach'],[['Anfangseinsatz','200 alte Aktien','0'],['Zwei-für-eins-Split','400 neue Aktien','0'],['Dividende für 400 neue Aktien','400 neue Aktien','600 Anspruch, später Bargeld'],['Verkauf von 100 neuen Aktien zu 32','300 neue Aktien','3.800 Bargeld nach Zahlung und Verkauf'],['Endbewertung zu 35','300 neue Aktien im Wert von 10.500','3.800 Bargeld']],'Der spätere Verkauf löscht den zuvor bereits abgetrennten Anspruch des Verkäufers nicht. Nur der verbleibende Bestand wird zum Endkurs bewertet.'),
   F('W_0=200\\cdot60=12000,\\quad W_1=300\\cdot35+100\\cdot32+400\\cdot1{,}50=14300','Die drei Endwertbestandteile sind verbleibende Aktien, im Depot gehaltene Verkaufserlöse und gezahlte Dividenden. Kein Bestandteil wird doppelt gezählt.',[['W_0','Ursprünglicher Kapitaleinsatz.'],['W_1','Endvermögen der gesamten Strategie.']]),
   F('R=\\frac{14300-12000}{12000}=19{,}1667\\%','Da Erlöse und Dividenden innerhalb der Strategie verbleiben, gibt es nach dem Anfangseinsatz keine externen Geldflüsse.',[['R','Gesamtrendite der beschriebenen Strategie über den angegebenen Zeitraum.']]),
   'Ein reines Halten aller vierhundert Aktien bis zum Endkurs hätte 14.600 ergeben. Die Differenz von 300 entsteht daraus, dass hundert Aktien zu 32 statt zum späteren Wert 35 in Bargeld umgewandelt wurden. Sie kommt weder vom Split noch von einem verlorenen Dividendenanspruch.'
  ],'Das Aktien- und Bargeldkonto erklärt sowohl die Gesamtrendite als auch den Einfluss der einzelnen Entscheidung.')
 ]),
 S('review','22. Prüfungslogik und Grenzen der Modelle','a b c',[
  T(['Kontrollfrage','Begründeter Lösungsweg'],[['Welche Ansprüche sind überhaupt im Anfangskurs enthalten?','Cum- und Ex-Status sowie eventuell separat erfasste Forderungen feststellen.'],['Welche Stückzahl ist richtig?','Jede Ausgabe, jeden Rückkauf, Split und tatsächlichen Verkauf zeitlich fortschreiben.'],['Wem steht die Dividende zu?','Angegebenen Ex-Tag, Settlement und Sonderregeln einschließlich Due Bills prüfen.'],['Wird Bargeld gehalten, entnommen oder wiederangelegt?','Nur mit derselben Strategie sind Renditen vergleichbar.'],['Ist EPS-Wachstum Wertschaffung?','Finanzierungskosten, Aktienbasis und fairen Rückkaufpreis getrennt untersuchen.'],['Sind historische Daten bereits bereinigt?','Splits und Dividenden jeweils genau einmal berücksichtigen.']],'Die Übungsfragen enthalten eigenständige Rechen-, Vergleichs- und Abwicklungsfälle mit erklärten Fehlantworten.'),
  'Die neutralen Modellrechnungen isolieren die Wirkung einer einzelnen Maßnahme. Sie sagen nicht, dass Marktpreise sich immer mechanisch anpassen oder Ankündigungen keine Informationen transportieren. Ebenso ist eine angenommene faire Bewertung kein beobachtbarer sicherer Marktparameter.',
  'Für CFA Level I steht die korrekte Zuordnung von Maßnahme, Anspruch und Rendite im Mittelpunkt. Die vertiefenden Herleitungen helfen, ähnliche Fälle zu unterscheiden, ohne isolierte Merksätze auf unpassende Voraussetzungen anzuwenden.'
 ])
],related:[
 {unit:'valuation-overview',section:'bridge',label:'Vom operativen Wert zum Wert je Stammaktie'},
 {unit:'returns',section:'holding-return',label:'Allgemeine Haltedauerrendite und ihre Bestandteile'},
 {unit:'benchmarks',section:'time-weighted',label:'Externe Geldflüsse und zeitgewichtete Renditen'},
 {unit:'equity-trading',section:'return-types',label:'Kurs-, Brutto- und Netto-Gesamtrenditeindizes'},
 {unit:'income-statement',section:'basic-eps',label:'Zeitgewichtete Aktienzahl im veröffentlichten EPS'},
 {unit:'voting',section:'record',label:'Dividendenstichtag vom Stimmrechtsstichtag unterscheiden'},
 {unit:'capital-allocation',section:'npv',label:'Ausschüttung und wertschaffende Kapitalverwendung'}
],sources:[
 {title:'CFA Institute: Lernziele Level I 2027, Sources of Equity Returns, Seite 16',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=16'},
 {title:'SEC Investor.gov: Ex-Dividend Dates; aktuelle US-Regeln und Sonderfälle, geprüft September 2026',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/ex-dividend-dates-when-are-you-entitled-stock-and'},
 {title:'FINRA: Understanding Settlement Cycles; T+1 im aktuellen US-Rahmen',url:'https://www.finra.org/investors/insights/understanding-settlement-cycles'},
 {title:'FINRA: Stock Splits; reine Stückelungswirkung und Reverse Splits',url:'https://www.finra.org/investors/investing/investment-products/stocks/stock-splits'},
 {title:'CFA Institute: Analysis of Dividends and Share Repurchases; ergänzende vertiefende Übersicht 2026, nicht die Abgrenzung der Level-I-2027-Lernziele',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/analysis-of-dividends-and-share-repurchases'}
],review:{status:'draft',date:'2026-09-30',note:'Eigene Vermögenskonten, kontrollierte Rückkauf- und Wiederanlagevergleiche sowie abgegrenzte US-Terminregeln. Fachlicher Gesamtaudit und vollständige Prüfungsvorbereitung bleiben offen.'}};
