const {F,T,X,S,G}=require('../author.cjs');
const cost=q=>Math.min(q,100)*50.02+Math.min(Math.max(q-100,0),300)*50.05+Math.max(q-400,0)*50.10;
const sizes=Array.from({length:100},(_,i)=>(i+1)*10);
module.exports={id:'equity-trading',intro:[
 'Aktienmärkte erfüllen mehrere Aufgaben: Sie ermöglichen die Aufnahme von Eigenkapital, den späteren Eigentümerwechsel und die laufende Preisbildung. Eine Börsentransaktion erhöht aber nicht automatisch die Kasse des Unternehmens. Ebenso wenig ist eine hohe Marktkapitalisierung schon ein Beweis, dass eine große Position kurzfristig zu einem engen Spread handelbar ist.',
 'CFA Level I 2027 verlangt die Funktionen von Primär- und Sekundärmarkt, den Vergleich von Handelsplätzen, Liquiditätsmaße einschließlich Free Float und durchschnittlichem Tagesvolumen sowie Aktienindexarten. Die eigenen Rechenfälle verbinden diese Lernziele. Vertiefungen zu Ausführungskosten und Indexdivisoren erklären die Mechanik; sämtliche Zahlen sind hypothetisch, und nationale Marktregeln werden ausdrücklich abgegrenzt.'
],sections:[
 S('flows','1. Zuerst den Empfänger des Geldes bestimmen','a',[
  'Am Primärmarkt werden neu ausgegebene Aktien platziert. Der Emittent erhält die vereinbarten Erlöse abzüglich seiner Emissionskosten; die Zahl ausstehender Aktien kann steigen. Am Sekundärmarkt wechseln bereits bestehende Aktien den Eigentümer. Der Kaufpreis geht an den verkaufenden Anleger beziehungsweise die beteiligten Handelspartner, nicht als neues Eigenkapital in die Gesellschaft.',
  T(['Vorgang','Empfänger des Verkaufserlöses','Ausstehende Aktien'],[['Neue Aktien werden gegen Bareinzahlung ausgegeben.','Emittent, abzüglich seiner Kosten.','Steigen um die tatsächlich neu ausgegebenen Aktien.'],['Ein Gründer verkauft bereits bestehende Aktien.','Verkaufender Gründer, abzüglich seiner Kosten.','Bleiben durch den bloßen Eigentümerwechsel gleich.'],['Anleger handeln nach der Notierung miteinander.','Verkäufer beziehungsweise Handelspartner.','Bleiben durch den bloßen Handel gleich.']],'Finanzierung und Handel können im selben Angebot vorkommen, bleiben aber wirtschaftlich verschieden.'),
  'Auch ein Börsengang kann neue Aktien und Verkäufe bestehender Eigentümer enthalten. „Öffentliches Angebot“ beschreibt deshalb nicht allein den Geldempfänger. In einem gemischten Angebot wird jede Tranche getrennt untersucht. Der Prospekt nennt unter anderem angebotene Stückzahlen, verkaufende Aktionäre und geplante Mittelverwendung.',
  'Der Sekundärmarkt hilft dem Primärmarkt indirekt: Anleger sind eher bereit, Kapital langfristig bereitzustellen, wenn sie ihre Beteiligung später übertragen können. Preisbildung und Handelbarkeit beeinflussen geforderte Rendite und Finanzierungsbedingungen. Eine solche Wechselwirkung ist etwas anderes als die direkte Verbuchung jedes Börsenumsatzes beim Unternehmen.'
 ]),
 S('offering','2. Ein gemischtes Angebot vollständig abrechnen','a',[
  F('C_{issuer}=n_{new}P_O(1-u)-K','Vom Bruttoerlös der neuen Aktien werden der hier prozentual definierte Emissionsabschlag und die zusätzlichen Emittentenkosten abgezogen. Verkäufe alter Aktien gehören nicht in diesen Erlös.',[['C_{issuer}','Nettozufluss an die Gesellschaft.'],['n_{new}','Zahl tatsächlich neu ausgegebener Aktien.'],['P_O','Angebotspreis je Aktie.'],['u','Auf die neuen Aktien angewandter prozentualer Emissionsabschlag als Dezimalzahl.'],['K','Weitere von der Gesellschaft getragene fixe Kosten, ohne den schon berücksichtigten Abschlag.']]),
  X('Neue Finanzierung und Altaktionärserlös im selben Börsengang','Vor dem Angebot bestehen 40 Millionen identische Aktien. Zehn Millionen neue und fünf Millionen bestehende Aktien werden zu je 20 angeboten und vollständig verkauft. Ein Abschlag von fünf Prozent gilt für beide Tranchen; zusätzliche Kosten von zwei Millionen trägt nur die Gesellschaft. Die Verkäufer der alten Aktien tragen sonst keine Kosten.',[
   F('C_{issuer}=10\\cdot20\\cdot0{,}95-2=188,\\qquad C_{seller}=5\\cdot20\\cdot0{,}95=95','Die neue und die bestehende Tranche werden getrennt abgerechnet. Der Faktor 0,95 zieht den fünfprozentigen Abschlag ab.',[['C_{issuer}','Nettozufluss an die Gesellschaft in Millionen Geldeinheiten.'],['C_{seller}','Nettozufluss an die verkaufenden Altaktionäre in Millionen Geldeinheiten.']]),
   T(['Rechnung in Millionen Geldeinheiten','Gesellschaft','Verkaufende Altaktionäre'],[['Bruttoerlös','200','100'],['Prozentualer Abschlag','10','5'],['Weitere Kosten','2','0'],['Nettozufluss','188','95']],'Der Gesamtpreis von 300 Millionen wird nicht vollständig zum neuen Unternehmenskapital.'),
   F('N_1=40+10=50,\\qquad q_{new}=\\frac{10}{50}=20\\%','Die verkauften fünf Millionen alten Aktien werden nicht ein zweites Mal ausgegeben.',[['N_1','Ausstehende Aktien nach dem Angebot in Millionen.'],['q_{new}','Anteil der Käufer neu ausgegebener Aktien am gesamten Kapital nach Ausgabe.']]),
   'Ein Altaktionär mit vier Millionen Aktien, der nicht verkauft und nicht mitzeichnet, sinkt von zehn auf acht Prozent der Aktien. Die relative Quote wird kleiner. Das ist allein noch kein Beweis eines Wertverlusts: Die Gesellschaft erhält zugleich neues Kapital. Preis, Kosten und dessen Verwendung entscheiden über die wirtschaftliche Wirkung.'
  ],'Aktienzahl, Beteiligungsquote, Unternehmenszufluss und Verkäufererlös müssen getrennt abgestimmt werden.')
 ]),
 S('pricing','3. Angebotspreis, Zuteilung und späterer Börsenkurs','a',[
  'Beim Bookbuilding sammeln die beteiligten Banken Kaufinteresse zu Preisen und Mengen. Das unterstützt die Festlegung von Angebotspreis und Zuteilung. Interessenbekundungen sind jedoch keine sichere Prognose künftiger Nachfrage. Ein überzeichnetes Angebot garantiert weder jedem Interessenten eine Zuteilung noch einen späteren Gewinn.',
  'Underpricing bezeichnet einen Angebotspreis unter dem verwendeten späteren Marktvergleich, häufig dem ersten Schlusskurs. Der Abstand ist eine ex post beobachtete Größe. Er beweist nicht, dass die gesamte Emission vorher sicher zum späteren Kurs hätte verkauft werden können. Marktbedingungen, Unsicherheit und die tatsächlich angebotene Menge sind relevant.',
  X('Drei Preise, drei verschiedene wirtschaftliche Fragen','Eine neue Aktie wird zu 20 platziert. Der erste verfügbare Börsenkauf eines anderen Anlegers erfolgt zu 25; am Tagesende steht sie bei 24. Keine Dividende oder Gebühr im Vergleich.',[
   F('R_O=\\frac{24-20}{20}=20\\%,\\qquad R_B=\\frac{24-25}{25}=-4\\%','Die Zuteilung zum Angebotspreis und der spätere Börsenkauf besitzen unterschiedliche Einstiegspreise.',[['R_O','Tagesrendite eines zum Angebotspreis zugeteilten Anlegers.'],['R_B','Tagesrendite des hier erst zu 25 kaufenden Börsenanlegers.']]),
   'Der Emittent erhält aus einer bereits zu 20 verkauften neuen Aktie nicht nachträglich vier weitere Geldeinheiten, nur weil der erste Schlusskurs 24 beträgt. Ebenso wenig durfte der spätere Käufer seine Rendite auf den für ihn nicht verfügbaren Angebotspreis beziehen.'
  ],'Ein erfolgreicher erster Börsentag ist keine einheitliche Rendite für alle Beteiligten.'),
  'Eine regulatorische Prüfung eines Angebots ist kein Gütesiegel für seine Anlagequalität. Für das US-Beispiel stellt die SEC ausdrücklich klar, dass die Wirksamkeit einer Registrierung keine inhaltliche Empfehlung des Investments darstellt. Unternehmensrisiko, Vertragsrechte und verlangter Preis bleiben zu analysieren.'
 ]),
 S('underwriting','4. Platzierungsrisiko und Wege zum Markt','a',[
  'Bei einem Firm Commitment übernimmt das Bankenkonsortium nach den vereinbarten Bedingungen die Emission zum festgelegten Übernahmepreis und trägt das entsprechende Weiterverkaufsrisiko. Bei Best Efforts versucht der Vermittler, die Aktien zu platzieren, ohne in derselben Weise den Absatz des gesamten Angebots zu garantieren. Verpflichtungen und Ausnahmen folgen dem konkreten Vertrag.',
  T(['Ausgestaltung','Finanzierungsfrage','Was daraus nicht folgt'],[['Firm Commitment','Welchen Betrag und welches Risiko übernimmt der Underwriter vertraglich?','Der spätere Aktienkurs ist nicht garantiert.'],['Best Efforts','Wie viel wird tatsächlich platziert und welche Mindestbedingungen gelten?','Das vollständige angestrebte Kapital ist nicht automatisch gesichert.'],['Folgeemission','Welche zusätzlichen Aktien gibt eine bereits öffentliche Gesellschaft aus?','Ein öffentliches Folgeangebot muss nicht ihr erster Börsengang sein.'],['Verkauf alter Aktien','Welcher bisherige Eigentümer schafft Liquidität für sich?','Nicht jeder Angebotserlös fließt an den Emittenten.'],['Direct Listing','Welche bestehenden oder gegebenenfalls neuen Aktien werden nach dem zulässigen Verfahren zugänglich?','Direktnotierung bedeutet nicht unter allen heutigen Regeln zwingend keine Kapitalaufnahme.']],'Finanzierungsweg, Notierung und Handelsbeginn werden anhand der tatsächlichen Struktur beurteilt.'),
  'Eine Bezugsrechtsemission räumt bestehenden Aktionären nach den Bedingungen die Möglichkeit ein, an der neuen Ausgabe teilzunehmen. Anzahl, Bezugspreis, Frist und gegebenenfalls Handelbarkeit der Rechte entscheiden darüber, wie eine Beteiligungsquote erhalten oder ein Recht verwertet werden kann. Ein Bezugsrecht ist keine Pflicht, zusätzliches Kapital zu investieren.',
  'Für die Analyse werden Emissionsvolumen und Kosten mit geplantem Kapitalbedarf verbunden. Ein nominell hoher Erlös hilft wenig, wenn er an verkaufende Altaktionäre geht oder nach Kosten nicht für die geplanten Investitionen reicht. Die Finanzierung wird deshalb in das Unternehmensmodell überführt.'
 ]),
 S('secondary','5. Was ein Sekundärmarkt leistet','a b',[
  'Der Sekundärmarkt bringt Kauf- und Verkaufsinteressen zusammen. Er ermöglicht Liquidität für Anleger und erzeugt beobachtbare Preise. Diese Preise verdichten Einschätzungen über künftige Zahlungen und Risiken; sie können durch neue Informationen, Liquiditätsbedarf oder Handelsfriktionen schwanken.',
  'Ein Broker handelt im Auftrag beziehungsweise vermittelt. Ein Dealer handelt auf eigene Rechnung; ein Market Maker stellt nach seinem Geschäftsmodell und den jeweils geltenden Verpflichtungen Kauf- und Verkaufskurse. Eine Firma kann verschiedene Rollen besitzen. Bei einer konkreten Transaktion sind Rolle, Gegenpartei, Preis und Vergütung zu unterscheiden.',
  X('Die Bilanz der Gesellschaft bleibt beim Anlegerhandel unberührt','Ein Anleger verkauft tausend bereits bestehende Aktien zu 50 an einen anderen. Beide zahlen jeweils zehn Gebühr an ihre jeweiligen Broker. Die Gesellschaft ist nicht Handelspartner.',[
   'Der Käufer zahlt 50.010, der Verkäufer erhält 49.990. Die Broker erhalten zusammen zwanzig. Die Gesellschaft bekommt aus dieser Transaktion keinen neuen Emissionserlös.',
   'Die ausstehenden Aktien bleiben gleich. Lediglich ihre Eigentümer wechseln. Ein neu beobachteter Kurs kann allerdings den Börsenwert aller ausstehenden Aktien verändern, ohne dass dieser gesamte Wert als Geld geflossen wäre.'
  ],'Handelsumsatz, Marktkapitalisierung und Finanzierung sind unterschiedliche Größen.'),
  'Auch hohe Handelsaktivität beweist keine effiziente Bewertung jeder einzelnen Aktie. Ein Preis kann bei beschränkter Information oder wenig Tiefe stark reagieren. Marktqualität wird daher nicht nur an der Zahl von Abschlüssen gemessen.'
 ]),
 S('venues','6. Notierung und Ausführungsort auseinanderhalten','b',[
  'Eine Aktie kann an einer Börse notiert sein und trotzdem außerhalb dieser Börse gehandelt werden. Listing bezeichnet den Status nach den Regeln des Notierungsplatzes; Ausführungsort bezeichnet den Ort beziehungsweise Mechanismus eines konkreten Geschäfts. Diese Dimensionen dürfen nicht gleichgesetzt werden.',
  T(['Ausführung','Grundidee','Zu prüfen'],[['Börse','Mehrere Kauf- und Verkaufsinteressen treffen nach einem Regelwerk zusammen, etwa im Orderbuch oder in einer Auktion.','Zugängliche Preise, verfügbare Mengen und Auktions- beziehungsweise Handelsregeln.'],['Alternatives System','Ein anderer organisierter Mechanismus führt Interessen zusammen.','Regulatorische Kategorie, Zugang, Offenlegung und Abwicklung.'],['Dealer / Internalisierung','Eine Firma erfüllt Kundeninteresse aus eigenem Handel oder führt es innerhalb ihrer Ausführungsstruktur aus.','Tatsächlicher Preis, Kosten, Konflikte und Ausführungsqualität.'],['Bilateral / OTC','Parteien handeln außerhalb einer Börsenausführung miteinander.','Gegenpartei, Preisfindung, Meldung und Abwicklungsbedingungen.']],'Die rechtlichen Bezeichnungen unterscheiden sich zwischen Ländern. Die Tabelle beschreibt Funktionen.'),
  'Im US-Beispiel können börsennotierte Aktien an Börsen, auf Alternative Trading Systems oder über weitere Broker-Dealer-Strukturen gehandelt werden. FINRA unterscheidet außerbörsliche Geschäfte in notierten Aktien von nicht börsennotierten OTC Equity Securities. Die Aussage „OTC bedeutet immer unnotierte Aktie“ wäre dort falsch.',
  'Außerbörslich bedeutet auch nicht automatisch unreguliert. Zulassung, Verhaltenspflichten, Meldung und Transparenz folgen dem jeweiligen Rahmen. Aus der Bezeichnung allein lässt sich weder bessere noch schlechtere Ausführung ableiten.'
 ]),
 S('transparency','7. Sichtbarkeit vor und nach dem Abschluss','b',[
  'Pre-Trade Transparency betrifft sichtbare Kauf- und Verkaufsinteressen vor dem Abschluss. Post-Trade Transparency betrifft veröffentlichte Informationen über ausgeführte Geschäfte. Ein Handelsplatz kann in der ersten Dimension wenig anzeigen und in der zweiten dennoch Meldepflichten haben.',
  'Ein Dark Pool veröffentlicht typischerweise nicht dieselben vor der Ausführung sichtbaren Quotierungen wie ein offenes Orderbuch. Im US-ATS-Beispiel verschwinden ausgeführte Geschäfte dadurch nicht einfach aus sämtlichen Meldesystemen: Auch solche Systeme müssen Transaktionen nach den einschlägigen Vorgaben melden. Geringe Vorhandelssichtbarkeit ist nicht gleich keinerlei Kontrolle.',
  X('Ein großer Auftrag und ein kleiner sichtbarer Bestand','Ein institutioneller Anleger möchte hunderttausend Aktien handeln. Im offenen Buch sind nahe am aktuellen Preis nur kleine Mengen sichtbar. Ein alternativer Mechanismus könnte eine passende Gegenpartei finden, ohne den gesamten Auftrag vorab anzuzeigen.',[
   'Das kann Informationspreisgabe begrenzen, garantiert aber keine passende Gegenpartei. Der Auftrag kann teilweise oder gar nicht ausgeführt werden. Eine spätere Ausführung kann außerdem in einem veränderten Markt stattfinden.',
   'Der Vergleich berücksichtigt daher Preis, Gebühren, Wahrscheinlichkeit und Umfang der Ausführung, Zeit und Informationsrisiko. Ein einzelner gemeldeter günstiger Preis beweist nicht, dass jeder Teil des Auftrags gleich günstig gehandelt werden konnte.'
  ],'Transparenz, Handelbarkeit und Ausführungsqualität sind miteinander verbunden, aber nicht identisch.'),
  'Ein OTC-Label, eine dunkle Ausführung oder ein hoher Marktanteil allein belegt weder Marktmissbrauch noch eine risikolose Verbesserung. Für eine begründete Beurteilung braucht man Daten zum tatsächlichen Auftrag und zum relevanten Marktvergleich.'
 ]),
 S('orders','8. Preisgrenze und Ausführungswunsch','b c',[
  'Eine Market Order priorisiert die möglichst zeitnahe Ausführung zum verfügbaren Markt. Sie garantiert keinen bestimmten Kurs und kann über mehrere Preisstufen gefüllt werden. Handelsunterbrechungen, fehlende Gegenorders und andere Marktbedingungen können auch die Ausführung beeinträchtigen.',
  'Eine Limit Order legt beim Kauf einen Höchstpreis, beim Verkauf einen Mindestpreis fest. Sie begrenzt den zulässigen Preis, garantiert aber keine Ausführung. Auch ein beobachteter Handel zum Limit beweist nicht, dass die eigene Order aufgrund von Reihenfolge, Menge und Handelsplatz vollständig zum Zuge kam.',
  X('Preisobergrenze und Restauftrag im eingefrorenen Orderbuch','Die Verkaufsseite bietet 100 Aktien zu 50,02, weitere 300 zu 50,05 und 600 zu 50,10. Ein Kaufauftrag über 500 trifft allein auf dieses Buch. Keine Änderungen, Gebühren, verdeckten Mengen oder andere Handelsplätze.',[
   'Eine unlimitierte Market Order nimmt zuerst die hundert günstigsten Aktien, dann dreihundert auf der nächsten Stufe und schließlich hundert zu 50,10.',
   'Eine Kauf-Limitorder zu 50,05 erhält unter denselben vereinfachten Bedingungen höchstens vierhundert sofort. Die restlichen hundert werden nicht oberhalb des Limits ausgeführt; ihr weiteres Schicksal hängt etwa von Gültigkeit und Orderbedingungen ab.'
  ],'Ein Preislimit kann die Ausführung begrenzen. Eine Market Order kann über den besten angezeigten Preis hinausgehen.'),
  'Für die folgende Kostenrechnung bleibt das Buch bewusst eingefroren. In einem echten Markt verändern neue Orders, Stornierungen, andere Käufer und Routing den verfügbaren Bestand. Historische Tiefe ist keine feste zukünftige Zusage.'
 ]),
 S('spread','9. Spread: Geldpreis, Briefpreis und Bezugsgröße','c',[
  'Der Bid ist der Preis, zu dem auf der betrachteten Stufe gekauft werden soll: Ein sofort verkaufender Anleger trifft auf diese Kaufseite. Der Ask ist der angebotene Verkaufspreis: Ein sofort kaufender Anleger zahlt auf dieser Seite. Der Quoted Spread ist ihre Differenz. Ein enger Spread beschreibt zunächst nur die betrachtete Preisstufe und ihre verfügbare Menge.',
  F('M=\\frac{A+B}{2},\\qquad S=A-B,\\qquad s=\\frac{A-B}{M},\\qquad s_{bp}=10^4s','Der relative Spread verwendet hier den zeitgleichen Mittelpunkt als Nenner. Andere Konventionen müssen ausdrücklich genannt werden.',[['A','Bester betrachteter Briefkurs, Ask, in Geldeinheiten je Aktie.'],['B','Bester betrachteter Geldkurs, Bid, in derselben Einheit.'],['M','Mittelpunkt von Geld- und Briefkurs.'],['S','Absoluter Spread in Geldeinheiten je Aktie.'],['s','Relativer Spread als Dezimalzahl.'],['s_{bp}','Relativer Spread in Basispunkten; ein Basispunkt ist 0,01 Prozentpunkt.']]),
  X('Vier Cent können je nach Aktienpreis sehr unterschiedlich sein','Aktie X wird 49,98 zu 50,02 quotiert. Aktie Y wird 1,98 zu 2,02 quotiert. Die nötigen kleinen Mengen sind jeweils verfügbar. Keine Gebühren oder weitere Kosten.',[
   T(['Aktie','Absoluter Spread','Mittelpunkt','Relativer Spread','Basispunkte'],[['X','0,04','50,00','0,08 %','8'],['Y','0,04','2,00','2,00 %','200']],'Gleiche Centdifferenz bedeutet nicht gleiche relative Handelskosten.'),
   'Beim sofortigen Kauf von X liegt der Preis zwei Cent über dem Mittelpunkt, also vier Basispunkte. Ein anschließender sofortiger Verkauf zum unveränderten Bid verliert vier Cent je Aktie: den vollen Spread. Einseitige Abweichung und Hin-und-zurück-Kosten sind deshalb zu unterscheiden.'
  ],'Spreadvergleiche benötigen Einheit, Bezugsgröße, Zeitpunkt und Menge.')
 ]),
 S('depth','10. Tiefe: warum die Auftragsgröße Kosten verändert','c',[
  F('\\bar P=\\frac{\\sum_{k=1}^{K}q_kP_k}{Q},\\qquad Q=\\sum_{k=1}^{K}q_k,\\qquad C=Q(\\bar P-M)','Der volumengewichtete Ausführungspreis beschreibt diesen einzelnen vollständig ausgeführten Kauf. Die letzte Formel misst seinen Mehrbetrag gegenüber dem vorgegebenen Mittelpunkt, ohne zusätzliche Gebühren.',[['\\bar P','Durchschnittlicher Preis der ausgeführten Aktien.'],['q_k','Auf Preisstufe k tatsächlich gekaufte Aktien.'],['P_k','Ausführungspreis dieser Stufe.'],['Q','Gesamte ausgeführte Kaufmenge.'],['K,k','Zahl genutzter Preisstufen und Stufenindex.'],['M','Mittelpunkt vor dem Auftrag; hier 50.'],['C','Gesamter Kaufmehrbetrag gegenüber Q Aktien zum Mittelpunkt.']]),
  X('Dasselbe beste Angebot, unterschiedliche Durchschnittspreise','Verkaufsbuch wie zuvor: 100 Aktien zu 50,02, 300 zu 50,05 und 600 zu 50,10. Der Bid vor dem Auftrag beträgt 49,98. Jede Zeile ist eine separate alternative Kauforder gegen dasselbe unveränderte Ausgangsbuch.',[
   T(['Kaufmenge','Gesamter Kaufpreis','Durchschnitt','Mehrbetrag gegenüber 50'],[['100','5.002','50,020','2'],['400','20.017','50,0425','17'],['500','25.027','50,054','27'],['1.000','50.077','50,077','77']],'Größere Orders verbrauchen die günstigen Stufen; die vier Fälle werden nicht nacheinander ausgeführt.'),
   F('\\bar P_{500}=\\frac{100\\cdot50{,}02+300\\cdot50{,}05+100\\cdot50{,}10}{500}=50{,}054','Für die Fünfhundert-Stück-Order reichen weder der beste Ask noch ein einfacher Mittelwert der drei Kurse.',[['\\bar P_{500}','Volumengewichteter Preis der vollständig ausgeführten 500 Aktien.']]),
   'Die Kosten relativ zum Mittelpunkt sind 27. Gegenüber einem hypothetischen vollständigen Kauf zum besten Ask von 50,02 entstehen weitere siebzehn. Diese Aufteilung ist eine Beschreibung des vorgegebenen Buchs; sie isoliert nicht sämtliche kausalen Bestandteile echten Markteinflusses.'
  ],'Preis und verfügbarer Bestand müssen gemeinsam betrachtet werden.'),
  G({id:'depth-cost',title:'Mehr Kaufmenge erreicht teurere Preisstufen',caption:'Eigene Rechnung aus dem eingefrorenen Verkaufsbuch: 100 Stück zu 50,02, 300 zu 50,05, 600 zu 50,10. Alternative vollständige Käufe ohne Gebühren oder neue Orders.',reading:'Bis hundert Stück liegt der Durchschnitt beim besten Ask. Danach steigt er, weil zusätzliche Aktien teurer sind. Der Durchschnitt springt an den Stufengrenzen nicht plötzlich auf den höchsten Einzelkurs.',plot:{x:[0,1000],y:[50.01,50.09],xTicks:[0,100,400,700,1000],yTicks:[50.02,50.04,50.06,50.08],xLabel:'Gekaufte Aktien',yLabel:'Durchschnittlicher Kaufpreis je Aktie',series:[{name:'Volumengewichteter Ausführungspreis',points:sizes.map(q=>[q,cost(q)/q])}],marks:[100,400,1000].map(q=>({x:q,y:cost(q)/q,label:String(q),anchor:q===1000?'end':'start',dx:q===1000?-10:10,dy:-12}))}})
 ]),
 S('float','11. Free Float: Bestandsgröße mit definierter Methodik','c',[
  'Free Float bezeichnet den als frei verfügbar beziehungsweise investierbar berücksichtigten Aktienbestand nach der angegebenen Methodik. Strategische Kontrollbeteiligungen oder beschränkte Bestände können ausgeschlossen sein. Nicht jede große institutionelle Beteiligung ist allein wegen ihrer Größe strategisch gebunden. Schwellen und Klassifikation sind methodenspezifisch.',
  F('N_{out}=N_{issued}-N_{treasury},\\qquad N_{float}=N_{out}-N_{excluded},\\qquad f=\\frac{N_{float}}{N_{out}}','Zuerst wird ausgegeben von ausstehend getrennt. Danach werden ausdrücklich ausgeschlossene Bestände nur einmal abgezogen. Überlappende Kategorien müssen vor der Addition bereinigt werden.',[['N_{issued}','Ausgegebene Aktienzahl.'],['N_{treasury}','Eigene Aktien der Gesellschaft, soweit hier bereits nicht ausstehend.'],['N_{out}','Ausstehende Aktienzahl nach der angegebenen Definition.'],['N_{excluded}','Nicht zum Float gehörende ausstehende Aktien, ohne Doppelzählung.'],['N_{float}','Investierbarer Float in Aktien.'],['f','Float Ratio als Anteil der ausstehenden Aktien.']]),
  X('Eigene Aktien und gesperrte Beteiligungen nicht doppelt abziehen','120 Millionen Aktien wurden ausgegeben; zehn Millionen liegen im eigenen Bestand und sind hier nicht ausstehend. Von den ausstehenden Aktien werden 30 Millionen Gründeraktien und weitere zehn Millionen gesperrte Aktien ausgeschlossen. Die beiden Ausschlussgruppen überlappen ausdrücklich nicht.',[
   F('N_{out}=120-10=110,\\qquad N_{float}=110-30-10=70,\\qquad f=\\frac{70}{110}=63{,}64\\%','Sämtliche Aktienzahlen sind Millionen. Eine Quote auf 120 würde eine andere Bezugsgröße verwenden.',[['N_{out}','Ausstehende Aktien in Millionen.'],['N_{float}','Float in Millionen Aktien.'],['f','Float-Anteil an ausstehenden Aktien.']]),
   'Bei Kurs 25 beträgt die volle Marktkapitalisierung 2.750 Millionen, die floatbereinigte 1.750 Millionen. Keine dieser Größen ist die Kasse des Unternehmens oder der Tagesumsatz der Aktie.',
   'Laufen die Sperren der zusätzlichen zehn Millionen Aktien aus und zählen sie danach zum Float, steigt dieser auf achtzig Millionen. Allein das Ende der Sperre ist weder eine Neuemission noch der Nachweis, dass diese Aktien sofort verkauft werden.'
  ],'Float beschreibt einen Bestand. Volumen beschreibt Handel während eines Zeitraums.'),
  'Bei mehreren Klassen sind Kurs, Aktienzahl und Investierbarkeit klassenweise zuzuordnen. Ein ADR und die durch ihn repräsentierten Stammaktien dürfen bei einer wirtschaftlichen Gesamtbestandsanalyse nicht ohne Prüfung doppelt erfasst werden.'
 ]),
 S('volume','12. Durchschnittliches Tagesvolumen richtig berechnen','c',[
  'Average Daily Volume beschreibt die durchschnittliche täglich gehandelte Aktienmenge. Average Daily Traded Value beschreibt dagegen den durchschnittlichen Geldumsatz. Beide Kennzahlen benötigen einen definierten Beobachtungszeitraum und eine konsistente Abgrenzung der erfassten Geschäfte.',
  F('ADV=\\frac{1}{T}\\sum_{t=1}^{T}V_t,\\qquad ADTV=\\frac{1}{T}\\sum_{t=1}^{T}\\sum_{k=1}^{K_t}P_{tk}q_{tk}','ADV misst hier Aktien pro Handelstag; ADTV misst gehandelten Geldwert pro Handelstag. Der Datenumfang, die Handelsplätze und der Beobachtungszeitraum sind festzulegen.',[['ADV','Average Daily Volume in Aktien je Handelstag.'],['ADTV','Average Daily Traded Value in Geldeinheiten je Handelstag.'],['T','Zahl der einbezogenen Handelstage; keine Kalendertage ohne Sitzung.'],['V_t','Einmal gezähltes tatsächliches Aktienhandelsvolumen am Tag t.'],['P_{tk},q_{tk}','Preis und Aktienmenge des Abschlusses k am Tag t.'],['K_t','Zahl einbezogener Abschlüsse am Tag t.'],['t,k','Tagesindex und Abschlussindex.']]),
  X('Ein Spitzentag verändert den Durchschnitt','Fünf Handelstage melden 0,8; 1,0; 1,2; 0,9 und 3,1 Millionen Aktien. Der fünfte Tag enthält eine ungewöhnliche Nachricht. In einer vereinfachten Geldwertrechnung sei der Preis aller Geschäfte an den fünf Tagen jeweils 10, 11, 10, 12 und 10.',[
   F('ADV=\\frac{0{,}8+1{,}0+1{,}2+0{,}9+3{,}1}{5}=1{,}4','Das Mittel liegt deutlich über dem Median von einer Million Aktien. Der Nachrichtentag wird nicht heimlich entfernt, sondern bei der Interpretation kenntlich gemacht.',[['ADV','Durchschnittliches Tagesvolumen in Millionen Aktien.']]),
   F('ADTV=\\frac{0{,}8\\cdot10+1{,}0\\cdot11+1{,}2\\cdot10+0{,}9\\cdot12+3{,}1\\cdot10}{5}=14{,}56','Der durchschnittliche Geldumsatz ist nicht allgemein durchschnittlicher Kurs mal durchschnittliche Aktienmenge. Hier ergäbe diese falsche Abkürzung 10,6 mal 1,4 gleich 14,84.',[['ADTV','Durchschnittlich gehandelter Geldwert in Millionen Geldeinheiten je Handelstag.']]),
   'Ein Abschluss über hundert Aktien besitzt einen Käufer und einen Verkäufer, aber wird in dieser Volumenkonvention als hundert gehandelte Aktien gezählt, nicht als zweihundert. Kombinierte Datenfeeds dürfen denselben Abschluss nicht erneut addieren.'
  ],'Mittelwert, Median, Aktienvolumen und Geldumsatz beantworten unterschiedliche Fragen.'),
  'Aktien mit Splits oder wechselnder Datenabdeckung benötigen vergleichbare Einheiten. Ein handelsfreier Feiertag ist kein Handelstag mit null Volumen. Eine planmäßig offene Sitzung ohne Abschlüsse kann dagegen als null zum definierten Fenster gehören. Die Datenkonvention wird offengelegt, statt den Nenner nach Ergebnis zu wählen.'
 ]),
 S('capacity','13. Von Volumen zu einer vorsichtigen Größenordnung','c',[
  F('\\tau=\\frac{V_{period}}{N_{float}},\\qquad H=\\frac{Q}{p\\cdot ADV}','Die erste Größe beschreibt den Periodenumschlag relativ zum Float. Die zweite ist eine vereinfachte Ausführungsdauer bei konstantem Volumen und begrenzter Teilnahme am Tageshandel, keine garantierte Liquidationszeit.',[['\\tau','Floatbezogene Umschlagshäufigkeit im betrachteten Zeitraum.'],['V_{period}','Einmal gezähltes Handelsvolumen über denselben Zeitraum.'],['N_{float}','Passender Floatbestand; bei Veränderungen ist eine konsistente Bezugsgröße nötig.'],['H','Rechnerische Anzahl Handelstage; für ganze Sitzungen gegebenenfalls aufrunden.'],['Q','Zu handelnde Gesamtposition in Aktien.'],['p','Angenommener eigener Anteil am gesamten Tagesvolumen, als Dezimalzahl.'],['ADV','Für die Planung angenommene Aktienmenge je Handelstag.']]),
  X('Derselbe Auftrag unter normalen und schwächeren Handelsbedingungen','Eine Position umfasst 700.000 Aktien. Für die Modellrechnung werden höchstens zehn Prozent des gesamten Tagesvolumens beansprucht. Beim zuvor berechneten ADV von 1,4 Millionen wären das 140.000 pro Tag; bei einem vorsichtigeren Volumen von einer Million nur 100.000.',[
   F('H_1=\\frac{700000}{0{,}10\\cdot1400000}=5,\\qquad H_2=\\frac{700000}{0{,}10\\cdot1000000}=7','Der Mittelwert des Nachrichtenfensters ergibt eine kürzere Dauer als die vorsichtigere Volumenannahme.',[['H_1,H_2','Modellierte Dauer in Handelstagen bei den beiden Volumenannahmen.']]),
   'Fünf beziehungsweise sieben Tage sind keine Ausführungsgarantien. Preisgrenzen, schwache Gegenseite, gleichgerichtete Großaufträge, Handelsunterbrechungen und sich änderndes Volumen können die Durchführung verlängern oder verteuern.'
  ],'Eine Kapazitätsrechnung soll Annahmen sichtbar machen, nicht Liquidität vortäuschen.'),
  G({id:'volume-capacity',title:'Weniger tägliches Volumen verlängert die rechnerische Ausführung',caption:'Eigene Modellrechnung: Position 700.000 Aktien, höchstens 10 % Teilnahme am als konstant angenommenen Tagesvolumen. Gezeigt werden rechnerische Tagesanteile vor Aufrundung.',reading:'Bei 1,4 Millionen Aktien je Tag ergibt sich eine Dauer von fünf Tagen, bei einer Million sieben. Die inverse Beziehung bedeutet, dass eine Halbierung des Volumens die modellierte Dauer verdoppelt.',plot:{x:[.5,2],y:[0,15],xTicks:[.5,1,1.4,2],yTicks:[0,5,7,10,15],xLabel:'Angenommenes Tagesvolumen in Millionen Aktien',yLabel:'Rechnerische Handelstage',series:[{name:'700.000 Aktien bei 10 % Teilnahme',points:Array.from({length:151},(_,i)=>{const v=.5+i/100;return [v,.7/(.1*v)];})}],marks:[{x:1,y:7,label:'7 Tage',dx:12,dy:18},{x:1.4,y:5,label:'5 Tage',dx:12,dy:18}]}}),
  'Ein Jahresumsatz von mehr als hundert Prozent des Float ist möglich: Dieselbe Aktie kann mehrfach gehandelt werden. Daraus folgt weder, dass jede Aktie einmal den Besitzer wechselte, noch dass der gesamte Float gleichzeitig zum aktuellen Kurs verkäuflich wäre. Spread, Tiefe, Geschwindigkeit und Erholung nach Aufträgen ergänzen die Volumeninformation.'
 ]),
 S('index-map','14. Welche Frage soll ein Aktienindex beantworten?','d',[
  'Ein Aktienindex verdichtet die Entwicklung eines regelgebundenen Bestands. Sein Anlageuniversum bestimmt, welche Aktien überhaupt infrage kommen. Auswahlregeln bestimmen die Mitglieder. Gewichtung, Ausschüttungsbehandlung, Währung und Anpassungen bestimmen, welche Entwicklung gemessen wird.',
  T(['Unterscheidung','Beispiele','Wirtschaftliche Aussage'],[['Marktabdeckung','Breiter Gesamtmarkt, Land, Region, Branche.','Welcher Ausschnitt wird als Vergleichsmarkt abgebildet?'],['Größe oder Stil','Große und kleine Unternehmen, Value und Growth.','Welche systematischen Expositionen werden betont?'],['Auswahlregel','Regelbasierte Kriterien oder ein dokumentiertes Auswahlverfahren.','Welche Eintritts- und Ausschlussbedingungen gelten?'],['Gewichtung','Preis, Marktwert, Float, gleiche Gewichte oder Fundamentaldaten.','Welcher Titel beeinflusst die Entwicklung wie stark?'],['Ertragskonvention','Kursindex, Gross oder Net Total Return.','Welche Ausschüttungen und Steuern werden berücksichtigt?'],['Währung','Lokale, umgerechnete oder abgesicherte Darstellung.','Welcher Wechselkurseinfluss verbleibt?']],'Eine Kategorie schließt die anderen nicht aus: Ein Branchenindex kann zugleich floatgewichtet und als Gesamtrenditeindex berechnet werden.'),
  'Ein Index ist eine Rechenvorschrift, kein automatisch handelbares Depot. Ein Fonds kann ihn nachbilden, trägt aber Kosten, Steuern, Umsetzungsgrenzen und möglicherweise Nachbildungsabweichungen. Ein Indexstand von 10.000 ist nicht deshalb besser oder größer als ein Stand von 1.000: Basisdatum und Skalierung sind zunächst frei gewählte Konventionen.'
 ]),
 S('weights','15. Gewichtungsformeln und ihre wirtschaftliche Logik','d',[
  F('w_i^P=\\frac{P_i}{\\sum_jP_j},\\qquad w_i^M=\\frac{P_iN_i}{\\sum_jP_jN_j}','Preisgewichtung gibt einer Aktie mit hohem Stückkurs viel Einfluss. Marktwertgewichtung berücksichtigt zusätzlich, wie viele Aktien ausstehen.',[['w_i^P,w_i^M','Anfangsgewicht von Titel i bei Preis- beziehungsweise Marktwertgewichtung.'],['P_i,P_j','Vergleichbare Kurse je Aktie zum selben Zeitpunkt und in derselben Währung.'],['N_i,N_j','Berücksichtigte ausstehende Aktienzahlen.'],['i,j','Betrachteter Titel und Summationsindex über alle Mitglieder.']]),
  F('w_i^F=\\frac{P_iN_if_i}{\\sum_jP_jN_jf_j},\\qquad w_i^E=\\frac1n','Floatgewichtung beschränkt den Marktwert auf die methodisch investierbare Basis. Gleichgewichtung setzt bei der Ausrichtung denselben Kapitalanteil in jeden Titel.',[['w_i^F,w_i^E','Anfangsgewicht bei Float- beziehungsweise Gleichgewichtung.'],['P_i,P_j','Aktienkurse in gemeinsamer Währung.'],['N_i,N_j','Berücksichtigte ausstehende Aktienzahlen.'],['f_i,f_j','Floatfaktoren nach einheitlicher Methodik, zwischen null und eins.'],['n','Anzahl der Indexmitglieder.'],['i,j','Titelindex und Summationsindex.']]),
  'Ein hoher Stückkurs ist keine Aussage über den gesamten Unternehmenswert. Ein Split kann den Preis je Aktie verändern, ohne einen entsprechenden wirtschaftlichen Wertverlust auszulösen. Umgekehrt kann ein sehr großes Unternehmen aufgrund kleiner investierbarer Quote in einem Floatindex ein wesentlich geringeres Gewicht haben.',
  'Fundamentalgewichtete Indizes verwenden nach ihrer Methodik etwa Umsatz, Cashflow oder Buchwert als Gewichtsgrundlage. Faktor- und thematische Indizes können weitere Kriterien nutzen; gedeckelte Indizes begrenzen bestimmte Einzel- oder Gruppengewichte. Solche Regeln verändern Risiken und Umsetzungsbedarf. Keine Gewichtungsmethode beseitigt grundsätzlich Kursverluste.'
 ]),
 S('comparison','16. Gleiche Aktien, verschiedene gemessene Marktrenditen','d',[
  F('R_I=\\sum_{i=1}^{n}w_{i,0}R_i','Für die betrachtete Periode werden die passenden Titelrenditen mit ihren Anfangsgewichten kombiniert. Es gibt hier keine zwischenzeitliche Umschichtung, neue Aktien oder andere Kapitalmaßnahmen.',[['R_I','Index- beziehungsweise Modellportfoliorendite.'],['w_{i,0}','Anfangsgewicht von Titel i.'],['R_i','Einzelrendite während derselben Periode nach einheitlicher Ertragskonvention.'],['n,i','Anzahl der Titel und Titelindex.']]),
  X('Drei Aktien machen den Einfluss der Gewichtung sichtbar','A kostet 100 bei einer Million Aktien und 20 % Float. B kostet 20 bei zehn Millionen Aktien und 90 % Float. C kostet 10 bei zehn Millionen Aktien und 80 % Float. Im nächsten Zeitraum steigt A auf 110, B bleibt bei 20 und C fällt auf 9. Keine Ausschüttungen oder Kapitalmaßnahmen.',[
   T(['Größe','A','B','C'],[['Marktwert in Millionen','100','200','100'],['Float-Marktwert in Millionen','20','180','80'],['Preisgewicht','76,92 %','15,38 %','7,69 %'],['Marktwertgewicht','25 %','50 %','25 %'],['Floatgewicht','7,14 %','64,29 %','28,57 %'],['Gleichgewicht','33,33 %','33,33 %','33,33 %'],['Titelrendite','10 %','0 %','−10 %']],'Gewichte sind gerundet; Rechnungen verwenden die ungerundeten Brüche.'),
   F('R_P=\\frac{100\\cdot0{,}10+20\\cdot0+10(-0{,}10)}{130}\\approx6{,}92\\%,\\qquad R_M=0{,}25\\cdot0{,}10+0{,}50\\cdot0+0{,}25(-0{,}10)=0','Preisgewichtung wird vom hochpreisigen Gewinner dominiert. Bei Marktwertgewichtung gleichen sich die Beiträge von A und C aus.',[['R_P','Rendite des Preisindex.'],['R_M','Rendite des vollen Marktwertindex.']]),
   F('R_F=\\frac{20\\cdot0{,}10+180\\cdot0+80(-0{,}10)}{280}\\approx-2{,}14\\%,\\qquad R_E=\\frac{0{,}10+0-0{,}10}{3}=0','Im Floatindex ist der investierbare Wert des Verlierers C viermal so hoch wie der von A. Die Gleichgewichtung gibt beiden denselben Einfluss.',[['R_F','Rendite des Floatindex.'],['R_E','Rendite bei gleichen Anfangsgewichten.']]),
   T(['Methode','Beitrag A','Beitrag B','Beitrag C','Indexrendite'],[['Preis','7,69 pp','0,00 pp','−0,77 pp','6,92 %'],['Marktwert','2,50 pp','0,00 pp','−2,50 pp','0,00 %'],['Float','0,71 pp','0,00 pp','−2,86 pp','−2,14 %'],['Gleich','3,33 pp','0,00 pp','−3,33 pp','0,00 %']],'Beiträge in Prozentpunkten (pp); Summen werden vor Rundung gebildet. Der Floatbeitrag kann deshalb gerundet um 0,01 Prozentpunkt von der Summe der angezeigten Einzelwerte abweichen.'),
   'Die volle Marktkapitalisierung bleibt bei vierhundert Millionen: A gewinnt zehn Millionen, C verliert zehn. Die Floatbasis sinkt dagegen von 280 auf 274 Millionen. Das erklärt die Nullrendite beziehungsweise den Verlust auch ohne direktes Einsetzen in die Gewichtsformel.'
  ],'Unterschiedliche Indexmeldungen können auf denselben Aktien und denselben korrekten Kursen beruhen.'),
  G({id:'index-sensitivity',title:'Die Gewichtung verändert den Einfluss derselben Aktie',caption:'Eigener Drei-Aktien-Fall: Nur die Rendite von A variiert; B bleibt unverändert, C verliert stets 10 %. Anfangsgewichte bleiben für die jeweilige Einperiodenrechnung fest.',reading:'Der Preisindex reagiert am stärksten auf A, weil dessen Stückkurs das größte Gewicht erhält. Beim beobachteten Anstieg von A um 10 % liegen Marktwert- und Gleichgewichtung bei null, während die Floatgewichtung negativ bleibt.',plot:{x:[-20,20],y:[-20,20],xTicks:[-20,-10,0,10,20],yTicks:[-20,-10,0,10,20],xLabel:'Rendite von A in Prozent',yLabel:'Indexrendite in Prozent',series:[{name:'Preis',a:100/130,c:10/130},{name:'Marktwert',a:.25,c:.25},{name:'Float',a:20/280,c:80/280},{name:'Gleich',a:1/3,c:1/3}].map(({name,a,c})=>({name,points:[-20,20].map(r=>[r,a*r-c*10])}))}})
 ]),
 S('divisor','17. Ein Divisor hält technische Änderungen aus der Rendite heraus','d',[
  F('I=\\frac{Z}{d},\\qquad d_{new}=\\frac{Z_{after}}{I_{before}}=d_{old}\\frac{Z_{after}}{Z_{before}}','Bei einer neutral einzubauenden technischen Änderung wird der Zähler neu skaliert, sodass das Indexniveau unmittelbar danach unverändert bleibt. Echte Marktbewegungen werden nicht neutralisiert.',[['I,I_{before}','Indexniveau beziehungsweise Niveau unmittelbar vor der technischen Änderung.'],['Z,Z_{before},Z_{after}','Methodischer Indexzähler, etwa Kurssumme oder Marktwert, vor und nach der Änderung.'],['d,d_{old},d_{new}','Divisor allgemein, vor und nach der Anpassung.']]),
  X('Ein Split verändert Stückpreise und künftige Preisgewichte','Die Anfangskurse aus dem Drei-Aktien-Fall sind 100, 20 und 10. Ein Preisindex verwendet Divisor 1,3 und steht bei 100. A führt einen 5:1-Split ohne wirtschaftliche Wertänderung durch; sein neuer Kurs ist 20 und seine Aktienzahl fünf Millionen.',[
   F('d_{new}=\\frac{20+20+10}{100}=0{,}5,\\qquad I_{after}=\\frac{50}{0{,}5}=100','Der alte Divisor würde fälschlich einen starken Verlust anzeigen. Die Anpassung erhält die Kontinuität.',[['d_{new}','Neuer Preisindexdivisor.'],['I_{after}','Niveau direkt nach dem Split.']]),
   'Die künftigen Preisgewichte sind jetzt vierzig, vierzig und zwanzig Prozent. Steigt anschließend nur B von 20 auf 22, steigt der Index auf 104. Seine Rendite von vier Prozent entspricht dem neuen B-Gewicht von vierzig Prozent mal zehn Prozent Kursanstieg.',
   'Der volle Marktwert von A bleibt beim Split dagegen hundert Millionen: zwanzig mal fünf Millionen ersetzt hundert mal eine Million. In einem einfachen Marktwertindex mit korrekt angepasster Aktienzahl erfordert allein dieser Split keine Divisoränderung.'
  ],'Niveaukontinuität verhindert eine Scheinrendite, hält aber nicht jedes künftige Gewicht unverändert.'),
  'Auch Mitgliederwechsel oder andere Kapitalmaßnahmen können einen Zähler ohne echten Marktgewinn verändern. Welche Anpassung nötig ist, folgt der Methodik. Die Richtung einer Divisoränderung wird aus der Kontinuitätsgleichung hergeleitet und nicht als pauschale Regel auswendig gelernt.'
 ]),
 S('rebalancing','18. Rebalancing und Mitgliederwechsel kosten Umsetzung','d',[
  'Reconstitution verändert die Indexmitgliedschaft. Rebalancing richtet Gewichte nach der Methodik neu aus. Beides kann zum selben Termin vorkommen, ist aber nicht dasselbe. Eine Gleichgewichtung bleibt nach Kursbewegungen nicht von selbst dauerhaft gleich.',
  X('Gleiche Anfangsbeträge werden ungleich','Ein Zwei-Aktien-Modell hält zu Beginn je 100 in A und B. Danach steigt A um zwanzig Prozent, B bleibt unverändert. Keine Ausschüttung, Einzahlung oder Gebühr.',[
   F('w_{A,1}=\\frac{120}{220}=54{,}55\\%,\\qquad w_{B,1}=\\frac{100}{220}=45{,}45\\%','Die Gewichte folgen zunächst den Marktwerten der unveränderten Bestände.',[['w_{A,1},w_{B,1}','Tatsächliche Gewichte der beiden Positionen nach der Kursbewegung.']]),
   'Um wieder fünfzig zu fünfzig zu erreichen, sollen jeweils 110 gehalten werden. Es werden zehn von A verkauft und zehn von B gekauft. Der gesamte gehandelte Geldbetrag beträgt zwanzig; einseitig gemessener Umschlag wäre zehn geteilt durch 220. Beide Konventionen dürfen nicht verwechselt werden.',
   'In einem Marktwertportfolio mit unveränderten maßgeblichen Aktienzahlen gehört das höhere Gewicht des gestiegenen Titels zur Regel. Es muss nicht allein wegen dieser Kursbewegung auf das frühere Gewicht zurückgesetzt werden.'
  ],'Zielgewichte und tatsächlich zwischen Anpassungen gehaltene Gewichte sind verschieden.'),
  'Ein realer Indexfonds muss Änderungen handeln oder anderweitig umsetzen. Spread, Gebühren, Steuern und verfügbare Liquidität können seine Rendite vom theoretischen Index unterscheiden. Besonders bei kleinen oder wenig gehandelten Titeln kann eine geringe rechnerische Gewichtung dennoch nennenswerten Umsetzungsaufwand verursachen.'
 ]),
 S('return-types','19. Kursindex, Gesamtrendite und Währung','d',[
  'Ein Price Return Index betrachtet Kursentwicklung. Ein Gross Total Return Index berücksichtigt die methodisch vorgesehene Wiederanlage der Bruttodividenden; Net Total Return verwendet eine bestimmte Steuerannahme. „Net“ bedeutet nicht automatisch nach sämtlichen Gebühren eines konkreten Fonds oder nach der individuellen Steuer jedes Anlegers.',
  X('Ausschüttung und Währung können den Vergleich umkehren','Eine Aktie beginnt bei 100 und endet nach einer am Periodenende ausgezahlten Dividende von vier bei 98. Keine weitere Ausschüttung. Für eine reine Modell-Nettorendite werden 25 % der Dividende einbehalten.',[
   F('R_P=\\frac{98-100}{100}=-2\\%,\\quad R_G=\\frac{98+4-100}{100}=2\\%,\\quad R_N=\\frac{98+3-100}{100}=1\\%','Kurs-, Brutto- und Modellnettorendite unterscheiden sich allein durch die Berücksichtigung der Ausschüttung.',[['R_P','Kursrendite der Periode.'],['R_G','Bruttogesamtrendite.'],['R_N','Nettogesamtrendite unter der angegebenen Dividendensteuerannahme.']]),
   F('1+R_H=(1+R_L)(1+R_{FX})','Für einen ungehedgten Einperiodenvergleich mit passenden Zahlungszeitpunkten werden lokaler Wertzuwachs und Wechselkursfaktor multipliziert.',[['R_H','Rendite in der Heimatwährung.'],['R_L','Konsistent erfasste Rendite in lokaler Währung.'],['R_{FX}','Änderung des Kurses in Einheiten Heimatwährung je Einheit lokaler Währung.']]),
   'Steigt die lokale Anlage insgesamt um zwei Prozent, während ihre Währung gegenüber der Heimatwährung zehn Prozent verliert, ergibt sich 1,02 mal 0,90 minus eins gleich −8,2 Prozent. Ein lokaler Indexvergleich allein erklärt dann die Anlegererfahrung nicht.'
  ],'Vor einem Leistungsvergleich werden Renditeart, Währung, Steuerannahme und Zeitraum angeglichen.'),
  'Über mehrere Ausschüttungstermine ist die genaue Wiederanlagekonvention nötig. Währungsabsicherung bringt weitere Instrumente und Kosten mit sich und ist nicht mit dem Weglassen des Wechselkurseffekts identisch. Diese Vertiefungen werden mit Renditemessung und Devisenrechnung verbunden.'
 ]),
 S('case','20. Finanzierung, investierbarer Bestand und Handelskapazität verbinden','a b c d',[
  X('Vom neuen Kapital zum möglichen Indexauftrag','Eine Gesellschaft besitzt 60 Millionen ausstehende Aktien. Davon sind vierzig Millionen strategisch gebunden; zwanzig zählen zum Float. Sie gibt zehn Millionen neue, vollständig frei investierbare Aktien zu 15 aus. Keine Emissionskosten oder Kursreaktion in diesem vereinfachten Fall. Danach bleibt der Marktpreis bei 15. Beobachtetes ADV beträgt 500.000 Aktien. Ein Fonds plant einen Kauf von einer Million Aktien.',[
   T(['Größe','Vorher','Nachher'],[['Ausstehende Aktien in Millionen','60','70'],['Float in Millionen Aktien','20','30'],['Float-Anteil','33,33 %','42,86 %'],['Voller Marktwert in Millionen','900','1.050'],['Float-Marktwert in Millionen','300','450']],'Die neuen Aktien verändern den Float und die Finanzierung; die strategischen Altbestände bleiben konstant.'),
   'Die Gesellschaft erhält 150 Millionen neues Kapital. Ein späterer Fondskauf bestehender Aktien im Sekundärmarkt zahlt dagegen an die Verkäufer. Bei unverändertem Kurs benötigt der Fonds vor Kosten fünfzehn Millionen; das ist keine zweite Kapitalerhöhung.',
   F('H=\\frac{1000000}{0{,}20\\cdot500000}=10','Bei zwanzig Prozent angenommener Teilnahme am gesamten Tagesvolumen ergibt sich eine rechnerische Dauer von zehn Handelstagen.',[['H','Modellierte Dauer in Handelstagen unter konstantem Volumen.']]),
   'Der größere Float kann das Gewicht in einem passenden Index beeinflussen, sofern dessen Regeln die neuen Aktien zum betrachteten Zeitpunkt berücksichtigen. Er beweist aber keine sofort ausreichende Orderbuchtiefe. Datum der Indexanpassung, andere Mitglieder und Fondsumsetzung werden zusätzlich geprüft.'
  ],'Ein gemeinsamer Fall kann vier verschiedene Fragen enthalten. Jede benötigt ihre eigene Rechnung und Bezugsgröße.')
 ]),
 S('review','21. Ein belastbares Analyseergebnis formulieren','a b c d',[
  T(['Prüfschritt','Ergebnis'],[['Geldfluss','Neue Aktien, bestehende Verkäufe, Kosten und Empfänger getrennt.'],['Ausführung','Notierung, Handelsplatz, Ordertyp und tatsächlicher Abschluss unterschieden.'],['Liquidität','Spread, Tiefe, Float, Volumenfenster und Auftragsgröße gemeinsam beurteilt.'],['Index','Universum, Auswahl, Gewichtung, Divisor, Ausschüttung und Währung genannt.'],['Grenzen','Annahmen, Datenlücken, Kosten und rechtlicher Geltungsbereich kenntlich.']],'So werden Begriffe zu einer zusammenhängenden Marktanalyse.'),
  'Typische Fehler entstehen durch falsche Nenner und vermischte Zeitpunkte: ausgegebene statt ausstehende Aktien, doppelt abgezogene Sperrbestände, Kalendertage statt Handelstage, Schlusskurs statt tatsächlicher Einstieg und Endgewichte statt Anfangsgewichte. Vor dem Rechnen wird deshalb festgelegt, was genau gemessen werden soll.',
  'Weder Börsennotierung noch hohe Handelsaktivität noch Indexmitgliedschaft ersetzt die Bewertung des zugrunde liegenden Anspruchs. Marktmechanik erklärt, wie Kapital und Anteile übertragen und Preise gemessen werden. Ob der Preis attraktiv ist, verlangt anschließend eine Untersuchung erwarteter Zahlungen, Risiken und Alternativen.'
 ])
],related:[
 {unit:'issuer-forms',section:'primary-secondary',label:'Finanzierungszufluss und Eigentümerwechsel vergleichen'},
 {unit:'equity-features',section:'public-private',label:'Öffentliche und private Beteiligungen unterscheiden'},
 {unit:'voting',section:'weights',label:'Aktienzahl von Stimmgewicht trennen'},
 {unit:'benchmarks',section:'divisor',label:'Weitere Indexdivisor-Fälle nachrechnen'},
 {unit:'benchmarks',section:'total-return',label:'Ausschüttungen bei Leistungsvergleichen berücksichtigen'},
 {unit:'standard-iii',section:'loyalty',label:'Ausführungsqualität im Kundeninteresse beurteilen'},
 {unit:'fx-markets',section:'quotation',label:'Wechselkurse mit den richtigen Einheiten lesen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Equity Issuance and Trading',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=15'},
 {title:'SEC Investor.gov: Investing in an IPO; Geldempfänger, Angebotspreis und Registrierung',url:'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-17'},
 {title:'CFA Institute: Market Organization and Structure; ergänzende öffentliche Einführung 2026',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/market-organization-structure'},
 {title:'FINRA: Regulatory Notice 16-08; Abgrenzung Firm Commitment und Best Efforts',url:'https://www.finra.org/sites/default/files/Regulatory-Notice-16-08.pdf'},
 {title:'NYSE: Direct Listings, mögliche Kapitalaufnahme nach den zulässigen Verfahren',url:'https://www.nyse.com/direct-listings'},
 {title:'FINRA: Where Do Stocks Trade? US-Handelsplätze und Transparenz',url:'https://www.finra.org/investors/insights/where-do-stocks-trade'},
 {title:'FINRA: Over-the-Counter Equities Trading; Notierung und außerbörsliche Ausführung',url:'https://www.finra.org/investors/insights/over-the-counter-equities-trading'},
 {title:'SEC Investor.gov: Executing an Order',url:'https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/executing-order'},
 {title:'SEC: Trading Basics, Markt- und Limitorders',url:'https://www.sec.gov/tm/investor-alerts-bulletins/trading101basics.pdf'},
 {title:'CFA Institute: Liquidity in Equity Markets; Liquiditätsdimensionen',url:'https://www.cfainstitute.org/sites/default/files/-/media/documents/article/position-paper/liquidity-in-equity-markets-characteristics-dynamics-implications-for-market-quality.pdf'},
 {title:'S&P Dow Jones Indices: Float Adjustment Methodology; konkrete Indexmethodik statt universeller Ausschlussliste',url:'https://www.spglobal.com/spdji/en/documents/index-policies/methodology-sp-float-adjustment.pdf'},
 {title:'S&P Dow Jones Indices: Index Mathematics Methodology',url:'https://www.spglobal.com/spdji/en/documents/methodologies/methodology-index-math.pdf'}
],review:{status:'draft',date:'2026-09-29',note:'Eigene zusammenhängende Emissions-, Orderbuch-, Float-, Volumen- und Indexfälle. Zusätzliche Rechnungen vertiefen die überwiegend beschreibenden Lernziele. Fachlicher Gesamtaudit bleibt offen.'}};
