const {F,T,X,S,G}=require('../author.cjs');
module.exports={id:'governance',intro:[
 'Professionelle Unternehmensführung ist Arbeitsteilung: Viele Kapitalgeber stellen Mittel bereit, wenige Menschen entscheiden täglich über deren Einsatz. Diese Organisation ermöglicht Spezialisierung, schafft aber ein Problem. Wer entscheidet, besitzt häufig mehr Informationen als die Menschen, deren Interessen er vertreten soll. Er kann außerdem von anderen Ergebnissen profitieren als sie.',
 'Corporate Governance verbindet Zuständigkeit, Information, Anreiz und Kontrolle. Wir betrachten zuerst den Konflikt, dann den passenden Mechanismus und schließlich dessen Nutzen und Grenzen. Eigene Zahlenfälle machen private Vorteile, Kontrollkosten, Vergütung und Minderheitenschutz sichtbar. Die Modelle vertiefen die drei CFA-Level-I-Lernziele für 2027; sie behaupten weder eine universell beste Organstruktur noch identische Rechtsregeln in allen Ländern.'
],sections:[
 S('delegation','1. Prinzipal und Agent: Warum Delegation Kontrolle benötigt','a',[
  'Der Prinzipal überträgt einem Agenten eine Aufgabe oder Entscheidung. Der Agent soll innerhalb seines Mandats im Interesse des Auftraggebers handeln. In einer typischen Kapitalgesellschaft wählen Aktionäre ein Board; dieses bestellt und überwacht die operative Leitung. Auch der Aufsichtsakteur ist damit selbst Teil einer Delegationskette. Die rechtlichen Pflichten eines Organs richten sich nach der jeweiligen Gesellschaftsordnung und sind nicht auf Wünsche eines einzelnen Großaktionärs reduzierbar.',
  'Ein Principal-Agent-Problem entsteht, wenn abweichende Interessen mit unvollständiger Beobachtbarkeit oder Kontrolle zusammentreffen. Der Eigentümer sieht beispielsweise Umsatz und Gewinn, aber nicht jede Prüfung, die das Management vor einem Erwerb tatsächlich vorgenommen hat. Ein schlechtes Ergebnis kann aus Nachlässigkeit stammen oder trotz sorgfältiger Arbeit durch einen unerwarteten Marktwechsel entstehen. Ergebnis und Handlungsqualität sind deshalb nicht gleichzusetzen.',
  T(['Stufe','Delegierte Aufgabe','Worauf Kontrolle achten muss'],[['Aktionäre an Board','Leitung auswählen und überwachen, zentrale Entscheidungen beaufsichtigen.','Kompetenz, Unabhängigkeit, Information, Verantwortlichkeit und Wahlrechte.'],['Board an Geschäftsführung','Strategie umsetzen und laufenden Betrieb führen.','Mandat, Risikogrenzen, nachvollziehbare Berichte und angemessene Anreize.'],['Geschäftsführung an Beschäftigte','Spezifische operative Aufgaben ausführen.','Klare Befugnisse, verlässliche Daten, passende Ziele und wirksame Eskalation.']],'Eine weitere Kontrollstufe beseitigt nicht automatisch jedes Problem; auch Kontrolleure benötigen geeignete Anreize und Informationen.'),
  'Governance versucht nicht, jede operative Entscheidung durch eine Eigentümerversammlung treffen zu lassen. Sie bestimmt vielmehr, welche Entscheidungen delegiert werden, welche Grenzen gelten, welche Informationen zurückfließen und wer bei Abweichungen eingreifen kann. Ein bloßer Organigrammkasten beweist nicht, dass diese Funktionen tatsächlich erfüllt werden.'
 ]),
 S('private-incentives','2. Informationsvorsprung und privater Nutzen','a',[
  'Informationsasymmetrie bedeutet, dass Beteiligte nicht dasselbe entscheidungsrelevante Wissen besitzen. Vor einer Beauftragung kann es schwer sein, Kompetenz oder Zuverlässigkeit eines Kandidaten zu beurteilen. Nach der Beauftragung bleiben Einsatz, Interessenkonflikte oder konkrete Handlungen teilweise verborgen. Auswahl, laufende Überwachung und Vertragsgestaltung lösen daher unterschiedliche Teile des Problems.',
  X('Eine kleine Aktienbeteiligung beseitigt nicht jeden Konflikt','Eine Führungskraft besitzt 2 % der Aktien. Eine von ihr bevorzugte Entscheidung verringert den gesamten Eigenkapitalwert um 2 Millionen Euro, verschafft ihr aber einen separaten privaten Vorteil im Wert von 250.000 Euro. Alle Beträge sind bereits auf denselben Zeitpunkt bezogen; Steuern, Sanktionen, Rufschäden und andere Folgen werden zur isolierten Anreizanalyse ausgeblendet.',[
   F('L_{own}=0{,}02\\cdot2000000=40000,\\qquad\\Delta W_M=250000-40000=210000','Die Führungskraft trägt über ihre Aktien nur zwei Prozent des Unternehmenswertverlusts, erhält den privaten Vorteil aber vollständig.',[['L_{own}','Wertverlust der eigenen Aktien in Euro.'],['\\Delta W_M','Private Nettovermögensänderung im ausdrücklich vereinfachten Modell.']]),
   'Die übrigen Aktionäre verlieren zusammen 1,96 Millionen Euro. Eine persönliche Vermögensmehrung der Führungskraft beweist hier keine Wertschaffung für das Unternehmen. Der Vorteil ist gesondert vom Schaden der Gesellschaft definiert, nicht als zusätzliche Aktienrendite.',
   'Reale Pflichten, Kontrolle, mögliche Sanktionen und künftige Karriereschäden können den Anreiz erheblich verändern. Das Zahlenmodell erklärt einen Konflikt, es bewertet die Handlung nicht als zulässig.'
  ],'Aktienbesitz kann Interessen annähern, garantiert aber keine vollständige Übereinstimmung. Beteiligungsquote, private Vorteile und tatsächliche Kontrollmöglichkeiten müssen zusammen betrachtet werden.'),
  'Ein weiterer Konflikt entsteht bei der Auswahl: Übertriebene Erfolgsdarstellung kann einem ungeeigneten Agenten ein Mandat verschaffen. Die spätere Kontrolle benötigt dann nicht nur Kennzahlen, sondern auch belastbare Nachweise über Entscheidungen und Prozesse. Das verbindet Governance mit der Quellenkritik im Kapitel Abschlussanalyse.'
 ]),
 S('conflict-map','3. Welche Interessen stehen sich konkret gegenüber?','a',[
  T(['Beziehung','Möglicher Konflikt','Passender Ansatzpunkt'],[['Eigentümer und Management','Größe, Komfort oder kurzfristiger Bonus statt nachhaltigem Wert.','Leistungsbeurteilung, unabhängige Überwachung, Vergütungsdesign.'],['Mehrheit und Minderheit','Vorteile außerhalb der Gesellschaft zulasten gemeinsamer Vermögenswerte.','Prüfung nahestehender Geschäfte, faire Verfahren und wirksame Minderheitsrechte.'],['Aktionäre und alte Gläubiger','Risikoverlagerung oder Auszahlung des vorhandenen Vermögenspuffers.','Covenants, angemessene Information, Rang- und Sicherheitenrechte.'],['Management und Beschäftigte','Unrealistische Ziele oder Benachteiligung bei berechtigten Hinweisen.','Klare Aufgaben, faire Verfahren, geschützte Meldewege.'],['Unternehmen und Kunden / Lieferanten','Informationsvorsprung, unsichere Qualität oder einseitige Zahlungsbedingungen.','Verträge, Qualitätsprüfung, verlässliche Beschwerden und Zusammenarbeit.'],['Unternehmen und Öffentlichkeit','Private Vorteile bei ausgelagerten Kosten oder Regelverletzungen.','Rechtlicher Rahmen, Aufsicht, nachvollziehbare Verantwortung.']],'Dies sind mögliche Konflikte. Nicht jede Geschäftsbeziehung ist konfliktbelastet, und nicht jede Gegenpartei ist technisch ein Agent.'),
  'Die Analyse muss den Vorteilsempfänger und den belasteten Anspruch nennen. Ein Mehrheitsaktionär kann wie andere Aktionäre an höherem Gesellschaftswert interessiert sein und zugleich Geschäfte mit einem eigenen anderen Unternehmen bevorzugen. Ein Gläubiger kann ein Projekt mit hohem Aktienpotenzial ablehnen, wenn nur sein Ausfallrisiko steigt. Diese Mechanismen sind verschieden und benötigen unterschiedliche Gegenmaßnahmen.',
  'Das vorangehende Stakeholder-Kapitel leitet die Verteilung zwischen Schuld und Eigenkapital rechnerisch her. Hier fragen wir zusätzlich, wer die problematische Handlung beschließen kann, wer sie sieht, wer widersprechen darf und ob der Widerspruch praktische Folgen hat.'
 ]),
 S('agency-costs','4. Agency-Kosten sind mehr als der Konflikt selbst','a b c',[
  'Agency-Kosten bezeichnen die wirtschaftlichen Kosten einer Delegationsbeziehung mit Interessengegensätzen. In der klassischen Einteilung gehören dazu Überwachungsaufwand des Prinzipals, Bindungs- oder Zusicherungsaufwand des Agenten und ein verbleibender Wohlfahrtsverlust durch nicht vollständig angeglichene Entscheidungen. Ein Konflikt ist die Ursache; Kosten beschreiben seine Folgen und den Aufwand seiner Begrenzung.',
  F('AC=M+B+L','Alle Bestandteile müssen auf einen konsistenten Zeitraum und eine vergleichbare Bewertungsbasis bezogen sein.',[['AC','Gesamte Agency-Kosten im verwendeten Modell.'],['M','Monitoring-Aufwand: Kosten der Überwachung.'],['B','Bonding-Aufwand: Kosten glaubwürdiger Bindung oder Zusicherung durch den Agenten.'],['L','Verbleibender wirtschaftlicher Verlust gegenüber der konfliktfreien Vergleichssituation.']]),
  'Monitoring umfasst beispielsweise zusätzliche Prüfungen und Kontrollkapazität. Bonding meint eine glaubwürdige Bindung des Agenten, etwa überprüfbare Zusagen oder Beschränkungen; der englische Begriff bezeichnet hier keine Unternehmensanleihe. Residual Loss ist der trotz Maßnahmen verbleibende Nachteil und darf nicht mit dem Residualanspruch der Aktionäre verwechselt werden.',
  X('Warum nicht unbegrenzt zusätzliche Kontrolle kaufen?','Eigenes didaktisches Jahresmodell nach Erfüllung aller Pflichtkontrollen: Zusätzlicher freiwilliger Kontrollaufwand m wird in Millionen Euro gemessen. Der geschätzte verbleibende Verlust ist 12 geteilt durch 1 plus m. Ein zusätzlicher konstanter Bindungsaufwand beträgt 0,5 Millionen. Die Funktion ist eine Modellannahme, keine empirisch geschätzte allgemeine Gesetzmäßigkeit.',[
   F('AC(m)=m+0{,}5+\\frac{12}{1+m},\\qquad m\\geq0','Mehr Überwachung senkt hier den verbleibenden Schaden, aber mit abnehmender zusätzlicher Wirkung.',[['AC(m)','Gesamte jährliche Modellkosten in Millionen Euro.'],['m','Zahlenwert des zusätzlichen jährlichen Monitoring-Aufwands, gemessen in Millionen Euro.']]),
   T(['Monitoring m','Bindungsaufwand','Verbleibender Verlust','Gesamtkosten'],[['0','0,5','12','12,5'],['1','0,5','6','7,5'],['2','0,5','4','6,5'],['3','0,5','3','6,5'],['5','0,5','2','7,5']],'Von null auf eins spart eine zusätzliche Million sechs Millionen Verlust; von drei auf fünf spart sie bei zwei Millionen Mehrkosten nur eine Million Verlust.'),
   F("AC'(m)=1-\\frac{12}{(1+m)^2}=0\\quad\\Longrightarrow\\quad m^*=\\sqrt{12}-1\\approx2{,}46",'Am inneren Minimum entspricht die zusätzliche Verlustminderung dem zusätzlichen Aufwand. Links davon überwiegt die Ersparnis, rechts davon der Aufwand.',[["AC'(m)",'Änderungsrate der gesamten Modellkosten bei höherem Monitoring-Aufwand.'],['m','Monitoring-Aufwand als Zahlenwert in Millionen Euro.'],['m^*','Im kontinuierlichen Modell kostenminimierender Zusatzaufwand.']]),
   'Die Verlustminderung je zusätzlicher Einheit nimmt hier mit wachsendem m ab. Daher wechselt die Änderungsrate von negativ zu positiv und der gefundene Punkt ist ein Minimum. Diese Herleitung ist eine didaktische Vertiefung, keine Empfehlung für ein reales Budget und kein auswendig zu lernender CFA-Grenzwert.'
  ],'Verglichen werden zulässige zusätzliche Maßnahmen. Gesetzliche Mindestanforderungen, unverzichtbarer Schutz und schwer quantifizierbare Schäden dürfen nicht allein wegen eines errechneten Erwartungswerts entfallen.'),
  G({id:'agency-control-costs',title:'Zusätzliche Kontrolle senkt den Restschaden, kostet aber selbst Ressourcen',caption:'Eigenes hypothetisches Jahresmodell: veränderlicher Monitoring-Aufwand, konstanter Bindungsaufwand 0,5 und verbleibender Verlust gemäß der oben hergeleiteten Funktion, jeweils in Mio. Euro. Pflichtkontrollen sind bereits erfüllt.',reading:'Die fallende Verlustkurve und der steigende Kontrollaufwand ergeben eine Gesamtkostenkurve mit einem Minimum bei rund 2,46 Mio. Euro Monitoring. Danach steigt die Summe trotz weiter sinkendem Restverlust. Die Form illustriert eine Abwägung, keine empirische Wirkungsgarantie.',plot:{x:[0,6],y:[0,14],xTicks:[0,1,2,3,4,5,6],xLabel:'Zusätzlicher Monitoring-Aufwand in Mio. Euro',yLabel:'Jährliche Modellkosten in Mio. Euro',series:[{name:'Monitoring + Bonding',points:Array.from({length:61},(_,i)=>[i/10,i/10+.5])},{name:'Verbleibender Verlust',points:Array.from({length:61},(_,i)=>[i/10,12/(1+i/10)])},{name:'Gesamtkosten',points:[...Array.from({length:61},(_,i)=>i/10),Math.sqrt(12)-1].sort((a,b)=>a-b).map(m=>[m,m+.5+12/(1+m)])}],marks:[{x:Math.sqrt(12)-1,y:2*Math.sqrt(12)-.5,label:'Minimum: m ≈ 2,46',dx:8,dy:-16}]}})
 ]),
 S('board-structure','5. Leitung und Aufsicht organisatorisch zuordnen','b',[
  'Das Board legt oder beaufsichtigt den strategischen Rahmen, bestellt und beurteilt die Leitung und überwacht wesentliche Risiken und Kontrollsysteme. Die operative Geschäftsführung organisiert den laufenden Betrieb. Gute Governance macht diese Rollen ausdrücklich, statt dieselbe Entscheidung unklar mehreren Gremien zuzuweisen. Welche Entscheidungen zustimmungspflichtig sind, hängt von Recht, Satzung und Mandat ab.',
  T(['Grundstruktur','Organisation','Was dadurch noch nicht bewiesen ist'],[['Einstufig / Unitary Board','Ein Board mit geschäftsführenden und nicht geschäftsführenden Mitgliedern im jeweiligen Modell.','Nicht jedes nicht geschäftsführende Mitglied ist unabhängig.'],['Zweistufig / Two-Tier Board','Leitungsorgan und getrenntes Aufsichtsorgan; nähere Besetzung nach geltenden Regeln.','Organisatorische Trennung allein garantiert weder Fachwissen noch wirksame Kontrolle.'],['Getrennte CEO- und Chair-Rolle','Operative Leitung und Vorsitz der Aufsichtsfunktion liegen bei unterschiedlichen Personen.','Private Beziehungen oder Informationsabhängigkeit können trotzdem den Widerspruch erschweren.']],'Keines der Modelle schafft ohne geeignete Personen, Informationen und Verantwortlichkeit automatisch gute Ergebnisse.'),
  'In einem einstufigen System kann eine Zusammenlegung von CEO und Chair die Abstimmung beschleunigen, zugleich aber die Prüfung eigener Entscheidungen erschweren. Ein unabhängiger Vorsitz oder Lead Independent Director kann einen Gegenpol schaffen. Entscheidend ist, ob unabhängige Mitglieder selbst Themen setzen, Informationen anfordern und ohne operative Leitung beraten können.',
  'Die Zusammensetzung sollte zum Geschäft passen: Ein komplexes Finanzunternehmen benötigt andere Fachkenntnisse als ein kleiner industrieller Spezialist. Unterschiedliche Erfahrungen können blinde Flecken verringern. Zu viele Mandate, schwache Vorbereitung oder fehlende Zeit begrenzen die Wirkung auch hervorragend klingender Lebensläufe.'
 ]),
 S('committees','6. Ausschüsse vertiefen die Arbeit, ersetzen nicht die Verantwortung','b c',[
  T(['Ausschuss / Funktion','Typische Aufgabe','Zu prüfende Grenze'],[['Audit Committee','Überwachung von Berichterstattung, Abschlussprüfung und relevanten internen Kontrollen.','Es erstellt nicht selbst den Abschluss und darf Prüfung nicht durch operative Selbstkontrolle ersetzen.'],['Remuneration Committee','Vergütungssystem, Leistungsbedingungen und Interessenkonflikte bei Bezahlung prüfen.','Die Begünstigten sollen ihre eigene Vergütung nicht unkontrolliert bestimmen.'],['Nomination Committee','Passende Kandidaten, Nachfolge, Eignung und Zusammensetzung vorbereiten.','Ein bloßer Vorschlag aus dem bestehenden persönlichen Netzwerk schafft noch keine unabhängige Auswahl.'],['Risk Committee oder zugeordnete Risikofunktion','Wesentliche Risiken, Grenzen und Berichterstattung vertieft überwachen.','Geschäftsführung bleibt für laufende Risikosteuerung verantwortlich.']],'Aufgaben, Besetzung und rechtliche Anforderungen unterscheiden sich. Ausschüsse unterstützen die Arbeit des Boards; Verantwortung verschwindet durch Delegation nicht einfach.'),
  'Unabhängigkeit ist mehr als das Fehlen eines aktuellen Arbeitsvertrags. Bedeutende Geschäftsbeziehungen, familiäre Verbindungen, Abhängigkeit vom Großaktionär oder erhebliche zusätzliche Vergütung können das Urteil beeinflussen. Eine formale Checkliste ist nützlich, muss aber durch die tatsächliche Beziehung und das beobachtbare Verhalten ergänzt werden.',
  'Zugleich ist Unabhängigkeit ohne Kompetenz und Zugang wenig wirksam. Ein Audit Committee benötigt verständliche, rechtzeitige Information, die Möglichkeit zu vertraulichen Gesprächen mit Prüfern und ein Verfahren zur Nachverfolgung offener Punkte. Eine regelmäßig wiederkehrende erhebliche Schwäche ohne Verantwortlichen und Frist ist ein anderes Signal als eine erkannte und nachweisbar behobene Schwäche.',
  'Für Investoren sind daher Zusammensetzung, Mandate, Anwesenheit, einschlägige Erfahrung, Berichtswege und dokumentierte Reaktionen gemeinsam aussagekräftig. Eine hohe Anzahl an Sitzungen ist allein kein Qualitätsmaß: Sie kann intensive Arbeit oder eine schlecht gesteuerte Krise widerspiegeln.'
 ]),
 S('equity-pay','7. Aktien und Optionen setzen unterschiedliche Anreize','a b',[
  'Eine Aktienzuteilung macht die Führungskraft an positiven und negativen Kursänderungen beteiligt. Eine gewöhnliche Kaufoption zahlt bei Ausübung nur den positiven Unterschied zwischen Kurs und Ausübungspreis. Unterhalb des Ausübungspreises ist ihr Auszahlungsbetrag null. Die Form der Beteiligung kann deshalb beeinflussen, wie zusätzliche Streuung des Ergebnisses attraktiv erscheint.',
  F('W_S=N_S S_T,\\qquad W_O=N_O\\max(S_T-K,0)','Verglichen werden Bruttowerte einer gehaltenen Aktienzuteilung und vollständig ausübbarer Optionen am gemeinsamen Endzeitpunkt, ohne Gebühren, Steuer oder Dividende.',[['W_S','Endwert der betrachteten Aktienzuteilung.'],['W_O','Auszahlungswert der betrachteten Optionszuteilung nach Zahlung des Ausübungspreises.'],['N_S','Anzahl zugeteilter Aktien.'],['N_O','Anzahl Optionen, hier je auf eine Aktie.'],['S_T','Aktienkurs am Endzeitpunkt T.'],['K','Ausübungspreis je Option.'],['T','Gemeinsamer Bewertungs- beziehungsweise Ausübungszeitpunkt.']]),
  X('Gleicher erwarteter Aktienkurs, anderer erwarteter Optionsbetrag','Eigener Vergleich: 2.000 Aktien oder 10.000 Optionen mit Ausübungspreis 50 Euro. Eine Strategie führt sicher zu einem Endkurs von 60. Eine riskantere führt mit je 50 % zu 30 oder 90. Keine Dividenden, Steuern, Kosten oder weiteren Bedingungen. Die beiden Zuteilungen werden nicht als heute gleichwertige Vergütungspakete behauptet.',[
   T(['Strategie / Zustand','Endkurs','Wert der 2.000 Aktien','Auszahlung der 10.000 Optionen'],[['Sicher','60 €','120.000 €','100.000 €'],['Riskant, niedriger Zustand','30 €','60.000 €','0 €'],['Riskant, hoher Zustand','90 €','180.000 €','400.000 €'],['Riskant, Erwartungswert','60 €','120.000 €','200.000 €']],'Die Aktie reagiert linear auf den Kurs. Die Option lässt negative Unterschiede zum Ausübungspreis nicht als negative Auszahlung zu.'),
   'Der erwartete Aktienwert bleibt gleich; die erwartete Optionsauszahlung verdoppelt sich. Das illustriert einen möglichen Risikoanreiz bei sonst gleichen Bedingungen. Risikoscheu, übriges Vermögen, eigene Investitionen, Reputation und Arbeitsplatzeinkommen können die persönliche Entscheidung verändern.',
   'Diese Endauszahlungen sind keine heutigen Optionspreise. Für einen Preis wären Zeit, Risiko, Handelbarkeit und weitere Bewertungsannahmen erforderlich. Auch Bilanzaufwand aktienbasierter Vergütung wird nach seinen Rechnungslegungsregeln bestimmt.'
  ],'Mehr Aktienbezug ist nicht automatisch bessere Governance. Instrument, Laufzeit, Haltepflicht, Ausübungsbedingungen und gesamtes Anreizpaket müssen zur Aufgabe passen.')
 ]),
 S('bonus-horizon','8. Kennzahl, Schwelle und Zeithorizont verbinden','a b c',[
  'Eine erfolgsabhängige Vergütung benötigt eine geeignete Erfolgsgröße. Umsatz allein kann unrentables Wachstum belohnen; Gewinn kann durch Schätzungen, unterlassene Ausgaben oder zusätzliches Risiko steigen. Kennzahlen mit einer harten Schwelle erzeugen besonders in ihrer Nähe einen starken Anreiz, den sichtbaren Wert über diese Grenze zu bringen.',
  X('Heutiger Bonus, spätere zusätzliche Kosten','Ein Vertrag zahlt fünf Prozent des Jahresgewinns oberhalb von zehn Millionen Euro, höchstens 0,5 Millionen. Der echte Gewinn vor einer Entscheidung ist 9,8 Millionen. Verschobene notwendige Wartung erhöht den heutigen Gewinn um eine Million, verursacht im Folgejahr aber 1,3 Millionen zusätzliche Wartungszahlung. Zur isolierten Rechnung: Diskontsatz null, keine Steuern, vollständige Cashwirkung der Wartung und keine weiteren Folgen. Der Bonus wird sofort gezahlt.',[
   F('B(\\Pi)=\\min\\{0{,}5;\\ 0{,}05\\max(\\Pi-10,0)\\}','Gewinn und Bonus werden in Millionen Euro gemessen. Die Formel zeigt zuerst die Schwelle und anschließend die Obergrenze.',[['B(\\Pi)','Bonusbetrag in Millionen Euro bei Jahresgewinn Π.'],['\\Pi','Für den Vertrag verwendeter Jahresgewinn vor dem Bonus in Millionen Euro.']]),
   F('B(9{,}8)=0,\\qquad B(10{,}8)=0{,}04','Die Verschiebung schafft im Modell 40.000 Euro Bonus, obwohl sie den operativen Gesamtwert mindert.',[['B(9{,}8)','Bonus beim unveränderten Ausgangsgewinn.'],['B(10{,}8)','Bonus beim durch Wartungsverschiebung erhöhten ausgewiesenen Gewinn.']]),
   F('\\Delta V=1-1{,}3-0{,}04=-0{,}34','Eine Million heute gesparte Zahlung minus spätere 1,3 Millionen und zusätzlicher Bonus ergibt einen Gesamtverlust von 340.000 Euro.',[['\\Delta V','Gesamte Cashwertänderung für die Gesellschaft in Millionen Euro beim Diskontsatz null.']]),
   'Ein mehrjähriger Maßstab und Kontrollen des Wartungszustands können diesen Konflikt besser erfassen als allein die aktuelle Gewinnschwelle. Mehr Kennzahlen helfen jedoch nur, wenn sie konsistent, überprüfbar und nicht beliebig nachverhandelbar sind.'
  ],'Der Anreiz erklärt, warum Berichtsqualität, operative Kontrolle und Vergütung zusammengehören. Eine formale Zielerreichung ist noch kein Nachweis wirtschaftlichen Erfolgs.'),
  'Vesting und Haltebedingungen können kurzfristigen Ausstieg begrenzen. Malus reduziert noch nicht endgültig ausgezahlte oder unverfallbare variable Vergütung nach den geltenden Bedingungen; Clawback verlangt bereits gezahlte Vergütung zurück. Auslöser, Fristen und Durchsetzbarkeit sind zu prüfen. Eine Klausel auf Papier beweist weder automatische Rückholung noch gleiche Regeln in jedem Land.'
 ]),
 S('minority-protection','9. Nahestehende Geschäfte und Minderheiten prüfen','a b c',[
  'Ein Related-Party-Geschäft verbindet die Gesellschaft mit einer ihr nahestehenden Person oder Einheit, etwa über Kontrolle oder eine Schlüsselposition. Solche Beziehungen können nützliche Geschäfte ermöglichen, bergen aber zusätzliche Konflikte. Ein Geschäft ist nicht allein wegen der Beziehung nachteilig; umgekehrt beweist Offenlegung allein keine Angemessenheit des Preises.',
  X('Der Großaktionär kann trotz eigenem Anteilsverlust gewinnen','Eine kontrollierende Person hält 60 % der Käufergesellschaft und 100 % der Verkäufergesellschaft. Die Käuferin zahlt für einen Vermögenswert zwei Millionen Euro über seinem fairen Wert. Keine Steuern, Synergien, Sanktionen oder sonstigen Effekte; beide Werteffekte treffen sofort ein.',[
   T(['Betroffener Anspruch','Wertänderung'],[['Gesamte Käufergesellschaft','−2,0 Mio. €'],['60-%-Anteil der kontrollierenden Person an der Käuferin','−1,2 Mio. €'],['Übrige 40 % der Käuferin','−0,8 Mio. €'],['Vollständig gehaltene Verkäuferin: Vorteil aus dem Mehrpreis','+2,0 Mio. €']],'Der volle Vorteil beim Verkäufer und die nur anteilige Belastung beim Käufer erzeugen den Konflikt.'),
   F('\\Delta W_C=2-0{,}60\\cdot2=0{,}8','Die kontrollierende Person gewinnt netto 0,8 Millionen; die Minderheit verliert denselben Betrag.',[['\\Delta W_C','Nettoänderung des Vermögens der kontrollierenden Person in Millionen Euro.']]),
   'Eine unabhängige Preisprüfung, ein Verfahren ohne entscheidende Mitwirkung des Begünstigten und wirksame Rechte nicht interessierter Eigentümer können den Konflikt begrenzen. Welche Schritte vorgeschrieben oder verfügbar sind, richtet sich nach dem maßgeblichen Recht und Vertrag.'
  ],'Mehrheitseigentum schafft nicht automatisch identische Interessen aller Aktionäre. Zusätzliche Beteiligungen und Beziehungen gehören zur Analyse.'),
  'IAS 24 macht solche Beziehungen und Transaktionen für Abschlussadressaten sichtbar. Die Offenlegung einer Transaktion ist eine Informationsfunktion; sie ersetzt weder eine wirtschaftliche Angemessenheitsprüfung noch die rechtlich erforderliche Genehmigung. Ein angeblich marktüblicher Preis braucht geeignete Vergleichsdaten und nachvollziehbare Bedingungen.'
 ]),
 S('shareholder-rights','10. Eigentümerrechte müssen praktisch nutzbar sein','b',[
  'Aktionäre können je nach geltenden Regeln über Organbesetzung, grundlegende Strukturentscheidungen und bestimmte Anträge abstimmen. Hauptversammlungen, Sonderversammlungen, transparente Unterlagen und angemessene Fristen machen diese Rechte nutzbar. Ein formales Stimmrecht hilft wenig, wenn Informationen zu spät kommen oder Kandidaturen praktisch blockiert werden.',
  'Proxy Voting bezeichnet die Stimmabgabe durch einen bevollmächtigten Vertreter beziehungsweise ein entsprechendes Vertretungsverfahren. Das ist vom bloßen Aktienverkauf zu unterscheiden. Institutionelle Anleger können außerdem mit der Führung sprechen, Anträge stellen oder sich unter geltenden Regeln koordinieren. Sie haben ihrerseits Pflichten gegenüber den Menschen, deren Geld sie verwalten.',
  X('Ein Wahlsystem verändert den Einfluss einer Minderheit','Eigenes Beispiel mit 100 gleich stimmberechtigten Aktien, vollständiger Teilnahme und drei gleichzeitig zu besetzenden Board-Sitzen. Die Minderheit hält 30 Aktien, die Mehrheit 70. Die drei Kandidaten mit den meisten Stimmen gewinnen; keine weiteren Sonderrechte.',[
   'Bei getrennter einfacher Abstimmung je Sitz kann die geschlossene Mehrheit jeweils 70 gegen 30 Stimmen einsetzen und alle drei Sitze besetzen.',
   'Bei Cumulative Voting besitzt die Minderheit 30 mal drei, also 90 kumulierbare Stimmen. Setzt sie alle auf eine Person, verfügt die Mehrheit insgesamt über 210 Stimmen. Um alle drei eigenen Kandidaten jeweils über 90 zu bringen, bräuchte sie mindestens 273 Stimmen. Selbst drei Gleichstände mit je 90 Stimmen würden bereits 270 Stimmen benötigen. Beides ist hier unmöglich.',
   F('V_M=30\\cdot3=90,\\qquad V_H=70\\cdot3=210','Kumulierte Stimmen ergeben sich aus Aktienzahl mal Zahl gleichzeitig vergebener Sitze. Die Verteilung auf Kandidaten entscheidet über das Ergebnis.',[['V_M','Gesamtzahl kumulierbarer Stimmen der Minderheit.'],['V_H','Gesamtzahl kumulierbarer Stimmen der Mehrheit.']]),
   'Die Minderheit kann im angegebenen Fall einen Sitz sichern, aber nicht allein die Mehrheit des Boards bestimmen. Bei anderen Beteiligungsquoten, Teilnahme, Sitzanzahl oder Wahlregeln ist das Ergebnis neu zu prüfen.'
  ],'Die wirtschaftliche Beteiligungsquote bleibt 30 %. Das Wahlverfahren verändert ihre Umsetzbarkeit in Aufsichtseinfluss, nicht den Anteil am Gesellschaftsvermögen.'),
  'Ein Staggered Board, bei dem nur ein Teil der Mandate gleichzeitig zur Wahl steht, kann Kontinuität fördern und einen schnellen Austausch erschweren. Übernahmeschutz kann Zeit für Verhandlungen verschaffen, zugleich aber schwache Leitung verfestigen. Kein einzelnes Merkmal ist ohne Kontext ein abschließendes Qualitätsurteil.'
 ]),
 S('reporting-controls','11. Bericht, interne Kontrolle und Prüfung unterscheiden','b c',[
  'Transparenz verringert Informationsasymmetrie nur, wenn Angaben rechtzeitig, verständlich und verlässlich sind. Management verantwortet Prozesse und Berichterstellung; das Board überwacht. Eine unabhängige Abschlussprüfung erhöht die Verlässlichkeit innerhalb ihres Prüfungskreises. Sie garantiert weder jeden einzelnen Betrag noch die künftige Profitabilität oder vollständige Betrugsfreiheit.',
  T(['Funktion','Konkretes Beispiel','Grenze'],[['Operative Kontrolle','Eine Zahlung benötigt getrennte Freigabe; Stammdatenänderungen werden dokumentiert.','Zusammenwirken mehrerer Beteiligter oder Management Override kann eine Kontrolle umgehen.'],['Risikomanagement / Compliance','Risikolimits, Vertragsbedingungen und Regelverstöße werden überwacht und eskaliert.','Diese Tätigkeiten gehören zur Unternehmenssteuerung und sind nicht allein durch ihre Bezeichnung unabhängig.'],['Interne Revision','Unabhängige Prüfung und Beratung zur Angemessenheit und Wirksamkeit von Prozessen.','Sie soll nicht ungeschützt ihre eigenen zuvor verantworteten operativen Entscheidungen prüfen.'],['Externe Abschlussprüfung','Prüfungsurteil zu den betroffenen Abschlüssen nach dem relevanten Prüfungsrahmen.','Der genaue Umfang des Auftrags begrenzt die Aussage; reine Zukunftsprognosen sind nicht automatisch mitgeprüft.']],'Klare Zuständigkeit verhindert, dass jede Stelle fälschlich annimmt, die andere habe das Risiko bereits vollständig übernommen.'),
  'Das IIA betont die Unterscheidung zwischen Verantwortung des Leitungs- und Aufsichtsrahmens, Risikosteuerung durch das Management und unabhängiger interner Prüfung. Praktisch braucht die Interne Revision ungehinderten Zugang zu relevanten Informationen, geeignete Ressourcen und einen wirksamen Berichtskanal zur Aufsicht. Zusammenarbeit ist sinnvoll; sie darf ihre objektive Beurteilung nicht beseitigen.',
  'Ein Beispiel ist die wiederholte nachträgliche Änderung von Lieferantenbankdaten. Die operative Ebene benötigt Berechtigungen und Kontrollnachweise; Risikofunktionen untersuchen Muster; die Interne Revision beurteilt die Wirksamkeit des Systems; das zuständige Aufsichtsorgan verfolgt erhebliche offene Mängel. Nur ein zusätzliches Formular einzuführen, ohne Zuständigkeit und Nachverfolgung, löst die Ursache möglicherweise nicht.'
 ]),
 S('creditor-controls','12. Gläubigerrechte überwachen etwas anderes als Aktionärsstimmen','a b',[
  'Gläubiger kaufen einen vertraglichen Zahlungsanspruch. Ihre Governanceinstrumente setzen daher besonders bei Information, Deckung, Rang, Verschuldung und Ausschüttungen an. Ein Covenant kann auf einer Kennzahl beruhen oder eine bestimmte Handlung verbieten. Definitionswahl, Prüfungstermin und Rechtsfolge sind ebenso wichtig wie der Zahlenwert.',
  X('Die Vertragsdefinition entscheidet über die Einhaltung','Ein eigener Vertrag erlaubt höchstens das Dreifache des ausdrücklich definierten jährlichen Covenant-EBITDA als Nettoschuld. Schuld beträgt 120, anrechenbarer Cash 20 und Covenant-EBITDA 40. Im Stressfall fällt dieses EBITDA auf 30. Alle Beträge in derselben Millioneneinheit; keine weiteren Bereinigungen.',[
   F('L_0=\\frac{120-20}{40}=2{,}5,\\qquad L_1=\\frac{120-20}{30}\\approx3{,}33','Der Schuldendienstpuffer verschlechtert sich, obwohl die Schuld selbst nicht steigt.',[['L_0','Nettoverschuldungsquote gemäß Vertrag im Ausgangsfall.'],['L_1','Dieselbe Quote im Stressfall.']]),
   'Im Ausgangsfall ist die Grenze eingehalten. Bei genau diesem Stresswert wird sie überschritten. Ob Nachbesserung, höhere Marge, Zustimmung zu einer Ausnahme oder Kündigungsrechte folgen, ergibt sich aus dem Vertrag; die Quote allein legt die Rechtsfolge nicht fest.',
   'Wer nur anrechenbaren Cash von 20 für eine Tilgung von 20 verwendet, senkt Schuld auf 100 und Cash auf null. Die Nettoschuld bleibt 100 und die Quote deshalb 3,33. Eine rein innerhalb der Nettoschuld umgeschichtete Zahlung heilt diese konkrete Kennzahl nicht.'
  ],'Eine Kennzahl wird nicht durch eine beliebige wirtschaftlich ähnlich klingende Alternative ersetzt. Anrechenbarer Cash und zulässige EBITDA-Bereinigungen müssen aus dem tatsächlichen Vertrag stammen.'),
  'Ein einzelner Kreditgeber und eine verstreute Anleihegläubigerschaft können unterschiedliche Verhandlungskosten haben. Vertreter, Zustimmungsmehrheiten und Informationspflichten helfen bei Koordination. Sie beseitigen weder Interessengegensätze zwischen Rangklassen noch das im Stakeholder-Kapitel erklärte Unterinvestitionsproblem.'
 ]),
 S('other-mechanisms','13. Beschäftigte, Geschäftspartner, Markt und Staat','b c',[
  'Beschäftigte beobachten operative Vorgänge häufig früher als ein Board. Klare Verantwortlichkeiten, Schulung, faire Leistungsbeurteilung und verlässliche Hinweiswege können Fehler sichtbar machen. Whistleblowing-Verfahren benötigen eine angemessene vertrauliche Bearbeitung, Schutz vor unzulässigen Repressalien und eine Stelle, die auch bei Hinweisen gegen Vorgesetzte unabhängig reagieren kann. Ein Hinweis ist ein Untersuchungsanlass, noch kein Beweis.',
  'Eine hohe Zahl von Meldungen kann viele Missstände oder eine vertrauenswürdige Meldekultur anzeigen. Eine sehr niedrige Zahl kann gute Prozesse oder Angst vor Nachteilen bedeuten. Aussagekräftiger sind daneben Bearbeitungsdauer, substantiierte Befunde, Wiederholungen und tatsächlich umgesetzte Abhilfen. Die Kennzahl muss im Kontext interpretiert werden.',
  'Kunden und Lieferanten wirken über Verträge, Qualitätsnachweise, Beschwerden und die Möglichkeit des Anbieterwechsels. Langfristige Beziehungen können Informationen und Vertrauen schaffen, zugleich Abhängigkeit und Druck erzeugen. Auditrechte oder Qualitätsklauseln helfen nur, wenn sie angemessen genutzt und erhebliche Befunde nachverfolgt werden.',
  'Der Markt für Unternehmenskontrolle kann schwache Leitung disziplinieren, wenn Übernehmer eine Verbesserung erwarten und tatsächlich handeln können. Übernahmehindernisse, Finanzierung, Informationskosten und Interessen des Erwerbers begrenzen diesen Mechanismus. Auch Wettbewerb um Kunden, Fachkräfte und Kapital setzt Anreize. Er ersetzt keine konkrete Pflicht zur ordnungsgemäßen Leitung.',
  'Staatliche Regeln und ihre Durchsetzung schaffen einen äußeren Rahmen, etwa durch Gesellschafts-, Arbeits-, Wettbewerbs- oder Wertpapierrecht. Branchen und Länder unterscheiden sich. Die Existenz eines Gesetzes beweist noch keine gleich wirksame Anwendung; freiwillige Codes und verbindliche Pflichten müssen getrennt werden.'
 ]),
 S('risk-benefit','14. Governance wirkt über operative, rechtliche und finanzielle Folgen','c',[
  T(['Bereich','Schwache Governance kann bewirken','Wirksame Governance kann verbessern'],[['Operativ','Fehlinvestitionen, unklare Verantwortung, Qualitätsmängel oder verspätete Reaktion.','Kapitalallokation, Risikosteuerung, verlässliche Prozesse und Anpassungsfähigkeit.'],['Rechtlich / regulatorisch','Sanktionen, Rechtskosten, Lizenzprobleme und unerfüllte Verpflichtungen.','Frühe Erkennung und nachvollziehbare Einhaltung relevanter Pflichten.'],['Reputation / Beziehungen','Vertrauensverlust bei Kunden, Personal, Lieferanten und Kapitalgebern.','Glaubwürdige Information und tragfähige Zusammenarbeit.'],['Finanziell','Cashverluste, teure Finanzierung, erschwerter Kapitalzugang und geringere Bewertung.','Belastbarere Cashflows, geringere Informationsprobleme und bessere Finanzierungsmöglichkeiten.']],'Diese Wirkungen sind Möglichkeiten mit konkreten Übertragungswegen, keine garantierte Renditeliste.'),
  X('Eine zusätzliche freiwillige Kontrolle als wirtschaftliche Entscheidung','Alle Pflichtkontrollen sind bereits erfüllt. Eine zusätzliche Maßnahme kostet jährlich 0,4 Millionen. Im eigenen Einjahresmodell reduziert sie die Wahrscheinlichkeit eines vollständig erfassten Schadens von 10 Millionen von 8 % auf 3 %. Keine Steuern, Diskontierung oder sonstigen Wirkungen.',[
   F('\\Delta V=(0{,}08-0{,}03)\\cdot10-0{,}4=0{,}1','Eine halbe Million erwarteter Schadensminderung übersteigt die laufenden Kosten um 0,1 Millionen.',[['\\Delta V','Erwarteter jährlicher Nettovorteil in Millionen.']]),
   'Die Maßnahme macht den Schaden nicht unmöglich. Eine veränderte Schadenhöhe, nicht erfasste Auswirkungen oder schlechte Durchsetzung kann das Urteil ändern. Ein Ereignis von zehn Millionen kann außerdem einen Liquiditätsengpass auslösen, obwohl sein Erwartungswert viel kleiner ist.'
  ],'Kosten und Nutzen helfen bei der Wahl zusätzlicher Maßnahmen. Notwendige Pflichten und Risiken, die die Existenz oder Rechte anderer betreffen, werden dadurch nicht auf einen einzigen Erwartungswert reduziert.'),
  'Ein günstiger beobachteter Zusammenhang zwischen Governance-Merkmalen und Unternehmensleistung beweist für sich keine Ursache. Bereits erfolgreiche Firmen können sich bessere Kontrollen leisten; Branche und Eigentümerstruktur können beide Größen beeinflussen. Für eine Anlageentscheidung zählt zudem, welche Verbesserung bereits im Wertpapierpreis enthalten ist.'
 ]),
 S('integrated-case','15. Vom Warnsignal zu einem überprüfbaren Maßnahmenpaket','a b c',[
  'Die fiktive Nordwerk AG steigert ihren berichteten Gewinn. Gleichzeitig werden Wartung verschoben, der Bonus basiert auf Jahresgewinn, der CEO führt auch das Board, ein Lieferant gehört dem Großaktionär und erhebliche Kontrollmängel tauchen wiederholt im internen Bericht auf. Kein einzelnes Merkmal beweist Betrug. Ihre Kombination erfordert jedoch gezielte Fragen und belastbare Nachweise.',
  T(['Befund','Möglicher Mechanismus','Gezielter nächster Prüfschritt'],[['Gewinn steigt, Wartung fällt','Kurzfristiger Bonus könnte zukünftige Kosten verdrängen.','Wartungsplan, Anlagenzustand, mehrjährige Zahlungen und Bonusdefinition abstimmen.'],['Lieferant gehört dem Großaktionär','Preis oder Bedingungen könnten Vorteile außerhalb der Firma übertragen.','Beziehung, Vergleichsangebote, Genehmigung und Mitwirkung interessierter Personen untersuchen.'],['CEO führt Board und bestimmt Informationsfluss','Eigene Entscheidungen werden möglicherweise unzureichend hinterfragt.','Informationszugang und eigenständige Arbeit unabhängiger Mitglieder nachweisen.'],['Wiederholter erheblicher Kontrollmangel','Berichte führen möglicherweise nicht zu Abhilfe.','Verantwortliche, Fristen, Statusbelege und Eskalation an zuständige Aufsicht prüfen.'],['Wenige Beschwerden trotz hoher Fluktuation','Meldeweg könnte unbekannt oder mit Angst verbunden sein.','Vertraulichkeit, Erreichbarkeit, Untersuchung und Schutzmaßnahmen prüfen.']],'Eine Gegenmaßnahme soll den gefundenen Mechanismus treffen. Pauschal „mehr Transparenz“ oder „mehr unabhängige Personen“ genügt ohne Umsetzung nicht.'),
  'Die Analyse verknüpft den Befund anschließend mit Cashflows und Risiken. Ein überhöhter Einkaufspreis reduziert operative Marge; verschobene Wartung verändert zukünftige Zahlungen; fehlende Kontrolle kann Unsicherheit und Finanzierungskosten erhöhen. Bereits korrigierte Cashflows dürfen nicht nochmals um denselben erwarteten Verlust gekürzt werden.',
  'Ein brauchbarer Maßnahmenplan benennt Verantwortliche, Termine und einen unabhängigen Nachweis der Wirkung. Nach einer Änderung werden sowohl das Verhalten als auch mögliche Ausweichreaktionen beobachtet. Wird statt Jahresgewinn nun Umsatz belohnt, kann ein gelöstes Problem durch unrentables Wachstum ersetzt werden.'
 ]),
 S('analyst-check','16. Governance beurteilen, ohne Checklistenpunkte mit Qualität zu verwechseln','a b c',[
  'Beginne beim konkreten Geschäftsmodell, den Eigentumsrechten und den wesentlichen Entscheidungen. Suche danach die möglichen Interessengegensätze und Informationslücken. Erst anschließend lässt sich beurteilen, ob Board, Verträge, Berichte, Vergütung und externe Disziplin zusammenpassen. Eine aus vielen formalen Merkmalen gebildete Note kann diesen Zusammenhang verdecken.',
  T(['Prüffrage','Belastbare Evidenz statt bloßer Behauptung'],[['Wer darf entscheiden?','Aktuelle Rechte, Mandate, Zustimmungsvorbehalte und tatsächliche Entscheidungswege.'],['Wer profitiert möglicherweise gesondert?','Beteiligungen, Geschäfte mit nahestehenden Parteien, Vergütung und sonstige Beziehungen.'],['Wer kann unabhängig prüfen?','Kompetenz, Ressourcen, Informationen und nutzbare Berichtskanäle.'],['Was passiert bei Abweichungen?','Konkrete Eskalation, nachvollziehbare Entscheidungen und nachgewiesene Abhilfe.'],['Welche Kosten und Grenzen entstehen?','Kontrollaufwand, verlorene Flexibilität, verbleibende Risiken und Durchsetzbarkeit.'],['Wie beeinflusst der Befund die Anlage?','Begründete Cashflow- oder Risikofolgen relativ zum aktuellen Preis und gehaltenen Anspruch.']],'Der Prüfmaßstab ist die nachvollziehbare Funktion des Systems, nicht die Anzahl vorhandener Richtlinien.'),
  'Für CFA-Fälle hilft die Reihenfolge: Konfliktparteien identifizieren, Mechanismus erklären, passende Kontrolle wählen, Nutzen und Grenze benennen. Eine Antwort, die alle Risiken automatisch verschwinden lässt oder eine formale Eigenschaft als universellen Beweis behandelt, benötigt besonders kritische Prüfung.',
  'Die Verbindung zu Ethics bleibt zentral: Ein zulässiger formaler Prozess entbindet Beteiligte nicht von ihren beruflichen Pflichten. Zugleich sind Unternehmensorgane, Analysten und Anlageverwalter unterschiedliche Rollen. Die Pflichten einer Rolle dürfen nicht ohne Prüfung auf eine andere übertragen werden.'
 ])
],related:[
 {unit:'voting',section:'cumulative',label:'Kumulative Wahlen, Quoren und Mehrheitsschwellen herleiten'},
 {unit:'stakeholders',section:'risk-shifting',label:'Risikoverlagerung zwischen alten Gläubigern und Aktionären nachrechnen'},
 {unit:'stakeholders',section:'debt-overhang',label:'Warum ein vorteilhaftes Projekt an der Nutzenverteilung scheitern kann'},
 {unit:'issuer-forms',section:'voting',label:'Wirtschaftlichen Anteil und Stimmrechtskontrolle trennen'},
 {unit:'reporting-quality',section:'incentives',label:'Anreiz, Gelegenheit und Berichtsverzerrung erkennen'},
 {unit:'analysis-framework',section:'audit',label:'Reichweite eines externen Prüfungsurteils verstehen'},
 {unit:'leases-compensation',section:'share-payments',label:'Vergütungsanreiz und bilanziellen Vergütungsaufwand auseinanderhalten'}
],sources:[
 {title:'CFA Institute: Level I 2027, Corporate Governance, Lernziele',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=9'},
 {title:'CFA Institute: Corporate Governance, Conflicts, Mechanisms, Risks, and Benefits',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/corporate-governance-conflicts-mechanisms-risks-and-benefits'},
 {title:'Jensen / Meckling: Theory of the Firm, Agency Costs and Ownership Structure (Originalaufsatz, World-Bank-Archiv)',url:'https://state-owned-enterprises.worldbank.org/sites/soe/files/reports/Theory%20of%20the%20Firm-%20Managerial%20Behavior%2C%20Agency%20Costs%20and%20Ownership%20Structure.pdf'},
 {title:'OECD: Verantwortlichkeiten, Unabhängigkeit und Ausschüsse des Boards',url:'https://www.oecd.org/en/publications/g20-oecd-principles-of-corporate-governance-2023_ed750b30-en/full-report/component-8.html'},
 {title:'SEC / Investor.gov: Shareholder Voting',url:'https://www.investor.gov/shareholder-voting'},
 {title:'SEC / Investor.gov: Cumulative Voting',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/cumulative-voting'},
 {title:'IFRS Foundation: IAS 24, Angaben zu nahestehenden Personen und Transaktionen',url:'https://www.ifrs.org/issued-standards/list-of-standards/ias-24-related-party-disclosures/'},
 {title:'Institute of Internal Auditors: Rollen und Verantwortung der Governance',url:'https://www.theiia.org/en/content/advocacy/roles-and-responsibilities-of-governance/'}
],review:{status:'draft',date:'2026-09-26',note:'Eigene Konflikt-, Vergütungs-, Minderheiten-, Wahl- und Kontrollrechnungen. Governancefunktion wird von formaler Struktur und rechtlich unterschiedlichen Anforderungen getrennt. Fachlicher Gesamtaudit bleibt offen.'}};
