const {F,T,X,S,G}=require('../author.cjs');
const adoption=t=>100/(1+Math.exp(-.8*(t-6)));
const value=(margin,capitalRatio)=> (242*margin*.75-.03*242*capitalRatio)/(.09-.03);
module.exports={id:'industry',intro:[
 'Die Qualität einer Aktienprognose hängt davon ab, ob das Unternehmen in einem wirtschaftlich verstandenen Umfeld betrachtet wird. Zehn Prozent Umsatzwachstum können durch einen wachsenden Markt, höhere Preise, einen gewonnenen Kunden oder eine Übernahme entstehen. Dieselbe heutige Marge kann auf dauerhaftem Kundennutzen, vorübergehender Knappheit oder ungewöhnlich niedrigen Kosten beruhen. Branchenanalyse trennt diese Ursachen und prüft, wie Wettbewerb die erreichbaren Erträge begrenzt.',
 'Dieses Kapitel behandelt die vier offiziellen Lernziele zu Industry and Competitive Analysis für CFA Level I 2027. Der eigene Nordmarkt-Fall verbindet Marktgrenzen, Größe, Anteilstrends und Profitabilität. Weitere eigene Vergleiche verfolgen Preis-, Kosten-, Kapital- und Umfeldänderungen bis zur Bewertung. Konzentrationsrechnung, Diffusionsmodell und Barwertherleitung vertiefen die Intuition; sie werden nicht als zusätzliche offizielle Speziallernziele ausgegeben. Zahlen und Unternehmen sind hypothetisch; die Klassifikationsbeschreibung wurde mit den verlinkten Primärquellen abgeglichen.'
],sections:[
 S('scope','1. Branche, Unternehmen und Aktie stellen verschiedene Fragen','a b c d',[
  'Eine Branche umfasst nach einer benannten Abgrenzung wirtschaftliche Aktivitäten oder Anbieter. Ihr Umfeld beeinflusst Nachfrage, Preise, Ressourcen und Konkurrenz. Ein Unternehmen besitzt zusätzlich eine eigene Position: Kunden, Kosten, Fähigkeiten, Verträge und Finanzierung. Eine Aktie ist schließlich ein bestimmter Eigentümeranspruch mit einem beobachteten Preis. Eine attraktive Branche garantiert deshalb weder ein gutes Unternehmen noch eine attraktiv bepreiste Aktie.',
  T(['Ebene','Zu prüfende Aussage','Was zusätzlich benötigt wird'],[['Branche','Nachfrage und strukturelle Ertragsmöglichkeiten.','Grenzen, Teilnehmer, Ersatzangebote und Zugangsmöglichkeiten.'],['Unternehmen','Eigene Position gegenüber anderen Anbietern.','Relative Kosten, Leistung, Ressourcen und Ausführung.'],['Finanzprognose','Erwartete Verkäufe, Marge und Kapitalbindung.','Zeitpunkte, Szenarien und nachvollziehbare Treiber.'],['Aktienbewertung','Wert des Eigentümeranspruchs relativ zum Preis.','Investitionsbedarf, Risiko, andere Ansprüche und Preisstichtag.']],'Ein Urteil auf einer Ebene darf nicht ungeprüft auf die nächste übertragen werden.'),
  'Die Analyse dient der Erklärung historischer Ergebnisse, der Entwicklung einer Zukunftsthese, der Auswahl von Vergleichsunternehmen und der Prüfung von Risiken. Entscheidend ist, aus einer Beobachtung eine überprüfbare wirtschaftliche Hypothese zu machen: Was verursacht die Marge, wie lange kann die Ursache wirken und welche Beobachtung würde diese Erklärung widerlegen?'
 ]),
 S('workflow','2. Ein wiederholbarer Analyseprozess','a b c d',[
  T(['Schritt','Konkretes Ergebnis'],[['1. Frage und Markt abgrenzen','Produkt, Kundennutzen, Region, Wertschöpfungsstufe und Zeitraum.'],['2. Teilnehmer und Daten ordnen','Klassifikationssystem, Unternehmen, Segmente, Quellen und Datenstand.'],['3. Markt vermessen','Umsatz oder Menge, Wachstum, Profitabilität, Anteile und Konzentration.'],['4. Wettbewerb erklären','Five Forces mit Beobachtungen und überprüfbaren Gegenhypothesen.'],['5. Umfeld prüfen','PESTLE mit Wirkungskette, Zeithorizont und Unsicherheit.'],['6. Firmenposition vergleichen','Kosten, Differenzierung, Kapital und Fähigkeit zur Umsetzung.'],['7. Prognosefolgen ableiten','Explizite Mengen-, Preis-, Margen- und Investitionsannahmen.'],['8. Aktualisieren','Frühindikatoren, neue Information und Bedingungen der These.']],'Die Reihenfolge organisiert die Arbeit; neue Erkenntnisse können eine frühere Marktdefinition verändern.'),
  'Eine Analystin arbeitet iterativ. Eine zunächst breite Gruppe kann sich als mehrere Märkte mit verschiedenen Kunden herausstellen. Ein scheinbarer Konkurrent kann tatsächlich Lieferant sein. Eine neue technische Alternative kann die Marktgrenze erweitern. Solche Änderungen werden dokumentiert und die betroffenen Größen neu gerechnet.',
  'Das Ergebnis ist keine Sammlung möglichst vieler Branchenfakten. Es ist eine begründete Erklärung, welche Kräfte die zukünftige wirtschaftliche Leistung bestimmen. Quellen, Annahmen und Schlussfolgerungen bleiben erkennbar getrennt.'
 ]),
 S('boundaries','3. Marktgrenzen aus der wirtschaftlichen Frage ableiten','a b c d',[
  'Die Branchenbezeichnung einer Datenbank und der für eine Analyse relevante Markt sind nicht automatisch identisch. Für einen Marktanteil muss der Nenner Angebote enthalten, die für dieselbe Frage vergleichbar sind. Produkt, Kunden, Region, Zeit und Wertschöpfungsstufe werden ausdrücklich benannt. Ob ein Angebot wirtschaftlich austauschbar ist, hängt auch von Leistung, Zugang, Kosten des Wechsels und dem betrachteten Zeithorizont ab.',
  X('Nordmarkt: dieselbe Firma, drei verschiedene Nenner','ThermaFlex verkauft Geräte und externe Wartung industrieller Prozesswärmeanlagen. Untersucht wird zunächst nur externe Wartung in Region Nord innerhalb eines Kalenderjahres, ohne Geräteverkäufe und ohne Wartung durch eigenes Kundenpersonal.',[
   T(['Abgrenzung','Marktumsatz','Passender ThermaFlex-Umsatz','Indizierter Anteil'],[['Externe Wartung in Region Nord','1.000','200','20 %'],['Externe Wartung in größerer Region','2.500','300','12 %'],['Geräte und Wartung in Region Nord','4.000','500','12,5 %']],'Alle Umsätze sind Mio. €. Diese sind drei ausdrücklich verschiedene Fragen, keine widersprüchlichen Rechnungen.'),
   'Der Wartungsumsatz 200 darf nicht durch den Geräte-und-Wartungsmarkt geteilt und als Wartungsanteil interpretiert werden. Umgekehrt darf die gesamte Firma 500 nicht dem engeren Wartungsmarkt zugeordnet werden.'
  ],'Ein Marktanteil ist nur so aussagekräftig wie die gemeinsame Definition von Zähler und Nenner.'),
  'Eine Kundengruppe kann eine lokale Bereitschaftsleistung benötigen, eine andere weltweit beschaffbare Software. Gleiche Rechnungsbezeichnungen bedeuten dann keine identischen Wettbewerbsbedingungen. Die hier gewählte analytische Grenze ist keine abschließende rechtliche Marktabgrenzung; eine konkrete Wettbewerbssache benötigt ihre eigenen geltenden Regeln und Beweise.'
 ]),
 S('taxonomies','4. Klassifikationssysteme nutzen, ohne sie mit dem Markt zu verwechseln','a b',[
  T(['System','Hierarchie oder Erhebungseinheit','Wesentliche Einordnung'],[['GICS','Sector → Industry Group → Industry → Sub-Industry.','Globale Unternehmenseinordnung nach Hauptaktivität; Umsatz ist wichtig, auch Ergebnis und Marktwahrnehmung werden berücksichtigt.'],['ICB','Industry → Supersector → Sector → Subsector.','Unternehmenszuordnung auf Grundlage der Geschäftstätigkeit, Umsatzerlöse und weiterer öffentlicher Informationen.'],['NAICS','Statistische Klassifikation von Betriebsstätten.','Produktionsorientierte Gruppierung wirtschaftlicher Aktivitäten; eine Firma kann mehrere verschieden klassifizierte Betriebsstätten besitzen.']],'Die gleich klingenden Wörter Sector und Industry stehen in GICS und ICB auf verschiedenen Hierarchieebenen. Methodenstand und Erhebungseinheit werden genannt.'),
  'Eine standardisierte Taxonomie unterstützt Universumsauswahl, Portfoliovergleich und Datenorganisation. Sie entscheidet nicht allein, welche Kunden zwischen Angeboten wechseln könnten oder ob zwei Firmen dieselben Risiken und Kapitalbedarfe besitzen. Ein Code ist ein praktischer Startpunkt, keine vollständige wirtschaftliche Analyse.',
  X('Eine Hauptklassifikation verliert Sparteninformation','Ein fiktiver Konzern erzielt sechzig Prozent Umsatz aus Anlagenbau und vierzig Prozent aus Wartungssoftware. Seine standardisierte Hauptzuordnung bildet nicht automatisch jede Tätigkeit als eigenständiges Unternehmen ab.',[
   'Für den Anlagenbereich können Kapazität, Bestellzyklus und Working Capital wichtig sein; für Software Vertragsbindung, Entwicklung und laufender Betrieb. Eine Peer-Suche allein nach der Hauptzuordnung kann einen relevanten Teil der Ertragslogik übersehen.',
   'Die konkrete Zuordnung folgt den Regeln des gewählten Anbieters und wird nicht allein aus einer selbst erfundenen Sechzigprozentregel abgeleitet. Ein analytischer Spartenvergleich kann daneben sinnvoll bleiben.'
  ],'Standardisierte Einordnung und zusätzliche Segmentanalyse ergänzen sich.'),
  'Klassifikationen können geändert werden. Historische Analysen benötigen den damals passenden Stand oder eine offengelegte rückwirkende Harmonisierung. Eine heutige Firmenzuordnung oder ein nachträglich bekannter Spartenumsatz darf nicht unbemerkt in eine frühere Auswahl einfließen.'
 ]),
 S('grouping','5. Alternative Gruppierungen beantworten andere Fragen','a b c',[
  T(['Gruppierung','Geeignete Frage','Wichtige Grenze'],[['Ähnliche Produkte oder Dienstleistungen','Wer konkurriert um vergleichbare Kundenbedürfnisse?','Region, Qualität, Zugang und Ersatzmöglichkeiten bleiben zu prüfen.'],['Geschäftsmodell und Wertschöpfungsstufe','Wer verdient mit einer vergleichbaren Leistung und Zahlungslogik?','Ein Hersteller und ein Händler können denselben Produktnamen, aber andere Kosten besitzen.'],['Wirtschaftliche Treiber','Wer reagiert auf ähnliche Zinsen, Rohstoffpreise oder Endkundennachfrage?','Gemeinsame Risiken bedeuten nicht automatisch direkte Konkurrenz.'],['Zyklus- und Nachfrageeigenschaften','Welche Umsätze reagieren auf Investitionen, Ersatz oder Grundbedarf?','Zyklisch/defensiv ist eine graduelle Beziehung, keine Garantie.'],['Statistische Renditemuster','Welche Anlagen besitzen ähnliche gemessene Risikobeziehungen?','Zeitraum, Finanzierung, Markt- und Währungseinfluss können die Ähnlichkeit erklären.']],'Das Gruppierungskriterium wird aus der Analysefrage gewählt, nicht aus dem bequemsten verfügbaren Datensatz.'),
  'Eine Rohstoffförderfirma und ein Chemiebetrieb können auf denselben Rohstoffpreis entgegengesetzt reagieren. Zwei Firmen aus verschiedenen Produktbranchen können denselben Bauinvestitionszyklus spüren. Eine Renditekorrelation kann für ein Portfolio relevant sein, obwohl die Kunden die Produkte nicht gegeneinander austauschen.',
  X('Ein Peer besitzt zwei Arten von Ähnlichkeit','Ein Wartungsdienst und ein Anlagenhersteller beliefern dieselben Industriekunden. Der Wartungsdienst verdient überwiegend aus vorhandener Anlagenbasis; der Hersteller überwiegend aus neuen Investitionsentscheidungen.',[
   'Gemeinsame Kunden machen beide für einen Endmarktausblick relevant. Sie machen ihren Umsatzzyklus und ihre Kapitalbindung aber nicht gleich.',
   'Für die Bewertung werden wiederkehrender Service, Auftragsschwankung, Kundenvorauszahlung und Investitionsbedarf getrennt. Der gemeinsame Branchenname erklärt diese Unterschiede nicht weg.'
  ],'Eine gute Vergleichsgruppe wird nach der konkreten wirtschaftlichen Eigenschaft begründet.')
 ]),
 S('segments','6. Konsolidierung, Segmente und geografische Exposition','a b c',[
  F('S_{group}=\\sum_j S_{j,external}','Für den Gesamtumsatz werden externe Segmentumsätze konsistent erfasst. Interne Verkäufe zwischen Segmenten dürfen nicht nochmals zum Konzernumsatz addiert werden.',[['S_{group}','Konsolidierter externer Konzernumsatz.'],['j','Segmentindex.'],['S_{j,external}','Umsatz des Segments mit externen Kunden.'],['\\sum','Summe über die einbezogenen Segmente.']]),
  'Ein Firmensitz bestimmt nicht zwingend die wirtschaftliche Nachfrageexposition. Absatzregion, Produktionsstandort, Lieferantenwährung und Finanzierungswährung beantworten unterschiedliche Fragen. Eine im Inland notierte Firma kann fast vollständig von ausländischer Nachfrage und Wechselkursen abhängen.',
  X('Interne Umsätze verzerren die scheinbare Marktgröße','Die Geräteabteilung liefert intern Bauteile für achtzig an die Serviceabteilung. Externe Geräteumsätze betragen zweihundert, externe Serviceumsätze hundert.',[
   F('S_{group}=200+100=300','Die internen achtzig gehören nicht zusätzlich zum externen Gruppenumsatz.',[['S_{group}','Konsolidierter externer Umsatz.']]),
   'Eine Datensammlung mit Segmentumsätzen einschließlich interner Transfers würde 380 anzeigen. Für das Wachstum externer Kundennachfrage wäre dieser Betrag unpassend. Segmentmargen benötigen außerdem eine konsistente Behandlung zentraler Kosten und interner Verrechnung.'
  ],'Die Erhebungseinheit und der Konsolidierungsumfang werden vor dem Addieren festgelegt.')
 ]),
 S('data','7. Datenqualität und Evidenz gehören zur Branchenanalyse','a b c d',[
  'Mögliche Quellen sind geprüfte Berichte, öffentliche Statistik, Verbandsdaten, Produkt- und Kundeninformationen sowie begründete eigene Schätzungen. Jede Quelle besitzt einen Umfang und eine Verzögerung. Ein Verband kann nur Mitglieder erfassen; eine Börsendatenbank nur notierte Firmen; eine Statistik Betriebsstätten; ein Konzernbericht konsolidierte externe Umsätze. Eine große Zahl wird durch ihre Größe nicht vollständig.',
  T(['Prüfung','Warum sie die Aussage verändert'],[['Definition und Einheit','Umsatz, Stückzahl, installierte Basis und Handelsvolumen sind verschiedene Größen.'],['Zeit und Informationsstand','Geschäftsjahr, Kalenderjahr und Bekanntmachungsdatum müssen passen.'],['Währung und Preise','Wechselkurse und Inflation können nominales Wachstum erklären.'],['Teilnehmerauswahl','Fehlende private Firmen, Insolvenzen oder Neueintritte verändern die Stichprobe.'],['Konsolidierung und Stufe','Interne Umsätze oder mehrere Stufen derselben Leistung können doppelt zählen.'],['Unsicherheit','Eine geschätzte Marktgröße kann einen Bereich statt eines exakten Werts rechtfertigen.']],'Ein konsistentes Datenblatt erleichtert spätere Aktualisierungen.'),
  X('Marktgröße als Bereich statt Scheingenauigkeit','Passender Firmenumsatz 200 ist gut dokumentiert. Der externe Wartungsmarkt wird wegen fehlender kleiner Anbieter auf 900 bis 1.100 geschätzt.',[
   F('s_{low}=200/1100\\approx18{,}1818\\%,\\quad s_{high}=200/900\\approx22{,}2222\\%','Größerer Markt ergibt bei gleichem Firmenumsatz den kleineren Anteil.',[['s_{low},s_{high}','Unterer und oberer begründeter Anteilswert.']]),
   'Ein einzelner behaupteter Zwanzigprozentanteil verschweigt diese Unsicherheit. Die weiteren Schlussfolgerungen werden darauf geprüft, ob sie auch innerhalb des begründeten Bereichs tragen.'
  ],'Ein nachvollziehbares Intervall kann informativer sein als eine ungesicherte Nachkommastelle.')
 ]),
 S('size','8. Marktgröße aus Umsatz oder Mengen ableiten','a c',[
  F('M_t=\\sum_i S_{i,t},\\qquad M_t=Q_t\\bar p_t','Die erste Gleichung addiert vollständig und überschneidungsfrei erfasste Anbieterumsätze desselben Markts. Die zweite misst denselben Markt über Menge und passend definierten Durchschnittspreis.',[['M_t','Marktumsatz des gewählten Zeitraums.'],['i','Anbieterindex.'],['S_{i,t}','Passender externer Marktumsatz des Anbieters.'],['Q_t','Gesamte verkaufte Menge, hier vergleichbare Jahresverträge.'],['\\bar p_t','Mengenbezogener durchschnittlicher realisierter Preis.'],['t,\\sum','Periodenindex und Summe über die erfassten Anbieter.']]),
  X('Nordmarkt von zwei Seiten vermessen','Fünf Anbieter besitzen passende Umsätze 200, 300, 250, 150 und 100 Mio. €. Unabhängig werden 20.000 gleich abgegrenzte Jahresverträge mit Durchschnittspreis 50.000 € erfasst.',[
   F('M_0=200+300+250+150+100=1000\\text{ Mio. EUR}','Die vollständigen Anbieterumsätze bilden dieselbe externe Wartungsfrage.',[['M_0','Ausgangsmarktumsatz in Millionen Euro.']]),
   F('M_0=20000\\cdot50000=1000000000\\text{ EUR}','Die Vertragsrechnung ergibt denselben Betrag mit anderer Einheitendarstellung.',[['M_0','Derselbe Marktumsatz, nun in Euro.']]),
   'Die Übereinstimmung unterstützt die Abgrenzung, sofern Vertragszählung und Durchschnittspreis tatsächlich unabhängig erhoben wurden. Zwei Quellen, die dieselbe ursprüngliche Schätzung übernehmen, schaffen keine unabhängige Bestätigung.'
  ],'Marktgröße ist eine wirtschaftlich abgegrenzte Stromgröße, nicht automatisch die gesamte installierte Anlagenbasis.'),
  X('Doppelzählung über die Wertschöpfungskette vermeiden','Ein getrenntes Gerätebeispiel: Der Hersteller verkauft ein Gerät für achtzig an den Händler; der Händler verkauft dasselbe Gerät für hundert an den Endkunden.',[
   'Der Endkunden-Gerätemarkt dieses Vorgangs beträgt hundert, nicht hundertachtzig. Die Summe beider Umsätze misst mehrere Wertschöpfungsstufen. Ein anderes bewusst definiertes Branchenaggregat kann andere Größen erfassen, muss dann aber entsprechend benannt werden.'
  ],'Umsätze werden nicht addiert, bevor die Wertschöpfungsstufe feststeht.')
 ]),
 S('potential','9. Heutiger Markt und erreichbarer Markt sind verschieden','a c',[
  'Total Addressable Market beschreibt ein begründetes Gesamtpotenzial unter einer bestimmten Bedarfs- und Angebotsdefinition. Serviceable Available Market grenzt den Teil ein, den das Angebot unter geografischen, technischen oder rechtlichen Voraussetzungen bedienen könnte. Serviceable Obtainable Market beschreibt einen plausibel tatsächlich erreichbaren Teil innerhalb eines genannten Zeithorizonts. Diese ergänzenden Planungsbegriffe besitzen ohne explizite Definition keinen einheitlichen, automatisch gemessenen Inhalt.',
  X('Potenzial braucht Zugang und Ausführung','Im eigenen Planungsfall könnten 40.000 Anlagen grundsätzlich extern betreut werden. Je Anlage wären vergleichbare Jahreserlöse 50.000 €. Das eigene Angebot passt aber nur zu 24.000 Anlagen; innerhalb von drei Jahren kann die Kapazität höchstens 4.000 Anlagen bedienen.',[
   F('TAM=40000\\cdot50000=2000\\text{ Mio. EUR},\\quad SAM=24000\\cdot50000=1200\\text{ Mio. EUR}','Technische Erreichbarkeit reduziert das breite Potenzial.',[['TAM,SAM','Hier definierte jährliche Gesamt- und bedienbare Umsatzpotenziale.']]),
   F('S_{capacity}=4000\\cdot50000=200\\text{ Mio. EUR}','Zweihundert ist eine Kapazitätsgrenze unter den genannten Preisen, keine garantierte Kundengewinnung.',[['S_{capacity}','Kapazitätsbedingt höchstens bedienbarer Jahresumsatz.']]),
   'Die heutige externe Vertragsbasis kann gleichzeitig zwanzigtausend Anlagen umfassen. Potenziell auslagerbare Eigenwartung ist noch kein tatsächlich verkaufter externer Vertrag. Konkurrenz, Abschlussquoten, Personalaufbau und Zahlungsbereitschaft begrenzen den erreichbaren Teil zusätzlich.'
  ],'Ein großer TAM darf nicht unmittelbar in Umsatz, Marktanteil oder Aktienwert umgesetzt werden.')
 ]),
 S('growth','10. Nominales, reales und organisches Marktwachstum','a c',[
  F('g_M=\\frac{M_1}{M_0}-1,\\qquad CAGR=\\left(\\frac{M_n}{M_0}\\right)^{1/n}-1','Einperiodiges Wachstum und geometrisch geglättetes Mehrperiodenwachstum beantworten verschiedene Fragen. CAGR beschreibt den gleichen Endpunkt, nicht die tatsächliche Schwankung jedes Zwischenjahres.',[['g_M','Einperiodiges Marktumsatzwachstum.'],['M_0,M_1,M_n','Marktgröße am Anfang, nach einer und nach n Perioden.'],['CAGR','Compound Annual Growth Rate.'],['n','Zahl der jährlichen Wachstumsperioden größer null.']]),
  F('1+g_{nom}=(1+g_Q)(1+g_p)','Bei homogener Mengen- und Preisbasis enthält nominales Umsatzwachstum beide Effekte und ihren Kreuzterm. Bei mehreren Produkten kommen Mischungsänderungen hinzu.',[['g_{nom}','Nominales Marktumsatzwachstum.'],['g_Q','Mengenwachstum.'],['g_p','Änderung des passenden Durchschnittspreises.']]),
  X('Steigende Erlöse sagen noch nichts Eindeutiges über die Menge','Menge steigt vier Prozent und Preise sechs Prozent. Im getrennten Mehrjahresbeispiel wächst der Markt von tausend auf 1.331 in drei Jahren.',[
   F('g_{nom}=1{,}04\\cdot1{,}06-1=10{,}24\\%,\\quad CAGR=(1331/1000)^{1/3}-1=10\\%','Der erste Fall trennt Ursachen; der zweite glättet den Zeitverlauf.',[['g_{nom}','Nominales Wachstum im Preis-Mengen-Fall.'],['CAGR','Geometrisches Jahreswachstum im getrennten Dreijahresfall.']]),
   'Ein allgemeiner Inflationsindex ist nicht immer der richtige Branchenpreisindex. Technische Qualität, Vertragsumfang und Produktmix können den Durchschnittspreis ändern. Mengenwachstum und reales wertmäßiges Wachstum sind deshalb nur unter passenden Preis- und Qualitätsannahmen gleichzusetzen.'
  ],'Wachstumsbasis, Währung und Preisbereinigung werden ausdrücklich angegeben.'),
  'Organisches Wachstum schließt für die jeweilige Definition Übernahmen und andere Umfangsänderungen aus; Constant Currency isoliert Wechselkurseffekte. Eine Übernahme verschiebt Marktanteile zwischen Eigentümern, erzeugt aber bei unveränderter Nachfrage nicht denselben zusätzlichen Gesamtmarktumsatz. Prognosen aus unterschiedlichen Definitionen werden vor dem Vergleich angeglichen.'
 ]),
 S('shares','11. Marktanteilsänderungen und Firmenwachstum exakt verbinden','a c',[
  'Wertmäßiger Marktanteil misst Umsatz, mengenmäßiger Marktanteil vergleichbare verkaufte Einheiten. Eine Firma mit Preisprämie kann einen höheren Umsatz- als Mengenanteil besitzen. Ein Preisnachlass kann umgekehrt Menge gewinnen, ohne den Umsatzanteil entsprechend zu erhöhen. Unterschiedliche Qualität und Produktmix begrenzen den Vergleich einer einfachen Stückzählung.',
  F('s_i^{V}=\\frac{Q_ip_i}{Q\\bar p}=s_i^{Q}\\frac{p_i}{\\bar p},\\quad s_i^{Q}=Q_i/Q','Der Umsatzanteil besteht aus dem Mengenanteil mal relativem realisiertem Preis. Die Gleichung verlangt vergleichbare Mengen und einen dazu passend mengengewichteten Durchschnittspreis.',[['s_i^{V},s_i^{Q}','Wertmäßiger und mengenmäßiger Anteil der Firma i.'],['Q_i,Q','Passende Firmen- und Gesamtmarktmenge.'],['p_i,\\bar p','Realisierter Firmenpreis und Durchschnittspreis des gesamten Markts.'],['i','Firmenindex.']]),
  X('Eine Preisprämie verändert den Umsatzanteil','Ein getrennter homogener Lehrmarkt verkauft tausend vergleichbare Einheiten zum Gesamtdurchschnitt hundert Euro. Eine Firma verkauft hundert davon zu hundertzwanzig Euro; ihre höheren Preise sind in diesem Gesamtdurchschnitt bereits enthalten.',[
   F('s^{Q}=100/1000=10\\%,\\quad s^{V}=(100\\cdot120)/(1000\\cdot100)=12\\%','Zwölf Prozent Umsatzanteil und zehn Prozent Mengenanteil sind gleichzeitig korrekt.',[['s^{Q},s^{V}','Mengen- und Umsatzanteil derselben Firma.']]),
   'Das Ergebnis erklärt eine Preisprämie, beweist aber weder deren Nachhaltigkeit noch hohe Rendite. Zusätzliche Qualität kann erhebliche Kosten und Kapital benötigen.'
  ],'Anteilsbasis und Preise werden genannt, bevor ein Wettbewerbsgewinn behauptet wird.'),
  F('s_{i,t}=\\frac{S_{i,t}}{M_t},\\qquad1+g_{S,i}=(1+g_M)\\frac{s_{i,1}}{s_{i,0}}','Bei unveränderten Definitionen ist Firmenumsatz Marktgröße mal Marktanteil. Markt- und Anteilswachstum wirken multiplikativ.',[['s_{i,t}','Wertmäßiger Marktanteil des Unternehmens i in Periode t.'],['S_{i,t},M_t','Passender Firmen- und gesamter Marktumsatz.'],['g_{S,i},g_M','Einperiodiges Firmen- und Marktwachstum.'],['i,t','Unternehmens- und Periodenindex.']]),
  T(['Anbieter','Umsatz Jahr 0','Anteil Jahr 0','Umsatz Jahr 1','Anteil Jahr 1'],[['A: ThermaFlex','200','20 %','242','22 %'],['B','300','30 %','308','28 %'],['C','250','25 %','264','24 %'],['D','150','15 %','154','14 %'],['E','100','10 %','132','12 %'],['Gesamt','1.000','100 %','1.100','100 %']],'Nordmarkt, Mio. €; dieselbe Abgrenzung und vollständig erfasste Anbieter in beiden Jahren.'),
  X('A wächst nicht nur mit dem Markt','Der Markt wächst zehn Prozent. A erhöht seinen Anteil von zwanzig auf zweiundzwanzig Prozent.',[
   F('\\Delta s_A=22\\%-20\\%=2\\text{ Prozentpunkte},\\quad g_{s,A}=22/20-1=10\\%','Zwei Prozentpunkte absolut entsprechen zehn Prozent relativem Anteilswachstum.',[['\\Delta s_A','Absolute Änderung des Anteils.'],['g_{s,A}','Relative Veränderung gegenüber dem alten Anteil.']]),
   F('g_{S,A}=1{,}10\\cdot1{,}10-1=21\\%,\\quad S_{A,1}=200\\cdot1{,}21=242','Die Marktgröße und der Anteil steigen beide um zehn Prozent relativ.',[['g_{S,A}','Umsatzwachstum von A.'],['S_{A,1}','Neuer passender Firmenumsatz in Millionen.']]),
   'B besitzt dagegen Umsatzwachstum von etwa 2,6667 Prozent und verliert zwei Anteilspunkte, obwohl sein Umsatz steigt. Ein absolut wachsendes Geschäft kann gegenüber einem noch schneller wachsenden Markt zurückfallen.'
  ],'Prozent, Prozentpunkte und verschiedene Nenner werden nicht vertauscht.'),
  F('\\ln\\frac{S_{i,1}}{S_{i,0}}=\\ln\\frac{M_1}{M_0}+\\ln\\frac{s_{i,1}}{s_{i,0}}','Bei positiven Größen zerlegt der Logarithmus den Wachstumsfaktor exakt additiv. Bloße Addition gewöhnlicher Prozentänderungen wäre dagegen nur eine Näherung.',[['S_{i,1},S_{i,0}','Passender aktueller und vorheriger Firmenumsatz.'],['M_1,M_0','Passende Marktgrößen.'],['s_{i,1},s_{i,0}','Positive Marktanteile.'],['\\ln','Natürlicher Logarithmus.']])
 ]),
 S('share-limits','12. Gewonnene Anteile können nicht unbegrenzt extrapoliert werden','a c d',[
  F('s_t=s_0\\left(\\frac{1+g_S}{1+g_M}\\right)^t','Konstant schnelleres Firmenwachstum als Marktwachstum verlangt ständig steigenden Anteil. Bei unveränderter enger Marktdefinition liegt ein tatsächlicher Anteil zwischen null und eins.',[['s_t,s_0','Impliziter zukünftiger und heutiger Anteil als Dezimalzahl.'],['g_S,g_M','Konstant unterstellte Firmen- und Marktumsatzwachstumsraten.'],['t','Zahl der Jahre nach der Ausgangsbasis.']]),
  F('t^*=\\frac{\\ln(1/s_0)}{\\ln((1+g_S)/(1+g_M))}','Bei Firmenwachstum oberhalb des Marktwachstums ist dies der rechnerische Zeitpunkt, an dem der Anteil eins erreicht. Jenseits davon ist dieselbe Fortschreibung innerhalb desselben Markts unmöglich.',[['t^*','Rechnerische Grenzzeit; kein beobachteter Eintrittszeitpunkt.'],['s_0','Positiver Ausgangsanteil unter eins.'],['g_S,g_M','Wachstumsraten mit g_S größer g_M.'],['\\ln','Natürlicher Logarithmus.']]),
  'Der Grenzausdruck setzt einen Anfangsanteil strikt zwischen null und eins und positive Umsatzwachstumsfaktoren voraus. Bei gleichem Firmen- und Marktwachstum bleibt der Anteil konstant und es gibt keine solche endliche Grenzzeit. Bei langsamerem Firmenwachstum sinkt der Anteil. Die kontinuierlich berechnete Grenze und ein erstmals darüberliegendes ganzes Prognosejahr sind unterschiedliche Zeitangaben.',
  G({id:'share-extrapolation',title:'Dauerhaftes Überwachstum verlangt einen irgendwann unmöglichen Anteil',caption:'Eigene Fortschreibung: Anfangsanteil 20 %, Firmenwachstum 21 %, Markt 10 % pro Jahr. Die Kurve zeigt die algebraisch implizite, nach Überschreiten von 100 % unzulässige Fortschreibung; sie ist keine reale Prognose.',reading:'Der Anteil würde nach etwa 16,89 Jahren hundert Prozent erreichen. Wachstumsvorsprung muss auslaufen oder der Markt beziehungsweise das Geschäft muss ausdrücklich anders abgegrenzt werden. Eine neue Grenze darf keine verdeckte Reparatur des alten Nennerfehlers sein.',plot:{x:[0,18],y:[0,120],xTicks:[0,3,6,9,12,15,18],yTicks:[0,20,40,60,80,100,120],xLabel:'Jahre der unveränderten Fortschreibung',yLabel:'Rechnerisch impliziter Anteil, Prozent',series:[{name:'20 % × 1,1ᵗ',points:Array.from({length:73},(_,i)=>[i/4,20*1.1**(i/4)])},{name:'Obergrenze desselben Markts',dash:true,points:[[0,100],[18,100]]}]}}),
  'Ein Unternehmen kann in neue Regionen oder Angebote expandieren. Dann werden neue relevante Märkte, Kosten, Konkurrenz und Ressourcen mitmodelliert. Ein jüngster Anteilsgewinn ist kein Beweis dauerhafter Überlegenheit; er kann auch Übernahme, Preisnachlass, einmaligen Großauftrag oder veränderte Erfassung abbilden.'
 ]),
 S('cycle','13. Zyklus, installierte Basis und Ersatzbedarf','a c d',[
  F('Q_{service}=B_{installed}\\,r_{external}\\,f_{service}','Ein einfaches mengenbasiertes Servicemodell verbindet vorhandene Anlagen, extern vergebenen Anteil und Servicehäufigkeit. Neuverkäufe und Servicebedarf sind unterschiedliche Ströme.',[['Q_{service}','Zahl vergleichbarer externer Leistungen pro Jahr.'],['B_{installed}','Anzahl funktionsfähiger relevanter Anlagen.'],['r_{external}','Anteil extern betreuter Anlagen zwischen null und eins.'],['f_{service}','Passende Leistungen je betreuter Anlage und Jahr.']]),
  X('Neugeräte schwächeln, Wartung bleibt nicht völlig unverändert','Vierzigtausend Anlagen sind vorhanden, die Hälfte wird extern einmal jährlich betreut. Geräte-Neuverkäufe fallen deutlich, die vorhandene Basis bleibt zunächst gleich.',[
   F('Q_{service}=40000\\cdot0{,}5\\cdot1=20000','Der unveränderte reine Basiseffekt liefert weiterhin zwanzigtausend Leistungen.',[['Q_{service}','Jährliche externe Serviceleistungen.']]),
   'Kunden können gleichzeitig Anlagen stilllegen, Wartung verschieben, selbst übernehmen oder Preise neu verhandeln. Der installierte Bestand erklärt eine stabilere Grundlage, garantiert aber keine feste Menge oder Marge. Gealterte Anlagen können zudem kurzfristig mehr Reparaturen benötigen.'
  ],'Ein Branchenmodell unterscheidet zyklische Neuanschaffung, laufenden Verbrauch und Ersatz.'),
  'Verglichen werden möglichst mehrere Phasen statt allein ein aktuelles Hoch. Auslastung, Aufträge, Lager, Kundenbudget und Finanzierung können unterschiedliche Vorläufe besitzen. Eine branchenweite Gewinnerholung aus niedriger Ausgangsbasis ist nicht automatisch eine neue dauerhafte Ertragsqualität. Korrelation mit dem Konjunkturzyklus zeigt eine Beziehung, beweist aber noch keine Ursache.'
 ]),
 S('lifecycle','14. Lebenszyklus und Technologiewandel als Hypothese','a c d',[
  'Ein Branchenlebenszyklus kann Entstehung, Expansion, Bereinigung, Reife und Rückgang unterscheiden. Das ist ein Orientierungsmuster, kein Naturgesetz. Technologie, neue Anwendungen, Länder und Teilsegmente können verschiedene Phasen besitzen. Das Alter eines einzelnen Unternehmens bestimmt nicht die Phase seines Markts.',
  F('Q(t)=\\frac{K}{1+e^{-a(t-t_0)}}','Ein eigenes logistisches Diffusionsmodell veranschaulicht anfänglich kleinen Absatz, spätere Beschleunigung und Annäherung an eine hier festgehaltene Sättigungsgrenze. Es erklärt allein keine konkrete Branchenkonkurrenz.',[['Q(t)','Modellierte Marktmenge als Funktion der Zeit.'],['K','Hier unverändertes langfristiges Mengenpotenzial.'],['a','Positiver Geschwindigkeitsparameter je Zeiteinheit.'],['t,t_0','Zeit und Modellzeitpunkt mit Menge K/2.'],['e','Basis der Exponentialfunktion.']]),
  G({id:'diffusion',title:'Ein mögliches Diffusionsmuster ist keine allgemeine Branchenprognose',caption:'Eigenes getrenntes Lehrmodell: a = 0,8 pro Jahr, Mittelpunkt t₀ = 6, gezeichnete Menge relativ zur festen Grenze K. Keine echten Nordmarkt-Verkäufe oder Wahrscheinlichkeiten.',reading:'Die absolute Mengenzunahme ist um den Mittelpunkt am größten, während das relative Wachstum schon vorher fallen kann. Reife bedeutet hier Nähe zur festen Modellgrenze; reale Märkte können durch neue Produkte oder Regionen andere Grenzen erhalten.',plot:{x:[0,12],y:[0,100],xTicks:[0,2,4,6,8,10,12],yTicks:[0,20,40,60,80,100],xLabel:'Modellzeit, Jahre',yLabel:'Menge relativ zu K, Prozent',series:[{name:'Logistische Modellmenge',points:Array.from({length:49},(_,i)=>[i/4,adoption(i/4)])}]}}),
  F('\\frac{1}{Q(t)}\\frac{dQ(t)}{dt}=a\\left(1-\\frac{Q(t)}{K}\\right)','Im kontinuierlichen Lehrmodell sinkt das relative Wachstum mit wachsender Durchdringung. Das unterscheidet relative Wachstumsrate von absolutem zusätzlichen Volumen.',[['Q(t),K,a','Modellmenge, feste Grenze und Geschwindigkeit.'],['dQ(t)/dt','Momentane absolute Mengenänderung je Zeiteinheit.'],['t','Kontinuierliche Modellzeit, nicht ein tatsächlich beobachtetes Geschäftsjahr.']]),
  'Eine Reifehypothese verlangt Evidenz: Durchdringung, Ersatzanteil, Preisverhalten, Kapazität und neue Verwendungen. Ein niedriges einzelnes Wachstumsjahr kann ebenso Rezession, Lieferengpass oder Messänderung sein. Ein Lebenszykluslabel ersetzt diese Analyse nicht.'
 ]),
 S('profitability','15. Branchenprofitabilität richtig aggregieren','a c d',[
  F('m_{industry}=\\frac{\\sum_i EBIT_i}{\\sum_i S_i}=\\sum_i\\frac{S_i}{\\sum_jS_j}m_i','Die aggregierte EBIT-Marge ist bei vollständiger vergleichbarer Basis ein umsatzgewichteter Mittelwert. Der einfache Firmenmittelwert beantwortet eine andere Frage.',[['m_{industry}','EBIT-Marge des erfassten Branchenaggregats.'],['EBIT_i,S_i,m_i','Passender EBIT, Umsatz und EBIT-Marge der Firma i.'],['i,j,\\sum','Firmenindizes und Summation über dasselbe Universum.']]),
  T(['Anbieter','Umsatz Jahr 0','EBIT-Marge Jahr 0','EBIT Jahr 0','Umsatz Jahr 1','EBIT-Marge Jahr 1','EBIT Jahr 1'],[['A','200','10 %','20','242','12 %','29,04'],['B','300','6 %','18','308','6 %','18,48'],['C','250','8 %','20','264','8 %','21,12'],['D','150','4 %','6','154','4 %','6,16'],['E','100','−2 %','−2','132','−2 %','−2,64']],'Nordmarkt, Mio. €; alle EBIT-Größen auf derselben vergleichbaren operativen Basis.'),
  X('Der Durchschnitt hängt von der gestellten Frage ab','Nordmarkt besitzt im ersten Jahr insgesamt EBIT 62 bei Umsatz 1.000, im folgenden EBIT 72,16 bei Umsatz 1.100.',[
   F('m_{0}=62/1000=6{,}2\\%,\\quad m_{1}=72{,}16/1100=6{,}56\\%','Die Branchenmarge verbessert sich trotz unveränderter Margen der Anbieter B bis E.',[['m_0,m_1','Aggregierte Branchenmargen beider Jahre.']]),
   F('\\bar m_{0}=(10+6+8+4-2)/5=5{,}2\\%,\\quad \\bar m_{1}=(12+6+8+4-2)/5=5{,}6\\%','Die gleich gewichtete typische Firmenbeobachtung ist nicht die Marge des Gesamtumsatzes.',[['\\bar m_0,\\bar m_1','Arithmetische Firmenmittelwerte auf Prozentbasis.']]),
   'Wird der Verlustanbieter E im Ausgangsjahr entfernt, steigt die ausgewiesene aggregierte Marge auf 64/900 oder 7,1111 Prozent. Das ist eine andere selektive Gruppe. Ein Branchenurteil darf die Firmen mit schwierigen Ergebnissen nicht stillschweigend verlieren.'
  ],'Gewicht, Ertragsdefinition und Auswahl werden neben jeder Branchenkennzahl genannt.'),
  'EBITDA-Marge, EBIT-Marge, Nettomarge und Kapitalrendite messen andere Ebenen. Hohe Abschreibung oder Finanzierung können die Rangfolge verändern. Bilanzierungs- und Konsolidierungsunterschiede werden vor einem Peer-Vergleich überprüft. Ein guter Branchendurchschnitt schließt schwache einzelne Firmen nicht aus.'
 ]),
 S('capital','16. Marge ist noch keine ausreichende Kapitalrendite','a c d',[
  F('ROIC=\\frac{NOPAT}{IC_{begin}}=\\frac{NOPAT}{S}\\frac{S}{IC_{begin}}','Die Rendite auf das vereinbarte Anfangskapital zerfällt in operative Nachsteuermarge und Kapitalumschlag. Beide Seiten benötigen denselben Betrieb und dieselbe Periode.',[['ROIC','Operative Kapitalrendite auf Anfangskapital.'],['NOPAT','Passender operativer Nachsteuerertrag.'],['IC_{begin}','Zu diesem Betrieb gehörendes operatives Anfangskapital größer null.'],['S','Umsatz der betrachteten Folgeperiode.']]),
  X('Ähnliche Marge, anderer Kapitalbedarf','Zwei eigene Fälle erzielen Umsatz 242 und EBIT-Marge zwölf Prozent bei Steuer fünfundzwanzig Prozent. Fall A benötigt Anfangskapital 121, Fall B 193,6.',[
   F('NOPAT=242\\cdot0{,}12\\cdot0{,}75=21{,}78,\\quad ROIC_A=21{,}78/121=18\\%,\\quad ROIC_B=21{,}78/193{,}6=11{,}25\\%','Gleicher Gewinn benötigt im zweiten Betrieb mehr wirtschaftlich gebundenes Kapital.',[['NOPAT','Nachsteuerbetriebsertrag in Millionen.'],['ROIC_A,ROIC_B','Renditen auf das jeweilige Anfangskapital.']]),
   'Bei Kosten neun Prozent verdienen beide hier darüber, aber die Überrendite ist unterschiedlich groß. Würde im kapitalintensiven Fall die EBIT-Marge auf acht Prozent fallen, wäre seine Rendite nur 7,5 Prozent. Umsatzwachstum dieses Geschäfts kann dann trotz positiver Marge Wert belasten.'
  ],'Ein Margenvergleich ohne Anlagen- und Bestandsbedarf lässt einen wichtigen Werttreiber aus.'),
  'Aggregierter Branchen-ROIC wird aus entsprechend aggregiertem NOPAT und Kapital berechnet, nicht als beliebiger Umsatzmittelwert der ROIC-Zahlen. Buchkapital kann wirtschaftlichen Einsatz bei immateriellen Ressourcen oder alten Anlagen nur unvollständig darstellen. Die Definition bleibt neben dem Ergebnis sichtbar.'
 ]),
 S('concentration','17. Marktanteile messen Konzentration, nicht allein Marktmacht','a c d',[
  F('CR_k=\\sum_{i=1}^{k}s_{(i)},\\quad HHI=\\sum_i s_i^2','Die Konzentrationsrate erfasst die größten k Anbieter, der HHI die gesamte Anteilsverteilung mit besonderem Gewicht großer Anbieter. Die hier verwendeten Anteile sind Prozentzahlen.',[['CR_k','Konzentrationsrate der k größten Anbieter, Prozent.'],['s_{(i)}','Absteigend geordnete Prozentanteile.'],['s_i','Prozentanteil eines Anbieters auf derselben Marktgrenze.'],['HHI','Herfindahl-Hirschman-Index auf der Skala bis 10.000.'],['i,k,\\sum','Index, Zahl der größten betrachteten Anbieter und Summation.']]),
  X('Nordmarkt: Wachstum des Unternehmens und Konzentration sind verschieden','Anteile Jahr null: 20, 30, 25, 15, 10 Prozent. Jahr eins: 22, 28, 24, 14, 12 Prozent.',[
   F('HHI_0=20^2+30^2+25^2+15^2+10^2=2250,\\quad CR_{4,0}=90\\%','Die größten vier Anbieter erfassen neunzig Prozent.',[['HHI_0,CR_{4,0}','Ausgangskonzentration.']]),
   F('HHI_1=22^2+28^2+24^2+14^2+12^2=2184,\\quad CR_{4,1}=88\\%','A gewinnt Anteil, während die Gesamtverteilung etwas ausgeglichener wird.',[['HHI_1,CR_{4,1}','Konzentration des Folgejahres.']]),
   'Würde E tatsächlich viele kleine unabhängige Firmen statt einer Firma umfassen, wäre sein zusammengefasstes Quadrat zu hoch. Ein Restposten andere Anbieter darf nicht ohne Prüfung wie ein einzelnes Unternehmen behandelt werden.'
  ],'Marktdefinition, Eigentümerabgrenzung und Restgruppen beeinflussen die Kennzahl.'),
  F('HHI_{rest,true}=\\sum_{j=1}^{n}r_j^2\\le\\left(\\sum_{j=1}^{n}r_j\\right)^2','Zusammenfassen nicht negativer Einzelanteile in einen einzigen Restanbieter kann Konzentration überschätzen; bei mehreren positiven Anteilen ist die Ungleichung strikt.',[['HHI_{rest,true}','Tatsächlicher HHI-Beitrag der Restfirmen.'],['r_j','Nicht negativer Prozentanteil einer Restfirma.'],['n,j','Zahl und Index der Restfirmen.'],['\\sum','Summation der betrachteten Anteile.']]),
  'Hoher Anteil und wenige Anbieter garantieren keine dauerhaften hohen Margen. Käufermacht, Importzugang, Ersatzangebote und glaubwürdiger Eintritt können den Preis begrenzen. Rechtliche Konzentrationsschwellen sind kontextabhängig und werden hier nicht als universelle Aktienbewertungsregel verwendet.'
 ]),
 S('five-forces','18. Five Forces: Wer kann einen Teil des geschaffenen Werts beanspruchen?','a c d',[
  T(['Kraft','Kernfrage'],[['Rivalität vorhandener Anbieter','Wie stark wirken Konkurrenzentscheidungen auf Preis, Leistung und Aufwand?'],['Bedrohung durch Eintritt','Wie leicht kann zusätzliche glaubwürdige Konkurrenz entstehen?'],['Käufermacht','Welche Bedingungen können Abnehmer durchsetzen?'],['Lieferantenmacht','Welche Bedingungen können relevante Ressourcenanbieter durchsetzen?'],['Bedrohung durch Substitute','Welche andersartigen Lösungen erfüllen dasselbe Kundenbedürfnis?']],'Die fünf Kräfte analysieren Branchenstruktur; eine konkrete Firma kann ihr unterschiedlich ausgesetzt sein.'),
  'Im eigenen Wartungsfall wird nicht einfach jeder Kraft ein unbegründeter Punktwert zugeteilt. Es werden Belege gesucht: Ausschreibungen, Alternativangebote, Vertragsdauer, Teilezugang, Schulungsbedarf, Personalverfügbarkeit und Kundenreaktionen. Ein Urteil hoch oder niedrig folgt aus diesen Umständen und nennt Unsicherheit.',
  'Die Wirkung erscheint in verschiedenen Finanzzeilen. Preisnachlass reduziert Erlöse; zusätzliche Bereitschaft erhöht Fixkosten; knappe Teile erhöhen Kosten und Lager; längere Zahlungsziele erhöhen Forderungen. Die gleiche unveränderte EBIT-Marge trotz sämtlicher verschlechterter Bedingungen wäre eine erklärungsbedürftige Prognose.'
 ]),
 S('rivalry','19. Rivalität: Preis, Menge, Kapazität und Exit zusammen sehen','a c d',[
  F('EBIT=(P-c)Q-F','Ein eigener einfacher Leistungsfall trennt Preis und variable Kosten je Einheit vom verpflichteten Fixkostenblock. Preiswettbewerb kann den gesamten vorhandenen Absatz treffen, während zusätzlicher Absatz nur zusätzlichen Stückbeitrag liefert.',[['EBIT','Operativer Gewinn in Millionen Euro bei Q in Millionen Einheiten.'],['P,c','Preis und variable Kosten in Euro je Einheit.'],['Q','Millionen vergleichbarer Leistungseinheiten.'],['F','Fixe Jahreskosten in Millionen Euro.']]),
  X('Marktanteil durch Rabatt ist nicht automatisch mehr Gewinn','Eigener ThermaFlex-Kostenvergleich: zwei Millionen abrechenbare Teilaufgaben, Preis hundert, variable Kosten sechzig, fixe Kosten sechzig Millionen. Diese Teilaufgaben sind nicht die zuvor gezählten 50.000-Euro-Jahresverträge. Für den isolierten Vergleich bleiben Kosten und Qualität zunächst unverändert.',[
   F('EBIT_0=(100-60)\\cdot2-60=20,\\quad EBIT_{cut}=(95-60)\\cdot2-60=10','Fünf Prozent Preisnachlass halbieren bei gleicher Menge den operativen Gewinn.',[['EBIT_0,EBIT_{cut}','Gewinn vor und nach Rabatt, Millionen.']]),
   F('Q_{sameprofit}=\\frac{20+60}{95-60}\\approx2{,}285714','Für denselben Gewinn zwanzig wären rund 14,2857 Prozent mehr Einheiten nötig.',[['Q_{sameprofit}','Benötigte Millionen Einheiten bei unveränderten Kosten.']]),
   F('EBIT_{more}=(95-60)\\cdot2{,}4-60=24','Zwanzig Prozent mehr Menge würde im begrenzten Modell den Gewinn erhöhen; dafür müssen Nachfrage und Kapazität tatsächlich verfügbar sein.',[['EBIT_{more}','Gewinn beim ausdrücklich höheren Mengenfall.']])
  ],'Rabatt, gewonnene Menge, Konkurrentenreaktion und nötige Zusatzkosten gehören in dieselbe Entscheidung.'),
  G({id:'rivalry-profit',title:'Ein Preisnachlass erhöht die benötigte Menge für denselben Gewinn',caption:'Eigene feste Kostenstruktur: variable Kosten 60 € je Einheit, fixe Kosten 60 Mio. €. Preise 100 beziehungsweise 95 €. Mengen bis drei Millionen bei unterstellter verfügbarer Kapazität; keine Steuer oder Finanzierung.',reading:'Bei zwei Millionen Einheiten fällt EBIT von zwanzig auf zehn. Die niedrigere Preiskurve braucht für denselben Gewinn mehr Menge. Zusätzliche Fabrik, Techniker oder Servicequalität würden die dargestellte Kostenstruktur verändern.',plot:{x:[0,3],y:[-60,70],xTicks:[0,.5,1,1.5,2,2.5,3],yTicks:[-60,-40,-20,0,20,40,60],xLabel:'Verkaufte Einheiten, Millionen',yLabel:'EBIT, Millionen Euro',series:[{name:'Preis 100 €',points:Array.from({length:31},(_,i)=>[i/10,40*i/10-60])},{name:'Preis 95 €',dash:true,points:Array.from({length:31},(_,i)=>[i/10,35*i/10-60])}]}}),
  'Verpflichtete Kapazität und teurer Rückzug können Anbieter auch bei schwacher Nachfrage am Markt halten. Kurzfristige Kostendeckung ist von langfristiger Rendite auf das Kapital zu unterscheiden. Wenige Konkurrenten können ebenfalls heftig konkurrieren; Konzentration ersetzt keine Prüfung ihrer Anreize. Das VWL-Kapitel erläutert diese strategischen Wechselwirkungen vertieft.'
 ]),
 S('entry','20. Eintrittsbarrieren und Ressourcenbedarf wirtschaftlich prüfen','a d',[
  'Eintrittsbarrieren sind Bedingungen, die einen neuen glaubwürdigen Wettbewerber erschweren. Im eigenen Servicefall können zertifizierte Techniker, Ersatzteilzugang, verlässliche Bereitschaft und Kundenvertrauen Zeit und Ressourcen beanspruchen. Ein bereits erfahrener Anbieter aus einer Nachbarregion kann diese Bedingungen anders erfüllen als ein vollständig neuer Betrieb.',
  X('Hoher Kapitalbedarf allein beweist keine Schutzwirkung','Der Aufbau eines Servicegebiets erfordert im Lehrfall dreißig Millionen. Zwei denkbare Eintrittsfinanzierungen verdienen danach denselben operativen Nachsteuerertrag vier Millionen pro Jahr.',[
   F('ROIC_{new}=4/30\\approx13{,}3333\\%','Die Ertrag-Kapital-Relation ist zunächst eine rechnerische Attraktivitätsgröße.',[['ROIC_{new}','Vereinfachter Ertrag relativ zur neuen Investition.']]),
   'Bei passenden Kosten neun Prozent kann der Einsatz attraktiv sein, sofern Marktzugang und Ausführung erreichbar sind. Kapitalbedarf dreißig ist dann nicht automatisch ein unüberwindbarer Schutz. Bei Kosten fünfzehn Prozent wäre derselbe Ertrag unzureichend; die konkrete Finanzierung und Risikostruktur verändern das Urteil.'
  ],'Barriere, Investitionshöhe und wirtschaftliche Attraktivität sind verwandte, aber verschiedene Fragen.'),
  'Skaleneffekte betreffen langfristige Stückkosten bei anderer Betriebsgröße; hohe Auslastung einer vorhandenen Anlage ist ein anderer Mechanismus. Netzwerkeffekte betreffen den Nutzen durch andere Teilnehmer. Die Existenz vieler Nutzer oder großer Anlagen wird nicht automatisch als dauerhafte Eintrittssperre interpretiert.',
  'Eine Barriere kann veralten: offener Teilezugang, standardisierte Diagnostik oder schnell erlernbare Technik können Marktzugang erleichtern. Umgekehrt kann eine neue Qualifikationsanforderung ihn erschweren. Wirkung, Dauer und mögliche Umgehung werden neben der behaupteten Stärke erklärt.'
 ]),
 S('buyers','21. Käufermacht kann Preis und Kapitalbindung gleichzeitig verändern','a c d',[
  'Im eigenen Servicefall besitzt ein Großkunde mehrere vergleichbare Angebote und kann Aufträge bündeln. Macht zeigt sich nicht nur im Preis: zusätzliche Verfügbarkeit, Garantien, Rabattbedingungen, längere Zahlungsziele und verlangte Zusatzleistungen können den verfügbaren Ertrag senken. Die Existenz eines großen Kunden allein beweist jedoch keine Macht, wenn seine Alternativen unzureichend oder der Wechsel teuer sind.',
  X('Gleicher Umsatz und Gewinn, späterer Zahlungseingang','Ein Kunde mit Jahresumsatz hundert Millionen zahlt bisher im gleichmäßig vereinfachten Modell nach dreißig Tagen, künftig nach sechzig. Keine Ausfälle und keine Änderung des Umsatzes oder Ergebnisses.',[
   F('\\Delta AR=100\\cdot(60-30)/365\\approx8{,}219178','Die verlängerten Bedingungen binden rund 8,22 Millionen zusätzliche Forderungen.',[['\\Delta AR','Zusätzliche operative Mittelbindung in Millionen.']]),
   'Diese Bindung reduziert bei sonst unverändertem Verlauf die freie Zahlung im Übergangsjahr. Sie ist nicht jedes Jahr erneut eine Änderung derselben Höhe. Der neue höhere Bestand bleibt aber wirtschaftlich zu finanzieren.'
  ],'Unveränderte Marge bedeutet nicht unveränderten Eigentümercashflow.'),
  'Eine überprüfbare Käufermachtsthese benennt Umsatzkonzentration, Alternativen, Ausschreibungsdisziplin, kundenspezifische Anlagen, Wechselaufwand und mögliche Eigenleistung. Im Branchenurteil wird zwischen verschiedenen Kundensegmenten unterschieden; eine zentral beschaffende Großfirma und ein kleiner Betrieb können andere Bedingungen durchsetzen.'
 ]),
 S('suppliers','22. Lieferantenmacht und Kostenweitergabe getrennt verfolgen','a c d',[
  F('\\Delta EBIT=(\\Delta P-\\Delta c)Q\\quad\\text{bei festem }Q,F','Unter konstantem Absatz und festen übrigen Kosten zeigt die Differenz aus Preis- und variabler Kostenänderung die unmittelbare Gewinnwirkung. Die konstante Menge ist eine Annahme, keine Folge erfolgreicher Weitergabe.',[['\\Delta EBIT','Operative Gewinnänderung.'],['\\Delta P,\\Delta c','Preis- und variable Kostenänderung je Einheit.'],['Q,F','Absatzmenge und fixer Kostenblock.']]),
  X('Teurere Teile: gleiche Marge, gleicher Gewinn und gleiche Menge sind nicht dasselbe','Ausgangsfall Preis hundert, variable Kosten sechzig, zwei Millionen Einheiten und Fixkosten sechzig Millionen. Teilekosten erhöhen den variablen Betrag auf vierundsechzig.',[
   T(['Reaktion','Preis','Menge, Mio.','EBIT, Mio. €','EBIT-Marge'],[['Keine Weitergabe','100','2','12','6 %'],['Hälftige Stückkostenweitergabe','102','2','16','7,8431 %'],['Volle Stückkostenweitergabe','104','2','20','9,6154 %'],['Volle Weitergabe, Menge −5 %','104','1,9','16','8,0972 %']],'Eigene isolierte und gemeinsame Vergleichsfälle; das letzte Szenario nimmt ausdrücklich eine Mengenreaktion an.'),
   F('EBIT_{full}= (104-64)\\cdot2-60=20,\\quad m_{full}=20/208\\approx9{,}6154\\%','Volle Weitergabe des zusätzlichen Stückbetrags erhält bei gleicher Menge den absoluten Gewinn, nicht die frühere Zehnprozentmarge.',[['EBIT_{full},m_{full}','Gewinn und Marge beim unveränderten Mengenfall mit vollständiger Stückkostenweitergabe.']]),
   F('EBIT_{volume}=(104-64)\\cdot1{,}9-60=16','Mengenrückgang senkt trotz vollständiger Stückweitergabe den Gewinn.',[['EBIT_{volume}','Gewinn unter der ausdrücklich gesunkenen Menge.']])
  ],'Eine Kostenweitergabethese benötigt zugleich Nachfrage-, Wettbewerbs- und Vertragsannahmen.'),
  'Abhängigkeit wird an Ersetzbarkeit, Qualifikation, Lieferzeit, Kapazität und Kosten eines Wechsels geprüft. Mehr Lager kann Lieferunsicherheit begrenzen, bindet aber Kapital und schafft Bestandsrisiken. Vertikale Integration kann Abhängigkeit verändern, bringt zugleich eigene Kosten, Ressourcen und neue Risiken.'
 ]),
 S('substitutes','23. Substitute erfüllen dasselbe Bedürfnis auf anderem Weg','a d',[
  'Ein direkter Wettbewerber bietet im betrachteten Markt ein vergleichbares Produkt an. Ein Substitut löst dasselbe grundlegende Kundenproblem auf eine andere Weise. Im Wartungsfall können andere Serviceanbieter direkt konkurrieren; interne Wartung, veränderte Anlagenkonzepte oder andere Prozesswärmetechnik können die Nachfrage nach dem externen Service ersetzen. Welche Alternative plausibel ist, hängt vom konkreten Bedarf ab.',
  X('Der Preisvergleich allein unterschätzt den Wechselaufwand','Ein Kunde zahlt jährlich hunderttausend für externen Service. Eigenleistung würde pro Jahr fünfundsiebzigtausend kosten, benötigt aber heutige Schulung und Ausstattung achtzigtausend. Vier Jahresendperioden, Kosten acht Prozent, keine weiteren Unterschiede oder Restwerte.',[
   F('NPV_{switch}=\\sum_{t=1}^{4}\\frac{25000}{1{,}08^t}-80000\\approx2803{,}1710','Die jährlichen Einsparungen haben heute nur knapp mehr Wert als der anfängliche Wechselaufwand.',[['NPV_{switch}','Netto-Barwert des vereinfachten Wechsels in Euro.'],['t,\\sum','Jahresindex und Summation über vier Zahlungen.']]),
   'Ausfallrisiko, Qualität, Personalengpass oder längere Nutzung könnten das Ergebnis stark verändern. Der jährliche Preisunterschied fünfundzwanzigtausend allein beweist daher noch keine starke oder schwache Substitutionsbedrohung.'
  ],'Alternativen werden nach Leistung, Gesamtaufwand, Risiko und Zeithorizont verglichen.'),
  'Technischer Fortschritt kann die Qualität des Ersatzangebots verbessern oder Wechselkosten reduzieren. Eine enge aktuelle Produktklassifikation darf solche Entwicklungen nicht aus der Analyse ausschließen. Ein Substitut kann die Zahlungsbereitschaft begrenzen, selbst wenn kein Kunde im beobachteten Jahr bereits gewechselt hat.'
 ]),
 S('interactions','24. Die Kräfte wirken gemeinsam und unterschiedlich auf Firmen','a c d',[
  'Die Five Forces werden nicht zu einer vermeintlich objektiven Durchschnittsnote addiert. Eine kleine Kostenänderung eines unbedeutenden Inputs kann weniger wirken als die Forderung eines entscheidenden Käufers. Neue Konkurrenz kann einen Lieferanten unabhängiger machen und zugleich Kunden neue Alternativen bieten. Entscheidend sind wirtschaftliche Größenordnung und gemeinsamer Mechanismus.',
  T(['Eigene Beobachtung im Servicefall','Mögliche wirtschaftliche Wirkung','Gegenhypothese oder Prüfung'],[['Offener Diagnosestandard','Neue Anbieter können schneller qualifiziert werden.','Kunden verlangen trotzdem dokumentierte Bereitschaft und Qualität.'],['Kunde bündelt mehrere Standorte','Stärkerer Preis- und Zahlungszieldruck.','Anbieter mit dichtem Netz kann günstiger zuverlässig liefern.'],['Knappe zertifizierte Techniker','Höhere Personalkosten und geringere Wachstumsfähigkeit.','Bessere Planung oder Ausbildung kann Engpass begrenzen.'],['Fernüberwachung wird verbessert','Weniger Vor-Ort-Einsätze und andere Preislogik.','Diagnostik kann zugleich neue betreute Anlagen erschließen.']],'Eine Entwicklung kann Nachfrage, Kosten und Wettbewerbsposition gleichzeitig ändern.'),
  'Branchenstruktur erklärt allgemeine Beschränkungen; relative Firmenposition erklärt die unterschiedliche Betroffenheit. Strategie ist erst dann überzeugend, wenn sie die benannte Kraft beeinflusst und die Firma die Ressourcen zur Umsetzung besitzt. Ein attraktiver Name oder das Wort Innovation reicht dafür nicht.',
  'Ergänzende Wirkungen von Komplementen, Plattformen und Regulierung werden wirtschaftlich eingeordnet. Five Forces besitzt genau die beschriebenen fünf Kategorien; zusätzliche Gesichtspunkte können sie beeinflussen, werden aber nicht stillschweigend als neue ursprüngliche Kraft ausgegeben.'
 ]),
 S('pestle','25. PESTLE erfasst das Umfeld und verlangt konkrete Wirkungsketten','a c d',[
  T(['Dimension','Eigene Frage für Nordmarkt','Mögliche Prognosefolge'],[['Political','Wie verändern politische Ziele oder Förderprioritäten Anlagenentscheidungen?','Zeitplan von Neuinstallationen und künftigem Servicebedarf.'],['Economic','Wie verändern Investitionszyklus, Zinsen und Finanzierung die Kundenbudgets?','Menge, Ersatzaufschub und Ausfall-/Zahlungsrisiko.'],['Social','Wie entwickeln sich Qualifikation, Arbeitsangebot und Akzeptanz von Automatisierung?','Technikerverfügbarkeit, Kosten und Nachfrage nach Eigenleistung.'],['Technological','Welche Diagnostik oder Prozesswärmetechnik verändert benötigte Leistungen?','Substitution, neue Angebote und Entwicklungsinvestition.'],['Legal','Welche tatsächlich anwendbaren Anforderungen betreffen Zugang, Verträge oder Sicherheit?','Qualifikation, Dokumentation, Compliancekosten und Marktzugang.'],['Environmental','Welche physischen Belastungen und Ressourcenbedingungen verändern Betrieb und Nachfrage?','Störungen, Ersatz, Effizienzbedarf und Investitionen.']],'PESTLE: politische, wirtschaftliche, soziale, technologische, rechtliche und ökologische Einflüsse. Eigene hypothetische Fragen, keine Aussage über aktuell geltende konkrete Regeln.'),
  'Die Analyse priorisiert nach Belegen, Wirkung, Zeitpunkt und Unsicherheit. Eine allgemeine Aussage wie Technik verändert alles wird erst nutzbar, wenn der betroffene Prozess, Kunde oder Preis benannt ist. Politische Ankündigung, beschlossenes Vorhaben, Umsetzung und tatsächliche Kundenreaktion sind verschiedene Informationsstände.',
  'Die Kategorien können sich überschneiden. Eine Klimapolitik kann politische, rechtliche, technologische und ökologische Kanäle besitzen. Dieselbe wirtschaftliche Folge wird dadurch nicht mehrfach in den Cashflow eingerechnet. PESTLE ergänzt die Wettbewerbsanalyse: Es zeigt mögliche Ursachen einer Veränderung, Five Forces verfolgt ihre Wirkung auf Konkurrenz und Wertverteilung.'
 ]),
 S('channels','26. Vom Umfeld zur Finanzzeile: Zeit, Unsicherheit und Szenario','a c d',[
  T(['Schritt der Wirkungskette','Prüfbare Frage'],[['Umfeldsignal','Welche äußere Entwicklung ist belegt?'],['Wirtschaftlicher Mechanismus','Wie verändert sie Kundenverhalten, Kosten, Zugang oder Ressourcen?'],['Prognosetreiber','Welche Menge, welcher Preis, Kosten- oder Kapitalbestand ändert sich wann?'],['Zahlungsfolge','Welche freie Zahlung folgt nach Steuern und benötigten Investitionen?']],'Jeder Übergang braucht Evidenz und Annahmen. Die Wirkungskette ist eine Erklärung, keine automatisch geltende Gleichung.'),
  X('Fernüberwachung kann zugleich Wachstum und Preisdruck verursachen','Ein eigener Anbieter betreut bisher zweitausend Anlagen zu fünfzigtausend Jahrespreis. Neue Fernüberwachung erlaubt zweitausendvierhundert betreute Anlagen, reduziert aber den realisierten Preis auf fünfundvierzigtausend.',[
   F('S_0=2000\\cdot50000=100\\text{ Mio. EUR},\\quad S_1=2400\\cdot45000=108\\text{ Mio. EUR}','Zwanzig Prozent mehr betreute Anlagen ergeben wegen zehn Prozent niedrigerem Preis nur acht Prozent mehr Umsatz.',[['S_0,S_1','Alter und neuer Jahresumsatz.']]),
   'Der Wert kann trotzdem steigen, wenn Technikeraufwand oder Kapitalbedarf stärker sinken. Er kann fallen, wenn hohe neue Entwicklung, schwache Gebühren oder neue Konkurrenz die Einsparung aufzehren. Technologie ist deshalb kein automatisch positiver oder negativer Wertinput.'
  ],'Ein konsistentes Szenario verbindet Preis, Menge, Kosten und benötigte Ressourcen.'),
  'Frühindikatoren werden mit ihrer Bedeutung und Verzögerung benannt. Ein Installationsauftrag kann künftige Wartung anzeigen; fehlende Techniker können verfügbare Kapazität begrenzen; veränderte Erneuerungsquoten können Substitution anzeigen. Datenqualität und alternative Erklärungen werden mitgeprüft.',
  'Bei einer einzelnen Sensitivität bleiben andere Größen ausdrücklich konstant. Bei einem Szenario werden zusammengehörige Größen gemeinsam verändert. Aus drei Szenarien entsteht ohne begründete Wahrscheinlichkeiten noch keine bekannte Eintrittsverteilung.'
 ]),
 S('integrated','27. Die Branchenthese bis zur Kapital- und Wertwirkung verfolgen','a c d',[
  'Der Nordmarkt-Fall zeigt zehn Prozent Marktumsatzwachstum, einen Anteilsgewinn von A und eine Verbesserung seiner Marge. Eine plausible These muss alle drei erklären: Nachfrage oder Preis, Gewinnung passender Kunden und nachhaltige Effizienz beziehungsweise Leistung. Gleichzeitig werden neue Anlagen, Personal, Teilebestand und Finanzierung geprüft. Umsatz plus Marge ist noch keine freie Zahlung.',
  X('Zwei stabile Zustände mit klarer Kapitalbasis vergleichen','Getrennte eigene Bewertungsfälle: kommender Umsatz 242, Steuer 25 Prozent, Kosten neun Prozent und Wachstum drei Prozent. Die Anfangskapitalquote ist Anfangskapital geteilt durch kommenden Umsatz. Neue Investitionen erhalten hier ausdrücklich dieselbe Rendite wie der konsistente stabile Gesamtbetrieb.',[
   T(['Fall','EBIT-Marge','Anfangskapital / nächster Umsatz','NOPAT','ROIC','Nettoinvestition','FCFF','Operativer Wert'],[['A','12 %','0,5','21,78','18 %','3,63','18,15','302,5'],['B','8 %','0,8','14,52','7,5 %','5,808','8,712','145,2']],'Mio. € außer Quoten. Wert eines unverschuldeten stabilen Betriebs am Zeitpunkt vor der ersten Zahlung; keine separate Cashposition oder sonstige Ansprüche.'),
   F('IC_0=\\lambda S_1,\\quad NOPAT_1=m(1-\\tau)S_1,\\quad IC_1=(1+g)IC_0','Bei konstanter Anfangskapitalquote benötigt der Umsatz der nächsten Folgeperiode ebenso viel prozentual mehr Kapital. Die Investition der ersten Periode bildet diesen zusätzlichen Bestand; bestehendes Kapital wird im Modell erhalten.',[['IC_0,IC_1','Operatives Kapital am Anfang und Ende der ersten Periode.'],['\\lambda','Anfangskapital relativ zum unmittelbar folgenden Umsatz.'],['S_1,NOPAT_1','Umsatz und operativer Nachsteuerertrag der ersten Periode.'],['m,\\tau,g','EBIT-Marge, Steuer und stabiles Wachstum.']]),
   F('I_{net,1}=IC_1-IC_0=gIC_0,\\quad FCFF_1=NOPAT_1-I_{net,1}','Fall A benötigt Anfangskapital 121 und zusätzlich 3,63; Fall B benötigt 193,6 und zusätzlich 5,808. Der höhere Kapitalbedarf mindert die erste freie Zahlung selbst bei gleichem Umsatzwachstum.',[['I_{net,1}','Zusätzliche Kapitalbindung der ersten Periode nach Erhaltung des bestehenden Kapitalstocks.'],['IC_0,IC_1','Operatives Anfangs- und Endkapital.'],['g','Stabiles Wachstum.'],['FCFF_1,NOPAT_1','Erste freie operative Zahlung und zugehöriger Nachsteuerertrag.']]),
   F('R=\\frac{m(1-\\tau)}{\\lambda},\\quad I_{net}=\\frac{g}{R}NOPAT,\\quad V_{op}=\\frac{NOPAT-I_{net}}{k-g}','Die stabile Konstruktion verbindet Marge und Anfangskapitalquote mit derselben Rendite neuer Investitionen. Sie wird nicht ungeprüft auf eine Firma mit abweichenden alten und neuen Renditen übertragen.',[['R','Konstante Gesamt- und marginale neue Kapitalrendite in genau diesen Vergleichsfällen.'],['m,\\tau','EBIT-Marge und Modellsteuer.'],['\\lambda','Operatives Anfangskapital relativ zum kommenden Umsatz.'],['I_{net},NOPAT','Zusätzliche Kapitalbindung der ersten Periode und ihr Nachsteuerertrag.'],['g,k','Stabiles Wachstum und passende Kosten mit g unter k und R.'],['V_{op}','Operativer Barwert der stabilen freien Zahlungen.']]),
   F('V_A=21{,}78(1-0{,}03/0{,}18)/0{,}06=302{,}5,\\quad V_B=14{,}52(1-0{,}03/0{,}075)/0{,}06=145{,}2','Marge und Kapitalbedarf erzeugen deutlich verschiedene Zahlungen bei gleicher Umsatzgröße.',[['V_A,V_B','Operative Werte der beiden ausdrücklich verschiedenen Fälle.']]),
   'Fall B hat trotz positivem Gewinn eine Rendite unter Kosten. Ohne Wachstum und bei gleicher erster Ertragsbasis wäre sein operativer Wert 14,52/0,09 oder 161,3333. Zusätzliches Wachstum auf dieser unterrentablen Kapitalbasis reduziert den Wert auf 145,2. Für A erhöht dasselbe Wachstum den Wert gegenüber 21,78/0,09 oder 242.'
  ],'Die Branchenanalyse begründet wirtschaftliche Inputs; die Bewertung prüft ihre vollständigen Kapital- und Zahlungsfolgen.'),
  G({id:'margin-capital-value',title:'Ein Margenurteil benötigt eine Kapitalannahme',caption:'Eigene stabile Vergleichsfälle: kommender Umsatz 242, Steuer 25 %, Wachstum 3 % und Kosten 9 %. Gezeichnete EBIT-Margen 4–16 %; Anfangskapital / nächster Umsatz beträgt 0,5 beziehungsweise 0,8. Neue Investitionsrendite entspricht hier der passenden stabilen Gesamt-Kapitalrendite.',reading:'Bei gleicher Marge verbraucht der kapitalintensivere Betrieb mehr Mittel für dasselbe Wachstum. Die Kurven sind kontrollierte Modellwirkungen, keine Marktkurse. Der tatsächliche Aktienwert benötigt zusätzlich passende Vermögens- und Anspruchsbrücken.',plot:{x:[4,16],y:[0,450],xTicks:[4,6,8,10,12,14,16],yTicks:[0,100,200,300,400],xLabel:'Stabile EBIT-Marge, Prozent',yLabel:'Operativer Wert, Millionen Euro',series:[{name:'Anfangskapitalquote 0,5',points:Array.from({length:49},(_,i)=>[4+i/4,value((4+i/4)/100,.5)])},{name:'Anfangskapitalquote 0,8',dash:true,points:Array.from({length:49},(_,i)=>[4+i/4,value((4+i/4)/100,.8)])}]}}),
  'Die konkrete Nordmarkt-Branchenrechnung und die stabilen Wertfälle werden nicht als identische Daten ausgegeben. Der erste Fall beschreibt zwei beobachtete hypothetische Jahre; die zweiten verlangen zusätzliche langfristige Kapital- und Risikohypothesen. Ein guter Researchbericht macht diesen Unterschied sichtbar.'
 ]),
 S('review','28. Prüffragen und belastbare Zusammenfassung','a b c d',[
  T(['Frage','Vollständige Erklärung'],[['Warum kann dieselbe Firma unterschiedliche Marktanteile besitzen?','Produkt, Region, Zeitraum und passende Umsätze verändern den Nenner.'],['Warum sind GICS und ICB nicht allein über Hierarchienamen gleichzusetzen?','Sector und Industry stehen auf verschiedenen Stufen.'],['Warum ist ein Betriebsstättencode nicht automatisch der Code eines ganzen Konzerns?','Erhebungseinheit und vielfältige Geschäftstätigkeit unterscheiden sich.'],['Warum können steigende Umsätze mit sinkendem Anteil auftreten?','Der Gesamtmarkt wächst noch schneller.'],['Warum sind zwei Anteilspunkte nicht zwei Prozent relative Verbesserung?','Relative Veränderung wird auf den alten Anteil bezogen.'],['Warum ist nominales Wachstum nicht gleich Mengenwachstum?','Preis, Qualität, Mix, Währung und Umfang können mitwirken.'],['Warum ist der Margendurchschnitt nicht die Branchenmarge?','Gewichte und Auswahl entscheiden den Quotienten.'],['Warum kann Konzentration ohne hohe Renditen bestehen?','Käufer, Substitute, Eintritt und Rivalitätsanreize begrenzen Erträge.'],['Warum braucht volle Kostenweitergabe eine Mengenannahme?','Höherer Preis kann Kundennachfrage und Konkurrenzreaktion verändern.'],['Warum benötigen Five Forces und PESTLE konkrete Kanäle?','Ein Label erklärt noch keine Finanzzeile oder Wirkungshöhe.'],['Warum kann Wachstum trotz positiver Marge Wert reduzieren?','Zusätzlich gebundenes Kapital verdient weniger als seine Kosten.'],['Welche Beobachtung würde die eigene These ändern?','Vorher benannte Daten, Gegenhypothesen und Entscheidungsschwellen.']],'Die unabhängige englische Fragenbank prüft Definition, Rechnung, Fallabgrenzung, Fehleranalyse und Transfer.'),
  'Ein belastbares Branchenurteil benennt Marktgrenzen, Messgrößen, relative Position, Wettbewerbsmechanismen, äußere Entwicklungen und Prognosefolgen. Es nennt Unsicherheit, Datenstand und die Bedingungen seiner Fortgeltung. Die ausführlichen mathematischen Beziehungen, Beispiele und verlinkten Kapitel dienen als Nachschlageweg; jede Formel besitzt ihre Lesart und ausklappbaren Symboldefinitionen.'
 ])
],related:[
 {unit:'market-structures',section:'concentration',label:'Konzentration, Marktform und Marktmacht trennen'},
 {unit:'market-structures',section:'strategic-choices',label:'Strategische Reaktion im Oligopol verstehen'},
 {unit:'market-structures',section:'shutdown',label:'Kurzfristige Kostendeckung von langfristigem Gewinn unterscheiden'},
 {unit:'business-models',section:'value-chain',label:'Wertschöpfungsstufen und Kundenrolle abgrenzen'},
 {unit:'business-models',section:'networks',label:'Netzwerkeffekte von Skaleneffekten unterscheiden'},
 {unit:'forecasting',section:'industry-company',label:'Markt- und Firmenprognose aufeinander abstimmen'},
 {unit:'forecasting',section:'competition',label:'Wettbewerb in Preis und Kosten übersetzen'},
 {unit:'valuation-model',section:'terminal-capital',label:'Marginale und gesamte Kapitalrendite konsistent behandeln'},
 {unit:'multiples',section:'peers',label:'Eine wirtschaftlich geeignete Vergleichsgruppe auswählen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Industry and Competitive Analysis, Seite 17; maßgebliche vier Lernziele',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=17'},
 {title:'CFA Institute: Industry and Competitive Analysis; ergänzende öffentliche Einführung 2026, nicht unverändert als Lernzielkatalog 2027 übernommen',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/industry-and-competitive-analysis'},
 {title:'MSCI: Global Industry Classification Standard; Hierarchie und Hauptaktivität',url:'https://www.msci.com/indexes/index-resources/gics'},
 {title:'LSEG / FTSE Russell: Industry Classification Benchmark; Hierarchie und Unternehmenseinordnung',url:'https://www.lseg.com/en/ftse-russell/industry-classification-benchmark-icb'},
 {title:'U.S. Census Bureau: NAICS; Erhebung wirtschaftlicher Betriebsstätten',url:'https://www.census.gov/naics/'},
 {title:'U.S. Census Bureau: NAICS 2022 Manual; produktionsorientierte Klassifikationsgrundlage',url:'https://www.census.gov/naics/reference_files_tools/2022_NAICS_Manual.pdf'},
 {title:'Harvard Business School, Institute for Strategy and Competitiveness: The Five Forces; ursprünglicher Methodenrahmen',url:'https://www.isc.hbs.edu/strategy/business-strategy/Pages/the-five-forces.aspx'},
 {title:'CIPD: PESTLE Analysis; externe Einflussdimensionen und Begrenzungen',url:'https://www.cipd.org/en/knowledge/factsheets/pestle-analysis-factsheet/'},
 {title:'OpenStax, Principles of Economics 3e: Barriers to Entry; Skalierung und Marktzugang',url:'https://openstax.org/books/principles-economics-3e/pages/9-1-how-monopolies-form-barriers-to-entry'},
 {title:'OpenStax, Principles of Economics 3e: Oligopoly; Konkurrenzanreize und gegenseitige Abhängigkeit',url:'https://openstax.org/books/principles-economics-3e/pages/10-2-oligopoly'}
],review:{status:'draft',date:'2026-10-06',note:'Eigene Markt-, Anteils-, Margen-, Wettbewerbs- und Wertfälle; ergänzende Mathematik als Vertiefung. Technische und numerische Prüfungen ersetzen nicht die fachliche Gesamtabnahme.'}};
