const {F,T,X,S,G}=require('../author.cjs');
module.exports={id:'issuer-forms',intro:[
 'Ein Unternehmen benötigt Ressourcen, Menschen und Kapital. Seine Rechtsform legt fest, wem Vermögen und Verpflichtungen rechtlich zugeordnet werden, wer Entscheidungen trifft und wie Eigentümer wechseln können. Für Investoren ist deshalb nicht nur der erwartete Gewinn entscheidend: Sie müssen wissen, welchen Anspruch sie kaufen und welches zusätzliche Risiko damit verbunden ist.',
 'Dieses Kapitel trennt vier Ebenen: Rechtsform, steuerliche Behandlung, Eigentümerstruktur und Zugang zum Kapitalmarkt. Ein Corporate Issuer nimmt als Unternehmen Kapital durch Ausgabe von Eigen- oder Fremdkapitalinstrumenten auf. Die englischen Grundbegriffe beschreiben typische Merkmale; konkrete Regeln unterscheiden sich zwischen Rechtsordnungen. Eigene Zahlenfälle zeigen Haftung, Steuern, Kapitalaufnahme, wirtschaftliche Beteiligung und Stimmrechte jeweils unter ausdrücklich genannten Annahmen.'
],sections:[
 S('dimensions','1. Vier Fragen vor jedem Unternehmensvergleich','a b c',[
  T(['Ebene','Leitfrage','Häufige Verwechslung'],[
   ['Rechtliche Zuordnung','Wer besitzt das Betriebsvermögen und schuldet die Zahlungen?','Ein Eigentümer besitzt nicht persönlich jeden einzelnen Vermögenswert seiner Gesellschaft.'],
   ['Haftung','Kann ein Gläubiger zusätzlich auf das persönliche Vermögen des Eigentümers zugreifen?','Beschränkte Haftung bedeutet nicht, dass die Aktie ihren Wert behalten muss.'],
   ['Steuern','Wird Gewinn auf Unternehmens-, Eigentümer- oder beiden Ebenen belastet?','Privates Eigentum legt die Steuerklassifikation nicht allein fest.'],
   ['Eigentum und Handel','Wer hält wirtschaftliche Rechte, wer kontrolliert Stimmen, und wie können Anteile verkauft werden?','Börsennotierung und Eigentum des Staates sind verschiedene Eigenschaften.']
  ],'Jede Ebene beantwortet eine eigene Frage. Ein kurzer Firmenzusatz liefert noch nicht alle Antworten.'),
  'Ein Investor kann zum Beispiel Anteile einer privat gehaltenen Kapitalgesellschaft besitzen, deren Schuldpapiere öffentlich angeboten werden. Eine andere Gesellschaft kann börsennotierte Aktien besitzen und zugleich von einer Familie oder einem Staat kontrolliert werden. Öffentlich gehandelte Eigenkapitalanteile, öffentliche Wertpapierangebote und staatliche Eigentümerschaft müssen daher sprachlich sauber auseinandergehalten werden.'
 ]),
 S('forms','2. Einzelunternehmen, Partnerschaft und Kapitalgesellschaft vergleichen','a',[
  'Beim Sole Proprietorship betreibt eine natürliche Person das Geschäft als Einzelunternehmer. Die direkte Entscheidungsmacht und die einfache Organisation können für einen kleinen Betrieb nützlich sein. Der Zugang zu zusätzlichem Eigenkapital ist jedoch an die einzelne Eigentümerperson gebunden; die Aufnahme weiterer Eigentümer erfordert eine andere Struktur. Im typischen Grundfall ist die persönliche Haftung nicht auf das Betriebsvermögen beschränkt.',
  'Eine General Partnership verbindet mehrere Gesellschafter. Sie kann Kapital, Fähigkeiten und Kundenbeziehungen zusammenführen, benötigt aber Regeln über Entscheidungen, Gewinnverteilung, Eintritt und Austritt. Die typischen persönlich haftenden Partner tragen gegenüber Gläubigern mehr Risiko als ein bloßer Aktionär einer haftungsbeschränkten Gesellschaft. Eine intern vereinbarte Gewinnquote allein begrenzt den externen Gläubigeranspruch nicht automatisch.',
  T(['Grundform','Eigentum und Leitung','Typische Haftungsstruktur','Finanzierungsfolge'],[
   ['Sole Proprietorship','Ein Eigentümer führt oder organisiert das Geschäft.','Persönliche Haftung des Einzelunternehmers im Grundmodell.','Keine eigenständige Ausgabe gewöhnlicher Unternehmensaktien an viele Eigentümer.'],
   ['General Partnership','Mehrere Partner; Entscheidungsrechte nach Vertrag und Recht.','General Partners grundsätzlich persönlich haftend; konkrete Anspruchsregeln prüfen.','Partnerkapital und Kredit; Übertragung und Fortführung benötigen passende Vereinbarungen.'],
   ['Limited Partnership','Mindestens ein General Partner; daneben Limited Partners.','Unbeschränkte Haftung auf Ebene des General Partners; begrenzte Haftung der Limited Partners unter den maßgeblichen Voraussetzungen.','Trennung von geschäftsführender Verantwortung und passivem Beteiligungskapital möglich.'],
   ['Limited Company / Corporation','Eigenständige Gesellschaft mit Anteilen; Eigentümer und Leitung können getrennt sein.','Gesellschaft haftet mit ihrem Vermögen; bloßer Anteilseigner typischerweise auf seine Beteiligung beschränkt.','Viele Eigentümer und handelbare Anteile erleichtern eine breite Eigenkapitalbasis.']
  ],'Typische Grundmodelle, keine Behauptung identischer Regeln in jedem Land.'),
  'Limited Partnership, Limited Liability Partnership und Limited Liability Company sind unterschiedliche Begriffe. Eine LLP kann die persönliche Haftung ihrer Mitglieder begrenzen; eine LLC verbindet unter ihrem jeweiligen Recht gesellschaftliche Haftungsmerkmale mit unterschiedlichen möglichen Steuerklassifikationen. Diese Kürzel dürfen nicht allein aufgrund des Wortes „limited“ gleichgesetzt werden.',
  'Auch die rechtliche Eigenständigkeit einer Partnerschaft ist länderabhängig. Für eine Analyse werden deshalb zuerst die konkrete Einheit, der Vertrag und die anwendbaren Regeln identifiziert. Anschließend lässt sich das wirtschaftliche Grundmuster aus der Tabelle zuordnen.'
 ]),
 S('liability','3. Beschränkte Haftung schützt nicht den investierten Betrag','a b',[
  'Eine Kapitalgesellschaft kann ihre gesamten Vermögenswerte verlieren. Beschränkte Haftung bedeutet im Grundfall, dass der Gläubiger den bloßen, vollständig eingezahlten Aktionär nicht zusätzlich zur Begleichung gewöhnlicher Gesellschaftsschulden heranzieht. Der Aktionär kann seine Beteiligung dennoch vollständig verlieren. Persönliche Garantien, nicht erfüllte Einlagepflichten und besondere Haftungstatbestände sind eigenständig zu prüfen.',
  X('Dasselbe Geschäft, unterschiedliche private Belastung','Ein Geschäft besitzt bei Abwicklung realisierbare Aktiva von 70 und fällige unbesicherte Schulden von 100. Es gibt einen Eigentümer, keine Abwicklungskosten und keine weiteren Rangklassen. Sein bereits investiertes Eigenkapital ist verloren. Verglichen werden ein persönlich haftender Einzelunternehmer mit ausreichend weiterem Privatvermögen und ein bloßer Aktionär ohne Garantie oder sonstige zusätzliche Haftung.',[
   F('H=\\max(D-A,0)=\\max(100-70,0)=30','Die Gesellschaftsaktiva lassen eine Deckungslücke von 30 zurück.',[['H','Ungedeckter Schuldenteil vor zusätzlichem persönlichem Rückgriff.'],['D','Fällige Schulden im vereinfachten Abwicklungsfall.'],['A','Dafür realisierbare Gesellschaftsaktiva.']]),
   T(['Variante','Aus dem Geschäft bezahlt','Zusätzlicher persönlicher Rückgriff im Fall','Verbleibender Gläubigerausfall'],[['Persönlich haftender Einzelunternehmer','70','30','0'],['Bloßer haftungsbeschränkter Aktionär','70','0','30']],'Bei beiden Varianten ist die Eigentümerbeteiligung am Geschäft wertlos. Nur der weitere Rückgriff unterscheidet sich.'),
   'Wäre für denselben Gesellschaftskredit eine wirksame persönliche Garantie über 20 gegeben, könnte der betrachtete Garant zusätzlich bis zu 20 leisten müssen. Der Schutz aus dem bloßen Aktienbesitz beseitigt die gesonderte Garantie nicht.'
  ],'Haftung beeinflusst die Verteilung eines Verlusts. Sie entfernt den Verlust nicht aus dem Wirtschaftssystem; Gläubiger berücksichtigen ihn etwa über Preis, Sicherheiten und Vertragsbedingungen.'),
  'Bei einer Limited Partnership kann der General Partner selbst eine haftungsbeschränkte Gesellschaft sein. Dann haftet diese Partnergesellschaft auf ihrer Ebene unbeschränkt für die Partnerschaftsschuld; daraus folgt nicht automatisch ein unbegrenzter Zugriff auf die privaten Vermögen ihrer eigenen Aktionäre. Die Kette der Rechtsträger muss Schritt für Schritt betrachtet werden.'
 ]),
 S('identity-control','4. Eigenständigkeit, Fortbestand und delegierte Leitung','b',[
  'Eine eigenständige Gesellschaft kann Vermögen halten, Verträge schließen und Finanzierung aufnehmen. Wenn ein Anteilseigner seine Aktien verkauft, verkauft er seinen Anteil an der Gesellschaft. Der Eigentümer des Betriebsvermögens bleibt im normalen Aktienverkauf dieselbe Gesellschaft; ihre Verpflichtungen werden nicht allein durch den Aktionärswechsel zu persönlichen Verpflichtungen des Käufers.',
  'Die Gesellschaft kann grundsätzlich über den Wechsel oder Tod einzelner Aktionäre hinaus fortbestehen. Das erleichtert langfristige Investitionen und die Übertragbarkeit von Eigentum. Fortbestand ist aber keine Garantie ewiger Existenz: Insolvenz, Verschmelzung, freiwillige Auflösung und rechtliche Eingriffe können ihn beenden.',
  'Eigentümer wählen im typischen Corporate-Modell ein Board, das Leitung bestellt und überwacht. Die operative Geschäftsführung trifft Entscheidungen innerhalb ihrer Befugnisse. Diese Delegation erlaubt professionelle Leitung und viele passive Kapitalgeber. Zugleich entstehen Informations- und Interessenkonflikte: Eine Führungskraft kann eigene Karriere, Vergütung oder Größe des Unternehmens gegenüber dem Wert für die Eigentümer bevorzugen.',
  'Die Struktur schafft deshalb zwei zusammenhängende Aufgaben. Finanzierung wird leichter, wenn ein Investor keine tägliche Leitungsarbeit übernehmen muss; Überwachung wird notwendiger, weil er die Entscheidungen nicht selbst trifft. Stimmrechte, Berichte, unabhängige Kontrolle und Vergütungsverträge verbinden beide Seiten. Die genaue Organstruktur kann etwa ein- oder zweistufig sein.'
 ]),
 S('taxation','5. Rechtsform und Steuerbelastung getrennt rechnen','a b',[
  'Steuerliche Transparenz bedeutet im hier betrachteten Grundmodell, dass ein Gewinn den Eigentümern für deren Besteuerung zugerechnet wird. Bei einer gesondert besteuerten Kapitalgesellschaft kann derselbe wirtschaftliche Gewinn zunächst Unternehmenssteuer und bei Ausschüttung zusätzlich Eigentümersteuer auslösen. Steueranrechnung, Befreiungen, Quellensteuern und weitere Regeln können den tatsächlichen Ablauf verändern.',
  'Eine privat gehaltene Gesellschaft ist nicht automatisch steuerlich transparent. Ein konkretes Gegenbeispiel ist die britische Private Limited Company, bei der grundsätzlich Corporation Tax auf steuerpflichtige Gewinne anfällt. Bei einer US-LLC hängt die Bundessteuerklassifikation unter anderem von Mitgliederzahl und wirksamen Wahlen ab. Eine gesellschaftsrechtliche Haftungsbegrenzung entscheidet deshalb nicht allein über die steuerliche Ebene.',
  F('C_{owner}=\\Pi(1-\\tau_c)(1-\\tau_d),\\qquad\\tau_{eff}=1-(1-\\tau_c)(1-\\tau_d)','Bei vollständiger Ausschüttung wird die Eigentümersteuer auf den bereits nach Unternehmenssteuer verbleibenden Betrag angewendet.',[['C_{owner}','Nach beiden Steuern beim Eigentümer ankommender Cashbetrag.'],['\\Pi','Gewinn vor den beiden betrachteten Steuerebenen.'],['\\tau_c','Angenommener Unternehmenssteuersatz.'],['\\tau_d','Angenommener Steuersatz auf die Ausschüttung beim Eigentümer.'],['\\tau_{eff}','Gesamte effektive Belastung relativ zum ursprünglichen Gewinn.']]),
  X('Warum zwei Steuersätze nicht einfach addiert werden','Eigener Modellfall: Gewinn 1.000, Unternehmenssteuer 25 %, zusätzliche Ausschüttungssteuer 20 %, vollständige Ausschüttung, keine Anrechnung oder sonstigen Steuern. Eine transparente Vergleichsform unterliegt ausschließlich einer angenommenen Eigentümersteuer von 35 %.',[
   F('C_{owner}=1000\\cdot0{,}75\\cdot0{,}80=600,\\quad\\tau_{eff}=40\\%','Unternehmenssteuer beträgt 250; Eigentümersteuer beträgt 150 auf den Rest von 750.',[['C_{owner}','Nettozufluss nach beiden Steuern.'],['\\tau_{eff}','Gesamtsteuer 400 relativ zum Ausgangsgewinn 1.000.']]),
   F('C_{pass}=1000(1-0{,}35)=650','Im ausdrücklich einstufigen Vergleichsfall verbleiben 650.',[['C_{pass}','Eigentümerbetrag nach der angenommenen transparenten Besteuerung und vollständigen Auszahlung.']]),
   '25 % plus 20 % ergäben fälschlich 45 %, weil die zweite Steuer nicht auf denselben Ausgangsbetrag erhoben wird. Die Differenz von 50 zwischen den Modellen stammt aus ihren Annahmen, nicht aus einer universell besseren Rechtsform.'
  ],'Die Rechnung erklärt den Mechanismus. Eine tatsächliche Strukturentscheidung benötigt außerdem Haftung, Finanzierung, Kosten und die konkret einschlägigen Steuerregeln.')
 ]),
 S('retention','6. Zurechenbarer Gewinn ist nicht automatisch ausgezahltes Geld','a b',[
  'Bei einer transparent besteuerten Beteiligung können Gewinnzurechnung und Ausschüttung auseinanderfallen. Eine Gesellschaft kann Mittel für Vorräte oder Anlagen einbehalten, während ein Eigentümer auf seinen zugerechneten Gewinn persönlich Steuern schuldet. Eine vertragliche Steuerausschüttung kann dieses Liquiditätsproblem berücksichtigen; ihre Verfügbarkeit darf nicht ohne Vertrag vorausgesetzt werden.',
  X('Steuer ohne passende Ausschüttung','Eine ausdrücklich steuerlich transparente Partnerschaft erwirtschaftet 100 Gewinn. Eine Partnerin besitzt einen Gewinnanteil von 60 %. Ihr angenommener Steuersatz beträgt 30 %. Der gesamte Gewinn bleibt im Betrieb; andere Regeln und Steuern werden im Fall ausgeschlossen.',[
   F('\\Pi_P=100\\cdot0{,}60=60,\\qquad Tax_P=60\\cdot0{,}30=18','Der zugerechnete Gewinn und die persönliche Steuer werden berechnet, obwohl keine Auszahlung erfolgt.',[['\\Pi_P','Der Partnerin zugerechneter Gewinn.'],['Tax_P','Persönlich zu zahlende Steuer im Modell.']]),
   'Die Partnerin erhält null Cash aus dem Unternehmen, benötigt aber 18 für ihre Steuer. Eine gute Ergebnisentwicklung kann so eine private Finanzierungslücke erzeugen.',
   'Bei einer gesondert besteuerten Gesellschaft sind einbehaltene Nachsteuergewinne dagegen zunächst Vermögen der Gesellschaft. Auch ein alleiniger Aktionär kann diesen Cashbestand nicht ohne passende gesellschafts- und steuerrechtliche Behandlung wie sein Privatkonto verwenden.'
  ],'Gewinnanspruch, Steuerzurechnung, Ausschüttung und frei verfügbares Eigentümergeld sind vier unterschiedliche Größen.')
 ]),
 S('voting','7. Kapitalanteil und Stimmrechtskontrolle auseinanderhalten','b c',[
  'Bei einer einfachen Aktienklasse mit gleichen Rechten folgen Stimm- und wirtschaftliche Beteiligung oft derselben Quote. Mehrere Aktienklassen können dies aufheben. Zusätzlich können Vereinbarungen, Vetorechte und besondere Beschlussmehrheiten relevant sein. Die bloße Aussage „hält 20 %“ ist deshalb ohne Angabe des betrachteten Rechts unvollständig.',
  F('w_E=\\frac{N_F}{N_A+N_B},\\qquad w_V=\\frac{v_A N_F}{v_A N_A+v_B N_B}','Die Gründerin hält hier ausschließlich einen Teil der A-Aktien; beide Klassen haben gleiche wirtschaftliche Rechte, aber unterschiedlich viele Stimmen je Aktie.',[['w_E,w_V','Wirtschaftliche Beteiligungsquote und Stimmrechtsquote der Gründerin.'],['N_F','Von der Gründerin gehaltene A-Aktien.'],['N_A,N_B','Sämtliche ausstehenden Aktien der Klassen A und B.'],['v_A,v_B','Stimmen je Aktie der jeweiligen Klasse.']]),
  X('20 % wirtschaftliches Eigentum, mehr als 70 % der Stimmen','200.000 A-Aktien mit je zehn Stimmen gehören vollständig der Gründerin. Weitere Anleger halten 800.000 B-Aktien mit je einer Stimme. Dividenden- und Liquidationsrechte seien je Aktie gleich; keine Sondervereinbarungen.',[
   F('w_E=\\frac{200000}{1000000}=20\\%,\\qquad w_V=\\frac{2000000}{2000000+800000}\\approx71{,}43\\%','Stimmgewicht und Kapitalgewicht verwenden unterschiedliche Zähler und Nenner.',[['w_E,w_V','Wirtschaftlicher Anteil und Stimmenanteil.']]),
   'Für Beschlüsse mit einfacher Stimmenmehrheit besitzt die Gründerin unter diesen Annahmen eine Mehrheit. Daraus folgt nicht, dass sie jede denkbare Entscheidung allein durchsetzen kann: Sondermehrheiten, Klassenrechte oder unabhängige Kontrollpflichten können zusätzlich gelten.'
  ],'Investoren bewerten deshalb sowohl den Zahlungsanspruch als auch die Möglichkeit, Entscheidungen zu beeinflussen.')
 ]),
 S('primary-secondary','8. Neue Aktien finanzieren die Firma, alte Aktien wechseln den Eigentümer','b c',[
  'Am Primärmarkt werden neue Wertpapiere ausgegeben. Der Emittent erhält den entsprechenden Emissionserlös nach Kosten. Beim normalen Sekundärmarktgeschäft verkauft dagegen ein bisheriger Anleger an einen neuen Anleger. Der Kaufpreis fließt an den Verkäufer; der Gesellschaft entsteht daraus allein kein neuer Cashzufluss.',
  F('N_1=N_0+\\frac{C}{p},\\qquad w_{F,1}=\\frac{N_F}{N_1}','Eine reine Ausgabe neuer gleicher Aktien vergrößert den Nenner der Beteiligungsquote. Die Gründerin zeichnet in diesem Fall nicht mit.',[['N_0,N_1','Ausstehende Aktien vor und nach der Kapitalerhöhung.'],['C','Bruttozufluss aus der Ausgabe neuer Aktien.'],['p','Einheitlicher Ausgabepreis je neuer Aktie.'],['N_F','Unveränderter Aktienbestand der Gründerin.'],['w_{F,1}','Ihre neue wirtschaftliche Beteiligungsquote.']]),
  X('Mira Sensors nimmt vier Millionen auf','Vor der Finanzierung bestehen 1,2 Mio. gleiche Aktien: 0,9 Mio. gehören der Gründerin, 0,3 Mio. anderen Anlegern. Der angenommene faire gesamte Eigenkapitalwert vor Finanzierung beträgt 12 Mio. €. Neue Anleger zahlen 4 Mio. € zu 10 € je Aktie. Keine Gebühren, keine Nebenrechte, kein anderer Wert- oder Geschäftseffekt.',[
   F('N_{new}=\\frac{4000000}{10}=400000,\\quad N_1=1600000,\\quad w_{F,1}=\\frac{900000}{1600000}=56{,}25\\%','Die Gründerin fällt von 75 % auf 56,25 %, behält aber alle 900.000 Aktien.',[['N_{new}','Neue Aktien.'],['N_1','Gesamte Aktien nach der Ausgabe.'],['w_{F,1}','Beteiligungsquote der Gründerin danach.']]),
   T(['Eigentümergruppe','Aktien vorher','Aktien nachher','Quote nachher','Wert nachher in Mio. €'],[['Gründerin','900.000','900.000','56,25 %','9'],['Übrige Altanleger','300.000','300.000','18,75 %','3'],['Neue Anleger','0','400.000','25 %','4'],['Summe','1.200.000','1.600.000','100 %','16']],'Zum angenommenen fairen Preis erhöht der neue Cashzufluss den Eigenkapitalwert auf 16 Mio. €.'),
   'Die Quote sinkt, der Wert der Gründerinnenbeteiligung bleibt im isolierten Modell 9 Mio. €. Quotenverwässerung bedeutet deshalb nicht automatisch Vermögensverlust. Kosten, ungünstige Sonderrechte oder ein zu niedriger Ausgabepreis können das Ergebnis ändern.',
   'Verkauft die Gründerin anschließend 100.000 bestehende Aktien zu 10 €, erhält sie selbst 1 Mio. €. Die Firma erhält aus diesem zweiten Vorgang null. Die gesamte Aktienzahl bleibt 1,6 Mio.; ihre restlichen 800.000 Aktien entsprechen 50 %.'
  ],'Vor einer Aussage über den Finanzierungserfolg wird jede angebotene Aktie ihrem Verkäufer und dem Empfänger ihres Kaufpreises zugeordnet.'),
  'Die Pre-Money-Bewertung bezeichnet hier den Eigenkapitalwert vor neuem Geld, die Post-Money-Bewertung den Wert danach. Eine Cap Table ordnet Aktien und Rechte den Eigentümern zu. Im fairen isolierten Fall wächst der Unternehmenswert im selben Verhältnis wie die Aktienzahl:',
  F('p_0=\\frac{V_0}{N_0},\\qquad p_1=\\frac{V_0+C}{N_0+C/p_0}=p_0','Mit V₀ gleich N₀ mal p₀ kürzt sich der neue Gesamtwert exakt zur bisherigen Bewertung je Aktie. Gleiche Rechte, keine Gebühren oder weiteren Wertänderungen sind wesentlich.',[['p_0,p_1','Theoretischer fairer Eigenkapitalwert je Aktie vor und nach der Finanzierung.'],['V_0','Gesamter Eigenkapitalwert vor neuem Geld.'],['N_0','Vorher ausstehende Aktien.'],['C','Neuer Eigenkapitalzufluss zum Preis p₀.']])
 ]),
 S('ownership-figure','9. Wie Kapitalbedarf eine Beteiligungsquote verändert','b c',[
  G({id:'capital-ownership',title:'Mehr neues Kapital kann die Stimmenmehrheit einer Gründerin auflösen',caption:'Mira-Modell: 1,2 Mio. gleiche Aktien vorher, davon 0,9 Mio. bei der Gründerin. Ausgabepreis konstant 10 €, keine Mitzeichnung, keine Gebühren oder Sonderrechte. Der anfängliche faire Eigenkapitalwert beträgt 12 Mio. €.',reading:'Ohne neue Ausgabe hält die Gründerin 75 %. Bei 4 Mio. € neuem Kapital hält sie 56,25 %, bei 6 Mio. genau 50 % und bei 12 Mio. 37,5 %. Bei gleichen Stimmen je Aktie und vollständiger Abstimmung besitzt sie jenseits von 6 Mio. keine eigene Stimmenmehrheit mehr. Im isolierten fairen Wertmodell bleiben ihre Aktien trotzdem zusammen 9 Mio. € wert.',plot:{x:[0,12],y:[30,80],xTicks:[0,2,4,6,8,10,12],xLabel:'Neues Eigenkapital in Mio. Euro',yLabel:'Anteil der Gründerin in %',series:[{name:'Beteiligungsquote',points:Array.from({length:25},(_,i)=>{const c=i*.5;return[c,.9/(1.2+c/10)*100];})},{name:'50-%-Schwelle',dash:'5 4',points:[[0,50],[12,50]]}],marks:[{x:0,y:75,label:'75 %',dx:8,dy:-12},{x:6,y:50,label:'6 Mio. / 50 %',dx:8,dy:-16},{x:12,y:37.5,label:'37,5 %',dx:-8,dy:20,anchor:'end'}]}}),
  F('\\frac{0{,}9}{1{,}2+C/10}=0{,}5\\quad\\Longrightarrow\\quad C=6','Der Schwellenwert folgt aus Aktienzahl und Preis; hier sind Aktienzahlen in Mio. und C in Mio. Euro angegeben.',[['C','Neues Kapital in Mio. Euro, bei dem der Gründerinnenanteil genau 50 % beträgt.']]),
  'Das Diagramm isoliert die Finanzierung bei konstantem Preis. In einer realen Verhandlung kann sich der Ausgabepreis mit Kapitalbedarf, neuen Informationen und Vertragsrechten ändern. 50 % sind außerdem keine allgemeine rechtliche Kontrollgarantie: Die konkrete Beschlussregel und Beteiligung an der Abstimmung bleiben entscheidend.',
  X('Ausgabe unter dem angenommenen fairen Wert','Im selben Ausgangsfall werden 4 Mio. € zu nur 5 € je neuer Aktie aufgenommen. Der wirtschaftliche Vorfinanzierungswert von 12 Mio. € bleibt als Modellannahme unverändert. Keine Bezugsrechte, Gebühren oder anderen Effekte.',[
   F('N_1=1{,}2+\\frac4{5}=2,\\qquad p_1=\\frac{12+4}{2}=8','Die Aktienzahl wächst auf 2 Mio.; rechnerischer fairer Wert je Aktie danach ist 8 €.',[['N_1','Aktienzahl nach Ausgabe in Mio. Stück.'],['p_1','Theoretischer Wert je Aktie nach Zufluss in Euro.']]),
   'Alle Altanleger zusammen besitzen danach 1,2 Mio. Aktien zu 8 €, also 9,6 Mio. statt vorher 12 Mio. €. Die neuen Anleger halten 0,8 Mio. Aktien im Wert von 6,4 Mio. für ihren Einsatz von 4 Mio. Die Wertübertragung von 2,4 Mio. stimmt auf beiden Seiten überein.',
   'Die Gründerin besitzt nun 45 % der Aktien, deren Modellwert nur noch 7,2 Mio. € beträgt. Hier fallen Beteiligungsquote und Vermögen. Dies unterscheidet den Fall von der fair bepreisten Ausgabe im vorigen Abschnitt.'
  ],'Erst Preis, Rechte und Mittelverwendung erlauben eine Bewertung der Verwässerung. Die veränderte Stückzahl allein genügt nicht.')
 ]),
 S('public-private','10. Öffentlich gehandelte und privat gehaltene Eigentumsanteile','c',[
  T(['Merkmal','Typische öffentlich gehandelte Aktie','Typische private Beteiligung'],[
   ['Verkaufsmöglichkeit','Organisierter Handel kann den Eigentümerwechsel erleichtern; Spread, Volumen und Sperrfristen bleiben relevant.','Käufersuche, Zustimmungserfordernisse und Vertragsrechte können den Verkauf erschweren.'],
   ['Preisinformation','Beobachtbare Kurse liefern laufende Marktbewertungen, aber keine garantierte korrekte Bewertung.','Verhandlungspreise und seltene Transaktionen verlangen mehr eigene Bewertung.'],
   ['Information','Umfangreiche öffentliche Berichts- und Marktanforderungen können gelten.','Weniger öffentliche Information; bestimmte Investoren können vertraglich detaillierte Berichte erhalten.'],
   ['Finanzierung','Breiterer potenzieller Anlegerkreis und spätere Emissionen möglich, abhängig von Marktlage und Zulassung.','Verhandelte Finanzierung durch Eigentümer, Fonds oder Kreditgeber; auch große Beträge möglich.'],
   ['Kontrolle und Kosten','Mehr Streubesitz kann Leitung von einzelnen Eigentümern entfernen; Veröffentlichung und Marktpräsenz verursachen Kosten.','Konzentrierte Eigentümer können direkt überwachen; Minderheitenschutz und Exitbedingungen werden besonders wichtig.']
  ],'Die Gegenüberstellung beschreibt typische Unterschiede, keine Garantie über Liquidität, Rendite oder Qualität.'),
  '„Public“ bedeutet in diesem Kapitalmarktkontext nicht automatisch „staatlich“. Eine börsennotierte Gesellschaft kann mehrheitlich einer Familie gehören. Ein Staatsunternehmen kann vollständig unnotiert bleiben. Ebenso sind „private limited company“ als Rechtsform und „privately held“ als Beschreibung der Eigentums- und Handelssituation nicht weltweit identische Begriffe.',
  'Ein Börsenkurs macht das zugrunde liegende Geschäft nicht risikolos. Eine illiquide private Beteiligung schwankt nicht allein deshalb weniger im wirtschaftlichen Wert, weil keine tägliche Kursnotierung sichtbar ist. Für den Vergleich müssen Preisbeobachtung und tatsächliches Geschäftsrisiko getrennt werden.'
 ]),
 S('ipo','11. Ein Börsengang mit neuen und bestehenden Aktien','c',[
  'Ein Initial Public Offering kann neue Aktien der Gesellschaft, bestehende Aktien bisheriger Eigentümer oder beide Arten enthalten. Der gesamte öffentlich gezeichnete Betrag ist deshalb nicht automatisch der neue Unternehmenscash. Emissionskosten vermindern zusätzlich den Nettozufluss des jeweiligen Kostenträgers.',
  F('C_{issuer}=pN_{new}-F,\\qquad C_{seller}=pN_{sold},\\qquad N_1=N_0+N_{new}','Nur neue Aktien erhöhen die ausstehende Aktienzahl. Der Altaktienverkauf verändert die Eigentümerzuordnung.',[['C_{issuer}','Nettozufluss an den Emittenten.'],['C_{seller}','Verkaufserlös der Altaktionäre vor eigenen Kosten und Steuern.'],['p','Angebotspreis je Aktie.'],['N_{new},N_{sold}','Zahl neuer bzw. von bisherigen Aktionären verkaufter bestehender Aktien.'],['F','Vom Emittenten getragene Emissionskosten.'],['N_0,N_1','Ausstehende Aktien vor und nach der Transaktion.']]),
  X('Großes Angebotsvolumen, kleinerer Unternehmenszufluss','Vor dem IPO bestehen 2 Mio. gleiche Aktien; eine Gründerin hält 1,4 Mio. Das Angebot umfasst 0,5 Mio. neue Aktien und 0,2 Mio. bestehende Aktien der Gründerin zu jeweils 20 €. Die Gesellschaft trägt 0,6 Mio. € Gebühren; persönliche Verkäuferkosten und Steuern bleiben außer Betracht.',[
   F('C_{offer}=20(0{,}5+0{,}2)=14,\\quad C_{issuer}=20\\cdot0{,}5-0{,}6=9{,}4,\\quad C_{seller}=20\\cdot0{,}2=4','Alle Geldbeträge sind Mio. Euro; die Aktienzahlen sind Mio. Stück.',[['C_{offer}','Gesamter Kaufpreis der Anleger.'],['C_{issuer}','Nettozufluss an die Gesellschaft.'],['C_{seller}','Erlös der Gründerin vor eigenen Steuern.']]),
   F('w_{F,1}=\\frac{1{,}4-0{,}2}{2+0{,}5}=48\\%','Die Gründerin verkauft einen Teil ihrer bisherigen Aktien; zusätzlich wächst der Gesamtnenner.',[['w_{F,1}','Gründerinnenanteil nach beiden Vorgängen.']]),
   'Die neuen öffentlichen Anleger besitzen zusammen 0,7 Mio. von 2,5 Mio. Aktien, also 28 %. Die Firma erhält dennoch nicht den Kaufpreis aller 0,7 Mio. Aktien. Kontrolle: 9,4 Firmenzufluss plus 0,6 Gebühren plus 4 Verkäufererlös ergeben die 14 Mio. Zahlung der Käufer.'
  ],'Nach dem IPO wirkt ein normaler Börsenverkauf zwischen Anlegern grundsätzlich auf deren Portfolios. Er führt ohne zusätzliche Emission nicht nochmals zu Finanzierung der Firma.'),
  'Anleger prüfen den Angebotsprospekt, Verwendung des Emissionserlöses, Verkäuferanteil, Rechte der Aktienklassen und mögliche Verkaufsbeschränkungen. Zulassung und regulatorische Registrierung sind keine behördliche Empfehlung, dass der Preis günstig oder das Geschäft sicher sei.'
 ]),
 S('listing-paths','12. IPO, Direktnotierung und SPAC unterscheiden','c',[
  'Ein traditioneller Börsengang wird häufig von Banken begleitet, die Nachfrage sammeln, Preisfindung und Platzierung organisieren. Eine Direct Listing kann dagegen bestehenden Eigentümern den Börsenhandel ihrer Aktien eröffnen, ohne eine klassische vorgelagerte Platzierung. Es existieren auch zugelassene Formen einer Primary Direct Listing mit Ausgabe neuer Aktien. Entscheidend ist daher die konkret gewählte Transaktion, nicht die pauschale Aussage „Direktnotierung bringt niemals neues Kapital“.',
  'Eine SPAC sammelt zunächst Kapital als börsennotierte Akquisitionsgesellschaft und sucht danach ein operatives Ziel. Durch die spätere Kombination kann das Ziel Zugang zu einem öffentlichen Aktienmarkt erhalten. Rückgaberechte der SPAC-Anleger, zusätzliche Investoren, Sponsorvergütung und potenzielle Aktien aus Warrants können den tatsächlich verfügbaren Cashbetrag und die Eigentumsquoten verändern.',
  X('Angekündigtes SPAC-Kapital ist noch kein endgültiger Zufluss','Eigener vereinfachter Fall: Ursprünglich stehen 200 Mio. € im Finanzierungstopf. Anleger lassen sich davon 120 Mio. auszahlen. Zusätzliche Investoren zahlen 50 Mio.; die Transaktion verbraucht 15 Mio. Kosten. Keine anderen Zuflüsse oder Verwendungen.',[
   F('C_{net}=200-120+50-15=115','Rückgaben und Kosten mindern den verfügbaren Betrag; die zusätzliche Finanzierung erhöht ihn.',[['C_{net}','Im vereinfachten Transaktionsrahmen verbleibender Cashbetrag in Mio. Euro.']]),
   '115 Mio. sind eine Cashrechnung. Um den Anteil der bisherigen Zieleigentümer zu bestimmen, werden außerdem alle ausgegebenen und potenziellen Aktien samt Vertragsrechten benötigt. Der ursprüngliche Topf von 200 Mio. beantwortet keine dieser beiden Fragen allein.'
  ],'Börsenzugang, Cashzufluss und wirtschaftliche Verwässerung sind getrennte Ergebnisse desselben Finanzierungsvorgangs.')
 ]),
 S('going-private','13. Rückzug von der Börse und Eigentümerwechsel','c',[
  'Bei einem Going Private werden öffentlich gehaltene Aktien beispielsweise durch einen kontrollierenden Eigentümer oder ein Übernahmekonsortium erworben; die Aktiennotierung kann anschließend enden. Das operative Unternehmen verschwindet dadurch nicht automatisch. Auch seine Gläubigeransprüche und Berichtsverpflichtungen lösen sich nicht allein mit dem Aktienhandel auf.',
  'Ein Leveraged Buyout nutzt einen erheblichen Fremdfinanzierungsanteil beim Erwerb. Der Käufer erwartet, seine Eigenkapitalrendite aus operativer Entwicklung, Schuldenabbau und späterem Verkauf zu erzielen. Die Finanzierung belastet aber die verfügbare Liquidität und kann Verluste auf dem Eigenkapital verstärken. Nicht jeder Rückzug von der Börse ist ein LBO; ein Erwerber kann auch überwiegend eigenes Geld verwenden.',
  X('Der gleiche Kaufpreis mit unterschiedlicher Eigenkapitalbelastung','Zwei vereinfachte Erwerbsfinanzierungen kaufen einen vollständig schuldenfreien Betrieb für 100. Im Vergleich A werden 100 Eigenkapital eingesetzt, in B 40 Eigenkapital und 60 endfällige Schulden. Ein Jahr später beträgt der verkaufbare Unternehmenswert entweder 110 oder 80. Nur zur Isolation des Hebels werden Zinsen, Steuern, Kosten und Ausschüttungen auf null gesetzt.',[
   T(['Endwert des Betriebs','Eigenkapitalwert A','Eigenkapitalrendite A','Eigenkapitalwert B nach Rückzahlung von 60','Eigenkapitalrendite B'],[['110','110','10 %','50','25 %'],['80','80','−20 %','20','−50 %']],'Gleicher operativer Wertverlauf, unterschiedlicher Eigenkapitaleinsatz und Vorranganspruch.'),
   F('r_E=\\frac{V_1-D_1}{E_0}-1','Die einfache Rechnung gilt hier, weil beide Endwerte oberhalb der Schuld liegen und weitere Cashflows ausdrücklich ausgeschlossen sind.',[['r_E','Eigenkapitalrendite des Erwerbers.'],['V_1','Verkaufbarer Unternehmenswert am Ende.'],['D_1','Dann zurückzuzahlende Schuld.'],['E_0','Anfänglicher Eigenkapitaleinsatz.']]),
   'Der höhere Gewinn in Variante B ist kein kostenloser Finanzierungsvorteil. Im schwachen Zustand fällt der Verlust ebenfalls größer aus; echte Zinsen und Restriktionen würden die Rechnung zusätzlich verändern.'
  ],'Kontrollwechsel und Finanzierungshebel müssen bei der Analyse gemeinsam, aber als unterschiedliche Mechanismen betrachtet werden.')
 ]),
 S('investor-map','14. Eigentümertypen, Auswahl und Grenzen der Struktur','a b c',[
  'Eigentümer können Gründerfamilien, Mitarbeitende, einzelne Anleger, Fonds, Versicherer, Pensionsinstitutionen, andere Unternehmen, gemeinnützige Organisationen oder Staaten sein. Ihre Ziele, Entscheidungsfristen und Kontrollmöglichkeiten unterscheiden sich. Ein strategischer Unternehmenseigentümer kann etwa Absatz- oder Technologieverbindungen suchen; ein Fonds muss zusätzlich die Regeln und Laufzeit seines Mandats beachten.',
  T(['Situation','Naheliegende Analysefrage','Unzulässiger Kurzschluss'],[
   ['Kleiner inhabergeführter Dienstleister','Wie wichtig sind einfache Organisation und persönliche Haftungsrisiken?','Jede kleine Firma sollte dieselbe Rechtsform wählen.'],
   ['Kapitalintensive Expansion','Wie lassen sich viele Kapitalgeber, übertragbare Anteile und professionelle Leitung organisieren?','Börsennotierung garantiert ausreichende Finanzierung.'],
   ['Konzentrierte Familienbeteiligung','Wie werden Kontrolle, Nachfolge und Minderheitenschutz geregelt?','Konzentriertes Eigentum ist immer gut oder immer schlecht.'],
   ['Privater institutioneller Investor','Welche Informationen, Zustimmungen und Exitwege stehen vertraglich zur Verfügung?','Ohne Börsenkurs ist keine sorgfältige Bewertung möglich.'],
   ['Staat als Anteilseigner','Wie wirken kommerzielle, politische und gesellschaftliche Ziele auf Entscheidungen?','Staatseigentum beseitigt jedes Ausfallrisiko.']
  ],'Die passende Struktur folgt aus konkreten Zielen und Einschränkungen.'),
  'Eine vollständige Beurteilung benennt schließlich den Rechtsträger, die persönliche Haftung, die Steuerbasis, den Empfänger neuer Finanzierungsmittel, sämtliche Eigentümer- und Stimmrechte sowie die spätere Verkaufsmöglichkeit. Wenn eine Information fehlt, wird ihre Wirkung als offene Annahme kenntlich gemacht. Erst danach ist ein Vergleich von Rendite, Risiko und Kontrolle belastbar.'
 ])
],related:[
 {unit:'balance-sheet',section:'measurement',label:'Rechtliche Ansprüche und Bilanzwerte auseinanderhalten'},
 {unit:'income-statement',section:'basic-eps',label:'Aktienzahl und Ergebnis je Aktie zeitlich richtig zuordnen'},
 {unit:'forecasting',section:'funding',label:'Kapitalbedarf bis zur Finanzierung verfolgen'},
 {unit:'ratios',section:'solvency',label:'Verschuldung und Zinsdeckung beurteilen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Corporate Finance, Lernziele',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=9'},
 {title:'CFA Institute: Organizational Forms, Corporate Issuer Features, and Ownership',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/organizational-forms-corporate-issuer-features-and-ownership'},
 {title:'U.S. Small Business Administration: Rechtsformen im US-Kontext',url:'https://www.sba.gov/counseling/launch-your-business/'},
 {title:'IRS: LLC und gesonderte steuerliche Klassifikation',url:'https://www.irs.gov/businesses/small-businesses-self-employed/limited-liability-company-llc'},
 {title:'GOV.UK: Private Limited Companies, Eigenständigkeit und Steuer',url:'https://www.gov.uk/limited-company-formation'},
 {title:'HMRC: General Partnership, Limited Partnership und LLP',url:'https://www.gov.uk/hmrc-internal-manuals/partnership-manual/pm131200'},
 {title:'SEC: Going Public, Voraussetzungen und Folgen',url:'https://www.sec.gov/resources-small-businesses/going-public'},
 {title:'SEC: IPO, SPAC und Direct Listing',url:'https://www.sec.gov/resources-small-businesses/capital-raising-building-blocks/types-registered-offerings'},
 {title:'SEC: Primary Direct Listings mit Kapitalaufnahme',url:'https://www.sec.gov/newsroom/speeches-statements/roisman-listings-2020-12-22'},
 {title:'SEC / Investor.gov: SPACs, Rückgaben und Verwässerung',url:'https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/what-you'},
 {title:'SEC: Unterschied zwischen Börsennotierung und Berichtspflichten',url:'https://www.sec.gov/resources-small-businesses/going-public/exchange-act-reporting-registration'}
],review:{status:'draft',date:'2026-09-26',note:'Eigene Fälle zu Haftung, mehrstufiger Steuer, Stimmrechten, fairer und unterbewerteter Ausgabe, IPO-Cash und Erwerbshebel. Globale Grundbegriffe werden von konkreten Rechts- und Steuerregeln getrennt. Numerische Gegenprüfungen und vollständiger Trainingsdurchlauf vorhanden; fachlicher Gesamtaudit bleibt offen.'}};
