const {F,T,X,S,G}=require('../author.cjs');
const pe=(roe,g,k=.1)=>(1-g/roe)/(k-g);
const pb=roe=>(roe-.03)/(.1-.03);
const ev=roic=>60*(1-.03/roic)/(.09-.03)/100;
module.exports={id:'multiples',intro:[
 'Ein Multiplikator macht Unternehmen unterschiedlicher Größe vergleichbar, indem er einen Preis oder Wert auf Gewinn, Buchkapital, Umsatz oder eine andere wirtschaftliche Bezugsgröße bezieht. Er verkürzt eine Bewertung, beseitigt aber ihre Annahmen nicht. Hinter einem KGV stehen Erwartungen über künftige Gewinne, ihre Verfügbarkeit, Wachstum und Risiko. Deshalb kann ein niedriger Quotient eine Gelegenheit, eine nachvollziehbare Risikoprämie oder eine vorübergehend überhöhte Gewinnbasis anzeigen.',
 'Dieses Kapitel behandelt die vier Lernziele der relativen Aktienbewertung für CFA Level I 2027. Eigene Fälle verbinden Vergleichsunternehmen, historisch und zukünftig abgegrenzte Daten, Anspruchsbrücken und fundamentale Herleitungen. Ergänzende Herleitungen, PEG, Mittelwertfragen und Endwertanwendungen vertiefen das Verständnis; die verlinkte öffentliche Level-II-Übersicht erweitert die Grundlage und ersetzt nicht die offizielle 2027-Level-I-Zuordnung.'
],sections:[
 S('scope','1. Was ein Multiplikator misst und was er offenlässt','a b',[
  F('m=\\frac{W}{Z},\\qquad W^*=m^*Z','Eine Wertgröße wird durch eine passende Bezugsgröße standardisiert. Ein begründet gewählter Multiplikator kann anschließend mit der entsprechenden Bezugsgröße des bewerteten Unternehmens multipliziert werden.',[['m','Beobachteter Multiplikator; ein Verhältnis, keine jährliche Rendite.'],['W','Definierter Marktpreis oder Marktwert des betrachteten Anspruchs.'],['Z','Zum Anspruch, Zeitraum, Rechnungslegungsumfang und zur Einheit passende Bezugsgröße.'],['m^*','Aus Vergleich oder Modell begründet gewählter Multiplikator.'],['W^*','Daraus geschätzter Wert desselben Anspruchs.']]),
  'Das Sternchen kennzeichnet eine Schätzung, keinen zweiten sicher beobachtbaren Preis. Ein Börsenkurs entsteht für einen konkreten handelbaren Anspruch. Ein Multiplikator aus Übernahmetransaktionen kann zusätzlich Kontrollrechte, Synergien, andere Marktbedingungen oder Gegenleistungen enthalten und ist nicht ohne Anpassung ein Vergleich für eine Minderheitsaktie.',
  X('Der Stückpreis ist keine Aussage über die Bewertung','Zwei identische wirtschaftliche Stammkapitalansprüche haben jeweils Gesamtmarktwert 100 und Jahresgewinn zehn. A hat zehn Aktien, B nach einem Aktiensplit zwanzig. Keine weiteren Änderungen.',[
   T(['Größe','A','B'],[['Aktienzahl','10','20'],['Preis je Aktie','10','5'],['Gewinn je Aktie','1','0,5'],['P/E','10','10']],'Der Split halbiert Preis und Gewinn je Aktie zugleich.'),
   F('m_{PE,A}=10/1=10,\\qquad m_{PE,B}=5/0{,}5=10','Die Stückelung verschiebt die beiden Beträge im selben Verhältnis.',[['m_{PE,A},m_{PE,B}','Preis-Gewinn-Verhältnisse der beiden Darstellungen.']])
  ],'Der niedrigere Stückpreis von B macht denselben Gesamtanspruch nicht günstiger.')
 ]),
 S('workflow','2. Zwei Bewertungswege und ihre unterschiedlichen Begründungen','a c d',[
  T(['Schritt','Method of Comparables','Method of Forecasted Fundamentals'],[['Datenbasis','Beobachtete Marktpreise geeigneter Vergleichsunternehmen.','Eigene Prognose der Vorteile, Kapitalbindung und Risiken.'],['Standardisierung','Für alle Peers dieselbe Multiplikatordefinition bilden.','Ein passendes Barwertmodell auf seine Bezugsgröße beziehen.'],['Begründung','Wirtschaftliche Unterschiede prüfen und den Vergleich begrenzen.','Cashflows, Wachstum, Kapitalrendite und Diskontsatz abstimmen.'],['Anwendung','Gewählten Vergleich auf die passende Größe des Zielunternehmens anwenden.','Fundamental gerechtfertigten Multiplikator mit derselben prognostizierten Größe verbinden.'],['Grenze','Eine ganze Vergleichsgruppe kann gemeinsam falsch bepreist sein.','Ein Modell kann trotz korrekter Algebra auf falschen Annahmen beruhen.']],'Beide Verfahren liefern bedingte Schätzungen. Die Basis ihres Multiplikators unterscheidet sich.'),
  'Bei Comparables ist etwa ein beobachtetes P/E von vierzehn eine Marktbeobachtung. Die Übertragung verlangt ähnliche ökonomische Eigenschaften und eine passende Gewinnperiode. Bei Forecasted Fundamentals wird der Quotient aus einem Zahlungsmodell hergeleitet. Ein justified P/E von vierzehn ist dann die Konsequenz dieses Modells, keine zusätzliche unabhängige Marktbestätigung.',
  'Eine belastbare Arbeitsschleife lautet: Anspruch und Stichtag definieren, Daten prüfen, Bezugsgröße normalisieren, geeignete Peers oder ein fundamentales Modell wählen, Unterschiede untersuchen und erst anschließend einen Wertbereich rechnen. Auswahlentscheidungen werden vor der gewünschten Schlussfolgerung festgelegt, damit ein Vergleich nicht nur passende teure Peers enthält.'
 ]),
 S('definitions','3. Preis- und Enterprise-Value-Multiplikatoren sauber unterscheiden','b',[
  F('m_{PE}=\\frac{P_0}{EPS}=\\frac{E_0}{NI},\\quad m_{PB}=\\frac{P_0}{BVPS}=\\frac{E_0}{B_0},\\quad m_{EV/EBITDA}=\\frac{EV_0}{EBITDA}','Die Gleichheit von Gesamt- und Pro-Aktie-Verhältnissen benötigt jeweils dieselbe Aktienbasis. Das EV-Verhältnis liegt auf einer umfassenderen Anspruchsebene.',[['P_0','Aktueller Preis je betrachteter Stammaktie.'],['EPS','Den betrachteten Stammaktionären zugeordneter Gewinn je Aktie der gewählten Periode.'],['E_0','Marktwert desselben Stammkapitals.'],['NI','Dessen Gewinn insgesamt.'],['BVPS,B_0','Buchwert je Aktie und gesamter zugehöriger Buchwert zum angegebenen Stichtag.'],['EV_0','Abgegrenzter Marktwert des operativen Geschäfts.'],['EBITDA','Passendes operatives Ergebnis vor Zinsen, Steuern und Abschreibungen.'],['m_{PE},m_{PB},m_{EV/EBITDA}','Jeweilige Multiplikatoren, gewöhnlich als x angegeben.']]),
  'Bei historischem EPS ist die gewichtete durchschnittliche Aktienzahl häufig anders als der heutige Bestand, mit dem die Marktkapitalisierung berechnet wird. Dann sind P/E und Marktkapitalisierung durch historischen Gewinn nicht mechanisch identisch. Basic und diluted EPS dürfen ebenfalls nicht stillschweigend vermischt werden. Datenanbieter können unterschiedliche Konventionen verwenden; ihr gleich klingender Kennzahlenname beweist keine gleiche Rechnung.',
  T(['Verhältnis','Wirtschaftlicher Fokus','Wichtige Einschränkung'],[['P/E','Preis des Stammkapitals relativ zu dessen Gewinn.','Gewinnqualität, Finanzierung, Aktienbasis und Verlustfälle.'],['P/B','Stammkapitalpreis relativ zu seinem Buchkapital.','Ansatzregeln, Wertminderungen und künftig erzielbarer ROE.'],['P/S','Eigenkapitalpreis relativ zu Umsatz je Aktie.','Umsatz ist vor vielen fremden Ansprüchen; Marge und Verschuldung sind besonders relevant.'],['EV/Sales','Operativer Gesamtwert relativ zu passendem konsolidiertem Umsatz.','Gleicher Umsatz erzeugt nicht automatisch gleichen freien Cashflow.'],['EV/EBIT oder EV/EBITDA','Operativer Wert relativ zu Ergebnis vor Finanzierungsverteilung.','Steuern, Ersatzinvestition, Kapitalbindung und Anspruchsbrücke.'],['P/Cash Flow','Preis relativ zu einer ausdrücklich benannten Cashflowdefinition.','CFO, Cash Earnings und FCFE sind verschiedene Größen.']],'Preis/Umsatz ist gebräuchlich, erfüllt aber nicht die strenge Gleichheit einer verbleibenden Eigentümerzahlung.'),
  'EV durch EPS mischt Gesamtwert und Stückbetrag sowie verschiedene Ansprüche. Derselbe umfassende EV durch nach Zinsen verbleibenden Stammgewinn ist ebenfalls keine passende Variante von P/E. EBITDA einer vollständig konsolidierten Tochter und EV ohne deren fremde Eigentümeranteile führen zu einer anderen Umfangsverletzung.'
 ]),
 S('periods','4. Trailing, aktuelle und zukünftige Gewinnbasis','a b d',[
  F('m_{PE,TTM}=\\frac{P_0}{EPS_{TTM}},\\qquad m_{PE,F}=\\frac{P_0}{\\widehat{EPS}_{NTM}}','Trailing P/E verwendet den zurückliegenden Zwölfmonatsgewinn. Forward P/E verwendet hier den prognostizierten Gewinn der nächsten zwölf Monate. Beide haben denselben heutigen Preis im Zähler.',[['P_0','Preis am heutigen Bewertungsstichtag.'],['EPS_{TTM}','Gewinn je Aktie der tatsächlich zurückliegenden zwölf Monate auf angegebener Aktienbasis.'],['\\widehat{EPS}_{NTM}','Geschätzter Gewinn je Aktie der nächsten zwölf Monate; Dach bedeutet Prognose.'],['m_{PE,TTM},m_{PE,F}','Historisches beziehungsweise hier definiertes zukünftiges P/E.']]),
  X('Ein niedrigeres Forward P/E ist noch keine Wertschaffung','Preis sechzig; vier vergangene Quartals-EPS von 0,6, 0,9, 1,1 und 1,4. Die Aktienbasis bleibt gleich und ist splitbereinigt. Prognose der nächsten zwölf Monate: EPS fünf.',[
   F('EPS_{TTM}=0{,}6+0{,}9+1{,}1+1{,}4=4,\\quad m_{PE,TTM}=60/4=15,\\quad m_{PE,F}=60/5=12','Nur der Nenner wechselt von beobachtetem zu erwartetem Gewinn. Der Preis ist unverändert.',[['EPS_{TTM}','Summe auf derselben Aktienbasis.'],['m_{PE,TTM},m_{PE,F}','Trailing und Forward P/E.']]),
   'Die erwartete Zunahme ist noch nicht verdient und kann bereits im Preis enthalten sein. Ein Peer mit Trailing P/E fünfzehn wird nicht unmittelbar mit dem Forward P/E zwölf des Zielunternehmens verglichen. Bei verändertem Aktienbestand werden zunächst Gewinnbeträge und die passende Aktienbasis rekonstruiert; die bloße Addition unterschiedlich gewichteter Quartals-EPS kann irreführen.'
  ],'Ein Vergleich benötigt für beide Unternehmen dieselbe periodische Definition.'),
  'Current kann den zuletzt abgeschlossenen Geschäftsjahresgewinn, eine aktuelle Jahresprognose oder annualisierte Zwischendaten meinen. Ein Halbjahres-EPS von 1,8 einfach zu verdoppeln ergibt eine Annahme von 3,6, keine bereits berichtete TTM-Größe. Saisonalität, Akquisitionen und Finanzierung begrenzen solche Hochrechnungen. Für Buchwert als Bestandsgröße wird dagegen ein konkret benannter Bilanzstichtag verwendet.'
 ]),
 S('calendar','5. Unterschiedliche Geschäftsjahre und historische Informationsstände','c d',[
  'FY1 ist das nächste oder aktuelle prognostizierte Geschäftsjahr nach Datenanbieterdefinition. NTM bezeichnet die nächsten zwölf Monate ab dem Bewertungsstichtag. Unternehmen mit unterschiedlichen Jahresenden haben bei derselben FY1-Bezeichnung möglicherweise andere Horizonte. Calendarization versucht, Größen auf gemeinsame Zeiträume zu beziehen; sie erzeugt keine bessere Prognosequalität.',
  X('Eine einfache Kalenderanpassung mit offener Annahme','Am Stichtag liegen noch drei Monate bis zum Geschäftsjahresende. EPS-Prognose des gesamten laufenden Geschäftsjahrs vier und des nächsten sechs. Aktienzahl konstant; Gewinne werden in diesem vereinfachten Fall gleichmäßig über jedes Geschäftsjahr erwirtschaftet.',[
   F('\\widehat{EPS}_{NTM}\\approx\\tfrac{3}{12}\\cdot4+\\tfrac{9}{12}\\cdot6=5{,}5','Die kommenden zwölf Monate enthalten drei Monate des ersten und neun Monate des zweiten Geschäftsjahrs.',[['\\widehat{EPS}_{NTM}','Hier zeitanteilig angenäherte Gewinnprognose.']]),
   'Bei einem Weihnachtsgeschäft ist diese Gewichtung nicht verlässlich: Die neun eingeschlossenen Monate können einen anderen Gewinnanteil als neun Zwölftel besitzen. Dann werden Quartale, Saisonmuster oder explizite Monatsprognosen benötigt. Ein Halbjahr alter Bilanzbuchwert und ein aktueller Preis erfordern außerdem eine Prüfung zwischenzeitlicher Ausschüttungen, Kapitalausgaben und Verluste.'
  ],'Die einfache Kalenderrechnung ist eine begrenzte Näherung mit benannter Saisonannahme.'),
  'Ein historischer Bewertungs- oder Strategietest darf nur damals verfügbare Berichte und Prognosen einsetzen. Der Gewinn des vergangenen Jahres wird oft erst nach Jahresende veröffentlicht. Heute restated Daten oder heute bekannte zukünftige Gewinne in einen alten Bewertungsstichtag einzusetzen erzeugt Look-ahead Bias. Eine historische Forward-Kennzahl benötigt die damals tatsächlich verfügbare Prognose, nicht den später realisierten Gewinn.'
 ]),
 S('normalization','6. Sondereffekte aus der dauerhaften Gewinnbasis abgrenzen','a b d',[
  F('NI_{norm}=NI_{reported}-G_{once}+L_{once},\\qquad EPS_{norm}=\\frac{NI_{norm}}{N}','Ein ausdrücklich nicht fortgesetzter Gewinn wird entfernt, ein entsprechend nicht fortgesetzter Verlust zurückgerechnet. Alle Anpassungen liegen hier bereits nach Steuern und gehören zum selben Stammkapital.',[['NI_{norm}','Geschätzter nachhaltiger normalisierter Gewinn.'],['NI_{reported}','Berichteter zurechenbarer Gewinn.'],['G_{once},L_{once}','Isolierte positive beziehungsweise negative nicht wiederkehrende Nachsteuereffekte.'],['N','Passende, im Beispiel unveränderte Aktienzahl.'],['EPS_{norm}','Normalisierter Gewinn je Aktie.']]),
  X('Ein Veräußerungsgewinn lässt eine Aktie nur rechnerisch billiger aussehen','Preis neunzig; berichteter Jahresgewinn hundert Millionen einschließlich eines isolierten Veräußerungsgewinns von vierzig nach Steuern; zehn Millionen Aktien konstant. Ein wirtschaftlich passender Vergleich verwendet vierzehnmal normalisierten Gewinn.',[
   F('EPS_{reported}=100/10=10,\\quad EPS_{norm}=(100-40)/10=6','Vierzig stammen im Fall aus einer nicht wiederholten Veräußerung.',[['EPS_{reported},EPS_{norm}','Berichteter und normalisierter Gewinn je Aktie.']]),
   F('m_{reported}=90/10=9,\\quad m_{norm}=90/6=15,\\quad v^*=14\\cdot6=84','Die Multiplikatordefinition und das Zielergebnis verwenden beide die bereinigte Gewinnbasis.',[['m_{reported},m_{norm}','Beobachtetes P/E auf jeweiliger Basis.'],['v^*','Vergleichswert je Aktie, unter den genannten Annahmen.']]),
   'Vierzehn mit zehn zu multiplizieren ergäbe 140 und würde einen Multiplikator für laufende Erträge auf eine andere Ertragsbasis anwenden. Der Erlös der Veräußerung ist trotzdem wirtschaftlich relevant: Verbleibende separate Mittel oder veräußerte künftige Erträge müssen im Gesamtmodell berücksichtigt werden. Die Bereinigung des Gewinns erlaubt kein pauschales Löschen tatsächlich vorhandener Vermögenswerte.'
  ],'Die beobachtete Neun erklärt sich hier durch einen außergewöhnlichen Nenner, nicht durch die nachhaltige Ertragskraft.'),
  'Normalisierung ist eine begründete Analystenschätzung. Restrukturierungen können regelmäßig wiederkehren, eine umstrittene Anpassung kann realen Aufwand verbergen und aktienbasierte Vergütung kann wirtschaftliche Kosten beziehungsweise Verwässerung erzeugen. Unternehmensseitig adjusted EPS wird deshalb auf Definition, Regelmäßigkeit und Folgeeffekte geprüft.'
 ]),
 S('cycle','7. Zyklische Gewinne benötigen einen vollständigen Vergleich','b c d',[
  F('\\overline{EPS}=\\frac{1}{n}\\sum_{j=1}^{n}EPS_j,\\qquad EPS_{norm}=\\overline{ROE}\\,BVPS_0','Zwei mögliche Normalisierungen verwenden entweder einen vollständigen Gewinnzyklus oder eine repräsentative Kapitalrendite auf heutiges Buchkapital. Sie sind keine automatisch gleichwertigen Schätzer.',[['\\overline{EPS}','Arithmetischer Durchschnitt repräsentativer, vergleichbar bereinigter Periodengewinne je Aktie.'],['n,j','Anzahl und Index der beobachteten Perioden.'],['EPS_j','Gewinn je Aktie in Periode j auf vergleichbarer Aktienbasis.'],['EPS_{norm}','Alternativ aus Kapitalrendite geschätzter normalisierter Gewinn je Aktie.'],['\\overline{ROE}','Begründete normale Rendite auf die hier gewählte Kapitalbasis.'],['BVPS_0','Aktueller passender Buchwert je Aktie.']]),
  X('Der billigste KGV-Wert kann am Höhepunkt des Zyklus liegen','Bei unverändertem Preis achtzig variieren Jahres-EPS eines eigenen Zyklusfalls zwischen zwei, vier und acht. Das Geschäft ist konjunkturabhängig; keine Aussage über tatsächlich konstante Börsenpreise über den Zyklus.',[
   T(['Gewinnzustand','EPS','P/E bei gleichem Preis'],[['Schwache Auslastung','2','40'],['Mittlere Auslastung','4','20'],['Hohe Auslastung','8','10']],'Der Preis wird gezielt festgehalten, um ausschließlich die Wirkung des Gewinnnenners zu zeigen.'),
   'Am Gewinnhoch ist der Quotient am kleinsten. Fallen die Gewinne anschließend wieder, war die Zehn kein sicherer Hinweis auf billige normale Erträge. Ein tatsächlich beobachteter Aktienpreis reagiert auf Erwartungen und kann den Gewinnzyklus vorwegnehmen.'
  ],'Eine niedrige zyklische Kennzahl kann eine vorübergehend hohe Auslastung anzeigen.'),
  X('Kapitalwachstum macht zwei Normalisierungen verschieden','Vier vergleichbare vergangene EPS: zwei, vier, sechs und acht. Ihr Durchschnitt ist fünf. Eine separat begründete normale Kapitalrendite von zehn Prozent auf den heutigen Buchwert je Aktie sechzig ergibt sechs. Preis neunzig.',[
   F('\\overline{EPS}=5,\\quad EPS_{norm}=0{,}10\\cdot60=6,\\quad 90/5=18,\\quad90/6=15','Der historische Durchschnitt und die Schätzung auf heutiger Kapitalbasis ergeben verschiedene Nenner.',[['\\overline{EPS},EPS_{norm}','Die beiden ausdrücklich verschiedenen Schätzgrößen.']]),
   'Bei gewachsenem Kapital kann ein reiner alter Gewinndurchschnitt die heutige Ertragsbasis unterschätzen. Umgekehrt macht heutiges Buchkapital eine historische Rendite nicht automatisch künftig erreichbar. Wettbewerbswandel, Überkapazität und wertlos gewordenes Kapital können die alte Rendite widerlegen.'
  ],'Die Wahl der Normalisierung folgt dem wirtschaftlichen Zustand, nicht dem gewünschten Aktienwert.')
 ]),
 S('pe-negative','8. Verluste, kleine Nenner und Earnings Yield','b',[
  F('y_E=\\frac{EPS}{P_0}=\\frac{1}{m_{PE}}\\quad(EPS\\ne0)','Earnings Yield kehrt die Preis-Gewinn-Relation um. Bei Preis größer null bleibt es auch für Verlust-EPS als negative Ergebnisrelation definiert; bei EPS null ist die direkte Ergebnisrendite null, während P/E nicht definiert ist.',[['y_E','Earnings Yield; Ergebnis relativ zum Preis, keine garantierte Anlagerendite.'],['EPS','Gewinn oder Verlust je Aktie der ausdrücklich gewählten Periode.'],['P_0','Positiver Preis je Aktie.'],['m_{PE}','P/E nur für einen von null verschiedenen Gewinnnenner.']]),
  T(['Preis','EPS','P/E','E/P','Interpretation'],[['40','−2','−20','−5 %','Größerer gegenwärtiger Verlust relativ zum Preis.'],['40','−0,5','−80','−1,25 %','Kleinerer gegenwärtiger Verlust; keine Begründung künftiger Erträge.'],['40','0','Nicht definiert','0 %','P/E hat einen Nullnenner.'],['40','0,1','400','0,25 %','Ein sehr kleiner positiver Gewinn macht P/E extrem hoch.']],'Negative P/E-Werte besitzen keine gewöhnliche Rangfolge günstiger positiver Gewinne.'),
  'Ein P/E von minus achtzig ist nicht deshalb besser oder schlechter als minus zwanzig, weil die Zahl kleiner oder größer erscheint. Die Verlustsituation, Finanzierung und künftige Ertragsfähigkeit müssen analysiert werden. E/P lässt die Vorzeichen und Nullgrenze übersichtlich sichtbar, ersetzt aber die Geschäftsprognose nicht.',
  'Nur in einem besonderen Modell ohne Wachstum, bei vollständiger dauerhafter Ausschüttung und passenden Risiken kann eine Ergebnisrendite der geforderten Eigentümerrendite entsprechen. Allgemein ist Gewinn weder Dividende noch freier Cashflow; eine Ergebnisrendite von fünf Prozent verspricht keine fünfprozentige Gesamtrendite.'
 ]),
 S('forward-pe','9. Das fundamental gerechtfertigte P/E aus dem DDM','a b d',[
  F('v_0=\\frac{D_1}{k_e-g}=\\frac{q\\,EPS_1}{k_e-g}\\quad\\Longrightarrow\\quad m^*_{PE,F}=\\frac{v_0}{EPS_1}=\\frac{q}{k_e-g}','Die Division des Gordon-Werts durch den nächsten Gewinn liefert den fundamental gerechtfertigten Forward-Multiplikator. Die zugrunde liegenden Dividenden wachsen dauerhaft mit g.',[['v_0','Geschätzter heutiger Wert je Aktie.'],['D_1','Erste Dividende nach dem Bewertungsstichtag.'],['q','Konstante Ausschüttungsquote D₁/EPS₁ im hier positiven Gewinnmodell.'],['EPS_1','Gewinn je Aktie der nächsten Jahresperiode.'],['k_e','Konstante angemessene Eigenkapitalkosten oberhalb der Wachstumsrate.'],['g','Langfristige Wachstumsrate des konsistenten Gewinn- und Dividendenmodells.'],['m^*_{PE,F}','Fundamental gerechtfertigtes Forward P/E.']]),
  F('EPS_1=EPS_0(1+g)\\quad\\Longrightarrow\\quad m^*_{PE,T}=\\frac{v_0}{EPS_0}=\\frac{q(1+g)}{k_e-g}=m^*_{PE,F}(1+g)','Wird dieselbe Schätzung auf den vergangenen statt den kommenden Gewinn bezogen, erhält sie einen anderen gerechtfertigten Multiplikator.',[['EPS_0,EPS_1','Vorheriger und nächster konsistent fortgeschriebener Gewinn je Aktie.'],['v_0','Derselbe heutige Modellwert.'],['q,k_e,g','Ausschüttungsquote, Eigenkapitalkosten und Wachstum.'],['m^*_{PE,T},m^*_{PE,F}','Gerechtfertigtes Trailing und Forward P/E in genau diesem Modell.']]),
  X('Zwei Multiplikatoren, ein Aktienwert','Letzter Gewinn je Aktie fünf; konstantes Wachstum vier Prozent; Ausschüttungsquote sechzig Prozent; Eigenkapitalkosten zehn Prozent. Einfache konstante Aktienzahl und dauerhafte Modellannahmen.',[
   F('EPS_1=5\\cdot1{,}04=5{,}2,\\quad D_1=0{,}6\\cdot5{,}2=3{,}12,\\quad v_0=3{,}12/0{,}06=52','Die nächste Dividende liefert den Gordon-Wert.',[['EPS_1,D_1','Nächster Gewinn und nächste Dividende je Aktie.'],['v_0','Heutiger Modellwert.']]),
   F('m^*_{PE,F}=0{,}6/0{,}06=10,\\quad m^*_{PE,T}=10\\cdot1{,}04=10{,}4,\\quad10\\cdot5{,}2=10{,}4\\cdot5=52','Beide Multiplikatoren stimmen mit ihrer jeweils richtigen Gewinnperiode überein.',[['m^*_{PE,F},m^*_{PE,T}','Die beiden fundamental begründeten Quotienten.']])
  ],'Zehn auf den alten Gewinn anzuwenden würde den Periodenwechsel übersehen.'),
  'Die Ableitung ist keine allgemeine Identität jedes beobachteten Markt-P/E. Bei mehrstufigem Wachstum wird zuerst der gesamte Dividenden- oder FCFE-Wert berechnet und anschließend durch die ausdrücklich definierte Gewinnbasis geteilt. Wird FCFE statt Dividende eingesetzt, steht die dazu passende Cashflow-Gewinn-Relation an Stelle der tatsächlichen Ausschüttungsquote.'
 ]),
 S('growth-pe','10. Wachstum kostet Kapital und verändert die Ausschüttung','a b c',[
  F('g=b\\rho,\\quad q=1-b=1-\\frac{g}{\\rho},\\quad m^*_{PE,F}=\\frac{1-g/\\rho}{k_e-g}','Bei konstantem ROE auf Anfangsbuchkapital, Clean Surplus, unverändertem Aktienbestand und ohne zusätzliche Eigentümertransaktionen bindet Wachstum einen Gewinnanteil. Ausschüttung und Wachstum sind deshalb nicht unabhängig.',[['g','Langfristiges Wachstum von Buchkapital, Gewinn und Dividende.'],['b,q','Einbehaltungs- und Ausschüttungsquote mit Summe eins.'],['\\rho','Konstanter ROE des Modells: nächster Gewinn relativ zu Anfangsbuchkapital.'],['k_e','Passende Eigenkapitalkosten größer als g.'],['m^*_{PE,F}','Gerechtfertigtes Forward P/E; hier positive Gewinne und 0 ≤ g < ρ.']]),
  F('\\frac{\\partial m^*_{PE,F}}{\\partial g}=\\frac{\\rho-k_e}{\\rho(k_e-g)^2}','Bei festgehaltener Kapitalrendite und Renditeforderung hängt das Vorzeichen der Wachstumswirkung von der Überrendite des zusätzlich gebundenen Kapitals ab.',[['m^*_{PE,F}','Gerechtfertigter nächster Gewinnmultiplikator.'],['g','Veränderte Wachstumsrate bei dazu angepasster Einbehaltung.'],['\\rho,k_e','Positive konstante Kapitalrendite und Eigenkapitalkosten.'],['\\partial','Partielle Änderung unter den angegebenen konstanten Größen.']]),
  T(['ROE bei kₑ = 10 %','g = 0 %','g = 2 %','g = 4 %'],[['6 %','10,0000','8,3333','5,5556'],['10 %','10,0000','10,0000','10,0000'],['15 %','10,0000','10,8333','12,2222']],'Alle Zellen beziehen sich auf den nächsten Gewinn. Höheres Wachstum erfordert jeweils mehr Einbehaltung.'),
  G({id:'pe-growth',title:'Mehr Wachstum rechtfertigt kein beliebig höheres KGV',caption:'Eigene stabile Modelle: kₑ = 10 %, Wachstum von null bis vier Prozent, jeweils konstantes Anfangsbuchwert-ROE. Einbehaltung wird mit g/ROE mitverändert.',reading:'Bei ROE oberhalb der Kosten steigen die gerechtfertigten Forward-Multiplikatoren; bei Gleichheit bleiben sie bei zehn; bei niedrigerem ROE sinken sie. Das ist eine kontrollierte Modellwirkung und keine beobachtete Börsenregel.',plot:{x:[0,4],y:[4,13],xTicks:[0,1,2,3,4],yTicks:[4,6,8,10,12],xLabel:'Stabiles Gewinnwachstum, Prozent',yLabel:'Gerechtfertigtes Forward P/E, x',series:[{name:'ROE 6 %',points:Array.from({length:41},(_,i)=>[i/10,pe(.06,i/1000)])},{name:'ROE 10 %',dash:true,points:Array.from({length:41},(_,i)=>[i/10,pe(.1,i/1000)])},{name:'ROE 15 %',points:Array.from({length:41},(_,i)=>[i/10,pe(.15,i/1000)])}]}}),
  X('Warum der erste Kurvenvergleich einen gleichen kommenden Gewinn braucht','Zwei Modellfälle besitzen denselben kommenden Gewinn eins und kₑ zehn Prozent. Bei ROE fünfzehn Prozent bedeutet Wachstum vier Prozent Einbehaltung von 26,6667 Prozent; bei ROE sechs Prozent benötigt dasselbe Wachstum 66,6667 Prozent.',[
   F('D_{1,A}=1(1-0{,}04/0{,}15)=0{,}733333,\\quad D_{1,B}=1(1-0{,}04/0{,}06)=0{,}333333','Das unproduktiver eingesetzte Kapital verbraucht mehr vom Gewinn für dieselbe Wachstumsrate.',[['D_{1,A},D_{1,B}','Erste Dividenden der beiden Modelle.']]),
   F('v_A=0{,}733333/0{,}06\\approx12{,}2222,\\quad v_B=0{,}333333/0{,}06\\approx5{,}5556','Gleicher kommender Gewinn und gleiches Wachstum erzeugen wegen verschiedener Kapitalbindung unterschiedliche Eigentümerwerte.',[['v_A,v_B','Werte je Aktie, hier zugleich Forward P/E bei EPS₁ eins.']]),
   'Mit gleich großem Ausgangsbuchkapital wäre auch der nächste Gewinn verschieden. Die Grafik hält bewusst den Gewinnnenner vergleichbar. Die Wirkung auf Gesamtwert bei festem Buchkapital wird im DCF-Kapitel separat hergeleitet.'
  ],'Ein Vergleich nur nach Gewinnwachstum übersieht, wie viel Kapital dieses Wachstum verbraucht.')
 ]),
 S('risk-pe','11. Risiko, Renditeforderung und scheinbare Billigkeit','a b c',[
  F('\\frac{\\partial m^*_{PE,F}}{\\partial k_e}=-\\frac{q}{(k_e-g)^2}<0','Bei positiver Ausschüttung und unverändertem Wachstum vermindert eine höhere passende Renditeforderung den gerechtfertigten Multiplikator.',[['m^*_{PE,F}','Gerechtfertigtes Forward P/E.'],['q','Positive konstant gehaltene Ausschüttungsquote.'],['k_e,g','Veränderliche Renditeforderung und festes Wachstum; die Renditeforderung bleibt größer.'],['\\partial','Partielle Änderung unter den genannten Bedingungen.']]),
  X('Gleiche Ertragsentwicklung, andere Risiken','Nächster EPS vier, Wachstum drei Prozent und ROE fünfzehn Prozent ergeben Ausschüttungsquote achtzig Prozent. Fall A hat kₑ neun, Fall B zwölf Prozent. Das sind kontrollierte Renditeannahmen, keine empirischen Schätzungen.',[
   F('m_A=0{,}8/(0{,}09-0{,}03)=13{,}3333,\\quad m_B=0{,}8/(0{,}12-0{,}03)=8{,}8889','Die höhere Renditeforderung von B macht denselben Gewinn- und Ausschüttungspfad heute weniger wert.',[['m_A,m_B','Gerechtfertigte Forward-Multiplikatoren.']]),
   F('v_A=13{,}3333\\cdot4\\approx53{,}3333,\\quad v_B=8{,}8889\\cdot4\\approx35{,}5556','Die Multiplikatordifferenz wird auf denselben kommenden Gewinn angewendet.',[['v_A,v_B','Werte je Aktie.']]),
   'Ein beobachteter Abschlag für B gegenüber A wäre im Modell wirtschaftlich nachvollziehbar. Ob ein realer Kursabschlag ausreichend oder übertrieben ist, hängt von den tatsächlich angemessenen Risikokosten und erwarteten Erträgen ab. Verschuldung, Kundenkonzentration, politische Risiken und schwache Finanzierungsreserven können solche Unterschiede erzeugen.'
  ],'Eine günstigere Quote bedeutet ohne Risikoabgleich keine kostenlose Zusatzrendite.')
 ]),
 S('peg','12. PEG und relative Kennzahlen: hilfreich, aber keine automatische Bereinigung','b c',[
  F('PEG=\\frac{m_{PE}}{100g_E},\\qquad m_{rel}=\\frac{m_{PE,firm}}{m_{PE,benchmark}}','Die übliche PEG-Konvention teilt P/E durch Gewinnwachstum als Prozentzahl, etwa zehn statt 0,10. Ein relatives P/E bezieht den Quotienten auf einen angegebenen Benchmark.',[['PEG','P/E-to-Growth-Ratio nach dieser ausdrücklich genannten Konvention.'],['m_{PE}','P/E auf angegebener Gewinnbasis.'],['g_E','Erwartete jährliche Gewinnwachstumsrate als Dezimalzahl; sinnvoller PEG-Vergleich hier nur bei positivem Wachstum.'],['m_{rel}','Relatives P/E.'],['m_{PE,firm},m_{PE,benchmark}','P/E des Unternehmens und eines gleich definierten Vergleichs.']]),
  X('Gleiches PEG, unterschiedliche wirtschaftliche Voraussetzungen','A hat P/E zwanzig und erwartetes Gewinnwachstum zehn Prozent; B hat P/E vierzig und Wachstum zwanzig Prozent. In beiden Fällen ist die Gewinnbasis positiv.',[
   F('PEG_A=20/10=2,\\qquad PEG_B=40/20=2','Die Quotienten stimmen rechnerisch überein.',[['PEG_A,PEG_B','PEG der beiden Unternehmen.']]),
   'Das beweist keine gleiche Angemessenheit. B kann höhere Kapitalkosten, geringere Cashflowverfügbarkeit, teurere Reinvestition oder eine kurze Hochwachstumsphase besitzen. P/E hängt nicht allgemein proportional von Wachstum ab. Ein dauerhaftes Wachstum von zwanzig Prozent ist außerdem ein anderes Modell als ein fünfjähriger Prognosezuwachs.'
  ],'PEG ist eine grobe Vergleichsrelation mit eigenen Annahmen.'),
  'PEG unter eins ist keine allgemeine Kaufregel. Bei Wachstum null ist die Quote nicht definiert; negative Gewinne oder negatives Wachstum zerstören die gewöhnliche Billigkeitsinterpretation. Auch ein relatives P/E von 0,8 kann eine dauerhaft niedrigere Rentabilität oder andere Sektorstruktur abbilden. Gleiche Benchmarkdefinition und wirtschaftlicher Abgleich bleiben erforderlich.'
 ]),
 S('pb','13. P/B: ein Buchwertabschlag benötigt eine ökonomische Erklärung','b c d',[
  X('Eine Buchwertänderung verändert die Kennzahl mechanisch','Stammkapitalmarktwert 120, Stammkapitalbuchwert hundert. Eine isolierte Wertminderung reduziert den Buchwert um zwanzig; für diese reine Kennzahlgegenprobe wird der Marktwert festgehalten. Keine Steuer- oder sonstigen Gegenposten im Fall.',[
   F('m_{PB,before}=120/100=1{,}2,\\qquad m_{PB,after}=120/80=1{,}5','Derselbe Zähler auf geringerem Buchkapital erzeugt einen höheren Quotienten.',[['m_{PB,before},m_{PB,after}','P/B vor und nach der angegebenen Buchwertanpassung.']]),
   'Das Unternehmen wurde durch die Buchung nicht automatisch produktiver oder teurer im wirtschaftlichen Sinn. Die Wertminderung kann gerade eine Verschlechterung offenlegen, auf die auch der Markt reagiert. Der konstant gehaltene Preis isoliert hier lediglich den Nennerkanal; er behauptet keine konstante reale Bewertung nach neuen Informationen.'
  ],'P/B wird gemeinsam mit Ansatzregeln, Kapitalqualität und erwarteter Rentabilität gelesen.'),
  'Buchkapital kann stabiler als ein zyklischer Jahresgewinn sein und bei bestimmten Finanzunternehmen eine sinnvolle Bezugsgröße darstellen. Bei Beratungs- oder Softwareunternehmen können intern aufgebaute Ressourcen teilweise nicht aktiviert sein. Abschreibungsalter, Goodwill, Rückkäufe und Wertminderungen beeinträchtigen den Vergleich. Ein sehr kleiner oder negativer Buchwert macht eine gewöhnliche positive P/B-Rangfolge problematisch.',
  'Tangible Book Value entfernt nach ausdrücklich definierten Regeln immaterielle Buchposten; dadurch wird nicht automatisch der ökonomische Wert von Technologie, Marken oder Kundenbeziehungen null. Ebenso ist Buchwert kein garantierter Rückzahlungs- oder Liquidationsbetrag.'
 ]),
 S('pb-fundamentals','14. P/B aus ROE, Wachstum und Residualgewinn herleiten','a b c',[
  F('EPS_1=\\rho BVPS_0,\\quad D_1=(1-g/\\rho)EPS_1\\quad\\Longrightarrow\\quad m^*_{PB}=\\frac{v_0}{BVPS_0}=\\frac{\\rho-g}{k_e-g}=1+\\frac{\\rho-k_e}{k_e-g}','Hier wird ROE als nächster Gewinn relativ zum heutigen Anfangsbuchkapital definiert. Division des konsistenten Dividendenwerts durch dieses Kapital zeigt den Wert der künftigen Überrenditen.',[['EPS_1,D_1','Nächster Gewinn und nächste Dividende je Aktie.'],['BVPS_0','Heutiges Anfangsbuchkapital je betrachteter Aktie.'],['\\rho','Konstanter prospektiver ROE auf Anfangsbuchkapital; nicht automatisch der historische Durchschnittsbuchwert-ROE.'],['g','Nichtnegative dauerhafte Wachstumsrate, kleiner als Kapitalrendite und Eigenkapitalkosten.'],['k_e','Konstante erforderliche Eigenkapitalrendite.'],['v_0,m^*_{PB}','Heutiger Modellwert und daraus gerechtfertigtes P/B.']]),
  X('Drei Kapitalrenditen auf dasselbe Buchkapital','Buchwert je Aktie zwanzig, kₑ zehn Prozent und stabiles Wachstum drei Prozent. Aktienbestand konstant, Clean Surplus und passende Einbehaltung gelten.',[
   T(['ROE','EPS₁','Einbehaltung g/ROE','D₁','Gerechtfertigtes P/B','Modellwert'],[['6 %','1,20','50 %','0,60','0,428571','8,5714'],['10 %','2,00','30 %','1,40','1,000000','20,0000'],['15 %','3,00','20 %','2,40','1,714286','34,2857']],'Der Barwert jeder ersten Dividende mit stabilem Wachstum ist D₁ geteilt durch sieben Prozent.'),
   'Im ersten Fall verdient das Kapital weniger als seine Kosten. Sein Buchwert wird deshalb im Modell unterschritten. Im mittleren Fall schaffen neue Investitionen keine Überrendite; Markt- und Buchwert stimmen unter genau diesen Annahmen überein. Im dritten Fall begründen dauerhafte Überschüsse eine Prämie.'
  ],'Ein Buchwertabschlag kann wirtschaftlich gerechtfertigt sein.'),
  G({id:'pb-roe',title:'Buchwertprämien folgen in diesem Modell der Kapitalüberrendite',caption:'Eigene stabile Modelle mit kₑ = 10 %, g = 3 % und konsistenter Einbehaltung. Die horizontale Referenz eins markiert Gleichheit von Modellwert und Buchwert.',reading:'Bei ROE zehn Prozent schneidet die Modellkurve P/B eins. Darunter liegt ein Abschlag, darüber eine Prämie. Bilanzierungsunterschiede und Änderungen künftiger Renditen sind hier bewusst ausgeschlossen.',plot:{x:[4,18],y:[0,2.3],xTicks:[4,6,10,14,18],yTicks:[0,.5,1,1.5,2],xLabel:'Prospektiver ROE auf Anfangsbuchwert, Prozent',yLabel:'Gerechtfertigtes P/B, x',series:[{name:'Modellwert/Buchwert',points:Array.from({length:57},(_,i)=>[4+i/4,pb((4+i/4)/100)])},{name:'Wert gleich Buchwert',dash:true,points:[[4,1],[18,1]]}]}}),
  'Die letzte Form der Formel verbindet direkt zum Residualgewinnmodell: Buchkapital bildet die Eins; zukünftige Gewinne über der Eigenkapitalbelastung begründen den Zusatzterm. Überrenditen für immer sind eine starke Annahme. Wettbewerb oder regulatorische Grenzen können sie abbauen; dann ist ein mehrstufiges Modell angemessener.'
 ]),
 S('ps','15. Umsatzmultiplikatoren brauchen Margen und Finanzierung','a b c',[
  F('m_{PS}=\\frac{E_0}{S}=\\frac{E_0}{NI}\\frac{NI}{S}=m_{PE}\\mu,\\qquad m^*_{PS,F}=\\frac{q\\mu_1}{k_e-g}','Bei identischem Perioden-, Konzern- und Stammkapitalumfang ist Preis/Umsatz gleich P/E mal Nettomarge. Die zweite Form setzt das oben definierte konstante Dividendenmodell ein.',[['m_{PS},m^*_{PS,F}','Beobachtetes beziehungsweise fundamental gerechtfertigtes Preis-Umsatz-Verhältnis.'],['E_0','Marktwert des angegebenen Stammkapitals.'],['S,NI','Passender Umsatz und den Stammaktionären zurechenbarer Gewinn derselben Periode.'],['m_{PE}','P/E auf eben dieser Gewinnbasis; algebraische Zerlegung setzt NI ungleich null voraus.'],['\\mu,\\mu_1','Nettomarge NI/S beziehungsweise erwartete nächste Nettomarge.'],['q,k_e,g','Passende Ausschüttungsquote, Renditeforderung und stabiles Wachstum.']]),
  X('Derselbe Umsatz bezahlt unterschiedliche Gewinne','Nächster Umsatz je Aktie zehn. A erzielt Nettomarge fünf, B fünfzehn Prozent. Für den isolierten Vergleich wird für beide ein wirtschaftlich begründetes Forward P/E von zwölf angenommen; Aktienbasis konstant.',[
   F('EPS_{1,A}=10\\cdot0{,}05=0{,}5,\\quad EPS_{1,B}=10\\cdot0{,}15=1{,}5,\\quad v_A=12\\cdot0{,}5=6,\\quad v_B=12\\cdot1{,}5=18','Derselbe Umsatz erzeugt bei anderer Marge dreimal so viel Eigentümergewinn.',[['EPS_{1,A},EPS_{1,B}','Nächste Gewinne je Aktie.'],['v_A,v_B','Vergleichswerte je Aktie.']]),
   F('m_{PS,A}=6/10=0{,}6,\\qquad m_{PS,B}=18/10=1{,}8','Das niedrigere Umsatzverhältnis passt hier zur niedrigeren Gewinnmarge.',[['m_{PS,A},m_{PS,B}','Indizierte Preis-Umsatz-Verhältnisse auf nächster Umsatzbasis.']])
  ],'Umsatz gleichzusetzen reicht für eine Wertübertragung nicht.'),
  'Umsatzgrößen können auch bei Verlusten nutzbar sein, weil ein noch negativer Gewinn keinen P/E-Vergleich erlaubt. Das verschiebt die entscheidende Frage zur künftig erreichbaren Marge und zum Kapitalverbrauch. Hohe Retouren, Netto- gegenüber Bruttoumsatz, durchlaufende Posten oder Plattform-GMV verlangen eine präzise Definition. Umsatz ist kein an die Stammaktionäre ausgeschütteter Betrag; P/S reagiert deshalb auch auf Finanzierung. EV/Sales reduziert diese unmittelbare Anspruchsmischung, benötigt aber weiterhin operative Marge, Steuern und Reinvestition.'
 ]),
 S('pcf','16. Cashflow-Multiplikatoren sind nur so klar wie ihre Definition','b d',[
  F('m_{P/CE}=\\frac{E_0}{NI+NCC},\\quad m_{P/CFO}=\\frac{E_0}{CFO},\\quad m_{P/FCFE}=\\frac{E_0}{FCFE}','Diese häufig verwendeten Kennzahlen haben verschiedene Nenner. Cash Earnings addiert hier nicht zahlungswirksame Aufwendungen, CFO enthält weitere operative Zahlungsanpassungen und FCFE zusätzlich Investition sowie passende Finanzierung.',[['E_0','Marktwert des gleichen betrachteten Stammkapitals.'],['NI','Zurechenbarer Gewinn.'],['NCC','Hier positive nicht zahlungswirksame Aufwendungen; andere nicht zahlungswirksame Effekte würden passend bereinigt.'],['CFO','Explizit klassifizierter operativer Cashflow.'],['FCFE','Passend abgegrenzter freier Eigenkapitalcashflow.'],['m_{P/CE},m_{P/CFO},m_{P/FCFE}','Multiplikatoren auf Cash Earnings, CFO und FCFE.']]),
  X('Drei Zahlen sind keine austauschbaren Cashflowbewertungen','Stammkapitalmarktwert 800 Millionen; Gewinn sechzig, Abschreibung zwanzig und Zunahme operativen Working Capital zehn. Zinsen sind in diesem Fall bereits im Gewinn und im operativen Cashflow enthalten. Anlagenzahlung dreißig, keine Nettokreditaufnahme oder weitere Ansprüche.',[
   F('CE=60+20=80,\\quad CFO=80-10=70,\\quad FCFE=70-30=40','Von der groben Gewinnbereinigung zum freien Cashflow werden zusätzlich gebundene Mittel sichtbar.',[['CE,CFO,FCFE','Cash Earnings, operativer Cashflow und freier Eigenkapitalcashflow in Millionen.']]),
   F('m_{P/CE}=800/80=10,\\quad m_{P/CFO}=800/70=11{,}4286,\\quad m_{P/FCFE}=800/40=20','Der Preis bleibt gleich; die immer enger abgegrenzte Mittelverfügbarkeit erklärt die verschiedenen Quotienten.',[['m_{P/CE},m_{P/CFO},m_{P/FCFE}','Drei eindeutig benannte Relationen.']])
  ],'Ein Peer mit zehnmal Cash Earnings ist kein direkter Vergleich für zwanzigmal FCFE.'),
  'CFO kann Zinsen oder Steuern je nach Rechnungslegung und Ausweis anders einordnen. Eine Equity-Relation verlangt entsprechende Normalisierung; die unbereinigte CFO-Kennzahl ist nicht automatisch ein an Eigentümer verfügbarer Zahlungsstrom. Ein verzögert bezahlter Lieferant kann aktuellen CFO erhöhen, ohne nachhaltigen Wert zu schaffen. FCFE kann wegen Investition oder Tilgung vorübergehend negativ sein; dann hilft auch sein Multiplikator nicht als gewöhnliche positive Vergleichsrangfolge.'
 ]),
 S('ev-bridge','17. Ein EV-Multiple muss bis zum gesuchten Stammaktienwert geführt werden','a b',[
  F('EV_0=E_0+D_0+Pref_0+NCI_0-C_0-I_0,\\qquad E_0^*=m_{EV}^*Z+C_0+I_0-D_0-Pref_0-NCI_0','Die hier verwendete Brücke entfernt separat bewertete nicht operative Werte und erfasst die Kapitalgeberansprüche des konsolidierten operativen Geschäfts. Bei einer Schätzung wird dieselbe Brücke umgekehrt.',[['EV_0','Abgegrenzter operativer Marktwert.'],['E_0,E_0^*','Beobachteter beziehungsweise geschätzter Stammkapitalwert der Mutter.'],['D_0','Passender Schuldmarktwert; weitere schuldähnliche Ansprüche werden ausdrücklich behandelt.'],['Pref_0','Marktwert separat abzugrenzender Vorzugsansprüche.'],['NCI_0','Passender Wert fremder Anteile an vollständig erfassten Tochtergesellschaften.'],['C_0,I_0','Separate überschüssige Kasse und nicht im operativen Wert enthaltene Anlagen.'],['m_{EV}^*,Z','Begründeter EV-Multiplikator und zugehörige operative Bezugsgröße.']]),
  X('Marktbeobachtung und geschätzter Anspruch im selben Unternehmen','Stammkapitalmarktwert 480 Millionen; Schulden zweihundert, Vorzüge zwanzig, passende NCI dreißig, überschüssige Kasse vierzig und separat bewertete Finanzanlage zehn. Forward EBITDA achtzig; zehn Millionen Stammaktien unverändert. Geeigneter Vergleichsmultiplikator neun.',[
   F('EV_0=480+200+20+30-40-10=680,\\qquad m_{EV/EBITDA,F}=680/80=8{,}5','Der beobachtete Multiplikator bezieht sich auf das umfassende operative Geschäft.',[['EV_0','Beobachteter operativer Wert in Millionen.'],['m_{EV/EBITDA,F}','Beobachtetes Forward EV/EBITDA.']]),
   F('EV_0^*=9\\cdot80=720,\\quad E_0^*=720+40+10-200-20-30=520,\\quad v_0^*=520/10=52','Der Vergleich ergibt zunächst 720 für das operative Geschäft und erst danach 52 je Stammaktie.',[['EV_0^*,E_0^*','Indizierter operativer und Stammkapitalwert in Millionen.'],['v_0^*','Indizierter Wert je Stammaktie.']]),
   '720 durch zehn zu teilen ergäbe 72 und ordnete fremde Ansprüche den Stammaktionären zu. Nur Schulden abzuziehen und Vorzüge sowie NCI auszulassen ergäbe 57. Kasse nochmals zusätzlich hinzuzufügen, obwohl sie bereits im definierten Ausgangswert enthalten wäre, würde ebenfalls doppelt zählen.'
  ],'Die passende Umfangs- und Anspruchsbrücke bleibt auch bei einer kurzen Multiplikatorrechnung erforderlich.')
 ]),
 S('leverage','18. Warum Finanzierung P/E stärker direkt verändert','b c',[
  X('Dasselbe operative Geschäft mit drei Finanzierungsmischungen','Ewiges steuerfreies Geschäft mit EBIT und operativem Cashflow sechzig, operativem Wert sechshundert und ohne Abschreibung oder Investitionsbedarf. Schulden kosten fünf Prozent, es gibt keine weitere Kasse oder Ansprüche. Nur die Schuldhöhe wird verändert.',[
   T(['Schuldmarktwert','Zinsen','Stammkapitalwert','Gewinn/FCFE','P/E','EV/EBIT'],[['0','0','600','60','10','10'],['200','10','400','50','8','10'],['400','20','200','40','5','10']],'Alle Werte folgen derselben steuerfreien Finanzierung und desselben operativen Geschäfts.'),
   F('E=600-D,\\quad NI=60-0{,}05D,\\quad m_{PE}=\\frac{600-D}{60-0{,}05D}','Zins und verbleibender Anspruch verändern das Equity-Verhältnis, obwohl der operative Wert unverändert bleibt.',[['E,D','Stammkapital- und Schuldmarktwert.'],['NI','Nach Zinsen verbleibender Gewinn, hier zugleich ewiger FCFE.'],['m_{PE}','P/E des jeweiligen Stammkapitals.']]),
   F('k_{e,0}=60/600=10\\%,\\quad k_{e,200}=50/400=12{,}5\\%,\\quad k_{e,400}=40/200=20\\%','In diesem abgestimmten Fall trägt der kleinere Restanspruch eine höhere erforderliche Rendite.',[['k_{e,0},k_{e,200},k_{e,400}','Konsistente Eigenkapitalrenditeforderungen bei den drei Schuldwerten.']]),
   'Die Fünf ist kein Beweis, dass das stärker verschuldete Geschäft halb so teuer ist wie das unverschuldete. Seine Stammaktionäre erhalten einen kleineren und riskanteren Restanspruch. EV/EBIT bleibt hier zehn, weil Finanzierung nur die Verteilung desselben operativen Geschäfts verändert.'
  ],'Ein Finanzierungsvorteil des EV-Vergleichs bedeutet nicht vollständige Unabhängigkeit von jeder Kapitalstrukturwirkung.'),
  'In realen Fällen ändern Steuervorteile, Finanzierungskosten, Insolvenzrisiko und operative Entscheidungen auch den Gesamtwert. EV-Multiplikatoren können diese wirtschaftlichen Folgen reflektieren. Banken und Versicherer haben zudem Schulden und Zinsgrößen als Teil ihres operativen Geschäfts; ein gewöhnliches Industrie-EV/EBITDA-Modell kann für sie unpassend sein.'
 ]),
 S('ebitda','19. EBIT, EBITDA und Umsatz drücken verschiedene Belastungen aus','b c',[
  F('EBIT=EBITDA-DA,\\qquad m_{EV/EBIT}=\\frac{m_{EV/EBITDA}}{1-DA/EBITDA}','Bei positivem EBIT und gleichem EV ist EV/EBIT höher als EV/EBITDA, wenn Abschreibungen positiv sind. Die Relation erklärt einen Nennerunterschied, keine zusätzliche Wertschaffung.',[['EBITDA,EBIT','Ergebnis vor beziehungsweise nach Abschreibungen, jeweils vor Zinsen und Steuern.'],['DA','Zum operativen Ergebnis passende Abschreibungen und Amortisationen.'],['m_{EV/EBIT},m_{EV/EBITDA}','Multiplikatoren auf dieselbe Periode und denselben operativen Umfang.']]),
  X('Der Quotient wechselt, obwohl der Unternehmenswert feststeht','EV achthundert; EBITDA hundert; Abschreibung zwanzig; Umsatz fünfhundert. Alle Größen haben denselben konsolidierten Umfang und dieselbe Jahresbasis.',[
   F('EBIT=100-20=80,\\quad m_{EV/EBITDA}=800/100=8,\\quad m_{EV/EBIT}=800/80=10,\\quad m_{EV/S}=800/500=1{,}6','Jeder Quotient standardisiert den gleichen Wert auf eine andere operative Größe.',[['EBIT','Gewinn vor Zinsen und Steuern.'],['m_{EV/EBITDA},m_{EV/EBIT},m_{EV/S}','Die drei operativen Multiplikatoren.']]),
   'Ein Peer mit EBITDA-Multiple acht und ein anderer mit EBIT-Multiple zehn sind hier keine verschiedenen Werturteile. EBITDA erleichtert einzelne Vergleiche unterschiedlich alter Anlagen, ignoriert aber ihren tatsächlichen Verbrauch. EBIT nimmt bilanziellen Verbrauch auf, hängt jedoch von Abschreibungsregeln und Ansatzentscheidungen ab.'
  ],'Der passende Nenner hängt von Branche, Kapitalintensität und Datenqualität ab.'),
  'EV/EBITDA kann bei positivem EBITDA trotz negativem EBIT oder Gewinn berechenbar bleiben. Damit verschwinden die Probleme nicht: Ein großer Ersatzbedarf, steigende Betriebskapitalbindung oder wirtschaftlich entwertete Anlagen können weiterhin die Eigentümerleistung stark belasten. Einheitliche Leasing- und Anpassungskonventionen müssen auch im EV und im EBITDA aufeinander abgestimmt sein.'
 ]),
 S('cash-investment','20. EBITDA ist kein freier Cashflow','b c',[
  F('FCFF_1=(EBITDA_1-DA_1)(1-\\tau)+DA_1-Capex_1-\\Delta WC_1','Nachsteuerlicher operativer Gewinn wird um nicht zahlungswirksamen Aufwand bereinigt und anschließend um tatsächliche Kapitalbindung vermindert.',[['FCFF_1','Erster freier operativer Cashflow vor Finanzierungsverteilung.'],['EBITDA_1,DA_1','Erster operativer Gewinn vor Abschreibungen und dessen Abschreibungen.'],['\\tau','Hier angemessen nutzbarer proportionaler Steuersatz.'],['Capex_1','Erste operative Anlagenzahlung.'],['\\Delta WC_1','Zusätzlich gebundenes operatives Working Capital, ohne Kasse und Finanzierung.']]),
  X('Gleiche EBITDA-Zahl, verschiedene Mittelverfügbarkeit','Im ersten Prognosejahr besitzen zwei Firmen EBITDA hundert, Abschreibung zwanzig, Steuersatz 25 Prozent und keine Working-Capital-Veränderung. A benötigt Anlagenzahlungen 32, B fünfzig. Für den stabilen Modellvergleich im folgenden Abschnitt wachsen die passenden Größen danach mit drei Prozent.',[
   F('NOPAT_1=(100-20)(1-0{,}25)=60,\\quad FCFF_{1,A}=60+20-32=48,\\quad FCFF_{1,B}=60+20-50=30','Unterschiedliche Nettoinvestition zwölf beziehungsweise dreißig lässt verschiedene freie Cashflows übrig.',[['NOPAT_1','Erster operativer Nachsteuergewinn.'],['FCFF_{1,A},FCFF_{1,B}','Erste frei verfügbare operative Mittel.']]),
   'Auf EBITDA allein sähen die Firmen gleich aus. Der größere Kapitalbedarf von B bindet aber achtzehn zusätzliche Einheiten. Keine dieser Investitionen wird durch Addition der Abschreibung zu Geld: Das Zurückrechnen eines Buchaufwands und die tatsächliche Anlagezahlung sind getrennte Schritte.'
  ],'Ein Cashflowvergleich braucht Steuern, Anlagen und Working Capital.')
 ]),
 S('ev-fundamentals','21. Das fundamental gerechtfertigte EV-Multiple','a b c d',[
  F('FCFF_1=NOPAT_1\\left(1-\\frac{g}{ROIC}\\right),\\qquad m^*_{EV/EBITDA,F}=\\frac{FCFF_1/EBITDA_1}{WACC-g}','Im konsistenten stabilen Modell bindet Gewinnwachstum einen Anteil g/ROIC des operativen Gewinns. Der freie Cashflow wird mit passenden Gesamtkapitalkosten bewertet und dann auf das nächste EBITDA bezogen.',[['FCFF_1','Erster freier operativer Cashflow.'],['NOPAT_1','Erster operativer Nachsteuergewinn.'],['g','Dauerhafte Wachstumsrate; hier kleiner als WACC und positiver ROIC.'],['ROIC','Konstante Rendite auf das zur Erzeugung des Gewinns gebundene Anfangskapital.'],['EBITDA_1','Nächster operativer Gewinn vor Abschreibungen.'],['WACC','Passende konstante Gesamtkapitalkosten.'],['m^*_{EV/EBITDA,F}','Gerechtfertigtes Forward EV/EBITDA.']]),
  X('Den EBITDA-Vergleich mit Kapitalrendite und Wachstum erklären','Fortsetzung: NOPAT sechzig und nächstes EBITDA hundert. A hat ROIC fünfzehn Prozent, B sechs Prozent; Wachstum drei und WACC neun Prozent in beiden Fällen. Die daraus nötige erste Nettoinvestition stimmt mit zwölf beziehungsweise dreißig aus dem vorherigen Abschnitt überein.',[
   F('IC_{0,A}=60/0{,}15=400,\\quad IC_{0,B}=60/0{,}06=1000,\\quad\\Delta IC_{1,A}=0{,}03\\cdot400=12,\\quad\\Delta IC_{1,B}=0{,}03\\cdot1000=30','Das weniger produktive Geschäft braucht für dieselbe Gewinnhöhe und dasselbe Wachstum mehr Kapital.',[['IC_{0,A},IC_{0,B}','Zum ersten NOPAT passende Anfangskapitalbeträge.'],['\\Delta IC_{1,A},\\Delta IC_{1,B}','Für Wachstum zusätzlich gebundenes Kapital.']]),
   F('EV_A^*=48/(0{,}09-0{,}03)=800,\\quad EV_B^*=30/0{,}06=500,\\quad m_A^*=8,\\quad m_B^*=5','Beide Werte verwenden eigene freie Mittel, gleichen Diskontsatz und gleiches Wachstum.',[['EV_A^*,EV_B^*','Operative Modellwerte.'],['m_A^*,m_B^*','Deren Forward EBITDA-Multiplikatoren.']]),
   'Ohne weitere Wachstumsinvestitionen würde der eigene Vergleich mit unverändertem NOPAT sechzig und vollständiger Verfügbarkeit einen operativen Wert von 666,67 ergeben. Das Wachstum von A erhöht den Wert gegenüber diesem Vergleich, das von B vermindert ihn. Der gemeinsame Wachstumsprozentsatz begründet daher keinen gleichen EBITDA-Multiplikator.'
  ],'Eine niedrigere Quote kann zu niedrigerer Kapitalproduktivität passen.'),
  G({id:'ev-roic',title:'Kapitalproduktivität erklärt Unterschiede trotz gleichem EBITDA',caption:'Eigene stabile Modelle: EBITDA₁ = 100, NOPAT₁ = 60, Wachstum 3 %, WACC 9 %. Der ROIC verändert den Reinvestitionsbedarf und damit FCFF₁.',reading:'Von ROIC vier bis achtzehn Prozent steigt der gerechtfertigte EBITDA-Multiplikator, weil für denselben Gewinnzuwachs weniger Kapital gebunden werden muss. Alle Punkte setzen ROIC über Wachstum voraus; die Grafik ist kein empirischer Branchenvergleich.',plot:{x:[4,18],y:[2,9],xTicks:[4,6,9,12,15,18],yTicks:[2,4,6,8],xLabel:'ROIC auf Anfangskapital, Prozent',yLabel:'Gerechtfertigtes Forward EV/EBITDA, x',series:[{name:'FCFF-Modell mit Reinvestition',points:Array.from({length:57},(_,i)=>[4+i/4,ev((4+i/4)/100)])}]}}),
  'Konstante ROIC- und Wachstumsannahmen können nur für einen erklärten wirtschaftlichen Zustand gelten. Zusätzliche Effizienz, einmalige Freisetzung gebundenen Kapitals und endliche Wachstumsphasen erfordern gesonderte Prognosen. Ein beobachtetes EV-Multiple erlaubt deshalb keine eindeutige Rückrechnung auf nur eine Wachstumsrate ohne die übrigen Annahmen.'
 ]),
 S('peers','22. Eine Vergleichsgruppe nach wirtschaftlichen Treibern aufbauen','a c',[
  'Eine Branchenklassifikation liefert einen sinnvollen Ausgangspunkt: Produkte, Kunden, Regulierung und Kosten reagieren oft auf verwandte Bedingungen. Trotzdem können eine reife Vertragsfirma und ein stark fremdfinanzierter Neuling derselben Branche ganz andere Gewinne, Risiken und Investitionen besitzen. Andere Branchen können für einzelne Treiber ähnlich sein, bringen aber neue Unterschiede mit. Ein vollkommen identischer Peer existiert selten.',
  T(['Treiber','Warum er den Vergleich verändert','Was konkret abgleichen'],[['Wachstum und Dauer','Spätere Erträge und nötige Kapitalbindung.','Kurzfristiger Zuwachs gegenüber langlebigem stabilem Zustand.'],['Risiko und Finanzierung','Erforderliche Rendite und Restanspruch.','Schulden, Liquidität, Geschäfts- und Länderrisiko.'],['Rentabilität','Gewinn je Umsatz oder eingesetztem Kapital.','Bereinigte Marge, ROE und ROIC auf vergleichbarer Basis.'],['Investition','Gleicher Gewinn kann unterschiedlich viel freies Geld lassen.','Ersatz, Wachstum, Working Capital und Kapitalumschlag.'],['Rechnungslegung und Umfang','Gleich benannte Nenner können etwas anderes messen.','Leasing, Entwicklungskosten, Konsolidierung, Sonderposten und Aktienrechte.'],['Zeit und Handel','Marktbedingungen und erwartete Perioden müssen passen.','Preisdatum, Veröffentlichungsstand, Prognosehorizont und Liquidität.']],'Peer-Auswahl und Anpassungen werden begründet dokumentiert.'),
  X('Gleiche Branche, unterschiedlich passende Forward-P/E-Peers','Das Zielunternehmen wird für einen stabilen Zustand mit ROE fünfzehn, Wachstum drei und kₑ zehn Prozent untersucht. Nächster EPS vier. Die folgenden Multiplikatoren sind eigene illustrative Marktbeobachtungen, keine echten Börsendaten.',[
   T(['Peer','ROE','g','kₑ','Beobachtetes Forward P/E','Bewertungsrelevanter Unterschied'],[['A','15 %','3 %','10 %','11,5','Treiber sind näher am Zielfall.'],['B','15 %','3 %','12 %','9,0','Höhere Risikokosten.'],['C','8 %','3 %','10 %','8,9','Mehr Gewinn muss für dasselbe Wachstum einbehalten werden.'],['D','15 %','5 %','10 %','13,3','Höheres Wachstum und andere Einbehaltung.']],'Der einfache Branchendurchschnitt würde die verschiedenen wirtschaftlichen Fälle vermischen.'),
   F('m^*_{target}=\\frac{1-0{,}03/0{,}15}{0{,}10-0{,}03}=11{,}4286,\\qquad v^*_{target}=11{,}4286\\cdot4=45{,}7143','Das fundamentale Modell erklärt hier, warum A ein näherer Vergleich ist. Sein beobachtetes 11,5 bleibt eine getrennte Marktgröße.',[['m^*_{target},v^*_{target}','Fundamentaler Multiplikator und Wert des Zielmodells.']]),
   'A allein wäre noch keine robuste reale Vergleichsgruppe. Auch Ergebnisqualität, Haltbarkeit der Überrendite, Geschäftsmodell und Handelbarkeit sind abzugleichen. Man kann B oder D mit begründeten Risiko- beziehungsweise Wachstumsanpassungen einbeziehen; das ist anspruchsvoller als ihr P/E pauschal zu mitteln.'
  ],'Branchenzugehörigkeit organisiert die Suche; die Werttreiber begründen die Übertragung.'),
  'Regressionsmodelle können Preisrelationen mit mehreren Treibern verknüpfen. Das ist eine ergänzende Methode und keine Level-I-Rechenpflicht dieses Moduls. Form, Stichprobe, Ausreißer, Kollinearität und Prognosebereich bestimmen ihre Grenzen. Ein hohes R² beweist weder kausale Interpretation noch richtige zukünftige Bewertung. Die unabhängigen Variablen müssen für OLS nicht sämtlich untereinander unkorreliert sein; perfekte lineare Abhängigkeit verhindert aber eine eindeutige getrennte Schätzung.'
 ]),
 S('summary','23. Mittelwert, Median und harmonischer Vergleich','a b c',[
  F('\\overline m_A=\\frac{1}{n}\\sum_{i=1}^{n}m_i,\\quad m_{med}=\\operatorname{median}(m_1,\\ldots,m_n),\\quad\\overline m_H=\\frac{n}{\\sum_{i=1}^{n}1/m_i}','Arithmetisches Mittel, Median und harmonisches Mittel fassen dieselbe Gruppe anders zusammen. Die übliche Interpretation des harmonischen Vergleichs setzt hier positive Multiplikatoren voraus.',[['\\overline m_A,m_{med},\\overline m_H','Arithmetischer Durchschnitt, Median und harmonischer Durchschnitt.'],['m_i','Gleich definierter positiver Multiplikator des Peers i.'],['n,i','Anzahl und Index der Peers.'],['\\operatorname{median}','Mittlere geordnete Beobachtung; bei gerader Zahl Mittel der beiden mittleren Werte.']]),
  X('Ein extremer P/E-Nenner verschiebt die Zusammenfassung','Drei ansonsten für diese reine Rechengegenprobe gleich behandelte positive P/E-Werte: zehn, zwanzig und sechzig. Jeder wird auf derselben Gewinnbasis berechnet.',[
   F('\\overline m_A=(10+20+60)/3=30,\\quad m_{med}=20,\\quad\\overline m_H=3/(1/10+1/20+1/60)=18','Der große Quotient beeinflusst das arithmetische Mittel stärker.',[['\\overline m_A,m_{med},\\overline m_H','Die drei Zusammenfassungen.']]),
   F('E_{total}=3\\cdot60=180,\\quad NI_{total}=60/10+60/20+60/60=10,\\quad E_{total}/NI_{total}=18','Eine gleich große Geldanlage von sechzig in jeden Peer kauft Gewinnansprüche von sechs, drei und eins. Ihr aggregiertes P/E ist das harmonische Mittel.',[['E_{total}','Gesamte Anlage in dieser Rechengegenprobe.'],['NI_{total}','Dazugehöriger proportional erworbener Jahresgewinnanspruch.']]),
   'Die erworbenen Gewinne werden nicht automatisch als Dividenden ausgezahlt. Die Rechnung erklärt nur die Gewichtung. Ein Median ist robust gegenüber einzelnen Extremwerten, aber nicht gegenüber einer wirtschaftlich ungeeigneten ganzen Gruppe. Ein harmonischer Mittelwert ist ebenfalls kein universell richtigerer Wert.'
  ],'Die Zusammenfassung soll zur Frage und zur Gewichtung passen.'),
  'Eine Ausschlussregel muss wirtschaftlich begründet sein. Verlustfirmen nur zu entfernen und dann den verbleibenden Median als ganze Branche darzustellen kann Selection Bias erzeugen. Ungewöhnlich hohe Multiples können auf fast verschwundene Gewinne, aber auch auf andere Wachstumsperspektiven zurückgehen. Erst wird die Ursache untersucht, danach ein transparenter Umgang festgelegt.'
 ]),
 S('aggregate','24. Aggregiertes P/E und gewichtetes harmonisches Mittel','b c',[
  F('m_{agg}=\\frac{\\sum_i E_i}{\\sum_i NI_i}=\\frac{1}{\\sum_i w_i/m_i},\\qquad w_i=\\frac{E_i}{\\sum_jE_j}','Wenn alle Gewinne und Werte passend definiert und positiv sind, entspricht das Verhältnis der aggregierten Werte einem mit Kapitalmarktwerten gewichteten harmonischen P/E.',[['m_{agg}','Verhältnis der gesamten Marktwerte zu den gesamten entsprechenden Gewinnen.'],['E_i,NI_i','Stammkapitalmarktwert und gleich abgegrenzter Gewinn des Unternehmens i.'],['m_i','Sein P/E als Eᵢ/NIᵢ.'],['w_i','Marktwertgewicht mit Summe eins.'],['i,j','Summationsindizes der Vergleichsgruppe.']]),
  X('Gewichtete und ungewichtete Gruppenwerte unterscheiden sich','A hat Stammkapitalwert hundert und Gewinn zehn, B Stammkapitalwert sechshundert und Gewinn zwanzig. P/E zehn beziehungsweise dreißig; identische Gewinnperioden.',[
   F('m_{agg}=(100+600)/(10+20)=23{,}3333','Der gesamte Wert kauft hier den gesamten ausgewiesenen Gewinnanspruch.',[['m_{agg}','Aggregiertes P/E.']]),
   F('w_A=1/7,\\quad w_B=6/7,\\quad m_{H,w}=\\frac{1}{(1/7)/10+(6/7)/30}=23{,}3333','Die Marktwertgewichtung reproduziert das Aggregat.',[['w_A,w_B','Marktwertgewichte der beiden Unternehmen.'],['m_{H,w}','Marktwertgewichtetes harmonisches P/E.']]),
   F('m_{A,w}=(1/7)10+(6/7)30=27{,}1429,\\qquad m_{H,equal}=2/(1/10+1/30)=15','Ein gewichtetes arithmetisches und ein gleich gewichtetes harmonisches Mittel beantworten andere Fragen.',[['m_{A,w}','Marktwertgewichteter arithmetischer Durchschnitt.'],['m_{H,equal}','Harmonischer Durchschnitt bei gleichen Geldgewichten.']])
  ],'Ein Datenanbieterwert muss zusammen mit seinen Gewichten verstanden werden.'),
  'Bei negativen Einzelgewinnen lässt sich ein Gesamtwert durch einen eventuell noch positiven Gesamtgewinn weiterhin direkt ausrechnen. Seine wirtschaftliche Aussage erfordert aber eine Prüfung der Verlustbeiträge und des Gesamtzustands. Die gewöhnliche positive harmonische Vergleichsinterpretation darf nicht unbesehen auf Vorzeichenmischungen übertragen werden.'
 ]),
 S('accounting','25. Rechnungslegung, Konsolidierung und Währung abgleichen','b c d',[
  'Eine Entwicklungszahlung, die ein Unternehmen aufwandswirksam erfasst und ein anderes aktiviert, kann Gewinn, Buchwert und Abschreibung gleichzeitig verändern. Das macht eine isolierte P/E-Bereinigung unvollständig: spätere Amortisation und gebundenes Kapital gehören ebenfalls zur Vergleichsbasis. Unterschiede werden anhand tatsächlicher Regeln und Anhangangaben analysiert, nicht allein anhand des Landesnamens.',
  T(['Problem','Auswirkung','Begründete Gegenprobe'],[['Leasing','Schulden, Abschreibung, Zins und operative Ergebnisdarstellung verändern sich.','Ansprüche und Ergebnisgrößen nach derselben Konvention behandeln.'],['NCI und Konsolidierung','Vollständiger Tochterumsatz trifft sonst auf einen nur teilweisen Wertanspruch.','Vollständig konsolidierte operative Größen mit passenden fremden Tochteranteilen im EV abstimmen.'],['Zeitgewichtete Aktienzahl','Aktueller Preis und historischer Gesamtgewinn können eine andere Anzahl verwenden.','Pro-Aktie- und Gesamtwertrelation getrennt nachvollziehen.'],['Währung','Gemischte Einheiten verfälschen Quotienten.','Zähler und Nenner auf passende gemeinsame Währungs- und Periodenbasis bringen.'],['Adjusted Kennzahlen','Wiederkehrende Kosten können ausgeschlossen werden.','Definition, Nachsteuereffekt und vollständige Folgeeffekte erklären.']],'Ein formal dimensionsloser Quotient ist nicht gegen uneinheitliche Ausgangsdaten immun.'),
  X('Gleiche Währungsumrechnung verändert den Quotienten nicht','Ein Marktwert von zweihundert und ein Jahresgewinn zehn sind auf konsistenter Basis in derselben Währung angegeben. Für eine reine Einheitengegenprobe werden beide mit dem festen Faktor 1,2 in eine andere Währung übertragen.',[
   F('m_{PE}=200/10=20,\\qquad m_{PE,converted}=240/12=20','Eine einheitliche Einheitenumrechnung lässt das Verhältnis gleich.',[['m_{PE},m_{PE,converted}','Quotient vor und nach derselben festen Umrechnung.']]),
   'Im echten Bericht kann der Gewinn mit periodischen Durchschnittskursen und der Marktwert mit einem Stichtagskurs übersetzt sein. Dann wirkt nicht bloß ein gemeinsamer Faktor. Inflations-, Wechselkurs- und Geschäftsänderungen können außerdem die ökonomischen Treiber verändern.'
  ],'Gleiche Einheiten sind notwendig; gleiche Einheiten allein beweisen keine wirtschaftliche Vergleichbarkeit.')
 ]),
 S('terminal','26. Multiplikatoren auf zukünftige Werte beziehen','a b d',[
  F('v_T=m^*_{PE,T,trail}EPS_T=m^*_{PE,T,forward}EPS_{T+1},\\qquad v_0=\\sum_{t=1}^{T}\\frac{D_t}{(1+k_e)^t}+\\frac{v_T}{(1+k_e)^T}','Ein zukünftiger Terminalpreis benötigt einen Multiplikator mit dazu passender Gewinnperiode. Anschließend wird dieser zukünftige Wert zusammen mit Detaildividenden auf heute abgezinst.',[['v_T','Wert am Ende von T nach der letzten ausdrücklich erfassten Dividende.'],['m^*_{PE,T,trail},m^*_{PE,T,forward}','Am Termin T begründetes Trailing beziehungsweise Forward P/E.'],['EPS_T,EPS_{T+1}','Gewinn der letzten Detailperiode beziehungsweise der ersten nachfolgenden Periode.'],['v_0','Heutiger Modellwert.'],['D_t','Dividende am Ende der Detailperiode t.'],['k_e','Hier konstanter passender Eigenkapitalsatz.'],['t,T','Zahlungsindex und Detailhorizont.']]),
  X('Ein Forward-Endmultiple gehört zur ersten folgenden Gewinnperiode','In jedem der drei nächsten Jahre Dividende zwei. EPS im dritten Jahr fünf, im vierten 5,2. Nach der dritten Dividende wird ein begründetes Forward P/E von vierzehn für den dann verbleibenden Anspruch angesetzt; kₑ zehn Prozent.',[
   F('v_3=14\\cdot5{,}2=72{,}8,\\qquad m^*_{PE,3,trail}=72{,}8/5=14{,}56','Der äquivalente Trailing-Multiplikator ist nicht dieselbe Vierzehn, weil die Gewinnbasis wechselt.',[['v_3','Verbleibender Wert in Jahr drei.'],['m^*_{PE,3,trail}','Dazu passendes Trailing P/E am selben Termin.']]),
   F('v_0=2/1{,}1+2/1{,}1^2+(2+72{,}8)/1{,}1^3=59{,}6694','Die dritte Dividende ist noch nicht im nach Zahlung gemessenen Terminalpreis enthalten und bleibt deshalb zusätzlich erforderlich.',[['v_0','Heutiger Wert je Aktie.']]),
   'Vierzehn auf EPS₃ fünf anzuwenden ergäbe Terminalwert siebzig und heutigen Wert etwa 57,57. Das wäre eine andere Terminalannahme. Den richtigen 72,8 ungezinst zu heute hinzuzufügen würde den Zeitwert missachten. Ein heute beobachteter Hochwachstums-Peer-Multiplikator ist zudem nicht automatisch für ein zukünftig reifes Unternehmen passend.'
  ],'Ein kurzer Endmultiple ersetzt die Begründung des zukünftigen wirtschaftlichen Zustands nicht.'),
  'Für eine zukünftige EV-Bewertung wird das entsprechende zukünftige EBIT, EBITDA oder Umsatz verwendet und der Wert mit zum operativen Anspruch passenden Sätzen diskontiert. Die Brücke zu Eigenkapital muss Ansprüche und Zahlungszeitpunkt konsistent behandeln. Gegenwärtige und zukünftige Schuldenwerte dürfen nicht ohne Finanzierungsplanung gemischt werden.'
 ]),
 S('integrated','27. Ein vollständiger Vergleich mit Sensitivität und Gegenmodell','a b c d',[
  X('Vom Peer-Universum zur nachvollziehbaren Aussage','Das Unternehmen aus der EV-Brücke hat Preis achtundvierzig, zehn Millionen Aktien, Forward EBITDA achtzig und normalisierten kommenden Stammgewinn vierzig Millionen. Schulden zweihundert, Vorzüge zwanzig, NCI dreißig, überschüssige Kasse vierzig und separate Anlage zehn bleiben auf heute konsistenter Basis. Drei nach wirtschaftlicher Prüfung geeignete Peers haben Forward EV/EBITDA acht, neun und zehn.',[
   T(['Begründeter Vergleich','Operativer Wert','Stammkapitalwert','Wert je Aktie'],[['8 × EBITDA','640','440','44'],['9 × EBITDA','720','520','52'],['10 × EBITDA','800','600','60']],'Die Anspruchsbrücke beträgt in jedem Fall netto minus zweihundert Millionen. Der Wertbereich ist kein statistisches Konfidenzintervall.'),
   F('EPS_1=40/10=4,\\quad m_{PE,F}=48/4=12,\\quad m^*_{PE,F}=52/4=13','Der beobachtete Preis und der mittlere EV-Vergleich entsprechen hier verschiedenen Forward-P/E-Relationen.',[['EPS_1','Normalisierter nächster Gewinn je Aktie.'],['m_{PE,F}','Beobachtetes Forward P/E.'],['m^*_{PE,F}','P/E, das mit dem mittleren indizierten Wert vereinbar wäre; keine zusätzlich unabhängig bewiesene Schätzung.']]),
   'Ein unabhängig geprüfter passender P/E-Vergleich von dreizehn könnte ebenfalls 52 ergeben. Wenn beide Verfahren dieselben Umsatz-, Margen- und Finanzierungsschätzungen verwenden, können sie jedoch denselben Fehler teilen. Ihre Übereinstimmung begründet keine Sicherheit. Ein DCF-Gegenmodell sollte prüfen, welche Mittel nach dem benötigten Kapitalaufbau tatsächlich für Eigentümer verfügbar werden.',
   'Gegen den heutigen Preis 48 liefert das untere Szenario 44 keinen positiven Bewertungsabstand. Das mittlere 52 liefert etwa 8,33 Prozent Abstand relativ zum Preis. Dieser modellierte Abstand ist keine sichere Rendite; insbesondere Prognosequalität, Anpassungsbedarf und mögliche Transaktionskosten beeinflussen die Aussage.'
  ],'Das Ergebnis ist ein begründeter bedingter Bereich mit offen gelegten Werttreibern.'),
  'Eine Veränderung des Multiplikators um eins verschiebt hier den operativen Wert um achtzig Millionen und den Aktienwert um acht. Ein größeres EBITDA infolge einer dauerhaft besseren Marge ist wirtschaftlich anders als ein höheres EBITDA durch einen ausgelassenen echten Kostenposten. Sensitivität zeigt rechnerische Wirkung; Analyse entscheidet, welche Eingabe vertretbar ist.'
 ]),
 S('review','28. Gegenfragen für Prüfung und eigene Bewertung','a b c d',[
  T(['Frage','Zu erklärender Zusammenhang'],[['Warum kann ein niedriger KGV-Wert am Zyklushöhepunkt entstehen?','Preis geteilt durch vorübergehend sehr hohen Gewinn.'],['Warum kann mehr Wachstum einen gerechtfertigten Multiplikator senken?','Kapitalbindung bei Rendite unter den passenden Kosten.'],['Warum sind zwei gleiche PEG-Werte nicht gleichwertig?','Risiko, Ausschüttung und Wachstumsdauer bleiben verschieden.'],['Warum kann P/B unter eins sachgerecht sein?','Künftiger ROE liegt im konsistenten Modell unter Eigenkapitalkosten.'],['Warum brauchen Umsatzverhältnisse eine Margenanalyse?','Umsatz ist noch kein Gewinn oder verfügbarer Eigentümerbetrag.'],['Warum verändert Verschuldung das P/E?','Zins, Eigenkapitalwert und Risiko des Restanspruchs ändern sich.'],['Warum ist EV/EBITDA keine Cashflowabkürzung?','Steuern und benötigte Investitionen fehlen.'],['Warum stimmt ein durchschnittliches P/E nicht zwingend mit dem Gruppen-P/E überein?','Quotienten und aggregierte Ansprüche werden unterschiedlich gewichtet.'],['Warum kann ein alter Bericht im historischen Test unzulässig sein?','Er kann am angenommenen Stichtag noch nicht veröffentlicht gewesen sein.'],['Warum gehört ein Forward-Terminalmultiple auf EPSₜ₊₁?','Sein Nenner liegt nach dem zukünftigen Bewertungsstichtag.']],'Eigene Trainingsfragen prüfen Berechnung, Begründung, Modellwahl und Fehlersuche.'),
  'Die zusätzliche Formeltiefe dient dem Verständnis. In CFA Level I 2027 muss vor allem der Prozess beider Bewertungswege, die richtige Multiplikatordefinition, die Peer-Auswahl und die historische oder zukünftige Basis beherrscht werden. Begrenzungen werden nicht auswendig als bloße Liste gelernt: Für jeden Fall wird erklärt, welchen Anspruch, welche Kapitalbindung oder welche Zeitinformation die einfache Quote auslässt.'
 ])
],related:[
 {unit:'industry',section:'grouping',label:'Branchenklassifikation und wirtschaftliche Vergleichbarkeit unterscheiden'},
 {unit:'valuation-model',section:'alternatives',label:'Multiplikatoren mit vollständiger Abschlussbewertung vergleichen'},
 {unit:'valuation-overview',section:'bridge',label:'Marktwert und Anspruchsbrücke im Gesamtunternehmen'},
 {unit:'dcf-equity',section:'growth-value',label:'Einbehaltung, Kapitalrendite und Wert der Wachstumsgelegenheiten'},
 {unit:'dcf-equity',section:'reinvestment',label:'Operatives Wachstum aus ROIC und Nettoinvestition'},
 {unit:'dcf-equity',section:'equivalence-case',label:'Dividenden- und Residualgewinnbewertung abstimmen'},
 {unit:'income-statement',section:'nonrecurring',label:'Sondereffekte und nachhaltige Ertragskraft'},
 {unit:'income-statement',section:'basic-eps',label:'Aktienbasis und Gewinn je Aktie'},
 {unit:'cashflow-analysis',section:'classification',label:'Zinsklassifikation und passende Cashflowbrücken'},
 {unit:'forecasting',section:'continuing',label:'Kapitalbindung im langfristigen Prognosezustand'},
 {unit:'return-types',section:'harmonic',label:'Harmonisches Mittel bei gleichen Geldbeträgen'},
 {unit:'regression',section:'workflow',label:'Grenzen einer statistischen Vorhersage'}
],sources:[
 {title:'CFA Institute: Level I 2027, Relative Value Equity Valuation Approaches, Seite 16; maßgebliche Lernzielzuordnung',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=16'},
 {title:'CFA Institute: Market-Based Valuation – Price and Enterprise Value Multiples; ergänzende öffentliche Level-II-Vertiefung 2026',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/market-based-valuation-price-enterprise-value-multiples'},
 {title:'Aswath Damodaran, NYU Stern: The Anatomy of a Multiple; Definition und Analyse von Vergleichsrelationen',url:'https://pages.stern.nyu.edu/adamodar/New_Home_Page/lectures/multintr.htm'},
 {title:'Aswath Damodaran, NYU Stern: Determinants of the PE Ratio; Verbindung zum Zahlungsmodell',url:'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/invfables/peratio.htm'},
 {title:'Aswath Damodaran, NYU Stern: Determinants of Price to Book Ratios; Kapitalrendite und Wertrelation',url:'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/invfables/pbvdeterminants.htm'},
 {title:'Aswath Damodaran, NYU Stern: Standardized Values and Multiples; Vergleichsgrößen',url:'https://pages.stern.nyu.edu/adamodar/New_Home_Page/littlebook/multiples.htm'},
 {title:'Aswath Damodaran, NYU Stern: Controlling for Differences in Relative Valuation; Grenzen einfacher Anpassungen',url:'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/littlebook/controldifferences.htm'}
],review:{status:'draft',date:'2026-10-03',note:'Eigene Gewinn-, Anspruchs-, Kapital- und Periodenfälle sowie vollständig erläuterte fundamentale Herleitungen. Unabhängige technische Gegenprüfungen ersetzen nicht die spätere fachliche Gesamtabnahme.'}};
