const {F,T,X,S}=require('../author.cjs');
module.exports={id:'ratios',intro:[
 'Eine Kennzahl ist eine verdichtete Frage an einen Abschluss: Reichen kurzfristige Mittel? Wie viel Kapital bindet das Geschäft? Wer trägt das Finanzierungsrisiko? Woher stammt die Eigentümerrendite? Erst die Fragestellung entscheidet über die passende Kennzahl. Eine große Zahl ist nicht grundsätzlich gut und eine kleine nicht grundsätzlich schlecht.',
 'Dieses Kapitel baut ein Rechensystem auf, mit dem Bilanz, Gewinnrechnung und Cashflow gemeinsam interpretiert werden. Stromgrößen wie Umsatz und Gewinn gehören zur Periode; Bestände wie Forderungen und Eigenkapital gehören zu Stichtagen. Bei Strom-Bestands-Verhältnissen verwenden wir deshalb nach Möglichkeit Durchschnittsbestände. Die Aufgabenangaben können eine andere Konvention ausdrücklich vorgeben.'
 ],sections:[
 S('methods','1. Vergleichbarkeit vor dem Rechnen','a',[
  'Zeitreihenvergleich untersucht dasselbe Unternehmen über mehrere Perioden. Querschnittsvergleich stellt ähnliche Unternehmen gegenüber. Eine Common-Size-Rechnung setzt jeden Posten zur selben Basis ins Verhältnis, etwa Umsatz bei der GuV oder Gesamtvermögen bei der Bilanz. Ein Trendindex setzt das Basisjahr auf 100. Dadurch lassen sich Größen- und Wachstumsunterschiede erkennen, aber nicht automatisch unterschiedliche Geschäftsmodelle oder Rechnungslegungsmethoden neutralisieren.',
  'Prüfe vor einem Vergleich Konsolidierungskreis, Währung, Berichtsperiode, Geschäftsmodell und Bilanzierungswahl. Ein am Jahresende übernommenes Unternehmen kann die Bilanz bereits vollständig erhöhen, während sein Umsatz erst wenige Wochen zur Gewinnrechnung beiträgt. Ein bloßer Anfangs-/Enddurchschnitt ist bei starken saisonalen Schwankungen ebenfalls nur eine Näherung. Monats- oder Quartalsbestände können geeigneter sein.',
  F('X_t^{idx}=100\\frac{X_t}{X_0},\\qquad \\overline B\\approx\\frac{B_{Anfang}+B_{Ende}}2','Ein Trendindex normalisiert eine Zeitreihe; ein Durchschnittsbestand stellt näherungsweise den über die Periode eingesetzten Bestand dar.',[
   ['X_t^{idx}','Indexwert der Größe X in Periode t, Basisperiode 0 = 100.'],['X_t,X_0','Vergleichbare Werte derselben Größe in aktueller und Basisperiode.'],
   ['\\overline B','Durchschnittlicher Bestand; gleiche Einheit wie B.'],['B_{Anfang},B_{Ende}','Bestand zu Beginn und Ende der Berichtsperiode.']
  ]),
  'Eine belastbare Analyse führt Beobachtung, mögliche Ursache und zusätzliche Prüfung getrennt auf: „Forderungstage steigen“ ist eine Beobachtung; „Kunden zahlen später“ eine mögliche Erklärung; Altersstruktur, Ausfälle und neue Vertragsbedingungen sind zusätzliche Prüfungen. Eine Kennzahl allein liefert selten einen kausalen Beweis.'
 ]),
 S('liquidity','2. Liquidität: vier verschiedene Sicherheitsreserven','b',[
  'Current Ratio verwendet das gesamte Umlaufvermögen. Quick Ratio schränkt die Deckungsmasse auf liquide Mittel, kurzfristig veräußerbare Anlagen und geeignete Forderungen ein. Vorräte und Vorauszahlungen sind darin nicht enthalten. Cash Ratio lässt auch Forderungen weg. So wird die Frage zunehmend strenger: Welche Mittel stehen ohne Warenverkauf oder Kundenzahlung bereits zur Verfügung?',
  F('CR=\\frac{CA}{CL},\\qquad QR=\\frac{C+MS+AR}{CL},\\qquad CaR=\\frac{C+MS}{CL}','Die Nenner bleiben gleich; nur die Qualität und Verfügbarkeit der Deckungsmasse wird enger definiert.',[
   ['CR,QR,CaR','Current Ratio, Quick Ratio und Cash Ratio; dimensionslose Deckungsverhältnisse.'],['CA,CL','Umlaufvermögen und kurzfristige Verbindlichkeiten zum selben Stichtag.'],
   ['C','Liquide Mittel einschließlich der nach Datenabgrenzung geeigneten Zahlungsmitteläquivalente.'],['MS','Kurzfristige marktgängige Wertpapieranlagen.'],['AR','Geeignete kurzfristige Nettoforderungen aus Lieferungen und Leistungen.']
  ]),
  F('DI=\\frac{C+MS+AR}{DCE}','Das Defensive Interval übersetzt die liquiden Reserven in Tage gewöhnlicher betrieblicher Barausgaben.',[
   ['DI','Defensive Interval in Tagen.'],['C,MS,AR','Liquide Mittel, kurzfristige marktgängige Anlagen und geeignete Nettoforderungen.'],
   ['DCE','Durchschnittliche tägliche betriebliche Barausgaben; Abschreibungen und andere nicht zahlungswirksame Aufwendungen sind ausgeschlossen.']
  ]),
  X('Gleiche kurzfristige Schuld, unterschiedliche Deckung','Cash 20, kurzfristige Anlagen 10, Forderungen 50, Vorräte 90 und Vorauszahlungen 10. Kurzfristige Verbindlichkeiten 100. Durchschnittliche betriebliche Barausgaben 2 pro Tag.',[
   F('CR=\\frac{180}{100}=1{,}8,\\quad QR=\\frac{80}{100}=0{,}8,\\quad CaR=\\frac{30}{100}=0{,}3,\\quad DI=\\frac{80}{2}=40','Jede Zahl beschreibt einen anderen Liquidations- oder Zahlungszeitraum.',[['CR,QR,CaR','Current, Quick und Cash Ratio.'],['DI','Defensive Interval in Tagen.']]),
   'Die Current Ratio sieht komfortabler aus, weil sie Waren und Vorauszahlungen mitzählt. Vorauszahlungen bezahlen jedoch keine neue Lieferantenrechnung. Forderungen können überfällig sein; kurzfristige Anlagen können Kurs- oder Verfügungsrisiken besitzen.'
  ],'Eine hohe Current Ratio beseitigt keine Fälligkeitslücke. Umgekehrt kann ein Unternehmen mit schnellem Cashumschlag und stabiler Finanzierung mit einer niedrigeren Quote arbeiten.'),
  'Das Defensive Interval ist eine vereinfachte Reservenrechnung und keine exakte Überlebensdauer. Es unterstellt keine neuen Zuflüsse und eine passende Ausgabenbasis. Fällige Kredite, saisonale Spitzen und gebundene Sicherheiten müssen zusätzlich betrachtet werden.'
 ]),
 S('activity','3. Aktivität: aus Umschlag werden gebundene Tage','b f',[
  'Ein Umschlag setzt den zugehörigen Periodenstrom zum durchschnittlichen Bestand ins Verhältnis. Forderungen entstehen aus Umsatz, Vorräte werden über Umsatzkosten verbraucht, Lieferantenverbindlichkeiten entstehen durch Einkäufe. Der Nenner der Tagekennzahl ist jeweils der passende Strom. Insbesondere Umsatzkosten und Einkäufe sind bei veränderlichem Vorratsbestand nicht identisch.',
  F('RT=\\frac{S}{\\overline{AR}},\\quad IT=\\frac{COGS}{\\overline{Inv}},\\quad PT=\\frac{Purch}{\\overline{AP}},\\quad AT=\\frac{S}{\\overline A}','Die Umschläge geben an, wie oft die jeweilige durchschnittliche Bestandsgröße im Jahr durch den zugehörigen Strom bewegt wird.',[
   ['RT,IT,PT,AT','Forderungs-, Vorrats-, Lieferantenverbindlichkeits- und Gesamtvermögensumschlag pro Jahr.'],['S,COGS,Purch','Jahresumsatz, jährliche Umsatzkosten und jährliche Einkäufe.'],
   ['\\overline{AR},\\overline{Inv},\\overline{AP},\\overline A','Durchschnittliche Forderungen, Vorräte, Lieferantenverbindlichkeiten und Gesamtaktiva.']
  ]),
  F('DSO=\\frac{365}{RT},\\quad DIO=\\frac{365}{IT},\\quad DPO=\\frac{365}{PT},\\quad CCC=DIO+DSO-DPO','Umschlag und Tagekennzahl sind inverse Darstellungen; der Cash Conversion Cycle verbindet die Zahlungsphasen.',[
   ['DSO,DIO,DPO','Forderungs-, Vorrats- und Verbindlichkeitstage.'],['RT,IT,PT','Die oben definierten Jahresumschläge.'],['CCC','Cash Conversion Cycle in Tagen; hier ein Jahr mit 365 Tagen.']
  ]),
  X('Warum Einkäufe und Umsatzkosten auseinanderfallen','Umsatz 730, Umsatzkosten 438, Vorräte Anfang 90 und Ende 110. Durchschnittliche Forderungen 80, durchschnittliche Lieferantenverbindlichkeiten 60. Keine sonstigen Vorratsbewegungen.',[
   F('Purch=438+110-90=458,\\quad\\overline{Inv}=100','Einkäufe müssen zusätzlich den Aufbau des Vorrats finanzieren.',[['Purch','Einkäufe der Periode.'],['\\overline{Inv}','Durchschnittlicher Vorratsbestand.']]),
   F('DSO=365\\frac{80}{730}=40,\\quad DIO=365\\frac{100}{438}\\approx83{,}33,\\quad DPO=365\\frac{60}{458}\\approx47{,}82','Die drei Tagekennzahlen verwenden unterschiedliche wirtschaftlich passende Ströme.',[['DSO,DIO,DPO','Forderungs-, Vorrats- und Verbindlichkeitstage.']]),
   F('CCC\\approx83{,}33+40-47{,}82=75{,}51','Lieferantenkredit finanziert einen Teil der Lager- und Kundenphase.',[['CCC','Cash Conversion Cycle in Tagen.']])
  ],'Umsatzkosten als Ersatz für Einkäufe sind nur eine ausdrücklich bezeichnete Näherung. Sie werden ungenauer, wenn sich Vorräte stark verändern.'),
  'Ein sehr hoher Vorratsumschlag kann Effizienz oder einen drohenden Lagerengpass anzeigen. Ein sinkender Vermögensumschlag kann eine Fehlallokation oder gerade einen noch nicht ausgelasteten Kapazitätsausbau widerspiegeln. Der Modellzusammenhang hilft, die richtigen Anschlussfragen zu stellen.'
 ]),
 S('solvency','4. Solvenz und Schuldendienst','b',[
  'Solvenzkennzahlen untersuchen die Finanzierungsstruktur über längere Zeiträume. Zinsdeckung verbindet einen Ergebnisstrom mit dem zugehörigen Zinsaufwand. Schuldenquoten verwenden dagegen Bilanz- oder Marktbestände. Die Definition von „Debt“ muss festgehalten werden: Üblicherweise ist verzinsliche Verschuldung gemeint, nicht pauschal die Summe aller Verbindlichkeiten. Leasing und Pensionsdefizite können für eine konkrete Analyse zusätzlich relevant sein.',
  F('D_A=\\frac{D}{A},\\quad D_C=\\frac{D}{D+E},\\quad D_E=\\frac{D}{E},\\quad FL=\\frac{\\overline A}{\\overline E},\\quad IC=\\frac{EBIT}{I}','Die ersten drei Quoten beschreiben Verschuldung, Financial Leverage den Vermögenshebel und Interest Coverage die periodische Zinsdeckung.',[
   ['D_A,D_C,D_E','Debt-to-Assets, Debt-to-Capital und Debt-to-Equity; dimensionslose Quoten.'],['D,A,E','Nach festgelegter Definition erfasste Schulden, Aktiva und Eigenkapital zum selben Stichtag.'],
   ['FL','Financial Leverage bzw. Eigenkapitalmultiplikator.'],['\\overline A,\\overline E','Durchschnittliche Aktiva und durchschnittliches Eigenkapital.'],['IC,EBIT,I','Zinsdeckung, Ergebnis vor Zinsen und Steuern und Zinsaufwand derselben Periode.']
  ]),
  F('FCCR=\\frac{EBIT+LP}{I+LP}','Ein einfacher Fixed-Charge-Coverage-Ansatz berücksichtigt zusätzlich die im EBIT bereits abgezogenen Miet-/Leasingaufwendungen.',[
   ['FCCR','Fixed Charge Coverage in diesem ausdrücklich abgegrenzten Ansatz.'],['EBIT','Ergebnis nach den betrachteten Mietaufwendungen, vor Zinsen und Steuern.'],
   ['LP','In EBIT abgezogene fixe Miet-/Leasingaufwendungen der Periode.'],['I','Zinsaufwand derselben Periode.']
  ]),
  'Die letzte Formel darf nach einer Leasingaktivierung nicht ungeprüft mit alten Mietkosten weitergerechnet werden: Dann sind Zins- und Abschreibungskomponenten anders erfasst. Bei negativem oder sehr kleinem Eigenkapital werden Debt-to-Equity und ROE instabil oder schwer sinnvoll interpretierbar. EBITDA ist zudem keine freie Kasse; notwendige Investitionen und Working Capital können Mittel verbrauchen, die für den Schuldendienst fehlen.'
 ]),
 S('profitability','5. Ertragskraft auf Umsatz oder Kapital beziehen','b c',[
  'Umsatzmargen messen, wie viel Ergebnis aus einem Umsatzeuro übrig bleibt. Kapitalrenditen fragen, wie effizient das dafür benötigte Kapital eingesetzt wird. Ein Unternehmen kann deshalb eine geringe Marge und trotzdem eine gute Kapitalrendite besitzen, wenn es das gebundene Vermögen häufig umschlägt.',
  F('GM=\\frac{S-COGS}{S},\\quad OM=\\frac{EBIT}{S},\\quad NM=\\frac{NI}{S},\\quad ROA=\\frac{NI}{\\overline A},\\quad ROE=\\frac{NI}{\\overline E}','Marge und Kapitalrendite verwenden verschiedene Bezugsgrößen; die angegebene ROA-Konvention verwendet Nettogewinn.',[
   ['GM,OM,NM','Brutto-, operative und Nettomarge.'],['S,COGS,EBIT,NI','Umsatz, Umsatzkosten, Ergebnis vor Zinsen und Steuern sowie Nettogewinn.'],
   ['ROA,ROE','Return on Assets und Return on Equity in der hier verwendeten Definition.'],['\\overline A,\\overline E','Durchschnittliche Aktiva und durchschnittliches Eigenkapital.']
  ]),
  F('ROIC=\\frac{EBIT(1-\\tau)}{\\overline{IC}}','ROIC verbindet den operativen Nachsteuergewinn mit dem dafür eingesetzten Kapital aller betrachteten Kapitalgeber.',[
   ['ROIC','Return on Invested Capital.'],['EBIT','Operatives Ergebnis vor Zinsen und Steuern.'],['\\tau','Für die operative Nachsteuerrechnung angesetzter Steuersatz.'],
   ['\\overline{IC}','Durchschnittliches investiertes Kapital nach konsistenter Abgrenzung, beispielsweise verzinsliche Schulden plus Eigenkapital abzüglich nicht operativ benötigter Liquidität.']
  ]),
  'ROIC-Definitionen variieren bei überschüssigem Cash, Goodwill und Leasing. Ein Vergleich mit WACC ist nur sinnvoll, wenn Risiko, Zeitmaßstab und Kapitalabgrenzung zusammenpassen. Eine hohe historische Buchkapitalrendite kann aus alten niedrigen Buchwerten stammen und ist nicht automatisch die Rendite auf einen heutigen Aktienkauf.'
 ]),
 S('dupont','6. Die vollständige DuPont-Brücke','c d',[
  'Die Zerlegung entsteht durch Multiplizieren mit Brüchen, die jeweils eins sind. Umsatz und Aktiva werden in Zähler und Nenner eingefügt und kürzen sich in der Gesamtgleichung wieder heraus. Die drei Faktoren trennen Nettomarge, Umschlag und Finanzierungshebel. Eine Steigerung der ROE kann dadurch auf die jeweils veränderte Ursache zurückgeführt werden.',
  F('ROE=\\frac{NI}{S}\\frac{S}{\\overline A}\\frac{\\overline A}{\\overline E}','Marge mal Vermögensumschlag mal Eigenkapitalmultiplikator ergibt dieselbe Eigenkapitalrendite wie die direkte Rechnung.',[
   ['ROE','Eigenkapitalrendite der Periode.'],['NI,S','Nettogewinn und Umsatz dieser Periode.'],['\\overline A,\\overline E','Durchschnittliche Aktiva und durchschnittliches Eigenkapital.']
  ]),
  F('ROE=\\underbrace{\\frac{NI}{EBT}}_{TB}\\underbrace{\\frac{EBT}{EBIT}}_{IB}\\underbrace{\\frac{EBIT}{S}}_{OM}\\underbrace{\\frac{S}{\\overline A}}_{AT}\\underbrace{\\frac{\\overline A}{\\overline E}}_{FL}','Die Nettomarge wird zusätzlich in Steuerbelastungsfaktor, Zinsbelastungsfaktor und operative Marge zerlegt.',[
   ['NI,EBT,EBIT,S','Nettogewinn, Vorsteuergewinn, Ergebnis vor Zinsen und Steuern und Umsatz.'],['\\overline A,\\overline E','Durchschnittliche Aktiva und Eigenkapital.'],
   ['TB,IB','Tax Burden und Interest Burden: verbleibende Ergebnisanteile nach Steuer bzw. Zins. Bei positiven Bezugsgrößen bedeutet ein kleinerer Faktor eine stärkere Belastung.'],
   ['OM,AT,FL','Operative Marge, Gesamtvermögensumschlag und Eigenkapitalmultiplikator.'],['ROE','Eigenkapitalrendite; Faktoren werden als Dezimalwerte multipliziert.']
  ]),
  X('Ein vollständiger Abschlussausschnitt','Umsatz 1.000; EBIT 200; Zinsaufwand 40; Steueraufwand 48; durchschnittliche Aktiva 800 und Eigenkapital 400. Keine weiteren Ergebnisbestandteile.',[
   F('EBT=200-40=160,\\quad NI=160-48=112','Zins und Steuer führen vom operativen Ergebnis zum Ergebnis der Eigentümer.',[['EBT','Vorsteuergewinn.'],['NI','Nettogewinn.']]),
   F('ROE=0{,}7\\cdot0{,}8\\cdot0{,}2\\cdot1{,}25\\cdot2=0{,}28=28\\%','Die fünf Faktoren sind 112/160, 160/200, 200/1.000, 1.000/800 und 800/400.',[['ROE','Eigenkapitalrendite.']]),
   'Direkte Kontrolle: 112/400 = 28 %. Steigt bei sonst unveränderten Angaben der Zinsaufwand auf 80 und bleibt die Steuerquote 30 %, sinkt der Nettogewinn auf 84. Der Zinsbelastungsfaktor fällt auf 0,6; ROE sinkt auf 21 %. Die operative Marge bleibt 20 %.'
  ],'Die Ursache des Rückgangs liegt hier in der Finanzierung, nicht im Produktgeschäft. Eine höhere Verschuldung darf deshalb nicht nur im Hebelfaktor berücksichtigt werden, während der Zinsaufwand künstlich unverändert bleibt.'),
  'Wenn EBIT oder EBT null sind, kann die fünfteilige Schreibweise undefinierte Zwischenbrüche enthalten, obwohl eine direkte ROE berechenbar bleibt. Bei negativen Ergebnissen kehren sich manche intuitive Richtungen um. Die Zerlegung ist eine algebraische Diagnose, keine automatische Empfehlung, einen einzelnen Faktor zu maximieren.'
 ]),
 S('interactions','7. Transaktionen verändern mehrere Kennzahlen gleichzeitig','c',[
  X('Eine bessere Quote bei weniger Cash','Umlaufvermögen 200, kurzfristige Verbindlichkeiten 100. Eine Lieferantenrechnung von 40 wird aus vorhandenen liquiden Mitteln bezahlt.',[
   F('CR_0=\\frac{200}{100}=2,\\qquad CR_1=\\frac{200-40}{100-40}=\\frac83\\approx2{,}67','Die Current Ratio steigt, weil bei einer Ausgangsquote über eins der Nenner relativ stärker fällt.',[['CR_0,CR_1','Current Ratio vor und nach Zahlung.']]),
   'Die Firma besitzt jetzt 40 weniger Cash und 40 weniger kurzfristige Schuld. Eine bessere Quote ist damit vereinbar, dass ein unerwarteter zusätzlicher Cashbedarf schwieriger zu finanzieren wäre.'
  ],'Absolute Beträge, Fälligkeiten und Quoten gehören zusammen. Eine Stichtagsverbesserung kann rein mechanisch entstehen.'),
  'Ein Wareneinkauf gegen Cash lässt bei gleicher Bewertung das Umlaufvermögen unverändert. Current Ratio bleibt gleich, während Quick Ratio und Cash Ratio sinken. Ein Forderungseinzug verschiebt dagegen AR in Cash: Quick Ratio bleibt im einfachen Fall gleich, Cash Ratio steigt. Solche Vergleiche zeigen, was die Kennzahl jeweils tatsächlich misst.'
 ]),
 S('industry-forecast','8. Branchenfragen und Prognosen','e f',[
  'Für eine Bank kann die Nettozinsmarge auf durchschnittliche zinstragende Aktiva aussagekräftiger sein als eine industrielle Umsatzmarge. Kreditverluste, Kapitalquoten und Liquidität müssen ergänzend untersucht werden. Bei einem Sachversicherer zeigt die kombinierte Schaden- und Kostenquote die Zeichnungsleistung; die konkrete Prämienbasis der Teilquoten muss geprüft werden. Ein Immobilienunternehmen benötigt unter anderem Belegungs-, Miet- und Betriebsergebnisgrößen. Branchenkennzahlen ersetzen die allgemeinen Rechnungslegungsprüfungen nicht.',
  'In Prognosen werden Verhältnisse zu Treibern: Aus erwartetem Umsatz und Forderungstagen entsteht eine erwartete Forderungsposition. Aus Umsatzkosten und Lagerdauer folgt der notwendige Vorrat. So wird Umsatzwachstum in Finanzierungsbedarf übersetzt. Historische Quotenkonstanz ist dabei eine Modellannahme, die Preisänderungen, Kreditpolitik und Kapazitätsgrenzen verletzen können.',
  F('AR_1=S_1\\frac{DSO_1}{365},\\qquad Inv_1=COGS_1\\frac{DIO_1}{365}','Zieltage werden zurück in modellierte Bestände übersetzt; die vereinfachte Jahresplanung behandelt die genannten Bestände als passende Repräsentanten des Zieljahrs.',[
   ['AR_1,Inv_1','Modellierte Forderungen und Vorräte der Zielperiode.'],['S_1,COGS_1','Geplanter Jahresumsatz und geplante Umsatzkosten.'],['DSO_1,DIO_1','Geplante Forderungs- und Lagerdauer in Tagen.']
  ]),
  X('Wachstum mit schlechteren Zahlungsbedingungen','Der Umsatz steigt von 365 auf 438. Forderungstage steigen von 30 auf 45. Gleichmäßige Verkäufe, keine Umsatzsteuer oder Ausfälle.',[
   F('AR_0=365\\frac{30}{365}=30,\\quad AR_1=438\\frac{45}{365}=54,\\quad\\Delta AR=24','Umsatzwachstum und spätere Zahlung erhöhen gemeinsam die Forderungsbindung.',[['AR_0,AR_1','Forderungsbestände im vereinfachten Ausgangs- und Zielmodell.'],['\\Delta AR','Zusätzliche Bindung in Forderungen.']]),
   'Bei unveränderten 30 Tagen wären nur 36 erforderlich. Von den zusätzlichen 24 entstehen also 6 durch Wachstum und 18 durch die Verschlechterung der Zahlungslaufzeit.'
  ],'Gewinnwachstum kann mit einem operativen Cashabfluss einhergehen. Die Zerlegung macht sichtbar, welche operative Annahme dafür verantwortlich ist.'),
  'Diese vereinfachten Bestände sind ausdrücklich Planungsrepräsentanten. Wird DSO stattdessen streng aus dem Mittel von Anfangs- und Endforderungen definiert, erhält man aus Umsatz mal DSO / 365 zunächst einen Durchschnitt. Der folgende Abschnitt zu Prognosekonventionen löst daraus den tatsächlich benötigten Endbestand auf.'
 ]),
 S('additional-ratios','9. Kapitalbasis und Ergebnisanspruch vollständig abgrenzen','b',[
  'Ähnlich klingende Renditen sind nicht austauschbar. Ein Ergebnis vor Zinsen gehört zu einer breiteren Kapitalbasis als der nach Vorrangansprüchen verbleibende Stammaktiengewinn. Ein Umschlag misst dagegen Umsatz je gebundener Kapitaleinheit und ist selbst noch keine Gewinnrendite. Die folgenden zusätzlichen Definitionen ergänzen das bisherige Rechensystem.',
  F('WCT=\\frac{S}{\\overline{CA}-\\overline{CL}},\\qquad FAT=\\frac{S}{\\overline{PPE}_{net}}','Working Capital Turnover verwendet hier gesamtes Nettoumlaufvermögen; Fixed Asset Turnover die Nettosachanlagen.',[['WCT,FAT','Working Capital Turnover und Fixed Asset Turnover pro Jahr.'],['S','Jahresumsatz.'],['\\overline{CA},\\overline{CL}','Zeitlich konsistente durchschnittliche kurzfristige Aktiva und Verbindlichkeiten.'],['\\overline{PPE}_{net}','Durchschnittliche Sachanlagen nach kumulierter Abschreibung und Wertminderung.']]),
  'Operatives Working Capital in einem Cashflowmodell kann Cash und verzinsliche Schulden bewusst ausschließen. Diese engere Größe darf nicht stillschweigend in eine anders definierte Umsatzkennzahl übernommen werden. Bei verschwindend kleiner positiver Kapitalbasis wird der Umschlag sehr groß; bei negativem Nettoumlaufvermögen verliert die normale Rangfolge „höher ist effizienter“ ihren Sinn.',
  F('ROA_{op}=\\frac{EBIT}{\\overline A},\\quad ROTC=\\frac{EBIT}{\\overline D+\\overline E},\\quad ROCE=\\frac{NI-PD}{\\overline{CE}}','Diese drei Vorsteuer- bzw. Eigentümerrenditen verwenden jeweils die hier ausdrücklich bezeichnete Ergebnisebene und Kapitalbasis.',[['ROA_{op}','Operative Return on Assets.'],['ROTC','Return on Total Capital in der hier gewählten EBIT-Konvention; nicht identisch mit operativer Nachsteuer-ROIC.'],['ROCE','Hier Return on Common Equity. Dieselbe Abkürzung wird andernorts für Return on Capital Employed benutzt: den ausgeschriebenen Namen prüfen.'],['EBIT,NI,PD','Operatives Ergebnis vor Zinsen und Steuern, Nettogewinn und relevante Vorzugsdividenden.'],['\\overline A,\\overline D,\\overline E,\\overline{CE}','Durchschnittliche Gesamtaktiva, verzinsliche Schulden, gesamtes Eigenkapital und nur den Stammaktionären zurechenbares Eigenkapital.']]),
  X('Ein Zahlenwerk, mehrere berechtigte Renditefragen','Jahresumsatz 900, EBIT 120, Nettogewinn 70, Vorzugsdividenden 10. Durchschnittliche Aktiva 600, verzinsliche Schulden 150, gesamtes Eigenkapital 300, davon Stammaktienkapital 250. Durchschnittliche Nettosachanlagen 225; Umlaufvermögen 240 und kurzfristige Verbindlichkeiten 90.',[
   T(['Kennzahl','Zähler','Nenner','Ergebnis'],[['Gesamtvermögensumschlag','900','600','1,5'],['Fixed Asset Turnover','900','225','4'],['Working Capital Turnover','900','150','6'],['Nettogewinn-ROA','70','600','11,67 %'],['Operative ROA','120','600','20 %'],['Return on Total Capital','120','450','26,67 %'],['Gesamteigenkapitalrendite','70','300','23,33 %'],['Return on Common Equity','60','250','24 %']],'Jede Kennzahl ist Zähler geteilt durch Nenner; Renditen werden mit 100 in Prozent umgerechnet. Die Prozentwerte sind gerundet.'),
   'Dass ROCE höher als die Gesamteigenkapitalrendite ist, folgt hier aus den konkreten Vorrangansprüchen und Kapitalanteilen. Es ist keine allgemeine Regel. Die Differenz von Gesamtaktiva zu verzinslichen Schulden plus Eigenkapital enthält andere Verbindlichkeiten.'
  ],'Beim Lernen die Formel immer als Zuordnung von Anspruch und Kapital lesen. Das ist robuster als ein isoliertes Kürzel.'),
  'Alte niedrige Nettobuchwerte können Anlagenumschlag und Kapitalrendite erhöhen, obwohl die technische Leistungsfähigkeit unverändert ist. Ein frischer Kapazitätsausbau kann beide zunächst senken. Altersstruktur, Auslastung und nötige Ersatzinvestitionen helfen, den Quotienten zu deuten.'
 ]),
 S('ratio-bridge','10. Eine ROE-Veränderung Schritt für Schritt erklären','c d',[
  'Die DuPont-Gleichung ist eine Identität: Sie zerlegt dieselbe beobachtete Rendite in andere Größen. Daraus folgt noch keine kausale Behauptung, dass ein Faktor unabhängig veränderbar wäre. Besonders bei Kreditaufnahme verändern sich Hebel, Zins und möglicherweise Risiko gleichzeitig. Für einen historischen Vergleich kann eine geordnete Rechenbrücke dennoch zeigen, welche Faktoränderung welchen Teil der Differenz erklärt.',
  F('\\Delta ROE=(m_1-m_0)a_0l_0+m_1(a_1-a_0)l_0+m_1a_1(l_1-l_0)','Hier wird zuerst die Nettomarge, dann der Umschlag und zuletzt der Hebel ersetzt. Die drei Differenzen addieren sich exakt.',[['\\Delta ROE','Neue minus alte Eigenkapitalrendite; als Prozentzahl ausgedrückt eine Änderung in Prozentpunkten.'],['m_0,m_1','Alte und neue Nettomarge als Dezimalzahl.'],['a_0,a_1','Alter und neuer Gesamtvermögensumschlag.'],['l_0,l_1','Alter und neuer Eigenkapitalmultiplikator.']]),
  X('Ein höheres ROE trotz schlechterem Umschlag','Nettomarge steigt von 5 % auf 6 %, Umschlag sinkt von 1,5 auf 1,4, Hebel steigt von 2 auf 2,5. Die Daten beziehen sich jeweils auf konsistent abgegrenzte Perioden.',[
   T(['Schritt','Marge','Umschlag','Hebel','ROE','Änderung'],[['Ausgang','5 %','1,5','2','15 %','—'],['Neue Marge','6 %','1,5','2','18 %','+3 Prozentpunkte'],['Neuer Umschlag','6 %','1,4','2','16,8 %','−1,2 Prozentpunkte'],['Neuer Hebel','6 %','1,4','2,5','21 %','+4,2 Prozentpunkte']],'Marge mal Umschlag mal Hebel ergibt jeweils ROE. Die Gesamtänderung ist +6 Prozentpunkte oder relativ +40 %; diese Angaben sind nicht gleichbedeutend.'),
   'Die höhere Marge verbessert den Zwischenwert, die größere Kapitalbindung je Umsatzeinheit schwächt ihn, und der höhere Hebel erhöht die verbleibende Eigentümerrendite. Ob die neue Finanzierung nachhaltig ist, muss über Zinsdeckung und Fälligkeiten geprüft werden.',
   'Würde der Hebel zuerst ersetzt, entfielen auf diesen Schritt nur 0,05 × 1,5 × 0,5 = 3,75 Prozentpunkte. Andere Schritte würden entsprechend andere Beiträge erhalten. Die Gesamtdifferenz bliebe +6 Prozentpunkte.'
  ],'Die Reihenfolge ist eine offengelegte Zuordnungskonvention. Eine solche Brücke beweist keine voneinander unabhängigen Ursachen.'),
  'Auch das Ausgangsniveau gehört zur Interpretation. Bei Verlusten oder negativem Eigenkapital kann ein positiver Quotient entstehen, ohne gesunde Rentabilität zu belegen. Bei einem Nullnenner ist er undefiniert. In solchen Fällen sind absolute Ergebnisbeträge und die Finanzierungslage aussagekräftiger als eine scheinbar attraktive Rangposition.'
 ]),
 S('industry-cases','11. Branchenkennzahlen am tatsächlichen Geschäftsmodell prüfen','e',[
  'Eine Kennzahl ist hilfreich, wenn sie einen wesentlichen betrieblichen Prozess isoliert. Für drei unterschiedliche Geschäftsmodelle rechnen wir deshalb mit verschiedenen Treibern. Die Fallzahlen sind eigene vereinfachte Beispiele; ein tatsächlicher Bericht muss zusätzlich auf seine Definitionen geprüft werden.',
  F('NIM=\\frac{II-IE}{\\overline{EA}}','Net Interest Margin misst den Zinsüberschuss relativ zum dafür abgegrenzten durchschnittlichen Ertragsvermögen.',[['NIM','Net Interest Margin bzw. Nettozinsmarge für die betrachtete Periode.'],['II,IE','Zinsertrag und Zinsaufwand dieser Periode.'],['\\overline{EA}','Durchschnittliche zinstragende Aktiva; Periodenlänge und gegebenenfalls Annualisierung müssen zur Ergebnisgröße passen.']]),
  X('Bank: höhere Marge mit höheren Verlusten','Durchschnittliche zinstragende Aktiva betragen in beiden Jahren 2.000. Zinsertrag steigt von 100 auf 140; Zinsaufwand von 40 auf 50. Kreditausfallaufwand steigt von 10 auf 45. Andere Ergebnispositionen werden konstant gehalten.',[
   F('NIM_0=\\frac{100-40}{2000}=3\\%,\\qquad NIM_1=\\frac{140-50}{2000}=4{,}5\\%','Die Zinsmarge steigt um 1,5 Prozentpunkte.',[['NIM_0,NIM_1','Nettozinsmargen der beiden Jahre.']]),
   'Nach dem zusätzlich genannten Kreditaufwand verbleiben aber zunächst 50 und danach nur 45. Die verbesserte Einzelmarge genügt nicht, um das risikobehaftete Kreditgeschäft insgesamt als besser einzustufen.'
  ],'Kreditkosten, Laufzeiten, Finanzierung und Eigenkapitalbedarf vervollständigen die Bankanalyse.'),
  F('CR_{ins}=LR+ER=\\frac{L}{P_e}+\\frac{X}{P_x}','Die Combined Ratio addiert Schaden- und Kostenquote. Die jeweilige Prämienbasis muss angegeben werden.',[['CR_{ins}','Combined Ratio; zur Unterscheidung von der Current Ratio mit Branchenindex.'],['LR,ER','Schadenquote einschließlich betrachteter Schadenregulierungskosten und Zeichnungskostenquote.'],['L,X','Entsprechende Schaden- und Kostenbeträge.'],['P_e','Verdiente Prämien derselben Abgrenzung.'],['P_x','Vorgeschriebene Prämienbasis der Kostenquote, je nach Berichtsdefinition beispielsweise geschriebene oder verdiente Prämien.']]),
  'Bei einer ausdrücklich gemeinsamen verdienten Prämienbasis von 800, Schäden von 520 und Kosten von 200 beträgt die Combined Ratio 90 %. Das vereinfachte Zeichnungsergebnis beträgt 80. Kapitalanlageergebnis und Steuer sind darin nicht enthalten. Verwendet die Kostenquote dagegen geschriebene Prämien, darf die Summe nicht ohne Überleitung als exakt derselbe Ergebnisanteil an verdienten Prämien gelesen werden. Rückversicherungs- und Reserveeffekte erfordern ebenfalls eine konsistente Abgrenzung.',
  F('S=N\\cdot u\\cdot p,\\qquad NOI=S-O','Ein vereinfachtes Immobilienmodell verbindet vermietbare Einheiten, Belegung und effektiven Mietpreis mit dem Objektbetriebsergebnis.',[['S','Mietumsatz der Periode ohne zusätzliche Erlösarten.'],['N','Zahl gleichartiger vermietbarer Einheiten.'],['u','Vermieteter Anteil zwischen null und eins.'],['p','Effektive Miete je belegter Einheit und Periode.'],['NOI','Net Operating Income in diesem Fall: Objektumsatz minus Objektbetriebskosten, vor Zins, Abschreibung und Steuer.'],['O','Zugehörige Objektbetriebskosten.']]),
  '100 gleichartige Einheiten bei 90 % Belegung und Monatsmiete 1.200 erzeugen 108.000 Monatsumsatz. Bei Betriebskosten von 28.000 beträgt NOI 80.000. Eine höhere Belegung zu stark rabattierten Mieten muss NOI nicht verbessern. Bei verschiedenen Flächengrößen oder Nutzungsarten benötigt das Modell entsprechend getrennte und gewichtete Treiber.'
 ]),
 S('forecast-conventions','12. Von Kennzahlen zu einem konsistenten Prognosemodell','a f',[
  'Vor jeder Rückrechnung wird die Kennzahl ausgeschrieben. „40 Forderungstage“ kann auf Jahresendforderungen oder auf durchschnittlichen Forderungen beruhen. Beides kann bei gleichmäßigem Geschäft ähnlich aussehen, führt bei Wachstum aber zu unterschiedlichen Bilanzprognosen. Eine Näherung ist verwendbar, wenn sie bewusst gewählt und plausibel ist; sie ist nicht dieselbe Rechnung wie eine exakte Mittelwertdefinition.',
  F('\\overline{AR}=S\\frac{DSO}{365},\\qquad AR_1=2\\overline{AR}-AR_0','Gilt ausdrücklich der einfache Anfangs-/Enddurchschnitt, ist dies die exakte Auflösung nach dem Endbestand.',[['\\overline{AR}','Einfacher Mittelwert aus Anfangs- und Endforderungen.'],['S','Geplanter Jahresumsatz auf passender Kreditumsatzbasis.'],['DSO','Forderungstage nach genau dieser Durchschnittsdefinition, hier bei 365 Tagen.'],['AR_0,AR_1','Forderungen am Jahresanfang und Jahresende.']]),
  X('Eine scheinbar kleine Definitionsfrage verdoppelt den Cashbedarf','Jahresumsatz 1.095, geplante DSO 40 und Anfangsforderungen 90. DSO verwendet ausdrücklich den einfachen Anfangs-/Enddurchschnitt. Keine Ausfälle, Steuern oder sonstigen Forderungsbewegungen.',[
   F('\\overline{AR}=1095\\frac{40}{365}=120,\\quad AR_1=2\\cdot120-90=150,\\quad\\Delta AR=60','120 ist die benötigte Durchschnittsbindung; die Bilanz benötigt 150 am Jahresende.',[['\\overline{AR}','Durchschnittsforderungen.'],['AR_1','Endforderungen.'],['\\Delta AR','End- minus Anfangsforderungen.']]),
   'Wer 120 versehentlich als Endbestand einsetzt, berechnet nur 30 zusätzliche Kapitalbindung. Tatsächlich bleiben nach dieser Definition 60 des Umsatzes zusätzlich in Forderungen gebunden.',
   F('C_{in}=1095+90-150=1035','Kundeneinzahlungen liefern eine unabhängige Gegenrechnung zur Bestandsänderung.',[['C_{in}','Einzahlungen aus dem gesamten Forderungs- und Umsatzbestand dieser Periode.']]),
   'Eine Durchschnittsdefinition macht einen angenommenen Zahlungstermin noch nicht wirtschaftlich plausibel. Bei Saison oder sprunghaften Umsätzen ist eine monatliche Rechnung oft geeigneter. Entsteht aus einer groben Jahresgleichung ein negativer Endbestand, sind Annahmen und Aggregation zu überprüfen.'
  ],'Diese Unterscheidung wird im vollständigen Prognosekapitel bis zur Kreditaufnahme und zur ausgeglichenen Bilanz weitergeführt.'),
  F('NI=(S\\cdot OM-I)(1-\\tau)','Eine vereinfachte Gewinnprognose überführt operative Marge zuerst in EBIT, dann in Vorsteuer- und Nachsteuergewinn.',[['NI','Prognostizierter Nettogewinn.'],['S,OM','Prognoseumsatz und operative Marge als Dezimalzahl.'],['I','Zinsaufwand; zusätzliche Finanzierung kann diesen Wert verändern.'],['\\tau','Für das positive Vorsteuerergebnis angenommene effektive Steuerquote; keine weiteren Ergebnisbestandteile.']]),
  'Eine Sensitivität ändert zum Beispiel nur die Zahlungsdauer. Ein Rezessionsszenario kann zugleich Menge, Kundenbonität, Zahlungsdauer und Zins verändern. Historische Quotenkonstanz ist für beide nur eine Annahme. Kapazitätsgrenzen, Wettbewerb und Kreditverfügbarkeit müssen weiterhin zu den prognostizierten Zahlen passen.'
 ])],
 related:[{unit:'forecasting',section:'working-capital',label:'Durchschnitt und Endbestand im vollständigen Modell'},{unit:'forecasting',section:'funding-figure',label:'Zahlungsdauer und Kreditbedarf grafisch vergleichen'},{unit:'income-statement',section:'common-size',label:'Margenänderungen über die Gewinnrechnung erklären'},{unit:'long-assets',section:'depreciation',label:'Abschreibung verändert die Nettokapitalbasis'}],
 sources:[
  {title:'CFA Institute: Financial Analysis Techniques',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/financial-analysis-techniques'},
  {title:'CFA Institute: Financial Ratio List – Definitionen und Konventionsunterschiede',url:'https://www.cfainstitute.org/sites/default/files/-/media/documents/support/programs/cfa/cfa_program_level_ii_financial_ratio_list.pdf'},
  {title:'Federal Reserve: Definition der Net Interest Margin',url:'https://www.federalreserve.gov/publications/2023-may-supervision-and-regulation-report-banking-system-conditions.htm'},
  {title:'NAIC: Combined Ratio und unterschiedliche Prämienbasen im Branchenbericht',url:'https://content.naic.org/sites/default/files/pc-and-title-2024mid-year-industry-report.pdf'}
 ],review:{status:'draft',date:'2026-09-25',note:'Renditebasen, Branchenfälle, Prognosekonventionen und schrittweise DuPont-Brücke erweitert; Rechenfälle werden unabhängig getestet. Fachlicher Gesamtaudit bleibt offen.'}};
