const {F,T,X,S,G}=require('../author.cjs');
const annuity=[1,2,3,4].reduce((v,t)=>v+1/1.08**t,0);
module.exports={id:'stakeholders',intro:[
 'Ein und dasselbe Unternehmen kann für verschiedene Menschen etwas anderes bedeuten: eine Zinsquelle, eine Wachstumsanlage, einen Arbeitsplatz, einen verlässlichen Lieferanten oder einen Belastungsfaktor für die Nachbarschaft. Um eine Entscheidung zu beurteilen, müssen wir deshalb zuerst fragen, wessen Anspruch sich verändert. Ein höherer Aktienwert beweist allein noch nicht, dass insgesamt zusätzlicher Wert geschaffen wurde.',
 'Wir beginnen mit der Zahlungsreihenfolge von Fremd- und Eigenkapital und leiten daraus mögliche Konflikte ab. Danach erweitern wir die Betrachtung auf weitere Stakeholder und übersetzen Umwelt-, Sozial- und Governancefaktoren in überprüfbare wirtschaftliche Wirkungen. Alle Zahlenfälle sind eigene vereinfachte Modelle. Die zusätzlichen Herleitungen erklären die CFA-Level-I-Begriffe; Optionsbewertungsmodelle oder konkrete nationale Rechtsberatung werden dafür nicht vorausgesetzt.'
],sections:[
 S('claims','1. Versprochene Zahlung und verbleibender Anspruch','a',[
  'Ein gewöhnlicher Kredit verpflichtet den Schuldner zu vereinbarten Zahlungen. Fälligkeit, Zins, Rang, Sicherheiten und Vertragsbedingungen bestimmen den konkreten Anspruch. Ein höherer Unternehmensgewinn erhöht eine gewöhnliche feste Zinszahlung nicht automatisch. Der Kreditgeber interessiert sich daher besonders für Schuldendienstfähigkeit, Verlust bei Ausfall und die Möglichkeit, sein Geld rechtzeitig zurückzuerhalten.',
  'Gewöhnliche Stammaktien haben dagegen im Grundmodell keinen festen Rückzahlungstermin und keine versprochene Dividende. Aktionäre tragen den nach vorrangigen Ansprüchen verbleibenden Erfolg. Sie können von Wachstum und steigenden Margen profitieren, aber auch ihr gesamtes investiertes Kapital verlieren. Ein Verkauf an einen anderen Anleger ist keine Rückzahlungspflicht des Emittenten.',
  T(['Merkmal','Gewöhnlicher Kredit / feste Schuld','Gewöhnliche Stammaktie'],[
   ['Zahlungsanspruch','Vertraglich vereinbarter Zins und Tilgung; Ausfall bleibt möglich.','Residualanspruch; gewöhnliche Dividende wird nicht allein durch Aktienbesitz garantiert.'],
   ['Rang','Vor Stammaktionären; zwischen Schulden bestehen weitere Rangunterschiede.','Nach vorrangigen Verpflichtungen.'],
   ['Erfolgsbeteiligung','Im einfachen Vertrag nach oben durch vereinbarte Zahlung begrenzt.','Steigender verbleibender Unternehmenswert kommt den Aktionären zugute.'],
   ['Einfluss','Verträge, Informationsrechte, Sicherheiten und gegebenenfalls Rechte bei Verstoß.','Stimmrechte nach Aktienklasse und Satzung; Einfluss hängt von Kontrollstruktur ab.'],
   ['Emittentenperspektive','Feste Fälligkeiten schaffen Liquiditäts- und Refinanzierungsdruck.','Keine gewöhnliche feste Bedienungspflicht; Ausgabe kann Eigentum und Stimmen verwässern.']
  ],'Wandelanleihen, Vorzugsaktien, ewige Anleihen und besondere Vertragsrechte können von diesem Grundvergleich abweichen.'),
  'Die Risikoaussage benötigt eine Vergleichsbasis. Bei demselben Emittenten ist eine gewöhnliche Stammaktie wegen ihres Nachrangs typischerweise stärker am Unternehmensrisiko beteiligt als eine vorrangige Schuld. Daraus folgt nicht, dass jede Aktie weltweit riskanter als jede Anleihe ist. Laufzeit, Währung, Einstiegspreis, Emittent und eingebettete Optionen können den Vergleich verändern.'
 ]),
 S('waterfall','2. Die Zahlungsreihenfolge mathematisch verstehen','a',[
  'Betrachten wir genau einen Endzeitpunkt. Sämtliche operativen Verpflichtungen und Abwicklungskosten sind bereits abgezogen; der verbleibende realisierbare Betrag wird nur zwischen einer Schuldklasse und vollständig eingezahlten, beschränkt haftenden Stammaktionären aufgeteilt. Die Schuld enthält bereits alle am Endzeitpunkt geschuldeten Zinsen. Es gibt keine Garantien oder weiteren Mittelzuflüsse.',
  F('B_T=\\min(V_T,D),\\qquad E_T=\\max(V_T-D,0),\\qquad B_T+E_T=V_T','Die Gläubiger erhalten höchstens ihre fällige Forderung; der Rest gehört den Aktionären. Beide Auszahlungen zusammen verbrauchen exakt den verfügbaren Betrag.',[['B_T','Tatsächliche Auszahlung an die einzige Schuldklasse am Endzeitpunkt T.'],['E_T','Auszahlung an Stammaktionäre am Endzeitpunkt T.'],['V_T','Nicht negativer, nach den genannten Vorabzügen verteilter Unternehmensbetrag.'],['D','Fälliger vertraglicher Gesamtanspruch der betrachteten Schuldklasse.'],['T','Einheitlicher End- und Verteilungszeitpunkt.']]),
  T(['Verfügbarer Betrag','Schuldanspruch','Gläubigerzahlung','Aktionärszahlung','Gläubigerverlust'],[['40','80','40','0','40'],['80','80','80','0','0'],['100','80','80','20','0'],['160','80','80','80','0']],'Die Schwelle 80 trennt die Bereiche: darunter tragen die Gläubiger den nächsten fehlenden Euro, darüber erhalten Aktionäre den nächsten zusätzlichen Euro.'),
  G({id:'claim-payoffs',title:'Wer erhält einen zusätzlichen Euro Unternehmenswert?',caption:'Vereinfachte Endauszahlungen bei einer einzigen fälligen Schuld von 80. Keine Kosten, Garantien, weiteren Ansprüche oder vorzeitigen Ausschüttungen.',reading:'Bis 80 steigt nur die Gläubigerzahlung. Danach bleibt sie bei 80, während die Aktionärszahlung steigt. Die gestrichelte Gesamtsumme entspricht an jedem Punkt dem verfügbaren Betrag. Dies sind Endauszahlungen, keine heutigen Marktpreise.',plot:{x:[0,160],y:[0,160],xTicks:[0,40,80,120,160],xLabel:'Verfügbarer Betrag am Endzeitpunkt',yLabel:'Endauszahlung',series:[{name:'Gläubiger',points:[[0,0],[80,80],[160,80]]},{name:'Aktionäre',points:[[0,0],[80,0],[160,80]]},{name:'Summe beider Ansprüche',dash:'5 4',points:[[0,0],[160,160]]}],marks:[{x:80,y:80,label:'Schuld vollständig gedeckt',dx:8,dy:22}]}}),
  'Der Knick der Aktienauszahlung ähnelt dem Auszahlungsprofil einer Kaufoption auf den Unternehmensbetrag mit einer Schwelle in Höhe der Schuld. Diese Analogie erklärt den Anreiz zu zusätzlichem Risiko. Sie liefert ohne weitere Annahmen noch keinen heutigen Options- oder Aktienpreis. Insolvenzverfahren können außerdem Rangfolgen, Kosten und Verteilungszeitpunkte wesentlich komplexer machen.'
 ]),
 S('seniority','3. Nicht alle Gläubiger sitzen an derselben Stelle','a',[
  'Seniorität bezeichnet den Vorrang eines Anspruchs gegenüber einem anderen. Besicherung und Seniorität sind verbunden, aber nicht dasselbe: Eine Sicherheit betrifft einen bestimmten verwertbaren Vermögenswert und ihre rechtliche Durchsetzbarkeit; ein Rang ordnet Zahlungsansprüche zueinander. Schulden verschiedener Konzerngesellschaften sind ebenfalls nicht automatisch Ansprüche auf denselben Vermögenstopf.',
  X('Ein Rangunterschied wird bei Knappheit sichtbar','Nach allen hier vorgelagerten Kosten stehen 95 zur Verfügung. Es gibt eine vorrangige Forderung von 60 und eine ausdrücklich nachrangige Forderung von 50. Keine weiteren Rechte, Sicherheiten oder Kosten verändern die Verteilung.',[
   'Zuerst werden 60 an die vorrangige Klasse verteilt. Der Rest beträgt 35. Die nachrangige Klasse erhält davon 35 auf ihren Anspruch von 50; für Aktionäre bleibt nichts.',
   F('RR_J=\\frac{95-60}{50}=70\\%,\\qquad L_J=50-35=15','Die Rückgewinnungsquote verwendet die Forderung genau der betrachteten Klasse als Nenner.',[['RR_J','Recovery Rate der nachrangigen Schuldklasse J.'],['L_J','Betrag ihres Ausfalls in den verwendeten Geldeinheiten.']]),
   'Eine pauschale Quote von 95 geteilt durch 110 wäre nur eine Gesamtdeckungsquote. Sie beschreibt hier nicht die tatsächliche Rückgewinnungsquote beider Klassen: Die vorrangige Klasse erhält 100 %, die nachrangige 70 %.'
  ],'Ein Kreditvergleich benötigt den konkreten Anspruch, seinen Rang und den verfügbaren Vermögenstopf. Das Wort „Anleihe“ allein genügt nicht.'),
  'Auch bevor ein Ausfall eintritt, wirken Vertragsbedingungen auf den Preis. Die Möglichkeit einer späteren schlechteren Deckung beeinflusst die verlangte Rendite und die Bereitschaft zur Finanzierung. Eine Garantie eines anderen Rechtsträgers muss zusätzlich auf Umfang, Zahlungsfähigkeit und Durchsetzbarkeit geprüft werden.'
 ]),
 S('promised-expected','4. Versprochene Rendite ist keine erwartete Rendite','a',[
  'Eine hohe versprochene Zahlung kann gerade die Folge eines hohen Ausfallrisikos sein. Für die erwartete Rendite werden tatsächliche mögliche Zahlungen mit ihren Wahrscheinlichkeiten gewichtet. Der Marktpreis berücksichtigt daneben Zeitwert, Risikoaversion, Liquidität und weitere Faktoren. Eine Rechnung mit realen Szenariowahrscheinlichkeiten ist daher nicht automatisch ein Marktpreismodell.',
  X('Zehn Prozent auf dem Vertrag, sechs Prozent im Erwartungswert','Ein einperiodiger Titel kostet 100 und verspricht am Periodenende 110. Im eigenen Szenariomodell werden mit 90 % Wahrscheinlichkeit 110 und mit 10 % Wahrscheinlichkeit nur 70 bezahlt. Keine weiteren Zahlungen oder Kosten.',[
   F('\\mathbb{E}[C_1]=0{,}9\\cdot110+0{,}1\\cdot70=106','Zuerst werden die möglichen tatsächlichen Endzahlungen gewichtet.',[['\\mathbb{E}[C_1]','Erwartete tatsächliche Zahlung am Ende der Periode.'],['C_1','Szenarioabhängige Endzahlung.']]),
   F('y_{prom}=\\frac{110}{100}-1=10\\%,\\qquad\\mathbb{E}[R]=\\frac{106}{100}-1=6\\%','Die versprochene Rendite und die erwartete realisierte Rendite teilen denselben Anfangspreis, aber unterschiedliche Endzahlungen.',[['y_{prom}','Einperiodige Rendite bei vollständiger Zahlung des Versprechens.'],['\\mathbb{E}[R]','Mit den angegebenen Wahrscheinlichkeiten erwartete Halteperiodenrendite.']]),
   'Die Differenz von vier Prozentpunkten entspricht hier dem erwarteten Zahlungsausfall von vier relativ zum Kaufpreis 100. Sie ist nicht automatisch eine reine Risikoprämie. Eine solche Prämie würde den erwarteten Ertrag unter anderem mit einer passenden risikofreien Anlage vergleichen.'
  ],'Gläubiger suchen nicht bloß einen hohen Kupon. Sie müssen beurteilen, welche Zahlung tatsächlich erreichbar ist und welche Verluste mit ungünstigen Zuständen zusammenfallen.'),
  'Aus Emittentensicht kann dieselbe feste Zahlung den Betrieb unter Druck setzen, obwohl sie für den Anleger relativ zum Aktienanspruch vorrangig ist. „Für wen riskant?“ und „gegenüber welcher Alternative?“ gehören deshalb zu jeder Aussage.'
 ]),
 S('risk-shifting','5. Warum mehr Risiko Eigentümer und Gläubiger trennt','a b',[
  'Die Aktienauszahlung verliert unterhalb der Schuldenschwelle nicht weiter an Wert, weil sie bereits null ist. Oberhalb der Schwelle erhalten Aktionäre dagegen jeden zusätzlichen Euro. Wird ein relativ sicherer Vermögenswert nach der Kreditvergabe durch eine riskantere Strategie ersetzt, kann diese Asymmetrie Eigentümer begünstigen. Das nennt man Asset Substitution oder Risk Shifting. Die alte Schuld muss dabei unverändert bleiben; kann der Kreditgeber sofort neu bepreisen, verändert sich der Fall.',
  X('Gleicher erwarteter Unternehmensbetrag, andere Verteilung','Die alte Schuld verspricht 80. Alle Strategien benötigen dieselben vorhandenen Ressourcen. Es gibt keine Zwischenzahlungen oder Kosten. Verglichen werden undis­kontierte erwartete Endzahlungen; wir setzen sie ausdrücklich nicht mit heutigen Marktwerten gleich.',[
   T(['Strategie','Endbetrag und Wahrscheinlichkeit','Erwarteter Gesamtbetrag','Erwartete Gläubigerzahlung','Erwartete Aktienzahlung'],[
    ['Sicher','100 mit 100 %','100','80','20'],
    ['Riskanter','50 oder 150, jeweils 50 %','100','65','35'],
    ['Riskanter und insgesamt schlechter','40 oder 150, jeweils 50 %','95','60','35']
   ],'Jeder Zustand wird zuerst nach der Rangfolge aufgeteilt. Erst danach werden die Auszahlungen gemittelt.'),
   F('\\mathbb{E}[B_T]=0{,}5\\min(50,80)+0{,}5\\min(150,80)=65','In der mittleren Strategie erhält die Schuld im schlechten Zustand 50, im guten nur die vereinbarten 80.',[['\\mathbb{E}[B_T]','Erwartete Gläubigerzahlung im riskanteren Fall.'],['B_T','Tatsächliche Endzahlung an Gläubiger.']]),
   F('\\mathbb{E}[E_T]=0{,}5\\max(50-80,0)+0{,}5\\max(150-80,0)=35','Die Verlustseite der Aktionäre endet bei null; im günstigen Zustand verbleiben 70.',[['\\mathbb{E}[E_T]','Erwartete Aktionärszahlung im riskanteren Fall.'],['E_T','Tatsächliche Endzahlung an Aktionäre.']]),
   'Gegenüber der sicheren Strategie gewinnen Aktionäre erwartete 15; Gläubiger verlieren 15. In der dritten Strategie gewinnen Aktionäre weiterhin 15, während Gläubiger 20 verlieren. Die Differenz von fünf ist zusätzlich vernichteter erwarteter Gesamtbetrag.'
  ],'Ein Eigentümer kann eine Entscheidung bevorzugen, die weder den Gesamtbetrag erhöht noch Gläubiger angemessen entschädigt. Ein hoher Aktienertrag ist deshalb kein ausreichender Beleg für gute Investitionspolitik.'),
  'Die Aussage ist kein universelles Gesetz „Aktionäre wollen immer maximalen Einsatz“. Reputation, persönliche Konzentration, künftiger Kapitalbedarf, Verträge und Insolvenzfolgen können den Anreiz begrenzen. Der Fall isoliert einen bestimmten Konflikt bei bereits ausstehender Schuld.'
 ]),
 S('debt-overhang','6. Warum ein gutes Projekt trotzdem unterbleiben kann','a b',[
  'Der umgekehrte Konflikt ist Debt Overhang: Ein Teil des Vorteils einer neuen, sinnvollen Investition fließt an alte Gläubiger, weil ihr bisher gefährdeter Anspruch besser gedeckt wird. Sollen ausschließlich die Aktionäre den neuen Einsatz tragen, kann ihr eigener Nutzen unter den Kosten liegen. Hohe bestehende Schulden können so Unterinvestition erzeugen.',
  X('Positiver Projektwert, negativer privater Finanzierungsanreiz','Am gemeinsamen Endzeitpunkt liefert das vorhandene Geschäft sicher 70; alte Schuld von 90 ist dann fällig. Ein Zusatzprojekt kostet heute 15 und liefert am Endzeitpunkt zusätzliche 25. Für diese isolierte Rechnung beträgt der Diskontsatz null. Keine Kosten, Garantien, Ausschüttungen oder anderen Ansprüche.',[
   T(['Größe','Ohne Projekt','Mit Projekt'],[['Verteilbarer Endbetrag','70','95'],['Alte Gläubigerzahlung','70','90'],['Aktionärszahlung am Ende','0','5'],['Neuer Einsatz der Aktionäre heute','0','15']],'Zusätzlich geschaffene 25 verteilen sich auf 20 bessere Gläubigerdeckung und fünf verbleibende Aktionärszahlung.'),
   F('NPV_{project}=25-15=10,\\qquad\\Delta W_E=5-15=-10','Das Gesamtprojekt ist vorteilhaft, seine Finanzierung durch die bisherigen Aktionäre im gegebenen unveränderten Vertrag jedoch nicht.',[['NPV_{project}','Kapitalwert des Zusatzprojekts beim ausdrücklich angenommenen Diskontsatz null.'],['\\Delta W_E','Vermögensänderung der finanzierenden Aktionäre gegenüber Verzicht.']]),
   'Die Gläubiger gewinnen 20 an Endzahlung, die Aktionäre verlieren netto zehn. Zusammen ergibt das den positiven Projektwert von zehn. Eine einvernehmliche Änderung des Altanspruchs oder eine passende neue Finanzierung kann den Überschuss anders verteilen; ob das rechtlich und wirtschaftlich gelingt, ist eine eigene Prüfung.'
  ],'Projektqualität und Verteilung ihres Nutzens sind zwei verschiedene Fragen. Eine Ablehnung kann aus einem Finanzierungsproblem entstehen, obwohl das Projekt Ressourcen produktiv einsetzt.'),
  'Diese Mechanik verbindet Kapitalstruktur und Kapitalallokation. Bei einer normalen, gut gedeckten Schuld würde zusätzliche Projektleistung überwiegend den Aktionären zufallen. Der Konflikt verschärft sich, wenn alte Gläubiger erst durch die neue Investition wieder vollständig bezahlt werden.'
 ]),
 S('claim-protection','7. Verträge begrenzen Konflikte und schaffen eigene Kosten','a b',[
  'Gläubiger können Covenants verlangen, beispielsweise Informationspflichten, Begrenzungen zusätzlicher Verschuldung oder Bedingungen für Ausschüttungen. Sicherheiten, kurze Kontrollintervalle und abgestimmte Gläubigervertretung ergänzen diese Regeln. Ein Covenant ist aber nur so wirksam wie seine Definition, Überwachung und Durchsetzbarkeit. Bilanzkennzahlen und Marktwerte dürfen nicht ohne Weiteres vertauscht werden.',
  T(['Mögliche Handlung','Warum Gläubiger betroffen sind','Mögliche Gegenmaßnahme und Grenze'],[
   ['Riskanteres Geschäft nach Kreditvergabe','Verlustseite wächst, vereinbarte Zahlung steigt nicht automatisch.','Investitions- oder Risikogrenzen; zu enge Regeln können sinnvolle Projekte verhindern.'],
   ['Ausschüttung vorhandener Liquidität','Weniger Vermögen bleibt für den Schuldendienst.','Ausschüttungsbedingungen; vorhandene vertragliche Ausnahmen prüfen.'],
   ['Neue vorrangige Verschuldung','Bestehender Anspruch kann schlechter gedeckt werden.','Verschuldungs- und Besicherungsklauseln; konkrete Rang- und Gesellschaftsebene prüfen.'],
   ['Wichtige Daten verspätet melden','Probleme werden erst nach Handlungsmöglichkeiten sichtbar.','Informationspflichten und Prüfung; Berichtsqualität bleibt entscheidend.']
  ],'Schutz ist kein kostenloser Zusatz. Verhandlung, Überwachung und verlorene Flexibilität gehören zur Finanzierung.'),
  'Besteht umgekehrt ein Debt-Overhang-Problem, kann eine pauschale Sperre jeder neuen Finanzierung den produktiven Ausweg erschweren. Gute Verträge verbinden Schutz vor Wertverschiebung mit einem Verfahren für sinnvolle Änderungen. Eine Covenantverletzung bedeutet außerdem nicht in jedem Vertrag sofortige Liquidation; Heilungsfristen, Verzicht, Nachverhandlung und Kündigungsrechte sind gesondert geregelt.'
 ]),
 S('stakeholder-map','8. Anspruchsgruppen systematisch erfassen','b',[
  'Stakeholder sind Personen oder Gruppen, die das Unternehmen beeinflussen oder von ihm betroffen sind. Hier verwenden wir den weiten Begriff einschließlich Aktionären und Gläubigern. Manche Quellen verwenden „Stakeholder“ enger für die übrigen Gruppen. Die Definition muss erkennbar sein, bevor Aussagen verglichen werden.',
  T(['Gruppe','Typisches Interesse','Möglicher Konflikt oder gemeinsamer Vorteil'],[
   ['Aktionäre','Langfristiger Wert, Ausschüttungen und wirksame Eigentümerrechte.','Mehrheit und Minderheit oder kurzfristige und langfristige Anleger können verschieden profitieren.'],
   ['Gläubiger','Verlässlicher Schuldendienst und Werterhalt des Anspruchs.','Stabile Deckung kann wichtiger sein als eine sehr riskante Wachstumschance.'],
   ['Management und Board','Mandat erfüllen, Vergütung, Reputation und Fortbestand.','Persönliche Karriere oder Größe können wertvolle Entscheidungen verdrängen.'],
   ['Beschäftigte','Vergütung, Sicherheit, Gesundheit und Entwicklung.','Kurzfristige Einsparung kann Motivation, Wissen und Produktivität kosten.'],
   ['Kunden','Qualität, Verlässlichkeit, Preis und Schutz ihrer Daten.','Versteckte Qualitätskürzung kann heute Marge und morgen Schadenersatz oder Kundenverlust erzeugen.'],
   ['Lieferanten','Faire, planbare Zahlung und stabile Zusammenarbeit.','Einseitig längere Zahlungsziele belasten ihre Liquidität und können Lieferfähigkeit schwächen.'],
   ['Staat und Aufsicht','Regeleinhaltung, Steuern, Wettbewerb und öffentliche Interessen.','Ein Staat kann zugleich Regulierer, Kunde und Eigentümer mit unterschiedlichen Zielen sein.'],
   ['Gemeinschaften und Umwelt','Lebensqualität, Ressourcen, lokale Beschäftigung und langfristige Belastbarkeit.','Nicht vollständig eingepreiste Schäden können außerhalb der Unternehmensrechnung liegen.']
  ],'Interessen sind mögliche Ausgangspunkte der Analyse, keine Behauptung identischer Präferenzen aller Mitglieder einer Gruppe.'),
  'Die Einteilung ist nicht überschneidungsfrei: Beschäftigte können Aktien besitzen, ein Lieferant kann zugleich Kreditgeber sein, ein Fonds kann Aktien und Anleihen desselben Emittenten halten. Für die konkrete Entscheidung zählt, welcher Anspruch oder welche Rolle betroffen ist. Ein institutioneller Aktionär handelt außerdem häufig für Begünstigte mit eigenen Zielen.'
 ]),
 S('tradeoffs','9. Wert schaffen, Wert übertragen und Schäden auslagern','b c',[
  'Nicht jeder Stakeholderkonflikt ist ein unvermeidlicher Gegensatz. Sicherere Arbeit kann weniger Unfälle, geringere Ausfälle und höhere Bindung schaffen. Eine robuste Lieferkette kann Kunden und Kapitalgeber zugleich schützen. Andere Entscheidungen übertragen lediglich Geld oder Risiko. Beide Arten dürfen in einer Analyse nicht vermischt werden.',
  X('Ein Zahlungsziel verbessert nicht automatisch das gesamte Geschäft','Ein Käufer verlängert nach Vereinbarung das Zahlungsziel für eine unveränderte Rechnung um 30 Tage. Er behält das Geld länger; der Lieferant erhält es entsprechend später. Der Warenwert und die Gesamtzahlung ändern sich zunächst nicht.',[
   'Auf Ebene des Käufers verbessert sich vorübergehend die Liquidität. Auf Ebene des Lieferanten verschlechtert sie sich um den gleichen Zahlungsbetrag. Dies ist zunächst ein zeitlicher Finanzierungstransfer, noch keine höhere Produktivität.',
   'Muss der Lieferant nun teurer finanzieren, Preise erhöhen oder Lieferungen kürzen, entstehen zusätzliche Folgen. Hat der Käufer günstigere Finanzierungsmöglichkeiten, kann eine gemeinsame Finanzierungslösung effizienter sein als einseitiger Druck.',
   'Der Analyst prüft daher nicht nur die Käuferkennzahl, sondern auch Lieferantenkonzentration, Ausfallrisiko, künftige Preise und die Dauerhaftigkeit der Vereinbarung.'
  ],'Eine gute Kennzahl kann aus einer Verschiebung zu einem anderen Beteiligten stammen. Der nächste Schritt ist die Prüfung der wirtschaftlichen Gesamtauswirkung.'),
  'Eine negative Externalität liegt vor, wenn eine Tätigkeit anderen Kosten auferlegt, die der Verursacher nicht vollständig in seiner privaten Rechnung trägt. Ein emissionsintensiver Prozess kann etwa heute billig erscheinen, während Schäden außerhalb der Firma anfallen. Regeln, Haftung, Kundenverhalten oder Ressourcenknappheit können einen Teil dieser Belastung später zu privaten Kosten machen. Auch ohne solche Rückwirkung bleibt die gesellschaftliche Wirkung eine eigenständige Frage.',
  'Shareholder Theory stellt die Eigentümerperspektive in den Mittelpunkt; Stakeholder Theory berücksichtigt weitere berechtigte Interessen ausdrücklich. Langfristiger Unternehmenswert kann gute Beziehungen voraussetzen. Das hebt wirkliche Verteilungskonflikte oder rechtliche Pflichten aber nicht automatisch auf. Ein bloßer Verweis auf „alle gewinnen“ ersetzt keine Analyse.'
 ]),
 S('horizons','10. Unterschiedliche Zeithorizonte verändern die Entscheidung','a b',[
  'Ein Mitarbeiter hat oft einen großen Teil seines Einkommens und seiner beruflichen Erfahrung an ein Unternehmen gebunden. Ein breit diversifizierter Aktionär kann Unternehmensrisiko leichter auf viele Anlagen verteilen. Ein Manager mit bald auslaufendem Bonusplan kann wiederum andere Anreize haben als beide. Unterschiede in Konzentration, Zahlungszeitpunkt und Kontrolle erklären Konflikte besser als pauschale Charakterurteile.',
  'Eine Forschungsausgabe senkt möglicherweise den heutigen Gewinn und erhöht erst später die Wettbewerbsfähigkeit. Wird die Führung ausschließlich am aktuellen Ergebnis gemessen, kann sie sinnvolle Ausgaben verschieben. Umgekehrt rechtfertigt der Begriff „langfristig“ nicht jedes unkontrollierte Projekt: Fortschritt, Kapitalbedarf, Abbruchregeln und überprüfbare Zwischenziele bleiben notwendig.',
  'Kreditgeber haben ebenfalls unterschiedliche Horizonte. Eine bald fällige besicherte Schuld kann von einem späteren Klimarisiko weniger direkt betroffen sein als eine lang laufende unbesicherte Anleihe. Trotzdem können schon heute Refinanzierung, Sicherheitenwerte oder Kundenentscheidungen reagieren. Das Risiko verschwindet nicht automatisch, weil der erwartete Schaden nach der eigenen Fälligkeit liegt.',
  'Bei Mehrheitsaktionären kommt ein weiterer Gegensatz hinzu: Eine Transaktion kann dem Mehrheitsaktionär außerhalb der Gesellschaft Vorteile verschaffen und zugleich Minderheitsaktionäre belasten. Die Trennung zwischen Stimmrecht, wirtschaftlichem Anteil und sonstigen Beziehungen aus dem Kapitel Unternehmensformen hilft, diesen Konflikt zu erkennen.'
 ]),
 S('esg-channels','11. ESG von Schlagworten in Wirkungsketten übersetzen','c',[
  'ESG fasst Environmental, Social und Governance zusammen. Für die finanzielle Analyse beginnt die Arbeit nicht mit einem Gesamtscore, sondern mit einem konkreten Vorgang: Welche Ressource, Beziehung oder Entscheidung verändert welche Zahlung, zu welchem Zeitpunkt und unter welchen Bedingungen? Risiken und Chancen gehören beide in die Betrachtung.',
  T(['Faktor','Beispiel einer Wirkungskette','Mögliche Stelle im Modell'],[
   ['Umwelt: Wasserknappheit','Weniger Prozesswasser begrenzt Produktion oder erfordert alternative Versorgung.','Absatzmenge, laufende Kosten, Investitionen und Standortwert.'],
   ['Umwelt: Energieeffizienz','Geringerer Energieeinsatz pro Einheit senkt den Verbrauch, benötigt aber Anfangskapital.','Betriebskosten, Capex und Projektrendite.'],
   ['Soziales: Sicherheit und Qualifikation','Weniger Unfälle und Fluktuation können Ausfälle und Ersatzkosten reduzieren.','Personalaufwand, Produktivität, Versicherungs- und Haftungskosten.'],
   ['Soziales: Datenschutz und Produktqualität','Ein Vorfall kann Kundenverlust, Nachbesserung und Sanktionen auslösen.','Umsatz, Rückstellungen, Cashabfluss und Szenariorisiko.'],
   ['Governance: Kontrolle und Anreize','Unentdeckte Eigeninteressen oder schwache Kontrollen können Fehlallokation begünstigen.','Prognosegüte, Investitionsrendite, Rechtsrisiken und Finanzierungszugang.']
  ],'Die Zuordnung E, S oder G kann sich überschneiden. Entscheidend ist der wirtschaftliche Mechanismus, nicht allein das Etikett.'),
  'Finanzielle Wesentlichkeit bedeutet hier, dass eine Information die wirtschaftliche Beurteilung des Unternehmens oder seiner Wertpapiere beeinflussen kann. Branchen, Standorte, Geschäftsmodelle und Zeithorizonte unterscheiden sich. Wasserverbrauch ist für manche Produktionsstandorte ein unmittelbar kritischer Treiber; bei einer Softwarefirma können Datensicherheit und Personalbindung zentraler sein.',
  'Die IFRS-S1-Perspektive richtet sich auf nachhaltigkeitsbezogene Risiken und Chancen mit möglichen Folgen für Cashflows, Finanzierungszugang oder Kapitalkosten. Ob ein bestimmtes Unternehmen zu einer Veröffentlichung nach einem Standard verpflichtet ist, hängt von den für es geltenden Regeln ab. Die hier erklärte Analyse setzt keine weltweit einheitliche Anwendungspflicht voraus.',
  'Die Wirkung des Unternehmens auf Menschen und Umwelt ist eine weitere Betrachtungsrichtung. Sie kann finanziell zurückwirken, muss es aber nicht sofort tun. Ein Investment mit dem Ziel positiver Wirkung und eine Analyse finanzieller ESG-Risiken beantworten daher unterschiedliche Fragen; beide benötigen ausdrücklich benannte Ziele und Nachweise.'
 ]),
 S('climate','12. Physische Risiken und Übergangsrisiken auseinanderhalten','c',[
  'Physische Klimarisiken wirken durch Ereignisse oder längerfristige Veränderungen: eine Überschwemmung zerstört Anlagen, häufigere Hitze senkt Arbeitsleistung oder anhaltende Trockenheit verändert Wasserverfügbarkeit. Akute und chronische Wirkungen können sich verstärken. Standort, Schutzmaßnahmen und Versicherungsbedingungen beeinflussen die wirtschaftliche Exposition.',
  'Übergangsrisiken entstehen bei der Veränderung hin zu einer emissionsärmeren Wirtschaft, etwa durch Technologie, Nachfrage, Politik oder Haftungsansprüche. Ein angenommener CO₂-Preis verändert Kosten; eine neue Technologie kann Nachfrage nach alten Anlagen verringern. Solche Entwicklungen können zugleich Chancen für effiziente Produkte schaffen. Physischer Schaden und regulatorischer Kostendruck sind getrennte Mechanismen, können aber dieselbe Firma treffen.',
  X('Ein Kostenschock mit teilweise möglicher Weitergabe','Ein eigener Produktionsfall emittiert unverändert 100.000 Tonnen pro Jahr. Der angenommene vollständig zahlungswirksame CO₂-Preis steigt von 50 auf 80 Euro je Tonne. Es gibt keine Freizuteilung. 40 % des Mehrbetrags können ohne Absatzverlust über Preise weitergegeben werden. Der verbleibende Aufwand ist sofort mit 25 % steuerwirksam.',[
   F('\\Delta C_{gross}=100000(80-50)=3000000','Menge mal Preisänderung ergibt zunächst drei Millionen Euro zusätzliche Jahreskosten.',[['\\Delta C_{gross}','Zusätzlicher jährlicher Bruttokostenbetrag vor Weitergabe und Steuer.']]),
   F('\\Delta CF=-3000000(1-0{,}40)(1-0{,}25)=-1350000','Nach 1,2 Millionen zusätzlichem Erlös verbleiben 1,8 Millionen Aufwand; die angenommene Steuerwirkung reduziert den Nettoabfluss auf 1,35 Millionen.',[['\\Delta CF','Jährliche Cashflowänderung nach der ausdrücklich angenommenen Weitergabe und Steuerwirkung.']]),
   'Ohne Weitergabe wären es 2,25 Millionen Nettoabfluss; bei vollständiger Weitergabe und unveränderter Menge wäre der isolierte operative Effekt null. Diese Unterschiede zeigen, warum Emissionsmenge allein die Gewinnwirkung nicht bestimmt.'
  ],'Tatsächlich können Preiselastizität, Wettbewerb, Zertifikate, steuerliche Verlustsituationen und Anpassung der Produktion die Rechnung verändern. Ein belastbares Szenario benennt diese Annahmen.'),
  X('Erwarteter Schaden ist eine Szenariogröße','Ein Standort erleidet im Modell jährlich mit 10 % Wahrscheinlichkeit einen zahlungswirksamen Schaden von 30 Millionen. Eine Schutzmaßnahme senkt diese Wahrscheinlichkeit auf 4 % und kostet jährlich 0,8 Millionen. Schadenhöhe, andere Wirkungen und Steuer werden hier konstant beziehungsweise null gesetzt.',[
   F('\\Delta CF=(0{,}10-0{,}04)\\cdot30-0{,}8=1{,}0','Die erwartete jährliche Schadensminderung beträgt 1,8 Millionen; nach laufenden Schutzkosten verbleibt eine Million erwarteter Vorteil.',[['\\Delta CF','Erwartete jährliche Nettoverbesserung in Millionen.']]),
   'Ein Erwartungswert von drei Millionen vor Schutz bedeutet nicht, dass jedes Jahr drei Millionen bezahlt werden. Die tatsächlichen Modellzustände sind null oder 30 Millionen. Auch die verbleibenden seltenen großen Verluste, Versicherung und Liquiditätsreserven bleiben zu prüfen.'
  ],'Die Zahlen illustrieren die Wirkung einer Annahme. Sie sind keine Schätzung einer realen Naturgefahr.')
 ]),
 S('transition-investment','13. Umweltinvestitionen nach denselben Wertregeln prüfen','c',[
  'Eine Emissionssenkung ist technisch messbar. Ob sie unter gegebenen finanziellen Annahmen Wert schafft, hängt zusätzlich von Investitionsbetrag, Kostenersparnis, Laufzeit, Preis und Risiko ab. Ein positives Umweltmerkmal ersetzt keine Kapitalwertrechnung; umgekehrt bildet der finanzielle Kapitalwert nicht automatisch den gesamten gesellschaftlichen Nutzen ab.',
  X('Wie der CO₂-Preis die Investitionsentscheidung verändert','Eine eigenständige Modellinvestition kostet heute 3,5 Millionen Euro und vermeidet in jedem der nächsten vier Jahre 20.000 zahlungspflichtige Tonnen. Der CO₂-Preis ist in jedem Szenario über vier Jahre konstant. Die Firma behält die volle Ersparnis; keine Preisweitergabe, Mengenänderung, weiteren Betriebs- oder Steuerwirkungen, Abschreibungsvorteile oder Restwerte. Die Ersparnis wird sofort mit 25 % besteuert; Diskontsatz 8 %, Zahlung jeweils am Jahresende.',[
   F('NPV(p)=-I_0+q\\,p(1-\\tau)\\sum_{t=1}^{n}(1+r)^{-t}','Vermiedene Menge mal Preis liefert die jährliche Ersparnis. Nach Steuer wird jede Jahreszahlung separat abgezinst.',[['NPV(p)','Finanzieller Kapitalwert als Funktion des konstanten Preises p.'],['I_0','Heutiger Investitionsbetrag: 3,5 Millionen Euro.'],['q','Jährlich vermiedene zahlungspflichtige Emissionen: 20.000 Tonnen.'],['p','Angenommener Preis in Euro je Tonne.'],['\\tau','Sofort wirksamer Steuersatz auf die Ersparnis: 25 %.'],['n','Vier jährliche Nutzungsperioden.'],['t','Index des jeweiligen Zahlungsjahres.'],['r','Jährlicher Diskontsatz: 8 %.']]),
   T(['CO₂-Preis je Tonne','Jährliche Ersparnis nach Steuer in Mio. €','Barwert der Ersparnisse in Mio. €','Kapitalwert in Mio. €'],[['50 €','0,750','2,484','−1,016'],['80 €','1,200','3,975','0,475'],['110 €','1,650','5,465','1,965']],'Barwertfaktor über vier Jahre bei 8 %: rund 3,31213. Erst nach Abzinsung wird der heutige Einsatz abgezogen.'),
   F('p^*=\\frac{3500000}{20000(1-0{,}25)\\sum_{t=1}^{4}(1{,}08)^{-t}}\\approx70{,}45','Die finanzielle Gewinnschwelle wird durch Gleichsetzen des Kapitalwerts mit null bestimmt.',[['p^*','Konstanter CO₂-Preis in Euro je Tonne, bei dem der Kapitalwert des Modells null ist.'],['t','Zahlungsjahr eins bis vier.']])
  ],'Oberhalb von rund 70,45 Euro ist der Kapitalwert unter diesen Annahmen positiv. Ein volatiler Preis, andere Risiken oder weitere reale Effekte benötigen ein erweitertes Modell.'),
  G({id:'carbon-investment',title:'Technisch gleiche Einsparung, unterschiedlicher Kapitalwert',caption:'3,5 Mio. € Anfangseinsatz; jährlich 20.000 vermiedene Tonnen über vier Jahre; 25 % Steuer; 8 % Diskontsatz. Die übrigen Annahmen stehen im Rechenfall.',reading:'Bei 50 Euro pro Tonne ist der Kapitalwert etwa minus 1,016 Mio. Euro, bei 80 Euro plus 0,475 Mio. Euro. Die Nulllinie wird bei etwa 70,45 Euro erreicht. Der Zusammenhang ist in diesem konstanten Modell linear; diese Gerade ist keine Prognose des CO₂-Preises.',plot:{x:[0,120],y:[-4,3],xTicks:[0,20,40,60,80,100,120],xLabel:'Konstanter Preis in Euro je Tonne',yLabel:'Kapitalwert in Mio. Euro',series:[{name:'Kapitalwert',points:Array.from({length:25},(_,i)=>{const p=i*5;return[p,-3.5+.02*p*.75*annuity];})},{name:'Nullgrenze',dash:'5 4',points:[[0,0],[120,0]]}],marks:[{x:3.5/(.02*.75*annuity),y:0,label:'70,45 €/t',dx:8,dy:22}]}})
 ]),
 S('social-governance','14. Soziale und Governancefaktoren konkret beurteilen','b c',[
  'Soziale Faktoren betreffen unter anderem Arbeitsbedingungen, Qualifikation, Sicherheit, Menschenrechte, Produktverantwortung und Kundendaten. Die analytische Frage lautet, wie sich ein beobachtbarer Zustand auf Beschäftigte, Kunden und die wirtschaftliche Zukunft auswirkt. Eine niedrige Unfallquote benötigt beispielsweise die Zahl der Arbeitsstunden als Bezugsbasis und eine verlässliche Meldungskultur.',
  X('Eine Personalmaßnahme wirkt über mehrere Treiber','Ein Unternehmen ersetzt bisher 200 Beschäftigte pro Jahr. Durchschnittliche zahlungswirksame Ersatzkosten betragen 5.000 Euro pro Person. Ein dauerhaftes Programm kostet jährlich 600.000 Euro, senkt Ersatzfälle auf 120 und vermeidet zusätzlich nachweisbar 300.000 Euro Ausschuss pro Jahr. Kein Anfangseinsatz, keine Überschneidung der beiden Ersparnisse und keine Steuern in diesem Fall.',[
   F('\\Delta CF=(200-120)\\cdot5000+300000-600000=100000','400.000 Euro geringere Ersatzkosten plus 300.000 Euro weniger Ausschuss decken 600.000 Euro laufende Programmkosten und lassen 100.000 Euro übrig.',[['\\Delta CF','Jährliche Nettoverbesserung der betrachteten Zahlungen.']]),
   'Die niedriger erscheinende Personalfluktuation allein wäre kein ausreichender Wirkungsnachweis. Zu prüfen sind Gesamtbelegschaft, Konjunktur, freiwillige und unfreiwillige Abgänge sowie die Abgrenzung der Ersatz- und Ausschusskosten.'
  ],'Ein besserer sozialer Zustand kann einen finanziellen Nutzen haben. Dessen Höhe wird anhand konkreter Treiber geschätzt, nicht aus einem allgemeinen Gütesiegel abgelesen.'),
  'Governance betrifft die Regeln und Kontrollen, nach denen Entscheidungen getroffen, überwacht und verantwortet werden. Zu prüfen sind etwa Board-Kompetenz und Unabhängigkeit, Interessenkonflikte, Kontrollrechte, Vergütung, Minderheitenschutz, Berichtsqualität und der Umgang mit Fehlverhalten. Ein formal unabhängiges Mitglied ohne Zeit, Fachwissen oder Zugang zu Informationen kann seine Aufgabe nur begrenzt erfüllen.',
  'Governance wirkt außerdem auf die Glaubwürdigkeit von Umwelt- und Sozialangaben: Wer definiert eine Kennzahl, wer prüft die Rohdaten und welche Vergütung hängt vom Ergebnis ab? Eine schöne Verbesserung kann aus geänderter Abgrenzung, ausgelagerter Produktion oder selektiver Berichterstattung stammen. Deshalb gehören Datenkontrolle und wirtschaftliche Bewertung zusammen.'
 ]),
 S('measurement','15. Kennzahlen und Ratings kritisch lesen','c',[
  'Ein ESG-Rating verdichtet eine Methodik, keine allgemeingültige Wahrheit über ein Unternehmen. Anbieter können unterschiedliche Themen, Gewichte, Vergleichsgruppen, Datenstände und Schätzungen verwenden. Ein hoher Wert kann beispielsweise gute relative Risikosteuerung in einer belastenden Branche ausdrücken; er beweist nicht automatisch geringe absolute Umweltwirkung oder hohe erwartete Aktienrendite.',
  X('Sinkende Intensität bei steigender Gesamtbelastung','Eine Firma emittiert im Ausgangsjahr 100.000 Tonnen bei 100 Millionen Euro Umsatz. Im Folgejahr emittiert sie 110.000 Tonnen bei 125 Millionen Euro Umsatz. Gleiche Erfassungsgrenzen in beiden Jahren.',[
   F('I_0=\\frac{100000}{100}=1000,\\quad I_1=\\frac{110000}{125}=880','Die Intensität fällt von 1.000 auf 880 Tonnen je Million Euro Umsatz.',[['I_0','Emissionsintensität im Ausgangsjahr, Tonnen je Million Euro Umsatz.'],['I_1','Emissionsintensität im Folgejahr auf derselben Basis.']]),
   F('g_I=\\frac{880}{1000}-1=-12\\%,\\qquad g_A=\\frac{110000}{100000}-1=10\\%','Die relative Kennzahl verbessert sich um zwölf Prozent, während die absoluten Emissionen um zehn Prozent steigen.',[['g_I','Relative Veränderung der Emissionsintensität.'],['g_A','Relative Veränderung der absoluten Emissionen.']]),
   'Beide Aussagen können gleichzeitig richtig sein. Preissteigerungen im Umsatz, eine Akquisition oder ein veränderter Produktmix können die Intensität zusätzlich bewegen. Für technische Effizienz kann eine physische Produktionsbasis geeigneter sein als nominaler Umsatz.'
  ],'Eine Kennzahl benötigt Zähler, Nenner, Zeitraum, Abgrenzung und eine Erklärung der Veränderung.'),
  'Greenwashing bezeichnet irreführende Darstellung ökologischer Eigenschaften oder Wirkungen. Die Prüfung sucht nach belastbaren Ausgangsdaten, klaren Zielgrößen, vollständig erfassten Aktivitäten und nachvollziehbarer Entwicklung. Ein angekündigtes Ziel ist noch keine erreichte Wirkung. Ein niedriger ESG-Score ist umgekehrt nicht ohne Prüfung ein Beleg absichtlicher Täuschung.',
  'Ergänze Unternehmensangaben durch geeignete externe Quellen und untersuche Widersprüche. Fehlende Daten sind nicht dasselbe wie nachgewiesene geringe Exposition. Schätzwerte benötigen eine erkennbare Unsicherheit; ein Ratingwechsel kann auch aus geänderter Methodik statt aus verändertem Unternehmensverhalten entstehen.'
 ]),
 S('valuation','16. Vom Befund zur Bewertung ohne Doppelzählung','a b c',[
  'Ein relevanter ESG-Befund wird in einen konkreten Bewertungsbaustein übersetzt: Absatz, Marge, Investitionsbedarf, Working Capital, mögliche Verluste oder Finanzierung. Die Wirkung muss zur bewerteten Anspruchsklasse passen. Ein geringerer Unternehmensbetrag kann zuerst den Aktienpuffer verkleinern und erst in schlechteren Zuständen zu Kreditausfällen führen.',
  F('V_0=\\sum_{t=1}^{n}\\frac{\\mathbb{E}[CF_t]}{(1+r)^t}','Erwartete Zahlungen werden mit einem zum Anspruch und Risiko passenden Satz auf heute abgezinst. Dieses Modell zeigt den Übertragungsweg; es ersetzt keine vollständige Bewertungsanalyse.',[['V_0','Heutiger Modellwert des betrachteten Anspruchs ohne weiteren Restwert.'],['\\mathbb{E}[CF_t]','Erwartete, dem betrachteten Anspruch zurechenbare Zahlung im Jahr t.'],['r','Für Zahlungsart, Währung und Risiko konsistenter jährlicher Diskontsatz.'],['t','Zahlungsjahr.'],['n','Letztes im Modell enthaltenes Zahlungsjahr.']]),
  'Wird ein erwarteter Schaden bereits als verminderter Cashflow erfasst, darf derselbe erwartete Betrag nicht noch einmal pauschal vom Ergebnis abgezogen werden. Eine zusätzliche Änderung des Diskontsatzes kann bei veränderter systematischer Risikoexposition oder verlangter Rendite begründet sein; sie braucht eine eigene Begründung. „ESG-Risiko“ auf beiden Seiten als pauschaler Sicherheitsabschlag reicht nicht.',
  T(['Analyseschritt','Prüfbare Frage'],[['Anspruch','Bewerte ich Aktie, konkrete Anleihe oder gesamtes operatives Geschäft?'],['Exposition','Welche Aktivität, Region, Beziehung und Laufzeit ist betroffen?'],['Übertragung','Welche Menge, welcher Preis, welche Zahlung oder welche Ausfallwahrscheinlichkeit ändert sich?'],['Reaktion','Kann das Unternehmen anpassen, versichern, investieren oder Kosten weitergeben?'],['Daten','Sind Messgrenzen, Basisjahr, Quellen und Unsicherheit dokumentiert?'],['Modell','Sind Cashflows, Diskontsatz und Alternativszenarien konsistent und ohne doppelte Belastung?'],['Entscheidung','Welcher heutige Preis, welche Verpflichtung und welches Mandat stehen der Einschätzung gegenüber?']],'Ein besseres Unternehmen ist nicht zu jedem Preis die bessere Anlage. Erwartete Entwicklung und bereits eingepreiste Erwartungen müssen verglichen werden.'),
  'Eine Analyse endet deshalb mit einer begründeten Einschätzung und den Annahmen, die diese verändern würden. Ein ESG-Etikett garantiert weder eine bestimmte Rendite noch die Erfüllung eines Wirkungsziels. Ebenso ersetzt die stärkere Beachtung einer Gruppe nicht die Prüfung der Ansprüche und Rechte anderer Beteiligter.'
 ])
],related:[
 {unit:'issuer-forms',section:'voting',label:'Wirtschaftliche Beteiligung und Kontrolle unterscheiden'},
 {unit:'issuer-forms',section:'liability',label:'Beschränkte Haftung und zusätzliche Garantien'},
 {unit:'forecasting',section:'funding',label:'Cashflowannahmen bis zum Finanzierungsbedarf verfolgen'},
 {unit:'ratios',section:'solvency',label:'Verschuldung und Deckung als Gläubigersignale'}
],sources:[
 {title:'CFA Institute: Level I 2027, Lernziele Corporate Issuers',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=9'},
 {title:'CFA Institute: Investors and Other Stakeholders, Grundbegriffe und Lernziele',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/investors-and-other-stakeholders'},
 {title:'OECD: G20/OECD Principles 2023, Stakeholder, Nachhaltigkeit und Widerstandsfähigkeit',url:'https://www.oecd.org/en/publications/2023/09/g20-oecd-principles-of-corporate-governance-2023_60836fcb/full-report/component-9.html'},
 {title:'IFRS Foundation: IFRS S1, finanzielle Nachhaltigkeitsinformationen',url:'https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s1-general-requirements/'},
 {title:'IFRS Foundation: IFRS S2, physische Risiken, Übergangsrisiken und Chancen',url:'https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s2-climate-related-disclosures/'},
 {title:'IFRS Foundation: SASB Standards und branchenspezifische Analyse',url:'https://www.ifrs.org/issued-standards/sasb-standards/'},
 {title:'CFA Institute: ESG Considerations in Investment Analysis, ergänzende Vertiefung',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/esg-considerations-investment-analysis'},
 {title:'CFA Institute: Methodik und Unterschiede von ESG-Ratings',url:'https://www.cfainstitute.org/insights/articles/the-role-and-rise-of-esg-ratings'}
],review:{status:'draft',date:'2026-09-26',note:'Eigene Rechenfälle zu Rangfolge, Ausfall, Risikoübertragung, Unterinvestition und finanziellen ESG-Wirkungen. Endauszahlungen und heutige Marktpreise werden getrennt; alle Bewertungsannahmen und Symbolbedeutungen sind ausdrücklich angegeben. Abschließender fachlicher Gesamtaudit bleibt offen.'}};
