const {F,T,X,S,G}=require('../author.cjs');
const fixedPV=50.55/1.09+53.583/1.09**2+56.79798/1.09**3;
const stableValue=(g,r=.12,k=.09)=> (fixedPV+64.4041902*(1-g/r)/(k-g)/1.09**3+30)/10;
module.exports={id:'valuation-model',intro:[
 'Ein Abschlussmodell übersetzt eine Geschäftsthese in künftige Erträge, Vermögensbestände und Zahlungen. Erst ein dazu passendes Bewertungsmodell übersetzt diese Ergebnisse in einen heutigen Wertanspruch. Der entscheidende Schritt besteht nicht darin, eine Gewinnzeile in eine Formel einzusetzen: Wachstum beansprucht Kapital, Finanzierung verteilt die Zahlungen und die langfristige Phase muss wirtschaftlich neu begründet werden.',
 'Dieses Kapitel vertieft die drei Lernziele von Financial Statement Forecasting in Equity Valuation für CFA Level I 2027. Das Kapitel zum integrierten Abschlussmodell erklärt die Prognosekonstruktion ausführlich; hier steht ihre vollständige Verbindung zur Aktienbewertung im Mittelpunkt. Der eigene Fall Nordlicht enthält drei Detailjahre, eine gesonderte stabile Phase, eine konsistente Ausschüttungspolitik und Gegenprüfungen über Bilanz, direkte Zahlungen und Residual Income. Alle Beträge des Falls sind Millionen Euro, außer ausdrücklich angegebenen Werten je Aktie. Ergänzende Herleitungen dienen dem Verständnis; sie sind keine zusätzliche offizielle Prüfungsstoffliste.'
],sections:[
 S('scope','1. Prognose, Bewertung und Entscheidung auseinanderhalten','a b c',[
  'Eine Umsatzprognose beantwortet, welche Erlöse unter bestimmten Annahmen entstehen. Eine Gewinnprognose berücksichtigt die dafür verbrauchten Ressourcen. Eine Zahlungsprognose berücksichtigt zusätzlich, wann Kunden zahlen, Lieferanten Kredit geben und Investitionen bezahlt werden. Eine Bewertung fragt schließlich, was die passend abgegrenzten künftigen Zahlungen heute wert sind. Diese Ebenen gehören zusammen, sind aber nicht austauschbar.',
  T(['Ebene','Konkrete Frage','Typischer Fehlschluss'],[['Geschäftsthese','Welche Kunden, Mengen, Preise und Wettbewerbsvorteile tragen die Erwartungen?','Managementziel ist bereits eine gesicherte Prognose.'],['Abschlussmodell','Welche Ergebnis-, Bestands- und Zahlungsfolgen hat die These?','Höherer Gewinn ist automatisch mehr ausschüttbares Geld.'],['Bewertungsmodell','Welcher Kapitalanspruch erhält welche Zahlung bei welchem Risiko?','FCFF wird direkt zum Stammaktienwert.'],['Entscheidung','Wie verhält sich ein unsicherer Wertbereich zum beobachteten Preis?','Ein positiver Modellabstand garantiert eine realisierte Rendite.']],'Jede Ebene benötigt eigene Begründungen und eigene Kontrollen.'),
  'Ein Modell kann für Bewertung, Finanzierung, Stressanalyse, Ergebnisüberraschungen und die Überprüfung einer Investmentthese genutzt werden. Die Verwendungsfrage bestimmt die nötige Auflösung: Bei knapper Liquidität sind Monatszahlungen wichtig; bei langfristiger Aktienbewertung sind nachhaltige Marge, Kapitalbindung und Kapitalrendite zentral. Dieselbe Jahresprognose erfüllt nicht automatisch beide Zwecke.'
 ]),
 S('architecture','2. Die Kette vom Geschäftsmodell zum Wertanspruch','a c',[
  F('S_t\\longrightarrow EBIT_t\\longrightarrow NOPAT_t\\longrightarrow FCFF_t\\longrightarrow V_{op,0}\\longrightarrow E_{common,0}\\longrightarrow v_0','Die Kette zeigt wirtschaftliche Abhängigkeiten, keine Gleichheitszeichen. Umsatz führt über Kosten und Steuern zum operativen Nachsteuerergebnis; benötigte Investitionen führen zum freien operativen Cashflow. Erst Diskontierung und Anspruchsbrücke führen zum Stammaktienwert.',[['t','Jahresindex; null ist der Bewertungsstichtag.'],['S_t','Umsatz der Periode.'],['EBIT_t','Operatives Ergebnis nach Abschreibung, vor Zins und Steuer.'],['NOPAT_t','Operatives Nachsteuerergebnis vor Finanzierung.'],['FCFF_t','Freier Cashflow für die operativen Kapitalgeber.'],['V_{op,0}','Heutiger Wert des abgegrenzten operativen Geschäfts.'],['E_{common,0}','Heutiger Wert des passenden Stammkapitalanspruchs.'],['v_0','Wert je betrachteter Stammaktie.'],['\\longrightarrow','Wirtschaftlicher Ableitungsschritt; keine numerische Identität.']]),
  'Ein Abschlussprognosemodell legt Gewinn- und Verlustrechnung, Bilanz und Cashflowrechnung nicht als drei unabhängige Prognosen an. Eine längere Kundenzahlungsfrist verändert Forderungen und Kundeneinzahlungen, zunächst aber weder verkauften Umsatz noch Gewinn. Ein Anlagenzugang verändert Capex, Anlagen und spätere Abschreibung. Eine neue Schuld verändert verfügbare Liquidität, Zinsen und den Eigentümeranspruch; sie ist kein operativer Umsatz.',
  'Ein transparentes Modell trennt historische Ausgangsdaten, Schätzannahmen, berechnete Abschlüsse, Bewertungsannahmen und Prüfergebnisse. Jeder entscheidende Input besitzt Datum, Quelle, Definition und Begründung. Ein gewünschter Aktienwert wird nicht als versteckte Ursache der Umsätze verwendet.'
 ]),
 S('information','3. Die Ausgangsbasis wirtschaftlich bereinigen','a b',[
  'Historische Zahlen sind Ausgangsinformationen, keine Zukunftsgarantie. Der Analyst prüft Berichtsstandard, Konsolidierung, Währung, Geschäftsjahr, Akquisitionen, aufgegebene Bereiche und einmalige Effekte. Eine Übernahme kann Umsatzwachstum ohne organisches Mengenwachstum erzeugen. Wechselkurse können Berichtswachstum ohne höhere lokale Verkäufe erzeugen. Ein aktueller Marktwert darf nicht mit einer vor dem Stichtag unbekannten Gewinnzahl in einen historischen Test gestellt werden.',
  X('Die Ausgangsmarge verändert die gesamte Prognose','Berichteter Umsatz 400 und EBIT 60 enthalten einen isolierten operativen Veräußerungsgewinn 20. Der Steuersatz ist im Beispiel 25 Prozent; die Veräußerung betrifft keinen fortgesetzten Betriebsbeitrag.',[
   F('EBIT_{norm}=60-20=40,\\quad m_{norm}=40/400=10\\%','Der fortgesetzte Betrieb besitzt hier zehn statt fünfzehn Prozent EBIT-Marge.',[['EBIT_{norm}','Für die angegebene Zukunftsbasis bereinigtes operatives Ergebnis.'],['m_{norm}','Normalisierte EBIT-Marge.']]),
   F('\\Delta NOPAT=(60-40)(1-0{,}25)=15','Unbereinigte Fortschreibung würde bereits den ersten jährlichen Nachsteuerbetriebsertrag um fünfzehn überschätzen.',[['\\Delta NOPAT','Differenz der beiden Nachsteuerertragsbasen.']]),
   'Ob ein Aufwand wirklich einmalig ist, folgt nicht allein aus seinem Etikett. Wiederholte Restrukturierung, wiederkehrende Kundenakquisition oder nötige Forschung dürfen nicht nur deshalb entfernt werden, weil das Ergebnis angenehmer wird.'
  ],'Prognosebereinigung wird offengelegt und ersetzt weder den veröffentlichten Abschluss noch eine Fehlerkorrektur.'),
  'Die Ausgangsbilanz muss denselben Betrieb abbilden wie das bereinigte Ergebnis. Verkauftes Vermögen kann nicht gleichzeitig weiter Einnahmen und einen zusätzlichen Verkaufserlös liefern. Investitionen in immaterielle Ressourcen bleiben wirtschaftlich relevant, auch wenn die Rechnungslegung sie sofort als Aufwand erfasst.'
 ]),
 S('model-choice','4. Das Modell folgt dem Unternehmen','a b',[
  T(['Unternehmen','Besonders geeignete Modellbausteine','Grenze pauschaler Umsatzquoten'],[['Reifer Industriebetrieb','Mengen und Preise, Kapazität, Anlagenersatz, Working Capital, FCFF und Anspruchsbrücke.','Kapazitätssprünge und Anlagenalter gehen in Durchschnittsquoten verloren.'],['Bank oder Versicherer','Erträge, Kredit-/Schadenrisiko, erforderliches Eigenkapital, Ausschüttungsfähigkeit; häufig direkte Eigenkapital- oder Residual-Income-Modelle.','Einlagen und viele Finanzierungspositionen gehören zum operativen Geschäft; industrielles FCFF ist schwerer sinnvoll abzugrenzen.'],['Junges Unternehmen','Kundenentwicklung, Stückökonomie, Skalierung, Zahlungsbedarf, Finanzierung und künftige Aktienzahl.','Heute negative Gewinne erlauben kein sinnvolles positives KGV; Finanzierung kann die vorhandenen Eigentümer verwässern.'],['Zyklischer oder Rohstoffbetrieb','Menge, Preiszyklus, Kostenkurve, Normalisierung und Reserven/Anlagen.','Der Hochpunkt ist keine dauerhafte Marge; endliche Ressourcen erlauben nicht automatisch ewiges Wachstum.'],['Immobiliengesellschaft','Objektmieten, Leerstand, Betriebskosten, Ersatzinvestitionen, Projektfinanzierung.','NOI ist vor Finanzierung und nicht automatisch Eigentümercashflow.'],['Konzern mit verschiedenen Sparten','Spartenweise Treiber und Werte, zentrale Kosten, nicht operative Beteiligungen, Tochteransprüche.','Ein einziger Multiplikator kann unterschiedliche Risiken und Anspruchsgrenzen verdecken.']],'Die Modellwahl betrifft sowohl Prognosekonstruktion als auch Bewertungsanspruch.'),
  X('Bankwachstum benötigt Eigentümerkapital','Ein vereinfachter Bankfall hat Anfangseigenkapital 1.000, erwarteten Gewinn 120 und benötigt zur unveränderten Kapitalausstattung am Jahresende 1.100. Keine sonstigen Eigenkapitalbewegungen; der Gewinn ist nach allen modellierten operativen Kosten.',[
   F('D_1=NI_1-(B_1-B_0)=120-100=20','Nur zwanzig können unter den angegebenen Kapitalanforderungen ausgeschüttet werden.',[['D_1','Verfügbare Ausschüttung der Periode.'],['NI_1','Gewinn des Stammkapitalumfangs.'],['B_0,B_1','Anfangs- und benötigtes Endeigenkapital.']]),
   'Die Betrachtung von 120 als vollständig verfügbarem FCFE übersieht die Kapitalbindung. Tatsächliche regulatorische und vertragliche Ausschüttungsbeschränkungen können die verfügbare Zahlung zusätzlich begrenzen.'
  ],'Eine höhere Bilanzsumme ist keine kostenlose Quelle höheren Eigentümerwerts.')
 ]),
 S('revenue','5. Umsatz mit überprüfbaren Ursachen prognostizieren','a b',[
  F('S_t=Q_t p_t,\\qquad 1+u_t=(1+u_{Q,t})(1+u_{p,t})','Bei einem homogenen Produkt entsteht Umsatz aus Menge und realisiertem Stückpreis. Mengen- und Preisänderung wirken einschließlich ihres Kreuzterms.',[['S_t','Umsatz einer Periode.'],['Q_t','Verkaufte Einheiten.'],['p_t','Durchschnittlich realisierter Preis je Einheit.'],['u_t,u_{Q,t},u_{p,t}','Umsatz-, Mengen- und Preiswachstum als Dezimalraten.']]),
  F('S_t=\\sum_j Q_{j,t}p_{j,t}','Mehrere Produkte oder Segmente erhalten getrennte Mengen und Preise. Eine veränderte Mischung kann den Gesamtpreis verändern, ohne dass ein einzelner Produktpreis steigt.',[['S_t','Gesamter abgegrenzter Umsatz.'],['j','Produkt- oder Segmentindex.'],['Q_{j,t},p_{j,t}','Menge und Preis des jeweiligen Segments.'],['\\sum','Summe über alle erfassten Segmente.']]),
  X('Preissteigerung bei Mengenrückgang','Ein Produkt verkauft zuvor 100 Einheiten zu fünf. Nun sinkt die Menge um vier Prozent und der Preis steigt um zehn Prozent.',[
   F('S_1=100(1-0{,}04)\\cdot5(1+0{,}10)=528,\\qquad u_1=1{,}056-1=5{,}6\\%','Sechs Prozent als bloße Addition wäre zu hoch, weil der höhere Preis auf weniger Einheiten wirkt.',[['S_1','Neuer Umsatz.'],['u_1','Tatsächliches Umsatzwachstum dieses Falls.']])
  ],'Das Umsatzwachstum kann trotz sinkender Menge positiv sein. Ob die Preissteigerung dauerhaft trägt, ist eine Wettbewerbsfrage.'),
  'Top-down-Prognosen beginnen bei Marktgröße und Marktanteil; Bottom-up-Prognosen bei Kunden, Filialen, Kapazität oder Aufträgen. Beide sollten aufeinander abgestimmt werden. Ein kleiner Betrieb kann zeitweise schneller als der Markt wachsen; ein riesiger Marktführer kann nicht endlos Marktanteil gewinnen. Auftragsbestand ist nur dann Umsatz, wenn Leistung, Zeitplan und Stornorisiken die Umwandlung tragen.'
 ]),
 S('costs','6. Marge, Kostenstruktur und operative Hebelwirkung','a b c',[
  F('EBIT_t=S_t-C_{var,t}-C_{fix,t}-DA_t,\\qquad m_t=\\frac{EBIT_t}{S_t}','Variable, feste und abschreibungsbedingte Kosten werden wirtschaftlich getrennt. Eine konstante Marge ist eine starke Zusammenfassung dieser verschiedenen Entwicklungen.',[['EBIT_t','Operativer Gewinn vor Zinsen und Steuern.'],['S_t','Umsatz größer null.'],['C_{var,t},C_{fix,t}','Variable und feste operative Aufwendungen ohne die gesonderte Abschreibung.'],['DA_t','Abschreibung und Amortisation der Periode.'],['m_t','EBIT-Marge.']]),
  X('Mehr Umsatz mit konstanten Fixkosten','Variable Kosten entsprechen sechzig Prozent des Umsatzes, feste Kosten einschließlich hier fixer Abschreibung 120. Der Umsatz steigt von 400 auf 440; keine neue Kapazitätsstufe wird ausgelöst.',[
   F('EBIT_0=400\\cdot0{,}4-120=40,\\quad EBIT_1=440\\cdot0{,}4-120=56','Vierzig zusätzlicher Umsatz liefern sechzehn zusätzlichen Deckungsbeitrag.',[['EBIT_0,EBIT_1','Operatives Ergebnis vor und nach der Umsatzänderung.']]),
   F('m_0=40/400=10\\%,\\quad m_1=56/440\\approx12{,}7273\\%','Eine konstante Zehnprozentmarge würde den erhöhten Gewinnbeitrag der vorhandenen Kapazität übersehen.',[['m_0,m_1','Die beiden EBIT-Margen.']])
  ],'Die umgekehrte Wirkung verschärft Gewinnrückgänge. Wird eine neue Fabrik nötig, sind die Fixkosten nicht mehr konstant.'),
  'Preissteigerung ist nicht automatisch Margensteigerung: Löhne, Energie, Beschaffung und Anlagenersatz können schneller teurer werden. Eine Bilanzierungsänderung kann EBIT oder EBITDA verändern, ohne eine entsprechende Verbesserung der Zahlungen zu erzeugen. Für Bewertung zählt die nachhaltig erreichbare wirtschaftliche Leistung.'
 ]),
 S('working-capital','7. Operatives Working Capital verbindet Bestände und Zahlungen','a b c',[
  F('WC_t=AR_t+Inv_t-AP_t,\\qquad \\Delta WC_t=WC_t-WC_{t-1}','Das vereinfachte operative Working Capital bindet Mittel in Forderungen und Vorräten, abzüglich Lieferantenfinanzierung. Sein Anstieg ist eine Mittelbindung, sein Rückgang setzt Mittel frei.',[['WC_t','Nicht liquide, nicht zinstragende operative Nettokapitalbindung.'],['AR_t','Operative Kundenforderungen.'],['Inv_t','Vorräte.'],['AP_t','Operative Lieferantenverbindlichkeiten.'],['\\Delta WC_t','Bestandsveränderung über die Periode.'],['t,t-1','Periodenende und vorheriges Periodenende.']]),
  F('AR_t\\approx S_t\\frac{DSO_t}{365},\\quad Inv_t\\approx COGS_t\\frac{DIO_t}{365},\\quad AP_t\\approx Purch_t\\frac{DPO_t}{365}','Tagesannahmen können Bestände erklären. Die Relationen sind Näherungen bei passenden gleichmäßigen Strömen; Schlussbestände, Durchschnittsbestände und Saisonhöhen sind nicht beliebig austauschbar.',[['AR_t,Inv_t,AP_t','Prognostizierte operative Bestände.'],['S_t,COGS_t,Purch_t','Jahresumsatz, Warenverbrauch und Einkauf auf jeweils passender Basis.'],['DSO_t,DIO_t,DPO_t','Forderungs-, Vorrats- und Zahlungstage unter der gewählten Konvention.'],['365','Hier verwendete Tagebasis; andere Konventionen sind ausdrücklich anzugeben.'],['\\approx','Näherung, keine universelle Bestandsidentität.']]),
  'Liquide Mittel werden im gewöhnlichen nicht liquiden Working Capital für FCFF nicht mitgerechnet. Zinsschulden gehören in die Finanzierungsplanung. Für den Betrieb notwendige Cashbestände oder andere operative Abgrenzungen können eine gesonderte sachgerechte Behandlung benötigen. Überflüssiges Cash wird erst in der Wertbrücke behandelt.',
  X('Die Quote verändert sich, nicht nur der Umsatz','Anfangsumsatz 500, operatives Working Capital 100. Der Umsatz steigt auf 530. Mit Quote zwanzig Prozent beträgt das Ende-WC 106; mit Quote fünfundzwanzig Prozent 132,5.',[
   F('\\Delta WC_A=106-100=6,\\quad \\Delta WC_B=132{,}5-100=32{,}5','Die verschlechterte Quote bindet zusätzlich 26,5 Mittel im selben Jahr.',[['\\Delta WC_A,\\Delta WC_B','Mittelbindung unter der alten und neuen Schlussquote.']]),
   'Ein höherer Forderungsbestand ist kein zusätzlicher Gewinn; er kann auf schlechteren Zahlungseingang hinweisen. Eine einmalige Verbesserung der Quote darf nicht als jährlich wiederholbare Freisetzung derselben Mittel fortgeschrieben werden.'
  ],'Wachstum und Bestandsqualität beeinflussen den freien Cashflow gemeinsam.'),
  'Negatives Working Capital kann bei Vorauszahlung durch Kunden oder langem Lieferantenkredit wirtschaftlich nachhaltig sein. Es ist weder automatisch ein Fehler noch eine kostenlose unbeschränkte Finanzierung. Die Bedingungen müssen bei Expansion, Nachfragerückgang und Vertrauensverlust weiter tragfähig sein.'
 ]),
 S('assets','8. Anlagenplanung: Abschreibung und Investition sind verschieden','a b c',[
  F('PPE_t=PPE_{t-1}+Capex_t-DA_t','Ohne Abgänge, Wertminderungen, Neubewertung oder Wechselkurseffekte überleitet die Gleichung Anlagenbuchwerte. Andere Bewegungen müssen bei einem echten Unternehmen zusätzlich separat erfasst werden.',[['PPE_t,PPE_{t-1}','Nettoanlagenbuchwerte am Ende und Anfang.'],['Capex_t','Hier vollständig zahlungswirksame aktivierte Investitionen.'],['DA_t','Buchmäßiger Werteverzehr der erfassten Anlagen.']]),
  F('Capex_t=(PPE_t-PPE_{t-1})+DA_t','Aus dem gewünschten Endbestand und der geplanten Abschreibung ergibt sich in diesem einfachen Anlagenmodell die Investition. Die Addition der Abschreibung zur Cashflowrechnung allein beseitigt den Ersatzbedarf nicht.',[['Capex_t','Investitionszahlung der Periode.'],['PPE_t-PPE_{t-1}','Zuwachs des Nettoanlagenbuchwerts.'],['DA_t','Abschreibung im übergeleiteten Anlagenumfang.']]),
  'Eine Anlagenquote als Verhältnis von Anlagenbuchwert zu Umsatz kann ein hilfreicher Planungsansatz sein, ist aber keine physische Kapazitätsprüfung. Alte voll abgeschriebene Maschinen können weiter produzieren; neue Anlagen können teuer sein und erst später Auslastung erreichen. Ein echtes Anlagenmodell benötigt Bauzeit, Inbetriebnahme, Nutzungsdauer, Ersatz, Stilllegung und gegebenenfalls Anlagenjahrgänge.',
  X('Abschreibung kann in der freien Zahlung vollständig verschwinden','NOPAT 60, Abschreibung 30, Nettoanlagenzuwachs 15 und Working-Capital-Zuwachs sechs. Ohne sonstige Anlagenbewegungen.',[
   F('Capex=30+15=45,\\quad FCFF=60+30-45-6=39','Die Nichtzahlung Abschreibung wird addiert, doch die tatsächliche Investition wird abgezogen.',[['Capex','Investition in Millionen.'],['FCFF','Freie operative Jahreszahlung.']]),
   F('FCFF=NOPAT-\\Delta PPE-\\Delta WC=60-15-6=39','Nach der vollständigen Überleitung entspricht die freie Zahlung dem Gewinn nach operativer Nettoinvestition.',[['NOPAT','Operativer Nachsteuergewinn.'],['\\Delta PPE,\\Delta WC','Nettozuwächse des Anlage- und Working-Capital-Bestands.']])
  ],'Die verkürzte zweite Formel gilt nur unter der ausdrücklich einfachen Anlagen- und Abgrenzungsstruktur.')
 ]),
 S('tax-financing','9. Steuern, Zinsen und Finanzierung konsistent behandeln','a b c',[
  F('NOPAT_t=EBIT_t(1-\\tau),\\qquad NI_t=(EBIT_t-I_t)(1-\\tau)','Die einfache Steuerkonvention unterstellt sofortige volle Besteuerung und nutzbare Zinsabzüge. NOPAT misst Betrieb vor Finanzierung; NI enthält die Zinsverteilung.',[['NOPAT_t','Operativer Nachsteuerertrag.'],['EBIT_t','Betriebsertrag vor Finanzierung und Steuer.'],['NI_t','Gewinn nach Zinsen und Steuern im vereinfachten Eigentümerumfang.'],['I_t','Zinsaufwand.'],['\\tau','Einheitlicher Modellsteuersatz als Dezimalzahl.']]),
  F('FCFF_t=NI_t+I_t(1-\\tau)+DA_t-Capex_t-\\Delta WC_t','Aus dem Gewinn wird der Nachsteuerzins entfernt, um die Zahlung vor Verteilung an Fremd- und Eigenkapitalgeber zu erhalten.',[['FCFF_t','Freier operativer Cashflow.'],['NI_t','Gewinn nach Zins und Steuer.'],['I_t(1-\\tau)','Nachsteuerzins unter dem nutzbaren Steuerabzug.'],['DA_t,Capex_t,\\Delta WC_t','Nicht zahlungswirksame Abschreibung, Investition und zusätzliche operative Bestandsbindung.']]),
  F('FCFE_t=FCFF_t-I_t(1-\\tau)+NB_t','Eigentümer erhalten die freie Zahlung nach Nachsteuerzins und einschließlich Nettoschuldenaufnahme. Neue Kredite erhöhen den heutigen FCFE, sind aber kein frei geschaffener operativer Wert.',[['FCFE_t','Freier Cashflow für den erfassten Eigenkapitalanspruch.'],['FCFF_t','Freier Cashflow vor Finanzierungsverteilung.'],['I_t(1-\\tau)','Passender Nachsteuerzins.'],['NB_t','Neue zinstragende Schulden minus Tilgung der Periode.']]),
  'Im echten Abschluss ist Steueraufwand nicht immer Steuerzahlung. Verlustvorträge, latente Steuern, verschiedene Länder und unbrauchbare Zinsabzüge verlangen eine eigene Überleitung. Eine negative steuerliche Bemessungsgrundlage erzeugt nicht automatisch eine sofortige Erstattung. Werden benötigte Kredite als Ausgleichsposten berechnet, müssen Zinsfolgen und Kreditverfügbarkeit geprüft werden. Ein festes Schuldenniveau und ein dauerhaft fixes Marktwert-Schuldengewicht sind verschiedene Politiken.'
 ]),
 S('case-opening','10. Nordlicht: Ausgangsbilanz und Eigentümerpolitik','a b c',[
  'Nordlicht ist ein fiktiver, unverschuldeter Industriebetrieb. Am Bewertungsstichtag beträgt der Umsatz der Ausgangsperiode 500. Es existieren zehn Millionen gleiche Stammaktien, keine Vorzugsaktien und keine Tochteranteile Dritter. Die drei Detailjahre haben sechs Prozent Umsatzwachstum und achtzehn Prozent EBIT-Marge. Der Modellsteuersatz beträgt fünfundzwanzig Prozent; Aufwendungen und Steuerzahlungen fallen in derselben Periode an.',
  T(['Position','Vor heutiger Sonderzahlung','Nach heutiger Sonderzahlung'],[['Überschüssiges Cash','30','0'],['Kundenforderungen','50','50'],['Vorräte','80','80'],['Nettoanlagen','250','250'],['Summe Aktiva','410','380'],['Lieferantenverbindlichkeiten','30','30'],['Zinsschulden','0','0'],['Stammbuchkapital','380','350'],['Summe Passiva','410','380']],'Die dreißig überschüssigen Mittel werden heute an die vorhandenen Eigentümer ausgeschüttet, also drei Euro je Aktie.'),
  F('IC_0=PPE_0+WC_0=250+(50+80-30)=350','Nach Ausschüttung des separaten Cash entspricht das operative investierte Kapital hier dem Buchkapital.',[['IC_0','Operativ gebundenes Kapital am Prognoseanfang.'],['PPE_0','Anfangsnettoanlagen.'],['WC_0','Operatives Working Capital.']]),
  'Jede positive freie Jahresendzahlung wird vollständig ausgeschüttet. Ein negativer Betrag müsste proportional von denselben Eigentümern beigetragen werden; es entstehen im Lehrfall keine neuen Aktien. Diese Annahme ist ausdrücklich bedingt: Sie beweist weder Zahlungsbereitschaft noch Finanzierungszugang. In der Realität wären Kapitalerhöhung, Kredit, gekürzte Investition oder ein anderes Geschäftsmodell zu prüfen.',
  'Die heutige Sonderzahlung wird einmal in den Wert vor Ausschüttung aufgenommen. Die anschließende Prognose beginnt bereits mit Cash null und Buchkapital 350. Wer mit Buchkapital 380 weiterrechnet und zugleich Cash 30 addiert, erzeugt eine inkonsistente doppelte Cashbasis. Jahresend-Cash null bedeutet außerdem nicht, dass unterjährig keinerlei Betriebsmittel oder Liquiditätslinien nötig wären.'
 ]),
 S('case-forecast','11. Die drei Detailjahre aus den Annahmen ableiten','a c',[
  F('S_t=S_{t-1}(1+u),\\quad EBIT_t=mS_t,\\quad PPE_t=aS_t,\\quad WC_t=wS_t','Im Detailfall werden Umsatz, Ergebnis und gewünschte Endbestände durch explizite Quoten bestimmt. Die Parameter sind Planungsannahmen, keine allgemeinen Rechnungslegungsgesetze.',[['S_t,S_{t-1}','Aktueller und vorheriger Jahresumsatz.'],['u','Umsatzwachstum von sechs Prozent.'],['m','EBIT-Marge von achtzehn Prozent nach Abschreibung.'],['PPE_t,WC_t','Gewünschter Nettoanlagen- und operativer Working-Capital-Endbestand.'],['a,w','Endbestandsquoten fünfzig und zwanzig Prozent des Umsatzes.'],['t','Hier Jahre eins bis drei.']]),
  F('DA_t=0{,}12PPE_{t-1},\\quad Capex_t=PPE_t-PPE_{t-1}+DA_t','Die vereinfachte Abschreibung beträgt zwölf Prozent des Anfangsbuchwerts. Neue Investitionen werden am Jahresende bezahlt und in diesem Jahr noch nicht abgeschrieben.',[['DA_t','Geplante Abschreibung.'],['PPE_{t-1},PPE_t','Anfangs- und Endanlagenbuchwert.'],['Capex_t','Passende gesamte Investitionszahlung.']]),
  'Die zwölfprozentige Buchwertregel ist eine vereinfachte aggregierte Planungsmethode. Sie beweist keine bestimmte wirtschaftliche Nutzungsdauer und ersetzt bei einem echten Betrieb keine Anlagenjahrgänge. Weil die EBIT-Marge bereits nach Abschreibung definiert ist, wird Abschreibung nicht ein zweites Mal vom EBIT abgezogen.',
  X('Jahr eins vollständig aufbauen','Ausgangsumsatz 500, Anlagen 250, Working Capital 100. Wachstum sechs Prozent, Marge achtzehn Prozent, Steuer fünfundzwanzig Prozent.',[
   F('S_1=500\\cdot1{,}06=530,\\quad EBIT_1=530\\cdot0{,}18=95{,}4,\\quad NI_1=NOPAT_1=95{,}4\\cdot0{,}75=71{,}55','Ohne Zins und andere Ansprüche sind Nachsteuerbetriebsertrag und Eigentümergewinn gleich.',[['S_1,EBIT_1','Umsatz und Betriebsergebnis.'],['NI_1,NOPAT_1','Gewinn und operativer Nachsteuerertrag dieses unverschuldeten Falls.']]),
   F('PPE_1=265,\\quad DA_1=30,\\quad Capex_1=265-250+30=45,\\quad WC_1=106,\\quad\\Delta WC_1=6','Fünfzehn netto mehr Anlagen benötigen wegen des Werteverzehrs fünfundvierzig Bruttoinvestition.',[['PPE_1,DA_1,Capex_1','Anlagenendwert, Abschreibung und Investitionszahlung.'],['WC_1,\\Delta WC_1','End-Working-Capital und zusätzliche Bindung.']])
  ],'Der Gewinn von 71,55 ist noch nicht die freie Zahlung.'),
  T(['Position, Mio. €','Jahr 1','Jahr 2','Jahr 3'],[['Umsatz','530','561,8','595,508'],['EBIT','95,4','101,124','107,19144'],['NOPAT = NI','71,55','75,843','80,39358'],['Abschreibung','30','31,8','33,708'],['Capex','45','47,7','50,562'],['Nettoanlagen am Ende','265','280,9','297,754'],['Working Capital am Ende','106','112,36','119,1016'],['Δ Working Capital','6','6,36','6,7416']],'Berechnete Detailprognose; intern wird vor Darstellung nicht gerundet.')
 ]),
 S('cashflow','12. Den Gewinn direkt und indirekt in Zahlungen überleiten','a c',[
  F('CFO_t=NI_t+DA_t-\\Delta WC_t,\\qquad FCFF_t=CFO_t-Capex_t','Im unverschuldeten Fall mit sofortigen Steuern und ohne andere Abgrenzungen folgt die operative Zahlung aus Gewinn, Nichtzahlung Abschreibung und Bestandsänderung. Anschließend werden die Anlagenzahlungen abgezogen.',[['CFO_t','Cashflow aus dem operativen Geschäft.'],['NI_t','Nachsteuergewinn.'],['DA_t','Nicht zahlungswirksame Abschreibung.'],['\\Delta WC_t','Zusätzliche operative Bestandsbindung.'],['FCFF_t','Freie Zahlung vor Verteilung.'],['Capex_t','Gesamte Investitionszahlung.']]),
  X('Jahr eins: Kontrolle über prognostizierte Zahlungsströme','Forderungen steigen von 50 auf 53, Vorräte von 80 auf 84,8 und Lieferantenverbindlichkeiten von 30 auf 31,8. Sonstige operative Kosten werden sofort bezahlt, es gibt keine weiteren Abgrenzungen.',[
   F('C_{op,1}=S_1-EBIT_1-DA_1=530-95{,}4-30=404{,}6','Der in der Gewinnrechnung erfasste operative Kostenbetrag ohne Abschreibung beträgt 404,6.',[['C_{op,1}','Operative Aufwendungen ohne Abschreibung; noch vor Bestandszahlungsanpassung.'],['S_1,EBIT_1,DA_1','Umsatz, Betriebsergebnis und Abschreibung.']]),
   F('Cash_{customers}=530-(53-50)=527','Drei Umsatz sind in zusätzlichen Forderungen gebunden und noch nicht eingezahlt.',[['Cash_{customers}','Kundeneinzahlungen des Jahres.']]),
   F('Cash_{costs}=404{,}6+(84{,}8-80)-(31{,}8-30)=407{,}6','Zusätzlicher Vorrat kostet 4,8; zusätzlicher Lieferantenkredit finanziert 1,8 davon. Das setzt den genannten passenden Kosten- und Bestandsumfang voraus.',[['Cash_{costs}','Operative Auszahlungen ohne Ertragsteuer und Anlageninvestition.']]),
   F('CFO_1=527-407{,}6-23{,}85=95{,}55=71{,}55+30-6','Steuerzahlung 23,85 entspricht dem vereinfachten Steueraufwand. Direkte und indirekte Rechnung stimmen überein.',[['CFO_1','Operativer Cashflow.']]),
   F('FCFF_1=FCFE_1=95{,}55-45=50{,}55','Nach Anlagenzahlungen stehen 50,55 für die vorhandenen Eigentümer zur Verfügung.',[['FCFF_1,FCFE_1','Identische freie operative und Eigentümerzahlung im unverschuldeten Fall.']])
  ],'Gewinn, operative Zahlung und freie Zahlung sind drei verschiedene Beträge desselben Geschäfts.'),
  T(['Zahlung, Mio. €','Jahr 1','Jahr 2','Jahr 3'],[['CFO','95,55','101,283','107,35998'],['FCFF = FCFE','50,55','53,583','56,79798'],['Dividende','50,55','53,583','56,79798'],['Eigentümerbeitrag','0','0','0']],'Alle positiven freien Jahresendzahlungen werden in diesem Fall ausgeschüttet. Dividende ist eine Finanzierungsauszahlung, kein zusätzlicher Betriebsaufwand.')
 ]),
 S('balance-check','13. Die Bilanz ist eine Gegenprüfung, kein Wertbeweis','a c',[
  F('B_t=B_{t-1}+NI_t-D_t+C_t','Der Buchkapital-Roll-forward erfasst Gewinn, Ausschüttung und Eigentümerbeitrag. Im Fall fehlen bewusst OCI, Rückkäufe, neue Aktien, Vorzugsansprüche und andere Buchkapitalbewegungen.',[['B_t,B_{t-1}','End- und Anfangsstammbuchkapital nach der heutigen Sonderzahlung.'],['NI_t','Erfasster Gewinn.'],['D_t','Ausschüttung an Eigentümer.'],['C_t','Proportionaler Eigentümerbeitrag ohne neue Aktien im Lehrfall.']]),
  F('Cash_t+AR_t+Inv_t+PPE_t=AP_t+B_t','Der reduzierte unverschuldete Abschluss muss schließen. Ein positiver Gewinn allein beweist weder diesen Abschluss noch seine wirtschaftliche Plausibilität.',[['Cash_t','Jahresend-Cash, hier null.'],['AR_t,Inv_t,PPE_t','Forderungen, Vorräte und Nettoanlagen.'],['AP_t','Lieferantenverbindlichkeiten.'],['B_t','Stammbuchkapital.']]),
  X('Erste Schlussbilanz unabhängig schließen','Die heutige Sonderzahlung ist bereits erfolgt. Anfangsbuchkapital 350, Gewinn 71,55, Dividende 50,55, kein Eigentümerbeitrag.',[
   F('B_1=350+71{,}55-50{,}55=371,\\quad Assets_1=53+84{,}8+265=402{,}8','Einbehaltener Gewinn 21 entspricht der Nettoinvestition fünfzehn Anlagen plus sechs Working Capital.',[['B_1','Schlussbuchkapital.'],['Assets_1','Summe der hier erfassten Aktiva.']]),
   F('AP_1+B_1=31{,}8+371=402{,}8','Die Passivseite entspricht der Aktivseite.',[['AP_1,B_1','Lieferantenfinanzierung und Eigentümerbuchkapital.']])
  ],'Ein zufällig geschlossener Abschluss kann trotzdem falsche Umsatz-, Margen- oder Investitionsannahmen enthalten.'),
  T(['Endbestand, Mio. €','Jahr 1','Jahr 2','Jahr 3'],[['Forderungen','53','56,18','59,5508'],['Vorräte','84,8','89,888','95,28128'],['Nettoanlagen','265','280,9','297,754'],['Aktiva, Cash null','402,8','426,968','452,58608'],['Lieferantenverbindlichkeiten','31,8','33,708','35,73048'],['Stammbuchkapital','371','393,26','416,8556']],'Jedes Jahr besitzt dieselbe Anspruchsgrenze und vollständige Bestandsüberleitung.')
 ]),
 S('investment-growth','14. Warum mehr Wachstum den ersten freien Cashflow senken kann','a b c',[
  F('FCFF_1=S_0\\left[m(1-\\tau)(1+u)-(a+w)u\\right]','Wenn Anlagen- und Working-Capital-Quoten bereits am Anfang gleich ihren Endquoten sind, verbraucht Umsatzwachstum zusätzliche Kapitalbindung. Abschreibung fällt nach konsistenter Anlagenüberleitung aus dieser verkürzten Formel heraus.',[['FCFF_1','Erste freie operative Jahreszahlung.'],['S_0','Ausgangsumsatz.'],['m','Konstante EBIT-Marge.'],['\\tau','Sofortiger Modellsteuersatz.'],['u','Detailumsatzwachstum als Dezimalrate.'],['a,w','Unveränderte End- und Anfangsquoten der Nettoanlagen und des Working Capital.']]),
  F('\\frac{\\partial FCFF_1}{\\partial u}=S_0\\left[m(1-\\tau)-(a+w)\\right]=500(0{,}135-0{,}7)=-282{,}5','Die Ableitung ist je einer ganzen Einheit Wachstumsrate. Ein Prozentpunkt mehr Wachstum senkt hier die erste freie Zahlung um 2,825 Millionen, während der Gewinn steigt.',[['\\partial FCFF_1/\\partial u','Partielle Änderung bei unveränderten übrigen Detailannahmen.'],['S_0,m,\\tau,a,w','Ausgangsumsatz, Marge, Steuer- und Kapitalquoten des Nordlicht-Falls.']]),
  T(['Detailwachstum','Gewinn Jahr 1, Mio. €','Nettoinvestition Jahr 1, Mio. €','Freie Zahlung Jahr 1, Mio. €'],[['0 %','67,5','0','67,5'],['6 %','71,55','21','50,55'],['15 %','77,625','52,5','25,125']],'Gleiche Ausgangsbasis und gleiche Quoten; höhere Gewinne stehen neben größeren heute benötigten Investitionen.'),
  G({id:'growth-capital',title:'Gewinnwachstum und freie Zahlung können in verschiedene Richtungen gehen',caption:'Eigene erste Jahresprognose: Umsatzbasis 500, EBIT-Marge 18 %, Steuer 25 %, Anlagenquote 50 % und Working-Capital-Quote 20 % unverändert. Nur Detailwachstum wird geändert.',reading:'Mit mehr Wachstum steigt der Gewinn leicht, während der Kapitalbedarf stark steigt. Der kurzfristige Cashflowvergleich allein sagt noch nicht, welches Wachstum langfristig wertschaffend ist.',plot:{x:[0,15],y:[0,90],xTicks:[0,3,6,9,12,15],yTicks:[0,20,40,60,80],xLabel:'Umsatzwachstum im ersten Jahr, Prozent',yLabel:'Millionen Euro',series:[{name:'NOPAT',points:Array.from({length:31},(_,i)=>[i/2,67.5*(1+i/200)])},{name:'FCFF nach Nettoinvestition',dash:true,points:Array.from({length:31},(_,i)=>[i/2,67.5*(1+i/200)-350*i/200])}]}}),
  'Höheres Wachstum kann trotz kleinerer heutiger Zahlung den Gesamtwert erhöhen, wenn zusätzliches Kapital künftig angemessen produktiv eingesetzt wird. Es kann auch Wert zerstören, wenn es dauerhaft zu wenig verdient. Im Nordlicht-Modell verändert Detailwachstum zugleich die spätere Umsatzbasis; eine isolierte Betrachtung der ersten Zahlung ist deshalb unvollständig.',
  X('Eine zusätzliche Finanzierungsbedingung erkennen','Gleicher Ausgangsbetrieb, Wachstum fünfzehn Prozent, Detailmarge acht Prozent und End-WC-Quote fünfunddreißig Prozent statt ursprünglich zwanzig.',[
   F('NI_1=575\\cdot0{,}08\\cdot0{,}75=34{,}5,\\quad\\Delta PPE_1=37{,}5,\\quad\\Delta WC_1=201{,}25-100=101{,}25','Margenschwäche und schlechtere Bestandsquote erhöhen den ungedeckten Mittelbedarf.',[['NI_1','Gewinn des Stressfalls.'],['\\Delta PPE_1,\\Delta WC_1','Zusätzliche Nettoanlagen und operative Bestandsbindung.']]),
   F('FCFE_1=34{,}5-37{,}5-101{,}25=-104{,}25','Die bestehende Eigentümergruppe müsste 104,25 beitragen, damit die unverschuldete Prognose realisierbar bleibt.',[['FCFE_1','Negative freie Eigentümerzahlung, hier Kapitalbedarf.']])
  ],'Das positive spätere Modellresultat ist bedingt auf eine tatsächlich durchführbare Finanzierung.')
 ]),
 S('terminal','15. Die stabile Phase ist eine neue wirtschaftliche Prognose','a b c',[
  'Nach Jahr drei setzt Nordlicht nicht seine hohe Detailmarge unbegründet fort. Die normalisierte EBIT-Marge fällt auf vierzehn Prozent, der nächste Umsatz steigt um drei Prozent. Neue Wachstumsinvestitionen verdienen langfristig zwölf Prozent nach Steuern. Diese Annahmen müssen Wettbewerb, Kapazität, Inflation und Risiko widerspiegeln. Im eigenen Fall sind sie bewusst geändert, um die Konsequenz des Übergangs sichtbar zu machen.',
  F('S_4=S_3(1+g),\\quad NOPAT_4=S_4m_\\infty(1-\\tau)','Der erste stabile Nachsteuerertrag wird aus dem zukünftigen Umsatz und der stabilen Marge neu berechnet. Er ist nicht automatisch der alte Ertrag mal eins plus Wachstum.',[['S_3,S_4','Letzter Detailumsatz und erster stabiler Umsatz.'],['g','Umsatz- und späteres stabiles Ertragswachstum von drei Prozent.'],['m_\\infty','Stabile EBIT-Marge von vierzehn Prozent.'],['\\tau','Modellsteuersatz von fünfundzwanzig Prozent.'],['NOPAT_4','Erster normalisierter stabiler Nachsteuerertrag.']]),
  X('Das erste stabile Jahr richtig aufbauen','Umsatz Jahr drei 595,508. Stabile Marge vierzehn statt achtzehn Prozent; Wachstum drei Prozent.',[
   F('S_4=595{,}508\\cdot1{,}03=613{,}37324,\\quad NOPAT_4=613{,}37324\\cdot0{,}14\\cdot0{,}75=64{,}4041902','Trotz höherem Umsatz fällt der normalisierte Ertrag von 80,39358 auf 64,4041902.',[['S_4','Erster stabiler Umsatz.'],['NOPAT_4','Erster stabiler Nachsteuerertrag.']]),
   'Drei Prozent stabiles Ertragswachstum gilt ab dieser neu gesetzten Ertragsbasis für Jahr fünf und danach. Der Rückgang von Jahr drei auf vier ist der ausdrückliche Margenübergang und widerspricht dem anschließenden stabilen Wachstum nicht.'
  ],'Die Detail- und Endphase können unterschiedliche Margen besitzen, müssen aber bewusst miteinander übergeleitet werden.'),
  'Ein abrupter Übergang ist eine transparente Vereinfachung. Bei schrittweisem Wettbewerbseintritt wäre eine längere Übergangsphase mit sukzessiv sinkender Marge und veränderten Investitionen häufig geeigneter. Mehr Detailjahre verbessern das Modell nur, wenn ihre zusätzlichen Annahmen wirtschaftlich belastbar sind.'
 ]),
 S('terminal-capital','16. Marginale Investitionsrendite und gesamter ROIC nicht verwechseln','a b c',[
  'Die marginale Investitionsrendite verbindet zusätzlichen Ertrag mit neu eingesetztem Kapital. Der Gesamt-ROIC verbindet dagegen den gesamten Ertrag mit dem gesamten vorhandenen Kapital. Ein sehr produktiver alter Betrieb kann daher neben niedrigeren Renditen neuer Expansionsmöglichkeiten bestehen. Gerade diese Unterscheidung verhindert, dass im Endwert Wachstum ohne passenden Kapitalbedarf behauptet wird.',
  F('R_{new}=\\frac{NOPAT_5-NOPAT_4}{I_{net,4}},\\quad NOPAT_5=NOPAT_4(1+g)\\quad\\Longrightarrow\\quad I_{net,4}=\\frac{g}{R_{new}}NOPAT_4','Bei positiver zusätzlicher Nettoinvestition in Jahr vier finanziert diese hier den zusätzlichen Ertrag in Jahr fünf. Ihre marginale Nachsteuerrendite bestimmt den Kapitalbedarf dieses Wachstums.',[['R_{new}','Positive Rendite neuer stabiler Wachstumsinvestitionen, hier zwölf Prozent.'],['NOPAT_4,NOPAT_5','Normalisierter Ertrag des ersten und zweiten stabilen Jahres.'],['I_{net,4}','Zusätzlich gebundenes operatives Kapital in Jahr vier; für die erste Verhältnisdefinition größer null.'],['g','Stabile Ertragswachstumsrate nach dem ersten normalisierten Jahr.']]),
  'Bei Wachstum null ergibt die Kapitalbedarfsformel Nettoinvestition null. Die Rendite neuer Investitionen ist dann eine Annahme über mögliche zusätzliche Projekte und nicht aus dem tatsächlich fehlenden Ertrags- und Kapitalzuwachs schätzbar. Erhaltungsinvestitionen bleiben dennoch nötig, soweit sie die fortgesetzte Ertragsbasis erhalten.',
  F('FCFF_4=NOPAT_4-I_{net,4}=NOPAT_4\\left(1-\\frac{g}{R_{new}}\\right)','Ersatz des bisherigen Betriebs ist in der Erhaltung seiner Ertragsbasis berücksichtigt. Die zusätzlich nötige Nettoinvestition reduziert den ausschüttbaren Betrag.',[['FCFF_4','Erste stabile freie Zahlung.'],['NOPAT_4','Normalisierter operativer Nachsteuerertrag.'],['I_{net,4}','Operative Nettoinvestition.'],['g,R_{new}','Stabiles Wachstum und marginale Rendite des zusätzlichen Kapitals.']]),
  X('Jahr vier an das vorhandene Kapital anschließen','Ertrag 64,4041902, Wachstum drei Prozent, Rendite neuer Investitionen zwölf Prozent. Ende-IC in Jahr drei beträgt 416,8556.',[
   F('I_{net,4}=64{,}4041902\\cdot0{,}03/0{,}12=16{,}10104755,\\quad FCFF_4=48{,}30314265','Ein Viertel des ersten stabilen Ertrags wird für zusätzliches Wachstumskapital gebraucht.',[['I_{net,4}','Nettoinvestition, Mio. €.'],['FCFF_4','Erste freie stabile Zahlung, Mio. €.']]),
   F('IC_4=416{,}8556+16{,}10104755=432{,}95664755,\\quad ROIC_{4,begin}=64{,}4041902/416{,}8556=15{,}45\\%','Die Rendite auf das gesamte vorhandene Anfangskapital ist nicht gleich der marginalen Zwölfprozentannahme.',[['IC_4','Gesamtes gebundenes Kapital am Ende von Jahr vier.'],['ROIC_{4,begin}','Erster stabiler Ertrag relativ zum gesamten Anfangskapital.']]),
   F('\\Delta WC_4=0{,}2(613{,}37324-595{,}508)=3{,}573048,\\quad\\Delta PPE_4=16{,}10104755-3{,}573048=12{,}52799955','Bleibt die Working-Capital-Quote zwanzig Prozent, entfällt der übrige Nettoinvestitionsbetrag auf Anlagen. Die frühere Anlagenquote wird in dieser stabilen Konstruktion bewusst nicht zusätzlich erzwungen.',[['\\Delta WC_4,\\Delta PPE_4','Nettozuwächse des Working Capital und der Anlagen.']]),
   F('DA_4=0{,}12\\cdot297{,}754=35{,}73048,\\quad Capex_4=35{,}73048+12{,}52799955=48{,}25847955','Die vollständige Bruttoinvestition erhält die Abschreibungsüberleitung und die geplante Nettoinvestition.',[['DA_4,Capex_4','Abschreibung und Bruttoinvestition im ersten stabilen Jahr.']])
  ],'Wachstum, Marge, Anlagenquote und Kapitalrendite können nicht unabhängig auf beliebige Wunschwerte gesetzt werden.'),
  F('IC_{4+h}=IC_3+\\frac{NOPAT_4}{R_{new}}\\left[(1+g)^{h+1}-1\\right]','Bei unveränderten Regeln addieren sich die wachstumsbedingten Nettoinvestitionen zu dieser Kapitalfortschreibung. Für positives stabiles Wachstum nähert sich die Rendite auf das gesamte Anfangskapital langfristig der marginalen Rendite an; sie springt nicht sofort dorthin.',[['IC_{4+h},IC_3','Gebundenes Kapital nach h weiteren stabilen Jahren und vor Eintritt in die stabile Phase.'],['h','Ganzzahliger Index ab null.'],['NOPAT_4','Erste normalisierte Ertragsbasis.'],['R_{new},g','Marginale Rendite und konstantes positives Wachstum.']]),
  'Bei einem anderen Modell mit von Beginn an konstantem Gesamt-ROIC müsste auch das gesamte Kapital am Übergang dazu passen. Eine notwendige Kapitalfreisetzung, zusätzliche Investition oder Neubewertung wäre ausdrücklich zu erklären. Die hier verwendete marginale Konstruktion vermeidet eine versteckte sofortige Umschreibung des alten Kapitals.'
 ]),
 S('valuation','17. Vom Endwert zum heutigen Aktienwert rechnen','a c',[
  F('TV_3=\\frac{FCFF_4}{k-g},\\quad V_{op,0}=\\sum_{t=1}^{3}\\frac{FCFF_t}{(1+k)^t}+\\frac{TV_3}{(1+k)^3}','Der Endwert am Ende des dritten Jahres erfasst freie Zahlungen ab Jahr vier. Er wird um drei Jahre diskontiert; die erste stabile Zahlung wird nicht zusätzlich nochmals außerhalb des Endwerts addiert.',[['TV_3','Operativer Fortführungswert am Ende von Jahr drei.'],['FCFF_t,FCFF_4','Detailzahlungen und erste stabile Jahresendzahlung.'],['k','Passender konstanter Diskontsatz, hier neun Prozent; ohne Verschuldung identisch mit Eigenkapitalkosten.'],['g','Stabiles Zahlungswachstum unterhalb von k.'],['V_{op,0}','Heutiger operativer Barwert.'],['t,\\sum','Jahresindex und Summe über die drei Detailzahlungen.']]),
  X('Nordlicht vollständig bewerten','Detail-FCFF 50,55; 53,583; 56,79798. Erste stabile freie Zahlung 48,30314265; Diskontsatz neun Prozent; stabiles Wachstum drei Prozent.',[
   F('TV_3=48{,}30314265/0{,}06=805{,}0523775,\\quad PV(TV_3)=805{,}0523775/1{,}09^3\\approx621{,}6481465','805,05 ist ein zukünftiger Wert, nicht bereits sein heutiger Betrag.',[['TV_3','Endwert am Ende von Jahr drei.'],['PV(TV_3)','Heutiger Barwert des Endwerts.']]),
   F('PV_{detail}=50{,}55/1{,}09+53{,}583/1{,}09^2+56{,}79798/1{,}09^3\\approx135{,}3343477','Jede Detailzahlung bekommt ihren eigenen Zahlungstermin.',[['PV_{detail}','Summe der drei heutigen Detailzahlungsbarwerte.']]),
   F('V_{op,0}\\approx135{,}3343477+621{,}6481465=756{,}9824942','Der operative Wert enthält nur den definierten Betrieb.',[['V_{op,0}','Operativer Wert in Millionen Euro.']]),
   F('E_{common,0}=756{,}9824942+30=786{,}9824942,\\quad v_0=786{,}9824942/10\\approx78{,}6982494','Vor heutiger Sonderzahlung umfasst der Stammkapitalwert das separate Cash einmal. Millionen Euro geteilt durch Millionen Aktien ergibt Euro je Aktie.',[['E_{common,0}','Stammkapitalwert vor heutiger Sonderzahlung.'],['v_0','Wert je Aktie in Euro bei zehn Millionen Aktien.']])
  ],'Nach der Sonderzahlung ist der Modellwert je Aktie um drei Euro kleiner, während der bisherige Eigentümer drei Euro Cash erhalten hat.'),
  F('\\frac{PV(TV_3)}{V_{op,0}}\\approx\\frac{621{,}6481465}{756{,}9824942}\\approx82{,}1219\\%','Der hohe Endwertanteil zeigt, wie stark das Ergebnis auf langfristige Annahmen angewiesen ist. Er ist kein eigenständiger Beweis einer fehlerhaften oder richtigen Bewertung.',[['PV(TV_3)','Heutiger Barwert der Zahlungen nach der Detailphase.'],['V_{op,0}','Heutiger operativer Wert ohne Sondercash.']]),
  'Eine ewige Fortführung ist bei endlichen Konzessionen oder Reserven nicht selbstverständlich. Liquidation, Verlängerung, Ersatzinvestition oder zusätzliche Geschäftsfelder benötigen eigene Annahmen. Ein belastbarer Endwert ist eine wirtschaftliche Aussage über die Zeit nach der letzten Tabellenzeile.'
 ]),
 S('claims','18. Anspruchsbrücke und Aktienzahl vollständig abgleichen','a b c',[
  F('E_{common}=V_{op}+A_{nonop}-D_{fin}-P_{pref}-NCI,\\qquad v=\\frac{E_{common}}{N}','Die Brücke gilt bei konsistenten Wert- und Konsolidierungsgrenzen. Nicht operative Vermögenswerte werden hinzugefügt; fremde Ansprüche auf erfasste Werte werden abgezogen. Jede Position benötigt die passende Bewertung.',[['E_{common}','Wert des betrachteten Stammkapitals.'],['V_{op}','Wert des vollständig abgegrenzten operativen Geschäfts.'],['A_{nonop}','Nicht operative Vermögenswerte außerhalb dieses Cashflowmodells.'],['D_{fin}','Passender Wert zinstragender Fremdansprüche.'],['P_{pref}','Passender Wert vorrangiger Vorzugsansprüche.'],['NCI','Wert von Tochteransprüchen Dritter, soweit die entsprechenden Tochtercashflows vollständig erfasst wurden.'],['N','Aktienzahl mit passenden Rechten und Stichtag.'],['v','Wert je solcher Stammaktie.']]),
  X('Getrennter Konzernfall mit vorrangigen Ansprüchen','Ein anderer Fall hat operativen Wert 900, separat bewertetes Cash 50 und Beteiligungen 20, Finanzierungsschulden 180, Vorzugsansprüche 30 und Tochteransprüche Dritter 40. Zwölf Millionen gleiche Stammaktien.',[
   F('E_{common}=900+50+20-180-30-40=720,\\quad v=720/12=60','Der vollständig erfasste Tochterbetrieb darf nicht den Stammaktionären allein zugewiesen werden.',[['E_{common}','Stammkapitalwert in Millionen.'],['v','Wert in Euro je Stammaktie.']])
  ],'Buchschulden sind nur dann eine angemessene Näherung des Anspruchswerts, wenn die konkrete Bewertungssituation dies trägt.'),
  'Optionsvergütung, Wandlungsrechte, unterschiedliche Aktienklassen und geplante Kapitalerhöhungen können die Stückansprüche verändern. Der aktuelle Aktienbestand ist nicht immer die gewichtete Aktienzahl des berichteten EPS. Eine mögliche Verwässerung darf nicht sowohl als Anspruchsabzug als auch vollständig nochmals im Nenner erfasst werden. Leasing, Pensionen und andere Verpflichtungen müssen zum Cashflowumfang passen; sie werden weder pauschal vergessen noch zweimal abgezogen.'
 ]),
 S('alternatives','19. DDM und Residual Income als konsistente Gegenrechnung','a b c',[
  'Im Nordlicht-Fall sind freie positive Eigentümerzahlungen echte Dividenden. Weil keine Verschuldung besteht, stimmen FCFF, FCFE und ausgeschüttete Beträge überein. Deshalb ergibt das Dividend Discount Model nach der heutigen Sonderzahlung denselben Betriebswert. Bei einem echten Unternehmen mit zurückgehaltenem Cash ist diese unmittelbare Gleichsetzung falsch: Künftige Verfügbarkeit und Verwendung der einbehaltenen Mittel müssen ausdrücklich modelliert werden.',
  F('RI_t=NI_t-k_eB_{t-1},\\qquad V_0=B_0+\\sum_{t=1}^{3}\\frac{RI_t}{(1+k_e)^t}+\\frac{V_3-B_3}{(1+k_e)^3}','Residual Income bewertet Buchkapital und künftigen Gewinn oberhalb seiner Kapitalverzinsung. Im endlichen Horizont wird die noch nicht erfasste spätere Überrendite als Wert minus Buchkapital am Horizont ergänzt. Die Identität setzt konsistente Eigentümerflüsse und Clean Surplus voraus.',[['RI_t','Residual Income der Periode.'],['NI_t','Passender Eigentümergewinn.'],['k_e','Eigenkapitalkosten, hier neun Prozent.'],['B_{t-1},B_0,B_3','Anfangsbuchkapital, Stichtagsbuchkapital nach Sonderzahlung und Endbuchkapital Jahr drei.'],['V_0,V_3','Eigentümerwert nach Sonderzahlung und am zukünftigen Horizont.'],['t,\\sum','Periodenindex und Summation der expliziten Überrenditen.']]),
  X('Eine zweite Rechnung mit demselben Geschäft','Buchkapital nach Sonderzahlung 350; Detailgewinne 71,55; 75,843; 80,39358. Endbuchkapital 371; 393,26; 416,8556. Kapitalverzinsung neun Prozent.',[
   F('RI_1=71{,}55-0{,}09\\cdot350=40{,}05,\\quad RI_2=75{,}843-0{,}09\\cdot371=42{,}453,\\quad RI_3=80{,}39358-0{,}09\\cdot393{,}26=45{,}00018','Der Kapitalzins fällt auf das jeweilige Anfangsbuchkapital, nicht pauschal auf dieselbe Ausgangszahl.',[['RI_1,RI_2,RI_3','Explizite Jahresüberrenditen in Millionen.']]),
   F('V_0=350+40{,}05/1{,}09+42{,}453/1{,}09^2+45{,}00018/1{,}09^3+(805{,}0523775-416{,}8556)/1{,}09^3\\approx756{,}9824942','Die Gegenrechnung stimmt mit dem Barwert der Dividenden nach Sonderzahlung überein. Das separate Cash dreißig wird erst für den Wert vor Sonderzahlung ergänzt.',[['V_0','Heutiger Wert nach Sonderzahlung.']])
  ],'Die Übereinstimmung prüft Anspruch und Algebra; sie bestätigt nicht unabhängig die Umsatz- oder Margenprognose.'),
  'Multiplikatoren können die resultierende Wertrelation mit Peers vergleichen. Ein aus demselben DCF berechnetes gerechtfertigtes KGV ist aber keine unabhängige zweite Marktevidenz. Marktpreise und entsprechend abgegrenzte Peer-Erträge liefern eine zusätzliche Perspektive, bleiben jedoch von Vergleichbarkeit und möglicher gemeinsamer Fehlbewertung abhängig.'
 ]),
 S('uncertainty','20. Sensitivität, Szenario und Erwartungswert unterscheiden','a b c',[
  'Sensitivität verändert eine Annahme bei bewusst konstanten anderen Größen. Sie beantwortet, wo das Ergebnis rechnerisch empfindlich ist. Ein Szenario verändert zusammengehörige Annahmen: Eine Rezession kann gleichzeitig Menge, Preis, Marge, Forderungsausfälle, Finanzierung und Investitionspläne beeinflussen. Ein Preisstress mit unveränderten Kosten und unveränderter Kapitalbindung kann ein nützlicher isolierter Versuch sein, aber kein vollständiges Rezessionsszenario.',
  F('\\mathbb{E}[V]=\\sum_s p_sV_s,\\quad\\sum_s p_s=1','Ein gewichteter Szenariowert setzt begründete Wahrscheinlichkeiten und sinnvoll vergleichbare bedingte Werte voraus. Nichtlineare Bewertung macht den Wert durchschnittlicher Eingaben im Allgemeinen verschieden vom durchschnittlichen Wert.',[['\\mathbb{E}[V]','Erwarteter Wert unter dem ausdrücklich gewählten Szenariorahmen.'],['s','Szenarioindex.'],['p_s','Nicht negative Szenariowahrscheinlichkeit.'],['V_s','Wert im betreffenden konsistenten Szenario.'],['\\sum','Summe über die vollständig betrachteten Szenarien.']]),
  X('Unsichere Endwachstumsrate bei festem ersten Cashflow','Erste stabile Zahlung zehn, Diskontsatz zehn Prozent. Zwei gleich wahrscheinliche Fälle haben Wachstum null und vier Prozent. Für diese isolierte Demonstration sind die zehn bereits nach den jeweiligen Investitionen verfügbare Zahlungen.',[
   F('V_A=10/0{,}10=100,\\quad V_B=10/0{,}06\\approx166{,}6667,\\quad \\mathbb{E}[V]\\approx133{,}3333','Die zwei bedingten Endwerte werden gemittelt.',[['V_A,V_B','Bedingte Werte.'],['\\mathbb{E}[V]','Gleich gewichteter Wertdurchschnitt.']]),
   F('V(\\mathbb{E}[g])=10/(0{,}10-0{,}02)=125','Das mittlere Wachstum erzeugt einen anderen Wert als das Mittel der Werte.',[['V(\\mathbb{E}[g])','Wert mit dem durchschnittlichen Wachstumsinput.'],['g','Zufällige Wachstumsrate im vereinfachten Demonstrationsrahmen.']])
  ],'Ohne glaubwürdige Wahrscheinlichkeiten ist ein Szenarioband ehrlicher als eine scheinbar exakte Wahrscheinlichkeitsbewertung.'),
  'Bei risikobehafteten Cashflows sind physische Erwartungen und angemessene Risikodiskontierung gemeinsam zu begründen. Man darf Szenariorisiko nicht willkürlich einmal in zu pessimistischen Cashflows und nochmals als unbegründeten hohen Aufschlag abziehen. Verschiedene Diskontsätze je Szenario schaffen nicht automatisch ein konsistentes Bewertungsmodell.'
 ]),
 S('sensitivity','21. Langfristiges Wachstum, Kapitalrendite und Diskontsatz','a b c',[
  F('TV=\\frac{N(1-g/R)}{k-g},\\qquad\\frac{\\partial TV}{\\partial g}=\\frac{N(R-k)}{R(k-g)^2}','Bei festem ersten stabilen Nachsteuerertrag, konstantem marginalem Investitionsertrag und passenden Kosten hängt die Wachstumswirkung von der Überrendite neuen Kapitals ab.',[['TV','Operativer Endwert.'],['N','Festgehaltener erster stabiler NOPAT größer null.'],['R','Nachsteuerrendite neuer Wachstumsinvestitionen.'],['g','Stabiles Wachstum; hier unter k und R.'],['k','Passender konstanter Diskontsatz.'],['\\partial TV/\\partial g','Partielle Änderung unter diesen festgehaltenen Größen.']]),
  G({id:'stable-productivity',title:'Endwachstum schafft nur bei ausreichender Investitionsrendite zusätzlichen Wert',caption:'Eigene kontrollierte Vergleichsfälle: erster stabiler NOPAT stets 64,4041902; Diskontsatz 9 %, gleiche drei Detailzahlungen und separates Cash 30. Wachstum betrifft nur die Jahre nach dem ersten stabilen Ertrag. Neue Kapitalrenditen 6 %, 9 % und 15 %.',reading:'Bei neuer Rendite oberhalb der Kosten steigt der Wert, bei Gleichheit bleibt er konstant und darunter sinkt er. Der Nordlicht-Rechner verändert mit stabilem Umsatzwachstum zusätzlich den ersten stabilen Umsatz; seine Kurve ist daher ein anderer, ausdrücklich breiterer Versuch.',plot:{x:[0,4],y:[45,105],xTicks:[0,1,2,3,4],yTicks:[50,60,70,80,90,100],xLabel:'Wachstum nach erster stabiler Ertragsbasis, Prozent',yLabel:'Wert vor Sonderzahlung, Euro je Aktie',series:[{name:'Neue Kapitalrendite 6 %',points:Array.from({length:41},(_,i)=>[i/10,stableValue(i/1000,.06)])},{name:'Neue Kapitalrendite 9 %',dash:true,points:Array.from({length:41},(_,i)=>[i/10,stableValue(i/1000,.09)])},{name:'Neue Kapitalrendite 15 %',points:Array.from({length:41},(_,i)=>[i/10,stableValue(i/1000,.15)])}]}}),
  T(['Diskontsatz des Gesamtmodells','Stabiles g = 1 %','Stabiles g = 2 %','Stabiles g = 3 %'],[['7 %','95,8011','103,8118','115,6152'],['9 %','72,4114','75,1632','78,6982'],['11 %','58,3853','59,2362','60,2045']],'Nordlicht-Wert je Aktie vor Sonderzahlung. Alle Detailzahlungen werden mit dem jeweiligen Satz diskontiert; Jahr vier wird jeweils aus Umsatz, stabiler Marge und dazu passender Nettoinvestition neu aufgebaut.'),
  G({id:'stable-margin',title:'Eine dauerhafte Margenänderung wirkt auf viele künftige Zahlungen',caption:'Eigene Nordlicht-Sensitivität: alle Detailzahlungen unverändert; erster stabiler Umsatz 613,37324, Steuer 25 %, Wachstum 3 %, neue Investitionsrendite 12 % und Kosten 9 %. Nur die stabile EBIT-Marge wird verändert.',reading:'Eine höhere stabile Marge erhöht den Ertrag und bei gleicher Wachstumskonstruktion auch den benötigten Investitionsbetrag. Der verfügbare Anteil bleibt drei Viertel des Ertrags; deshalb steigt der Wert hier linear. Ob die höhere Marge erreichbar ist, kann die Grafik nicht beweisen.',plot:{x:[10,20],y:[50,110],xTicks:[10,12,14,16,18,20],yTicks:[50,60,70,80,90,100,110],xLabel:'Stabile EBIT-Marge, Prozent',yLabel:'Wert vor Sonderzahlung, Euro je Aktie',series:[{name:'Nordlicht bei sonst gleichen Annahmen',points:Array.from({length:41},(_,i)=>{const m=(10+i/4)/100;return [m*100,(fixedPV+613.37324*m*.75*.75/.06/1.09**3+30)/10];})}]}}),
  'Die Tabelle ist keine Empfehlung, langfristiges Wachstum so nahe wie möglich an den Diskontsatz zu legen. Ein kleiner Nenner macht Bewertung empfindlich, nicht zuverlässig. Ein stabiles Wachstum jenseits der angemessenen langfristigen Wirtschafts- und Währungsbasis benötigt besondere Begründung. Nominale Cashflows brauchen nominale Sätze derselben Währung; reales Wachstum und nominale Kosten dürfen nicht ohne Umrechnung kombiniert werden.',
  'Der Rechner ermöglicht gezielte Versuche: Verändere erst die Detailwachstumsrate und beobachte Gewinn, Investition und erste freie Zahlung. Ändere dann nur die Working-Capital-Quote, anschließend die stabile Marge und zuletzt die Rendite neuer Investitionen. Erkläre jeweils die wirtschaftliche Ursache, bevor du die neue Bewertung interpretierst.'
 ]),
 S('reverse','22. Vom beobachteten Preis zu notwendigen Annahmen','a b c',[
  F('TV_{3,req}=\\left(P_0N-A_{nonop}-PV_{detail}\\right)(1+k)^3','Im unverschuldeten vereinfachten Fall kann der beobachtete Gesamtpreis in einen benötigten Endwert übersetzt werden. Dadurch werden die impliziten langfristigen Anforderungen sichtbar.',[['TV_{3,req}','Vom Preis benötigter operativer Endwert.'],['P_0','Beobachteter Preis je Aktie vor heutiger Sonderzahlung.'],['N','Zehn Millionen gleiche Aktien.'],['A_{nonop}','Separates heute ausschüttbares Cash von dreißig Millionen.'],['PV_{detail}','Barwert der unveränderten drei Detailzahlungen.'],['k','Konstanter passender Diskontsatz.']]),
  F('NOPAT_{4,req}=TV_{3,req}\\frac{k-g}{1-g/R_{new}},\\qquad m_{req}=\\frac{NOPAT_{4,req}}{S_4(1-\\tau)}','Bei festem Wachstum, neuen Investitionsrenditen, Steuer und Umsatz lässt sich der benötigte Endwert auf eine erforderliche stabile Marge zurückführen.',[['NOPAT_{4,req}','Erster stabiler Ertrag, der den angenommenen Preis stützt.'],['TV_{3,req}','Benötigter Endwert.'],['k,g,R_{new}','Fixierter Diskontsatz, Wachstum und Rendite neuen Kapitals.'],['m_{req}','Erforderliche stabile EBIT-Marge.'],['S_4,\\tau','Fixierter erster stabiler Umsatz und Steuersatz.']]),
  'Reverse DCF ist eine Diagnose, keine Entdeckung der eindeutig wahren Marktprognose. Derselbe Preis kann aus höherer Marge, niedrigerem Diskontsatz, anderem Kapitalbedarf oder veränderter Wachstumsdauer entstehen. Man hält deshalb einige Größen ausdrücklich fest und prüft, ob die verbleibende erforderliche Annahme wirtschaftlich plausibel ist.',
  X('Die zentrale Preisfrage stellen','Der Nordlicht-Modellwert beträgt vor Sonderzahlung etwa 78,70. Ein beobachteter Preis oberhalb davon muss bei unveränderten übrigen Annahmen eine höhere stabile Marge voraussetzen.',[
   F('m_{req}=\\frac{(80\\cdot10-30-135{,}334347725)(1{,}09)^3\\cdot0{,}06}{(1-0{,}03/0{,}12)\\cdot613{,}37324\\cdot0{,}75}\\approx14{,}2932\\%','Ein Preis achtzig würde bei genau den festgehaltenen Nordlicht-Annahmen eine stabile Marge von etwa 14,2932 statt vierzehn Prozent benötigen.',[['m_{req}','Vom Preis achtzig bedingt erforderliche stabile EBIT-Marge.']]),
   'Eine solche Margenforderung wird mit Wettbewerb, Preismacht, Kostenstruktur und Kapazität verglichen. Ein Wertpapier kann dennoch richtig bepreist sein, wenn andere Annahmen des eigenen Modells zu pessimistisch sind. Der Modellabstand ist ein Auftrag zur Prüfung dieser Ursachen.',
   'Ein implizites Ergebnis wird nicht als explizite Managementprognose präsentiert. Der Marktpreis enthält keine eindeutige Liste einzelner Erwartungen.'
  ],'Die nützliche Frage lautet, welche Bedingungen den Preis tragen und welche Evidenz für oder gegen diese Bedingungen spricht.')
 ]),
 S('forecast-controls','23. Gegenprüfungen, die verschiedene Fehler entdecken','a b c',[
  T(['Kontrolle','Was sie aufdeckt','Was sie nicht beweist'],[['Bilanzsumme und Eigenkapital-Roll-forward','Fehlende Bestände, Eigentümerflüsse und doppelte Zahlungen.','Richtigkeit der Wettbewerbs- und Margenthese.'],['Direkte gegen indirekte CFO-Rechnung','Falsche Vorzeichen oder fehlende Bestandsanpassungen.','Dass Kunden die angenommenen Zahlungen leisten.'],['Anlagenbewegung gegen Capex','Verwechslung von Bruttoinvestition, Abschreibung und Nettozuwachs.','Technische Kapazität oder tatsächliche Ersatzpreise.'],['FCFF gegen FCFE und Finanzierung','Falsche Zinsverteilung, Schuldentilgung und Nettoschuldenaufnahme.','Tatsächliche Kreditverfügbarkeit.'],['DDM/Residual Income bei gleichen Annahmen','Inkonsistente Buchkapital- und Ausschüttungsbehandlung.','Unabhängige Bestätigung derselben Prognosen.'],['Peer-Verhältnisse und historische Bandbreiten','Auffällige oder unvergleichbare Wertrelationen.','Dass Peers fair bepreist sind.'],['Endkapital, Marge und Wachstumsbedarf','Unvereinbare stabile Quoten und Kapitalrenditen.','Dauerhafte Erreichbarkeit der Endphase.']],'Mehrere Prüfungen sind nötig, weil eine einzelne geschlossene Gleichung nur ihren eigenen Zusammenhang prüft.'),
  'Sensitivitätstests sollten auch Extrem- und Nullfälle enthalten: Nullwachstum, schwächere Margen, unveränderte Kapitalbestände und benötigte Finanzierung. Negative freie Zahlung wird sichtbar und nicht automatisch abgeschnitten. Erfordern Prognosen neue Aktien, wird der Anspruch der bisherigen Eigentümer mitmodelliert. Begrenzte Kreditlinien und Mindestcash werden als wirtschaftliche Bedingungen geprüft.',
  'Die Prognose wird nach neuen Informationen aktualisiert: Zuerst die betroffene Ursache, dann sämtliche abhängigen Rechnungen und der Wert. Eine neue geringere Absatzmenge ändert nicht nur die Umsatzzeile, sondern gegebenenfalls Kapazität, Lager, Marge, Steuer und Investitionsentscheidungen. Eine fortlaufende Abweichungsanalyse trennt Datenfehler, einmalige Überraschung und geänderte These.'
 ]),
 S('limitations','24. Grenzen eines sauberen und dennoch unsicheren Modells','a b c',[
  'Ein Abschlussmodell verarbeitet Annahmen; seine Präzision ist nicht die Präzision der Zukunft. Detaillierte Zeilen erzeugen zusätzliche Schätzfehler, wenn keine belastbare Information dahintersteht. Gegenläufige Fehler können einen scheinbar passenden historischen Gesamtgewinn liefern. Ein Modell kann daher richtig addieren und dennoch ein falsches Geschäftsbild erzählen.',
  'Der Nordlicht-Rechner ist ein jährliches Lehrmodell ohne Zins, Kreditgrenzen, saisonale Liquidität, Ausfälle, Verlustvorträge, Anlagenabgänge, Akquisitionen, Aktienvergütung und separate Wachstumsprojekte. Die Anlagenquote der Detailphase und die marginale Investitionsrendite der Endphase sind zwei bewusst verschiedene Kapitalannahmen. End-Cash null wird über Ausschüttung oder Beiträge hergestellt. Diese Konstruktion erklärt Wertzusammenhänge; sie ersetzt keine Unternehmensprüfung.',
  'Bei dauerhaft negativen Margen oder nicht finanzierbarem Wachstum kann ein Fortführungsmodell unangebracht sein. Bei verschiedenen Geschäftsbereichen kann eine spartenweise Bewertung sinnvoll sein. Bei Banken sind regulatorisches Kapital und Geschäftsschulden zentral. Bei endlichen Rohstoffreserven können Mengen und Laufzeit wichtiger als eine ewige Formel sein. Modellwahl ist deshalb ein fachliches Urteil und keine Auswahl nach der bequemsten verfügbaren Formel.',
  'Ein berechneter Preisabstand ist keine Bestehens-, Gewinn- oder Sicherheitswahrscheinlichkeit. Prüferfolg verlangt, Annahmen und Anspruchsgrenzen in neuen Fällen selbst zu erkennen. Anlageerfolg verlangt zusätzlich zutreffende Zukunftseinschätzungen und einen passenden Umgang mit Unsicherheit.'
 ]),
 S('workflow','25. Ein vollständiger Bewertungsablauf zum Nachschlagen','a b c',[
  T(['Schritt','Überprüfbares Ergebnis'],[['1. Bewertungsfrage abgrenzen','Stichtag, Währung, Betrieb, Konsolidierung und betrachteter Aktienanspruch.'],['2. Historische Basis prüfen','Bereinigte Ertragsbasis plus dazu passende Bestände und Datenverfügbarkeit.'],['3. Treiber prognostizieren','Menge, Preis, Mix, Kosten, Kapazität und Kapitalbedarf mit Begründung.'],['4. Abschlüsse integrieren','Gewinn, Anlagen, Working Capital, Steuern und Finanzierung schließen gemeinsam.'],['5. Freie Zahlungen ableiten','FCFF oder FCFE mit klarer Zins-, Investitions- und Schuldenbehandlung.'],['6. Endphase neu konstruieren','Nachhaltige Marge, Wachstum, Kapitalbedarf, Rendite und Fortführbarkeit.'],['7. Diskontieren','Passender Kapitalanspruch, Risiko, Währung und Zahlungszeitpunkt.'],['8. Ansprüche überleiten','Nicht operative Werte, Schuld-, Vorzugs- und Tochteransprüche und Aktienzahl.'],['9. Gegenrechnen','Bilanz, Zahlungen, alternative Darstellung und vergleichbare Marktverhältnisse.'],['10. Unsicherheit erklären','Szenarien, Sensitivitäten, finanzielle Bedingungen und überprüfbare Investmentthese.']],'Erst die gesamte Kette macht aus einer Gewinnprognose eine begründete Aktienbewertung.'),
  X('Nordlicht in einem Satz begründen','Umsatzwachstum und Detailmarge tragen die ersten Erträge; zusätzliche Anlagen und Bestände reduzieren die freien Zahlungen; anschließend begrenzen niedrigere stabile Marge und Kapitalbedarf die Endphase.',[
   'Die drei Detailzahlungen haben heute etwa 135,33 Wert. Die normalisierte Endphase hat heute etwa 621,65 Wert. Das operativ bewertete Geschäft beträgt deshalb etwa 756,98. Einmaliges heutiges Überschusscash von dreißig liefert vor seiner Sonderausschüttung etwa 786,98 Stammkapitalwert oder 78,70 Euro je Aktie.',
   'Die Aussage gilt unter den genannten Zukunfts- und Finanzierungsannahmen. Sie wird erst dann belastbar, wenn diese Annahmen wirtschaftlich plausibel sind und auf neue Beobachtungen reagieren.'
  ],'Eine gute Erläuterung nennt die Wertursachen und Bedingungen neben dem Ergebnis.')
 ]),
 S('review','26. Verständnisfragen für selbstständige Anwendung','a b c',[
  T(['Frage','Was eine vollständige Antwort verbindet'],[['Warum sind Umsatz-, Gewinn- und Zahlungswachstum verschieden?','Kosten, Abgrenzung, Anlagen und operative Bestandsbindung.'],['Warum muss eine Bilanz neben der Gewinnprognose erstellt werden?','Gewinn benötigt Vermögen und Finanzierung; Bestände steuern Zahlungen.'],['Warum kann mehr Wachstum die erste freie Zahlung senken?','Zusätzlicher Ertrag im Vergleich zum zusätzlich gebundenen Kapital.'],['Warum ist die stabile Zahlung nicht einfach die letzte Zahlung mal eins plus g?','Margen-, Kapital- und Renditeannahmen können am Übergang wechseln.'],['Warum ist eine marginale Rendite nicht der Gesamt-ROIC?','Neue zusätzliche Erträge relativ zu neuem Kapital gegenüber gesamtem Ertrag auf altem Kapital.'],['Warum gehört der Endwert am Ende Jahr drei in dessen Diskontfaktor?','Die enthaltenen Zahlungen beginnen erst in Jahr vier.'],['Warum wird Cash nicht in Working Capital und nochmals in der Wertbrücke erfasst?','Operative Mittelbindung und separates Vermögen haben unterschiedliche Rollen.'],['Wann können FCFF, FCFE und Dividenden übereinstimmen?','Ohne Verschuldung und bei tatsächlich vollständiger Ausschüttung der verfügbaren Mittel.'],['Warum beweisen gleiches DCF und Residual Income keine unabhängige Prognosegüte?','Dieselben Annahmen werden algebraisch verschieden dargestellt.'],['Wann ist ein Jahresmodell für die Liquiditätsfrage unzureichend?','Unterjährige Zahlungsspitzen und Finanzierungsbedingungen fehlen.'],['Warum benötigt ein Bankmodell eine andere Kapitalplanung?','Regulatorisches Eigenkapital und operative Finanzierungspositionen.'],['Was liefert Reverse DCF und was bleibt offen?','Notwendige bedingte Annahmen, aber keine eindeutige wahre Markterwartung.']],'Die eigene Fragenbank prüft Berechnung, Erklärung, Fehlersuche, Modellwahl und Transfer.'),
  'Die Symbole stehen ausklappbar an jeder Formel. Tabellen, genaue Rechenschritte, der Rechner und die verlinkten Kapitel ergänzen sich: Eine Formel wird erst verstanden, wenn ihre Größen, Zeitpunkte, Anspruchsgrenzen und wirtschaftlichen Voraussetzungen erklärt werden können.'
 ])
],explorations:[{section:'sensitivity',lesson:'equity-09',focus:'lab',label:'Nordlicht-Modell verändern: Abschlüsse, Investitionen und Aktienwert'}],related:[
 {unit:'industry',section:'integrated',label:'Branchen- und Wettbewerbshypothesen mit vollständigem Kapitalbedarf verbinden'},
 {unit:'forecasting',section:'architecture',label:'Integriertes Abschlussmodell ausführlich konstruieren'},
 {unit:'forecasting',section:'circularity',label:'Kreditbedarf und neue Zinsen zusammen lösen'},
 {unit:'dcf-equity',section:'terminal-normalization',label:'Übergang zur ersten stabilen Zahlung herleiten'},
 {unit:'dcf-equity',section:'equivalence-case',label:'Dividenden, FCFE und Residual Income aufeinander abstimmen'},
 {unit:'multiples',section:'ev-fundamentals',label:'Kapitalbedarf hinter operativen Multiplikatoren'},
 {unit:'valuation-overview',section:'enterprise',label:'Operativen Wert vom Aktienanspruch unterscheiden'},
 {unit:'cashflow-preparation',section:'supplier-cash',label:'Vorräte, Einkauf und Lieferantenzahlungen verbinden'},
 {unit:'income-taxes',section:'reconciliation',label:'Steueraufwand und Steuerzahlung abgleichen'},
 {unit:'long-assets',section:'depreciation',label:'Abschreibung, Nutzungsdauer und Investition unterscheiden'}
],sources:[
 {title:'CFA Institute: Level I 2027, Financial Statement Forecasting in Equity Valuation, Seite 16; maßgebliche Lernzielzuordnung',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=16'},
 {title:'CFA Institute: Introduction to Financial Statement Modeling; ergänzende öffentliche Grundlage 2026',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/introduction-to-financial-statement-modeling'},
 {title:'Aswath Damodaran, NYU Stern: Working Capital in Valuation; operative Bestände und Mittelbindung',url:'https://pages.stern.nyu.edu/~adamodar/New_Home_Page/valquestions/noncashwc.htm'},
 {title:'Aswath Damodaran, NYU Stern: Cash Flow Estimation; Anspruch und Reinvestition',url:'https://pages.stern.nyu.edu/~adamodar/pdfiles/eqnotes/cashflow.pdf'},
 {title:'Aswath Damodaran, NYU Stern: Mature Companies – Value Drivers; Ertrag, Wachstum, Risiko und gesonderte Vermögenswerte',url:'https://pages.stern.nyu.edu/adamodar/New_Home_Page/littlebook/maturevaluedrivers.htm'}
],review:{status:'draft',date:'2026-10-06',note:'Eigene integrierte Jahres- und Endphasenfälle, explizite marginale Kapitalrendite und Anspruchspolitik; Gegenprüfungen ersetzen nicht die abschließende fachliche Gesamtabnahme.'}};
