const {F,T,X,S,G}=require('../author.cjs');
const weights=[1,5,10],xs=Array.from({length:101},(_,i)=>i);
module.exports={id:'voting',intro:[
 'Eine Beteiligung vermittelt Zahlungsrechte und Einflussmöglichkeiten. Beide können unterschiedlich verteilt sein. Wer zehn Prozent des Kapitals hält, hat weder zwangsläufig zehn Prozent der Stimmen noch automatisch Einfluss auf jede Entscheidung. Zur Analyse gehören Aktienklasse, Rechtsordnung, Beschlussgegenstand und die tatsächlich wirksame Ausübung der Rechte.',
 'CFA Level I 2027 behandelt hier Rechte verschiedener Aktienklassen und Rechtsordnungen sowie die Rollen im Abstimmungsprozess. Die folgenden eigenen Zahlenfälle vertiefen diese beschreibenden Lernziele. Ihre Wahlregeln sind ausdrücklich gesetzte Annahmen; nationale Rechtsbeispiele werden getrennt erläutert. Die Rechenmodelle dienen dem Verständnis, nicht als universelle Vorschrift für Hauptversammlungen.'
],sections:[
 S('rights','1. Wirtschaftliche Rechte und Stimmrechte getrennt lesen','a',[
  'Wirtschaftliche Rechte bestimmen die Beteiligung an Ausschüttungen, Liquidationserlösen und gegebenenfalls Bezugsrechten. Stimmrechte bestimmen, wer über bestimmte Fragen mitentscheidet. Auch Informations-, Antrags- und Sonderzustimmungsrechte können wichtig sein. Ein Vertrag kann wirtschaftlich gleichberechtigten Aktien ein unterschiedliches Stimmgewicht geben; umgekehrt können zwei gleich gewichtete Stimmen zu unterschiedlichen Zahlungsansprüchen gehören.',
  T(['Recht','Analysefrage','Mögliche Fehlinterpretation'],[['Dividende und Liquidation','Welche Klasse erhält wann und in welcher Reihenfolge etwas?','Gewinnanteil ist keine automatisch fällige Dividende.'],['Allgemeines Stimmrecht','Wie viele Stimmen je Aktie gelten für diesen Gegenstand?','Gleiche Aktienzahl muss nicht gleiches Stimmgewicht bedeuten.'],['Sonderzustimmung','Muss eine betroffene Klasse gesondert zustimmen?','Gesamtmehrheit ersetzt nicht jede Klassenentscheidung.'],['Information und Antrag','Welche Unterlagen und Beteiligungsmöglichkeiten bestehen?','Wenig Stimmgewicht bedeutet nicht zwingend keinerlei Schutz.'],['Übertragung und Umwandlung','Bleiben Sonderrechte bei Verkauf oder Fristablauf bestehen?','Heutige Kontrolle muss nicht dauerhaft unverändert bleiben.']],'Die konkrete Klasse wird als Rechtebündel beschrieben, bevor ihre Bezeichnung bewertet wird.'),
  'Eine stimmrechtslose Aktie ist deshalb nicht automatisch wertlos: Sie kann erhebliche Zahlungsansprüche haben. Ein Mehrstimmrecht garantiert umgekehrt keine zusätzliche Dividende. Sonderrechte können langfristige Strategien stabilisieren, aber auch die Rechenschaftspflicht gegenüber wirtschaftlich stark beteiligten Minderheitsaktionären schwächen. Beides ist in der Governanceanalyse zu berücksichtigen.'
 ]),
 S('jurisdiction','2. Rechtsordnung, Börsenregeln und Satzung zusammendenken','a',[
  'Die Rechtsordnung der Gesellschaft ist nicht schon aus Handelswährung, Börsenplatz oder Wohnsitz des Anlegers ersichtlich. Zuerst wird die rechtliche Einheit und ihr Gründungsrecht identifiziert. Gesellschaftsrecht, Wertpapier- und Börsenregeln sowie Satzung und konkrete Emissionsbedingungen wirken zusammen. Eine private Beteiligung kann zusätzlich vertragliche Zustimmungs- und Übertragungsregeln enthalten.',
  T(['Ebene','Was sie typischerweise klärt','Prüffrage'],[['Gesellschaftsrecht','Zulässige Aktienrechte, Organe und grundlegende Verfahren.','Welche Rechtsordnung und welche aktuelle Fassung gelten?'],['Wertpapier- und Börsenregeln','Information, Markttransparenz und Anforderungen der Notierung.','Welche Regeln kommen durch die konkrete Notierung hinzu?'],['Satzung und Klassenbedingungen','Stimmgewichte, Wahlverfahren und Sonderrechte im zulässigen Rahmen.','Welche gesetzlichen Grundregeln wurden wirksam ausgestaltet?'],['Versammlungsunterlagen','Stichtag, Gegenstände, Fristen und konkrete Zählregeln.','Was gilt bei genau dieser Abstimmung?'],['Anlagemandat','Wer darf für das Portfolio entscheiden und wie wird berichtet?','Ist die Ausübung beim Asset Owner oder Asset Manager vereinbart?']],'Die Ebenen ergänzen einander. Ein privater Vertrag setzt zwingendes Recht nicht außer Kraft.'),
  'Beispiel Delaware: DGCL § 212 sieht grundsätzlich eine Stimme je Aktie vor, lässt aber andere Gewichte im Certificate of Incorporation zu. § 214 erlaubt dort vorgesehenes kumulatives Wahlrecht. § 216 enthält Grundregeln zu Quorum und Mehrheiten, wobei gesetzliche Sonderregeln und zulässige Satzungsbestimmungen zu beachten sind. Das sind keine pauschalen Regeln für alle US-Gesellschaften.',
  'Beispiel Deutschland: § 12 AktG erlaubt nach den gesetzlichen Voraussetzungen auch stimmrechtslose Vorzugsaktien und Mehrstimmrechtsaktien. „In Deutschland gibt es ausschließlich eine Stimme je Aktie“ wäre daher falsch. Aus der gesetzlichen Möglichkeit folgt noch nicht, dass eine bestimmte Gesellschaft solche Aktien ausgegeben hat. Ihre tatsächlichen Bedingungen müssen geprüft werden.',
  'Beim Ländervergleich sind auch Organstruktur, Minderheitenschutz, Durchsetzung und Offenlegung relevant. Ein einstufiges Board und ein System mit getrenntem Leitungs- und Aufsichtsorgan verteilen Aufgaben anders. Aus der bloßen Anzahl der Organe folgt jedoch noch keine bessere Kontrolle. Die institutionelle Ausgestaltung wird im Governancekapitel vertieft.'
 ]),
 S('weights','3. Von Aktienzahlen zu Stimmgewichten','a',[
  F('q_{V,i}=\\frac{\\sum_{j=1}^{J}n_{ij}v_j}{\\sum_{j=1}^{J}N_jv_j}','Zuerst werden Aktien je Klasse mit den für den Gegenstand gültigen Stimmen je Aktie multipliziert. Erst dann wird die Quote gebildet. Es werden alle hier stimmberechtigten ausstehenden Aktien betrachtet.',[['q_{V,i}','Stimmrechtsquote von Anleger i an allen relevanten Stimmen.'],['n_{ij}','Von Anleger i gehaltene Aktien der Klasse j.'],['N_j','Gesamtzahl stimmberechtigter ausstehender Aktien der Klasse j.'],['v_j','Stimmen je Aktie der Klasse j für diesen Beschlussgegenstand.'],['J','Anzahl der berücksichtigten Aktienklassen.'],['i,j','Anlegerindex und Klassenindex.']]),
  X('Gleiche wirtschaftliche Ansprüche, verschiedene Stimmgewichte','90 Millionen A-Aktien besitzen je eine Stimme. Zehn Millionen B-Aktien besitzen je zehn Stimmen. Ausschüttungsrechte sind je Aktie identisch; eine Gründerin hält sämtliche B-Aktien und keine A-Aktien. Keine weiteren Klassen, eigenen Aktien oder Stimmrechtsbeschränkungen.',[
   F('q_E=\\frac{10}{90+10}=10\\%,\\qquad q_V=\\frac{10\\cdot10}{90+10\\cdot10}=52{,}63\\%','Der wirtschaftliche Nenner sind hundert Millionen gleichberechtigte Aktien; der Stimmnenner sind 190 Millionen Stimmen.',[['q_E','Wirtschaftlicher Anteil der Gründerin an den hier identischen Zahlungsrechten.'],['q_V','Anteil ihrer Stimmen an sämtlichen Stimmen.']]),
   'Eine einfache Mehrheit aller Stimmen kann sie im Modell allein erreichen. Für eine Zweidrittelmehrheit aller Stimmen reicht ihr Anteil nicht. Ein gesondertes Zustimmungsrecht der A-Klasse könnte sie mit B-Stimmen ebenfalls nicht ersetzen.'
  ],'Kontrolle ist immer relativ zur konkreten Entscheidung und ihrer Schwelle.'),
  'Unterschiedliche Aktienkurse ändern diese Stimmenzählung nicht. Auch die Quote am gesamten Börsenwert ist bei verschiedenen Klassenpreisen nicht mit der Stückzahlquote identisch. Beim wirtschaftlichen Vergleich werden deshalb Zahlungsrechte und beim politischen Einfluss die jeweiligen Stimmen separat ausgewiesen.'
 ]),
 S('leverage','4. Wie Mehrstimmrechte Kontrolle verstärken','a',[
  'Für zwei Klassen mit identischen wirtschaftlichen Rechten lässt sich der Zusammenhang besonders klar darstellen. Der betrachtete Eigentümer hält alle Mehrstimmrechtsaktien, deren Anteil am gesamten Kapital bekannt ist. Jede übrige Aktie hat genau eine Stimme.',
  F('q_V=\\frac{mq}{mq+(1-q)}=\\frac{mq}{1+(m-1)q}','Der Zähler ist das gewichtete Kapital des Eigentümers. Im Nenner kommt der einfach gewichtete übrige Anteil hinzu.',[['q_V','Anteil des Eigentümers an allen Stimmen.'],['q','Anteil seiner Mehrstimmrechtsaktien an allen wirtschaftlich gleichberechtigten Aktien, als Dezimalzahl.'],['m','Stimmen je Mehrstimmrechtsaktie; übrige Aktien haben eine Stimme.']]),
  F('q_V>\\frac12\\iff 2mq>mq+1-q\\iff q>\\frac{1}{m+1}','Bei positiver Stimmenbasis kann die Ungleichung ohne Vorzeichenwechsel umgeformt werden. Genau auf der Grenze liegen fünfzig Prozent, noch keine strikte Mehrheit.',[['q_V','Stimmrechtsquote.'],['q','Wirtschaftlicher Anteil der Mehrstimmrechtsklasse beim betrachteten Eigentümer.'],['m','Stimmenmultiplikator gegenüber der anderen Klasse.']]),
  G({id:'voting-leverage',title:'Stimmgewicht wächst schneller als Kapitalanteil',caption:'Eigene Modellrechnung mit gleichen wirtschaftlichen Rechten: Eine Person hält alle Aktien mit m Stimmen, die übrigen Aktien besitzen jeweils eine Stimme. Alle ausstehenden Stimmen sind im Nenner.',reading:'Bei einer Stimme je Aktie fallen Kapital- und Stimmquote zusammen. Bei zehn Stimmen je Aktie reichen etwas mehr als 9,09 Prozent des Kapitals für eine strikte Mehrheit aller Stimmen. Der Abstand ist keine zusätzliche Beteiligung am Gewinn.',plot:{x:[0,100],y:[0,100],xTicks:[0,20,40,60,80,100],yTicks:[0,20,40,50,60,80,100],xLabel:'Wirtschaftlicher Anteil in Prozent',yLabel:'Anteil an allen Stimmen in Prozent',series:weights.map(m=>({name:m+' Stimme'+(m===1?'':'n')+' je Aktie',points:xs.map(x=>[x,100*m*(x/100)/(1+(m-1)*x/100)])}))}}),
  'Der Zusammenhang hält nur, solange Rechte und Bestände unverändert bleiben. Eine Umwandlung in einfach stimmberechtigte Aktien, neue Emissionen oder ein Sunset-Mechanismus können die Quote verändern. Ein Sunset ist das Auslaufen eines Sonderrechts nach festgelegter Zeit oder Bedingung; welche Bedingung gilt, ergibt sich aus Recht und Vertrag.'
 ]),
 S('turnout','5. Teilnahmequote und tatsächlich abgegebene Stimmen','a b',[
  'Auch ohne Mehrstimmrechte kann ein geschlossener Block unter den tatsächlich Abstimmenden viel Gewicht haben. Das ist eine andere Aussage als eine Mehrheit aller ausstehenden Stimmen. Der Effekt hängt vom Verhalten der übrigen Anleger ab und kann bei einem umstrittenen Beschluss verschwinden.',
  F('q_{cast}=\\frac{b}{b+t(1-b)}','Ein Block beteiligt sich vollständig. Vom übrigen Stimmvolumen nimmt nur ein Anteil teil. Im Modell gibt es keine Enthaltungen, und alle Teilnehmenden geben gültige Ja- oder Nein-Stimmen ab.',[['q_{cast}','Anteil des Blocks an gültig abgegebenen Ja- und Nein-Stimmen.'],['b','Anteil des Blocks an allen ausstehenden Stimmen, als Dezimalzahl.'],['t','Teilnahmequote des übrigen Stimmvolumens zwischen null und eins.']]),
  X('Zwanzig Prozent werden im Abstimmungsergebnis zur Hälfte','Ein Block hält zwanzig Prozent aller Stimmen und stimmt geschlossen zu. Vom übrigen Bestand beteiligt sich ein Viertel; diese Stimmen lehnen geschlossen ab. Ein erforderliches Quorum sei separat erfüllt.',[
   F('q_{cast}=\\frac{0{,}20}{0{,}20+0{,}25\\cdot0{,}80}=50\\%','Zwanzig Prozentpunkte stimmen zu, weitere zwanzig Prozentpunkte dagegen. Eine strikte Mehrheit der abgegebenen Stimmen ist nicht erreicht.',[['q_{cast}','Zustimmungsanteil unter den gültigen Ja- und Nein-Stimmen.']]),
   'Steigt die Teilnahme der übrigen Anleger auf fünfzig Prozent, sinkt die Quote des Blocks auf ein Drittel. Bei Vollteilnahme beträgt sie wieder zwanzig Prozent. Der Kapitalanteil ändert sich in keinem dieser Fälle.'
  ],'Niedrige Teilnahme kann Einfluss vergrößern, beseitigt aber weder Quorum noch besondere Mehrheitserfordernisse.'),
  G({id:'turnout-power',title:'Derselbe Block bei unterschiedlicher Beteiligung',caption:'Geschlossener Block mit 20 % aller Stimmen nimmt vollständig teil; übrige Teilnahme variiert. Keine Enthaltungen. Die Grafik beurteilt weder ein Quorum noch die rechtliche Wirksamkeit eines Beschlusses.',reading:'Sinkende Teilnahme der anderen erhöht die Quote unter den abgegebenen Stimmen. Bei 25 Prozent Teilnahme des übrigen Bestands erreicht der Block genau 50 Prozent, nicht mehr als die Hälfte.',plot:{x:[0,100],y:[0,100],xTicks:[0,25,50,75,100],yTicks:[0,20,40,50,60,80,100],xLabel:'Teilnahme des übrigen Bestands in Prozent',yLabel:'Blockanteil an abgegebenen Stimmen in Prozent',series:[{name:'Block mit 20 % aller Stimmen',points:xs.map(t=>[t,100*.2/(.2+t/100*.8)])}]}}),
  'Ein Abstimmungsergebnis aus einem früheren Jahr ist damit keine sichere Prognose künftiger Kontrolle. Koalitionen, neue institutionelle Anleger, Kampagnen und Konflikte können Teilnahme und Stimmverhalten verändern.'
 ]),
 S('class-votes','6. Klassenabstimmungen und besondere Zustimmungen','a',[
  'Eine Klassenabstimmung prüft die Zustimmung innerhalb einer betroffenen Klasse. Solche Rechte können etwa bei Änderungen ihrer Ansprüche relevant werden. Ob sie bestehen, entscheidet die konkrete Rechts- und Vertragslage. Die einfache Gesamtzahl sämtlicher Stimmen reicht dann nicht als Entscheidungsmaßstab.',
  X('Gesamtmehrheit und Klassenmehrheit sind zwei Tests','Eine hypothetische Satzung verlangt für die Änderung einer Vorzugsklasse sowohl mehr als die Hälfte aller ausstehenden Stimmen als auch mehr als die Hälfte der ausstehenden Stimmen dieser Klasse. Jede der hundert Aktien hat für diese Abstimmung eine Stimme. Von achtzig Stammaktien stimmen sechzig zu; von zwanzig Vorzugsaktien stimmen acht zu. Alle übrigen stimmen dagegen.',[
   T(['Prüfung','Zustimmung','Nenner','Quote','Ergebnis'],[['Gesamt','68','100','68 %','Erfüllt'],['Vorzugsaktienklasse','8','20','40 %','Nicht erfüllt']],'Beide Bedingungen sind im Beispiel kumulativ erforderlich.'),
   'Der Antrag scheitert trotz achtundsechzig Prozent Gesamtzustimmung. Die sechzig Stammstimmen dürfen nicht in den Nenner oder Zähler der gesonderten Vorzugsabstimmung übernommen werden.'
  ],'Eine Klasse kann einen begrenzten Schutz besitzen, ohne das Unternehmen allgemein zu kontrollieren.'),
  'Auch ein Vetorecht ist gegenstandsbezogen: Eine Schutzklausel gegen die Verschlechterung eines Vorzugsanspruchs ist nicht dasselbe wie das Recht, das operative Tagesgeschäft anzuweisen. Bei verbundenen Parteien können ferner Stimmrechtsausschlüsse oder gesonderte Zustimmungen erforderlich sein; solche Ausschlüsse werden vor dem Rechnen ermittelt.'
 ]),
 S('quorum','7. Beschlussfähigkeit vor Mehrheitsprüfung','a b',[
  'Das Quorum ist die erforderliche Vertretung stimmberechtigter Anteile oder Stimmen, damit die betreffende Versammlung oder Abstimmung beschlussfähig ist. Die Bezugsgröße und die Behandlung einzelner Kategorien folgen den geltenden Regeln. Ein erfülltes Quorum sagt noch nichts darüber, ob ein Antrag genügend Zustimmung hat.',
  F('q_R=\\frac{R}{V}','Die hier verwendete Anwesenheitsquote vergleicht vertretenes, für das Quorum berücksichtigtes Stimmvolumen mit der maßgeblichen Gesamtbasis. Bei einer Quorumsregel nach Stückzahlen müssen entsprechend Stückzahlen eingesetzt werden.',[['q_R','Vertretungsquote für das im Beispiel definierte Quorum.'],['R','Für dieses Quorum gezählte vertretene Stimmen.'],['V','Gesamte für dieses Quorum maßgebliche Stimmenbasis.']]),
  X('Viele Ja-Stimmen unter Anwesenden können trotzdem nicht reichen','Eine eigene Modellregel verlangt mindestens fünfzig Prozent Vertretung von tausend ausstehenden Stimmen. Nur vierhundert sind vertreten; davon stimmen dreihundertneunzig für einen Antrag.',[
   'Die Zustimmung unter den Vertretenen beträgt 97,5 Prozent. Trotzdem sind nur vierzig Prozent der Gesamtbasis vertreten. Das Quorum ist nicht erfüllt; die hohe Zustimmung ersetzt die fehlende Beschlussfähigkeit nicht.',
   'Bei fünfhundert vertretenen Stimmen wäre diese ausdrücklich inklusive Schwelle erreicht. Lautete die Regel dagegen „mehr als die Hälfte“, wären mindestens fünfhunderteine notwendig. Die genaue Formulierung entscheidet am Rand.'
  ],'Zuerst Berechtigung und Quorum, danach die passende Mehrheit prüfen.')
 ]),
 S('denominators','8. Derselbe Stimmenstand, drei unterschiedliche Ergebnisse','a b',[
  'Eine Abstimmungsquote benötigt einen ausdrücklich benannten Nenner. „Mehrheit“ kann je nach Regel mehr als die Hälfte der gültigen Ja-/Nein-Stimmen, der vertretenen stimmberechtigten Stimmen oder aller ausstehenden stimmberechtigten Stimmen bedeuten. Diese Größen sind bei Enthaltungen oder Abwesenheit verschieden.',
  F('p_{cast}=\\frac{Y}{Y+N},\\qquad p_{represented}=\\frac{Y}{Y+N+A},\\qquad p_{outstanding}=\\frac{Y}{V}','Die Formeln beschreiben drei alternative Modellregeln. Im zweiten Nenner gibt es hier ausschließlich Ja, Nein und Enthaltungen; keine weiteren vertretenen Kategorien. Das Quorum wird separat geprüft.',[['Y','Gültige Ja-Stimmen.'],['N','Gültige Nein-Stimmen.'],['A','Vertretene und für diese zweite Regel berücksichtigte Enthaltungen.'],['V','Alle für den Gegenstand ausstehenden stimmberechtigten Stimmen.'],['p_{cast},p_{represented},p_{outstanding}','Zustimmungsquoten bei den drei angegebenen Bezugsgrößen.']]),
  X('Warum eine Enthaltung nicht immer neutral wirkt','Tausend Stimmen sind ausstehend. Dreihundertzwanzig stimmen zu, zweihundertachtzig dagegen, hundert enthalten sich; dreihundert sind nicht vertreten. Das vorgegebene Quorum von mindestens fünfzig Prozent ist erfüllt.',[
   T(['Alternative Regel','Rechnung','Zustimmung','Mehr als 50 %?'],[['Ja und Nein','320 / 600','53,33 %','Ja'],['Alle hier vertretenen Stimmen','320 / 700','45,71 %','Nein'],['Alle ausstehenden Stimmen','320 / 1.000','32,00 %','Nein']],'Die Regeln sind alternative Annahmen, keine Wahlmöglichkeit nach Bekanntwerden des Ergebnisses.'),
   'Bei der ersten Regel gehen Enthaltungen nicht in die Zustimmungsquote ein. Bei der zweiten erhöhen sie die erforderliche Zahl von Ja-Stimmen, ohne den Zähler zu erhöhen. Sie wirken für das Erreichen der Schwelle wie fehlende Zustimmung, bleiben aber als Stimmkategorie von Nein-Stimmen verschieden.',
   'Bei einer strikten Mehrheit aller tausend Stimmen wären fünfhunderteine Ja-Stimme erforderlich. Auch abwesende Anleger verringern diesen Nenner nicht. Eine Grenze von genau fünfzig Prozent genügt bei keiner der drei ausdrücklich strikten Mehrheitsregeln.'
  ],'Die richtige Rechnung beginnt mit dem Wortlaut der Zählregel.'),
  'Supermajority bezeichnet eine erhöhte Mehrheit, etwa mindestens zwei Drittel. Auch hier fehlen ohne Bezugsgröße und genaue Ungleichung entscheidende Informationen. Zwei Drittel der abgegebenen Stimmen sind nicht dasselbe wie zwei Drittel aller ausstehenden Stimmen.'
 ]),
 S('nonvotes','9. Enthaltung, fehlende Weisung und ungültige Stimme','a b',[
  'Eine Enthaltung ist eine abgegebene Erklärung. Ein Broker Non-Vote bezeichnet im US-Abstimmungsprozess dagegen eine fehlende Stimme des Intermediärs zu einem Gegenstand, für den ihm die Weisung und eine eigene Abstimmungsbefugnis fehlen. Eine ungültige oder verspätete Weisung ist wiederum ein anderes Problem. Die Kategorien werden nicht automatisch zusammengezählt.',
  'Nach den einschlägigen US-Regeln können Broker bei bestimmten Routinegegenständen unter Voraussetzungen ohne Kundenweisung abstimmen; bei anderen Gegenständen benötigen sie eine Weisung. Daraus folgt weder eine generelle Bankvollmacht für jede Frage noch eine weltweit einheitliche Einteilung. Die Versammlungsunterlagen erläutern die Behandlung des jeweiligen Gegenstands.',
  X('Vertreten für das Quorum, aber keine Stimme zum Antrag','Im hypothetischen Zählprotokoll sind 1.000 Stimmen ausstehend. Für das Quorum zählen 750 als vertreten: 300 Ja, 250 Nein, 100 Enthaltungen und 100 Broker Non-Votes. Für den Antrag gilt ausdrücklich mehr als die Hälfte aus Ja plus Nein; Enthaltungen und Broker Non-Votes sind aus diesem Nenner ausgeschlossen.',[
   'Das Quorum von mindestens fünfzig Prozent ist mit fünfundsiebzig Prozent erfüllt. Die maßgebliche Zustimmungsquote beträgt 300 geteilt durch 550, also 54,55 Prozent. Der Antrag ist nach der gesetzten Regel angenommen.',
   'Wer alle 750 vertretenen Stimmen als Mehrheitsnenner verwendet, erhält vierzig Prozent und beantwortet eine andere Frage. Wer die Broker Non-Votes als hundert zusätzliche Nein-Stimmen einträgt, verändert das tatsächliche Stimmprotokoll.'
  ],'Quorumsbasis und Abstimmungsbasis können unterschiedlich sein. Die Einordnung wird vorab festgelegt.'),
  'Die Berechnung ersetzt keine Prüfung der Berechtigung. Doppelte Weisungen, geänderte Weisungen und mehrere Depotstellen müssen nach den Verfahrensregeln abgeglichen werden. Eine versendete Nachricht ist noch kein Nachweis, dass die korrekte Stimmenzahl angenommen wurde.'
 ]),
 S('elections','10. Plurality Voting und Majority Voting unterscheiden','a',[
  'Plurality Voting wählt die Kandidaten mit den höchsten gültigen Stimmenzahlen für die verfügbaren Sitze. Eine absolute Mehrheit ist dabei nicht notwendig. Majority Voting verlangt dagegen eine festgelegte Mehrheit; der genaue Nenner und die Folgen bei Nichterreichen sind zu prüfen. Ein Rücktrittsverfahren für amtierende Direktoren ist nicht automatisch identisch mit einer sofortigen Neubesetzung.',
  X('Ein Sitz, drei Kandidaten','Dreihundert Stimmen werden abgegeben, jede nur für einen Kandidaten: A erhält 140, B 100 und C 60. Keine Enthaltungen oder ungültigen Stimmen.',[
   'Nach einer einfachen Plurality-Regel gewinnt A mit 46,67 Prozent. Nach einer Regel mit mehr als der Hälfte dieser dreihundert Stimmen erreicht niemand die erforderlichen 151 Stimmen.',
   'Ob dann eine Stichwahl, eine neue Wahl, eine vorübergehende Fortführung oder ein anderes Verfahren folgt, ist eine zusätzliche Regel. Sie lässt sich aus dem Wort „Majority“ allein nicht ableiten.'
  ],'Die höchste Stimmenzahl und die erforderliche Mehrheit sind zwei unterschiedliche Kriterien.'),
  'Bei Straight Voting kann der Anleger seine Stimmen für jeden zu besetzenden Sitz beziehungsweise zulässigen Kandidaten ausüben, aber nicht alle Sitzstimmen auf einen einzigen Kandidaten kumulieren. Ein geschlossener Mehrheitsblock kann unter einem entsprechenden Wahlverfahren sämtliche Sitze gewinnen. Genau diese Konzentrationsbeschränkung ändert kumulatives Wahlrecht.'
 ]),
 S('cumulative','11. Kumulatives Wahlrecht mathematisch verstehen','a',[
  'Bei Cumulative Voting erhält jede stimmberechtigte Aktie im einfachen Modell so viele Wahlstimmen, wie Sitze gleichzeitig zu wählen sind. Diese können auf einen Kandidaten konzentriert oder verteilt werden. Die meistgewählten Kandidaten erhalten die Sitze. Der Mechanismus verbessert die Chance einer konzentriert abstimmenden Minderheit auf Vertretung; er gibt ihr nicht automatisch eine Unternehmensmehrheit.',
  F('B=ds,\\qquad ds>N-s\\iff s>\\frac{N}{d+1},\\qquad s_{min}=\\left\\lfloor\\frac{N}{d+1}\\right\\rfloor+1','Für einen sicher gewinnbaren Sitz konzentriert der Block alle Wahlstimmen auf einen Kandidaten. Um ihn auszuschließen, müssten die übrigen Anleger d Kandidaten mindestens gleich viele Stimmen geben. Dafür bräuchten sie mindestens d mal ds Stimmen; verfügbar sind nur d mal (N−s). Gleichstand soll nicht als garantierter Sieg zählen.',[['B','Kumulative Wahlstimmen des betrachteten Blocks.'],['d','Zahl der gleichzeitig zu wählenden Sitze; die d höchstplatzierten Kandidaten gewinnen.'],['s','Vom geschlossen abstimmenden Block gehaltene Aktien mit jeweils gleichem Grundstimmrecht.'],['N','Gesamte stimmberechtigte Aktien; im Modell vollständige Teilnahme.'],['s_{min}','Kleinste ganze Aktienzahl, die unter diesen Annahmen einen Sitz ohne Gleichstandsrisiko sichert.'],['\\lfloor x\\rfloor','Abrunden der Zahl x auf die nächstkleinere ganze Zahl.']]),
  X('Der Unterschied zwischen fünfundzwanzig und sechsundzwanzig Aktien','Hundert Aktien, drei gleichzeitig zu wählende Sitze, gleiche Grundstimmrechte, vollständig teilnehmende Anleger. Der Minderheitsblock konzentriert alle Stimmen auf einen Kandidaten. Alle anderen Anleger dürfen sich optimal dagegen koordinieren.',[
   T(['Blockaktien','Blockstimmen für einen Kandidaten','Übrige Wahlstimmen','Können drei Rivalen mindestens gleichziehen?'],[['25','75','225','Ja: 75 + 75 + 75; Gleichstand möglich.'],['26','78','222','Nein: dafür wären mindestens 234 nötig.'],['30','90','210','Nein: dafür wären mindestens 270 nötig.']],'Eine Garantie erfordert einen strikten Vorsprung gegenüber mindestens einem der drei möglichen Rivalen.'),
   'Die Formel liefert abgerundet 100 / 4 plus eins, also 26 Aktien. Bei Straight Voting mit separaten Sitzentscheidungen könnte ein geschlossener Block aus 74 Aktien dagegen jeden der drei Sitze gewinnen. Das kumulative Wahlrecht verändert die Zuweisung der Stimmen, nicht die wirtschaftliche Beteiligung.'
  ],'Ein garantierter Sitz benötigt mehr als ein Viertel, nicht mindestens ein Viertel der Aktien in diesem Drei-Sitze-Modell.'),
  'Die Garantie setzt die genannten Regeln und eine zulässige eigene Kandidatur voraus. Unterschiedliche Grundstimmgewichte, Klassenwahlen, weniger gleichzeitig offene Sitze oder andere Wahlhürden verlangen eine neue Analyse. Die Formel ist eine zusätzliche Herleitung zur Intuition des Lernziels.'
 ]),
 S('staggered','12. Gestaffelte Wahlen ändern den Zeithorizont','a',[
  'Ein Staggered Board hat gestaffelte Amtszeiten: Nur ein Teil der Sitze wird in einem gewöhnlichen Wahlzyklus neu gewählt. Das kann Kontinuität ermöglichen und einen schnellen vollständigen Austausch erschweren. Für kumulative Wahlen zählt die Zahl der tatsächlich gleichzeitig offenen Sitze, nicht die gesamte Größe des Boards.',
  G({id:'cumulative-seats',title:'Mehr gleichzeitig offene Sitze erleichtern Minderheitenvertretung',caption:'Eigenes Modell: 100 stimmberechtigte Aktien, volle Teilnahme, Cumulative Voting und die d höchstplatzierten Kandidaten gewinnen. Gezeigt wird die kleinste ganze Aktienzahl für einen ohne Gleichstand garantierten Sitz.',reading:'Bei einem offenen Sitz werden 51 Aktien benötigt. Bei drei offenen Sitzen sind es 26, bei sechs 15. Ein Board aus sechs Personen mit jährlich nur zwei offenen Sitzen wird in dieser Rechnung mit zwei Sitzen angesetzt und verlangt 34 Aktien.',plot:{x:[1,6],y:[0,60],xTicks:[1,2,3,4,5,6],yTicks:[0,10,20,30,40,50,60],xLabel:'Gleichzeitig zu wählende Sitze',yLabel:'Benötigte Aktien von insgesamt 100',series:[{name:'Ein garantierter Sitz',points:[1,2,3,4,5,6].map(d=>[d,Math.floor(100/(d+1))+1])}],marks:[1,2,3,4,5,6].map(d=>({x:d,y:Math.floor(100/(d+1))+1,label:String(Math.floor(100/(d+1))+1),dx:d===6?-10:10,dy:-12,anchor:d===6?'end':'start'}))}}),
  'Die verbundenen Punkte erleichtern den Vergleich; Sitzanzahlen sind ausschließlich ganze Zahlen. Die Grafik zeigt keine möglichen Wahlen mit zweieinhalb Sitzen. Ein gestaffeltes Board hebt außerdem Abberufungs-, Sonderwahl- oder sonstige gesetzliche Rechte nicht pauschal auf.',
  'Für eine Anlageanalyse werden Nutzen und Kosten gemeinsam betrachtet: strategische Kontinuität, Schutz vor kurzfristigem Druck, erschwerte Ablösung schwacher Führung und mögliche Entrenchment-Effekte. Ob eine konkrete Regel Wert schafft, hängt von Unternehmen, Schutzrechten und Qualität der Verantwortlichen ab.'
 ]),
 S('record','13. Stichtag, Fristen und Berechtigung','b',[
  'Der Voting Record Date ist der maßgebliche Stichtag zur Feststellung der Stimmberechtigung nach dem anwendbaren Verfahren. Er ist nicht automatisch Versammlungstag, letzter Weisungstermin oder Dividendenstichtag. Kaufauftrag, Handelsabschluss, Abwicklung und register- beziehungsweise depotrechtlicher Nachweis können auf unterschiedliche Tage fallen.',
  T(['Schritt','Praktische Aufgabe','Warum er wichtig ist'],[['Ankündigung und Unterlagen','Gegenstände, Berechtigung, Form und Fristen lesen.','Ohne diese Angaben lässt sich die Stimme nicht zuverlässig planen.'],['Stichtagsprüfung','Berechtigten Bestand und gegebenenfalls Nachweiskette feststellen.','Ein späterer Depotbestand muss nicht die damalige Berechtigung wiedergeben.'],['Analyse und Entscheidung','Antrag, Konflikte, Mandat und Empfehlung prüfen.','Technische Ausübung ersetzt kein begründetes Urteil.'],['Interne Weisungsfrist','Ausreichenden Vorlauf bei Bank, Verwahrer oder Dienstleister einhalten.','Ein Intermediär kann früher schließen als die Versammlung.'],['Abgabe und Bestätigung','Gültige Weisung übermitteln, Status und Stimmenzahl abgleichen.','„Gesendet“ und „angenommen“ sind verschiedene Zustände.'],['Ergebnis und Nacharbeit','Auszählung, Abweichungen und Folgemaßnahmen dokumentieren.','Die Verantwortlichkeit endet nicht beim Absenden.']],'Die Reihenfolge ist ein Prozessmodell; tatsächliche Termine und zulässige Verfahren stehen in den konkreten Unterlagen.'),
  X('Ein korrekter Entschluss kann operativ zu spät kommen','In einer ausdrücklich hypothetischen Versammlung liegen der Stimmberechtigungsstichtag am 3. Juni, die Depotbankfrist am 18. Juni und die Versammlung am 20. Juni. Die Bank akzeptiert nach ihrer angegebenen Frist keine neuen Weisungen mehr. Eine berechtigte Anlegerin sendet ihre erste Weisung erst am 19. Juni.',[
   'Die Anlegerin war zwar am maßgeblichen Stichtag berechtigt, hat aber den gewählten Ausübungsweg verpasst. Aus der späteren Versammlung am 20. Juni folgt nicht, dass ihre Bank die verspätete Weisung noch verarbeitet.',
   'Ob ein anderer zulässiger Weg verfügbar ist, muss anhand der Unterlagen geprüft werden. Der Analyst darf keine erfolgreiche Stimmabgabe allein aus dem Aktienbestand oder dem Versand einer E-Mail ableiten.'
  ],'Berechtigung und fristgerechte technische Ausübung sind getrennte Voraussetzungen.')
 ]),
 S('chain','14. Eingetragener Inhaber und Depotkette','b',[
  'Ein Registered Owner steht unmittelbar als Inhaber im Register der Gesellschaft. Ein Beneficial Owner hält den wirtschaftlichen Anspruch über einen Intermediär, etwa eine Bank oder einen Broker. Im US-Street-Name-Verfahren erhält er typischerweise ein Voting Instruction Form: Damit weist er den Intermediär zur Ausübung an. Diese Weisung ist vom direkt gegenüber dem Emittenten verwendeten Proxy eines eingetragenen Inhabers zu unterscheiden.',
  'Proxy Voting ist die Ausübung durch einen Bevollmächtigten. Der Bevollmächtigte wird dadurch nicht automatisch wirtschaftlicher Eigentümer. Auch ein Stimmrechtsberater ist nicht schon durch seine Empfehlung der Bevollmächtigte. Analysiere deshalb nacheinander: Wem stehen die Ansprüche zu, wer entscheidet, wer ist formal berechtigt und wer übermittelt?',
  T(['Rolle in einer beispielhaften Kette','Beitrag','Nicht automatisch damit verbunden'],[['Asset Owner','Bestimmt Ziele und vereinbarte Zuständigkeiten.','Direkte Registerstellung jeder Portfolioposition.'],['Asset Manager','Trifft bei entsprechender Vollmacht Anlage- und Abstimmungsentscheidungen.','Wirtschaftliches Eigentum am Kundenvermögen.'],['Depotbank / Verwahrer','Führt Bestände und unterstützt die Weiterleitung berechtigter Weisungen.','Freie inhaltliche Entscheidung über jeden Antrag.'],['Bevollmächtigter / Plattform','Übermittelt oder übt im autorisierten Umfang aus.','Unbegrenztes Ermessen unabhängig vom Mandat.'],['Auszählungsstelle','Prüft und zählt die wirksamen Stimmen nach den Regeln.','Beurteilung, ob der Antrag eine gute Investitionsentscheidung ist.']],'In der Praxis können Rollen zusammenfallen; ihre Funktionen bleiben unterscheidbar.'),
  'Eine gute Prozesskontrolle stimmt berechtigten Bestand, erteilte Weisung und bestätigte Zählung ab. Bei mehreren Fonds oder Mandaten muss die richtige Position dem richtigen Auftrag zugeordnet werden. Unterschiedliche Mandate können zu unterschiedlichen zulässigen Entscheidungen führen; eine Plattform darf sie nicht unbemerkt zusammenlegen.'
 ]),
 S('issuer','15. Geschäftsleitung und Board: Vorschlag und Aufsicht','b',[
  'Die Geschäftsleitung liefert operative Informationen, begründet Vorhaben und unterstützt die Vorbereitung der Versammlungsunterlagen. Ihre Empfehlung kann sachlich fundiert sein, ist aber auch von eigenen Interessen betroffen, etwa bei Vergütung oder Machterhalt. Aktionäre beurteilen einen Antrag daher anhand seiner Folgen für das Unternehmen und ihrer Rechte.',
  'Das Board beziehungsweise das zuständige Aufsichtsorgan überwacht im jeweiligen Governance-System die Leitung, prüft Strategie und wesentliche Entscheidungen und kann Empfehlungen zur Abstimmung geben. Wer rechtlich einberuft, Tagesordnung festlegt oder Kandidaten vorschlägt, hängt von der Organstruktur und den Regeln ab. Management und Board sind keine austauschbaren Bezeichnungen.',
  X('Eine Vergütungsvorlage begründet prüfen','Eine Gesellschaft schlägt einen neuen Aktienvergütungsplan vor. Die Geschäftsleitung betont Mitarbeiterbindung; das zuständige unabhängige Board-Komitee erläutert Leistungsbedingungen, Verwässerung und Rückforderungsklauseln.',[
   'Der Investor prüft, ob die Leistungskennzahlen langfristige Wertschaffung fördern oder lediglich kurzfristige Kurs- beziehungsweise Bilanzziele. Außerdem vergleicht er den zusätzlichen Aktienbedarf mit der bestehenden Kapitalbasis und untersucht mögliche Interessenkonflikte.',
   'Eine positive Empfehlung eines unabhängigen Ausschusses ist ein relevantes Signal. Sie ersetzt weder die Prüfung der Angaben noch die Entscheidung im passenden Mandat. Ein Aktionär kann gut begründet zustimmen oder ablehnen.'
  ],'Empfehlung, Kontrolle und abschließende Stimmentscheidung sind unterschiedliche Aufgaben.'),
  'Auch die rechtliche Wirkung eines Antrags muss klar sein. Eine beratende Abstimmung signalisiert Zustimmung oder Kritik, ohne zwingend dieselbe unmittelbare Rechtswirkung wie ein bindender Beschluss zu haben. Ein Unternehmen sollte das Ergebnis dennoch im jeweiligen Governancezusammenhang beurteilen.'
 ]),
 S('owners','16. Asset Owner: Auftrag und Kontrolle des Beauftragten','b',[
  'Ein Asset Owner wie ein Pensionsfonds oder eine Stiftung trägt Verantwortung für Anlageziele und Begünstigte. Er legt im zulässigen Rahmen fest, welche Abstimmungsaufgaben selbst wahrgenommen und welche an Asset Manager übertragen werden. Dazu gehören Richtlinien, Berichtspflichten, Konfliktregeln und Eskalation bei Abweichungen.',
  'Delegation kann Expertise und Skalenvorteile nutzbar machen. Sie schafft aber eine weitere Principal-Agent-Beziehung: Der Eigentümer muss beurteilen können, ob der Beauftragte den vereinbarten Auftrag erfüllt. Eine bloße Zusage „wir stimmen verantwortungsvoll ab“ ist weniger überprüfbar als ein Protokoll mit Gegenstand, Entscheidung, Begründung und aufgetretenen Problemen.',
  T(['Vor Delegation klären','Bei laufender Kontrolle prüfen'],[['Wer entscheidet und welche Ausnahmen bleiben vorbehalten?','Wurden Entscheidungen innerhalb dieser Zuständigkeit getroffen?'],['Welche Ziele, Beschränkungen und rechtlichen Anforderungen gelten?','Passen die Begründungen zum Mandat und zu den Begünstigten?'],['Wie werden Interessenkonflikte behandelt?','Sind Konflikte identifiziert, bearbeitet und nachvollziehbar dokumentiert?'],['Wie werden verspätete oder fehlerhafte Weisungen behandelt?','Wurden Abweichungen erkannt und zeitnah behoben beziehungsweise berichtet?']],'Delegation verteilt Aufgaben; sie macht den Auftrag nicht bedeutungslos.'),
  'Beim Pensionsvermögen sind die maßgeblichen Begünstigten zu berücksichtigen. Der Wunsch des Unternehmens, das den Manager beauftragt oder Gebühren bezahlt, ist nicht automatisch identisch mit dem Interesse der Leistungsempfänger. Dieser Unterschied verbindet den Abstimmungsprozess mit den Kundenpflichten aus Ethics.'
 ]),
 S('managers','17. Asset Manager: Analyse, Ausführung und Nachweis','b',[
  'Ein Asset Manager prüft zunächst, ob und in welchem Umfang ihm die Abstimmung übertragen wurde. Dann verbindet er Unternehmensanalyse, Portfoliokontext und vereinbarte Richtlinien. Eine allgemeine Richtlinie schafft Konsistenz; außergewöhnliche Sachverhalte brauchen trotzdem ein begründetes Urteil.',
  'Stewardship bezeichnet hier den verantwortlichen Umgang mit anvertrautem Kapital einschließlich Überwachung, Dialog und gegebenenfalls Stimmrechtsausübung. Engagement ist der Austausch mit einem Emittenten zu relevanten Fragen. Ein Gespräch ist noch keine abgegebene Stimme; umgekehrt ist eine Stimme nur ein möglicher Bestandteil der Betreuung.',
  X('Vom Research zur überprüfbaren Ausführung','Ein Manager ist für die Stimmen eines Mandats verantwortlich. Ein Antrag soll eine Schutzklausel für Minderheitsaktionäre abschaffen. Seine allgemeine Richtlinie verlangt eine Einzelfallprüfung bei Änderungen von Schutzrechten.',[
   'Zuerst wird geklärt, was sich vertraglich ändert und welche wirtschaftlichen Folgen plausibel sind. Anschließend werden Emittentenbegründung, unabhängige Informationen und mögliche Beraterempfehlungen gewichtet.',
   'Die Entscheidung wird mit Bezug zum Mandat festgehalten und rechtzeitig übermittelt. Danach vergleicht das zuständige Team die bestätigte Stimmenzahl mit dem berechtigten Bestand. Eine Abweichung wird aufgeklärt und nach dem vereinbarten Verfahren berichtet.'
  ],'Analysequalität und Ausführungsqualität sind beide erforderlich.'),
  'Eine kostengünstige passive Anlagestrategie beseitigt diese Fragen nicht. Ein Indexfonds kann zwar weniger Spielraum zum Verkauf einer Indexposition haben, aber weiterhin Stimmrechte und vereinbarte Betreuungspflichten besitzen. Was konkret geschuldet ist, ergibt sich aus Recht, Mandat und offengelegter Politik.'
 ]),
 S('advisers','18. Stimmrechtsberater unterstützen das Urteil','b',[
  'Ein Proxy Adviser analysiert Abstimmungsunterlagen und gibt Empfehlungen nach einer Methodik oder kundenspezifischen Richtlinie. Manche Anbieter unterstützen zusätzlich die technische Abwicklung. Research, Empfehlung, Plattformdienst und rechtswirksame Bevollmächtigung sind jedoch verschiedene Leistungen.',
  'Stimmrechtsberater können Informationen bündeln und den Aufwand über viele Beteiligungen verteilen. Eine standardisierte Analyse kann aber unternehmensspezifische Besonderheiten übersehen. Der Manager prüft deshalb wesentliche Annahmen, Datenqualität, Aktualität und Passung zum Mandat. Eine Empfehlung allein überträgt ihm seine eigene Verantwortung nicht ab.',
  T(['Zu prüfender Punkt','Beispiel für seine Bedeutung'],[['Methodik','Ein pauschaler Schwellenwert kann Branchen- oder Lebenszyklusunterschiede unzureichend erfassen.'],['Datenstand','Eine spätere Änderung des Antrags kann eine frühere Empfehlung überholen.'],['Konflikte','Beratung des Emittenten und Empfehlung an Investoren können konkurrierende Interessen schaffen.'],['Leistungsumfang','Die Empfehlung „dagegen“ ist noch kein Nachweis einer wirksam übermittelten Nein-Stimme.'],['Kundenspezifische Vorgaben','Ein allgemeines Modell muss nicht sämtliche Einschränkungen eines Mandats abbilden.']],'Dies sind eigene Prüfkriterien für die Anwendung, keine Vermutung, dass jede Empfehlung fehlerhaft ist.'),
  'Der Manager muss nicht für jede routinemäßige Abstimmung sämtliche Daten unabhängig neu erheben. Er benötigt aber ein tragfähiges Verfahren zur Auswahl, Überwachung und sachgerechten Nutzung des Dienstleisters. Bei erkennbaren Fehlern oder wesentlichen Konflikten ist blindes Folgen keine belastbare Begründung.'
 ]),
 S('conflicts','19. Kundeninteresse, Konflikte und Aufwand','b',[
  'CFA Standard III(A) verlangt informierte, verantwortliche Behandlung des wirtschaftlichen Werts von Stimmrechten. Ungeprüft dem Management bei wesentlichen Governancefragen zu folgen, kann die Kundenpflichten verletzen. Eine dokumentierte Kosten-Nutzen-Abwägung kann aber ergeben, dass nicht jede einzelne Abstimmung dem Kunden nützt; die Politik ist offenzulegen. Strengere gesetzliche oder vertragliche Pflichten bleiben maßgeblich.',
  X('Ein kommerzieller Vorteil des Managers ist kein Kundennutzen','Ein Emittent bietet einem Asset Manager einen zusätzlichen Beratungsauftrag an, falls die verwalteten Fonds für einen umstrittenen Antrag stimmen. Eine unabhängige interne Analyse erwartet Nachteile für die betroffenen Fonds.',[
   'Der mögliche Honorarzuwachs fällt beim Manager an, die erwarteten Nachteile bei den Kundenportfolios. Die beiden Perspektiven dürfen in der Entscheidungsbegründung nicht vermischt werden.',
   'Der Konflikt ist nach den einschlägigen Regeln zu behandeln; eine bloße Offenlegung macht eine kundenwidrige Stimmentscheidung nicht sachgerecht. Ein unabhängiger Entscheidungsweg kann helfen, ersetzt aber die Orientierung am Mandat nicht.'
  ],'Der maßgebliche Nutzen gehört den berechtigten Kunden beziehungsweise Begünstigten.'),
  'Ebenso wenig rechtfertigt die kleine eigene Stimmenzahl automatisch Untätigkeit. Bedeutung des Beschlusses, mögliche Zusammenarbeit, Aufwand und Mandat gehören in die Beurteilung. Die Wahrscheinlichkeit, allein ausschlaggebend zu sein, ist nur ein Aspekt. Ein rein mechanischer Vergleich einzelner Bearbeitungskosten mit einem unterstellten sicheren Gewinn wäre Scheingenauigkeit.',
  'In der Dokumentation werden deshalb Zuständigkeit, Informationsgrundlage, wesentliche Konflikte, Entscheidung und Ausführung festgehalten. Eine begründete Ausnahme ist überprüfbar; ein fehlender Prozess wird durch das Wort „Kosten“ nicht nachträglich zu einer Analyse.'
 ]),
 S('case','20. Gesamtablauf an einem verbundenen Zahlenfall','a b',[
  X('Vom Aktienregister bis zum Abstimmungsergebnis','Eine hypothetische Gesellschaft hat 80 Millionen A-Aktien mit einer Stimme und 20 Millionen B-Aktien mit fünf Stimmen. Wirtschaftliche Rechte je Aktie sind identisch. Die Gründerfamilie hält alle B-Aktien. Der Antrag benötigt mehr als die Hälfte der gültigen Ja- und Nein-Stimmen; Quorum mindestens die Hälfte aller Stimmen. Keine Klassenabstimmung oder Sondermehrheit. Alle B-Stimmen sind vertreten und stimmen zu. Von A sind 60 Millionen Stimmen vertreten: 15 Millionen Ja, 35 Millionen Nein und zehn Millionen Enthaltungen. Die übrigen A-Aktien sind nicht vertreten.',[
   F('V=80+20\\cdot5=180,\\qquad q_E=20\\%,\\qquad q_V=\\frac{100}{180}=55{,}56\\%','Alle Stimmenzahlen dieser Rechnung sind Millionen. Die Familie besitzt zwanzig Prozent der gleichberechtigten Aktien, aber mehr als die Hälfte aller Stimmen.',[['V','Gesamte ausstehende Stimmen in Millionen.'],['q_E','Wirtschaftlicher Anteil der Familie.'],['q_V','Stimmrechtsquote der Familie an allen ausstehenden Stimmen.']]),
   F('q_R=\\frac{60+100}{180}=88{,}89\\%,\\qquad p_{cast}=\\frac{15+100}{15+100+35}=76{,}67\\%','Die Enthaltungen zählen hier zur ausdrücklich definierten Vertretung, aber nicht zu Ja plus Nein. Quorum und Zustimmung sind erfüllt.',[['q_R','Für das Quorum maßgebliche Vertretungsquote.'],['p_{cast}','Zustimmung unter gültigen Ja- und Nein-Stimmen.']]),
   T(['Änderung nur einer Annahme','Folge','Was unverändert bleibt'],[['B wird vor dem Stichtag wirksam in einfach stimmberechtigte Aktien umgewandelt.','Stimmen insgesamt 100; vertreten 80; Ja 35, Nein 35: 50 % der gültigen Stimmen, Antrag scheitert.','Wirtschaftlicher Familienanteil 20 %.'],['Stattdessen gilt bei ursprünglichen B-Rechten mindestens zwei Drittel aller ausstehenden Stimmen.','Erforderlich sind 120 Millionen Ja-Stimmen; vorhanden 115: Antrag scheitert.','Ursprüngliche Stimmzahlen, Quorum und Kapitalanteile.']],'Die Alternativen gelten jeweils für sich; sie werden nicht miteinander vermischt.'),
   'Der verantwortliche Asset Manager prüft die Rechte und den Antrag vor der Entscheidung. Der Asset Owner kontrolliert den vereinbarten Auftrag. Ein Proxy Adviser kann die Analyse unterstützen. Der Verwahrer übermittelt berechtigte Weisungen; die Auszählungsstelle wendet die feststehenden Regeln an. Keine dieser Tätigkeiten lässt sich durch die richtige Prozentrechnung allein ersetzen.'
  ],'Rechte, Teilnahme, Zählregel und Rollen müssen im selben Fall konsistent zusammenpassen.')
 ]),
 S('review','21. Anwendung, Grenzen und Lösungsweg','a b',[
  T(['Schritt','Nachweis einer belastbaren Antwort'],[['1. Rechtsträger und Gegenstand','Rechtsordnung, Aktienklassen und konkrete Entscheidung benannt.'],['2. Berechtigung','Stichtag, Bestand, Stimmgewichte und Ausschlüsse geprüft.'],['3. Verfahren','Quorum, Mehrheitsnenner, Fristen und Sonderzustimmungen getrennt.'],['4. Entscheidung','Wirtschaftliche Folgen, Kundeninteresse und Konflikte beurteilt.'],['5. Ausführung','Zuständigkeit, Weisung und bestätigte Stimmenzahl abgestimmt.'],['6. Ergebnis','Zählung und Bedeutung des Beschlusses erklärt, Folgemaßnahmen festgehalten.']],'Dieses Schema verbindet die beiden Lernziele des Moduls.'),
  'In Prüfungsfällen markierst du besonders „ausstehend“, „vertreten“, „gültig abgegeben“, „mehr als“ und „mindestens“. Bei einer Rollenfrage suche nach Entscheidung, Beratung, Übermittlung oder Auszählung. Bei einer Konfliktfrage identifiziere die tatsächlich berechtigten Begünstigten, bevor du einen kommerziellen Vorteil als Nutzen bewertest.',
  'Für reale Bewertungen sind die Grenzen ebenso wichtig: Mathematische Stimmmehrheit ist nicht unbegrenzte rechtliche Macht, Minderheitenschutz ist nicht automatisch wirksam durchgesetzt, und hohe Teilnahme garantiert keine gute Entscheidung. Dieses Modul erklärt die Mechanik; Qualität der Unternehmensführung, Anreize und erwartete Zahlungswirkungen werden mit den verbundenen Kapiteln zusammen beurteilt.'
 ])
],related:[
 {unit:'equity-features',section:'classes',label:'Aktienklassen und wirtschaftliche Instrumentenrechte vergleichen'},
 {unit:'governance',section:'shareholder-rights',label:'Minderheitenschutz und Wahlverfahren im Governancezusammenhang'},
 {unit:'issuer-forms',section:'voting',label:'Gesellschaftsform, Kapitalanteil und Kontrolle'},
 {unit:'standard-iii',section:'loyalty',label:'Loyalität, Begünstigte und verantwortliche Stimmrechtsausübung'},
 {unit:'standard-vi',section:'conflicts',label:'Interessenkonflikte erkennen und behandeln'},
 {unit:'leases-compensation',section:'share-payments',label:'Aktienvergütung und Verwässerung verstehen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Equity Jurisdictions, Classes, and the Voting Process',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=15'},
 {title:'Delaware General Corporation Law: §§ 212–214 und 216; ausdrücklich rechtsordnungsspezifische Beispiele',url:'https://delcode.delaware.gov/title8/c001/sc07/index.html'},
 {title:'Bundesministerium der Justiz / Bundesamt für Justiz: § 12 AktG, Stimmrechte',url:'https://www.gesetze-im-internet.de/aktg/__12.html'},
 {title:'SEC Investor.gov: eingetragene und wirtschaftliche Inhaber im Abstimmungsprozess',url:'https://www.investor.gov/what-difference-between-registered-and-beneficial-owners-when-voting-corporate-matters'},
 {title:'SEC Investor.gov: Wege der Stimmabgabe',url:'https://www.investor.gov/what-are-mechanics-voting-either-person-or-proxy'},
 {title:'SEC Investor.gov: Broker Vote, begrenzte Ausübung ohne Kundenweisung',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/broker-vote'},
 {title:'SEC Investor.gov: Cumulative Voting',url:'https://www.investor.gov/introduction-investing/investing-basics/glossary/cumulative-voting'},
 {title:'OECD: G20/OECD Principles of Corporate Governance 2023, institutionelle Anleger und Intermediäre',url:'https://www.oecd.org/en/publications/g20-oecd-principles-of-corporate-governance-2023_ed750b30-en/full-report/component-6.html'},
 {title:'CFA Institute: Standard III(A), Proxy Voting Policies und Kundenpflichten',url:'https://www.cfainstitute.org/standards/professionals/code-ethics-standards/standards-of-practice-iii-a'}
],review:{status:'draft',date:'2026-09-29',note:'Eigene Rechte-, Quorums-, Mehrheits- und Wahlfälle. Nationale Beispiele eng abgegrenzt; zusätzliche mathematische Herleitungen dienen der Intuition der beschreibenden Lernziele. Fachlicher Gesamtaudit bleibt offen.'}};
