const {F,T,X,S,G}=require('../author.cjs');
module.exports={id:'working-capital',intro:[
 'Ein Unternehmen kann einen Gewinn ausweisen und trotzdem eine heute fällige Rechnung nicht bezahlen. Zwischen Einkauf, Leistung, Verkauf und Zahlung liegen oft Wochen. In dieser Zeit binden Vorräte und Forderungen Geld; Lieferantenkredit und andere Finanzierungsquellen überbrücken einen Teil des Bedarfs. Working Capital verbindet deshalb das Geschäftsmodell mit Bilanz, Zahlungsstrom und Finanzierung.',
 'Dieses Kapitel entwickelt die drei Lernziele für CFA Level I 2027: den Cash Conversion Cycle erklären und vergleichen, Liquidität beurteilen sowie Maßnahmen zur Steuerung von Betriebskapital und Zahlungsfähigkeit abwägen. Eigene Zahlenfälle trennen Bestandsgrößen von Zahlungsströmen, eine einmalige Geldfreisetzung von laufendem Ertrag und eine bessere Kennzahl von wirtschaftlich besserem Verhalten. Zusätzliche Herleitungen dienen dem Verständnis; es gibt keine allgemeingültige optimale Tageszahl oder Liquiditätsquote.'
],sections:[
 S('definitions','1. Welches Kapital ist tatsächlich gebunden?','a b',[
  'Working Capital wird nicht überall gleich abgegrenzt. Das bilanzielle Nettoumlaufvermögen ist das kurzfristige Vermögen abzüglich kurzfristiger Verbindlichkeiten. Für eine operative Analyse interessieren häufig speziell Vorräte und Forderungen aus Lieferungen und Leistungen abzüglich Lieferantenverbindlichkeiten. Überschüssiges Geld und verzinsliche Finanzierung sollen dann nicht mit der Kapitalbindung im Warenprozess vermischt werden.',
  F('NWC=CA-CL,\\qquad OWC=I+AR-AP','Die erste Größe umfasst alle als kurzfristig klassifizierten Bilanzposten. Die zweite ist die ausdrücklich vereinfachte operative Abgrenzung dieses Kapitels.',[['NWC','Net Working Capital: bilanzielles Nettoumlaufvermögen.'],['CA','Current Assets: gesamtes kurzfristiges Vermögen einschließlich dort ausgewiesener Zahlungsmittel.'],['CL','Current Liabilities: gesamte kurzfristige Verbindlichkeiten einschließlich kurzfristiger Finanzschulden.'],['OWC','Operatives Working Capital in der hier definierten Abgrenzung.'],['I','Vorräte zum Buchwert.'],['AR','Trade Accounts Receivable: Forderungen aus Lieferungen und Leistungen.'],['AP','Trade Accounts Payable: Verbindlichkeiten aus Lieferungen und Leistungen.']]),
  T(['Fragestellung','Geeignete Sicht','Wichtige Grenze'],[['Welche kurzfristigen Vermögenswerte übersteigen kurzfristige Pflichten?','NWC und Zusammensetzung der Bilanz.','Fälligkeit und tatsächliche Verwertbarkeit fehlen in der bloßen Differenz.'],['Wie viel Kapital bindet der Waren- und Kreditverkaufsprozess?','OWC und dessen Veränderung.','Weitere operative Posten können wichtig sein und müssen dann ausdrücklich ergänzt werden.'],['Kann eine konkrete Zahlung fristgerecht erfolgen?','Zeitlich gegliederter Liquiditätsplan mit verfügbaren Mitteln.','Eine positive Bilanzgröße ist kein heute verfügbares Bankguthaben.']],'Brutto-Working-Capital bezeichnet in manchen Texten nur das kurzfristige Vermögen. Vor jedem Vergleich ist daher die Definition zu lesen.'),
  'Beispiel: Zahlungsmittel 30, Vorräte 50, Kundenforderungen 40, Lieferantenverbindlichkeiten 35 und kurzfristiger Bankkredit 25 ergeben NWC von 60 und OWC von 55. Die Differenz von fünf ist hier Zahlungsmittel minus Bankkredit. Weitere operative Abgrenzungen könnten beispielsweise Steuerschulden, Rückstellungen oder erhaltene Anzahlungen einbeziehen. Das Wort Working Capital allein ersetzt diese Abgrenzung nicht.',
  'Liquidität bezeichnet die Fähigkeit, fällige Zahlungen rechtzeitig zu leisten; bei einem Vermögenswert meint sie dessen zeitnahe Umwandelbarkeit in Geld ohne erheblichen Preisabschlag. Profitabilität beschreibt Ertragskraft, Solvenz die längerfristige Tragfähigkeit der Ansprüche. Ein wertvolles, aber schwer verkäufliches Gebäude kann zur Solvenz beitragen, ohne die morgige Lohnzahlung zu ermöglichen.'
 ]),
 S('cash-timeline','2. Vom Einkauf zum Geld: eine vollständige Zeitachse','a b',[
  X('Gewinn an Tag 45, Zahlungseingang erst an Tag 75','Ein Händler erhält an Tag 0 Ware für 100 Euro auf Rechnung, bezahlt an Tag 20 und verkauft die gesamte Ware an Tag 45 für 130 Euro auf Ziel. Der Kunde zahlt an Tag 75. Umsatz und Aufwand werden am Verkaufstag erfasst. Es gibt keine weiteren Aufwendungen, Steuern, Zinsen oder Anfangsbestände.',[
   T(['Tag und Ereignis','Vorräte','Forderungen','Lieferantenverbindlichkeiten','Kumulierter Gewinn','Kumulierte Zahlungen netto'],[['0: Ware erhalten','100','0','100','0','0'],['20: Lieferant bezahlt','100','0','0','0','−100'],['45: Ware verkauft','0','130','0','30','−100'],['75: Kunde bezahlt','0','0','0','30','30']],'Alle Werte in Euro. Die letzte Spalte zeigt Einzahlungen minus Auszahlungen aus diesem Geschäft vor Finanzierung, keinen tatsächlich erlaubten negativen Kassenbestand.'),
   'Die Lagerphase dauert 45 Tage. Nach dem Verkauf folgen weitere 30 Tage bis zur Kundenzahlung. Der Lieferant finanziert die ersten 20 Tage. Das Unternehmen muss deshalb 55 Tage zwischen eigener Zahlung und Geldeingang überbrücken. Ein Bankkredit würde die tatsächliche Kontobewegung ergänzen; er wird hier bewusst außerhalb des operativen Zahlungsstroms gehalten.',
   'Am Verkaufstag steigt der Gewinn um 30, aber kein Geld geht ein. Erst die Zahlung ersetzt die Forderung durch Zahlungsmittel. Am Ende verbleiben 30 Euro netto: Die Einzahlung von 130 darf nicht mit dem Nettoüberschuss nach dem vorherigen Einkauf verwechselt werden.'
  ],'Erfolg wird nach Leistungs- und Aufwandszuordnung gemessen; Zahlungsfähigkeit hängt von Terminen ab. Genau diese zeitliche Lücke erklärt den Finanzierungsbedarf.'),
  G({id:'cash-timeline',title:'Die Finanzierungslücke beginnt mit der Lieferantenzahlung',caption:'Eigener Einzelfall, Beträge in Euro vor Finanzierung. Einkauf an Tag 0, Zahlung an Tag 20, Verkauf an Tag 45, Kundenzahlung an Tag 75. Negative Werte sind der kumulierte operative Geldabfluss dieses Geschäfts.',reading:'Zwischen Tag 20 und Tag 75 fehlen 100 Euro aus dem Geschäft. Der Verkauf an Tag 45 ändert diese Zahlungsposition noch nicht. An Tag 75 steigt die Summe um 130 auf einen Nettoüberschuss von 30 Euro.',plot:{x:[0,90],y:[-120,50],xTicks:[0,20,45,75,90],yTicks:[-100,-50,0,30],xLabel:'Tage seit Wareneingang',yLabel:'Kumulierte Zahlungen netto in Euro',series:[{name:'Operativer Zahlungsstrom vor Finanzierung',points:[[0,0],[20,0],[20,-100],[75,-100],[75,30],[90,30]]}],marks:[{x:20,y:-100,label:'Zahlung −100',dx:8,dy:20},{x:45,y:-100,label:'Verkauf: noch kein Geld',dx:-75,dy:-15},{x:75,y:30,label:'Einzahlung +130',dx:-105,dy:-15}]}}),
  'Die Zeitachse verfolgt ein einzelnes Geschäft. Aus Jahresabschlüssen berechnete Tageskennzahlen sind dagegen Durchschnittsnäherungen für viele überlappende Geschäfte. Sie sagen nicht voraus, dass jede einzelne Rechnung genau am durchschnittlichen Tag bezahlt wird.'
 ]),
 S('cycle-formulas','3. Bestände in Tage übersetzen und den CCC herleiten','a',[
  'Ein durchschnittlicher Bestand geteilt durch den passenden Jahresstrom ergibt den Anteil eines Jahres, den dieser Bestand repräsentiert. Multiplikation mit der Tagesbasis übersetzt diesen Anteil in Tage. Die passenden Ströme unterscheiden sich: Vorräte stehen zu Kosten in der Bilanz, Kundenforderungen enthalten den Verkaufspreis, Lieferantenverbindlichkeiten entstehen aus Einkäufen.',
  F('DIO=\\frac{\\bar I}{COGS}D,\\qquad DSO=\\frac{\\overline{AR}}{S_c}D,\\qquad DPO=\\frac{\\overline{AP}}{P_c}D','Bestände und Ströme müssen dieselbe Aktivität, Währung und Periodenabgrenzung beschreiben.',[['DIO','Days Inventory Outstanding: durchschnittliche Vorratstage.'],['DSO','Days Sales Outstanding: durchschnittliche Forderungstage.'],['DPO','Days Payables Outstanding: durchschnittliche Lieferantenverbindlichkeitstage.'],['\\bar I','Durchschnittlicher Vorratsbestand; der Überstrich kennzeichnet einen Periodendurchschnitt.'],['\\overline{AR}','Durchschnittliche Forderungen aus Kreditverkäufen.'],['\\overline{AP}','Durchschnittliche Lieferantenverbindlichkeiten.'],['COGS','Cost of Goods Sold: Umsatzkosten der betrachteten Periode.'],['S_c','Kreditumsatz der Periode.'],['P_c','Einkäufe auf Kredit in der Periode.'],['D','Tage der betrachteten Periode beziehungsweise vereinbarte Jahresbasis, hier regelmäßig 365.']]),
  F('OC=DIO+DSO,\\qquad CCC=OC-DPO=DIO+DSO-DPO','Der operative Zyklus reicht vom Vorratserwerb bis zur Kundenzahlung. Die vom Lieferanten gewährte Finanzierung verkürzt die eigene Zahlungsbindung.',[['OC','Operating Cycle: Dauer des operativen Zyklus in Tagen.'],['CCC','Cash Conversion Cycle: Geldumschlagsdauer in Tagen.'],['DIO','Durchschnittliche Vorratstage.'],['DSO','Durchschnittliche Forderungstage.'],['DPO','Durchschnittliche Lieferantenverbindlichkeitstage.']]),
  F('CCC=45+30-20=55','Im Einzelfall des vorigen Abschnitts stimmen die Zeitabstände unmittelbar mit den Tageskomponenten überein.',[['CCC','Geldumschlagsdauer in Tagen für das gezeigte Geschäft.']]),
  'Steigen die Vorrats- oder Forderungstage bei sonst gleichen Bedingungen um zehn, steigt auch der CCC um zehn. Steigen die Lieferantenverbindlichkeitstage um zehn, fällt der CCC um zehn. Das Vorzeichen folgt aus dem Zahlungszeitpunkt: Wer später selbst zahlt, muss eine kürzere Lücke finanzieren. Ob die Verzögerung wirtschaftlich sinnvoll oder vertragsgemäß ist, steht auf einem anderen Blatt.',
  'Umschlagshäufigkeit und Tage sind Gegenstücke: Bei zwölf Vorratsumschlägen pro 360-Tage-Jahr entspricht der durchschnittliche Vorrat einem Monat oder 30 Tagen. Eine Aufgabe mit 360 Tagen muss durchgängig diese Basis verwenden. Ein Dreimonatsstrom darf nicht ohne passende Anpassung wie ein Jahresstrom behandelt werden.'
 ]),
 S('measurement','4. Richtige Nenner, Saisonalität und Vergleichbarkeit','a b',[
  F('P=COGS+I_1-I_0','Für einen vereinfachten Warenbestand ohne Wertberichtigung, Wechselkurs-, Erwerbs- oder andere Sondereffekte entsprechen Einkäufe dem Verbrauch zuzüglich Bestandsaufbau.',[['P','Gesamte Einkäufe der Periode zu Anschaffungskosten.'],['COGS','Kosten der verkauften Ware.'],['I_1','Vorratsbestand am Periodenende.'],['I_0','Vorratsbestand am Periodenanfang.']]),
  X('Warum Umsatzkosten den Lieferantenkredit verzerren können','365 Tage, Umsatzkosten 730.000 Euro, Anfangsvorräte 80.000, Endvorräte 153.000 und durchschnittliche Lieferantenverbindlichkeiten 66.000 Euro. Alle Einkäufe erfolgen auf Kredit; außer Kauf und Verkauf gibt es keine Bestandsveränderungen.',[
   F('P=730000+153000-80000=803000,\\qquad DPO=\\frac{66000}{803000}365=30','Die Bestände steigen; deshalb wurde mehr eingekauft als verkauft beziehungsweise verbraucht.',[['P','Jahreseinkäufe in Euro, hier zugleich Krediteinkäufe.'],['DPO','Lieferantenverbindlichkeitstage auf der Einkaufbasis.']]),
   'Mit Umsatzkosten im Nenner ergäben sich 33 Tage. Das wäre in diesem Fall eine Überschätzung um drei Tage und ließe den CCC zu kurz erscheinen. Bei fehlenden Einkaufsdaten kann der Umsatzkostenansatz eine offengelegte Näherung sein; hier liegen aber ausreichende Daten für die richtige Basis vor.'
  ],'Den Nenner nicht nach Bequemlichkeit wählen: Ein steigender Vorratsbestand erklärt, warum Einkauf und Aufwand auseinanderfallen.'),
  'Für Forderungen ist Kreditumsatz die sachgerechte Basis. Wenn 40 % der Verkäufe sofort bezahlt werden, erzeugen diese Verkäufe keine vergleichbare Kundenforderung. Der Gesamtumsatz im Nenner kann dann den tatsächlichen Einzug der Kreditverkäufe zu schnell erscheinen lassen. Ist die Umsatzaufteilung unbekannt, ist der Gesamtumsatz eine ausdrücklich bezeichnete Näherung.',
  'Der Mittelwert aus Anfangs- und Endbestand ist bei gleichmäßigem Geschäft oft brauchbar. Bei einem saisonalen Händler können beide Stichtage den jährlichen Höchstbestand verfehlen; monatliche oder tägliche Durchschnitte sind dann aussagekräftiger. Ein schneller Verkauf von Forderungen direkt vor dem Bilanzstichtag verkürzt die ausgewiesenen Forderungstage, ohne zwingend das Zahlungsverhalten der Kunden zu verbessern.',
  'Vergleiche benötigen ähnliche Geschäftsmodelle, Bilanzierungsregeln, Brutto- oder Nettodarstellung, Steuerbehandlung und Perioden. Forderungen einschließlich Umsatzsteuer durch Umsatz ohne diese Steuer zu teilen erzeugt eine weitere Verzerrung. Ein ungewöhnlicher Wert ist ein Ausgangspunkt für die Untersuchung, noch kein Beweis für Effizienz oder Fehlverhalten.'
 ]),
 S('cash-amount','5. Von Tagen zu Euro: Warum CCC mal Tageskosten nicht genügt','a c',[
  'Tage messen Dauer; Euro messen Kapitalbindung. Dieselbe Dauer kann bei anderem Umsatzvolumen viel mehr Geld benötigen. Außerdem stehen Forderungen zu Verkaufspreisen und Vorräte zu Kosten in der Bilanz. Deshalb lässt sich die operative Kapitalbindung im Allgemeinen nicht durch Multiplikation des gesamten CCC mit einem einzigen Tagesbetrag rekonstruieren.',
  F('OWC=c\\,DIO+s\\,DSO-p\\,DPO','Die Umstellung der Tageskennzahlen liefert jeden Bestand auf seiner eigenen Strombasis. Alle Bestände sind hier konsistent als Durchschnitte definiert.',[['OWC','Durchschnittliches operatives Working Capital, hier Vorräte plus Forderungen minus Lieferantenverbindlichkeiten.'],['c','Umsatzkosten je Tag.'],['s','Kreditumsatz je Tag.'],['p','Krediteinkäufe je Tag.'],['DIO','Vorratstage.'],['DSO','Forderungstage.'],['DPO','Lieferantenverbindlichkeitstage.']]),
  X('40 Tage entsprechen hier nicht 8.000 Euro','Ein stationärer Händler verkauft täglich auf Kredit für 300 Euro. Tägliche Umsatzkosten und Krediteinkäufe betragen jeweils 200 Euro. DIO sind 50, DSO 30 und DPO 40 Tage. Bestände und Tagesströme sind dauerhaft repräsentativ.',[
   T(['Posten','Rechnung','Durchschnittlicher Betrag'],[['Vorräte','50 × 200','10.000 €'],['Kundenforderungen','30 × 300','9.000 €'],['Lieferantenverbindlichkeiten','40 × 200','8.000 €'],['Operative Kapitalbindung','10.000 + 9.000 − 8.000','11.000 €']],'Der CCC beträgt 50 + 30 − 40 = 40 Tage; 40 × 200 = 8.000 Euro lässt die Forderungen fälschlich nur zu Kosten entstehen.'),
   F('OWC=c\\,CCC+(s-c)DSO=200\\cdot40+100\\cdot30=11000','Diese zweite Darstellung gilt unter der zusätzlichen Annahme, dass tägliche Krediteinkäufe und Umsatzkosten gleich groß sind.',[['OWC','Durchschnittliche operative Kapitalbindung in Euro.'],['c','Umsatzkosten je Tag, hier zugleich Krediteinkäufe je Tag.'],['s','Kreditumsatz je Tag.'],['CCC','Cash Conversion Cycle in Tagen.'],['DSO','Forderungstage.']]),
   'Die zusätzlichen 3.000 Euro sind die im Forderungsbestand enthaltene Differenz zwischen Verkaufspreis und Kosten. Das ist keine zusätzliche Auszahlung für eine Gewinnmarge. Es erklärt den Unterschied zwischen einem buchhalterischen Forderungsbestand und einer vereinfachten Finanzierung nur bereits bezahlter Kosten.'
  ],'Für eine Liquiditätsplanung werden tatsächliche Zahlungsströme gebraucht. Die bilanzielle Kapitalbindung und die dafür verwendete Finanzierungsnäherung sind ausdrücklich zu unterscheiden.'),
  'Wenn Einkäufe und Umsatzkosten wegen Aufbau oder Abbau von Vorräten auseinanderfallen, bleibt die erste Formel mit drei Tagesströmen maßgeblich. Bei Ausfällen, Anzahlungen, Steuern oder sonstigen operativen Posten benötigt das Modell zusätzliche Größen.'
 ]),
 S('comparison','6. Unternehmen vergleichen und einen negativen CCC verstehen','a b',[
  T(['Eigenes Modellunternehmen','DIO','DSO','DPO','CCC','Erste Erklärung'],[['Sofortzahlender Einzelhandel','18','2','35','−15','Kunden zahlen vor der durchschnittlichen Lieferantenzahlung.'],['Industriehändler','50','30','40','40','Lager- und Kundenfinanzierung übersteigen den Lieferantenkredit.'],['Spezialanfertigung','100','45','30','115','Lange Produktion und spätere Kundenzahlung binden Mittel.']],'Alle Werte sind hypothetische Tage auf konsistenter Basis. Die Tabelle ist keine Rangliste wirtschaftlicher Qualität.'),
  'Ein negativer CCC bedeutet, dass das Geschäft im Durchschnitt Kundenzahlungen erhält, bevor es die zugehörigen Lieferanten bezahlt. Er kann bei schneller Lagerdrehung und Sofortzahlung ein Vorteil sein. Er beweist jedoch weder hohen Gewinn noch eine jederzeit gesicherte Finanzierung. Löhne, Steuern, Investitionen und Schuldendienst fehlen in dieser Kennzahl.',
  'Gerade bei negativem CCC kann ein Umsatzrückgang Liquidität belasten: Neue Kundeneinzahlungen sinken sofort, während alte Lieferantenrechnungen noch fällig werden. Umgekehrt benötigt schnelles Wachstum bei positivem CCC oft zusätzliches Kapital. Die Richtung des Wachstumseffekts hängt damit auch vom Geschäftsmodell ab.',
  'Ein niedrigerer DIO kann bessere Disposition oder gefährliche Unterbevorratung bedeuten. Ein niedrigerer DSO kann konsequentes Inkasso oder großzügige Rabatte und Forderungsverkäufe widerspiegeln. Ein höherer DPO kann verhandelte Bedingungen oder überfällige Rechnungen anzeigen. Bei einem Vergleich sollen Kennzahl, Ursache, vertragliche Bedingungen und Folgen zusammenpassen.'
 ]),
 S('sensitivity','7. Wachstum, Tagesverbesserung und einmalige Geldfreisetzung','a c',[
  F('\\Delta OWC=c\\,\\Delta DIO+s\\,\\Delta DSO-p\\,\\Delta DPO','Diese Sensitivität hält die Tagesströme konstant. Das Delta bezeichnet jeweils die Veränderung gegenüber dem Ausgangszustand.',[['\\Delta OWC','Veränderung der durchschnittlichen operativen Kapitalbindung.'],['c','Konstante Umsatzkosten je Tag.'],['s','Konstanter Kreditumsatz je Tag.'],['p','Konstante Krediteinkäufe je Tag.'],['\\Delta DIO','Änderung der Vorratstage.'],['\\Delta DSO','Änderung der Forderungstage.'],['\\Delta DPO','Änderung der Lieferantenverbindlichkeitstage.']]),
  'Im Händlerfall mit 200 Euro Tageskosten und 300 Euro Tagesumsatz setzt eine Verringerung des DSO um zehn Tage 3.000 Euro frei. Zehn Tage weniger Vorräte setzen 2.000 Euro frei; zehn zusätzlich vereinbarte Lieferantentage vermindern die Bindung um 2.000 Euro. Die gleiche Tagesänderung hat damit unterschiedliche Geldwirkung.',
  G({id:'days-and-cash',title:'Gleiche Tagesänderung, unterschiedliche Kapitalwirkung',caption:'Eigenes stationäres Händlermodell mit anfänglich 11.000 Euro OWC, 300 Euro Kreditumsatz und je 200 Euro Kosten und Krediteinkäufen pro Tag. Nur die jeweils bezeichnete Tageskomponente wird erhöht.',reading:'Zehn zusätzliche Forderungstage erhöhen die Kapitalbindung auf 14.000 Euro, zehn zusätzliche Vorratstage auf 13.000. Zehn zusätzliche Lieferantentage senken sie auf 9.000. Die dritte Linie fällt wegen der Finanzierung durch den Lieferanten.',plot:{x:[0,20],y:[6000,18000],xTicks:[0,5,10,15,20],yTicks:[6000,9000,12000,15000,18000],xLabel:'Zusätzliche Tage der jeweiligen Komponente',yLabel:'Operative Kapitalbindung in Euro',series:[{name:'DSO steigt; übrige Werte konstant',points:[[0,11000],[20,17000]]},{name:'DIO steigt; übrige Werte konstant',points:[[0,11000],[20,15000]]},{name:'DPO steigt; übrige Werte konstant',points:[[0,11000],[20,7000]]}]}}),
  X('Freigesetztes Kapital ist kein jährlich wiederkehrender Gewinn','Eine dauerhafte Prozessverbesserung senkt den Forderungsbestand bei unverändertem Geschäft einmalig um 3.000 Euro. Die Mittel ersetzen dauerhaft verzinsliche Finanzierung zu angenommenen 8 % jährlich; Steuern, Gebühren und Umsetzungskosten werden hier ausgeblendet.',[
   F('\\Delta CF_0=3000,\\qquad S_I=3000\\cdot0{,}08=240','Die einmalige Geldfreisetzung und die jährliche Zinsersparnis haben verschiedene Zeitdimensionen.',[['\\Delta CF_0','Einmaliger zusätzlicher Zahlungszufluss durch Abbau der Kapitalbindung in Euro.'],['S_I','Jährliche Zinsersparnis unter den angegebenen Annahmen in Euro.']]),
   'Die 3.000 Euro entstehen nicht jedes Jahr erneut. In einer unverschuldeten Projektbewertung wird der operative Freisetzungsbetrag als Cashflow berücksichtigt; eine Finanzierungsersparnis darf nicht zusätzlich ohne Rücksicht auf den verwendeten Diskontierungs- und Finanzierungsansatz doppelt gezählt werden.'
  ],'Zeitpunkt, Bestand und jährlicher Ertrag müssen getrennt bleiben. Umsetzungskosten, Ausfälle und Umsatzverluste können den Vorteil verändern.'),
  'Bei unveränderten Tagen und proportional zehn Prozent höheren Tagesströmen wächst das OWC im Händlerfall von 11.000 auf 12.100 Euro. Die zusätzlichen 1.100 müssen bereitgestellt werden. Overtrading bezeichnet eine Ausweitung des Geschäfts, für die die verfügbaren Finanzierungsressourcen nicht ausreichen; mehr profitable Aufträge können dann eine Zahlungsnot verschärfen.'
 ]),
 S('liquidity-ratios','8. Liquiditätskennzahlen lesen statt Grenzwerte auswendig lernen','b',[
  F('CR=\\frac{CA}{CL},\\qquad QR=\\frac{C+MS+AR}{CL},\\qquad CashR=\\frac{C+MS}{CL}','Mit jeder engeren Definition werden weniger leicht unmittelbar verfügbare Vermögenswerte ausgeschlossen. Bestandteile sind auf Verfügbarkeit und Einbringlichkeit zu prüfen.',[['CR','Current Ratio: kurzfristiges Vermögen relativ zu kurzfristigen Verbindlichkeiten.'],['QR','Quick Ratio in der hier verwendeten Definition.'],['CashR','Cash Ratio in der hier verwendeten Definition.'],['CA','Gesamtes kurzfristiges Vermögen.'],['CL','Gesamte kurzfristige Verbindlichkeiten.'],['C','Zahlungsmittel und Zahlungsmitteläquivalente; Einschränkungen gesondert prüfen.'],['MS','Kurzfristige liquide Wertpapiere, ohne Doppelzählung bereits in C erfasster Beträge.'],['AR','Einbringliche kurzfristige Forderungen aus Lieferungen und Leistungen.']]),
  'Beim Quick Ratio werden Vorräte und Vorauszahlungen typischerweise ausgeschlossen. Die Abkürzung kurzfristiges Vermögen minus Vorräte stimmt nur dann mit der hier verwendeten Definition überein, wenn keine weiteren auszuschließenden Posten vorhanden sind. Ein Current Ratio von zwei kann daher bei hohen Ladenhütern schwächer sein als ein niedrigeres Verhältnis mit sofort verfügbarem Geld.',
  F('DIR=\\frac{C+MS+AR}{E_d}','Die Defensive Interval Ratio übersetzt den Bestand defensiver Mittel in Tage laufender zahlungswirksamer Betriebsausgaben, ohne neue operative Einzahlungen zu unterstellen.',[['DIR','Defensive Interval Ratio: rechnerische Reichweite in Tagen.'],['C','Verfügbare Zahlungsmittel und Zahlungsmitteläquivalente.'],['MS','Zusätzliche liquide kurzfristige Wertpapiere.'],['AR','Einbringliche kurzfristige Kundenforderungen, deren zeitlicher Einzug dennoch zu prüfen ist.'],['E_d','Durchschnittliche tägliche zahlungswirksame Betriebsausgaben; nicht zahlungswirksame Aufwendungen werden ausgeschlossen.']]),
  X('Drei Quoten und eine zeitliche Reichweite','Kurzfristiges Vermögen 200, davon Zahlungsmittel 30, liquide Wertpapiere 20, Kundenforderungen 50, Vorräte 80 und Vorauszahlungen 20. Kurzfristige Verbindlichkeiten 100; laufende zahlungswirksame Betriebsausgaben zwei pro Tag. Alle Geldwerte stehen in derselben Einheit.',[
   T(['Kennzahl','Rechnung','Ergebnis'],[['Current Ratio','200 / 100','2,0'],['Quick Ratio','(30 + 20 + 50) / 100','1,0'],['Cash Ratio','(30 + 20) / 100','0,5'],['Defensive Interval','(30 + 20 + 50) / 2','50 Tage']],'Würde beim Quick Ratio nur der Vorrat abgezogen, entstünde durch die Vorauszahlungen die zu hohe Zahl 1,2.'),
   'Die 50 Tage sind eine rechnerische Reichweite, keine Zahlungsgarantie: Forderungen treffen möglicherweise erst nach der morgen fälligen Ausgabe ein. Investitionen, große Schuldentilgungen und andere nicht einbezogene Auszahlungen benötigen zusätzliche Planung.'
  ],'Quoten verdichten Informationen. Eine belastbare Liquiditätsbeurteilung ergänzt Fälligkeiten, Verwertbarkeit, verfügbare Kredite und Stressannahmen.'),
  'Es gibt keinen branchenübergreifend ausreichenden Mindestwert. Eine planbare Sofortzahlungskette mit verlässlicher Finanzierung kann weniger Bilanzliquidität benötigen als eine saisonale Firma mit konzentrierten Kunden und unsicherem Kreditrahmen.'
 ]),
 S('ratio-traps','9. Eine schönere Quote kann weniger Geld bedeuten','b',[
  X('Kurzfristige Schulden mit vorhandener Kasse tilgen','Ein Unternehmen besitzt kurzfristiges Vermögen von 200, darin Kasse 60, und kurzfristige Verbindlichkeiten von 100. Es zahlt 40 auf diese Verbindlichkeiten. Keine Gebühren, kein Gewinn- oder Verlusteffekt und keine sonstigen Bilanzänderungen.',[
   T(['Größe','Vorher','Nachher'],[['Kurzfristiges Vermögen','200','160'],['Kurzfristige Verbindlichkeiten','100','60'],['Current Ratio','2,0','2,67'],['Nettoumlaufvermögen','100','100'],['Kasse','60','20']],'Die Quote steigt, obwohl vierzig Einheiten weniger Kasse verfügbar sind. Gleichzeitig ist eine Verpflichtung erfüllt; für die Gesamtbeurteilung zählt deren Fälligkeit.'),
   F('\\frac{CA-x}{CL-x}-\\frac{CA}{CL}=\\frac{x(CA-CL)}{CL(CL-x)}','Bei einer Zahlung aus kurzfristigem Vermögen bleibt die Differenz CA minus CL gleich. Die Richtung der Quotenänderung folgt aus dem Vorzeichen dieser Differenz.',[['CA','Kurzfristiges Vermögen vor Zahlung.'],['CL','Kurzfristige Verbindlichkeiten vor Zahlung.'],['x','Gezahlter Betrag; hier größer null und kleiner als CL, mit ausreichend verfügbarer Kasse.']]),
   'Liegt die Ausgangsquote über eins, steigt sie. Unter eins fällt sie; bei genau eins bleibt sie eins. Die Rechnung beurteilt keine untertägige Zahlungsfähigkeit, sondern eine mechanische Quoteneigenschaft.'
  ],'Window Dressing nutzt solche Stichtagseffekte für einen günstigeren Eindruck. Eine Tilgung kann wirtschaftlich sinnvoll sein; problematisch wäre eine Schlussfolgerung allein aus der verbesserten Quote.'),
  'Auch ein neuer kurzfristiger Kredit erhöht zunächst Kasse und kurzfristige Schulden um denselben Betrag. Bei einer Quote über eins sinkt die Quote in Richtung eins, obwohl mehr sofort verfügbares Geld vorhanden ist. Umgekehrt kann ein Verkauf uneinbringlicher Forderungen eine Kennzahl optisch verbessern und zugleich einen Verlust offenlegen. Veränderungen sind deshalb in Geschäftsvorfälle zurückzuübersetzen.'
 ]),
 S('cash-budget','10. Der Liquiditätsplan findet die höchste Finanzierungslücke','b c',[
  F('C_t^{pre}=C_{t-1}+R_t-P_t,\\qquad C_t=C_t^{pre}+B_t-A_t','Zuerst werden Zahlungen ohne neue Finanzierung geplant; danach werden Kreditzugänge und Tilgungen ergänzt.',[['C_t^{pre}','Kassenbestand am Periodenende vor neuer Kreditaufnahme beziehungsweise Tilgung.'],['C_{t-1}','Verfügbarer Kassenbestand zu Periodenbeginn.'],['R_t','Einzahlungen in Periode t.'],['P_t','Auszahlungen in Periode t, hier ohne die gesondert modellierte Kredittilgung.'],['C_t','Kassenbestand nach Finanzierung.'],['B_t','Neue Kreditaufnahme in Periode t.'],['A_t','Tilgung des betrachteten Kredits in Periode t.'],['t','Zeitindex der Planperiode.']]),
  X('Am Ende fehlen 15, zwischendurch werden aber 20 benötigt','Drei Perioden, Anfangskasse 20 und gewünschte Mindestkasse 10. Anfangsschuld null. Einzahlungen 40, 80 und 50; Auszahlungen 70, 60 und 65. Überschüsse über zehn werden bis zur Höhe der bestehenden Schuld zur Tilgung genutzt. Alle Beträge sind Tausend Euro; Zinsen und Gebühren sind zur Darstellung des Ablaufs ausgeblendet.',[
   T(['Periode','Anfangskasse','Einzahlungen','Auszahlungen','Vor Finanzierung','Aufnahme / Tilgung','Endkasse','Endschuld'],[['1','20','40','70','−10','+20','10','20'],['2','10','80','60','30','−20','10','0'],['3','10','50','65','−5','+15','10','15']],'Die maximale benötigte Kreditinanspruchnahme beträgt zwanzig. Die Endschuld von fünfzehn reicht nicht zur Dimensionierung der Linie.'),
   'Stressfall: Zwanzig der ersten Einzahlung kommen erst in Periode zwei. Dann betragen die Einzahlungen 20, 100 und 50. In Periode eins fällt die Kasse vor Finanzierung auf minus 30; zur Mindestkasse zehn ist ein Kredit von 40 nötig. Periode zwei ermöglicht die vollständige Tilgung dieser 40. Die Endschuld bleibt fünfzehn, die Spitzenbeanspruchung verdoppelt sich aber.',
   'Mit einem tatsächlich verfügbaren Kreditlimit von 30 entsteht im Stressfall eine Lücke von zehn gegenüber der gewünschten Mindestkasse. Bei unverändert vollständiger Nutzung der Linie wäre die Endkasse der ersten Periode null. Das ist noch nicht automatisch ein unbezahlter Rechnungsbetrag, zeigt aber den Verlust des festgelegten Puffers.'
  ],'Gleiche Gesamtzahlungen und gleiche Endschuld können einen völlig anderen Liquiditätsbedarf im Zeitverlauf erzeugen. Eine Jahresrechnung verdeckt diese Spitzen.'),
  'Die Perioden müssen kurz genug für die Entscheidung sein. Eine monatliche Planung kann eine große Zahlung am Monatsanfang übersehen, die erst am Monatsende durch Einzahlungen gedeckt wird. Reale Pläne ergänzen Zinsen, Steuern, Mindestguthaben, Währungen, Abruffristen, Sicherheiten und Grenzen der Verfügbarkeit.'
 ]),
 S('sources-drags','11. Verfügbare Quellen, verzögerte Zuflüsse und vorgezogene Abflüsse','b c',[
  'Primäre Liquiditätsquellen sind insbesondere verfügbare Kasse, kurzfristig verwertbare liquide Anlagen, laufende operative Einzahlungen und tatsächlich nutzbare Kreditmöglichkeiten. Sekundäre Maßnahmen wie ein ungewöhnlicher Verkauf langfristiger Vermögenswerte, Neuverhandlung bestehender Verpflichtungen oder Restrukturierung können Zeit und wirtschaftliche Zugeständnisse erfordern. Die Einordnung beschreibt die normale Zugänglichkeit, keine starre Rangfolge in jedem Geschäftsmodell.',
  T(['Beobachtung','Zahlungswirkung','Prüfung'],[['Kunde zahlt später, Ware bleibt liegen','Einzahlung verzögert sich: Drag on Liquidity.','Einbringlichkeit, Alter der Forderung, realistische Verkaufschance.'],['Lieferant verkürzt vereinbarte Fristen','Auszahlung wird vorgezogen: Pull on Liquidity.','Neuer Fälligkeitstermin, alternative Bezugsquellen, Folge für den Betrieb.'],['Bank nennt eine hohe Kreditlinie','Nur der unter Bedingungen tatsächlich abrufbare Teil hilft.','Zusagen, Laufzeit, Covenants, Sicherheiten und bereits erfolgte Nutzung.'],['Kasse liegt in gebundener Form oder an schwer zugänglichem Ort','Bilanzbetrag ist nicht vollständig für die konkrete Zahlung verfügbar.','Rechtliche Beschränkung, Transfermöglichkeit, Währung und Termin.'],['Anlage muss schnell verkauft werden','Zufluss kann einen Abschlag und spätere Ertragseinbußen verursachen.','Dauer, erzielbarer Nettobetrag, betriebliche Notwendigkeit.']],'Drag und Pull beschreiben unterschiedliche Ursachen einer Finanzierungslücke. Mehrere Effekte können in einer Krise gleichzeitig auftreten.'),
  'Eine zugesagte Linie kann bessere Planungssicherheit bieten als eine jederzeit neu zu entscheidende Kreditgewährung. Trotzdem sind vertragliche Bedingungen und tatsächliche Abruffähigkeit relevant. Ein nominelles Limit von 100, bereits beansprucht mit 70, schafft höchstens 30 zusätzlichen Spielraum und möglicherweise weniger, wenn die anrechenbaren Sicherheiten sinken.',
  'Geldanlagen zur Deckung kurzfristiger Zahlungen sollen nach Sicherheit, Verfügbarkeit und passender Fälligkeit beurteilt werden. Zusätzliche Rendite durch Laufzeit, Ausfall-, Währungs- oder Marktrisiko kann gerade im Stress fehlen, wenn das Geld gebraucht wird. Diversifikation der Gegenparteien und Zahlungswege reduziert Konzentration, beseitigt aber nicht jede gemeinsame Störung.'
 ]),
 S('inventory-policy','12. Vorräte steuern: Kosten sparen, Lieferfähigkeit erhalten','c',[
  'Vorräte sichern Produktion und Absatz gegen Lieferzeiten und Nachfrageschwankungen. Sie verursachen zugleich Kapitalbindung, Lageraufwand, Verderb und technologische Veralterung. Eine bloße Minimierung des Bestands kann deshalb Aufträge, Qualität oder Produktion gefährden. Die passende Politik hängt von Beschaffungsdauer, Prognosefehlern und den Kosten eines Fehlbestands ab.',
  X('Eine Lagerreduktion mit und ohne verlorene Lieferfähigkeit','Eine Maßnahme vermindert den dauerhaft benötigten Vorratsbestand um 20.000 Euro. Pro Jahr entfallen 1.200 Euro Lagerkosten und bei angenommenen 8 % weitere 1.600 Euro Finanzierungskosten. Die Umsetzung verursacht in diesem Vergleich keine weiteren Kosten; Steuern sind ausgeblendet.',[
   'Ohne Serviceverlust beträgt die jährliche Ersparnis 2.800 Euro. Zusätzlich werden einmalig 20.000 Euro aus der bisherigen Kapitalbindung frei. Diese beiden Größen dürfen nicht als derselbe jährliche Gewinn bezeichnet werden.',
   'Verursacht die Reduktion jährlich 4.000 Euro verlorenen Deckungsbeitrag durch Lieferausfälle, verschlechtert sich der laufende Beitrag dagegen um 1.200 Euro. Der niedrigere Vorratsbestand und der kürzere CCC beweisen dann keinen besseren Betrieb.'
  ],'Für die Entscheidung zählen vermiedene Kosten und zusätzliche Schäden. Eine Bestandskennzahl bildet diese Abwägung nicht allein ab.'),
  'Just-in-Time verschiebt Beschaffung näher an den Verbrauch und kann die durchschnittliche Bindung senken. Es benötigt verlässliche Abläufe und erhöht bei zu geringem Puffer die Empfindlichkeit gegenüber Störungen. Sicherheitsbestand, mehrere Bezugsquellen oder andere Liefervereinbarungen können begründet sein, auch wenn sie den sichtbar niedrigsten DIO verhindern.',
  'Bei saisonaler Ware ist außerdem der Verkaufszeitpunkt entscheidend. Ein Buchwert von hundert ist keine Zusage, dass hundert rechtzeitig erlöst werden. Wertberichtigung und Notverkauf haben unterschiedliche Wirkungen auf Gewinn und Geld; ein bilanzieller Abschreibungsaufwand selbst zahlt keine Rechnung.'
 ]),
 S('credit-policy','13. Kundenkredit: Mehr Umsatz gegen Kapitalbindung und Ausfall abwägen','c',[
  'Kreditprüfung, individuelle Limits, Zahlungsbedingungen, Rechnungsqualität, Mahnwesen und eine Altersstruktur der Forderungen bilden einen zusammenhängenden Prozess. Eine Altersstrukturanalyse teilt ausstehende Forderungen beispielsweise in noch nicht fällige, bis 30 Tage überfällige und länger überfällige Beträge. Ein stabiler Durchschnitts-DSO kann dabei eine kleine, aber gefährliche Gruppe alter Forderungen verdecken.',
  X('Großzügigere Zahlungsziele sind nicht durch Mehrumsatz allein gerechtfertigt','Eigener Jahresvergleich, 360 Tage und gleichmäßiges Geschäft. Kreditumsatz bisher 360.000 Euro bei DSO 30; neu 396.000 bei DSO 45. Zusätzlicher Deckungsbeitrag beträgt 25 % des Mehrumsatzes, zusätzliche erwartete Ausfälle 3.000 und zusätzliche Verwaltung 1.000 Euro jährlich. Für diese konservative Planungsnäherung wird der volle zusätzliche Forderungsbestand mit 10 % Kapitalkosten belastet. Sonstige Bestände und Lieferantenkredite bleiben gleich.',[
   F('AR_0=\\frac{360000}{360}30=30000,\\qquad AR_1=\\frac{396000}{360}45=49500','Mehr Umsatz und längere Laufzeit wirken gleichzeitig auf den neuen Forderungsbestand.',[['AR_0','Alter durchschnittlicher Forderungsbestand in Euro.'],['AR_1','Neuer durchschnittlicher Forderungsbestand in Euro.']]),
   F('\\Delta V=(396000-360000)0{,}25-3000-1000-(49500-30000)0{,}10=3050','Verglichen wird ein jährlicher zusätzlicher Beitrag nach den ausdrücklich angenommenen Kosten, kein heutiger Unternehmenswert.',[['\\Delta V','Zusätzlicher jährlicher Modellbeitrag in Euro vor Steuern.']]),
   'Die Bindung wächst um 19.500 Euro; die jährliche Kapitalbelastung beträgt 1.950. Zusammen mit Ausfällen und Verwaltung bleiben 3.050. Würde man nur den Mehrumsatz oder nur die DSO-Veränderung verwenden, fehlte ein wesentlicher Teil der Rechnung.',
   'Der volle Forderungsbetrag ist hier eine definierte Opportunitätskostenbasis. Eine detaillierte Zahlungsrechnung kann stattdessen bereits bezahlte variable Kosten, verzögerte bestehende Einzahlungen, feste Kosten und deren genaue Termine unterscheiden. Beide Ansätze dürfen nicht ohne Anpassung vermischt werden.'
  ],'Das Ergebnis hängt an Nachfrage, Marge, Einzug, Ausfällen und Finanzierung. Eine Sensitivität für schlechtere Zahlung und geringeren Mehrabsatz gehört zur realen Entscheidung.'),
  'Strengere Bedingungen können Forderungen und Verluste senken, aber gute Kunden an Wettbewerber verlieren. Ein hoher Anteil bestrittenen Rechnungsvolumens kann zudem ein Leistungs- oder Qualitätsproblem anzeigen, das ein schärferes Mahnschreiben nicht löst. Forderungsmanagement verbindet Vertrieb, Betrieb, Recht und Treasury.'
 ]),
 S('trade-discount','14. Lieferantenkredit und Skonto: kürzerer CCC kann teuer sein','a c',[
  'Die Bedingung 2/10, net 40 bedeutet im folgenden Fall zwei Prozent Abzug bei Zahlung an Tag zehn, sonst den vollen Betrag an Tag vierzig. Wer den Skonto nicht nutzt, hält den rabattierten Betrag weitere dreißig Tage und zahlt dafür den entgangenen Rabatt. Für den Finanzierungssatz ist deshalb der rabattierte Betrag der Nenner.',
  F('r_{per}=\\frac{d}{1-d},\\qquad r_{simple}=\\frac{d}{1-d}\\frac{D}{n-k},\\qquad r_{eff}=\\left(\\frac{1}{1-d}\\right)^{D/(n-k)}-1','Einfache Hochrechnung und effektive Jahresrate sind unterschiedliche Vergleichskonventionen. Die effektive Rate unterstellt wiederholte gleichartige Finanzierung über ein Jahr.',[['r_{per}','Finanzierungskosten relativ zum zusätzlich behaltenen Geld für die verlängerte Zahlungsperiode.'],['d','Skontosatz als Dezimalzahl.'],['D','Vereinbarte Jahrestagesbasis, hier 365.'],['n','Tag der Nettofälligkeit nach dem Ausgangstermin.'],['k','Letzter Tag für Skontonutzung; n muss größer als k sein.'],['r_{simple}','Einfach annualisierter Vergleichssatz.'],['r_{eff}','Effektiver jährlicher Vergleichssatz bei wiederholter Verzinsung.']]),
  X('Bankkredit aufnehmen, um Skonto zu nutzen?','Rechnung 100.000 Euro, zwei Prozent Skonto bis Tag zehn, volle Zahlung an Tag vierzig. Ein tatsächlich verfügbarer Bankkredit kostet für genau die zusätzlichen dreißig Tage 8 % einfachen Jahreszins auf Basis 365; keine Gebühren, Restriktionen oder Steuern.',[
   F('r_{per}=\\frac{2000}{98000}\\approx2{,}0408\\%,\\qquad r_{simple}\\approx24{,}83\\%,\\qquad r_{eff}\\approx27{,}86\\%','Die hohe Jahreszahl entsteht, weil der Rabatt bereits für einen kurzen zusätzlichen Zahlungsaufschub aufgegeben wird.',[['r_{per}','Dreißigtägiger Finanzierungssatz des Skontoverzichts.'],['r_{simple}','Einfach annualisierte Kosten des Skontoverzichts.'],['r_{eff}','Effektive Jahreskosten bei Wiederholung desselben Finanzierungsmusters.']]),
   F('I_B=98000\\cdot0{,}08\\frac{30}{365}\\approx644{,}38,\\qquad S=2000-I_B\\approx1355{,}62','Mit Bankfinanzierung werden am Tag zehn 98.000 bezahlt; am Tag vierzig werden Kredit und Zins von zusammen 98.644,38 zurückgezahlt.',[['I_B','Bankzins für dreißig Tage in Euro.'],['S','Ersparnis gegenüber voller Lieferantenzahlung an Tag vierzig in Euro.']]),
   'Der frühere Ausgleich der Lieferantenrechnung verringert DPO und verlängert damit bei sonst gleichen Komponenten den CCC. Trotzdem ist er im konkreten Fall günstiger, weil die Bankfinanzierung weniger kostet als der aufgegebene Rabatt. Skontoverzicht kann also die kurzfristige Kasse entlasten und zugleich wirtschaftlich teuer sein.'
  ],'Maßnahmen sind nach Zahlungswirkung und vollständigen Kosten zu beurteilen. Ein nicht verfügbarer Bankkredit ist keine nutzbare Alternative, selbst wenn sein theoretischer Satz niedriger wäre.'),
  'Eine eigenmächtige Zahlung nach vertraglicher Fälligkeit ist nochmals anders als die Nutzung des vereinbarten Zahlungsziels. Verzugsfolgen, Lieferstopps und Verlust von Vertrauen gehören dann in die Beurteilung. Der in den offiziellen CFA-Errata korrigierte Vorzeichenzusammenhang bleibt: längere Lieferantenzahlungsdauer verkürzt, nicht verlängert, den CCC.'
 ]),
 S('factoring','15. Factoring: früheres Geld, Gebühren und verbleibendes Risiko','c',[
  'Beim Factoring werden Forderungen an einen Finanzierer übertragen; je nach Vertrag gehören Finanzierung, Einzug und Schutz gegen definierte Ausfälle dazu. Invoice Discounting finanziert ebenfalls gegen Forderungen, während die Betreuung oder Einziehung oft stärker beim Unternehmen bleibt. Die tatsächlichen Vertragsrechte sind wichtiger als die Produktbezeichnung.',
  'Mit Rückgriff bleibt das Unternehmen für bestimmte Nichtzahlungen wirtschaftlich verantwortlich. Ohne Rückgriff übernimmt der Anbieter bestimmte vertraglich definierte Kreditrisiken; Streit über die zugrunde liegende Leistung, Betrug, Garantien oder Ausschlüsse können trotzdem beim Verkäufer bleiben. Ohne Rückgriff bedeutet daher nicht automatisch, dass jedes Risiko verschwunden ist. Auch die bilanzielle Ausbuchung richtet sich nach den geltenden Regeln zur Risiko- und Kontrollübertragung.',
  X('Forderungswert ist nicht sofort verfügbarer Vorschuss','Ein Unternehmen überträgt eine einbringliche Forderung über 100.000 Euro, fällig in sechzig Tagen. Der Factor zahlt jetzt 80 % vor und behält den Rest bis zum vollständigen Einzug zurück. Bei planmäßiger Zahlung werden eine Gebühr von 1 % des Nennbetrags und einfacher Jahreszins von 9 % auf den Vorschuss, Basis 365, vom Restbetrag abgezogen. Keine weiteren Kosten.',[
   F('A=0{,}80\\cdot100000=80000,\\qquad I_F=80000\\cdot0{,}09\\frac{60}{365}\\approx1183{,}56','Finanzierungszins entsteht auf den tatsächlich vorfinanzierten Betrag; die gesonderte Gebühr richtet sich laut Vertrag nach dem Nennbetrag.',[['A','Sofortiger Vorschuss in Euro.'],['I_F','Zins für die sechzigtägige Vorfinanzierung in Euro.']]),
   F('R=20000-1000-1183{,}56=17816{,}44','Der zurückbehaltene Rest wird erst nach Kundenzahlung abzüglich der vereinbarten Kosten ausgezahlt.',[['R','Spätere Restzahlung an das Unternehmen in Euro.']]),
   'Insgesamt erhält das Unternehmen 97.816,44 Euro, davon aber nur 80.000 sofort. Eine morgen fällige Zahlung über 90.000 ist damit ohne weitere Kasse nicht vollständig gedeckt. Die zeitliche Verteilung ist für Liquidität wichtiger als die Addition beider Zahlungstermine.'
  ],'Der Vergleich mit Eigeninkasso oder Bankkredit berücksichtigt Vorschuss, Gebührenbasis, Zins, Einzugsaufwand, Ausfallrisiko und verfügbares Geld an den benötigten Terminen.'),
  'Ein niedrigerer ausgewiesener DSO nach Forderungsverkauf kann Finanzierung und Risikotransfer zeigen, ohne dass Kunden schneller zahlen. Für operative Vergleiche sind dieser Effekt und mögliche Rückgriffspflichten offenzulegen. Ein Angebot mit hoher Vorschussquote ist zudem nicht automatisch billiger; Gebühren und Nebenbedingungen verändern den wirtschaftlichen Preis.'
 ]),
 S('funding-cost','16. Kurzfristige Finanzierungsquellen nach Nettomitteln vergleichen','b c',[
  T(['Quelle','Typischer Nutzen','Zentrale Grenze'],[['Lieferantenkredit','Entsteht im operativen Einkauf und passt oft zum Warenstrom.','Skontoverzicht, Preiswirkung, feste Fälligkeit und Lieferantenbeziehung.'],['Kreditlinie / Kontokorrent','Flexible Ziehung innerhalb tatsächlich verfügbarer Grenzen.','Zins, Bereitstellungsgebühr, Laufzeit, Covenants und Abrufbedingungen.'],['Besicherter kurzfristiger Kredit','Forderungen oder Vorräte können Zugang ermöglichen.','Anrechenbare Sicherheiten, Abschläge und regelmäßige Neubewertung.'],['Commercial Paper','Kurzfristige handelbare Schuldverschreibung für geeignete Emittenten.','Marktzugang und Refinanzierung bei Fälligkeit sind nicht garantiert.'],['Forderungsfinanzierung','Beschleunigt den Zugang zu künftigen Einzahlungen.','Gebühren, Reserve, Rückgriff, Daten- und Vertragsanforderungen.']],'Ein niedriger ausgewiesener Nominalzins beantwortet noch nicht die Frage nach Kosten und Verfügbarkeit.'),
  X('Gebühr und Mindestguthaben erhöhen die tatsächlichen Kosten','Ein Darlehen läuft genau ein Jahr. Nennbetrag 100.000 Euro, Zins 6.000 am Jahresende, einmalige Gebühr 1.000 bei Auszahlung. Gleichzeitig werden 10.000 als unverzinsliches, nicht nutzbares Mindestguthaben gebunden und bei Tilgung wieder freigegeben. Keine weiteren Zahlungen.',[
   F('C_0=100000-1000-10000=89000,\\qquad C_1=100000+6000-10000=96000','Der erste Betrag ist heute frei verfügbar. Der zweite ist der Nettoabfluss am Jahresende nach Rückerhalt des gebundenen Guthabens.',[['C_0','Frei verfügbare Finanzierung bei Beginn in Euro.'],['C_1','Nettozahlung des Kreditnehmers bei Laufzeitende in Euro.']]),
   F('r=\\frac{C_1}{C_0}-1=\\frac{96000}{89000}-1\\approx7{,}87\\%','Bei genau einem Jahr und diesen zwei Nettozahlungszeitpunkten entspricht das Verhältnis der effektiven Jahresbelastung.',[['r','Effektiver Jahresfinanzierungssatz im angegebenen Zwei-Zahlungs-Modell.'],['C_0','Heute frei verfügbare Mittel in Euro.'],['C_1','Nettoabfluss am Jahresende in Euro.']]),
   'Die Summe aus Zins und Gebühr beträgt 7.000. Bezogen auf 89.000 nutzbare Mittel entspricht sie derselben Rate. Ohne die zeitlichen Annahmen wäre diese einfache Kostenquote keine allgemeine Ersatzformel für einen internen Zinsfuß.'
  ],'Nominalbetrag, tatsächlich nutzbarer Zufluss und spätere Zahlungen sind auseinanderzuhalten. Zinsangebote werden auf dieselbe Laufzeit und Kostenbasis gebracht.'),
  'Commercial Paper oder kurzfristige Bankmittel können heute verfügbar sein und bei der nächsten Fälligkeit ausfallen. Eine Firma mit langfristig gebundenen Vermögenswerten trägt dann Refinanzierungsrisiko. Eine höhere langfristige Finanzierungsquote kann den häufigen Erneuerungsbedarf vermindern, aber Kosten und Flexibilität verändern; die Zinskurve muss nicht immer aufwärts geneigt sein.'
 ]),
 S('policy','17. Investitionspolitik und Finanzierungspolitik sind zwei Entscheidungen','c',[
  'Die Investitionspolitik bestimmt, wie viel in kurzfristige Vermögenswerte investiert wird: etwa Pufferkasse, Sicherheitsbestand und gewährte Kundenkredite. Die Finanzierungspolitik bestimmt, wie diese Mittel finanziert werden: langfristig, kurzfristig oder gemischt. Ein großer Vorrat ist deshalb nicht dasselbe wie langfristige Finanzierung; die beiden Entscheidungen können unterschiedlich kombiniert werden.',
  T(['Politik','Kennzeichen','Abwägung'],[['Konservative Investition in Umlaufvermögen','Größere Puffer, ausreichend Vorräte und gegebenenfalls großzügigere Kundenbedingungen.','Mehr Bindung und mögliche Lagerkosten; geringere Störanfälligkeit ist möglich, aber nicht garantiert.'],['Aggressive Investition in Umlaufvermögen','Knappere Kasse, Vorräte und Kreditgewährung.','Weniger Bindung; höhere Gefahr von Engpässen oder verlorenen Kunden.'],['Laufzeitabgestimmte Finanzierung','Dauerbedarf langfristig; vorübergehende Spitzen mit passender kurzfristiger Finanzierung.','Reduziert manche Laufzeitkonflikte, benötigt aber realistische Bedarfsschätzungen.'],['Konservative Finanzierung','Langfristige Mittel decken auch einen Teil temporärer Spitzen.','Weniger häufige Refinanzierung; zeitweise überschüssige Mittel und Kosten möglich.'],['Aggressive Finanzierung','Kurzfristige Mittel finanzieren auch einen Teil des dauerhaften Bedarfs.','Höherer Refinanzierungs- und Zinsanpassungsbedarf; Kosten sind nicht in jeder Zinslage niedriger.']],'Die Adjektive beschreiben die jeweilige Dimension. Sie sind keine vollständige Qualitätsnote.'),
  'Ein dauerhaft benötigter Vorratsbestand kann sich laufend aus anderen einzelnen Waren zusammensetzen. Obwohl jedes Stück rasch verkauft wird, verschwindet der Grundbedarf deshalb nicht. Permanent Working Capital bezeichnet diesen dauerhaften Sockel; Seasonal Working Capital die zusätzlichen saisonalen Spitzen.',
  X('Einzelne Ware ist kurzfristig, der Sockelbedarf bleibt','Eine Firma benötigt ganzjährig 100.000 Euro operatives Kapital und für drei Monate weitere 40.000. Eine abgestimmte Politik finanziert den Sockel langfristig und die Spitze für die passenden Monate. Eine aggressivere Variante finanziert nur 60.000 langfristig.',[
   'In der aggressiveren Variante müssen schon außerhalb der Saison 40.000 kurzfristig finanziert werden, während der Spitze 80.000. Die langfristige Bindung ist dadurch nicht verschwunden; nur ihre Finanzierungsquelle hat eine kürzere Laufzeit.',
   'Eine konservativere Variante mit 140.000 langfristigen Mitteln hält außerhalb der Spitze vorübergehend 40.000 Überschuss. Deren sichere Anlage, Verfügbarkeit und Rendite relativ zu den Finanzierungskosten gehören in den Vergleich.'
  ],'Die Wahl ist eine Abwägung zwischen Ausfallsicherheit der Finanzierung, Kosten und Flexibilität. Eine notwendige Refinanzierung zu einem festen Termin erzeugt ein anderes Risiko als langfristig gesicherte Mittel.')
 ]),
 S('decision','18. Maßnahmen gemeinsam beurteilen und sauber begründen','a b c',[
  X('Ein kurzer CCC ist ein Mittel, kein Selbstzweck','Der stationäre Händler aus Abschnitt fünf bindet zunächst 11.000 Euro bei DIO 50, DSO 30 und DPO 40. Tageskosten und Krediteinkäufe bleiben 200, Tageskreditumsatz 300. Ein zusammenhängendes Programm senkt DIO um fünf, senkt DSO um fünf und verlängert vertraglich DPO um fünf; Volumen, Marge und sonstige Bedingungen bleiben im Basisszenario unverändert.',[
   F('CCC_1=45+25-45=25,\\qquad OWC_1=200\\cdot45+300\\cdot25-200\\cdot45=7500','Die Dauer sinkt um fünfzehn Tage, die Kapitalbindung um 3.500 Euro. Die drei Einzelwirkungen sind 1.000, 1.500 und 1.000 Euro Freisetzung.',[['CCC_1','Neuer Cash Conversion Cycle in Tagen.'],['OWC_1','Neue durchschnittliche operative Kapitalbindung in Euro.']]),
   'Vor einer Empfehlung müssen die Basisszenario-Annahmen geprüft werden: Entstehen Fehlbestände, Kundenverluste, Rabatte, Gebühren oder schlechtere Einkaufspreise? Ein Verlust dieser Art kann die Einsparung vermindern oder übersteigen. Erlaubt der Liefervertrag die fünf zusätzlichen Tage tatsächlich?',
   'Danach kommt der Liquiditätsplan: Wann werden die 3.500 frei, wann entstehen Umsetzungskosten und welche Zahlungsspitze bleibt im Stressfall? Eine dauerhaft geringere Durchschnittsbindung ersetzt keine Kontrolle der größten kurzfristigen Lücke.'
  ],'Eine vollständige Antwort verbindet Richtung, Betrag, Termin und Nebenwirkung. Nur eine Kennzahl zu nennen reicht für die Beurteilung nicht aus.'),
  T(['Prüfschritt','Konkrete Frage'],[['Abgrenzung','Bilanz-NWC, operatives Working Capital oder tatsächliche Finanzierungslücke?'],['Datenbasis','Passende Durchschnittsbestände, Kreditumsätze, Einkäufe und Tagesbasis?'],['Mechanismus','Welche Zahlung oder Bestandsgröße verändert sich warum?'],['Vergleich','Gleiches Geschäftsmodell, gleiche Bilanzierungs- und Finanzierungseffekte?'],['Kosten und Nutzen','Einmaliger Zufluss, laufende Kosten, Ausfälle und Servicewirkung getrennt?'],['Robustheit','Welche Spitze entsteht bei späterem Einzug, Lieferstörung oder eingeschränktem Kredit?']],'Diese Reihenfolge hilft sowohl bei einer CFA-Frage als auch bei einer realen Unternehmensanalyse.'),
  'Die Verbindung zur Abschlussanalyse ist unmittelbar: Eine Zunahme operativer Forderungen oder Vorräte bindet unter sonst gleichen Bedingungen Cashflow; eine Zunahme operativer Verbindlichkeiten liefert Finanzierung. Prognosen übersetzen Umsatzannahmen und Tageskennzahlen in künftige Bestände. Bei der Unternehmensbewertung muss schließlich die Veränderung des operativen Kapitals konsistent im freien Cashflow erscheinen.'
 ])
],related:[
 {unit:'ratios',section:'activity',label:'Umschlagshäufigkeit, Tageskennzahlen und Vergleichsgrenzen'},
 {unit:'ratios',section:'liquidity',label:'Liquiditätsquoten in der umfassenden Kennzahlenanalyse'},
 {unit:'forecasting',section:'working-capital',label:'Aus Umsatzannahmen und Tagen künftige Bestände planen'},
 {unit:'cashflow-preparation',section:'indirect',label:'Operative Bestandsveränderungen in der Cashflow-Rechnung'},
 {unit:'governance',section:'creditor-controls',label:'Warum Kreditbedingungen und Covenants Verfügbarkeit begrenzen'}
],sources:[
 {title:'CFA Institute: Level I 2027, Working Capital and Liquidity, Lernziele',url:'https://www.cfainstitute.org/sites/default/files/2027levelitopicoutline_online.pdf#page=10'},
 {title:'CFA Institute: Working Capital and Liquidity, Einführung und Lernziele',url:'https://www.cfainstitute.org/insights/professional-learning/refresher-readings/2026/working-capital-and-liquidity'},
 {title:'ACCA: Working Capital Management, Grundlagen und Vergleichsgrenzen',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f9/technical-articles/wcm.html'},
 {title:'ACCA: Accounts Receivable Management, Kreditbedingungen und Einzug',url:'https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f9/technical-articles/arm.html'},
 {title:'ACCA: Cashflow Finance und Invoice Factoring, Vorschuss und Rückgriff',url:'https://www.accaglobal.com/gb/en/business-finance/types-finance/cashflow-invoice.html'},
 {title:'CFA Institute: Curriculum-Errata 2026, Korrektur zur Richtung des CCC bei längerer Lieferantenzahlung',url:'https://www.cfainstitute.org/sites/default/files/docs/programs/cfa-program/candidate-resources/2026-cfa-li-curriculum-errata-notice.pdf#page=29'}
],review:{status:'draft',date:'2026-09-27',note:'Eigene Zeitachsen-, Tagesbasis-, Liquiditäts-, Finanzierungs- und Politikfälle mit ausdrücklichen Modellgrenzen. 2027-Lernzielzuordnung; fachlicher Gesamtaudit und vollständige Kursfreigabe bleiben offen.'}};
