const R=require('./schema.cjs');
module.exports=[
R('Kapitalmarkterwartungen sind konsistente Annahmen, keine Punktgewissheiten',`Langfristige Erwartungen verbinden Ausgangsbewertung, laufenden Ertrag und wirtschaftliches Wachstum. Bei Aktien kann eine grobe Zerlegung Dividenden, Gewinnwachstum und Bewertungsänderung unterscheiden; bei Anleihen sind Anfangsrendite, Ausfälle und Wiederanlage relevant. Historische Durchschnittsrenditen sind ein Datenpunkt, aber keine automatisch unveränderte Zukunftserwartung.

Die Annahmen verschiedener Anlageklassen müssen zusammenpassen. Nominale Renditen hängen mit Inflation zusammen, Währungsrenditen mit dem Referenzwährungsraum und Risikoprämien mit dem betrachteten Horizont. Statt nur eine Zahl zu verwenden, helfen Szenarien, Bandbreiten und Sensitivitäten. Je stärker eine Allokation von einer kleinen Prognosedifferenz abhängt, desto wichtiger ist eine robuste Entscheidung.`,
'Ein Aktienmarkt bietet Dividendenrendite 3 %, erwartetes langfristiges nominales Gewinnwachstum 4 % und einen über zehn Jahre angenommenen Bewertungsrückgang von KGV 20 auf 18.',[
'Jährlicher Bewertungseffekt=(18/20)^(1/10)−1≈−1,048 %.|Die gesamte Multipleänderung wird geometrisch auf zehn Jahre verteilt.',
'Grobe additive Renditeerwartung≈3 %+4 %−1,048 %=5,952 %.|Die Zerlegung zeigt die Quellen; sie ist keine exakte Zahlungsstromrechnung.',
'Bei unverändertem Multiple ergäbe dieselbe Näherung 7 %.|Die Ausgangsbewertung kann den langfristigen Ertrag deutlich beeinflussen, obwohl die Gewinnwachstumsannahme gleich bleibt.'
],'Grundlage für strategische Allokation und langfristige Finanzplanung.','Gewinnwachstum, Ausschüttung und Bewertung sind nicht unabhängig. Prognoseintervalle werden häufig unterschätzt; Regimewechsel begrenzen historische Modelle.','Aktienbewertung erklärt Bewertungsniveaus; Szenarioanalyse untersucht alternative gemeinsame Entwicklungen.'),
R('Restriktionen verändern sowohl die Lösung als auch die Bedeutung von Optimalität',`Ein unbeschränkter Optimierer kann hohe Leverage, Short-Positionen oder illiquide Gewichte vorschlagen. Reale Portfolios müssen dagegen Liquidität, Konzentrationsgrenzen, Steuern, regulatorische Vorgaben und Umsetzbarkeit erfüllen. Das beste Portfolio innerhalb dieser Grenzen ist ein anderes Optimierungsproblem als das beste theoretisch denkbare Portfolio.

Neben Kapitalgewichten sind Risikobeiträge wichtig. Ein kleiner Anteil einer sehr volatilen Anlage kann einen großen Teil des Gesamtrisikos verursachen. Robuste Methoden begrenzen die Empfindlichkeit gegenüber Schätzfehlern, etwa durch Bandbreiten oder konservative Erwartungen. Eine zusätzliche Nebenbedingung kann die erwartete Modellrendite senken und dennoch die tatsächliche Entscheidung verbessern, weil sie Modellunsicherheit oder reale Pflichten abbildet.`,
'Ein Anleger besitzt 10 Mio. €. Mindestens 2 Mio. € müssen liquide bleiben; illiquide Anlagen dürfen höchstens 30 % ausmachen. Ein Modell schlägt 15 % liquide, 40 % illiquide und 45 % weitere Anlagen vor.',[
'Liquiditätsminimum=2/10=20 %; Modell unterschreitet es um 5 Prozentpunkte.|Ein nominell attraktives Ergebnis erfüllt die tatsächliche Zahlungsvorgabe nicht.',
'Illiquides Gewicht muss von 40 % auf höchstens 30 % sinken.|Die vorgeschlagene Bindung überschreitet das erlaubte Kapitalbudget um 1 Mio. €.',
'Eine zulässige Ausgangslösung wäre 20 % liquide, 30 % illiquide, 50 % weitere Anlagen.|Sie ist noch nicht automatisch optimal; innerhalb der zulässigen Menge müssen Rendite, Risiko und Korrelation neu beurteilt werden.'
],'Verwendet für institutionelle Allokation, private Mandate und robuste Portfoliokonstruktion.','Kapitalgrenzen allein erfassen nicht jede Risikokonzentration. Zu viele unreflektierte Restriktionen können ein Modell scheinbar präzise, aber wirtschaftlich unverständlich machen.','IPS liefert die Nebenbedingungen; Risikobudgetierung betrachtet die tatsächlichen Schwankungsbeiträge.'),
R('Im ALM ist die Verpflichtung Teil des Risikomaßstabs',`Asset-Liability-Management beurteilt Vermögen relativ zu den zu finanzierenden Verpflichtungen. Ein Vermögenswert kann für sich schwanken und trotzdem das Risiko des Überschusses senken, wenn Verpflichtungen ähnlich reagieren. Umgekehrt kann ein stabiles Nominalvermögen für inflationsabhängige Ausgaben unzureichend sein.

Zentrale Größen sind Überschuss, Deckungsgrad und ihre Sensitivitäten. Cashflow Matching ordnet Zahlungen zeitlich zu; Duration Matching gleicht zunächst lokale Zinsreaktionen ab. Zielbasierte private Anlage verwendet eine verwandte Logik für einzelne Ausgabenwünsche mit unterschiedlichen Prioritäten. Die Schwierigkeit liegt in unsicheren Verpflichtungen, optionalen Zahlungen und Basisrisiken zwischen Vermögen und Diskontierung.`,
'Vermögen 105 Mio. € mit Duration 5; Verpflichtungsbarwert 100 Mio. € mit Duration 8. Ein paralleler Zinsrückgang von 1 Prozentpunkt wird linear approximiert.',[
'Ausgangsüberschuss=105−100=5 Mio. €; Deckungsgrad=105 %.|Beide Größen setzen Vermögen und Verpflichtung in Beziehung.',
'Vermögensanstieg≈105×5×0,01=5,25; Verpflichtungsanstieg≈100×8×0,01=8 Mio. €.|Die längere Verpflichtungsduration reagiert stärker auf sinkende Zinsen.',
'Neuer Überschuss≈110,25−108=2,25 Mio. €; Deckungsgrad≈102,08 %.|Obwohl das Vermögen steigt, verschlechtert sich die Finanzierungssituation.'
],'Eingesetzt bei Pensionen, Versicherungen, Banken und langfristigen privaten Zielen.','Diskontierungsregeln und tatsächliche Zahlungsrisiken müssen unterschieden werden. Duration ist lokal und erfasst Inflation, Langlebigkeit oder nichtparallele Kurvenänderungen nicht vollständig.','Immunisierung vertieft den Sensitivitätsabgleich; Zeitwert bewertet künftige Verpflichtungen.'),
R('Der passende Anlageprozess hängt vom wirtschaftlichen Eigentümer ab',`Private Haushalte verbinden Anlagevermögen mit Einkommen, Ausgaben, Steuern und persönlichen Zielen. Institutionen besitzen andere Verpflichtungen und Governance: Pensionspläne finanzieren Leistungen, Stiftungen Ausgaben, Versicherer Schadenansprüche. Derselbe liquide Marktbaustein kann daher in verschiedenen Mandaten eine andere Funktion haben.

Die Allokation muss den tatsächlichen Entscheidungsspielraum berücksichtigen. Ein sehr langer institutioneller Horizont erlaubt nicht unbegrenzt Illiquidität, wenn kurzfristige Ausschüttungen oder Sicherheiten erforderlich sind. Bei Privatanlegern können Unternehmenseigentum und Arbeitslohn bereits stark mit Aktienmarktrisiko korrelieren. Der Vergleich beginnt deshalb mit Verpflichtungen, Einnahmen und Governance, bevor Produkte ausgewählt werden.`,
'Eine Stiftung besitzt 100 Mio. € und plant 4 Mio. € jährliche Ausgaben. Ein Haushalt besitzt 1 Mio. €, benötigt 40.000 € jährlich, erhält aber zusätzlich 25.000 € verlässliches Nettoeinkommen.',[
'Stiftungsentnahmequote=4/100=4 %.|Die gesamte Ausgabe muss hier aus dem Vermögen beziehungsweise dessen Erträgen kommen.',
'Haushaltsentnahme aus Portfolio=40.000−25.000=15.000 €; Quote=1,5 %.|Externe Einnahmen verändern die Anforderung an das Finanzvermögen.',
'Inflation, Ausfall der Einnahmen und Sonderausgaben jeweils ergänzen.|Ähnliche Bruttoausgabenquoten hätten die unterschiedliche Finanzierungslage verdeckt.'
],'Hilft bei Mandatsgestaltung und Übertragung von Portfoliokonzepten auf konkrete Anleger.','Institutionelle Vorgaben und private Lebensverhältnisse unterscheiden sich stark. Verlässlichkeit externer Einnahmen darf nicht ungeprüft vorausgesetzt werden.','IPS strukturiert die Anforderungen; Lebenszyklusplanung berücksichtigt Humankapital und Entnahmen.'),
R('Assetklassen sind Bausteine mit teilweise überlappenden Risiken',`Aktien, Anleihen und alternative Anlagen sind nützliche Kategorien, aber keine vollständig getrennten wirtschaftlichen Welten. Unternehmensanleihen und Aktien desselben Emittenten reagieren auf gemeinsame Geschäftsrisiken; Private Equity besitzt trotz anderer Bewertungspraxis erhebliches Unternehmens- und Finanzierungsrisiko.

Integration bedeutet deshalb, Renditequellen, Faktorexponierungen, Liquidität und Verpflichtungsbeiträge über alle Bausteine hinweg zu prüfen. Eine neue Anlage kann trotz eigener Kategorie wenig zusätzliche Diversifikation bringen. Umgekehrt kann ein Derivat eine konkrete Risikolücke schließen, ohne als neue kapitalintensive Assetklasse aufzutreten. Der Gesamtprozess verbindet Allokation mit Umsetzung und laufender Überwachung.`,
'Ein Portfolio hält 50 % börsennotierte Aktien, 20 % Private Equity und 30 % Anleihen. In einem vereinfachten Stress verlieren Aktien 30 %, Private Equity 35 %, Anleihen gewinnen 2 %.',[
'Aktienbeitrag=0,5×(−30 %)=−15 Prozentpunkte.|Die große liquide Aktienposition dominiert bereits einen Teil des Verlusts.',
'Private-Equity-Beitrag=0,2×(−35 %)=−7; Anleihebeitrag=0,3×2 %=+0,6 Prozentpunkte.|Die alternative Kategorie trägt im Szenario ähnliches Unternehmensrisiko statt gegenläufigen Schutz.',
'Gesamtrendite=−21,4 %.|Die Etiketten „Aktien, Alternativen, Anleihen“ allein hätten die Konzentration im wirtschaftlichen Wachstum nicht beschrieben.'
],'Verwendet für Gesamtportfolioanalyse und Prüfung neuer Anlagestrategien.','Szenarioergebnisse hängen von gemeinsamen Annahmen ab. Modellierte Korrelationen privater Anlagen können wegen Bewertungsverzögerung zu niedrig sein.','Faktormodelle untersuchen Überschneidungen; Stressanalyse prüft das Gesamtverhalten unter ungünstigen Bedingungen.'),
R('Währungsrisiko gehört zur Rendite in der Zielwährung',`Die Rendite einer ausländischen Anlage entsteht aus lokaler Vermögensrendite und Wechselkursveränderung. Beide Effekte werden miteinander multipliziert, weil sich die Währung auf den veränderten Endwert auswirkt. Eine Absicherung verändert dieses Währungsrisiko, verursacht jedoch Forward-Punkte, Handelskosten und möglichen Sicherheitenbedarf.

Die geeignete Hedgequote hängt von Anlageklasse, Verpflichtungswährung, Horizont und gemeinsamer Bewegung von Währung und Basisanlage ab. Vollständige nominale Absicherung kann bei schwankendem Assetwert schnell über- oder unterdimensioniert sein. Strategische Währungsregeln und taktische Abweichungen sollten getrennt bewertet werden.`,
'Ein Euroanleger investiert 100.000 USD bei 0,90 EUR je USD. Die Anlage gewinnt lokal 10 %, der Dollar fällt auf 0,81 EUR. Vereinfachend sichert ein Forward den ursprünglichen Dollarbetrag zu 0,90; Forward-Punkte werden hier auf null gesetzt.',[
'Anfangswert=90.000 €; ungesicherter Endwert=110.000×0,81=89.100 €.|Die lokale Wertsteigerung wird vom Währungsrückgang überkompensiert.',
'Forward-Gewinn=(0,90−0,81)×100.000=9.000 €.|Gesichert ist nur das anfängliche Nominal, nicht der zusätzliche Anlagegewinn.',
'Gesicherter Gesamtendwert=98.100 €; Rendite=9 %.|Die restliche Währungswirkung auf den Gewinn von 10.000 USD erklärt die Abweichung von der lokalen Rendite von 10 %.'
],'Verwendet für internationale Portfolios und Verpflichtungen in einer festgelegten Währung.','Forward-Punkte sind im Allgemeinen nicht null. Rolltermine, Cashflows und unterschiedliche Exposureentwicklung erzeugen Restabweichungen.','Wechselkursrechnung liefert die multiplikative Rendite; Forwards erklären Preis und laufenden Hedgewert.'),
R('Ein Overlay verändert gezielt das Risiko eines bestehenden Portfolios',`Ein Overlay legt eine zusätzliche Derivateposition über vorhandene Anlagen. Damit können Beta, Duration, Währung oder Verlustprofil verändert werden, ohne sämtliche zugrunde liegenden Positionen zu handeln. Dies erleichtert Übergänge und die Trennung von Managerauswahl und Gesamtportfoliorisiko.

Wirtschaftliche Exponierung, Kapitalbedarf und Governance müssen gemeinsam geplant werden. Ein Futures-Overlay kann mit wenig anfänglichem Geld viel Marktrisiko erzeugen. Ein Optionsoverlay besitzt zusätzlich zeit- und volatilitätsabhängige Sensitivitäten. Klare Zuständigkeiten verhindern, dass Basismanager und Overlaymanager gegeneinander handeln oder Risiken doppelt absichern.`,
'Ein Portfolio von 20 Mio. € soll seine Modified Duration von 3 auf 5 erhöhen. Ein Long-Zinsfuture liefert modelliert einen positiven DV01 von 80 € je Kontrakt; Basisrisiken werden zunächst ignoriert.',[
'Zusätzlicher benötigter DV01=20.000.000×(5−3)×0,0001=4.000 € je Basispunkt.|Die Zieländerung wird zunächst in Geldsensitivität übersetzt.',
'Kontraktzahl=4.000/80=50 Long-Kontrakte.|Eine Long-Anleihefuturesposition gewinnt bei fallenden Renditen und erhöht die gewünschte Duration.',
'Bei einem Zinsanstieg von 10 Basispunkten verliert das Overlay näherungsweise 40.000 €.|Zusätzlich zur strategischen Risikowirkung ist dieser mögliche Marginabfluss einzuplanen.'
],'Hilft bei Transition Management, Cash Equitization und zentraler Risikosteuerung.','DV01 des Futures hängt unter anderem vom lieferbaren Bond und Konversionsfaktor ab. Große Kurvenbewegungen verändern die Absicherung.','Duration und Derivatehedging liefern die Dimensionierung; Liquiditätsplanung berücksichtigt Sicherheiten.'),
R('Liquidität ist ein gemeinsames Problem von Anlagen und Verpflichtungen',`Liquiditätsrisiko entsteht, wenn fällige Zahlungen nicht rechtzeitig ohne unvertretbare Verluste finanziert werden können. Es unterscheidet sich von langfristiger Solvenz. Ein Portfolio kann einen positiven Nettovermögenswert besitzen und dennoch bei einem Margin Call oder Kapitalabruf zahlungsunfähig werden.

Konzentration verschärft dieses Risiko, wenn viele Positionen dieselbe Verkaufsquelle oder Finanzierung nutzen. Eine Liquiditätsleiter ordnet verfügbare Mittel und mögliche Zahlungen nach Zeithorizonten. Haircuts, Rückgabefristen und Stressabschläge gehören dazu. Bei Extremrisiken ist zudem zu prüfen, ob Sicherheitenanforderungen gerade dann steigen, wenn die liquidierbaren Anlagen fallen.`,
'Ein Fonds besitzt 5 Mio. € Geld und 10 Mio. € innerhalb einer Woche veräußerbare Anleihen. Im Wochenstress sind 8 Mio. € Rückgaben und 4 Mio. € Margin Calls fällig; Anleiheverkäufe erleiden 10 % Abschlag.',[
'Gesamter Liquiditätsbedarf=8+4=12 Mio. €.|Mehrere Zahlungsquellen müssen gemeinsam betrachtet werden.',
'Nach Einsatz des Geldbestands fehlen 7 Mio. €.|Bilanzvermögen ersetzt keine zeitgerechte Zahlung.',
'Erforderlicher Verkauf zum Vorstresswert=7/0,90≈7,778 Mio. €.|Der Stressabschlag erhöht den zu verkaufenden Bestand; die angenommene Wochenliquidität reicht hier aus, wäre bei kürzerer Frist aber gesondert zu prüfen.'
],'Verwendet für Rücknahmeplanung, Sicherheitenbudgets und Krisenreserven.','Stressliquidität ist unsicher und korreliert oft mit Verlusten. Kreditlinien können Bedingungen enthalten oder selbst gefährdet sein.','Repo und Derivate erzeugen Sicherheitenbedarf; Reverse Stress Testing untersucht die Grenze der Zahlungsfähigkeit.'),
R('Attribution erklärt, welche Entscheidungen zur aktiven Rendite beitrugen',`Performance Attribution zerlegt die Differenz zwischen Portfolio und Benchmark. Bei einer sektorbasierten Brinson-Zerlegung beschreibt Allokation die Wirkung anderer Gewichte, Selektion die Wirkung anderer Renditen innerhalb der Segmente und Interaktion deren Kombination. Die gewählte Formelkonvention muss offengelegt werden.

Eine rechnerische Zuordnung ist noch keine vollständige Kausalerklärung oder Fähigkeitsmessung. Sektorrenditen können auf versteckten Faktoren beruhen, und eine einzige Periode kann Zufall sein. Mehrperiodige Attribution benötigt zudem eine konsistente Verknüpfung; aktive Renditen lassen sich nicht in jeder Darstellung einfach über die Zeit addieren.`,
'Benchmark: 50 % Aktien mit 10 %, 50 % Anleihen mit 2 %, Gesamtrendite 6 %. Portfolio: 60 % Aktien mit 12 %, 40 % Anleihen mit 1 %. Verwendet wird Brinson-Fachler mit separater Interaktion.',[
'Portfoliorendite=0,6×12 %+0,4×1 %=7,6 %; aktiv=1,6 Prozentpunkte.|Die Gesamtzahl ist die Kontrollsumme der Zerlegung.',
'Allokation=0,1×(10−6)+(−0,1)×(2−6)=0,8 Prozentpunkte.|Die Gewichtungsabweichung wird mit der jeweiligen Benchmarksegmentrendite relativ zur Gesamtbenchmark verbunden.',
'Selektion=0,5×(12−10)+0,5×(1−2)=0,5 Prozentpunkte.|Hier werden Renditedifferenzen mit Benchmarkgewichten gemessen.',
'Interaktion=0,1×2+(−0,1)×(−1)=0,3; Summe=0,8+0,5+0,3=1,6.|Der zusätzliche Effekt entsteht, weil gerade die übergewichtete Aktienseite besser abschneidet.'
],'Genutzt für Reporting, Verantwortungsteilung und Überprüfung von Investmententscheidungen.','Andere Brinson-Konventionen ordnen Komponenten anders zu. Währungen, Derivate, Cashflows und mehrperiodige Verkettung benötigen Erweiterungen.','Asset Allocation erklärt Gewichtsentscheidungen; Appraisal prüft, ob beobachtete Beiträge belastbare Fähigkeit zeigen.'),
R('Ein guter Track Record muss Risiko, Zufall und Auswahl überstehen',`Performance Appraisal beurteilt, wie aussagekräftig vergangene Ergebnisse für Qualität oder Fähigkeit sind. Dazu werden passende Benchmarks, Faktorbereinigung, Gebühren, Datenqualität und statistische Unsicherheit geprüft. Ein hoher Durchschnitt kann aus wenigen Extrembeobachtungen oder günstigen Marktrisiken stammen.

Viele gleichzeitig getestete Manager oder Strategien erzeugen schon zufällig beeindruckende Gewinner. Deshalb sind vorab formulierte Hypothesen, wirtschaftliche Erklärungen und Ergebnisse außerhalb der Auswahlperiode wertvoll. Qualitative Prozessprüfung ergänzt Statistik: Ein nicht reproduzierbarer Zufallstreffer und ein nachvollziehbarer, disziplinierter Prozess sind trotz gleichem Rückblick nicht gleich zu beurteilen.`,
'Eine Strategie weist über 60 Monate eine durchschnittliche aktive Monatsrendite von 0,20 % und eine Standardabweichung aktiver Monatsrenditen von 2 % auf. Beobachtungen werden für diese Grundrechnung als unabhängig angenommen.',[
'Standardfehler des Mittelwerts=2 %/√60≈0,2582 %.|Unsicherheit des Durchschnitts ist kleiner als die Schwankung einzelner Monate, aber nicht null.',
't-Wert=0,20/0,2582≈0,775.|Die positive durchschnittliche Rendite ist relativ zu ihrer Schätzunsicherheit klein.',
'Grobe 95-%-Spanne mit Normalnäherung: 0,20 %±1,96×0,2582 %, also etwa −0,306 % bis +0,706 % monatlich.|Null liegt darin; bei kleinem Sample ist eine t-Verteilung passender, zeitliche Abhängigkeit verlangt robuste Verfahren.'
],'Verwendet für Managerbewertung, Strategievalidierung und Interpretation von Alpha.','Nicht signifikant bedeutet nicht bewiesen wirkungslos. Umgekehrt garantiert Signifikanz weder Investierbarkeit noch Fortbestand nach Kosten.','Hypothesentests erklären Unsicherheit; Alpha ist modellabhängig; Backtesting behandelt Mehrfachtests und Datenlecks.'),
R('Managerauswahl verbindet Fähigkeit mit organisatorischer Verlässlichkeit',`Die Auswahl beginnt mit der Rolle im Gesamtportfolio: Benchmark, Risikobudget, Liquidität und gewünschte Exponierung. Danach werden Menschen, Prozess, Portfolio und Leistung geprüft. Ein erfolgreicher Manager kann unpassend sein, wenn sein Stil bereits stark vertreten ist oder seine Kapazität erschöpft ist.

Monitoring sucht Veränderungen gegenüber der ursprünglichen Auswahlthese: Schlüsselpersonen, Eigentümerwechsel, Stilabweichung, Kontrollen, Kosten oder unerklärte Positionen. Ein Mandatswechsel sollte erwarteten Nutzen gegen Transaktionskosten, Steuern und Übergangsrisiken abwägen. Kurzfristige Unterperformance allein ist kein vollständiger Beweis für Prozessversagen; dauerhaft veränderte Voraussetzungen können dagegen auch bei guter jüngster Rendite einen Wechsel rechtfertigen.`,
'Ein 50-Mio.-€-Mandat könnte zu einem neuen Manager wechseln. Erwarteter jährlicher Nettoverbesserungsbeitrag 0,30 %, einmalige Übergangskosten 0,80 %. Beide Schätzungen sind unsicher.',[
'Erwarteter Jahresnutzen=50 Mio.×0,003=150.000 €.|Die Prognose muss nach laufenden Gebühren formuliert sein.',
'Einmalige Kosten=50 Mio.×0,008=400.000 €.|Handel, Marktimpact und gegebenenfalls Steuern mindern den Wechselnutzen sofort.',
'Einfache Amortisationszeit=400.000/150.000≈2,67 Jahre.|Dies ist nur eine erste Schwelle ohne Diskontierung oder Prognoserisiko; die erwartete Verbesserung muss ausreichend lange bestehen.'
],'Relevant für institutionelle Mandate, Fondsselektion und Governance von Outsourcing.','Erwartetes Alpha ist besonders unsicher. Gute Prozesse können schlechte Perioden haben; qualitative Bewertung kann selbst voreingenommen sein.','Investmentthese strukturiert Auswahlgründe; Implementation Shortfall misst die Kosten des Übergangs.'),
R('GIPS zielt auf faire und vergleichbare Darstellung von Anlageergebnissen',`Die Global Investment Performance Standards regeln die Berechnung und Präsentation von Performance unter definierten Voraussetzungen. Eine zentrale Idee ist, passende tatsächlich verwaltete Portfolios in Composites zusammenzufassen, statt nur erfolgreiche Einzelmandate zu zeigen. Die Definition der Firma, Diskretion, Gebührenstatus und Strategiezuordnung sind dabei wesentlich.

Für Composite-Zeitrenditen werden Portfoliorenditen grundsätzlich vermögensgewichtet oder mit der zulässigen Aggregatmethode kombiniert. Die Standards enthalten zusätzliche Regeln und besondere Bedingungen, unter anderem für geldgewichtete Renditen in bestimmten Situationen. GIPS-Konformität ist eine umfassende Aussage zur Firma und den anwendbaren Anforderungen, keine Auszeichnung für eine einzelne attraktive Rendite und keine Garantie zukünftigen Erfolgs.`,
'Ein vereinfachtes Composite umfasst zwei während der gesamten Periode bestehende passende Portfolios ohne externe Cashflows: A startet mit 80 Mio. € und erzielt 5 %, B mit 20 Mio. € und erzielt 10 %.',[
'Anfangsgewichte=80 % und 20 %.|Die Composite-Rechnung berücksichtigt die Größe des verwalteten Kapitals.',
'Vermögensgewichtete Rendite=0,8×5 %+0,2×10 %=6 %.|Dies entspricht hier dem Gesamtgewinn 4+2=6 auf Anfangsvermögen 100.',
'Der einfache Durchschnitt von 7,5 % wäre für diese gewählte Aggregation falsch.|Er würde dem kleinen Portfolio denselben Einfluss geben wie dem viermal größeren; vollständige GIPS-Berichte verlangen wesentlich mehr als diese Einzelrechnung.'
],'Genutzt für institutionelle Performancepräsentation und vergleichbare Managerprüfung.','Die konkrete Konformitätsprüfung erfordert die aktuellen Standards mit allen anwendbaren Bestimmungen. Das Beispiel erklärt nur einen Berechnungsbaustein.','Ethik fordert faire Darstellung; TWR trennt externe Mittelbewegungen von der zeitlichen Anlageleistung.')
];
