const R=require('./schema.cjs');
module.exports=[
R('Der Anlagezugang verändert das Risiko derselben Vermögensart',`Alternative Investments umfassen sehr unterschiedliche wirtschaftliche Risiken. Eine direkt gehaltene Immobilie, ein börsennotierter REIT und ein geschlossener Immobilienfonds können auf ähnliche Gebäude zugreifen, unterscheiden sich aber in Liquidität, Verschuldung, Gebühren und Kontrolle. Die Hülle ist deshalb Teil der Anlageanalyse.

Geschlossene Fonds sammeln häufig Kapitalzusagen ein, rufen Geld später ab und schütten es nach Verkäufen zurück. Eine Zusage ist bereits eine Verpflichtung, obwohl noch kein Geld investiert ist. Offene Strukturen bieten möglicherweise Rückgaben, können aber Kündigungsfristen, Gates oder Aussetzungen vorsehen. Langfristig gebundene Anlagen benötigen einen Liquiditätsplan für den gesamten Anleger, nicht nur eine erwartete Rendite.`,
'Ein Anleger sagt einem Fonds 1 Mio. € zu. Im ersten Jahr werden 30 %, im zweiten weitere 40 % der ursprünglichen Zusage abgerufen. Es gibt noch keine Ausschüttungen.',[
'Erster Abruf=300.000 €; offene Zusage danach 700.000 €.|Noch nicht abgerufenes Geld bleibt eine mögliche zukünftige Zahlungspflicht.',
'Zweiter Abruf=400.000 €; kumuliert eingezahlt 700.000 €.|Die Prozentangabe bezieht sich hier auf die ursprüngliche Zusage, nicht auf den Rest.',
'Verbleibende Abrufverpflichtung=300.000 €.|Ein Portfolio mit nur 100.000 € sofort verfügbarer Liquidität braucht zusätzliche verlässliche Finanzierungsmöglichkeiten, selbst wenn seine Fondsanteile wertvoll sind.'
],'Relevant für Auswahl von Fondsstrukturen und Liquiditätsplanung institutioneller oder privater Portfolios.','Verträge können Abruffristen, Recycling und Verlängerungen erlauben. Gemeldeter NAV ist nicht zwingend kurzfristig realisierbarer Verkaufserlös.','Private-Market-Verträge erklären Kapitalabrufe; ALM gleicht Verpflichtungen mit tatsächlich verfügbaren Mitteln ab.'),
R('Gebühren bestimmen, wie Bruttowertschöpfung beim Anleger ankommt',`Management Fees vergüten die Verwaltung meist auf einer vertraglich definierten Kapitalbasis. Carried Interest beteiligt den Manager an bestimmten Gewinnen. Hurdle, Catch-up, High-Water-Mark, Reihenfolge der Ausschüttungen und Clawback bestimmen, wann und wie viel gezahlt wird. Gleiche Überschriften wie „2 und 20“ können wirtschaftlich unterschiedliche Verträge beschreiben.

Für Anleger zählt die Nettorendite nach allen relevanten Kosten. Bei unregelmäßigen Kapitalflüssen ergänzt IRR die Kapitalmultiplikatoren. Ein hoher IRR kann durch frühe kleine Rückzahlungen entstehen, während der absolute Gewinn gering bleibt. Deshalb werden Zeitpunkt, Kapitalbindung, realisierte Ausschüttungen und verbleibende Bewertungen gemeinsam betrachtet.`,
'Ein vereinfachter Einjahresfonds startet mit 100. Bruttogewinn 15. Management Fee 2 auf Anfangskapital; Performance Fee 20 % des nach Management Fee verbleibenden Gewinns, ohne Hurdle.',[
'Gewinn nach Management Fee=15−2=13.|Die vereinbarte Reihenfolge legt die Basis der Erfolgsgebühr fest.',
'Performance Fee=13×20 %=2,6.|Eine Berechnung auf den Bruttogewinn würde einen anderen Vertrag unterstellen.',
'Nettoendwert=100+15−2−2,6=110,4; Nettorendite=10,4 %.|Von 15 % Bruttorendite verbleiben hier 10,4 % für den Anleger.'
],'Benötigt für Fondsvergleich, Vertragsprüfung und Performancebeurteilung.','Das Beispiel bildet keinen universellen Fondsvertrag ab. Mehrjährige Waterfalls, Kosten auf Fondsebene und Rückforderungsregeln können das Ergebnis stark ändern.','IRR und TWR erklären unterschiedliche Renditefragen; Ethik untersucht Transparenz und Interessenkonflikte.'),
R('Selten beobachtete Preise können Risiko verbergen',`Private Anlagen werden häufig durch Gutachten oder Modelle bewertet. Wenn neue Informationen schrittweise in Bewertungen eingehen, wirken berichtete Renditen geglättet: Schwankung und zeitgleiche Korrelation mit liquiden Märkten erscheinen zu niedrig. Die wirtschaftliche Unsicherheit verschwindet dadurch nicht.

Datenbanken können außerdem Survivorship Bias enthalten, wenn gescheiterte Fonds fehlen, oder Backfill Bias, wenn erfolgreiche Vorgeschichten nachträglich aufgenommen werden. Due Diligence prüft deshalb Datenentstehung, Bewertungsregeln, Verwahrung, Kontrollen, Personal und tatsächliche Transaktionen. Eine überzeugende Renditekurve allein sagt wenig darüber, ob sie vollständig, investierbar und unabhängig verifiziert ist.`,
'Fünf Fonds erzielen in einem Jahr 12 %, 10 %, 8 %, 5 % und −35 %. Der letzte Fonds schließt und fehlt anschließend in einer vereinfachten Datenbank.',[
'Vollständiger gleichgewichteter Durchschnitt=(12+10+8+5−35)/5=0 %.|Alle anfänglich möglichen Anlagen gehören zur Beurteilung des Ausgangsuniversums.',
'Durchschnitt der Überlebenden=(12+10+8+5)/4=8,75 %.|Das Entfernen des Fehlschlags lässt die beobachtete Historie attraktiver erscheinen.',
'Verzerrung=8,75 Prozentpunkte.|Diese Differenz ist kein Anlageerfolg, sondern entsteht allein aus unvollständiger Datenauswahl.'
],'Wichtig bei Fondsselektion, Schätzung von Korrelationen und Vergleich alternativer mit liquiden Anlagen.','Auch bereinigte Daten bleiben oft klein, heterogen und zeitverzögert. Mathematisches Entglätten erfordert zusätzliche Modellannahmen.','Statistische Stichprobenfehler und Backtesting erklären ähnliche Probleme; Managerprüfung ergänzt Zahlen um Prozesskontrollen.'),
R('Private Equity verbindet Unternehmensentwicklung mit Finanzierungsstruktur',`Buyouts erwerben häufig etablierte Unternehmen, während Venture Capital junge Firmen mit unsicherem Geschäftsmodell finanziert. Wert entsteht aus operativer Verbesserung, Wachstum, Kapitalstruktur und dem späteren Verkaufspreis. Verschuldung kann Eigenkapitalrenditen erhöhen, erhöht aber ebenso Insolvenz- und Refinanzierungsrisiko.

Bei Venture Capital sind einzelne Ausfälle und sehr große Gewinner typisch für die Modellierung. Beteiligungsrechte, Folgefinanzierungen und Verwässerung bestimmen den tatsächlichen Eigentümerertrag. Bei Buyouts muss die Renditequelle getrennt werden: Ein gestiegener Exit-Multiple ist etwas anderes als verbesserter Cashflow oder getilgte Schulden. Ohne diese Trennung kann ein günstiges Marktumfeld mit operativer Leistung verwechselt werden.`,
'Ein Unternehmen wird für Enterprise Value 100 gekauft, finanziert mit Schulden 60 und Eigenkapital 40. Nach fünf Jahren beträgt der Verkaufswert 120 und die Restschuld 40.',[
'Eigenkapital beim Exit=120−40=80.|Der Eigentümer erhält den Unternehmenswert nach Ablösung der Restschuld.',
'Kapitalmultiplikator=80/40=2; annualisierte Rendite=2^(1/5)−1≈14,87 %.|Ohne Zwischenzahlungen wird der Endwert über fünf Jahre auf eine Jahresrate umgerechnet.',
'Wertzuwachs des Eigenkapitals 40 setzt sich aus 20 höherem Unternehmenswert und 20 Schuldenabbau zusammen.|Die Renditequellen sind wirtschaftlich verschieden und sollten getrennt überprüft werden.'
],'Verwendet für Buyoutmodelle, Investitionsentscheidungen und Erklärung von Fondsrenditen.','Gebühren, Zwischenzahlungen, Verwässerung und Transaktionskosten fehlen in dieser Grundrechnung. Exitwerte sind unsicher und Finanzierungsbedingungen können sich verschlechtern.','FCFF liefert operative Mittel zur Entschuldung; Kapitalstruktur erklärt die Hebelwirkung.'),
R('Private Credit verlangt besonders genaue Vertrags- und Verlustanalyse',`Private Credit stellt Unternehmen Kredite außerhalb breit gehandelter öffentlicher Märkte bereit. Der Mehrertrag kann Vergütung für Kreditrisiko, geringe Handelbarkeit, komplexe Struktur oder Origination sein. Ein hoher laufender Zinssatz sagt wenig über die Nettorendite aus, wenn spätere Verluste oder Kosten erheblich sind.

Distressed Debt konzentriert sich auf angeschlagene Schuldner und mögliche Restrukturierungen. Hier bestimmen Sicherheiten, Rang, Unternehmenswert, Verhandlungsrechte und Verfahrenskosten die Recovery. PIK-Zinsen werden dem Kapital zugeschlagen und erhöhen berichteten Ertrag, ohne sofortige Liquidität zu liefern. Die Analyse muss deshalb zwischen aufgelaufenem Anspruch und realistisch einbringlichem Geld unterscheiden.`,
'Ein Kredit von 100 trägt 8 % PIK-Zins jährlich. Zwei Jahre erfolgt keine Barzahlung. Danach lassen sich im Restrukturierungsszenario nur 90 zurückgewinnen.',[
'Vertraglicher Anspruch nach zwei Jahren=100×1,08²=116,64.|Die nicht gezahlten Zinsen erhöhen die Forderung und werden selbst verzinst.',
'Recovery relativ zum Anspruch=90/116,64≈77,16 %.|Der Abschlag auf den zuletzt ausgewiesenen Anspruch beträgt rund 22,84 %.',
'Anlegerergebnis gegenüber dem eingesetzten Geld: 90/100−1=−10 % kumuliert.|Trotz zweier Jahre ausgewiesener PIK-Erträge hat der Anleger wirtschaftlich Geld verloren.'
],'Genutzt für Direct Lending, Mezzanine und Restrukturierungsinvestitionen.','Verträge, Gerichtsbarkeit und Sicherheitenbewertung sind entscheidend. Bewertete Forderungen können bis zum Ereignis scheinbar stabil bleiben.','Kreditanalyse trennt Zahlungsfähigkeit von Bilanzgewinn; Waterfalls erklären die Rangfolge im Verlustfall.'),
R('Immobilienwert hängt an nachhaltig erzielbarem Nettoertrag',`Der Net Operating Income zieht von Immobilienerträgen die laufenden objektbezogenen Betriebskosten ab, gewöhnlich vor Finanzierung und bestimmten Investitionsausgaben. Bei stabilen Verhältnissen kann eine Kapitalisierungsrate den nachhaltigen NOI in einen Wert übersetzen. Die Cap Rate ist keine vollständige Eigenkapitalrendite und darf nicht ohne Prüfung von Wachstum und Investitionsbedarf interpretiert werden.

Eine DCF-Bewertung modelliert Mieten, Leerstand, Kosten, Modernisierung und Verkauf einzeln. REITs bieten einen handelbaren Zugang, tragen aber zusätzlich Unternehmens-, Finanzierungs- und Börsenpreisrisiken. Mietverträge können Inflationsschutz bieten, dessen Wirkung jedoch von Indexierung, Zahlungsfähigkeit der Mieter und zeitlichen Verzögerungen abhängt.`,
'Jährliche potenzielle Mieten 1 Mio. €, erwarteter Leerstand 10 %, Betriebskosten 0,3 Mio. €. Nachhaltige Cap Rate 5 %.',[
'Effektive Miete=1×0,90=0,9 Mio. €; NOI=0,9−0,3=0,6 Mio. €.|Nicht jede theoretisch vermietbare Fläche liefert tatsächlich Geld.',
'Geschätzter Objektwert=0,6/0,05=12 Mio. €.|Die direkte Kapitalisierung unterstellt einen zur Rate passenden nachhaltigen Ertrag.',
'Steigt die Cap Rate auf 6 %, fällt der Wert auf 0,6/0,06=10 Mio. €.|Bei gleichem NOI sinkt der Wert um 16,67 %; bessere laufende Mieten garantieren bei steigenden Renditeforderungen keinen Kursgewinn.'
],'Verwendet für Objektbewertung, Kreditbeleihung und Vergleich von Immobilienmärkten.','Aufgeschobene Instandhaltung, Mietanreize und struktureller Leerstand können NOI verzerren. Cap Rates sind objekt- und marktabhängig.','Gordon-Modell erklärt die Ertragskapitalisierung; Leverage verstärkt Wertänderungen im Immobilien-Eigenkapital.'),
R('Real Assets kombinieren langfristige Nachfrage mit konkreten Betriebsrisiken',`Infrastruktur umfasst etwa Energie-, Transport- oder Versorgungsanlagen. Brownfield-Projekte betreiben vorhandene Anlagen; Greenfield-Projekte tragen zusätzlich Bau- und Anlaufrisiken. Regulierte oder vertragliche Erlöse können planbarer sein, sind aber von Regeln, Gegenparteien und tatsächlicher Verfügbarkeit abhängig.

Land- und Forstwirtschaft erzeugen reale Güter und biologische Wachstumsprozesse. Wetter, Krankheiten, Wasserverfügbarkeit, Rohstoffpreise und Erntezeitpunkt beeinflussen Cashflows. Inflationsschutz ist deshalb kein automatisches Merkmal jedes Real Assets. Entscheidend ist, ob Erlöse schneller oder langsamer als Kosten reagieren und welche Investitionen zum Erhalt der Ertragskraft erforderlich sind.`,
'Eine Infrastrukturgesellschaft erzielt 10 Mio. € Jahreserlös und hat 6 Mio. € Betriebskosten. Der Vertrag erlaubt eine Erlösanpassung um 3 %, Kosten steigen jedoch um 5 %.',[
'Neuer Erlös=10×1,03=10,3 Mio. €.|Die vertragliche Indexierung erhöht die Einnahmen.',
'Neue Kosten=6×1,05=6,3 Mio. €; operativer Überschuss=4,0 Mio. €.|Der nominale Überschuss bleibt trotz höherer Erlöse unverändert.',
'Bei allgemeiner Inflation von 3 % sinkt seine reale Kaufkraft auf 4/1,03≈3,883 Mio. € in heutigen Preisen.|Indexierte Umsätze allein garantieren keinen vollständigen Inflationsschutz des Eigentümers.'
],'Relevant für langfristige Portfolioanlagen, Projektfinanzierung und Inflationsanalyse.','Regulatorische Änderungen, politische Eingriffe und klimatische Risiken sind projektspezifisch. Lange Laufzeiten erhöhen die Bedeutung kleiner Annahmefehler.','ALM prüft passende langfristige Zahlungen; Szenarioanalyse verbindet Preis-, Kosten- und Verfügbarkeitsrisiken.'),
R('Rohstoff-Futures-Rendite ist mehr als die Veränderung des Kassapreises',`Wer Rohstoffexposure über Futures hält, besitzt in der Regel keinen dauerhaft unveränderten Kontrakt. Auslaufende Positionen werden durch spätere Fälligkeiten ersetzt. Gesamtrendite eines besicherten Futures-Investments hängt von Kontraktpreisbewegungen, Rollvorgängen, Verzinsung der Sicherheiten und Kosten ab.

Contango bezeichnet eine aufwärts gerichtete, Backwardation eine abwärts gerichtete Terminkurve. Bei ansonsten unveränderter Kassapreisumgebung kann ein teurerer Futures-Kontrakt mit nahender Fälligkeit an Wert verlieren. Der Roll ist selbst kein sofortiger Verlust in Höhe des Preisabstands, weil Futures nicht wie voll bezahlte Aktien getauscht werden. Entscheidend sind die anschließenden Kontraktbewegungen und die gewählte Renditedefinition.`,
'Der Kassapreis liegt bei 100. Ein neu gekaufter Future notiert bei 105 und konvergiert bis Fälligkeit auf einen unveränderten Kassapreis von 100. Kontraktgröße eine Einheit.',[
'Futures-Ergebnis=100−105=−5 je Einheit.|Der Verlust entsteht durch die Preisbewegung des gehaltenen Vertrags.',
'Bei einer expliziten anfänglichen Kapitalbasis von 100 entspricht dies −5 %.|Die Prozentzahl benötigt eine definierte Anlage- oder Sicherheitenbasis.',
'Verdienen diese 100 währenddessen 2 Zinseinnahmen, ergibt sich vereinfachte Gesamtrendite (−5+2)/100=−3 %.|Ein unveränderter Kassapreis bedeutet bei Futures-Umsetzung also nicht automatisch null Gesamtrendite.'
],'Wichtig für Rohstoffindizes, Inflationsstrategien und Vergleich physischer mit terminbasierter Anlage.','Kurven verändern sich; rollabhängige Renditezerlegungen sind konventionsabhängig. Lagerkosten und Convenience Yield variieren stark.','Cost of Carry erklärt die Kurve; Performance Attribution trennt Marktbewegung, Umsetzung und Sicherheitenzins.'),
R('Hedgefondsstrategien müssen nach ihren tatsächlichen Risikotreibern beurteilt werden',`Long-Short Equity, Global Macro, Event Driven und Relative Value beschreiben verschiedene Handelsansätze. Das Wort Hedgefonds garantiert keine abgesicherte oder geringe Verlustgefahr. Eine marktneutrale Nettoposition kann hohe Bruttoexponierung, Finanzierungssensitivität und Konzentration enthalten.

Relative-Value-Strategien versuchen, Preisunterschiede verwandter Instrumente auszunutzen. Wenn sich die Differenz vorübergehend ausweitet, können Margin Calls und Rückgaben eine vorzeitige Auflösung erzwingen. Regelmäßig kleine Gewinne können zudem aus dem Verkauf seltener großer Risiken stammen. Die Analyse untersucht daher neben Durchschnittsrendite und Volatilität auch Leverage, Schiefe, Liquidität und Stressverhalten.`,
'Ein Fonds mit Eigenkapital 100 hält Long-Positionen von 150 und Short-Positionen von 150. Die Long-Seite fällt um 4 %, die geshorteten Werte steigen um 3 %.',[
'Nettoexposure=150−150=0; Bruttoexposure=150+150=300.|Marktneutralität im Nominal bedeutet nicht, dass keine Positionen oder Risiken bestehen.',
'Long-Verlust=150×4 %=6; Short-Verlust=150×3 %=4,5.|Beide Seiten können gleichzeitig gegen den Fonds laufen.',
'Gesamtverlust=10,5 beziehungsweise 10,5 % des Eigenkapitals.|Finanzierungskosten und Sicherheitenforderungen können den Druck zusätzlich erhöhen.'
],'Genutzt für Strategieauswahl, Faktorzerlegung und operative Due Diligence.','Nettoexposure erfasst unterschiedliche Betas oder nichtlineare Risiken nicht. Historische Ruhephasen können versteckte Extremrisiken verdecken.','Faktormodelle messen gemeinsame Exponierungen; Stressanalyse untersucht Liquidations- und Finanzierungsrisiko.'),
R('Tokenisierung verändert die technische Darstellung, nicht automatisch den Anspruch',`Ein digitaler Vermögenswert kann ein natives Netzwerkasset, ein vertraglicher Anspruch oder die digitale Darstellung eines traditionellen Wertpapiers sein. Zuerst ist zu klären, was der Besitzer wirtschaftlich und rechtlich tatsächlich erhält. Ein Token auf ein Gebäude ist nicht allein durch seine Technik automatisch durchsetzbares Eigentum am Gebäude.

Bewertung und Risiken folgen dem konkreten Nutzen, den Zahlungsrechten, der Angebotsregel und den Abhängigkeiten des Systems. Verwahrung, Schlüsselverlust, Smart-Contract-Fehler, Governance und Schnittstellen zu externen Daten können zusätzliche Risiken erzeugen. Bei Stablecoins sind Reserven, Rückgaberechte und Liquidität entscheidend; ein angestrebter stabiler Preis ist keine Garantie.`,
'Ein vereinfachter Token verspricht einen Anspruch von 1 € auf Reserven. Es sind 100 Mio. Token ausgegeben; Reserven bestehen aus 70 Mio. € Geld und Wertpapieren mit Buchwert 30 Mio. €.',[
'Buchmäßige Deckung=(70+30)/100=100 %.|Diese Kennzahl benutzt zunächst die ausgewiesenen Werte.',
'Fallen die Wertpapiere bei sofortiger Veräußerung auf 27 Mio. €, sind nur 97 Mio. € realisierbar.|Markt- und Liquiditätsrisiko können eine Lücke trotz vorheriger Vollabdeckung erzeugen.',
'Realisierbare Deckung=97 %; zusätzlich Rückgaberechte und Gläubigerrang prüfen.|Eine technische Transaktion auf einer Blockchain beseitigt die wirtschaftliche Deckungslücke nicht.'
],'Hilft bei Analyse tokenisierter Anlagen, Verwahrung und digitaler Zahlungsinstrumente.','Technische und rechtliche Strukturen ändern sich schnell; projektspezifische Dokumente sind unverzichtbar. Das Beispiel ist keine Aussage über einen bestimmten Anbieter.','Bilanzanalyse prüft Reserven; Liquiditätsrisiko und Gegenparteirisiko gelten auch für digital dargestellte Ansprüche.'),
R('Diversifikation muss in schlechten Zuständen und nach Kosten bestehen',`Alternative Anlagen können zusätzliche Renditetreiber erschließen, etwa illiquide Unternehmensentwicklung, spezielle Risikoprämien oder reale Nutzungsentgelte. Ihr Nutzen hängt davon ab, wie diese Risiken mit dem bestehenden Portfolio zusammenwirken. Eine geringe historische Korrelation genügt nicht, wenn sie auf geglätteten Bewertungen oder kurzen Beobachtungszeiträumen beruht.

Nachhaltigkeitsrisiken wirken über konkrete Cashflows und Diskontsätze: physische Schäden, Anpassungsinvestitionen, Regulierung, Nachfrage oder Rechtsstreitigkeiten. Sie sind nicht bei jeder Anlage gleich und sollten nicht nur durch ein Etikett ersetzt werden. Ein Portfoliobeitrag wird deshalb mit Kosten, Liquidität, Bewertungsunsicherheit und Stressverlusten gemeinsam beurteilt.`,
'Ein Portfolio besteht zu 80 % aus liquiden Anlagen und zu 20 % aus einer Alternative. Im Stress verlieren die liquiden Anlagen 20 %, die Alternative wirtschaftlich 30 %, obwohl ihre letzte Bewertung unverändert ist.',[
'Wirtschaftlicher Portfoliostress=0,8×(−20 %)+0,2×(−30 %)=−22 %.|Der tatsächliche gemeinsame Zustand ist für Verlustfähigkeit relevant.',
'Mit unverändert gemeldetem Alternativenwert erschiene nur −16 %.|Zeitverzögerte Bewertungen unterschätzen den aktuellen Verlust um 6 Prozentpunkte.',
'Liquiditätsbedarf auf den realistischen Stresswert beziehen und offene Kapitalabrufe ergänzen.|Ein scheinbar stabiler NAV kann nicht zuverlässig als sofort verfügbare Verlustreserve dienen.'
],'Genutzt für strategische Allokation, Nachhaltigkeitsprüfung und Stressbudgets.','Zusammenhänge ändern sich in Krisen. Szenarien sind keine präzisen Wahrscheinlichkeitsprognosen und müssen mehrere mögliche Mechanismen abdecken.','Korrelation und Risikobudget erklären Portfoliobeiträge; Due Diligence prüft Daten und ökonomische Substanz.')
];
