const R=require('./schema.cjs');
module.exports=[
R('Eine Anleihe ist ein Bündel vertraglicher Zahlungsbedingungen',`Nennwert, Kupon, Fälligkeit, Währung und Rang bestimmen zunächst, welche Zahlungen versprochen sind. Der Marktpreis ist der heutige Wert dieser unsicheren Versprechen. Ein hoher Kupon bedeutet deshalb weder automatisch hohe Rendite noch geringe Gefahr: Der Kaufpreis und die tatsächliche Zahlungsfähigkeit gehören zur Analyse.

Covenants begrenzen bestimmte Handlungen des Emittenten oder verlangen Kennzahlen und Informationen. Sie sollen verhindern, dass nach Kreditvergabe Risiko zulasten der Gläubiger verschoben wird. Besicherung und Rang wirken besonders im Ausfall; Covenants können schon vorher Eingriffsrechte auslösen. Entscheidend sind Definitionen, Ausnahmen und Rechtsdurchsetzbarkeit, nicht nur das Vorhandensein eines Schutzversprechens.`,
'Eine Anleihe hat Nennwert 1.000 €, jährlichen Kupon 4 % und drei Jahre Restlaufzeit. Der Emittent darf laut vereinfachter Klausel Nettoschulden/EBITDA von 3 nicht überschreiten.',[
'Jährlicher Kupon=1.000×4 %=40 €; letzte Zahlung=1.040 €.|Zins und Tilgung sind unterschiedliche Bestandteile des Zahlungsplans.',
'Nettoschulden 240, EBITDA 100: Verhältnis 2,4.|Unter diesen Definitionen ist die vertragliche Schwelle eingehalten.',
'Sinkt EBITDA auf 70, steigt das Verhältnis auf 3,43.|Auch ohne neue Schulden kann ein Covenant verletzt werden; Folgen richten sich nach dem Vertrag und sind nicht automatisch gleichbedeutend mit Zahlungsausfall.'
],'Ausgangspunkt für Cashflowmodell, Kreditprüfung und Vertragsvergleich.','Kuponpläne können variabel, bedingt oder optionsabhängig sein. Rechtlicher Schutz ist nur so wirksam wie seine konkrete Ausgestaltung.','Kreditanalyse untersucht die Fähigkeit zur Vertragserfüllung; Optionsbewertung behandelt Kündigungs- und Umtauschrechte.'),
R('Emittent und Laufzeit bestimmen unterschiedliche Risikoquellen',`Staatspapiere hängen von fiskalischer Tragfähigkeit, Währungsregime und institutionellen Bedingungen ab. Schulden in eigener Währung unterscheiden sich von Fremdwährungsschulden, sind aber nicht frei von Inflations-, Kurs- oder Restrukturierungsrisiko. Unternehmensanleihen tragen zusätzlich Geschäfts-, Finanzierungs- und Insolvenzrisiken.

Geldmarktpapiere sind kurzfristige Instrumente zur Liquiditätsanlage und Finanzierung. Ihre geringe Laufzeit reduziert gewöhnlich die Zinssensitivität, beseitigt jedoch Ausfall- und Wiederanlagerisiko nicht. Renditen werden teils als Diskontsätze auf Nennwert oder mit verschiedenen Tageskonventionen notiert. Vor einem Vergleich müssen Zahlungsbasis, Laufzeit und Annualisierung vereinheitlicht werden.`,
'Ein 90-Tage-Papier zahlt 10.000 € zurück und kostet 9.900 €. Für den Vergleich wird ein 360-Tage-Jahr verwendet.',[
'Ertrag=10.000−9.900=100 €.|Der Ertrag entsteht aus dem Abschlag statt aus einer separaten Kuponzahlung.',
'Haltedauerrendite=100/9.900=1,0101 %.|Die tatsächliche Investition ist der richtige Nenner für die Anlegerrendite.',
'Einfach annualisiert: 1,0101 %×360/90=4,0404 %; Diskontquote=100/10.000×4=4 %.|Der unterschiedliche Nenner erklärt verschiedene Notierungen desselben Geschäfts.'
],'Hilft beim Liquiditätsmanagement und Vergleich von Bills, Commercial Paper und längerfristigen Schuldtiteln.','Steuern, Tageskonventionen, Handelbarkeit und Kreditqualität verhindern einen unbereinigten Renditevergleich.','Zeitwert liefert die Umrechnung; Staatsfinanzen und Wechselkursanalyse erklären Emittentenrisiken.'),
R('Clean Price und Dirty Price trennen Notierung und Zahlung',`Zwischen Kuponterminen entsteht ein Anspruch auf den nächsten Kupon. Beim Verkauf erhält der Verkäufer deshalb gewöhnlich aufgelaufene Stückzinsen. Der Clean Price blendet diesen zeitabhängigen Anteil aus; der Dirty Price ist der volle Abrechnungspreis vor weiteren Gebühren.

Diese Trennung erleichtert die Beobachtung von Marktpreisänderungen. Ohne sie würde der Preis allein durch den täglich anwachsenden Kuponanspruch steigen und am Zahlungstermin fallen. Die Höhe der Stückzinsen hängt von der vereinbarten Tageszählung und besonderen Marktregeln ab. Bei amortisierenden Anleihen sinkt außerdem der ausstehende Nennwert, sodass Zinsen und Tilgung auf einen veränderten Kapitalbetrag bezogen werden.`,
'Eine Anleihe mit Nennwert 1.000 € zahlt halbjährlich 30 €. Genau 60 von angenommenen 180 Tagen der Kuponperiode sind vergangen; Clean-Notierung 101 %.',[
'Clean Price=1.000×1,01=1.010 €.|Die Prozentnotierung bezieht sich auf den Nennwert.',
'Stückzinsen=30×60/180=10 €.|Der Verkäufer wird für den seit dem letzten Kupontermin entstandenen Anteil entschädigt.',
'Dirty Price=1.010+10=1.020 €.|Dieser Betrag ist im vereinfachten Beispiel beim Kauf zu zahlen und bildet den Ausgangspunkt einer korrekten Renditerechnung.'
],'Wichtig bei Orderabrechnung, Portfoliobewertung und Renditeberechnung.','Ex-Kupon-Regeln und tatsächliche Day-Count-Konventionen können vom vereinfachten Bruch abweichen.','Cashflow-Zeitachsen verhindern doppelt gezählte Kupons; Gesamtrendite berücksichtigt Preis und laufende Zahlungen.'),
R('Liquidität ist die Möglichkeit zu handeln, ohne den Preis stark zu verändern',`Im Primärmarkt beschafft der Emittent Kapital durch neue Wertpapiere. Im Sekundärmarkt wechseln bereits bestehende Ansprüche den Eigentümer. Anleihemärkte sind häufig weniger transparent und stärker dealerbasiert als zentrale Aktienorderbücher. Seltene Transaktionen erschweren die Feststellung eines unmittelbar ausführbaren Marktpreises.

Liquidität zeigt sich in Spread, handelbarer Größe, Preiswirkung und Erholung nach einer Order. Ein letzter Kurs oder Modellpreis ist keine Garantie für sofortige Veräußerung. Unter Stress können viele Anleger gleichzeitig verkaufen, während Händler ihre Bestände reduzieren. Ein Portfolio mit langfristig zahlungsfähigen Emittenten kann deshalb kurzfristig erhebliche Liquidationsverluste erleiden.`,
'Eine Anleihe wird mit Bid 98 und Ask 100 je 100 Nennwert quotiert. Ein Anleger kauft 100.000 Nennwert und verkauft unmittelbar bei unveränderten Quotes.',[
'Kaufzahlung=100.000×100/100=100.000.|Ein Käufer nimmt das Verkaufsangebot des Händlers an.',
'Verkaufserlös=100.000×98/100=98.000.|Der sofortige Verkauf erfolgt zur niedrigeren Geldseite.',
'Rundlaufverlust=2.000 beziehungsweise 2 % des Kaufbetrags.|Der Spread verursacht Kosten auch ohne Veränderung von Zinsen oder Kreditqualität.'
],'Relevant für Fondsliquidität, Bewertung illiquider Positionen und Auswahl handelbarer Emissionen.','Quotes gelten möglicherweise nur für kleine Größen. Stückzinsen, Gebühren und Marktbewegungen kommen zum Beispiel hinzu.','Implementation Shortfall erfasst tatsächliche Handelskosten; Stressanalyse untersucht erzwungene Verkäufe.'),
R('Rendite bis Fälligkeit ist ein interner Zinsfuß',`Der Preis einer festverzinslichen Anleihe ist die Summe diskontierter Kupons und Tilgung. Die Yield to Maturity ist der einheitliche Diskontsatz, der diesen Barwert dem beobachteten Preis gleichsetzt. Steigt der geforderte Satz bei festen Zahlungen, fällt der Preis: Zukünftiges Geld wird stärker abgezinst.

YTM fasst viele Zahlungen in eine Kennzahl zusammen. Sie ist keine sichere tatsächliche Gesamtrendite. Die Realisierung einer entsprechenden zusammengesetzten Rendite setzt unter anderem Vertragserfüllung und passende Wiederanlage der Kupons voraus. Bei schiefer Zinskurve werden die einzelnen Cashflows für eine arbitragefreie Bewertung besser mit laufzeitspezifischen Spot Rates bewertet.`,
'Zweijährige Anleihe, Nennwert 100, jährlicher Kupon 5. Geforderte jährliche Rendite 6 %.',[
'Barwert Kupon Jahr 1=5/1,06=4,717.|Die erste Zahlung wird eine Periode diskontiert.',
'Barwert Jahr 2=(100+5)/1,06²=93,450; Preis=98,167.|Tilgung und letzter Kupon fallen zusammen an.',
'Bei Rendite 5 % beträgt der Preis genau 100.|Kuponsatz und Rendite stimmen dann überein; bei höherer Rendite muss der Einstiegspreis unter Nennwert sinken.'
],'Genutzt zur Preisermittlung, Quotierung und ersten Renditevergleich.','Kündigungsrechte, Ausfälle und Wiederanlagebedingungen können die tatsächliche Rendite verändern. Verschiedene Verzinsungskonventionen müssen vereinheitlicht werden.','IRR erklärt die mathematische Lösung; Spotkurven zeigen die differenzierte Bewertung jedes Zahlungszeitpunkts.'),
R('Spot, Par und Forward beschreiben dieselbe Kurve auf verschiedene Weise',`Ein Spot Rate diskontiert eine einzelne Zahlung von einer bestimmten Fälligkeit auf heute. Ein Par-Satz ist dagegen der Kuponsatz, bei dem eine bestimmte Kuponanleihe zum Nennwert bewertet würde. Er kombiniert mehrere Diskontfaktoren und ist deshalb nicht einfach der Spot Rate der Endfälligkeit.

Ein Forward Rate ist ein heute aus Preisen ableitbarer Satz für einen zukünftigen Zeitraum. Ohne Arbitrage muss eine direkte zweijährige Anlage denselben Endwert liefern wie eine einjährige Anlage mit heute festgelegter Anschlussanlage. Der resultierende Forward ist ein Marktpreis für diese Verknüpfung, keine unverzerrte Zusage über den später tatsächlich beobachteten Kurzfristzins.`,
'Einjährige Spot Rate 3 %, zweijährige Spot Rate 4 %, jeweils jährliche Verzinsung.',[
'Diskontfaktoren: d₁=1/1,03=0,970874; d₂=1/1,04²=0,924556.|Jede Fälligkeit erhält ihren eigenen heutigen Wert je Geldeinheit.',
'Forward für Jahr 2: 1,04²/1,03−1=5,0097 %.|Die Verzinsungsfaktoren müssen das gleiche zweijährige Endvermögen erzeugen.',
'Zweijähriger Par-Kupon: 100×(1−d₂)/(d₁+d₂)≈3,9803.|Die Gleichung 100=c×d₁+(100+c)×d₂ wird nach c aufgelöst.'
],'Verwendet für Bootstrapping, Bewertung von Swaps und Festzinscashflows.','Marktfriktionen und unterschiedliche Kredit- oder Besicherungsbedingungen begrenzen einfache Arbitragevergleiche. Forwards enthalten mögliche Risikoprämien.','Arbitragefreiheit bei Derivaten nutzt dieselben Diskontfaktoren; Zinsstrukturtheorien erklären Erwartungen und Prämien.'),
R('Die Zinskurve mischt Erwartungen und Risikoprämien',`Langfristige Zinssätze hängen von erwarteten zukünftigen kurzfristigen Sätzen und von Prämien für Laufzeitrisiko, Liquidität und gegebenenfalls Kreditrisiko ab. Die reine Erwartungshypothese setzt bestimmte Prämien auf null. Eine steigende Kurve muss deshalb nicht bedeuten, dass die Zentralbank im selben Umfang erhöhen wird.

Zinsmodelle beschreiben die Dynamik der Kurve, beispielsweise durch einen kurzfristigen Zins oder mehrere Faktoren für Niveau, Steigung und Krümmung. Für Bewertung und Risikosimulation müssen Parameter zu Marktdaten und Verwendungszweck passen. Ein statistisches Modell realer Zinsbewegungen und ein risikoneutrales Bewertungsmodell beantworten unterschiedliche Fragen; ihre Wahrscheinlichkeiten dürfen nicht beliebig ausgetauscht werden.`,
'Vereinfacht entspricht eine zweijährige Rendite von 4 % dem Durchschnitt erwarteter Einjahreszinsen plus einer Laufzeitprämie von 0,5 Prozentpunkten. Der erste Einjahreszins beträgt 3 %.',[
'Erwartungskomponente=4−0,5=3,5 %.|Zunächst wird die angenommene Prämie aus der langfristigen Rendite entfernt.',
'(3+x)/2=3,5 ergibt x=4 %.|Unter dieser linearen Näherung wird für das zweite Jahr ein Satz von 4 % erwartet.',
'Ohne Prämie ergäbe dieselbe Näherung x=5 %.|Die Interpretation der Kurve hängt wesentlich von der Prämienannahme ab; exakte Forwardrechnung verwendet Verzinsungsfaktoren.'
],'Hilft bei Makrointerpretation, Kurvenszenarien und Bewertung zinsabhängiger Optionen.','Prämien sind nicht direkt beobachtbar. Einfaktormodelle erfassen nicht jede Verdrehung der Kurve; Parameterschätzungen können instabil sein.','Spot-Forward-Beziehungen liefern exakte Preisidentitäten; Kapitalmarkterwartungen behandeln die unsichere Prognose dahinter.'),
R('Duration ist eine lokale Empfindlichkeit, keine Verlustgarantie',`Modified Duration approximiert die relative Preisänderung bei einer kleinen Änderung der Rendite. Das negative Vorzeichen folgt aus der inversen Preis-Zins-Beziehung. DV01 übersetzt diese Empfindlichkeit in Geld je Basispunkt. Macaulay Duration ist dagegen ein barwertgewichteter Zahlungszeitpunkt und muss bei Kuponanleihen für Preissensitivität angepasst werden.

Konvexität ergänzt die Krümmung, weil eine Gerade bei größeren Änderungen ungenau wird. Key-Rate-Durations messen Empfindlichkeiten an einzelnen Kurvenpunkten. Zwei Portfolios mit gleicher Gesamtduration können auf Versteilung völlig verschieden reagieren. Bei Cashflows, die sich durch Optionen ändern, werden effektive Sensitivitäten aus einer Neubewertung unter veränderten Kurven benötigt.`,
'Portfoliowert 1 Mio. €, Modified Duration 5 und Konvexität 30. Die Rendite steigt parallel um 0,50 Prozentpunkte.',[
'Δy=0,005; linearer Effekt=−5×0,005=−2,5 %.|Prozentpunkte werden als Dezimalzahl eingesetzt; 50 Basispunkte sind nicht 0,5 in der Formel.',
'Konvexitätskorrektur=0,5×30×0,005²=0,0375 %.|Die positive Krümmung verringert bei einer gewöhnlichen optionsfreien Anleihe den geschätzten Verlust.',
'Gesamteffekt≈−2,4625 %=−24.625 €; DV01≈1.000.000×5×0,0001=500 €.|DV01 beschreibt nur die lokale Größenordnung je Basispunkt, die Szenariorechnung berücksichtigt zusätzlich Krümmung.'
],'Zentrale Werkzeuge für Hedging, Limits und Anleiheportfolioanalyse.','Parallelverschiebungen sind nur ein Szenario. Große Zinsänderungen, Spreadbewegungen und eingebettete Optionen verlangen Neubewertung.','Immunisierung nutzt Duration zum Abgleich von Vermögen und Verpflichtungen; Derivate können einzelne Kurvenrisiken verändern.'),
R('Haltedauerrendite verbindet Kupon, Preis und Wiederanlage',`Wer eine Anleihe vor Fälligkeit verkauft, erzielt eine Rendite aus laufenden Zahlungen und dem dann gültigen Marktpreis. Dieser hängt von verbleibender Laufzeit, Zinskurve und Kreditspread ab. Der ursprüngliche YTM allein beschreibt diesen Verkaufspreis nicht.

Mit fortschreitender Zeit wandert die Anleihe auf der Kurve zu einer kürzeren Laufzeit. Bei unveränderter Kurve kann daraus ein Roll-down-Effekt entstehen. Zusätzlich wirken Carry, tatsächliche Kurvenverschiebung, Spreadänderung und Wiederanlage. Eine saubere Analyse legt zuerst Horizont und Szenario fest, verschiebt dann die Restcashflows und bewertet sie unter den angenommenen Marktbedingungen neu.`,
'Eine zweijährige Anleihe mit jährlichem Kupon 5 und Nennwert 100 wird zu 100 gekauft. Nach einem Jahr und Kuponzahlung liegt ihre einjährige Rendite bei 4 %.',[
'Verkaufspreis nach dem Kupon=105/1,04=100,9615.|Es bleibt nur die Zahlung aus Tilgung und letztem Kupon in einem Jahr.',
'Endvermögen=5+100,9615=105,9615.|Der gerade erhaltene Kupon wird dem Verkaufserlös hinzugefügt.',
'Einjährige Rendite=105,9615/100−1=5,9615 %.|Die Rendite liegt wegen des Zinsrückgangs über dem ursprünglichen Kupon; Wiederanlage innerhalb dieses Beispiels ist nicht nötig.'
],'Genutzt zur Szenarioplanung und Erklärung realisierter Anleiherenditen.','Unveränderte Kurve ist eine Annahme. Mehrere Kupons innerhalb des Horizonts benötigen eigene Wiederanlageannahmen.','Duration approximiert Preisänderungen; Performance Attribution zerlegt Carry, Kurven- und Krediteffekte.'),
R('Erwarteter Kreditverlust verbindet Häufigkeit und Schwere',`Probability of Default beschreibt die Ausfallwahrscheinlichkeit über einen angegebenen Horizont. Loss Given Default ist der bedingte Verlustanteil im Ausfall; Recovery ist der wiedergewonnene Anteil auf konsistenter Basis. Exposure at Default beschreibt den dann ausstehenden gefährdeten Betrag. Ihr Produkt ist unter den jeweiligen Modellannahmen der erwartete Verlust.

Erwarteter Verlust ist ein Durchschnitt über viele mögliche Verläufe. Ein einzelner Kredit zahlt typischerweise vertragsgemäß oder erleidet einen wesentlich größeren Schaden als diesen Mittelwert. Für Kapitalbedarf und Stress ist deshalb die Verlustverteilung entscheidend. Zudem steigen Ausfälle und Verlustquoten in Krisen häufig gleichzeitig; Unabhängigkeit ist dann eine problematische Vereinfachung.`,
'Einjähriges Exposure 1 Mio. €, Ausfallwahrscheinlichkeit 2 %, Recovery im Ausfall 40 %. Diskontierung wird zur Übersicht weggelassen.',[
'LGD=1−0,40=60 %.|Der nicht zurückgewonnene Anteil ist die Verlustquote.',
'Verlust im Ausfall=1.000.000×0,60=600.000 €.|Dies ist die bedingte Schadenshöhe, nicht der Durchschnitt.',
'Erwarteter Verlust=0,02×600.000=12.000 € beziehungsweise 1,2 % des Exposure.|Die Wahrscheinlichkeit gewichtet die Schadenshöhe; daraus folgt keine Obergrenze von 12.000 € für den möglichen Verlust.'
],'Grundlage für Kreditpreisbildung, Portfoliomodelle und Risikovorsorge.','PD-Horizont, Recovery-Definition und Exposure müssen zusammenpassen. Spread enthält zusätzlich Risikoprämien, Liquidität und weitere Komponenten.','VaR und Expected Shortfall betrachten Verteilungsschwänze; Kreditspreads sind Marktpreise und nicht reine Ausfallprognosen.'),
R('Kreditqualität ist eine Zahlungsfähigkeitsanalyse',`Kreditanalyse untersucht, ob der Emittent Zinsen und Tilgung auch unter ungünstigen Bedingungen leisten kann. Dazu gehören Geschäftsrisiko, Cashflowstabilität, Verschuldung, Fälligkeitsstruktur, Sicherheiten und Zugang zu Refinanzierung. Ein positives Ergebnis reicht nicht aus, wenn liquide Mittel zum Fälligkeitstermin fehlen.

Ratings verdichten diese Einschätzung in Kategorien, können sich aber verzögert ändern und ersetzen keine eigene Prüfung. Credit Spreads sind die zusätzliche Rendite gegenüber einer geeigneten Vergleichskurve. Sie reflektieren erwartete Verluste, Risikovergütung, Liquidität und Marktbedingungen. Eine Spreadausweitung kann deshalb auch bei unveränderter kurzfristiger Ausfallprognose auftreten.`,
'Ein Unternehmen hat EBITDA 50, Schulden 200, Geldbestand 20 und Zinsaufwand 10 Mio. €. EBITDA fällt im Stress auf 35; Schulden und Zinsen bleiben zunächst gleich.',[
'Nettoverschuldung/EBITDA=(200−20)/50=3,6.|Die Kennzahl setzt die Schuldenlast zur groben operativen Ertragskraft.',
'Stress-Leverage=180/35=5,14; EBITDA/Zinsen sinkt von 5 auf 3,5.|Sinkende Erträge verschlechtern mehrere Schutzpuffer zugleich.',
'Tilgungen, Investitionen und Working Capital zusätzlich prüfen.|EBITDA ist kein frei verfügbarer Schuldendienst-Cashflow; gute Deckungskennzahlen können einen nahen Refinanzierungsengpass verdecken.'
],'Verwendet bei Kreditentscheidung, Ratingbeurteilung und Bond-Selektion.','Branchenunterschiede und Bilanzierungswahlrechte begrenzen pauschale Grenzwerte. Vergleichsspreads müssen Laufzeit, Währung und Optionen berücksichtigen.','Cashflowrechnung erklärt Schuldendienstfähigkeit; Kapitalstruktur und Covenants bestimmen Handlungsspielräume.'),
R('Ein Repo ist wirtschaftlich eine besicherte Finanzierung',`Bei einem Repo wird ein Wertpapier verkauft und sein späterer Rückkauf vereinbart. Wirtschaftlich erhält eine Partei kurzfristig Geld und stellt ein Wertpapier als Sicherheit. Der Unterschied zwischen Verkauf und Rückkauf entspricht der Finanzierungsvergütung. Die rechtliche Struktur und Sicherheitenverwertung hängen vom Vertrag ab.

Ein Haircut sorgt dafür, dass der Marktwert der Sicherheit über dem geliehenen Geldbetrag liegt. Dieser Puffer schützt gegen Preisbewegungen und Verwertungskosten, beseitigt aber Gegenparteirisiko nicht vollständig. Zusätzliche Sicherheitenforderungen können bei fallenden Preisen einen Liquiditätsbedarf auslösen. Wer langfristige Wertpapiere fortlaufend kurzfristig finanziert, trägt außerdem Roll-over-Risiko.`,
'Wertpapiere im Marktwert von 1 Mio. € werden mit 5 % Haircut für 30 Tage finanziert. Repo-Satz 3 % p. a., einfache Verzinsung auf 360-Tage-Basis.',[
'Geliehener Geldbetrag=1.000.000×0,95=950.000 €.|Der Haircut wird hier ausdrücklich vom Sicherheitenwert abgezogen.',
'Finanzierungszins=950.000×0,03×30/360=2.375 €.|Der Zins bezieht sich auf den tatsächlich bereitgestellten Geldbetrag.',
'Rückkaufpreis=952.375 €.|Der Kreditnehmer benötigt am Ende Geld für Kapital und Zins; ein werthaltiges Papier allein verhindert keinen Liquiditätsengpass.'
],'Genutzt zur Wertpapierfinanzierung, Liquiditätssteuerung und Umsetzung von Relative-Value-Strategien.','Haircut-Konventionen, tägliche Neubewertung und Close-out-Regeln sind vertragsabhängig. Krisen können Haircuts und Finanzierungskosten gleichzeitig erhöhen.','Leverage verstärkt Eigenkapitalverluste; Liquiditätsstress untersucht Sicherheiten- und Refinanzierungsbedarf.'),
R('Verbriefung verteilt dieselben Kreditverluste auf unterschiedliche Ränge',`Bei einer Verbriefung finanzieren gebündelte Forderungen mehrere Wertpapierklassen. Ein Zahlungswasserfall legt fest, welche Tranche wann Zins und Tilgung erhält und wer Verluste zuerst trägt. Die Senior-Tranche wird durch nachrangiges Kapital geschützt; die Equity-Tranche absorbiert zunächst Verluste und erhält dafür einen unsicheren Rest.

Das Verpacken schafft nicht automatisch bessere zugrunde liegende Kredite. Die Wirkung hängt von Ausfallabhängigkeit, Sicherheitenqualität, Vorzahlungen, Servicing und Vertragsregeln ab. Je stärker Kreditausfälle gemeinsam auftreten, desto eher wird auch der Schutz höherer Tranchen aufgezehrt. Die Analyse muss deshalb vom Forderungspool über Szenarien bis zum konkreten Wasserfall reichen.`,
'Ein Pool von 100 Mio. € finanziert Senior 80, Mezzanine 15 und Equity 5. Ein vereinfachter Verlustwasserfall belastet jeweils zuerst die nachrangigste Klasse.',[
'Bei Poolverlust 3 verliert Equity 3 von 5, also 60 %.|Nachrangiges Kapital konzentriert die ersten Schäden.',
'Bei Poolverlust 12 verliert Equity 5 und Mezzanine 7 von 15, also 46,67 %.|Erst nach vollständigem Verbrauch der Equity-Schicht greift der nächste Rang.',
'Bei Poolverlust 25 verlieren Equity und Mezzanine zusammen 20; Senior verliert 5 von 80=6,25 %.|Seniorität schützt bis zu einem Schwellenwert, nicht gegen beliebig große Poolverluste.'
],'Wichtig für ABS-, MBS- und strukturierte Kreditanalyse.','Reale Wasserfälle enthalten Auslöser, Reserven und zeitabhängige Regeln; reine Endverluste erfassen Zahlungszeitpunkte nicht.','Korrelation beeinflusst gemeinsame Kreditausfälle; Kreditrisiko liefert PD und LGD für den Pool.',{headers:['Tranche','Kapital','Erster Verlust ab'],rows:[['Equity','5','0 Poolverlust'],['Mezzanine','15','5 Poolverlust'],['Senior','80','20 Poolverlust']]}),
R('Vorzeitige Rückzahlung verändert die Laufzeit gerade dann, wenn sie wichtig wird',`Bei vielen Hypotheken kann der Schuldner vorzeitig zurückzahlen. Fallen Marktzinsen, wird Refinanzierung attraktiver; hohe Kupons verschwinden früher und müssen zu niedrigeren Sätzen ersetzt werden. Steigen Zinsen, bleibt die unattraktiv niedrig verzinste Forderung dagegen länger bestehen. Der Anleger ist wirtschaftlich Verkäufer einer Option.

Dieses Verhalten erzeugt negative Konvexität in relevanten Bereichen: Der Kursgewinn bei fallenden Zinsen wird begrenzt, während die Zinsbindung bei steigenden Sätzen zunehmen kann. Contraction bezeichnet verkürzte, Extension verlängerte erwartete Laufzeit. Vorzahlungen hängen zusätzlich von Umzug, Kreditwürdigkeit, Gebühren und Verhalten ab; ein reines Zinsmodell reicht deshalb häufig nicht.`,
'Ein Hypothekenpool von 100 Mio. € zahlt 6 % Zins. Marktzinsen fallen auf 4 %. Vereinfacht werden sofort 30 Mio. € zurückgezahlt und zu 4 % neu angelegt.',[
'Ohne Vorzahlung wären jährliche Zinsen 100×6 %=6 Mio. €.|Dies ist die Vergleichszahl bei unverändertem Kapitalbestand.',
'Nach Umschichtung: 70×6 %+30×4 %=5,4 Mio. €.|Der zurückgezahlte Teil verdient künftig weniger.',
'Ertragsrückgang=0,6 Mio. € jährlich.|Die Rückzahlung zum Nennwert nimmt dem Anleger einen Teil des Vorteils der alten hohen Verzinsung; Marktwert- und Timingeffekte kommen hinzu.'
],'Genutzt zur MBS-Bewertung, Hedging und Planung von Wiederanlagebedarf.','Vorzahlungsmodelle sind verhaltensabhängig und können nach Regimewechseln versagen. Nicht jede Hypothek bietet dieselben Kündigungsrechte.','Optionsbewertung erklärt die Asymmetrie; effektive Duration reagiert auf veränderte Cashflows.'),
R('Ein OAS trennt den modellierten Optionswert vom übrigen Spread',`Eine kündbare Anleihe gibt dem Emittenten das Recht, die Schuld unter bestimmten Bedingungen zurückzuzahlen. Für den Anleger ist sie wirtschaftlich eine optionsfreie Anleihe abzüglich einer verkauften Kündigungsoption. Ein Anleger-Put hat dagegen einen positiven Wert für den Besitzer. Der einfache Renditeaufschlag vermischt daher Kredit-, Liquiditäts- und Optionseffekte.

Ein optionsbereinigter Spread wird in einem Zins- und Ausübungsmodell so angepasst, dass der modellierte Preis zum Marktpreis passt. Er soll den Spread nach Berücksichtigung der Option beschreiben. Er ist damit modellabhängig: Andere Volatilitäts- oder Verhaltensannahmen können bei gleichem Marktpreis einen anderen OAS liefern.`,
'Eine vergleichbare optionsfreie Anleihe wäre 105 wert. Die Kündigungsoption des Emittenten wird im Modell mit 3 bewertet.',[
'Wert der kündbaren Anleihe=105−3=102.|Der Anleger gibt ein Recht ab, deshalb wird dessen Wert abgezogen.',
'Steigt der modellierte Optionswert bei höherer Volatilität auf 5, ergibt sich zunächst 100.|Die größere Wahlmöglichkeit begünstigt den Emittenten und belastet den Anleger, wenn alles andere gleich bleibt.',
'Bleibt der beobachtete Preis 102, muss das Modell an anderer Stelle angepasst werden, etwa über einen niedrigeren OAS.|Ein berechneter OAS hängt somit von den zugrunde gelegten Optionsannahmen ab und ist kein direkt beobachtbarer reiner Kreditspread.'
],'Hilft beim Vergleich von Bonds mit unterschiedlichen Kündigungsrechten.','Z-Spread minus Optionskosten ist nur eine vereinfachte Deutung; belastbare OAS-Bewertung benötigt den gesamten Pfad- und Ausübungsmechanismus.','Binomialbäume bewerten zustandsabhängige Zahlungen; Credit Spreads erklären die nach der Optionsbereinigung verbleibenden Risiken.')
];
