const R=require('./schema.cjs');
module.exports=[
R('Derivate übertragen Risiken, ohne den Basiswert vollständig zu kaufen',`Ein Derivat leitet Zahlungen aus einem Basiswert, Referenzsatz oder Ereignis ab. Dadurch lassen sich Risiken gezielt verändern, ohne alle physischen Vermögenswerte umzuschichten. Der anfängliche Marktwert kann null oder klein sein, während spätere Gewinne und Verluste im Verhältnis zum eingesetzten Geld groß ausfallen. Nominalbetrag, Marktwert und Risikoposition sind deshalb verschiedene Größen.

Zentrales Clearing stellt eine Clearingstelle zwischen die Parteien und verlangt Sicherheiten sowie laufenden Verlustausgleich. Es verändert und bündelt Gegenparteirisiken, beseitigt sie aber nicht vollständig. Bei bilateralen Verträgen bestimmen Netting, Besicherung und Close-out-Regeln die Exponierung. Ein ökonomisch hilfreicher Hedge kann zwischenzeitlich erhebliche liquide Mittel für Margin Calls benötigen.`,
'Ein Futures-Kontrakt hat einen Multiplikator von 100 € je Indexpunkt. Einstieg bei 4.000 Punkten, anfängliche Margin 20.000 €, nächster Abrechnungskurs 3.900.',[
'Nominale Marktexponierung=4.000×100=400.000 €.|Die Margin ist nur eine Sicherheit und nicht der wirtschaftlich bewegte Betrag.',
'Tagesverlust einer Long-Position=(3.900−4.000)×100=−10.000 €.|Der Preisrückgang wird über Variation Margin abgerechnet.',
'Der Verlust entspricht 50 % der anfänglichen Margin, aber 2,5 % des ursprünglichen Nominals.|Beide Prozentangaben sind korrekt, beschreiben jedoch unterschiedliche Bezugsgrößen und Risikofragen.'
],'Verwendet bei Absicherung, effizientem Portfolioaufbau und Gegenparteirisikomanagement.','Marginanforderungen können im Stress steigen. Sicherheiten senken Kreditexposure, erzeugen aber Liquiditäts- und Abwicklungsbedarf.','Leverage erklärt die Wirkung kleiner Anfangsmittel; Liquiditätsmanagement plant Sicherheitenzahlungen.'),
R('Arbitragefreiheit vergleicht identische zukünftige Zahlungen',`Wenn zwei handelbare Strategien unter denselben Bedingungen in jedem Zustand denselben Zahlungsstrom liefern, müssen ihre heutigen Kosten übereinstimmen. Andernfalls könnte die teure Strategie verkauft und die günstige gekauft werden. Dieser Replikationsgedanke bewertet Derivate, ohne eine subjektive Kursprognose vorauszusetzen.

Cost of Carry beschreibt die Kosten und Erträge des Haltens des Basiswerts bis zur Lieferung. Finanzierung und Lagerung erhöhen gewöhnlich den Forwardpreis; Dividenden und andere Erträge senken ihn. Bei physischen Rohstoffen kann der Nutzen des Besitzes als Convenience Yield wirken. Praktische Arbitragegrenzen entstehen durch Leerverkaufsbeschränkungen, Transaktionskosten, Sicherheitenbedarf und unterschiedliche Finanzierungssätze.`,
'Eine dividendenlose Aktie kostet 100 €. Sichere jährliche Finanzierung für ein Jahr kostet 5 %. Ein Forward wird zu 108 € angeboten; Handel und Leerverkauf seien friktionsfrei möglich.',[
'Replikationskosten bei Fälligkeit=100×1,05=105 €.|Kreditaufnahme und sofortiger Aktienkauf sichern den späteren Besitz.',
'Aktie heute kreditfinanziert kaufen und einen Forward zu 108 verkaufen.|Bei Fälligkeit wird die vorhandene Aktie gegen den vereinbarten Preis geliefert.',
'Sicherer Überschuss=108−105=3 €.|Unter den Annahmen ist das Angebot zu teuer; im Gleichgewicht entspricht der Forwardpreis 105 €.'
],'Grundlage für Forward-, Futures- und Optionsbewertung.','Der Gewinn ist nur bei gesicherten Finanzierungs-, Liefer- und Handelsbedingungen risikolos. Praktische Friktionen können eine scheinbare Arbitrage aufzehren.','Zeitwert bestimmt Finanzierung; Put-Call-Parität verwendet denselben Vergleich identischer Zahlungsströme.'),
R('Forwardpreis und Wert eines bestehenden Forwards sind nicht dasselbe',`Der Forwardpreis ist der heute faire Lieferpreis eines neu abgeschlossenen Vertrags. Bei einem marktgerechten neuen Vertrag ist sein anfänglicher Wert typischerweise null. Ein bereits bestehender Vertrag behält dagegen seinen vereinbarten Lieferpreis, auch wenn sich der Markt verändert.

Für einen Long-Forward ist ein alter niedriger Lieferpreis vorteilhaft, wenn ein neuer Vertrag teurer wäre. Der Vertragswert entspricht dem heutigen Wert dieser Preisdifferenz bei passenden Diskontierungsannahmen. Basiswertkurs, verbleibende Laufzeit, Zinsen und laufende Erträge wirken auf den neuen fairen Forwardpreis. Man darf daher den neuen Lieferpreis nicht einfach als heutigen Gewinn verbuchen.`,
'Ein alter Long-Forward verpflichtet in einem Jahr zum Kauf für 100 €. Ein heute neu abgeschlossener Forward auf dieselbe Lieferung hätte Lieferpreis 108 €. Der passende einjährige Diskontsatz beträgt 4 %.',[
'Differenz der Endzahlungen=108−100=8 €.|Durch einen entgegengesetzten neuen Vertrag ließe sich diese Differenz bei Fälligkeit unter den Annahmen festlegen.',
'Heutiger Wert des alten Long-Forwards=8/1,04=7,69 €.|Der sichere Endbetrag wird auf den heutigen Bewertungszeitpunkt diskontiert.',
'Der neue Forward mit Lieferpreis 108 hat dagegen anfänglich Wert 0.|Sein Lieferpreis ist eine zukünftige Verpflichtung, keine heutige Anschaffungsauszahlung von 108 €.'
],'Benötigt für laufende Bewertung, Bilanzierung und Auflösung von Sicherungsgeschäften.','Besicherung, Kreditrisiko und Währung können die Diskontierung verändern. Die einfache Formel setzt übereinstimmende Lieferbedingungen voraus.','Arbitragefreiheit begründet den Vergleich; Swaps lassen sich als Folge verwandter Forward-Zahlungen verstehen.'),
R('Ein Futures-Hedge passt die Empfindlichkeit zweier Positionen an',`Futures werden laufend abgerechnet. Dadurch unterscheidet sich der Zahlungszeitpunkt von einem ansonsten ähnlichen Forward, dessen Gewinn meist am Ende anfällt. Für die Absicherung soll der Gewinn der Futures-Position einen Verlust des Grundgeschäfts möglichst ausgleichen.

Wenn Basiswert und Absicherungsinstrument nicht identisch sind, bleibt Basisrisiko. Die Minimum-Varianz-Hedge-Ratio kombiniert Korrelation und relative Volatilitäten. Eine vollständige nominale Absicherung ist dann nicht notwendigerweise varianzminimal. Außerdem müssen Kontraktgröße, Laufzeit und Richtung stimmen. Ein Hedge kann das Endwertrisiko senken und dennoch durch tägliche Marginzahlungen Liquiditätsprobleme erzeugen.`,
'Ein Warenbestand ist 1 Mio. € wert. Relative Preisvolatilität 20 %, Futures-Volatilität 25 %, Korrelation 0,9. Ein Kontrakt repräsentiert 50.000 € Marktwert.',[
'Optimale relative Hedge-Ratio h=0,9×0,20/0,25=0,72.|Schwächere Korrelation und höhere Futures-Volatilität verringern die benötigte Exponierung.',
'Abzusicherndes Futures-Nominal=0,72×1.000.000=720.000 €.|Die varianzminimale Position ist kleiner als der volle Warenwert.',
'Kontrakte=720.000/50.000=14,4; praktisch etwa 14 oder 15 Short-Kontrakte.|Ein fallender Warenpreis soll durch Gewinne aus verkauften Futures kompensiert werden; Rundung hinterlässt zusätzliche Abweichung.'
],'Verwendet bei Rohstoff-, Aktienindex- und Zinsabsicherung.','Historische Korrelationen können sich verändern. Die Ratio minimiert Varianz unter Modellannahmen, nicht jeden möglichen Verlust oder Liquiditätsbedarf.','Regression liefert die Hedge-Ratio als Sensitivität; Korrelation erklärt das unvermeidbare Restrisiko.'),
R('Ein Swap tauscht Zahlungsregeln statt notwendigerweise Kapital',`Ein Zinsswap tauscht beispielsweise einen festen gegen einen variablen Zins auf einen Nominalbetrag. Bei gewöhnlichen einwährungsbezogenen Zinsswaps wird dieser Nominalbetrag nicht ausgetauscht. Der anfängliche feste Satz wird so gewählt, dass beide Zahlungsseiten denselben Barwert besitzen.

Ein Festzinszahler profitiert im Allgemeinen von steigenden Marktzinsen, weil seine festgelegte Zahlung relativ attraktiv wird. Ein Währungsswap kann dagegen auch Kapitalbeträge verschiedener Währungen austauschen; ein Equity Swap überträgt Aktien- oder Indexrenditen gegen eine andere Vergütung. Bewertung benötigt korrekte Zahlungsdaten, Referenzsätze, Kurven und Besicherungsbedingungen. Die wirtschaftliche Risikowirkung ergibt sich aus Grundgeschäft und Swap gemeinsam.`,
'Ein Unternehmen zahlt auf 10 Mio. € Kredit einen variablen Referenzsatz plus 1 %. Es schließt einen Swap ab, in dem es 4 % fest zahlt und denselben variablen Referenzsatz erhält.',[
'Bei Referenzsatz 3 %: Kreditzins 400.000 €, Swap netto 100.000 € Zahlung.|Der erhaltene variable Swapanteil kompensiert den Referenzteil des Kredits.',
'Gesamtzahlung=500.000 € beziehungsweise 5 %.|Übrig bleiben der feste Swapsatz von 4 % und die Kreditmarge von 1 %.',
'Bei Referenzsatz 6 %: Kredit 700.000 €, Swap netto 200.000 € Eingang; Gesamt wieder 500.000 €.|Der Zins wird unter übereinstimmenden Konditionen fixiert; die Kreditmarge und Gegenparteirisiken bleiben relevant.'
],'Genutzt zur Zinsbindung, Währungsfinanzierung und synthetischen Marktexponierung.','Unterschiedliche Referenzsätze, Reset-Termine oder Nominale erzeugen Basisrisiko. Ein Swap beseitigt keine Refinanzierungs- oder Bonitätsprobleme des Kredits.','ALM betrachtet die gesamte Bilanzwirkung; Diskontfaktoren bewerten die einzelnen Swapzahlungen.'),
R('Optionsrechte erzeugen asymmetrische Auszahlungen',`Ein Call gibt dem Käufer das Recht, den Basiswert zum Ausübungspreis zu kaufen; ein Put das Recht zu verkaufen. Der Käufer muss nicht ausüben, wenn dies nachteilig wäre. Der Verkäufer trägt die entsprechende Verpflichtung. Der Optionspreis ist die heutige Zahlung für dieses Recht und muss bei Gewinnrechnungen berücksichtigt werden.

Put-Call-Parität verbindet europäische Calls und Puts mit gleichem Basiswert, Strike und Fälligkeit. Ein Call plus abgezinster Strike liefert am Ende denselben Wert wie ein Put plus Aktie, wenn keine Dividenden anfallen. Der Zusammenhang ist eine Replikationsidentität und gilt in dieser Form nicht unverändert bei unterschiedlichen Ausübungsrechten oder laufenden Erträgen.`,
'Aktie heute 100 €, Strike 100 €, ein Jahr Laufzeit, risikofreier Satz 5 %, europäischer Callpreis 10 €, keine Dividenden.',[
'Barwert Strike=100/1,05=95,238 €.|Der sichere Betrag von 100 € bei Fälligkeit kostet heute weniger.',
'Putpreis aus Parität: 10+95,238−100=5,238 €.|Die Gleichung C+PV(K)=P+S wird nach P aufgelöst.',
'Bei Endkurs 80 ist Call+100 genau 100; Put+Aktie ist 20+80=100.|Der gleiche Endwert erklärt die Preisbeziehung; bei Endkurs über 100 liefern beide Strategien ebenfalls denselben Wert.'
],'Grundlage für Optionsvergleich, synthetische Positionen und Arbitrageprüfung.','Gewinn und Auszahlung sind zu unterscheiden. Dividenden, Finanzierungskosten und amerikanische Ausübung verändern die einfache Beziehung.','Replikation erklärt die Logik; Optionskombinationen nutzen Call und Put zur gezielten Gestaltung von Ergebnissen.'),
R('Risikoneutrale Bewertung ersetzt Prognosen durch replizierende Preise',`Im Einperioden-Binomialmodell kann der Basiswert nur zwei bekannte Endwerte annehmen. Eine Kombination aus Aktie und sicherer Finanzierung kann dann die beiden Optionsauszahlungen exakt nachbilden. Der Optionspreis folgt aus den heutigen Kosten dieser Kombination.

Die risikoneutrale Wahrscheinlichkeit ist eine rechnerische Gewichtung, unter der der Basiswert mit dem risikofreien Satz wächst. Sie ist nicht die geschätzte tatsächliche Wahrscheinlichkeit einer Kurssteigerung. Ihre Verwendung ist zulässig, weil sie dieselben Preise wie Replikation liefert. Liegt der sichere Wachstumsfaktor nicht zwischen Abwärts- und Aufwärtsfaktor, wäre das einfache Modell nicht arbitragefrei.`,
'Aktie 100 €, mögliche Endkurse 120 und 80 €, Strike 100 €, sicherer Jahreszins 5 %.',[
'Callauszahlungen: oben 20 €, unten 0 €; Hedge-Delta=(20−0)/(120−80)=0,5.|Eine halbe Aktie erzeugt genau die benötigte Auszahlungsdifferenz.',
'Risikoneutrales Gewicht q=(1,05−0,8)/(1,2−0,8)=0,625.|Dieses Gewicht lässt den erwarteten Aktienendwert unter der Bewertungsrechnung auf 105 steigen.',
'Callpreis=(0,625×20+0,375×0)/1,05=11,9048 €.|Kontrolle: 0,5 Aktien kosten 50; ein Kredit von 40/1,05=38,0952 reduziert die Kosten auf denselben Betrag und repliziert beide Zustände.'
],'Didaktische Grundlage für komplexere Optionsbäume und frühe Ausübungsentscheidungen.','Zwei Zustände sind eine starke Vereinfachung. Mehr Perioden verbessern die Auflösung, ersetzen aber keine Prüfung von Volatilität und Vertragsbedingungen.','Delta erklärt die Replikationsposition; Black-Scholes-Merton ist ein kontinuierliches Modell verwandter Absicherungslogik.'),
R('Black-Scholes-Merton ist ein Modell dynamischer Replikation',`Das Modell bewertet europäische Optionen unter Annahmen über die stochastische Kursentwicklung und kontinuierliche Absicherung. In der klassischen Fassung sind Volatilität und risikofreier Satz konstant, Kurse bewegen sich kontinuierlich und Handel ist friktionsfrei. Der Optionspreis hängt von Kurs, Strike, Laufzeit, Zins, Volatilität und gegebenenfalls laufendem Ertrag ab.

Die Normalverteilungsfunktionen gewichten Bestandteile der Replikation. N(d₁) ist im einfachen dividendenlosen Fall das Call-Delta; N(d₂) hat eine risikoneutrale Ausübungsinterpretation. Beide sind keine beliebig austauschbaren realen Erfolgswahrscheinlichkeiten. Die praktische Stärke des Modells liegt auch in konsistenter Quotierung und Sensitivitäten; beobachtete Volatilitätssmiles zeigen zugleich Grenzen konstanter Volatilität.`,
'Europäischer Call: S=K=100, Laufzeit 1 Jahr, stetiger Zins 5 %, Volatilität 20 %, keine Dividende.',[
'd₁=[ln(100/100)+(0,05+0,20²/2)×1]/0,20=0,35; d₂=0,15.|Logarithmischer Kursabstand wird um Zeit- und Volatilitätseffekte angepasst.',
'N(d₁)≈0,6368; N(d₂)≈0,5596; Barwert Strike=100×e^(−0,05)≈95,1229.|Hier wird stetige Verzinsung verwendet, anders als in Beispielen mit jährlichem Zinsfaktor.',
'Call≈100×0,6368−95,1229×0,5596≈10,45 €.|Die gerundeten Verteilungswerte liefern den Preis näherungsweise; mit voller Genauigkeit ergibt sich rund 10,4506 €.'
],'Verwendet für europäische Standardoptionen, implizite Volatilität und Sensitivitätsanalyse.','Sprünge, stochastische Volatilität, diskreter Handel und Kosten verhindern perfekte Absicherung. Amerikanische Optionen benötigen zusätzliche Ausübungsanalyse.','Normalverteilung liefert die Rechenfunktion; Greeks beschreiben lokale Änderungen des Modellpreises.'),
R('Greeks beschreiben, welches Risiko sich gerade verändert',`Delta misst die lokale Änderung des Optionspreises je Kurseinheit des Basiswerts. Gamma misst die Änderung von Delta und damit die Krümmung. Vega erfasst die Wirkung veränderter Volatilität, Theta die Wirkung vergehender Zeit und Rho die Zinsabhängigkeit. Diese Ableitungen sind lokale Näherungen und keine vollständigen Szenarien.

Implizite Volatilität ist der Volatilitätswert, der einen Modellpreis an einen beobachteten Optionspreis anpasst. Sie ist eine preisbasierte Kennzahl und nicht automatisch die beste Prognose realisierter Schwankung. Die Volatilitätsstruktur über Strikes und Laufzeiten zeigt, dass der Markt verschiedene Risiken unterschiedlich bewertet. Ein delta-neutrales Portfolio kann weiterhin große Gamma-, Vega- oder Sprungrisiken besitzen.`,
'Eine Option hat Delta 0,6, Gamma 0,04 und Vega 0,20 € je Volatilitätsprozentpunkt. Der Basiswert steigt um 2 €, implizite Volatilität um 3 Prozentpunkte; andere Einflüsse werden ignoriert.',[
'Deltaeffekt=0,6×2=1,20 €.|Die lineare Näherung folgt der aktuellen Kursempfindlichkeit.',
'Gammaeffekt=0,5×0,04×2²=0,08 €; Vegaeffekt=0,20×3=0,60 €.|Krümmung und Volatilitätsänderung ergänzen die lineare Kurswirkung.',
'Geschätzte Preisänderung=1,20+0,08+0,60=1,88 €.|Vega ist hier ausdrücklich pro Prozentpunkt definiert; bei einer Definition pro Dezimaleinheit wäre der Zahlenwert anders.'
],'Genutzt für Optionshedging, Risikolimits und Erklärung täglicher Wertänderungen.','Kreuzableitungen, Theta und höhere Terme fehlen in der Näherung. Greeks verändern sich selbst mit Marktbewegungen.','Duration ist eine verwandte Sensitivitätsidee; Stressanalyse bewertet große gemeinsame Veränderungen direkt.'),
R('Optionskombinationen tauschen Prämien gegen begrenzte Chancen und Risiken',`Durch Kombination von Aktie, Call und Put lässt sich die Form des Endvermögens gezielt gestalten. Ein Protective Put begrenzt den Verlust des Aktienbestands unterhalb eines Strikes, kostet aber Prämie. Ein Covered Call erzielt Prämie und verzichtet dafür auf Kursgewinne oberhalb des Strikes; er bietet nur einen begrenzten Verlustpuffer.

Ein Collar finanziert einen gekauften Put teilweise oder vollständig durch einen verkauften Call. Die passende Strategie folgt aus dem wirtschaftlichen Ziel: Mindestvermögen, maximal tragbarer Verlust, Bereitschaft zum Verkauf und Anlagehorizont. Eine günstige Anfangsprämie bedeutet keine kostenlose Absicherung, weil Rechte abgegeben oder andere Risiken übernommen werden.`,
'Aktienkauf zu 100 €, Put mit Strike 95 kostet 3 €, verkaufter Call mit Strike 110 bringt 2 €. Beide verfallen gleichzeitig; Zinsen und Dividenden werden ignoriert.',[
'Nettoanfangsausgabe=100+3−2=101 €.|Die Optionskombination kostet zusätzlich 1 € zum Aktienkauf.',
'Bei Endkurs 80: Aktie 80+Put 15−Call 0=95; Gewinn=−6 €.|Der Put stützt das Endvermögen auf 95, aber die gezahlte Nettoprämie gehört zum Verlust.',
'Bei Endkurs 120: 120+0−10=110; Gewinn=9 €.|Der verkaufte Call begrenzt den Gewinn; zwischen 95 und 110 folgt das Endvermögen dem Aktienkurs.'
],'Geeignet für begrenzte Verlustbudgets, konzentrierte Aktienpositionen und strukturierte Auszahlungsziele.','Vor Fälligkeit wirken Zeitwert und Volatilität. Kontraktgröße, Steuern und mögliche vorzeitige Ausübung können die Umsetzung verändern.','Put-Call-Parität erklärt synthetische Äquivalenzen; Wealth Management verbindet die Strategie mit Liquiditäts- und Konzentrationszielen.',{headers:['Endkurs','Endvermögen des Collars','Gewinn gegenüber 101'],rows:[['80','95','−6'],['100','100','−1'],['120','110','+9']]}),
R('Ein CDS überträgt ein vertraglich definiertes Kreditereignisrisiko',`Der Käufer von Kreditschutz zahlt eine Prämie und erhält bei einem definierten Kreditereignis eine vertraglich bestimmte Ausgleichsleistung. Wirtschaftlich kann ein CDS einen Teil des Kreditrisikos einer Anleihe übertragen. Nominalbetrag, Referenzschuldner, Laufzeit, lieferbare Verpflichtungen und Ereignisdefinition müssen zur abzusichernden Position passen.

Eine vereinfachte laufende faire Prämie entspricht bei konstantem Hazard Rate ungefähr Ausfallintensität mal Verlustquote. Reale Bewertung berücksichtigt überlebensabhängige Prämienzahlungen, erwartete Schutzzahlungen, Diskontierung und Vertragskonventionen. CDS-Bond-Basis, Gegenparteirisiko und Liquidität verhindern, dass ein Anleihe-CDS-Paket in jeder Lage völlig risikolos ist.`,
'CDS-Nominal 10 Mio. €, vereinfachte jährliche Ausfallintensität 2 %, angenommene Recovery 40 %. Ein Kreditereignis führt im Beispiel zu einem Abrechnungswert von 35 %.',[
'Ungefähre faire Jahresprämie: 0,02×(1−0,40)=1,2 %=120 Basispunkte.|Die erwartete Schadenshäufigkeit wird mit der angenommenen Schwere kombiniert.',
'Prämiengrößenordnung=10.000.000×1,2 %=120.000 € pro Jahr.|Die tatsächlichen Zahlungstermine und eventuelle Upfront-Zahlungen folgen dem Vertrag.',
'Schutzzahlung im konkreten Ereignis=10.000.000×(1−0,35)=6,5 Mio. €.|Die realisierte Recovery kann von der Preisannahme abweichen; die Schutzzahlung richtet sich nach der Abrechnung.'
],'Genutzt zum Absichern oder gezielten Eingehen von Kreditrisiko und für relative Kreditbewertungen.','Die Näherung ist kein vollständiger CDS-Preis. Ein Vertragsereignis muss nicht jede wirtschaftliche Wertminderung einer Anleihe abdecken.','PD/LGD erklären erwartete Verluste; Gegenparteirisiko bleibt auch beim Kauf von Schutz relevant.'),
R('Ein Hedge beginnt mit der wirtschaftlichen Risikofrage',`Vor der Wahl eines Instruments muss klar sein, welcher Geldbetrag, Zeitpunkt und Risikotreiber geschützt werden soll. Ein Exporteur mit einer Fremdwährungsforderung benötigt eine andere Position als ein Importeur mit einer künftigen Zahlung. Ein Portfoliohedge kann systematisches Aktienrisiko reduzieren, ohne das Einzeltitelrisiko vollständig zu beseitigen.

Die Hedgegröße wird aus der Empfindlichkeit des Grundgeschäfts abgeleitet. Nominale Beträge sind nur dann ausreichend, wenn die Risiken genau proportional sind. Bei Anleihen verwendet man etwa DV01, bei Aktien Beta und bei Optionen Delta. Das gemeinsame Ergebnis aus Grundgeschäft, Hedgekosten, Basisrisiko und Sicherheitenbedarf ist der relevante Maßstab.`,
'Ein Aktienportfolio von 5 Mio. € hat Beta 1,2. Zielbeta ist 0,4. Ein Indexfuture repräsentiert 100.000 € Indexexposure und habe Beta 1.',[
'Zu reduzierendes Marktexposure=(1,2−0,4)×5.000.000=4.000.000 €.|Nur die Differenz zwischen aktuellem und gewünschtem systematischem Risiko wird abgesichert.',
'Benötigte Position=4.000.000/100.000=40 Short-Futures.|Die Gegenposition gewinnt typischerweise bei fallendem Index.',
'Bei Indexverlust 10 %: modellierter Portfolioverlust 600.000 €, Futuresgewinn 400.000 €, netto −200.000 € beziehungsweise −4 %.|Das entspricht Zielbeta 0,4; idiosynkratische Renditen, Basisänderung und Kosten sind hier ausdrücklich ausgeschlossen.'
],'Dient der taktischen Risikosteuerung, Währungsabsicherung und Anpassung von Zinsbindungen.','Geschätzte Sensitivitäten ändern sich. Ein wirksamer Markthedge kann Liquiditätsbedarf schaffen und andere Risiken offenlassen.','CAPM liefert Beta; IPS und Risikobudget legen fest, welches Risiko überhaupt reduziert werden soll.')
];
