const R=require('./schema.cjs');
module.exports=[
R('Eine Aktie verbindet Zahlungsansprüche mit Kontrollrechten',`Eine Stammaktie ist ein Anteil am verbleibenden Unternehmenswert. Dividenden sind im Unterschied zu vertraglichen Zinsen normalerweise keine feste Verpflichtung. Bei Liquidation erhalten Aktionäre erst nach den vorrangigen Anspruchsgruppen einen Rest. Dafür ist ihr Gewinnpotenzial bei wachsendem Unternehmenswert grundsätzlich nicht auf einen festen Betrag begrenzt.

Stimmrechte erlauben Einfluss auf bestimmte Unternehmensentscheidungen; wirtschaftliche Beteiligung und Stimmen müssen jedoch nicht proportional sein. Mehrstimmrechte, Vorzugsaktien und Hinterlegungsscheine können verschiedene Rechte vermitteln. Der Handelsplatz beeinflusst Zugänglichkeit, Transparenz und Abwicklung, verändert aber nicht automatisch die zugrunde liegende Ertragskraft. Eine genaue Analyse beginnt deshalb bei Satzung, Aktienklasse und tatsächlichem Anspruch.`,
'Eine Gesellschaft hat 1 Mio. Aktien der Klasse A mit einer Stimme und 0,2 Mio. Aktien der Klasse B mit zehn Stimmen. Alle haben den gleichen Dividendenanspruch.',[
'Wirtschaftlicher Anteil von B: 0,2/1,2=16,67 %.|Der Zahlungsanspruch richtet sich hier nach der Aktienzahl.',
'Stimmen von B: 0,2×10=2 Mio.; insgesamt 3 Mio.|Die besondere Stimmrechtsausstattung verändert die Kontrolle.',
'Stimmanteil von B: 2/3=66,67 %.|Eine kleine wirtschaftliche Beteiligung kann die Mehrheit der Stimmen kontrollieren; Minderheitsanleger müssen diesen Unterschied bewerten.'
],'Relevant für Governance, Übernahmen, Aktienauswahl und Vergleich verschiedener Aktienklassen.','Rechte unterscheiden sich nach Rechtsordnung und Vertrag. Ein rechnerischer Minderheitsanteil garantiert weder Liquidität noch wirksamen Einfluss.','Kapitalstruktur erklärt den nachrangigen Anspruch; Governance untersucht Konflikte zwischen kontrollierenden und übrigen Eigentümern.'),
R('Eine Order legt fest, welcher Teil des Ausführungsrisikos getragen wird',`Eine Market Order verlangt eine möglichst unmittelbare Ausführung zu verfügbaren Preisen. Eine Limit Order begrenzt den akzeptierten Preis, kann aber unausgeführt bleiben. Dieser Tausch zwischen Preiskontrolle und Ausführungswahrscheinlichkeit ist zentral: Ein Limit beseitigt keine Kosten, sondern verändert deren Art.

Im Orderbuch stehen Kaufgebote auf der Bid-Seite und Verkaufsangebote auf der Ask-Seite. Der Spread vergütet unter anderem Liquiditätsbereitstellung und das Risiko, gegen besser informierte Händler zu handeln. Große Aufträge verbrauchen mehrere Preisstufen. Neben sichtbaren Gebühren entstehen deshalb Spreadkosten und Markteinfluss. Eine Orderentscheidung sollte Größe, Dringlichkeit, Volatilität und Markttiefe berücksichtigen.`,
'Ein Ask-Orderbuch bietet 100 Aktien zu 20,00 € und weitere 200 zu 20,10 €. Du möchtest 250 Aktien kaufen.',[
'100×20,00+150×20,10=5.015 €.|Die Market Order verbraucht zuerst das günstigste Angebot und anschließend die nächste Preisstufe.',
'Durchschnittlicher Kaufpreis: 5.015/250=20,06 €.|Der angezeigte beste Ask war nicht der Preis für die gesamte Order.',
'Ein Kauflimit von 20,00 € würde zunächst höchstens 100 Aktien ausführen.|Die übrigen 150 bleiben offen; steigt der Markt, kann die gewünschte Position unvollständig bleiben.'
],'Verwendet in Handelsplanung, Umsetzung von Portfoliogewichten und Transaktionskostenanalyse.','Ein sichtbares Orderbuch ist eine Momentaufnahme. Stornierungen, versteckte Liquidität und weitere Handelsplätze können die tatsächliche Ausführung verändern.','Implementation Shortfall misst auch Verzögerung und entgangene Ausführung; Liquiditätsrisiko betrifft die Kosten einer Positionsänderung.'),
R('Ein Index ist eine regelgebundene Anlageentscheidung',`Ein Index verdichtet einen definierten Markt zu einer Kennzahl. Die Auswahl und Gewichtung bestimmen, welche Risiken er repräsentiert. Ein kapitalisierungsgewichteter Index gibt großen frei handelbaren Marktwerten mehr Gewicht; ein gleichgewichteter Index verteilt Kapital gleich und benötigt regelmäßige Anpassungen. Ein preisgewichteter Index hängt von Aktienkursen je Stück ab, die durch Aktiensplits verändert werden können.

Markteffizienz beschreibt, wie Informationen in Preisen verarbeitet sind. Sie bedeutet weder, dass Preise immer dem später erkennbaren Fundamentalwert entsprechen, noch, dass niemand zufällig Überrenditen erzielt. Die praktische Frage lautet, ob eine Informationsstrategie nach Risiko, Kosten und realistisch verfügbarer Information systematisch zusätzlichen Wert erzeugt. Ein fairer Vergleich verlangt einen passenden Total-Return-Index mit Dividenden.`,
'Zwei Unternehmen besitzen Marktwerte von 80 und 20 Mio. €. Im Jahr steigt A um 10 %, B fällt um 10 %; Dividenden werden hier ausgeschlossen.',[
'Kapitalisierungsgewichte: 80 % und 20 %.|Die Anfangswerte bestimmen die Beteiligung am Marktergebnis.',
'Indexrendite: 0,8×10 %+0,2×(−10 %)=6 %.|Das größere Unternehmen prägt die Rendite stärker.',
'Gleichgewichtete Anfangsanlage: 0,5×10 %+0,5×(−10 %)=0 %.|Die andere Indexregel erzeugt ein anderes Risikoprofil; die Differenz ist nicht automatisch Manager-Alpha.'
],'Genutzt für Benchmarks, passive Fonds, Marktanalysen und Prüfung aktiver Strategien.','Rückgerechnete Indizes können Auswahlverzerrungen enthalten. Effizienz hängt von Informationsart, Markt und Implementierungskosten ab.','Faktormodelle erklären Unterschiede zwischen Gewichtungsregeln; Performance Appraisal trennt Risikoprämien von aktiver Leistung.'),
R('Wettbewerb entscheidet, wie lange gute Margen bestehen bleiben',`Branchenanalyse fragt, wer wirtschaftlichen Überschuss abschöpfen kann. Kundenmacht drückt Verkaufspreise, Lieferantenmacht erhöht Kosten, Ersatzprodukte begrenzen Zahlungsbereitschaft und neue Wettbewerber bedrohen Gewinne. Eintrittsbarrieren wie Netzwerkeffekte oder Wechselkosten können hohe Kapitalrenditen schützen, müssen aber konkret belegt werden.

Ein Wettbewerbsvorteil ist für die Bewertung nur wertvoll, soweit er zukünftige Cashflows oder deren Sicherheit verbessert. Hohe aktuelle Margen können aus einem vorübergehenden Engpass statt aus dauerhafter Stärke stammen. Deshalb werden Branchenwachstum, Marktanteil, Preisentwicklung und Kapitalbedarf getrennt untersucht. Eine attraktive Branche garantiert außerdem keinen attraktiven Aktienkauf, wenn der Preis bereits überoptimistische Erwartungen enthält.`,
'Eine Firma verkauft 100.000 Einheiten zu 50 €. Variable Stückkosten betragen 30 €, fixe Betriebskosten 1 Mio. €. Neue Konkurrenz erzwingt einen Preis von 47 €.',[
'Vorher EBIT: 100.000×(50−30)−1.000.000=1.000.000 €.|Der Deckungsbeitrag finanziert zunächst die fixen Kosten.',
'Nachher EBIT: 100.000×(47−30)−1.000.000=700.000 €.|Bei unveränderter Menge schlagen die 300.000 € Umsatzverlust vollständig auf das operative Ergebnis durch.',
'Preis fällt um 6 %, EBIT um 30 %.|Fixkosten verstärken den Ergebniseffekt; eine kleine Änderung der Wettbewerbsposition kann großen Bewertungsbedarf auslösen.'
],'Hilft bei Prognose langfristiger Margen, Terminalwert und Auswahl von Vergleichsunternehmen.','Branchenabgrenzungen sind unscharf; technologische Veränderungen können vermeintliche Eintrittsbarrieren schnell entwerten.','Operativer Leverage erklärt den Ergebniseffekt; Residualgewinn verbindet Wettbewerbsvorteile mit Kapitalrenditen über den Kapitalkosten.'),
R('Wachstum muss in Umsatztreiber und Kapitalbedarf zerlegt werden',`Umsatz entsteht aus Menge und Preis beziehungsweise aus Kundenzahl, Nutzung und Erlös je Kunde. Eine treiberbasierte Prognose erklärt, warum Wachstum eintreten soll, statt lediglich eine Prozentzahl fortzuschreiben. Margen verbinden diese Nachfrageannahmen mit Kostenstruktur, Kapazitätsauslastung und Preissetzung.

Gewinnwachstum ist noch kein gleich hohes Cashflowwachstum. Zusätzlicher Umsatz bindet häufig Forderungen, Lager und Sachanlagen. Bei geringer Kapitalrendite kann Wachstum sogar Wert vernichten. Ein konsistentes Modell verbindet daher Umsatz, operative Marge, Steuern, Investitionen, Abschreibungen und Working Capital. Die nachhaltige Wachstumsrate lässt sich nur zusammen mit Reinvestitionsquote und Rendite auf das neu investierte Kapital beurteilen.`,
'Umsatz steigt von 100 auf 110 Mio. €. EBIT-Marge 15 %, Steuersatz 25 %, Abschreibungen 4, Investitionen 7 und zusätzliches Working Capital 2 Mio. €.',[
'EBIT=110×15 %=16,5; NOPAT=16,5×0,75=12,375 Mio. €.|Zuerst wird das operative Ergebnis nach Steuern vor Finanzierung berechnet.',
'Nettoinvestitionen=7−4=3; gesamte zusätzliche Kapitalbindung=3+2=5 Mio. €.|Abschreibungen sind nicht zahlungswirksam, Investitionen und Working Capital beanspruchen Geld.',
'FCFF=12,375+4−7−2=7,375 Mio. €.|Nur dieser Betrag steht im Modell nach operativer Reinvestition allen Kapitalgebern zur Verfügung.'
],'Grundlage für DCF, Unternehmensplanung und Prüfung von Wachstumsbehauptungen.','Margen und Investitionen reagieren oft nicht linear. Kapazitätssprünge, Inflation und Akquisitionen erfordern eigene Annahmen.','Bilanzprognose erklärt Kapitalbindung; FCFF übersetzt operative Prognosen in bewertbare Zahlungsströme.'),
R('Eigenkapitalkosten sind eine Opportunitätsrendite',`Die geforderte Eigenkapitalrendite ist die Entlohnung, die Anleger für Zeit und übernommenes Risiko verlangen. Sie ist keine vertraglich garantierte Zahlung und keine rückblickend beobachtete Eigenkapitalrendite der Bilanz. In einer Bewertung dient sie als Diskontsatz für Cashflows an Aktionäre.

Das CAPM verbindet die Renditeforderung mit dem systematischen Marktrisiko Beta. Faktoransätze berücksichtigen weitere gemeinsame Risikotreiber. Entscheidend ist die Konsistenz: Währung, Inflation, Laufzeit und Cashflowart müssen zum Diskontsatz passen. Ein höherer Diskontsatz senkt bei positiven gegebenen Cashflows den heutigen Wert. Unsicherheit kann durch Szenarien oder Risikoprämien berücksichtigt werden, sollte aber nicht unbemerkt doppelt belastet werden.`,
'Risikofreier Satz 3 %, Marktrisikoprämie 5 %, Beta 1,2. Ein vereinfachter Aktionärscashflow von 10 € wird in einem Jahr erwartet.',[
'Eigenkapitalkosten=3 %+1,2×5 %=9 %.|Beta skaliert die Vergütung für nicht diversifizierbares Marktrisiko.',
'Barwert=10/1,09=9,17 €.|Der erwartete Betrag wird mit der geforderten Rendite auf heute zurückgerechnet.',
'Bei Beta 1,6 steigen die Kosten auf 11 %; Barwert=10/1,11=9,01 €.|Bei gleichem erwarteten Cashflow reduziert höheres systematisches Risiko die Zahlungsbereitschaft.'
],'Eingesetzt in Dividenden-, FCFE- und Residualgewinnmodellen sowie zur Beurteilung aktiver Renditen.','Beta und Risikoprämien sind geschätzt. Historische Daten können das künftige Geschäfts- und Finanzierungsrisiko verfehlen.','CAPM erläutert die Risikologik; WACC kombiniert Eigen- und Fremdkapitalkosten für FCFF.'),
R('Eine Investmentthese braucht einen Mechanismus und eine Widerlegungsmöglichkeit',`Eine Investmentthese erklärt, welche Erwartungen im Preis stecken, worin die eigene Einschätzung abweicht und wie sich diese Abweichung in Zahlungsströmen niederschlagen soll. Ein gutes Unternehmen ist nicht automatisch ein gutes Investment. Der entscheidende Vergleich ist zwischen bezahltem Preis und einem risikogerecht geschätzten Wert.

Katalysatoren sind mögliche Ereignisse, durch die neue Informationen sichtbar werden, etwa eine Produkteinführung oder ein Schuldenabbau. Sie garantieren keine Neubewertung. Ein Research-Bericht trennt beobachtete Fakten, eigene Annahmen, Bewertungsmethode und Handlungsempfehlung. Vorab definierte Gegenbelege helfen, eine These bei neuen Informationen zu aktualisieren, statt nur bestätigende Nachrichten zu sammeln.`,
'Aktienkurs 40 €. Drei Einjahresszenarien ergeben Kurse von 30, 48 und 60 € mit Wahrscheinlichkeiten 25 %, 50 % und 25 %. Jeweils werden 2 € Dividende angenommen.',[
'Erwarteter Endkurs=0,25×30+0,5×48+0,25×60=46,50 €.|Die Szenarien werden nach ihren Annahmewahrscheinlichkeiten gewichtet.',
'Erwartete Gesamtrendite=(46,50+2−40)/40=21,25 %.|Die Dividende gehört neben der Kursänderung zum Ertrag.',
'Im schlechten Szenario beträgt die Rendite (30+2−40)/40=−20 %.|Der Erwartungswert ersetzt keine Verlustanalyse; Positionsgröße und These müssen diesen möglichen Verlauf verkraften.'
],'Genutzt für Investmentkomitees, Positionsentscheidungen und spätere Überprüfung der eigenen Prognosequalität.','Wahrscheinlichkeiten und Zielkurse sind keine gesicherten Fakten. Ein fehlender Katalysator oder steigender Diskontsatz kann die Realisierung verzögern.','Szenarioanalyse liefert mögliche Verläufe; Behavioral Finance erklärt Bestätigungsfehler und übermäßige Sicherheit.'),
R('Dividendenmodelle bewerten Zahlungen an die Eigentümer',`Das Dividend Discount Model diskontiert erwartete Dividenden. Im Gordon-Modell wachsen sie dauerhaft mit konstanter Rate. Die Formel entsteht aus einer unendlichen geometrischen Reihe und setzt einen Diskontsatz über der Wachstumsrate voraus. Verwendet wird die nächste Dividende, nicht die zuletzt gezahlte.

Junge Unternehmen wachsen selten sofort stabil. Ein mehrstufiges Modell prognostiziert zunächst einzelne Jahre und setzt erst danach einen plausiblen Dauerzustand an. Der Terminalwert liegt am Ende der expliziten Prognoseperiode und muss auf heute diskontiert werden. Wachstum, Ausschüttung und Kapitalrendite müssen zueinander passen: Höheres Wachstum verlangt häufig mehr einbehaltene Gewinne.`,
'Dividenden in Jahr 1 und 2: 2,00 und 2,20 €. Danach dauerhaft 3 % Wachstum. Eigenkapitalkosten 8 %.',[
'Dividende Jahr 3=2,20×1,03=2,266 €.|Der Terminalwert am Ende von Jahr 2 beginnt mit der Zahlung des Folgejahres.',
'Terminalwert Jahr 2=2,266/(0,08−0,03)=45,32 €.|Dieser Betrag repräsentiert alle Dividenden ab Jahr 3.',
'Heutiger Wert=2/1,08+(2,20+45,32)/1,08²=42,59 €.|Die zweite Dividende und der Terminalwert liegen auf demselben Zeitpunkt; beide werden zwei Jahre diskontiert.'
],'Geeignet bei nachvollziehbarer Ausschüttungspolitik, etwa reifen Unternehmen.','Sehr empfindlich gegenüber der Differenz zwischen Diskontsatz und Wachstum. Ausschüttungen können erheblich von wirtschaftlich verfügbarem Cashflow abweichen.','FCFE bewertet Ausschüttungskapazität; Zeitwert erklärt die Lage des Terminalwerts auf der Zeitachse.'),
R('FCFF und FCFE unterscheiden sich durch die Anspruchsgruppe',`Free Cashflow to the Firm ist der nach operativen Steuern und Reinvestitionen verfügbare Cashflow vor Zahlungen an Fremdkapitalgeber. Er wird mit dem WACC diskontiert und liefert den Wert des operativen Geschäfts. Vom Unternehmenswert werden anschließend vorrangige Ansprüche abgezogen und nichtoperative Vermögenswerte passend ergänzt.

Free Cashflow to Equity berücksichtigt dagegen Zinsen und Nettokreditaufnahme. Er steht den Aktionären zur Verfügung und wird mit Eigenkapitalkosten diskontiert. Die Verfahren können bei konsistenten Finanzierungsannahmen denselben Eigenkapitalwert liefern. Ein häufiger Fehler besteht darin, FCFF mit Eigenkapitalkosten zu diskontieren oder Zinsen sowohl im Cashflow als auch im WACC erneut abzuziehen.`,
'EBIT 100, Steuersatz 25 %, Abschreibung 10, Investitionen 20, Zunahme Working Capital 5, Zinsen 12, Nettokreditaufnahme 3; alle Werte in Mio. €.',[
'FCFF=100×0,75+10−20−5=60.|Die operative Rechnung ignoriert zunächst die Finanzierung.',
'Zinsen nach Steuern=12×0,75=9; FCFE=60−9+3=54.|Fremdkapitalgeber erhalten Zinsen, während neue Nettofinanzierung Geld für Eigentümer verfügbar macht.',
'Alternativ Nettoergebnis=(100−12)×0,75=66; FCFE=66+10−20−5+3=54.|Beide Wege stimmen überein und liefern eine nützliche Modellkontrolle.'
],'Standardverfahren bei Unternehmensbewertung, Übernahmen und Unternehmen mit unregelmäßigen Dividenden.','Konstante WACC-Annahmen passen nicht zu jeder Verschuldungsentwicklung. Finanzunternehmen erfordern oft andere operative Abgrenzungen.','Kapitalstruktur bestimmt Finanzierung; Bilanzanalyse liefert die Brücke von Gewinn zu Cashflow.',{headers:['Cashflow','Empfänger','Diskontsatz','Ergebnis'],rows:[['FCFF','Alle Kapitalgeber','WACC','Operativer Unternehmenswert'],['FCFE','Aktionäre','Eigenkapitalkosten','Eigenkapitalwert']]}),
R('Multiplikatoren sind verdichtete Bewertungen mit versteckten Annahmen',`Ein Multiplikator setzt einen Marktwert zu einer wirtschaftlichen Bezugsgröße ins Verhältnis. Zähler und Nenner müssen dieselbe Anspruchsgruppe betreffen: Kurs oder Eigenkapitalwert passt zu Gewinn nach Zinsen; Enterprise Value passt zu operativen Größen vor Finanzierung. Ein niedriger Multiplikator kann Unterbewertung bedeuten, aber ebenso geringe Qualität, hohe Risiken oder schwaches Wachstum.

Vergleichsunternehmen sollten hinsichtlich Geschäftsmodell, Wachstum, Kapitalintensität, Rechnungslegung und Risiko ähnlich sein. Vergangenheitsgewinne und erwartete Gewinne dürfen nicht unbemerkt vermischt werden. EBITDA entfernt Abschreibungen, beseitigt aber nicht den wirtschaftlichen Bedarf an Ersatzinvestitionen. Deshalb ergänzen Cashflow- und Kapitalrenditeanalysen den relativen Vergleich.`,
'Vergleichbare Unternehmen handeln zu EV/EBITDA=8. Das Zielunternehmen erwartet EBITDA 20 Mio. €, hat Schulden 50 und überschüssiges Geld 10 Mio. € sowie 12 Mio. Aktien.',[
'Geschätzter Enterprise Value=8×20=160 Mio. €.|Der Multiplikator bewertet das operative Geschäft vor Aufteilung auf Kapitalgeber.',
'Eigenkapitalwert=160−50+10=120 Mio. €.|Schulden mindern den Eigentümerrest, überschüssiges Geld erhöht ihn.',
'Wert je Aktie=120/12=10 €.|Erst nach der Überleitung zur richtigen Anspruchsgruppe darf durch die Aktienzahl geteilt werden.'
],'Nützlich für Marktvergleich, Plausibilisierung einer DCF-Bewertung und Transaktionsanalyse.','Ein ganzer Vergleichssektor kann teuer sein. Negative oder zyklisch ungewöhnliche Nenner machen Multiplikatoren instabil.','DCF macht die im Multiple verborgenen Wachstums- und Renditeannahmen sichtbar; Rechnungslegungsanalyse verbessert Vergleichbarkeit.'),
R('Residualgewinn misst Gewinn oberhalb der Eigenkapitalkosten',`Buchwert ist das bilanziell erfasste Eigenkapital, kein unmittelbarer Marktwert. Das Residualgewinnmodell ergänzt ihn um den Barwert künftiger Gewinne nach Abzug einer kalkulatorischen Eigenkapitalbelastung. Ein Unternehmen schafft in diesem Sinn Wert, wenn es auf das zu Periodenbeginn gebundene Eigenkapital mehr verdient als Anleger verlangen.

Unter passenden Rechnungslegungsbeziehungen lässt sich diese Darstellung aus dem Dividendenmodell herleiten. Zentral ist Clean Surplus: Veränderungen des Buchwerts ergeben sich aus Ergebnis und Eigentümertransaktionen; sonstige erfolgsneutrale Änderungen müssen konsistent behandelt werden. Substanzorientierte Bewertung stellt dagegen auf angepasste Vermögenswerte ab, was bei vermögensintensiven oder zu liquidierenden Unternehmen hilfreich sein kann.`,
'Eigenkapitalbuchwert heute 100 Mio. €, erwarteter nächster Gewinn 12 Mio. €, Eigenkapitalkosten 8 %. Danach werde vereinfachend kein weiterer Residualgewinn erwartet.',[
'Eigenkapitalbelastung=100×8 %=8 Mio. €.|Auch Eigenkapital besitzt eine Opportunitätskostenschwelle, obwohl sie nicht als Aufwand verbucht wird.',
'Residualgewinn=12−8=4 Mio. €.|Nur der Gewinn oberhalb dieser Schwelle erhöht den Wert über den Buchwert.',
'Eigenkapitalwert=100+4/1,08=103,70 Mio. €.|Der vorhandene Buchwert wird um den Barwert des einzigen angenommenen Mehrgewinns ergänzt.'
],'Geeignet für Unternehmen mit aussagekräftigen Buchwerten und schwer prognostizierbaren Ausschüttungen.','Buchwertverzerrungen, immaterielle Werte und unsaubere Ergebnisabgrenzung können den Ansatz stark beeinflussen.','ROE gegenüber Eigenkapitalkosten erklärt Mehrwert; Bilanzanalyse prüft die Qualität des Ausgangsbuchwerts.'),
R('Bei privaten Unternehmen ist Bewertung stärker von Bedingungen abhängig',`Private Unternehmen besitzen oft keinen laufend beobachtbaren Marktpreis. Bewertung muss deshalb Geschäftszahlen normalisieren, Kontrollrechte und Übertragungsbeschränkungen untersuchen und plausible Transaktionsbedingungen festlegen. Unternehmerlohn, private Aufwendungen oder einmalige Geschäfte können berichtete Ergebnisse verzerren.

Ein Minderheitsanteil ohne Ausschüttungseinfluss ist wirtschaftlich nicht identisch mit vollständiger Kontrolle. Ebenso kann geringe Veräußerbarkeit relevant sein. Solche Unterschiede dürfen nicht pauschal mit beliebigen Abschlägen versehen werden: Ausgangswert, Rechte und empirische Begründung müssen zusammenpassen. Szenarien oder Wertbandbreiten machen die Unsicherheit oft ehrlicher sichtbar als eine scheinbar exakte Einzelzahl.`,
'Ein Betrieb berichtet EBITDA 1,0 Mio. €. Darin sind 0,2 Mio. private Eigentümerkosten und 0,1 Mio. einmaliger Ertrag enthalten. Ein begründeter Vergleichsmultiple liegt zwischen 5 und 7.',[
'Normalisiertes EBITDA=1,0+0,2−0,1=1,1 Mio. €.|Nichtbetriebliche Kosten werden zurückgenommen und nicht wiederkehrende Erträge entfernt.',
'Operativer Wertbereich=1,1×5 bis 1,1×7=5,5 bis 7,7 Mio. €.|Die Bandbreite reflektiert unterschiedliche plausible Marktbewertungen.',
'Bei Nettoschulden von 2 Mio. € ergibt sich Eigenkapital von 3,5 bis 5,7 Mio. €.|Erst danach werden die konkret bewerteten Anteilsrechte und Transaktionsbedingungen geprüft.'
],'Relevant für Nachfolge, Private Equity, Übernahmen und Mitarbeiterbeteiligungen.','Kleine Stichproben, vertrauliche Vertragsdetails und Schlüsselpersonenrisiko begrenzen Vergleichbarkeit. Keine universelle Illiquiditätsabschlagsformel ersetzt die Einzelfallanalyse.','Due Diligence prüft Normalisierungen; Wealth Management behandelt die Konzentration im eigenen Unternehmen.')
];
