const R=require('./schema.cjs');
module.exports=[
R('Ethische Urteile brauchen einen nachvollziehbaren Prozess',`Ethik beschäftigt sich mit der Frage, welche Handlung gegenüber anderen verantwortbar ist. Im Investmentgeschäft entstehen Konflikte, weil Berater mehr Informationen als Kunden besitzen und über fremdes Vermögen entscheiden. Fachwissen allein reicht daher nicht: Die Empfehlung muss auch unabhängig, sorgfältig und auf den Auftrag ausgerichtet sein.

Ein Entscheidungsprozess trennt beobachtete Fakten, betroffene Personen, geltende Pflichten und mögliche Handlungen. Erst danach wird abgewogen. Die spätere Dokumentation erklärt, welche Information zum Entscheidungszeitpunkt vorlag. Ein zufällig gutes Ergebnis macht eine unsorgfältige Entscheidung nicht nachträglich richtig; ein Verlust beweist umgekehrt keinen Pflichtverstoß.`,
'Eine Analystin soll einen Fonds empfehlen. Der eigene Arbeitgeber erhält dafür eine höhere Provision, während ein vergleichbares Produkt günstiger ist.',[
'Fakten feststellen: gleiche Anlageidee, aber unterschiedliche Gesamtkosten.|Damit wird der konkrete Konflikt sichtbar; bloße Produktwerbung reicht zur Beurteilung nicht.',
'Kundenziel und Alternativen vergleichen: Gibt es belegbare Vorteile des teureren Fonds?|Höhere Kosten können nur im Zusammenhang mit einer nachvollziehbaren Leistung bewertet werden.',
'Konflikt behandeln, Empfehlung begründen und relevante Vergütung transparent machen.|Offenlegung allein ersetzt weder Eignung noch eine sachliche Entscheidungsgrundlage.'
],'Dieser Ablauf eignet sich für Research, Produktauswahl und die Beurteilung von Fallvignetten. Formuliere jeweils Pflicht, problematischen Sachverhalt und konkrete Abhilfe.','Kodizes lösen nicht jeden Zielkonflikt mechanisch. Anwendbares Recht, tatsächliche Rolle und weitere Pflichten müssen zusätzlich berücksichtigt werden.','Das IPS konkretisiert das Kundeninteresse; Kostenanalyse und Due Diligence liefern die Sachgrundlage.'),
R('Unabhängigkeit betrifft auch den Entstehungsprozess einer Meinung',`Ein Analyst kann durch Geschenke, Zugang zum Management, Vergütung oder Druck des Vertriebs beeinflusst werden. Objektivität bedeutet, Schlussfolgerungen aus nachvollziehbarer Evidenz abzuleiten. Sie verlangt auch, eigene Grenzen zu erkennen und bei widersprüchlichen Informationen nachzuprüfen.

Trenne ein für die Analyse notwendiges Treffen von einem persönlichen Vorteil. Auch eine tatsächlich unveränderte Meinung kann unglaubwürdig wirken, wenn der Emittent luxuriöse Vorteile finanziert. Maßgeblich sind Art, Umfang und Kontext, nicht eine selbst erfundene universelle Geldgrenze. Bei unterschiedlichen rechtlichen und beruflichen Anforderungen ist die strengere einschlägige Regel zu beachten.`,
'Ein Unternehmen bietet einer Analystin nach positiver Berichterstattung ein luxuriöses Wochenende und Zugang zu einer Werkbesichtigung an.',[
'Werkbesichtigung und Freizeitangebot getrennt beurteilen.|Die Besichtigung kann fachlich sinnvoll sein; der Freizeitvorteil erzeugt einen persönlichen Anreiz.',
'Freizeitvorteil ablehnen und eine sachgerechte Finanzierung des notwendigen Besuchs organisieren.|Dadurch wird die Analyse weniger von der Großzügigkeit des Emittenten abhängig.',
'Annahmen und Daten unabhängig prüfen; Änderung der Bewertung nur fachlich begründen.|Die relevante Leistung ist ein belastbares Urteil und nicht die Gegenleistung für Zugang.'
],'Praktisch helfen Geschenkregister, unabhängige Freigaben und Trennung von Research und provisionsabhängigem Vertrieb.','Interne Genehmigung macht eine unzulässige Zuwendung nicht automatisch zulässig. Eine pauschale Aussage „kleine Geschenke sind immer erlaubt“ wäre zu grob.','Interessenkonflikte betreffen Anreize; Reasonable Basis betrifft Qualität und Tragfähigkeit der Analyse.'),
R('Öffentlichkeit und Wesentlichkeit getrennt prüfen',`Eine Information ist wesentlich, wenn sie für eine vernünftige Anlageentscheidung bedeutsam sein könnte. Nicht öffentlich ist sie, solange der Markt keinen angemessenen Zugang hat. Die Kombination ist kritisch: Wer wesentliche nicht öffentliche Information besitzt, darf daraus keinen Handelsvorteil für sich oder andere ableiten.

Die Mosaic Theory erlaubt das Zusammenführen öffentlich verfügbarer wesentlicher Informationen mit nicht wesentlichen nicht öffentlichen Puzzleteilen. Sie erlaubt nicht, eine vertrauliche Gewinnwarnung durch Beimischung öffentlicher Daten zu legitimieren. Marktmanipulation kann daneben durch falsche Aussagen oder durch Transaktionen entstehen, die bewusst irreführende Preis- oder Volumensignale setzen.`,
'Ein Finanzvorstand nennt einem Analysten vertraulich einen noch unangekündigten Einbruch des Jahresgewinns.',[
'Gewinneinbruch auf Wesentlichkeit prüfen.|Ein erheblicher Einfluss auf erwartete Cashflows und Bewertung spricht für Entscheidungsrelevanz.',
'Öffentlichkeit prüfen: Die Aussage fiel in einem vertraulichen Gespräch.|Dass mehrere Personen im Raum waren, macht sie nicht marktöffentlich.',
'Nicht handeln oder weiterempfehlen; zuständige Compliance-Funktion einschalten.|Das Handelsverbot betrifft auch die Nutzung für Kunden. Die konkrete Behandlung erfolgt nach den einschlägigen Verfahren.'
],'Die Zweifragenprüfung ist nützlich bei Managementgesprächen, Expertennetzwerken und alternativen Daten.','Die Abgrenzung hängt vom konkreten Inhalt und Verbreitungsstand ab. Ein Kursanstieg nach einer Information beweist allein keine Manipulation.','Bewertung erklärt Wesentlichkeit über Werttreiber; Ethik begrenzt, welche Informationen für eine Handelsentscheidung genutzt werden dürfen.'),
R('Kundeneignung wird am Gesamtportfolio beurteilt',`Sorgfalt umfasst, den Auftrag und die wirtschaftliche Situation des Kunden zu kennen. Eignung verbindet Anlageziel, Zeithorizont, Liquidität, Risikotragfähigkeit und vorhandene Anlagen. Ein isoliert attraktives Produkt kann im Gesamtportfolio eine gefährliche Konzentration erzeugen.

Fair Dealing verlangt faire Verfahren für Empfehlungen und Transaktionen. Es bedeutet nicht, jeden Kunden unabhängig von Mandat und Bedarf identisch zu behandeln. Vertraulichkeit schützt Kundendaten; legitime Ausnahmen sind konkret zu prüfen. Die Interessen der Begünstigten sind insbesondere bei Treuhand- und Pensionsmandaten von den Interessen einzelner Ansprechpartner zu unterscheiden.`,
'Eine Kundin besitzt 800.000 € Vermögen, davon 600.000 € Aktien ihres Arbeitgebers, und möchte weitere 100.000 € in dieselbe Branche anlegen.',[
'600.000/800.000 = 75 % direkte Arbeitgeberkonzentration.|Zusätzlich kann ihr Arbeitseinkommen von derselben Firma abhängen.',
'Neue Anlage wirtschaftlich zum bestehenden Risiko addieren.|Eine andere Aktie desselben Sektors kann gemeinsame Konjunktur- und Branchenrisiken verstärken.',
'Alternative anhand Liquiditätsziel, Konzentrationsabbau und Kosten begründen.|Eine hohe erwartete Einzelrendite beantwortet die Eignungsfrage nicht vollständig.'
],'Diese Prüfung wird vor Empfehlungen und bei wesentlichen Änderungen der Kundensituation aktualisiert.','Risikobereitschaft und finanzielle Verlusttragfähigkeit können auseinanderfallen. Ein unterschriebener Risikohinweis ersetzt die Analyse nicht.','Human Capital erweitert die Vermögenssicht; Diversifikation misst gemeinsame Risiken; IPS dokumentiert die Entscheidung.'),
R('Aufsicht bedeutet organisierte Prävention und Reaktion',`Vorgesetzte benötigen angemessene Verfahren, mit denen Regelverstöße verhindert und erkannt werden können. Dazu gehören Zuständigkeiten, Schulung, Kontrolle und Eskalation. Eine Richtlinie im Ordner wirkt nicht, wenn niemand ihre Einhaltung überprüft.

Loyalität gegenüber dem Arbeitgeber umfasst den Schutz berechtigter Interessen und vertraulicher Informationen. Sie verlangt nicht, Fehlverhalten zu unterstützen. Zusätzliche Vergütungen können Konflikte auslösen und erfordern die einschlägige Zustimmung. Beim Arbeitgeberwechsel sind eigene Fähigkeiten von vertraulichen Kundendaten und fremdem Arbeitseigentum zu trennen.`,
'Eine Teamleiterin erkennt wiederholt private Mitarbeitertransaktionen kurz vor größeren Kundenorders.',[
'Daten sichern und den Vorgang zeitnah untersuchen lassen.|Ohne Orderzeitpunkte und Zuständigkeiten bleibt der Verdacht nicht überprüfbar.',
'Bis zur Klärung geeignete zusätzliche Kontrollen oder Beschränkungen einsetzen.|Die konkrete Maßnahme muss weitere problematische Transaktionen verhindern können.',
'Nach Ursache auch den Prozess korrigieren und die Umsetzung kontrollieren.|Nur eine Ermahnung lässt eine systematische Kontrolllücke bestehen.'
],'Der Ansatz ist relevant für Handelsteams, Research und externe Dienstleister mit delegierten Aufgaben.','Eine Führungskraft garantiert nicht, dass nie ein Verstoß geschieht. Entscheidend sind angemessene Systeme und die Reaktion auf erkennbare Probleme.','Front Running ist ein Interessenkonflikt; Dokumentation ermöglicht Rekonstruktion und wirksame Aufsicht.'),
R('Eine Empfehlung muss von Daten bis Schlussfolgerung prüfbar sein',`Reasonable Basis bedeutet, dass eine Empfehlung eine angemessene analytische Grundlage besitzt. Dazu gehören relevante Informationen, passende Methoden und nachvollziehbare Annahmen. Auch zugekauftes Research muss beurteilt werden; Herkunft von einem bekannten Anbieter ist kein Ersatz für Prüfung.

Kommunikation trennt Fakten, Schätzungen und Meinungen. Eine Modellbewertung ist eine bedingte Aussage: Ändern sich Wachstum, Risiko oder Kapitalbedarf, ändert sich der Wert. Die Dokumentation sollte den damaligen Entscheidungsprozess rekonstruierbar machen. Das ist besonders wichtig, wenn neue Daten später zu einer anderen Empfehlung führen.`,
'Ein Gordon-Modell verwendet erwartete Dividende 4 €, Eigenkapitalkosten 8 % und Dauerwachstum 3 %.',[
'8 % − 3 % = 5 Prozentpunkte; 4/0,05 = 80 €.|Der Nenner fasst Diskontierung und Wachstum zusammen; beide müssen auf derselben Basis vorliegen.',
'Wachstum testweise auf 2 % reduzieren: 4/0,06 = 66,67 €.|Ein Prozentpunkt weniger Dauerwachstum senkt den Modellwert um 13,33 € und zeigt die Annahmeabhängigkeit.',
'80 € als Szenariowert samt Annahmen berichten.|Eine präzise Ausgabe ist keine präzise Gewissheit. Sensitivität und Begründung gehören zur Empfehlung.'
],'Geeignet für Researchberichte, Modellfreigaben und die Überprüfung KI-gestützter Analyse.','Dokumentierte Rechnungen können auf falschen Inputs beruhen. Plausibilität, Datenqualität und Modellgrenzen sind eigenständige Prüfschritte.','DCF und Sensitivitätsanalyse liefern die Rechnung; Ethik bestimmt die transparente Darstellung gegenüber Kunden.'),
R('Interessenkonflikte erkennen, bevor sie das Urteil beeinflussen',`Ein Konflikt liegt vor, wenn ein Nebeninteresse die Erfüllung einer beruflichen Pflicht beeinflussen kann. Eigene Wertpapierbestände, erfolgsabhängige Vergütung, Vermittlungsgebühren und familiäre Beziehungen sind typische Quellen. Ein Konflikt muss nicht bereits zu einem Schaden geführt haben, um relevant zu sein.

Die sachgerechte Behandlung kann Vermeidung, organisatorische Trennung oder andere Kontrolle und eine klare Offenlegung verlangen. Kundenorders haben gegenüber wirtschaftlich gleichgerichteten eigenen Transaktionen Vorrang. Eine bloße Fußnote heilt weder unfaire Ausführung noch eine ungeeignete Empfehlung.`,
'Ein Berater besitzt selbst eine illiquide Aktie und möchte sie Kunden empfehlen; eine große Kundenorder würde vermutlich den Kurs bewegen.',[
'Eigenbestand und erwartete Kurswirkung als Konflikt benennen.|Der Berater könnte persönlich von seiner Empfehlung profitieren.',
'Unabhängige Prüfung und Regeln für Eigengeschäfte anwenden.|Die Kundenentscheidung darf nicht zur Verbesserung des eigenen Verkaufspreises dienen.',
'Wesentliche Beteiligung offenlegen und Kundenfairness bei Ausführung sichern.|Transparenz ermöglicht Einordnung, ersetzt aber den Vorrang der Kundeninteressen nicht.'
],'Konfliktregister und Freigaben vor Eigengeschäften helfen, solche Situationen frühzeitig zu behandeln.','Nicht jeder Konflikt lässt sich allein mit Offenlegung ausreichend steuern. Die konkrete Rolle und Transaktion bestimmen die nötige Maßnahme.','Markteinfluss verbindet diesen Ethikfall mit Handelskosten; Fair Dealing betrifft die Verteilung knapper Handelsmöglichkeiten.'),
R('Qualifikation korrekt darstellen',`Eine Berufsqualifikation beschreibt bestandene Anforderungen und laufende Verpflichtungen. Sie ist keine Renditegarantie und keine Billigung einzelner Produkte durch die verleihende Organisation. Kandidatenstatus und Mitgliedschaft dürfen nur im tatsächlich zutreffenden Umfang angegeben werden.

Die Integrität einer Prüfung verlangt Schutz vertraulicher Prüfungsinhalte. Lernende dürfen öffentliche Themen diskutieren, aber nicht nicht öffentliche konkrete Aufgaben rekonstruieren und verbreiten. Die Abgrenzung betrifft den Inhalt und die Vertraulichkeit, nicht nur die Frage, ob jemand dafür bezahlt wird.`,
'Eine Person hat eine Prüfungsstufe bestanden und wirbt mit „CFA garantiert überdurchschnittliche Ergebnisse“.',[
'Ausbildungsstand und verwendete Bezeichnung abgleichen.|Eine Teilprüfung verleiht nicht automatisch die vollständige Berufsbezeichnung.',
'Renditebehauptung separat prüfen.|Prüfungsleistung belegt keine garantierte künftige Investmentperformance.',
'Darstellung auf zutreffende, sachliche Angaben korrigieren.|Damit können Kunden den tatsächlichen Status erkennen, ohne eine Leistungsgarantie zu unterstellen.'
],'Relevant für Lebensläufe, berufliche Profile, Werbematerial und Prüfungsvorbereitung.','Die genaue zulässige Bezeichnung hängt vom tatsächlichen Status und den aktuellen Regeln ab. Es gibt keine allgemeine Freigabe für selbst erfundene Titel.','Performance Appraisal beurteilt Können anhand von Daten; Qualifikationsangaben beschreiben Ausbildung und Status.'),
R('Ethik auf Ebene einer Organisation verankern',`Der Asset Manager Code richtet den Blick auf die Vermögensverwaltungsorganisation. Kundentreue, Anlageprozess, Handel, Risikomanagement, Bewertung und Offenlegung müssen in verlässliche Abläufe übersetzt werden. Eine gute persönliche Absicht reicht nicht, wenn die Organisation systematisch falsche Anreize setzt.

Unabhängige Bewertung, klare Verantwortlichkeiten und ein kontrollierter Umgang mit Fehlern stärken die Nachvollziehbarkeit. Insbesondere illiquide Anlagen benötigen dokumentierte Bewertungsverfahren: Der Manager kann zugleich an hohen ausgewiesenen Werten und hohen Gebühren interessiert sein. Eine Konformitätsbehauptung verlangt die Erfüllung der maßgeblichen Anforderungen, nicht die Auswahl angenehmer Teile.`,
'Ein Fondsmanager erhöht den geschätzten Wert einer nicht gehandelten Beteiligung kurz vor Berechnung seiner Erfolgsgebühr.',[
'Bewertungsgrundlage und wirtschaftliche Änderungen dokumentieren.|Ein höherer Wert muss durch Annahmen oder Informationen nachvollziehbar sein.',
'Interessenkonflikt durch eine geeignete unabhängige Kontrolle behandeln.|Wer von der Bewertung profitiert, sollte nicht unkontrolliert allein darüber entscheiden.',
'Gebühren- und Bewertungsmethode den Anlegern verständlich erläutern.|Anleger müssen erkennen können, wie Schätzwerte auf ihre Kosten wirken.'
],'Der organisationsbezogene Ansatz hilft bei Managerauswahl, Due Diligence und Prozessgestaltung.','Ein Verhaltenskodex ist keine staatliche Aufsichtszulassung und keine Versicherung gegen Anlageverluste.','Alternative Anlagen benötigen Bewertungsannahmen; Fondsgebühren übersetzen die Werte in reale Zahlungsansprüche.'),
R('Vergleichbare Performance braucht einheitliche Regeln',`Ein Manager kann seine Leistung besser aussehen lassen, indem er erfolgreiche Mandate auswählt, unterschiedliche Gebührenbasen vermischt oder fehlgeschlagene Portfolios verschwinden lässt. GIPS zielt auf faire, konsistente Darstellung. Wesentlich sind eine sachgerechte Definition der Firma und die Zuordnung geeigneter Portfolios zu vergleichbaren Composites.

Zeitgewichtete Renditen zerlegen Zeiträume an externen Cashflows und verketten Teilrenditen. Dadurch wird der Einfluss vom Kunden veranlasster Ein- und Auszahlungen reduziert. Die Aussage unterscheidet sich von der persönlichen geldgewichteten Rendite. Die Standards enthalten über diese Grundidee hinaus detaillierte Berechnungs- und Offenlegungsanforderungen.`,
'Ein Portfolio verdient in der ersten Teilperiode 10 % und verliert in der zweiten 5 %. Zwischen den Teilperioden zahlt der Kunde zusätzlich ein.',[
'Erste Teilrendite als Faktor 1,10 schreiben.|Der Faktor enthält Startkapital und Ertrag der ersten Periode.',
'1,10 × 0,95 = 1,045; verknüpfte Rendite 4,5 %.|Die zweite Rendite wirkt auf den fortgeschriebenen Bestand. Der externe Zufluss ist kein Investmentertrag.',
'Rendite zusammen mit Zeitraum, Kostenbasis und passender Vergleichsgruppe berichten.|Erst diese Angaben erlauben einen sinnvollen Vergleich mit anderen Mandaten.'
],'Nützlich bei Managervergleich und Performanceberichten. Vermögensgewichtete Composite-Berechnung ergänzt die Zeitverkettung einzelner Portfolios.','Eine korrekt berechnete Rendite beweist weder Fähigkeit noch passendes Risiko. Eine isolierte Rechenmethode bedeutet noch keine vollständige GIPS-Konformität.','TWR erklärt Cashflow-Neutralisierung; Composites verhindern selektive Portfoliowahl; Appraisal prüft die Aussagekraft des Ergebnisses.'),
R('Ethische Fallfragen in eine Handlung übersetzen',`Fallvignetten enthalten oft viele Fakten, aber nur wenige entscheiden über die einschlägige Pflicht. Eine gute Lösung benennt zunächst Rolle, Auftrag und Konflikt. Danach folgt die konkrete Handlung: prüfen, offenlegen, ablehnen, korrigieren oder eskalieren. Moralische Wertungen ohne Bezug zur beruflichen Pflicht bleiben unpräzise.

Die Reihenfolge kann entscheidend sein. Eine Offenlegung nach Abschluss eines Geschäfts informiert zu spät, wenn der Kunde vorher entscheiden können musste. Ebenso kann ein verlässlicher Analyseprozess notwendig sein, bevor überhaupt eine Empfehlung entsteht. Mehrere Pflichten können gleichzeitig gelten.`,
'Eine Analystin entdeckt nach Veröffentlichung einen wesentlichen Rechenfehler in ihrem Kursziel. Ein wichtiger Kunde hat den Bericht bereits erhalten.',[
'Fehler und Auswirkung nachvollziehbar feststellen.|Nur ein Tippfehler oder ein entscheidungsrelevanter Bewertungsfehler erfordert jeweils eine andere Reaktion.',
'Bericht korrigieren und betroffene Empfänger zeitnah über wesentliche Änderungen informieren.|Die alte Empfehlung darf nicht unkommentiert als gültige Analyse weiterwirken.',
'Ursache dokumentieren und Kontrollprozess verbessern.|Die Lösung behandelt sowohl die aktuelle Fehlkommunikation als auch das Wiederholungsrisiko.'
],'Beim Lernen lohnt ein Dreisatz: relevanter Fakt, zugehörige Pflicht, konkrete Maßnahme. Das trainiert begründete statt bloß erinnerte Antworten.','Ohne vollständigen Sachverhalt lassen sich manche Fälle nicht abschließend entscheiden. Fehlende Informationen sind gezielt zu benennen, nicht durch Vermutungen zu ersetzen.','Kommunikationspflichten, Dokumentation und Aufsicht greifen im selben Fall ineinander.')
];
