const R=require('./schema.cjs');
module.exports=[
R('Due Diligence prüft die Behauptungen, auf denen der Kaufpreis beruht',`Deal Sourcing schafft Zugang zu möglichen Transaktionen; Screening prüft zunächst strategische Passung und offensichtliche Ausschlussgründe. Vertiefte Due Diligence untersucht Markt, Kunden, Betrieb, Finanzen, Recht, Steuern und Organisation. Ihr Ziel ist eine belastbare Entscheidung, nicht bloß eine lange Dokumentenliste.

Besonders wichtig ist die Qualität nachhaltiger Erträge. Einmalige Umsätze, Kundenkonzentration, nicht marktgerechte Eigentümerleistungen oder unterlassene Investitionen können die berichtete Profitabilität verfälschen. Erkenntnisse müssen in Prognosen, Preis, Vertragsgarantien oder Transaktionsabbruch übersetzt werden. Unabhängige Belege und die gezielte Suche nach Gegenargumenten reduzieren die Gefahr einer vom Abschlusswunsch getriebenen Analyse.`,
'Ein Verkaufsmodell zeigt EBITDA 5 Mio. €. Darin stecken 0,8 Mio. € einmaliger Lizenzumsatz; zusätzlich fehlt marktüblicher Geschäftsführungsaufwand von 0,3 Mio. €. Bewertungsmultiple 8.',[
'Nachhaltiges EBITDA=5−0,8−0,3=3,9 Mio. €.|Beide Korrekturen reduzieren den künftig plausiblen operativen Ertrag.',
'Unbereinigter Wert=5×8=40 Mio. €; bereinigter Wert=3,9×8=31,2 Mio. €.|Die gleiche Bewertungsregel erzeugt nach Prüfung eine wesentlich andere Zahlungsbereitschaft.',
'Differenz=8,8 Mio. €; Vertrags- und Prognosefolgen dokumentieren.|Ein Datenfund schafft erst dann Entscheidungsnutzen, wenn er in die Transaktion eingeht.'
],'Genutzt für Buyouts, Private Credit und Venture-Investitionen, jeweils mit angepassten Prüfschwerpunkten.','Datenräume können unvollständig sein; Zeitdruck und Informationsasymmetrie bleiben bestehen. Garantien ersetzen keine wirtschaftliche Prüfung ihrer Durchsetzbarkeit.','Bilanzqualität erklärt Normalisierung; Investmentthese benennt entscheidende Gegenbelege.'),
R('Die Transaktionsstruktur verteilt Cashflows, Kontrolle und Verlusttragung',`Der Kaufpreis ist nur ein Teil der Transaktion. Schulden, Eigenkapital, Verkäuferdarlehen, Earn-outs und bevorzugte Rechte legen fest, wer unter welchen Bedingungen Zahlungen erhält. Gleicher Enterprise Value kann deshalb für Käufer und Verkäufer sehr unterschiedliche wirtschaftliche Ergebnisse erzeugen.

Ein Finanzierungsmodell beginnt mit Sources and Uses: Jede Verwendung von Geld muss durch eine Quelle gedeckt sein. Danach werden Schuldendienst, Covenants und Szenarien geprüft. Höhere Verschuldung reduziert den anfänglichen Eigenkapitaleinsatz, erhöht aber die Empfindlichkeit gegenüber Ergebnisrückgang und Exitwert. Vertragliche Flexibilität kann in schlechten Zuständen wichtiger sein als der niedrigste anfängliche Zins.`,
'Ein Unternehmenskauf benötigt 100 Mio. € Kaufzahlung und 5 Mio. € Transaktionskosten. Banken stellen 60 Mio. € bereit; Verkäuferdarlehen 10 Mio. €.',[
'Gesamte Mittelverwendung=100+5=105 Mio. €.|Kosten gehören zum Kapitalbedarf, auch wenn sie den operativen Unternehmenswert nicht erhöhen.',
'Benötigtes Eigenkapital=105−60−10=35 Mio. €.|Sources und Uses müssen sich ausgleichen.',
'Bei Exitwert 110 und unverändert insgesamt 70 Schulden verbleiben 40 Mio. € Eigenkapital.|Der Zuwachs gegenüber 35 beträgt nur 5; der Vergleich mit einem vermeintlichen Einstiegseigenkapital von 30 würde die Kosten unterschlagen.'
],'Grundlage für LBO-Modelle, Finanzierung und Verhandlung wirtschaftlicher Rechte.','Zwischenzahlungen, Zinsen, Refinanzierung und Steuern fehlen in der einfachen Endwertrechnung. Earn-outs und bevorzugte Ansprüche benötigen eigene Szenarien.','Kapitalstruktur erklärt Hebelwirkung; Waterfalls bestimmen die Verteilung komplexer Anspruchsgruppen.'),
R('Ein Wertsteigerungsplan muss in operative Maßnahmen und Geld übersetzt werden',`Nach dem Kauf wird die Investmentthese zu einem umsetzbaren Plan mit Verantwortlichkeiten, Meilensteinen und Kennzahlen. Umsatzwachstum, Preisverbesserung, Produktivität und Working-Capital-Steuerung wirken auf unterschiedliche Weise. Eine angekündigte Kostensenkung kann zunächst Restrukturierungszahlungen verlangen und Kunden oder Qualität gefährden.

Beim Exit wird der Erfolg in operative Verbesserung, Schuldenabbau, Multipleänderung und weitere Kapitalflüsse zerlegt. So lässt sich erkennen, ob Rendite aus eigener Wertschöpfung oder einem günstigen Markt stammt. Exitwege wie strategischer Verkauf, Börsengang oder Sekundärverkauf besitzen unterschiedliche Voraussetzungen, Kosten und Zeitrisiken.`,
'Einstieg: EBITDA 10 Mio. €, Multiple 8, Enterprise Value 80, Schulden 50. Exit: EBITDA 12, Multiple weiterhin 8, Schulden 35; keine Zwischenzahlungen oder weiteren Einlagen.',[
'Anfangseigenkapital=80−50=30 Mio. €.|Dies ist die tatsächliche Eigentümerbasis vor weiteren Kostenannahmen.',
'Exit-Enterprise-Value=12×8=96; Exiteigenkapital=96−35=61 Mio. €.|Die operative Steigerung wird bei unveränderter Bewertung in Unternehmenswert übersetzt.',
'Eigenkapitalzuwachs=31, davon 16 durch höheres EBITDA bei konstantem Multiple und 15 durch geringere Schulden.|Die Zerlegung trennt operative Wertsteigerung und Mittelverwendung zur Entschuldung.'
],'Verwendet für Beteiligungssteuerung, Board-Reporting und Erklärung realisierter Renditen.','EBITDA-Wachstum kann durch teure Zukäufe entstehen. Zusätzliche Investitionen und Kapitalzuführungen müssen dann in die Renditezerlegung aufgenommen werden.','FCFF erklärt verfügbare Entschuldungsmittel; Attribution überträgt den Gedanken der Ergebniszerlegung.'),
R('Fondsverträge bestimmen, wann Kapital fließt und wer zuerst beteiligt wird',`Limited Partners sagen Kapital zu; der General Partner investiert und steuert den Fonds innerhalb vereinbarter Regeln. Der Vertrag regelt Investitionsperiode, Laufzeit, Gebühren, Kapitalabrufe, Ausschüttungsreihenfolge und Kontrollrechte. Unfunded Commitments sind potenzielle Verpflichtungen und keine frei verfügbare Reserve.

Ein Ausschüttungswasserfall kann zunächst Kapital zurückzahlen, danach eine Vorzugsrendite und anschließend Gewinne verteilen. Catch-up und Clawback verändern die endgültige Managerbeteiligung. Deal-by-deal- und Whole-fund-Strukturen unterscheiden sich besonders darin, wann Carry ausgezahlt wird und wie spätere Verluste berücksichtigt werden. Deshalb muss eine Gebührenrechnung dem konkreten Vertrag folgen.`,
'Vereinfachter Whole-fund-Wasserfall: Anleger zahlen zu Beginn 100 ein; nach genau einem Jahr werden 130 verteilt. Zuerst Kapitalrückzahlung, dann 8 Vorzugsrendite, danach verbleibender Gewinn 80/20 an Anleger/Manager, ohne Catch-up und weitere Gebühren.',[
'Nach Kapitalrückzahlung bleiben 130−100=30.|Der ursprüngliche Einsatz wird von Gewinn getrennt.',
'Nach Vorzugsrendite bleiben 30−8=22.|Die Hurdle erhält in diesem ausdrücklich vereinfachten Vertrag Vorrang.',
'Manager erhält 22×20 %=4,4; Anleger erhält 100+8+22×80 %=125,6.|Die Anleger-Einjahresrendite beträgt 25,6 %; mit Catch-up wäre die Verteilung anders.'
],'Benötigt für Vertragsvergleich, Liquiditätsplanung und Net-to-LP-Renditen.','Reale Hurdles können auf zeitgewichteten Kapitalständen beruhen und sich auf mehrere Jahre beziehen. Rechtliche Dokumente und Rückforderungsregeln sind maßgeblich.','Zeitwert und IRR berücksichtigen tatsächliche Zahlungsdaten; Ethik behandelt transparente Gebührenkommunikation.'),
R('Private Strategien benötigen unterschiedliche Erfolgs- und Verlustmodelle',`Buyouts fokussieren oft auf etablierte Cashflows und Kapitalstruktur, Venture auf unsichere Skalierung und Folgefinanzierung, Private Debt auf vertraglichen Schuldendienst und Recovery. Real Assets ergänzen Betriebs-, Bau-, Ressourcen- oder regulatorische Risiken. Eine gemeinsame Kategorie „privat“ erklärt diese wirtschaftlichen Unterschiede nicht.

Die passende Bewertungsmethode folgt den Cashflows und Rechten. Frühe Venture-Projekte benötigen Wahrscheinlichkeiten, Verwässerung und unterschiedliche Beteiligungsränge; ein besicherter Kredit benötigt vor allem Stressdeckung und Vertragsanalyse. Portfolioaufbau muss außerdem Kapitalabrufprofile und gemeinsame Konjunkturabhängigkeiten berücksichtigen. Diversifikation über Namen hilft wenig, wenn alle Anlagen dieselbe Refinanzierung benötigen.`,
'Ein vereinfachtes Venture-Portfolio investiert je 1 Mio. € in zehn Firmen. Sechs enden bei null, drei zahlen je 2 Mio. €, eine zahlt 12 Mio. €. Keine weiteren Einzahlungen oder Gebühren.',[
'Gesamteinsatz=10 Mio. €; Rückflüsse=6×0+3×2+12=18 Mio. €.|Erfolge und vollständige Ausfälle werden gemeinsam erfasst.',
'Bruttomultiple=18/10=1,8.|Ein hoher Anteil gescheiterter Firmen kann mit positivem Gesamtgewinn vereinbar sein.',
'Ohne den größten Gewinner lägen Rückflüsse nur bei 6 Mio. €.|Die Rendite hängt stark von wenigen Ausreißern ab; aus dem Multiple allein lässt sich ohne Zahlungszeitpunkte kein IRR bestimmen.'
],'Hilft bei Strategieauswahl, Portfolioaufbau und angemessenen Due-Diligence-Schwerpunkten.','Historische Gewinnerverteilungen sind unsicher; Folgekapital und Verwässerung können die Ergebnisse entscheidend verändern.','Wahrscheinlichkeitsverteilungen erklären Schiefe; Kreditrisiko betrachtet eine andere begrenzte Ertrags- und Verluststruktur.'),
R('Private-Fund-Performance benötigt Zeitmaß und Kapitalmaß',`DPI misst realisierte Ausschüttungen relativ zum eingezahlten Kapital. RVPI misst den verbleibenden bewerteten Anteil, TVPI ihre Summe. Diese Multiplikatoren zeigen, wie viel Kapital zurückkam beziehungsweise noch im Fonds bewertet ist, ohne allein die Dauer zu berücksichtigen.

IRR berücksichtigt Zahlungszeitpunkte, ist aber empfindlich gegenüber früheren Rückflüssen, Kreditlinien und dem angenommenen Restwert. Ein Public Market Equivalent stellt den Cashflows einen gewählten öffentlichen Markt gegenüber, wobei die konkrete PME-Methode offengelegt werden muss. Gute Beurteilung kombiniert Nettoergebnisse, Realisationsgrad, Risiko und Anreize statt einen einzelnen Spitzenwert auszuwählen.`,
'Ein Fonds hat kumuliert 100 Mio. € abgerufen, 60 ausgeschüttet und meldet Restwert 70. Für diese Kennzahlen wird eingezahltes Kapital als 100 definiert.',[
'DPI=60/100=0,6; RVPI=70/100=0,7.|Realisierte Rückzahlungen und noch bewertetes Vermögen werden getrennt.',
'TVPI=(60+70)/100=1,3=DPI+RVPI.|Der gemeldete Gesamtwert entspricht dem 1,3-Fachen des Einsatzes.',
'Fällt der Restwert um 30 %, wird er 49; neuer TVPI=(60+49)/100=1,09.|DPI bleibt 0,6, aber der noch unrealisierte Mehrwert schrumpft deutlich; ein IRR kann ohne Zahlungszeitpunkte nicht berechnet werden.'
],'Verwendet für Fondsvergleich, LP-Reporting und Monitoring von Restwertrisiken.','NAV ist eine Schätzung; Gebührenbasis und Fondsalter beeinflussen Vergleichbarkeit. Unterschiedliche PME-Varianten sind nicht austauschbar.','IRR erklärt Zeitabhängigkeit; Bewertungsqualität und GIPS unterstützen konsistente Darstellung.',{headers:['Kennzahl','Zähler','Frage'],rows:[['DPI','Ausschüttungen','Was wurde bereits zurückgezahlt?'],['RVPI','Restwert','Was ist noch bewertet?'],['TVPI','Ausschüttungen + Restwert','Welcher Gesamtmultiplikator wird ausgewiesen?']]} )
];
