const R=require('./schema.cjs');
module.exports=[
R('Beratung ist ein Prozess zur Lösung eines Kundenproblems',`Wealth Management verbindet Anlageentscheidungen mit Liquidität, Steuern, Vorsorge, Unternehmenseigentum und Familienzielen. Geschäftsmodelle unterscheiden sich in Leistungsumfang und Vergütung, etwa Honorar, volumenabhängige Gebühr oder produktbezogene Zahlungen. Die Vergütungsbasis beeinflusst mögliche Interessenkonflikte und sollte verständlich offengelegt werden.

Ein guter Prozess beginnt mit Zielen und Gesamtbilanz, prüft geeignete Alternativen und dokumentiert die Begründung. Produkte folgen daraus. Laufende Betreuung bedeutet außerdem, Veränderungen rechtzeitig zu erkennen und Entscheidungen nachvollziehbar zu aktualisieren. Der Kundennutzen umfasst neben Rendite auch vermiedene Fehler, Koordination und verlässliche Umsetzung, darf aber nicht mit unbelegten Renditeversprechen verkauft werden.`,
'Ein Kunde hat 2 Mio. € betreutes Vermögen. Angebot A kostet jährlich 0,8 % auf das Vermögen, Angebot B ein Honorar von 10.000 €. Vereinfachend werden identischer Leistungsumfang und keine weiteren Kosten angenommen.',[
'Jahreskosten A=2.000.000×0,008=16.000 €.|Volumenabhängige Vergütung steigt mit der betreuten Bemessungsgrundlage.',
'Kostenunterschied=16.000−10.000=6.000 € beziehungsweise 0,3 % des Vermögens.|Kosten werden in Geld und relativ zum Vermögen sichtbar gemacht.',
'Danach tatsächlichen Leistungsumfang, Produktkosten und Anreize vergleichen.|Der reine Preisvergleich ist nur unter der ausdrücklich angenommenen Leistungsgleichheit vollständig.'
],'Verwendet für Auswahl von Beratungsmodellen und transparente Mandatsvereinbarung.','Gebührenmodelle unterscheiden sich in enthaltenen Leistungen und Zusatzkosten. Ein niedriger Preis beweist weder gute Beratung noch passende Umsetzung.','Ethik behandelt Interessenkonflikte; IPS dokumentiert Ziele und Zuständigkeiten.'),
R('Das Kundenprofil umfasst wirtschaftliche und familiäre Entscheidungsrechte',`Eine Familie besitzt oft mehrere Vermögenstöpfe, Eigentümer und Zeithorizonte. Wer rechtlich verfügt, wer wirtschaftlich profitiert und wer Entscheidungen beeinflusst, muss nicht dieselbe Person sein. Ein vollständiges Profil erfasst deshalb neben Zahlen auch Ziele, Kommunikation und potenzielle Konflikte.

Family Governance legt Rollen, Entscheidungsregeln und Verfahren für Konflikte fest. Sie kann helfen, Unternehmenskontrolle, Liquiditätswünsche und Verantwortung zwischen Generationen zu koordinieren. Dabei dürfen gemeinsame Familienziele individuelle Eigentumsrechte und Bedürfnisse nicht überdecken. Ein klarer Prozess erleichtert Entscheidungen gerade dann, wenn Marktverluste oder Nachfolge emotional belasten.`,
'Eine Familie besitzt 10 Mio. € Vermögen: 7 Mio. € im Unternehmen, 2 Mio. € Immobilien und 1 Mio. € liquide Anlagen. Zwei Angehörige erwarten jeweils kurzfristig 600.000 € für eigene Vorhaben.',[
'Gesamter kurzfristiger Wunsch=1,2 Mio. €.|Beide Ansprüche werden gleichzeitig betrachtet statt einzeln zugesagt.',
'Sofort verfügbare Anlagen=1 Mio. €; Lücke=200.000 € vor Reservebedarf.|Hoher Gesamtvermögenswert bedeutet nicht ausreichend freie Liquidität.',
'Prioritäten, Rechtsansprüche, Zeitplan und Finanzierung gemeinsam klären.|Eine Governance-Regel kann die Verteilung strukturieren; der Verkauf eines Unternehmensanteils ist nicht automatisch kurzfristig möglich.'
],'Hilft bei Familienvermögen, Unternehmernachfolge und Koordination mehrerer Berater.','Rechtliche Eigentums- und Vertretungsfragen sind einzelfallabhängig. Eine gemeinsame Besprechung ersetzt keine eindeutige Dokumentation der Rechte.','Liquiditätsplanung trennt Wert und Verfügbarkeit; Nachfolge verbindet Kontrolle und wirtschaftliche Ansprüche.'),
R('Ruhestandsplanung ist ein Zahlungsstromproblem mit unsicherem Horizont',`Während der Erwerbsphase ergänzt Humankapital das Finanzvermögen: Künftiges Einkommen ermöglicht Sparen und Verlustausgleich. Im Ruhestand wird das Portfolio häufig zur Finanzierungsquelle. Lebenserwartung, Inflation, Gesundheitsausgaben und verlässliche Renteneinnahmen bestimmen die Anforderungen.

Sequence-of-Returns-Risiko entsteht, weil Entnahmen während früher Verluste mehr Anteile verbrauchen. Selbst gleiche Renditen in anderer Reihenfolge können deshalb zu unterschiedlichem Restvermögen führen. Eine tragfähige Planung untersucht mehrere Verläufe und mögliche Anpassungen von Ausgaben, Reserve oder Renteneinkommen. Eine feste Entnahmequote ist keine allgemeine Garantie.`,
'Anfangsvermögen 100. In jedem der zwei Jahre werden am Jahresende nach der Rendite 10 entnommen. Die Jahresrenditen sind einmal −20 % und einmal +20 %.',[
'Schlechte Reihenfolge zuerst: Jahr 1=100×0,8−10=70; Jahr 2=70×1,2−10=74.|Der frühe Verlust reduziert die Basis, auf der spätere Erholung wirkt.',
'Gute Reihenfolge zuerst: Jahr 1=100×1,2−10=110; Jahr 2=110×0,8−10=78.|Die gleiche Entnahme beansprucht zu Beginn einen kleineren Anteil des gestiegenen Vermögens.',
'Ohne Entnahmen enden beide Reihenfolgen bei 100×0,8×1,2=96.|Der Unterschied von 4 entsteht durch das Zusammenspiel von Zahlungszeitpunkten und Renditefolge.'
],'Verwendet für Entnahmepläne, Vorsorgeziele und Kommunikation von Ruhestandsrisiken.','Zwei Jahre illustrieren nur den Mechanismus. Steuern, Inflation, Langlebigkeit und flexible Ausgaben verlangen ein umfangreicheres Modell.','TWR und MWR unterscheiden zeitliche Anlageleistung und Zahlungsstromergebnis; Monte Carlo untersucht viele mögliche Verläufe.'),
R('Steuerbewusste Anlage bewertet den tatsächlich verfügbaren Nettozahlungsstrom',`Steuern können Ertragshöhe, Zahlungszeitpunkt und geeigneten Anlageort verändern. Laufend besteuerte Erträge verlieren einen Teil ihrer Wiederanlagebasis; aufgeschobene Besteuerung kann einen Zinseszinseffekt erhalten. Asset Location ordnet Anlagen den jeweils geeigneten Konten oder Strukturen zu, ohne die gewünschte Gesamtallokation aus dem Blick zu verlieren.

Grenzüberschreitende Vermögen bringen zusätzliche Fragen zu Steueransässigkeit, Quellensteuern, Abkommen, Meldepflichten und Währung mit sich. Die Analyse muss konkrete Rechtsräume und persönliche Verhältnisse berücksichtigen. Didaktische pauschale Steuersätze erklären Mechanismen, sind aber keine Darstellung eines bestimmten nationalen Rechts. Steueroptimierung sollte wirtschaftliche Diversifikation und Liquidität nicht unbemerkt verdrängen.`,
'Reines Rechenmodell: 100 werden für zehn Jahre zu 6 % angelegt. Einheitlicher Steuersatz 25 % auf Erträge. Variante A besteuert jährlich, Variante B erst den gesamten Gewinn am Ende; keine Freibeträge oder weiteren Regeln.',[
'A: jährliche Nettorendite=6 %×0,75=4,5 %; Endwert=100×1,045¹⁰≈155,30.|Früh gezahlte Steuer steht später nicht mehr zur Wiederanlage bereit.',
'B: Bruttoendwert=100×1,06¹⁰≈179,08; steuerpflichtiger Gewinn≈79,08.|Der ursprüngliche Einsatz wird im Modell nicht erneut besteuert.',
'Nettoendwert B≈159,31; Vorteil mit ungerundeten Endwerten≈4,02.|Allein die Verschiebung des Steuerzeitpunkts erzeugt unter diesen Annahmen zusätzliches Endvermögen.'
],'Hilft beim Verständnis von Steuerstundung, Anlagekonten und Nettovergleich von Strategien.','Tatsächliche Rechtsregeln, Verlustverrechnung und Steuersätze können die Rangfolge ändern. Konkrete grenzüberschreitende Umsetzung braucht aktuelle landesspezifische Prüfung.','Zeitwert erklärt Steuerstundung; Asset Allocation muss auf der Nachsteuerwirkung der Gesamtbilanz beruhen.'),
R('Unternehmervermögen verbindet Anlage-, Einkommens- und Kontrollrisiko',`Ein Unternehmer kann gleichzeitig Eigentümer, Geschäftsführer, Kreditbürge und Vermieter seines Betriebs sein. Dann reagieren mehrere Teile seiner wirtschaftlichen Bilanz auf denselben Geschäftserfolg. Eine kleine Streuung im Wertpapierdepot beseitigt diese Gesamtkonzentration nicht.

Mögliche Maßnahmen umfassen schrittweisen Verkauf, Aufbau unabhängiger Reserven, passende Versicherungen und unter bestimmten Bedingungen Derivate auf handelbare Positionen. Jede Maßnahme tauscht Chancen, Kosten, Kontrolle und Liquidität. Bei nicht börsennotierten Unternehmen existiert häufig kein passender direkter Hedge; ein Branchenindex kann nur einen Teil des Risikos abdecken.`,
'Gesamtvermögen 10 Mio. €: 8 Mio. € Firmenanteil und 2 Mio. € diversifizierte liquide Anlagen. Ein Stress senkt den Firmenwert um 40 %, die übrigen Anlagen um 10 %.',[
'Firmenverlust=8×40 %=3,2 Mio. €; übriger Verlust=2×10 %=0,2 Mio. €.|Die große Unternehmensposition dominiert den Schaden.',
'Gesamtverlust=3,4 Mio. € beziehungsweise 34 %.|Ein diversifiziertes Teildepot macht das Gesamtvermögen nicht automatisch breit gestreut.',
'Bei vorherigem Verkauf von 2 Mio. € Firmenanteilen zum angenommenen Ausgangswert und Umschichtung in dieselben liquiden Anlagen wäre der Szenarioverlust 6×40 %+4×10 %=2,8 Mio. €.|Die Konzentration sinkt; Steuern, Verkaufskosten und Kontrollfolgen sind zusätzlich zu prüfen.'
],'Relevant für Unternehmerberatung, Mitarbeiteraktien und Vorbereitung eines Unternehmensverkaufs.','Firmenwerte sind unsicher und Verkäufe möglicherweise eingeschränkt. Ein Markthedge schützt nicht vor individuellem Geschäfts-, Rechts- oder Schlüsselpersonenrisiko.','Korrelation betrachtet das Gesamtvermögen; Private-Unternehmensbewertung und Nachfolge bestimmen realistische Handlungsoptionen.'),
R('Nachfolge plant Vermögensübergang, Kontrolle und verfügbare Mittel gemeinsam',`Vermögenstransfer ist mehr als die Benennung eines Begünstigten. Er verbindet Eigentumsrechte, Entscheidungsfähigkeit, familiäre Ziele, Liquidität und mögliche Abgaben. Ein wertvolles, aber illiquides Unternehmen kann schwer gleichmäßig verteilt werden, ohne Kontrolle oder Betrieb zu beeinträchtigen.

Philanthropie ergänzt Ziele wie zeitnahe Wirkung, langfristige Förderung oder Einbindung der nächsten Generation. Die geeignete Struktur hängt vom Rechtsrahmen, Verwaltungskosten und gewünschter Kontrolle ab. Ein tragfähiger Plan dokumentiert Absichten, prüft belastende Szenarien und wird bei familiären oder rechtlichen Veränderungen aktualisiert. Dieses Kapitel erklärt den Entscheidungsprozess; konkrete Rechtsinstrumente werden landesspezifisch beurteilt.`,
'Ein vereinfachtes Vermögen besteht aus Unternehmen 6 Mio. € und liquiden Anlagen 2 Mio. €. Zwei Kinder sollen wirtschaftlich je 4 Mio. € erhalten; eines soll das gesamte Unternehmen übernehmen.',[
'Übernimmt Kind A das Unternehmen, liegt sein Ausgangswert 2 Mio. € über dem Ziel.|Kontrollwunsch und gleiche wirtschaftliche Verteilung passen nicht ohne zusätzliche Regelung zusammen.',
'Die vorhandenen 2 Mio. € Liquidität gehen an Kind B; zu dessen Ziel fehlen weitere 2 Mio. €.|Der Ausgleichsbedarf wird sichtbar, bevor eine ungeprüfte Zusage erfolgt.',
'Mögliche zeitliche Ausgleichszahlungen, Finanzierung oder andere Anteilsrechte prüfen und ihren Barwert berücksichtigen.|Eine Zahlung in vielen Jahren ist wirtschaftlich nicht gleich einer sofortigen Zahlung desselben Nominals.'
],'Genutzt für Nachfolgegespräche, Vermögensinventar und Abstimmung mit Rechts- und Steuerberatung.','Bewertungsunsicherheit, Pflichtansprüche, Steuern und Vertretungsregeln sind rechtsabhängig. Familienziele können sich ändern.','Zeitwert bewertet zeitversetzten Ausgleich; Family Governance ordnet Rechte und Konfliktlösungen.')
];
