const R=require('./schema.cjs');
module.exports=[
R('Diversifikation wirkt über gemeinsame Schwankungen',`Die erwartete Portfoliorendite ist der gewichtete Durchschnitt der Einzelrenditen. Das Portfoliorisiko ist dagegen nicht einfach der Durchschnitt der Volatilitäten, weil Gewinne und Verluste verschiedener Anlagen sich teilweise ausgleichen können. Die Kovarianz beschreibt, wie zwei Renditen gemeinsam vom Mittelwert abweichen; Korrelation normiert diesen Zusammenhang.

Diversifikation beseitigt kein allgemeines Marktrisiko und schützt nicht automatisch gegen Verluste. Sie reduziert vor allem Risiken, die nicht gleichzeitig eintreten. Viele ähnliche Wertpapiere können daher weniger diversifizieren als wenige wirtschaftlich unterschiedliche Positionen. In Krisen können Abhängigkeiten zunehmen; außerdem erfasst lineare Korrelation nicht jede gemeinsame Extrembewegung.`,
'Zwei Anlagen haben jeweils Volatilität 20 % und Gewicht 50 %. Ihre Korrelation beträgt zunächst null.',[
'Varianz=0,5²×0,2²+0,5²×0,2²+2×0,5×0,5×0,2×0,2×0=0,02.|Der gemeinsame Schwankungsterm verschwindet bei Korrelation null.',
'Portfoliovolatilität=√0,02=14,14 %.|Erst die Quadratwurzel übersetzt Varianz zurück in Renditeeinheiten.',
'Bei Korrelation 1 beträgt die Varianz 0,04 und die Volatilität 20 %.|Gleichgerichtete Schwankungen bieten bei diesen positiven Gewichten keinen Risikorückgang; bei Korrelation −1 wäre das idealisierte gleichgewichtete Portfolio schwankungsfrei.'
],'Grundlage für Allokation, Risikobudgets und Prüfung wirtschaftlicher Konzentration.','Volatilität unterscheidet nicht gute von schlechten Abweichungen. Schätzfehler, instabile Abhängigkeiten und nichtlineare Auszahlungen begrenzen die Aussage.','Multifaktormodelle identifizieren gemeinsame Ursachen; Stressanalyse untersucht Zustände, die Durchschnittskorrelationen verdecken.'),
R('Optimale Portfolios hängen von Zielen und Verlustempfindlichkeit ab',`In einem Mean-Variance-Nutzenmodell wird erwartete Rendite um einen Abschlag für Varianz vermindert. Der Risikoaversionsparameter beschreibt, wie stark zusätzliche Unsicherheit gegenüber zusätzlicher Rendite gewichtet wird. Er ist keine objektive Eigenschaft eines Wertpapiers und keine direkt beobachtbare Naturkonstante.

Bei einer Mischung aus sicherer Anlage und einem riskanten Portfolio hängt das optimale Gewicht von dessen erwarteter Überschussrendite, Varianz und der Risikoaversion ab. Diese Lösung ist ein Modellresultat. Reale Anleger besitzen Mindestziele, Schulden, Steuern und Grenzen für Fremdfinanzierung. Ein rechnerisch optimales Gewicht über 100 % ist daher zunächst ein Hinweis auf die Modellannahmen und keine unmittelbare Handlungsempfehlung.`,
'Sicherer Satz 3 %, erwartete Rendite des riskanten Portfolios 8 %, Volatilität 20 %, Risikoaversion A=4. Es gelten dezimale Renditen.',[
'Risikoprämie=0,08−0,03=0,05; Varianz=0,2²=0,04.|Erwarteter Mehrertrag und Risiko werden auf konsistenter Skala eingesetzt.',
'Optimales riskantes Gewicht y=0,05/(4×0,04)=0,3125.|Die erste Ableitung des Nutzens nach y wird null gesetzt.',
'Erwartete Mischrendite=3 %+0,3125×5 %=4,5625 %; Volatilität=0,3125×20 %=6,25 %.|Der Rest von 68,75 % liegt im Modell sicher; höhere Risikoaversion würde das riskante Gewicht verringern.'
],'Hilft, den Trade-off zwischen Rendite und Risiko transparent zu diskutieren.','Mean-Variance-Nutzen bildet Verlustschwellen, Schiefe und mehrperiodige Ziele nur begrenzt ab. Kleine Änderungen erwarteter Renditen können Gewichte stark bewegen.','Effiziente Grenze liefert mögliche Portfolios; IPS übersetzt abstrakte Präferenzen in konkrete Ziele und Grenzen.'),
R('Die effiziente Grenze enthält die besten verfügbaren Risiko-Rendite-Kombinationen',`Ein Portfolio ist im Mean-Variance-Sinn ineffizient, wenn ein anderes bei gleichem Risiko mehr erwartete Rendite oder bei gleicher Rendite weniger Risiko bietet. Die effiziente Grenze bildet die nicht dominierten Kombinationen oberhalb des Minimum-Varianz-Portfolios. Sie hängt vollständig von erwarteten Renditen, Kovarianzen und erlaubten Positionen ab.

Kann zusätzlich zum selben risikofreien Satz angelegt und geliehen werden, berührt die Kapitalallokationslinie die Grenze beim Tangentialportfolio mit maximaler Sharpe Ratio. Unter CAPM-Gleichgewichtsannahmen ist dies das Marktportfolio, und die Linie heißt Kapitalmarktlinie. Sie gilt für effiziente Kombinationen aus Markt und sicherer Anlage; einzelne Aktien liegen nicht allgemein auf ihr.`,
'Portfolio A erwartet 7 % bei 10 % Volatilität, B 8 % bei 10 %, C 9 % bei 15 %. Sicherer Satz 2 %. Es werden zunächst nur diese drei riskanten Kandidaten verglichen.',[
'A wird von B dominiert.|Bei gleichem Risiko bietet B mehr erwarteten Ertrag.',
'Sharpe B=(8−2)/10=0,60; Sharpe C=(9−2)/15≈0,467.|Für eine Mischung mit sicherer Anlage liefert B hier den steileren Renditeanstieg je Risikoeinheit.',
'Eine 50-%-Mischung aus B und sicherer Anlage erwartet 5 % bei 5 % Volatilität.|Diese Kombination liegt auf der Kapitalallokationslinie zu B; weitere Mischungen riskanter Anlagen könnten den Kandidatenvergleich noch verbessern.'
],'Verwendet für Portfoliokonstruktion und Diskussion effizienter Risikobudgets.','Optimierer können Schätzfehler in extreme Gewichte übersetzen. Finanzierung, Kosten und Anlagegrenzen verändern die erreichbare Grenze.','Sharpe Ratio misst die Steigung; CAPM unterscheidet Kapitalmarktlinie und Wertpapiermarktlinie.'),
R('Beta misst Marktempfindlichkeit, nicht das gesamte Risiko',`Im CAPM werden Anleger nur für systematisches Risiko vergütet, weil unter den Modellannahmen unternehmensspezifisches Risiko diversifiziert werden kann. Beta ist die Kovarianz mit dem Markt geteilt durch die Marktvarianz. Ein Beta von 1,2 bedeutet eine modellierte Marktempfindlichkeit von 1,2, nicht eine sichere tägliche Kursbewegung im selben Verhältnis.

Die Wertpapiermarktlinie verbindet erwartete Rendite und Beta. Anders als die Kapitalmarktlinie gilt sie im Modell auch für einzelne Wertpapiere und ineffiziente Portfolios. Eine Anlage mit hohem Gesamtrisiko kann dennoch niedriges Beta haben, wenn ihre Schwankungen kaum mit dem Markt zusammenhängen. Das macht sie für einen konzentrierten Anleger nicht automatisch ungefährlich.`,
'Risikofreier Satz 3 %, erwartete Marktrendite 8 %, Aktienbeta 1,2. Die Aktie erzielt in einem betrachteten Jahr tatsächlich 11 %, der Markt tatsächlich 8 %.',[
'Marktrisikoprämie=8−3=5 Prozentpunkte.|Nur die Marktrendite oberhalb der sicheren Alternative wird für Marktrisiko vergütet.',
'CAPM-Renditeforderung=3+1,2×5=9 %.|Das höhere Beta verlangt hier mehr Rendite als das Marktportfolio.',
'Realisiertes abnormales Ergebnis gegenüber dieser Einperiodenreferenz=11−9=2 Prozentpunkte.|Es ist nicht identisch mit der einfachen Marktdifferenz 11−8=3 Prozentpunkte und beweist allein noch keine dauerhafte Fähigkeit.'
],'Verwendet für Eigenkapitalkosten, systematische Risikoabsicherung und risikobereinigten Leistungsvergleich.','CAPM beruht auf starken Marktannahmen. Beta ist geschätzt und hängt von Zeitraum, Frequenz und gewähltem Marktproxy ab.','Alpha erweitert den Vergleich um die Frage nach nicht durch modellierte Risiken erklärter Rendite; Regression schätzt Beta.'),
R('Alpha ist der Renditeteil, den ein gewähltes Vergleichsmodell nicht erklärt',`Eine hohe Rendite kann aus einem allgemein guten Markt, gezielt übernommenen Risiken oder besonderen Anlageentscheidungen entstehen. Alpha versucht, den letzten Teil vom modellierten Risikoertrag zu trennen. Es ist immer relativ zu einem Modell und dessen Faktoren definiert. Ohne Angabe der Referenz ist die Aussage „der Fonds hat Alpha“ unvollständig.

Im Einfaktormodell wird die Überschussrendite des Fonds auf die Überschussrendite des Marktes regressiert: Fondsrendite minus risikofreier Satz entspricht Alpha plus Beta mal Marktrisikoprämie plus Restfehler. Beta misst die Empfindlichkeit; Alpha ist der geschätzte Achsenabschnitt. Der Restfehler beschreibt einzelne nicht erklärte Beobachtungen. Ein gutes Einzeljahr kann daher positive unerklärte Rendite zeigen, ohne dass das langfristige Alpha positiv ist.

Multifaktormodelle erweitern den Vergleich beispielsweise um Größe, Value, Momentum oder andere begründete Risikofaktoren. Ein Fonds kann scheinbares CAPM-Alpha verlieren, wenn seine Rendite durch solche Exponierungen erklärbar wird. Das ist keine nachträgliche Wegdefinition jeder Leistung, sondern eine präzisere Vergleichsfrage. Faktoren müssen wirtschaftlich begründet, investierbar beziehungsweise korrekt interpretiert und ohne nachträgliche Erfolgsselektion gewählt werden.

Die Arbitrage Pricing Theory verbindet unter ihren Annahmen erwartete Renditen mit mehreren gemeinsamen Risikotreibern. Sie benennt jedoch nicht automatisch die einzig richtigen Faktoren. Statistische Signifikanz, wirtschaftliche Größenordnung, Gebühren und Stabilität außerhalb der Schätzperiode entscheiden gemeinsam darüber, wie überzeugend ein Alpha-Befund ist.`,
'Ein Fonds erzielt 11 % netto. Der risikofreie Satz beträgt 3 %, die Marktrendite 8 %, sein vorab geschätztes Markt-Beta 1,2. Ein erweitertes Modell ordnet dem Fonds außerdem eine Value-Exponierung von 0,5 zu; die Value-Faktorprämie im Zeitraum beträgt 2 %.',[
'Überschussrendite des Fonds=11−3=8 %; Marktrisikoprämie=8−3=5 %.|Beide Renditen werden zunächst auf dieselbe sichere Alternative bezogen.',
'Marktbedingter Beitrag=1,2×5=6 %; Einfaktor-Referenz insgesamt=3+6=9 %.|Ein Marktvergleich ohne Beta würde das eingegangene zusätzliche Marktrisiko übersehen.',
'Einperiodige unerklärte Rendite im Einfaktormodell=11−9=2 Prozentpunkte.|Das ist eine realisierte Modellabweichung; erst eine Zeitreihenschätzung trennt systematisches Alpha und Zufallsrest.',
'Value-Beitrag=0,5×2=1 Prozentpunkt; erweiterte Referenz=10 %; Rest=1 Prozentpunkt.|Die Hälfte der vorherigen Abweichung wird nun durch den zusätzlichen Faktor erklärt.',
'Angenommen, eine monatliche Regression schätzt Alpha 0,10 % mit Standardfehler 0,08 %: t=1,25.|Das Ergebnis ist unter üblichen zweiseitigen 5-%-Tests mit ausreichend vielen Freiheitsgraden nicht signifikant; 0,10 % pro Monat darf zudem nicht als 0,10 % pro Jahr berichtet werden.'
],'Genutzt zur Managerbeurteilung, Strategieanalyse und Trennung von Risikoprämien und zusätzlicher Leistung.','Ein weggelassener Faktor, ungeeignete Benchmark, geglättete Bewertungen oder viele getestete Strategien können Alpha vortäuschen. Gebührenbasis, Periodenlänge und robust geschätzte Standardfehler müssen offengelegt werden.','Regression erklärt Achsenabschnitt und Standardfehler; Hypothesentests beurteilen Unsicherheit; Performance Appraisal ergänzt den statistischen Befund um Prozess und Investierbarkeit.',{headers:['Größe','Im Beispiel','Bedeutung'],rows:[['Gesamtrendite','11 %','Tatsächliches Nettoergebnis'],['Überschuss über risikofrei','8 Prozentpunkte','Vergleich mit 3 % sicherem Satz'],['Mehr als der Markt','3 Prozentpunkte','Unbereinigter Benchmarkvergleich'],['Abweichung vom CAPM','2 Prozentpunkte','Nach Markt-Beta-Anpassung'],['Abweichung vom Zweifaktormodell','1 Prozentpunkt','Nach Markt- und Value-Beitrag']]}),
R('Ein IPS übersetzt Lebens- oder Institutionsziele in Anlageentscheidungen',`Das Investment Policy Statement hält Ziele, Risikobudget, Restriktionen und Verantwortlichkeiten fest. Renditeziele entstehen aus Ausgaben, Verpflichtungen, Inflation und gewünschtem Vermögenserhalt. Sie sollten als realistisch prüfbare Anforderungen formuliert werden, nicht als losgelöster Wunsch nach maximalem Ertrag.

Liquidität, Horizont, Steuern, rechtliche Bedingungen und besondere Vorgaben beeinflussen die zulässige Umsetzung. Ein gutes IPS erklärt außerdem Rebalancing, Überwachung und Anlässe zur Überarbeitung. Dadurch verhindert es, dass kurzfristige Marktstimmung langfristige Entscheidungen ersetzt. Widersprechen sich Zielrendite und Risikotragfähigkeit, muss der Konflikt durch Sparen, Ausgaben, Horizont oder Ziele gelöst werden; mehr Risiko macht eine Anforderung nicht sicher erreichbar.`,
'Ein Vermögen von 1 Mio. € soll heute 30.000 € jährliche Ausgaben finanzieren und langfristig seine Kaufkraft erhalten. Erwartete Inflation 2 %, Kosten vereinfachend 0,5 % des Vermögens.',[
'Anfängliche Ausgabenquote=30.000/1.000.000=3 %.|Das reale Entnahmeziel wird zur Vermögensbasis in Beziehung gesetzt.',
'Grobe nominale Renditeanforderung≈3 %+2 %+0,5 %=5,5 %.|Die additive Näherung zeigt die Größenordnung vor genauer Zahlungszeitpunkt- und Steuerrechnung.',
'Ertragsschwankungen und ungünstige frühe Jahre separat simulieren.|Eine erwartete Rendite von 5,5 % garantiert keine dauerhaft tragfähige Entnahme, weil Verluste die spätere Kapitalbasis reduzieren.'
],'Grundlage für Beratung, Mandatsvergabe und disziplinierte Portfoliosteuerung.','Ein IPS ist nur nützlich, wenn Annahmen aktualisiert und Regeln tatsächlich angewendet werden. Starre Renditevorgaben können unerwünschte Risikosuche fördern.','Ruhestandsplanung vertieft Entnahmerisiko; Asset Allocation setzt die vereinbarten Ziele um.'),
R('Verlustbereitschaft und Verlusttragfähigkeit sind verschiedene Grenzen',`Risikobereitschaft beschreibt, wie ein Anleger Schwankungen emotional akzeptiert. Risikotragfähigkeit beschreibt, welche Verluste seine finanziellen Ziele und Verpflichtungen tatsächlich verkraften. Ein selbstbewusster Anleger mit bald fälliger Zahlung kann hohe Bereitschaft, aber geringe Tragfähigkeit besitzen.

Der Horizont ist nicht nur ein einzelnes Enddatum. Verschiedene Ziele benötigen Mittel zu unterschiedlichen Zeitpunkten. Kurzfristige Verpflichtungen sollten daher gemeinsam mit Notreserven und verlässlichen Einnahmen betrachtet werden. Ein langer Horizont kann Erholungszeit schaffen, macht riskante Anlagen aber nicht risikolos. Konzentration in Arbeitslohn, Unternehmen oder Wohnimmobilie beeinflusst die Gesamttragfähigkeit zusätzlich.`,
'Ein Haushalt besitzt 200.000 € liquide Anlagen. In einem Jahr werden sicher 80.000 € benötigt; zusätzlich sollen 20.000 € Reserve verfügbar bleiben.',[
'Kurzfristig gebundener Betrag=80.000+20.000=100.000 €.|Diese Mittel erfüllen konkrete Verpflichtungen und Pufferfunktionen.',
'Verbleibendes Kapital für längerfristige Risiken=100.000 €.|Die gesamte Vermögenssumme als risikofähig anzusehen würde die Zahlungsziele ignorieren.',
'Bei 40 % Verlust dieses riskanten Teils bleiben insgesamt 160.000 €.|Der reservierte Betrag ist unter der Annahme einer passenden sicheren Anlage weiter verfügbar; ein 40-%-Verlust des gesamten Vermögens hätte nur 120.000 € übrig gelassen.'
],'Verwendet für Geeignetheitsprüfung, Reserveplanung und Entscheidung über illiquide Anlagen.','Auch sichere Anlagen müssen zu Währung, Fälligkeit und Einlagensituation passen. Unerwartete Ausgaben und Einkommen können den Spielraum verändern.','ALM ordnet Vermögen Verpflichtungen zu; Behavioral Finance hilft bei emotionalen Reaktionen auf Verluste.'),
R('Strategische Allokation bestimmt den langfristigen Risikorahmen',`Strategische Asset Allocation legt langfristige Zielgewichte oder Risikobeiträge fest. Sie folgt Zielen, Verpflichtungen und langfristigen Kapitalmarkterwartungen. Taktische Allokation weicht zeitweise davon ab, etwa aufgrund einer begründeten Bewertung oder Konjunktureinschätzung. Diese Abweichungen benötigen ein eigenes Risikobudget und klare Rückkehrregeln.

Der Unterschied ist wichtig für Verantwortlichkeit: Ein Verlust aus bewusst höherem Aktiengewicht sollte nicht als schlechte Einzeltitelauswahl erklärt werden. Die Umsetzung muss außerdem Liquidität, Steuern und Kosten berücksichtigen. Strategische Gewichte sind keine ewigen Naturwerte; sie werden bei veränderten Zielen oder tragfähigen langfristigen Annahmen überprüft, nicht bei jeder Marktbewegung.`,
'Strategische Gewichte: 60 % Aktien, 40 % Anleihen. Taktisch werden 70/30 gehalten. Im Zeitraum erzielen Aktien 10 %, Anleihen 2 %; keine Kosten.',[
'Strategische Rendite=0,6×10 %+0,4×2 %=6,8 %.|Dies ist die regelbasierte Vergleichsentscheidung.',
'Tatsächliche Allokationsrendite=0,7×10 %+0,3×2 %=7,6 %.|Das höhere Aktiengewicht verstärkt im Beispiel den Ertrag.',
'Taktischer Beitrag=7,6−6,8=0,8 Prozentpunkte.|Äquivalent: Übergewicht 10 %×Renditedifferenz 8 %=0,8 Prozentpunkte; bei schwachen Aktien kann das Vorzeichen umkehren.'
],'Genutzt für Portfolioaufbau, Entscheidungsmandate und Attribution.','Prognosefehler und Handelskosten können taktischen Mehrwert aufzehren. Unklare Grenzen verwandeln langfristige Allokation in ungeplantes Market Timing.','Kapitalmarkterwartungen liefern Annahmen; Attribution misst die Wirkung der Gewichtsentscheidung.'),
R('Aktiv und passiv beschreiben den Prozess, nicht automatisch die Qualität',`Passive Umsetzung versucht, eine festgelegte Benchmark möglichst genau und kostengünstig abzubilden. Aktives Management nimmt bewusste Abweichungen vor, um ein anderes Ergebnis zu erzielen. Bereits die Benchmarkwahl ist eine Anlageentscheidung: Markt, Gewichtung, Ausschlüsse und Rebalancing bestimmen die Risiken.

Bei ETFs und Fonds zählen neben Gebühren auch Tracking Difference, Tracking Error, Steuern, Handelsspread, Replikation und Wertpapierleihe. Tracking Difference ist die tatsächliche Renditedifferenz; Tracking Error die Schwankung dieser aktiven Renditen. Ein Fonds kann seine Benchmark sehr gleichmäßig um die Kosten unterschreiten und dabei geringen Tracking Error haben.`,
'Ein Index erzielt 8 %. Fonds A erzielt 7,8 %, Fonds B 7,4 %. A verlangt 0,15 % ausgewiesene laufende Kosten, B 0,30 %; weitere Effekte sind möglich.',[
'Tracking Difference A=7,8−8=−0,2 Prozentpunkte; B=−0,6.|Die tatsächliche Abweichung erfasst mehr als nur die ausgewiesene Gebühr.',
'Nicht allein aus diesen zwei Jahreszahlen auf Tracking Error schließen.|Für dessen Berechnung wird eine Zeitreihe aktiver Renditen benötigt.',
'Bei 100.000 € Anfangskapital beträgt der Ergebnisunterschied zwischen A und B 400 €.|Kosten und Umsetzung wirken direkt auf Anlegervermögen; Steuer- und Handelsbedingungen können den individuellen Vergleich verändern.'
],'Hilft bei Fondsauswahl und Entscheidung über aktive Risikobudgets.','Historische Tracking Difference kann durch einmalige Effekte geprägt sein. Indexnähe ist nur sinnvoll, wenn der Index zum Anlageziel passt.','Markteffizienz motiviert Kostenbewusstsein; Performance Appraisal prüft aktive Ergebnisse nach Risiko und Gebühren.'),
R('Rebalancing hält das gewünschte Risiko trotz Marktbewegungen aufrecht',`Wenn Anlagen unterschiedlich steigen, ändern sich ihre Portfoliogewichte auch ohne Handel. Rebalancing führt das Portfolio zu vereinbarten Gewichten oder Bändern zurück. Der primäre Zweck ist Risikokontrolle; ein sicherer Zusatzgewinn folgt daraus nicht.

Kalenderregeln prüfen zu festen Terminen, Bandregeln reagieren auf ausreichend große Abweichungen. Häufige Anpassung hält Gewichte enger, verursacht aber mehr Kosten und möglicherweise Steuern. Neue Einzahlungen oder Entnahmen können genutzt werden, um Abweichungen mit weniger Verkäufen zu korrigieren. Bei illiquiden Anlagen muss der erreichbare Zielzustand gemeinsam mit Kapitalabrufen und Handelsfristen geplant werden.`,
'Ein Portfolio startet mit 60 € Aktien und 40 € Anleihen. Aktien steigen um 20 %, Anleihen bleiben unverändert. Zielgewicht bleibt 60/40.',[
'Neue Werte: Aktien 72, Anleihen 40, Gesamt 112.|Unterschiedliche Renditen verändern zunächst die Vermögensanteile.',
'Aktiengewicht=72/112=64,29 %; gewünschter Aktienwert=112×0,60=67,20.|Die Zielquote wird auf das aktuelle Gesamtvermögen angewendet.',
'4,80 Aktien verkaufen und 4,80 Anleihen kaufen.|Danach stehen 67,20 und 44,80 im Portfolio; bei Kosten müsste der geringere Gesamtwert berücksichtigt werden.'
],'Verwendet zur disziplinierten Risikosteuerung und Umsetzung von IPS-Regeln.','Rebalancing kann in Trendphasen Rendite kosten. Steuern, Spreads und Mindesthandelsgrößen beeinflussen sinnvolle Bänder.','Asset Allocation definiert das Ziel; Transaktionskostenanalyse beurteilt dessen effiziente Umsetzung.'),
R('Verhaltensfehler entstehen oft aus an sich nützlichen Denkabkürzungen',`Menschen vereinfachen komplexe Entscheidungen mit Heuristiken. Diese können systematisch irreführen: Anchoring hält an einer auffälligen Ausgangszahl fest, Confirmation Bias bevorzugt bestätigende Informationen, Overconfidence unterschätzt Unsicherheit. Verlustaversion gewichtet Verluste relativ zu einem Bezugspunkt besonders stark.

Kognitive Fehler lassen sich häufig durch bessere Daten und Entscheidungsstrukturen abschwächen; emotionale Reaktionen können zusätzlich eine tragfähige Portfolioausgestaltung erfordern. Eine Diagnose sollte konkrete Entscheidungen untersuchen und nicht jede Abweichung vom Modell als irrational abstempeln. Vorab definierte Kriterien, Gegenargumente und ein Entscheidungsjournal machen spätere Überprüfung leichter.`,
'Eine Aktie wurde zu 100 € gekauft und steht bei 70 €. Neue, unabhängig geprüfte Informationen legen einen Wertbereich von 60 bis 65 € nahe. Der Anleger möchte erst bei 100 verkaufen.',[
'Der historische Kaufpreis bestimmt den bereits entstandenen Verlust, aber nicht den heutigen Unternehmenswert.|Das Festhalten an 100 kann ein Anker und Ausdruck des Wunsches sein, keinen Verlust zu realisieren.',
'Die relevante Entscheidung vergleicht heutigen Verkaufserlös 70 mit künftigem Risiko und verfügbaren Alternativen.|Vergangene Ausgaben sind für diese Vorwärtsentscheidung grundsätzlich versunkene Kosten; Steuern können separat relevant sein.',
'Vorab prüfen: Würde die Position mit heutigem Wissen zu 70 neu gekauft werden?|Diese Gegenfrage hilft, Besitz und Kaufentscheidung konsistent zu beurteilen, ersetzt aber keine Bewertung.'
],'Nützlich für Research, Beratung, Risikokommunikation und disziplinierte Umsetzung.','Ein beobachtetes Verhalten kann mehrere vernünftige oder psychologische Gründe haben. Etiketten allein lösen das Problem nicht.','Investmentthese definiert Gegenbelege; Rebalancing und IPS reduzieren spontane Entscheidungen unter Stress.'),
R('VaR markiert eine Verlustschwelle; Expected Shortfall betrachtet den Bereich dahinter',`Value at Risk ist ein Quantil der Verlustverteilung für einen festen Horizont und ein Konfidenzniveau. Ein 95-%-VaR von 10 bedeutet: Im Modell liegt der Verlust mit 95 % Wahrscheinlichkeit höchstens bei 10; in den übrigen 5 % kann er höher sein. Er sagt nicht, dass 10 der maximal mögliche Verlust ist.

Expected Shortfall betrachtet den durchschnittlichen Verlust im schlechtesten angegebenen Anteil der Verteilung, mit passender Behandlung von Quantilsgrenzen. Er reagiert damit auf die Schwere extremer Verluste, die der VaR ausblendet. Beide Größen hängen von Daten, Modell, Horizont und Liquiditätsannahmen ab. Ein exakt berechneter Modellwert kann wirtschaftlich unzuverlässig sein, wenn seltene Krisen fehlen.`,
'Ein didaktisches Modell enthält 100 gleich wahrscheinliche Szenarien. Die 95 kleineren Verluste liegen höchstens bei 10; die fünf größten Verluste sind 12, 14, 16, 20 und 38. Der 95. sortierte Verlust ist genau 10.',[
'95-%-VaR nach der hier verwendeten empirischen Quantildefinition=10.|Die Schwelle umfasst die ersten 95 von 100 Szenarien.',
'95-%-Expected-Shortfall=(12+14+16+20+38)/5=20.|Die fünf schlechtesten Szenarien zeigen den durchschnittlichen Schaden jenseits der Schwelle.',
'Wird 38 durch 88 ersetzt, bleibt VaR 10, aber ES steigt auf 30.|Das Beispiel zeigt, warum ein unveränderter VaR eine Verschärfung extremer Verluste übersehen kann.'
],'Eingesetzt für Risikolimits, Kapitalplanung und Vergleich von Verlustprofilen.','Empirische Quantilkonventionen können abweichen. Historische Daten enthalten möglicherweise keine relevanten Extremereignisse; Liquidationskosten müssen ergänzt werden.','Wahrscheinlichkeitsverteilungen erklären Quantile; Stressszenarien ergänzen Ereignisse außerhalb der Stichprobe.',{headers:['Kennzahl','Fragestellung','Keine Aussage über'],rows:[['VaR','Wo liegt die Verlustschwelle?','Maximalverlust'],['Expected Shortfall','Wie groß sind die schlechtesten Verluste im Mittel?','Sichere Obergrenze'],['Stresstest','Was passiert in einem bestimmten Szenario?','Automatisch bekannte Eintrittswahrscheinlichkeit']]}),
R('Stressanalyse beginnt mit einem wirtschaftlichen Mechanismus',`Ein Stresstest verändert Risikotreiber deutlich und berechnet ihre gemeinsamen Auswirkungen. Historische Szenarien wiederholen beobachtete Schocks; hypothetische Szenarien untersuchen neue Kombinationen. Reverse Stress Testing beginnt mit einem nicht tragbaren Ergebnis und fragt, welche plausiblen Entwicklungen es auslösen könnten.

Gute Szenarien verbinden Marktpreise mit Liquidität, Gegenparteien und Verhalten. Steigende Zinsen können gleichzeitig Anleihekurse senken, Finanzierung verteuern und Sicherheitenbedarf erhöhen. Eine reine Addition unabhängiger Einzelschocks übersieht solche Rückkopplungen. Die Szenariorechnung ist eine bedingte Aussage: Wenn die Annahmen eintreten, ergibt sich der modellierte Effekt; daraus folgt noch keine präzise Wahrscheinlichkeit.`,
'Ein Portfolio enthält 600.000 € Aktien und 400.000 € Anleihen mit Modified Duration 5. Szenario: Aktien −25 %, paralleler Zinsanstieg 1 Prozentpunkt; Konvexität und Spreads werden zunächst ignoriert.',[
'Aktienverlust=600.000×25 %=150.000 €.|Der angenommene Marktschock wird auf die aktuelle Exponierung angewendet.',
'Anleiheänderung≈−5×0,01×400.000=−20.000 €.|Duration liefert eine erste Näherung für den Zinsschock.',
'Gesamtverlust≈170.000 € beziehungsweise 17 %.|Anschließend sind Spreadverluste, Liquidationskosten und mögliche Margin Calls zu ergänzen; sie sind in dieser Zahl nicht bereits enthalten.'
],'Hilft bei Verlustbudgets, Krisenvorbereitung und Kommunikation nichtlinearer Risiken.','Unplausible Kombinationen oder zu milde Schocks können falsche Sicherheit erzeugen. Sensitivitätsnäherungen werden bei großen Bewegungen ungenau.','Duration und Greeks liefern erste Effekte; Liquiditätsplanung untersucht, ob das Portfolio den Stress durchhalten kann.'),
R('Eine Performancekennzahl ist nur sinnvoll, wenn sie zur Frage passt',`Die Sharpe Ratio vergleicht Überschussrendite mit Gesamtschwankung. Die Information Ratio vergleicht aktive Rendite mit Tracking Error relativ zu einer Benchmark. Alpha berücksichtigt ein gewähltes Risikomodell. Diese Kennzahlen beantworten verschiedene Fragen und können deshalb denselben Fonds unterschiedlich einordnen.

Benchmarks müssen zur Strategie passen und möglichst vorab feststehen. Nachhaltigkeitsziele benötigen zusätzlich eigene messbare Kriterien: Ein guter Renditewert beweist weder geringere Emissionen noch positiven realwirtschaftlichen Einfluss. Finanzielle Leistung, Zielerreichung und Risiko sollten getrennt berichtet und anschließend gemeinsam beurteilt werden. Gebühren, Währung, Zeitraum und Renditemethode müssen konsistent sein.`,
'Portfolio 9 %, sicherer Satz 3 %, Portfoliovolatilität 12 %, Benchmark 8 %, Tracking Error 4 %. Alle Größen beziehen sich auf denselben Jahresmaßstab.',[
'Sharpe Ratio=(9−3)/12=0,50.|Sie bewertet Mehrertrag je Einheit des gesamten gemessenen Risikos.',
'Information Ratio=(9−8)/4=0,25.|Sie bewertet den aktiven Mehrertrag je Einheit der Abweichung zur Benchmark.',
'Ein Nachhaltigkeitsziel wie eine festgelegte Emissionsintensität separat messen.|Weder 0,50 noch 0,25 enthält diese Information; eine Veränderung kann außerdem durch Portfolioverkauf statt reale Emissionssenkung entstehen.'
],'Genutzt für Portfoliovergleich, Reporting und Kontrolle mehrerer Mandatsziele.','Nichtnormale Renditen und kurze Zeiträume erschweren Interpretation. Annualisierung setzt Annahmen über zeitliche Abhängigkeiten voraus.','Alpha erklärt Modellbereinigung; Attribution erklärt Ergebnisquellen; GIPS behandelt konsistente Leistungsdarstellung.')
];
