const R=require('./schema.cjs');
module.exports=[
R('Ein gutes Finanzmodell macht Annahmen und Fehler sichtbar',`Ein Tabellenmodell übersetzt wirtschaftliche Zusammenhänge in eine überprüfbare Struktur. Eingaben, Berechnungen und Ergebnisse sollten unterscheidbar sein. Zeitachsen, Einheiten, Vorzeichen und konsistente Formelbezüge sind wichtiger als dekorative Komplexität. Wiederholte Konstanten in Formeln erschweren spätere Änderungen und begünstigen Widersprüche.

Plausibilitätsprüfungen nutzen wirtschaftliche Identitäten: Die Bilanz muss aufgehen, Sources und Uses müssen übereinstimmen, Cashflow und Geldbestand müssen sich überleiten lassen. Sensitivitäten sollten sich in nachvollziehbarer Richtung bewegen. Ein Modell kann technisch fehlerfrei rechnen und trotzdem auf falschen Definitionen beruhen; deshalb werden sowohl Rechenwerk als auch ökonomische Logik geprüft.`,
'Ein Jahresmodell startet mit 20 Geldbestand, zeigt CFO +12, Investitionscashflow −8 und Finanzierungscashflow −5. Die Bilanz weist am Ende versehentlich 24 aus.',[
'Erwarteter Endbestand=20+12−8−5=19.|Alle zahlungswirksamen Veränderungen werden mit eindeutigem Vorzeichen übergeleitet.',
'Kontrolldifferenz=24−19=5.|Die Abweichung zeigt einen Verknüpfungs- oder Eingabefehler; sie wird nicht durch eine unbegründete Ausgleichsbuchung versteckt.',
'Quellen der 5 prüfen, etwa doppelt erfasste Finanzierung oder falschen Bilanzbezug.|Die Identität lokalisiert das Problem, entscheidet aber noch nicht, welche Eingabe falsch ist.'
],'Verwendet für DCF, Budgetierung, LBO und Anlageplanung.','Eine aufgegangene Bilanz beweist nicht die Richtigkeit aller Annahmen. Harte Ausgleichspositionen können Fehler verdecken.','Cashflowrechnung liefert die Kontrollidentität; Szenarioanalyse prüft Verhalten bei veränderten Eingaben.'),
R('Finanzdaten brauchen eine explizite Bedeutung, bevor Code sie verarbeitet',`Eine Kursreihe besteht nicht nur aus Zahlen. Datum, Zeitzone, Währung, Handelskalender und Behandlung von Dividenden oder Splits bestimmen, welche Rendite berechnet wird. Fehlende Werte können Handelsunterbrechung, Datenfehler oder unterschiedliche Börsentage bedeuten. Eine pauschale Ersetzung durch null verändert den wirtschaftlichen Inhalt.

Ein reproduzierbarer Analyseprozess dokumentiert Herkunft, Transformationen und Stichtagswissen. Bei Backtests dürfen Informationen erst ab ihrem tatsächlichen Verfügbarkeitszeitpunkt verwendet werden. Trainings- und Testzeiträume werden zeitlich sauber getrennt; Datenbereinigung und Parameterschätzung dürfen zukünftige Informationen nicht vorwegnehmen. Code macht einen Fehler schnell wiederholbar, aber nicht richtig.`,
'Eine Aktie notiert vor einem 2:1-Split bei 100 € und danach bei 50 €. Es gibt keine wirtschaftliche Preisänderung und keine Dividende.',[
'Unbereinigte Kursrendite=50/100−1=−50 %.|Die naive Rechnung verwechselt eine Stückelungsänderung mit Vermögensverlust.',
'Nach dem Split besitzt ein Anleger statt einer Aktie zwei zu je 50 €; Gesamtwert bleibt 100 €.|Die Stückzahl ist Teil der wirtschaftlichen Position.',
'Mit konsistent splitbereinigter Historie, etwa altem Vergleichskurs 50 €, ergibt sich 50/50−1=0 %.|Bereinigungsmethode und Datenanbieterdefinition müssen bekannt sein; Dividendenerträge verlangen zusätzlich eine passende Total-Return-Behandlung.'
],'Grundlage für Python-Analysen, Backtests und automatisiertes Reporting.','Bereinigte Daten können nachträglich revidiert werden. Survivorship Bias und verzögerte Veröffentlichung bleiben auch bei sauberem Code mögliche Probleme.','Renditedefinitionen und Indexkonstruktion erklären die Zielgröße; Statistik behandelt Datenlecks und Stichprobenauswahl.'),
R('Research verbindet Quellenkritik mit einer überprüfbaren Entscheidung',`Research beginnt mit einer klaren Frage, etwa ob ein Unternehmen den im Kurs enthaltenen Wachstumspfad finanzieren kann. Primärquellen wie Berichte, Verträge und offizielle Daten liefern die Ausgangsbasis. Sekundäre Einschätzungen helfen bei Interpretation, sollten aber nicht unbemerkt als gesicherte Fakten übernommen werden.

Ein belastbarer Prozess trennt Datenerhebung, Normalisierung, Prognose und Bewertung. Gegenhypothesen prüfen, ob dieselben Beobachtungen anders erklärbar sind. Änderungen der These werden mit Datum und Ursache dokumentiert. So wird später sichtbar, ob ein Ergebnis aus einer guten ursprünglichen Einschätzung, einer sinnvollen Aktualisierung oder bloß Glück entstand.`,
'Ein Unternehmen meldet 20 % Umsatzwachstum: 12 Prozentpunkte stammen aus einer Übernahme, 5 aus Währung und 3 aus organischer Entwicklung. Für dieses Beispiel ist die additive Zerlegung ausdrücklich vorgegeben.',[
'Bereinigtes organisches Wachstum=20−12−5=3 %.|Die berichtete Gesamtrate wird nach wirtschaftlichen Ursachen getrennt.',
'Eine Prognose von dauerhaft 20 % benötigt weitere Übernahmen, entsprechende Finanzierung oder eine andere operative Begründung.|Die historische Schlagzeile allein trägt diese Annahme nicht.',
'Kaufpreis der Übernahme, Margen und Kapitalbindung in die Bewertung aufnehmen.|Umsatzwachstum schafft nur dann Wert, wenn der Nutzen den zusätzlichen Kapitaleinsatz und dessen Kosten rechtfertigt.'
],'Verwendet für Aktienresearch, Kreditprüfung und makroökonomische Investmentthesen.','Veröffentlichte Wachstumsbrücken sind nicht immer additiv und können wechselnde Definitionen verwenden. Quellen und Bezugsbasis müssen dokumentiert werden.','Bilanzanalyse normalisiert Zahlen; Unternehmensbewertung übersetzt die Prognose in Wert.'),
R('Eine gute Grafik macht die entscheidende Vergleichsfrage sichtbar',`Visualisierung soll Zusammenhänge erkennbar machen, ohne Größenordnung oder Unsicherheit zu verzerren. Zeitreihen eignen sich für Entwicklungen, Balken für diskrete Vergleiche, Streudiagramme für Zusammenhänge und Tabellen für präzise Zahlen. Eine logarithmische Achse zeigt proportionale Veränderungen anders als eine lineare Achse und muss erkennbar beschriftet sein.

Entscheidungskommunikation verbindet Ergebnis, Mechanismus und Konsequenz. Eine einzelne Punktprognose sollte nicht dieselbe Gewissheit suggerieren wie ein beobachteter Zahlungsbetrag. Bandbreiten und Szenarien können Unsicherheit sichtbar machen. Farben, Achsen und Beschriftungen sollten auch ohne mündliche Erklärung eindeutig sein und nicht nur die gewünschte Geschichte hervorheben.`,
'Zwei Fonds erzielen im Jahr 5,0 % und 5,5 %. Eine Balkengrafik beginnt ihre Achse bei 4,9 % statt bei null.',[
'Tatsächliche Differenz=0,5 Prozentpunkte; relativ zu 5,0 % entspricht sie 10 % mehr Rendite, nicht 10 % mehr Endvermögen.|Die Bezugsgröße muss präzise genannt werden.',
'Bei 10.000 € Anfangskapital lauten Endwerte 10.500 und 10.550 €; Unterschied 50 €.|Die Geldwirkung hilft, die praktische Größenordnung einzuordnen.',
'Eine stark abgeschnittene Balkenachse lässt die Balkenlängen im Verhältnis 0,1 zu 0,6 erscheinen.|Für Balken ist ein Nullbeginn meist sinnvoll; eine vergrößerte Detailansicht muss die Achsenwahl und tatsächlichen Werte klar zeigen.'
],'Genutzt für Investmentberichte, Kundengespräche und eigene Modellkontrolle.','Eine Grafik beweist keine Kausalität. Ausgewählte Zeiträume, verdeckte Gebühren oder fehlende Vergleichsreihen können trotz korrekter Zahlen irreführen.','Ethik fordert faire Darstellung; Statistik erklärt Unsicherheit und Zusammenhang versus Ursache.'),
R('Einheitenkontrolle verhindert viele Fehler vor dem eigentlichen Rechnen',`Formeln verbinden Größen mit bestimmten Dimensionen. Renditen brauchen eine Periodenangabe, Zinsen eine Verzinsungskonvention und Geldgrößen eine Währung beziehungsweise Skalierung. Basispunkte und Prozentpunkte müssen vor dem Einsetzen in Dezimalwerte umgerechnet werden. Ein formal plausibles Ergebnis kann um den Faktor 100 oder 10.000 falsch sein.

Beim Finanzrechner bestimmen Vorzeichen die Richtung des Zahlungsstroms; Einzahlungen und Auszahlungen dürfen nicht beide gleich signiert werden. Periodenzahl und Periodenzins müssen übereinstimmen. Eine gute Routine zeichnet zuerst die Zeitachse, definiert Symbole und schätzt die Größenordnung, bevor die genaue Eingabe erfolgt.`,
'Ein Anleiheportfolio von 2 Mio. € hat Modified Duration 4. Die Rendite steigt um 25 Basispunkte.',[
'25 Basispunkte=0,25 Prozentpunkte=0,0025 als Dezimaländerung.|Die Durationformel verlangt die Dezimaländerung des Renditesatzes.',
'Relative Preisänderung≈−4×0,0025=−0,01=−1 %.|Das Vorzeichen entspricht der inversen Preis-Zins-Beziehung.',
'Geldänderung≈2.000.000×(−0,01)=−20.000 €.|Ein Ergebnis von −2 Mio. € würde bereits durch die grobe Größenordnung auf eine fehlerhafte Prozentumrechnung hinweisen.'
],'Hilft bei Klausuren, Tabellenmodellen und Überprüfung von Rechnerausgaben.','Näherungsformeln bleiben trotz korrekter Einheiten Näherungen. Bei Zinsen sind zusätzlich Periodizität und stetige versus diskrete Verzinsung zu prüfen.','Duration liefert den Sachzusammenhang; Zeitwert erklärt Periodenabgleich und Vorzeichen.'),
R('Fallvignetten prüfen die Auswahl des richtigen Zusammenhangs',`Eine Multiple-Choice-Aufgabe erfordert mehr als Wiedererkennen einer Formel. Zuerst wird die konkrete Zielgröße bestimmt: heutiger Wert, erwartete Rendite, realisierte Rendite oder risikobereinigte Abweichung. Dann werden relevante Daten und Annahmen ausgewählt. Zusätzliche Angaben können bewusst andere, ähnlich aussehende Rechnungen ermöglichen.

Bei vernetzten Fällen müssen die Teilaufgaben auf konsistenten Ausgangsdaten beruhen. Ein Lösungsweg sollte unabhängig von den Antwortoptionen begonnen werden, um Anker zu vermeiden. Falsche Optionen sind anschließend Lernmaterial: Sie zeigen häufig einen typischen Nenner-, Vorzeichen- oder Timingfehler. Raten nach Zahlenähnlichkeit trainiert diesen Zusammenhang nicht.`,
'Eine Aktie kostet 50 €, zahlt am Jahresende 2 € Dividende und wird dann für 53 € verkauft. Gesucht ist die einfache Gesamtrendite. Optionen: 4 %, 6 % oder 10 %.',[
'Kursgewinn=53−50=3 €.|Dies ist nur ein Teil des Anlageertrags.',
'Gesamter Ertrag=3+2=5 €; Rendite=5/50=10 %.|Kursänderung und Ausschüttung werden auf den Anfangseinsatz bezogen.',
'4 % wäre nur Dividendenrendite, 6 % nur Kursrendite.|Das Erklären der falschen Optionen zeigt genau, welcher Bestandteil jeweils ausgelassen wurde.'
],'Verwendet für systematisches Aufgabentraining und Diagnose wiederkehrender Fehler.','Die Aufgaben hier sind eigene Lernbeispiele und keine nachgebildeten vertraulichen Prüfungsfragen. Reale Aufgaben können zusätzliche Steuer- oder Zahlungszeitpunktannahmen verlangen.','Renditemaße definieren die Zielgröße; Formeltraining sichert Einheiten und Bezugsbasis.'),
R('Eine schriftliche Antwort braucht eine Entscheidung mit kausaler Begründung',`Aufgabenwörter wie berechnen, vergleichen, begründen oder empfehlen verlangen unterschiedliche Leistungen. Eine Berechnung braucht Formel, eingesetzte Werte und Ergebnis. Eine Empfehlung braucht eine klare Wahl, einen fallspezifischen Grund und gegebenenfalls eine relevante Grenze. Allgemeine Lehrbuchsätze ohne Bezug zum Fall beantworten die Entscheidungsfrage oft nicht.

Präzision bedeutet, den entscheidenden Mechanismus sichtbar zu machen. Beispielsweise begründet „lange Duration“ allein noch keine Maßnahme; erst der Bezug zur Verpflichtungsduration und zum gewünschten Überschussrisiko erklärt die Richtung. Kurze vollständige Argumentationsketten sind häufig verständlicher als viele unverbundene Fachbegriffe.`,
'Ein Pensionsplan hat Vermögensduration 4 und Verpflichtungsduration 9. Die Aufgabe verlangt eine Maßnahme, um das Zinsrisiko des Überschusses bei fallenden Zinsen zu reduzieren.',[
'Problem benennen: Verpflichtungen steigen bei einem Zinsrückgang empfindlicher als das Vermögen.|Der relevante Verlustmaßstab ist die Deckung beziehungsweise der Überschuss.',
'Maßnahme: Vermögens-Zinssensitivität passend erhöhen, etwa durch geeignete längere Anleihen oder ein Overlay.|Die Richtung folgt aus dem Sensitivitätsdefizit, nicht aus einer allgemeinen Vorliebe für lange Laufzeiten.',
'Begründung und Grenze: Der Abgleich reduziert lokale parallele Zinsrisiken; Marktwerte, Key-Rate-Risiken und Liquidität zusätzlich prüfen.|Eine gute Antwort verbindet Wirkung und verbleibende Unsicherheit, ohne einen vollständigen Schutz zu behaupten.'
],'Trainiert begründete Portfolioentscheidungen und klare Kommunikation im Investmentprozess.','Ohne Marktwerte reicht der bloße Vergleich der Durationjahre nicht für eine exakte Hedgegröße. Die Aufgabe muss vollständig gelesen werden.','ALM definiert das Ziel; Duration und Overlay liefern passende Instrumente und Dimensionierung.'),
R('Fehleranalyse macht aus einer Probeklausur einen Lernplan',`Eine gemischte Fallstudie prüft Abruf, Konzeptwahl und Zeitmanagement zugleich. Der Lerneffekt entsteht vor allem in der Nachbereitung: War die Definition unklar, die passende Formel unbekannt, ein Rechenschritt falsch oder die Frage missverstanden? Verschiedene Ursachen benötigen verschiedene Übungen.

Ein Fehlerjournal hält Thema, Fehlmechanismus, korrekte Regel und einen späteren erneuten Versuch fest. Zeitversetztes Wiederholen ohne sofort sichtbare Lösung prüft echten Abruf. Die Gesamtquote allein ist zu grob: Eine richtige Antwort durch Zufall und eine knapp falsche Antwort mit gutem Verständnis liefern unterschiedliche Informationen über den Lernstand.`,
'In einem eigenen Übungsset mit 40 Aufgaben sind 28 richtig. Von 12 Fehlern beruhen 5 auf Konzeptlücken, 4 auf Rechen- oder Einheitenfehlern und 3 auf falsch gelesenen Fragen.',[
'Rohquote=28/40=70 %.|Sie beschreibt dieses Übungsset, nicht automatisch eine offizielle Bestehenswahrscheinlichkeit.',
'Fehleranteile: Konzepte 5/12≈41,7 %, Rechnen 33,3 %, Lesen 25 %.|Die Zerlegung zeigt, dass bloßes Lesen zusätzlicher Theorie nicht alle Probleme lösen würde.',
'Für jede Gruppe eine passende Maßnahme planen und später mit neuen Aufgaben prüfen.|Konzeptlücken brauchen Erklärung und Gegenbeispiele, Rechenfehler strukturierte Kontrolle, Lesefehler bewusste Markierung der Zielgröße.'
],'Genutzt für selbstständige Lernplanung und belastbare Fortschrittskontrolle.','Kleine oder nicht repräsentative Sets erlauben keine präzise Prognose des Prüfungsergebnisses. Wiedererkennen bereits bekannter Antworten überschätzt den Lernfortschritt.','Hypothesentests erinnern an Stichprobenunsicherheit; alle Fachkapitel liefern gezielte Wiederholungsziele.')
];
