const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('biz-'+id,'business-models','corporate',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','A business model description is most complete when it explains:',[
 ['the customer benefit, delivery activities, payment mechanism and resources required to earn a return.','Die Beschreibung verbindet Kundennutzen mit Erfüllung, Erlösen und erforderlichen Ressourcen.'],['only the next three years of projected revenue growth.','Eine Umsatzprognose erklärt nicht, warum Kunden zahlen oder welche Kosten und Ressourcen benötigt werden.'],['only management’s desired position relative to competitors.','Die angestrebte Position ist ein Strategieaspekt, aber noch keine vollständige wirtschaftliche Funktionsweise.']
 ],['Geschäftsmodell, Strategie und Finanzprognose sind miteinander verbunden. Sie beantworten jedoch unterschiedliche Fragen.','Eine belastbare Analyse verfolgt die gesamte Kette von Kundenproblem bis zu Zahlungen und Kapitalbindung.'],'map'),
 q('02','practice','a','For a maintenance provider, which statement most directly describes a value proposition?',[
 ['It reduces costly unexpected equipment downtime for small factories.','Das benennt den konkreten Kundennutzen gegenüber einer Alternative.'],['It invoices a monthly fee plus charges for emergency visits.','Das beschreibt den Zahlungsmechanismus.'],['It employs 40 technicians and leases a warehouse.','Das beschreibt Ressourcen, ohne den daraus entstehenden Nutzen bereits zu erklären.']
 ],['Kundennutzen ist mehr als eine Liste von Eigenschaften. Er erklärt, welches relevante Problem für eine bestimmte Gruppe besser gelöst wird.','Die Preis- und Ressourcenbeschreibungen sind ebenfalls wichtig, gehören aber zu anderen Bausteinen.'],'value'),
 q('03','practice','a','A buyer’s willingness to pay for one unit is 150. The price is 100 and the provider’s relevant unit resource cost is 60. With no other effects, total surplus created by the transaction is:',[
 ['90','Kundennutzen über Preis und Anbieterüberschuss zusammen ergeben Zahlungsbereitschaft minus Ressourcenkosten.'],['40','Dies ist nur der Anbieterüberschuss vor weiteren nicht erfassten Kosten.'],['50','Dies ist nur der beim Käufer verbleibende Überschuss.']
 ],[F('S=(150-100)+(100-60)=150-60=90','Der Preis verteilt den Überschuss zwischen den Parteien, ohne hier seine Gesamthöhe zu verändern.',[['S','Gesamter Überschuss pro Einheit in den angegebenen Geldeinheiten.']]),'Eine Preisänderung könnte in einem realen Markt auch Nachfrage oder Qualität verändern; das ist hier ausdrücklich ausgeschlossen.'],'value'),
 q('04','practice','a','Employees use a workplace software product, department heads approve adoption and the employer pays the vendor. The analyst should:',[
 ['distinguish user needs from purchasing authority and the payer’s budget.','Nutzung, Entscheidung und Zahlung liegen bei verschiedenen Rollen.'],['treat favorable employee reviews as sufficient evidence of purchasing demand.','Zufriedene Nutzer allein überwinden weder Beschaffung noch Budgetgrenzen.'],['classify every employee as a separate paying customer regardless of the contract.','Die zahlende Vertragspartei wird dadurch falsch bestimmt.']
 ],['Die Value Proposition muss tatsächlichen Nutzen erzeugen und den Beschaffungsprozess erreichen.','Kundenanzahl und Nutzeranzahl können im selben Unternehmen stark voneinander abweichen.'],'customers'),
 q('05','practice','a','A brand outsources production but contractually commits to large minimum purchases even if final demand falls. The most appropriate conclusion is:',[
 ['reduced ownership of factories does not eliminate the brand’s volume and commitment risk.','Die wirtschaftliche Abnahmeverpflichtung bleibt trotz externer Produktion bestehen.'],['all operating risk has moved to the manufacturer because production is outsourced.','Das ignoriert die ausdrücklich verbleibende Verpflichtung.'],['the brand’s cost of goods becomes zero because it does not operate the plant.','Extern beschaffte Leistung muss weiterhin bezahlt werden.']
 ],['Asset-light beschreibt zunächst eine Vermögensstruktur, nicht das vollständige Verschwinden von Kosten oder Risiko.','Die Analyse folgt Verträgen, Waren, Zahlungen und tatsächlichen Verpflichtungen.'],'value-chain'),
 q('06','practice','a b','At the same annual volume, direct sales provide a unit contribution of 36 with fixed costs of 180,000. Selling through a distributor provides a unit contribution of 24 with fixed costs of 60,000. Other effects are identical. Annual volume at which operating profits are equal is:',[
 ['10,000','Zusätzliche Fixkosten von 120.000 werden durch zwölf zusätzlichen Stückbeitrag gedeckt.'],['5,000','Dies ist die eigene Gewinnschwelle des Direktkanals, nicht der Vergleichspunkt.'],['2,500','Dies ist die eigene Gewinnschwelle des Händlerkanals.']
 ],[F('Q^*=\\frac{180000-60000}{36-24}=10000','Die Differenz beider Ergebnisfunktionen wird gleich null gesetzt.',[['Q^*','Jährliche Absatzmenge mit gleichem Ergebnis in beiden Kanälen.']]),'Beide Wege liefern an diesem Punkt ein Ergebnis von 180.000. Die gleiche Mengenannahme dient dem kontrollierten Kostenvergleich.'],'channels'),
 q('07','practice','a b','A direct channel has a higher unit contribution but substantially higher fixed costs than a reseller channel. At low sales volumes, the reseller channel may be preferable because:',[
 ['the saved fixed costs can exceed the forgone contribution per unit.','Gesamtergebnis verbindet Stückbeitrag und Menge mit den gemeinsamen Kosten.'],['a higher unit contribution always reduces total profit.','Der höhere Beitrag ist vorteilhaft, muss aber die zusätzliche Fixkostenbelastung decken.'],['using a reseller necessarily produces more revenue per unit for the manufacturer.','Die Frage gibt gerade den gegenteiligen Beitragsunterschied vor.']
 ],['Die Vorteilhaftigkeit hängt unter den genannten Bedingungen vom Absatz ab.','Ein höherer Direktverkaufspreis ist ohne die zusätzlich übernommenen Aufgaben und Kosten keine vollständige Vergleichsgröße.'],'channels'),
 q('08','practice','a','A firm sells 10,000 units at 80 each, with variable unit cost of 50 and annual fixed costs of 150,000. It cuts price to 72 without changing costs or capacity constraints. The percentage increase in volume needed to preserve operating profit is closest to:',[
 ['36.36%','Der Stückbeitrag fällt von dreißig auf zweiundzwanzig; der Gesamtbeitrag muss trotzdem dreihunderttausend bleiben.'],['11.11%','Dies würde lediglich den bisherigen Umsatz erhalten.'],['10.00%','Die prozentuale Preissenkung kann nicht unmittelbar als notwendige Mengensteigerung übernommen werden.']
 ],[F('Q_1=\\frac{10000(80-50)}{72-50}\\approx13636{,}36,\\qquad g_Q=\\frac{Q_1}{10000}-1\\approx36{,}36\\%','Da Fixkosten unverändert sind, muss derselbe gesamte Deckungsbeitrag erwirtschaftet werden.',[['Q_1','Erforderliche neue Stückzahl.'],['g_Q','Notwendige relative Mengensteigerung.']]),'Ob diese zusätzliche Nachfrage tatsächlich entsteht, ist eine eigene empirische Frage.'],'unit-economics'),
 q('09','practice','a','A service has revenue of 75 per completed job, variable cost of 45 per job and fixed costs of 90,000 per period. Within the relevant capacity range, its operating break-even volume is:',[
 ['3,000','Neunzigtausend Fixkosten werden durch dreißig Beitrag je Auftrag gedeckt.'],['1,200','Dies teilt Fixkosten durch Umsatz und ignoriert variable Kosten.'],['2,000','Dies teilt Fixkosten durch variable Kosten statt durch den verbleibenden Beitrag.']
 ],[F('Q_{BE}=\\frac{90000}{75-45}=3000','An der Gewinnschwelle deckt der gesamte Beitrag genau die Fixkosten.',[['Q_{BE}','Zahl abgeschlossener Aufträge in der Periode.']]),'Neue Kapazitätsstufen oder variable Preise würden die einfache lineare Rechnung verändern.'],'unit-economics'),
 q('10','practice','a','A start-up reports positive contribution per order after delivery costs but excludes substantial customer acquisition and central development costs. This finding:',[
 ['does not by itself establish positive company profit or value.','Wesentliche weitere Ressourcen werden von dieser Teilkennzahl noch nicht gedeckt.'],['proves that faster growth must always improve company value.','Zusätzliche Akquisition kann teuer oder schlecht gebunden sein.'],['means all excluded costs are sunk and irrelevant to future decisions.','Die Abgrenzung einer Kennzahl macht künftig vermeidbare Kosten nicht zu versunkenen Kosten.']
 ],['Unit Economics braucht einen offengelegten Kostenzähler und eine passende Einheit.','Ein positiver Teilbeitrag kann sinnvoll sein, ist aber noch kein vollständiger Gewinn oder Kapitalwert.'],'unit-economics'),
 q('11','practice','b','A distributor buys goods from several producers, holds stock and supplies small quantities promptly to retailers. Its customer value most directly arises from:',[
 ['availability, aggregation and efficient delivery rather than necessarily manufacturing the goods.','Die Leistung entsteht aus Beschaffung und Zugang, auch ohne eigene Produktion.'],['automatically owning the patents used by every supplier.','Eigentum an Lieferantenrechten folgt nicht aus dem Einkauf.'],['eliminating all inventory and customer-credit requirements.','Gerade Bestand und Zahlungsziele können wesentliche Ressourcen dieses Modells sein.']
 ],['Konventionelle Zwischenstufen können echten Kundennutzen schaffen.','Ihre Beiträge werden gegen Logistik-, Lager- und Finanzierungskosten abgewogen.'],'conventional'),
 q('12','practice','b','A consultancy must hire and train additional specialists for each substantial increase in client projects. The analyst should be most cautious about the claim that:',[
 ['revenue can scale indefinitely at almost zero incremental service cost.','Zusätzliche Leistung benötigt hier ausdrücklich zusätzliche knappe Arbeitsressourcen.'],['employee capacity and utilization affect the economics.','Diese Aussage folgt gerade aus dem beschriebenen Modell.'],['reputation and service quality may influence customer retention.','Das ist mit einer fachlich geprägten Dienstleistung vereinbar.']
 ],['Eine digitale Bestelloberfläche verändert den Arbeitsbedarf der eigentlichen Leistung nicht automatisch.','Standardisierung kann helfen, muss aber tatsächlich die zugrunde liegenden Aktivitäten verändern.'],'conventional'),
 q('13','practice','a b','A provider charges an unlimited-use flat monthly subscription while its variable costs increase materially with each use. Compared with equivalent per-use pricing, the flat fee most directly exposes the provider to:',[
 ['higher-than-expected customer usage without proportional extra revenue.','Pauschale Erlöse und nutzungsabhängige Kosten können auseinanderlaufen.'],['a guarantee that subscription revenue rises with each additional use.','Das widerspricht der unbegrenzten Pauschale.'],['the elimination of the need to monitor service costs.','Gerade die Nutzungskosten müssen beobachtet werden.']
 ],['Ein Abonnement verändert die Zahlungsregel und damit die Verteilung von Nutzungsrisiko.','Die Vorteile planbarer Erlöse müssen mit Intensität, Kapazität und Vertragsbedingungen zusammen betrachtet werden.'],'recurring'),
 q('14','practice','a b','For its defined MRR metric, a company has 60 annual subscriptions at 1,200 each and 40 monthly subscriptions at 150 each. All are active, provide evenly distributed service and have no discounts or one-off fees. MRR is:',[
 ['12,000','Jahresverträge werden monatlich normiert und zu den Monatsverträgen addiert.'],['78,000','Dies kombiniert die gesamten Jahreszahlungen mit Monatsbeträgen.'],['144,000','Dies annualisiert bereits das gesamte monatliche Ergebnis und entspricht hier ARR.']
 ],[F('MRR=60\\frac{1200}{12}+40\\cdot150=12000','Die Kennzahl verwendet für alle Verträge dieselbe Monatsbasis.',[['MRR','Monatlich normierter wiederkehrender Vertragsbestand in den angegebenen Geldeinheiten.']]),'Der Zeitpunkt tatsächlicher Zahlungen und bilanzieller Umsatzrealisierung bleibt separat zu untersuchen.'],'recurring'),
 q('15','practice','a','A company reports ARR equal to 12 times its current MRR. The most appropriate interpretation is:',[
 ['an annualized recurring-revenue snapshot rather than a guaranteed next-year revenue forecast.','Kündigungen, neue Kunden, Preise und andere Veränderungen können den späteren Umsatz verändern.'],['revenue already earned and collected over the previous twelve months.','Eine Stichtagsannualisierung ist kein historischer Jahreszahlungsnachweis.'],['the present value of all future subscriber cash flows.','Es werden weder zukünftige Bindung noch Kosten oder Diskontierung erfasst.']
 ],['Die Kennzahl beschreibt bei der gegebenen Definition einen aktuellen Vertragsstand.','Vor Vergleichen müssen Umfang, einmalige Leistungen und variable Nutzung abgeglichen werden.'],'recurring'),
 q('16','practice','a','A company begins a month with 800 customers, loses 64 of those customers and adds 100 new customers. Define customer churn as lost beginning customers divided by beginning customers. Monthly churn is:',[
 ['8.00%','Die Abgänge werden auf den vorgegebenen Anfangsbestand bezogen.'],['7.66%','Dies verwendet den Endbestand von 836 statt des Anfangsbestands.'],['4.50%','Dies verwechselt den positiven Netto-Kundenzuwachs mit den tatsächlichen Abgängen.']
 ],[F('CR=\\frac{64}{800}=8\\%','Neukunden verringern die gemessenen Abgänge der Anfangskohorte nicht.',[['CR','Kunden-Churn der Periode.']]),'Der Gesamtbestand wächst netto um sechsunddreißig Kunden, obwohl acht Prozent des alten Bestands verloren gingen.'],'retention'),
 q('17','practice','a b','Beginning-cohort MRR is 80,000. During the period, cancellations remove 8,000, contract downgrades remove 4,000 and expansions add 12,000. New customers add a separate 20,000. Gross revenue retention excluding expansion is:',[
 ['85.00%','Vom Anfangsbestand werden Kündigung und Verkleinerung abgezogen; Expansion und Neukunden bleiben außen vor.'],['100.00%','Dies ist hier die Nettoumsatzbindung einschließlich Expansion.'],['125.00%','Dies verwendet den gesamten Endbestand einschließlich Neukunden relativ zum alten Bestand.']
 ],[F('GRR=\\frac{80000-8000-4000}{80000}=85\\%','Die Bruttobindung zeigt, was von der Ausgangsumsatzbasis ohne ausgleichende Expansion bleibt.',[['GRR','Gross Revenue Retention der Anfangskohorte.']]),'Eine gute Nettokennzahl kann deshalb tatsächliche Abwanderung oder Verkleinerung verdecken.'],'retention'),
 q('18','practice','a b','A fixed beginning customer cohort generates MRR of 60,000. Cancellations remove 6,000, downgrades remove 3,000 and expansions within that cohort add 15,000. A separate new-customer cohort adds MRR of 30,000. Net revenue retention of the beginning cohort is:',[
 ['110.00%','Der alte Kundenkreis endet bei 66.000 und damit zehn Prozent über seiner Ausgangsbasis.'],['85.00%','Dies lässt Expansion aus und entspricht der Bruttoumsatzbindung.'],['160.00%','Dies zählt den neuen Kundenkreis zur Retention des alten hinzu.']
 ],[F('NRR=\\frac{60000-6000-3000+15000}{60000}=110\\%','Die Kohorte bleibt über beide Zeitpunkte gleich definiert.',[['NRR','Net Revenue Retention der Anfangskohorte.']]),'NRR über hundert Prozent schließt Kündigungen einzelner Kunden nicht aus.'],'retention'),
 q('19','practice','a','Total subscription revenue is growing quickly, but successive acquisition cohorts retain less revenue after their first year. The most useful next analysis is to:',[
 ['separate growth from new acquisition and retention of comparable existing cohorts.','Gesamtwachstum kann durch ständig neue Akquisition eine Verschlechterung des alten Bestands überdecken.'],['conclude that retention is irrelevant because total revenue rose.','Die Bindung beeinflusst künftige Beiträge und benötigte Akquisitionsausgaben.'],['add new customers to each old cohort to improve comparability.','Das würde gerade die untersuchte Ausgangsgruppe verändern.']
 ],['Kohortenanalyse verfolgt definierte Gruppen über vergleichbare Altersstufen.','Sie hilft zu erkennen, ob Wachstum dauerhaft profitabel ist oder zunehmend Ersatz für verlorene Kunden finanziert.'],'retention'),
 q('20','practice','a b','As an analytical extension, a newly acquired customer certainly contributes 15 at the end of month 1. Each later month is reached with conditional retention of 90%. Monthly contribution is constant, the appropriate monthly discount rate is 2%, and CAC paid today is 80. Customer contribution value after CAC is:',[
 ['45.00','Der Beitragsbarwert ist 125; nach Abzug der heutigen Akquisition bleiben fünfundvierzig.'],['70.00','Dies verwendet Beitrag geteilt durch Churn und ignoriert den Zeitwert.'],['125.00','Dies ist der Beitragsbarwert vor Akquisitionskosten.']
 ],[F('CLV=\\frac{15}{1{,}02-0{,}90}-80=45','Die erste Zahlung ist im gegebenen Modell sicher vereinbart; spätere Beiträge werden mit der Überlebenswahrscheinlichkeit gewichtet.',[['CLV','Beitragsbarwert nach heutiger Akquisition, vor sonstigen nicht angegebenen gemeinsamen Kosten.']]),'Die konstante unendliche Kundenwelt dient der Vertiefung; echte Kohorten können andere Bindungs- und Kostenverläufe haben.'],'lifetime'),
 q('21','practice','a','Two identical customer-value models differ only in timing: model A guarantees the first contribution, while model B requires a 95% retention event before that first contribution and every later contribution shifts by the same extra retention factor. Before acquisition costs, model B’s contribution present value is:',[
 ['5% lower than model A’s.','Jede erwartete Zahlung wird zusätzlich mit 0,95 multipliziert.'],['identical because both models quote the same periodic retention rate.','Die erste Bindungsentscheidung findet an einem anderen Zeitpunkt statt.'],['5% higher because more retention events are modeled.','Ein zusätzlicher möglicher Abgang erhöht den Zahlungswert nicht.']
 ],['Die geometrischen Reihen unterscheiden sich um einen gemeinsamen Faktor von 0,95.','Nach Abzug identischer fixer CAC wäre die prozentuale Veränderung des verbleibenden Nettowerts nicht notwendigerweise ebenfalls fünf Prozent.'],'lifetime'),
 q('22','practice','a b','In a customer-cohort model, the first monthly contribution of 20 is certain and subsequent retention is 90% per monthly transition. There is no discounting and no reactivation. CAC is 200 paid today. The expected cumulative contribution reaches 200:',[
 ['only as a limit over infinitely many months, not at any finite month.','Die Summe ist zweihundert mal eins minus 0,9 hoch Monatszahl und bleibt für jede endliche Zahl kleiner als zweihundert.'],['after exactly ten months because 200 divided by 20 equals ten.','Dies setzt den Monatsbeitrag für alle Kunden als dauerhaft ungekündigt an.'],['at the end of the first month because expected lifetime value equals CAC.','Der Wert der gesamten erwarteten Folge ist nicht bereits der erste Geldzufluss.']
 ],[F('C(n)=20\\frac{1-0{,}9^n}{1-0{,}9}=200(1-0{,}9^n)<200','Für jede endliche positive Monatszahl bleibt die Potenz positiv.',[['C(n)','Erwartete undiskontierte Beitragssumme bis Monat n.'],['n','Endliche Anzahl der berücksichtigten Monatsendzahlungen.']]),'Ein positiver Diskontsatz würde den gesamten Beitragsbarwert zusätzlich unter zweihundert senken.'],'payback'),
 q('23','practice','a b','A freemium service has 5,000 active users, 10% of whom pay 18 per period. Variable cost is 4 per paying user and 0.40 per free user. Fixed period costs are 4,000, with no other costs. Operating profit is:',[
 ['1,200','Beitrag der fünfhundert Zahler minus Kosten der 4.500 kostenlosen Nutzer und Fixkosten.'],['3,000','Dies ignoriert die Kosten der kostenlosen Nutzer.'],['5,000','Dies ignoriert sämtliche variablen Kosten.']
 ],[F('\\Pi=500(18-4)-4500\\cdot0{,}40-4000=1200','Kostenlose Nutzer bleiben Teil der Leistungsbereitstellung und werden nicht aus der Rechnung gestrichen.',[['\\Pi','Operatives Periodenergebnis in den angegebenen Geldeinheiten.']]),'Die Betrachtung hält die Zahl und Kosten der Nutzer für diese Periode ausdrücklich konstant.'],'freemium'),
 q('24','practice','b','Which offering is most clearly freemium rather than only a free trial?',[
 ['A permanently available basic tier is free, while advanced features require payment.','Kostenloser Grundumfang und bezahlte Zusatzfunktionen bestehen parallel.'],['Full access is free for fourteen days and then ends unless the user pays.','Das ist eine zeitlich begrenzte Testphase.'],['Every customer must buy a full subscription before using any feature.','Hier fehlt der dauerhaft kostenlose Grundzugang.']
 ],['Die Unterscheidung betrifft Zugang und Zahlungsmechanismus.','Sie sagt noch nicht, ob die Konversion, Bindung und Kosten eines der Modelle attraktiv sind.'],'freemium'),
 q('25','practice','a b','An advertising-funded service offers 2 million ad impressions in a period. It sells 75% of them at 8 per thousand sold impressions. Advertising revenue is:',[
 ['12,000','Eineinhalb Millionen vermarktete Kontakte entsprechen 1.500 Tausenderpaketen.'],['16,000','Dies unterstellt, dass sämtliche verfügbaren Kontakte verkauft werden.'],['1,500','Dies ist die Anzahl der vermarkteten Tausenderpakete vor Multiplikation mit dem Preis.']
 ],[F('R_{ad}=\\frac{2000000\\cdot0{,}75}{1000}\\cdot8=12000','Nutzungsvolumen, tatsächliche Vermarktung und Preis sind getrennte Erlöstreiber.',[['R_{ad}','Werbeerlös der Periode.']]),'Inhalts-, Vertriebs- und Betriebskosten müssen für den Gewinn zusätzlich berücksichtigt werden.'],'freemium'),
 q('26','practice','a b','A device is sold today at a unit loss of 24. Each associated refill bought from the same provider contributes 6 at the end of year 1. At a 20% appropriate annual discount rate, the minimum whole number of refills needed for nonnegative NPV is:',[
 ['5','Fünf Beiträge liefern nach Abzinsung fünfundzwanzig und decken die anfänglichen vierundzwanzig.'],['4','Vier Beiträge decken den Verlust nur nominal, nicht nach Zeitwert.'],['6','Diese Menge wäre ausreichend, ist aber nicht die kleinste ausreichende ganze Zahl.']
 ],[F('-24+\\frac{6q}{1{,}20}\\ge0\\quad\\Longrightarrow\\quad q\\ge4{,}8','Die Anzahl muss ganzzahlig sein und wird deshalb auf fünf aufgerundet.',[['q','Anzahl dem Anbieter zurechenbarer Nachfüllkäufe am Jahresende.']]),'Käufe kompatibler Fremdprodukte erzeugen keinen solchen eigenen Beitrag.'],'complements'),
 q('27','practice','a b','Two products sell separately for 60 each. A new bundle costs 90. For customers who would otherwise have bought both products, holding all quantities and costs fixed, the bundle:',[
 ['reduces revenue by 30 per such customer.','Diese Kunden hätten zuvor insgesamt 120 gezahlt.'],['increases revenue by 30 because the bundle exceeds one standalone price.','Das verwendet die falsche Alternative für die ausdrücklich genannten Kunden.'],['has no revenue effect because it contains the same two products.','Der Gesamtpreis ändert sich trotz unveränderter Bestandteile.']
 ],['Andere Kunden könnten ohne Bündel nur ein Produkt gekauft haben und nun mehr ausgeben.','Die Gesamtauswirkung hängt deshalb von Segmenten, Gegenfaktum und zusätzlichen Kosten ab.'],'complements'),
 q('28','practice','a b','An asset-access business invests 500 today. It receives net cash of 240 at each of the next two year-ends plus a separate terminal disposal amount of 50 at year 2. All relevant costs and tax effects are included. At 10%, NPV is closest to:',[
 ['−42.15','Die zweite Zahlung umfasst laufenden Nettozufluss plus Verkaufserlös; beide werden auf heute abgezinst.'],['30.00','Dies addiert Zahlungen ohne Zeitwert.'],['−83.47','Dies lässt den zusätzlichen Restwert aus.']
 ],[F('NPV=-500+\\frac{240}{1{,}10}+\\frac{290}{1{,}10^2}\\approx-42{,}15','Wiederkehrender Zufluss allein beweist keine ausreichende Vergütung des gebundenen Kapitals.',[['NPV','Heutiger Kapitalwert in den angegebenen Einheiten.']]),'Kapitalbedarf, Laufzeit und Restwert gehören zur Geschäftsmodellprüfung.'],'assets'),
 q('29','practice','b','A technology owner permits a manufacturer to use a specified patent in return for a royalty, without providing a complete branded operating system for the manufacturer’s business. The arrangement is most closely described as:',[
 ['licensing.','Ein definiertes Nutzungsrecht wird gegen Vergütung eingeräumt.'],['a direct retail sale of finished goods to consumers.','Der Rechteinhaber verkauft hier ein Nutzungsrecht an einen Hersteller.'],['an unlimited-use consumer subscription with no payment obligation.','Die vereinbarte Royalty ist eine Zahlung und die Beziehung ist anders beschrieben.']
 ],['Lizenzierung und Franchising können Rechte und wiederkehrende Gebühren enthalten, sind aber nicht synonym.','Der Fall konzentriert sich auf ein einzelnes technisches Recht und beschreibt kein vollständiges Franchisesystem.'],'rights'),
 q('30','practice','b','Six independent franchisees each generate annual sales of 800,000. A franchisor receives only a 5% royalty on those sales and incurs support costs of 12,000 per franchisee. Its royalty revenue is:',[
 ['240,000','Fünf Prozent des Systemumsatzes von 4,8 Millionen werden zu eigener Gebühr.'],['4,800,000','Dies ist der Umsatz der unabhängigen Standorte, nicht der eigene Gebührenumsatz.'],['168,000','Dies ist der Beitrag nach den angegebenen Betreuungskosten, nicht Umsatz.']
 ],[F('R_F=6\\cdot800000\\cdot0{,}05=240000','Die laufende Gebühr wird getrennt von den Umsätzen und Kosten der Betreiber betrachtet.',[['R_F','Jährlicher Gebührenumsatz des Franchisegebers.']]),'Weitere eigene Warenlieferungen oder Standorte wären zusätzliche Geschäftsströme, sind hier jedoch ausgeschlossen.'],'rights'),
 q('31','practice','a b','A pure commission platform has GMV of 6 million, a take rate of 10%, variable costs of 3% of GMV and fixed period costs of 300,000. Its operating profit is:',[
 ['120,000','Gebühren sechshunderttausend minus variable Kosten hundertachtzigtausend minus Fixkosten.'],['300,000','Dies ignoriert die volumenabhängigen Kosten.'],['5,520,000','Dies behandelt das gesamte Handelsvolumen fälschlich als eigenen Umsatz.']
 ],[F('\\Pi=6000000(0{,}10-0{,}03)-300000=120000','Gebühr und variable Kostenquote beziehen sich hier auf dasselbe GMV.',[['\\Pi','Operatives Periodenergebnis der Plattform.']]),'Eine andere Kennzahlendefinition würde eine neue Überleitung benötigen.'],'platforms'),
 q('32','practice','a b','A business calls itself a platform and collects the full customer payment before forwarding most of it to suppliers. For IFRS 15 gross-versus-net revenue analysis, the key issue is:',[
 ['whether it controls the specified good or service before transfer or instead arranges for another party to provide it.','Die wirtschaftliche Rolle als Principal oder Agent bestimmt die relevante Betrachtung.'],['whether its marketing materials use the word platform.','Ein Etikett ersetzt keine Vertrags- und Kontrollanalyse.'],['whether it physically receives the cash first, regardless of its obligations.','Geldfluss allein bestimmt die Kontrolle der zugesagten Leistung nicht.']
 ],['Ein Agent kann Zahlungsabwicklung übernehmen, ohne den gesamten Warenwert als eigenen Umsatz zu verdienen.','Umgekehrt kann ein digitaler Anbieter auch selbst als Principal liefern. Die tatsächliche Zusage ist zu prüfen.'],'platforms'),
 q('33','practice','b','A marketplace becomes more useful to buyers when more relevant sellers join, improving availability and choice. This is most directly:',[
 ['an indirect network effect across participant groups.','Eine Seite profitiert von zusätzlicher relevanter Teilnahme der anderen Seite.'],['only a decline in production cost from allocating factory overhead over more units.','Das würde einen Kostenskaleneffekt statt des beschriebenen Teilnehmernutzens erklären.'],['proof that every existing seller benefits equally from additional competition.','Mehr Anbieter können die Konkurrenz innerhalb der Verkäuferseite erhöhen.']
 ],['Der Netzwerkeffekt hängt von relevanten, aktiven und passenden Teilnehmern ab.','Sein Vorzeichen und Umfang können sich zwischen Käufer- und Verkäuferseite unterscheiden.'],'networks'),
 q('34','practice','a b','A software firm spreads the same development cost over more paying customers, while each customer’s benefit from the product is unaffected by other users. The stated mechanism is:',[
 ['a scale economy, without demonstrated network effects.','Gemeinsame Kosten verteilen sich auf mehr Einheiten, ohne den Kundennutzen über andere Nutzer zu verändern.'],['a direct network effect solely because the customer count rises.','Die notwendige Verbindung zum Nutzen anderer Nutzer fehlt.'],['proof that all marginal operating costs are zero.','Gemeinsame Entwicklungskosten sagen noch nichts über Support, Rechenleistung oder andere Zusatzkosten.']
 ],['Skaleneffekte betreffen hier die Kostenseite. Netzwerkeffekte betreffen die Abhängigkeit des Teilnahmenutzens von anderen Teilnehmern.','Beides kann gemeinsam vorkommen, wird aber durch unterschiedliche Evidenz belegt.'],'networks'),
 q('35','practice','b','Buyers and sellers can use several competing platforms simultaneously at little extra cost. Other things equal, this multi-homing most likely:',[
 ['limits the inference that a large user base guarantees durable pricing power.','Teilnehmer können alternative Zugänge nutzen, wodurch Bindung und Gebührenmacht begrenzt werden können.'],['proves that network effects cannot exist at all.','Netzwerknutzen und parallele Nutzung schließen sich nicht grundsätzlich aus.'],['guarantees that the largest platform can raise fees without losing activity.','Die leicht zugänglichen Alternativen sprechen gerade gegen eine solche Garantie.']
 ],['Reichweite ist ein möglicher Vorteil, aber kein vollständiger Nachweis dauerhafter Abschöpfung.','Qualität, lokale Dichte, Wechselkosten und alternative Zugänge ergänzen die Beurteilung.'],'networks'),
 q('36','practice','a b','A firm describes itself as an asset-light technology marketplace but buys most goods in advance, finances customer receivables and promises long-term maintenance. The analyst should first:',[
 ['separate the actual trading, financing, service and intermediary activities before forecasting.','Die beschriebenen Rechte, Pflichten und Ressourcen können verschiedene wirtschaftliche Modelle enthalten.'],['apply a pure commission-platform margin to all reported sales.','Das ignoriert eigene Waren- und Leistungsverpflichtungen.'],['assume the description is false without examining contracts and segment information.','Eine Gegenhypothese muss ebenso anhand tatsächlicher Informationen geprüft werden.']
 ],['Der wirtschaftliche Inhalt wird weder aus dem attraktivsten Etikett noch aus pauschalem Misstrauen abgeleitet.','Getrennte Treiber und Cashflows machen nachvollziehbar, welcher Teil Kapital bindet und wo die Beiträge entstehen.'],'evidence'),
 q('a1','mock-a','a b','A digital health-information service offers a permanent free basic tier, charges some users for advanced tools and sells advertising shown to free users. Active users remain constant, but advertisers cut spending while user conversion and service costs are unchanged. The most appropriate assessment is that:',[
 ['the hybrid model can lose revenue and profit despite unchanged user numbers.','Eine eigenständige zahlende Kundengruppe reduziert ihre Ausgaben, während die anderen genannten Treiber unverändert bleiben.'],['stable user numbers guarantee stable revenue because all users pay subscriptions.','Der Fall unterscheidet ausdrücklich kostenlose Nutzung, zahlende Nutzer und Werbung.'],['the business is necessarily a franchise system because several groups provide revenue.','Mehrere Zahlungsquellen begründen kein übertragenes Marken- und Betriebssystem für unabhängige Betreiber.']
 ],['Die Erlöspfade müssen einzeln rekonstruiert werden: bezahlte Funktionen und Werbevermarktung.','Die unveränderte Nutzerzahl erhält den Anzeigenpreis oder die verkaufte Werbenachfrage nicht automatisch. Ein Hybridmodell ist keine Garantie gegen einen Rückgang einer wesentlichen Erlösquelle.'],'hybrids'),
 q('b1','mock-b','a b','Firm A controls and resells goods, reporting sales of 9,000 and supplier costs of 8,000. Firm B arranges comparable transactions as an agent and reports commission revenue of 1,000 without purchasing the goods. Both have other operating costs of 600. Which conclusion is most appropriate?',[
 ['Their operating profits are equal, while different gross-versus-net revenue bases produce different margins.','Beide behalten vor sonstigen Kosten eintausend und danach vierhundert; ihre Umsatznenner unterscheiden sich.'],['Firm B’s higher reported margin alone proves it creates more absolute operating profit.','Die Quote ist höher, der absolute Ergebnisbetrag aber gleich.'],['Firm A earns nine times as much operating profit because its revenue is nine times as large.','Der Warenaufwand von achttausend wird dabei ignoriert.']
 ],[F('\\Pi_A=9000-8000-600=400,\\qquad \\Pi_B=1000-600=400','Der wirtschaftliche Periodenbeitrag ist in diesen vorgegebenen Zahlen gleich, obwohl die Umsatzdarstellung stark abweicht.',[['\\Pi_A,\\Pi_B','Operative Ergebnisse von A und B in derselben Periode.']]),F('M_A=\\frac{400}{9000}\\approx4{,}44\\%,\\qquad M_B=\\frac{400}{1000}=40\\%','Die Margen verwenden unterschiedliche Umsatzbasen.',[['M_A,M_B','Operative Ergebnismargen von A und B.']]),'Gleicher Periodengewinn beweist umgekehrt noch keinen gleichen Unternehmenswert: Kapitalbedarf, Risiko und weitere Zahlungen können sich unterscheiden.'],'financial-profile')
];
