const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('dcf-'+id,'dcf-equity','equity',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','The cash flow discounted directly at the required return on common equity in a dividend discount model is:',[
 ['the expected dividend payable to the specified common shareholders.','Das DDM bewertet erwartete Zahlungen an den betrachteten Stammkapitalanspruch.'],['EBIT before tax and investment.','EBIT ist weder verfügbare Zahlung noch auf Stammaktionäre abgegrenzt.'],['FCFF before interest, discounted at WACC.','Dies gehört zum operativen Unternehmensmodell, nicht zum DDM.']
 ],['Zuerst wird die Zahlung definiert.','DDM, FCFE und FCFF dürfen nicht allein wegen ähnlicher Formeln als derselbe Anspruch behandelt werden.'],'scope'),
 q('02','practice','a c','A profitable company pays no dividends for several years but is expected to generate positive cash available to equity holders. The most appropriate conclusion is that:',[
 ['an FCFE approach may be useful, with reinvestment, financing and use of retained funds explicitly assessed.','Fehlende aktuelle Dividenden verhindern nicht jede wirtschaftliche Bewertung.'],['its common equity necessarily has zero intrinsic value.','Spätere Eigentümerleistungen können einen Wert begründen.'],['net income may be discounted without any investment or financing adjustments.','Gewinn ist kein automatisch vollständig verfügbarer Cashflow.']
 ],['Die Modellwahl berücksichtigt erwartete Eigentümerleistungen und Kapitalverwendung.','Ein FCFE-Modell benötigt trotzdem eine konsistente Zukunfts- und Finanzierungserklärung.'],'ddm'),
 q('03','practice','a','Residual income for common equity is most accurately defined as:',[
 ['income available to common shareholders less the equity charge on beginning common book equity.','Die kalkulatorische Eigenkapitalbelastung wird auf das Anfangskapital bezogen.'],['the cash dividend plus the same period’s FCFE.','Dies addiert möglicherweise dieselbe Eigentümerleistung doppelt.'],['income before financing less only the interest paid on debt.','Die Eigenkapitalbelastung fehlt; auch die Ausgangsgröße ist anders abgegrenzt.']
 ],['Residualgewinn zeigt den Überschuss nach den Eigenkapitalkosten.','Er ist keine zusätzliche Zahlung neben Dividenden oder FCFE.'],'residual-charge'),
 q('04','practice','a b','A share is expected to pay a dividend of 6 in one year and be worth 104 immediately after that payment. Its required annual return is 10%. Intrinsic value today is:',[
 ['100.00','Beide Leistungen am Jahresende werden gemeinsam diskontiert.'],['110.00','Dies ist die ungezinst aufsummierte Zukunftsleistung.'],['94.55','Dies lässt die Dividende aus.']
 ],[F('V_0=(6+104)/1{,}10=100','Dividende und verbleibender Anspruch werden auf denselben Stichtag gebracht.',[['V_0','Heutiger Wert je Aktie.']])],'one-period'),
 q('05','practice','a b','An analyst explicitly forecasts dividends through year 3. Terminal equity value V3 is measured immediately after the year-3 dividend. Which treatment is correct?',[
 ['add D3 and V3 at year 3 and discount their sum for three years.','Die letzte Detailzahlung und der danach verbleibende Anspruch liegen am selben Termin.'],['replace D3 with V3 because terminal value includes the dividend already paid at year 3.','Der nach Zahlung gemessene Wert enthält diese gerade gezahlte Dividende nicht.'],['add V3 to today’s value without discounting it.','Ein Wert in Jahr drei ist kein heutiger Betrag.']
 ],['Der definierte Endwert enthält hier nur Leistungen nach Jahr drei.','Deshalb bleiben die letzte Detaildividende und die Diskontierung des Endwerts erforderlich.'],'horizon'),
 q('06','practice','a','A company reports EBIT of 120, interest of 20 and a 25% usable tax rate. Depreciation is 10, capital expenditure is 40 and operating working capital increases by 15. With no other adjustments, FCFF is:',[
 ['45.00','Nachsteuerliches EBIT neunzig plus Abschreibung zehn minus Investitionen fünfundfünfzig.'],['30.00','Dies lässt die nachsteuerliche Zinswirkung im Cashflow für sämtliche Kapitalgeber.'],['75.00','Dies ist der Gewinn nach Zinsen und Steuern vor Cashflowanpassungen.']
 ],[F('FCFF=120(1-0{,}25)+10-40-15=45','Der Zahlungsstrom liegt vor Finanzierungsverteilung.',[['FCFF','Freier operativer Cashflow der Periode.']])],'fcff'),
 q('07','practice','a','FCFF is 45, interest expense is 20, the usable tax rate is 25%, new debt is 12 and debt repayment is 7. With no other claims, FCFE is:',[
 ['35.00','Nachsteuerliche Zinsen werden abgezogen, Nettokreditaufnahme fünf wird ergänzt.'],['25.00','Dies zieht die Nettokreditaufnahme fälschlich ab.'],['50.00','Dies lässt die nachsteuerlichen Zinsen aus.']
 ],[F('FCFE=45-20(1-0{,}25)+(12-7)=35','Finanzierung wird vor der direkten Eigenkapitalbewertung berücksichtigt.',[['FCFE','Freier Eigenkapitalcashflow.']])],'fcfe'),
 q('08','practice','a c','Holding operations and investment unchanged, a one-time additional debt issue most directly:',[
 ['increases current FCFE but does not by itself establish higher sustainable operating value.','Zusätzliche Finanzierung ist kein operativer Wertbeweis.'],['increases current FCFF by exactly the proceeds.','FCFF liegt vor Finanzierungsverteilung und erfasst die Aufnahme nicht als operativen Cashflow.'],['proves the dividend growth rate can rise permanently by the same percentage.','Kreditbedingungen, Rückzahlung und Produktivität müssen geplant werden.']
 ],['Nettokreditaufnahme gehört zur FCFE-Brücke.','Ihre späteren Zinsen und Tilgungen sowie Risikoänderungen bleiben wirtschaftlich relevant.'],'fcfe'),
 q('09','practice','a','An analyst discounts correctly specified FCFE at the appropriate equity return, obtaining equity value of 60. Debt market value is 40 and no extra adjustments are needed. The correct equity value is:',[
 ['60.00','Die direkte Bewertung enthält bereits die Finanzierungswirkungen.'],['20.00','Dies zieht dieselbe Finanzierung nach dem FCFE-Modell erneut ab.'],['100.00','Dies gibt den Fremdkapitalanspruch den Eigenkapitalgebern hinzu.']
 ],['Nach einer vollständigen direkten FCFE-Bewertung wird dieselbe Schuld nicht noch einmal abgezogen.','Die Schuldenbrücke gehört zu einem entsprechenden Ausgangswert sämtlicher Kapitalgeber.'],'consistent-debt'),
 q('10','practice','a b','In a no-tax perpetual model, FCFF is 10 and WACC is 10%. Debt pays annual interest of 2 and has market value 40. There are no other claims or cash assets. The equity return consistent with the residual equity value and FCFE is closest to:',[
 ['13.33%','Eigenkapitalwert sechzig und jährliche Eigenkapitalzahlung acht.'],['10.00%','Dies verwendet den Satz des Gesamtanspruchs.'],['5.00%','Dies ist die Fremdkapitalrendite zwei geteilt durch vierzig.']
 ],[F('V_{op}=10/0{,}10=100,\\quad E=100-40=60,\\quad k_e=(10-2)/60=13{,}3333\\%','Werte, Zahlungen und Renditeforderungen gehören zu demselben Teilanspruch.',[['V_{op},E','Operativer Gesamt- und Eigenkapitalwert.'],['k_e','Konsistente Eigenkapitalrenditeforderung.']])],'consistent-debt'),
 q('11','practice','b','The dividend just paid was 2 per share. Dividends are expected to grow by 4% indefinitely and required return is 10%. Intrinsic value is closest to:',[
 ['34.67','Die nächste Dividende 2,08 wird durch sechs Prozent geteilt.'],['33.33','Dies verwendet die bereits gezahlte Dividende im Zähler.'],['20.80','Dies ignoriert den Wachstumsabzug im Nenner.']
 ],[F('V_0=2(1{,}04)/(0{,}10-0{,}04)=34{,}6667','Der Zähler ist die erste noch ausstehende Zahlung.',[['V_0','Heutiger Wert je Aktie.']])],'dividend-timing'),
 q('12','practice','b','The next annual dividend is already forecast at 3. Required return is 9% and dividends grow by 3% thereafter. Intrinsic value is:',[
 ['50.00','Die nächste Zahlung ist bereits angegeben.'],['51.50','Dies erhöht die bereits kommende Dividende erneut um Wachstum.'],['33.33','Dies lässt den Wachstumsabzug weg.']
 ],[F('V_0=3/(0{,}09-0{,}03)=50','Ein gegebenes D_1 wird nicht nochmals auf das nächste Jahr erhöht.',[['V_0','Heutiger Aktienwert.']])],'dividend-timing'),
 q('13','practice','b c','A positive dividend stream is assumed to grow forever at 12%, while required return is 10%. Applying the Gordon formula most accurately:',[
 ['fails to produce a finite valid value because the infinite discounted series does not converge.','Die Konvergenzbedingung ist verletzt.'],['establishes a negative intrinsic value because the denominator is negative.','Eine negative algebraische Zahl ist keine gültige Summe dieser positiven Reihe.'],['is valid whenever the company currently has positive earnings.','Aktuelle Gewinne beheben die unendliche Wachstumsannahme nicht.']
 ],['Die einzelnen diskontierten Zahlungen werden nicht ausreichend kleiner.','Ein endlicher Hochwachstumsabschnitt und eine begründete stabile Endphase wären ein anderes Modell.'],'geometric'),
 q('14','practice','b c','The next dividend is 2, dividends decline by 2% per year indefinitely and required return is 8%. Assuming the model is appropriate, intrinsic value is:',[
 ['20.00','Diskontsatz minus negatives Wachstum ergibt zehn Prozent.'],['33.33','Dies zieht zwei positive Prozentpunkte ab und kehrt das Vorzeichen um.'],['25.00','Dies ignoriert den Rückgang.']
 ],[F('V_0=2/(0{,}08-(-0{,}02))=20','Sinkende positive Dividenden können eine konvergente positive Reihe bilden.',[['V_0','Heutiger Wert.']])],'dividend-timing'),
 q('15','practice','b c','A share price is 50, the next dividend is fixed in the forecast at 2 and required return is 10%. The perpetual growth rate implied by the Gordon model is:',[
 ['6.00%','Zehn Prozent minus nächste Dividendenrendite vier Prozent.'],['4.00%','Dies ist nur die nächste Dividendenrendite.'],['10.00%','Dies ignoriert die Dividendenzahlung.']
 ],[F('g=0{,}10-2/50=6\\%','Die Rückrechnung setzt voraus, dass Preis und Modellwert gleichgesetzt werden.',[['g','Impliziertes konstantes Wachstum.']])],'implied'),
 q('16','practice','b c','A share price is 50, the dividend just paid was 2 and required return is 10%. The perpetual dividend growth rate implied by the Gordon model is closest to:',[
 ['5.77%','Die nächste Dividende hängt selbst vom gesuchten Wachstum ab.'],['6.00%','Dies behandelt die vergangene Zahlung als bereits festgelegte nächste Dividende.'],['4.00%','Dies ist die vergangene Zahlung relativ zum Preis, nicht die gesuchte Rate.']
 ],[F('g=(0{,}10\\cdot50-2)/(50+2)=5{,}7692\\%','Die Zeitangabe der Dividende verändert die Umstellung.',[['g','Impliziertes langfristiges Wachstum.']])],'implied'),
 q('17','practice','b c','Under constant beginning-book-equity ROE of 15%, no share issues and a retention ratio of 40%, the sustainable earnings growth rate is:',[
 ['6.00%','Vierzig Prozent des Gewinns werden bei fünfzehn Prozent Kapitalrendite produktiv einbehalten.'],['40.00%','Dies ist Einbehaltung, nicht daraus erzeugtes Wachstum.'],['15.00%','Dies ist die Kapitalrendite vor Berücksichtigung der Ausschüttung.']
 ],[F('g=b\\,ROE=0{,}40\\cdot0{,}15=6\\%','Der Zusammenhang setzt unveränderte Rendite und eine passende Kapitalfortschreibung voraus.',[['g','Nachhaltiges Wachstum.'],['b','Einbehaltungsquote.'],['ROE','Rendite auf das Anfangsbuchkapital.']])],'retention'),
 q('18','practice','b c','A stable company targets growth of 4% and expects ROE of 10% on beginning book equity, with no external equity issues. The required retention ratio is:',[
 ['40.00%','Wachstum geteilt durch die Kapitalrendite.'],['60.00%','Dies ist die verbleibende Ausschüttungsquote.'],['4.00%','Dies setzt Wachstumsrate und Finanzierungsquote gleich.']
 ],[F('b=0{,}04/0{,}10=40\\%','Die Ausschüttungsquote beträgt unter diesen Annahmen sechzig Prozent.',[['b','Erforderliche Einbehaltung.']])],'retention'),
 q('19','practice','b','Beginning book equity is 100, first-year ROE is 15% and 40% of earnings are retained. No other book equity changes occur. End-of-year book equity is:',[
 ['106.00','Gewinn fünfzehn, davon sechs einbehalten.'],['109.00','Dies ergänzt die ausgeschüttete Dividende statt des einbehaltenen Gewinns.'],['115.00','Dies lässt die Dividende in der Buchwertfortschreibung aus.']
 ],[F('B_1=100+0{,}40\\cdot15=106','Die Dividende neun verlässt das Eigenkapital.',[['B_1','Buchwert nach der ersten Periode.']])],'retention'),
 q('20','practice','b c','Book equity is 100, ROE is permanently 15%, retention is permanently 40% and required equity return is 10%. With clean book equity evolution and no other changes, intrinsic equity value is:',[
 ['225.00','Nächste Dividende neun und Wachstum sechs Prozent.'],['150.00','Dies ist der Vergleich ohne weitere Reinvestition und Wachstum.'],['375.00','Dies kapitalisiert den gesamten Gewinn mit Wachstum und lässt die Einbehaltung im Cashflow aus.']
 ],[F('D_1=15(1-0{,}40)=9,\\quad g=6\\%,\\quad V_0=9/(0{,}10-0{,}06)=225','Der Wachstumsnutzen wird gemeinsam mit der dazugehörigen kleineren Ausschüttung bewertet.',[['D_1','Nächste Dividende.'],['g','Nachhaltiges Wachstum.'],['V_0','Eigenkapitalwert.']])],'growth-value'),
 q('21','practice','b c','Book equity is 100, permanent ROE and required return are both 10%. Retention rises from zero to 40%, with no other model changes. Intrinsic equity value after the change is:',[
 ['100.00','Neue Investitionen verdienen genau ihre Eigenkapitalkosten.'],['166.67','Dies behält den ganzen Gewinn im Zähler trotz reduzierter Ausschüttung.'],['60.00','Dies senkt die Dividende ohne das damit finanzierte Wachstum zu berücksichtigen.']
 ],[F('V_0=6/(0{,}10-0{,}04)=100','Dividende und Wachstum verändern sich gemeinsam.',[['V_0','Wert im neuen konstanten Modell.']])],'growth-value'),
 q('22','practice','b c','Book equity is 100, permanent ROE is 6%, retention is 40% and required return is 10%. With the stated constant assumptions, intrinsic equity value is closest to:',[
 ['47.37','Zusätzliches Kapital verdient weniger als gefordert; Dividende 3,6 und Wachstum 2,4 Prozent.'],['60.00','Dies ist der alternative Fall ohne neue Einbehaltung.'],['78.95','Dies verwendet den ganzen Gewinn bei gleichzeitiger Wachstumsannahme.']
 ],[F('V_0=6(1-0{,}40)/(0{,}10-0{,}40\\cdot0{,}06)=47{,}3684','Positives Wachstum kann bei unzureichender Reinvestitionsrendite den Wert vermindern.',[['V_0','Eigenkapitalwert.']])],'growth-value'),
 q('23','practice','a b c','A stable operating model expects growth of 3% and ROIC of 12%. Under constant capital productivity, the required operating reinvestment rate is:',[
 ['25.00%','Wachstum geteilt durch Rendite auf benötigtes Kapital.'],['3.00%','Dies ist Wachstum, nicht der dafür gebundene Gewinnanteil.'],['75.00%','Dies ist der nach Reinvestition verbleibende Anteil von NOPAT.']
 ],[F('\\eta=0{,}03/0{,}12=25\\%','Das stabile Modell verknüpft Kapitalbindung und erwartete Produktivität.',[['\\eta','Operative Reinvestitionsquote.']])],'reinvestment'),
 q('24','practice','a b c','Next-year NOPAT is 72, sustainable growth is 3% and ROIC is 12%. Assuming the stable reinvestment relation holds, next-year FCFF is:',[
 ['54.00','Benötigte Reinvestition achtzehn wird vom Nachsteuergewinn abgezogen.'],['72.00','Dies lässt die zur Wachstumsannahme gehörenden Investitionen aus.'],['18.00','Dies ist die Reinvestition statt des verbleibenden Cashflows.']
 ],[F('FCFF_1=72(1-0{,}03/0{,}12)=54','Nach Wachstumskapitalbindung bleiben fünfundsiebzig Prozent des NOPAT verfügbar.',[['FCFF_1','Nächster operativer freier Cashflow.']])],'reinvestment'),
 q('25','practice','a b c','Next-year FCFF is 54, grows indefinitely at 3% and is discounted at a suitable constant WACC of 10%. With no separately included non-operating assets, intrinsic operating value is closest to:',[
 ['771.43','Nächster FCFF geteilt durch sieben Prozent.'],['540.00','Dies ignoriert das Wachstum.'],['1,028.57','Dies könnte aus NOPAT zweiundsiebzig statt FCFF vierundfünfzig entstehen.']
 ],[F('V_{op}=54/(0{,}10-0{,}03)=771{,}4286','Das Ergebnis gehört zum operativen Gesamtanspruch, noch nicht automatisch zum Stammkapital.',[['V_{op}','Operativer Wert.']])],'reinvestment'),
 q('26','practice','b c','The dividend just paid was 2. Dividends grow by 20% for the next two years and 4% thereafter. Required return is 10%. Intrinsic value is closest to:',[
 ['45.82','Detaildividenden und korrekt datierter Fortführungswert werden diskontiert.'],['54.48','Dies addiert den Endwert 49,92 ohne Diskontierung zum korrekten Barwert der Detaildividenden.'],['44.23','Dies verwendet D₂ statt D₃ als erste Zahlung der stabilen Reihe.']
 ],[F('D_1=2{,}4,\\quad D_2=2{,}88,\\quad V_2=2{,}88(1{,}04)/0{,}06=49{,}92,\\quad V_0=2{,}4/1{,}1+(2{,}88+49{,}92)/1{,}1^2=45{,}8182','Der Endwert liegt nach der zweiten Detaildividende und umfasst die Zahlungen ab Jahr drei.',[['D_1,D_2','Detaildividenden.'],['V_2','Fortführungswert am Ende von Jahr zwei.'],['V_0','Heutiger Wert.']])],'two-stage'),
 q('27','practice','b c','In a two-stage DDM, year-2 dividend is 3, stable growth begins with year 3 at 2% and required return is 8%. The terminal value measured immediately after the year-2 dividend is:',[
 ['51.00','Die erste enthaltene Zahlung ist 3,06 in Jahr drei.'],['50.00','Dies nimmt die bereits gezahlte Dividende drei als erste zukünftige Zahlung.'],['47.22','Dies ist eine weitere Diskontierung, nicht der am Ende von Jahr zwei gefragte Betrag.']
 ],[F('V_2=3(1{,}02)/(0{,}08-0{,}02)=51','Bewertungszeitpunkt und Beginn der verbleibenden Reihe stimmen überein.',[['V_2','Endwert nach der zweiten Dividende.']])],'two-stage'),
 q('28','practice','b c','A company is expected to grow dividends at 20% for three years, followed by stable growth of 3%; required return is 10%. The high initial growth rate:',[
 ['can be used in a finite detail phase if the later perpetual phase has justified assumptions and growth below its discount rate.','Die begrenzte erste Phase ist keine unendliche zwanzigprozentige Reihe.'],['automatically invalidates every present-value model because 20% exceeds 10%.','Die Konvergenzbedingung betrifft die unendliche Endphase.'],['allows 20% to be used in the perpetual terminal-value denominator.','Das widerspräche der angegebenen stabilen Endphase und Konvergenz.']
 ],['Die einzelnen frühen Zahlungen werden unabhängig von einer ewigen Hochwachstumsannahme diskontiert.','Der stabile Endzustand benötigt trotzdem wirtschaftliche Begründung.'],'geometric'),
 q('29','practice','b c','The dividend just paid was 2. Dividend growth for years 1–4 is 20%, 15%, 10% and 5%, followed by 3% indefinitely. Required return is 10%. Intrinsic value is closest to:',[
 ['40.96','Die konkret fortgeschriebenen Zahlungen und der Endwert am richtigen Termin werden bewertet.'],['46.91','Dies ist nur der zukünftige Fortführungswert nach Jahr vier.'],['45.82','Dies entspricht einem anderen abrupten Zwei-Phasen-Fall.']
 ],[F('V_4=3{,}1878(1{,}03)/0{,}07=46{,}9062,\\quad V_0=2{,}4/1{,}1+2{,}76/1{,}1^2+3{,}036/1{,}1^3+(3{,}1878+46{,}9062)/1{,}1^4=40{,}9587','Die Jahresraten wirken jeweils auf die eigene Vorjahresbasis.',[['V_4,V_0','Endwert und heutiger Wert der angegebenen Reihe.']])],'transition'),
 q('30','practice','a b c','At the end of year 2, common book equity is 112.36. Beginning in year 3, ROE is 10% on beginning book equity and the retention ratio is 30%. There are no other equity changes. The first stable dividend D3 is:',[
 ['7.8652','Gewinn 11,236 mal Ausschüttungsquote siebzig Prozent.'],['9.8262','Dies könnte die alte höhere Dividende 9,54 mit neuem Wachstum fortschreiben und den ROE-Wechsel ignorieren.'],['11.2360','Dies schüttet trotz dreißig Prozent Einbehaltung den gesamten Gewinn aus.']
 ],[F('D_3=112{,}36\\cdot0{,}10\\cdot0{,}70=7{,}8652','Die stabile Zahlung wird aus den neuen Kapitalrendite- und Ausschüttungsannahmen berechnet.',[['D_3','Dividende des dritten Jahres.']])],'terminal-normalization'),
 q('31','practice','a b','FCFF is 40 in year 1 and 50 in year 2. The first stable FCFF in year 3 is 54 and grows at 3% thereafter. WACC is 10%. Excess separate cash is 20, debt is 150, preferred equity is 30 and non-controlling interests are 20, all at appropriate values. There are 10 identical common shares. Intrinsic common value per share is closest to:',[
 ['53.52','Der operative Barwert wird nach Anspruchsbrücke durch die aktuelle Stammaktienzahl geteilt.'],['71.52','Dies dividiert den operativen Gesamtwert ohne die übrigen Ansprüche abzugrenzen.'],['77.14','Dies dividiert einen zukünftigen operativen Fortführungswert ungeprüft durch Stammaktien.']
 ],[F('V_{op,0}=40/1{,}1+(50+54/0{,}07)/1{,}1^2=715{,}2302,\\quad v_0=(715{,}2302+20-150-30-20)/10=53{,}5230','Endwert, heutiger operativer Wert und heutiger Stammaktionärswert sind drei verschiedene Rechenschritte.',[['V_{op,0}','Heutiger operativer Wert.'],['v_0','Heutiger Wert je Stammaktie.']])],'negative'),
 q('32','practice','a b c','An equity claim requires a contribution of 5 at the end of year 1. It delivers FCFE of 4 at the end of year 2, followed by 3% annual growth. Required return is 12%, with no dilution or other claims. Intrinsic value today is closest to:',[
 ['35.22','Der Beitrag wird negativ erfasst, danach die positiven Zahlungen samt Endwert.'],['39.68','Dies lässt den frühen benötigten Kapitaleinsatz aus.'],['44.15','Dies erfasst den Kapitaleinsatz fälschlich als positive Auszahlung.']
 ],[F('E_0=-5/1{,}12+(4+4\\cdot1{,}03/0{,}09)/1{,}12^2=35{,}2183','Ein späterer positiver Wert beseitigt nicht den früheren Finanzierungsbedarf.',[['E_0','Heutiger Eigenkapitalwert des Anspruchs.']])],'negative'),
 q('33','practice','a b c','A claim pays 20 at the end of year 1 and a final 30 at the end of year 2. The model’s appropriate period-specific discount rates are 8% for the first year and 10% for the second. No other payments remain. Present value is closest to:',[
 ['43.77','Die zweite Zahlung wird mit beiden aufeinanderfolgenden Periodenfaktoren abgezinst.'],['42.98','Dies verwendet zehn Prozent auch für die erste Jahresperiode.'],['44.24','Dies verwendet acht Prozent auch für die zweite Jahresperiode.']
 ],[F('V_0=20/1{,}08+30/(1{,}08\\cdot1{,}10)=43{,}7710','Die Faktoren wirken bis zum jeweiligen Zahlungstermin.',[['V_0','Heutiger Anspruchswert.']])],'negative'),
 q('34','practice','a b','Beginning common book equity is 200, income available to common holders is 12 and required equity return is 8%. Residual income is:',[
 ['−4.00','Der Gewinn zwölf liegt vier unter der Eigenkapitalbelastung sechzehn.'],['12.00','Dies ist Gewinn vor Eigenkapitalbelastung.'],['28.00','Dies addiert statt subtrahiert die kalkulatorischen Kosten.']
 ],[F('RI=12-0{,}08\\cdot200=-4','Positive Gewinne können unterhalb der geforderten Verzinsung liegen.',[['RI','Residualgewinn dieser Periode.']])],'residual-charge'),
 q('35','practice','a b','Under clean surplus with no other owner transactions, beginning book equity is 100, net income is 15 and the dividend is 9. End book equity is:',[
 ['106.00','Gewinn wird addiert und die Ausschüttung abgezogen.'],['124.00','Dies addiert die ausgeschütteten Mittel zum Buchwert.'],['100.00','Dies ignoriert den einbehaltenen Gewinn.']
 ],[F('B_1=100+15-9=106','Die Beziehung verbindet Ergebnis, Dividende und verbleibendes Buchkapital.',[['B_1','Endbuchwert.']])],'clean-surplus'),
 q('36','practice','a b','A finite residual-income model explicitly forecasts through year T. Its remaining-value term, in addition to current book equity and discounted residual incomes, is:',[
 ['the discounted difference between terminal equity value and terminal book equity.','Der zukünftige Buchwert ist in der algebraischen Zerlegung bereits abgegrenzt.'],['the full terminal equity value without subtracting terminal book equity.','Dies zählt den Buchkapitalteil zusätzlich zum bereits verwendeten Anfangsbuchwert.'],['all dividends plus all FCFE for every remaining period.','Dies vermischt alternative Darstellungen derselben Vorteile.']
 ],['Die Clean-Surplus-Teleskopsumme lässt einen negativen diskontierten Endbuchwert übrig.','Mit dem übrigen Aktienwert wird daraus der diskontierte Wert über Buchwert.'],'clean-surplus'),
 q('37','practice','a b c','Current book equity is 100. Residual incomes for years 1 and 2 are 5 and 5.3; after year 2, value equals book equity because ROE equals required return permanently. Required return is 10%. Intrinsic value is closest to:',[
 ['108.93','Anfangsbuchwert plus die zwei abgezinsten Überschüsse.'],['8.93','Dies lässt den Anfangsbuchwert aus.'],['221.29','Dies könnte den zukünftigen Buchwert 112,36 zusätzlich ungezinst addieren.']
 ],[F('V_0=100+5/1{,}1+5{,}3/1{,}1^2=108{,}9256','Der nach Jahr zwei verbleibende Überschuss über Buchwert ist null, nicht der gesamte Geschäftswert.',[['V_0','Heutiger Eigenkapitalwert.']])],'equivalence-case'),
 q('38','practice','a b','Beginning book equity is 100, reported income is 10 and a dividend of 10 is paid. A separate direct-to-equity loss of 5 makes end book equity 95. Required return is 10% and the remaining claim after this year is worth exactly 95. Present value is closest to:',[
 ['95.45','Dividende zehn plus verbleibender Anspruch 95, beide diskontiert.'],['100.00','Dies ignoriert den direkt gebuchten Verlust bei einer vereinfachten unbereinigten RI-Rechnung.'],['104.55','Dies erfasst den Verlust in der falschen Richtung.']
 ],[F('V_0=(10+95)/1{,}1=95{,}4545,\\quad NI^{*}=95-100+10=5,\\quad RI^{*}=5-10=-5','Die bereinigte Fortschreibung ergibt ebenfalls hundert minus fünf geteilt durch 1,1.',[['V_0','Wert im isolierten Kontrollfall.'],['NI^{*},RI^{*}','Für diese Buchwertfortschreibung bereinigtes Ergebnis und Residualgewinn.']])],'clean-surplus'),
 q('39','practice','a b c','Current common book equity is 100. Next-year residual income is 1, expected to grow by 4% indefinitely. Required return is 8% and the clean-surplus and boundary assumptions hold. Intrinsic equity value is:',[
 ['125.00','Anfangsbuchwert plus kapitalisierte Residualgewinnreihe fünfundzwanzig.'],['25.00','Dies lässt den Anfangsbuchwert aus.'],['112.50','Dies ignoriert das Wachstum des Residualgewinns.']
 ],[F('V_0=100+1/(0{,}08-0{,}04)=125','Das Wachstum betrifft hier ausdrücklich Residualgewinne.',[['V_0','Heutiger Eigenkapitalwert.']])],'continuing-ri'),
 q('40','practice','b c','A perpetual growth assumption of 9.9% is below a 10% required return. The most accurate assessment is that:',[
 ['mathematical convergence alone does not establish economic plausibility; market size, investment and persistent returns need scrutiny.','Ein positiver kleiner Nenner ist kein Nachweis tragfähiger ewiger Annahmen.'],['the assumption must be sound because the denominator is positive.','Die Ungleichung genügt mathematisch, nicht wirtschaftlich.'],['the resulting value is insensitive because both numbers are close.','Ein enger Abstand verstärkt die Empfindlichkeit.']
 ],['Stabile Reinvestition, absolute Geschäftsdimension und Wettbewerb begründen die Endphase.','Bei kleinem Nenner können geringe plausible Änderungen das Urteil wesentlich verändern.'],'sensitivity'),
 q('41','practice','b d','A preferred stock is non-callable and non-convertible. Before using the perpetual dividend formula, the analyst must also establish that:',[
 ['the contract has a perpetual fixed payment structure and the discount rate and payment timing are appropriate.','Nicht kündbar und nicht wandelbar legen allein noch keine ewige feste Zahlungsreihe fest.'],['the stated nominal amount is always the current intrinsic value.','Der Bezugsbetrag definiert Rechte, nicht automatisch den heutigen Marktwert.'],['preferred dividends are necessarily risk-free.','Vorrang vor Stammkapital beseitigt Zahlungsrisiko nicht.']
 ],['Eine feste Endfälligkeit oder veränderliche Dividende erfordert ein anderes Zahlungsmodell.','Die Renditeforderung gehört zum tatsächlichen Vorzugsanspruch.'],'preferred'),
 q('42','practice','b d','A non-callable, non-convertible perpetual preferred share is expected to pay a fixed annual dividend of 5, beginning in one year. Required preferred return is 8%. Intrinsic value is:',[
 ['62.50','Fünf geteilt durch acht Prozent.'],['100.00','Dies könnte der Nominalbetrag sein, bestimmt aber nicht automatisch den Wert.'],['40.00','Dies vertauscht Dividende und Rendite in der Kapitalisierung.']
 ],[F('V_{PS}=5/0{,}08=62{,}50','Der Wert ist der Barwert der konstanten ewigen Reihe.',[['V_{PS}','Heutiger Vorzugsaktienwert.']])],'preferred'),
 q('43','practice','b d','A perpetual non-callable, non-convertible preferred share has contractual nominal amount 100 and a fixed annual dividend rate of 6% on that amount. Required return is 8%, and the first dividend is in one year. Intrinsic value is:',[
 ['75.00','Vertragszahlung sechs wird mit acht Prozent kapitalisiert.'],['100.00','Dies setzt Nominalbetrag und Wert gleich.'],['133.33','Dies kehrt Dividenden- und Renditesatz um.']
 ],[F('D_{PS}=100\\cdot0{,}06=6,\\qquad V_{PS}=6/0{,}08=75','Der feste Vertragsprozentsatz wird zunächst in einen Geldbetrag umgewandelt.',[['D_{PS}','Jahresdividende.'],['V_{PS}','Heutiger Wert.']])],'preferred'),
 q('44','practice','b d','A perpetual preferred share pays 1.50 each quarter, beginning in exactly one quarter. Required effective annual return is 8%. With all payments expected, intrinsic value is closest to:',[
 ['77.21','Die Jahresquote wird in eine effektive Quartalsrendite umgerechnet.'],['75.00','Dies bewertet sechs erst am Jahresende oder behandelt die effektive Jahresquote als nominale Quote.'],['18.75','Dies verwendet eine einzelne Quartalszahlung mit dem ganzen Jahressatz.']
 ],[F('k_q=1{,}08^{1/4}-1,\\quad V_{PS}=1{,}50/k_q=77{,}2139','Zahlungsfrequenz und Diskontierungsperiode werden abgestimmt.',[['k_q','Effektive Quartalsrendite.'],['V_{PS}','Heutiger Vorzugswert.']])],'preferred-timing'),
 q('45','practice','b d','A non-callable, non-convertible preferred share has five remaining annual dividends of 5 and contractual redemption of 100 with the final dividend. Required return is 8%. Intrinsic value is closest to:',[
 ['88.02','Endliche Dividendenreihe und Rückzahlung werden separat bewertet.'],['62.50','Dies bewertet eine ewige Zahlung ohne Rückzahlung.'],['119.96','Dies addiert die künftige Rückzahlung ohne Diskontierung.']
 ],[F('V_{PS}=5(1-1{,}08^{-5})/0{,}08+100/1{,}08^5=88{,}0219','Die Rückzahlung verändert die Vertragsreihe materiell.',[['V_{PS}','Wert des endlichen Vorzugsanspruchs.']])],'preferred-timing'),
 q('46','practice','d','A preferred share pays 5 in one year and is certain, under the specified simplified scenario, to be called immediately after that dividend for 80. Required return is 5%. Its value under this scenario is closest to:',[
 ['80.95','Die erste Zahlung und der Kündigungsbetrag werden gemeinsam diskontiert.'],['100.00','Dies verwendet die ewige Dividendenreihe trotz festgelegter Kündigung.'],['80.00','Dies ignoriert die Dividende und die zeitliche Diskontierung.']
 ],[F('V_{call}=(5+80)/1{,}05=80{,}9524','Der Kündigungsbetrag liegt am späteren Termin; er ist keine strikte heutige Kursobergrenze.',[['V_{call}','Heutiger Wert unter der vorgegebenen sicheren Kündigungsfolge.']])],'contingencies'),
 q('47','practice','d','A preferred share can voluntarily be converted immediately into two common shares worth 40 each, surrendering all preferred rights. The value of retaining the non-converted claim is 70. Assuming frictionless immediate choice and enforceable rights, the convertible claim must be worth:',[
 ['at least 80, although future option flexibility may make its full value higher.','Die sofort verfügbare günstigere Alternative liefert die Untergrenze.'],['exactly 150 because both claims are received.','Wandlung gibt den bisherigen Vorzug auf.'],['exactly 70 because the issuer’s preferred dividend is fixed.','Das zusätzliche Wandlungsrecht wird ignoriert.']
 ],[F('CV=2\\cdot40=80,\\quad V_{choice}\\geq\\max(70,80)','Das Maximum der sofortigen Alternativen ist nicht zwingend der vollständige Optionswert.',[['CV','Sofortiger Wandlungswert.'],['V_{choice}','Wert des freiwilligen Wahlanspruchs.']])],'contingencies'),
 q('48','practice','d','Cumulative preferred dividends have been omitted for two years. The cumulative feature most directly implies that:',[
 ['contractual arrears may need to be satisfied before common distributions, but timing and payment ability must still be analyzed.','Nachholrang ist keine sichere sofortige Zahlung.'],['all omitted dividends must already be treated as cash received today.','Zeitpunkt und Erfüllung bleiben offen.'],['the value cannot be affected by issuer distress.','Auch kumulative Rechte benötigen wirtschaftliche Erfüllungsfähigkeit.']
 ],['Ein Nachholrecht verändert die Vertragszahlungen und ihre Reihenfolge.','Es beseitigt weder Diskontierung noch Ausfall- oder Aufschubrisiko.'],'contingencies'),
 q('49','practice','d','A preferred dividend resets with a reference rate every year. The most accurate valuation approach is to:',[
 ['model the reset terms and expected conditional cash flows with appropriate risk and timing.','Die konkrete variable Zahlungsstruktur wird abgebildet.'],['capitalize today’s dividend as a guaranteed fixed perpetual payment.','Dies unterstellt eine andere Vertragsreihe.'],['use the common share’s dividend growth rate without examining the contract.','Stamm- und Vorzugsansprüche haben verschiedene Rechte.']
 ],['Referenzsatz, Zuschlag, Grenzen und Resettermine bestimmen die Zahlung.','Eine feste ewige Reihe ist für diesen Vertrag nicht ohne Begründung passend.'],'contingencies'),
 q('50','practice','d','Holding all other contractual features fixed, granting the issuer an additional economically valuable call option on preferred shares most likely:',[
 ['reduces investor value relative to the identical non-callable claim.','Der Emittent kann günstige Fortsetzungsvorteile des Investors beenden.'],['increases investor value because the issuer receives flexibility.','Die Flexibilität gehört dem Emittenten, nicht automatisch dem Anleger.'],['has no value effect because today’s dividend remains unchanged.','Künftige bedingte Zahlungen können sich trotz gleicher heutiger Zahlung ändern.']
 ],['Die Richtung gilt beim Vergleich ansonsten identischer Ansprüche.','Ein abweichender Dividendensatz oder Kündigungspreis muss gesondert verglichen werden.'],'contingencies'),
 q('a1','mock-a','a b c','A company forecasts FCFF of 30 and 42 in years 1 and 2. At year 3 it reaches stable NOPAT of 60, ROIC of 12% and growth of 3%. Constant appropriate WACC is 9%. Excess cash is 12, debt value 140 and preferred value 25; no other claims exist. With 8 common shares, intrinsic common value per share is closest to:',[
 ['67.64','Der stabile FCFF berücksichtigt Reinvestition, der Endwert wird diskontiert und die Anspruchsbrücke durchgeführt.'],['93.94','Dies kapitalisiert den gesamten stabilen NOPAT ohne Wachstumskapitalbindung.'],['86.77','Dies dividiert den heutigen operativen Gesamtwert ohne Anspruchsbrücke durch Stammaktien.']
 ],[F('FCFF_3=60(1-0{,}03/0{,}12)=45,\\quad V_{op,2}=45/(0{,}09-0{,}03)=750','Die erste stabile Zahlung gehört in Jahr drei.',[['FCFF_3','Stabiler operativer Cashflow.'],['V_{op,2}','Operativer Endwert nach Jahr zwei.']]),F('V_{op,0}=30/1{,}09+(42+750)/1{,}09^2=694{,}1335,\\quad v_0=(V_{op,0}+12-140-25)/8=67{,}6417','Operativer Wert und Stammaktionärswert werden erst nach Diskontierung abgegrenzt.',[['V_{op,0}','Heutiger operativer Wert.'],['v_0','Wert je Stammaktie.']])],'negative'),
 q('a2','mock-a','a b c','An analyst discounts all dividends through year 4 and obtains their present value. A clean-surplus RI model has the same beginning book equity and annual assumptions. At year 4, estimated equity value is 150 and book equity is 120. To reconcile the RI model with the same DDM, the remaining RI-model term is:',[
 ['30 discounted from year 4 to today.','Im RI-Modell bleibt der Endwert über Endbuchwert.'],['150 added to current book equity without discounting.','Dies erfasst Kapital doppelt und ignoriert den Termin.'],['zero because the dividend stream has four explicit observations.','Ein positiver Restwert über Buchwert verschwindet nicht durch eine kurze Detailphase.']
 ],[F('R_0=(150-120)/(1+k_e)^4','Die endliche Clean-Surplus-Zerlegung macht denselben verbleibenden Anspruch vergleichbar.',[['R_0','Heutiger Restterm im RI-Modell.'],['k_e','Die für beide Modelle konsistent verwendeten Eigenkapitalkosten.']])],'clean-surplus'),
 q('a3','mock-a','b d','A non-callable, non-convertible perpetual preferred share pays 2 at the end of each half-year, beginning in six months. Its required return is a nominal annual 10% compounded semiannually. Intrinsic value is:',[
 ['40.00','Der Periodensatz fünf Prozent passt zur Halbjahresdividende zwei.'],['40.98','Dies würde eine effektive Jahresrendite zehn Prozent unterstellen.'],['20.00','Dies verwendet den ganzen nominalen Jahressatz für eine Halbjahreszahlung.']
 ],[F('k_{1/2}=0{,}10/2=5\\%,\\quad V_{PS}=2/0{,}05=40','Die Aufgabenstellung nennt ausdrücklich eine nominale Jahresquote.',[['k_{1/2}','Rendite je Halbjahresperiode.'],['V_{PS}','Heutiger Vorzugswert.']])],'preferred-timing'),
 q('b1','mock-b','a b c','A company has book equity of 80. In year 1 its ROE is 15% on beginning book equity and retention is 50%. From year 2 onward ROE equals the constant required equity return of 10%, with retention 20%. Clean surplus holds and no other transactions occur. Intrinsic equity value today is closest to:',[
 ['83.64','Nur der erste Residualgewinn liegt über der Kapitalbelastung; der Endwert ab danach entspricht Buchwert.'],['120.00','Dies kapitalisiert den ersten Gewinn zwölf ohne die zeitlich begrenzte Überrendite zu berücksichtigen.'],['86.00','Dies ist der zukünftige Endbuchwert und nicht der heutige Gesamtwert.']
 ],[F('NI_1=12,\\quad D_1=6,\\quad B_1=86,\\quad RI_1=12-0{,}10\\cdot80=4','Die hohe Rentabilität gilt nur im ersten Jahr.',[['NI_1,D_1,B_1,RI_1','Gewinn, Dividende, Endbuchwert und Residualgewinn.']]),F('D_2=86\\cdot0{,}10\\cdot0{,}80=6{,}88,\\quad V_1=6{,}88/(0{,}10-0{,}02)=86,\\quad V_0=(6+86)/1{,}1=80+4/1{,}1=83{,}6364','Dividenden- und Residualgewinnweg stimmen überein.',[['D_2','Erste stabile Dividende.'],['V_1,V_0','Verbleibender Wert nach Jahr eins und heutiger Wert.']])],'equivalence-case'),
 q('b2','mock-b','b d','A preferred share has a fixed payment of 4 next year. Immediately after that payment, the investor may either keep a claim worth 70 or exercise an enforceable put for 90. Under the given certain one-year scenario, appropriate annual required return is 8% and no costs arise. Value today is closest to:',[
 ['87.04','Nach der Dividende wird die größere verfügbare Alternative neunzig gewählt und mitdiskontiert.'],['64.81','Dies ignoriert Dividende und wertvolles Rückgaberecht.'],['151.85','Dies addiert beide einander ausschließenden Endalternativen.']
 ],[F('V_0=(4+\\max(70,90))/1{,}08=87{,}0370','Das Wahlrecht verändert die spätere Leistung, ohne beide Alternativen gleichzeitig zu liefern.',[['V_0','Heutiger Wert der konkret vorgegebenen sicheren Folge.']])],'contingencies'),
 q('b3','mock-b','a b c','An analyst forecasts positive growth of 4% indefinitely with next-year operating after-tax income of 80, ROIC of 10% and WACC of 9%. The analyst capitalizes all 80 at WACC minus growth, omitting reinvestment. With the stable capital-productivity assumptions holding, the correct operating value is:',[
 ['960.00','Vierzig Prozent des Gewinns werden für Wachstum gebunden; FCFF beträgt achtundvierzig.'],['1,600.00','Dies ist die Rechnung ohne notwendige Reinvestition.'],['888.89','Dies kapitalisiert den ganzen Gewinn als Nullwachstumszahlung und mischt die Annahmen.']
 ],[F('\\eta=0{,}04/0{,}10=40\\%,\\quad FCFF_1=80(1-0{,}40)=48,\\quad V_{op}=48/(0{,}09-0{,}04)=960','Der Wachstumsnutzen benötigt unter den ausdrücklich genannten Annahmen Kapitalbindung.',[['\\eta','Erforderliche Reinvestitionsquote.'],['FCFF_1','Nächster operativer freier Cashflow.'],['V_{op}','Operativer Wert.']])],'reinvestment')
];
