const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('eqr-'+id,'equity-returns','equity',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','A company has paid an ordinary cash dividend each year for a decade. This history most accurately indicates:',[
 ['an established payout pattern, but not a guarantee of every future dividend.','Eine Gewohnheit oder Markterwartung ersetzt keinen zukünftigen Beschluss.'],['an unconditional contractual obligation to maintain that dividend forever.','Für gewöhnliche Stammaktiendividenden folgt daraus keine solche Verpflichtung.'],['that the dividend can never be financed from previously accumulated cash.','Historie legt die Finanzierungsquelle nicht zwingend fest.']
 ],['Regelmäßige Ausschüttungen können Erwartungen prägen.','Tragfähigkeit und tatsächlich beschlossene Zahlungen sind separat zu prüfen.'],'forms'),
 q('02','practice','a','A company sells its remaining assets and distributes the proceeds while winding down. The distribution is best interpreted as:',[
 ['a liquidation distribution that need not indicate sustainable recurring earnings.','Bei Abwicklung wird Vermögen zurückgegeben.'],['proof that the same dividend can be maintained indefinitely.','Nach Abwicklung besteht möglicherweise kein fortdauerndes Geschäft.'],['a stock split because shareholders receive something from the company.','Eine Vermögensausschüttung ist keine reine Umstückelung.']
 ],['Zahlungsgröße und nachhaltige Ertragskraft sind verschiedene Informationen.','Künftige Investitionsmöglichkeiten und verbleibende Vermögenswerte sind nach der Abwicklung anders.'],'forms'),
 q('03','practice','a','A proportional dividend of additional identical shares in the same company, with no cash component, directly:',[
 ['increases share counts without by itself increasing proportional owners’ wealth.','Gleicher Wert verteilt sich auf mehr identische Stücke.'],['gives each shareholder a cash return equal to the percentage of new shares.','Zusätzliche eigene Aktien sind hier keine Bardividende.'],['reduces the proportional interest of every shareholder by the same percentage.','Proportionale Ausgabe an alle lässt relative Quoten gleich.']
 ],['Eine Ausschüttung von Aktien einer anderen Gesellschaft wäre gesondert zu analysieren.','Die Frage beschreibt ausdrücklich zusätzliche identische eigene Aktien.'],'stock-dividend'),
 q('04','practice','b c','Immediately after a normal dividend goes ex, but before payment, a qualifying holder sells the stock. The detached dividend receivable is not included in the ex-price. To measure the holder’s wealth correctly, the analyst should:',[
 ['include the dividend receivable once, separately from the sale proceeds.','Der Verkäufer behält hier den zuvor abgetrennten Anspruch.'],['discard the receivable because the shares have been sold.','Der normale Ex-Verkauf überträgt diesen Anspruch gerade nicht.'],['count the receivable at ex-date and add it again as new wealth at payment.','Die Zahlung ersetzt den Anspruch; sie erzeugt keinen zweiten Ertrag.']
 ],['Anspruch und Bargeld sind zwei zeitliche Formen derselben Ausschüttung.','Die ursprüngliche Aktie darf nicht zugleich cum und mit zusätzlichem separaten Anspruch bewertet werden.'],'wealth'),
 q('05','practice','b','The date on which the company announces a specific dividend and its terms is the:',[
 ['declaration date.','Dies ist der Bekanntgabe- beziehungsweise Beschlusstag.'],['payment date.','Dies ist der Tag der vorgesehenen Auszahlung.'],['ex-dividend date.','Dies ist der erste Handelstag ohne den betreffenden Anspruch.']
 ],['Eine Ankündigung ist nicht automatisch eine sofortige Auszahlung.','Der konkrete Beschluss enthält weitere relevante Termine.'],'dates'),
 q('06','practice','b','The dividend record date primarily identifies:',[
 ['the register snapshot used for dividend allocation, subject to applicable transfer and settlement rules.','Registerbasis und endgültige wirtschaftliche Zuordnung müssen zusammenpassen.'],['the first trading day without the dividend in every jurisdiction and every type of distribution.','Das kann im Standardfall zusammenfallen, ist aber keine universelle Definition.'],['the date cash must already have reached every beneficial owner’s bank account.','Dies verwechselt Stichtag und tatsächliche Zahlungsweiterleitung.']
 ],['Ex-Tag, Registerstichtag und Auszahlung besitzen verschiedene Funktionen.','Besondere Weiterleitungsregeln können relevant bleiben.'],'dates'),
 q('07','practice','b','For an ordinary US cash dividend, Friday is the announced record date and ex-date. There are no holidays and trades settle T+1. The last purchase day carrying this dividend is:',[
 ['Thursday.','Ein Donnerstaggeschäft wird Freitag abgewickelt und liegt vor dem Ex-Tag.'],['Friday.','Der Kauf am Ex-Tag enthält das abgetrennte Recht nicht.'],['Wednesday.','Dies zieht im beschriebenen T+1-Fall einen Geschäftstag zu viel ab.']
 ],['T+1 ist der ausdrücklich angegebene Rahmen.','Der Käufer darf einen alten T+2-Merksatz nicht auf diesen Fall anwenden.'],'settlement'),
 q('08','practice','b','An investor owns a stock before the ex-date for a normal cash dividend and sells it on the announced ex-date. No special due-bill rule applies. The investor:',[
 ['retains the detached dividend entitlement despite selling before payment.','Der Ex-Verkauf erfolgt ohne den bereits abgetrennten Anspruch.'],['must keep the stock until payment to receive the dividend.','Dies verwechselt Besitz der Aktie mit Besitz des abgetrennten Anspruchs.'],['transfers the dividend automatically because cash has not yet arrived.','Der fehlende Kontoeingang ändert den vereinbarten Ex-Status nicht.']
 ],['Für die Zuordnung ist der Handel mit oder ohne Recht entscheidend.','Der Zahlungstag ist im normalen Fall nicht die letzte notwendige Aktienhaltefrist.'],'settlement'),
 q('09','practice','b','Tuesday is the announced ex-date and record date for an ordinary US dividend. Monday is a settlement holiday, and the preceding Friday is a business day. A Friday purchase settles T+1 on Tuesday. The purchaser:',[
 ['receives this dividend because the purchase is before the ex-date under the stated rules.','Der Geschäftskalender führt das Freitaggeschäft bis zum Dienstag.'],['does not receive it because T+1 means Saturday settlement.','T+1 zählt Geschäftstage, nicht jeden Kalendertag.'],['must buy on Tuesday instead to qualify.','Ein Kauf erst am angegebenen Ex-Tag wäre ohne diesen Anspruch.']
 ],['Die Frage gibt Handelskalender und Termine vor.','Beides ist gemeinsam zu verwenden.'],'settlement'),
 q('10','practice','a b','A special distribution notice specifies payment on Tuesday and ex-date on Wednesday. A registered holder receives the distribution and sells on Tuesday in a trade that carries the distribution right. The holder should:',[
 ['recognize the required onward transfer of the distribution under the stated rules.','Der Verkauf erfolgt noch mit dem Recht.'],['retain both the distribution and the full cum-distribution sale proceeds without any obligation.','Dies lässt die ausdrücklich festgelegte Weiterleitung weg.'],['treat Wednesday as the payment date regardless of the notice.','Angegebene Zahlungs- und Ex-Termine dürfen nicht vertauscht werden.']
 ],['Ein Due Bill kann die Registerzahlung dem wirtschaftlich berechtigten Käufer zuordnen.','Ein zunächst sichtbarer Zahlungseingang ist nicht zwingend endgültiger eigener Ertrag.'],'exceptions'),
 q('11','practice','a b','An analyst claims every dividend described as “special” must have an ex-date after its payment date worldwide. The most accurate assessment is:',[
 ['the claim is too broad; the market’s rules and the actual distribution terms must be checked.','Bezeichnung allein und ein US-Sonderfall sind keine universelle Regel.'],['the claim is correct because “special” legally means at least 25% in every market.','Diese weltweite Begriffsdefinition existiert hier nicht.'],['the claim is correct because special distributions never have a record date.','Auch besondere Maßnahmen können Registerstichtage besitzen.']
 ],['Einmaligkeit und die konkreten Abwicklungsbedingungen sind verschiedene Merkmale.','Die angekündigten Termine und anwendbaren Regeln bestimmen den Fall.'],'exceptions'),
 q('12','practice','b c','A share trades cum-dividend at 40. A dividend of 1 detaches, and positive new information results in an ex-price of 42. Ignoring discounting, costs and taxes, the total return over this event is:',[
 ['7.50%','Endwert ist 42 Aktienwert plus ein separater Anspruch gegenüber vierzig.'],['5.00%','Dies ist nur die Kursrendite und lässt die Dividende aus.'],['2.50%','Dies ist nur der Dividendenbeitrag.']
 ],[F('R=\\frac{42+1-40}{40}=7{,}50\\%','Neue Informationen können den theoretischen Dividendenabschlag überlagern.',[['R','Gesamtrendite einschließlich des abgetrennten Anspruchs.']])],'exprice'),
 q('13','practice','a b','A stock is worth 75 including an imminent certain dividend of 3. With no taxes, costs, discounting or other information, its theoretical ex-dividend price is:',[
 ['72','Drei Anspruch werden aus dem gehandelten Aktienpaket abgetrennt.'],['75','Dies ließe den Anspruch gleichzeitig im Aktienwert und separat bestehen.'],['78','Die Dividende wird hier nicht zusätzlich als neues Vermögen geschaffen.']
 ],[F('P_{ex}=75-3=72','Der berechtigte Anleger hält außerdem den Dividendenanspruch.',[['P_{ex}','Theoretischer Preis ohne den abgetrennten Anspruch.']])],'exprice'),
 q('14','practice','a c','A stock price is 60, annual dividend per share is 3 and annual EPS is 5. The dividend yield is:',[
 ['5.00%','Drei werden durch den Preis sechzig geteilt.'],['60.00%','Dies ist die Ausschüttungsquote, drei geteilt durch fünf.'],['8.33%','Dies ist die Ergebnisrendite, fünf geteilt durch sechzig.']
 ],[F('y_D=\\frac3{60}=5\\%','Der Renditenenner ist der Aktienpreis.',[['y_D','Dividendenrendite auf der angegebenen Jahresbasis.']])],'yield'),
 q('15','practice','a','For annual dividend per share of 3 and matching annual EPS of 5, the dividend payout ratio is:',[
 ['60.00%','Drei von fünf Ergebnis je Aktie werden ausgeschüttet.'],['166.67%','Dies dreht den Quotienten um.'],['40.00%','Dies ist die rechnerisch einbehaltene Quote.']
 ],[F('p=\\frac35=60\\%','Die Aussage ist von der Dividendenrendite auf den Aktienpreis zu unterscheiden.',[['p','Ausschüttungsquote bei positivem EPS.']])],'yield'),
 q('16','practice','a c','A stock trades at 30. Last year’s dividend was 3, but the analyst forecasts 1.20 for the next year. The forecast dividend yield is:',[
 ['4.00%','Für eine Prognoserendite wird die prognostizierte Dividende verwendet.'],['10.00%','Dies ist die historische Dividendenrendite.'],['6.00%','Dies verwendet den Rückgang der Dividende als Renditezähler.']
 ],[F('y_D=\\frac{1{,}20}{30}=4\\%','Historischer und prognostizierter Zähler beantworten unterschiedliche Fragen.',[['y_D','Prognostizierte Dividendenrendite.']])],'yield'),
 q('17','practice','a','A firm has 24 million shares outstanding and completes a 120 million cash repurchase at 30 per share. The acquired shares cease to be outstanding, and no new shares are issued. Remaining shares outstanding, in millions, are:',[
 ['20','Vier Millionen Aktien werden zurückgekauft.'],['28','Dies behandelt den Rückkauf als Neuemission.'],['4','Dies ist nur die gekaufte Menge.']
 ],[F('N_1=24-\\frac{120}{30}=20','Budget durch Ausführungspreis ergibt die eingezogene ausstehende Menge.',[['N_1','Nach dem Rückkauf ausstehende Aktien in Millionen.']])],'repurchases'),
 q('18','practice','a','An investor retains 0.96 million shares while a repurchase reduces total shares outstanding from 24 million to 20 million. The investor’s ownership percentage afterward is:',[
 ['4.80%','Unveränderter eigener Bestand wird durch die kleinere Gesamtzahl geteilt.'],['4.00%','Dies ist die vorherige Quote.'],['20.00%','Dies verwechselt die Veränderung des Nenners mit dem eigenen Eigentumsanteil.']
 ],[F('q_1=\\frac{0{,}96}{20}=4{,}80\\%','Die größere Quote allein beweist keinen Wertzuwachs.',[['q_1','Anteil an den nach Rückkauf ausstehenden Aktien.']])],'repurchases'),
 q('19','practice','a','A company has fair equity value of 1,200 million including excess cash and 20 million shares. It spends 240 million buying shares at the fair price of 60. Ignoring all other effects, fair value per remaining share is:',[
 ['60.00','960 Millionen verbleibender Wert werden von sechzehn Millionen Aktien getragen.'],['75.00','Dies reduziert die Aktienzahl, lässt aber die ausgegebene Kasse im Unternehmenswert.'],['48.00','Dies reduziert den Wert, lässt aber die zurückgekauften Aktien ausstehend.']
 ],[F('v_1=\\frac{1200-240}{20-240/60}=60','Bei fairem Rückkauf heben sich die proportionalen Änderungen hier auf.',[['v_1','Fairer Wert je verbleibender Aktie.']])],'buyback-value'),
 q('20','practice','a','A company has fair equity value of 1,200 million and 20 million shares. It instead spends 240 million repurchasing at 80 per share. The operating business value is unchanged and no other effects occur. Fair value per remaining share is closest to:',[
 ['56.47','Nach Abfluss der Kasse verbleiben 960 Millionen für siebzehn Millionen Aktien.'],['60.00','Ein über dem Ausgangswert gezahlter Preis ist für verbleibende Anleger nicht neutral.'],['70.59','Dies lässt die ausgegebene Kasse im Zähler.']
 ],[F('v_1=\\frac{1200-240}{20-240/80}=\\frac{960}{17}\\approx56{,}47','Überhöhter Rückkaufpreis führt im angegebenen Modell zu einem Werttransfer an Verkäufer.',[['v_1','Fairer Wert je verbleibender Aktie.']])],'buyback-value'),
 q('21','practice','a','For the full year following a repurchase, pre-repurchase net income would be 60 million and shares 12 million. A repurchase spends 120 million at 40 per share, with annual after-tax financing costs equal to 5% of the budget. No other changes occur. Post-repurchase EPS is:',[
 ['6.00','54 Millionen Ergebnis werden auf neun Millionen Aktien verteilt.'],['6.67','Dies ignoriert sechs Millionen Finanzierungskosten.'],['5.00','Dies ist das Ergebnis je Aktie ohne Rückkauf.']
 ],[F('EPS_1=\\frac{60-120\\cdot0{,}05}{12-120/40}=6','Zähler und Nenner ändern sich gemeinsam.',[['EPS_1','Ergebnis je Aktie der vollständigen Folgeperiode.']])],'eps'),
 q('22','practice','a','Before a repurchase, EPS is 3. The repurchase price is 50. In the simple full-period financing model, the after-tax annual financing cost rate that leaves EPS unchanged is:',[
 ['6.00%','Die Schwelle ist die ursprüngliche Ergebnisrendite zum Rückkaufpreis.'],['16.67%','Dies verwendet ein invertiertes Verhältnis ohne passende Interpretation.'],['3.00%','EPS ist ein Betrag je Aktie, keine Prozentquote.']
 ],[F('k^*=\\frac3{50}=6\\%','Oberhalb dieser Kostenquote sinkt EPS im angegebenen Modell; unterhalb steigt es.',[['k^*','Nachsteuerkostenquote mit unverändertem EPS.']])],'eps'),
 q('23','practice','a','For reported annual EPS, a company has 20 million shares during the first half-year and 16 million during the second half-year after a repurchase. Annual net income available to common shares is 90 million; no other share changes occur. Basic EPS is:',[
 ['5.00','Neunzig werden durch die gewichtete durchschnittliche Zahl achtzehn geteilt.'],['5.625','Dies verwendet nur die Schlussaktienzahl.'],['4.50','Dies ignoriert den Rückkauf im zweiten Halbjahr.']
 ],[F('EPS=\\frac{90}{20\\cdot0{,}5+16\\cdot0{,}5}=5','Berichtetes Jahres-EPS verwendet nicht automatisch den Endbestand.',[['EPS','Unverwässertes Ergebnis je Aktie für das ganze Jahr.']])],'eps'),
 q('24','practice','a','A firm announces a repurchase authorization and also issues employee shares. To assess the actual reduction in outstanding shares, an analyst should primarily:',[
 ['reconcile executed purchases and actual issuances rather than treating the authorization as completed.','Nur tatsächliche Bewegungen erklären den Bestand.'],['subtract the entire authorized budget from the share count directly.','Ein Geldbudget ist keine Aktienzahl und keine garantierte Ausführung.'],['assume employee issuance cannot offset any repurchase.','Neu ausgegebene Aktien können den Rückkaufeffekt kompensieren.']
 ],['Genehmigter Höchstbetrag, ausgeführte Menge und ausstehender Nettoendbestand sind getrennt zu erfassen.','Eigene Aktien sind außerdem von ausstehenden Aktien zu unterscheiden.'],'repurchases'),
 q('25','practice','a','In a frictionless model with no taxes, costs, information changes or investment-policy changes, an investor can create a desired cash flow without a dividend by:',[
 ['selling an appropriately sized part of the holding.','Ein Teilverkauf wandelt Beteiligungswert in Bargeld um.'],['counting an undeclared future dividend as current cash.','Eine Erwartung ist kein heute verfügbarer Zahlungsmittelbestand.'],['asking for a stock split and treating every additional share as cash.','Umstückelung selbst überträgt kein Bargeld.']
 ],['Die unmittelbare Modellgleichwertigkeit setzt unveränderten Gesamtwert und reibungsfreie Transaktionen voraus.','Sie behauptet keine Gleichheit sämtlicher realer Steuer- und Transaktionsfolgen.'],'policy'),
 q('26','practice','a c','An investor owns 200 shares at 75. A proportional 25% stock dividend of identical own-company shares occurs with no other value changes. The theoretical price per share afterward is:',[
 ['60.00','250 Aktien tragen weiterhin den Gesamtwert von 15.000.'],['56.25','Dies zieht fälschlich einfach 25 Prozent vom alten Preis ab.'],['75.00','Dies lässt die zusätzliche Stückzahl ohne Wertanpassung bestehen.']
 ],[F('P_1=\\frac{75}{1{,}25}=60','Die Stückzahl wächst um ein Viertel; der Preis sinkt um ein Fünftel.',[['P_1','Theoretischer Preis je Aktie nach proportionaler Ausgabe.']])],'stock-dividend'),
 q('27','practice','a c','A proportional stock dividend increases identical shares by 25% with total equity value unchanged. The theoretical percentage price decline is:',[
 ['20.00%','Der neue Preis ist eins geteilt durch 1,25 des alten Preises.'],['25.00%','Stückzuwachs und Preisrückgang haben verschiedene Nenner.'],['0.00%','Dies würde bei mehr Aktien einen unveränderten Gesamtwert verletzen.']
 ],[F('d=1-\\frac1{1{,}25}=20\\%','Der Preisabschlag wird relativ zum alten Preis berechnet.',[['d','Theoretischer relativer Preisrückgang als positive Größe.']])],'stock-dividend'),
 q('28','practice','a','Before a three-for-two split, an investor owns 80 shares at 45. With no other value changes, the new share count and price are respectively:',[
 ['120 shares and 30 per share.','Aktienzahl mal 1,5 und Preis durch 1,5 halten den Wert bei 3.600.'],['160 shares and 22.50 per share.','Dies wäre ein Zwei-für-eins-Split.'],['120 shares and 45 per share.','Dies erzeugt fälschlich zusätzliches Vermögen durch Umstückelung.']
 ],[F('n_1=80\\cdot\\frac32=120,\\qquad P_1=45\\cdot\\frac23=30','Beide Größen müssen zusammen angepasst werden.',[['n_1','Aktienzahl nach Split.'],['P_1','Theoretischer neuer Preis.']])],'splits'),
 q('29','practice','a c','A share initially costs 72. After a two-for-one split, the new shares end at 39 each. There are no dividends or costs. The investor’s price return over the full period is closest to:',[
 ['8.33%','Jede alte Aktie wurde zu zwei neuen im Gesamtwert 78.'],['−45.83%','Dies vergleicht unbereinigt eine neue mit einer alten Aktie.'],['16.67%','Dies verdoppelt den korrekt berechneten Renditeprozentsatz nochmals.']
 ],[F('R_P=\\frac{2\\cdot39-72}{72}=8{,}3333\\%','Alternativ wird der neue Kurs 39 mit dem splitbereinigten Anfangskurs 36 verglichen.',[['R_P','Kursrendite auf konsistenter Beteiligungsbasis.']])],'normalization'),
 q('30','practice','a','An investor has 800 shares at 3 before a one-for-four reverse split. With no other effects, the resulting position is:',[
 ['200 shares at 12, with unchanged total value.','Ein Viertel der Aktienzahl bei vierfachem Stückpreis.'],['3,200 shares at 0.75, with unchanged total value.','Dies wäre der umgekehrte Split.'],['200 shares at 3, implying a 75% loss solely from the split.','Dies passt den Kurs nicht an die geänderte Einheit an.']
 ],[F('n_1=800/4=200,\\qquad P_1=3\\cdot4=12','Beide Seiten ergeben einen Positionswert von 2.400.',[['n_1','Neue Aktienzahl.'],['P_1','Theoretischer neuer Stückpreis.']])],'reverse'),
 q('31','practice','a c','An investor holds 107 shares at 4 before a one-for-ten reverse split. The stated terms provide 10 whole new shares at a theoretical price of 40 plus 28 cash in lieu of the remaining fraction. Total post-action wealth is:',[
 ['428','Vierhundert Aktienwert plus achtundzwanzig Bruchteilsabfindung.'],['400','Dies lässt die Abfindung aus.'],['4,280','Dies wendet den Kursfaktor zusätzlich auf das gesamte Vermögen an.']
 ],[F('W_1=10\\cdot40+28=428','Dies entspricht 107 mal vier vor der Maßnahme.',[['W_1','Gesamtwert nach der beschriebenen Bruchteilsbehandlung.']])],'reverse'),
 q('32','practice','a c','An investor buys 60 shares at 80. A two-for-one split occurs, followed by a dividend of 1 per new share. All dividends are held as non-interest-bearing cash. New shares end at 43. Total return is:',[
 ['10.00%','120 neue Aktien zu 43 plus 120 Dividende gegenüber 4.800 Einsatz.'],['8.75%','Dies multipliziert die Dividende nur mit den sechzig alten Aktien.'],['−45.00%','Dies vergleicht den neuen Kurs samt Dividende unbereinigt mit achtzig.']
 ],[F('R_T=\\frac{120\\cdot43+120-60\\cdot80}{60\\cdot80}=10\\%','Kurs und Dividende beziehen sich auf die neue Aktienbasis.',[['R_T','Gesamtrendite inklusive gehaltener Bardividende.']])],'normalization'),
 q('33','practice','c','A provider explicitly documents that its adjusted series includes all dividends under a stated reinvestment convention. The series increases from 100 to 106. For a return using that same convention, the analyst should:',[
 ['use 6% without adding the same dividends again.','Die Ausschüttungen sind bereits Bestandteil der dokumentierten Renditereihe.'],['add dividend yield again because only prices can appear in a data series.','Auch eine synthetisch bereinigte Reihe kann Gesamtrendite abbilden.'],['infer an ordinary unadjusted share price of 106 without checking units.','Ein bereinigter Reihenwert ist nicht automatisch ein tatsächlich gehandelter Kurs.']
 ],['Die Dokumentation bestimmt, welche Anpassungen bereits enthalten sind.','Splitbereinigung allein wäre eine andere Konvention.'],'normalization'),
 q('34','practice','c','A stock is purchased at 40, pays a dividend of 3 at the end of the holding period and ends at 38. With no costs or taxes, total return is:',[
 ['2.50%','Der Kursverlust zwei wird durch die Dividende drei überkompensiert.'],['−5.00%','Dies ist nur die Kursrendite.'],['7.50%','Dies ist nur der Dividendenbeitrag.']
 ],[F('R_T=\\frac{38+3-40}{40}=2{,}50\\%','Der gesamte Endwert beträgt einundvierzig gegenüber vierzig Einsatz.',[['R_T','Gesamtrendite der Haltedauer.']])],'returns'),
 q('35','practice','c','A stock starts at 50. At the first period end it is 52 and pays a dividend of 2; at the second it is 50 and pays 3. Each dividend is reinvested immediately at the corresponding end price. Cumulative total return is closest to:',[
 ['10.08%','Die periodischen Faktoren 54/50 und 53/52 werden multipliziert.'],['10.00%','Dies entspricht hier unverzinst gehaltenen Dividenden statt Wiederanlage.'],['9.92%','Dies addiert die beiden periodischen Renditen statt sie zu verketten.']
 ],[F('R_{cum}=\\frac{54}{50}\\cdot\\frac{53}{52}-1\\approx10{,}0769\\%','Die erste Ausschüttung verändert die für Periode zwei gehaltene Stückzahl.',[['R_{cum}','Gesamtrendite mit der angegebenen Wiederanlage.']])],'reinvestment'),
 q('36','practice','a c','An investor starts with 100 shares at 20. At year one end the price is 20 and the dividend is 2; at year two end the price is 22 and the dividend is 1. All dividends are reinvested at these end prices, with fractional shares allowed and no costs. Terminal wealth is:',[
 ['2,530','Nach erster Wiederanlage bestehen 110 Aktien, deren zweiter Endwert inklusive Dividende je 23 beträgt.'],['2,500','Dies ist der Endwert bei unverzinst gehaltenen Dividenden.'],['2,420','Dies berücksichtigt den zweiten Aktienwert, aber nicht die zweite Dividende.']
 ],[F('W_2=100(1+2/20)(22+1)=2530','Eine Wiederanlage der letzten Dividende ändert ihren unmittelbaren Wert nicht.',[['W_2','Terminales Vermögen nach zwei Jahren.']])],'reinvestment'),
 q('37','practice','a c','An investor instead keeps all dividends as non-interest-bearing cash: 100 shares bought at 20, a first dividend of 2 per share, a second dividend of 1 and an end price of 22. No share changes occur. Total two-year return is:',[
 ['25.00%','2.200 Aktienwert plus 300 Bargeld gegenüber 2.000 Einsatz.'],['26.50%','Dies wäre die Wiederanlagestrategie zu den im anderen Beispiel angegebenen Preisen.'],['10.00%','Dies ignoriert alle Ausschüttungen.']
 ],[F('R_T=\\frac{100\\cdot22+100(2+1)-2000}{2000}=25\\%','Bargeld bleibt hier innerhalb der Strategie und wird nicht verzinst.',[['R_T','Gesamtrendite ohne Dividendenwiederanlage.']])],'cash-comparison'),
 q('38','practice','c','An investor buys 200 shares at 25 and sells at 27, paying a fee of 5 on each trade. The dividend is 0.50 per share, taxed at 20%; no capital gains tax or other cash flows apply. Net return on the full initial outlay is closest to:',[
 ['9.39%','Nettoüberschuss 470 wird durch den vollständigen Einsatz 5.005 geteilt.'],['9.40%','Dies verwendet den Aktienpreis ohne Kaufgebühr als Nenner.'],['8.00%','Dies ist weder der korrekt besteuerte Dividendenbeitrag noch die Gesamtnettorendite.']
 ],[F('R_{net}=\\frac{200\\cdot27-5+200\\cdot0{,}5\\cdot0{,}8-5005}{5005}\\approx9{,}3906\\%','Nur die Dividende unterliegt hier der ausdrücklich angegebenen Steuer.',[['R_{net}','Nettorendite einschließlich beider Gebühren.']])],'costs'),
 q('39','practice','c','A fully reinvested investment grows from 10,000 to 12,100 in exactly two years with no external cash flows. Its geometrically annualized return is:',[
 ['10.00%','Der jährliche Faktor 1,10 ergibt zweimal angewandt 1,21.'],['10.50%','Dies teilt die Gesamtrendite lediglich durch zwei.'],['21.00%','Dies ist die Zweijahresrendite.']
 ],[F('R_{ann}=\\sqrt{1{,}21}-1=10\\%','Annualisierung verwendet einen äquivalenten Zinseszinsfaktor.',[['R_{ann}','Geometrische jährliche Rendite.']])],'horizon'),
 q('40','practice','a b c','An investor buys 100 shares at 40. After a two-for-one split, all 200 new shares become entitled to a dividend of 1. After that entitlement detaches, 50 shares are sold at 22. The remaining 150 end at 24. Dividends and sale proceeds stay as non-interest-bearing cash, with no taxes or fees. Total return is:',[
 ['22.50%','Endvermögen ist 3.600 Restaktien plus 1.100 Verkaufserlös plus 200 Dividende.'],['25.00%','Dies bewertet auch die bereits verkauften Aktien fälschlich zum späteren Endkurs.'],['20.00%','Dies lässt hundert des zutreffenden Dividendenanspruchs aus.']
 ],[F('R=\\frac{150\\cdot24+50\\cdot22+200-4000}{4000}=22{,}50\\%','Der Ex-Verkauf hebt den schon abgetrennten Anspruch auf alle zweihundert Aktien nicht auf.',[['R','Rendite der gesamten beschriebenen Strategie.']])],'case'),
 q('a1','mock-a','a b','A custodian receives a large distribution for its registered position. Its client had already sold that position in a transaction explicitly carrying the distribution right until a later ex-date. The broker reports the receipt as spendable client profit without recognizing any onward obligation. The most accurate assessment is that:',[
 ['the report can overstate client wealth because the distribution must be allocated according to the rights transferred in the sale.','Zunächst empfangene Zahlung und endgültiger wirtschaftlicher Anspruch können auseinanderfallen.'],['the report is necessarily correct because the custodian was the registered holder.','Registerzuordnung allein löst die ausdrücklich vereinbarte Weiterleitung nicht auf.'],['the report is necessarily correct because the payment date always extinguishes all due bills.','Dies widerspricht dem beschriebenen Verkauf mit fortbestehendem Ausschüttungsrecht.']
 ],['Die maßgeblichen Bedingungen des Geschäfts bestimmen, wem die Ausschüttung wirtschaftlich zusteht.','Ein Geldzufluss ohne Berücksichtigung der dazugehörigen Verpflichtung kann den Nettowert überzeichnen.'],'exceptions'),
 q('a2','mock-a','a c','An investor buys 500 shares at 24. A proportional 20% stock dividend of identical shares occurs. The company then repurchases shares only from other owners. The investor keeps all 600 shares, receives a final cash dividend of 0.50 on each, and ends with an ex-price of 20. With no costs or taxes and no reinvestment, this investor’s total return is:',[
 ['2.50%','600 Aktien zu zwanzig plus dreihundert Dividende gegenüber 12.000 Anfangseinsatz.'],['22.50%','Dies zählt die reine Erhöhung der Stückzahl nochmals als zusätzliche Rendite.'],['a number requiring the company’s entire repurchase budget to be added to the investor’s cash flows.','Ein nicht verkaufender Anleger erhält diesen Rückkaufbetrag nicht persönlich.']
 ],[F('R=\\frac{600\\cdot20+600\\cdot0{,}50-500\\cdot24}{500\\cdot24}=2{,}50\\%','Der Rückkauf anderer Eigentümer wird nicht als eigener zusätzlicher Geldzufluss verbucht.',[['R','Gesamtrendite des beschriebenen Anlegers.']])],'returns'),
 q('b1','mock-b','a c','An investor starts with 960 shares at 3. A one-for-eight reverse split is followed by a cash dividend of 2.40 per new share. The investor holds all resulting shares until an ex-price of 25 and retains the dividend in cash. Ignoring taxes and costs, total return is closest to:',[
 ['14.17%','120 neue Aktien tragen Kurswert und Dividende auf derselben neuen Basis.'],['84.17%','Dies multipliziert die Dividende je neuer Aktie fälschlich mit den 960 alten Aktien.'],['813.33%','Dies vergleicht den neuen Stückpreis samt Dividende mit dem unbereinigten alten Preis.']
 ],[F('R=\\frac{120(25+2{,}40)-960\\cdot3}{960\\cdot3}\\approx14{,}1667\\%','Alternativ werden 27,40 je neuer Aktie mit dem angepassten Einstand 24 verglichen.',[['R','Gesamtrendite über Reverse Split und Ausschüttung.']])],'normalization'),
 q('b2','mock-b','b c','A portfolio system recognizes a normal dividend receivable when it detaches at ex-date. At payment it leaves that receivable unchanged and also adds the cash received. With unchanged stock prices and no other events, the reported payment-day gain is:',[
 ['an artificial gain caused by counting the same entitlement twice.','Die Zahlung muss den zuvor erfassten Anspruch ersetzen.'],['a valid second dividend return because ex-date and payment date are separate events.','Verschiedene Termine erzeugen keine zwei wirtschaftlichen Ausschüttungen.'],['a capital gain that must be attributed solely to the share price.','Der Kurs ist ausdrücklich unverändert; der Fehler liegt in der Anspruchsbuchung.']
 ],['Am Ex-Tag kann ein separater Anspruch entstehen; am Payment Date wird dieser durch Bargeld erfüllt.','Ohne neue Wertänderung erhöht der reine Formwechsel das Gesamtvermögen nicht.'],'wealth')
];
