const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('etr-'+id,'equity-trading','equity',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','An investor buys an existing shareholder’s listed shares through a broker. The company does not participate in the transaction. The purchase price primarily:',[
 ['compensates the seller rather than providing new equity capital to the company.','Bestehende Aktien wechseln ihren Eigentümer.'],['becomes new cash on the issuer’s balance sheet.','Der Emittent verkauft hier keine neuen Aktien.'],['increases the number of shares outstanding by the number purchased.','Eigentümerwechsel ist keine Neuemission.']
 ],['Sekundärhandel kann die Attraktivität einer Beteiligung durch Übertragbarkeit unterstützen.','Diese indirekte Finanzierungsfunktion ist vom unmittelbaren Geldempfänger zu unterscheiden.'],'flows'),
 q('02','practice','a','An offering sells 6 million newly issued shares and 4 million existing shares at 25 each. Ignore all costs. Gross proceeds to the company, in millions, are:',[
 ['150','Nur sechs Millionen neue Aktien finanzieren die Gesellschaft.'],['250','Dies enthält zusätzlich den Verkaufserlös der Altaktionäre.'],['100','Dies ist der Erlös der hier verkauften bestehenden Aktien.']
 ],[F('C=6\\cdot25=150','Die übrigen hundert Millionen fließen den verkaufenden Altaktionären zu.',[['C','Bruttozufluss an den Emittenten in Millionen Geldeinheiten.']])],'offering'),
 q('03','practice','a','A company issues 8 million new shares at 30 each. The underwriting discount is 4% of the new-share proceeds, and additional issuer costs are 3 million. Net proceeds to the issuer, in millions, are:',[
 ['227.4','Von 240 werden 9,6 Abschlag und drei weitere Kosten abgezogen.'],['230.4','Dies lässt die zusätzlichen fixen Emittentenkosten aus.'],['240.0','Dies ist der Bruttoerlös vor allen Kosten.']
 ],[F('C=8\\cdot30(1-0{,}04)-3=227{,}4','Der prozentuale Abschlag wird auf die korrekte Tranche angewandt.',[['C','Nettozufluss in Millionen Geldeinheiten.']])],'offering'),
 q('04','practice','a','Before an offering, 30 million shares are outstanding. The offering includes 5 million new shares and the resale of 7 million existing shares. Shares outstanding immediately after completion, in millions, equal:',[
 ['35','Nur die neuen fünf Millionen kommen hinzu.'],['42','Dies zählt die sieben Millionen Altaktien nochmals als neue Ausgabe.'],['28','Ein Verkauf durch Altanleger zieht die Aktien nicht ein.']
 ],[F('N_1=30+5=35','Die sieben Millionen bestehenden Aktien wechseln lediglich den Inhaber.',[['N_1','Ausstehende Aktien nach dem Angebot in Millionen.']])],'offering'),
 q('05','practice','a','An owner holds 3 million of 30 million identical shares. The firm issues 10 million new shares for cash, and the owner neither buys nor sells. The owner’s percentage holding afterward is:',[
 ['7.50%','Drei Millionen werden durch vierzig Millionen ausstehende Aktien geteilt.'],['10.00%','Dies verwendet die Aktienzahl vor der Ausgabe.'],['30.00%','Dies verwendet nur die neuen Aktien als Nenner.']
 ],[F('q=\\frac3{30+10}=7{,}50\\%','Die Quote sinkt, während gleichzeitig Kapital in die Gesellschaft fließt.',[['q','Beteiligungsquote nach der Ausgabe.']]),'Ob der Vermögenswert fällt, hängt zusätzlich von Preis, Kosten und Verwendung des Kapitals ab.'],'offering'),
 q('06','practice','a','An IPO offer price is 16. An investor instead buys in secondary trading at 20 and sells at the end of the same day at 18. With no fees or dividends, that investor’s return is:',[
 ['−10.00%','Der tatsächliche eigene Kaufpreis beträgt zwanzig.'],['12.50%','Dies verwendet den nicht gezahlten Angebotspreis als Einstieg.'],['25.00%','Dies misst den Anstieg vom Angebotspreis bis zum eigenen Kauf.']
 ],[F('R=\\frac{18-20}{20}=-10\\%','Die Rendite einer IPO-Zuteilung kann von der Rendite des späteren Börsenkäufers abweichen.',[['R','Realisierte Rendite des beschriebenen Anlegers.']])],'pricing'),
 q('07','practice','a','An offering’s order book indicates demand well above the number of shares offered. The most accurate conclusion is that:',[
 ['allocation and future trading performance still depend on actual decisions and market conditions.','Interessenbekundungen sind keine garantierte zukünftige Rendite.'],['every investor must receive their full requested allocation.','Bei begrenztem Angebot kann gerade eine Kürzung erforderlich sein.'],['the first trading price can never fall below the offer price.','Überzeichnung schafft keine solche Preisgarantie.']
 ],['Bookbuilding unterstützt Preis und Zuteilung, ersetzt aber keine Bewertung.','Ex post beobachtetes Underpricing ist kein sicher vorab realisierbarer Gewinn für jeden Anleger.'],'pricing'),
 q('08','practice','a','Under a firm-commitment underwriting agreement, subject to its stated conditions, the underwriter’s distinguishing commitment is to:',[
 ['purchase the agreed issue before distributing it to investors.','Damit übernimmt der Underwriter das vertraglich entsprechende Weiterverkaufsrisiko.'],['guarantee the stock’s secondary-market price indefinitely.','Die Emissionsübernahme ist keine dauerhafte Kursgarantie.'],['act only as an agent without committing to buy the agreed issue.','Dies beschreibt nicht die kennzeichnende Übernahmeverpflichtung.']
 ],['Vertragsbedingungen und eventuelle Ausnahmen sind zu prüfen.','Die Risikoverteilung unterscheidet sich von einer reinen Best-Efforts-Platzierung.'],'underwriting'),
 q('09','practice','a','A company considers a direct listing under rules permitting a primary capital raise. An analyst says all direct listings necessarily provide zero new capital. The analyst’s statement is:',[
 ['too broad; the permitted transaction structure and actual shares sold must be examined.','Notierungsweg allein bestimmt nicht unter allen Regeln den Geldempfänger.'],['correct because a direct listing can never include newly issued shares.','Dies widerspricht dem ausdrücklich zugelassenen Primärkapitalfall.'],['correct because all listed shares must already have been sold to the public.','Eine solche allgemeine zeitliche Voraussetzung gilt hier nicht.']
 ],['Bei einer reinen Altaktienstruktur geht der Erlös an Verkäufer; bei einer zulässigen Neuausgabe kann Kapital zur Gesellschaft fließen.','Die Analyse ordnet die tatsächlichen Aktien und Erlöse zu.'],'underwriting'),
 q('10','practice','a b','The secondary market supports primary equity issuance most directly by:',[
 ['giving investors a potential later exit and providing ongoing price information.','Übertragbarkeit und Preisbildung können die Bedingungen neuer Finanzierung beeinflussen.'],['transferring every resale price to the issuer as additional paid-in capital.','Sekundäre Verkaufserlöse gehen grundsätzlich an Verkäufer.'],['eliminating investment risk once the shares are listed.','Notierung beseitigt weder Kurs- noch Unternehmensrisiko.']
 ],['Die Finanzierungswirkung ist hier indirekt.','Sie darf nicht mit einem unmittelbaren Mittelzufluss aus jedem Börsengeschäft verwechselt werden.'],'secondary'),
 q('11','practice','b','A firm executes a client’s stock purchase by selling shares from its own inventory. In that transaction, the firm is acting primarily as a:',[
 ['dealer.','Die Firma ist selbst Handelspartner auf eigene Rechnung.'],['broker acting solely as an agent.','Reine Vermittlung umfasst gerade nicht den beschriebenen Verkauf aus eigenem Bestand.'],['corporate issuer creating new shares.','Ein Händlerbestand ist keine automatische Neuemission der Gesellschaft.']
 ],['Eine Firma kann verschiedene Rollen haben.','Maßgeblich ist die konkrete Transaktion und nicht nur ihre allgemeine Unternehmensbezeichnung.'],'secondary'),
 q('12','practice','b','In the US market, an exchange-listed stock is executed on an alternative trading system. This is best described as:',[
 ['off-exchange execution of a listed security.','Notierungsstatus und Ausführungsort sind verschieden.'],['proof that the security is unlisted.','Der außerbörsliche Abschluss hebt die Notierung nicht auf.'],['a new public issuance merely because the venue is electronic.','Die elektronische Ausführung bestimmt nicht, ob neue Aktien ausgegeben werden.']
 ],['Ein notierter Titel kann an verschiedenen Orten gehandelt werden.','OTC-Geschäfte in notierten Aktien werden von unnotierten OTC Equity Securities unterschieden.'],'venues'),
 q('13','practice','b','The statement “all off-exchange stock trading is unregulated” is most accurately assessed as:',[
 ['incorrect because applicable securities, intermediary and reporting rules can still apply.','Außerhalb einer Börse bedeutet nicht außerhalb sämtlicher Regeln.'],['correct because only a listing exchange can impose any financial-market obligations.','Andere Aufsichts- und Verhaltensregeln können relevant sein.'],['correct whenever the trade is not displayed in a public order book before execution.','Geringe Vorhandelstransparenz beseitigt nicht automatisch Aufsicht oder Meldepflichten.']
 ],['Der konkrete rechtliche Rahmen und Handelsmechanismus werden geprüft.','Die Funktionsbezeichnung allein begründet keine Aussage über Anlagequalität.'],'venues'),
 q('14','practice','b','A US dark-pool ATS does not display public quotations before execution. Which inference is most appropriate?',[
 ['limited pre-trade display does not imply that executed trades have no reporting obligations.','Vor- und Nachhandelstransparenz sind getrennte Dimensionen.'],['no executed trade may ever be reported.','Dies folgt nicht aus dem fehlenden öffentlichen Orderbuch.'],['every client order will receive a complete fill at the midpoint.','Weder passende Gegenmenge noch eine solche Ausführung ist dadurch garantiert.']
 ],['Auch nicht vorab angezeigte Geschäfte unterliegen dem geltenden Melderahmen.','Ausführungspreis und Menge werden anhand tatsächlicher Daten beurteilt.'],'transparency'),
 q('15','practice','b','An institutional trader chooses a venue that reveals less of an unexecuted block order. The most relevant trade-off is that:',[
 ['lower information exposure may be accompanied by uncertain fill quantity or waiting time.','Weniger Offenlegung garantiert keine sofort passende Gegenseite.'],['concealing the order guarantees both zero price impact and immediate full execution.','Diese Garantien folgen nicht aus der geringeren Sichtbarkeit.'],['the trade ceases to have economic costs once routed away from an exchange.','Preis, Gebühren, Zeit und Ausführungsrisiko bleiben relevant.']
 ],['Die Bewertung bezieht sich auf den Gesamtauftrag.','Ein günstiger Teilabschluss kann mit einem teuren oder unausgeführten Rest zusammenfallen.'],'transparency'),
 q('16','practice','b c','A buy limit order at 40 is submitted while the lowest available ask is 40.05. With no hidden liquidity or other venues, the order:',[
 ['does not immediately execute above 40 merely to ensure completion.','Das Limit setzt einen zulässigen Höchstpreis.'],['must execute at 40.05 because it is the best available quote.','Dies würde die Preisgrenze verletzen.'],['guarantees a later complete fill at exactly 40.','Preisbegrenzung ist keine Ausführungsgarantie.']
 ],['Die weitere Behandlung hängt von Gültigkeit und Orderbedingungen ab.','Ein Käufer kann Preisdisziplin wählen und dabei Nichtausführung riskieren.'],'orders'),
 q('17','practice','b c','A market buy order is larger than the quantity offered at the best ask. In an otherwise unchanged order book, it may:',[
 ['execute across more expensive ask levels.','Die günstigste sichtbare Menge kann aufgebraucht werden.'],['force every seller to supply unlimited shares at the original best ask.','Eine Quotierung stellt keine unbegrenzte Mengenzusage dar.'],['execute at the bid solely because the investor prefers a lower price.','Der Bid ist die Kaufseite anderer Marktteilnehmer.']
 ],['Ausführung wird mit den tatsächlich verfügbaren Preis-Mengen-Paaren gerechnet.','Der letzte beobachtete oder beste angezeigte Kurs ist kein garantierter Durchschnitt.'],'orders'),
 q('18','practice','c','A stock is quoted at a bid of 24.97 and an ask of 25.03. Using the quote midpoint, the quoted spread in basis points is:',[
 ['24','Sechs Cent relativ zu fünfundzwanzig entsprechen 24 Basispunkten.'],['12','Dies ist die einseitige Abweichung des Ask vom Mittelpunkt.'],['240','Dies verschiebt die Dezimalstelle um den Faktor zehn.']
 ],[F('s_{bp}=\\frac{25{,}03-24{,}97}{25}\\cdot10000=24','Der Mittelpunkt beträgt genau 25.',[['s_{bp}','Relativer vollständiger Quoted Spread in Basispunkten.']])],'spread'),
 q('19','practice','c','Two stocks have the same absolute bid–ask spread of 0.04. Their midpoints are 50 and 2. The second stock’s relative spread is:',[
 ['25 times the first stock’s relative spread.','Bei gleichem Zähler ist der Nenner der zweiten Aktie nur ein Fünfundzwanzigstel.'],['the same because both spreads are four cents.','Gleiche absolute Kosten bedeuten keine gleiche relative Belastung.'],['one twenty-fifth of the first stock’s relative spread.','Dies kehrt den Zusammenhang zwischen Nenner und Quote um.']
 ],['Die relativen Spreads betragen 0,08 Prozent und zwei Prozent.','Für Vergleiche sind Einheit und Bezugsgröße wesentlich.'],'spread'),
 q('20','practice','c','An unchanged sell book offers 200 shares at 20.02 and 400 at 20.05. A market purchase of 500 shares executes only against that book. With no fees, the average execution price is:',[
 ['20.038','Zweihundert Aktien zum ersten und dreihundert zum zweiten Preis werden gewichtet.'],['20.020','Zum besten Ask reichen nur zweihundert Aktien.'],['20.035','Dies ist der ungewichtete Mittelwert der beiden Preisstufen.']
 ],[F('\\bar P=\\frac{200\\cdot20{,}02+300\\cdot20{,}05}{500}=20{,}038','Die Mengen der tatsächlich ausgeführten Teilgeschäfte bestimmen die Gewichte.',[['\\bar P','Durchschnittlicher Kaufpreis je Aktie.']])],'depth'),
 q('21','practice','b c','A sell book offers 100 shares at 50.02, 300 at 50.05 and 600 at 50.10. A buy limit order for 500 shares has a limit of 50.05. With no other orders, hidden liquidity or venues, the maximum immediately executable quantity is:',[
 ['400','Nur die ersten beiden Stufen liegen innerhalb der Preisgrenze.'],['500','Die letzten hundert würden oberhalb des Limits gekauft.'],['100','Die zweite Stufe zum Limitpreis ist ebenfalls zulässig.']
 ],[F('Q_{fill}=100+300=400','Die verbleibenden hundert Aktien sind nicht automatisch ausgeführt.',[['Q_{fill}','Sofort ausführbare Aktienzahl innerhalb des Kaufpreislimits.']])],'orders'),
 q('22','practice','c','A company has issued 150 million shares, holds 10 million treasury shares that are not outstanding, and has 35 million non-float outstanding shares. There are no overlaps. Its float, in millions of shares, is:',[
 ['105','Ausstehend sind 140 Millionen; davon werden 35 Millionen abgezogen.'],['115','Dies lässt den eigenen, nicht ausstehenden Bestand im Ausgangswert.'],['95','Dies zieht die zehn Millionen eigenen Aktien zweimal ab.']
 ],[F('N_{float}=150-10-35=105','Jeder ausgeschlossene Bestand wird genau einmal berücksichtigt.',[['N_{float}','Float in Millionen Aktien.']])],'float'),
 q('23','practice','c','There are 80 million outstanding shares, of which 20 million are excluded under the stated float methodology. The float ratio is:',[
 ['75.00%','Sechzig Millionen investierbare Aktien werden durch achtzig Millionen ausstehende geteilt.'],['25.00%','Dies ist der ausgeschlossene Anteil.'],['33.33%','Dies setzt den ausgeschlossenen Bestand zum Float statt zum Gesamtbestand ins Verhältnis.']
 ],[F('f=\\frac{80-20}{80}=75\\%','Eigene, bereits nicht ausstehende Aktien dürften nicht nochmals abgezogen werden.',[['f','Float Ratio relativ zu ausstehenden Aktien.']])],'float'),
 q('24','practice','c','A lock-up expires on shares that then qualify for inclusion in float. No shares are issued or cancelled and no sale has yet occurred. The most accurate conclusion is that:',[
 ['float can increase without increasing shares outstanding or proving an immediate sale.','Verfügbarkeit, Ausgabe und tatsächlicher Handel sind getrennte Vorgänge.'],['the company must receive cash equal to the released shares’ market value.','Ein Sperrablauf ist keine Kapitalaufnahme.'],['the released shares must already be counted as that day’s trading volume.','Eine Verkaufsberechtigung ist noch kein Abschluss.']
 ],['Die konkrete Methodik bestimmt die Aufnahme in den investierbaren Bestand.','Volumen wird erst aus tatsächlich erfassten Abschlüssen des Zeitraums berechnet.'],'float'),
 q('25','practice','c','Five trading sessions record 0.6, 0.8, 0.9, 0.7 and 2.0 million shares. Average daily volume, in millions of shares, is:',[
 ['1.00','Fünf Millionen Aktien werden durch fünf Handelstage geteilt.'],['0.80','Dies ist der Median, nicht der arithmetische Tagesdurchschnitt.'],['0.71','Dies teilt näherungsweise durch sieben Kalendertage statt die gegebenen fünf Sitzungen.']
 ],[F('ADV=\\frac{0{,}6+0{,}8+0{,}9+0{,}7+2{,}0}{5}=1','Der hohe letzte Tag beeinflusst das Mittel und sollte interpretiert werden.',[['ADV','Durchschnittliches Tagesvolumen in Millionen Aktien je Handelstag.']])],'volume'),
 q('26','practice','c','A data set contains two trading days. All trades on day one occur at 10 for a total of 100 shares; on day two at 20 for 300 shares. Average daily traded value is:',[
 ['3,500','Die täglichen Geldumsätze von tausend und sechstausend werden gemittelt.'],['3,000','Dies ist der ungewichtete Durchschnittspreis fünfzehn mal durchschnittlich zweihundert Aktien.'],['7,000','Dies ist der gesamte Zweitagesumsatz, nicht der Tagesdurchschnitt.']
 ],[F('ADTV=\\frac{100\\cdot10+300\\cdot20}{2}=3500','Durchschnitt von Preis mal Menge ist nicht allgemein Produkt der beiden Durchschnitte.',[['ADTV','Durchschnittlicher täglicher Geldumsatz.']])],'volume'),
 q('27','practice','c','A feed reports one matched transaction for 2,000 shares, identifying both buyer and seller. Under a once-per-executed-trade volume convention, reported share volume should be:',[
 ['2,000','Kauf und Verkauf sind die beiden Seiten desselben Abschlusses.'],['4,000','Dies zählt die beiden Seiten doppelt.'],['1,000','Eine Halbierung der tatsächlich gehandelten Menge wäre ebenfalls falsch.']
 ],['Daten aus mehreren Quellen müssen zusätzlich auf Duplikate geprüft werden.','Die tatsächliche Aktienmenge ist von der Anzahl der beteiligten Seiten zu unterscheiden.'],'volume'),
 q('28','practice','c','A position of 900,000 shares is to be traded at no more than 15% of assumed constant daily volume of 1.2 million shares. The modelled trading duration is:',[
 ['5 days','Pro Tag werden 180.000 Aktien angesetzt.'],['0.75 days','Dies ignoriert die Teilnahmebegrenzung.'],['7.5 days','Dies verwendet eine andere tägliche Mengengrenze als angegeben.']
 ],[F('H=\\frac{900000}{0{,}15\\cdot1200000}=5','Die Rechnung ist eine Planungsannahme und keine zugesicherte Liquidität.',[['H','Rechnerische Anzahl Handelstage.']])],'capacity'),
 q('29','practice','c','Annual trading volume equals 160% of the stated constant float. This most accurately means that:',[
 ['shares can have traded repeatedly; it does not prove every float share changed owners.','Umschlag ist eine Mengenrelation über die Zeit, keine Liste unterschiedlicher Aktien.'],['the company necessarily issued 60% more shares.','Handelsvolumen ist keine Neuemissionszahl.'],['all float shares could be sold simultaneously without affecting price.','Jahresvolumen beweist keine gleichzeitige Orderbuchtiefe.']
 ],['Eine Aktie kann viele Abschlüsse verursachen, während andere gar nicht gehandelt werden.','Liquiditätsanalyse ergänzt Volumen deshalb um Preise, Tiefe und Marktbedingungen.'],'capacity'),
 q('30','practice','d','Two equity indexes begin on different base dates and currently stand at 1,000 and 10,000. Without further information, the higher level:',[
 ['does not establish a superior investment return or a larger underlying market.','Skalierung und Basisdatum beeinflussen das Niveau.'],['proves the second market is ten times larger.','Indexpunkte sind keine direkt vergleichbaren gesamten Marktwerte.'],['proves the second index earned ten times the return.','Rendite benötigt einen passenden Anfangs- und Endwert über denselben Zeitraum.']
 ],['Zuerst werden Universum, Gewichtung und Ertragskonvention geprüft.','Der Index ist eine Rechenvorschrift; ein nachbildender Fonds hat zusätzliche Umsetzungsbedingungen.'],'index-map'),
 q('31','practice','d','A price-weighted index includes stocks priced at 80, 15 and 5, with no corporate actions. The weight of the first stock is:',[
 ['80.00%','Der Stückkurs achtzig wird durch die Kurssumme hundert geteilt.'],['33.33%','Dies entspräche einer Gleichgewichtung.'],['Cannot be calculated without outstanding share counts.','Stückzahlen sind für diese Preisgewichtung nicht erforderlich.']
 ],[F('w_1^P=\\frac{80}{80+15+5}=80\\%','Preisgewichtung misst Einfluss über den relativen Stückkurs.',[['w_1^P','Gewicht des ersten Titels im Preisindex.']])],'weights'),
 q('32','practice','d','Stock A has a price of 40 and 2 million shares; stock B has a price of 10 and 12 million shares. The market-capitalization weight of A is:',[
 ['40.00%','A hat achtzig Millionen Marktwert, B hundertzwanzig.'],['80.00%','Dies ist das Preisgewicht und ignoriert die Aktienzahlen.'],['14.29%','Dies setzt ausschließlich Aktienzahlen ins Verhältnis.']
 ],[F('w_A=\\frac{40\\cdot2}{40\\cdot2+10\\cdot12}=40\\%','Preise und Aktienzahlen gehören gemeinsam in die Marktwertbasis.',[['w_A','Marktwertgewicht von A.']])],'weights'),
 q('33','practice','d','Two stocks each have a full market value of 200 million. Their float factors are 25% and 75%. The first stock’s float-adjusted index weight is:',[
 ['25.00%','Die investierbaren Werte betragen fünfzig und hundertfünfzig Millionen.'],['50.00%','Dies verwendet volle statt floatbereinigte Marktwerte.'],['75.00%','Dies ist das Gewicht des zweiten Titels.']
 ],[F('w_1^F=\\frac{200\\cdot0{,}25}{200\\cdot0{,}25+200\\cdot0{,}75}=25\\%','Gleiche volle Marktwerte erzeugen bei unterschiedlicher Investierbarkeit nicht gleiche Floatgewichte.',[['w_1^F','Floatgewicht des ersten Titels.']])],'weights'),
 q('34','practice','d','A fixed three-stock portfolio starts with weights of 20%, 50% and 30%. The stocks return 15%, 2% and −10%, respectively. There are no intermediate cash flows or trades. The portfolio return is:',[
 ['1.00%','Die Beiträge sind drei, eins und minus drei Prozentpunkte.'],['2.33%','Dies ist der ungewichtete Durchschnitt der drei Titelrenditen.'],['7.00%','Dies addiert die drei Titelrenditen ohne korrekte Gewichtung.']
 ],[F('R=0{,}20\\cdot0{,}15+0{,}50\\cdot0{,}02+0{,}30(-0{,}10)=1\\%','Anfangsgewichte und Renditen müssen sich auf dieselbe Periode beziehen.',[['R','Rendite des unverändert gehaltenen Portfolios.']])],'comparison'),
 q('35','practice','d','A price index sums prices of 90, 30 and 15 and uses a divisor of 1.35. The first stock then splits three for one with no economic value change. The new divisor preserving the index level is:',[
 ['0.75','Die neue Kurssumme ist 75; das bisherige Niveau bleibt hundert.'],['1.35','Dies würde die technische Kurssenkung als Verlust anzeigen.'],['4.05','Dies multipliziert pauschal mit dem Splitfaktor, statt die Kontinuität zu lösen.']
 ],[F('I_0=\\frac{90+30+15}{1{,}35}=100,\\qquad d_1=\\frac{30+30+15}{100}=0{,}75','Die Aktienzahl des gesplitteten Titels steigt, ist aber nicht der Zähler dieses Preisindex.',[['I_0','Indexniveau vor dem Split.'],['d_1','Neuer Divisor.']])],'divisor'),
 q('36','practice','d','A simple market-capitalization index correctly adjusts share counts for a two-for-one split. With no economic price change or other event, that split alone:',[
 ['leaves the stock’s market value unchanged and does not require a divisor adjustment.','Halber Stückkurs und doppelte Aktienzahl gleichen sich aus.'],['halves both the company’s market value and index level.','Dies ignoriert die veränderte Aktienzahl.'],['must double the divisor under every index methodology.','Eine solche pauschale Regel folgt nicht aus der Kontinuitätsgleichung.']
 ],['Bei einem Preisindex kann dagegen eine Divisoränderung nötig sein.','Zuerst wird der tatsächlich verwendete Indexzähler bestimmt.'],'divisor'),
 q('37','practice','d','An equal-weight two-stock portfolio starts with 100 invested in each stock. One rises to 120 while the other remains at 100. With no costs, restoring equal weights requires:',[
 ['selling 10 of the first stock’s market value and buying 10 of the second.','Der Gesamtwert 220 wird auf zweimal 110 ausgerichtet.'],['selling 20 of the first and making no purchase.','Dies würde Kapital herausnehmen und nicht die ursprüngliche Vollinvestition gleich gewichten.'],['no trade because equal weights remain equal automatically.','Unterschiedliche Renditen lassen die Gewichte driften.']
 ],['Rebalancing richtet Gewichte aus; Reconstitution verändert Mitglieder.','Der Verkauf und der Kauf gehören zur Umsetzung und können im echten Markt Kosten verursachen.'],'rebalancing'),
 q('38','practice','d','An index replaces an ineligible constituent with a newly eligible company according to its rules. This action is most specifically:',[
 ['reconstitution.','Die Mitgliedschaft ändert sich.'],['a guarantee that the index return increases.','Eine neue Zusammensetzung garantiert keinen Wertzuwachs.'],['proof that the index is equally weighted.','Mitgliederregeln und Gewichtungsmethode sind verschiedene Dimensionen.']
 ],['Ein Mitgliederwechsel kann gleichzeitig eine Gewichtsänderung auslösen.','Technische Zähleränderungen werden nach der Methodik behandelt, damit kein künstlicher Marktgewinn entsteht.'],'rebalancing'),
 q('39','practice','d','A stock starts at 80, ends at 78 and pays a dividend of 4 at period-end. A specified net-return convention withholds 25% of the dividend. Ignoring all other costs, the net total return is:',[
 ['1.25%','Nach Steuern verbleiben drei Dividende; der Gesamtertrag beträgt eins auf achtzig.'],['2.50%','Dies ist die Bruttogesamtrendite vor dem angegebenen Einbehalt.'],['−2.50%','Dies ist die reine Kursrendite ohne Ausschüttung.']
 ],[F('R_N=\\frac{78+4(1-0{,}25)-80}{80}=1{,}25\\%','Netto bezieht sich auf die definierte Steuerannahme, nicht automatisch auf sämtliche Fondsgebühren.',[['R_N','Modellnettorendite über die Periode.']])],'return-types'),
 q('40','practice','d','An unhedged investment has a local-currency total return of 5%. Its currency loses 8% measured in home-currency units per local unit. With consistent period-end cash flows, the home-currency return is:',[
 ['−3.40%','Die Wachstumsfaktoren 1,05 und 0,92 werden multipliziert.'],['−3.00%','Dies addiert die Prozentsätze und lässt den Kreuzterm aus.'],['13.00%','Dies verwendet das falsche Vorzeichen für den Währungsverlust.']
 ],[F('R_H=1{,}05\\cdot0{,}92-1=-3{,}40\\%','Währungsnotierung und lokaler Ertrag müssen zusammenpassen.',[['R_H','Rendite in Heimatwährung ohne Absicherung.']])],'return-types'),
 q('a1','mock-a','a b','An exchange-listed issuer completes a public transaction consisting entirely of shares sold by a founder. A fund later buys those shares from another investor on a US ATS. Which conclusion is most accurate?',[
 ['Neither the founder sale nor the later ATS trade by itself supplies new equity proceeds to the issuer.','Beide Vorgänge betreffen bestehende Aktien, auch wenn sie öffentlich angeboten beziehungsweise außerbörslich ausgeführt werden.'],['The public founder sale raises issuer capital, whereas the ATS trade does not.','Öffentliches Angebot bestimmt nicht allein den Geldempfänger.'],['The ATS transaction turns the listed stock into an unlisted security.','Ausführungsort und Notierungsstatus sind getrennt.']
 ],['Zuerst wird festgestellt, wer welche Aktien verkauft.','Anschließend werden Angebot und späterer Ausführungsort getrennt klassifiziert.'],'flows'),
 q('a2','mock-a','c d','A float-adjusted index includes two companies with market values of 600 million and 400 million and initial float factors of 50% each. With prices and outstanding shares unchanged, a previously excluded block of the first company equal to 25% of its outstanding shares becomes eligible float. Once incorporated under the index rules, the first company’s new weight is closest to:',[
 ['69.23%','Die erste investierbare Basis steigt auf 450 Millionen; die zweite bleibt bei 200.'],['60.00%','Dies ist das ursprüngliche Floatgewicht beziehungsweise das volle Marktwertgewicht.'],['75.00%','Dies ist der neue Floatfaktor des ersten Titels, nicht sein Anteil am Index.']
 ],[F('w_1=\\frac{600(0{,}50+0{,}25)}{600(0{,}50+0{,}25)+400\\cdot0{,}50}=69{,}23\\%','Eine methodische Bestandsänderung kann Gewichte verändern, ohne einen Kursgewinn zu erzeugen.',[['w_1','Neues Floatgewicht der ersten Gesellschaft.']])],'float'),
 q('b1','mock-b','a c','A company with 90 million outstanding shares has 30 million float shares. It sells 10 million new shares, all immediately eligible float, and a founder simultaneously sells 5 million previously excluded shares to dispersed investors who qualify as float holders. Ignore costs and other changes. The post-transaction float ratio is:',[
 ['45.00%','Float steigt auf 45 Millionen; ausstehend sind nur hundert Millionen, da der Gründerverkauf keine Ausgabe ist.'],['40.00%','Dies lässt die zusätzlich frei investierbaren Gründeraktien aus.'],['42.86%','Dies zählt die fünf Millionen bestehenden Gründeraktien im Gesamtkapital nochmals als neue Ausgabe.']
 ],[F('f=\\frac{30+10+5}{90+10}=45\\%','Die Neuemission und der Eigentümerwechsel beeinflussen den Float, aber nur die erste erhöht die ausstehenden Aktien.',[['f','Floatquote nach beiden vollständig vollzogenen Transaktionen.']])],'case'),
 q('b2','mock-b','b d','A fund tracks an equal-weight equity index using off-exchange execution. Its manager claims that using the same constituents ensures permanent equality of weights and that off-exchange routing removes transaction costs. The most appropriate assessment is that:',[
 ['both claims are incorrect: weights can drift and execution costs can remain.','Gleiche Mitgliedschaft hält Gewichte nicht konstant; Handelsort garantiert keine Kostenfreiheit.'],['only the first claim is incorrect because off-exchange execution is always free.','Außerbörsliche Ausführung kann Preiseffekte und Gebühren enthalten.'],['only the second claim is incorrect because equal-weight indexes need no rebalancing.','Unterschiedliche Titelrenditen verändern die tatsächlich gehaltenen Gewichte.']
 ],['Theoretische Indexregeln werden von ihrer praktischen Nachbildung unterschieden.','Ordertyp, Preis, Menge, Gebühren und Anpassungsbedarf bestimmen die konkrete Umsetzung.'],'rebalancing')
];
