const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,correct,solution,section)=>Q('fis-'+id,'fiscal','economics',pool,los,stem,options,correct,solution,{section});
const eq=(tex,reading,symbol,meaning)=>F(tex,reading,[[symbol,meaning]]);
module.exports=[
 q('01','practice','a','Which action is most directly a fiscal policy decision?',[
 ['Increasing government purchases of newly produced medical services.','Das verändert staatliche Güternachfrage.'],['Changing the central bank rate paid on reserves.','Das ist ein geldpolitisches Instrument.'],['Changing the terms of a central bank refinancing facility.','Das betrifft die geldpolitische Liquiditätsbereitstellung.']
 ],0,['Die Entscheidung über öffentliche Käufe gehört zur Fiskalpolitik, unabhängig davon, ob sie durch laufende Einnahmen oder Schuldaufnahme finanziert wird.'],'policy-map'),
 q('02','practice','c','A government transfers 50 to households, which initially spend 30 on newly produced domestic consumer goods. The transfer itself:',[
 ['adds 50 directly to government purchases in the GDP expenditure identity.','Transfers sind keine unmittelbaren Käufe neu produzierter Güter.'],['is not a government purchase; the initial consumption expenditure adds 30 to C.','Produktion und Konsumausgabe sind von der Umverteilungszahlung zu trennen.'],['creates no possible demand effect because it is not included in G.','Die Verwendung der Zahlung kann private Nachfrage verändern.']
 ],1,['Der Transfer verändert verfügbares Einkommen. Seine Folgeausgaben wirken über andere Komponenten; weitere Rückkopplungen sind noch nicht angegeben.'],'instruments'),
 q('03','practice','c','A reduction in personal income taxes initially affects aggregate demand most directly by:',[
 ['automatically increasing government purchases by the same amount.','Steuern und staatliche Käufe sind verschiedene Instrumente.'],['requiring households to spend the entire tax saving.','Haushalte können auch sparen oder tilgen.'],['raising disposable income and potentially consumption.','Die Konsumreaktion hängt unter anderem von der marginalen Konsumneigung ab.']
 ],2,['Die erste Konsumrunde ist bei einer marginalen Konsumneigung unter eins kleiner als die Steuersenkung.'],'multipliers'),
 q('04','practice','c','In a fixed-price model, the marginal propensity to consume is 0.75, the marginal net tax rate is 0.20, and the marginal propensity to import is 0.10. The government-purchases multiplier is:',[
 ['2.00.','1/[1 − 0,75 × 0,8 + 0,1] = 2.'],['2.50.','Das ignoriert die Importreaktion.'],['4.00.','Das ignoriert proportionale Nettosteuern und Importe.']
 ],0,[eq('k_G=1/[1-0{,}75(1-0{,}20)+0{,}10]=2','Die gesamte induzierte Nachfrage nach heimischem Output aus zusätzlichem Einkommen ist 0,5.','k_G','Ausgabenmultiplikator im angegebenen Modell.')],'multipliers'),
 q('05','practice','c d','A fixed-price economy has a government-purchases multiplier of 2 and a marginal propensity to consume of 0.75. Autonomous net taxes decrease by 12, with no other change. Equilibrium output increases by:',[
 ['12.','Das lässt die Konsum- und Rückkopplungseffekte weg.'],['18.','Der Steuermultiplikator ist −0,75 × 2 = −1,5; mal −12 ergibt +18.'],['24.','Das verwendet den Ausgaben- statt den Steuermultiplikator.']
 ],1,[eq('\\Delta Y=(-0{,}75\\cdot2)(-12)=18','Ein negativer Fiskalmultiplikator mal eine negative Steueränderung ergibt eine positive Einkommensänderung.','\\Delta Y','Änderung des Gleichgewichtseinkommens.')],'leakages'),
 q('06','practice','c d','In the simple closed-economy model with lump-sum taxes, no proportional taxes, fixed prices, and MPC 0.60, both government purchases and lump-sum taxes rise by 15. Output rises by:',[
 ['0.','Gleiche anfängliche Haushaltsbeträge haben verschiedene direkte Nachfragewirkungen.'],['37.50.','Das berücksichtigt nur die Staatskäufe.'],['15.00.','(1 − 0,6)/(1 − 0,6) × 15.']
 ],2,[eq('\\Delta Y=(15-0{,}6\\cdot15)/(1-0{,}6)=15','Die erste Runde ist +6, danach wirkt der Fiskalmultiplikator 2,5.','\\Delta Y','Einkommensänderung unter den angegebenen restriktiven Annahmen.')],'balanced-budget'),
 q('07','practice','c','Holding the marginal propensity to consume and other model assumptions fixed, a higher marginal propensity to import most likely:',[
 ['reduces the government-purchases multiplier for domestic output.','Ein größerer Teil der Folgerunden entfällt auf ausländische Produktion.'],['increases the multiplier because all imports are domestic production.','Importe sind keine heimische Produktion.'],['has no effect on the model denominator.','Die Importneigung steht mit positivem Vorzeichen im Nenner.']
 ],0,['Diese Aussage gilt für das definierte Modell, nicht als vollständige Wohlfahrtsbeurteilung von Importen.'],'leakages'),
 q('08','practice','c d','During a recession, tax receipts decline and unemployment benefit payments rise under unchanged rules. The resulting larger deficit most directly reflects:',[
 ['a newly enacted discretionary expansion in every case.','Es wurden gerade keine Regeln geändert.'],['automatic stabilizers.','Die bestehende Steuer- und Transferstruktur reagiert auf Aktivität.'],['an automatic monetary policy tightening.','Ein Haushaltssaldo ist keine Zentralbankzinsentscheidung.']
 ],1,['Die Reaktion puffert verfügbares Einkommen. Ein neues Defizitniveau allein identifiziert die diskretionäre Politikrichtung nicht.'],'stabilizers'),
 q('09','practice','d','All balances use the same GDP basis. The observed primary balance improves from −5% to −4%, while its estimated cyclical component improves from −4% to −1%. The cyclically adjusted primary balance:',[
 ['improves from −1% to +3%.','Nachher ist −4 − (−1) = −3, nicht +3.'],['is unchanged because both observed balances are deficits.','Es zählen die bereinigten Werte und ihre Änderung.'],['deteriorates from −1% to −3%, suggesting a more expansionary fiscal change.','Der Konjunktureffekt verdeckt die bereinigte Verschlechterung.']
 ],2,['Vorher: −5 − (−4) = −1. Nachher: −4 − (−1) = −3. Die Interpretation bleibt von Bereinigungsqualität und Zusammensetzung abhängig.'],'stance'),
 q('10','practice','b','Government revenue is 110 and primary expenditure is 104. Opening debt is 200 and the effective nominal interest rate is 4%. The overall budget balance, with a surplus positive, is:',[
 ['−2.','Primärüberschuss 6 minus Zinsen 8.'],['6.','Das ist der Primärsaldo vor Zinsen.'],['14.','Das addiert Zinskosten, statt sie abzuziehen.']
 ],0,[eq('BUD=(110-104)-0{,}04\\cdot200=-2','Ein Primärüberschuss von 6 steht einem Gesamtdefizit von 2 gegenüber.','BUD','Gesamtbudgetsaldo; Überschuss positiv.')],'stance'),
 q('11','practice','b','Opening nominal GDP is 100 and debt is 60. Nominal GDP grows 4%, the effective interest rate is 6%, and the primary surplus equals 2% of current GDP. With no stock-flow adjustments, the new debt-to-GDP ratio is closest to:',[
 ['61.60%.','Das verwendet den falschen GDP-Bezug und behandelt eine Quote wie einen Geldbetrag.'],['59.15%.','Neue Schuld 60 × 1,06 − 0,02 × 104 = 61,52; geteilt durch 104.'],['63.60%.','Das ist Schuld nach Zinsen vor dem Überschuss relativ zum alten BIP.']
 ],1,[eq('d_1=(60\\cdot1{,}06-0{,}02\\cdot104)/104\\approx59{,}1538\\%','Nominalschuld steigt, ihre Quote fällt. Primärsaldo und Quote verwenden aktuelles BIP.','d_1','Schuldenquote am Ende der neuen Periode.')],'debt-dynamics'),
 q('12','practice','b','Opening debt is 90% of GDP. The effective nominal interest rate is 6% and nominal GDP grows 2%. With no stock-flow adjustments, the primary surplus as a share of current GDP needed to stabilize the ratio is closest to:',[
 ['1.80%.','Das berücksichtigt den Zins-Wachstums-Abstand nicht korrekt.'],['3.60%.','Das ist die Näherung ohne Division durch 1,02.'],['3.53%.','(0,06 − 0,02)/1,02 × 0,9.']
 ],2,[eq('pb^*=(0{,}06-0{,}02)\\cdot0{,}9/1{,}02\\approx3{,}5294\\%','Die exakte Bestandsrechnung unterscheidet sich hier erkennbar von der häufigen Näherung.','pb^*','Stabilisierender Primärüberschuss relativ zum aktuellen BIP.')],'debt-example'),
 q('13','practice','b','A country has opening debt equal to 90% of GDP, a zero primary balance, an effective nominal interest rate of 3%, and nominal growth of 6%. Ignoring other adjustments, the new debt ratio is closest to:',[
 ['87.45%.','0,9 × 1,03/1,06.'],['90.00%.','Ein ausgeglichener Primärsaldo hält bei unterschiedlichem Zins und Wachstum die Quote nicht konstant.'],['92.62%.','Das vertauscht Zins- und Wachstumsfaktor.']
 ],0,[eq('d_1=0{,}9\\cdot1{,}03/1{,}06\\approx87{,}4528\\%','Der Nenner wächst schneller als der verzinste Schuldenbestand.','d_1','Neue Schuldenquote.')],'debt-dynamics'),
 q('14','practice','b','Nominal debt rises from 80 to 84 while nominal GDP rises from 100 to 110. The new debt ratio is:',[
 ['84.00%.','Das verwendet das alte BIP.'],['76.36%.','84/110, unterhalb der alten Quote von 80 %.'],['80.00%.','Die beiden Größen wachsen nicht im gleichen Verhältnis.']
 ],1,[eq('d_1=84/110\\approx76{,}3636\\%','Höhere Nominalschuld bedeutet nicht zwingend höhere Schuldenquote.','d_1','Neue Schuld relativ zum neuen BIP.')],'debt-example'),
 q('15','practice','b','Two governments report the same gross debt-to-GDP ratio. Which additional information is most relevant to comparing refinancing vulnerability?',[
 ['Whether the latest annual budget showed a surplus, without considering maturities.','Ein Jahressaldo allein erfasst den anstehenden Refinanzierungsbedarf nicht.'],['Their nominal GDP growth alone, assuming currency and maturity cannot affect funding risk.','Wachstum ist relevant, aber die ausgeschlossenen Finanzierungsmerkmale sind es ebenfalls.'],['Maturity profile, currency denomination, and access to a stable investor base.','Fälligkeit und Finanzierungsstruktur bestimmen Liquiditäts- und Währungsrisiken mit.']
 ],2,['Eine einzelne Bruttoquote erfasst weder kurzfristigen Refinanzierungsbedarf noch sämtliche Vermögenswerte oder bedingten Verpflichtungen.'],'debt-assessment'),
 q('16','practice','b c','Under the restrictive assumptions of Ricardian equivalence, a debt-financed tax cut with an unchanged government spending path is most likely to:',[
 ['raise private saving as households anticipate future taxes.','Der heutige Steuervorteil wird zur Deckung der erwarteten künftigen Last zurückgelegt.'],['raise consumption by the entire tax cut regardless of borrowing constraints.','Das ist nicht die ricardianische Neutralitätsaussage.'],['eliminate the government debt mechanically.','Private Erwartungsbildung löscht keine staatlichen Verbindlichkeiten.']
 ],0,['Die Annahmen sind wesentlich. Liquiditätsbeschränkte Haushalte oder abweichende Horizonte können anders reagieren.'],'crowding-out'),
 q('17','practice','d','After a fiscal package is legally approved, infrastructure spending is delayed by procurement and construction preparation. This most directly illustrates:',[
 ['a recognition lag in identifying the recession.','Die Diagnose und der Beschluss liegen schon vor.'],['an implementation lag.','Es geht um den Weg vom Beschluss zur tatsächlichen Ausführung.'],['the absence of all potential fiscal effects.','Verzögerung bedeutet nicht zwingend Wirkungslosigkeit.']
 ],1,['Erkennung, Entscheidung, Umsetzung und spätere wirtschaftliche Reaktion sind verschiedene Verzögerungen.'],'implementation'),
 q('18','practice','c d','In a fixed-price model with an expenditure multiplier of 2, government purchases rise by 8 but an assumed financing response reduces autonomous private investment by 3. The output change is:',[
 ['16.','Das ignoriert die private Gegenreaktion.'],['22.','Das addiert den Investitionsrückgang.'],['10.','2 × (8 − 3).']
 ],2,[eq('\\Delta Y=2(8-3)=10','Die private Reaktion ist hier vorgegeben, nicht aus dem einfachen Fiskalmultiplikator hergeleitet.','\\Delta Y','Gesamte Outputänderung unter den Modellannahmen.')],'crowding-out'),
 q('19','practice','d','A structural primary deficit falls from 6% to 4% of GDP on a comparable basis. This change is most consistent with:',[
 ['a contractionary fiscal change, although a deficit remains.','Die bereinigte Position wird weniger expansiv als zuvor.'],['an expansionary change solely because the balance is still negative.','Das verwechselt Niveau und Veränderung.'],['no possible change in aggregate demand.','Ein verbleibendes Defizit schließt einen negativen Nachfrageimpuls nicht aus.']
 ],0,['Die Zusammensetzung der Änderungen beeinflusst die konkrete Wirkung; das Vorzeichen der Saldenänderung ist dennoch von der Defizitexistenz zu trennen.'],'stance'),
 q('20','practice','c','A temporary transfer reaches two groups. Group A is liquidity constrained with MPC 0.9; group B has MPC 0.3. For an equal transfer, the initial consumption response is most likely:',[
 ['identical because both receive the same amount.','Verwendung und Zahlung sind nicht identisch.'],['larger for group A.','Bei gleichen Beträgen werden zunächst 90 % statt 30 % konsumiert.'],['larger for group B because it saves more.','Sparen ist gerade nicht der unmittelbare Konsumimpuls.']
 ],1,['Die erste Runde sagt noch nicht alles über langfristigen Nutzen, Verschuldung oder sämtliche Nachfrageeffekte aus.'],'instruments'),
 q('a1','mock-a','b','Opening nominal GDP and debt are both 100. Nominal growth is 4%, the effective interest rate is 6%, and the primary surplus equals 2% of current GDP. With no other adjustments, the new debt ratio is closest to:',[
 ['99.92%.','Neue Schuld 106 − 2,08 = 103,92; neues BIP 104.'],['100.00%.','Das entspricht hier nur der Näherung ohne Wachstumsnenner.'],['102.00%.','Das verwendet den Primärsaldo und den Nenner inkonsistent.']
 ],0,[eq('d_1=(106-2{,}08)/104\\approx99{,}9231\\%','Die exakte Rechnung verwendet den Primärüberschuss als Anteil des neuen BIP.','d_1','Schuldenquote der neuen Periode.')],'debt-dynamics'),
 q('a2','mock-a','d','A government cuts purchases while raising autonomous net taxes, holding the economic environment and other policies constant. These discretionary actions are most likely:',[
 ['expansionary because tax revenue rises.','Höhere Einnahmen sind nicht automatisch höhere private Nachfrage.'],['contractionary through both direct purchases and disposable income.','Weniger Käufe und geringeres verfügbares Einkommen dämpfen die betrachteten Nachfragekanäle.'],['neutral whenever public debt is positive.','Der Schuldenbestand hebt diese Nachfrageänderungen nicht automatisch auf.']
 ],1,['Die Aussage betrifft die Richtung unter konstanten Rahmenbedingungen, nicht die genaue Größe oder gesellschaftliche Zweckmäßigkeit.'],'multipliers'),
 q('b1','mock-b','c','A fixed-price model has MPC 0.60, a marginal net tax rate of 0.20, and marginal import propensity 0.08. Government purchases rise by 12. The increase in equilibrium output is:',[
 ['12.','Das ignoriert induzierte Nachfrage.'],['30.','Das ignoriert Steuern und Importe.'],['20.','12/[1 − 0,6 × 0,8 + 0,08].']
 ],2,[eq('\\Delta Y=12/[1-0{,}6(1-0{,}2)+0{,}08]=20','Der Nenner beträgt 0,6, der Ausgabenmultiplikator 5/3.','\\Delta Y','Outputänderung bei unveränderten übrigen Modellannahmen.')],'multipliers'),
 q('b2','mock-b','c d','A headline deficit widens during falling activity, but no tax or spending rules change. The most appropriate conclusion is that:',[
 ['the widening alone does not prove a discretionary fiscal expansion.','Automatische Einnahmen- und Transferreaktionen können den Saldo verändern.'],['the government must have cut tax rates.','Sinkende Einnahmen können auch bei konstanten Sätzen entstehen.'],['the structural deficit must widen by exactly the same amount.','Konjunkturbereinigung kann den zyklischen Anteil herausrechnen.']
 ],0,['Zur Beurteilung der diskretionären Richtung sind Regeln, Zusammensetzung und bereinigte Salden zusätzlich nötig.'],'stabilizers')
];
