const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,correct,solution,section)=>Q('geo-'+id,'geopolitics','economics',pool,los,stem,options,correct,solution,{section});
module.exports=[
 q('01','practice','a','Two rival governments agree on a common shipping-data standard while continuing to compete for port investment. Their relationship is best described as:',[
 ['cooperation in one area alongside competition in another.','Eine gemeinsame technische Regel schließt Standortwettbewerb nicht aus.'],['a transition to an economic union.','Ein Datenstandard begründet keine gemeinsame Wirtschaftspolitik.'],['the removal of differences in national interests.','Die konkurrierenden Investitionsziele bleiben ausdrücklich bestehen.']
 ],0,['Kooperation wird für eine konkrete Entscheidung beurteilt. Akteure können gleichzeitig voneinander profitieren und um die Verteilung der Vorteile konkurrieren.'],'cooperation'),
 q('02','practice','a','A government accepts a higher procurement cost to reduce reliance on a foreign supplier for critical communications. The analyst should first recognize that:',[
 ['the decision necessarily maximizes the supplier profit margin.','Die Lieferantenmarge ist nicht das erklärte staatliche Ziel.'],['the stated security objective changes the relevant trade-off.','Versorgungssicherheit kann neben kurzfristigen Kosten Teil der Zielfunktion sein.'],['the higher invoice price measures the complete social cost.','Ausfallrisiko und weitere Folgen fehlen in einer reinen Preisbetrachtung.']
 ],1,['Ein vermeintlich unökonomischer Preisvergleich kann auf einer unvollständigen Zieldefinition beruhen. Ob die Maßnahme effizient ist, erfordert anschließend einen Vergleich von Kosten und tatsächlich verringerter Abhängigkeit.'],'actors'),
 q('03','practice','b','A manufacturer moves assembly closer to its customers but both the old and new plants depend on the same sole-source chip producer. The move most directly:',[
 ['eliminates its supplier concentration.','Der gemeinsame Engpass bleibt.'],['turns all fixed costs into variable costs.','Eine geografische Änderung verändert die Kostenklassifikation nicht zwangsläufig.'],['may shorten delivery routes while leaving a common input vulnerability.','Transportweg und vorgelagerte Konzentration sind verschiedene Expositionen.']
 ],2,['Nearshoring betrifft Standortnähe. Für Resilienz muss die gesamte relevante Lieferkette betrachtet werden, nicht nur die Endmontage.'],'globalization'),
 q('04','practice','b','A tariff reduction lowers consumer prices but displaces workers in one import-competing region. Which assessment is most appropriate?',[
 ['Aggregate gains can coexist with concentrated adjustment costs.','Gesamtgewinn und ungleiche Verteilung sind vereinbar.'],['A consumer gain proves that each affected worker gains.','Das verwechselt Aggregat und individuelle Verteilung.'],['Regional job losses alone prove that aggregate welfare falls.','Ohne übrige Effekte folgt daraus kein Gesamtvorzeichen.']
 ],0,['Umschulung, Mobilität und Zeit bis zur neuen Beschäftigung beeinflussen die Verteilung und die realen Übergangskosten.'],'globalization'),
 q('05','practice','a b','Several states adopt common rules and a shared negotiation forum without transferring all policy powers to a single dominant state. This arrangement is most closely associated with:',[
 ['autarky.','Autarkie zielt stärker auf Unabhängigkeit von grenzüberschreitendem Austausch.'],['multilateralism.','Mehrere Akteure koordinieren sich über gemeinsame Verfahren.'],['hegemony alone.','Eine dominierende Macht mit asymmetrischer Einflussstruktur ist nicht die beschriebene Kerneigenschaft.']
 ],1,['Die Kategorien beschreiben idealtypische Beziehungen. Reale Staaten können je nach Politikfeld verschiedene Formen kombinieren.'],'archetypes'),
 q('06','practice','c','A country seeks external support for an acute balance-of-payments financing problem and macroeconomic stabilization. The institution most directly aligned with that request is the:',[
 ['World Trade Organization.','Die WTO ist keine allgemeine makroökonomische Kreditfazilität.'],['World Bank in its long-term project-financing role.','Entwicklungsprojekte entsprechen nicht primär dem beschriebenen akuten Stabilisierungsbedarf.'],['International Monetary Fund.','Zahlungsbilanzfinanzierung und makroökonomische Stabilisierung gehören zum IMF-Aufgabenbereich.']
 ],2,['Institution, Finanzierungstyp und Problemhorizont müssen zusammenpassen; Unterstützung kann an Bedingungen geknüpft sein.'],'institutions'),
 q('07','practice','c','A low-income country plans a multi-year water-infrastructure and poverty-reduction project. Which institutional function is most relevant?',[
 ['World Bank development finance and expertise.','Langfristige Entwicklung und Projektunterstützung passen zur Aufgabe.'],['WTO adjudication of a tariff dispute.','Die Aufgabe beschreibt keine Auslegung eines Handelsabkommens.'],['IMF surveillance as a substitute for constructing the water system.','Überwachung allein baut und finanziert das Projekt nicht.']
 ],0,['Die Weltbank-Gruppe umfasst unterschiedliche Einrichtungen. Die konkrete Unterstützung hängt von Land, Projekt und zuständigem Teil der Gruppe ab.'],'institutions'),
 q('08','practice','c','Two members disagree over the interpretation of obligations in a multilateral trade agreement. Which role is most closely associated with the WTO?',[
 ['Guaranteeing the exchange value of member currencies.','Die WTO garantiert keine Währungsparitäten.'],['Providing a framework for trade rules and dispute procedures.','Handelsregeln und Streitbeilegungsrahmen passen zur Institution.'],['Lending directly to any exporter facing weak demand.','Eine solche allgemeine Firmenkreditrolle gehört nicht zu ihrer Kernfunktion.']
 ],1,['Die institutionelle Zuständigkeit bedeutet nicht, dass jedes konkrete Verfahren jederzeit ohne praktische Einschränkungen funktioniert.'],'institutions'),
 q('09','practice','d','An election date is known, but its policy outcome is uncertain. The risk is most naturally classified as:',[
 ['a purely thematic risk with no identifiable decision date.','Die Entscheidung hat gerade einen bekannten Termin.'],['an exogenous shock whose occurrence could not be anticipated.','Die Wahl selbst ist geplant; ihr Ausgang ist offen.'],['event risk.','Ein abgrenzbares Ereignis mit ungewissem Ausgang ist der zentrale Auslöser.']
 ],2,['Die Folgen des Ereignisses können längerfristige Themenrisiken verstärken. Die Einordnung beschreibt hier den unmittelbaren Auslöser.'],'risk-types'),
 q('10','practice','d','A gradual decade-long fragmentation of technical standards is best analyzed primarily as:',[
 ['thematic risk.','Die Entwicklung wirkt als längerfristiger struktureller Prozess.'],['a one-day settlement failure.','Das wäre ein abgrenzbares Abwicklungsereignis.'],['a scheduled election result.','Im Sachverhalt fehlt ein einzelner Wahltermin.']
 ],0,['Ein thematisches Risiko kann durch konkrete Ereignisse beschleunigt werden. Laufzeit und Geschwindigkeit der Wirkung bleiben eigene Beurteilungsgrößen.'],'risk-types'),
 q('11','practice','e f','A profitable subsidiary can legally operate but new restrictions prevent remitting dividends to its parent. The immediate valuation concern is most directly:',[
 ['that local accounting revenue must become zero.','Operativer Umsatz kann trotz Transferbeschränkung fortbestehen.'],['the timing and accessibility of parent-level cash flows.','Gewinn und frei verfügbarer Zahlungsstrom an den Eigentümer unterscheiden sich.'],['that currency translation removes the restriction.','Umrechnung ändert keine rechtliche Transfermöglichkeit.']
 ],1,['Ein Modell braucht gegebenenfalls andere Ausschüttungstermine und Szenarien. Ein pauschaler Abschlag ohne Zahlungsstromanalyse erklärt den Mechanismus nicht.'],'instruments'),
 q('12','practice','e f','A supplier change preserves 140 additional deliveries at a contribution margin of 2,500 each and requires 90,000 of incremental adaptation cost. The incremental operating contribution is:',[
 ['350,000.','Das sind die zusätzlichen Deckungsbeiträge vor Anpassungskosten.'],['440,000.','Die Kosten werden fälschlich addiert.'],['260,000.','140 × 2.500 − 90.000.']
 ],2,[F('\\Delta\\Pi=140\\cdot2500-90000=260000','Der Nutzen erhaltener Lieferungen wird um die zusätzlichen Anpassungskosten vermindert.',[['\\Delta\\Pi','Zusätzlicher operativer Beitrag in Geldeinheiten.']]),'Eine Unternehmensbewertung müsste zusätzlich Zeitwert, Steuern und weitere Zahlungsströme berücksichtigen.'],'exposures'),
 q('13','practice','d f','Risk A has a 3% probability of a loss of 100 million; risk B has a 30% probability of a loss of 10 million. Other outcomes have zero loss. Which statement is correct?',[
 ['Their expected losses are equal, but their loss severity differs.','Beide Erwartungswerte sind 3 Millionen; der seltene Verlust A ist wesentlich größer.'],['Their liquidity requirements must be identical.','Liquidität im Verlustfall hängt auch von der Höhe ab.'],['Risk A has one tenth the expected loss of risk B.','Die zehnfache Verlusthöhe gleicht die kleinere Wahrscheinlichkeit aus.']
 ],0,['Gleicher Erwartungswert bedeutet weder gleiche Verlustverteilung noch gleiche Eignung für einen gegebenen Risikoträger.'],'scenarios'),
 q('14','practice','e f','Without mitigation, an event causes a loss of 40. Mitigation costs 3 in every state and reduces the event loss to 10. At which event probability are expected costs equal?',[
 ['7.50%.','3/40 ignoriert den verbleibenden Verlust nach Absicherung.'],['10.00%.','3/(40 − 10).'],['30.00%.','Die absolute Risikoreduktion 30 ist keine Wahrscheinlichkeit.']
 ],1,[F('40p=3+10p\\Rightarrow p=3/30=10\\%','Die sichere Ausgabe muss durch den erwarteten vermiedenen Verlust gedeckt werden.',[['p','Ereigniswahrscheinlichkeit.']])],'mitigation'),
 q('15','practice','d f','An analyst sees five articles repeating the same original unverified report. Relative to that original report, the five articles should be treated primarily as:',[
 ['five independent confirmations.','Die Informationsquelle ist gemeinsam.'],['evidence that the event probability has reached 100%.','Wiederholung beseitigt die Unsicherheit nicht.'],['potentially dependent repetitions requiring source verification.','Die gemeinsame Herkunft begrenzt den zusätzlichen Informationsgehalt.']
 ],2,['Aktualisierung von Wahrscheinlichkeiten verlangt neue Information und eine Beurteilung ihrer Zuverlässigkeit, nicht bloß Nachrichtenhäufigkeit.'],'signposts'),
 q('16','practice','f','Expected cash flows already include scenario-weighted losses from a supply disruption. The analyst then subtracts the identical expected loss again as a valuation adjustment. This most likely:',[
 ['double counts the same cash-flow effect.','Derselbe erwartete Verlust wird zweimal abgezogen.'],['is required whenever risk is geopolitical.','Die Bezeichnung begründet keine doppelte Berücksichtigung.'],['eliminates the need to consider market risk premia.','Erwartete Verluste und Preise für systematische Risiken sind verschiedene Komponenten.']
 ],0,['Ein Risikozuschlag kann für andere, noch nicht berücksichtigte preisrelevante Risiken begründet sein. Er muss konsistent zu den verwendeten Zahlungsströmen sein.'],'valuation'),
 q('17','practice','e','A state uses export licensing to restrict access to advanced production equipment. The most direct initial transmission channel is:',[
 ['a reduction in the importing country statutory income-tax rate.','Die Lizenzregel verändert diesen Steuersatz nicht unmittelbar.'],['availability and cost of the affected productive inputs.','Die Maßnahme beschränkt Zugang zu einem Produktionsmittel.'],['a guaranteed increase in all affected companies dividends.','Gewinne und Ausschüttungen folgen nicht automatisch in diese Richtung.']
 ],1,['Substitute, Lagerbestände, Weitergabemöglichkeiten und Durchsetzung beeinflussen die tatsächliche Wirkung.'],'instruments'),
 q('18','practice','f','A portfolio holds firms headquartered in six countries, but all depend on the same critical processing facility. Geographic diversification of headquarters:',[
 ['fully diversifies the processing disruption risk.','Der gemeinsame Engpass bleibt bestehen.'],['makes supplier exposure irrelevant to portfolio risk.','Der Zulieferer kann viele Portfoliounternehmen gleichzeitig treffen.'],['may overstate diversification of this specific exposure.','Sitzstaaten bilden die tatsächliche gemeinsame Abhängigkeit nicht vollständig ab.']
 ],2,['Die geeignete Risikoeinheit ist hier die Lieferabhängigkeit. Länderlisten sollten durch wirtschaftliche Expositionsdaten ergänzt werden.'],'valuation'),
 q('a1','mock-a','d e f','An event has probability 15% and causes a loss of 60 if no action is taken. A plan costs 4 in every state and lowers the event loss to 20 without changing its probability. Its expected cost advantage over no action is:',[
 ['2.00.','Ohne Plan 9, mit Plan 4 + 3 = 7.'],['6.00.','Das ist der erwartete vermiedene Ereignisverlust vor sicheren Plankosten.'],['7.00.','Das sind die gesamten erwarteten Kosten mit Plan.']
 ],0,[F('\\Delta E[C]=0{,}15\\cdot60-(4+0{,}15\\cdot20)=2','Die sicheren Kosten fallen auch ohne Ereignis an.',[['\\Delta E[C]','Erwartete Kostenersparnis durch den Plan.']]),'Eine Entscheidung kann zusätzlich Liquidität, Verlustspitzen und Unsicherheit der Wahrscheinlichkeit berücksichtigen.'],'mitigation'),
 q('b1','mock-b','a c','A country faces an external financing crisis, while a separate agency plans a ten-year rural electrification project. The most appropriate initial institutional mapping is:',[
 ['WTO for external crisis lending; IMF for the electricity project.','Die WTO ist keine Zahlungsbilanzkreditinstitution; der Projektfokus ist ebenfalls vertauscht.'],['IMF for macroeconomic stabilization; World Bank for long-term development support.','Die Problemhorizonte passen zu diesen Kernaufgaben.'],['World Bank for adjudicating trade rules; WTO for infrastructure finance.','Beide genannten Funktionen sind falsch zugeordnet.']
 ],1,['Die genaue Zuständigkeit und Finanzierungsfähigkeit sind fallabhängig. Die Grundzuordnung unterscheidet Stabilisierung, Entwicklung und Handelsregeln.'],'institutions')
];
