const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('gov-'+id,'governance','corporate',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','A principal delegates investment decisions to a manager who has better information about the decisions and may prefer personal benefits. The central governance concern is:',[
 ['divergent interests combined with limited observability or control.','Der Informationsvorsprung kann es erschweren, eigennützige Entscheidungen rechtzeitig zu erkennen.'],['that delegation necessarily makes every decision illegal.','Delegation ermöglicht sinnvolle Spezialisierung und ist nicht an sich unzulässig.'],['that the principal and agent must possess identical information in every efficient firm.','Wirksame Arbeitsteilung setzt häufig gerade unterschiedliche Kenntnisse voraus.']
 ],['Das Principal-Agent-Problem betrifft die Ausrichtung delegierter Handlungsspielräume. Kontrolle und Anreize sollen sie mit dem Mandat verbinden.','Ein Informationsvorsprung allein beweist noch kein Fehlverhalten; die möglichen eigenen Interessen und Kontrollmöglichkeiten werden zusätzlich untersucht.'],'delegation'),
 q('02','practice','a','A carefully evaluated project loses money because of an unforeseeable market shock. Which conclusion is most appropriate?',[
 ['The poor outcome alone does not establish negligent or disloyal decision-making.','Handlungsqualität und Ergebnis sind verschiedene Größen.'],['Any negative outcome proves a principal-agent violation.','Auch sorgfältige Entscheidungen können unter Unsicherheit scheitern.'],['No review is appropriate because the outcome was unexpected.','Eine Nachprüfung der Annahmen und Prozesse bleibt sinnvoll, ohne das Ergebnis allein als Schuldbeweis zu verwenden.']
 ],['Der Analyst prüft Informationen, Sorgfalt, Mandat und Interessenkonflikte zum Entscheidungszeitpunkt. Rückblickendes Wissen darf nicht automatisch mit damals verfügbarem Wissen gleichgesetzt werden.','Auch ein zufällig gutes Ergebnis würde umgekehrt keinen mangelhaften Prozess rechtfertigen.'],'delegation'),
 q('03','practice','a','A manager owns 3% of equity. A decision reduces total equity value by €4 million but provides the manager a separately defined private benefit worth €200,000. Ignore taxes, penalties, reputation effects, and all other consequences. The manager’s net private wealth change is:',[
 ['€80,000','Privater Vorteil 200.000 abzüglich drei Prozent des Aktienwertverlusts, also 120.000.'],['−€3,800,000','Dies belastet die Führungskraft fälschlich mit dem gesamten Wertverlust aller Aktien.'],['€200,000','Dies ignoriert den Verlust der eigenen Beteiligung.']
 ],[F('\\Delta W_M=200000-0{,}03\\cdot4000000=80000','Die Kostenbeteiligung ist anteilig, der gesonderte Vorteil dagegen vollständig.',[['\\Delta W_M','Private Nettovermögensänderung der Führungskraft in Euro.']]),'Aktienbesitz kann den Konflikt begrenzen, beseitigt ihn im Modell aber nicht. Das Rechenresultat ist keine Aussage zur Zulässigkeit der Handlung.'],'private-incentives'),
 q('04','practice','a b','In the classical agency-cost framework, bonding most accurately refers to:',[
 ['resources used by an agent to credibly constrain or assure its behavior toward the principal.','Es geht um glaubwürdige Bindung oder Zusicherung in der Delegationsbeziehung.'],['issuing a corporate bond regardless of its terms.','Das englische Wort wird hier nicht im Sinn einer Anleiheemission verwendet.'],['the entire residual payoff received by common shareholders.','Residualanspruch und Bindungsaufwand sind unterschiedliche Begriffe.']
 ],['Monitoring stammt aus Überwachungsmaßnahmen, Bonding aus glaubwürdiger Bindung des Agenten, Residual Loss aus dem verbleibenden Nachteil.','Die Einteilung beschreibt Kosten und ihre Begrenzung, nicht bloß den Interessenkonflikt als solchen.'],'agency-costs'),
 q('05','practice','a c','On a consistent annual basis, monitoring costs are 0.3, bonding costs are 0.1, and the remaining economic loss from divergent decisions is 0.9. Total agency costs are:',[
 ['1.3','Alle drei getrennt erfassten Komponenten werden addiert.'],['0.4','Dies lässt den verbleibenden wirtschaftlichen Verlust weg.'],['0.9','Dies lässt Überwachungs- und Bindungsaufwand weg.']
 ],[F('AC=0{,}3+0{,}1+0{,}9=1{,}3','Die Frage verwendet dieselbe Perioden- und Bewertungsbasis für alle Größen.',[['AC','Gesamte jährliche Agency-Kosten in der vorgegebenen Einheit.']]),'Ein niedriger Restschaden allein beweist keine geringen Gesamtkosten, wenn seine Vermeidung sehr teuer ist.'],'agency-costs'),
 q('06','practice','b c','Two additional control packages both satisfy all legal and mandatory requirements. Package A costs 0.5 and leaves expected loss of 2.0. Package B costs 1.2 and leaves expected loss of 1.1. Each also has separate bonding costs of 0.2. Under this complete one-period model:',[
 ['B has lower total modeled costs by 0.2.','A kostet insgesamt 2,7; B insgesamt 2,5.'],['A is preferable solely because its control budget is smaller.','Der verbleibende Schaden gehört ebenso in die Vergleichsrechnung.'],['B eliminates the need to consider any residual risk.','Im Modell verbleibt ausdrücklich ein erwarteter Verlust von 1,1.']
 ],['Zuerst werden Kontrolle, Bindung und verbleibender Verlust zusammengeführt. Der höhere Budgetbetrag kann durch stärkere Schadensminderung mehr als ausgeglichen werden.','Die Aussage gilt für die angegebenen vollständigen Modellkosten. Gesetzliche Pflichten oder ausgelassene wesentliche Folgen dürfen nicht wegoptimiert werden.'],'agency-costs'),
 q('07','practice','a','A controlling shareholder also owns a separate supplier and favors overpriced purchases from that supplier. The most direct shareholder conflict is between:',[
 ['the controlling shareholder and minority shareholders of the buyer.','Die gesonderte Verkäuferbeteiligung schafft asymmetrische Vorteile.'],['all shareholders with exactly identical external interests.','Die Minderheit besitzt im Fall keinen identischen Anspruch am Lieferanten.'],['only bondholders and suppliers, with no possible equity effect.','Ein überhöhter Einkaufspreis kann auch den verbleibenden Gesellschaftswert vermindern.']
 ],['Mehrheitseigentum schafft nicht automatisch eine einheitliche Interessenlage. Zunächst werden beide Gesellschaften und die jeweiligen Beteiligungsrechte getrennt erfasst.','Der Konflikt verlangt Preisprüfung und ein angemessenes Verfahren für nahestehende Geschäfte.'],'minority-protection'),
 q('08','practice','a b','After borrowing on fixed terms, shareholders can choose a much riskier operating strategy that benefits equity while reducing the expected recovery of old lenders. Which mechanism most directly addresses that conflict?',[
 ['Appropriately defined debt covenants and monitoring of the agreed risk restrictions.','Die Schutzrechte setzen am alten Zahlungsanspruch und seiner veränderten Deckung an.'],['Giving the CEO a bonus based only on the resulting share price increase.','Das kann den Eigentümeranreiz verstärken, ohne den Gläubigerschutz zu verbessern.'],['Assuming the lender’s promised payment automatically adjusts upward.','Die Fallbeschreibung setzt unveränderte alte Vertragsbedingungen voraus.']
 ],['Die Maßnahme sollte genau den Risikotransfer begrenzen oder ein zulässiges Verfahren zur Zustimmung eröffnen. Vertragliche Definitionen und Durchsetzung bleiben entscheidend.','Zu enge Regeln können sinnvolle Anpassungen verhindern; auch ihre Kosten und Flexibilität werden geprüft.'],'creditor-controls'),
 q('09','practice','b','A non-executive director receives substantial consulting revenue from the company. The analyst should:',[
 ['examine whether that economic relationship compromises independent judgment.','Nicht operativ angestellt zu sein beweist keine wirtschaftliche Unabhängigkeit.'],['classify the director as independent solely because the director is non-executive.','Dies setzt zwei verschiedene Eigenschaften gleich.'],['conclude that every consulting relationship automatically proves fraud.','Ein Interessenkonflikt erfordert Prüfung; er ist für sich noch kein Betrugsnachweis.']
 ],['Unabhängigkeit wird anhand relevanter Beziehungen und tatsächlicher Einflussmöglichkeiten beurteilt. Zusätzliche Vergütung kann Abhängigkeit schaffen.','Kompetenz, Zeit und Informationszugang müssen daneben ebenfalls betrachtet werden.'],'committees'),
 q('10','practice','b','Which statement about one-tier and two-tier board systems is most defensible?',[
 ['Structural separation can support oversight but does not by itself prove independence, competence, or effectiveness.','Organstruktur und tatsächliche Kontrollwirkung sind getrennte Ebenen.'],['A two-tier system guarantees that no conflict can occur.','Auch getrennte Organe können abhängig, schlecht informiert oder ungeeignet sein.'],['A one-tier system necessarily prohibits non-executive oversight.','Im Grundmodell kann ein einstufiges Board nicht geschäftsführende Mitglieder enthalten.']
 ],['Ein sinnvolles Urteil untersucht Zuständigkeit, Personen, Rechte und Informationen. Nationale Regeln können die konkrete Ausgestaltung verändern.','Kein Organigramm ersetzt den Nachweis, wie wesentliche Entscheidungen tatsächlich hinterfragt werden.'],'board-structure'),
 q('11','practice','b','A board creates a risk committee to examine complex exposures. The most appropriate general conclusion is that:',[
 ['the committee supports deeper review while overall board accountability does not simply disappear.','Aufgabenteilung kann Arbeit vertiefen, hebt die Verantwortung des Gesamtorgans aber nicht pauschal auf.'],['the full board is automatically relieved of all responsibility for risk.','Delegation an einen Ausschuss ist keine generelle Haftungs- oder Verantwortungsbefreiung.'],['the committee must personally execute every routine operating trade.','Aufsicht ist nicht mit laufender operativer Ausführung gleichzusetzen.']
 ],['Mandat, Besetzung und Berichtswege müssen klar sein. Die Geschäftsführung bleibt für die laufende Steuerung innerhalb ihrer Befugnisse verantwortlich.','Rechtlich besondere Zuständigkeiten müssen konkret geprüft werden statt sie aus einem Ausschussnamen abzuleiten.'],'committees'),
 q('12','practice','b c','Which task is most consistent with an audit committee’s oversight role?',[
 ['Reviewing the integrity of financial reporting and following up on significant control deficiencies.','Berichtsqualität und wirksame Nachverfolgung gehören zum typischen Prüfungsaufsichtsbereich.'],['Preparing the company’s accounting records in place of management.','Damit würden operative Erstellung und unabhängige Überwachung vermischt.'],['Guaranteeing that every future investment earns a positive return.','Prüfungsaufsicht schafft keine Garantie künftiger wirtschaftlicher Ergebnisse.']
 ],['Das Audit Committee benötigt geeignete Information und Zugang zu Prüfern. Die Verantwortung für die Erstellung des Abschlusses verbleibt beim zuständigen Management.','Auch eine unabhängige externe Prüfung hat einen bestimmten Umfang und ist keine vollständige Risikogarantie.'],'committees'),
 q('13','practice','a b','A CEO determines the CEO’s own bonus formula without independent review. The most direct governance improvement is:',[
 ['an appropriately independent remuneration process with measurable, suitable performance conditions.','Die Begünstigten sollen die eigene Vergütung nicht unkontrolliert bestimmen.'],['automatic payment of every proposed bonus whenever earnings rise.','Ein Gewinnanstieg allein beweist weder Wertschaffung noch Angemessenheit der Vergütung.'],['replacement of all performance measures with the number of board meetings.','Eine leicht zählbare Kennzahl muss nicht zum wirtschaftlichen Mandat passen.']
 ],['Der Vergütungsprozess prüft Ziele, Risiko, Zeithorizont und Interessenkonflikte. Er braucht belastbare Kriterien und die Möglichkeit, ungerechtfertigte Anpassungen abzulehnen.','Die Bezeichnung „unabhängig“ allein genügt ohne entsprechende Personen und Rechte nicht.'],'committees'),
 q('14','practice','b','A nomination committee is most directly concerned with:',[
 ['identifying suitable board candidates and planning composition and succession.','Die Auswahl soll zu den benötigten Fähigkeiten und Aufgaben passen.'],['authorizing every daily supplier payment.','Dies ist eine operative Aufgabe, keine gewöhnliche Nominierungsfunktion.'],['calculating the market price of every outstanding option.','Optionsbewertung ist nicht der zentrale Auftrag dieses Ausschusses.']
 ],['Kandidatenprofil, Kompetenzmix und ein transparentes Verfahren stehen im Mittelpunkt. Die bloße Wiederbesetzung aus persönlichen Netzwerken kann notwendige unabhängige Perspektiven fehlen lassen.','Konkrete Wahl- und Vorschlagsrechte der Aktionäre bleiben zu beachten.'],'committees'),
 q('15','practice','a b','A fully vested award contains 10,000 call options, each covering one share, with exercise price €50. At expiry, the share price will be €40 or €80 with equal probability. Ignore taxes and fees. The expected exercise payoff is:',[
 ['€150,000','Niedriger Zustand null, hoher Zustand 300.000; der gleich gewichtete Durchschnitt ist 150.000.'],['€100,000','Dies setzt den erwarteten Kurs 60 direkt in die nicht lineare Auszahlungsformel ein.'],['€600,000','Dies ist der erwartete Wert von 10.000 Aktien, ohne Ausübungspreis und Optionsschwelle.']
 ],[F('\\mathbb{E}[W_O]=0{,}5\\cdot0+0{,}5\\cdot10000(80-50)=150000','Zuerst wird jeder Zustand nach der Optionsregel bewertet, dann werden die Auszahlungen gewichtet.',[['\\mathbb{E}[W_O]','Erwartete Optionsauszahlung am Ausübungszeitpunkt in Euro.']]),'Bei einem sicheren Kurs von 60 wären es 100.000. Der Unterschied erklärt die Nichtlinearität; er ist keine Berechnung heutiger Optionspreise.'],'equity-pay'),
 q('16','practice','a b','A bonus pays 5% of annual profit above €10 million, capped at €0.5 million. Profit before the bonus is €18 million. The bonus is:',[
 ['€400,000','Fünf Prozent des Überschusses von acht Millionen ergeben 0,4 Millionen, unterhalb der Obergrenze.'],['€900,000','Dies wendet den Prozentsatz auf den gesamten Gewinn an und ignoriert zusätzlich die Obergrenze.'],['€500,000','Die Obergrenze ist kein automatisch ausgezahlter Mindestbonus.']
 ],[F('B=\\min(500000,0{,}05\\max(18000000-10000000,0))=400000','Schwelle und Obergrenze werden in der angegebenen Reihenfolge berücksichtigt.',[['B','Bonus in Euro.']]),'Die Vertragsgröße ist ausdrücklich Gewinn vor Bonus. Eine Definition nach Bonus würde eine andere Rechnung verlangen.'],'bonus-horizon'),
 q('17','practice','b','A compensation policy permits recovery of bonuses already paid if specified reporting errors are later established. This recovery mechanism is most appropriately described as:',[
 ['clawback, with its practical effect depending on the applicable terms and enforceability.','Bereits ausgezahlte Vergütung soll unter bestimmten Voraussetzungen zurückgefordert werden.'],['vesting, which necessarily guarantees immediate repayment.','Vesting betrifft das Unverfallbarwerden, keine allgemeine Rückzahlungsgarantie.'],['an automatic elimination of all incentives to misreport.','Auch eine Rückforderungsklausel beseitigt nicht jedes Informations- und Durchsetzungsproblem.']
 ],['Malus und Clawback unterscheiden sich insbesondere danach, ob noch zurückgehaltene oder bereits gezahlte Vergütung betroffen ist. Die konkrete Ausgestaltung entscheidet.','Ein Vertragstext ist noch kein Nachweis, dass ein Anspruch in jeder Lage vollständig eingetrieben werden kann.'],'bonus-horizon'),
 q('18','practice','a b','A board replaces short-dated options with shares subject to a multiyear holding requirement. Which conclusion is most appropriate?',[
 ['The change can alter horizon and downside exposure, but the complete incentive package still requires review.','Instrument und Haltezeit können das Verhalten ändern, ohne alle Konflikte zu beseitigen.'],['All private benefits and reporting incentives necessarily disappear.','Aktienbesitz und Haltepflicht schaffen keine vollständige Interessenidentität.'],['End payoffs alone prove both packages have identical current fair values.','Eine faire heutige Wertgleichheit braucht weitere Bewertungsinformationen.']
 ],['Die Analyse prüft Vergütungsgröße, Bedingungen, andere Vermögensrisiken und das Mandat gemeinsam. Eine Führungskraft kann gleichzeitig Arbeitsplatz- und Beteiligungsrisiko tragen.','Weder das Wort Aktie noch das Wort langfristig ersetzt diese Prüfung.'],'equity-pay'),
 q('19','practice','a c','An individual owns 70% of a buyer and all of a seller. A transaction transfers €3 million of value from the buyer to the seller through overpricing. Ignore taxes and other effects. The individual’s net wealth gain in millions is:',[
 ['0.9','Der volle Verkäufergewinn von drei wird um 70 % des Käuferverlusts, also 2,1, vermindert.'],['3.0','Dies ignoriert die eigene Beteiligung am geschädigten Käufer.'],['2.1','Dies ist der Verlust des eigenen Käuferanteils, nicht der Nettovorteil.']
 ],[F('\\Delta W_C=3-0{,}70\\cdot3=0{,}9','Die Minderheit trägt die verbleibenden 30 % des übertragenen Betrags.',[['\\Delta W_C','Privater Nettovorteil in Millionen Euro.']]),'Ein Mehrheitsaktionär kann trotz eigener anteiliger Belastung profitieren, wenn ein externer Vorteil vollständig bei ihm ankommt.'],'minority-protection'),
 q('20','practice','a b','A company discloses a large related-party purchase in the notes to its financial statements. The disclosure alone:',[
 ['does not establish that the price and approval process were fair.','Information und wirtschaftliche Angemessenheit sind verschiedene Prüfungen.'],['proves the transaction could not disadvantage minority shareholders.','Ein offengelegter überhöhter Preis kann weiterhin Minderheiten belasten.'],['means every related-party transaction must be prohibited.','Solche Beziehungen können auch legitime und vorteilhafte Geschäfte ermöglichen.']
 ],['Die Beziehung, Bedingungen, Vergleichspreise und Entscheidung ohne unkontrollierte Mitwirkung Begünstigter werden zusätzlich geprüft.','Offenlegung ist notwendig für Transparenz, aber kein Ersatz für eine geeignete Sachprüfung oder erforderliche Genehmigung.'],'minority-protection'),
 q('21','practice','b','A shareholder holds 40 one-vote shares. Five board seats are filled simultaneously using cumulative voting. How many votes may the shareholder concentrate on a single nominee?',[
 ['200','40 Aktien mal fünf gleichzeitig vergebene Sitze.'],['40','Dies übersieht die Kumulation über alle Sitze.'],['8','Dies teilt die Aktienzahl durch die Zahl der Sitze statt Stimmen zusammenzuführen.']
 ],[F('V=40\\cdot5=200','Kumulative Stimmen dürfen nach den angegebenen Regeln auf einen Kandidaten konzentriert werden.',[['V','Verfügbare kumulierbare Stimmen.']]),'Ob diese Stimmen für einen Sitz genügen, hängt zusätzlich von Gesamtstimmen, Teilnahme und Konkurrenz ab. Die Frage fragt nur nach dem verfügbaren Stimmvolumen.'],'shareholder-rights'),
 q('22','practice','b c','A company elects only one-third of its directors each year. This arrangement most directly:',[
 ['supports continuity but can make rapid replacement of the full board more difficult.','Gestaffelte Mandate haben sowohl Kontinuitäts- als auch Verfestigungseffekte.'],['guarantees that every incumbent is independent.','Wahlrhythmus und persönliche Unabhängigkeit sind getrennte Eigenschaften.'],['eliminates any need for shareholder information before elections.','Wirksame Wahlrechte benötigen weiterhin geeignete Unterlagen.']
 ],['Die Struktur wird als Staggered Board bezeichnet. Ihre Wirkung hängt von weiteren Kontroll-, Abberufungs- und Eigentümerrechten ab.','Ein Merkmal kann nützlich sein und zugleich die Disziplinierung schwacher Leitung erschweren.'],'shareholder-rights'),
 q('23','practice','b c','The head of internal audit is asked to take permanent responsibility for approving supplier payments and then independently audit that same process without safeguards. The most direct concern is:',[
 ['self-review arising from combining operational responsibility with independent assurance.','Eigene operative Entscheidungen würden anschließend als unabhängig geprüft erscheinen.'],['that internal audit must never communicate with management.','Zusammenarbeit ist sinnvoll, solange Objektivität und Unabhängigkeit erhalten bleiben.'],['that every control activity belongs exclusively to the external auditor.','Management besitzt eigene Prozess- und Kontrollverantwortung.']
 ],['Die Rollen benötigen klare Abgrenzung und gegebenenfalls geeignete Schutzmaßnahmen. Ein unabhängiger Berichtskanal, Kompetenz und Ressourcen sind ebenfalls wichtig.','Unabhängigkeit bedeutet nicht Isolation, sondern die Möglichkeit objektiver Beurteilung ohne unangemessene Einflussnahme.'],'reporting-controls'),
 q('24','practice','b c','A company receives an unmodified external audit opinion on its financial statements. An investor should most appropriately infer that:',[
 ['the opinion provides assurance within its stated reporting and audit scope, without guaranteeing future profitability or absence of every fraud.','Aussage und Grenzen richten sich nach dem konkreten Prüfungsrahmen.'],['all future forecasts are guaranteed to be achieved.','Ein Urteil über Abschlüsse ist keine Garantie der Zukunft.'],['management no longer remains responsible for preparing financial reports.','Die externe Prüfung ersetzt die Verantwortung des Erstellers nicht.']
 ],['Der Bericht wird auf Zeitraum, Prüfungsgegenstand und maßgeblichen Rahmen gelesen. Zusätzliche Prognosen oder andere Berichte sind nicht automatisch umfasst.','Prüfungsurteil, Geschäftsaussicht und konkrete Governancequalität bleiben unterschiedliche Analysefragen.'],'reporting-controls'),
 q('25','practice','b','A covenant defines leverage as debt minus eligible cash, divided by covenant EBITDA. Debt is 150, eligible cash is 30, and EBITDA is 32. The company uses 20 of eligible cash to repay debt immediately. With no other changes, the ratio after repayment is:',[
 ['3.75','Nach Tilgung stehen 130 Schuld minus zehn Cash weiterhin für 120 Nettoschuld.'],['3.125','Dies senkt nur die Schuld im Zähler, hält aber den verbrauchten Cash fälschlich konstant.'],['4.0625','Dies dividiert die Bruttoschuld 130 durch EBITDA und lässt den verbleibenden Cash weg.']
 ],[F('L=\\frac{(150-20)-(30-20)}{32}=3{,}75','Beide Bilanzpositionen ändern sich um denselben Zahlungsbetrag.',[['L','Vertraglich definierte Nettoverschuldungsquote nach der Tilgung.']]),'Eine reine Umschichtung zwischen anrechenbarem Cash und Schuld heilt diese Nettoschuldkennzahl nicht. Anders definierte Verträge können anders reagieren.'],'creditor-controls'),
 q('26','practice','b','A debt covenant allows deduction only of unrestricted cash. The company has debt of 96, unrestricted cash of 12, restricted cash of 8, and covenant EBITDA of 28. The contractual net leverage ratio is:',[
 ['3.00','Nur die ausdrücklich anrechenbaren zwölf werden abgezogen: 84 geteilt durch 28.'],['2.71','Dies zieht den gesperrten Cash unzulässig ebenfalls ab.'],['3.43','Dies ignoriert den zulässigen Abzug des frei verfügbaren Cash.']
 ],[F('L=\\frac{96-12}{28}=3','Die Vertragsdefinition entscheidet über den Zähler.',[['L','Nettoverschuldungsquote gemäß der angegebenen Klausel.']]),'Eine gewöhnliche Analysekennzahl darf nicht ohne Abgleich als Vertragskennzahl ausgegeben werden. Auch EBITDA-Bereinigungen und Prüftermine müssen passen.'],'creditor-controls'),
 q('27','practice','b c','After a company introduces a trusted confidential reporting channel, employee reports increase. This most appropriately suggests that the analyst should:',[
 ['examine reporting trust, substantiation, follow-up, and actual misconduct rather than treating the count alone as proof of deterioration.','Mehr Meldungen können bessere Sichtbarkeit oder mehr Probleme widerspiegeln.'],['conclude that the new channel necessarily caused more misconduct.','Die höhere Beobachtungszahl beweist keinen solchen ursächlichen Anstieg.'],['reward management solely for reducing the report count to zero.','Dies könnte Unterdrückung von Meldungen statt wirksame Abhilfe belohnen.']
 ],['Bearbeitungsdauer, wiederkehrende Befunde, tatsächliche Abhilfe und Schutz vor Nachteilen liefern zusätzlichen Kontext.','Ein Hinweis ist ein Untersuchungsanlass. Eine niedrige Zahl kann auch Angst oder mangelnde Zugänglichkeit anzeigen.'],'other-mechanisms'),
 q('28','practice','b c','An issuer adopts a voluntary governance code while operating under binding legal requirements. Which approach is most appropriate?',[
 ['Distinguish the code’s commitments from legal duties and examine how each is implemented and enforced.','Freiwillige Regeln und verbindliche Pflichten haben unterschiedliche Grundlagen.'],['Assume adopting the code replaces all applicable law.','Eine freiwillige Selbstverpflichtung beseitigt gesetzliche Pflichten nicht.'],['Treat publication of the code as proof that every control operates effectively.','Eine veröffentlichte Regel ist kein Nachweis ihrer tatsächlichen Umsetzung.']
 ],['Die Prüfung verbindet konkrete Vorschriften mit Zuständigkeiten, Ressourcen, Information und Nachverfolgung. Unterschiede zwischen Ländern und Branchen bleiben relevant.','Weder Gesetzestext noch Richtlinienzahl beweisen allein die Wirksamkeit im Einzelfall.'],'other-mechanisms'),
 q('29','practice','c','All mandatory controls are satisfied. A further annual control costs 0.4 million and reduces the probability of a 15 million loss from 6% to 2%. With no other effects, its expected annual net benefit in millions is:',[
 ['0.2','Vermiedener erwarteter Verlust 0,6 minus Kontrollkosten 0,4.'],['0.6','Dies lässt die Kosten der zusätzlichen Maßnahme weg.'],['0.9','Dies ist der Ausgangserwartungswert des Verlusts; das Risiko wird nicht vollständig beseitigt.']
 ],[F('\\Delta V=(0{,}06-0{,}02)\\cdot15-0{,}4=0{,}2','Die Änderung der Eintrittswahrscheinlichkeit beträgt vier Prozentpunkte.',[['\\Delta V','Erwarteter jährlicher Nettovorteil in Millionen.']]),'Die Berechnung gilt für die angegebenen zusätzlichen zulässigen Maßnahmen. Sie ersetzt keine Prüfung ausgelassener Schäden oder verpflichtender Mindeststandards.'],'risk-benefit'),
 q('30','practice','c','Firms with a certain governance feature have historically earned higher returns in a sample. This finding alone:',[
 ['does not prove causation or guarantee an attractive investment at the current price.','Drittvariablen, Auswahl und bereits eingepreiste Erwartungen können das Ergebnis erklären oder verändern.'],['proves that adding the feature will raise every firm’s future return.','Eine statistische Beziehung begründet keine universelle kausale Wirkung.'],['means that governance can have no effect on cash flows.','Fehlender Kausalitätsbeweis aus einer einzelnen Beobachtung widerlegt keinen möglichen wirtschaftlichen Mechanismus.']
 ],['Der Analyst untersucht Branche, Eigentum, Unternehmenslage und die zeitliche Reihenfolge. Bereits erfolgreiche Unternehmen können sich bestimmte Strukturen eher leisten.','Geschäftsqualität und Wertpapierbewertung zum aktuellen Preis bleiben gesonderte Fragen.'],'risk-benefit'),
 q('31','practice','a b c','A board receives repeated reports of a significant purchasing-control deficiency involving a supplier owned by the controller. No person is assigned to remedy it. The most appropriate next step is:',[
 ['independent review of the relationship and transactions, with accountable remediation and follow-up evidence.','Die Maßnahme trifft sowohl den Interessenkonflikt als auch das erkennbare Umsetzungsproblem.'],['more frequent reports without assigning anyone responsibility.','Weitere Information allein löst fehlende Zuständigkeit und Abhilfe nicht.'],['automatic acceptance because the supplier relationship is disclosed.','Offenlegung beweist weder faire Bedingungen noch wirksame Kontrolle.']
 ],['Der Befund wird mit Vertragsbedingungen, Vergleichspreisen und Genehmigungswegen abgeglichen. Interessierte Personen dürfen die Konfliktprüfung nicht unkontrolliert bestimmen.','Fristen, Verantwortliche und unabhängige Wirksamkeitsnachweise machen aus einem Bericht eine überprüfbare Reaktion.'],'integrated-case'),
 q('32','practice','a b c','An analyst ranks governance quality solely by the number of policies and board meetings. The main weakness is that:',[
 ['activity counts do not establish how well conflicts, information, responsibility, and remediation are handled.','Formaler Umfang und tatsächliche Funktionsfähigkeit sind nicht identisch.'],['having any policies necessarily weakens control.','Geeignete Regeln können nützlich sein; kritisiert wird der alleinige Zählmaßstab.'],['shareholder rights and incentive terms are unrelated to governance.','Diese Größen gehören gerade zur Untersuchung der Entscheidungsstruktur.']
 ],['Ein belastbares Urteil beginnt bei konkreten Entscheidungen und Risiken. Es prüft, wer handelt, wer gesondert profitiert, wer unabhängig kontrolliert und was bei Abweichungen tatsächlich geschieht.','Mehr Sitzungen können gründliche Arbeit oder die Bewältigung wiederholter Probleme bedeuten.'],'analyst-check'),
 q('a1','mock-a','a c','An owner controls Buyer through enhanced voting rights but holds only 25% of its economic rights. The owner also holds all economic rights in Seller. Buyer overpays Seller by 1.6 million with no other effects. The owner’s net economic gain in millions is:',[
 ['1.2','Voller Verkäufergewinn 1,6 abzüglich 25 % eigener Käuferverlust, also 0,4.'],['0.4','Dies ist die Belastung des eigenen Käuferanteils, nicht der Nettovorteil.'],['1.6','Dies ignoriert den eigenen wirtschaftlichen Anteil am geschädigten Käufer.']
 ],[F('\\Delta W_C=1{,}6-0{,}25\\cdot1{,}6=1{,}2','Für die Vermögenswirkung werden wirtschaftliche Rechte verwendet, nicht das höhere Stimmgewicht.',[['\\Delta W_C','Nettovermögenszuwachs der kontrollierenden Person in Millionen.']]),'Die übrigen wirtschaftlichen Eigentümer der Käuferin verlieren ebenfalls 1,2. Stimmkontrolle ermöglicht die Entscheidung, bestimmt aber nicht allein die Verteilung der Wertänderung.'],'minority-protection'),
 q('a2','mock-a','b c','A covenant defines net debt as debt less eligible cash and caps net debt/EBITDA at 2.5. Debt is 90, eligible cash is 10, and covenant EBITDA is 30. A proposal uses 5 of eligible cash to repay debt. With no other changes, the proposal:',[
 ['leaves net debt at 80 and does not restore compliance.','85 Schuld minus fünf Cash bleiben 80; die Quote bleibt etwa 2,67.'],['reduces net debt to 75 and restores compliance at exactly 2.5.','Das rechnet die Tilgung, lässt aber den gleichzeitigen Verbrauch des Cash weg.'],['automatically forces liquidation under every debt agreement.','Die Kennzahl legt ohne weitere Vertragsangaben keine solche Rechtsfolge fest.']
 ],[F('L=\\frac{85-5}{30}\\approx2{,}67>2{,}5','Tilgung aus anrechenbarem Cash verändert den vertraglichen Nettobetrag nicht.',[['L','Nettoverschuldungsquote nach dem vorgeschlagenen Vorgang.']]),'Bei unverändertem EBITDA dürfte die Nettoschuld höchstens 75 betragen. Nachbesserungs- und Verzichtsmöglichkeiten müssten im tatsächlichen Vertrag geprüft werden.'],'creditor-controls'),
 q('b1','mock-b','a b','A CEO’s bonus depends on an annual profit threshold. The CEO also proposes the bonus adjustments and controls which information reaches directors. Which response most directly addresses the described conflict?',[
 ['Independent remuneration review supported by direct information access and performance conditions aligned with the decision horizon.','Anreizgestaltung und Informationsabhängigkeit werden beide angegangen.'],['More options based solely on the same annual reported profit, with the CEO retaining exclusive control of information.','Dies lässt das geschilderte Kontrollproblem bestehen und kann den Anreiz verstärken.'],['Relying exclusively on the next external audit to guarantee that every decision served shareholders.','Die Abschlussprüfung hat weder diese vollständige Reichweite noch eine Garantie wirtschaftlicher Optimalität.']
 ],['Die passende Maßnahme wird aus dem konkreten Mechanismus abgeleitet. Unabhängige Vergütungsprüfung benötigt belastbare Informationen und darf von den Begünstigten nicht kontrolliert werden.','Mehrjährige Beurteilung, angemessene Bedingungen und Rückforderungsregeln können ergänzen, beseitigen aber nicht jede Unsicherheit.'],'bonus-horizon'),
 q('b2','mock-b','a b c','All mandatory controls are in place. Under a complete annual agency-cost model, Plan X has monitoring cost 0.8, bonding cost 0.2, and residual loss 1.4. Plan Y has monitoring cost 1.1, bonding cost 0.3, and residual loss 0.7. The reduction in total agency costs from adopting Y rather than X is:',[
 ['0.3','X kostet 2,4, Y kostet 2,1; der Nettofortschritt beträgt 0,3.'],['0.7','Dies ist nur die Verminderung des Restverlusts und ignoriert höhere Kontroll- und Bindungskosten.'],['0.4','Dies ist der Zuwachs von Monitoring und Bonding, nicht die Gesamtkostenersparnis.']
 ],[F('\\Delta AC=(0{,}8+0{,}2+1{,}4)-(1{,}1+0{,}3+0{,}7)=0{,}3','Die beiden Pläne werden auf derselben Periodenbasis vollständig verglichen.',[['\\Delta AC','Verminderung der gesamten jährlichen Agency-Kosten in den gegebenen Einheiten.']]),'Eine wirksame zusätzliche Kontrolle kann den verbleibenden Verlust verringern und trotzdem nur einen Teil davon als Nettoersparnis liefern. Pflichtstandards sind im Fall ausdrücklich bereits erfüllt.'],'agency-costs')
];
