const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('org-'+id,'issuer-forms','corporate',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','A sole proprietor wants several outside investors to become ordinary equity owners of the same business. Which consideration is most appropriate?',[
 ['The ownership structure must change; a sole proprietorship has one owner.','Mehrere gewöhnliche Miteigentümer passen nicht mehr zur definierten Ein-Eigentümer-Struktur.'],['The owner can issue ordinary corporate shares without changing the business form.','Corporate Shares setzen eine passende Gesellschaftsstruktur voraus.'],['Every outside payment must be recorded as revenue.','Finanzierungszahlungen sind keine aus Kundenleistung verdienten Umsätze.']
 ],['Eine Partnerschaft oder geeignete Gesellschaft kann mehrere Eigentümer aufnehmen. Die konkrete Auswahl hängt zusätzlich von Haftung, Steuern, Leitungsrechten und Finanzierung ab.','Der Kapitalbedarf allein schreibt weder eine Börsennotierung noch eine bestimmte nationale Rechtsform zwingend vor.'],'forms'),
 q('02','practice','a','A general partner receives 40% of partnership profits. The partnership agreement does not change creditors’ legal rights. Which conclusion is most defensible?',[
 ['The profit share alone does not establish a 40% limit on the partner’s liability to creditors.','Interne Gewinnverteilung und externe Haftungsansprüche sind getrennte Regelungen.'],['The partner’s maximum liability must equal 40% of each debt.','Aus der Gewinnquote folgt keine solche automatische Haftungsobergrenze.'],['A partner with less than 50% of profits is automatically a limited partner.','Die Art der Partnerschaft und vertraglich-rechtliche Stellung hängen nicht allein von der Gewinnquote ab.']
 ],['Zunächst werden die konkrete Rechtsform und die Gläubigerrechte festgestellt. Erst anschließend lässt sich eine externe Haftung und gegebenenfalls ein interner Ausgleich bestimmen.','Eine wirtschaftliche Beteiligungsquote ist keine allgemeine Formel für persönliche Haftung.'],'forms'),
 q('03','practice','a','In the conventional limited partnership model described in the curriculum, which statement best distinguishes a general partner from a limited partner?',[
 ['The general partner manages the business and bears unlimited liability at its own legal-entity level.','Die Haftung trifft die Person oder Gesellschaft, die rechtlich General Partner ist.'],['Every limited partner automatically bears unlimited liability merely by receiving profits.','Gewinnbeteiligung allein hebt den vorgesehenen Haftungsschutz nicht auf.'],['Limited partnership and limited liability partnership are interchangeable legal terms.','Die ähnlich klingenden Formen können unterschiedliche Leitungs- und Haftungsstrukturen besitzen.']
 ],['Die Haftung eines Limited Partners hängt von den maßgeblichen Voraussetzungen ab. Der General Partner kann auch eine eigenständige Gesellschaft sein.','Ist diese selbst haftungsbeschränkt, folgt aus ihrer Partnerhaftung noch keine unbegrenzte persönliche Haftung sämtlicher hinter ihr stehender Anteilseigner.'],'liability'),
 q('04','practice','a','An analyst compares partnerships incorporated or organized in different jurisdictions. The most appropriate assumption about separate legal personality is that it:',[
 ['must be checked under the relevant jurisdiction and form.','Partnerschaften werden rechtlich nicht in jedem Land identisch behandelt.'],['is absent for every partnership worldwide.','Eine solche weltweite Gleichsetzung ist unzutreffend.'],['necessarily follows from whether profits are taxed at the owner level.','Steuerliche Zurechnung und rechtliche Eigenständigkeit sind verschiedene Ebenen.']
 ],['Der Analyst identifiziert zuerst die konkrete Einheit, die anwendbare Rechtsordnung und die Vertragsstruktur. Englische Oberbegriffe helfen beim Vergleich, ersetzen diesen Schritt aber nicht.','Auch „limited“ allein beantwortet weder Steuerklassifikation noch sämtliche Haftungsfragen.'],'forms'),
 q('05','practice','a b','A corporation has realizable assets of 65 and debt of 100. A fully paid shareholder has given an enforceable personal guarantee capped at 20 and has sufficient personal assets. There are no other claims, costs, or grounds for personal liability. The maximum additional personal payment under the guarantee is:',[
 ['20','Die Deckungslücke beträgt 35; die gesonderte Garantie begrenzt den zusätzlichen Rückgriff auf 20.'],['0','Beschränkte Aktionärshaftung beseitigt nicht die ausdrücklich übernommene Garantie.'],['35','Dies ignoriert die Garantieobergrenze von 20.']
 ],[F('P=\\min(100-65,20)=20','Ungedeckte Schuld und Garantieobergrenze werden gemeinsam berücksichtigt.',[['P','Zusätzliche Zahlung des Garanten in der angegebenen Geldeinheit.']]),'Danach verbleiben im vereinfachten Fall 15 ungedeckte Schulden. Ein Verlust der bereits investierten Beteiligung ist von dieser zusätzlichen persönlichen Zahlung zu unterscheiden.'],'liability'),
 q('06','practice','a','A US limited liability company has multiple members. For federal income tax analysis, the analyst should most appropriately:',[
 ['check the default classification and any valid tax election instead of inferring the result solely from limited liability.','LLC ist eine rechtliche Struktur, deren Bundessteuerklassifikation gesondert bestimmt wird.'],['assume all LLCs are taxed identically to listed corporations.','Mitgliederzahl und steuerliche Wahlen können die Klassifikation verändern.'],['assume a private company can never pay tax at the company level.','Privates Eigentum ist kein allgemeiner Ausschluss eigener Unternehmensbesteuerung.']
 ],['Die IRS-Regeln unterscheiden die rechtliche LLC von ihrer steuerlichen Einordnung. Die Frage verlangt diesen Analyseschritt, keine Berechnung eines konkreten Steuersatzes.','Ebenso kann eine britische Private Limited Company eine eigene Pflicht zur Corporation Tax haben; der Begriff „private“ schafft keine weltweite steuerliche Transparenz.'],'taxation'),
 q('07','practice','a b','A corporation earns 1,000 before tax, pays company tax at 20%, and distributes the entire remaining amount. The owner then pays 30% tax on the distribution. There are no credits or other taxes. The combined effective tax rate on the original profit is:',[
 ['44%','Unternehmenssteuer 200 plus Eigentümersteuer 240 ergeben 440 auf den Ausgangsgewinn.'],['50%','Dies addiert Sätze, die auf unterschiedliche Bemessungsgrundlagen angewendet werden.'],['24%','Dies ist nur die zweite Steuer relativ zum ursprünglichen Gewinn.']
 ],[F('\\tau_{eff}=1-(1-0{,}20)(1-0{,}30)=44\\%','Nach der ersten Steuer verbleiben 800, nach der zweiten 560.',[['\\tau_{eff}','Gesamte Steuerbelastung relativ zum ursprünglichen Gewinn.']]),'Die Rechnung setzt vollständige Ausschüttung und fehlende Anrechnung voraus. Sie ist keine Aussage über einen tatsächlich geltenden nationalen Gesamtsatz.'],'taxation'),
 q('08','practice','a','A partnership is expressly treated as tax-transparent in this scenario. Profit is 160; one partner is allocated 25% and pays personal tax at 20% on that allocation. The partnership distributes no cash. The partner’s tax attributable to the allocated profit is:',[
 ['8','Zugerechneter Gewinn 40 wird mit 20 % besteuert.'],['0','Keine Auszahlung bedeutet unter der ausdrücklich vorgegebenen Zurechnung keine Steuerfreiheit.'],['32','Dies besteuert den gesamten Partnerschaftsgewinn beim einzelnen Partner.']
 ],[F('Tax_P=160\\cdot0{,}25\\cdot0{,}20=8','Steuer folgt im gegebenen Modell der Gewinnzurechnung, nicht erst einer Auszahlung.',[['Tax_P','Persönliche Steuer des betrachteten Partners.']]),'Ohne Steuerausschüttung muss der Partner die acht Geldeinheiten aus anderer Liquidität finanzieren.'],'retention'),
 q('09','practice','b','An investor purchases 10% of a corporation’s ordinary shares from another shareholder. The corporation owns a factory. Which statement is most accurate?',[
 ['The investor owns shares in the corporation; the corporation remains the owner of the factory.','Der Aktienkauf überträgt den Beteiligungsanspruch, nicht unmittelbar einen getrennten Bruchteil jedes Betriebsvermögenswerts.'],['The investor directly acquires legal title to 10% of every machine.','Dies verwechselt Eigentum an Anteilen mit dem Vermögen der eigenständigen Gesellschaft.'],['The purchase automatically cancels 10% of the corporation’s debt.','Ein gewöhnlicher Aktionärswechsel lässt bestehende Gesellschaftsverpflichtungen unberührt.']
 ],['Der Kaufpreis fließt hier an den bisherigen Aktionär. Die Gesellschaftsidentität und die Zuordnung ihres Betriebsvermögens bleiben im normalen Aktienverkauf unverändert.','Besondere vertragliche Folgen eines Kontrollwechsels sind eine zusätzliche Frage und werden nicht aus jedem Aktienverkauf automatisch abgeleitet.'],'identity-control'),
 q('10','practice','b','A founder dies after transferring ownership of a business into a corporation with continued existence independent of individual shareholders. Which consequence is most consistent with this feature?',[
 ['The corporation can continue while ownership of the founder’s shares is resolved.','Fortbestand der Gesellschaft ist von der Identität eines einzelnen Aktionärs getrennt.'],['Every operating contract must automatically terminate solely because the founder died.','Die eigenständige Gesellschaft bleibt grundsätzlich dieselbe Vertragspartei.'],['The corporation can never be dissolved or become insolvent.','Fortbestand über Eigentümerwechsel hinaus ist keine Garantie unbegrenzter Existenz.']
 ],['Das Merkmal erleichtert langfristige Verträge und übertragbares Eigentum. Nachfolgefragen können die Kontrolle verändern, ohne das Unternehmen automatisch zu beenden.','Insolvenz, Auflösung oder besondere Vertragsregeln bleiben gesonderte mögliche Ereignisse.'],'identity-control'),
 q('11','practice','b','Separating ownership from professional management most directly creates which combination?',[
 ['Access to managerial specialization together with a need to control agency conflicts.','Professionelle Arbeitsteilung ist nützlich, aber Eigentümer müssen delegierte Entscheidungen überwachen.'],['Automatic elimination of conflicts because managers do not own all shares.','Fehlende vollständige Eigentümerstellung kann Interessengegensätze gerade ermöglichen.'],['A requirement that every shareholder approve every routine operating decision.','Die Delegation soll operative Entscheidungen gerade auf befugte Leitungspersonen übertragen.']
 ],['Viele passive Eigentümer können Kapital bereitstellen, während eine spezialisierte Leitung das Geschäft organisiert. Die Informationsasymmetrie schafft gleichzeitig Raum für Entscheidungen zugunsten der Leitung.','Kontrolle durch Board, Berichte und passende Anreize verbindet Finanzierung mit Verantwortlichkeit.'],'identity-control'),
 q('12','practice','b c','A founder owns all 150,000 Class A shares with ten votes per share. Other investors hold 850,000 Class B shares with one vote per share. All shares have equal economic rights. The founder’s voting share is closest to:',[
 ['63.83%','1,5 Mio. Gründerstimmen stehen insgesamt 2,35 Mio. Stimmen gegenüber.'],['15.00%','Dies ist der wirtschaftliche Anteil bei gleichen Rechten je Aktie, nicht das Stimmengewicht.'],['85.00%','Dies ist der Anteil der B-Aktien an der gesamten Aktienzahl.']
 ],[F('w_V=\\frac{150000\\cdot10}{150000\\cdot10+850000}\\approx63{,}83\\%','Jede Klasse wird mit ihren Stimmen pro Aktie gewichtet.',[['w_V','Stimmrechtsanteil der Gründerperson.']]),'Die Mehrheit betrifft unter den gegebenen Regeln einfache Stimmenentscheidungen. Abweichende Sondermehrheiten oder Vetorechte müssten zusätzlich geprüft werden.'],'voting'),
 q('13','practice','b c','A company has 900,000 identical shares worth a total of €9 million before financing. A founder holds 600,000 shares. New investors contribute €3 million at €10 per new share. There are no fees, special rights, or other value changes. The founder’s post-financing ownership and theoretical stake value are:',[
 ['50% and €6 million.','300.000 neue Aktien erhöhen den Nenner auf 1,2 Mio.; der faire Anteilspreis bleibt im isolierten Fall 10 €.'],['66.67% and €6 million.','Der Wert bleibt zwar gleich, aber die Beteiligungsquote muss den größeren Nenner berücksichtigen.'],['50% and €4.5 million.','Dieser Wert wendet die neue Quote auf den alten Gesamtwert an und ignoriert den neuen Cashzufluss.']
 ],[F('N_1=900000+\\frac{3000000}{10}=1200000,\\quad w_F=\\frac{600000}{1200000}=50\\%','Neue Aktien und neues Gesellschaftsvermögen steigen hier zum gleichen fairen Preis.',[['N_1','Aktienzahl nach der Finanzierung.'],['w_F','Neue Beteiligungsquote der Gründerperson.']]),'Der gesamte Eigenkapitalwert ist nun 12 Mio. €. Die Hälfte davon sind 6 Mio. €, gleich dem Wert der ursprünglichen 600.000 Aktien.'],'primary-secondary'),
 q('14','practice','b c','An existing shareholder sells 100,000 already outstanding shares to another investor for €12 each. The company issues no shares and incurs no costs. The company’s direct cash inflow from this transaction is:',[
 ['€0','Der Käufer bezahlt den verkaufenden Anteilseigner.'],['€1.2 million','Dies ist der Erlös des Verkäufers, nicht der Gesellschaft.'],['€12 million','Zusätzlich zum falschen Empfänger wird die Stückzahl um den Faktor zehn überhöht.']
 ],['Ein normaler Sekundärmarktverkauf verändert den Eigentümer der vorhandenen Aktien. Die ausstehende Aktienzahl und der Gesellschaftscash ändern sich dadurch nicht.','Liquider Sekundärhandel kann spätere Finanzierung erleichtern; dieser indirekte Vorteil ist von einem direkten neuen Emissionserlös zu trennen.'],'primary-secondary'),
 q('15','practice','a b','The general partner of a limited partnership is itself a separate limited-liability corporation. The corporation’s shareholders have fully paid their shares and have no guarantees or other personal obligations. Which inference is most appropriate?',[
 ['The general partner corporation’s liability does not automatically create unlimited personal liability for its shareholders.','Die Haftungskette muss über die einzelnen Rechtsträger verfolgt werden.'],['Every shareholder of the general partner must personally cover all partnership debts.','Dies überspringt die ausdrücklich gegebene eigenständige Haftungsbegrenzung der Partnergesellschaft.'],['The limited partnership has no general partner because the partner is not a natural person.','Eine Gesellschaft kann nach dem beschriebenen Strukturmodell selbst General Partner sein.']
 ],['Unbeschränkte Partnerhaftung betrifft zunächst die Gesellschaft, die den General-Partner-Status besitzt. Ihre eigenen Aktionäre sind davon zu unterscheiden.','Wirtschaftlich bleibt Risiko im Vermögen dieser Partnergesellschaft. Die mehrstufige Struktur lässt es nicht verschwinden.'],'liability'),
 q('16','practice','b','Which feature most directly helps a corporation attract capital from many investors who do not want to manage daily operations?',[
 ['Transferable ownership interests and delegation of management within an appropriate legal structure.','Investoren können Kapital geben und später Eigentum übertragen, ohne selbst jeden Betriebsvorgang auszuführen.'],['A guarantee that all new securities can always be sold at any desired price.','Die Rechtsform garantiert weder Nachfrage noch einen bestimmten Finanzierungspreis.'],['Elimination of disclosure, monitoring, and organizational costs.','Diese Kosten können bei breiter externer Finanzierung gerade bedeutsam sein.']
 ],['Beschränkte Haftung und eigenständige Fortführung können die Beteiligung weiterer Anleger zusätzlich erleichtern. Die konkrete Ausgabe und Übertragung unterliegt dennoch Regeln und Verträgen.','Leichterer Zugang bedeutet eine Möglichkeit, keine Zusage erfolgreicher Finanzierung.'],'identity-control'),
 q('17','practice','c','A company’s shares trade on an exchange, but a founding family owns 70% and the state owns none. Every share has one vote and ordinary control decisions require a simple majority, with no special rights. The company is best described as:',[
 ['publicly traded and family-controlled under the stated ownership facts.','Börsenhandel und konzentriertes privates Kontrolleigentum können gleichzeitig vorliegen.'],['state-owned because public trading means public-sector ownership.','„Publicly traded“ bezieht sich auf den Handel, nicht auf staatliches Eigentum.'],['privately held in the sense of having no publicly traded shares.','Dies widerspricht dem ausdrücklich genannten Börsenhandel.']
 ],['Die Kategorien beantworten verschiedene Fragen. Der Börsenstatus beschreibt Handel und zugehörige Anforderungen; die Familie beschreibt, wer die Beteiligungen hält.','Die genaue Kontrollwirkung setzt zusätzlich passende Stimmrechte voraus; die Eigentümerkonzentration allein beschreibt zunächst die Kapitalverteilung.'],'public-private'),
 q('18','practice','c','A private equity investor receives detailed monthly management accounts under a contractual information right. The company’s shares are not exchange-traded. Which conclusion is most justified?',[
 ['Limited public disclosure does not mean every private investor has limited access to information.','Vertragliche Informationsrechte können einzelnen Kapitalgebern umfangreiche Daten geben.'],['Private companies can never provide information beyond public annual accounts.','Die Aufgabe beschreibt gerade zusätzliche interne Informationen für einen berechtigten Investor.'],['Monthly reporting makes the shares exchange-listed automatically.','Informationszugang und Handelszulassung sind unterschiedliche Sachverhalte.']
 ],['Öffentlich verfügbare Daten und individuell vereinbarte Information werden getrennt beurteilt. Weitere Fragen betreffen Verlässlichkeit, Durchsetzbarkeit und rechtmäßige Verwendung der Informationen.','Ohne laufenden Börsenpreis bleibt außerdem eine eigenständige Bewertung nötig.'],'public-private'),
 q('19','practice','c','An exchange-listed company has a very small freely traded share supply, infrequent trades, and wide bid–ask spreads. Compared with the statement “listed shares are always liquid,” the evidence suggests that:',[
 ['listing creates a trading venue but does not guarantee low-cost immediate liquidity.','Tatsächliche Handelbarkeit hängt auch von Volumen, Streubesitz und Nachfrage ab.'],['every listed shareholder can sell any quantity immediately at the last quoted price.','Der letzte Kurs garantiert weder ausreichende Gegenaufträge noch geringe Preiswirkung.'],['the shares must therefore be legally identical to an unlisted partnership interest.','Ähnliche Liquiditätsprobleme heben Unterschiede der Rechts- und Handelsstruktur nicht auf.']
 ],['Ein Anleger prüft, welcher Betrag unter welchen Kosten und mit welcher Preiswirkung verkauft werden kann. Das ist konkreter als das bloße Merkmal „börsennotiert“.','Seltene Transaktionen können zugleich die Aussagekraft eines einzelnen beobachteten Kurses begrenzen.'],'public-private'),
 q('20','practice','c','A proposed transaction is explicitly permitted as a primary direct listing and includes newly issued shares sold by the company. Which claim is most accurate?',[
 ['The company can raise new capital through the primary share issuance.','Die ausdrücklich genannte Primärkomponente führt zu Emissionserlös der Gesellschaft.'],['A direct listing can never involve new capital under any exchange rules.','Dies verwechselt eine typische reine Altaktiennotierung mit sämtlichen zulässigen Varianten.'],['The transaction necessarily eliminates all dilution and transaction expenses.','Die Ausgabe kann den Beteiligungsnenner verändern; Kostenfreiheit ist nicht gegeben.']
 ],['Zuerst wird geprüft, ob bestehende Aktien verkauft oder neue Aktien ausgegeben werden. Der Name des Börsenzugangs ersetzt diese Zahlungs- und Eigentümeranalyse nicht.','Die Frage setzt die Zulässigkeit dieser konkreten Struktur ausdrücklich voraus.'],'listing-paths'),
 q('21','practice','c','An IPO includes 800,000 new shares and 200,000 existing shares sold by current owners, all at €15. The company pays €600,000 of issue costs. There are no other company cash flows. Net proceeds to the company are:',[
 ['€11.4 million','12 Mio. Bruttoerlös aus neuen Aktien abzüglich 0,6 Mio. Firmenkosten.'],['€14.4 million','Dies zählt auch den Kaufpreis der Altaktien als Gesellschaftszufluss.'],['€12.0 million','Dies berücksichtigt die ausdrücklich genannten Emissionskosten noch nicht.']
 ],[F('C_{issuer}=800000\\cdot15-600000=11400000','Der Verkauf bestehender Aktien finanziert den Verkäufer; nur die neue Ausgabe finanziert hier die Gesellschaft.',[['C_{issuer}','Nettoemissionserlös der Gesellschaft in Euro.']]),'Die übrigen 3 Mio. Kaufpreis gehen vor eigenen Kosten und Steuern an die verkaufenden Altaktionäre.'],'ipo'),
 q('22','practice','c','A simplified SPAC transaction starts with 150 in its financing pool. Investor redemptions use 90, additional investors contribute 40, and transaction costs consume 10. With no other movements, cash remaining for the transaction is:',[
 ['90','150 − 90 + 40 − 10 ergibt 90.'],['100','Dies lässt die Transaktionskosten weg.'],['60','Dies betrachtet nur den ursprünglichen Topf nach Rückgaben und ignoriert zusätzliche Finanzierung sowie Kosten.']
 ],[F('C_{net}=150-90+40-10=90','Angekündigtes Anfangskapital und endgültig verfügbarer Betrag sind verschieden.',[['C_{net}','Nach den genannten Bewegungen verbleibender Cashbetrag.']]),'Zur Eigentümerquote fehlen weiterhin Aktienzahlen, Sponsoransprüche und mögliche weitere Rechte. Cash allein bestimmt keine vollständige Cap Table.'],'listing-paths'),
 q('23','practice','c','A buyer acquires all publicly held ordinary shares and the company subsequently delists those shares. The operating company and its outstanding debt contracts continue. Which statement is most accurate?',[
 ['Going private changes the equity ownership and trading situation without automatically cancelling company obligations.','Aktiennotierung, Unternehmensfortbestand und Gläubigeransprüche sind getrennte Ebenen.'],['Delisting automatically repays all lenders in full.','Ein Ende des Aktienhandels erzeugt keinen automatischen Schuldendienst.'],['The company must cease all operations immediately.','Der Sachverhalt nennt gerade einen fortbestehenden operativen Betrieb.']
 ],['Die Finanzierungsstruktur des Erwerbs und die Bedingungen bestehender Schulden müssen zusätzlich geprüft werden. Die Eigentumsänderung allein beantwortet nicht, wie Gläubiger bedient werden.','Auch Berichtsanforderungen können aus anderen Tatbeständen fortbestehen; fehlender Aktienhandel ist keine pauschale Befreiung.'],'going-private'),
 q('24','practice','c','An acquisition costs 120 and is funded with 40 of equity and 80 of debt. One year later the company is sold for 130 and the debt is repaid at 80. Ignore interest, taxes, fees, and all other cash flows. The buyer’s equity return is:',[
 ['25.0%','Für das Eigenkapital verbleiben 50 nach Rückzahlung der Schuld; der Einsatz war 40.'],['8.33%','Dies ist der Anstieg des gesamten Unternehmenswerts relativ zum gesamten Kaufpreis.'],['50.0%','50 ist der Endwert des Eigenkapitals in Geldeinheiten, nicht seine prozentuale Rendite.']
 ],[F('r_E=\\frac{130-80}{40}-1=25\\%','Der vorrangige Schuldanspruch wird vor der Eigentümerrendite bedient.',[['r_E','Rendite des eingesetzten Erwerbseigenkapitals.']]),'Der Hebel erhöht unter den günstigen Vorgaben die Rendite. Ein Wertverlust würde relativ zum kleineren Eigenkapitaleinsatz ebenfalls stärker wirken.'],'going-private'),
 q('25','practice','a c','An analyst knows only that a company is privately held. Which additional conclusion cannot safely be inferred from that description alone?',[
 ['Its profits are necessarily taxed only at the shareholder level.','Eigentums- und Handelssituation bestimmen keine weltweit einheitliche Steuerklassifikation.'],['Its shares are not publicly exchange-traded in the stated classification.','Dies entspricht hier gerade der verwendeten Bedeutung von privately held.'],['Its equity ownership can be concentrated among a small group of investors.','Eine solche Konzentration ist mit privatem Eigentum vereinbar; „can“ behauptet keine allgemeine Pflicht.']
 ],['Eine steuerliche Aussage benötigt die konkrete Gesellschaftsform, Rechtsordnung und gegebenenfalls wirksame Wahlen. Bei einer privaten Kapitalgesellschaft kann Unternehmenssteuer anfallen.','Der Unterschied zwischen einer notwendigen Folgerung und einer bloß möglichen Eigenschaft ist Bestandteil der Frage.'],'taxation'),
 q('26','practice','b','A fully paid shareholder has limited liability and has made no guarantee or other additional commitment. The corporation fails and its equity has no residual value. Which outcome is consistent with these facts?',[
 ['The shareholder can lose the entire investment without owing additional ordinary corporate debts personally.','Der investierte Betrag trägt das Eigenkapitalrisiko; zusätzliche persönliche Haftung ist im gegebenen Fall ausgeschlossen.'],['The corporation must reimburse the investment because liability is limited.','Haftungsbegrenzung ist keine Garantie gegen Kursverlust oder Insolvenzverlust.'],['Every corporate creditor must be made whole by the shareholder personally.','Dies widerspricht der ausdrücklich gegebenen Haftungsbeschränkung ohne Zusatzverpflichtung.']
 ],['Haftungsbegrenzung betrifft den zusätzlichen Zugriff des Gläubigers auf den Eigentümer. Sie verspricht keinen Mindestwert des gekauften Anteils.','Diese Unterscheidung ist auch für breit gestreute passive Aktienanlagen grundlegend.'],'liability'),
 q('a1','mock-a','b c','A corporation’s ordinary shares remain entirely held by its founders. The corporation makes a registered public bond offering that triggers ongoing public reporting obligations. Which statement is most accurate?',[
 ['Its equity can remain privately held even though its debt financing is public and reporting obligations apply.','Öffentliches Fremdkapitalangebot, privates Aktieneigentum und Berichtspflicht können nebeneinander bestehen.'],['The bond offering necessarily lists the founders’ ordinary shares on an exchange.','Eine Anleiheemission ist keine automatische Börsenzulassung der Stammaktien.'],['The founders’ private ownership necessarily exempts the corporation from the stated reporting obligations.','Die Aufgabe nennt eine eigene Grundlage der Berichtspflicht; privates Aktieneigentum hebt sie nicht auf.']
 ],['Die drei Eigenschaften sind separat zu klassifizieren: Wer besitzt das Eigenkapital, welches Wertpapier wird öffentlich angeboten, und welche Pflichten entstehen aus diesem Angebot?','Eine Umbenennung aller Aktien in „öffentlich gehandelt“ oder eine pauschale Berichtsfreistellung würde diese getrennten Ebenen vermischen.'],'dimensions'),
 q('b1','mock-b','b c','A founder owns 200,000 Class A shares with ten votes each. Other investors own 800,000 Class B shares with one vote each. The company issues 400,000 new Class B shares. At the same time the founder sells 50,000 Class A shares, which automatically convert one-for-one into Class B when sold. No other shares or voting rights exist. The founder’s voting share afterward is closest to:',[
 ['54.55%','Es verbleiben 1,5 Mio. Gründerstimmen und 1,25 Mio. B-Stimmen.'],['62.50%','Dies teilt die ursprünglichen 2 Mio. Gründerstimmen durch 3,2 Mio. und ignoriert den Verkauf samt Umwandlung.'],['10.71%','Dies ist die wirtschaftliche Aktienquote bei gleichen wirtschaftlichen Rechten, nicht die gewichtete Stimmenquote.']
 ],[F('V_F=(200000-50000)10=1500000,\\quad V_B=800000+400000+50000=1250000','Die verkauften A-Aktien erhalten beim Käufer nur noch je eine Stimme. Die neue Ausgabe vergrößert zusätzlich die B-Klasse.',[['V_F','Verbleibende Stimmen der Gründerperson.'],['V_B','Stimmen sämtlicher B-Aktien nach beiden Vorgängen.']]),F('w_V=\\frac{1500000}{1500000+1250000}\\approx54{,}55\\%','Ausgabe, Verkauf und Umwandlung werden getrennt verarbeitet, bevor die Quote berechnet wird.',[['w_V','Stimmrechtsanteil der Gründerperson nach der Transaktion.']]),'Die gesamte Aktienzahl ist 1,4 Mio.; die Umwandlung verändert Stimmen, aber schafft keine zusätzliche Aktie. Die Gründerperson besitzt noch 150.000 Aktien.'],'voting')
];
