const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,correct,solution,section)=>Q('mon-'+id,'monetary','economics',pool,los,stem,options,correct,solution,{section});
const eq=(tex,reading,symbol,meaning)=>F(tex,reading,[[symbol,meaning]]);
module.exports=[
 q('01','practice','a','A bank owns assets expected to cover its liabilities but cannot meet an immediate settlement outflow. The central bank function most directly relevant is:',[
 ['providing conditional lender-of-last-resort liquidity.','Die Situation beschreibt zunächst einen Liquiditätsengpass.'],['guaranteeing that every bank shareholder avoids losses.','Liquiditätsunterstützung ist keine allgemeine Eigenkapitalgarantie.'],['setting the government corporate tax rate.','Das ist eine fiskalische Zuständigkeit.']
 ],0,['Liquiditätszugang kann an Sicherheiten und weitere Bedingungen gebunden sein. Die Solvenzbeurteilung bleibt eigenständig und kann unsicher sein.'],'roles'),
 q('02','practice','a c','A price index starts at 90, rises 4% in one year and 2% in the next. Its final value is closest to:',[
 ['91.80.','Das lässt das erste Jahr weg.'],['95.47.','90 × 1,04 × 1,02.'],['88.20.','Sinkende Inflation ist hier kein fallendes Preisniveau.']
 ],1,[eq('P_2=90\\cdot1{,}04\\cdot1{,}02=95{,}472','Inflation verlangsamt sich, aber das Preisniveau steigt in beiden Jahren.','P_2','Preisindex am Ende des zweiten Jahres.')],'objectives'),
 q('03','practice','b','A commercial bank grants a loan and credits the borrower deposit account. At origination, its balance sheet most directly records:',[
 ['a decrease in both loans and deposits.','Ein neuer Kredit ist keine Rückzahlung.'],['a loan asset increase with no liability change in every case.','Die Gutschrift erzeugt im beschriebenen Fall eine Einlagenverbindlichkeit.'],['a loan asset and a deposit liability increase.','Kreditforderung und Kundenguthaben steigen gleichzeitig.']
 ],2,['Die Buchung hebt spätere Kapital-, Liquiditäts-, Finanzierungs- und Risikobeschränkungen nicht auf.'],'reserves'),
 q('04','practice','b','In a simplified money-base identity, currency/deposits = 0.20, required reserves/deposits = 0.10, and excess reserves/deposits = 0.10. Broad money divided by the monetary base equals:',[
 ['3.00.','(1 + 0,2)/(0,2 + 0,1 + 0,1).'],['5.00.','Das ignoriert den Bargeldanteil in Zähler und Nenner.'],['10.00.','Das ist der unzulässige alleinige Kehrwert der Mindestreservequote.']
 ],0,[eq('M/H=(1+0{,}2)/(0{,}2+0{,}1+0{,}1)=3','Die Bilanzrelation ist keine automatische kausale Kreditwachstumsregel.','M/H','Vereinfachte breite Geldmenge geteilt durch Geldbasis.')],'reserves'),
 q('05','practice','b','A central bank buys a bond for 25 directly from a commercial bank and pays with reserves. Ignoring gains and fees, the commercial bank initially:',[
 ['must create a new household loan of 25.','Ein Wertpapierverkauf verpflichtet nicht zu einem neuen Haushaltskredit.'],['exchanges a bond asset for a reserve asset.','Die Zusammensetzung ihrer Aktiva verändert sich.'],['reduces its equity by 25.','Bei Verkauf zum Buchwert entsteht hier kein Eigenkapitalverlust.']
 ],1,['Ein Kauf von einer Nichtbank über die Bank hätte zusätzlich eine andere Einlagenwirkung. Die Gegenpartei gehört zur Bilanzanalyse.'],'reserves'),
 q('06','practice','b c','A reserve requirement is reduced. Banks face weak loan demand and binding capital constraints. Which conclusion is most appropriate?',[
 ['Loan growth must equal the reciprocal change in the reserve ratio.','Das unterstellt einen mechanischen Geldschöpfungsmultiplikator trotz weiterer Bindungen.'],['All existing customer deposits are immediately cancelled.','Eine Reservevorschrift löscht keine Kundeneinlagen.'],['The change alone does not establish how much lending will increase.','Kreditnachfrage und Kapital können weiterhin begrenzen.']
 ],2,['Eine erleichterte Reservehaltung ist nur ein Teil der Finanzierungs- und Risikobedingungen.'],'tools'),
 q('07','practice','b','For a fixed inflation assumption of 4% and a nominal one-year rate of 6%, the exact implied real rate is closest to:',[
 ['1.92%.','1,06/1,04 − 1.'],['2.00%.','Das ist die Differenznäherung, nicht die verlangte exakte Bruttozinsrechnung.'],['10.24%.','Das multipliziert die Faktoren, statt Kaufkraft herauszurechnen.']
 ],0,[eq('r^e=1{,}06/1{,}04-1\\approx1{,}9231\\%','Laufzeit und Inflationsperiode stimmen überein; Inflation ist in der Aufgabenannahme fest.','r^e','Implizierter Realzins unter der festen Inflationsannahme.')],'real-rate'),
 q('08','practice','b c','A nominal rate falls from 4% to 3%, while expected inflation falls from 3% to 1%. The estimated neutral real rate is unchanged. Using the difference approximation, monetary conditions become:',[
 ['looser because the nominal rate alone is lower.','Die Inflationserwartung fällt stärker als der Nominalzins.'],['tighter because the real rate rises from 1% to 2%.','Bei unverändertem neutralem Vergleichszins steigt der reale Abstand.'],['unchanged because both nominal rates and inflation fall.','Die Größen fallen nicht um denselben Betrag.']
 ],1,['Die Richtung hängt nicht allein vom Vorzeichen der nominalen Änderung ab. Die Aufgabe hält den neutralen Realzins ausdrücklich konstant.'],'real-rate'),
 q('09','practice','b','Expected short rates for three successive years are 3%, 4%, and 5%. Using an arithmetic expectation average and a term premium of 0.6 percentage points, the approximate three-year yield is:',[
 ['4.00%.','Das lässt die Laufzeitprämie weg.'],['5.60%.','Das verwendet nur den letzten erwarteten kurzen Zins.'],['4.60%.','(3 + 4 + 5)/3 + 0,6.']
 ],2,[eq('y_3=(3+4+5)/3+0{,}6=4{,}6\\%','Die Rechnung ist ausdrücklich eine Näherungszerlegung und keine exakte Diskontfaktorkurve.','y_3','Angenäherte Dreijahresrendite, Zahlen in Prozent.')],'yield-curve'),
 q('10','practice','b','A policy-rate reduction was fully anticipated and adds no new information about future rates or premia. Long-term bond yields:',[
 ['need not fall again solely because the anticipated decision is announced.','Die erwartete Senkung kann bereits eingepreist sein.'],['must fall by exactly the policy-rate reduction.','Längere Renditen hängen vom gesamten Erwartungspfad und Prämien ab.'],['must rise by the same amount.','Auch ein gleich großer Anstieg folgt nicht aus diesen Angaben.']
 ],0,['Marktreaktionen werden gegenüber vorherigen Erwartungen beurteilt, nicht nur gegenüber dem alten beobachteten Leitzins.'],'yield-curve'),
 q('11','practice','b','A floating-rate loan of 150,000 has annual principal repayment of 3,000. Assume interest is calculated on the stated balance for the year. If its rate rises from 2% to 4%, annual debt service increases by:',[
 ['6,000.','Das sind die neuen Zinsen, nicht die Änderung des gesamten Schuldendienstes.'],['3,000.','150.000 × (0,04 − 0,02), bei unveränderter Tilgung.'],['9,000.','Das ist der neue gesamte Schuldendienst.']
 ],1,[eq('\\Delta DS=150000(0{,}04-0{,}02)=3000','Vorher beträgt der Schuldendienst 6.000, danach 9.000. Die Tilgung bleibt unverändert.','\\Delta DS','Änderung von jährlichen Zinsen plus Tilgung.')],'transmission'),
 q('12','practice','b','A domestic monetary tightening raises interest rates relative to foreign rates. Holding expectations and risk premia otherwise constant, one possible exchange-rate transmission channel is:',[
 ['a guaranteed depreciation in every market regime.','Zinsänderung allein garantiert dieses Vorzeichen nicht.'],['no possible change in import prices because exchange rates cannot affect them.','Wechselkurse können in heimischer Währung gemessene Importpreise verändern.'],['currency appreciation that may reduce domestic-currency import costs.','Attraktivere inländische Verzinsung kann die Währung stützen; Weitergabe bleibt bedingt.']
 ],2,['Die Aussage ist ein bedingter Kanal. Gegenläufige ausländische Politik, Risikoprämien oder neue Erwartungen können ihn überlagern.'],'transmission'),
 q('13','practice','b c','Broad money grows 10%, income velocity falls 4%, and real output grows 2%. The exact inflation rate consistent with the quantity identity is closest to:',[
 ['3.53%.','1,10 × 0,96 / 1,02 − 1.'],['4.00%.','Das ist die additive Näherung.'],['10.00%.','Das ignoriert Umlaufgeschwindigkeit und reale Produktion.']
 ],0,[eq('\\pi=1{,}10\\cdot0{,}96/1{,}02-1\\approx3{,}5294\\%','Die drei Wachstumsfaktoren müssen multiplikativ verbunden werden.','\\pi','Mit den vorgegebenen Größen konsistente Inflation.')],'quantity'),
 q('14','practice','c','Which statement best distinguishes an inflation target from an operating interest-rate target?',[
 ['They are always the same numerical target.','Die Einheiten mögen Prozent sein, aber Zielgrößen und Horizonte unterscheiden sich.'],['An inflation-targeting central bank may use a short-term interest rate as its operating instrument.','Endziel und operatives Instrument können gleichzeitig Teil derselben Strategie sein.'],['Using an interest-rate instrument necessarily means the central bank has no inflation objective.','Das ist eine falsche Ausschließlichkeit.']
 ],1,['Man muss Zielgröße, Reaktionsstrategie und Umsetzung unterscheiden.'],'targets'),
 q('15','practice','c','With highly mobile capital and a credible fixed exchange rate, a central bank generally faces:',[
 ['unlimited independent control over domestic rates regardless of foreign conditions.','Die Bindung und Kapitalbewegungen schränken diese Kombination ein.'],['no need to consider reserve adequacy or expectations.','Die Verteidigung einer Bindung kann von beiden abhängen.'],['a constraint on independent monetary policy.','Die drei Ziele Wechselkursbindung, freie Kapitalmobilität und volle Autonomie sind nicht beliebig vereinbar.']
 ],2,['Abweichungen durch Kapitalbeschränkungen, Risiko oder unvollständige Glaubwürdigkeit ändern die Voraussetzungen des Arguments.'],'targets'),
 q('16','practice','a c','Instrument independence most directly allows a central bank to:',[
 ['choose how to deploy instruments within its mandated objectives.','Instrumentenwahl ist von Zielsetzung zu unterscheiden.'],['change its statutory objective without legal authority.','Das folgt aus Instrumentenunabhängigkeit nicht.'],['avoid explaining policy decisions under any accountability framework.','Unabhängigkeit ist nicht gleich fehlende Rechenschaft.']
 ],0,['Eine effektive institutionelle Gestaltung verbindet Entscheidungsfähigkeit mit klaren Zielen, Glaubwürdigkeit und Transparenz.'],'credibility'),
 q('17','practice','b c','In a static AD-AS model, a negative supply shock raises the price level while lowering output. A demand expansion that restores the old output, holding the new supply curve fixed, most likely:',[
 ['also restores the old lower price level automatically.','Auf der geschockten Angebotskurve benötigt der alte Output hier ein höheres Preisniveau.'],['raises the price level further.','Die Nachfragebewegung geht entlang der neuen aufwärts geneigten Angebotskurve.'],['eliminates the original supply constraint without changing demand.','Das wäre eine Angebotsverbesserung, die gerade nicht unterstellt wird.']
 ],1,['Die Grafik ist ein statischer Niveauvergleich. Eine dauerhafte Inflationsrate erfordert zusätzliche zeitliche Annahmen.'],'supply-shock'),
 q('18','practice','b c','Large-scale asset purchases by a central bank may affect financing conditions through:',[
 ['a guaranteed proportional increase in every bank loan category.','Reserve- und Kreditveränderungen sind nicht mechanisch identisch.'],['the automatic removal of all borrower credit risk.','Wertpapierkäufe beseitigen nicht jede Solvenzgefahr.'],['portfolio rebalancing, market functioning, and signals about future policy.','Verschiedene Kanäle können Prämien und Erwartungen verändern.']
 ],2,['Ihre Stärke hängt unter anderem von gekauften Papieren, Marktbedingungen und Glaubwürdigkeit ab.'],'unconventional'),
 q('19','practice','c','When policy rates are near an effective lower bound and private borrowers remain pessimistic, additional reserves:',[
 ['may have limited effects on new lending and spending.','Kreditnachfrage und erwartete Rentabilität können die Transmission begrenzen.'],['must create the maximum textbook deposit multiplier.','Das erfordert zusätzliche Verhaltensannahmen.'],['prove that fiscal policy is also always powerless.','Das folgt aus einer eingeschränkten monetären Transmission nicht.']
 ],0,['Die effektive Untergrenze ist nicht notwendigerweise genau null. Grenzen eines Instruments sind von völliger Wirkungslosigkeit aller Politik zu trennen.'],'limits'),
 q('20','practice','d','An expansionary fiscal change coincides with monetary tightening. Without information on the relative strength of the channels, the overall output effect is:',[
 ['necessarily zero.','Gegenläufige Vorzeichen bedeuten keine gleichen Beträge.'],['ambiguous, with possible changes in the composition of demand.','Staatskäufe und zinsabhängige private Nachfrage können sich unterschiedlich bewegen.'],['necessarily equal to the fiscal effect alone.','Das ignoriert die geldpolitische Gegenwirkung.']
 ],1,['Dosierung, Ausgangslage und Transmission sind nötig, um einen Gesamteffekt zu quantifizieren.'],'policy-mix'),
 q('a1','mock-a','b c','A nominal one-year rate is 5% and inflation over that year is assumed fixed at 2%. The exact implied real rate is closest to:',[
 ['3.00%.','Das ist die Differenznäherung.'],['7.10%.','Das multipliziert statt zu deflationieren.'],['2.94%.','1,05/1,02 − 1.']
 ],2,[eq('r^e=1{,}05/1{,}02-1\\approx2{,}9412\\%','Die Bruttozinsrelation liefert die Kaufkraftänderung unter der festen Inflationsannahme.','r^e','Implizierter Realzins.')],'real-rate'),
 q('a2','mock-a','a c','A central bank publishes the information that would trigger a change in its projected policy path. After that information changes, it adjusts the path and explains why. This behavior is most consistent with:',[
 ['transparent state-contingent communication.','Die ursprüngliche Aussage war ausdrücklich von den Umständen abhängig.'],['a necessarily broken unconditional promise.','Es lag gerade kein unbedingtes Versprechen vor.'],['automatic abandonment of price stability.','Eine Anpassung an neue Daten kann der Zielverfolgung dienen.']
 ],0,['Glaubwürdigkeit verlangt verständliche und konsistente Zielverfolgung, nicht eine unveränderte Reaktion auf beliebig neue Informationen.'],'credibility'),
 q('b1','mock-b','b','Expected short rates over four successive years are 2%, 3%, 4%, and 5%. With a term premium of 0.5 percentage points, the arithmetic-approximation four-year yield is:',[
 ['3.50%.','Das ignoriert die Laufzeitprämie.'],['4.00%.','Der Erwartungsdurchschnitt ist 3,5 %, dazu 0,5 Punkte.'],['5.50%.','Das verwendet nur den letzten kurzen Zins.']
 ],1,[eq('y_4=(2+3+4+5)/4+0{,}5=4\\%','Es handelt sich um die ausdrücklich gefragte Näherungszerlegung.','y_4','Angenäherte Vierjahresrendite, Eingaben in Prozent.')],'yield-curve'),
 q('b2','mock-b','d','Fiscal tightening and monetary easing occur together. Which conclusion is most appropriate without quantified response estimates?',[
 ['Aggregate output must rise because only monetary policy matters.','Fiskalische Nachfrageänderungen verschwinden dadurch nicht.'],['Aggregate output must fall because lower rates cannot affect private demand.','Günstigere Finanzierung kann sehr wohl private Nachfrage beeinflussen.'],['Private and public demand may shift in opposite directions, while the net output effect remains uncertain.','Die relative Größe und Geschwindigkeit der beiden Wirkungen fehlen.']
 ],2,['Ein sinnvoller Vergleich nennt die Zusammensetzung und Bedingungen statt aus zwei Politiketiketten einen sicheren Gesamteffekt abzuleiten.'],'policy-mix')
];
