const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('mult-'+id,'multiples','equity',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a b','A price multiple is most accurately described as:',[
 ['a market price or value standardized by a specified economic measure, with assumptions about comparability still required.','Standardisierung erleichtert Vergleiche, ersetzt aber keine Analyse von Werttreibern.'],
 ['a promised annual total return on the shares.','Ein Preisverhältnis ist weder vertragliche Zahlung noch garantierte Gesamtrendite.'],
 ['an intrinsic value independent of growth, risk and accounting.','Die wirtschaftlichen und bilanziellen Voraussetzungen bleiben in der Quote enthalten.']
 ],['Zuerst werden Wertanspruch und Bezugsgröße eindeutig festgelegt.','Erst wirtschaftliche Vergleichbarkeit erlaubt eine begründete Übertragung.'],'scope'),
 q('02','practice','b','A 2-for-1 split halves the share price and EPS, with no economic changes. The P/E ratio immediately following the split is:',[
 ['unchanged.','Zähler und Nenner halbieren sich gleichzeitig.'],['halved.','Dies berücksichtigt nur den Preis und lässt den veränderten Gewinn je Aktie aus.'],['doubled.','Dies berücksichtigt nur den EPS-Nenner.']
 ],[F('\\frac{P_0/2}{EPS/2}=\\frac{P_0}{EPS}','Die Stückelung kürzt sich aus dem Verhältnis heraus.',[['P_0,EPS','Preis und Gewinn je Aktie vor dem Split.']])],'scope'),
 q('03','practice','a c','Under the method of comparables, the selected multiple is primarily supported by:',[
 ['market prices of appropriately comparable firms, after checking economic and measurement differences.','Die Begründung beginnt mit Marktbeobachtungen und einem wirtschaftlichen Abgleich.'],['the subject company’s historical share price alone.','Ein einzelner früherer Kurs definiert keine passende Vergleichsgruppe.'],['a guarantee that all firms in the sector are fairly valued.','Gemeinsame Fehlbewertung ist gerade eine Grenze des relativen Verfahrens.']
 ],['Ein gemeinsamer Branchenname ist ein Ausgangspunkt, keine vollständige Begründung.','Wachstum, Risiko, Rentabilität, Kapitalbindung und Basis müssen passen.'],'workflow'),
 q('04','practice','a','A justified multiple derived under the method of forecasted fundamentals is:',[
 ['the consequence of the stated cash flow, growth, reinvestment and required return assumptions.','Das fundamentale Modell erzeugt die Wertrelation.'],['a second independent market observation confirming the same DCF estimate.','Division eines DCF-Werts schafft keine unabhängige neue Preisbeobachtung.'],['valid regardless of the accuracy of the forecasts.','Korrekte Algebra kann auf falschen Prognosen beruhen.']
 ],['Ein Wertmodell wird durch die ausdrücklich definierte Bezugsgröße geteilt.','Die Modellannahmen bleiben in der gerechtfertigten Quote enthalten.'],'workflow'),
 q('05','practice','b','Which pairing best preserves the claim and unit scope for an industrial firm?',[
 ['Enterprise value divided by consolidated EBITDA with corresponding capital claims included.','Umfassender operativer Wert und Ergebnis vor Finanzierungsverteilung passen zusammen.'],['Enterprise value divided by EPS attributable only to parent common shareholders.','Dies mischt Gesamtwert, Stückbetrag und einen engeren Eigentümeranspruch.'],['Price per common share divided by total consolidated EBITDA.','Stückpreis und gesamter operativer Gewinn haben verschiedene Einheiten und Ansprüche.']
 ],['Anspruch, Konsolidierung und Einheit werden gemeinsam geprüft.','Die passende EV-Brücke enthält auch Ansprüche auf vollständig erfasste Tochtergeschäfte.'],'definitions'),
 q('06','practice','b d','Current market capitalization divided by last year’s total common earnings differs from current price divided by reported EPS. A possible measurement explanation is:',[
 ['the current share count differs from the weighted average share count used for reported EPS.','Die Gleichheit der beiden Relationen verlangt dieselbe Aktienbasis.'],['P/E must always use total revenue in the denominator.','P/E verwendet Gewinn, kein Umsatzverhältnis.'],['a difference proves a valuation arbitrage regardless of share issuance.','Eine unterschiedliche Aktienbasis kann den Unterschied vollständig erklären.']
 ],['Heutige Marktkapitalisierung verwendet aktuellen Bestand.','Berichtetes EPS verwendet regelmäßig die für seine Periode gewichtete Aktienzahl.'],'definitions'),
 q('07','practice','b d','A share trades at 72. Comparable trailing EPS is 4 and forecast EPS for the next 12 months is 6. Forward P/E is:',[
 ['12.00','Der heutige Preis wird durch den nächsten Zwölfmonatsgewinn geteilt.'],['18.00','Dies ist Trailing P/E.'],['1.50','Dies ist die Relation der beiden EPS-Basen, kein Preis-Gewinn-Verhältnis.']
 ],[F('m_{PE,F}=72/6=12','Der Preisstichtag bleibt heute; der Gewinnnenner ist zukünftig.',[['m_{PE,F}','Forward P/E auf NTM-Basis.']])],'periods'),
 q('08','practice','b d','A firm has a constant comparable share count. Its last four quarterly EPS figures are 0.8, 1.0, 1.2 and 2.0. At a price of 75, trailing 12-month P/E is:',[
 ['15.00','Die vier vergleichbaren Quartale ergeben EPS fünf.'],['37.50','Dies verwendet nur das letzte Quartal, ohne die Jahresbasis.'],['9.38','Dies annualisiert das letzte Quartal und unterstellt dieselbe Quartalshöhe.']
 ],[F('EPS_{TTM}=0{,}8+1+1{,}2+2=5,\\quad m_{PE,TTM}=75/5=15','Der ganze vergangene Zwölfmonatszeitraum ist maßgeblich.',[['EPS_{TTM},m_{PE,TTM}','Gewinn der vier Quartale und zugehöriger Multiplikator.']])],'periods'),
 q('09','practice','b d','Six months remain in the current fiscal year. Forecast full-year EPS is 4 for that year and 6 for the following year. With constant shares and earnings uniform within each fiscal year, estimated next-12-month EPS is:',[
 ['5.00','Die nächsten zwölf Monate enthalten je sechs Monate der beiden Geschäftsjahre.'],['4.00','Dies verwendet ausschließlich FY1 statt des gesamten NTM-Horizonts.'],['6.00','Dies verwendet ausschließlich FY2.']
 ],[F('\\widehat{EPS}_{NTM}=0{,}5\\cdot4+0{,}5\\cdot6=5','Die zeitanteilige Näherung ist nur unter der ausdrücklich gegebenen Saisonannahme vertretbar.',[['\\widehat{EPS}_{NTM}','Geschätzter Gewinn der nächsten zwölf Monate.']])],'calendar'),
 q('10','practice','c d','A historical investment test uses fiscal-year earnings published in March to select stocks at the preceding December year-end. It assumes those earnings were already known. This most directly introduces:',[
 ['look-ahead bias.','Der historische Informationsstand enthält später veröffentlichte Daten.'],['a necessary calendarization adjustment.','Zeitliche Gewinnangleichung erlaubt keine damals noch unbekannten Berichte.'],['proof that the valuation strategy is implementable.','Die angenommenen Informationen waren am Entscheidungsstichtag nicht verfügbar.']
 ],['Der Zeitraum, auf den sich Gewinn bezieht, ist nicht sein Veröffentlichungsdatum.','Ein umsetzbarer historischer Test verwendet damals verfügbare Angaben.'],'calendar'),
 q('11','practice','b d','Common earnings are 90 million, including an isolated nonrecurring after-tax gain of 30 million. Shares are constant at 15 million. With no other adjustments, normalized EPS is:',[
 ['4.00','Der nicht fortgesetzte Gewinn wird vor der Division entfernt.'],['6.00','Dies ist berichtetes EPS einschließlich des Sondereffekts.'],['8.00','Dies addiert den einmaligen Gewinn erneut.']
 ],[F('EPS_{norm}=(90-30)/15=4','Alle Gewinnbeträge gehören zum selben Nachsteuer- und Stammkapitalumfang.',[['EPS_{norm}','Normalisierter Gewinn je Aktie.']])],'normalization'),
 q('12','practice','a b d','A suitable peer P/E of 16 is defined on normalized earnings. The subject’s normalized EPS is 3, while reported EPS including a nonrecurring gain is 5. Indicated value per share is:',[
 ['48.00','Peer-Quote und Zielgröße verwenden dieselbe normalisierte Basis.'],['80.00','Dies überträgt eine normalisierte Quote auf unbereinigte Gewinne.'],['32.00','Dies bewertet nur die Differenz der EPS-Basen.']
 ],[F('v^*=16\\cdot3=48','Die vergleichbare Gewinnbasis entscheidet den Multiplikanden.',[['v^*','Indizierter Wert je Aktie.']])],'normalization'),
 q('13','practice','a c d','Management excludes restructuring expenses from adjusted earnings every year. An analyst should most appropriately:',[
 ['evaluate their recurrence and economic effects before accepting the adjusted denominator.','Ein wiederholter ausgeschlossener Aufwand kann Teil der normalen Kostenbasis sein.'],['automatically exclude them because management calls them nonrecurring.','Die Bezeichnung allein begründet keine Normalisierung.'],['ignore any consequences for future cash flows and financing.','Aufwand und Zahlungen können die nachhaltige Verfügbarkeit beeinflussen.']
 ],['Normalisierung prüft Ursache, Häufigkeit, Steuern und Folgeeffekte.','Eine günstiger wirkende Kennzahl ist keine Begründung, reale Kosten wegzulassen.'],'normalization'),
 q('14','practice','b c d','For a cyclical company, holding price constant, unusually high peak-cycle earnings most directly cause:',[
 ['a lower trailing P/E that may not represent normal earning power.','Ein zeitweise großer Nenner senkt den Quotienten.'],['a higher trailing P/E because the share must be cheap.','Die Nennerwirkung läuft in die andere Richtung; Billigkeit folgt nicht daraus.'],['proof that future earnings must rise further.','Ein Zyklushoch garantiert keine weitere Expansion.']
 ],['Preis und Gewinnnenner werden getrennt analysiert.','Eine normale Gewinnbasis muss den vollständigen Zyklus und mögliche Strukturänderungen berücksichtigen.'],'cycle'),
 q('15','practice','b d','A full-cycle adjusted EPS average is 4. A separate estimate uses normal ROE of 10% on current book value per share of 50. At a price of 60, P/E using the current-book normalization is:',[
 ['12.00','Normales EPS auf heutiger Kapitalbasis ist fünf.'],['15.00','Dies verwendet den historischen EPS-Durchschnitt vier.'],['6.00','Dies teilt durch die Prozentzahl zehn statt durch einen Gewinn je Aktie.']
 ],[F('EPS_{norm}=0{,}10\\cdot50=5,\\quad m_{PE,norm}=60/5=12','Die zwei Normalisierungsverfahren sind ausdrücklich verschiedene Schätzungen.',[['EPS_{norm},m_{PE,norm}','Kapitalbasierter normaler Gewinn und dessen P/E.']])],'cycle'),
 q('16','practice','b','At the same positive share price, loss-making firms report negative P/E ratios of −10 and −40. The most accurate conclusion is:',[
 ['negative P/E ratios do not provide the usual ranking of cheap positive earnings.','Die übliche Billigkeitsrangfolge benötigt eine sinnvolle positive Gewinnbasis.'],['−40 necessarily represents the larger earnings loss relative to price.','Bei gleichem positiven Preis hat −40 den kleineren absoluten Verlustnenner.'],['the firm with −10 must have a negative share price.','Ein positiver Preis geteilt durch Verlust-EPS ergibt eine negative Quote.']
 ],['Ein anderer sinnvoller Nenner kann notwendig werden, ohne Verlust- und Finanzierungsprobleme zu beseitigen.','E/P zeigt die Ergebnisrelation einschließlich Vorzeichen deutlicher; es garantiert keine Anlagerendite.'],'pe-negative'),
 q('17','practice','b','A share price is 50 and comparable EPS is −1. Earnings yield is:',[
 ['−2.00%','Verlust je Aktie wird auf den positiven Preis bezogen.'],['−50.00%','Dies verwechselt das negative P/E von −50 mit einer Prozentgröße.'],['2.00%','Dies entfernt das entscheidende Verlustvorzeichen.']
 ],[F('y_E=(-1)/50=-0{,}02=-2\\%','Earnings Yield ist eine Ergebnisrelation, kein versprochener Total Return.',[['y_E','Ergebnisrendite auf der genannten Gewinnbasis.']])],'pe-negative'),
 q('18','practice','a b d','Under a constant-growth DDM, last EPS is 4, growth is 5%, payout is 50%, and required equity return is 10%. Model value per share is:',[
 ['42.00','Nächster Gewinn 4,2 und nächste Dividende 2,1 werden mit fünf Prozent kapitalisiert.'],['40.00','Dies verwendet den vergangenen statt den nächsten Gewinn bei der Forward-Quote.'],['21.00','Dies lässt den Wachstumsabzug im Nenner aus.']
 ],[F('EPS_1=4\\cdot1{,}05=4{,}2,\\quad v_0=0{,}5\\cdot4{,}2/(0{,}10-0{,}05)=42','Das Modell beginnt mit der nächsten Eigentümerleistung.',[['EPS_1','Nächster Gewinn je Aktie.'],['v_0','Heutiger DDM-Wert.']])],'forward-pe'),
 q('19','practice','a b d','For the same justified equity value, earnings grow by 4% between the trailing and forward periods. Justified forward P/E is 10. Justified trailing P/E is:',[
 ['10.40','Derselbe Wert wird durch den kleineren vergangenen Gewinn geteilt.'],['10.00','Dies ignoriert die verschiedene Gewinnperiode.'],['9.62','Dies wendet die Wachstumsanpassung in die umgekehrte Richtung an.']
 ],[F('m^*_{PE,T}=m^*_{PE,F}(1+g)=10\\cdot1{,}04=10{,}4','Die Preisgröße bleibt identisch, der Gewinnnenner wechselt.',[['m^*_{PE,T},m^*_{PE,F}','Trailing und Forward Modellquotient.'],['g','Gewinnwachstum vier Prozent.']])],'forward-pe'),
 q('20','practice','a b c','In a stable clean-surplus model with constant shares, ROE is below the cost of equity. Growth rises through additional earnings retention while ROE and the cost of equity stay constant. Justified forward P/E most likely:',[
 ['decreases because more earnings fund investments earning below the required return.','Zusätzliche Kapitalbindung zu unzureichender Rendite vermindert verfügbare Dividenden und Wert.'],['increases automatically because any growth creates value.','Die Rendite des Wachstumsinvestments entscheidet die Wertwirkung.'],['is necessarily undefined even when growth remains below both ROE and the cost of equity.','Unter den genannten gültigen Grenzen ist die Quote berechenbar.']
 ],['Einbehaltung und Wachstum werden konsistent miteinander verändert.','Bei festem ROE ist die Wachstumswirkung durch den Abstand zwischen Kapitalrendite und Eigenkapitalkosten bestimmt.'],'growth-pe'),
 q('21','practice','a b','In the same stable model, ROE equals the required equity return of 10%. Growth can range from 0% to 4% through consistent retention. Justified forward P/E is:',[
 ['10.00','Beim gleich hohen ROE und Diskontsatz kürzt sich die Wachstumswirkung heraus.'],['16.67','Dies ignoriert die für Wachstum erforderliche geringere Ausschüttung.'],['6.00','Dies verwechselt den Ausschüttungsanteil bei vier Prozent Wachstum mit dem Wertmultiplikator.']
 ],[F('m^*_{PE,F}=\\frac{1-g/0{,}10}{0{,}10-g}=10','Investition zur passenden Kostenrendite schafft hier keine zusätzliche Überrendite.',[['m^*_{PE,F}','Gerechtfertigtes Forward P/E.'],['g','Zulässige stabile Wachstumsrate.']])],'growth-pe'),
 q('22','practice','a b c','A stable firm has payout of 60% and growth of 3%. Holding these fixed, required equity return rises from 9% to 12%. The new justified forward P/E is closest to:',[
 ['6.67','Sechzig Prozent Ausschüttung geteilt durch neun Prozent Rendite-Wachstums-Abstand.'],['10.00','Dies ist die alte Modellquote bei neun Prozent Eigenkapitalkosten.'],['20.00','Dies dividiert allein durch die Wachstumsrate.']
 ],[F('m^*_{PE,F}=0{,}60/(0{,}12-0{,}03)=6{,}6667','Mehr erforderliche Rendite senkt bei gleicher Zahlungsperspektive den heutigen Wert.',[['m^*_{PE,F}','Neue gerechtfertigte Quote.']])],'risk-pe'),
 q('23','practice','b c','P/E is 24 and expected annual EPS growth is 12%. Under the convention of dividing P/E by growth in percentage points, PEG is:',[
 ['2.00','Vierundzwanzig wird durch zwölf geteilt.'],['200.00','Dies verwendet 0,12 statt der ausdrücklich genannten Prozentzahl zwölf.'],['0.50','Dies kehrt die Quote um.']
 ],[F('PEG=24/(100\\cdot0{,}12)=2','Die Wachstumseinheit ist Teil der Kennzahlkonvention.',[['PEG','P/E-to-Growth-Ratio nach der gegebenen Konvention.']])],'peg'),
 q('24','practice','b c','Two firms have identical positive PEG ratios. This most accurately indicates that:',[
 ['their P/E-to-growth quotients match, while risk, payout, reinvestment and growth duration may still differ.','PEG bereinigt diese anderen Treiber nicht automatisch.'],['both must be fairly valued because growth fully explains P/E.','P/E hängt nicht nur und nicht allgemein proportional vom Wachstum ab.'],['the higher-growth firm can sustain that growth indefinitely without investment.','Wachstumsdauer und Kapitalbedarf müssen separat begründet werden.']
 ],['Gleichheit eines zusammenfassenden Quotienten ist keine Gleichheit sämtlicher Werttreiber.','Null- und negatives Wachstum begrenzen zusätzlich seine gewöhnliche Interpretation.'],'peg'),
 q('25','practice','b d','Common book equity is 360 million, with 12 million current comparable shares. The price is 45 per share. P/B is:',[
 ['1.50','Buchwert je Aktie dreißig wird mit dem Preis fünfundvierzig verglichen.'],['0.13','Dies teilt Stückpreis durch Gesamtbuchkapital.'],['0.67','Dies kehrt Buchwert je Aktie und Preis im Verhältnis um.']
 ],[F('BVPS=360/12=30,\\quad m_{PB}=45/30=1{,}5','Buchwert und Bestand beziehen sich auf denselben Stichtag und Anspruch.',[['BVPS','Buchwert je Aktie.'],['m_{PB}','Preis-Buchwert-Verhältnis.']])],'pb'),
 q('26','practice','b c','A write-down lowers common book equity from 200 to 160. For a controlled denominator comparison, market capitalization stays at 240. P/B after the write-down is:',[
 ['1.50','Derselbe Marktwert wird durch den geringeren Buchwert geteilt.'],['1.20','Dies ist das Verhältnis vor der Wertminderung.'],['0.67','Dies kehrt die neue Preis-Buchwert-Relation um.']
 ],[F('m_{PB}=240/160=1{,}5','Die mechanische Kennzahlwirkung allein beweist keine neue ökonomische Überbewertung.',[['m_{PB}','P/B nach der angegebenen Buchwertänderung.']])],'pb'),
 q('27','practice','a b c','A stable clean-surplus firm has next-year ROE on beginning book equity of 8%, growth of 2% and a 10% required equity return. Justified P/B is:',[
 ['0.75','Kapitalrendite minus Wachstum wird durch Kosten minus Wachstum geteilt.'],['1.00','Dies würde im Modell ROE gleich Kosten verlangen.'],['1.33','Dies kehrt die richtige Relation um.']
 ],[F('m^*_{PB}=(0{,}08-0{,}02)/(0{,}10-0{,}02)=0{,}75','ROE unter den Kosten rechtfertigt hier einen Buchwertabschlag.',[['m^*_{PB}','Gerechtfertigtes P/B.']])],'pb-fundamentals'),
 q('28','practice','b','On matching positive earnings and revenue bases, P/E is 18 and common net income is 10% of sales. Price-to-sales is:',[
 ['1.80','Das Gewinnverhältnis wird mit der Nettomarge multipliziert.'],['180.00','Dies teilt durch die Marge statt zu multiplizieren.'],['18.00','Dies behandelt Umsatz und Nettogewinn als gleich.']
 ],[F('m_{PS}=m_{PE}\\mu=18\\cdot0{,}10=1{,}8','Der Umsatznenner ist größer als der Gewinnnenner.',[['m_{PS},m_{PE}','Passende Preis-Umsatz- und Preis-Gewinn-Verhältnisse.'],['\\mu','Nettomarge zehn Prozent.']])],'ps'),
 q('29','practice','a b c','Two firms have the same projected sales per share and appropriately equal justified forward P/E. One has twice the projected common net margin. Its justified forward price-to-sales ratio is:',[
 ['twice as high under the stated controlled assumptions.','Doppelte Marge erzeugt doppelte Gewinne je Umsatzeinheit und hier doppelte Wertrelation.'],['the same because sales alone determine equity value.','Marge ist gerade der im Fall veränderte Eigentümergewinnkanal.'],['half as high because higher profits increase the revenue denominator.','Der Umsatz wird im Fall nicht verändert.']
 ],['P/S entspricht bei passender Basis P/E mal Nettomarge.','Eine reale Peer-Auswahl müsste auch die Voraussetzungen des gleichen gerechtfertigten P/E prüfen.'],'ps'),
 q('30','practice','b d','A firm has common market value of 600, net income of 40, depreciation of 10 and operating working capital investment of 5. Interest is already included in income and CFO; there are no other CFO adjustments. Price-to-CFO is closest to:',[
 ['13.33','CFO beträgt vierzig plus zehn minus fünf, also fünfundvierzig.'],['12.00','Dies verwendet Cash Earnings fünfzig ohne Working-Capital-Bindung.'],['15.00','Dies verwendet nur Nettogewinn vierzig.']
 ],[F('CFO=40+10-5=45,\\quad m_{P/CFO}=600/45=13{,}3333','Die Cashflowdefinition unterscheidet sich von einer groben Gewinnbereinigung.',[['CFO','Operativer Cashflow.'],['m_{P/CFO}','Preis-CFO-Verhältnis.']])],'pcf'),
 q('31','practice','b','CFO already after interest is 60, capital expenditures are 25 and net borrowing is 5, with no other adjustments or claims. Common market value is 800. Price-to-FCFE is:',[
 ['20.00','Freier Eigenkapitalcashflow ist sechzig minus fünfundzwanzig plus fünf.'],['13.33','Dies verwendet CFO und lässt Investition sowie Nettokreditaufnahme aus.'],['26.67','Dies zieht die Nettokreditaufnahme statt sie hinzuzufügen.']
 ],[F('FCFE=60-25+5=40,\\quad m_{P/FCFE}=800/40=20','Cashflow und Finanzierung sind für denselben Eigentümeranspruch abgestimmt.',[['FCFE','Freier Eigenkapitalcashflow.'],['m_{P/FCFE}','Preis-FCFE-Verhältnis.']])],'pcf'),
 q('32','practice','b','Common market capitalization is 500, debt 150, preferred claims 20 and corresponding noncontrolling interests 30. Surplus cash is 40 and a separate nonoperating investment is 10. Matching EBITDA is 100. EV/EBITDA is:',[
 ['6.50','Operativer EV ist fünfhundert plus zweihundert Ansprüche minus fünfzig separate Werte.'],['5.00','Dies verwendet ausschließlich Stammkapital statt den operativen Gesamtanspruch.'],['7.00','Dies entfernt separate Kasse und Anlage nicht.']
 ],[F('EV=500+150+20+30-40-10=650,\\quad m_{EV/EBITDA}=650/100=6{,}5','Die konsolidierten operativen Größen und die dazugehörigen Ansprüche passen zusammen.',[['EV','Abgegrenzter operativer Marktwert.'],['m_{EV/EBITDA}','Operativer Multiplikator.']])],'ev-bridge'),
 q('33','practice','a b','An appropriate EV/EBITDA multiple of 8 is applied to forecast EBITDA of 90 million. Debt is 180, preferred claims 20, corresponding NCI 30, surplus cash 40 and a separate investment 10 million. There are 10 million common shares. Indicated common value per share is:',[
 ['54.00','Operativer Wert 720 wird vollständig zum Stammkapital 540 übergeleitet.'],['72.00','Dies teilt EV direkt durch Stammaktien und lässt die Anspruchsbrücke aus.'],['59.00','Dies lässt Vorzüge und NCI aus.']
 ],[F('v^*=(8\\cdot90+40+10-180-20-30)/10=54','Jeder fremde Anspruch und separate Wert wird genau einmal berücksichtigt.',[['v^*','Indizierter Wert je Stammaktie.']])],'ev-bridge'),
 q('34','practice','b c','An analyst uses fully consolidated subsidiary EBITDA in an EV comparison but excludes the corresponding noncontrolling interest value from observed EV. With positive EBITDA, the observed EV/EBITDA will most directly be:',[
 ['understated relative to the consistently matched scope.','Der volle operative Nenner wird auf einen zu kleinen Anspruchswert bezogen.'],['overstated because all subsidiary earnings belong to outsiders.','Nur ein Teil gehört Außenstehenden; die fehlende Wertaddition vermindert den Zähler.'],['unaffected because NCI can never matter in an enterprise comparison.','Fremde Tochteranteile gehören zum vollständig erfassten Geschäftsumfang.']
 ],['Die Konsolidierung erfasst das Geschäft vollständig.','Die Wertseite benötigt die dazu passenden Ansprüche, bevor Multiplikatoren verglichen werden.'],'ev-bridge'),
 q('35','practice','b c','In a no-tax perpetual model, operating value is 500 and EBIT is 50. Debt value is 200 and annual interest is 10. No other claims, cash or investments exist. P/E is closest to:',[
 ['7.50','Stammkapital dreihundert wird auf verbleibenden Gewinn vierzig bezogen.'],['10.00','Dies ist das unveränderte operative EV/EBIT.'],['12.50','Dies teilt den umfassenden EV durch den nach Zinsen verbleibenden Stammgewinn.']
 ],[F('E=500-200=300,\\quad NI=50-10=40,\\quad m_{PE}=300/40=7{,}5','Finanzierung verändert Zähler und Nenner des Equity-Verhältnisses.',[['E,NI','Verbleibender Stammkapitalwert und Gewinn.'],['m_{PE}','P/E.']])],'leverage'),
 q('36','practice','b c','An industrial peer has lower P/E because its equity claim carries substantially more financial risk. An EV-based comparison:',[
 ['can reduce the direct financing-scope difference but still requires assessment of economic financing effects.','EV-Größen helfen beim Umfangsabgleich, beseitigen aber Steuern und Insolvenzfolgen nicht.'],['proves the peer is cheaper on an identical risk-adjusted basis.','Risiko und andere fundamentale Unterschiede müssen weiterhin geprüft werden.'],['is always appropriate for banks because debt has no operating role there.','Bei Banken sind Schulden und Zinsströme oft Teil des operativen Geschäfts.']
 ],['Operative und Equity-Verhältnisse beantworten verschiedene Fragen.','Die saubere Anspruchsebene ergänzt eine wirtschaftliche Risikoanalyse.'],'leverage'),
 q('37','practice','b','EV is 720, EBITDA is 120 and corresponding depreciation is 30. EV/EBIT is:',[
 ['8.00','EBIT beträgt neunzig.'],['6.00','Dies ist EV/EBITDA.'],['24.00','Dies verwendet ausschließlich Abschreibung als Nenner.']
 ],[F('EBIT=120-30=90,\\quad m_{EV/EBIT}=720/90=8','Beide Quotienten verwenden denselben Wert, aber verschiedene Ergebnisgrößen.',[['EBIT','Ergebnis vor Zinsen und Steuern.'],['m_{EV/EBIT}','Operativer EBIT-Multiplikator.']])],'ebitda'),
 q('38','practice','b','Forecast EBITDA is 120, depreciation is 20, the usable tax rate is 25%, capital expenditures are 35 and working capital investment is 10. With no other adjustments, FCFF is:',[
 ['50.00','Nachsteuerliches EBIT fünfundsiebzig plus Abschreibung zwanzig minus Investitionen fünfundvierzig.'],['95.00','Dies lässt Capex und Working Capital aus.'],['120.00','Dies behandelt EBITDA als freien Cashflow.']
 ],[F('FCFF=(120-20)(1-0{,}25)+20-35-10=50','Steuern und Kapitalbindung werden ausdrücklich berücksichtigt.',[['FCFF','Freier operativer Cashflow der ersten Prognoseperiode.']])],'cash-investment'),
 q('39','practice','a b c','In a stable model, next NOPAT is 80, ROIC is 10% and growth is 4%, with matching reinvestment and no efficiency changes. Required net operating reinvestment is:',[
 ['32.00','Vierzig Prozent des operativen Gewinns müssen gebunden werden.'],['3.20','Dies multipliziert NOPAT nur mit Wachstum und übersieht den Kapitalbedarf je Gewinneinheit.'],['48.00','Dies ist der nach Reinvestition verbleibende FCFF.']
 ],[F('I_{net,1}=80\\cdot(0{,}04/0{,}10)=32','Die Kapitalrendite übersetzt Gewinnzuwachs in benötigtes Kapital.',[['I_{net,1}','Erste erforderliche Nettoinvestition des stabilen Modells.']])],'ev-fundamentals'),
 q('40','practice','a b c d','Next EBITDA is 100 and NOPAT is 60. Stable growth is 3%, ROIC is 10% and WACC is 9%. Assuming consistent reinvestment and stable cash flow growth, justified forward EV/EBITDA is:',[
 ['7.00','FCFF zweiundvierzig geteilt durch sechs Prozent liefert EV siebenhundert.'],['10.00','Dies kapitalisiert NOPAT ohne die Wachstumsinvestition.'],['4.67','Dies ignoriert den Wachstumsabzug im Diskontnenner.']
 ],[F('FCFF_1=60(1-0{,}03/0{,}10)=42,\\quad EV^*=42/(0{,}09-0{,}03)=700,\\quad m^*_{EV/EBITDA,F}=700/100=7','Wachstum und Kapitalbindung sind in derselben Modellphase abgestimmt.',[['FCFF_1,EV^*','Erster freier Cashflow und operativer Modellwert.'],['m^*_{EV/EBITDA,F}','Gerechtfertigter nächster EBITDA-Multiplikator.']])],'ev-fundamentals'),
 q('41','practice','a c','The most appropriate potential peer group for an industrial company is one:',[
 ['screened for business similarity and valuation drivers such as growth, risk, profitability and reinvestment.','Die Branche organisiert die Suche; wirtschaftliche Gemeinsamkeiten begründen den Vergleich.'],['containing every firm in the same industry regardless of capital requirements and risk.','Ein Branchenname garantiert keine gleichen Werttreiber.'],['chosen solely to make the subject’s current price appear low.','Eine gewünschte Schlussfolgerung ist kein sachgerechtes Auswahlkriterium.']
 ],['Auch Rechnungslegung, Umfang, Zeitbasis und Marktliquidität werden abgeglichen.','Kein Peer ist vollkommen identisch; verbleibende Unterschiede werden erklärt.'],'peers'),
 q('42','practice','a c','A company trades below a carefully matched sector P/E median. The entire sector may still be overvalued. The most accurate conclusion is:',[
 ['relative cheapness does not establish absolute undervaluation; a fundamental cross-check remains useful.','Ein Vergleich kann gemeinsame Fehlpreise übernehmen.'],['a below-median price multiple guarantees a positive return.','Gemeinsame Fehler und künftige Risiken bleiben bestehen.'],['a median eliminates any error in the selected peer universe.','Robuste Zusammenfassung heilt keine ungeeignete oder falsch bepreiste Gruppe.']
 ],['Comparables beurteilen eine relative Beziehung.','Ein DCF-Gegenmodell kann die Cashflow-, Kapital- und Risikoannahmen separat prüfen.'],'peers'),
 q('43','practice','a b c','Three equally treated positive peer P/E ratios are 8, 12 and 40. The median is:',[
 ['12.00','Die mittlere geordnete Beobachtung ist zwölf.'],['20.00','Dies ist das arithmetische Mittel.'],['40.00','Dies ist der größte Wert.']
 ],['Median und Mittelwert fassen dieselben Daten auf verschiedene Weise zusammen.','Die wirtschaftliche Eignung der Gruppe wird dadurch noch nicht geprüft.'],'summary'),
 q('44','practice','b','Equal monetary investments are made in two firms with matching positive P/E ratios of 10 and 30. P/E of the combined acquired earnings claim is:',[
 ['15.00','Gleiche Geldgewichte führen zum harmonischen Mittel.'],['20.00','Dies ist der ungewichtete arithmetische Durchschnitt der Quotienten.'],['40.00','Dies addiert die Quotienten ohne Bezug zu den erworbenen Ansprüchen.']
 ],[F('m_{combined}=2/(1/10+1/30)=15','Je sechzig Geldeinheiten kaufen Gewinnansprüche sechs und zwei; hundertzwanzig durch acht ist fünfzehn.',[['m_{combined}','Aggregiertes P/E der gleich großen Geldanlagen.']])],'summary'),
 q('45','practice','b c','Company A has common market value 120 and common earnings 10. Company B has common market value 360 and common earnings 20. Earnings bases match. Aggregated market value divided by aggregated earnings is:',[
 ['16.00','Gesamtwert vierhundertachtzig geteilt durch Gewinn dreißig.'],['15.00','Dies ist der ungewichtete Durchschnitt der Einzel-P/E zwölf und achtzehn.'],['16.50','Dies ist der mit Marktwerten gewichtete arithmetische Durchschnitt.']
 ],[F('m_{agg}=(120+360)/(10+20)=16','Der aggregierte Anspruch entspricht dem marktwertgewichteten harmonischen Verhältnis.',[['m_{agg}','Aggregiertes P/E der beiden Unternehmen.']])],'aggregate'),
 q('46','practice','b c d','Price and matching EPS are translated into another currency using the same fixed conversion factor. Their P/E ratio:',[
 ['is unchanged by that pure unit conversion.','Der gemeinsame Faktor kürzt sich heraus.'],['must increase by the conversion factor.','Dies würde nur den Zähler umrechnen.'],['is necessarily comparable across all countries after conversion.','Gleiche Einheiten beseitigen keine Risiko-, Bilanzierungs- oder Prognoseunterschiede.']
 ],[F('\\frac{aP}{aEPS}=\\frac{P}{EPS}\\quad(a>0)','Die reine gemeinsame Einheitenänderung lässt die Quote gleich.',[['a','Gemeinsamer positiver Umrechnungsfaktor.'],['P,EPS','Preis und passender Gewinn je Aktie in ursprünglicher Währung.']])],'accounting'),
 q('47','practice','a b d','An estimated value at the end of year 2 uses a justified forward P/E of 12. EPS in year 2 is 4 and EPS in year 3 is 4.4. The terminal share value immediately after the year-2 dividend is:',[
 ['52.80','Der Forward-Nenner am Termin zwei ist der Gewinn der nachfolgenden Periode drei.'],['48.00','Dies verwendet EPS₂ mit einer für die folgende Periode definierten Quote.'],['58.08','Dies schiebt die Gewinnbasis um eine weitere nicht gefragte Wachstumsperiode.']
 ],[F('v_2=12\\cdot4{,}4=52{,}8','Der zukünftige Bewertungsstichtag und seine nächste Gewinnperiode bleiben konsistent.',[['v_2','Verbleibender Wert in Jahr zwei vor Diskontierung auf heute.']])],'terminal'),
 q('48','practice','a b c d','Forward EBITDA is 80 million and the current claim bridge from operating value to common equity is −200 million. There are 10 million common shares. Holding these inputs fixed, increasing the selected forward EV/EBITDA from 8 to 9 changes indicated common value per share by:',[
 ['8.00','Der operative Wert steigt um achtzig Millionen, verteilt auf zehn Millionen Aktien.'],['1.00','Dies verwechselt Multiplikatoränderung mit einer Geldänderung je Aktie.'],['80.00','Dies lässt die Division durch die Aktienzahl aus.']
 ],[F('\\Delta v^*=(9-8)80/10=8','Die unveränderte Anspruchsbrücke kürzt sich im Unterschied heraus.',[['\\Delta v^*','Änderung des indizierten Werts je Stammaktie.']])],'integrated'),
 q('a1','mock-a','a b c d','An industrial firm has 12 million constant common shares at 50, debt market value of 180 million, preferred claims of 30 and corresponding NCI of 40. Surplus cash is 50 and a separate nonoperating investment is 20 million. Forward consolidated EBITDA is 100 million. After reviewing growth, risk and investment, an analyst selects a matching forward EV/EBITDA of 9. Indicated common value per share is:',[
 ['60.00','Der Vergleich ergibt EV neunhundert und nach vollständiger Brücke Stammkapital siebenhundertzwanzig.'],['75.00','Dies teilt den operativen Gesamtwert direkt durch Stammaktien.'],['63.33','Dies lässt die fremden Tochteranteile in der Anspruchsbrücke aus.']
 ],[F('EV_{observed}=12\\cdot50+180+30+40-50-20=780,\\quad m_{observed}=780/100=7{,}8','Die vorhandene Marktquote und die gewählte Vergleichsquote bleiben getrennte Größen.',[['EV_{observed},m_{observed}','Beobachteter operativer Wert und Forward EBITDA-Multiple.']]),
 F('v^*=(9\\cdot100+50+20-180-30-40)/12=60','Umfang, Gewinnperiode und fremde Ansprüche werden bis zur gesuchten Stammaktie abgegrenzt.',[['v^*','Indizierter Wert je Stammaktie.']])],'ev-bridge'),
 q('a2','mock-a','a b c','A stable clean-surplus subject has forecast ROE on beginning book equity of 12%, growth of 3% and required equity return of 9%. A same-industry peer has the same growth and required return, but forecast ROE of 15% and observed P/B of 2. The most appropriate justified P/B for the subject under these assumptions is:',[
 ['1.50','Die geringere Kapitalüberrendite des Zielunternehmens erklärt einen niedrigeren Modellquotienten.'],['2.00','Dies übernimmt den Peer-Wert ohne die abweichende Kapitalrendite.'],['1.00','Dies setzt gleiche Kapitalrendite und Kosten voraus, obwohl zwölf über neun Prozent liegt.']
 ],[F('m^*_{PB,subject}=(0{,}12-0{,}03)/(0{,}09-0{,}03)=1{,}5','Die Branche allein erlaubt keine Übertragung eines höheren ROE-Multiplikators.',[['m^*_{PB,subject}','Gerechtfertigtes P/B des Zielunternehmens.']]),
 'Die beobachtete Peer-Quote zwei wäre mit dessen eigenem stabilen Modell vereinbar. Beide Rechnungen bleiben von dauerhaft erreichbaren Renditen und passenden Buchwerten abhängig.'],'pb-fundamentals'),
 q('b1','mock-b','a b c d','An industrial firm has next EBITDA of 120 million, depreciation of 20 and a usable tax rate of 25%. Its stable ROIC is 6.25%, growth 3% and WACC 9%, with consistent net reinvestment and growing free cash flow. Debt is 120 million, surplus cash 20, no other adjustments and 10 million common shares. The indicated common value per share from the fundamental forward enterprise multiple is:',[
 ['55.00','NOPAT fünfundsiebzig erfordert Nettoinvestition sechsunddreißig; FCFF neununddreißig ergibt operativen Wert sechshundertfünfzig.'],['85.00','Dies verwendet die geringere Reinvestition eines anderen Modells mit doppelt so hohem ROIC.'],['65.00','Dies teilt EV direkt durch Aktien und lässt die Nettoanspruchsbrücke aus.']
 ],[F('NOPAT_1=(120-20)(1-0{,}25)=75,\\quad FCFF_1=75(1-0{,}03/0{,}0625)=39','Wachstum bindet hier achtundvierzig Prozent des operativen Gewinns.',[['NOPAT_1,FCFF_1','Erster operativer Nachsteuergewinn und freier Cashflow.']]),
 F('EV^*=39/(0{,}09-0{,}03)=650,\\quad m^*_{EV/EBITDA,F}=650/120=5{,}4167,\\quad v^*=(650+20-120)/10=55','Der vergleichsweise niedrige EBITDA-Multiplikator folgt aus dem hohen Kapitalbedarf; die Brücke führt zum Stammanspruch.',[['EV^*','Operativer Modellwert.'],['m^*_{EV/EBITDA,F}','Gerechtfertigtes Forward EBITDA-Verhältnis.'],['v^*','Wert je Stammaktie.']])],'ev-fundamentals'),
 q('b2','mock-b','b c d','A group of three common equity holdings has market value weights of 20%, 30% and 50%. Matching positive P/E ratios on the same forward basis are 8, 16 and 40. P/E of the combined proportional earnings claim is closest to:',[
 ['17.78','Der Gesamtwert geteilt durch die erworbenen Gewinne entspricht dem gewichteten harmonischen Mittel.'],['26.40','Dies ist das marktwertgewichtete arithmetische Mittel der Quotienten.'],['21.33','Dies ist der ungewichtete arithmetische Durchschnitt.']
 ],[F('m_{combined}=\\frac{1}{0{,}20/8+0{,}30/16+0{,}50/40}=17{,}7778','Bei hypothetischem Gesamtwert hundert ergeben die Teilwerte zwanzig, dreißig und fünfzig Gewinnansprüche 2,5, 1,875 und 1,25.',[['m_{combined}','P/E des zusammen betrachteten Anspruchs.']]),
 'Die Gewichtung bezieht sich auf erworbenen Marktwert. Das Ergebnis ist weiterhin eine Gewinnrelation und kein zugesagter Ausschüttungsertrag.'],'aggregate')
];
