const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('stk-'+id,'stakeholders','corporate',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','Which feature most accurately describes ordinary common equity in the basic corporate financing model?',[
 ['A residual claim without a contractual promise of dividends or repayment at a fixed maturity.','Der verbleibende Erfolg gehört den Stammaktionären; der gewöhnliche Aktienanspruch verspricht keine feste Bedienung.'],['A fixed interest claim ranking ahead of all lenders.','Das beschreibt weder die Zahlungsform noch den Rang gewöhnlicher Stammaktien.'],['A right to force the issuer to repurchase every share at the original price.','Ein gewöhnlicher Aktienverkauf ist keine solche Rückzahlungsverpflichtung der Gesellschaft.']
 ],['Zuerst werden vertraglich vorrangige Ansprüche berücksichtigt. Erst der verbleibende Betrag steht den gewöhnlichen Aktionären zu.','Besondere Rückkaufs-, Vorzugs- oder Wandelrechte müssen gesondert geprüft werden; sie werden hier nicht unterstellt.'],'claims'),
 q('02','practice','a','Compared with ordinary common equity financing, fixed debt most directly increases the issuer’s:',[
 ['exposure to mandatory debt service and refinancing needs.','Vereinbarte Fälligkeiten können Liquiditätsdruck erzeugen.'],['ability to omit all promised payments whenever earnings are low.','Ein schwaches Ergebnis beseitigt die vertragliche Bedienungspflicht nicht automatisch.'],['obligation to give every lender ordinary shareholder voting rights.','Kreditverträge können Kontrollrechte enthalten, schaffen aber nicht automatisch gewöhnliche Aktionärsstimmen.']
 ],['Die Schuld kann aus Anlegersicht vorrangig sein und dennoch aus Emittentensicht feste Zahlungsrisiken schaffen. Die Perspektive ist entscheidend.','Eigenkapitalausgabe hat andere Kosten, etwa Beteiligungsverwässerung und verlangte Eigenkapitalrendite.'],'claims'),
 q('03','practice','a','At liquidation, 65 is available after all prior costs. The sole debt claim is 80. Common shareholders have fully paid their shares and owe no guarantees. Their end payment is:',[
 ['0','Der verfügbare Betrag deckt nicht einmal die vorrangige Schuld.'],['15','Dies ist der Gläubigerausfall, kein positiver Aktienanspruch.'],['65','Dies ignoriert den Vorrang der Schuld.']
 ],[F('E_T=\\max(65-80,0)=0','Beschränkte Haftung verhindert eine negative zusätzliche Auszahlung im gegebenen Grundmodell.',[['E_T','Verbleibende Endzahlung an die Aktionäre.']]),'Gläubiger erhalten 65 und verlieren 15 auf ihren vertraglichen Anspruch. Die Aktionäre können ihre frühere Investition verloren haben, ohne zusätzlich 15 einzahlen zu müssen.'],'waterfall'),
 q('04','practice','a','There are 84 of assets available for two debt classes. Senior debt of 60 must be paid first; subordinated debt is 40. There are no other claims or costs. The subordinated debt recovery rate is:',[
 ['60%','Nach Zahlung der vorrangigen 60 verbleiben 24; 24 geteilt durch 40 sind 60 %.'],['84%','Dies ist die Gesamtdeckung von 100 Schuld, nicht die Recovery der nachrangigen Klasse.'],['100%','Die verfügbare Summe reicht nicht für beide Klassen.']
 ],[F('RR_J=\\frac{84-60}{40}=60\\%','Der Nenner ist die Forderung der betrachteten Klasse.',[['RR_J','Rückgewinnungsquote der nachrangigen Schuld.']]),'Die Senior-Klasse wird vollständig bedient. Unterschiedlicher Rang führt trotz desselben Emittenten zu unterschiedlichen Verlusten.'],'seniority'),
 q('05','practice','a','A one-year debt security costs 100. It pays 108 with probability 96% and 60 otherwise. There are no intermediate payments or fees. Its expected holding-period return is closest to:',[
 ['6.08%','Die erwartete Zahlung beträgt 106,08.'],['8.00%','Dies ist die Rendite bei vollständiger Zahlung des Versprechens.'],['4.00%','Dies ist die Ausfallwahrscheinlichkeit, keine Rendite.']
 ],[F('\\mathbb{E}[R]=\\frac{0{,}96\\cdot108+0{,}04\\cdot60}{100}-1=6{,}08\\%','Zunächst wird der erwartete tatsächliche Endbetrag berechnet.',[['\\mathbb{E}[R]','Erwartete einjährige Halteperiodenrendite.']]),'Wahrscheinlichkeit und Verlusthöhe müssen gemeinsam berücksichtigt werden. Eine hohe versprochene Rendite darf nicht mit einer sicheren oder erwarteten Rendite verwechselt werden.'],'promised-expected'),
 q('06','practice','a b','Existing debt promises 90. A safe strategy pays 110 for certain. An alternative pays either 60 or 160 with equal probability, using the same resources. There are no other claims or costs. Moving to the alternative changes expected common equity end payments from:',[
 ['20 to 35, while expected debt payments fall from 90 to 75.','Im riskanten Fall bekommt Eigenkapital null oder 70; die Schuld erhält 60 oder 90.'],['20 to 20, because expected total assets are unchanged.','Ein unveränderter Gesamtmittelwert bedeutet nicht unveränderte Verteilung zwischen Ansprüchen.'],['20 to 50, while debt payments remain certain at 90.','Im niedrigen Zustand können nicht 90 aus lediglich 60 bezahlt werden.']
 ],[F('\\mathbb{E}[E_T]=0{,}5\\cdot0+0{,}5\\cdot70=35','Der zusätzliche erwartete Aktienbetrag stammt im Fall vollständig aus geringerer Gläubigerdeckung.',[['\\mathbb{E}[E_T]','Erwartete Endzahlung an Aktionäre in der Alternative.']]),'Die erwartete Gesamtsumme bleibt 110. Dies ist eine Zahlungsumverteilung bei unverändertem alten Schuldversprechen, keine Aussage über heutige Marktpreise.'],'risk-shifting'),
 q('07','practice','a b','Why can shareholders sometimes prefer a riskier strategy that reduces expected total end assets when debt has already been issued on fixed terms?',[
 ['Their residual payoff is bounded below by zero while lenders absorb part of the additional downside.','Die begrenzte Verlustseite und die verbleibende Erfolgsbeteiligung können einen Übertragungsanreiz erzeugen.'],['All losses must be repaid personally by every shareholder.','Diese Behauptung widerspricht dem hier betrachteten Grundmodell beschränkter Haftung.'],['The lender’s promised payment automatically rises with every increase in business risk.','Die Frage setzt gerade unveränderte Vertragsbedingungen voraus.']
 ],['Jeder Zustand wird zunächst zwischen Schuld und Eigenkapital aufgeteilt. Erst dann werden die Zahlungen gewichtet. Aktionäre können im günstigen Zustand stark profitieren, während im schlechten Zustand hauptsächlich die alte Schuld zusätzlich verliert.','Reputation, Covenants und künftiger Finanzierungsbedarf können diesen Anreiz begrenzen.'],'risk-shifting'),
 q('08','practice','a b','At a common future date, existing assets will pay 80 and old debt of 100 is due. A new project costs shareholders 10 today and adds 25 at that date. The discount rate is zero and there are no other cash flows. If debt terms do not change, the shareholders’ net gain from funding the project is:',[
 ['−5','Sie bezahlen zehn, erhalten am Ende aber nur fünf über der alten Schuld.'],['15','Dies ist der Kapitalwert des Gesamtprojekts, nicht der allein finanzierenden Aktionäre.'],['25','Dies ignoriert neuen Einsatz und Verbesserung der alten Gläubigerdeckung.']
 ],[F('\\Delta W_E=\\max(80+25-100,0)-10=-5','Vor der Investition ist die Aktienendzahlung null; danach beträgt sie fünf.',[['\\Delta W_E','Nettoänderung des Aktionärsvermögens beim Diskontsatz null.']]),'Das Projekt schafft insgesamt 15 an Kapitalwert. Alte Gläubiger gewinnen 20 an Deckung, die Aktionäre verlieren fünf. Dies erklärt mögliche Unterinvestition durch Debt Overhang.'],'debt-overhang'),
 q('09','practice','a b','A covenant restricting dividends is most directly intended to reduce the risk that:',[
 ['assets supporting existing debt are distributed to shareholders.','Die Ausschüttung kann den für den Schuldendienst verfügbaren Puffer vermindern.'],['ordinary shareholders receive the lender’s scheduled coupon by mistake.','Dies ist nicht der wirtschaftliche Kern einer Ausschüttungsbegrenzung.'],['the company ever undertakes a positive-value project.','Das ist kein sinnvolles Schutzziel; zu enge Klauseln können allerdings unbeabsichtigt gute Projekte behindern.']
 ],['Die konkrete Ausschüttungsregel, Ausnahmen und Rechtsfolgen müssen gelesen werden. Der Name Covenant allein beschreibt weder eine universelle Formel noch automatische Liquidation.','Schutz vor Wertübertragung wird gegen Finanzierungskosten und verlorene Flexibilität abgewogen.'],'claim-protection'),
 q('10','practice','a','An analyst states that every common stock is less safe than every corporate bond. The best response is that:',[
 ['priority supports a comparison within a given issuer, but cross-issuer risk also depends on credit quality, maturity, currency, and price.','Die Rangfolge allein erlaubt keine weltweite Rangordnung beliebiger Titel.'],['bonds can never lose principal.','Ausfall und andere Risiken können den Anleihewert und Rückzahlungsbetrag reduzieren.'],['all securities of all issuers have the same risk once listed.','Börsenhandel beseitigt Unterschiede im Anspruch und Emittentenrisiko nicht.']
 ],['Für den Grundvergleich wird dieselbe Firma mit gewöhnlicher vorrangiger Schuld und nachrangiger Aktie betrachtet. Ein Vergleich verschiedener Firmen braucht zusätzliche Informationen.','Auch Marktpreisschwankungen lang laufender Schuld und ihre Halteperiode sind von bloßem Ausfallrisiko zu trennen.'],'claims'),
 q('11','practice','b','A supplier sells inputs to a company on credit and also owns a small equity stake in it. The supplier is most appropriately analyzed:',[
 ['in both roles, because trade-credit and equity interests can differ.','Die Rollen überlappen, ohne ihre unterschiedlichen Ansprüche zu beseitigen.'],['only as a shareholder because ownership cancels the invoice claim.','Der Aktienbesitz hebt eine separate Forderung nicht automatisch auf.'],['only as an external observer with no financial exposure.','Sowohl die offene Rechnung als auch der Aktienanteil schaffen finanzielle Exposition.']
 ],['Stakeholdergruppen sind keine zwingend disjunkten Personengruppen. Für die jeweilige Entscheidung werden Forderung, Beteiligung und Geschäftsbeziehung getrennt betrachtet.','Ein stabiler Liefervertrag kann zusätzlich zur unmittelbaren Zahlungsforderung wertvoll sein.'],'stakeholder-map'),
 q('12','practice','b','A CEO pursues an acquisition primarily because managing a larger company would increase personal status, even though the acquisition is expected to destroy value. This most directly illustrates a conflict between:',[
 ['managerial private benefits and the interests of the company’s investors.','Persönlicher Nutzen kann von produktiver Kapitalverwendung abweichen.'],['identical preferences automatically shared by all stakeholders.','Die Fallbeschreibung nennt gerade einen Gegensatz.'],['a supplier’s fixed invoice and its due date.','Der konkrete Auslöser ist der private Größenanreiz der Führung.']
 ],['Nicht jede große Akquisition ist schlecht. Ausschlaggebend ist hier der ausdrücklich genannte private Beweggrund bei erwarteter Wertvernichtung.','Überwachung und angemessene Anreize sollen Entscheidungen an nachvollziehbare Unternehmensziele binden.'],'stakeholder-map'),
 q('13','practice','b','A controlling shareholder causes the company to buy an asset from a separately owned business at a price above its fair value. The most direct concern for minority shareholders is:',[
 ['a transfer of company value to the controller through a related transaction.','Der Mehrheitsaktionär kann außerhalb der Gesellschaft profitieren, während alle Aktionäre den überhöhten Preis tragen.'],['automatic equal benefit to every shareholder from the controller’s outside business.','Minderheiten besitzen nicht automatisch denselben Anspruch an der Verkäufergesellschaft.'],['elimination of conflicts because the transaction was directed by an owner.','Eigentümer können unterschiedliche zusätzliche Beziehungen und Interessen haben.']
 ],['Eigentümer und Management sind nicht die einzigen möglichen Konfliktparteien. Auch Mehrheit und Minderheit können gegensätzliche Interessen haben.','Entscheidend sind wirtschaftliche Rechte, Kontrolle und der Empfänger des Vorteils.'],'horizons'),
 q('14','practice','b','Employees may prefer lower firm-specific risk than a widely diversified shareholder primarily because employees often:',[
 ['have labor income and specialized skills concentrated in the same firm.','Ein Arbeitsplatzverlust kann zugleich Einkommen und Wert firmenspezifischer Erfahrung betreffen.'],['receive all interest and principal before every creditor.','Eine solche universelle Rangregel wird weder durch Beschäftigung noch durch den Fall begründet.'],['can diversify all career risks as easily as trading small portfolio positions.','Arbeits- und Wissensbindungen sind oft weniger flexibel als breit verteilte Wertpapieranlagen.']
 ],['Unterschiedliche Konzentration erklärt Präferenzen ohne eine Gruppe als grundsätzlich irrational zu behandeln. Mitarbeiter können zusätzlich Aktien besitzen und damit noch stärker konzentriert sein.','Das tatsächliche Ausmaß hängt von Qualifikation, Arbeitsmarkt und persönlichen Umständen ab.'],'horizons'),
 q('15','practice','b','A buyer negotiates a 30-day extension of an unchanged supplier invoice. Before considering any secondary effects, this most directly:',[
 ['shifts financing toward the supplier while improving the buyer’s temporary liquidity.','Der Käufer behält das Geld länger, der Lieferant wartet entsprechend länger.'],['creates an equal permanent increase in productivity for both firms.','Eine reine Zahlungsverschiebung verbessert nicht automatisch die Ressourcennutzung.'],['increases the agreed invoice amount by 30%.','Zeitverlängerung und Preisänderung sind verschiedene Vertragsgrößen.']
 ],['Die erste Wirkung ist eine Verschiebung des Zahlungszeitpunkts. Danach werden Finanzierungskosten, Preisreaktionen und Lieferfähigkeit geprüft.','Eine bessere Käuferkennzahl kann mit einem schlechteren Zustand beim Geschäftspartner einhergehen.'],'tradeoffs'),
 q('16','practice','b c','A production process imposes costs on nearby residents that the producer does not fully bear. This most directly represents:',[
 ['a negative externality that may later also become financially relevant to the producer.','Die externe Belastung und ihre mögliche spätere Internalisierung sind getrennte Schritte.'],['proof that the producer already pays the full social cost.','Das widerspricht der Fallvoraussetzung.'],['a guaranteed immediate increase in every shareholder’s required return by the same amount.','Art, Zeitpunkt und Bewertung der finanziellen Rückwirkung müssen erst untersucht werden.']
 ],['Private Kostenrechnung und gesellschaftliche Wirkung können auseinanderfallen. Regeln, Haftung, Nachfrage oder Ressourcenknappheit können einen Teil später in private Kosten übersetzen.','Auch wenn noch keine finanzielle Rückwirkung vorliegt, ist die Belastung der Betroffenen damit nicht verschwunden.'],'tradeoffs'),
 q('17','practice','b','A manager’s bonus depends solely on this year’s earnings. Cutting valuable employee training would raise current earnings but damage expected future cash flows. The most relevant concern is:',[
 ['a mismatch between the reward horizon and the economic effect of the decision.','Der Bonus kann heutige sichtbare Gewinne gegenüber späterem wirtschaftlichem Nutzen bevorzugen.'],['that every reduction in training must increase long-term value.','Der Fall setzt gerade eine schädliche zukünftige Wirkung voraus.'],['that calling a project long term removes the need to monitor it.','Langfristigkeit ersetzt keine überprüfbaren Ziele oder Fortschrittskontrolle.']
 ],['Zahlungs- und Leistungshorizonte müssen mit der Entscheidung zusammenpassen. Eine reine Einjahreskennzahl kann sonst sinnvolle Ausgaben verdrängen.','Auch längerfristige Vergütung braucht geeignete Messgrößen und Schutz vor Manipulation.'],'horizons'),
 q('18','practice','b','Relative to a shareholder-centered framework, stakeholder theory most directly broadens attention to:',[
 ['the legitimate interests of groups affected by or able to affect the firm.','Die Perspektive umfasst beispielsweise Beschäftigte, Kunden, Lieferanten und Gemeinschaften.'],['a rule that every group must receive exactly the same cash payment.','Breitere Berücksichtigung verlangt keine identischen Ansprüche oder Zahlungen.'],['the elimination of all trade-offs between interested groups.','Tatsächliche Konflikte bleiben und müssen analysiert werden.']
 ],['Breitere Verantwortung und eine konkrete Verteilungsregel sind unterschiedliche Dinge. Langfristiger Wert kann gute Beziehungen voraussetzen, trotzdem bleiben echte Abwägungen.','Die verwendete Stakeholderdefinition sollte erkennen lassen, ob Kapitalgeber eingeschlossen sind.'],'tradeoffs'),
 q('19','practice','c','A factory faces increasingly frequent flooding that interrupts production. This is most directly a:',[
 ['physical climate risk.','Der Schaden entsteht durch ein physisches Ereignis am Standort.'],['transition risk arising solely from a change in carbon-pricing policy.','Ein Politikwechsel ist nicht der hier beschriebene Auslöser.'],['governance opportunity that necessarily increases profit.','Die Fallbeschreibung enthält Produktionsunterbrechung, keine garantierte Chance.']
 ],['Akute physische Risiken umfassen etwa Überschwemmungsereignisse; chronische Veränderungen können Wasserverfügbarkeit oder Hitze betreffen.','Das Unternehmen kann zugleich Übergangsrisiken besitzen, doch dieser konkrete Mechanismus ist physisch.'],'climate'),
 q('20','practice','c','Customers switch from a company’s emissions-intensive technology to a lower-emission substitute. The resulting demand pressure is best classified as:',[
 ['a transition risk linked to technological and market change.','Die wirtschaftliche Umstellung verändert Nachfrage und Wettbewerbsposition.'],['only an acute physical event at the factory.','Es wurde kein physischer Schadensfall genannt.'],['proof that all low-emission competitors are attractive at any stock price.','Eine Geschäftschance ist kein Bewertungsurteil unabhängig vom Einstiegspreis.']
 ],['Übergangsrisiken sind nicht auf eine staatliche Steuer begrenzt. Technologie, Kundenpräferenzen und Haftung können ebenfalls wirken.','Der Analyst übersetzt den Nachfragewechsel in Absatz, Marge, Anpassungsbedarf und Szenarien.'],'climate'),
 q('21','practice','c','Annual chargeable emissions remain at 80,000 tonnes. A hypothetical cash carbon charge rises by €20 per tonne. The firm can recover 30% through higher revenue without volume loss, and the remaining expense immediately reduces tax at 25%. The annual after-tax cash-flow reduction is:',[
 ['€840,000','1,6 Mio. Mehrkosten mal 70 % Restbelastung mal 75 % nach Steuer.'],['€1,600,000','Dies ignoriert Weitergabe und Steuerwirkung.'],['€360,000','Dies verwendet die weitergegebene statt der verbleibenden Belastung.']
 ],[F('L_{CF}=80000\\cdot20(1-0{,}30)(1-0{,}25)=840000','Kostenmenge, Weitergabefähigkeit und Steuerbasis werden nacheinander verarbeitet.',[['L_{CF}','Betrag der jährlichen Cashflowminderung in Euro.']]),'Die Rechnung gilt unter den ausdrücklich vorgegebenen konstanten Mengen und sofort nutzbaren Steuerwirkungen. Reale Elastizität oder fehlende Steuernutzbarkeit würden sie ändern.'],'climate'),
 q('22','practice','c','A protective measure reduces the annual probability of a €20 million loss from 12% to 5% and costs €0.6 million per year. Ignore taxes, initial costs, and all other effects. The expected annual net cash benefit in millions is:',[
 ['0.8','Vermiedener erwarteter Schaden 1,4 abzüglich jährlicher Kosten 0,6.'],['1.4','Dies ist der Nutzen vor den Schutzkosten.'],['2.4','Dies ist der ursprüngliche erwartete Schaden, der nicht vollständig entfällt.']
 ],[F('\\Delta CF=(0{,}12-0{,}05)\\cdot20-0{,}6=0{,}8','Die Wahrscheinlichkeit sinkt um sieben Prozentpunkte, nicht auf null.',[['\\Delta CF','Erwarteter jährlicher Nettovorteil in Millionen Euro.']]),'Der verbleibende große Schaden ist weiterhin möglich. Erwartungswert, Liquiditätsbedarf im Schadenfall und Extremrisiko sind getrennte Größen.'],'climate'),
 q('23','practice','c','A project costs €3.5 million today and saves charges on 20,000 tonnes per year for four years. The charge is €90 per tonne, savings are taxed immediately at 25%, and the discount rate is 8%. Savings arrive at each year-end. There are no other cash flows or tax effects. NPV in millions is closest to:',[
 ['0.971','Jährlich 1,35 Mio. nach Steuer mal Vierjahresbarwertfaktor 3,31213 minus 3,5 Mio. Einsatz.'],['1.900','Dies addiert vier nominale Zahlungen und ignoriert den Zeitwert.'],['4.471','Dies ist der Barwert der Ersparnisse vor Abzug des Einsatzes.']
 ],[F('NPV=-3{,}5+1{,}35\\sum_{t=1}^{4}(1{,}08)^{-t}\\approx0{,}971','Geldeinheit Millionen; der Anfangseinsatz wird nicht nochmals abgezinst.',[['NPV','Kapitalwert in Millionen Euro.'],['t','Jahr der Zahlung eins bis vier.']]),'Technische Einsparung, Steuer, Laufzeit und Preis müssen zusammenpassen. Der positive Modellwert ist kein garantierter realer Ertrag bei anderen Annahmen.'],'transition-investment'),
 q('24','practice','c','A proposed environmental investment has a negative financial NPV under the analyst’s stated cash-flow assumptions. The most appropriate conclusion is that:',[
 ['the modeled financial benefits do not cover the investment cost, while wider impacts or different justified assumptions require separate analysis.','Finanzieller Kapitalwert und gesamter gesellschaftlicher Nutzen beantworten verschiedene Fragen.'],['the project cannot possibly reduce emissions.','Ein technischer Umwelteffekt wird durch negativen finanziellen Kapitalwert nicht widerlegt.'],['the NPV must be changed to positive solely because the project is labeled green.','Ein Etikett ersetzt keine belastbaren Zahlungsannahmen.']
 ],['Zunächst wird die finanzielle Rechnung unter den angegebenen Annahmen beurteilt. Danach können etwa Pflichten, andere Wirkungen oder dokumentierte Szenarien die Entscheidung beeinflussen.','Die Zahlen dürfen nicht allein zur gewünschten Etikettierung angepasst werden.'],'transition-investment'),
 q('25','practice','b c','An annual staff program costs €350,000. It reduces annual replacement hires from 150 to 100, each costing €4,000, and separately avoids €250,000 of scrap. Ignore taxes, initial costs, and overlaps. The annual net cash benefit is:',[
 ['€100,000','200.000 vermiedene Ersatzkosten plus 250.000 Ausschussersparnis minus 350.000 Programmkosten.'],['€450,000','Dies ist der Bruttonutzen vor Programmkosten.'],['€250,000','Dies berücksichtigt nur einen der beiden Nutzenkanäle und keinen vollständigen Saldo.']
 ],[F('\\Delta CF=(150-100)\\cdot4000+250000-350000=100000','Die Mengenänderung wird mit Kosten je Ersatzfall multipliziert.',[['\\Delta CF','Jährlicher Nettovorteil in Euro.']]),'Die Ersparnisse müssen eigenständig belegt und ohne Überschneidung abgegrenzt sein. Eine bloße Korrelation zwischen Programmstart und besseren Kennzahlen beweist noch keine Ursache.'],'social-governance'),
 q('26','practice','c','When assessing financially material ESG factors across a water-intensive manufacturer and a software firm, an analyst should most appropriately:',[
 ['investigate their distinct business models, locations, exposures, and time horizons.','Wesentlichkeit hängt von konkreten Wirkungsketten ab.'],['assign every environmental and social metric exactly the same importance to both.','Ein universelles Gewicht kann die tatsächliche wirtschaftliche Exposition verdecken.'],['ignore factors not already recorded as a liability in the latest balance sheet.','Zukünftige Risiken und Chancen können relevant sein, bevor ein Bilanzansatz entsteht.']
 ],['Wasserverfügbarkeit kann Produktion unmittelbar begrenzen; Datenkontrolle und Personalbindung können für ein anderes Modell besonders wichtig sein. Das sind Analysehypothesen, keine abschließenden Pauschalurteile.','Standort- und firmenspezifische Daten entscheiden über Stärke, Zeitpunkt und Unsicherheit der Wirkung.'],'esg-channels'),
 q('27','practice','c','Two ESG rating providers assign materially different ratings to the same issuer. The analyst should first:',[
 ['compare scope, weighting, peer groups, sources, estimation, and update dates.','Methodikunterschiede können ein abweichendes Ergebnis erklären.'],['conclude that one provider has necessarily committed fraud.','Eine Abweichung allein beweist keine absichtliche Täuschung.'],['treat the higher rating as a guarantee of higher future stock returns.','Rating und erwartete Rendite bei einem gegebenen Preis sind verschiedene Aussagen.']
 ],['Ein Rating fasst eine bestimmte Methodik zusammen. Relative Branchennoten, absolute Wirkungen und finanzielle Risikoexposition können unterschiedlich gewichtet sein.','Der Analyst nutzt die Unterschiede zur vertieften Prüfung der zugrunde liegenden Daten.'],'measurement'),
 q('28','practice','c','Emissions rise from 150,000 to 165,000 tonnes while revenue rises from €200 million to €250 million. Reporting boundaries are unchanged. The percentage change in emissions per million euros of revenue is:',[
 ['−12%','Die Intensität sinkt von 750 auf 660 Tonnen je Mio. Euro.'],['10%','Dies ist die Zunahme absoluter Emissionen.'],['25%','Dies ist die Umsatzsteigerung.']
 ],[F('g_I=\\frac{165000/250}{150000/200}-1=-12\\%','Erst werden beide Intensitäten auf gleicher Basis ermittelt.',[['g_I','Relative Änderung der Emissionsintensität.']]),'Gleichzeitig steigen absolute Emissionen um zehn Prozent. Eine bessere relative Kennzahl beweist deshalb keine geringere Gesamtbelastung.'],'measurement'),
 q('29','practice','c','A company advertises a large reduction in emissions intensity but omits that total emissions rose and that a major operation was excluded from the measurement boundary. The most appropriate analytical action is to:',[
 ['reconcile absolute and relative measures and the reporting boundary before accepting the claim.','Der Analyst prüft, was tatsächlich verglichen wurde und ob wesentliche Informationen fehlen.'],['accept the claim because intensity and total emissions are identical measures.','Zähler-Nenner-Kennzahl und absolute Menge sind nicht identisch.'],['assume every target announced by management has already been achieved.','Ziel, Maßnahme und tatsächliche Wirkung sind getrennte Nachweise.']
 ],['Selektive oder irreführende Darstellung kann Greenwashing darstellen. Der konkrete Befund wird anhand von Daten, Abgrenzungen und Vergleichsperioden untersucht.','Eine schlechtere Kennzahl allein wäre umgekehrt noch kein Beweis vorsätzlicher Täuschung.'],'measurement'),
 q('30','practice','c','An analyst has already reduced expected cash flows by the estimated expected loss from a specific environmental event. The analyst proposes subtracting the same expected loss again from the resulting value. This would most likely:',[
 ['double count the same expected loss.','Der wirtschaftlich identische Betrag würde zweimal belasten.'],['be necessary whenever the event has an ESG label.','Die Bezeichnung schafft keine zweite unabhängige wirtschaftliche Wirkung.'],['eliminate the need to analyze risk or uncertainty.','Risikoanalyse bleibt auch bei korrekter Erwartungswertrechnung erforderlich.']
 ],['Cashflow, Risiko und Bewertung müssen konsistent sein. Eine begründete Änderung der Risikoprämie kann neben veränderten erwarteten Zahlungen sinnvoll sein, braucht aber eine eigene Grundlage.','Eine zweite pauschale Kürzung desselben erwarteten Betrags ist keine solche Grundlage.'],'valuation'),
 q('31','practice','a c','A long-dated lender assesses an environmental issue that may reduce company cash flows. Which step is most appropriate?',[
 ['Trace the issue through cash flows, debt service, asset coverage, and the specific loan terms.','Die Wirkung muss bis zum tatsächlich gehaltenen Anspruch verfolgt werden.'],['Apply the same absolute loss to debt and equity regardless of the payment waterfall.','Die Rangfolge kann Verluste unterschiedlich verteilen.'],['Ignore the issue whenever it is not classified as a traditional accounting ratio.','Der wirtschaftliche Übertragungsweg ist relevanter als das Etikett der Information.']
 ],['Ein geringerer Unternehmensbetrag kann zunächst Eigenkapitalpuffer reduzieren und in schlechteren Szenarien auch Kreditausfall erzeugen. Laufzeit, Sicherheit und Rang verändern diese Wirkung.','Szenarien helfen, die Grenze zwischen geringerer Aktienzahlung und schlechterer Schulddeckung zu erkennen.'],'valuation'),
 q('32','practice','c','An investor seeks measurable positive environmental impact. Another investor uses ESG information only to improve financial risk analysis. These approaches:',[
 ['have different objectives that require explicit mandates and suitable evidence.','Wirkungsziel und finanzielle Risikoanalyse können sich ergänzen, sind aber nicht identisch.'],['must produce identical portfolios because both mention ESG.','Ein gemeinsames Kürzel legt weder Anlageziel noch Auswahlregel fest.'],['allow investment prices and financial constraints to be ignored automatically.','Die tatsächlichen Ziele und Grenzen des Mandats bleiben maßgeblich.']
 ],['Eine positive Unternehmenswirkung beweist weder automatisch eine zusätzliche Wirkung des konkreten Investments noch eine attraktive Rendite zum aktuellen Preis.','Die Analyse benennt deshalb, ob sie Risiken, Wertepräferenzen, messbare Wirkung oder eine begründete Kombination beurteilt.'],'esg-channels'),
 q('a1','mock-a','a b','An existing debt claim is fixed at 100. The firm can retain a strategy producing 120 for certain or switch to one producing 70 with 60% probability and 180 otherwise. No resources, costs, intermediate payments, or debt terms change. The reduction in expected debt end payments from switching is:',[
 ['18','Die alte Schuldzahlung 100 fällt im Erwartungswert auf 0,6 mal 70 plus 0,4 mal 100, also 82.'],['12','Dies ist der Zuwachs der erwarteten Aktienzahlung von 20 auf 32.'],['6','Dies ist die Verminderung des erwarteten Gesamtbetrags von 120 auf 114.']
 ],[F('L_B=100-(0{,}6\\cdot70+0{,}4\\cdot100)=18','Die vertragliche Obergrenze wird vor der Gewichtung auf jeden Zustand angewendet.',[['L_B','Verminderung der erwarteten Gläubigerendzahlung.']]),'Aktionäre gewinnen zwölf, Gläubiger verlieren 18; zusammen sinkt der erwartete Gesamtbetrag um sechs. Die Frage betrifft erwartete Endzahlungen, nicht heutige Marktpreise.'],'risk-shifting'),
 q('b1','mock-b','b c','A manufacturer’s expected annual cash loss from water interruptions is already included in its forecast. Management proposes a project that lowers that expected loss by €1.2 million, costs €0.5 million each year, and requires €2 million today. Assume four year-end benefits, an 8% discount rate, no taxes or other effects, and no terminal value. The project NPV in millions is closest to:',[
 ['0.318','Jährlicher inkrementeller Vorteil 0,7 Mio. mal Faktor 3,31213 minus zwei Mio. Einsatz.'],['1.975','Dies lässt die jährlichen Betriebskosten des Schutzprojekts weg.'],['0.800','Dies addiert nominale Nettovorteile ohne Abzinsung.']
 ],[F('NPV=-2+(1{,}2-0{,}5)\\sum_{t=1}^{4}(1{,}08)^{-t}\\approx0{,}318','Bewertet werden nur Änderungen gegenüber der bereits belasteten Ausgangsprognose.',[['NPV','Kapitalwert in Millionen Euro.'],['t','Jahr des jeweiligen Nettozuflusses.']]),'Die vorhandene Verlustprognose wird nicht zusätzlich noch einmal abgezogen. Die Maßnahme kann Betrieb und Stakeholder schützen; ihre finanzielle Bewertung benötigt trotzdem Einsatz, laufende Kosten und Zeitwert.'],'valuation')
];
