const {Q,F}=require('../author.cjs');
const q=(id,los,stem,options,solution,section)=>Q('ra-'+id,'ratios','statements','practice',los,stem,options,0,solution,{section});
module.exports=[
 q('11','a','Over a comparable period, revenue rises from 200 to 260 and the representative asset base rises from 120 to 180. With both initial values indexed to 100, which statement is most accurate?',[
 ['The asset index exceeds the revenue index, consistent with lower asset turnover.','Aktivaindex 150 übersteigt Umsatzindex 130; jeder Vermögenseuro trägt weniger Umsatz.'],['Both indexes rise by 60 because the absolute increases are equal.','Ein Index misst relative Änderung zum jeweiligen Ausgangswert.'],['Revenue growing proves that asset turnover rises.','Der Nenner wächst hier relativ schneller als der Zähler.']
 ],[F('S^{idx}=100\\frac{260}{200}=130,\\qquad A^{idx}=100\\frac{180}{120}=150','Gleiche absolute Änderungen können unterschiedliche relative Veränderungen bedeuten.',[['S^{idx},A^{idx}','Umsatz- und Aktivaindex, jeweils eigene Basis 100.']]),'Umschlag sinkt von 200/120 ≈ 1,667 auf 260/180 ≈ 1,444. Ursachen könnten ungenutzte Kapazität oder ein noch anlaufender Ausbau sein.'],'methods'),
 q('12','a','Net income changes from a loss of 20 to a loss of 5. The usual change-relative-to-base calculation gives −75%. The most appropriate interpretation is:',[
 ['The loss has narrowed by 15; the negative-base percentage needs explicit explanation.','Der gewöhnliche Wachstumswortlaut würde hier die Richtung der Verbesserung verschleiern.'],['Profitability necessarily deteriorated because the computed growth rate is negative.','Der Verlustbetrag wird kleiner; das negative Vorzeichen des Ausgangswerts verändert die Prozentinterpretation.'],['The company has become profitable because the loss fell 75%.','Ein Verlust von 5 bleibt ein negatives Ergebnis.']
 ],['Veränderung und Ausgangsniveau getrennt berichten: Ergebnisverbesserung um 15, Verlustbetrag um 75 % geringer, aber weiterhin Verlust.','Bei null als Ausgangswert ist diese Wachstumsquote sogar undefiniert. Ein Trendindex löst das Problem einer negativen oder verschwindenden Bezugsbasis nicht.'],'methods'),
 q('13','a','A seasonal retailer has very low inventory at both the opening and closing reporting dates but high inventory through most of the year. For annual inventory turnover, the most suitable denominator is:',[
 ['a representative time-weighted average, using more frequent inventory observations.','Die tatsächlich über das Jahr gebundene Warenmenge muss zum Jahresverbrauch passen.'],['the average of the two low reporting-date balances regardless of seasonality.','Zwei untypisch niedrige Stichtage würden den Bestand unterschätzen und den Umschlag überschätzen.'],['the maximum observed inventory balance in every case.','Der Spitzenbestand ist ebenfalls kein zeitlich repräsentativer Durchschnitt.']
 ],['Monats- oder Quartalsbeobachtungen können die Saison besser erfassen. Besonders schwankende Bestände können noch häufigere Messungen erfordern.','Die gleiche Frage betrifft Forderungen, Aktiva und Eigenkapital, wenn Periodenströme zu Beständen ins Verhältnis gesetzt werden.'],'methods'),
 q('14','b','A company has days sales outstanding of 30, days inventory outstanding of 50, and days payable outstanding of 65. Its cash conversion cycle is:',[
 ['15 days','Die operative Bindung von 80 Tagen wird um 65 Tage Lieferantenfinanzierung verkürzt.'],['80 days','Dies ist der Operating Cycle vor Abzug der Lieferantenfinanzierung.'],['145 days','Verbindlichkeitstage werden abgezogen, nicht hinzugezählt.']
 ],[F('CCC=50+30-65=15','Die drei Phasen beschreiben Lagerung, Kundenzahlung und eigenen Zahlungsaufschub.',[['CCC','Cash Conversion Cycle in Tagen.']]),'Die Durchschnittsgröße bildet weder jeden einzelnen Auftrag noch sämtliche Kreditfälligkeiten ab.'],'activity'),
 q('15','b','Net income is 90 and preferred dividends attributable to the period are 10. Average common equity is 400 and average total equity including preferred equity is 500. Return on common equity is:',[
 ['20.0%','Für Stammaktionäre verfügbar sind 80; deren Kapitalbasis beträgt 400.'],['18.0%','90/500 ist die Gesamteigenkapitalrendite in der angegebenen Definition.'],['22.5%','90/400 ordnet den Stammaktionären auch den Vorranganspruch zu.']
 ],[F('ROCE=\\frac{90-10}{400}=20\\%','Ergebnisanspruch und Kapitalbasis müssen denselben Eigentümerkreis betreffen.',[['ROCE','Return on Common Equity; hier ausdrücklich nicht Return on Capital Employed.']])],'additional-ratios'),
 q('16','b','EBIT is 80, net income is 42, and average total assets are 500. Using EBIT in the numerator, operating return on assets is:',[
 ['16.0%','Operative ROA verwendet hier 80/500.'],['8.4%','42/500 ist die Nettogewinn-ROA, eine andere ausdrücklich abzugrenzende Kennzahl.'],['52.5%','42/80 misst den Anteil des Nettogewinns am EBIT, keine Rendite auf Aktiva.']
 ],[F('ROA_{op}=\\frac{80}{500}=16\\%','Die operative Größe isoliert die angegebene Ergebnisstufe vor Finanzierung und Steuer.',[['ROA_{op}','Operative Rendite auf durchschnittliche Gesamtaktiva.']]),'Beide ROA-Konventionen können vorkommen. Ein Vergleich ohne dokumentierte Zählerdefinition ist irreführend.'],'additional-ratios'),
 q('17','b','EBIT of 120 is after deducting a fixed rental expense of 30. Interest expense is 20. Use the convention that adds rent back to EBIT and includes both rent and interest as fixed charges. Fixed charge coverage is:',[
 ['3.0','Vor beiden fixen Belastungen stehen 150 zur Deckung von insgesamt 50 zur Verfügung.'],['2.4','120/50 zählt die Miete im Nenner, ohne sie aus dem EBIT-Abzug zurückzunehmen.'],['6.0','120/20 ist nur die Zinsdeckung.']
 ],[F('FCCR=\\frac{120+30}{20+30}=3','Miete wird zuerst zum Ergebnis zurückaddiert und dann gemeinsam mit Zins gedeckt.',[['FCCR','Fixed Charge Coverage nach der angegebenen Formel.']]),'Bei aktivierten Leasingverträgen dürfen anders erfasste Zins- und Abschreibungskomponenten nicht nochmals wie derselbe Mietaufwand behandelt werden.'],'solvency'),
 q('18','b','Annual sales are 600. Average current assets are 200 and average current liabilities are 100. Using net working capital defined as current assets minus current liabilities, working capital turnover is:',[
 ['6.0','600 Umsatz stehen durchschnittlich 100 Nettoumlaufvermögen gegenüber.'],['3.0','Dieser Wert verwendet das gesamte Umlaufvermögen und lässt dessen kurzfristige Finanzierung weg.'],['2.0','Dieser Wert addiert die beiden Bilanzseiten statt ihre Differenz zu verwenden.']
 ],[F('WCT=\\frac{600}{200-100}=6','Zähler ist Jahresumsatz, Nenner die konsistent definierte durchschnittliche Kapitalbindung.',[['WCT','Working Capital Turnover pro Jahr.']]),'Bei sehr kleinem oder negativem Nettoumlaufvermögen kann die Quote instabil oder schwer interpretierbar werden.'],'additional-ratios'),
 q('19','b','Revenue is 840 and average net property, plant, and equipment is 210. Fixed asset turnover is:',[
 ['4.0','840 Jahresumsatz je 210 durchschnittlichem Nettosachanlagenbestand.'],['25.0%','Dies ist der Kehrwert der verlangten Umschlagskennzahl.'],['0.4','Dies verschiebt die Größenordnung um den Faktor zehn.']
 ],[F('FAT=\\frac{840}{210}=4','Der Anlagebestand wird in dieser Kennzahl viermal durch den Jahresumsatz repräsentiert.',[['FAT','Fixed Asset Turnover pro Jahr.']]),'Ein alter, weitgehend abgeschriebener Anlagenbestand kann eine hohe Quote erzeugen. Daraus folgt nicht automatisch technische Überlegenheit.'],'additional-ratios'),
 q('20','b c','Inventory turnover increases sharply while stockouts, emergency shipping costs, and lost sales also increase. The most defensible conclusion is:',[
 ['the higher turnover may reflect insufficient inventory rather than an unqualified efficiency improvement.','Die ergänzenden Beobachtungen zeigen Kosten einer zu kleinen Warenreserve.'],['higher turnover always proves stronger operating performance.','Die Quote misst nicht die Kosten entgangener Aufträge und Notlieferungen.'],['inventory turnover is unrelated to the inventory balance.','Bei gegebenen Umsatzkosten steigt Umschlag gerade mit einem kleineren durchschnittlichen Bestand.']
 ],['Ein Lagerabbau setzt Kapital frei, kann aber Lieferfähigkeit und Margen verschlechtern. Für eine Gesamtbeurteilung werden diese Effekte gemeinsam betrachtet.','Kennzahlen helfen, einen Zielkonflikt sichtbar zu machen; sie ersetzen nicht die wirtschaftliche Bewertung beider Seiten.'],'activity'),
 q('21','c d','Firm A has net margin 8%, asset turnover 1.5, and leverage 2. Firm B has net margin 4%, asset turnover 2, and leverage 3. The most accurate conclusion is:',[
 ['Both have 24% ROE, produced by different operating and financing combinations.','A: 0,08 × 1,5 × 2; B: 0,04 × 2 × 3.'],['Firm A has twice the ROE because its net margin is twice as high.','Die anderen beiden Faktoren unterscheiden sich ebenfalls.'],['Firm B’s higher leverage proves it has the same risk as Firm A.','Gleiches ROE bedeutet keine gleichen operativen oder finanziellen Risiken.']
 ],[F('ROE_A=0{,}08\\cdot1{,}5\\cdot2=24\\%,\\quad ROE_B=0{,}04\\cdot2\\cdot3=24\\%','Eine Ergebnisquote kann aus verschiedenen Geschäftsmodellen entstehen.',[['ROE_A,ROE_B','Eigenkapitalrendite der Unternehmen A und B.']]),'Prüfe zusätzlich Schwankungen der Margen, Vermögensqualität, Zinsdeckung und Fälligkeiten. Gleiche Endwerte sind keine ausreichende Grundlage für Gleichwertigkeit.'],'dupont'),
 q('22','c d','A company has net income of −10 and average equity of −50. Its arithmetic ROE is 20%. The most appropriate interpretation is:',[
 ['the positive quotient does not establish profitability because both the earnings and equity base are negative.','Zwei negative Größen erzeugen mathematisch einen positiven Bruch.'],['the firm necessarily earned a healthy 20% return for its owners.','Ein Verlust und negatives Buchkapital tragen diese wirtschaftliche Schlussfolgerung nicht.'],['ROE is mathematically undefined whenever equity is negative.','Undefiniert wäre ein Nullnenner; ein negativer Nenner ist berechenbar, aber problematisch zu deuten.']
 ],['Die Rechenoperation ist gültig, die übliche Interpretation einer Rendite auf positives Eigentümerkapital ist es nicht.','Analysiere Verlustursachen, Vermögenswerte, Verpflichtungen und Finanzierung gesondert. Eine Rangliste nach dem positiven ROE allein würde den Problemfall möglicherweise fälschlich belohnen.'],'solvency'),
 q('23','d','Net margin changes from 5% to 6%, asset turnover from 1.5 to 1.4, and leverage from 2 to 2.5. A sequential ROE bridge changes margin first, turnover second, and leverage last. The contribution of the final leverage step is:',[
 ['4.2 percentage points','Die letzte Änderung wirkt auf bereits neue Marge und neuen Umschlag: 0,06 × 1,4 × 0,5.'],['3.75 percentage points','Dies verwendet alte Marge und alten Umschlag für den letzten Schritt.'],['6.0 percentage points','Dies ist die gesamte ROE-Veränderung von 15 % auf 21 %, nicht allein der letzte Schritt.']
 ],[F('\\Delta ROE_{FL}=0{,}06\\cdot1{,}4(2{,}5-2)=4{,}2\\%','Die Prozentzahl ist hier eine additive Differenz der Rendite, also 4,2 Prozentpunkte.',[['\\Delta ROE_{FL}','ROE-Beitrag des Hebelschritts in der ausdrücklich gewählten Reihenfolge.']]),'Die Einzelzuordnung hängt von der Reihenfolge ab. Die Summe aller konsistenten Schritte bleibt die beobachtete Gesamtänderung.'],'ratio-bridge'),
 q('24','e','A bank has interest income of 240 and interest expense of 100. Average interest-earning assets are 4,000; average total assets are 5,000. Net interest margin on interest-earning assets is:',[
 ['3.5%','Nettozinsertrag 140 wird auf die geeignete durchschnittliche Basis 4.000 bezogen.'],['2.8%','Dies verwendet Gesamtaktiva statt der gefragten zinstragenden Aktiva.'],['6.0%','Dies lässt den Zinsaufwand aus dem Ergebnisbaustein weg.']
 ],[F('NIM=\\frac{240-100}{4000}=3{,}5\\%','Ertragsüberschuss und Ertragsbasis müssen zusammenpassen.',[['NIM','Net Interest Margin.']]),'Kreditverluste und Betriebsaufwand werden in diesem Ergebnisbaustein noch nicht abgezogen.'],'industry-cases'),
 q('25','e','For a simplified insurer analysis, claims of 330 and underwriting expenses of 140 are both divided by the same earned-premium base of 500. There are no other underwriting items. The combined ratio and underwriting profit are:',[
 ['94% and 30.','(330 + 140)/500 = 94 %; 500 − 330 − 140 = 30.'],['66% and 170.','Dies berücksichtigt nur Schäden und lässt Betriebskosten aus.'],['106% and −30.','Dies vertauscht den Überschuss mit einem Fehlbetrag.']
 ],[F('CR_{ins}=\\frac{330+140}{500}=94\\%,\\qquad U=500-330-140=30','Die gemeinsame Prämienbasis macht die vereinfachte Rechnung additiv.',[['CR_{ins}','Combined Ratio des Versicherers in dieser Definition.'],['U','Zeichnungsergebnis in der angegebenen Geldeinheit.']]),'Kapitalanlageergebnis und Steuer fehlen noch. Im tatsächlichen Bericht ist insbesondere eine abweichende Prämienbasis der Kostenquote zu prüfen.'],'industry-cases'),
 q('26','e','A property has 100 identical rentable units. Occupancy falls from 95% to 90%, while average monthly rent per occupied unit rises from 1,000 to 1,100. Ignore incentives, collection losses, and other income. Monthly rental revenue:',[
 ['rises from 95,000 to 99,000 despite lower occupancy.','Mietpreis und belegte Einheiten wirken gemeinsam auf den Ertrag.'],['falls by 5% because occupancy falls by five percentage points.','Dies verwechselt Prozentpunkte mit einer relativen Änderung und ignoriert die höhere Miete.'],['rises 10% because rent per occupied unit rises 10%.','Die kleinere belegte Menge wird dabei ausgelassen.']
 ],[F('S_0=100\\cdot0{,}95\\cdot1000=95000,\\quad S_1=100\\cdot0{,}90\\cdot1100=99000','Auslastung allein ist keine vollständige Umsatzprognose.',[['S_0,S_1','Monatlicher Mietumsatz vor und nach der Änderung.']]),'Für das Betriebsergebnis fehlen außerdem Objektkosten. Bei unterschiedlichen Einheiten ist eine gewichtete Flächen- oder Erlösbetrachtung geeigneter.'],'industry-cases'),
 q('27','e','A bank reports a higher net interest margin after shifting toward riskier loans. Credit-loss expense also rises substantially. Which conclusion is most justified?',[
 ['The margin improvement must be assessed together with credit losses, funding, and capital needs.','Höherer Zins kann lediglich höheres Kreditrisiko vergüten.'],['Higher net interest margin alone proves higher risk-adjusted profitability.','Die Kennzahl enthält die zusätzlich beschriebenen Kreditausfälle noch nicht.'],['Credit losses are irrelevant because they are not part of the net interest margin formula.','Eine Größe außerhalb einer Einzelkennzahl kann für die Gesamtbeurteilung wesentlich sein.']
 ],['Branchenkennzahlen fokussieren einen Teil des Geschäftsmodells. Diese Fokussierung ist nützlich, solange ausgelassene Risiken anschließend ergänzt werden.','Zinsmarge, Kreditkosten und eingesetztes Eigenkapital müssen für eine Aussage über nachhaltige Eigentümerrendite zusammengeführt werden.'],'industry-cases'),
 q('28','f','A model forecasts revenue of 1,200, an EBIT margin of 15%, interest expense of 30, and tax at 25% of positive pretax income. There are no other items. Forecast net income is:',[
 ['112.5','Operativer Gewinn 180, Vorsteuergewinn 150, Steuer 37,5.'],['135.0','Dies versteuert EBIT und vergisst den Zinsaufwand.'],['105.0','Dies versteuert zunächst EBIT und zieht den Zins danach vollständig ab, ohne dessen gegebenen Steuereffekt.']
 ],[F('NI=(1200\\cdot0{,}15-30)(1-0{,}25)=112{,}5','Eine prognostizierte Marge muss zur richtigen Ergebnisstufe gehören.',[['NI','Prognostizierter Nettogewinn.']]),'15 % als Nettomarge zu behandeln und 180 auszuweisen wäre ein weiterer Stufenfehler.'],'forecast-conventions'),
 q('29','f','An analyst models a recession by jointly reducing sales volume, lengthening customer payment terms, and increasing borrowing rates. Compared with changing only payment terms while holding every other input fixed, this is most accurately:',[
 ['a scenario analysis rather than a one-variable sensitivity.','Mehrere zusammengehörige Annahmen werden gleichzeitig verändert.'],['proof of the probability that the recession will occur.','Ein berechnetes Szenario liefert ohne zusätzliche Evidenz keine Eintrittswahrscheinlichkeit.'],['a method that makes internal accounting consistency unnecessary.','Jedes Szenario muss Bilanz und Zahlungsbewegungen weiterhin konsistent verknüpfen.']
 ],['Eine Sensitivität isoliert einen Übertragungsweg. Ein Szenario untersucht einen gemeinsamen wirtschaftlichen Zustand. Beide beantworten verschiedene Fragen.','Bei Kreditgrenzen, Mindestcash und anderen nichtlinearen Regeln ist das Ergebnis der Durchschnittsannahmen zudem nicht zwingend das durchschnittliche Ergebnis.'],'forecast-conventions'),
 q('30','f','A firm historically maintained a constant asset turnover while sales grew slowly. A new forecast doubles sales with the same assets, although production is already at full capacity and no outsourcing is planned. The most appropriate response is to:',[
 ['revise the capacity, investment, or sales assumptions before accepting the forecast.','Ein rechnerisch gewünschter Umschlag ersetzt keine real verfügbare Produktionskapazität.'],['accept the result because ratios are independent of operational constraints.','Die Quote beschreibt gerade das Verhältnis von Leistung und benötigten Ressourcen.'],['increase forecast cash by the asset shortfall to make the model feasible.','Ein erfundener Cashbestand schafft weder Finanzierung noch Produktionsanlagen.']
 ],['Prüfe zuerst, wie die zusätzliche Menge tatsächlich hergestellt und finanziert wird. Investition, Vorlaufzeit und Auslastung wirken anschließend auf Abschreibung, Cashflow und Bilanz.','Ein historischer Zusammenhang ist eine Ausgangshypothese und muss unter geänderten Bedingungen neu beurteilt werden.'],'forecast-conventions'),
 q('31','f','DSO is defined here using the simple average of opening and closing receivables. Forecast sales are 730, target DSO is 40 days, and opening receivables are 60. Using 365 days, required closing receivables are:',[
 ['100','Der Zielwert des Durchschnitts beträgt 80; der Endwert muss daher 100 sein.'],['80','Dies ist der Durchschnittsbestand, noch nicht der Endbestand.'],['20','Dies ist Durchschnitt minus Anfang und erfüllt die vorgegebene Mittelwertdefinition nicht.']
 ],[F('\\overline{AR}=730\\frac{40}{365}=80,\\qquad AR_1=2\\cdot80-60=100','Die Definition des verwendeten DSO muss vor der Bilanzprognose aufgelöst werden.',[['\\overline{AR}','Durchschnittliche Forderungen.'],['AR_1','Forderungen am Jahresende.']]),'Die tatsächliche Zunahme beträgt 40 und mindert bei sonst gleichen Annahmen den operativen Cashflow um 40.'],'forecast-conventions'),
 q('32','b c','A company has cash of 20, receivables of 80, inventory of 100, and current liabilities of 100. It collects 40 of receivables at carrying value. There are no other changes. Which statement is correct?',[
 ['Quick ratio stays at 1.0 while cash ratio rises from 0.2 to 0.6.','Forderungen werden in Cash umgewandelt; die Summe der Quick Assets bleibt 100.'],['Both quick ratio and cash ratio rise by 0.4.','Die Quick Ratio enthält die eingezogenen Forderungen bereits vor dem Einzug.'],['Current ratio rises because cash rises.','Das Umlaufvermögen ändert seine Zusammensetzung, nicht seine Summe.']
 ],[F('QR_1=\\frac{60+40}{100}=1,\\qquad CaR_1=\\frac{60}{100}=0{,}6','Es wird keine neue Forderung verdient; eine bestehende wird beglichen.',[['QR_1,CaR_1','Quick Ratio und Cash Ratio nach Zahlungseingang.']]),'Current Ratio bleibt 200/100 = 2. Der Einzug erhöht die sofort verfügbaren Mittel, ohne in diesem Fall neuen Umsatz oder Gewinn zu erzeugen.'],'interactions')
];
