const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('vote-'+id,'voting','equity',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','a','Two share classes have identical dividend and liquidation rights but different votes per share. The most accurate conclusion is that:',[
 ['economic participation and voting influence must be assessed separately.','Zahlungsrechte und Einflussrechte können auseinanderfallen.'],['the class with more votes necessarily receives a larger dividend per share.','Zusätzliche Stimmen erzeugen ohne entsprechende Bedingungen keinen zusätzlichen Zahlungsanspruch.'],['both classes must have the same market price because their votes do not affect investors.','Einflussrechte können bewertet werden; ein gleicher Kurs ist nicht garantiert.']
 ],['Zuerst werden die wirtschaftlichen Rechte verglichen, danach die für den Gegenstand geltenden Stimmen.','Erst eine Bewertung beider Rechtebündel erlaubt eine begründete Aussage zum Preis.'],'rights'),
 q('02','practice','a','A company is incorporated in one jurisdiction and listed on an exchange in another. An analyst assessing shareholder voting rights should first:',[
 ['identify the incorporation law, applicable listing rules and the actual share terms.','Mehrere Regelungsebenen können zusammenwirken.'],['assume the trading currency determines the corporation’s voting law.','Die Handelswährung ist kein ausreichender Nachweis des anwendbaren Gesellschaftsrechts.'],['apply the shareholder’s country of residence as the sole source of corporate voting rules.','Der Wohnsitz des Anlegers ersetzt die Prüfung der Gesellschaft und ihrer Rechte nicht.']
 ],['Satzung und Emissionsbedingungen konkretisieren die zulässigen Rechte.','Die konkrete Versammlung ergänzt Gegenstand, Stichtag, Fristen und Zählregeln.'],'jurisdiction'),
 q('03','practice','a','There are 84 million one-vote shares and 16 million shares with six votes each. Economic rights per share are identical. A founder owns all six-vote shares and none of the others. The founder’s percentage of all voting rights is closest to:',[
 ['53.33%','96 Millionen Stimmen werden durch insgesamt 180 Millionen geteilt.'],['16.00%','Dies ist die wirtschaftliche Stückzahlquote bei gleichen Zahlungsrechten.'],['96.00%','Dies setzt gewichtete Stimmen fälschlich zur ungewichteten Aktienzahl ins Verhältnis.']
 ],[F('q_V=\\frac{16\\cdot6}{84+16\\cdot6}=53{,}33\\%','Der Nenner enthält gewichtete Stimmen beider Klassen.',[['q_V','Quote des Gründers an allen Stimmrechten.']])],'weights'),
 q('04','practice','a','An owner holds all high-vote shares, each with four votes. All remaining shares have one vote, and economic rights are identical. To hold strictly more than half of all votes, the owner’s economic stake must be:',[
 ['greater than 20%.','Die Grenze ist eins geteilt durch fünf; genau zwanzig Prozent ergeben nur die Hälfte der Stimmen.'],['at least 20%, including exactly 20%.','Die verlangte strikte Mehrheit schließt den Gleichstand aus.'],['greater than 50%.','Mehrstimmrechte ermöglichen die Stimmmehrheit bereits unterhalb der Kapitalmehrheit.']
 ],[F('\\frac{4q}{4q+1-q}>\\frac12\\iff q>\\frac15','Bei zwanzig Prozent stehen 0,8 gewichtete Stimmenanteile auf beiden Seiten.',[['q','Anteil des Eigentümers an allen wirtschaftlich gleichberechtigten Aktien.']])],'leverage'),
 q('05','practice','a','A share class automatically loses its extra voting rights when a specified sunset condition occurs. Assuming no other changes, an analyst should:',[
 ['recompute voting influence using the rights that apply after the condition.','Der Multiplikator kann sich ändern, ohne dass Aktien verkauft werden.'],['retain the old voting percentage because the share count is unchanged.','Stimmen hängen auch vom Gewicht je Aktie ab.'],['assume the holder automatically loses all dividend rights.','Das Ende eines besonderen Stimmrechts ist nicht ohne Weiteres das Ende wirtschaftlicher Rechte.']
 ],['Eine kontrollierende Beteiligung wird zum relevanten Zeitpunkt beurteilt.','Der Sunset kann Zeit, Übertragung oder andere definierte Bedingungen betreffen; die konkreten Regeln entscheiden.'],'leverage'),
 q('06','practice','a b','A cohesive block owns 30% of all votes and votes all of them. Holders of the other votes cast 50% of their voting power. There are no abstentions. The block’s share of votes cast is closest to:',[
 ['46.15%','Dreißig geteilt durch dreißig plus fünfunddreißig ergibt die Quote.'],['30.00%','Dies ist der Anteil an allen ausstehenden Stimmen.'],['60.00%','Die übrige Teilnahmequote ist nicht der Nenner der Gesamtabstimmung.']
 ],[F('q_{cast}=\\frac{0{,}30}{0{,}30+0{,}50\\cdot0{,}70}=46{,}15\\%','Das gesamte abgegebene Stimmvolumen entspricht 65 Prozent der ausstehenden Stimmen.',[['q_{cast}','Anteil des Blocks an den gültig abgegebenen Stimmen.']]),'Ob ein Quorum erfüllt ist, wird gesondert geprüft.'],'turnout'),
 q('07','practice','a b','A 20% voting block participates fully. Participation by all other holders increases from 25% to 50%, with no abstentions. The block’s share of votes cast after the increase is:',[
 ['33.33%','Zwanzig von insgesamt sechzig Prozentpunkten ergeben ein Drittel.'],['50.00%','Dies war die Quote vor dem Anstieg der übrigen Teilnahme.'],['20.00%','Dies wäre die Quote bei vollständiger Teilnahme auch aller anderen.']
 ],[F('q_{cast}=\\frac{0{,}20}{0{,}20+0{,}50\\cdot0{,}80}=33{,}33\\%','Der Blockbestand bleibt konstant; nur der Nenner steigt.',[['q_{cast}','Anteil des Blocks an abgegebenen Stimmen nach dem Anstieg.']])],'turnout'),
 q('08','practice','a','An amendment requires both a strict majority of all outstanding votes and a strict majority of a protected class. It receives 70% overall but 45% within that class. Under these stated rules, the amendment:',[
 ['fails because the separate class requirement is not met.','Beide Bedingungen sind notwendig.'],['passes because the overall result overrides any class vote.','Dies ignoriert die ausdrücklich verlangte Klassenmehrheit.'],['passes because the average of the two percentages exceeds 50%.','Prozentwerte unterschiedlicher Grundlagen werden hier nicht gemittelt.']
 ],['Gesamt- und Klassenabstimmung werden getrennt geprüft.','Die Schutzklasse kann einen bestimmten Antrag blockieren, ohne allgemeine Unternehmensmehrheit zu besitzen.'],'class-votes'),
 q('09','practice','a b','A meeting requires at least 50% of 2,000 outstanding votes to be represented. Only 900 are represented, and 850 support the proposal. Under the stated rule:',[
 ['the quorum is not met, regardless of the high support among those represented.','Neunhundert sind nur fünfundvierzig Prozent der Gesamtbasis.'],['the quorum is met because support exceeds 90% of represented votes.','Zustimmung und Vertretung messen verschiedene Voraussetzungen.'],['the quorum is met whenever at least one valid affirmative vote is cast.','Das widerspricht der angegebenen Mindestvertretung.']
 ],[F('q_R=\\frac{900}{2000}=45\\%','Mindestens tausend Stimmen müssten vertreten sein.',[['q_R','Vertretungsquote für das festgelegte Quorum.']])],'quorum'),
 q('10','practice','a b','A proposal receives 420 votes for, 380 against and 200 abstentions. The quorum is met. It requires strictly more than half of votes for plus votes against; abstentions are excluded. The approval percentage is:',[
 ['52.50%','Der Nenner enthält ausschließlich achthundert Ja- und Nein-Stimmen.'],['42.00%','Dies bezieht die ausgeschlossenen Enthaltungen in den Nenner ein.'],['55.26%','Dies dividiert die Ja-Stimmen nur durch die Nein-Stimmen.']
 ],[F('p=\\frac{420}{420+380}=52{,}50\\%','Die ausdrücklich festgelegte Zustimmungsregel ist erfüllt.',[['p','Zustimmungsquote bei der angegebenen Ja-plus-Nein-Basis.']])],'denominators'),
 q('11','practice','a b','A resolution requires strictly more than half of 1,200 outstanding voting rights, regardless of attendance. The smallest whole number of affirmative votes that can pass it is:',[
 ['601','Genau sechshundert wären nur die Hälfte.'],['600','Eine strikte Mehrheit schließt Gleichstand aus.'],['501','Diese Zahl würde eine andere Gesamtbasis voraussetzen.']
 ],[F('Y_{min}=\\left\\lfloor\\frac{1200}{2}\\right\\rfloor+1=601','Nichtteilnahme senkt den ausdrücklich gegebenen Nenner nicht.',[['Y_{min}','Kleinste ganze Zahl zustimmender Stimmen.'],['\\lfloor x\\rfloor','Abrundung der Zahl x auf eine ganze Zahl.']])],'denominators'),
 q('12','practice','a b','Of 1,000 outstanding votes, 300 are for, 250 against, 100 abstentions and 100 broker non-votes. These four categories all count toward the stated quorum. Approval requires a strict majority of for plus against only. The approval percentage is closest to:',[
 ['54.55%','Zustimmung ist dreihundert geteilt durch fünfhundertfünfzig.'],['40.00%','Dies verwendet die Quorumsvertretung statt der angegebenen Zustimmungsbasis.'],['46.15%','Dies zählt eine ausgeschlossene Hundert-Stimmen-Kategorie im Nenner mit.']
 ],[F('p=\\frac{300}{300+250}=54{,}55\\%','Die 750 für das Quorum vertretenen Stimmen sind eine andere Größe.',[['p','Zustimmungsquote für den konkreten Antrag.']]),'Broker Non-Votes werden nicht in tatsächliche Nein-Stimmen umbenannt.'],'nonvotes'),
 q('13','practice','a','Under a single-seat plurality rule, three candidates receive 160, 150 and 90 votes. There are no other votes. The first candidate:',[
 ['wins because the largest number of votes is sufficient under this rule.','Eine Plurality-Regel verlangt hier keine absolute Mehrheit.'],['cannot win because 160 is less than half of 400.','Das wäre ein anderes Mehrheitserfordernis.'],['must share the seat with the second candidate because both exceed 100.','Eine solche Sitzteilung ist in der Regel nicht vorgesehen.']
 ],['Die Stimmen summieren sich auf vierhundert. Der erste Kandidat erhält vierzig Prozent und zugleich die höchste Zahl.','Eine Wahlregel mit strikter Mehrheit hätte ein anderes Ergebnis.'],'elections'),
 q('14','practice','a','A director election requires strictly more than half of 500 valid votes. The leading candidate receives 250. No fallback procedure is specified. The most accurate conclusion is that:',[
 ['the stated threshold is not met, and the next procedural step needs separate information.','Genau die Hälfte erfüllt keine strikte Mehrheit.'],['the candidate is elected automatically because no other candidate has more votes.','Die höchste Zahl ersetzt die vorgegebene Mehrheitsregel nicht.'],['a runoff must legally occur in every jurisdiction.','Das weitere Verfahren lässt sich ohne konkrete Regel nicht universell festlegen.']
 ],['Mindestens 251 gültige Stimmen wären nötig.','Ob eine neue Wahl oder ein anderes Verfahren folgt, ist eine gesonderte Rechts- und Satzungsfrage.'],'elections'),
 q('15','practice','a','A company has 120 equal-vote shares, full participation and four seats elected simultaneously by cumulative voting. The four highest vote totals win, and a tie is not a guaranteed win. A cohesive block can concentrate all its votes on one candidate. The smallest shareholding that guarantees that candidate a seat is:',[
 ['25','Mehr als 120 geteilt durch fünf ist erforderlich.'],['24','Vierundzwanzig ermöglicht einen Gleichstand mit vier Rivalen.'],['31','Dies verwendet einen falschen Nenner und ist nicht die kleinste ausreichende Zahl.']
 ],[F('s_{min}=\\left\\lfloor\\frac{120}{4+1}\\right\\rfloor+1=25','Mit 25 Aktien erhält der Kandidat 100 Stimmen. Die übrigen 95 Aktien liefern 380 Stimmen und damit zu wenig, um vier Rivalen jeweils hundert zu geben.',[['s_{min}','Kleinste ganze Aktienzahl für einen garantierten Sitz im Modell.'],['\\lfloor x\\rfloor','Abrundung der Zahl x.']])],'cumulative'),
 q('16','practice','a','With 100 equal-vote shares and three cumulative-voting seats, a 25-share block casts all 75 votes for one candidate. All other shares participate. A seat is not guaranteed because the remaining holders can:',[
 ['allocate 75 votes to each of three rivals, creating a tie.','Fünfundsiebzig Aktien liefern 225 verteilbare Stimmen.'],['allocate 100 votes to each of three rivals.','Dafür wären dreihundert Stimmen erforderlich; vorhanden sind nur 225.'],['cancel the block’s votes merely because the block is a minority.','Ein solches Aufhebungsrecht ist nicht gegeben.']
 ],['Die garantierende Schwelle muss Gleichstände ausschließen.','Mit 26 Aktien könnte der Block 78 Stimmen konzentrieren; die übrigen 222 reichen nicht für drei gleich starke Rivalen.'],'cumulative'),
 q('17','practice','a','A six-person board elects only two seats this year. There are 100 equal-vote shares and full participation. Under cumulative voting for the two open seats, the smallest cohesive block that guarantees one seat without relying on a tie is:',[
 ['34','Maßgeblich sind die zwei offenen Sitze, somit mehr als ein Drittel der Aktien.'],['15','Dies würde alle sechs Sitze als gleichzeitig offen behandeln.'],['51','Dies entspricht der Ein-Sitz-Schwelle, nicht den zwei offenen Sitzen.']
 ],[F('s_{min}=\\left\\lfloor\\frac{100}{2+1}\\right\\rfloor+1=34','Die Gesamtgröße des Boards ist nicht die Zahl der aktuell zu wählenden Sitze.',[['s_{min}','Kleinste ganze Aktienzahl im angegebenen Wahlmodell.'],['\\lfloor x\\rfloor','Abrundung der Zahl x.']])],'staggered'),
 q('18','practice','b','An eligible beneficial holder submits a voting instruction after the custodian’s stated final deadline but before the shareholder meeting. The custodian no longer accepts instructions through that route. The most appropriate conclusion is that:',[
 ['eligibility alone does not establish that the instruction was validly processed.','Stichtagsberechtigung und rechtzeitige Ausübung sind getrennt.'],['the later meeting date automatically overrides every intermediary deadline.','Diese automatische Verlängerung ist nicht gegeben.'],['a sent email proves the shares were counted.','Versand ist kein Nachweis der wirksamen Annahme und Zählung.']
 ],['Mögliche alternative Ausübungswege wären anhand der Unterlagen zu prüfen.','Ohne solchen Nachweis darf eine wirksame Stimme nicht behauptet werden.'],'record'),
 q('19','practice','b','In the US street-name voting process, a beneficial owner ordinarily uses a Voting Instruction Form primarily to:',[
 ['direct the intermediary how to vote the held shares.','Die Weisung wird in der Depotkette umgesetzt.'],['change the corporation’s incorporation jurisdiction.','Dafür ist das Weisungsformular nicht bestimmt.'],['transfer the economic ownership of the shares to a proxy adviser.','Eine Abstimmungsweisung überträgt nicht automatisch den wirtschaftlichen Anspruch.']
 ],['Der eingetragene Inhaber und der wirtschaftlich Berechtigte können verschiedene Personen sein.','Die technische Kette muss die Weisung den richtigen berechtigten Beständen zuordnen.'],'chain'),
 q('20','practice','b','A proxy adviser recommends voting against a resolution. No voting authority or execution service has been granted to the adviser. Which statement is most accurate?',[
 ['The recommendation alone neither casts the vote nor transfers decision responsibility.','Analyse, Empfehlung und autorisierte Ausübung sind unterschiedliche Leistungen.'],['The vote is automatically counted as against upon publication of the recommendation.','Ohne gültige Ausübung entsteht kein solcher Zählnachweis.'],['The adviser becomes the legal owner of every client share.','Die Beratung bewirkt keinen automatischen Eigentumsübergang.']
 ],['Der zuständige Entscheider beurteilt die Empfehlung im Mandatskontext.','Eine gültige und rechtzeitige Weisung muss anschließend über den vorgesehenen Weg erfolgen.'],'advisers'),
 q('21','practice','b','When assessing an executive compensation proposal, the most appropriate distinction between management and the board is that:',[
 ['management supplies operational rationale, while the relevant board body provides oversight under the governance framework.','Leitung und Überwachung sind funktional zu unterscheiden.'],['management approval eliminates the need for board oversight and investor assessment.','Eine Empfehlung ersetzt diese Aufgaben nicht.'],['the board’s recommendation guarantees that no conflict of interest can exist.','Auch eine Empfehlung ist auf Grundlage von Verfahren, Unabhängigkeit und Fakten zu beurteilen.']
 ],['Organstrukturen unterscheiden sich zwischen Rechtsordnungen.','Die tatsächliche Zuständigkeit wird geprüft, statt die Bezeichnungen Management und Board gleichzusetzen.'],'issuer'),
 q('22','practice','b','The meeting materials explicitly state that a vote on a policy is advisory. An analyst should most appropriately:',[
 ['distinguish its signaling and governance effects from an immediately binding legal decision.','Beratende und bindende Beschlüsse haben nicht automatisch dieselbe Rechtswirkung.'],['assume the vote instantly changes every affected contract.','Dies folgt aus der beratenden Wirkung nicht.'],['ignore the result because advisory votes can never matter economically.','Rechenschaft, Dialog und künftige Entscheidungen können wirtschaftlich relevant sein.']
 ],['Zuerst wird die Wirkung der konkreten Abstimmung festgestellt.','Danach wird geprüft, welche Reaktion des Unternehmens und seiner Verantwortlichen folgt.'],'issuer'),
 q('23','practice','b','A pension asset owner delegates voting to an external manager. The most appropriate ongoing action by the asset owner is to:',[
 ['monitor whether voting decisions and reports are consistent with the agreed mandate and beneficiary interests.','Delegation benötigt überprüfbare Zuständigkeiten und Kontrolle.'],['treat delegation as proof that every future vote will be appropriate.','Die Übertragung einer Aufgabe garantiert ihre gute Ausführung nicht.'],['instruct the manager to favor the sponsoring employer whenever its interests conflict with beneficiaries.','Der Sponsor ist nicht automatisch mit den maßgeblichen Begünstigten gleichzusetzen.']
 ],['Berichte sollten Entscheidung, wesentliche Begründung und Prozessabweichungen nachvollziehbar machen.','Die Interessen der maßgeblichen Begünstigten und die rechtlichen Anforderungen bleiben entscheidend.'],'owners'),
 q('24','practice','b','A manager with delegated voting authority has completed a careful proposal analysis. To establish that the intended votes were actually exercised, the next essential control is to:',[
 ['reconcile eligible holdings, submitted instructions and accepted voting confirmations.','Eine gute Entscheidung muss korrekt und rechtzeitig umgesetzt werden.'],['assume research completion is sufficient evidence of ballot acceptance.','Research ist kein Ausführungsnachweis.'],['replace the eligible holdings with the latest market value of the portfolio.','Marktwert ist weder Stichtagsbestand noch Stimmenzahl.']
 ],['Abweichungen zwischen Auftrag und Bestätigung müssen aufgeklärt werden.','Die gewählte Mehrheitsregel wird erst auf die tatsächlich gültigen Stimmen angewandt.'],'managers'),
 q('25','practice','b','An asset manager meets company directors to discuss minority protections but submits no voting instruction. The meeting is most accurately described as:',[
 ['engagement, which does not by itself prove that a vote was cast.','Dialog und Stimmabgabe sind verschiedene Handlungen.'],['automatic proxy execution for every portfolio holding.','Eine solche Vollmacht und technische Ausführung folgen nicht aus dem Gespräch.'],['a transfer of the manager’s client obligations to the directors.','Die Gesprächspartner übernehmen dadurch nicht den Kundenauftrag des Managers.']
 ],['Stewardship kann Dialog und Abstimmung umfassen.','Für jede Handlung werden Zweck, Zuständigkeit und Nachweis separat beurteilt.'],'managers'),
 q('26','practice','b','A proxy adviser’s report uses an outdated version of a materially amended proposal. The manager knows of the amendment. The most appropriate response is to:',[
 ['obtain or perform an updated assessment before relying on the recommendation.','Ein bekannter wesentlicher Datenfehler verlangt eine sachgerechte Reaktion.'],['follow the report unchanged because hiring an adviser removes the manager’s responsibility.','Beratung beseitigt die eigene Verantwortung nicht.'],['assume the amendment is irrelevant whenever the report was expensive.','Der Preis einer Analyse belegt nicht ihre Aktualität.']
 ],['Methodik und Datenstand müssen zum tatsächlichen Antrag passen.','Eintrag und Ausübung erfolgen erst auf der Grundlage der autorisierten Entscheidung.'],'advisers'),
 q('27','practice','b','An issuer offers an asset manager lucrative corporate work if the manager votes client shares for a proposal that its independent analysis finds harmful to those clients. The best response is to:',[
 ['address the conflict and decide according to the clients’ mandate and interests.','Ein Zusatzhonorar des Managers ist kein Vorteil des Kundenportfolios.'],['support the proposal because the manager’s revenue is part of client investment performance.','Hier werden verschiedene wirtschaftliche Begünstigte vermischt.'],['support the proposal once the conflict is disclosed, regardless of client harm.','Offenlegung allein macht eine kundenwidrige Entscheidung nicht sachgerecht.']
 ],['Die Stimmentscheidung braucht eine tragfähige kundenbezogene Begründung.','Geeignete Konfliktkontrollen unterstützen diesen Prozess; sie ersetzen das Kundeninteresse nicht.'],'conflicts'),
 q('28','practice','b','Under CFA Standard III(A), assuming no stricter legal or contractual requirement, a reasoned cost–benefit assessment finds that voting a particular proxy would not benefit the client. The most accurate statement is that:',[
 ['not voting may be appropriate; proxy policies should be disclosed and the decision grounded in client interests.','Der Standard verlangt keine ungeprüfte Pflicht zur Ausübung jeder einzelnen Stimme.'],['every proxy must always be voted regardless of client benefit.','Dies lässt die ausdrücklich mögliche Kosten-Nutzen-Abwägung aus.'],['the manager may instead sell the client’s vote for its own benefit.','Eine kundenbezogene Ausnahme erlaubt keinen persönlichen Missbrauch.']
 ],['Die Abwägung ist auf den Kunden und den tatsächlichen Auftrag bezogen.','Ein kleiner Stimmanteil oder ein bloßer Hinweis auf Aufwand ist noch keine ausreichende Analyse.'],'conflicts'),
 q('29','practice','b','Two separately managed mandates have different lawful, explicit voting instructions for the same proposal. A shared voting platform should:',[
 ['preserve the correct instruction and eligible holding for each mandate.','Die technische Bündelung darf unterschiedliche Aufträge nicht vermischen.'],['automatically assign the larger mandate’s instruction to both.','Die Größe eines Mandats setzt das andere nicht außer Kraft.'],['let the issuer choose which instruction is most convenient.','Der Emittent erhält dadurch kein Ermessen über Kundenweisungen.']
 ],['Zuständigkeit und Auftrag bestimmen die Entscheidung.','Bestandsabgleich und Bestätigung müssen die getrennten Weisungen nachvollziehbar erhalten.'],'chain'),
 q('30','practice','a b','A company has 80 million one-vote A shares and 20 million B shares with five votes each. All B votes support a proposal. Represented A votes are 15 million for, 35 million against and 10 million abstentions. Quorum is met. Approval uses only for plus against. The approval percentage is closest to:',[
 ['76.67%','115 Millionen Ja-Stimmen stehen insgesamt 150 Millionen Ja- und Nein-Stimmen gegenüber.'],['71.88%','Dies nimmt die zehn Millionen Enthaltungen in den Nenner auf.'],['55.56%','Dies ist die B-Quote an allen ausstehenden Stimmen, nicht die gesamte Zustimmung.']
 ],[F('p=\\frac{20\\cdot5+15}{20\\cdot5+15+35}=76{,}67\\%','Gewichte werden vor der Bildung der Zustimmungsquote angewandt.',[['p','Zustimmung unter gültigen Ja- und Nein-Stimmen.']])],'case'),
 q('31','practice','a b','Before the voting record date, 20 million five-vote B shares convert into one-vote shares. All B holders vote for. Other holders cast 15 million for, 35 million against and 10 million abstentions. Quorum is met; approval requires strictly more than half of for plus against. The proposal:',[
 ['fails because the resulting 35 million for and 35 million against are tied.','Das geänderte Stimmgewicht wird vor der Zählung berücksichtigt.'],['passes because the B holders historically had 100 million votes.','Die alten Mehrstimmrechte gelten zum relevanten Stichtag nicht mehr.'],['passes because exactly 50% always meets a strict-majority rule.','Genau die Hälfte ist nicht mehr als die Hälfte.']
 ],[F('p=\\frac{20+15}{20+15+35}=50\\%','Die wirtschaftlichen Bestände müssen sich dafür nicht ändern.',[['p','Zustimmungsquote nach wirksamer Umwandlung.']])],'case'),
 q('32','practice','a b','A proposal receives 115 million affirmative votes out of 180 million outstanding voting rights. It requires at least two thirds of all outstanding rights. The minimum affirmative total required, in millions, is:',[
 ['120','Zwei Drittel von 180 ergeben 120.'],['100','Dies ist keine Zweidrittelschwelle von 180.'],['115','Die vorhandene Zustimmung bestimmt nicht nachträglich die Schwelle.']
 ],[F('Y_{min}=\\frac23\\cdot180=120','Die vorhandenen 115 Millionen reichen trotz einer einfachen Mehrheit nicht.',[['Y_{min}','Erforderliche Ja-Stimmen in Millionen.']])],'case'),
 q('a1','mock-a','a','A founder owns all 20 million shares with ten votes each; the public holds 80 million one-vote shares. Economic rights are identical. Before the voting record date, the founder sells 8 million shares, which automatically convert to one-vote shares on transfer. The founder retains all other holdings. The founder’s share of all votes after the sale is closest to:',[
 ['57.69%','Nach dem Verkauf verbleiben 120 Millionen Gründerstimmen; die übrigen Aktien besitzen insgesamt 88 Millionen Stimmen.'],['42.86%','Dies reduziert den Gründerbestand, lässt aber die weggefallenen 72 Millionen Mehrstimmen fälschlich im Gesamtnenner.'],['12.00%','Dies ist die wirtschaftliche Restquote, nicht die gewichtete Stimmquote.']
 ],[F('q_V=\\frac{(20-8)\\cdot10}{(20-8)\\cdot10+80+8}=57{,}69\\%','Übertragung und Umwandlung verändern sowohl die Stimmen des Gründers als auch die gesamte Stimmenbasis. Seine einfache Stimmenmehrheit bleibt bestehen.',[['q_V','Anteil des Gründers an allen Stimmen nach dem Verkauf und der automatischen Umwandlung.']])],'leverage'),
 q('a2','mock-a','b','A delegated manager’s policy requires analysis of material changes to shareholder protections. The manager automatically follows issuer management on such a change without reviewing it, arguing that a proxy adviser will be responsible for any harm. The most appropriate assessment is that:',[
 ['the manager has not justified its decision or discharged its own responsibilities by invoking the adviser.','Weder automatische Managementfolge noch ein Beraterverweis ersetzt die geforderte Prüfung.'],['the adviser automatically assumes the manager’s duties whenever an issuer recommendation exists.','Ein solcher Verantwortungsübergang folgt daraus nicht.'],['following management eliminates conflicts because management knows the business best.','Wissen kann relevant sein, schließt eigene Interessen aber nicht aus.']
 ],['Entscheidung und Verantwortung müssen zum Mandat passen.','Der Manager braucht eine sachgerechte Informationsgrundlage und einen nachvollziehbaren Ausführungsprozess.'],'managers'),
 q('b1','mock-b','a','A listed company’s preferred shares carry no votes in ordinary director elections. Their valid terms nevertheless require separate preferred-class consent to reduce their liquidation priority. No other special rights apply. Which conclusion is most accurate?',[
 ['The class can protect the specified liquidation right without having general director-election voting power.','Ein gegenstandsbezogenes Schutzrecht ist von allgemeiner Organwahl zu unterscheiden.'],['The protective consent right automatically permits the class to elect a majority of directors.','Der begrenzte Gegenstand erzeugt keine nicht vereinbarten allgemeinen Wahlrechte.'],['The exchange listing makes the class consent unnecessary whenever common shareholders support the change.','Die Notierung beseitigt die ausdrücklich gültige besondere Zustimmungsvoraussetzung nicht.']
 ],['Die Bezeichnung als im gewöhnlichen Wahlverfahren stimmrechtslos schließt nicht jedes bedingte oder gegenstandsbezogene Zustimmungsrecht aus.','Zahlungsrang, allgemeines Stimmrecht und Schutz gegen Änderungen werden einzeln aus den Bedingungen gelesen.'],'class-votes'),
 q('b2','mock-b','b','A beneficial holder gives no instruction on a proposal for which its broker has no discretionary voting authority. The applicable meeting rules allow the represented holding to count toward quorum but exclude it from the for-plus-against approval denominator. The most appropriate treatment is to:',[
 ['record a broker non-vote for the proposal and apply the separately specified quorum and approval rules.','Eine vertretene Position kann für verschiedene Tests unterschiedlich behandelt werden.'],['convert the missing instruction into an affirmative vote because quorum includes the holding.','Vertretung für Beschlussfähigkeit ist keine Zustimmung.'],['record an abstention by the beneficial holder even though no instruction was given.','Dies behauptet eine nicht abgegebene Erklärung.']
 ],['Die tatsächliche Kategorie bleibt von ihrer Wirkung auf die jeweiligen Nenner getrennt.','Die fallbezogenen Regeln werden angewandt, ohne daraus eine universelle Regel für alle Versammlungen abzuleiten.'],'nonvotes')
];
