const {Q,F}=require('../author.cjs');
const q=(id,pool,los,stem,options,solution,section)=>Q('wc-'+id,'working-capital','corporate',pool,los,stem,options,0,solution,{section});
module.exports=[
 q('01','practice','b','An issuer reports current assets of €250 million and current liabilities of €140 million. Using the balance-sheet definition, its net working capital in millions is:',[
 ['110','Kurzfristiges Vermögen minus kurzfristige Verbindlichkeiten.'],['250','Das ist das gesamte kurzfristige Vermögen vor Abzug der Verpflichtungen.'],['390','Eine Addition ergibt kein Nettoumlaufvermögen.']
 ],[F('NWC=250-140=110','Die Größe sagt allein noch nichts über die Fälligkeiten und Verwertbarkeit der einzelnen Posten.',[['NWC','Bilanzielles Nettoumlaufvermögen in Millionen Euro.']]),'Eine positive Differenz ist keine Garantie, dass morgen jede Zahlung aus vorhandener Kasse geleistet werden kann.'],'definitions'),
 q('02','practice','a b','Define operating working capital as inventories plus trade receivables minus trade payables. An issuer has inventories of 60, receivables of 75, payables of 45, cash of 20 and short-term bank debt of 30. Its operating working capital is:',[
 ['90','Nur die drei ausdrücklich definierten operativen Posten werden einbezogen.'],['80','Dieser Wert berücksichtigt zusätzlich Kasse minus Bankkredit und wäre die hier rekonstruierbare bilanzielle Nettogröße.'],['135','Die Summe aus Vorräten und Forderungen ignoriert den Lieferantenkredit.']
 ],[F('OWC=60+75-45=90','Die Abgrenzung wird vor der Rechnung festgelegt.',[['OWC','Operatives Working Capital in den angegebenen Geldeinheiten.']]),'Die Zahlungsfähigkeit selbst muss anschließend mit Kasse, Fälligkeiten und tatsächlich zugänglicher Finanzierung beurteilt werden.'],'definitions'),
 q('03','practice','a','A retailer receives inventory on day 0, pays the supplier on day 30, sells on credit on day 50 and collects from the customer on day 80. The cash conversion cycle of this transaction, in days, is:',[
 ['50','Zwischen eigener Zahlung an Tag 30 und Einzug an Tag 80 liegen fünfzig Tage.'],['80','Das ist die Dauer vom Wareneingang bis zur Kundenzahlung ohne Abzug des Lieferantenkredits.'],['30','Das sind entweder die Lieferantentage oder die Forderungstage in diesem Fall, nicht deren Gesamteffekt.']
 ],[F('CCC=50+(80-50)-30=50','Die Lagerphase wird um die Forderungsphase verlängert und um die Lieferantenfinanzierung verkürzt.',[['CCC','Cash Conversion Cycle in Tagen.']]),'Der Verkaufstag verändert den Gewinn, aber noch nicht den Geldzufluss aus diesem Verkauf.'],'cash-timeline'),
 q('04','practice','a','Using 365 days, an issuer has average inventory of 90 and annual cost of goods sold of 1,095; average trade receivables of 120 and annual credit sales of 1,460; average trade payables of 60 and annual credit purchases of 730. Its cash conversion cycle is closest to:',[
 ['30','Jede Tageskomponente beträgt dreißig; nur die Lieferantentage werden abgezogen.'],['60','Dies ist der Operating Cycle vor Abzug der Lieferantenfinanzierung.'],['90','Dies addiert die Lieferantentage mit dem falschen Vorzeichen.']
 ],[F('CCC=365\\left(\\frac{90}{1095}+\\frac{120}{1460}-\\frac{60}{730}\\right)=30','Jeder Bestand wird durch den sachgerechten Jahresstrom geteilt.',[['CCC','Geldumschlagsdauer in Tagen.']]),'Ein einheitlicher Nenner für alle drei Bestände würde Verkaufs- und Kostenbasis vermischen.'],'cycle-formulas'),
 q('05','practice','a','Using 360 days, a merchant has annual cost of goods sold of 990, beginning inventory of 80, ending inventory of 110 and average trade payables of 85. All purchases are on credit and there are no other inventory changes. Days payables outstanding is closest to:',[
 ['30','Einkäufe sind 1.020; 85 geteilt durch 1.020 mal 360 ergibt dreißig.'],['30.91','Dieser Wert verwendet Umsatzkosten statt der höheren Einkäufe.'],['27.82','Dieser Wert behandelt den gesamten Endbestand fälschlich als zusätzlichen Einkauf ohne Abzug des Anfangsbestands.']
 ],[F('P=990+110-80=1020,\\qquad DPO=\\frac{85}{1020}360=30','Ein Bestandsaufbau erhöht die Einkäufe über den Aufwand für verkaufte Ware.',[['P','Krediteinkäufe in den angegebenen Geldeinheiten.'],['DPO','Lieferantenverbindlichkeitstage.']]),'Die Umsatzkosten-Näherung wäre nur als Näherung vertretbar, wenn geeignete Einkaufsdaten fehlen.'],'measurement'),
 q('06','practice','a','A company has annual credit sales of 720 and cash sales of 360. Average trade receivables are 90. Using 360 days and the credit-sales basis, days sales outstanding is:',[
 ['45','Nur Kreditverkäufe erzeugen den betrachteten Forderungsbestand.'],['30','Der Gesamtumsatz im Nenner lässt den Einzug der Kreditverkäufe hier zu schnell erscheinen.'],['90','Die Verwendung nur der Barverkäufe passt nicht zu den Forderungen.']
 ],[F('DSO=\\frac{90}{720}360=45','Barverkäufe werden für diese Frage aus der Strombasis ausgeschlossen.',[['DSO','Forderungstage der Kreditverkäufe.']]),'Bei unbekannter Aufteilung kann Gesamtumsatz eine offengelegte Näherung sein; in diesem Fall ist die richtige Aufteilung gegeben.'],'measurement'),
 q('07','practice','a b','A retailer reports a negative cash conversion cycle. Which interpretation is most appropriate?',[
 ['Customers pay, on average, before related supplier payments, but other cash obligations still require analysis.','Ein negativer operativer Zyklus ersetzt keine Planung von Löhnen, Steuern oder Tilgungen.'],['The company must be unprofitable because the number of days is negative.','Das Vorzeichen des CCC misst Zahlungsreihenfolge, nicht Gewinn.'],['All financing and liquidity risks have necessarily disappeared.','Andere Zahlungen und ein möglicher Geschäftsabschwung können weiterhin einen Engpass erzeugen.']
 ],['Ein negativer Wert kann eine günstige operative Finanzierungsstruktur anzeigen. Bei Umsatzrückgang können neue Kundenzuflüsse schneller sinken als alte Lieferantenzahlungen.','Kennzahl, Geschäftsmodell, Zahlungstermine und verfügbare Finanzierungsquellen werden zusammen beurteilt.'],'comparison'),
 q('08','practice','a b','A seasonal business has low inventory at both the beginning and end of its fiscal year but large inventory balances during its selling season. For assessing typical inventory days, the analyst should most appropriately:',[
 ['use more frequent representative inventory observations and examine the seasonal peak separately.','Mehr Beobachtungen verbessern den Durchschnitt; die Spitze bleibt für Finanzierung gesondert wichtig.'],['assume the average of the two year-end balances captures every seasonal financing need.','Beide Stichtage können denselben niedrigen Saisonpunkt treffen.'],['replace inventory with annual revenue because both measure the same economic item.','Umsatz ist ein Strom zu Verkaufspreisen; Vorräte sind ein Bestand zu Kosten.']
 ],['Durchschnittliche Bindung und maximale Liquiditätslücke beantworten unterschiedliche Fragen. Monats- oder Tageswerte können beides besser sichtbar machen.','Ein einzelner Stichtag beweist weder den normalen Bestand noch den höchsten Finanzierungsbedarf.'],'measurement'),
 q('09','practice','a c','A stable merchant has daily credit sales of €400 and daily cost of goods sold and credit purchases of €250 each. Inventory days are 40, receivable days 25 and payable days 30. Average operating working capital is:',[
 ['12,500','Vorräte 10.000 plus Forderungen 10.000 minus Verbindlichkeiten 7.500.'],['8,750','Dies multipliziert den gesamten CCC mit Tageskosten und unterschätzt die Forderungen.'],['20,000','Dies addiert Vorräte und Forderungen ohne Abzug der Lieferantenfinanzierung.']
 ],[F('OWC=40\\cdot250+25\\cdot400-30\\cdot250=12500','Die Forderungen werden auf Verkaufspreisbasis rekonstruiert.',[['OWC','Durchschnittliches operatives Working Capital in Euro.']]),'Der CCC beträgt 35 Tage, aber 35 mal 250 liefert nur 8.750. Die Differenz 3.750 entspricht der in den Forderungen enthaltenen Marge.'],'cash-amount'),
 q('10','practice','a c','With daily credit sales fixed at €500, an issuer permanently reduces days sales outstanding from 32 to 25. Ignoring other changes, the reduction in average receivables is:',[
 ['3,500','Sieben Tage weniger mal fünfhundert Euro Tageskreditumsatz.'],['12,500','Das ist der neue Forderungsbestand, nicht seine Veränderung.'],['16,000','Das ist der alte Forderungsbestand.']
 ],[F('\\Delta AR=500(25-32)=-3500','Die negative Bestandsänderung entspricht einer Freisetzung von 3.500 Euro.',[['\\Delta AR','Änderung des durchschnittlichen Forderungsbestands in Euro.']]),'Ob der Abbau ohne Rabatt, Ausfall oder verlorene Umsätze gelingt, ist eine zusätzliche wirtschaftliche Frage.'],'sensitivity'),
 q('11','practice','a c','A company has positive operating working capital of €18,000. Credit sales, purchases and cost of goods sold all grow by 20%, while the relevant turnover days remain unchanged. Additional operating working capital required is:',[
 ['3,600','Bei gleichen Tagen skalieren die zugehörigen Bestände proportional mit den Strömen.'],['21,600','Das ist der neue Gesamtbestand, nicht der zusätzliche Bedarf.'],['0','Unveränderte Tage bedeuten bei höherem Volumen keine unveränderte Geldbindung.']
 ],[F('\\Delta OWC=18000\\cdot0{,}20=3600','Die neue gesamte Bindung beträgt 21.600 Euro.',[['\\Delta OWC','Zusätzliche operative Kapitalbindung in Euro.']]),'Profitable Expansion kann deshalb zusätzliche Finanzierung benötigen, obwohl sich keine Tageskennzahl verschlechtert.'],'sensitivity'),
 q('12','practice','c','A permanent process improvement releases €20,000 once and allows the company to reduce interest-bearing funding permanently by that amount. The annual simple funding cost is 6%. Ignoring taxes and other effects, recurring annual interest savings are:',[
 ['1,200','Jährliche Zinsersparnis ist sechs Prozent des dauerhaft ersetzten Kreditbetrags.'],['20,000','Dies ist die einmalige Freisetzung, nicht die laufende Zinsersparnis.'],['21,200','Hier werden ein einmaliger Betrag und eine jährliche Stromgröße vermischt.']
 ],[F('S_I=20000\\cdot0{,}06=1200','Die Ersparnis tritt unter den Annahmen jährlich auf; die Kapitalfreisetzung selbst nur einmal.',[['S_I','Jährliche Zinsersparnis in Euro.']]),'Bei einer Projektbewertung müssen Cashflows und Finanzierung konsistent behandelt werden, damit derselbe Vorteil nicht doppelt gezählt wird.'],'sensitivity'),
 q('13','practice','b','Current assets consist of cash 40, marketable short-term investments 20, collectible trade receivables 90, inventory 120 and prepaid expenses 30. Current liabilities are 100. Using only cash, the investments and receivables in the numerator, the quick ratio is:',[
 ['1.5','Die drei ausdrücklich zugelassenen Posten ergeben 150.'],['1.8','Nur Vorräte vom kurzfristigen Vermögen abzuziehen lässt die Vorauszahlungen fälschlich im Zähler.'],['3.0','Dies ist die Current Ratio unter den gegebenen Zahlen.']
 ],[F('QR=\\frac{40+20+90}{100}=1{,}5','Vorauszahlungen stehen nicht als Geld zur Begleichung der betrachteten Verpflichtungen zur Verfügung.',[['QR','Quick Ratio nach der im Fall vorgegebenen Definition.']]),'Auch die verbleibenden Forderungen müssen rechtzeitig und tatsächlich einbringlich sein.'],'liquidity-ratios'),
 q('14','practice','b','An issuer has €180,000 of qualifying defensive liquid assets, including collectible receivables, and average daily cash operating expenditures of €3,000. Its defensive interval, in days, is:',[
 ['60','Bestand geteilt durch täglichen zahlungswirksamen Aufwand ergibt Tage.'],['540','Dies entsteht aus einer nicht passenden Multiplikation.'],['30','Die gegebenen Mittel decken rechnerisch doppelt so viele Tage.']
 ],[F('DIR=\\frac{180000}{3000}=60','Die Größe setzt die angegebenen defensiven Mittel in Beziehung zu den täglichen Ausgaben.',[['DIR','Defensive Interval Ratio in Tagen.']]),'Die Rechnung garantiert keinen rechtzeitigen Forderungseinzug und umfasst nur die im Nenner berücksichtigten Zahlungen.'],'liquidity-ratios'),
 q('15','practice','b','An issuer has current assets of 60, including cash of 30, and current liabilities of 100. It pays 20 of current liabilities using cash, with no other effects. Its current ratio immediately after payment is:',[
 ['0.5','Vermögen und Verbindlichkeiten sinken beide um zwanzig: vierzig geteilt durch achtzig.'],['0.6','Dies ist die Quote vor der Zahlung.'],['0.75','Dies verringert nur den Nenner und lässt den Kassenabgang aus.']
 ],[F('CR_1=\\frac{60-20}{100-20}=0{,}5','Bei einer Ausgangsquote unter eins verschlechtert sich die Quote durch diese Zahlung mechanisch.',[['CR_1','Current Ratio nach Zahlung.']]),'Eine erfüllte Verpflichtung und eine schlechtere Quote können gleichzeitig vorliegen. Das Nettoumlaufvermögen bleibt minus vierzig.'],'ratio-traps'),
 q('16','practice','b','Firm A has a current ratio of 2.4 dominated by slow-moving inventory. Firm B has a ratio of 1.5 and assets consisting mainly of available cash and receivables due before its obligations. The most appropriate conclusion is:',[
 ['The ratios alone do not establish A as more liquid; composition and payment timing matter.','Buchmäßige Deckung und rechtzeitige Verfügbarkeit sind unterschiedliche Eigenschaften.'],['A must be more liquid because its ratio is numerically larger.','Dies ignoriert die Realisierbarkeit der Vorräte und die Fälligkeiten.'],['B must be insolvent because its ratio is below 2.0.','Ein universeller Mindestwert von zwei lässt sich daraus nicht ableiten.']
 ],['Ergänzt werden Kassenplanung, Einbringlichkeit, laufende Zahlungsströme und verfügbare Finanzierung. Auch B ist nicht allein wegen dieser Angaben gegen jeden Stress geschützt.','Ein Vergleich verwendet passende Geschäftsmodelle und erklärt die Zusammensetzung statt nur Zahlen zu ordnen.'],'liquidity-ratios'),
 q('17','practice','b c','A company starts with cash of 12 and no debt and requires minimum cash of 5. For periods 1 and 2, cash receipts are 20 and 40, and operating cash payments are 37 and 30. It borrows as needed and repays debt with cash above 5. Ignoring interest, the peak borrowing required is:',[
 ['10','Periode eins endet vor Finanzierung bei minus fünf; zehn werden bis zur Mindestkasse benötigt.'],['5','Dies deckt nur den Fehlbetrag bis null und ignoriert die Mindestkasse.'],['0','Die Tilgung in Periode zwei beseitigt nicht den früheren Kreditbedarf.']
 ],[F('B_1=5-(12+20-37)=10','In Periode zwei stehen vor Tilgung fünfzehn bereit; zehn können vollständig zurückgezahlt werden.',[['B_1','Benötigte Kreditaufnahme in der ersten Periode in den angegebenen Geldeinheiten.']]),'Endschuld null ist mit einer vorherigen Spitzenbeanspruchung von zehn vereinbar.'],'cash-budget'),
 q('18','practice','b c','A bank facility has a stated limit of 100 and 70 already drawn. Further borrowing depends on collateral eligibility that has recently deteriorated. The analyst should most appropriately:',[
 ['verify the currently drawable amount rather than automatically count all 30 of nominal headroom as available cash.','Anrechenbare Sicherheiten und sonstige Bedingungen können den tatsächlich nutzbaren Rest verringern.'],['add the full limit of 100 to cash because the existing borrowing does not matter.','Dies zählt bereits genutzte Finanzierung erneut.'],['treat a stated limit as an unconditional guarantee regardless of the agreement.','Die Vertragsbedingungen sind für die Verfügbarkeit wesentlich.']
 ],['Nominelles Limit, bereits gezogene Beträge und aktuell erfüllte Bedingungen werden getrennt geprüft. Der nicht gezogene Betrag ist außerdem noch kein vorhandener Kassenbestand.','Liquiditätsplanung muss Zeitpunkt und Abruffähigkeit berücksichtigen.'],'sources-drags'),
 q('19','practice','b','An otherwise collectible customer invoice is paid substantially later than expected, with no change in the company’s payment obligations. This most directly creates:',[
 ['a drag on liquidity through delayed cash inflow.','Der Zufluss verzögert sich, während Auszahlungen weiterhin fällig werden.'],['a pull on liquidity caused by earlier supplier payment.','Der Fall nennt keine vorgezogene Lieferantenzahlung.'],['an automatic cash inflow equal to reported revenue.','Umsatzerfassung ist keine Zahlungsgarantie zum selben Zeitpunkt.']
 ],['Die Forderung kann bestehen bleiben, während die Finanzierungslücke wächst. Ob zusätzlich eine Wertberichtigung nötig wird, ist eine andere Frage.','Die Ursache der Lücke ist der spätere Eingang, nicht ein früherer Zahlungstermin eigener Verpflichtungen.'],'sources-drags'),
 q('20','practice','a b','A supplier changes agreed payment terms from 45 days to cash on delivery for future purchases. All else equal, the buyer experiences:',[
 ['a pull on liquidity and a longer cash conversion cycle.','Die eigene Zahlung wird vorgezogen; niedrigere DPO verlängern den CCC.'],['a shorter cash conversion cycle because less supplier credit is available.','Weniger Lieferantenfinanzierung verlängert die selbst zu überbrückende Zeit.'],['a delayed customer cash inflow with no change in its own payment timing.','Betroffen ist ausdrücklich der Lieferantenzahlungstermin.']
 ],['DPO fällt um 45 Tage. Bei gleichen DIO und DSO steigt der CCC entsprechend um 45 Tage.','Ein niedrigeres Verbindlichkeitsniveau kann hier höheren Finanzierungsbedarf bedeuten.'],'sources-drags'),
 q('21','practice','b c','To cover an unexpected near-term cash shortage, a manufacturer considers an unusual sale of a long-lived production asset. This source is most appropriately assessed as:',[
 ['a secondary liquidity measure whose timing, proceeds and operating consequences require review.','Ein Sonderverkauf kann Zeit, Abschläge und spätere Ertragseinbußen verursachen.'],['existing cash already available at the asset’s full book value.','Buchwert und sofort erzielbarer Verkaufserlös sind nicht gleich.'],['a routine customer collection that cannot affect future production.','Eine Produktionsanlage ist kein gewöhnlicher Forderungseinzug.']
 ],['Ein plausibler Liquiditätsplan verwendet erwarteten Nettoerlös und tatsächlichen Zahlungstermin. Die Anlage kann für den Betrieb notwendig sein.','Eine Maßnahme kann Geld beschaffen und zugleich zukünftige Zahlungsüberschüsse vermindern.'],'sources-drags'),
 q('22','practice','c','Reducing inventory by €20,000 saves annual funding costs of 8% of that amount and annual storage costs of €1,400, but causes €4,000 of lost annual contribution from stockouts. Ignoring other effects, the change in annual contribution after these costs is:',[
 ['−1,000','1.600 Finanzierung plus 1.400 Lagerersparnis minus 4.000 verlorener Beitrag.'],['3,000','Dies ignoriert die durch Fehlbestände verlorenen Beiträge.'],['19,000','Dies vermischt einmalige Kapitalfreisetzung mit dem jährlichen Nettoeffekt.']
 ],[F('\\Delta V=20000\\cdot0{,}08+1400-4000=-1000','Die niedrigere Vorratsbindung reicht nicht als Erfolgsmaßstab.',[['\\Delta V','Änderung des jährlichen Beitrags in Euro unter den Modellannahmen.']]),'Die einmalige Freisetzung von 20.000 ist eine andere Größe als der wiederkehrende Nachteil von 1.000.'],'inventory-policy'),
 q('23','practice','c','Using 360 days and stable sales within each year, a credit policy increases annual credit sales from €500,000 to €540,000 and DSO from 30 to 40. The increase in average receivables is closest to:',[
 ['18,333.33','Der neue Bestand von 60.000 wird mit dem alten Bestand von 41.666,67 verglichen.'],['15,000.00','Dies bewertet nur zehn zusätzliche Tage mit dem neuen Tagesumsatz und lässt den Volumeneffekt auf die bisherigen Tage aus.'],['60,000.00','Dies ist der neue Bestand und kein Zuwachs.']
 ],[F('\\Delta AR=\\frac{540000}{360}40-\\frac{500000}{360}30\\approx18333{,}33','Umsatzniveau und Zahlungsdauer verändern sich gemeinsam.',[['\\Delta AR','Zunahme des durchschnittlichen Forderungsbestands in Euro.']]),'Die Wirtschaftlichkeit hängt zusätzlich von Deckungsbeitrag, Ausfällen, Verwaltung und Kapitalkosten ab.'],'credit-policy'),
 q('24','practice','c','A supplier offers 1/15, net 45. Using a 365-day year, the simple annualized financing cost of foregoing the discount is closest to:',[
 ['12.29%','Ein Prozent Rabatt relativ zu 99 Prozent sofortiger Zahlung wird auf dreißig Tage bezogen.'],['12.17%','Dieser Wert verwendet den vollen Rechnungsbetrag statt der rabattierten Zahlung als Finanzierungsbasis.'],['8.19%','Dieser Wert verwendet die gesamte Nettofrist von 45 statt der zusätzlichen dreißig Tage.']
 ],[F('r=\\frac{0{,}01}{0{,}99}\\frac{365}{45-15}\\approx12{,}29\\%','Gefragt ist die einfache Annualisierung, nicht eine Wiederanlage mit Zinseszins.',[['r','Einfach annualisierter Finanzierungssatz des Skontoverzichts.']]),'Die Finanzierung beginnt erst an dem Tag, an dem man die rabattierte Zahlung alternativ leisten würde.'],'trade-discount'),
 q('25','practice','a c','An invoice of €50,000 offers a 2% discount on day 10 or full payment on day 40. A bank lends the discounted amount for the extra 30 days at 10% simple annual interest on a 365-day basis, without fees. The saving from taking the discount and using the bank loan is closest to:',[
 ['597.26','Der Rabatt von 1.000 wird um 402,74 Kreditzins auf 49.000 vermindert.'],['1,000.00','Dies ignoriert die Kosten der Bankfinanzierung.'],['402.74','Dies sind die Kreditzinsen, nicht die Ersparnis.']
 ],[F('S=1000-49000\\cdot0{,}10\\frac{30}{365}\\approx597{,}26','Die Bank finanziert nur den rabattierten Zahlbetrag über die zusätzliche Zeitspanne.',[['S','Ersparnis in Euro gegenüber Zahlung des vollen Rechnungsbetrags an Tag vierzig.']]),'Die frühere Lieferantenzahlung senkt DPO und verlängert den CCC, kann aber trotzdem den Gesamtaufwand reduzieren.'],'trade-discount'),
 q('26','practice','c','A factor advances 70% of a €200,000 invoice immediately. The remaining amount, less all fees and interest, is paid only after collection. No fee is deducted from the initial advance. Cash immediately available from factoring is:',[
 ['140,000','Nur der vereinbarte Vorschuss ist heute verfügbar.'],['200,000','Der zurückbehaltene Rest kommt erst später und wird noch um Kosten vermindert.'],['60,000','Dies ist der zunächst einbehaltene Betrag vor Kosten.']
 ],[F('A=200000\\cdot0{,}70=140000','Die Zahlungszeitpunkte dürfen nicht zu einer angeblich sofort verfügbaren Gesamtsumme zusammengezogen werden.',[['A','Sofortiger Factoringvorschuss in Euro.']]),'Für die vollständige Kostenrechnung werden zusätzlich Gebührenbasis, Zins, Dauer und verbleibendes Risiko benötigt.'],'factoring'),
 q('27','practice','c','A factoring contract is described as non-recourse for specified customer credit defaults but excludes disputes over goods delivered. The seller should most appropriately conclude that:',[
 ['covered credit risk may transfer, while excluded disputes can still create exposure.','Der vertragliche Schutz hat einen definierten Umfang.'],['every possible loss and operational risk is automatically transferred.','Ohne Rückgriff für bestimmte Ausfälle bedeutet keinen unbegrenzten Schutz.'],['the label alone proves financial-reporting derecognition under every accounting framework.','Ausbuchung hängt von den maßgeblichen Regeln und tatsächlichen Rechten beziehungsweise Risiken ab.']
 ],['Ausfallrisiko, Leistungsstreit und Bilanzierung sind getrennt zu prüfen. Die Produktbezeichnung ersetzt keine Lektüre des Vertrags.','Ein Vergleich benötigt außerdem Vorschuss, Gebühren, Einzugskosten und den Termin der Restzahlung.'],'factoring'),
 q('28','practice','c','A one-year loan has face value €50,000, interest of €2,500 payable at maturity, an upfront fee of €500 and a non-interest-bearing restricted deposit of €5,000 released at maturity. There are no other cash flows. The effective annual financing cost based on freely usable funds is closest to:',[
 ['6.74%','Heute nutzbar sind 44.500; am Ende fließen netto 47.500 ab.'],['5.00%','Dies ist der Nominalzins bezogen auf den Nennbetrag und ignoriert Gebühr und gebundenes Guthaben.'],['6.00%','Dies teilt Zins plus Gebühr durch den Nennbetrag statt durch die nutzbaren Mittel.']
 ],[F('r=\\frac{50000+2500-5000}{50000-500-5000}-1\\approx6{,}74\\%','Der am Ende freigegebene Betrag vermindert den Nettoabfluss, stand aber am Anfang nicht zur Verfügung.',[['r','Effektiver Einjahresfinanzierungssatz für die zwei gegebenen Nettozahlungszeitpunkte.']]),'Ein Vergleich mit anderen Angeboten benötigt dieselbe Laufzeit und vollständig berücksichtigte Gebühren.'],'funding-cost'),
 q('29','practice','c','A business replaces its inventory items frequently but continuously needs a base level of €100,000 of operating working capital throughout the year. This base level is most appropriately described as:',[
 ['permanent working capital, even though individual assets turn over.','Der dauerhafte Finanzierungsbedarf bleibt trotz Austausch der einzelnen Positionen bestehen.'],['purely seasonal working capital that disappears whenever one item is sold.','Der Verkauf eines Stücks beseitigt den zur Fortsetzung des Geschäfts benötigten Sockel nicht.'],['proof that all financing should mature before the next inventory sale.','Das folgt weder aus der Umschlagshäufigkeit noch aus der Dauer des Gesamtbedarfs.']
 ],['Ein temporärer Mehrbedarf ist vom dauerhaften Sockel zu unterscheiden. Diese Trennung hilft bei der Wahl passender Finanzierungslaufzeiten.','Einzelne Vermögenswerte sind kurzfristig, während die Summe dauerhaft benötigt sein kann.'],'policy'),
 q('30','practice','c','Compared with maturity-matched financing, an issuer finances part of its permanent operating working capital with short-term borrowing. All else equal, this most directly:',[
 ['increases exposure to refinancing when the short-term borrowing matures.','Der fortbestehende Bedarf muss häufiger durch neue oder verlängerte Mittel gedeckt werden.'],['guarantees lower financing costs under every yield curve.','Kurzfristige Sätze und Gebühren sind nicht unter allen Bedingungen niedriger.'],['eliminates the permanent nature of the operating investment.','Die Quelle der Finanzierung verändert nicht die Dauer des zugrunde liegenden Bedarfs.']
 ],['Dies ist eine aggressivere Finanzierungspolitik. Sie ist von einer Politik knapper Vorrats- oder Kassenhaltung zu unterscheiden.','Beurteilt werden Laufzeit, Zusagen, Reserven und Stresszugang statt nur der aktuelle Zinssatz.'],'policy'),
 q('31','practice','b c','Cash is earmarked for a fixed supplier payment in four weeks. An alternative investment offers higher expected return but has material price volatility and uncertain sale proceeds. The most appropriate assessment is:',[
 ['its risk and realizability may be unsuitable for the known payment need despite the higher expected return.','Liquiditätsreserve muss zum Termin und benötigten Betrag passen.'],['higher expected return guarantees more money on the payment date.','Ein Erwartungswert sichert keinen konkreten Realisationsbetrag.'],['the investment’s long-run expected return alone determines short-run payment capacity.','Zeithorizont und Wertschwankung gehören zur Beurteilung.']
 ],['Die Anlageentscheidung prüft Sicherheit, Fälligkeit, Währung, Gegenparteien und Verkaufsmöglichkeit. Zusätzliche Rendite kompensiert häufig zusätzliche Risiken.','Ein Liquiditätspuffer soll gerade dann verfügbar sein, wenn andere Zuflüsse schwächer ausfallen.'],'sources-drags'),
 q('32','practice','a b c','A proposal reduces average CCC by offering customers large discounts and paying suppliers after contractual due dates. The analyst should most appropriately:',[
 ['evaluate the cash released against discount costs, contractual consequences and operational effects.','Eine bessere Tageskennzahl kann durch wirtschaftlich nachteilige Maßnahmen entstehen.'],['accept the proposal solely because every reduction in CCC increases firm value.','CCC misst Dauer und ist kein vollständiges Wertmaß.'],['assume reported CCC changes identify the exact amount and timing of all future cash flows.','Kennzahlen geben weder alle Geldbeträge noch alle konkreten Zahlungstermine an.']
 ],['Die Analyse übersetzt jede Maßnahme in Geldbetrag, Zeitpunkt und Folgen. Dazu gehören verlorener Rabatt beziehungsweise gewährter Preisnachlass, Lieferfähigkeit, Ruf und zusätzliche Gebühren.','Die kürzeste Geldumschlagsdauer muss nicht die wirtschaftlich beste Politik sein.'],'decision'),
 q('a1','mock-a','a','Using 365 days, an issuer has average inventory of 150 with annual cost of goods sold of 1,825, average receivables of 160 with annual credit sales of 2,920, and average payables of 120 with annual credit purchases of 2,190. Its cash conversion cycle in days is:',[
 ['30','Vorratstage dreißig plus Forderungstage zwanzig minus Verbindlichkeitstage zwanzig.'],['50','Dies ist der operative Zyklus ohne Abzug des Lieferantenkredits.'],['70','Dies addiert die Verbindlichkeitstage statt sie abzuziehen.']
 ],[F('CCC=365\\left(\\frac{150}{1825}+\\frac{160}{2920}-\\frac{120}{2190}\\right)=30','Die drei unterschiedlichen Jahresströme liefern die jeweilige Tagesbasis.',[['CCC','Cash Conversion Cycle in Tagen.']]),'Die Lieferantenfinanzierung deckt zwanzig der fünfzig Tage zwischen Warenbindung und Kundenzahlung.'],'cycle-formulas'),
 q('a2','mock-a','b c','Two forecasts have identical total receipts and payments over a quarter. In the second forecast, a large customer receipt arrives a month later, after a major supplier payment. Which conclusion is most appropriate?',[
 ['The peak funding requirement can increase even if quarter-end cash before financing is unchanged.','Die Reihenfolge kann eine zwischenzeitliche Finanzierungslücke vergrößern.'],['Equal quarterly totals guarantee identical liquidity needs on every date.','Gesamtsummen verdecken unterjährige Termine.'],['The delayed receipt necessarily reduces the contractual supplier payment.','Eine spätere Kundenzahlung ändert nicht automatisch die eigene Verpflichtung.']
 ],['Liquiditätsplanung wird auf ausreichend kurze Perioden heruntergebrochen. Die maximale Inanspruchnahme, nicht nur der Endsaldo, bestimmt den benötigten Kreditrahmen.','Zusätzlich sind Reserven, tatsächliche Abruffähigkeit und eventuelle Kosten der längeren Finanzierung zu prüfen.'],'cash-budget'),
 q('b1','mock-b','a b','Two merchants use the same credit-sales and purchase conventions. Relative to last year, a merchant’s inventory days fall by 4, receivable days rise by 9 and payable days rise by 7. The change in its cash conversion cycle, in days, is:',[
 ['−2','Minus vier plus neun minus sieben ergibt minus zwei.'],['12','Dies addiert die Änderung der Lieferantentage mit falschem Vorzeichen.'],['2','Dies kehrt die Richtung der gesamten Veränderung um.']
 ],[F('\\Delta CCC=-4+9-7=-2','Der schnellere Lagerumschlag und zusätzliche Lieferantenkredit überwiegen die langsamere Kundenzahlung knapp.',[['\\Delta CCC','Veränderung des Cash Conversion Cycle in Tagen.']]),'Eine Verringerung um zwei Tage sagt ohne Volumen und Strombasen noch nicht, wie viele Euro freigesetzt werden.'],'sensitivity'),
 q('b2','mock-b','c','A supplier offers a 3% discount for payment on day 12 instead of full payment on day 42. With a 360-day year, the simple annualized cost of foregoing the discount is closest to:',[
 ['37.11%','Drei Prozent relativ zu siebenundneunzig Prozent für dreißig zusätzliche Tage, zwölfmal hochgerechnet.'],['36.00%','Dieser Wert verwendet den vollen Rechnungsbetrag als Finanzierungsbasis.'],['26.51%','Dieser Wert verwendet die gesamten 42 statt der zusätzlich finanzierten dreißig Tage.']
 ],[F('r=\\frac{0{,}03}{0{,}97}\\frac{360}{42-12}\\approx37{,}11\\%','Die Frage verlangt eine einfache Annualisierung; der effektive Satz mit Wiederholung wäre eine andere Größe.',[['r','Einfach annualisierter Vergleichssatz des Skontoverzichts.']]),'Ob eine alternative Finanzierung günstiger ist, hängt von ihren vollständigen Kosten und tatsächlicher Verfügbarkeit ab.'],'trade-discount')
];
